-- Migration: 20260716_add_realcomic_qwen_style
-- Registers the 'realcomic_qwen' visual style — Qwen-Image-Edit-2511 (fp8) +
-- Lightning 4-step LoRA + RealComic style-LoRA (Civitai 1757495). Identity is
-- 1-3 anchor portraits attached as VL image references (image1..image3 on
-- TextEncodeQwenImageEditPlus) — native multi-character support, no character
-- LoRA training. Style rides the RealComic LoRA + trigger phrase; anchors are
-- generated by the same Qwen graph (gen_anchor_portrait_realcomic_qwen_api.json).
--
-- identityStack reuses 'ip_adapter_plus_style_lora' deliberately: the only
-- consumer (anchor-render.service getStyleReadiness) treats it as
-- "ready ⟺ anchor PNG exists", which is exactly right here. The literal
-- mechanism is Qwen VL multi-image conditioning, not IP-Adapter.
--
-- Apply by hand (Prisma shadow-database issues on Windows per
-- PROJECT_CREATION_GUIDE Приложение A):
--   psql -h localhost -U gen_studio -d gen_studio -f scripts/migrations/20260716_add_realcomic_qwen_style.sql
--
-- Idempotent: ON CONFLICT DO NOTHING — re-running is safe.

BEGIN;

INSERT INTO visual_styles (
  id, "displayName", "styleBlock", "defaultNegative",
  "identityStack", "loraPipeline",
  "characterIpTemplateKey", "environmentTemplateKey", "datasetTemplateKey", "loraTrainTemplateKey"
) VALUES (
  'realcomic_qwen',
  'RealComic (Qwen 2511)',
  -- NB: Qwen prompts are natural-language instructions; the seed engines
  -- should bake this block as the head of promptFields.positive like every
  -- other style, and the strategies compose the "Picture N" instruction shell
  -- around it at render time (src/generation/scenes/qwen/qwen-prompt.ts).
  'realcomic style, hand-drawn comic illustration with a realistic touch, clean confident linework, painterly shading, muted cinematic color palette, 16:9 cinematic composition, no photorealism, no anime',
  -- Inert at cfg 1.0 (Lightning) — kept for parity and a future cfg-fallback.
  'photograph, photorealistic, 3D render, CGI, plastic skin, anime, manga, chibi, deformed hands, extra fingers, two heads, watermark, text overlay, blurry, low quality',
  'ip_adapter_plus_style_lora',
  -- No per-character LoRA training — identity is anchor-reference driven.
  'none',
  'scene_realcomic_qwen_p1',
  'scene_realcomic_qwen_p0',
  NULL,
  NULL
)
ON CONFLICT (id) DO NOTHING;

COMMIT;
