# -*- coding: utf-8 -*-
"""caregiver — акты 8–11: последняя зима, прощание, завещание, финал."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _caregiver_engine import seed_act

P8  = "a pale washed palette of low winter light through net curtains, white linen and thin translucent skin"
P9  = "a bleak late-winter palette of grey slush, black wool coats and a flat overcast sky"
P10 = "a hollow palette of bare daylight in an emptied room, pale wallpaper rectangles and settled grey dust"
P11 = "a quiet palette of soft afternoon light on a made bed, warm brass and pale walls"

LAST_WINTER = [
 ("A8_SH01", None, "val_room",
  "a bedroom in low winter daylight with the bed at the centre of the room, a folded wheelchair gone and a chair drawn permanently up to the bedside",
  "WS","eye","static","day",True,False,
  "на девятый год она перестаёт вставать совсем и почти уже не говорит."),
 ("A8_SH02", "NAD_END", "val_room",
  "Nadezhda rolling a light body towards herself on the mattress with one knee braced against the bed frame",
  "MS","eye","static","day",False,False,
  "ты поворачиваешь её каждые два часа, и по ночам тоже каждые два."),
 ("A8_SH03", None, "val_room",
  "a bedside cabinet stacked with a tube of cream, a tin of powder and a squared pile of ironed cotton draw sheets",
  "INSERT","top","static","day",True,False,
  "на тумбочке теперь стоят крем, присыпка и стопка чисто проглаженных мягких пелёнок."),
 ("A8_SH04", "NAD_END", "val_room",
  "Nadezhda's face checking a shoulder and a hip by touch, satisfied with what she finds",
  "CU","low","static","day",False,False,
  "пролежней у неё нет ни одного, и это твоя личная профессиональная гордость."),
 ("A8_SH05", ("NAD_END","VAL_END"), "val_room",
  "Nadezhda pours water from a jug over white hair held above a basin while Valentina lies back across a folded towel with her eyes shut",
  "MS","eye","static","day",False,False,
  "ты моешь ей голову над тазом раз в неделю, всегда по четвергам."),
 ("A8_SH06", "VAL_END", "val_room",
  "Valentina's face with her eyes closed under the warm water, every line in it gone soft",
  "CU","eye","static","day",False,True,
  "во время мытья она закрывает глаза и становится похожа на маленькую девочку."),
 ("A8_SH07", None, "val_room",
  "an enamel basin of grey water on a chair beside a bed with a jug standing in it and a wrung towel over the rim",
  "INSERT","low","static","day",True,False,
  "вода в тазу становится серой, и ты меняешь её целых три раза."),
 ("A8_SH08", "VAL_END", "val_room",
  "Valentina's eyes opening and settling somewhere past the ceiling as she says one name",
  "MCU","eye","static","day",False,False,
  "она открывает глаза и говорит одно имя, и это имя не твоё."),
 ("A8_SH09", "NAD_END", "val_room",
  "Nadezhda's face hearing the name and recognising which one it is",
  "CU","eye","static","day",False,True,
  "она зовёт мужа, которого нет уже почти тридцать лет, и зовёт ласково."),
 ("A8_SH10", "NAD_END", "val_room",
  "Nadezhda leaning in and answering in a low even voice as though the answer were hers to give",
  "MCU","low","static","day",False,False,
  "ты отвечаешь ей за него, потому что за девять лет уже привыкла."),
 ("A8_SH11", None, "val_room",
  "a bedroom from above at dusk with a small brass bell standing on the cabinet just out of reach of the bed",
  "WS","high","static","dusk",True,True,
  "колокольчик стоит на тумбочке, и она уже не может его сама поднять."),
 ("A8_SH12", "OBJ:bell", None,
  "an empty patch of crocheted doily where something has just been lifted away",
  "INSERT","eye","pull_out","interior",True,True,
  "ты придвигаешь его ближе, потом ещё ближе, а потом просто совсем убираешь."),
 ("A8_SH13", "NAD_END", "val_room",
  "Nadezhda's face at the bedside in the dusk, permanently within arm's reach now",
  "CU","eye","static","dusk",False,False,
  "вместо колокольчика теперь есть ты, и ты в этой комнате круглые сутки."),
 ("A8_SH14", None, "winter_yard",
  "a courtyard at night in deep February with one narrow trodden path to the bins and snow banked over the benches",
  "WS","eye","static","night",True,False,
  "ты выходишь во двор за весь январь всего один раз, вынести мусор."),
 ("A8_SH15", "ZINA_BASE", "stairwell",
  "Zina standing on the landing in her apron with her arms folded, saying something she has clearly decided to say",
  "MCU","eye","static","day",False,False,
  "Зина на площадке говорит тебе, что надо звонить её сыну прямо сейчас."),
 ("A8_SH16", "ZINA_BASE", "stairwell",
  "Zina's face gone unusually serious, counting three on her fingers with a grim set to her mouth",
  "CU","low","static","day",False,False,
  "она говорит, что видела такое уже трижды и что осталось совсем недолго."),
 ("A8_SH17", "NAD_END", "val_hall",
  "Nadezhda standing at the hallway shelf with the handset in both hands, speaking carefully and completely",
  "MS","eye","static","day",False,False,
  "ты звонишь Олегу в тот же вечер и говоришь ему всё честно."),
 ("A8_SH18", "NAD_END", "val_hall",
  "Nadezhda's face listening to an answer, her expression staying exactly as it was",
  "CU","eye","static","day",False,False,
  "он отвечает, что у него сейчас никак, и просит держать в курсе."),
 ("A8_SH19", None, "val_room",
  "a bedside at night lit by one lamp with a chair pulled hard against the bed frame and the coverlet turned down",
  "WS","low","static","night",True,False,
  "ты сидишь у её кровати ночами и держишь её руку поверх одеяла."),
 ("A8_SH20", ("VAL_END","NAD_END"), "val_room",
  "Valentina's fingers tighten faintly on a hand lying over hers while Nadezhda leans forward off the chair to catch it",
  "MCU","eye","static","night",False,True,
  "иногда она сжимает твои пальцы, и это единственный ответ, который у тебя есть."),
 ("A8_SH21", "OBJ:ring", None,
  "a hand lying open on a white coverlet in low lamplight",
  "INSERT","top","push_in","interior",True,True,
  "кольцо у неё на пальце висит свободно, и ты боишься его потерять."),
 ("A8_SH22", "NAD_END", "val_room",
  "Nadezhda easing a ring off a thin finger and setting it down in a saucer on the cabinet",
  "MS","eye","static","night",False,False,
  "ты снимаешь кольцо и кладёшь его в блюдце прямо на её тумбочке."),
 ("A8_SH23", "NAD_END", "val_room",
  "Nadezhda's face deciding against it and reaching back for the saucer an hour later",
  "CU","low","static","night",False,False,
  "через час ты надеваешь его обратно, потому что так ей заметно спокойнее."),
 ("A8_SH24", None, "val_kitchen",
  "a kitchen before dawn with a plate of food gone cold under a cloth and a chair standing pushed in at the table",
  "WS","eye","static","dawn",True,False,
  "на кухне стоит остывший ужин, и ты не помнишь, когда ела сама."),
 ("A8_SH25", "NAD_END", "val_kitchen",
  "Nadezhda standing at the kitchen window at first light with her housecoat hanging loose off her shoulders",
  "MCU","eye","static","dawn",False,False,
  "ты весишь на четырнадцать килограммов меньше, чем девять лет назад, и это заметно."),
 ("A8_SH26", "OBJ:watchpin", None,
  "the collar of a housecoat worn day and night, seen close at dawn",
  "INSERT","eye","static","interior",True,False,
  "часы-брошь ты не снимаешь даже ночью, потому что считаешь по ним пульс."),
 ("A8_SH27", "NAD_END", "val_room",
  "Nadezhda touching a teaspoon of water to closed lips and waiting, then wiping the chin with a cloth",
  "MCU","eye","push_in","dawn",False,False,
  "в феврале она перестаёт есть, и ты кормишь её с ложки водой."),
 ("A8_SH28", None, "winter_yard",
  "a courtyard from very high at night in early March with the snow gone grey and collapsing and water standing along the kerbs",
  "EWS","high","pull_out","night",True,False,
  "а в первых числах марта во дворе уже начинает пахнуть талой водой."),
]

FAREWELL = [
 ("A9_SH01", None, "val_room",
  "a bedroom at four in the morning with the overhead light on for once, the bed disordered and a chair knocked out of place",
  "WS","eye","static","night",True,False,
  "в середине марта ты вызываешь скорую в четыре утра, во второй раз."),
 ("A9_SH02", "NAD_END", "val_hall",
  "Nadezhda packing a plastic bag in the hallway with quick certain hands, taking items straight off shelves",
  "MS","eye","static","night",False,False,
  "ты собираешь её вещи в пакет за две минуты, потому что готовилась."),
 ("A9_SH03", None, "hospital_ward",
  "a hospital admissions area from above before dawn with a trolley being wheeled towards double doors and a line of empty chairs along the wall",
  "EWS","high","static","day",True,False,
  "в приёмном покое её увозят наверх, а тебя просят подождать пока внизу."),
 ("A9_SH04", "NAD_END", "clinic_corridor",
  "Nadezhda standing at a nurses' station explaining who she is, holding out a plastic bag as though it were proof",
  "MCU","eye","static","day",False,False,
  "ты говоришь, что ты сиделка, и это слово там ничего не значит."),
 ("A9_SH05", "NAD_END", "clinic_corridor",
  "Nadezhda's face receiving a rule she cannot argue with, her jaw setting on it",
  "CU","low","static","day",False,True,
  "в реанимацию пускают только родственников, а ты по всем документам ей никто."),
 ("A9_SH06", None, "clinic_corridor",
  "a hospital corridor with a row of joined chairs against the wall, a locked double door at the end and a window of grey daylight",
  "WS","eye","static","day",True,False,
  "ты сидишь в этом коридоре двое суток и выходишь только за кипятком."),
 ("A9_SH07", "NAD_END", "clinic_corridor",
  "Nadezhda lying across three joined chairs at night with a plastic bag folded under her head as a pillow",
  "MS","eye","static","night",False,False,
  "ночью ты спишь на трёх стульях, подложив себе под голову её пакет."),
 ("A9_SH08", None, "clinic_corridor",
  "a plastic bag open on a corridor chair showing a folded cream cardigan, a pair of felt slippers and a book with a bookmark in it",
  "INSERT","top","static","night",True,True,
  "в пакете лежит её кофта, тапки и та книга с закладкой внутри."),
 ("A9_SH09", "OLEG_BASE", "clinic_corridor",
  "Oleg walking straight past the row of chairs towards the double doors, a hospital gown pack already in his hand",
  "MCU","eye","static","day",False,False,
  "Олег прилетает на вторые сутки, и его пускают в реанимацию почти сразу."),
 ("A9_SH10", "NAD_END", "clinic_corridor",
  "Nadezhda standing a few steps from the closed doors with her hands at her sides, watching them",
  "CU","eye","static","day",False,False,
  "ты стоишь под дверью и ждёшь, пока он выйдет и что-то скажет."),
 ("A9_SH11", ("OLEG_BASE","NAD_END"), "clinic_corridor",
  "Oleg comes out through the double doors and stops in front of Nadezhda while she takes one step towards him and then stops as well",
  "MS","eye","static","day",False,False,
  "он выходит оттуда через двадцать минут и говорит тебе всего четыре слова."),
 ("A9_SH12", "OLEG_BASE", "clinic_corridor",
  "Oleg's face saying it plainly and then sitting down on the nearest chair",
  "CU","low","static","day",False,True,
  "мамы больше нет, говорит он, и садится на стул рядом с тобой."),
 ("A9_SH13", "NAD_END", "clinic_corridor",
  "Nadezhda's face holding perfectly still, her eyes wide and completely dry",
  "CU","eye","static","day",False,False,
  "ты не плачешь в коридоре, потому что в коридоре плакать почему-то нельзя."),
 ("A9_SH14", None, "clinic_corridor",
  "two occupied chairs in a long empty corridor seen low along the floor, four shoes side by side and bare linoleum around them",
  "WS","low","static","day",True,True,
  "вы сидите рядом на двух одинаковых стульях сорок минут и оба молчите."),
 ("A9_SH15", "OLEG_BASE", "clinic_corridor",
  "Oleg's face breaking quietly with one hand over his eyes and the watch bracelet loose on his wrist",
  "MCU","eye","static","day",False,True,
  "он первый раз за девять лет плачет, и плачет он совсем тихо."),
 ("A9_SH16", "NAD_END", "val_kitchen",
  "Nadezhda at the kitchen table with a list, a pen and three telephone numbers copied out in her own hand",
  "MS","eye","static","day",False,False,
  "похороны организуешь ты, потому что ты знаешь, где у неё что лежит."),
 ("A9_SH17", "OBJ:cookietin", None,
  "the inside of a glass-fronted sideboard with a shelf of cups pushed aside",
  "INSERT","eye","push_in","interior",True,True,
  "в серванте стоит жестянка из-под печенья, и на ней написано: на похороны."),
 ("A9_SH18", "NAD_END", "val_kitchen",
  "Nadezhda counting the contents of the tin into neat stacks on the oilcloth and finding it comes out exactly",
  "CU","low","static","day",False,False,
  "денег в ней хватает ровно на всё, потому что она копила годами."),
 ("A9_SH19", None, "cemetery",
  "a municipal cemetery from very high in late winter with a small group of dark coats gathered at one plot among long rows of painted fences",
  "EWS","high","pan_left","day",True,False,
  "на кладбище приезжает одиннадцать человек, и шестерых из них ты видишь впервые."),
 ("A9_SH20", "NAD_END", "cemetery",
  "Nadezhda standing at the back of a small graveside group with a folded cardigan held against her chest",
  "MS","eye","static","day",False,False,
  "ты стоишь не в первом ряду, потому что первый ряд для родных."),
 ("A9_SH21", "NAD_END", "cemetery",
  "Nadezhda's face in the cold, her hands working slowly on the folded wool she is holding",
  "CU","eye","static","day",False,False,
  "ты держишь в руках её кофту, потому что руки надо чем-то занять."),
 ("A9_SH22", "MAR_ADULT", "cemetery",
  "Marina arriving late along the gravel path in a grey coat, finding her mother in the group straight away",
  "MCU","eye","static","day",False,False,
  "Марина приезжает на похороны сама, и ты вовсе не просила её приезжать."),
 ("A9_SH23", ("MAR_ADULT","NAD_END"), "cemetery",
  "Marina steps in beside her mother and takes her by the arm, and Nadezhda goes on looking straight ahead and lets her",
  "MS","eye","static","day",False,False,
  "она встаёт рядом с тобой и держит тебя под руку всю службу."),
 ("A9_SH24", "MAR_ADULT", "cemetery",
  "Marina's face in profile, holding on with her mouth pressed shut",
  "CU","low","static","day",False,True,
  "за девять лет это первый раз, когда она к тебе вообще прикасается."),
 ("A9_SH25", None, "cemetery",
  "a gravel cemetery path in thawing slush with fresh footprints going both ways and a low chapel roof beyond the bare limes",
  "WS","eye","static","day",True,False,
  "поминки идут в кафе у кладбища и заканчиваются уже через полтора часа."),
 ("A9_SH26", "OLEG_BASE", "cemetery",
  "Oleg speaking briefly with a glass held low, turning once towards somebody at the back of the group",
  "MCU","eye","static","day",False,False,
  "Олег говорит короткий тост и называет тебя человеком, который был всегда рядом."),
 ("A9_SH27", "NAD_END", "cemetery",
  "Nadezhda's face accepting the words with a small nod, believing them completely",
  "CU","eye","static","day",False,True,
  "ты киваешь и в эту минуту всё ещё веришь в эту квартиру."),
 ("A9_SH28", None, "winter_yard",
  "a courtyard at dusk in thaw seen from very high with black wet asphalt showing through the last snow and one lit window on the fourth floor",
  "EWS","high","pull_out","dusk",True,False,
  "до девятого дня остаётся почти неделя, и всю её ты убираешь квартиру."),
]

WILL = [
 ("A10_SH01", None, "val_room",
  "a bedroom stripped for cleaning with the mattress bare, the curtains down off the rail and every surface wiped and empty",
  "WS","eye","static","day",True,False,
  "неделю до девятого дня ты моешь квартиру так, как не мыла никогда."),
 ("A10_SH02", "NAD_END", "val_room",
  "Nadezhda up on a chair washing a window with both hands, her sleeves pushed above the elbow",
  "MS","eye","static","day",False,False,
  "ты стираешь занавески, отмываешь окна и выносишь на помойку двенадцать полных мешков."),
 ("A10_SH03", None, "val_room",
  "a squared stack of ironed nightdresses and towels on a bare mattress with the iron still standing on its heel beside them",
  "INSERT","top","static","day",True,False,
  "её бельё ты гладишь и складываешь стопкой, хотя носить его уже некому."),
 ("A10_SH04", "NAD_END", "val_room",
  "Nadezhda's face folding cloth with complete attention, doing it the way she always has",
  "CU","low","static","day",False,False,
  "ты делаешь это потому, что девять лет делала это ровно каждую неделю."),
 ("A10_SH05", None, "val_room",
  "a cleared table in a bare room with three chairs pulled up to it and three sheets of paper squared in the middle",
  "WS","eye","static","day",True,False,
  "на девятый день Олег приезжает сюда не один, а вместе с нотариусом."),
 ("A10_SH06", "OLEG_BASE", "val_room",
  "Oleg sitting at the table in his overcoat, turning a single sheet round so it faces across the table",
  "MCU","eye","static","day",False,False,
  "они садятся за стол в комнате и раскладывают на нём три листа."),
 ("A10_SH07", "OBJ:will", None,
  "a cleared table top in bare daylight with a fountain pen laid across one corner",
  "INSERT","top","static","interior",True,True,
  "завещание уместилось на одной странице, и всё имущество переходит её единственному сыну."),
 ("A10_SH08", "NAD_END", "val_room",
  "Nadezhda leaning over the table with one finger held above the paper, asking to be shown something",
  "MCU","eye","push_in","day",False,True,
  "ты просишь показать тебе дату, и тебе очень спокойно её сразу показывают."),
 ("A10_SH09", None, "val_room",
  "the foot of a typed document filled by a printed date and a round embossed stamp pressed into the paper beside it",
  "ECU","top","static","day",True,True,
  "дата стоит за два года до того дня, когда ты сюда пришла."),
 ("A10_SH10", "NAD_END", "val_room",
  "Nadezhda straightening up off the table very slowly, working the whole thing out at once",
  "MCU","low","static","day",False,True,
  "то есть она обещала тебе то, чего у неё уже давно не было."),
 ("A10_SH11", "OLEG_BASE", "val_room",
  "Oleg's face offering a kind explanation, his hands folded on the table in front of him",
  "CU","eye","static","day",False,False,
  "Олег говорит, что мама, наверное, просто очень хотела, чтобы ты тут осталась."),
 ("A10_SH12", ("OLEG_BASE","NAD_END"), "val_room",
  "Oleg slides a plain envelope across the table towards Nadezhda while she stands on the other side of it with her hands still at her sides",
  "MS","eye","static","day",False,False,
  "он достаёт конверт и предлагает тебе три оклада сверху, просто так, по-человечески."),
 ("A10_SH13", "NAD_END", "val_room",
  "Nadezhda's hand closing over the envelope and her face perfectly blank",
  "CU","low","static","day",False,True,
  "ты берёшь этот конверт, потому что за март тебе никто не платил."),
 ("A10_SH14", None, "courtyard",
  "an apartment courtyard in thaw seen from above with wet asphalt, one bench clear of snow and a bin overflowing beside the porch",
  "WS","high","static","day",True,False,
  "стыдно тебе становится не в комнате, а через сорок минут на улице."),
 ("A10_SH15", "NAD_END", "val_room",
  "Nadezhda folding a camp bed flat against the wall and stacking her tunics on top of it",
  "MS","eye","static","day",False,False,
  "ты складываешь свои халаты и раскладушку и выносишь всё за один раз."),
 ("A10_SH16", "OBJ:slippers", None,
  "bare floorboards beside the leg of a stripped bed in flat daylight",
  "INSERT","low","static","interior",True,True,
  "её тапки так и стоят у кровати, и ты их не трогаешь."),
 ("A10_SH17", "NAD_END", "val_hall",
  "Nadezhda pulling a bedroom door closed by its handle and holding it a second after it shuts",
  "CU","eye","static","day",False,False,
  "ты закрываешь дверь в её комнату, хотя закрывать её теперь совсем незачем."),
 ("A10_SH18", None, "stairwell",
  "a landing with a toolbox open on the concrete, a new lock cylinder fitted into a door edge and a printed form on a clipboard on top of the box",
  "WS","eye","static","day",True,False,
  "на площадке слесарь заканчивает работу и просит кого-нибудь расписаться в его бланке."),
 ("A10_SH19", "NAD_END", "stairwell",
  "Nadezhda standing back from the doorway with her bags at her feet while somebody signs out of frame",
  "MCU","eye","static","day",False,False,
  "расписывается за неё Олег, потому что теперь эта квартира принадлежит только ему."),
 ("A10_SH20", ("ZINA_BASE","NAD_END"), "stairwell",
  "Zina opens her own door and stands in it looking across the landing while Nadezhda picks up both bags and looks back at her",
  "MS","eye","static","day",False,False,
  "Зина выходит на площадку, смотрит на тебя и не говорит ни слова."),
 ("A10_SH21", "ZINA_BASE", "stairwell",
  "Zina's face on the landing, entirely grave, her mouth pressed shut",
  "CU","eye","static","day",False,False,
  "она всё сказала тебе пять лет назад, и добавлять ей больше нечего."),
 ("A10_SH22", "NAD_END", "stairwell",
  "Nadezhda's face saying thank you for something vague she leaves unnamed",
  "CU","low","static","day",False,False,
  "ты благодаришь её за что-то и сама не понимаешь, за что именно."),
 ("A10_SH23", None, "stairwell",
  "a stairwell shaft seen straight down from the top landing with the flights turning away below and the handrail worn bright",
  "WS","high","static","day",True,False,
  "ты спускаешься по лестнице с двумя сумками и считаешь пролёты до самого низа."),
 ("A10_SH24", "NAD_END", "courtyard",
  "Nadezhda walking out across the courtyard with a bag in each hand, passing the second bench at the same steady pace",
  "WS","eye","track","day",False,True,
  "во дворе ты проходишь мимо второй скамейки и не садишься на неё."),
 ("A10_SH25", "NAD_END", "courtyard",
  "Nadezhda's face out in the open air, entirely steady, adding it up one last time",
  "CU","eye","push_in","day",False,True,
  "тебе пятьдесят три года, и у тебя нет ни жилья, ни работы."),
 ("A10_SH26", None, "courtyard",
  "an apartment block from very high with a printed sale notice taped inside a ground-floor window and the courtyard empty below",
  "EWS","high","pull_out","day",True,True,
  "а квартиру на первом этаже Олег выставляет на продажу через два месяца."),
]

CODA = [
 ("A11_SH01", None, "agency_office",
  "a care-agency office from above with the same two desks, the same laminated price list on the wall and one occupied chair at the counter",
  "EWS","high","static","day",True,False,
  "через год ты снова сидишь в том же агентстве, на том же стуле."),
 ("A11_SH02", "NAD_END", "agency_office",
  "Nadezhda reading a printed client card held at arm's length across the agency counter",
  "MS","eye","static","day",False,False,
  "тебе показывают карточку: мужчина восьмидесяти одного года, после инсульта, полностью лежачий больной."),
 ("A11_SH03", "NAD_END", "agency_office",
  "Nadezhda's face agreeing at once, already reaching for the pen",
  "CU","low","static","day",False,False,
  "ты соглашаешься сразу, потому что снимать комнату надо уже с этого понедельника."),
 ("A11_SH04", None, "new_flat_room",
  "another elderly person's bedroom with a made bed, a dark sideboard of framed photographs and a walking frame parked by the door",
  "WS","eye","static","day",True,False,
  "квартира здесь другая, но комната почти такая же: кровать, сервант и тумбочка."),
 ("A11_SH05", None, "new_flat_room",
  "a bedside cabinet with a doily, a covered glass and a small tarnished brass hand bell standing beside them",
  "INSERT","top","static","day",True,True,
  "на тумбочке у чужой кровати стоит точно такой же латунный дорожный колокольчик."),
 ("A11_SH06", "NAD_END", "new_flat_room",
  "Nadezhda looking at the cabinet for exactly two seconds and then setting her bag down on the floor",
  "MCU","eye","static","day",False,True,
  "ты смотришь на него ровно две секунды и ставишь сумку на пол."),
 ("A11_SH07", None, "marina_flat",
  "a tidy rented flat with a real table, two chairs and a kettle on a proper counter, afternoon light across the floor",
  "WS","eye","static","day",True,False,
  "с Мариной вы теперь видитесь раз в месяц, обычно по субботам днём."),
 ("A11_SH08", ("MAR_ADULT","NAD_END"), "marina_flat",
  "Marina pours tea for two at her own table while Nadezhda sits opposite her with her coat over the back of the chair",
  "MS","eye","static","day",False,False,
  "ей двадцать девять, она работает в магазине и снимает уже нормальную квартиру."),
 ("A11_SH09", "MAR_ADULT", "marina_flat",
  "Marina's face asking a direct question across the table with the teapot still in her hand",
  "CU","eye","static","day",False,False,
  "она спрашивает, платят ли тебе официально, и ты честно отвечаешь, что нет."),
 ("A11_SH10", "NAD_END", "marina_flat",
  "Nadezhda answering the second question with her eyes on her cup",
  "MCU","eye","static","day",False,False,
  "она спрашивает, обещали ли тебе что-то на этот раз, и ты говоришь нет."),
 ("A11_SH11", "MAR_ADULT", "marina_flat",
  "Marina's face holding a long look across the table and then saying one short thing",
  "CU","low","static","day",False,True,
  "она смотрит на тебя долго и говорит, что в этот раз проследит."),
 ("A11_SH12", "NAD_END", "marina_flat",
  "Nadezhda's face agreeing out loud while something entirely different sits behind her eyes",
  "CU","eye","static","day",False,False,
  "ты соглашаешься с ней вслух, а внутри уже примерно знаешь, как будет."),
 ("A11_SH13", None, "new_flat_room",
  "a bedroom from above in the afternoon with a chair drawn up to the bedside and a folded housecoat over its back",
  "WS","high","static","day",True,False,
  "в новой квартире ты работаешь шесть дней в неделю, как и раньше."),
 ("A11_SH14", "OBJ:notebook", None,
  "a bedside cabinet with a new pen laid across a fresh squared cover",
  "INSERT","eye","push_in","interior",True,True,
  "на второй день ты заводишь новую тетрадь и пишешь туда его давление."),
 ("A11_SH15", "NAD_END", "new_flat_room",
  "Nadezhda writing the first dated column into a clean exercise book, the letters coming out identical to the old ones",
  "MCU","eye","static","day",False,False,
  "почерк у тебя тот же, и строчки ложатся ровно, как двадцать лет назад."),
 ("A11_SH16", "NAD_END", "new_flat_room",
  "Nadezhda's hand finding a drawer handle by touch, her face already elsewhere",
  "CU","low","static","day",False,False,
  "ты снова знаешь, где что лежит, уже через девять своих рабочих дней."),
 ("A11_SH17", None, "courtyard",
  "a different apartment courtyard at dusk with two benches close to the porch and a low wall along the path",
  "WS","eye","static","dusk",True,False,
  "двор здесь другой, и вторая скамейка стоит гораздо ближе к самому подъезду."),
 ("A11_SH18", "NAD_END", "new_flat_room",
  "Nadezhda standing at the foot of the bed in the dusk and turning to look straight down the lens",
  "MCU","eye","static","dusk",False,True,
  "если тебе сейчас что-то обещают вместо денег, послушай меня всего одну минуту."),
 ("A11_SH19", "NAD_END", "new_flat_room",
  "Nadezhda's face close, speaking directly at the camera in a low even voice",
  "CU","eye","push_in","dusk",False,True,
  "обещание нельзя положить в банк, нельзя показать в суде и нельзя доказать."),
 ("A11_SH20", "NAD_END", "new_flat_room",
  "Nadezhda standing full height in the dim room with her hands folded in front of her, still addressing the camera",
  "WS","eye","static","dusk",False,True,
  "проси бумагу в тот же день, когда услышала обещание, и не стесняйся."),
 ("A11_SH21", "NAD_END", "new_flat_room",
  "Nadezhda's face finishing the thought, her mouth going flat on the last word",
  "CU","low","static","dusk",False,True,
  "стыдно спрашивать один раз, а не спросить — стыдно потом девять лет."),
 ("A11_SH22", None, "new_flat_room",
  "an empty bedside chair with a housecoat over its back and a small brass bell on the cabinet beside it",
  "INSERT","eye","static","dusk",True,True,
  "я не спросила, и поэтому к пятидесяти четырём у меня нет вообще ничего."),
 ("A11_SH23", "NAD_END", "new_flat_room",
  "Nadezhda buttoning her housecoat at the throat beside a stranger's bed as the little brass bell on the cabinet starts to ring",
  "MS","low","pull_out","dusk",False,True,
  "ты застёгиваешь халат, и на тумбочке рядом начинает звонить чужой латунный колокольчик."),
 ("A11_SH24", None, "new_flat_room",
  "a bedroom doorway seen from far back down a dim hallway with the lamp on inside and the door standing half open",
  "EWS","high","pull_out","dusk",True,False,
  "эта история вымышлена, все совпадения случайны, и ты не повторяй чужих ошибок."),
]

if __name__ == "__main__":
    seed_act("last_winter", P8,  LAST_WINTER)
    seed_act("farewell",    P9,  FAREWELL)
    seed_act("will",        P10, WILL)
    seed_act("coda",        P11, CODA)
