# -*- coding: utf-8 -*-
"""sailor_wife acts: cold_open (2026, 12) + dance (1978, 26). ALL animated.
Run: PYTHONIOENCODING=utf-8 python scripts/_seed_sailor_wife_A0A1.py"""
from _sailor_wife_engine import seed_act

PAL0="soft fog palette of pearl grey, pale harbour silver, warm lamp amber and faded navy"
COLD=[
("C_SH01",None,"harbor_panorama",
 "the harbour lying under thick morning fog, crane tops floating bodiless above the white, one dark ship's silhouette sliding toward the breakwater gap, gulls dissolving into the haze",
 "EWS","high","pan_right","morning",True,True,
 "март две тысячи двадцать шестого, порт лежит в тумане, и в тумане басом вздыхает уходящее судно.",
 "fog banks drifting slowly across the water, the dark ship silhouette gliding toward the breakwater, gull shapes fading in and out"),
("C_SH02","ANNA_OLD","anna_window_room_2020s",
 "a silver-haired woman of sixty-six rising from a worn armchair mid-motion, one hand on the armrest, her face already turned to the big window, a tartan blanket sliding from her knees",
 "MS","eye","static","morning",False,False,
 "ты поднимаешься с кресла раньше, чем успеваешь понять зачем, тело решает быстрее головы.",
 "her body rising from the armchair in one practised motion, the blanket sliding off her knees to the floor"),
("C_SH03","ANNA_OLD","anna_window_room_2020s",
 "the old woman standing close to the window glass, fog light flat on her face, her warm brown eyes searching the white where the harbour should be",
 "CU","eye","push_in","morning",False,True,
 "тебе шестьдесят шесть, и на этот звук ты встаёшь к окну уже сорок шесть лет подряд.",
 "her eyes moving slowly across the fogged glass, her breath clouding a small patch, her chin lifting to listen"),
("C_SH04","OBJ:anchor_pendant",None,
 "an aged hand closing around a small silver anchor pendant at the throat of a knitted cardigan, the chain fine as thread",
 "ECU","eye","static","morning",False,True,
 "пальцы сами находят на цепочке серебряный якорёк, за эти годы протёртый до мягкого блеска.",
 "the fingers closing gently around the pendant, the thumb rubbing the worn anchor once, twice"),
("C_SH05","VNUCHKA_BASE","anna_window_room_2020s",
 "a dark-curled girl of eight in a striped sailor shirt at the table with an open photo album, looking up at her grandmother with her head tilted",
 "MCU","low","static","morning",False,False,
 "за столом внучка отрывается от старого альбома и смотрит, как ты стоишь у окна, вся не здесь.",
 "the girl's head tilting up from the album page, her finger still holding her place on a photograph"),
("C_SH06","ANNA_OLD","anna_window_room_2020s",
 "the room seen wide from the doorway, the old woman a straight small figure at the bright window, the long souvenir shelf running the wall, two armchairs facing the light",
 "WS","eye","static","morning",False,False,
 "судно проходит створ, гудок тает над водой, а ты всё провожаешь его глазами до самых буёв.",
 "the woman's still figure at the window, fog light shifting through the curtains, the room holding quiet around her"),
("C_SH07","VNUCHKA_BASE","anna_window_room_2020s",
 "the curly-haired girl asking her question with open curiosity, elbows on the album, chin in both palms",
 "MCU","eye","static","morning",False,True,
 "бабушка, спрашивает она просто, а почему ты всегда встаёшь к окну, когда в порту гудит?",
 "her chin settling into her palms, her dark eyes fixed up at her grandmother, one foot swinging under the chair"),
("C_SH08","ANNA_OLD","anna_window_room_2020s",
 "the old woman turning from the window with her mouth opened for a short answer, the answer visibly not coming, fog light behind her silver waves",
 "CU","eye","static","morning",False,False,
 "ты открываешь рот ответить в двух словах и обнаруживаешь, что двух слов тут не хватит.",
 "her lips parting for an easy answer, pausing, closing, her eyebrows lifting at her own silence"),
("C_SH09","OBJ:souvenir_shelf",None,
 "a long wooden shelf by a bright window crowded end to end with small souvenirs, carved figures, shells, tiny flags, a ship in a bottle at the centre",
 "INSERT","eye","pan_left","morning",False,True,
 "на полке у окна стоят двадцать три сувенира, по одному с каждого рейса твоего мужа.",
 "light travelling slowly along the crowded shelf, glinting off glass and varnish, dust motes hanging over the little ships"),
("C_SH10","VIKTOR_OLD","anna_window_room_2020s",
 "a heavy white-bearded old man dozing in the second armchair by the window, a newspaper collapsed on his chest, a faded swallow tattoo on the forearm resting over it",
 "MS","eye","static","morning",False,False,
 "в соседнем кресле дремлет седой человек, который сорок лет был тебе мужем по переписке.",
 "his chest rising slowly under the fallen newspaper, his fingers twitching once in sleep, the tattooed forearm settling"),
("C_SH11","ANNA_OLD","anna_window_room_2020s",
 "the old woman settling onto the chair beside her granddaughter, taking the girl's small hand over the album, her face gathering a long story",
 "MCU","eye","static","morning",False,False,
 "садись ближе, говоришь ты внучке, это длинная история, длиной ровно в мою жизнь.",
 "her hand folding over the child's small one on the album page, her body settling in for a long telling"),
("C_SH12",None,"anna_window_room_2020s",
 "the fog-lit room from the window's side, two heads bent together over an open photo album, the sleeping old man beyond, the souvenir shelf framing them all",
 "WS","eye","pull_out","morning",True,False,
 "останься со мной до конца и подпишись, я расскажу, как море делит любовь на вахты.",
 "the two bent heads holding still over the album, fog light breathing through the curtains, the scene easing wider"),
]

PAL1="warm late-seventies palette of mirror-ball gold, summer-dress cotton, harbour dusk blue and accordion red"
DANCE=[
("A1_SH01",None,"port_quay",
 "the working port on a summer evening of nineteen seventy-eight, cranes bowing over a moored freighter, longshoremen's bicycles leaning by a warehouse, gold light on oily water",
 "EWS","high","static","evening",True,False,
 "тысяча девятьсот семьдесят восьмой, портовый город, где расписание всей жизни пишут пароходы и приливы."),
("A1_SH02","ANNA_YOUNG","courtyard_bench",
 "a bright-eyed girl of eighteen with dark-chestnut waves laughing as friends pull her up from the courtyard bench, a summer dress, sandals in one hand",
 "MS","eye","static","evening",False,False,
 "тебе восемнадцать, подруги тянут тебя с лавочки в клуб моряков, и ты для вида упираешься.",
 "her friends' hands pulling her laughing off the bench, her sandals swinging from one hand, her hair catching the low sun"),
("A1_SH03",None,"sailors_club",
 "the seamen's club hall in full evening swing, a mirror ball scattering slow constellations over the parquet, an accordion and double bass on the small stage, dancing couples blurring warm",
 "WS","eye","pan_right","night",True,False,
 "в клубе моряков по субботам играет живой оркестр, и паркет ходит ходуном до одиннадцати."),
("A1_SH04","VIKTOR_YOUNG","sailors_club",
 "a broad-shouldered fair-curled cadet of twenty-four by a column in a dress uniform, wringing his cap in both hands, pushed forward by grinning shipmates",
 "MCU","eye","static","night",False,False,
 "у колонны мнёт фуражку курсант мореходки, и товарищи выталкивают его в твою сторону.",
 "his hands wringing the cap brim, his shipmates' shoulders nudging him forward, his ears going visibly red"),
("A1_SH05","VIKTOR_YOUNG","sailors_club",
 "the cadet bowing his invitation to dance with clumsy ceremony, one hand offered, mirror-ball light sliding across his uniform buttons",
 "OTS","over","static","night",False,False,
 "он приглашает тебя с таким серьёзным лицом, будто сдаёт самый главный экзамен в жизни.",
 "his offered hand steady while the rest of him is not, the light points drifting across his buttons"),
("A1_SH06","ANNA_YOUNG","sailors_club",
 "the girl and the cadet turning in a waltz among other couples, her head back in a laugh as he missteps, constellations of light wheeling over them",
 "WS","eye","track","night",False,True,
 "на втором круге вальса он наступает тебе на ногу и извиняется потом до самого закрытия.",
 "the couple turning through the wheeling light, a hitch in his step, her head tipping back in laughter"),
("A1_SH07","ANNA_YOUNG","sailors_club",
 "the girl's laughing face close, dark waves swinging, mirror-ball points crossing her warm brown eyes",
 "CU","eye","static","night",False,False,
 "ты смеёшься не над ним, а от того, как старательно он считает шаги себе под нос.",
 "her laugh breaking open, light points crossing her eyes, a strand of hair swinging loose"),
("A1_SH08","VIKTOR_YOUNG","promenade",
 "the cadet walking the girl home along the night promenade at a careful arm's distance, his cap under his elbow, the lighthouse blinking far at the pier end",
 "MS","eye","track","night",False,False,
 "он провожает тебя по набережной на строгом расстоянии локтя и рассказывает про грузовые линии.",
 "the two figures keeping their careful distance along the railing, the lighthouse blink sweeping past them"),
("A1_SH09","ANNA_YOUNG","promenade",
 "the girl listening with her elbows on the painted railing, harbour lights doubled in the black water below her calm delighted face",
 "MCU","eye","static","night",False,True,
 "ты слушаешь про сухогрузы и меридианы, как про дальние страны, и веришь каждому слову.",
 "her chin settling onto her folded arms on the railing, harbour lights trembling in the water under her gaze"),
("A1_SH10",None,"harbor_panorama",
 "the night harbour from above, necklaces of quay lights, one ship leaving a long silver seam across the dark bay toward the open sea",
 "EWS","high","static","night",True,False,
 "ночью из порта уходит сухогруз, и его кильватерный след долго не зарастает на чёрной воде."),
("A1_SH11","VIKTOR_YOUNG","port_quay",
 "the cadet at the foot of a gangway in spring, a kit bag over his shoulder, turning back to wave, the ship's side rising huge and patient behind him",
 "MS","low","static","morning",False,False,
 "весной его курс уходит на практику, четыре месяца, и ты впервые провожаешь его к трапу.",
 "his free arm rising in a wide wave from the gangway foot, the kit bag swinging on his shoulder"),
("A1_SH12","ANNA_YOUNG","port_quay",
 "the girl on the quay among waving families, standing on tiptoe, one hand raised, the other pressed to her collarbone where a pendant will one day hang",
 "MCU","eye","static","morning",False,True,
 "ты машешь с причала, пока судно не становится размером с почтовую марку, и это только начало.",
 "her raised hand slowing as the ship shrinks, her other hand pressing flat below her throat"),
("A1_SH13","OBJ:letters_bundle",None,
 "a single envelope with a foreign port stamp lying on a courtyard bench slat, a girl's fingers just touching its corner",
 "INSERT","top","static","day",False,False,
 "первое письмо идёт до тебя шесть недель и пахнет трюмом, солью и чужим солнцем.",
 "the fingers drawing the envelope slowly across the bench slat, tilting it to read the stamp"),
("A1_SH14","ANNA_YOUNG","courtyard_bench",
 "the girl reading a letter on the courtyard bench under the acacia, her lips moving over the lines, sandals kicked off in the warm dust",
 "MS","eye","static","day",False,False,
 "ты читаешь его письма по три раза, вслух, шёпотом и про себя, и в каждом слышишь голос.",
 "her lips moving over the written lines, a page turning, her toes curling in the warm dust"),
("A1_SH15","ZINA_BASE","courtyard_bench",
 "a loud copper-haired neighbour of forty in a floral housecoat leaning over the bench back, reading shamelessly over the girl's shoulder, gold hoops swinging",
 "MCU","eye","static","day",False,False,
 "зина со второго этажа заглядывает через плечо и выносит вердикт, морячка из тебя растёт.",
 "her copper head craning over the bench back, hoops swinging, her finger tapping the letter's margin"),
("A1_SH16",None,"courtyard_bench",
 "the port-town courtyard in summer, laundry lines heavy with sheets, a cat asleep on a windowsill over geraniums, the acacia's shade moving on the beaten ground",
 "WS","eye","static","day",True,False,
 "во дворе у порта всё известно наперёд, чей муж в море, чей вернулся и чей загулял."),
("A1_SH17","ANNA_YOUNG","port_quay",
 "the girl running along the summer quay past bollards and coiled ropes toward a docking ship, her dress and hair streaming, families hurrying behind her",
 "WS","eye","track","day",False,True,
 "в августе его судно швартуется, и ты бежишь по причалу так, что теряешь босоножку.",
 "her run stretching long past the bollards, one sandal left behind, her hair streaming back"),
("A1_SH18","VIKTOR_YOUNG","port_quay",
 "the cadet catching the girl into a spinning embrace at the gangway foot, her feet off the ground, his cap knocked back, the crew whistling from the rail above",
 "MCU","eye","static","day",False,True,
 "он ловит тебя у трапа и кружит, и весь экипаж свистит вам сверху, как на стадионе.",
 "the embrace spinning through a full turn, her feet sweeping off the ground, his cap tipping back"),
("A1_SH19",None,"harbor_panorama",
 "the harbour at golden sunset, ships at anchor turned to dark cut-outs on molten water, the lighthouse catching the last direct ray",
 "EWS","eye","static","evening",True,False,
 "закат в порту длится долго, и вода в этот час дороже любого золота на свете."),
("A1_SH20","VIKTOR_YOUNG","promenade",
 "the cadet stopping the girl by the promenade railing in autumn, taking both her hands, his weathered young face grave and open",
 "MS","eye","static","evening",False,False,
 "осенью он останавливает тебя у парапета и говорит, выходи за меня, только знай, я моряк.",
 "his hands closing around both of hers, his shoulders squaring, his grave face holding hers"),
("A1_SH21","ANNA_YOUNG","promenade",
 "the girl's face lit with an answer that outruns the question, wind moving her dark waves, the pier lighthouse small and bright over her shoulder",
 "CU","eye","push_in","evening",False,True,
 "ты отвечаешь да раньше, чем он договаривает слово уходить, тебе восемнадцать, и слово это пока пустое.",
 "her answer breaking across her face before his words end, wind lifting her hair, her hands tightening in his"),
("A1_SH22","ZINA_BASE","courtyard_bench",
 "the copper-haired neighbour presiding over the bench before two old women, arms wide in dramatic report, gold hoops flashing in low sun",
 "MS","eye","static","evening",False,False,
 "к вечеру о помолвке знает весь двор, у зины новости ходят быстрее почтовых телеграмм.",
 "her arms spreading wide at the story's peak, the old women leaning in, hoops flashing"),
("A1_SH23","ANNA_YOUNG","anna_kitchen",
 "the small kitchen filled wall to wall with neighbour women fitting a plain white dress on the girl, pins between lips, a paper pattern spread on the table, lamplight over the crowded work",
 "WS","eye","static","evening",False,False,
 "платье вам шьют всем двором за девять вечеров, и каждая соседка вшивает свой совет.",
 "the women's hands turning her slowly by the shoulders, a hem lifting, pins catching the lamplight"),
("A1_SH24","VIKTOR_YOUNG","seafarers_office",
 "the cadet before the crewing-office wall board of vessel names and sailing dates in movable letters, his finger stopped on one line, his kit-bag posture gone still",
 "MCU","eye","static","day",False,False,
 "в конторе пароходства ему выписывают первый рейс, и дата стоит через девять дней после свадьбы.",
 "his finger resting on the board's movable letters, his head turning slowly from the date toward the door"),
("A1_SH25",None,"seafarers_office",
 "a crewing-office counter with a stamped contract folder, an inked date circled twice, a pigeonhole wall of folders rising behind",
 "INSERT","top","static","day",True,False,
 "в графе выхода написано ровно то, что написано, пароходство не двигает даты под свадьбы."),
("A1_SH26","ANNA_YOUNG","anna_kitchen",
 "the girl at the kitchen table marking two dates on a ship's calendar with a pencil, nine squares between them, her face practising being brave",
 "CU","high","static","night",False,True,
 "до свадьбы неделя, до его рейса шестнадцать дней, и оба числа ты выучиваешь наизусть.",
 "her pencil circling two calendar dates, her fingertip counting the nine squares between them one by one"),
]

seed_act("cold_open",PAL0,COLD)
seed_act("dance",PAL1,DANCE)
