# -*- coding: utf-8 -*-
"""announcer batch B: gallery_a (soldier mother + parting lovers) + gallery_b (commuter 7:14 + emigre family). static."""
from _announcer_engine import seed_act

PAL_A="muted daytime platform palette, grey steam and pale steel light, the ache of arrivals and farewells"
GA=[
 # --- B1 Мать у эшелонов ---
 ("GA_SH01",None,"platform_day","a military troop train arriving at a covered railway platform, steam and worn yellow safety lines","EWS","eye","push_in","day",True,False,
  "сверху ты объявляешь воинские эшелоны, и снизу их встречает одна и та же женщина."),
 ("GA_SH02","SOLMOTHER_BASE","platform_day","a woman in a grey headscarf clutching a letter and a photograph, scanning the carriages","MS","eye","static","day",False,False,
  "она стоит у третьего пути с фотографией сына и письмом, и ждёт каждый эшелон с фронта."),
 ("GA_SH03",None,"platform_day","extreme close on a folded letter and a worn photograph of a young man in uniform in a woman's hands","INSERT","top","push_in","day",False,True,
  "в руках у неё сложенное письмо и снимок мальчика в форме, затёртый по краям до белизны."),
 ("GA_SH04","SOLMOTHER_BASE","platform_day","close on the mother's hopeful face searching every soldier stepping onto the platform","CU","eye","static","day",False,False,
  "ты объявляешь прибытие, и она вглядывается в каждое лицо, что сходит с поезда на перрон."),
 ("GA_SH05","ANNOUNCER_MID","announcer_booth","the announcer watching the mother far below through the booth glass","MCU","high","static","day",False,False,
  "ты ведёшь эшелоны голосом и видишь сверху, как она снова не находит своего среди прибывших."),
 ("GA_SH06","SOLMOTHER_BASE","platform_day","the platform emptying of soldiers while the mother remains standing alone","WS","high","static","day",False,False,
  "перрон пустеет, солдаты расходятся по семьям, а она остаётся стоять у пустых холодных путей."),
 ("GA_SH07","SOLMOTHER_BASE","platform_day","close on the mother folding the photograph away and nodding up toward the booth","CU","eye","static","day",False,False,
  "она прячет фотографию, кивает тебе наверх, будто знакомой, и уходит до следующего поезда."),
 ("GA_SH08",None,"departures_board","a military arrival flipping up on the split-flap board","INSERT","eye","push_in","day",True,False,
  "ты объявляешь следующий эшелон и знаешь уже, что завтра она снова придёт на третий путь."),
 ("GA_SH09","SOLMOTHER_BASE","platform_day","the mother months later, greyer, the letter yellowed, still waiting","MS","eye","static","day",False,False,
  "проходят месяцы, потом годы, она седеет, а письмо в её руке желтеет, но она всё ждёт."),
 ("GA_SH10","ANNOUNCER_MID","announcer_booth","close on the announcer's helpless tenderness watching the mother","CU","eye","push_in","day",False,False,
  "ты не знаешь её имени, но знаешь её горе наизусть, и объявляешь поезда мягче, когда она внизу."),
 ("GA_SH11",None,"platform_day","an ordinary empty daytime platform long after the war has ended","WS","eye","static","day",True,False,
  "война давно кончилась, эшелоны с неё больше не приходят, а она всё равно приходит встречать."),
 ("GA_SH12","SOLMOTHER_BASE","platform_day","the old mother now waiting at an ordinary platform for any train at all","MCU","eye","static","day",False,False,
  "теперь она встречает обычные поезда, любые, как будто сын вернётся неизвестно с какого."),
 ("GA_SH13","SOLMOTHER_BASE","platform_day","close on the mother's face, faith and ruin together","CU","eye","push_in","day",False,False,
  "ты понимаешь, что она ждёт уже не сына, а тот единственный поезд, что вернёт ей прежнюю жизнь."),
 ("GA_SH14",None,"platform_day","the worn photograph left behind alone on a platform bench","INSERT","high","push_in","day",False,True,
  "однажды на скамье у третьего пути остаётся её фотография, а самой её больше нет."),
 ("GA_SH15","ANNOUNCER_MID","announcer_booth","the announcer waiting at the mic for a face that no longer comes","MS","eye","static","day",False,False,
  "ты ждёшь её у микрофона, объявляешь третий путь чуть громче, но снизу её больше нет."),
 ("GA_SH16","ANNOUNCER_MID","announcer_booth","close on the announcer's grief from above","CU","eye","push_in","day",False,False,
  "ты так и не узнала, дождалась ли она, и спросить совсем некого, и ты объявляешь дальше."),
 ("GA_SH17","ANNOUNCER_MID","concourse_hall","the announcer at night singing in the empty hall for the lost mother","WS","low","push_in","night",False,False,
  "ночью ты поёшь пустому залу за неё, женщину, что встречала каждый поезд до самого конца."),
 ("GA_SH18",None,"platform_night","the empty third platform at night under a single lamp","INSERT","eye","push_in","night",True,True,
  "третий путь пустует ночью, и ты объявляешь его эху, для одной так и не пришедшей женщины."),
 ("GA_SH19","ANNOUNCER_MID","announcer_booth","close on the announcer reckoning the toll of others' meetings","MCU","eye","static","night",False,False,
  "ты ведёшь чужие встречи сорок лет, и ни одна из них не твоя, ты только голос между ними."),
 ("GA_SH20","ANNOUNCER_MID","announcer_booth","close on the announcer's quiet dread","CU","eye","push_in","night",False,False,
  "и впервые ты думаешь, что и тебя однажды будут ждать у поезда, который так и не придёт."),
 # --- B2 Прощающиеся влюблённые ---
 ("GA_SH21","LOVERA_BASE","platform_day","a young couple embracing on a platform, she in a bright yellow scarf, he in a grey cap with a travel bag","MS","eye","static","day",False,False,
  "на пятом пути год за годом прощается одна и та же пара, она в жёлтом шарфе, он с сумкой."),
 ("GA_SH22",None,"platform_day","extreme close on a bright yellow scarf and a grey flat cap close together","INSERT","eye","push_in","day",False,True,
  "ты узнаёшь их по жёлтому шарфу и серой кепке, и объявляешь его поезд тише обычного."),
 ("GA_SH23","LOVERA_BASE","platform_day","close on the young woman gripping his sleeve until the last whistle","CU","eye","push_in","day",False,False,
  "она держится за его рукав до последнего гудка, а ты тянешь объявление, чтобы дать им минуту."),
 ("GA_SH24","LOVERB_BASE","platform_day","the young man boarding and leaning out from the carriage door","MS","eye","static","day",False,False,
  "он уезжает на заработки за границу и обещает вернуться к весне, и ты объявляешь отправление."),
 ("GA_SH25","LOVERA_BASE","platform_day","the young woman waving after the departing train, alone on the platform","CU","eye","static","day",False,False,
  "она машет вслед, пока поезд не скроется, и остаётся на пустом перроне в жёлтом шарфе."),
 ("GA_SH26",None,"platform_day","a train shrinking away down the tracks toward the points","WS","eye","static","day",True,False,
  "ты ведёшь его поезд голосом до самой стрелки, и он увозит половину её каждый раз."),
 ("GA_SH27","LOVERA_BASE","platform_day","months later the young woman meeting his returning train on the same platform","MCU","eye","static","day",False,False,
  "к весне ты объявляешь прибытие, и она встречает его на том же пятом пути, и они снова вместе."),
 ("GA_SH28","LOVERB_BASE","platform_day","the young man stepping off into her arms, reunited","CU","eye","push_in","day",False,False,
  "и так год за годом, он уезжает осенью, она встречает весной, и ты ведёшь оба их поезда."),
 ("GA_SH29",None,"platform_day","the bright yellow scarf seen across the platform","INSERT","high","static","day",True,False,
  "жёлтый шарф на перроне ты видишь издалека, и по нему отмеряешь время не хуже, чем по табло."),
 ("GA_SH30","LOVERA_BASE","platform_day","one spring the woman meeting the train alone as it empties without him","MS","eye","static","day",False,False,
  "но однажды весной ты объявляешь прибытие, она встречает, а он не выходит из вагона."),
 ("GA_SH31","LOVERA_BASE","platform_day","close on the woman peering into each carriage window, dawning fear","CU","eye","push_in","day",False,False,
  "она идёт вдоль состава, заглядывает в каждое окно, и поезд пустеет, а его всё нет и нет."),
 ("GA_SH32","LOVERA_BASE","platform_day","the woman standing alone in her yellow scarf as the empty train departs","WS","high","static","day",False,False,
  "ты объявляешь отправление, поезд уходит, и она остаётся одна на пятом пути в жёлтом шарфе."),
 ("GA_SH33",None,"departures_board","the split-flap board flipping the train away without explanation","INSERT","eye","push_in","day",True,False,
  "ты не знаешь, что с ним, другая ли, беда ли, и табло щёлкает, не объясняя тебе ничего."),
 ("GA_SH34","LOVERA_BASE","platform_day","the woman returning each spring, alone, to meet the train that never brings him","MCU","eye","static","day",False,False,
  "и всё равно каждую весну она приходит на пятый путь и встречает поезд, который его не везёт."),
 ("GA_SH35","ANNOUNCER_MID","announcer_booth","close on the announcer's voice catching as she watches the woman","CU","eye","push_in","day",False,False,
  "ты объявляешь этот поезд ей одной, год за годом, и голос твой садится на слове весна."),
 ("GA_SH36","LOVERA_BASE","platform_day","the woman older now, the yellow scarf faded almost white, still waiting","WS","eye","static","day",False,False,
  "она стареет на твоих глазах, жёлтый шарф выцветает, а она всё ждёт на том же самом месте."),
 ("GA_SH37",None,"platform_day","extreme close on a sun-faded almost-white yellow scarf","INSERT","eye","push_in","day",False,True,
  "жёлтый шарф её выцветает почти добела, а она всё носит его, чтобы он узнал её издалека."),
 ("GA_SH38","ANNOUNCER_MID","announcer_booth","close on the announcer making a quiet vow at the microphone","MCU","eye","static","day",False,False,
  "ты клянёшься себе объявлять её поезд, пока она ходит, и это всё, что ты можешь ей дать."),
 ("GA_SH39","ANNOUNCER_MID","concourse_hall","the announcer at night singing the lovers' parting to the empty hall","WS","low","push_in","night",False,False,
  "ночью ты поёшь пустому залу их прощание, и за неё, и за того, кто так и не вернулся."),
 ("GA_SH40","ANNOUNCER_MID","announcer_booth","close on the announcer understanding her own love never came","CU","eye","push_in","night",False,False,
  "ты ведёшь чужую любовь по расписанию и понимаешь, что своей у тебя так и не случилось."),
 ("GA_SH41",None,"platform_night","the empty fifth platform at night under a single lamp","INSERT","eye","push_in","night",True,True,
  "пятый путь пустеет ночью, и ты объявляешь его эху, для женщины в выцветшем жёлтом шарфе."),
 ("GA_SH42","ANNOUNCER_MID","announcer_booth","the announcer back at the daytime microphone, composed","MS","eye","static","day",False,False,
  "наутро ты снова голос с потолка, и снова ведёшь чужие встречи, которых у тебя нет."),
]

PAL_B="weekday commuter palette, cold morning steel-blue, repetitive and grey, the rhythm of the timetable"
GB=[
 # --- B3 Пассажир 7:14 ---
 ("GB_SH01",None,"platform_day","a morning commuter platform with a local train waiting, cold steel-blue light","EWS","eye","push_in","day",True,False,
  "каждое утро в семь четырнадцать ты объявляешь один и тот же пригородный поезд."),
 ("GB_SH02","COMMUTER_MID","platform_day","a tired man with a battered tan briefcase boarding at the same spot on the platform","MS","eye","static","day",False,False,
  "и каждое утро на него садится один и тот же человек с потёртым рыжим портфелем."),
 ("GB_SH03",None,"platform_day","extreme close on a battered tan leather briefcase and a fourfold-folded newspaper","INSERT","top","push_in","day",False,True,
  "ты узнаёшь его по портфелю и сложенной вчетверо газете, тридцать лет одно и то же."),
 ("GB_SH04","COMMUTER_MID","train_interior","close on the weary commuter's face settling into a window seat","CU","eye","static","day",False,False,
  "он садится в третий вагон, у окна, и ты объявляешь отправление ровно в семь четырнадцать."),
 ("GB_SH05","ANNOUNCER_MID","announcer_booth","the announcer marking her morning by the man's arrival","MCU","high","static","day",False,False,
  "ты сверяешь по нему утро, как по часам, и его портфель надёжнее, чем большое табло."),
 ("GB_SH06",None,"platform_day","the local train departing on its daily schedule","WS","eye","static","day",True,False,
  "тридцать лет он уезжает в семь четырнадцать и возвращается в восемнадцать сорок без пропусков."),
 ("GB_SH07","COMMUTER_MID","platform_day","close on the commuter a little older, greying, the same coat","CU","eye","push_in","day",False,False,
  "он стареет в одном и том же пальто, и седеет, и портфель его трескается по самым углам."),
 ("GB_SH08",None,"departures_board","the 7:14 line flipping on the split-flap board","INSERT","eye","push_in","day",True,False,
  "ты объявляешь его поезд столько лет, что голос сам произносит семь четырнадцать раньше тебя."),
 ("GB_SH09","COMMUTER_OLD","platform_day","the man now retired-looking, riding on a weekday for no reason","MS","eye","static","day",False,False,
  "потом он ездит реже, в будни без причины, будто без этого поезда не знает, куда деть утро."),
 ("GB_SH10","COMMUTER_OLD","train_interior","close on the old man with a nearly empty briefcase by the window","CU","eye","static","day",False,False,
  "портфель его теперь почти пустой, он возит газету и термос, и едет просто чтобы куда-то ехать."),
 ("GB_SH11","COMMUTER_OLD","platform_day","one morning the 7:14 leaves and the man's usual spot is empty","WS","eye","static","day",False,False,
  "и однажды в семь четырнадцать ты объявляешь поезд, а его привычного места у окна нет."),
 ("GB_SH12",None,"train_interior","an empty window seat in the third carriage where he always sat","INSERT","eye","push_in","day",False,True,
  "третий вагон уходит без него, и впервые за тридцать лет некому занять место у окна."),
 ("GB_SH13","ANNOUNCER_MID","announcer_booth","the announcer holding the announcement an extra second, waiting","MCU","eye","static","day",False,False,
  "ты держишь объявление на лишнюю секунду, ждёшь рыжий портфель, и он так и не появляется."),
 ("GB_SH14","ANNOUNCER_MID","announcer_booth","close on the announcer not knowing what became of him","CU","eye","push_in","day",False,False,
  "ты не знаешь, болен он, умер или просто кончились поезда, в которые ещё стоит садиться."),
 ("GB_SH15",None,"platform_day","the 7:14 running on, just as punctual, without him","WS","eye","static","day",True,False,
  "поезд в семь четырнадцать ходит дальше, такой же точный, и не замечает, что кого-то нет."),
 ("GB_SH16","ANNOUNCER_MID","announcer_booth","the announcer noting the empty seat for years after","MCU","eye","static","day",False,False,
  "ты объявляешь его ещё много лет, и каждый раз отмечаешь про себя пустое место у окна."),
 ("GB_SH17","ANNOUNCER_MID","announcer_booth","close on the announcer's quiet reckoning","CU","eye","push_in","day",False,False,
  "ты понимаешь, что можно тридцать лет ездить туда и обратно и однажды просто не вернуться."),
 ("GB_SH18",None,"departures_board","the 7:14 flipping over as routine as ever","INSERT","eye","push_in","day",True,False,
  "табло щёлкает семь четырнадцать, как щёлкало всегда, и людям всё равно, кто на нём ездил."),
 ("GB_SH19","ANNOUNCER_MID","concourse_hall","the announcer at night singing for the vanished commuter","WS","low","push_in","night",False,False,
  "ночью ты поёшь пустому залу за него, человека, что всю жизнь ездил по кругу и сошёл."),
 ("GB_SH20","ANNOUNCER_MID","announcer_booth","close on the announcer seeing her own circuit in his","CU","eye","push_in","night",False,False,
  "и думаешь, что и твой круг между будкой и домом однажды разомкнётся вот так же тихо."),
 # --- B4 Семья-эмигранты ---
 ("GB_SH21","EMFATHER_BASE","platform_day","a weary father gripping two rope-tied cardboard suitcases, a small child at his side, on a far platform","MS","eye","static","day",False,False,
  "на дальний путь приходит целая семья с двумя картонными чемоданами, перевязанными верёвкой."),
 ("GB_SH22",None,"platform_day","extreme close on two cardboard suitcases tied with rope","INSERT","top","push_in","day",False,True,
  "вся их жизнь умещается в двух чемоданах на верёвке, и ты объявляешь их поезд за границу."),
 ("GB_SH23","EMCHILD_BASE","platform_day","close on a solemn eight-year-old clutching a small wooden toy amid weeping adults","CU","low","static","day",False,False,
  "девочка лет восьми держит деревянную игрушку и не понимает, почему все вокруг плачут."),
 ("GB_SH24","EMFATHER_BASE","concourse_hall","the father taking a last look around the great hall he grew up in","MS","eye","static","day",False,False,
  "отец в последний раз оглядывает зал, в котором вырос, и крепче берёт свои чемоданы."),
 ("GB_SH25","EMFATHER_BASE","platform_day","close on the father's face, the whole weight of leaving forever","CU","eye","push_in","day",False,False,
  "он уезжает навсегда, без обратного билета, и твой голос провожает его прочь из города."),
 ("GB_SH26",None,"concourse_hall","the small family far below in the vast hall, relatives seeing them off","WS","high","static","day",True,False,
  "родня машет им снизу, и ты объявляешь посадку, и понимаешь, что этих людей город теряет насовсем."),
 ("GB_SH27","EMCHILD_BASE","platform_day","the child waving the wooden toy toward a grandmother on the platform","MCU","eye","static","day",False,False,
  "девочка машет игрушкой бабушке на перроне и не знает, что видит её в самый последний раз."),
 ("GB_SH28","EMCHILD_BASE","train_interior","close on the child pressing the toy to her chest by the train window","CU","eye","push_in","day",False,False,
  "ты объявляешь отправление, и ребёнок прижимает игрушку, единственное, что уезжает с ней из детства."),
 ("GB_SH29",None,"departures_board","a foreign destination name flipping up on the board","INSERT","eye","push_in","day",True,False,
  "на табло щёлкает название чужого города, и ты произносишь его впервые, чуть спотыкаясь."),
 ("GB_SH30","EMFATHER_BASE","platform_day","the family boarding the long-distance train","WS","eye","static","day",False,False,
  "семья садится в дальний поезд, и ты ведёшь его голосом к границе, как вела тысячи других."),
 ("GB_SH31","ANNOUNCER_MID","announcer_booth","close on the announcer watching the family go, envying their courage","CU","eye","push_in","day",False,False,
  "ты провожаешь их сверху и впервые завидуешь даже им, у кого хватило смелости вот так уехать."),
 ("GB_SH32","ANNOUNCER_MID","announcer_booth","close on the announcer and the bitter contrast of her staying","MCU","eye","static","day",False,False,
  "они уезжают начинать всё заново, а ты остаёшься в будке, из которой уже никуда не уедешь."),
 ("GB_SH33",None,"platform_day","the far train shrinking toward the border in haze","WS","eye","static","day",True,False,
  "их поезд уходит за стрелку, и ты ведёшь его голосом, пока он не растворится совсем в дымке."),
 ("GB_SH34",None,"platform_day","a dropped ticket stub left on the empty platform","INSERT","high","push_in","day",False,False,
  "на перроне остаётся оброненный корешок билета, и больше от целой семьи ничего не осталось."),
 ("GB_SH35","ANNOUNCER_MID","announcer_booth","close on the announcer's level voice over inner departure","MCU","eye","static","day",False,False,
  "ты объявляешь следующий поезд, и голос твой ровный, а внутри ты уехала с ними чуть-чуть."),
 ("GB_SH36","ANNOUNCER_MID","announcer_booth","close on the announcer who never bought a ticket for herself","CU","eye","push_in","day",False,False,
  "ты ведёшь тысячи отъездов и ни разу не купила билета себе, даже в один только конец."),
 ("GB_SH37","ANNOUNCER_MID","concourse_hall","the announcer at night singing for those who left","WS","low","push_in","night",False,False,
  "ночью ты поёшь пустому залу за тех, кто уехал, и за себя, что осталась тут навсегда."),
 ("GB_SH38",None,"concourse_hall","the vast hall with its many exits onto all directions","INSERT","low","push_in","night",True,True,
  "двери вокзала открыты на все стороны света, а ты так и не вышла ни в одну из них."),
 ("GB_SH39","ANNOUNCER_MID","announcer_booth","the announcer back in the booth at routine dawn","MCU","eye","static","day",False,False,
  "наутро ты снова в будке, и снова твой голос уезжает с каждым поездом, а ты остаёшься."),
 ("GB_SH40","ANNOUNCER_MID","announcer_booth","close on the announcer's deepening understanding","CU","eye","push_in","day",False,False,
  "ты начинаешь понимать, что прожила жизнь на перроне, провожая чужих, и ни разу не свою."),
]

seed_act("gallery_a", PAL_A, GA, render_mode="static")
seed_act("gallery_b", PAL_B, GB, render_mode="static")
