# -*- coding: utf-8 -*-
"""fortune batch B: act03_priestess + act04_lovers + act05_wheel."""
from _fortune_engine import seed_act

PAL_PRIEST="mysterious deep-neon palette, violet and teal glow with candle gold, incense haze, oracular shadow"
A3=[
 ("F3_SH01","ZARA_YOUNG","reading_room","a confident young fortune-teller mid-reading at a candlelit table, fully in command, beaded curtain glowing violet behind","MS","eye","push_in","night",False,False,
  "к двадцати годам ты уже не та испуганная девочка, ты мадам зара, и к тебе записываются за неделю."),
 ("F3_SH02","ZARA_YOUNG","reading_room","close on the young reader's kohl-lined eyes studying a client with practised stillness, neon and candle on her face","CU","over","static","night",False,False,
  "ты читаешь людей за секунды, и говоришь медленно, нараспев, чтобы каждое слово ложилось им на сердце."),
 ("F3_SH03","ZARA_YOUNG","reading_room","the young woman turning a tarot card slowly for a leaning client, theatrical and assured, candle smoke","OTS","eye","static","night",False,False,
  "ты научилась тянуть паузу, и в этой паузе человек сам договаривает за тебя всё, что ты хотела узнать."),
 ("F3_SH04",None,"reading_room","extreme close on tarot cards fanned across velvet, a high priestess card face-up, violet neon shimmer","INSERT","top","push_in","night",False,True,
  "ты говоришь им про дороги, про казённый дом, про даму с тёмным сердцем, и они кивают, узнавая своих."),
 ("F3_SH05","ZARA_YOUNG","reading_room","the young reader delivering soft certain comfort, a client's hopeful tearful face across the table","MCU","eye","static","night",False,False,
  "ты даёшь им не правду, а опору, и они уходят, расправив плечи, и ты честно веришь, что помогаешь."),
 ("F3_SH06","ZARA_YOUNG","reading_room","the young woman pausing, eyes going distant and certain in the middle of a reading, an uncanny shift","CU","eye","push_in","night",False,True,
  "но однажды посреди расклада ты вдруг слышишь свой собственный голос, говорящий то, чего ты не готовила."),
 ("F3_SH07","ZARA_YOUNG","reading_room","a client recoiling in shock across the table as if a deep secret was named, candle flame between them","OTS","over","static","night",False,False,
  "не ездите в пятницу, говоришь ты ей, а она белеет и шепчет, откуда вы знаете, я никому не говорила."),
 ("F3_SH08","ZARA_YOUNG","reading_room","close on the young reader's own startled unsettled eyes, she did not expect her own words","CU","low","push_in","night",False,True,
  "и ты не знаешь, откуда, ты правда не знала, и по предплечьям опять бежит этот знакомый холодок."),
 ("F3_SH09",None,"reading_room","extreme close on a moonstone ring on a young hand resting on velvet, candlelight and violet neon on the stone","ECU","top","static","night",False,True,
  "ты смотришь на мамино кольцо с лунным камнем, и впервые думаешь, а вдруг во всём этом что-то и вправду есть."),
 ("F3_SH10",None,"back_alley","a wet violet-and-green neon back alley at night, steam from a grate, reflections trembling in the puddles","WS","high","pan_right","night",True,False,
  "ты выходишь в переулок остыть, и ночной неон дрожит в лужах, и ты гонишь от себя простой и страшный вопрос."),
 ("F3_SH11","ZARA_YOUNG","zara_apartment","the young woman alone testing herself, predicting a small thing aloud before it happens, charms around her","MCU","eye","static","night",False,False,
  "дома ты ставишь себе тихие проверки, угадываю, кто позвонит, угадываю, что скажет соседка завтра утром."),
 ("F3_SH12","ZARA_YOUNG","zara_apartment","close on the young woman startled as a phone rings exactly as foretold, neon bleed through the blinds","CU","eye","push_in","night",False,True,
  "и порой это сбывается, телефон звонит ровно тогда, и тебе становится не по себе от собственной правоты."),
 ("F3_SH13","ZARA_YOUNG","zara_apartment","the young woman sitting very still, choosing not to examine it too closely, candle and neon glow","MCU","low","static","night",False,False,
  "а порой не сбывается вовсе, и ты говоришь себе, совпадение, и так и не решаешь для себя этот вопрос."),
 ("F3_SH14",None,"strip_mall_night","the pink-and-violet neon palm-and-eye sign glowing over the salon, a steady line of figures waiting","WS","low","static","night",True,False,
  "слухи о мадам заре, которая видит насквозь, расходятся по городу, и очередь к тебе только растёт."),
 ("F3_SH15","ZARA_YOUNG","reading_room","a well-dressed client across the table pushing a thick envelope toward the young reader, neon glow","OTS","over","static","night",False,False,
  "приходят люди и побогаче, и платят больше, и ты впервые понимаешь, что на этом можно по-настоящему жить."),
 ("F3_SH16",None,"reading_room","extreme close on a thick envelope of bills on velvet beside a fanned tarot spread, candlelight","INSERT","top","push_in","night",False,False,
  "конверты становятся толще, и ты прячешь их уже не в коробку из-под чая, а в банковскую ячейку."),
 ("F3_SH17","ZARA_YOUNG","reading_room","the young woman leaning into a richer mystic persona, more shawls and rings, theatrical and assured","MS","low","static","night",False,False,
  "ты обрастаешь шалями, кольцами, благовониями, ты лепишь из себя мадам зару, и тебе идёт эта роль."),
 ("F3_SH18","ZARA_YOUNG","reading_room","close on the young woman's confident performing face, kohl and hoops, candle smoke and violet neon","CU","eye","push_in","night",False,False,
  "и ты сама уже не всегда понимаешь, где кончается твоя игра, и где начинается то, во что ты веришь."),
 ("F3_SH19",None,"reading_room","extreme close on a crystal ball on velvet, a young woman's face curving back inside it amid neon swirls","ECU","eye","push_in","night",False,True,
  "ты подолгу глядишь в шар, как в детстве, и снова видишь там только своё лицо, и больше ничего."),
 ("F3_SH20","ZARA_YOUNG","zara_salon","the young woman standing proudly in the doorway of her busy glowing salon at night, owning it","WS","low","push_in","night",False,False,
  "к двадцати пяти ты уже не у мамы в углу, у тебя свой салон, и над ним твоя собственная неоновая вывеска."),
 ("F3_SH21",None,"strip_mall_night","a brand-new bright neon sign reading psychic tarot palm with a glowing hand-and-eye over a fresh storefront","INSERT","low","static","night",False,True,
  "ты заказываешь самую яркую ладонь с глазом во всём ряду, чтобы её было видно с дальнего конца парковки."),
 ("F3_SH22","ZARA_YOUNG","reading_room","the young reader closing up for the night, setting one card face-down apart, not turning it, candle low","MCU","eye","static","night",False,True,
  "и каждую ночь, закрывая салон, ты по-прежнему откладываешь одну карту рубашкой вверх, и не трогаешь её."),
 ("F3_SH23","ZARA_YOUNG","reading_room","close on the young woman's hand hovering over the lone face-down card, then withdrawing, neon glint","ECU","top","push_in","night",False,True,
  "на себя не гадают, повторяешь ты мамины слова, и убираешь руку, и гасишь свечу, и идёшь спать одна."),
 ("F3_SH24",None,"parking_lot_rain","the strip-mall parking lot in light rain at night, the new neon hand-and-eye doubled in the wet asphalt","WS","high","static","night",True,True,
  "ты засыпаешь счастливой и одинокой, и тебе кажется, что весь мир теперь приходит к тебе за ответами."),
]

PAL_LOVERS="warm romantic neon palette, soft rose and amber glow, tender candlelight, hopeful warm night colour"
A4=[
 ("F4_SH01","MAN","reading_room","a gentle dark-haired man in a flannel shirt sitting awkwardly at the reading table, out of place, soft neon","MS","eye","push_in","night",False,False,
  "тебе двадцать шесть, когда в салон входит он, неловкий, в клетчатой рубашке, и говорит, я не верю в это всё."),
 ("F4_SH02","ZARA_YOUNG","reading_room","the young reader amused, leaning back from the cards, studying the skeptical man instead of the spread","CU","over","static","night",False,False,
  "зачем же пришёл, спрашиваешь ты, а он смущается и говорит, друзья подарили, неудобно было отказаться."),
 ("F4_SH03","MAN","reading_room","the man laughing softly, relaxing, as the reader sets the cards aside, warm rose neon between them","MCU","eye","static","night",False,False,
  "ты впервые отодвигаешь колоду в сторону, и просто разговариваешь с человеком, без карт, без роли."),
 ("F4_SH04","ZARA_YOUNG","reading_room","close on the young woman's softened unguarded face, the performer gone, just a tired person, candle glow","CU","eye","push_in","night",False,False,
  "и ты ловишь себя на том, что тебе с ним хорошо без надежды на продажу, просто хорошо, и это пугает."),
 ("F4_SH05",None,"diner_neon","a late-night diner glowing red and blue neon, two coffee cups on the counter, rain on the windows","WS","eye","push_in","night",True,False,
  "он зовёт тебя в ночную закусочную через дорогу, и вы сидите до утра под красно-синим неоном, и говорите."),
 ("F4_SH06","MAN","diner_neon","the gentle man talking earnestly over coffee in a neon booth, the woman listening across the table","OTS","over","static","night",False,False,
  "его зовут сэм, он чинит машины, и ничего не хочет от тебя угадать, он просто хочет тебя слушать."),
 ("F4_SH07","ZARA_YOUNG","diner_neon","close on the young woman laughing freely in neon light, a rare open joy, coffee steam rising","CU","eye","push_in","night",False,False,
  "ты смеёшься так, как не смеялась с детства, и впервые тебе не нужно ничего из себя изображать."),
 ("F4_SH08",None,"street_night","a quiet neon-soaked side street at night, two figures walking close together under glowing signs, wet pavement","WS","eye","track","night",True,False,
  "вы гуляете по ночным улицам в неоне, и ты не раскладываешь его будущее, ты просто хочешь, чтобы оно было с тобой."),
 ("F4_SH09","MAN","reading_room","the man visiting the salon after hours, gently teasing about the crystal ball, the reader fond and shy","MCU","eye","static","night",False,False,
  "сэм подшучивает над твоим шаром и свечами, и ты не обижаешься, и впервые сама смеёшься над ремеслом."),
 ("F4_SH10","ZARA_YOUNG","zara_apartment","the young woman showing the man her charm-hung apartment, half proud half embarrassed, warm neon bleed","MS","eye","static","night",False,False,
  "ты приводишь его домой, и он разглядывает обереги и соль на окнах, и осторожно спрашивает, ты сама-то в это веришь."),
 ("F4_SH11","ZARA_YOUNG","zara_apartment","close on the young woman caught off guard by the question, an honest flicker of doubt, candlelight","CU","eye","push_in","night",False,False,
  "и ты впервые честно отвечаешь, не знаю, сэм, иногда да, иногда нет, и сама удивляешься, что сказала правду."),
 ("F4_SH12","MAN","kitchen_charms","the man cooking at the charm-hung stove, comfortable, the woman watching from the doorway, soft amber neon","MS","eye","static","night",False,False,
  "он начинает оставаться, готовит на твоей кухне в оберегах, и впервые дом перестаёт быть только салоном."),
 ("F4_SH13","ZARA_YOUNG","kitchen_charms","close on the young woman watching the man, a soft frightened tenderness, charms hanging around her","CU","low","push_in","night",False,False,
  "ты боишься этого счастья больше, чем любого клиента, потому что счастье не разложишь по картам наперёд."),
 ("F4_SH14","MAN","reading_room","the man quietly proposing across the candlelit reading table, holding out a plain ring, nervous and warm","MCU","eye","push_in","night",False,True,
  "сэм делает тебе предложение прямо за твоим гадальным столом, и говорит, давай построим то, чего в картах нет."),
 ("F4_SH15","ZARA_YOUNG","reading_room","close on the young woman's overwhelmed face, tears and a laugh, the plain ring beside her moonstone ring","CU","eye","static","night",False,True,
  "ты говоришь да, и надеваешь его простое кольцо рядом с маминым лунным камнем, и руки у тебя дрожат."),
 ("F4_SH16",None,"reading_room","extreme close on two rings on a young hand on velvet, a plain band beside a moonstone ring, candle glow","ECU","top","push_in","night",False,True,
  "два кольца на одной руке, его простое и мамин лунный камень, и ты ещё не знаешь, какое из них победит."),
 ("F4_SH17",None,"street_night","a small wedding party under neon outside a courthouse at night, confetti catching the colored light","WS","low","static","night",True,False,
  "вы расписываетесь без шума, и празднуете в той самой неоновой закусочной, и это лучшая ночь твоей жизни."),
 ("F4_SH18","ZARA_YOUNG","diner_neon","the bride in a simple dress laughing with the groom in a neon booth, confetti in her dark hair","MCU","eye","static","night",False,True,
  "ты танцуешь с сэмом между столиков под неоном, и впервые за годы не думаешь ни о картах, ни о завтра."),
 ("F4_SH19","MAN","zara_apartment","the man taking down a few of the evil-eye charms with a gentle smile, the woman letting him, hesitant","MCU","eye","static","day",False,False,
  "сэм потихоньку снимает с гвоздей пару оберегов, и ты позволяешь, и в доме впервые становится просто светло."),
 ("F4_SH20","ZARA_YOUNG","zara_apartment","close on the young woman's peaceful face in rare daylight, the neon off, a normal happy morning","CU","eye","push_in","day",False,False,
  "на пару лет ты почти обычная женщина, у которой есть муж, утренний кофе, и салон только до шести вечера."),
 ("F4_SH21",None,"reading_room","the lone face-down card sitting untouched and a little dusty at the edge of the velvet table, neon dim","INSERT","top","static","night",False,True,
  "ты даже почти забываешь про свою карту, что лежит рубашкой вверх, припорошённая пылью, у края стола."),
 ("F4_SH22","ZARA_YOUNG","kitchen_charms","the young woman smiling at a positive pregnancy test in a charm-hung bathroom doorway, soft warm light","MCU","eye","push_in","day",False,True,
  "а потом ты узнаёшь, что у вас будет дочь, и в первый раз твоё собственное завтра кажется тебе светлым."),
 ("F4_SH23","ZARA_YOUNG","zara_apartment","close on the young woman's hand resting on her belly, the moonstone ring catching soft neon, hopeful","CU","low","push_in","night",False,False,
  "ты кладёшь руку на живот, и думаешь, эту судьбу я сама напишу, без всяких карт, своими руками."),
 ("F4_SH24",None,"parking_lot_rain","the strip-mall parking lot at night, the salon neon warm and steady, a single car, soft rain","WS","high","static","night",True,False,
  "над парковкой тихо горит твоя ладонь с глазом, и кажется, что счастье наконец пришло и осталось насовсем."),
]

PAL_WHEEL="lavish success neon palette, bright saturated magenta and gold glow, glossy confident night colour"
A5=[
 ("F5_SH01",None,"zara_salon","a thriving fortune salon at night blazing with bright magenta-and-gold neon, a long queue of clients at the door","EWS","low","push_in","night",True,True,
  "колесо фортуны поворачивается, и к тридцати годам твой салон гремит на весь город, очередь стоит до утра."),
 ("F5_SH02","ZARA_YOUNG","reading_room","the woman reading for a wealthy client, rings and shawls, fully the famous madam now, gold neon glow","MS","eye","static","night",False,False,
  "к мадам заре едут уже из других городов, актрисы, бизнесмены, отчаявшиеся жёны, и все платят не торгуясь."),
 ("F5_SH03",None,"reading_room","extreme close on a fanned tarot spread crowned by the wheel of fortune card, gold and magenta neon shimmer","INSERT","top","push_in","night",False,True,
  "ты вытягиваешь им колесо фортуны, и обещаешь поворот к лучшему, и они уходят счастливыми и щедрыми."),
 ("F5_SH04","ZARA_YOUNG","reading_room","close on the woman's assured face counting a thick stack of bills with practised fingers, gold neon","CU","high","static","night",False,False,
  "ты считаешь выручку за вечер, и это больше, чем мать зарабатывала за месяц, и тебе кружит голову."),
 ("F5_SH05","MAN","kitchen_charms","the man feeding a baby in a high chair in the kitchen, warm and happy, a few charms still on the wall","MS","eye","static","day",False,False,
  "дома сэм нянчит вашу дочь холли, и в доме пахнет не благовониями, а кашей, и это новое счастье."),
 ("F5_SH06",None,"daughter_room","a baby's tidy nursery in soft daylight, deliberately plain, no charms, a mobile turning over the crib","WS","eye","push_in","day",False,False,
  "ты обещаешь себе, что холли вырастет нормальной, без свечей, без примет, без всей этой неоновой ворожбы."),
 ("F5_SH07","ZARA_YOUNG","zara_salon","the woman hiring an assistant and expanding the salon, pointing out where new neon will go, in command","MS","low","static","night",False,False,
  "ты расширяешь салон, нанимаешь помощницу, вешаешь ещё неона, и чувствуешь себя хозяйкой собственной судьбы."),
 ("F5_SH08",None,"strip_mall_night","the salon's huge bright hand-and-eye neon now the brightest sign on the whole strip, others dim beside it","WS","low","tilt_up","night",True,True,
  "твоя ладонь с глазом теперь самая яркая на всей улице, и в её свете меркнут все вывески соседей."),
 ("F5_SH09","ZARA_YOUNG","reading_room","the woman delivering a confident reading to a hopeful couple, radiant in her power, magenta neon","OTS","eye","static","night",False,False,
  "люди верят тебе во всём, кого им любить, куда вложить деньги, какое имя дать ребёнку, и ты решаешь за них."),
 ("F5_SH10","ZARA_YOUNG","reading_room","close on the woman's eyes, a flicker of intoxication with the power she holds over people's lives","CU","low","push_in","night",False,False,
  "и тебе нравится эта власть, нравится, как чужие жизни поворачиваются от одного твоего спокойного слова."),
 ("F5_SH11","ZARA_YOUNG","reading_room","the woman pausing mid-reading with the uncanny certain look again, naming something she could not know","CU","eye","push_in","night",False,True,
  "и снова, изредка, ты говоришь то, чего знать не можешь, и оно сбывается, и холодок бежит по рукам."),
 ("F5_SH12","ZARA_YOUNG","reading_room","a wealthy client staring awestruck, treating the reader as truly gifted, pressing more money on her","OTS","over","static","night",False,False,
  "после таких случаев о тебе говорят, что у мадам зары настоящий дар, и платят ещё больше, и ты не споришь."),
 ("F5_SH13","ZARA_YOUNG","zara_apartment","the woman at home only late at night now, kissing a sleeping child she barely saw all day, tired","CU","high","static","night",False,False,
  "ты приходишь домой за полночь, и целуешь спящую холли, которую за весь день толком и не видела."),
 ("F5_SH14","MAN","kitchen_charms","the man waiting up at the kitchen table with a cold dinner, gentle but lonely, charms on the wall behind","MS","eye","static","night",False,False,
  "сэм ждёт тебя с остывшим ужином, и не упрекает, но в его глазах ты впервые замечаешь тихое одиночество."),
 ("F5_SH15","ZARA_YOUNG","reading_room","the woman waving off her husband's worry, distracted, already shuffling cards for tomorrow, gold neon","CU","eye","static","night",False,False,
  "он просит тебя работать поменьше, а ты отвечаешь, ещё немного, сэм, дай встать на ноги, и тасуешь колоду."),
 ("F5_SH16",None,"reading_room","extreme close on hands shuffling tarot late at night, the lone face-down card pushed further to the table's edge","ECU","top","push_in","night",False,True,
  "салон забирает тебя всё сильнее, и своя карта так и лежит рубашкой вверх, всё дальше, у самого края стола."),
 ("F5_SH17","ZARA_YOUNG","zara_salon","the woman surveying her packed glowing salon with pride and a faint hunger for more, magenta and gold","MS","low","push_in","night",False,False,
  "тебе всё мало, и ты думаешь, если люди готовы платить за надежду, почему бы не продавать им её побольше."),
 ("F5_SH18",None,"reading_room","extreme close on a price list propped on the velvet table listing readings, candle and curse work, rising prices","INSERT","top","static","night",False,False,
  "ты вводишь прейскурант, простой расклад, расклад на любовь, и отдельно, дороже всего, снятие порчи."),
 ("F5_SH19","ZARA_YOUNG","reading_room","close on the woman's calculating thoughtful face as a frightened client mentions a curse, neon glow","CU","eye","push_in","night",False,False,
  "ты замечаешь, что стоит сказать человеку, на вас порча, как страх открывает и душу его, и кошелёк."),
 ("F5_SH20","ZARA_YOUNG","reading_room","the woman gravely telling a frightened client they are cursed, the client clutching their bag in fear","OTS","over","static","night",False,False,
  "и ты впервые произносишь это всерьёз, ради денег, на вас тёмная порча, но я смогу её снять, не бойтесь."),
 ("F5_SH21","ZARA_YOUNG","reading_room","close on the woman's eyes, a hard new line crossed, no chill this time, only cold calculation","CU","low","push_in","night",False,True,
  "и в этот раз холодок по рукам не бежит, и ты понимаешь, что только что переступила какую-то черту."),
 ("F5_SH22",None,"strip_mall_night","the bright hand-and-eye neon over the salon at night, brilliant and hard, the parking lot empty and wet","WS","low","static","night",True,True,
  "колесо фортуны на самом верху, ты богата, знаменита, замужем, и не видишь, что оно уже пошло вниз."),
 ("F5_SH23","ZARA_YOUNG","reading_room","the woman locking up alone, glancing at the dusty face-down card but not touching it, gold neon fading","MCU","eye","static","night",False,True,
  "ты запираешь салон, смотришь на свою пыльную карту у края стола, и опять не находишь смелости её перевернуть."),
 ("F5_SH24",None,"parking_lot_rain","the strip-mall lot at night, the salon's bright neon hand doubled in deep rain puddles, a coming storm in the sky","WS","high","static","night",True,False,
  "а над парковкой собирается дождь, и твоя сияющая ладонь дрожит в лужах, будто вот-вот сорвётся вниз."),
]

seed_act("act03_priestess", PAL_PRIEST, A3)
seed_act("act04_lovers",    PAL_LOVERS, A4)
seed_act("act05_wheel",     PAL_WHEEL,  A5)
