# -*- coding: utf-8 -*-
"""fortune batch E: act11_hermit + act12_world (decline + final card reveal / coda)."""
from _fortune_engine import seed_act

PAL_HERMIT="lonely hermit-neon palette, sparse cold blue and dying amber, mostly darkness with a single weak glow"
A11=[
 ("F11_SH01",None,"salon_dying","a fortune salon years into decline at night, half its neon dead, dust on the crystal ball, faded drapes, cold dim glow","WS","eye","push_in","night",True,True,
  "проходят годы, и салон ветшает вокруг тебя, неон гаснет буква за буквой, и пыль ложится на хрустальный шар."),
 ("F11_SH02","ZARA_OLD","salon_dying","an old woman in a headscarf sitting alone in the dim dusty salon waiting for clients who rarely come, weak neon","MS","eye","static","night",False,False,
  "тебе за шестьдесят, и ты сидишь в своём углу вечерами, и ждёшь клиентов, которые приходят теперь раз в неделю."),
 ("F11_SH03","ZARA_OLD","reading_room","close on the old woman's lined face lit by failing neon, reading honestly now for a rare poor client, gentle","CU","eye","static","night",False,False,
  "ты больше не снимаешь порчу, не пугаешь, не дерёшь втридорога, ты просто слушаешь редких стариков, как себя."),
 ("F11_SH04","ZARA_OLD","reading_room","the old woman gently holding a poor old client's hand across the worn table, no theatrics now, dim warm neon","MCU","over","static","night",False,False,
  "ты берёшь с них сущие копейки, или вовсе ничего, и впервые за всю жизнь ремесло приносит не деньги, а тихий стыд."),
 ("F11_SH05",None,"street_night","a neon street at night where a bright new young psychic salon glows, while an old dim one fades down the block","WS","eye","pan_right","night",True,False,
  "напротив гремит молодая гадалка, яркая, как ты когда-то, и весь город идёт к ней, и так и должно быть, наверное."),
 ("F11_SH06","ZARA_OLD","street_night","the old woman pausing on the sidewalk watching the bright young rival's glowing salon, no envy left, only knowing","MCU","eye","static","night",False,False,
  "ты смотришь на её сияющую ладонь с глазом, и тебе не завидно, тебе её просто заранее, наперёд, очень жаль."),
 ("F11_SH07","ZARA_OLD","pawn_shop","the old woman in a neon-lit pawn shop laying down her last gold hoop earrings for a few bills, keeping the ring","MS","eye","static","night",False,False,
  "ты доносишь в ломбард последнее, серьги, шали, всё, кроме маминого кольца, его ты не отдашь и за хлеб."),
 ("F11_SH08",None,"pawn_shop","extreme close on an old hand pushing earrings across a pawn counter, the moonstone ring staying firmly on the finger","ECU","top","push_in","night",False,True,
  "кольцо с лунным камнем срослось с твоим пальцем за полвека, и ты понимаешь, что его снимут уже только с мёртвой."),
 ("F11_SH09","ZARA_OLD","zara_apartment","the old woman alone in a bare apartment, all the charms gone now, eating thin soup by the light of a single bulb and neon bleed","MS","high","static","night",False,False,
  "дома голые стены, оберегов больше нет, ты сняла их все, и впервые тишина не пугает тебя, ты к ней привыкла."),
 ("F11_SH10","ZARA_OLD","zara_apartment","close on the old woman dialing a phone slowly, hopefully, then listening to it ring out unanswered, dim neon","CU","eye","push_in","night",False,False,
  "иногда ты набираешь номер холли, слушаешь гудки, и кладёшь трубку, и говоришь себе, в другой раз, не сегодня."),
 ("F11_SH11",None,"zara_apartment","extreme close on an old photo of a grown daughter and a faded snapshot of a man, propped together by a lamp","ECU","top","push_in","night",False,True,
  "у лампы стоят две фотографии, сэм и холли, единственные двое, кого ты любила не по картам, а по-настоящему."),
 ("F11_SH12","ZARA_OLD","reading_room","the old woman tidying the worn reading table at night, the lone face-down card always there at its edge, weak neon","MCU","eye","static","night",False,True,
  "а на краю стола всё лежит твоя карта, рубашкой вверх, всю жизнь, и ты так и не узнала, что на ней."),
 ("F11_SH13","ZARA_OLD","reading_room","close on the old woman gazing at her own face-down card with something softer than fear now, almost longing, dim neon","CU","low","push_in","night",False,True,
  "теперь ты её уже не боишься, ты просто бережёшь её напоследок, как берегут последнюю спичку в холодной комнате."),
 ("F11_SH14",None,"salon_storefront_day","the salon storefront by rare grey day, the neon off, dull dead tubes spelling psychic, an empty quiet sidewalk","WS","eye","static","day",True,False,
  "днём твоя вывеска просто серые трубки, и прохожие давно не поднимают на неё глаз, и не помнят мадам зару."),
 ("F11_SH15","ZARA_OLD","reading_room","an old client, frail and grateful, leaving the salon after a gentle free reading, the old woman seeing her out","MS","eye","static","night",False,False,
  "последняя твоя клиентка, старушка, благодарит и уходит, и ты понимаешь почему-то, что она была и вправду последней."),
 ("F11_SH16","ZARA_OLD","reading_room","close on the old woman alone after the last client, the empty chair across the table, the dim salon settling into silence","CU","eye","push_in","night",False,False,
  "ты остаёшься одна, и стул напротив пуст, и спрашивать тебя больше некому, и больше уже и не придут."),
 ("F11_SH17",None,"strip_mall_night","the salon's neon hand-and-eye with only two or three letters weakly flickering now, the rest dead, wet empty lot","WS","low","static","night",True,True,
  "снаружи догорает твоя ладонь с глазом, остались гореть две буквы, и те мигают, будто прощаются с улицей."),
 ("F11_SH18","ZARA_OLD","reading_room","the old woman lighting a single candle on the worn velvet table in the dark salon, settling in for a long night","MCU","low","push_in","night",False,False,
  "ты зажигаешь одну свечу, последнюю из коробки, и садишься к столу, и чувствуешь, что эта ночь будет особенной."),
 ("F11_SH19","ZARA_OLD","reading_room","close on the old woman's calm face by candlelight, a lifetime behind her, ready at last to face her own card, dim neon","CU","eye","push_in","night",False,False,
  "ты прожила всю жизнь, читая чужие судьбы, и ни разу не заглянула в свою, и вот пришло время это исправить."),
 ("F11_SH20",None,"parking_lot_rain","the strip-mall parking lot in soft night rain, the salon's last neon letters trembling in the wet asphalt, deserted","WS","high","static","night",True,True,
  "за окном начинается тихий дождь, тот самый, и неон дрожит в лужах, и это та самая ночь, с которой всё началось."),
 ("F11_SH21","ZARA_OLD","reading_room","the old woman slowly shuffling her worn tarot deck one last time by candlelight, cards clicking softly, dim neon","MCU","high","static","night",False,False,
  "ты тасуешь колоду в последний раз, и слушаешь, как щёлкают карты, и запах воска поднимается, как в детстве."),
 ("F11_SH22","ZARA_OLD","reading_room","close on the old woman's ringed hand resting on the lone face-down card at last, no longer afraid, candle glow","ECU","top","push_in","night",False,True,
  "и кладёшь ладонь на свою карту, ту, что лежала рубашкой вверх всю твою жизнь, и впервые рука у тебя не дрожит."),
 ("F11_SH23","ZARA_OLD","reading_room","the old woman pausing with her hand on the card, eyes closed, gathering a lifetime of courage, candlelight and dim neon","MCU","low","push_in","night",False,False,
  "на себя не гадают, говорила мать, на себя смотреть страшнее всего, и теперь ты понимаешь наконец, почему."),
 ("F11_SH24",None,"reading_room","extreme close on a single candle flame leaning in a draft beside a face-down tarot card on worn velvet, dim neon","INSERT","eye","push_in","night",False,True,
  "свеча клонится от сквозняка, и тень от неё ходит по карте, и ты делаешь самый глубокий вдох в своей жизни."),
]

PAL_WORLD="final dying-neon palette, last guttering magenta letters fading to black, candle-gold sinking into darkness"
A12=[
 ("F12_SH01","ZARA_OLD","salon_dying","an old woman alone at a candlelit table in a salon of dead neon at night, her hand on a single face-down card","MCU","eye","push_in","night",False,True,
  "вот мы и вернулись туда, где я начала, в эту дождливую ночь, к этой карте, что я обещала тебе показать."),
 ("F12_SH02","ZARA_OLD","reading_room","close on the old woman's resolved peaceful face by candlelight, ready, the dead neon cold behind her","CU","eye","static","night",False,False,
  "ты ждал со мной до самого конца, и за это я открою тебе то, чего не открывала себе шестьдесят лет."),
 ("F12_SH03","ZARA_OLD","reading_room","the old woman's ringed fingers beginning to lift the corner of the lone face-down tarot card, candle trembling","ECU","top","push_in","night",False,True,
  "ты берёшься за уголок своей карты, той единственной, на себя, и медленно, медленно начинаешь её переворачивать."),
 ("F12_SH04","ZARA_OLD","reading_room","the old woman's breath held, eyes wide on the turning card, a lifetime hanging on this moment, candlelight","MCU","low","push_in","night",False,False,
  "сердце колотится, как у той девочки на мамином стуле, и тебе кажется, что сейчас ты увидишь всю свою жизнь разом."),
 ("F12_SH05",None,"reading_room","extreme close on a worn old tarot card turned face-up at last, its painted image rubbed away to a blank smooth surface, candle glow","ECU","top","push_in","night",False,True,
  "и ты переворачиваешь её, и видишь, что рисунок давно стёрся, карта пустая, гладкая, на ней нет ничего."),
 ("F12_SH06","ZARA_OLD","reading_room","the old woman staring at the blank worn card in her hands, understanding flooding her face, candlelight","MCU","eye","push_in","night",False,True,
  "пустая, потому что ты так и не дала ей ничего сказать, ты прожила всю жизнь, не глядя в своё собственное завтра."),
 ("F12_SH07","ZARA_OLD","reading_room","the old woman laughing softly and weeping at once over the blank card, a terrible gentle understanding, dim glow","MCU","low","static","night",False,False,
  "ты смеёшься и плачешь разом, потому что карты не врут, врут руки, что их держат, а свою я держала рубашкой вверх."),
 ("F12_SH08","ZARA_OLD","reading_room","close on the old woman's wet eyes, the question of a lifetime, was it ever a gift, never to be answered now","CU","eye","push_in","night",False,True,
  "был ли у меня дар или одна лишь ловкость, я так и не узнала, и эта пустая карта мне уже не ответит."),
 ("F12_SH09","ZARA_OLD","zara_apartment","the old woman picking up the phone with sudden resolve, dialing a long-known number in the candlelit dark","MCU","eye","static","night",False,False,
  "ты берёшь телефон, и набираешь номер холли, не чтобы погадать, а просто чтобы один раз сказать живое слово."),
 ("F12_SH10","ZARA_OLD","zara_apartment","close on the old woman listening to the phone ring and ring, hope and grief together, dim neon and candle","CU","eye","push_in","night",False,False,
  "ты слушаешь гудки, один, другой, третий, и держишь трубку, и впервые не кладёшь её, ты ждёшь до конца."),
 ("F12_SH11","ZARA_OLD","zara_apartment","the old woman leaving a quiet message into the phone, the blank card on the table beside her, candlelight","MCU","low","push_in","night",False,False,
  "и в тишину автоответчика ты говоришь, холли, девочка, это мама, я ничего не хочу, просто прости меня, если сможешь."),
 ("F12_SH12","ZARA_OLD","reading_room","the old woman setting the phone down gently and turning back to the blank card and the guttering candle, at peace","MCU","eye","static","night",False,False,
  "ты кладёшь трубку, и возвращаешься к своей пустой карте, и тебе впервые за всю жизнь почти спокойно."),
 ("F12_SH13","ZARA_OLD","reading_room","close on the old woman addressing the viewer directly, gentle and certain, candlelight and dead neon around her","CU","eye","push_in","night",False,False,
  "вот и вся моя жизнь, и теперь ты знаешь, что было на моей карте, и можешь решать сам, верить мне или нет."),
 ("F12_SH14","ZARA_OLD","reading_room","the old woman speaking softly to the viewer, the CTA, weary and kind, the last candle low beside her","MCU","eye","static","night",False,False,
  "если ты досмотрел до конца, останься со мной ещё на миг, подпишись, и береги себя, слышишь, береги."),
 ("F12_SH15","ZARA_OLD","reading_room","close on the old woman's gentle warning face, the one true reading she gives, candlelight in her tired eyes","CU","eye","push_in","night",False,False,
  "и если однажды кто-то пообещает погадать тебе на завтра за деньги, вспомни меня, и просто пройди мимо."),
 ("F12_SH16",None,"reading_room","extreme close on the blank worn tarot card lying face-up on velvet beside a candle burning down to its base","ECU","top","static","night",False,True,
  "не отдавай чужим рукам свою судьбу, своё завтра, свои деньги, и не бойся однажды заглянуть в свою карту первым."),
 ("F12_SH17",None,"strip_mall_night","the salon's neon hand-and-eye flickering its last two letters, then going completely dark against the rainy night","WS","low","static","night",True,True,
  "за окном гаснет последняя буква твоей неоновой ладони, тихо, без искры, и улица погружается в темноту."),
 ("F12_SH18",None,"reading_room","extreme close on a candle flame guttering and shrinking beside the blank card on the velvet, shadows growing","ECU","eye","push_in","night",False,True,
  "и свеча на столе оплывает до самого конца, и пламя её становится всё меньше, и тени подступают всё ближе."),
 ("F12_SH19","ZARA_OLD","reading_room","the old woman sitting still and at peace in the near-dark salon, the blank card before her, eyes closing softly","MCU","high","pull_out","night",False,True,
  "ты сидишь в гаснущем свете, одна, с пустой картой в руках, и впервые ничего не предсказываешь, ты просто живёшь."),
 ("F12_SH20",None,"reading_room","a dim almost-dark reading table with a blank face-up card and a candle nearly out, the salon dissolving into shadow","EWS","eye","push_in","night",True,True,
  "эта история вымышлена, и все совпадения с реальными людьми случайны, не повторяй чужих ошибок, и береги себя."),
 ("F12_SH21",None,"reading_room","near-total darkness with a last faint pinpoint of candlelight on a blank tarot card, fading toward black","INSERT","eye","push_in","night",True,True,
  "а что было на твоей собственной карте всю эту жизнь, ты ведь так ни разу и не посмотрел, может, посмотришь, пока не поздно."),
]

seed_act("act11_hermit", PAL_HERMIT, A11)
seed_act("act12_world",  PAL_WORLD,  A12)
