# -*- coding: utf-8 -*-
"""mascot batch A: cold_open + act01_invisible + act02_first_mask + act03_first_mascot."""
from _mascot_engine import seed_act

PAL_BACK="dim cluttered back-room palette, cold fluorescent grey-green, dusty shadow, one warm patch of light"
COLD=[
 ("M0_SH01",None,"mascot_backroom","a giant grinning golden-eagle mascot head sitting alone on a folding table under a single fluorescent tube, hollow and smiling at nothing","INSERT","eye","push_in","day",True,True,
  "вот она, моя голова, точнее не моя, голова орла, в которой я прожил всю свою жизнь."),
 ("M0_SH02","MAN_OLD","mascot_backroom","the bare stooped back and grey head of an old man sitting on a stool facing away, never showing his face, a mascot head on the table before him","BACK","eye","static","day",False,False,
  "а это я, со спины, моё лицо ты всё равно не вспомнишь, его никто никогда и не видел."),
 ("M0_SH03",None,"mascot_backroom","a dim costume back room, plush fur suits hanging on a rack, several mascot heads on metal shelves, a fan, scuffed concrete","WS","eye","pan_right","day",True,False,
  "сорок лет меня любили миллионы, обнимали, фотографировали, и ни один не знал, как меня зовут."),
 ("M0_SH04","MAN_OLD","mascot_backroom","the silhouette of an old man's bowed head and shoulders from behind, the warm light of the room beyond, his face unseen","MCU","over","push_in","day",False,False,
  "останься со мной до самого конца, подпишись, и береги себя, слышишь, очень тебя прошу, береги."),
 ("M0_SH05",None,"mask_interior","the dark cramped inside of a giant foam mascot head, a mesh eye-screen letting in bright slatted light, a small faded photo taped beside it","INSERT","eye","push_in","day",False,True,
  "всю жизнь я смотрел на мир вот так, сквозь сетку, из темноты, изнутри чужой нарисованной улыбки."),
 ("M0_SH06","MAN_OLD","mascot_backroom","close on an old man's thin trembling hand resting on a folding table beside a mascot head, his face out of frame","CU","high","static","day",False,False,
  "снаружи я всегда улыбался, а внутри задыхался, потел и плакал, и этого не видел никто на свете."),
 ("M0_SH07",None,"mascot_backroom","an electric fan and a row of water bottles on a shelf in a dim costume room, a towel draped over a chair","MS","eye","static","day",True,False,
  "сейчас я наконец сниму эту голову, первый и последний раз при тебе, и ты увидишь, кто я такой."),
 ("M0_SH08",None,"mask_interior","extreme close on a small faded photograph of a woman and a child taped inside a foam mascot head beside the eye-mesh","ECU","eye","push_in","day",False,True,
  "но сначала я расскажу всё, с самого начала, как невидимый мальчик стал чужой большой улыбкой."),
 ("M0_SH09","MAN_OLD","mascot_backroom","an old man's stooped silhouette from behind in a dim back room, the grinning mascot head glowing faintly on the table","WS","eye","pull_out","day",False,False,
  "потому что это вся моя жизнь, и кроме тебя, рассказать её больше уже совсем некому."),
 ("M0_SH10",None,"mascot_backroom","extreme close on the painted permanent grin of a mascot head, the wide cheerful mouth catching the fluorescent light","ECU","low","push_in","day",False,True,
  "вот эту улыбку, нарисованную, вечную, ты помнишь, а меня под ней не помнишь совсем."),
 ("M0_SH11","MAN_OLD","mascot_backroom","the old man from behind lifting his face toward a small high window, his features still hidden in shadow","MCU","low","static","day",False,False,
  "не уходи, дай мне договорить до конца, и тогда сам решишь, стоила ли того эта улыбка."),
 ("M0_SH12",None,"childhood_home","a child's small toy corner in a faded 1980s living room, dusty and quiet, an empty chair, washed-out afternoon light","INSERT","eye","push_in","day",True,False,
  "а всё начинается в тихом доме, где меня будто и не было, в мальчике, которого не замечали."),
]

PAL_CHILD="muted lonely 1980s palette, faded beige and brown, flat domestic light, washed-out and unnoticed"
A1=[
 ("M1_SH01",None,"childhood_home","a faded 1980s American living room, a worn plaid sofa, a small boxy television murmuring, an empty quiet space","EWS","eye","push_in","day",True,False,
  "тысяча девятьсот восемьдесят пятый, тебе восемь, и ты тот ребёнок, которого в комнате не замечают."),
 ("M1_SH02","MAN_KID","childhood_home","a small shy boy sitting alone on the floor by a sofa, knees up, watching adults who do not look at him","MS","high","static","day",False,False,
  "родители заняты своим, телевизор громче тебя, и ты привыкаешь сидеть тихо, чтобы не мешать."),
 ("M1_SH03","MAN_KID","childhood_home","close on a small boy's downcast quiet face, big watchful eyes, unnoticed in the warm dim room","CU","eye","push_in","day",False,False,
  "ты рано понимаешь, что тебя проще не звать к столу, чем заметить, и ты не обижаешься, ты привыкаешь."),
 ("M1_SH04",None,"school_gym","a 1980s school classroom from the back, rows of desks, a teacher at the board, one empty-seeming desk in a corner","WS","eye","pan_right","day",True,False,
  "в школе всё то же самое, учительница ведёт пальцем по списку, и каждый раз перескакивает через тебя."),
 ("M1_SH05","MAN_KID","school_gym","a small boy at a desk with his hand half-raised then lowering it, unnoticed, other children turned away","MCU","eye","static","day",False,False,
  "ты тянешь руку, и опускаешь, потому что тебя всё равно не вызовут, и постепенно перестаёшь тянуть."),
 ("M1_SH06","MAN_KID","school_gym","a boy eating alone at the end of a long lunch table, other children clustered far down it laughing","WS","high","static","day",False,False,
  "ты обедаешь один на краю стола, и смотришь, как смеются другие, и учишься быть невидимым, как стекло."),
 ("M1_SH07",None,"suburban_street","other children playing ball in a suburban street at dusk, one small boy sitting alone on a far kerb watching","WS","eye","static","dusk",False,False,
  "после уроков двор гоняет мяч, а ты сидишь на бордюре и смотришь, и тебя не зовут, и ты не просишься."),
 ("M1_SH08","MAN_KID","suburban_street","close on a lonely boy's face watching unseen children play, longing and resignation together, dusk light","CU","low","push_in","dusk",False,False,
  "тебе хочется к ним, но ты не знаешь, как, слова застревают, и проще просто смотреть со стороны."),
 ("M1_SH09",None,"childhood_home","a class photograph on a faded wall where one small boy stands at the very edge, half cut off by the frame","INSERT","eye","push_in","day",False,True,
  "на всех общих фотографиях ты с самого края, наполовину срезан рамкой, будто тебя дорисовали потом."),
 ("M1_SH10","MAN_KID","childhood_home","a small boy lying on his bed staring at the ceiling, hands folded, utterly alone in a dim room","MS","high","static","night",False,False,
  "по вечерам ты лежишь и придумываешь, каким бы был, если бы тебя замечали, и засыпаешь на полуслове."),
 ("M1_SH11","MAN_KID","school_gym","a boy standing invisibly at the edge of a noisy group of children who all face away from him, bright gym light","MS","eye","static","day",False,False,
  "ты стоишь рядом с играющими, совсем близко, и всё равно как будто за стеклом, по ту сторону."),
 ("M1_SH12",None,"suburban_street","an ordinary deserted suburban street in flat summer daylight, modest houses, an empty driveway, still and quiet","EWS","high","pan_left","day",True,False,
  "целое лето может пройти, и ни один человек не позовёт тебя по имени, и ты к этому привыкаешь тоже."),
 ("M1_SH13","MAN_KID","childhood_home","a boy quietly setting the table for a family that doesn't notice, small and careful, warm dim kitchen beyond","MCU","eye","static","day",False,False,
  "ты стараешься быть полезным, тихим, удобным, думая, что тогда тебя заметят, но это не работает."),
 ("M1_SH14","MAN_KID","childhood_home","close on a boy's face brightening faintly as an adult passes, then falling as they pass without looking","CU","eye","push_in","day",False,False,
  "ты ловишь каждый взгляд взрослых, и каждый раз он скользит сквозь тебя, как сквозь пустое место."),
 ("M1_SH15",None,"school_gym","a hallway of lockers, children streaming past, one small still figure pressed against the wall unnoticed","WS","eye","track","day",False,False,
  "в коридоре тебя обтекают, как камень в реке, и ты учишься прижиматься к стене, чтобы не толкнули."),
 ("M1_SH16","MAN_KID","suburban_street","a boy walking home alone along a dusk street, long shadow, hands in pockets, small under big trees","WS","low","track","dusk",False,False,
  "ты идёшь домой один, и придумываешь себе друга, и разговариваешь с ним вслух, тихо, чтоб не услышали."),
 ("M1_SH17","MAN_KID","childhood_home","a boy drawing alone at a kitchen table, absorbed, a single lamp, the rest of the house dark","MCU","high","static","night",False,False,
  "ты рисуешь часами, миры, где тебя видят, где ты главный, и прячешь рисунки, чтоб над ними не смеялись."),
 ("M1_SH18",None,"childhood_home","extreme close on a child's drawing of a smiling figure surrounded by other smiling figures, crayon","ECU","top","push_in","night",False,True,
  "на каждом рисунке ты в центре, и все вокруг улыбаются тебе, и тебе тепло, пока ты не поднимешь глаза."),
 ("M1_SH19","MAN_KID","school_gym","a teacher handing out parts for a school show, children eager around the desk, one boy hanging back unseen","OTS","eye","static","day",False,False,
  "а потом в классе раздают роли для утренника, и все тянут руки, и ты, как всегда, стоишь в стороне."),
 ("M1_SH20","MAN_KID","school_gym","close on a boy watching other children get the good parts, quiet, expecting nothing","CU","eye","static","day",False,False,
  "хорошие роли разбирают быстро, принцы, рыцари, а тебе достаётся то, что не захотел никто другой."),
 ("M1_SH21",None,"school_gym","a bulky shapeless animal costume folded on a chair, a big papier-mache head beside it, unwanted","INSERT","high","push_in","day",False,True,
  "тебе дают костюм зверя, мешковатый, с большой головой, в котором не видно лица, никто его не хотел."),
 ("M1_SH22","MAN_KID","school_gym","a small boy holding up a big animal costume head, looking into its hollow grinning face, curious","MCU","eye","push_in","day",False,False,
  "ты берёшь эту голову в руки, и заглядываешь в неё, в пустую улыбку, и впервые тебе не страшно, а любопытно."),
 ("M1_SH23","MAN_KID","childhood_home","a boy practising the costume alone in his room at night, the big head on, only his small body visible","WS","low","static","night",False,False,
  "дома ты примеряешь её тайком, и смотришь в зеркало, и видишь не себя, а кого-то, кого можно полюбить."),
 ("M1_SH24",None,"mask_interior","the dark inside of a child-sized animal mask, slats of dim bedroom light through the eye-holes, close and quiet","INSERT","eye","push_in","night",False,True,
  "внутри темно и тихо, и слышно только твоё дыхание, и впервые в этой темноте тебе совсем спокойно."),
 ("M1_SH25","MAN_KID","childhood_home","close on a boy's calm face half-lit inside the costume head, no longer anxious, almost safe","CU","eye","push_in","night",False,False,
  "за этой маской тебя не видно, а значит, и не отвергнут, и ты вдруг понимаешь, что нашёл, где спрятаться."),
 ("M1_SH26","MAN_KID","childhood_home","a boy asleep hugging the big costume head like a pillow, peaceful in the dim room","MCU","high","static","night",False,False,
  "ты засыпаешь, обняв эту голову, как подушку, и тебе снится, что завтра весь зал наконец тебя увидит."),
 ("M1_SH27",None,"school_gym","an empty school stage at night with a single animal costume laid out, paper decorations, waiting","EWS","eye","push_in","night",True,False,
  "ты ещё не знаешь, что эта мешковатая шкура решит всю твою жизнь, и больше ты её уже не снимешь."),
 ("M1_SH28","MAN_KID","childhood_home","close on the boy's hopeful sleeping face in the dark, the costume head beside him on the pillow","CU","low","push_in","night",False,True,
  "восемь лет, тёмная комната, и мальчик, который наконец нашёл способ, чтобы его полюбили, не глядя на него."),
]

PAL_GYM="bright primary school-show palette, harsh gymnasium light, paper-decoration colours, cheerful and a little garish"
A2=[
 ("M2_SH01",None,"school_gym","a school gymnasium set for a children's holiday show, a low stage with a paper backdrop, rows of parents on folding chairs","EWS","high","push_in","day",True,False,
  "день утренника, спортзал полон родителей, и ты за кулисами, в мешковатой шкуре, с большой головой."),
 ("M2_SH02","MAN_KID","school_gym","a small boy in an oversized animal costume waiting in the wings, peeking at the bright stage, nervous","MS","eye","static","day",False,False,
  "ты должен просто стоять деревом на заднем плане, и ты выходишь, и у тебя подгибаются коленки."),
 ("M2_SH03",None,"mask_interior","the dark inside of a costume head looking out through eye-holes at a bright stage and a sea of parents","POV","eye","push_in","day",False,True,
  "сквозь дырки для глаз ты видишь полный зал, и сердце колотится, но лица твоего не видит никто."),
 ("M2_SH04","MAN_KID","school_gym","a costumed child accidentally tripping on stage, the big head wobbling, parents beginning to laugh warmly","WS","eye","static","day",False,False,
  "ты запинаешься о свой же хвост, и падаешь, и зал ахает, а потом смеётся, тепло, по-доброму."),
 ("M2_SH05","MAN_KID","school_gym","the costumed child playing up the stumble for laughs, hamming it, the audience delighted","MS","low","static","day",False,False,
  "и ты вдруг понимаешь, что смеются не над тобой, а над зверем, и ты падаешь ещё раз, нарочно."),
 ("M2_SH06",None,"school_gym","a gymnasium full of laughing applauding parents and children, all eyes on the stage, joyful","WS","eye","pan_right","day",False,True,
  "весь зал хохочет и хлопает, впервые в жизни сотня людей смотрит только на тебя, и ты им нравишься."),
 ("M2_SH07",None,"mask_interior","inside the costume head, the boy's face lit by stage light through the mesh, eyes wide and shining with joy","INSERT","eye","push_in","day",False,True,
  "внутри головы ты сияешь, по-настоящему, впервые, но этого сияния, как всегда, не видит никто."),
 ("M2_SH08","MAN_KID","school_gym","the costumed child taking an exaggerated bow to applause, the big head bobbing, triumphant","MCU","low","push_in","day",False,False,
  "ты кланяешься, и тебе кричат браво зверю, и ты впервые чувствуешь то, чего не знал, что тебя любят."),
 ("M2_SH09","MAN_KID","school_gym","children crowding around the costumed boy after the show, hugging the animal, delighted","WS","eye","static","day",False,False,
  "после спектакля дети липнут к зверю, обнимают, тянут за лапы, и тебе хочется, чтоб это не кончалось."),
 ("M2_SH10","MAN_KID","school_gym","a child hugging the mascot's leg tightly, looking up at the big grinning head with pure love","MCU","low","static","day",False,False,
  "одна девочка обнимает тебя крепко и говорит, я тебя люблю, и говорит это зверю, но слышишь это ты."),
 ("M2_SH11",None,"mask_interior","the boy's face inside the head, tears of joy on his cheeks behind the cheerful mesh-eyed mask","ECU","eye","push_in","day",False,True,
  "и за нарисованной улыбкой ты плачешь от счастья, и никто не видит слёз, видят только улыбку зверя."),
 ("M2_SH12","MAN_KID","school_gym","the costumed boy reluctant to take the head off, holding it on as other kids change out of costumes","MS","eye","static","day",False,False,
  "когда зовут разоблачаться, ты тянешь время, тебе не хочется снимать голову, не хочется снова исчезать."),
 ("M2_SH13","MAN_KID","school_gym","a teacher gently lifting the costume head off, the boy underneath instantly small and unnoticed again","MCU","eye","static","day",False,False,
  "учительница снимает с тебя голову, и ты снова обычный мальчик, и взгляды тут же соскальзывают с тебя."),
 ("M2_SH14","MAN_KID","school_gym","the same parents who cheered now looking past the unmasked boy, gathering their own children","WS","high","static","day",False,False,
  "те же родители, что кричали браво, теперь смотрят сквозь тебя, и хвалят зверя, а тебя не замечают."),
 ("M2_SH15","MAN_KID","school_gym","close on the unmasked boy's face dimming back to invisibility, longing toward the costume head on a chair","CU","eye","push_in","day",False,False,
  "и ты смотришь на брошенную на стул голову, и понимаешь, что любили не тебя, а её, эту улыбку."),
 ("M2_SH16",None,"school_gym","the discarded animal costume head sitting alone on a folding chair in an emptying gymnasium","INSERT","high","push_in","day",False,True,
  "но даже так это лучшее, что с тобой было, ведь впервые тебя, хоть и в шкуре, по-настоящему любили."),
 ("M2_SH17","MAN_KID","childhood_home","the boy at home that night drawing the animal costume over and over, obsessed, by lamplight","MCU","high","static","night",False,False,
  "дома ты рисуешь этого зверя снова и снова, и решаешь, что хочешь так всегда, любить из-под маски."),
 ("M2_SH18","MAN_KID","childhood_home","close on the boy's determined hopeful face, a crayon drawing of a smiling mascot in front of him","CU","eye","push_in","night",False,False,
  "если меня не видят без маски, думаешь ты, значит, я буду жить в маске, и пусть любят хоть её."),
 ("M2_SH19",None,"suburban_street","a teenager walking to school past a shop with a costumed mascot waving outside, watching it with longing","WS","eye","track","day",False,False,
  "ты подрастаешь, и всюду замечаешь их, ростовых кукол у магазинов, и завидуешь им до боли."),
 ("M2_SH20","MAN_KID","suburban_street","a teenage version of the boy pausing to watch a store mascot wave at passers-by, mesmerized","MCU","eye","static","day",False,False,
  "вот стоит огромная улыбающаяся кукла, и к ней бегут дети, и ты думаешь, я хочу быть вот этим."),
 ("M2_SH21","MAN_KID","childhood_home","a teenager sewing or mending a homemade costume head in his room at night, focused, alone","MS","high","static","night",False,False,
  "ты мастеришь себе маски сам, из картона, из старой шубы, и ходишь в них по дому, когда никого нет."),
 ("M2_SH22",None,"mask_interior","inside a crude homemade mask, a teenager's calm eyes looking out at a dim familiar room","INSERT","eye","push_in","night",False,True,
  "и каждый раз, надевая маску, ты чувствуешь, как отпускает, как будто только в ней ты можешь дышать."),
 ("M2_SH23","MAN_KID","childhood_home","close on a teenager's calm hidden face inside a homemade mask, finally at ease in the dark","CU","eye","push_in","night",False,False,
  "снаружи ты по-прежнему тихий, незаметный, а внутри маски, в темноте, ты наконец кто-то, ты есть."),
 ("M2_SH24",None,"school_gym","an empty stage with a spotlight on a lone costume head, the gym dark around it, waiting","EWS","eye","pull_out","night",True,True,
  "ты ещё не знаешь, что эта маленькая детская хитрость спрятаться за улыбкой станет всей твоей жизнью."),
]

PAL_MALL="glossy 1990s mall palette, bright skylight and neon storefronts, balloons, cheerful commercial colour, a little garish"
A3=[
 ("M3_SH01",None,"mall_atrium","a bright 1990s shopping-mall atrium, a tiled fountain, escalators, glass storefronts, a small stage with balloons","EWS","high","push_in","day",True,False,
  "тебе девятнадцать, и ты находишь своё, объявление, в торговый центр нужен человек в костюм талисмана."),
 ("M3_SH02","MAN_YOUNG","mall_atrium","a thin shy young man at a service counter handing over a form, awkward, barely meeting the manager's eye","OTS","eye","static","day",False,False,
  "на собеседовании ты двух слов связать не можешь, краснеешь, мнёшься, и менеджер уже хочет отказать."),
 ("M3_SH03","MANAGER","mall_atrium","a brisk events manager with a lanyard glancing at a thin nervous young man, unimpressed, about to wave him off","MCU","eye","static","day",False,False,
  "но костюмщик нужен срочно, и менеджер машет рукой, ладно, лезь в куклу, посмотрим, как справишься."),
 ("M3_SH04","MAN_YOUNG","dressing_area","a young man stepping into a large plush mascot suit in a cramped back area, pulling the big head on","WS","eye","static","day",False,False,
  "ты залезаешь в костюм, тяжёлый, душный, натягиваешь голову, и впервые за годы тебе становится легко."),
 ("M3_SH05",None,"mask_interior","inside the big mascot head, a young man's calm eyes looking out through the mesh at a bright mall","INSERT","eye","push_in","day",False,True,
  "сквозь сетку ты видишь толпу, и тебя не трясёт, ведь они видят не тебя, они видят весёлую куклу."),
 ("M3_SH06","MASCOT","mall_atrium","a big grinning plush mascot stepping out onto a mall stage, arms wide, as children come running","WS","low","push_in","day",False,True,
  "ты выходишь на площадку, разводишь лапы, и к тебе со всех сторон с визгом бегут дети, к тебе, к кукле."),
 ("M3_SH07","MASCOT","mall_atrium","the plush mascot hugging delighted children, parents filming, a joyful crowd around the costume","WS","eye","static","day",False,False,
  "ты обнимаешь их, машешь, пляшешь, и впервые тебя окружает любовь, целый круг любви, и ты в её центре."),
 ("M3_SH08",None,"mask_interior","inside the mascot head, the young man's face beaming with joy, sweat already beading on his brow","ECU","eye","push_in","day",False,True,
  "внутри ты сияешь и обливаешься потом, и это лучший день твоей жизни, и никто не видит ни того, ни другого."),
 ("M3_SH09","MASCOT","mall_atrium","the mascot posing for a family photo, a child on its arm, everyone smiling at the costume","MS","eye","static","day",False,False,
  "с тобой фотографируются семьями, и на всех этих снимках будет улыбающаяся кукла, а не ты, никогда не ты."),
 ("M3_SH10","MANAGER","mall_atrium","the manager watching the popular mascot work the crowd, nodding with satisfaction, counting the crowd","MCU","eye","static","day",False,False,
  "менеджер смотрит, как ты собираешь толпу, и довольно кивает, и берёт тебя на постоянно, ты прирождённый."),
 ("M3_SH11",None,"dressing_area","a sweat-soaked plush mascot suit slumped on a stand in a cramped back room, a fan blowing, water bottles","INSERT","high","static","day",False,False,
  "после смены ты выползаешь из костюма, мокрый насквозь, и пьёшь воду залпом, и тебе хорошо, как никогда."),
 ("M3_SH12","MAN_YOUNG","dressing_area","a thin young man slumped exhausted and happy against a wall in a dressing area, the mascot head beside him","MS","high","static","day",False,False,
  "руки трясутся от усталости, духота, но ты улыбаешься, потому что сегодня тебя любили четыре часа подряд."),
 ("M3_SH13","MAN_YOUNG","mall_atrium","the unmasked young man walking out through the mall after his shift, instantly invisible among shoppers","WS","eye","track","day",False,False,
  "а потом ты выходишь из служебной двери обычным человеком, и снова никто не оборачивается, и это уже не больно."),
 ("M3_SH14","MAN_YOUNG","mall_atrium","close on the young man's face, content rather than sad, carrying the secret of being loved in disguise","CU","eye","push_in","day",False,False,
  "ведь теперь у тебя есть тайна, ты знаешь, как быть любимым, надо просто исчезнуть в чужой улыбке."),
 ("M3_SH15","MASCOT","mall_atrium","the mascot at another event, dancing for a birthday crowd of children under bright lights","WS","eye","pan_right","day",False,False,
  "ты берёшь все смены, дни рождения, открытия, праздники, и не отказываешься ни от одного, тебе мало."),
 ("M3_SH16",None,"mask_interior","inside the head during a hot event, the young man's face dripping with sweat, breathing hard, still smiling","INSERT","eye","static","day",False,True,
  "внутри жара под сорок, пот заливает глаза, дышать нечем, но ты держишь улыбку, ведь снаружи праздник."),
 ("M3_SH17","MASCOT","fairground","the plush mascot working a county fair at dusk among string lights and game stalls, kids trailing it","WS","low","track","dusk",False,False,
  "тебя зовут на ярмарки, и ты пляшешь под гирляндами до ночи, и дети ходят за тобой хвостом, за куклой."),
 ("M3_SH18","MAN_YOUNG","dressing_area","the young man counting a small stack of cash from a gig in a back room, the suit drying behind him","MCU","high","static","night",False,False,
  "платят гроши, сорок долларов за выход, но тебе не за деньги, тебе за эти четыре часа чужой любви."),
 ("M3_SH19","MAN_YOUNG","suburban_street","the thin young man walking home alone late at night, ordinary and unseen, a costume bag over his shoulder","WS","low","track","night",False,False,
  "ты идёшь домой один, с костюмом в сумке, и дома тебя никто не ждёт, но ты уже привык, тебе хватает."),
 ("M3_SH20",None,"mask_interior","the inside of the mascot head resting on a table, the eye-mesh dark, a faded photo not yet taped there","INSERT","top","push_in","night",False,False,
  "ты ещё не знаешь, что скоро в эту голову, у самой сетки, ты приклеишь фотографию, и не снимешь никогда."),
 ("M3_SH21","MASCOT","mall_atrium","the mascot waving goodbye to a crowd at the end of a long day, children waving back, warm light","MS","eye","static","dusk",False,False,
  "каждый вечер ты машешь толпе на прощание, и они машут кукле в ответ, и ты уносишь это тепло домой."),
 ("M3_SH22","MAN_YOUNG","dressing_area","close on the young man's tired happy face removing the head, hair plastered with sweat, content","CU","eye","push_in","dusk",False,False,
  "ты снимаешь голову, мокрый, счастливый, и думаешь, вот оно, я нашёл своё место в жизни, наконец."),
 ("M3_SH23",None,"mall_atrium","a bright empty mall stage after closing, a single spotlight, balloons drifting, the mascot gone","EWS","eye","pull_out","night",True,False,
  "ты не замечаешь только одного, что место это, и вся твоя жизнь в нём, будут внутри чужой головы."),
 ("M3_SH24","MASCOT","fairground","the plush mascot silhouetted against a lit ferris wheel at night, alone after the crowd has gone","WS","low","static","night",True,True,
  "огромная улыбающаяся кукла стоит одна под колесом обозрения, и внутри неё человек, которого никто не знает."),
 ("M3_SH25","MAN_YOUNG","fairground","the young man pulling the mascot head off under the fairground lights, alone, his real face finally tired","MCU","low","static","night",False,False,
  "ты стягиваешь голову в опустевшем парке, и ночной воздух холодит мокрое лицо, и тебе хорошо и пусто разом."),
 ("M3_SH26","MAN_YOUNG","fairground","close on the young man's quiet face under string lights at night, content and alone, the head under his arm","CU","eye","push_in","night",False,True,
  "двадцать лет, ярмарочные огни, и человек, нашедший, как быть любимым, не показывая своего лица."),
]

seed_act("cold_open",        PAL_BACK,  COLD, render_mode="animated")
seed_act("act01_invisible",  PAL_CHILD, A1,   render_mode="animated")
seed_act("act02_first_mask", PAL_GYM,   A2,   render_mode="animated")
seed_act("act03_first_mascot",PAL_MALL, A3,   render_mode="animated")
