# -*- coding: utf-8 -*-
"""donor A6 trying + A7 diagnosis. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_donor_A6A7.py"""
from _donor_engine import seed_act

P_TRY="fragile hopeful palette, warm domestic light thinning month by month into cold worry"
P_DIAG="grief-cold palette, sterile clinic light and a home going grey, warmth draining out for good"

TRY=[
 ("A6_SH01",None,"nika_flat","a wide establishing view of a modest flat set for a small quiet wedding, two rings on a table","WS","eye","push_in","day",True,False,
  "в тридцать один вы тихо расписываетесь, и ты веришь, что заслужила право на своего ребёнка."),
 ("A6_SH02","NIKA_MID","nika_flat","a medium shot of the woman and the man hopeful together at home, planning","MS","eye","static","day",False,False,
  "вы решаете завести малыша сразу, и первые месяцы ты ждёшь чуда с замиранием сердца."),
 ("A6_SH03","ANTON_BASE","nika_flat","a medium close-up of the man holding up tiny baby socks with a hopeful grin","MCU","eye","static","day",False,False,
  "антон покупает крошечные носочки заранее и говорит, что у вас будет девочка с твоими глазами."),
 ("A6_SH04",None,None,"an extreme close-up macro insert of a pair of tiny baby socks resting on a shelf, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "крошечные носочки лежат на полке и ждут, и каждый месяц ты смотришь на них с надеждой."),
 ("A6_SH05","NIKA_MID","nika_flat","a close-up of the woman's face falling as she looks at a single-line test","CU","eye","static","day",False,False,
  "но месяц за месяцем тест показывает одну полоску, и надежда медленно превращается в тревогу."),
 ("A6_SH06",None,"nika_flat","a wide view of a wall calendar with many dates circled in the modest flat","WS","eye","static","day",True,False,
  "ты снова начинаешь считать дни по календарю так же дотошно, как когда-то считала циклы."),
 ("A6_SH07","NIKA_MID","nika_flat","a medium shot of the woman sitting alone with a quiet mounting fear","MS","eye","static","night",False,False,
  "внутри поднимается страх, который ты не можешь объяснить мужу, потому что знаешь его причину."),
 ("A6_SH08","NIKA_MID","clinic_consult","a medium close-up of the woman alone at a clinic desk reading the doctor's face","MCU","eye","static","day",False,False,
  "ты тайком идёшь провериться и по лицу врача понимаешь, что новости будут очень плохими."),
 ("A6_SH09",None,"clinic_consult","an extreme close-up macro insert of an ultrasound monitor showing an almost empty dark field, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "на мониторе почти пусто там, где у молодой женщины должно быть много, и врач хмурится."),
 ("A6_SH10","NIKA_MID","clinic_consult","a close-up of the woman rising from the chair on unsteady legs, dread in her eyes","CU","eye","static","day",False,False,
  "тебе говорят прийти на большое обследование, и ты выходишь из кабинета на ватных ногах."),
 ("A6_SH11","ANTON_BASE","nika_flat","a medium shot of the man embracing the woman, reassuring her at home","MS","eye","static","night",False,False,
  "антон обнимает тебя и говорит, что всё дело в усталости и что нужно просто ещё подождать."),
 ("A6_SH12","NIKA_MID","nika_flat","a medium close-up of the woman with her face pressed to his shoulder, unable to speak","MCU","eye","static","night",False,False,
  "ты киваешь ему в плечо и не можешь выговорить, что тело своё ты, кажется, уже истратила."),
 ("A6_SH13",None,None,"an extreme close-up macro insert of a pale-blue enamel forget-me-not brooch held in an open palm, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","push_in","night",True,False,
  "ночью ты достаёшь из ящика брошку-незабудку и впервые за годы держишь её в своей ладони."),
 ("A6_SH14","NIKA_MID","nika_flat","a close-up of the woman staring at the brooch, a bitter irony in her face","CU","eye","static","night",False,False,
  "на эмали написано не забудь, а ты всю жизнь только и делала, что старалась всё забыть."),
 ("A6_SH15",None,"city_street","a wide panning view of a city through changing seasons, light thinning toward winter","WS","eye","pan_left","day",True,False,
  "проходит год, вы всё ещё пытаетесь, и каждый пустой месяц отнимает у Антона немного света."),
 ("A6_SH16","NIKA_MID","nika_flat","a medium shot of the couple sitting apart in the same room, a thin crack between them","MS","eye","static","night",False,False,
  "между вами появляется тонкая трещина, и проходит она ровно по твоей неназванной тайне."),
 ("A6_SH17","ANTON_BASE","nika_flat","a medium close-up of the man gently proposing they see a doctor together","MCU","eye","static","night",False,False,
  "антон предлагает пойти к врачу вместе, и ты в ужасе понимаешь, что скрывать больше нельзя."),
 ("A6_SH18","NIKA_MID","nika_flat","a close-up of the woman lying awake at night, cornered by the coming truth","CU","eye","static","night",False,False,
  "ты соглашаешься на общее обследование и всю неделю не спишь, ожидая, что всё раскроется."),
 ("A6_SH19",None,"clinic_corridor","a wide view of a pale clinic corridor with a row of empty chairs before a closed door","WS","eye","static","day",True,False,
  "в день результатов вы сидите в том же коридоре, где когда-то ты сдавала себя по частям."),
 ("A6_SH20","NIKA_MID","clinic_corridor","a medium shot of the woman holding the man's hand in the waiting corridor, her hand cold","MS","eye","static","day",False,False,
  "ты держишь Антона за руку, и твоя ладонь совсем холодная, потому что ты уже знаешь ответ."),
 ("A6_SH21",None,"clinic_consult","an extreme close-up macro insert of a closed results folder lying on a clinic desk, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,True,
  "на столе лежит закрытая папка с твоими результатами, и в ней вся правда о твоём теле."),
 ("A6_SH22","NIKA_MID","clinic_corridor","a medium close-up of the woman of thirty-two holding her husband's hand, praying she is wrong","MCU","eye","static","day",False,True,
  "тебе тридцать два, ты держишь мужа за руку и впервые в жизни молишься, чтобы ошиблась."),
]

DIAG=[
 ("A7_SH01",None,"doctor_office_bad","a wide establishing view of a sober doctor's office with two chairs facing a desk and a cold lightbox","WS","eye","push_in","day",True,False,
  "в тридцать три вы вдвоём заходите в кабинет, где вам должны сказать, будут ли у вас дети."),
 ("A7_SH02","VRACH_BASE","doctor_office_bad","a medium close-up of the grey-bearded doctor lowering his half-moon glasses over the folder","MCU","eye","static","day",False,False,
  "врач долго молчит над папкой, снимает очки-половинки и говорит, что новости очень тяжёлые."),
 ("A7_SH03","NIKA_MID","doctor_office_bad","a close-up of the woman sitting frozen as she hears the words","CU","eye","static","day",False,False,
  "ты сидишь неподвижно и слышишь слова ранний климакс так, будто их говорят вовсе не про тебя."),
 ("A7_SH04","ANTON_BASE","doctor_office_bad","a medium shot of the stunned man leaning forward, asking if there is a mistake","MS","eye","static","day",False,False,
  "антон переспрашивает, не ошибка ли это, ведь тебе всего тридцать три и ты всегда была здорова."),
 ("A7_SH05","VRACH_BASE","doctor_office_bad","a medium close-up of the doctor explaining gravely, choosing his words with care","MCU","eye","static","day",False,False,
  "врач объясняет, что твой запас исчерпан так, будто тело работало на пределе много лет подряд."),
 ("A7_SH06",None,"doctor_office_bad","an extreme close-up macro insert of a scan image on a cold lightbox showing an almost empty field, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,True,
  "он показывает снимок, где почти ничего не осталось, и спрашивает, не было ли у тебя стимуляций."),
 ("A7_SH07","NIKA_MID","doctor_office_bad","a close-up of the woman looking from the doctor to her husband, choosing the lie","CU","eye","push_in","day",False,False,
  "ты смотришь врачу в глаза, потом на Антона, и говоришь нет, никогда, ни разу в жизни."),
 ("A7_SH08","VRACH_BASE","doctor_office_bad","a medium close-up of the doctor holding a silence a beat too long, unconvinced","MCU","eye","static","day",False,False,
  "врач держит паузу чуть дольше, чем нужно, и ты понимаешь, что он тебе совсем не поверил."),
 ("A7_SH09","ANTON_BASE","doctor_office_bad","a medium shot of the devastated man taking her hand, blaming only bad luck","MS","eye","static","day",False,False,
  "антон берёт тебя за руку, думая, что вам обоим просто очень не повезло с судьбой."),
 ("A7_SH10","NIKA_MID","doctor_office_bad","a close-up of the woman carrying a double weight behind her still face","CU","eye","static","day",False,False,
  "ты несёшь сразу две тяжести, что своих детей не будет и что виновата в этом только ты."),
 ("A7_SH11",None,"clinic_corridor","a wide view of a pale clinic corridor as two figures walk away in silence","WS","eye","static","day",True,False,
  "вы выходите из клиники молча, и между вами уже стоит то, чего Антон никогда не узнает."),
 ("A7_SH12","NIKA_MID","nika_flat","a medium shot of the woman quietly boxing away the tiny socks from the shelf at home","MS","eye","static","day",False,False,
  "дома ты убираешь крошечные носочки с полки в коробку и прячешь её так же, как банку."),
 ("A7_SH13",None,None,"an extreme close-up macro insert of tiny baby socks being placed into a dark closing box, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "носочки, которые Антон купил заранее, ложатся в темноту рядом с тем, о чём ты молчишь."),
 ("A7_SH14","ANTON_BASE","nika_flat","a medium close-up of the man sitting alone and quiet with his chipped blue mug","MCU","eye","static","night",False,False,
  "антон становится тихим, много работает и подолгу сидит один со своей синей кружкой."),
 ("A7_SH15","NIKA_MID","nika_flat","a close-up of the woman opening her mouth to confess, then closing it again","CU","eye","static","night",False,False,
  "сто раз ты хочешь всё рассказать, но боишься, что он возненавидит тебя, и опять молчишь."),
 ("A7_SH16",None,"nika_flat","a wide view of the flat looking colder now, two chairs turned away from each other","WS","eye","static","night",True,False,
  "тёплый дом медленно остывает, и вы всё чаще спите спиной друг к другу в полной тишине."),
 ("A7_SH17","NIKA_MID","nika_flat","a medium shot of the couple in the same room but far apart, no longer speaking of the future","MS","eye","static","day",False,False,
  "вы перестаёте говорить о будущем, потому что будущее для вас теперь пустое и бездетное."),
 ("A7_SH18","ANTON_BASE","nika_flat","a medium close-up of the man saying quietly that he cannot do this anymore","MCU","eye","static","night",False,False,
  "однажды антон говорит, что так больше не может, что рядом с тобой ему невыносимо больно."),
 ("A7_SH19","NIKA_MID","nika_flat","a close-up of the woman letting him go without a word of the real reason","CU","eye","static","night",False,False,
  "ты не удерживаешь его и не объясняешь причину, потому что правда была бы ещё страшнее."),
 ("A7_SH20",None,None,"an extreme close-up macro insert of a chipped blue enamel mug left behind on a shelf by the door, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "он забирает книги, но синюю кружку почему-то забывает, и она остаётся стоять у двери."),
 ("A7_SH21","NIKA_MID","front_door","a medium shot of the woman at the door watching through the peephole as he descends","MS","eye","static","day",False,False,
  "ты смотришь в глазок, как он спускается по лестнице, и не выходишь его окликнуть."),
 ("A7_SH22",None,"nika_flat","a wide view of the emptied flat, bare walls and a single glass jar on a shelf","WS","eye","static","night",True,False,
  "квартира снова становится просто съёмными стенами, и в ней остаёшься только ты и банка."),
 ("A7_SH23","NIKA_MID","nika_flat","a medium close-up of the woman alone in the empty flat, knowing what she did","MCU","eye","static","night",False,False,
  "тебе тридцать три, ты одна, бездетна, и знаешь, что своими руками отдала свою семью."),
 ("A7_SH24","NIKA_MID","nika_flat","a close-up of the woman staring into the dark, thinking of the children out there","CU","eye","push_in","night",False,True,
  "а где-то в чужих городах в это время растут сорок с лишним детей, у которых твои глаза."),
]

if __name__=="__main__":
    seed_act("trying",    P_TRY, TRY, render_mode="static")
    seed_act("diagnosis", P_DIAG, DIAG, render_mode="static")
