# -*- coding: utf-8 -*-
"""webcam A0 cold_open + A1 origin. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_webcam_A0A1.py"""
from _webcam_engine import seed_act

P_COLD="hollow dark palette, dead monitor grey and faint magenta afterglow, deep night shadow"
P_ORIGIN="rising neon palette, poverty greys lit by fresh magenta and cyan ring-light glow, seductive and cheap"

COLD=[
 ("A0_SH01","HERO_OLD","stream_room","a tired woman of thirty-four sitting in a dark streaming room after a broadcast, a ring light just gone dark beside her","WS","eye","push_in","night",False,False,
  "тебе тридцать четыре, ты сидишь в тёмной комнате после стрима, и кольцевая лампа только что погасла."),
 ("A0_SH02","HERO_OLD","stream_room","a medium close-up of the woman still wearing a thin velvet choker with a small star, a made-up but weary face","MCU","eye","static","night",False,False,
  "на тебе всё ещё бархатный чокер со звёздочкой, костюм девушки по имени Алиса, которой на самом деле нет."),
 ("A0_SH03",None,None,"an extreme close-up macro insert of a dark cooling ring light on a stand in a dim room, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,False,
  "кольцевая лампа остывает в темноте, и её щелчок — единственный звук, который остался после эфира."),
 ("A0_SH04","HERO_OLD","stream_room","a close-up of the woman counting the night's earnings on a phone, disappointment on her face","CU","eye","static","night",False,False,
  "ты пересчитываешь донаты за ночь и понимаешь, что их всё меньше, а тебя всё меньше хотят."),
 ("A0_SH05","HERO_OLD","bedroom_dark","a medium shot of the woman glancing toward a wall behind which a child sleeps, guarded and tired","MS","eye","static","night",False,False,
  "за стеной спит твоя дочь Лиза, и она не должна узнать, чем ты зарабатываешь на её жизнь."),
 ("A0_SH06",None,None,"an extreme close-up macro insert of a glass jar of crumpled cash and coins on a desk, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "в банке на столе мятые купюры и мелочь, и это меньше, чем ты тратишь на свет и грим."),
 ("A0_SH07",None,"bedroom_dark","a wide view of a dark quiet apartment room lit only by a dead monitor's faint glow, still and silent","WS","eye","pan_left","night",True,False,
  "квартира тёмная и тихая, экран погас, и ни одного дзынь, к которому ты так привыкла."),
 ("A0_SH08","HERO_OLD","stream_room","a medium close-up of the woman alone in the dark, a lifetime of performance behind her eyes","MCU","eye","static","night",False,False,
  "пятнадцать лет ты улыбалась в камеру для тысяч чужих мужчин, а рядом сейчас нет ни одного."),
 ("A0_SH09","HERO_OLD","stream_room","a close-up of the woman's worn face, abandoned by everyone who watched her","CU","eye","push_in","night",False,False,
  "тысячи людей писали, что любят тебя, и ни один не пришёл, когда лампа погасла навсегда."),
 ("A0_SH10","HERO_OLD","stream_room","a medium shot of the woman remembering, the dim room around her","MS","eye","static","night",False,False,
  "в девятнадцать тебе казалось, что это лёгкие деньги, свобода и внимание, о котором ты мечтала."),
 ("A0_SH11",None,"stream_room","a wide view of a streaming room with a ring light, a webcam on a tripod and a fairy-light backdrop, dim and staged","WS","eye","static","night",True,False,
  "кольцевая лампа, вебкамера, кровать с гирляндой, всё это когда-то было твоей маленькой сценой."),
 ("A0_SH12",None,None,"an extreme close-up macro insert of a thin velvet choker with a small star pendant held in fingers, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","push_in","night",True,False,
  "ты трогаешь чокер на шее и думаешь, кем ты стала, пока играла эту чужую весёлую девочку."),
 ("A0_SH13","HERO_OLD","stream_room","a medium close-up of the woman of thirty-four turning to face the viewer in the faint glow","MCU","eye","push_in","night",False,False,
  "если хочешь понять, как быстрые деньги в камеру забирают всю жизнь, останься со мной до конца."),
 ("A0_SH14","HERO_OLD","stream_room","a close-up of the woman looking directly at the viewer, worn and honest","CU","eye","push_in","night",False,True,
  "подпишись, и я покажу тебе всё с самого начала, пока свет ещё горит и на тебя смотрят."),
]

ORIGIN=[
 ("A1_SH01",None,"city_street_neon","a wide establishing view of a wet neon city street at night, magenta and cyan signs reflected in puddles, cold and lonely","WS","low","push_in","night",True,False,
  "пятнадцать лет назад тебе девятнадцать, ты в чужом большом городе, учишься и живёшь впроголодь."),
 ("A1_SH02","HERO_YOUNG","poor_flat","a medium shot of a pretty platinum-blonde girl of nineteen in a cramped cheap student flat, tired and broke","MS","eye","static","day",False,False,
  "ты снимаешь угол, тянешь учёбу и подработку официанткой, но денег не хватает даже на еду."),
 ("A1_SH03","HERO_YOUNG","poor_flat","a close-up of the young woman's pretty desperate face in the dim flat","CU","eye","push_in","day",False,False,
  "ты красивая, молодая и в отчаянии, и это именно то сочетание, на котором зарабатывают другие."),
 ("A1_SH04","PODRUGA_BASE","poor_flat","a medium close-up of a sharp jaded woman of thirty with a jet-black bob and a vape pen, showing a phone screen","MCU","over","static","day",False,False,
  "однажды знакомая по имени Рита показывает тебе телефон и говорит, что камера платит куда больше подноса."),
 ("A1_SH05",None,None,"an extreme close-up macro insert of a phone screen glowing with high earnings figures, numbers unreadable, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "на экране суммы за один вечер больше, чем ты получаешь за месяц беготни с тарелками."),
 ("A1_SH06","HERO_YOUNG","poor_flat","a close-up of the young woman torn, tempted despite herself","CU","eye","static","day",False,False,
  "ты говоришь, что никогда, что это стыдно, а вечером не можешь перестать думать про эти суммы."),
 ("A1_SH07",None,"poor_flat","a wide view of a cold cheap student flat with unpaid papers on a desk, dim ordinary light","WS","eye","static","day",True,False,
  "в холодной съёмной комнате ты считаешь долги за учёбу и понимаешь, что тонешь всё глубже."),
 ("A1_SH08","PODRUGA_BASE","poor_flat","a medium shot of the jaded woman reassuring the girl, gesturing casually with a vape pen","MS","over","static","day",False,False,
  "Рита говорит, что это просто шоу, что можно не раздеваться, что ты сама решаешь границы."),
 ("A1_SH09","HERO_YOUNG","poor_flat","a close-up of the young woman rationalizing the decision to herself","CU","eye","push_in","day",False,False,
  "ты убеждаешь себя, что попробуешь один раз, только чтобы закрыть долг, и на этом остановишься."),
 ("A1_SH10","HERO_YOUNG","stream_room","a medium shot of the young woman setting up a ring light and a webcam, turning her corner into a little studio","MS","eye","static","night",False,False,
  "ты покупаешь в кредит кольцевую лампу и вебкамеру и превращаешь свой угол в маленькую студию."),
 ("A1_SH11",None,None,"an extreme close-up macro insert of a hand clicking a ring light switch as it floods on with white light, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,False,
  "ты щёлкаешь выключателем, и кольцевая лампа заливает лицо ровным белым светом, как на допросе."),
 ("A1_SH12","HERO_YOUNG","stream_room","a medium close-up of the young woman in the flat ring-light glow, a bright staged smile settling over her real face","MCU","eye","static","night",False,False,
  "в этом свете ты перестаёшь быть Настей и становишься Алисой, весёлой и доступной для всех."),
 ("A1_SH13",None,None,"an extreme close-up macro insert of a thin velvet choker with a small star being fastened at a throat, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,False,
  "ты застёгиваешь на шее тонкий бархатный чокер со звёздочкой, и это твой первый костюм."),
 ("A1_SH14","HERO_YOUNG","stream_room","a medium shot of the clothed young woman going live at the webcam, hands trembling, the room empty of viewers","MS","eye","static","night",False,False,
  "ты включаешь эфир, руки дрожат, и первые минуты в комнату не заходит вообще никто."),
 ("A1_SH15","HERO_YOUNG","stream_room","a close-up of the young woman smiling into an empty camera, feeling foolish","CU","eye","static","night",False,False,
  "ты улыбаешься в пустоту, чувствуешь себя глупо и уже почти решаешь всё выключить."),
 ("A1_SH16",None,None,"an extreme close-up macro insert of a glowing screen showing a first tip notification lighting up, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,True,
  "и вдруг раздаётся первый дзынь, кто-то прислал тебе донат, и сердце подпрыгивает от радости."),
 ("A1_SH17","HERO_YOUNG","stream_room","a medium close-up of the young woman's face lighting up with a genuine smile at being noticed","MCU","eye","push_in","night",False,False,
  "ты улыбаешься уже искренне, потому что тебя заметили, и этот звук мгновенно становится наградой."),
 ("A1_SH18","HERO_YOUNG","stream_room","a medium shot of the young woman at dawn with a jar of cash beside the cooling ring light","MS","eye","static","night",False,False,
  "к утру в банке из-под кофе лежит больше, чем ты выносила подносов за две недели смен."),
 ("A1_SH19",None,None,"an extreme close-up macro insert of hands counting crumpled cash into a jar at dawn, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "ты пересчитываешь купюры на рассвете и не веришь, что это оказалось так просто и так быстро."),
 ("A1_SH20",None,"city_street_neon","a wide view of a neon city street fading into pale dawn, quiet and empty","WS","eye","tilt_up","day",True,False,
  "за окном светает над чужим городом, а ты впервые за год не думаешь, чем платить за жильё."),
 ("A1_SH21","HERO_YOUNG","poor_flat","a medium close-up of the young woman telling herself it is only temporary","MCU","eye","static","day",False,False,
  "ты говоришь себе, что это временно, только пока не встанешь на ноги, только до конца учёбы."),
 ("A1_SH22","HERO_YOUNG","stream_room","a close-up of the young woman already craving the next broadcast, the chime echoing in her head","CU","eye","push_in","night",False,False,
  "но звук доната уже поселился в тебе, и ты весь день ждёшь вечера, чтобы услышать его снова."),
 ("A1_SH23",None,"stream_room","a wide view of a ring light waiting in the corner of a small room, a webcam and fairy lights, quietly ominous","WS","eye","static","night",True,False,
  "кольцевая лампа стоит в углу и ждёт, и кажется, что это просто подработка, а не капкан."),
 ("A1_SH24","HERO_YOUNG","stream_room","a close-up of the platinum-blonde girl of nineteen, delighted with easy money, unaware of the price","CU","eye","push_in","night",False,True,
  "тебе девятнадцать, ты нашла лёгкие деньги, и ещё не знаешь, какой длинный за них счёт."),
]

if __name__=="__main__":
    seed_act("cold_open", P_COLD, COLD, render_mode="animated")
    seed_act("origin",    P_ORIGIN, ORIGIN, render_mode="animated")
