# -*- coding: utf-8 -*-
"""layoff act A5 catastrophe (переговорка, подпись, мёртвый турникет, коробка). PYTHONIOENCODING=utf-8 python scripts/_seed_layoff_A5.py"""
from _layoff_engine import seed_act
PAL="cold final palette, hard grey-blue and bleached white, flat merciless fluorescent light, sharp thin shadows"
S=[
 ("A5_SH01","GEROY_MAIN","turnstile_lobby","an extreme close-up of the man pressing his access card to the turnstile reader, a normal green light, an ordinary morning","ECU","eye","static","morning",False,False,
  "в то утро ты как всегда прикладываешь пропуск, загорается зелёный, и турникет пускает тебя в последний раз."),
 ("A5_SH02",None,"open_floor","a wide view of the familiar open office floor in the morning, ordinary and unaware","WS","eye","static","morning",True,False,
  "ты идёшь по знакомому этажу, киваешь охране и коллегам, и всё выглядит как любой другой рабочий день."),
 ("A5_SH03","GEROY_MAIN","open_floor","a medium shot of the man at his desk as an unseen colleague leans in to tell him something, his stomach dropping","MS","eye","static","day",False,False,
  "у твоего стола кто-то говорит, что тебя ждут в стеклянной переговорке, и внутри у тебя всё опускается."),
 ("A5_SH04","GEROY_MAIN","glass_meeting","a wide shot of the man entering the glass meeting room where the HR woman and the boss sit with a folder","WS","eye","static","day",False,False,
  "ты заходишь, видишь элю и начальника за столом и ту самую папку, и понимаешь всё ещё до первого слова."),
 ("A5_SH05","ELYA_BASE","glass_meeting","a medium close-up of the blonde HR woman sliding a single sheet across the table, tablet in hand, polite and cool","MCU","eye","static","day",False,False,
  "эля привычно вежливо двигает к тебе лист и произносит слово оптимизация, как будто речь о чужом столе."),
 ("A5_SH06",None,"glass_meeting","a macro insert of a termination agreement sheet on the table, a printed severance figure visible on it","INSERT","top","static","day",True,False,
  "на листе написано соглашение о расторжении и сумма выходного пособия — три твоих оклада за девятнадцать лет."),
 ("A5_SH07","GEROY_MAIN","glass_meeting","a close-up of the man's stunned face as he registers the number","CU","eye","push_in","day",False,False,
  "ты слышишь эту цифру и считаешь в уме, что это меньше, чем ты приносил конторе за один квартал."),
 ("A5_SH08","BOSS_BASE","glass_meeting","a medium shot of the balding boss looking down at the table, unable to meet the man's eyes","MS","eye","static","day",False,False,
  "начальник смотрит в стол и не поднимает на тебя глаз, и это говорит тебе больше, чем все её слова."),
 ("A5_SH09","GEROY_MAIN","glass_meeting","an extreme close-up of the man's hand resting on the access card, then reaching for the offered pen","ECU","eye","static","day",False,False,
  "твоя рука в последний раз ложится на пропуск, а потом сама берёт протянутую ручку."),
 ("A5_SH10",None,"glass_meeting","a macro insert of a signature being completed on the empty line of the agreement","INSERT","top","static","day",True,True,
  "ты ставишь подпись в том самом пустом поле, и девятнадцать лет умещаются в одну короткую строчку."),
 ("A5_SH11","ELYA_BASE","glass_meeting","a medium close-up of the HR woman explaining calmly, gesturing toward the access card","MCU","eye","static","day",False,False,
  "эля поясняет, что пропуск перестанет работать в шесть вечера и что карту нужно сдать на выходе."),
 ("A5_SH12","GEROY_MAIN","open_floor","a wide shot of the man walking back across the too-quiet office floor, colleagues looking away","WS","eye","static","day",False,False,
  "ты возвращаешься к своему столу через слишком тихий этаж, и коллеги смотрят куда угодно, только не на тебя."),
 ("A5_SH13",None,"your_desk","a macro insert of an empty cardboard box waiting on an office chair at a desk","INSERT","top","static","day",True,False,
  "на твоём стуле уже ждёт пустая картонная коробка, которую кто-то заботливо принёс заранее."),
 ("A5_SH14","GEROY_MAIN","your_desk","a medium close-up of the man packing a chipped mug and a framed photo into the cardboard box","MCU","eye","static","day",False,False,
  "ты складываешь в неё треснувшую кружку и фотографию жены, и вся твоя контора помещается в один короб."),
 ("A5_SH15","GEROY_MAIN","your_desk","a close-up of the man's hands lowering the family photo gently on top of the papers in the box","CU","top","static","day",False,True,
  "твои руки бережно опускают семейное фото поверх бумаг, будто это единственное, что здесь было настоящим."),
 ("A5_SH16","REPL_BASE","open_floor","a medium shot of the young undercut replacement with white earbuds glancing over at the desk, already measuring it","MS","eye","static","day",False,False,
  "молодой сменщик в наушниках уже косится на твой стол, прикидывая, как переставит монитор."),
 ("A5_SH17","GEROY_MAIN","open_floor","a wide shot of the man carrying the cardboard box down the rows of desks, the seated colleagues staying in their chairs with eyes lowered","WS","eye","track","day",False,False,
  "ты несёшь коробку вдоль рядов, и ни один из тех, кого ты учил, не встаёт, чтобы пожать тебе руку."),
 ("A5_SH18","GEROY_MAIN","turnstile_lobby","an extreme close-up of the man tapping his card to the turnstile reader, the light glowing hard red","ECU","eye","static","day",False,True,
  "у турникета ты по привычке прикладываешь пропуск, и впервые за девятнадцать лет загорается красный."),
 ("A5_SH19","GEROY_MAIN","turnstile_lobby","a medium shot of the man standing at the locked turnstile with the box in his arms, the gate refusing him","MS","eye","static","day",False,False,
  "ты стоишь перед закрытым турникетом с коробкой в руках, и створки больше не думают тебя впускать."),
 ("A5_SH20",None,"turnstile_lobby","a macro insert of the turnstile card reader glowing steady red, dark and silent, no green light","INSERT","eye","static","day",True,False,
  "сканер горит ровным красным, и там, где двадцать лет звучал короткий писк, теперь только тишина."),
 ("A5_SH21","GEROY_MAIN","turnstile_lobby","a close-up of the man dropping the access card into a plastic security tray, his hand left empty","CU","top","static","day",False,True,
  "ты опускаешь карту в пластиковый лоток охраны, и твоя рука впервые за годы остаётся совсем пустой."),
 ("A5_SH22","GEROY_MAIN","street_tower","an extreme wide view of the small lone man holding a cardboard box on the pavement at the foot of the huge glass tower","EWS","low","static","day",False,True,
  "стеклянные двери выпускают тебя на улицу, и ты стоишь под огромной башней совсем один, с коробкой в руках."),
]
if __name__=="__main__": seed_act("catastrophe", PAL, S, render_mode="animated")
