# -*- coding: utf-8 -*-
"""shuttle atmosphere breathers — act tails A1..A10, id_region='a'. §5.1a unique schemes per act, all with VO.
PYTHONIOENCODING=utf-8 python scripts/_seed_shuttle_atmo.py"""
from _shuttle_engine import seed_act

ACTS=[
 ("nii",1,"stalled institute palette, dusty drafting grey and winter window blue, one warm desk lamp of habit",[
  ("a wide view of the institute facade with half its windows dark on a working afternoon","WS","eye","push_in","day",
   "институт стоит красивый и пустеющий, и вахтёрша вяжет на проходной уже третий свитер."),
  ("an extreme close-up insert of a drafting table with a perfect unfinished drawing under dust","ECU","top","static","day",
   "твой последний чертёж так и остаётся неподписанным, и ты иногда его вспоминаешь."),
  ("a medium view of the kitchen shelf of counted jars, labels turned neatly outward","MS","eye","static","evening",
   "запасы у матери посчитаны и подписаны, и голод в этот дом не проходит дальше прихожей."),
  ("a wide view of the yard with grandmothers on the bench watching children around the swings","WS","eye","static","day",
   "двор живёт по-старому: лавочка всё видит, всё знает и почти не осуждает."),
  ("an extreme close-up insert of a child's drawing of a bus taped over a school desk","ECU","eye","static","evening",
   "Лена рисует автобусы задолго до того, как поймёт, куда они увозят маму."),
  ("a medium view of the lamplit kitchen table with the trip budget squared away in columns","MS","high","static","night",
   "смета готова, заём согласован, и остаётся только сделать первый шаг до автовокзала."),
 ]),
 ("first_run",2,"first-run palette, night highway blues breaking into Laleli lamp gold, nervous and alive",[
  ("an extreme close-up insert of a highway kilometre post flashing past a bus window","ECU","eye","static","night",
   "дорога до Стамбула — это тысяча восемьсот километров и два государственных флага."),
  ("a wide view of a roadside stop at night, a lit kiosk and a row of stretching passengers","WS","eye","static","night",
   "на стоянках все выходят размяться, и водитель считает пассажиров по головам, как детей."),
  ("a medium view of Laleli side street with hand-carts parked in a patient row","MS","eye","static","day",
   "тележечники здесь работают семьями, и твой груз возят отец и сын, молча и точно."),
  ("a wide view of the Bosphorus glimpsed between wholesale buildings, gulls over the water","WS","eye","static","day",
   "море ты видишь один раз, мельком, между рядами, и обещаешь себе вернуться сюда туристкой."),
  ("an extreme close-up insert of a first sold-out stall table, bare boards swept clean","ECU","top","static","evening",
   "к закрытию у тебя остаётся пустой прилавок, и пустой прилавок — лучший вид на свете."),
  ("a medium view of the kitchen with the girl asleep against her mother's shoulder over homework","MS","eye","static","night",
   "Лена засыпает на твоём плече над прописями, и ради этого плеча всё и затевалось."),
 ]),
 ("market",3,"market winter palette, steel stall grey and breath steam warmed by jacket leather browns",[
  ("a wide view of the market opening in half-dark, tarpaulins coming off in synchronised motion","WS","eye","push_in","dawn",
   "рынок просыпается в шесть, и брезенты снимают синхронно, как парус на регате."),
  ("a medium view of a stall counter made of a plaid bag laid flat, goods squared on it","MS","high","static","day",
   "прилавок из сумки — это стиль сезона, и твой всегда самый ровный в ряду."),
  ("an extreme close-up insert of a cash apron pocket with notes sorted by size","ECU","top","static","day",
   "купюры в фартуке разложены по достоинству, и рука находит нужную не глядя."),
  ("a wide view of the row at lunch, thermoses steaming on stall corners down the line","WS","eye","pan_right","day",
   "в полдень над рядом поднимается пар от семи термосов, и это общий обеденный гудок."),
  ("an extreme close-up insert of a first patch being sewn onto plaid fabric with double thread","ECU","eye","push_in","evening",
   "первая заплатка на сумке — от ножа в толкучке, и шов у тебя ровнее раны."),
  ("a medium view of the empty evening stop with one figure and two bags under the timetable","MS","eye","static","evening",
   "с рынка ты уезжаешь последним автобусом, и остановка знает твоё расписание лучше семьи."),
 ]),
 ("kidok",4,"pre-holiday betrayal palette, festive Laleli gold cut by shuttered-steel grey, cold inside warm",[
  ("an extreme close-up insert of holiday lights strung over a wholesale row","ECU","low","static","evening",
   "перед праздниками весь Лалели наряжается гирляндами лампочек, и торговля идёт до самой темноты."),
  ("a medium view of the bus luggage bay packed to the door with plaid pyramids","MS","eye","static","night",
   "багажник автобуса собирают, как тетрис, и твоя пустая сумка занимает позорно мало места."),
  ("a wide view of the home market under first snow, stalls trading through the white","WS","eye","static","day",
   "снег рынку не помеха: над рядами натягивают плёнку, и торговля идёт под хруст."),
  ("an extreme close-up insert of a doll in holiday wrapping beside mandarins on a table","ECU","top","static","night",
   "кукла для Лены куплена ещё в сентябре, до кидка, и это твоя маленькая победа."),
  ("a medium view of the ledger open to a circled negative line, a pencil laid across it","MS","high","static","night",
   "минусовую строку ты не вырываешь и не замазываешь: пусть учит, раз уж заплачено."),
  ("a wide view of the January market row, thin but alive, breath steaming over the stalls","WS","eye","pull_out","day",
   "январь вы перезимовываете всем рядом вместе, в складчину на чай и на оптимизм."),
 ]),
 ("border",5,"checkpoint palette, floodlight white on concrete blue, breath steam and long shadows, tense",[
  ("a medium view of the bus queue at the checkpoint, engines idling, breath and exhaust mixing","MS","eye","static","night",
   "на границе время меряют автобусами: два впереди — это часа полтора, если повезёт."),
  ("an extreme close-up insert of a passport with a fan of worn stamps across the page","ECU","top","static","night",
   "штампов в твоём паспорте больше, чем страниц, и каждый — это шестьдесят килограммов."),
  ("a wide view of the inspection lane at three a.m., steel tables shining under floodlights","WS","eye","static","night",
   "в три ночи бетон под прожекторами белый, как операционная, и такой же неласковый."),
  ("an extreme close-up insert of a chalk mark being drawn on a checked bag side","ECU","eye","static","night",
   "меловая галочка на боку сумки означает «проверено», и ты бережёшь её до дома."),
  ("a medium view of the dawn highway beyond the windscreen, the sun low over the fields","MS","pov","static","dawn",
   "после границы водитель включает старую кассету, и салон подпевает шёпотом, не просыпаясь."),
  ("a wide view of the home bus station at evening, one bus unloading plaid pyramids","WS","eye","static","evening",
   "автовокзал встречает вас носильщиками и таксистами, и все знают, что рейс — стамбульский."),
 ]),
 ("daughter",6,"waiting-child palette, school-concert warmth and window-lamp amber against highway dark",[
  ("an extreme close-up insert of a school notebook margin dense with doodled buses","ECU","top","static","evening",
   "на полях Лениных тетрадей едут автобусы, и учительница делает вид, что не видит."),
  ("a wide view of the school corridor with coat racks and one small figure waiting at a window","WS","eye","static","day",
   "после уроков Лена ждёт бабушку у окна, и окно выходит на дорогу."),
  ("a medium view of a grandmother and granddaughter baking at the kitchen table, flour in the lamplight","MS","eye","static","evening",
   "по субботам они пекут пироги, и половину всегда откладывают «маме на приезд»."),
  ("an extreme close-up insert of a postcard with a funny drawn face pinned over a child's desk","ECU","eye","static","day",
   "твои открытки Лена вешает над столом, и к весне над столом целый автопарк."),
  ("a medium view of the yard in summer dusk, a hopscotch grid chalked by the entrance","MS","high","static","evening",
   "классики у подъезда расчерчены её рукой, тем же ровным почерком, что у тебя."),
  ("a wide view of the fourth-floor window lit yellow over the darkening courtyard","WS","low","static","night",
   "окно на четвёртом горит до девяти, и по нему во дворе сверяют часы."),
 ]),
 ("default98",7,"crisis palette, exchange-board red on newsprint grey, one steady pencil line through the panic",[
  ("a wide view of a bank branch with a handwritten notice taped inside the glass door","WS","eye","static","day",
   "банки вывешивают объявления от руки, и очередь читает их молча, уже не удивляясь."),
  ("an extreme close-up insert of a price tag rewritten three times, erasures visible","ECU","eye","static","day",
   "на ценнике видны три слоя цифр, и это летопись осени девяносто восьмого."),
  ("a medium view of the market row sharing one radio, heads tilted toward the news","MS","eye","static","day",
   "новости слушают всем рядом из одного приёмника, и после новостей работают дальше."),
  ("a wide view of the market at dusk with gaps in the rows like missing teeth","WS","eye","pan_left","evening",
   "пустые места в рядах стоят до весны, и весной их займут новые люди."),
  ("an extreme close-up insert of the oilcloth ledger balanced against a scale weight","ECU","top","static","night",
   "клеёнчатая тетрадь оборота становится семейной реликвией раньше, чем ты успеваешь это заметить."),
  ("a medium view of three stalls under one hand, tarpaulins rolled in identical neat tubes","MS","eye","static","dawn",
   "три места открываются теперь одной рукой, и рука эта встаёт в пять тридцать."),
 ]),
 ("kiosk",8,"settled-trade palette, kiosk lamp amber against bus-stop winter blue, small warm plenty",[
  ("a wide view of the bus stop and kiosk in morning rush, trolleybus wires over the scene","WS","eye","push_in","day",
   "остановка кормит ларёк, ларёк греет остановку, и вместе они — целый маленький мир."),
  ("an extreme close-up insert of a heater coil glowing beside a stool leg","ECU","eye","static","day",
   "обогреватель в ларьке — роскошь, о которой на рынке ты не смела мечтать."),
  ("a medium view of the kiosk interior with goods in strict size order on the shelves","MS","eye","static","day",
   "товар на полках стоит по размерам и цветам, и покупатели говорят: у вас как в аптеке."),
  ("an extreme close-up insert of a lunch container open beside a thermos cap of tea","ECU","top","static","day",
   "мамин суп в судочке — это ежедневный праздник, и ты ешь его, не закрывая окошка."),
  ("a wide view of the evening street with the kiosk shutter down and lamplight on the snow","WS","eye","static","night",
   "после восьми на остановке остаётся только фонарь, и он честно дорабатывает смену."),
  ("a medium view of the old plaid bag resting folded on a mezzanine shelf edge","MS","low","static","night",
   "сумка на антресоли слышит, как ты приходишь в восемь тридцать, а не в полночь."),
 ]),
 ("store",9,"earned-respect palette, washed shop daylight over ordered racks, one hard cold conversation in it",[
  ("an extreme close-up insert of a cash register receipt curling out crisp and long","ECU","eye","static","day",
   "кассовый аппарат печатает чеки с названием «Вера», и первый чек ты заламинировала."),
  ("a wide view of the shop windows washed to invisibility, daylight deep into the racks","WS","eye","static","day",
   "окна ты моешь до невидимости, потому что свет — лучший продавец одежды."),
  ("a medium view of two assistants steaming jackets in the back corner, methodical and calm","MS","eye","static","day",
   "продавщиц ты учишь, как Валя учила тебя: с кем дружить и как считать."),
  ("an extreme close-up insert of a plaid keepsake shelf above an office door","ECU","low","static","day",
   "над дверью кабинета полка с клетчатой сумкой, и новенькие спрашивают, что это за экспонат."),
  ("a medium view of the fitting corner curtain drawn, shoes waiting outside it","MS","eye","static","day",
   "в примерочную выстраивается очередь, и ты подаёшь размеры через штору, как медсестра."),
  ("a wide view of the street at closing time, the shop sign lit warm over the pavement","WS","low","static","evening",
   "вывеска «Вера» горит до девяти, и по ней теперь сверяет часы уже вся улица."),
 ]),
 ("mend",10,"mending palette, graduation spring light and shop lamp gold, warmth returning by degrees",[
  ("a wide view of the spring street with graduates in gowns crossing toward a photographer","WS","eye","push_in","day",
   "в городе выпускной сезон, и фотографы работают у фонтана посменно, как на конвейере."),
  ("an extreme close-up insert of a framed first-takings note beside a wooden comb in a till drawer","ECU","top","static","day",
   "в кассе магазина лежат первая выручка и бабушкин гребень, и оба приносят удачу."),
  ("a medium view of mother and daughter unpacking boxes together in the stockroom","MS","eye","static","day",
   "в подсобке вы работаете в четыре руки, и коробки заканчиваются быстрее разговоров."),
  ("a wide view of the shop at Saturday noon, full and easy, a dog waiting by the door","WS","eye","static","day",
   "по субботам в магазине смена из двух поколений, и постоянные приходят именно на неё."),
  ("an extreme close-up insert of two identical neat handwritings side by side in one ledger","ECU","top","static","night",
   "в новой тетради две руки: твоя и Ленина, и почерк у вас теперь не различить."),
  ("a medium view of the courtyard bench at dusk with a folded shawl and quiet swings","MS","eye","static","evening",
   "лавочка во дворе стоит на месте, и вы с Леной сидите на ней теперь за бабушку."),
 ]),
]

if __name__=="__main__":
    for sk,ai,pal,items in ACTS:
        shots=[("A%d_SZ5%d"%(ai,i+1), None, None, subj, st, ang, mv, tod, True, False, narr)
               for i,(subj,st,ang,mv,tod,narr) in enumerate(items[:4])]  # max 4 per act tail (user 2026-07-04)
        seed_act(sk, pal, shots, render_mode="static", id_region="a")
