# -*- coding: utf-8 -*-
"""teacher acts: last_bell (2024, 32 shots) + coda (2026, 20 shots). Static.
Run: PYTHONIOENCODING=utf-8 python scripts/_seed_teacher_A10A11.py"""
from _teacher_engine import seed_act

PAL10="farewell palette of balloon red, gilt frame gold, thin autumn sun and cardboard-box brown"
LASTBELL=[
("A10_SH01",None,"teachers_room",
 "the staff room in spring twenty twenty-four, flattened cardboard boxes leaning by the trophy cabinet, the wall timetable board half-stripped of its paper slips",
 "WS","eye","static","day",True,False,
 "весной двадцать четвёртого в учительской появляются коробки, слово оптимизация оказалось про вас."),
("A10_SH02","LIDA_OLD","teachers_room",
 "the teacher of fifty-six listening at the staff meeting, hands folded on the green baize, her face still while younger colleagues argue around the long table",
 "MCU","eye","static","day",False,False,
 "вашу школу сливают с новой за проспектом, и в новом расписании твоих часов не находится.",
 "her folded hands very still on the baize, arguing voices moving around her stillness, her eyes level"),
("A10_SH03","LIDA_OLD","teachers_room",
 "a school official's hands sliding a paper across the green baize, an older hand holding folded reading glasses beside it, not reaching for the page",
 "INSERT","top","static","day",False,False,
 "тебе объясняют мягко, до пенсии вам два года, лидия андреевна, вы же понимаете.",
 "the paper sliding to a stop before her, her folded glasses tapping the baize once, twice"),
("A10_SH04","LIDA_OLD","classroom_hers_2010s",
 "the teacher alone in her classroom after the meeting, standing at the window with her forehead almost touching the glass, the maple's crown filling the pane",
 "MS","eye","static","evening",False,False,
 "ты стоишь у окна своего класса и считаешь не потери, а выпуски, их тридцать четыре.",
 "her breath fogging a small circle on the pane, the maple's crown swaying gently beyond the glass"),
("A10_SH05","LIDA_OLD","classroom_hers_2010s",
 "the teacher emptying her desk drawers into a cardboard box, a strata of decades emerging, postcards, a tin pencil case, bundled letters, dried flowers pressed flat",
 "MS","high","static","day",False,False,
 "ящики твоего стола отдают археологию, открытки, письма и гербарий из подаренных букетов.",
 "her hands lifting layer after layer from the drawer, pausing over a postcard, laying it in the box"),
("A10_SH06",None,"classroom_hers_2010s",
 "an open cardboard box holding a tin pencil case, bundles of pupils' letters tied with thread, a class photograph fan spread across decades of faces",
 "INSERT","top","static","day",True,False,
 "в одной коробке помещаются девяносто первый, девяносто восьмой, две тысячи шестой и все остальные."),
("A10_SH07","LIDA_OLD","classroom_hers_2010s",
 "the teacher finding the old squared-paper plan at the bottom of the last drawer, unfolding it by the window, its pencil dates faded to ghosts",
 "CU","eye","static","day",False,True,
 "на дне последнего ящика лежит листок в клетку, и обе даты на нём выцвели до теней.",
 "the soft paper unfolding along worn creases, her thumb smoothing the faded pencil ghosts"),
("A10_SH08","LIDA_OLD","classroom_hers_2010s",
 "the teacher folding the old plan and slipping it into the cardboard box between pupils' letters, her face closing the subject gently",
 "MCU","eye","static","day",False,False,
 "ты складываешь его к детским письмам, потому что там ему, честно говоря, и место.",
 "the folded plan sliding between letter bundles, her palm pressing the layer flat, the box flap closing"),
("A10_SH09",None,"assembly_hall",
 "the school assembly hall dressed for a last-bell ceremony, garlands of paper flowers and red balloons along the stage, folding seats filling with families, morning sun through thin curtains",
 "WS","eye","pan_right","morning",True,False,
 "последний звонок этой школы назначают на двадцать пятое мая, и зал не вмещает всех желающих."),
("A10_SH10","LIDA_OLD","assembly_hall",
 "the teacher seated in the front row of the ceremony in her formal jacket, her class of graduates in sashes ranged on the stage above her",
 "MS","low","static","morning",False,False,
 "твой одиннадцатый стоит на сцене в лентах, тридцать первый выпуск и последний в этих стенах.",
 "the sashed graduates shifting proudly on the stage, her face lifting to them from the front row"),
("A10_SH11","OBJ:brass_bell",None,
 "a small brass hand bell with a red ribbon bow held high in a first-grader's fist against stage lights, mid-swing, ribbon flying",
 "ECU","low","static","morning",False,True,
 "первоклассница на плече выпускника звонит в тот самый латунный звонок семьдесят пятого года."),
("A10_SH12","LIDA_OLD","assembly_hall",
 "the teacher listening to the bell with her eyes closed for one second, the hall soft around her, her thumb finding the amber ring",
 "CU","eye","static","morning",False,True,
 "ты закрываешь глаза на один звон, и пятьдесят один год умещается в нём целиком.",
 "her eyelids lowering slowly, her thumb pressing the amber ring, the hall's light trembling on her face"),
("A10_SH13","LIDA_OLD","assembly_hall",
 "the school director at the lectern reading from a folder, gesturing the teacher up to the stage, applause beginning in the packed hall",
 "WS","eye","static","day",False,False,
 "тебя вызывают на сцену со словами тридцать четыре года безупречного труда, и зал встаёт.",
 "her name carrying from the lectern, rows of families rising into applause, her hand finding the seat back"),
("A10_SH14","OBJ:gramota",None,
 "an honour certificate in a thin gilt frame held in two hands, an ornate border around a typed name, stage light flaring on the cheap glass",
 "INSERT","eye","static","day",False,True,
 "тебе вручают грамоту в тонкой рамке и коробку с электрическим чайником, итог подведён."),
("A10_SH15","LIDA_OLD","assembly_hall",
 "the teacher on stage holding the framed certificate and the boxed kettle, managing both and a handshake, her smile real above the absurd load",
 "MS","eye","static","day",False,False,
 "ты стоишь с грамотой и чайником в обнимку и думаешь, надо же, всё уместилось в две руки.",
 "the kettle box balancing against her hip, the frame catching light, her laugh breaking through the handshake"),
("A10_SH16","SANYA_RICH","assembly_hall",
 "the broad man of forty-one clapping over his head amid the standing rows of the packed hall, his silver chain flashing, his teenage daughter whistling beside him",
 "WS","eye","static","day",False,False,
 "из зала свистит и хлопает над головой саня, он привёз таньку и половину своего салона.",
 "his palms meeting high over his head, the chain flashing, the girl beside him whistling through fingers"),
("A10_SH17","KATYA_PROF","assembly_hall",
 "the copper-haired professor in the aisle filming on her phone with both hands, glasses slipping, unashamedly crying and smiling at once",
 "MCU","eye","static","day",False,False,
 "катя прилетела на один день и снимает тебя на телефон, забыв, что она доктор наук.",
 "the phone trembling slightly in her doubled grip, her smile breaking wider as her glasses slip"),
("A10_SH18","LIDA_OLD","assembly_hall",
 "the teacher looking out from the stage over the standing hall, faces of three generations of her pupils scattered through the rows, stage light warm on her",
 "POV","high","static","day",False,True,
 "со сцены видно сразу три поколения твоих учеников, и у половины уже свои школьники.",
 "rows of standing faces lifting toward the stage, hands clapping in slow warm waves across the hall"),
("A10_SH19","LIDA_OLD","classroom_hers_2010s",
 "the teacher hosting her graduates crowding her classroom after the ceremony, sashes bright among the desks, someone chalking a huge thank-you on the green board",
 "WS","eye","static","day",False,False,
 "после звонка твой класс набивается в кабинет, и кто-то пишет на доске спасибо во всю ширину.",
 "sashed figures crowding between desks, a boy's arm chalking giant letters across the green board"),
("A10_SH20","LIDA_OLD","classroom_hers_2010s",
 "the teacher laughing among her graduates, someone's sash draped over her shoulder, a girl showing her something on a phone, the chalked thank-you behind",
 "MCU","eye","static","day",False,False,
 "тебя фотографируют сорок раз, и на всех снимках у тебя чужая лента через плечо.",
 "the sash settling over her shoulder, phones rising around her, her laugh caught mid-turn"),
("A10_SH21",None,"school_yard",
 "the school yard emptying in late may afternoon, deflating balloons tied to the fence, the great maple in full leaf over scattered flower petals on the asphalt",
 "EWS","high","static","day",True,False,
 "к вечеру двор пустеет, и только шары на заборе кивают вслед последним семьям."),
("A10_SH22","LIDA_OLD","classroom_hers_2010s",
 "the teacher alone in the emptied classroom at dusk, washing the chalked thank-you off the board in wide slow strokes, the letters dissolving reluctantly",
 "BACK","eye","static","evening",False,True,
 "ты стираешь спасибо с доски сама, медленно, потому что эту доску больше некому мыть.",
 "the wet rag travelling through the giant letters, white words dissolving into green, her strokes unhurried"),
("A10_SH23","OBJ:chalk",None,
 "a started stub of chalk being lifted from the chalk rail by careful fingers and slipped into a cardigan pocket, the washed board dark and drying beyond",
 "ECU","eye","push_in","evening",False,True,
 "начатый кусок мела ты забираешь с бортика в карман, не по правилам, но по совести."),
("A10_SH24","LIDA_OLD","classroom_hers_2010s",
 "the teacher standing in the classroom doorway with her coat on, hand on the light switch, taking one long last inventory of the room",
 "MS","eye","static","evening",False,False,
 "у двери ты оборачиваешься и пересчитываешь парты, тридцать лет привычки не выключаются рубильником.",
 "her eyes travelling row by row over the desks, her hand resting on the switch, the room holding still"),
("A10_SH25",None,"classroom_hers_2010s",
 "the classroom dark except for street light through tall windows, chairs up on desks, the washed board a black mirror, the maple's shadow moving on the ceiling",
 "WS","eye","static","night",True,False,
 "свет гаснет, и класс остаётся жить своей ночной жизнью, которой ты никогда не видела."),
("A10_SH26","LIDA_OLD","school_corridor",
 "the teacher handing a labelled key to an old cloakroom attendant at the corridor's end, two women of one generation holding the moment between them",
 "MCU","eye","static","evening",False,False,
 "ключ от класса ты сдаёшь вахтёрше зинаиде, вы вместе тут с девяносто второго года.",
 "the labelled key passing palm to palm, both hands closing over it a moment longer than needed"),
("A10_SH27","LIDA_OLD","school_yard",
 "the teacher walking from the school steps across the darkening yard, pausing under the big maple to touch its bark once, her box of decades under one arm",
 "WS","eye","track","evening",False,False,
 "во дворе ты прощаешься с клёном ладонью, вы с ним пришли сюда в один год.",
 "her palm resting on the dark bark a long beat, then her steps carrying her on under the branches"),
("A10_SH28","LIDA_OLD","street_winter",
 "the teacher at her building's entrance looking back at the school's dark silhouette across the courtyard, the cardboard box balanced on her hip",
 "MS","eye","static","night",False,False,
 "от подъезда школу видно целиком, и ты впервые смотришь на неё как посторонний человек.",
 "the box settling on her hip, her head turning back to the dark building, her keys hanging forgotten"),
("A10_SH29",None,"lida_kitchen",
 "a boxed electric kettle still in its ribboned packaging standing unopened on a kitchen counter beside a battered enamel kettle on the stove",
 "INSERT","eye","static","night",True,False,
 "новый чайник так и стоит в коробке, старый эмалированный переживёт, наверное, всех."),
("A10_SH30","LIDA_OLD","lida_kitchen",
 "the teacher hanging the framed certificate on the kitchen wall beside the child's drawing and the defence photograph, straightening all three level",
 "MS","eye","static","night",False,False,
 "грамота занимает место на стене между танькиным рисунком и катиной защитой, компания достойная.",
 "her hands nudging the three frames into one line, a step back, a small approving nod"),
("A10_SH31","LIDA_OLD","lida_kitchen",
 "the teacher of fifty-six sitting at her kitchen table in the quiet, the chalk stub from her pocket placed before her on the oilcloth, her eyes resting on it",
 "CU","eye","push_in","night",False,True,
 "тебе пятьдесят шесть, работы больше нет, а мел из кармана ты выложить почему-то не можешь.",
 "the chalk stub small on the oilcloth before her, her fingertip touching it once, withdrawing, returning"),
("A10_SH32",None,"street_winter",
 "the courtyard at night, the school building dark for the first september in decades, a single kitchen window lit warm across from it, snowless late spring night",
 "EWS","eye","static","night",True,False,
 "в сентябре школа впервые за сорок лет не зажигает окон, и двор так и не привыкает."),
]

PAL11="still winter palette of slanted white sun, washed board green, chalk white and worn oilcloth check"
CODA=[
("A11_SH01","PUPIL_BASE","lida_kitchen",
 "the curly-haired boy of ten at the kitchen table still waiting for his answer, pencil down, his direct eyes on his tutor, morning sun between them",
 "MCU","eye","static","morning",False,False,
 "мальчик ждёт ответа, как умеют ждать только дети, не отводя глаз и не торопя.",
 "his eyes holding steady on her, one finger slowly spinning the pencil against the tabletop"),
("A11_SH02","LIDA_OLD","lida_kitchen",
 "the teacher of fifty-eight answering the boy with a calm clear face, her hand resting flat on the checked oilcloth, the amber ring warm in the sun",
 "CU","eye","static","morning",False,True,
 "есть, отвечаешь ты ровно, у меня их тысяча двадцать, и почти все уже взрослые.",
 "her hand settling flat and calm on the oilcloth, her chin lifting, the ring catching the morning sun"),
("A11_SH03","PUPIL_BASE","lida_kitchen",
 "the boy blinking, recalculating the number against the small kitchen around him, his mouth opening and closing on arithmetic he cannot finish",
 "MCU","eye","static","morning",False,False,
 "мальчик моргает, оглядывает твою маленькую кухню и явно не может свести это число.",
 "his eyes making a slow circuit of the small kitchen, his lips moving over silent arithmetic"),
("A11_SH04","LIDA_OLD","lida_kitchen",
 "the teacher laughing softly and tapping the boy's notebook to return him to work, the lesson resuming its quiet track, steam over the cups",
 "MS","eye","static","morning",False,False,
 "ты смеёшься и стучишь пальцем по тетради, до конца часа ещё двадцать минут, работаем.",
 "her finger tapping the notebook twice, the boy's head bowing back to the page, steam swaying"),
("A11_SH05",None,"street_winter",
 "the courtyard in slanted white winter sun after the lesson, fresh snow on the poplars, the old school building across the yard with an unfamiliar new signboard by its door",
 "WS","eye","static","day",True,False,
 "после урока ты идёшь через двор к школе, на её дверях теперь табличка с чужим номером."),
("A11_SH06","LIDA_OLD","school_corridor",
 "the old cloakroom attendant waving the teacher through the school door with a conspiratorial nod, keys jingling, the corridor stretching bright and empty behind her",
 "MS","eye","static","day",False,False,
 "зинаида пускает тебя без слов, кивком, у вахтёрш своя память и свои законы.",
 "the attendant's nod tipping toward the corridor, keys jingling on her belt, the door swinging wide"),
("A11_SH07","LIDA_OLD","school_corridor",
 "the teacher walking the long empty corridor in winter light, past the achievements board still hung with faces, her steps unhurried and sure of the way",
 "WS","eye","track","day",False,False,
 "коридор пахнет по-прежнему, краской и мелом, у школьных запахов оптимизации не бывает.",
 "her unhurried steps down the bright corridor, her head turning to the pinned faces as she passes"),
("A11_SH08","LIDA_OLD","classroom_hers_2010s",
 "the teacher opening her old classroom door slowly, winter sun flooding past her into the room, her silhouette on the threshold",
 "BACK","eye","push_in","day",False,True,
 "свой класс ты открываешь медленно, как открывают дверь, за которой может быть что угодно.",
 "the door swinging open by degrees under her hand, winter light spilling around her still silhouette"),
("A11_SH09",None,"classroom_hers_2010s",
 "the classroom in slanted white winter sun, desks in their rows under dust sheets folded back, the green board washed clean and drying without a single mark",
 "WS","eye","static","day",True,True,
 "класс стоит нетронутый, парты в три ряда, и доска вымыта чисто, как перед первым уроком."),
("A11_SH10","LIDA_OLD","classroom_hers_2010s",
 "the teacher walking slowly between the desk rows, her fingertips trailing along desktop after desktop, winter light moving with her",
 "MS","eye","track","day",False,False,
 "ты идёшь между рядами и трогаешь парты, за каждой сидело по тридцать разных судеб.",
 "her fingertips trailing from desk to desk, her pace slow, dust motes rising into the slanted sun"),
("A11_SH11","LIDA_OLD","classroom_hers_2010s",
 "the teacher stopping at the teacher's desk, standing behind it a moment with both palms flat on its top, the empty rows before her",
 "MCU","eye","static","day",False,False,
 "у своего стола ты становишься, как на урок, и пустые парты честно смотрят в ответ.",
 "her palms settling flat on the desktop, her spine finding its teaching line, her gaze crossing the rows"),
("A11_SH12","OBJ:chalk",None,
 "an aged hand drawing a started stub of chalk from a cardigan pocket and holding it a moment in the winter light, white dust in the knuckle creases",
 "ECU","eye","static","day",False,True,
 "ты достаёшь из кармана начатый мел, который два года ездил с тобой по чужим кухням."),
("A11_SH13","LIDA_OLD","classroom_hers_2010s",
 "the teacher at the green board writing one short clean word high in the corner where dates always lived, her hand steady, chalk singing",
 "BACK","eye","static","day",False,True,
 "на чистой доске, в углу, где всегда жила дата, ты пишешь одно слово, спасибо.",
 "her chalk hand travelling in short sure strokes, the single word appearing high in the corner"),
("A11_SH14","LIDA_OLD","classroom_hers_2010s",
 "the teacher placing a brand new stick of chalk still in its paper wrapper on the chalk rail, centring it precisely, her rings of age and amber in the light",
 "CU","eye","push_in","day",False,True,
 "а на бортик ты кладёшь новый кусок мела в обёртке, для того, кто придёт сюда после.",
 "the wrapped chalk settling onto the rail under her careful fingers, nudged once to the exact centre"),
("A11_SH15",None,"classroom_hers_2010s",
 "the classroom seen from the closing door, slanted white sun across empty desks, one chalked word high on the clean board, one wrapped chalk stick centred on the rail",
 "WS","eye","pull_out","day",True,True,
 "класс остаётся в зимнем свете, доска вымыта, и на бортике лежит один новый мел."),
("A11_SH16","LIDA_OLD","school_yard",
 "the teacher walking out under the bare great maple, pausing to look up through its black branches at the white sky, her breath a slow plume",
 "MS","low","static","day",False,False,
 "во дворе ты киваешь клёну, как коллеге, вы оба отработали здесь свои тридцать четыре.",
 "her face lifting through the black branches to the white sky, her breath rising in a slow plume"),
("A11_SH17","LIDA_OLD","street_winter",
 "the teacher of fifty-eight walking home across the winter courtyard, straight-backed and unhurried, her small figure certain between the snow and the lit windows",
 "WS","eye","track","day",False,False,
 "ты идёшь домой проверять чужую тетрадь, потому что в четыре часа придёт следующий ученик.",
 "her straight-backed figure crossing the courtyard unhurried, snow creaking underfoot, windows lighting ahead"),
("A11_SH18","LIDA_OLD","lida_kitchen",
 "the teacher at her kitchen table in the afternoon light laying out a fresh notebook and the red pen for the next pupil, the wall of three frames behind her",
 "MCU","eye","static","day",False,False,
 "вот и вся твоя жизнь, тетрадь, красная ручка и тысяча двадцать человек, которые умеют писать.",
 "her hands laying the notebook square to the table edge, the red pen settling beside it just so"),
("A11_SH19",None,"lida_kitchen",
 "the kitchen wall in soft afternoon light, a child's crayon drawing, a defence photograph and a gilt-framed certificate hanging level over the small table",
 "INSERT","eye","push_in","day",True,False,
 "если эта история задела тебя, подпишись и досмотри до конца, дальше только титры и правда."),
("A11_SH20",None,"classroom_hers_2010s",
 "the empty classroom at winter dusk, the slanted sun gone blue, the wrapped chalk stick alone on the rail catching the last light",
 "WS","eye","push_in","evening",True,True,
 "эта история вымышлена, все совпадения с реальными людьми и событиями случайны, не повторяй чужих ошибок."),
]

seed_act("last_bell",PAL10,LASTBELL,render_mode="animated")
seed_act("coda",PAL11,CODA,render_mode="animated")
