# -*- coding: utf-8 -*-
"""Batch 1: cold_open + act01_childhood (animated prefix)."""
from _flat_earth_engine import seed_act

# ── COLD OPEN — мягкая палата, «сейчас». Аудио уверено; картинка = дурка. ──
PAL_CELL = "stark clinical white-and-grey palette, flat even institutional light, cold sterile whites with faint grey shadow"
COLD = [
 ("A0_SH01","RAY","padded_cell","an intense gaunt man with wild greying curls strapped in a canvas straitjacket, sitting upright against a padded wall, staring straight ahead with burning certainty","CU","eye","push_in","day",False,True,
  "меня зовут рэй доусон, и за то, что я знаю и не хочу молчать, меня заперли вот в этой комнате."),
 ("A0_SH02","RAY","padded_cell","extreme close on the same man's wide pale unblinking eyes, fine sweat on his brow, utter conviction","ECU","eye","static","day",False,False,
  "они очень не хотят, чтобы ты дослушал меня до конца, и скоро ты сам поймёшь, почему именно меня."),
 ("A0_SH03",None,"padded_cell","a heavy seclusion-room door with a small wired observation window, seen from a dim corridor, a key card reader beside it","WS","eye","push_in","day",False,False,
  "поэтому меня держат тут, за крепкой дверью, подальше от тебя и от твоих вопросов."),
 ("A0_SH04","RAY","padded_cell","the strapped man sitting small on the soft white floor of a bare padded room, calm and certain, chin lifted","WS","high","static","day",False,False,
  "но ты дослушай меня до конца, и сам решишь, кто из нас двоих сошёл с ума."),
 ("A0_SH05","RAY","padded_cell","the man leaning his shoulder to the padded wall, speaking calmly toward the observation window","MS","eye","push_in","day",False,False,
  "останься со мной до самого конца, подпишись, и береги себя, слышишь, береги себя."),
 ("A0_SH06",None,"padded_cell","a brass folding carpenter's ruler lying alone in a clear plastic property tray on a steel shelf behind glass","INSERT","high","push_in","day",False,True,
  "видишь эту простую латунную линейку, с неё и началась вся моя долгая история, держи её в уме."),
 ("A0_SH07","RAY","padded_cell","close on the man's lined face, faint knowing half-smile, eyes fixed and clear","CU","eye","static","day",False,False,
  "сейчас тебе снова скажут, что земля это шар, тебе показывают её такой с самого детства."),
 ("A0_SH08","HALE","padded_cell","a calm doctor in a white coat with a lanyard badge writing on a clipboard, the strapped man blurred behind him","OTS","over","static","day",False,False,
  "а те, кто в белых халатах, им платят за то, чтобы ты в это верил и не задавал вопросов."),
 ("A0_SH09",None,"padded_cell","a close patch of off-white padded wall with a long perfectly straight horizontal line scuffed into it by a fingertip","ECU","eye","track","day",False,False,
  "присмотрись к линии горизонта над любым морем, она всегда ровная, и это вовсе не случайно."),
 ("A0_SH10","RAY","padded_cell","the man tilting his head toward the small wired window, light falling across half his face","MCU","low","push_in","day",False,False,
  "я начал понимать всё это в девять лет, на берегу озера, с отцовской линейкой в руках."),
 ("A0_SH11","RAY","padded_cell","very wide of the bare seclusion room, the strapped man a small figure in the corner under a caged ceiling light","EWS","high","pull_out","day",False,True,
  "пройди весь мой путь вместе со мной, от самого начала, и в конце сам реши, кто из нас прав."),
 ("A0_SH12",None,"padded_cell","the seclusion door easing shut, a thin blade of corridor light narrowing to nothing on the padded floor","INSERT","eye","static","day",True,False,
  "а начинается всё на старой заправке моего отца, на дальней окраине нэшвилла."),
]

# ── ACT 1 — 1986: заправка, озеро (рождение лейтмотива), школа. ──
PAL_CHILD = "warm faded 1980s Southern sepia palette, dusty golden light, nostalgic amber and teal, soft film-grain warmth"
A1 = [
 ("A1_SH01",None,"gas_station_dickerson","a small 1980s roadside gas station glowing under a flickering fluorescent canopy at dusk on an empty Tennessee pike, two worn pumps, moths circling the lights","EWS","eye","pan_right","dusk",True,True,
  "тысяча девятьсот восемьдесят шестой год, тебе восемь, и весь твой мир это отцовская заправка."),
 ("A1_SH02","FATHER","gas_station_dickerson","a wiry man in a mesh trucker cap behind a worn register under buzzing fluorescent light, ringing up a customer, cigarette behind his ear","MS","eye","static","dusk",False,False,
  "отец стоит за кассой по двенадцать часов, и говорит одну и ту же фразу каждому, кто берёт сдачу."),
 ("A1_SH03","FATHER","gas_station_dickerson","close on the capped man leaning over the counter, finger pointed, speaking with quiet conviction to someone off-frame","CU","low","push_in","dusk",False,False,
  "не верь телевизору, сынок, они показывают тебе ровно то, за что им заплатили, и ни словом больше."),
 ("A1_SH04",None,"gas_station_dickerson","an extreme close on a wire rack of lurid 1980s tabloids by the register, a screaming alien headline and a grainy flying-saucer photo, a price sticker reading one forty-nine","ECU","eye","push_in","dusk",False,True,
  "у кассы стоит вертушка с газетами по доллару сорок девять, и с обложек на тебя смотрят пришельцы."),
 ("A1_SH05",None,"gas_station_dickerson","a small freckled boy sitting on the gas-station step at dusk, knees up, utterly absorbed in a folded pulp tabloid","MS","high","static","dusk",False,False,
  "ты читаешь про тарелки, про рептилий в правительстве, про то, что от тебя прячут, и веришь каждому слову."),
 ("A1_SH06",None,"east_nash_street","a quiet older Nashville street at dusk, modest porches, oaks, power lines crossing a wide flat sky, a boy walking home alone with a rolled-up newspaper","WS","eye","track","dusk",True,False,
  "ты идёшь домой один, и впервые думаешь, что взрослые вокруг чего-то очень сильно не понимают."),
 ("A1_SH07",None,"percy_priest_lake","a wide reservoir at dawn from a long wooden jetty, dead-calm water stretching in a perfectly level line to a far pine shore, thin mist","EWS","eye","push_in","dawn",True,True,
  "тебе девять, отец берёт тебя на озеро перси-прист на рассвете, и вода лежит ровная, до самого горизонта."),
 ("A1_SH08",None,"percy_priest_lake","a small boy alone at the end of a long jetty holding a brass folding ruler up at arm's length against the flat line of the lake","MS","low","static","dawn",False,True,
  "ты достаёшь отцовскую латунную линейку и прикладываешь её к дальнему берегу, к самой кромке воды."),
 ("A1_SH09",None,"percy_priest_lake","extreme close on the brass ruler edge held against the dead-flat far shoreline, the line of water meeting the ruler with no curve at all","ECU","eye","push_in","dawn",False,True,
  "и линия ложится идеально ровно, ни единого изгиба, вода плоская, как стол, до самого края."),
 ("A1_SH10",None,"percy_priest_lake","close on the boy's still face at dawn, eyes wide with a private dawning certainty, the lake soft behind him","CU","eye","push_in","dawn",False,True,
  "и по твоей спине впервые бежит этот холодок, холодок узнавания, ведь шар никогда не выглядит так."),
 ("A1_SH11",None,"percy_priest_lake","a boy crouched at the water's edge sighting along a flat board laid on the surface, the level line running to the horizon","MS","high","static","dawn",False,False,
  "ты проверяешь снова и снова, кладёшь дощечку, ложишься щекой к воде, и всё ровно, всё всегда ровно."),
 ("A1_SH12",None,"ridge_overlook","a rural Tennessee ridge at first light, layered hills falling to a long flat haze on the horizon, telephone wires across the foreground","WS","high","pan_left","dawn",True,False,
  "с тех пор ты видишь эту ровную линию повсюду, на каждом поле, на каждой дороге, на каждой воде."),
 ("A1_SH13",None,"elementary_classroom","a 1980s classroom seen from the back, a teacher's hand spinning a globe on the desk, rows of children at wooden desks, a pull-down world map","WS","eye","push_in","day",False,False,
  "в школе тебе показывают глобус и говорят, что ты живёшь на огромном шаре, летящем сквозь пустоту."),
 ("A1_SH14",None,"elementary_classroom","a small boy at a wooden desk with his hand raised high, earnest and certain, other children turning to look","MCU","eye","static","day",False,False,
  "ты тянешь руку и спрашиваешь, почему же тогда вода в нашем озере не выгибается горбом посередине."),
 ("A1_SH15",None,"elementary_classroom","a classroom of children laughing and turning in their seats, one small boy standing alone among the desks, face hot","WS","high","pull_out","day",False,True,
  "и весь класс смеётся над тобой, а учительница только вздыхает, и ты впервые чувствуешь себя чужим."),
 ("A1_SH16",None,"elementary_classroom","extreme close on the boy's set jaw and stubborn wet eyes, refusing to cry, fists tight at his sides","ECU","low","push_in","day",False,False,
  "но ты не плачешь, ты решаешь, что однажды докажешь это всем, и от этого решения тебе становится тепло."),
 ("A1_SH17",None,"elementary_classroom","a teacher crouching to speak gently to the small boy after class, the empty desks around them, the globe on the desk behind","OTS","over","static","day",False,False,
  "учительница говорит, что глобус не врёт, что так написано во всех книгах, а значит, так оно и есть."),
 ("A1_SH18",None,"cody_bedroom","a child's 1980s bedroom at night, a boy under a desk lamp gluing newspaper clippings of saucers and maps into a school scrapbook","MS","eye","push_in","night",False,False,
  "дома по ночам ты вклеиваешь вырезки в тетрадь, тарелки, карты, всё, что доказывает, что мир другой."),
 ("A1_SH19",None,"cody_bedroom","extreme close on a child's scrapbook page, a crude drawing of a flat disc world with a ruler line across the sea, taped clippings","ECU","top","push_in","night",False,True,
  "на первой странице ты рисуешь плоский круг, а поверх моря проводишь линейкой ту самую ровную черту."),
 ("A1_SH20",None,"gas_station_dickerson","the boy showing his scrapbook proudly to the capped father across the register counter, the man half-listening, tired","OTS","eye","static","dusk",False,False,
  "ты показываешь тетрадь отцу, и он усмехается, и говорит, молодец, сынок, хоть один в семье не дурак."),
 ("A1_SH21","FATHER","gas_station_dickerson","the wiry capped man ruffling the boy's hair without looking up from the register, a weary fond half-smile","MCU","eye","static","dusk",False,False,
  "это единственная похвала, которую ты помнишь, и ты будешь гнаться за ней всю свою оставшуюся жизнь."),
 ("A1_SH22",None,"percy_priest_lake","a boy lying on the jetty boards at dusk, chin on hands, watching the flat orange water, the ruler beside him","CU","low","static","dusk",False,False,
  "каждый вечер после школы ты приходишь к воде, и смотришь на ровную линию, и тебе становится спокойно."),
 ("A1_SH23",None,"percy_priest_lake","the flat reservoir at last light, a single boy silhouette small at the end of the long jetty under a huge level horizon","EWS","eye","pull_out","dusk",True,True,
  "ты ещё не знаешь, что эта ровная линия уже забрала тебя, и не отпустит до самого конца."),
 ("A1_SH24",None,"interstate_south","a long straight Tennessee highway at dusk running dead level to a single vanishing point, fields either side, a boy on a bike at the roadside","WS","low","push_in","dusk",True,False,
  "ты замечаешь её и на шоссе, дорога уходит ровно в точку, и нигде, нигде она не загибается вниз."),
 ("A1_SH25",None,"elementary_classroom","a library corner of the classroom, the boy alone with an open encyclopedia, frowning at a diagram of a round earth","MS","high","static","day",False,False,
  "ты читаешь учебники от корки до корки, и чем больше читаешь, тем сильнее уверен, что тебя обманывают."),
 ("A1_SH26",None,"east_nash_street","other children playing ball in a Nashville street at dusk while one boy sits apart on a curb with his scrapbook","WS","eye","static","dusk",False,False,
  "другие дети гоняют мяч, а ты сидишь в стороне с тетрадью, и тебе кажется, что это они слепые."),
 ("A1_SH27",None,"cody_bedroom","close on a boy asleep at his desk over the open scrapbook, lamp still on, a crayon flat-earth disc under his cheek","CU","high","push_in","night",False,False,
  "ты засыпаешь прямо над тетрадью, и тебе снится, что ты идёшь по краю мира и заглядываешь за него."),
 ("A1_SH28",None,"ridge_overlook","a wide dawn vista of flat misted Tennessee farmland under an enormous level horizon, a lone bird crossing","EWS","high","pan_right","dawn",True,False,
  "а за краем, во сне, нет никакого космоса, там просто вода льётся вниз, в темноту, бесшумно."),
 ("A1_SH29","FATHER","gas_station_dickerson","the capped father locking up the dark gas station at night, the boy waiting by the door holding the brass ruler","WS","eye","static","night",False,False,
  "однажды отец отдаёт тебе свою линейку насовсем, и говорит, держи, измерь ими то, что я уже не успею."),
 ("A1_SH30",None,"percy_priest_lake","close on a small hand closing around the worn brass folding ruler at the water's edge, the flat lake behind","ECU","eye","push_in","night",False,True,
  "ты сжимаешь латунную линейку в кулаке, и обещаешь ему и себе, что однажды дойдёшь до самого края."),
]

seed_act("cold_open",      PAL_CELL,  COLD, render_mode="animated")
seed_act("act01_childhood",PAL_CHILD, A1,   render_mode="animated")
