# -*- coding: utf-8 -*-
"""fortune batch A: cold_open + act01_fool + act02_magician (animated prefix). Cold open = HOOK, no ending spoiler."""
from _fortune_engine import seed_act

PAL_DEAD="dying-neon palette, half-dead magenta and cyan tubes flickering over a cold dark salon, deep violet shadow"
COLD=[
 ("F0_SH01","ZARA_OLD","salon_dying","an old woman's ringed hand resting over a worn tarot deck on a velvet table, lit by failing pink neon","CU","high","push_in","night",False,True,
  "сорок лет ты раскладывала чужие судьбы на этом столе, под гудящей неоновой ладонью с глазом."),
 ("F0_SH02",None,"salon_dying","extreme close on a tarot deck with one single card set apart face-down on dark velvet, neon glint on its back","ECU","top","push_in","night",False,True,
  "и всю жизнь одна карта лежала вот так, рубашкой вверх, и ты ни разу её не перевернула."),
 ("F0_SH03",None,"salon_dying","a dim fortune salon with half its neon letters dead, an empty chair across a draped table, dust on a crystal ball","WS","eye","pan_right","night",True,False,
  "теперь неон почти погас, и стул напротив пуст, и спрашивать тебя больше уже некому."),
 ("F0_SH04","ZARA_OLD","salon_dying","an old kohl-eyed woman in a headscarf lit by flickering magenta neon, gazing past the camera, weary","MCU","eye","push_in","night",False,False,
  "люди шли ко мне за правдой о завтрашнем дне, и платили, и верили каждому моему слову."),
 ("F0_SH05","ZARA_OLD","salon_dying","close on the old woman's tired knowing eyes, neon catching the moisture in them","CU","eye","static","night",False,False,
  "а верить мне или нет, решай сам, я расскажу тебе всё как было, с самого начала, до конца."),
 ("F0_SH06",None,"strip_mall_night","extreme close on a buzzing neon palm-and-eye sign glowing magenta and cyan against the night","INSERT","low","static","night",False,True,
  "останься со мной до самого конца, подпишись, и береги себя, слышишь, береги себя."),
 ("F0_SH07","ZARA_OLD","salon_dying","the old woman slowly shuffling a worn tarot deck under low neon, cards clicking, candle smoke drifting","MS","eye","static","night",False,False,
  "всё началось в детстве, в таком же тесном салоне, под такой же неоновой вывеской, что и этот."),
 ("F0_SH08",None,"reading_room","extreme close on a crystal ball on velvet catching swirls of pink and cyan neon, candle flames doubled inside it","ECU","eye","push_in","night",False,True,
  "мать всегда говорила мне, карты не врут, врут только те руки, что эти карты держат."),
 ("F0_SH09",None,"parking_lot_rain","a rain-soaked strip-mall parking lot at night, neon signs smeared and doubled in the wet asphalt, falling rain","WS","high","static","night",True,False,
  "а я держала их в своих руках всю свою жизнь, до этой самой тихой дождливой ночи."),
 ("F0_SH10",None,"salon_dying","extreme close again on the single face-down tarot card apart from the deck, neon shimmering on it","ECU","top","push_in","night",False,True,
  "что нарисовано на этой карте, я скажу тебе в самом конце, если ты дойдёшь со мной до него."),
 ("F0_SH11","ZARA_OLD","salon_dying","the old woman half-smiling into the dark, neon flicker across her lined face, an invitation and a warning","MCU","low","push_in","night",False,False,
  "а пока ты ещё уверен, что знаешь наперёд, кто здесь кого обманывает, и в чём тут подвох."),
 ("F0_SH12",None,"mother_salon","extreme close on a single candle flame guttering beside a child's small hand on the table edge","INSERT","eye","push_in","night",True,False,
  "погоди, не уходи так скоро, дай мне начать с той серьёзной девочки среди маминых свечей."),
]

PAL_FOOL="warm childhood neon palette, soft pink and amber neon glow over candlelit clutter, nostalgic dusk tones, gentle haze"
A1=[
 ("F1_SH01",None,"mother_salon","a small 1980s strip-mall fortune parlor at dusk, a buzzing pink palm-and-eye neon sign in the window, beaded curtains, a velvet reading table, candles","EWS","eye","push_in","dusk",True,True,
  "тебе восемь, и весь твой мир это мамин салон гаданий в углу захудалого торгового ряда."),
 ("F1_SH02","MOTHER","mother_salon","a heavyset woman with big gold hoop earrings reading tarot for a client across a draped table under low neon, candle-lit","MS","eye","static","dusk",False,False,
  "мать гадает с утра до ночи, и кормит вас двоих картами, свечами и чужой надеждой на лучшее."),
 ("F1_SH03","ZARA_KID","mother_salon","a serious dark-haired girl with braids sitting in shadow behind beaded curtains, watching intently, neon glow on her face","MCU","low","static","dusk",False,False,
  "ты сидишь за бисерной занавеской и смотришь, как взрослые люди плачут и смеются от маминых слов."),
 ("F1_SH04","MOTHER","mother_salon","the woman leaning close over a client's hand, eyes sharp, reading them, neon and candlelight on the velvet","CU","over","push_in","dusk",False,False,
  "после она зовёт тебя и тихо объясняет, я ничего не угадываю, девочка, я просто очень внимательно смотрю."),
 ("F1_SH05","MOTHER","reading_room","the woman pointing discreetly at an unseen client's hand and clothes, teaching, beaded curtain glowing behind","MCU","eye","static","dusk",False,False,
  "светлая полоска на пальце, значит, недавно сняли кольцо, чёрное платье и красные глаза, значит, кто-то умер."),
 ("F1_SH06","ZARA_KID","reading_room","close on the serious girl's dark eyes widening with understanding, neon reflected in them","CU","eye","push_in","dusk",False,False,
  "и ты вдруг понимаешь, что люди сами рассказывают о себе всё, ещё до того, как откроют рот."),
 ("F1_SH07",None,"strip_mall_night","the strip-mall at night, the pink palm-and-eye neon humming above a row of dim shops, a wet sidewalk","WS","low","pan_left","night",True,False,
  "по вечерам неоновая ладонь гудит над улицей, и ты засыпаешь под её розовый свет, как под ночник."),
 ("F1_SH08","ZARA_KID","mother_salon","the girl practising a tarot spread alone on the rug by candlelight for a patient cat, very solemn","MS","high","static","night",False,False,
  "ты раскладываешь мамины карты коту и соседской малышне, и говоришь им то, что им хочется услышать."),
 ("F1_SH09","ZARA_KID","mother_salon","close on the girl's small hands turning a tarot card with exaggerated ceremony, candle flame near","CU","top","push_in","night",False,False,
  "и они слушают тебя, открыв рот, и тебе это нравится так сильно, что внутри становится горячо."),
 ("F1_SH10","MOTHER","mother_salon","the woman sliding a moonstone ring onto the girl's finger, too big for it, a tender ceremonial moment, neon glow","MCU","eye","push_in","night",False,True,
  "на девять лет мать надевает тебе на палец кольцо с лунным камнем, и говорит, теперь ты тоже из наших."),
 ("F1_SH11",None,"mother_salon","extreme close on a moonstone ring loose on a child's finger, glowing softly under candle and neon light","ECU","top","push_in","night",False,True,
  "кольцо велико, и ты сжимаешь кулак, чтобы не потерять его, и носишь его с того дня всю свою жизнь."),
 ("F1_SH12","ZARA_KID","salon_storefront_day","the girl walking to school by day past the salon, the neon off and dull, other parents steering children aside","WS","eye","track","day",False,False,
  "днём неон выключен, и вывеска просто серая, и в школе тебя зовут дочкой ведьмы, и обходят стороной."),
 ("F1_SH13",None,"salon_storefront_day","other children crossing the street away from a lone girl near a dull daytime psychic storefront","WS","high","static","day",False,False,
  "родители не пускают к тебе детей, и ты привыкаешь быть одна, и привыкаешь читать людей, как книги."),
 ("F1_SH14","ZARA_KID","reading_room","the girl peering into a neon-lit crystal ball, her own face curving back at her in the glass","CU","eye","push_in","dusk",False,False,
  "ты часами глядишь в стеклянный шар, и видишь в нём только своё лицо, но матери об этом не говоришь."),
 ("F1_SH15","MOTHER","reading_room","the woman counting small bills from a client's envelope by candlelight, the girl watching from the side","MCU","high","static","night",False,False,
  "ты видишь, как мать пересчитывает мятые купюры из конвертов, и понимаешь, что надежда хорошо продаётся."),
 ("F1_SH16","ZARA_KID","kitchen_charms","a girl eating supper in a small kitchen strung with evil-eye charms and salt lines, neon bleeding through the curtain","MS","eye","static","night",False,False,
  "дома у вас обереги на каждом гвозде и соль на подоконниках, и ты растёшь, веря в приметы, как в азбуку."),
 ("F1_SH17","MOTHER","kitchen_charms","the woman gently touching the girl's cheek across the kitchen table, warm and tired, charms hanging around them","CU","eye","push_in","night",False,False,
  "мать любит тебя, и это правда, и она правда верит, что оберегает тебя картами от злого мира."),
 ("F1_SH18",None,"mother_salon","a medium shot of the velvet reading table with a tarot deck, one card slightly askew, candles and neon glow across it","MS","high","static","night",False,False,
  "но среди всех её карт есть одна, которую она никогда не толкует на себя, и однажды ты спросишь, почему."),
 ("F1_SH19","MOTHER","mother_salon","the woman's face going briefly still and guarded at a question, candle flame between her and the girl","CU","eye","push_in","night",False,False,
  "и мать отвечает, на себя не гадают, девочка, на себя смотреть страшнее всего, запомни это крепко."),
 ("F1_SH20","ZARA_KID","mother_salon","the girl nodding solemnly, filing the warning away, the deck glowing between small careful hands","MCU","low","static","night",False,True,
  "ты киваешь, и запоминаешь, и проносишь этот завет через всю жизнь, до самой этой дождливой ночи."),
 ("F1_SH21",None,"strip_mall_night","the humming pink neon palm-and-eye sign in the rain at night, glowing halo around it, the shop dark below","WS","low","tilt_down","night",True,True,
  "ты ещё не знаешь, что эта неоновая ладонь будет светить над всей твоей жизнью, и над её концом."),
 ("F1_SH22","ZARA_KID","reading_room","the girl asleep at the reading table over a spread of cards, candle low, neon glow on her braids","CU","high","push_in","night",False,False,
  "ты засыпаешь над картами, и тебе снится длинная очередь людей, которые пришли узнать своё завтра."),
]

PAL_MAGICIAN="electric young-neon palette, vivid magenta and cyan glow, deep kohl shadows, seductive saturated night colour"
A2=[
 ("F2_SH01",None,"mother_salon","the small fortune salon at night, the pink neon sign humming, an empty reading chair, the mother's shawl left on it","WS","eye","push_in","night",True,False,
  "тебе семнадцать, мать слегла, и однажды вечером в салон входит клиент, а гадать некому, кроме тебя."),
 ("F2_SH02","ZARA_YOUNG","reading_room","a nervous young woman with long dark hair sitting down at the reading table for the first time as the reader, hands unsteady","MCU","eye","push_in","night",False,False,
  "ты садишься на мамин стул, и сердце колотится, и ты говоришь, садитесь, карты ждали именно вас."),
 ("F2_SH03","ZARA_YOUNG","reading_room","the young reader studying a client across the table, eyes flicking over their hands and clothes, neon and candlelight","CU","over","static","night",False,False,
  "ты смотришь на него так, как учила мать, стоптанные ботинки, обручальное кольцо, запах перегара, усталость."),
 ("F2_SH04","ZARA_YOUNG","reading_room","the young woman laying out tarot cards with growing confidence, the client leaning in, beads glowing behind","MS","high","static","night",False,False,
  "и ты раскладываешь карты, и говоришь ему то, что он хочет услышать, что всё наладится, что её можно вернуть."),
 ("F2_SH05",None,"reading_room","extreme close on a tarot card turned over on velvet, a hopeful image, neon shimmer along its edge","INSERT","top","push_in","night",False,True,
  "карты не врут, говоришь ты его словами, и сама удивляешься, как легко и гладко это звучит из твоих уст."),
 ("F2_SH06","ZARA_YOUNG","reading_room","the client across the table breaking into relieved tears, gripping the young reader's hand gratefully","OTS","over","static","night",False,False,
  "и он плачет от облегчения, и сжимает твою руку, и уходит другим человеком, лёгким, будто заново родился."),
 ("F2_SH07","ZARA_YOUNG","reading_room","close on the young woman's stunned face alone after the client has gone, a strange chill on her","CU","eye","push_in","night",False,True,
  "а ты сидишь одна, и впервые по твоим предплечьям бежит холодок, и ты не знаешь, что это было."),
 ("F2_SH08","ZARA_YOUNG","reading_room","the young reader looking down at her own hands and the deck as if they were strangers, neon glow","MCU","low","static","night",False,False,
  "ты дала ему надежду из воздуха, из ботинок и кольца, и он поверил, и тебе стало почти страшно от этой власти."),
 ("F2_SH09",None,"reading_room","extreme close on a worn tarot deck cradled in two young hands over candlelight, neon reflected on the cards","ECU","top","push_in","night",False,False,
  "в ту ночь ты не спишь, и снова и снова тасуешь колоду, и слушаешь, как щёлкают карты в тишине."),
 ("F2_SH10","ZARA_YOUNG","kitchen_charms","the young woman sitting at her sick mother's bedside corner, the mother's hand on hers, charms around them","MCU","eye","static","night",False,False,
  "ты рассказываешь матери про того клиента, и она слабо улыбается, и говорит, ну вот, теперь ты кормилица."),
 ("F2_SH11","ZARA_YOUNG","reading_room","the young reader confidently reading for a new client, fully in command now, the neon brighter, the room fuller","MS","eye","static","night",False,False,
  "клиенты идут один за другим, и с каждым ты всё увереннее, и каждый уходит со своей готовой надеждой."),
 ("F2_SH12","ZARA_YOUNG","reading_room","close on the young woman's confident kohl-lined eyes meeting a client's across candle smoke, neon glow","CU","eye","push_in","night",False,False,
  "ты учишься читать человека за минуту, по рукам, по взгляду, по тому, как он садится и молчит."),
 ("F2_SH13","ZARA_YOUNG","reading_room","an envelope of bills being slid across the velvet table toward the young reader, her hand accepting it","INSERT","top","static","night",False,False,
  "первые свои деньги ты прячешь в коробку из-под чая, и пересчитываешь их, как мать когда-то, ночами."),
 ("F2_SH14",None,"strip_mall_night","the pink neon palm-and-eye sign glowing brighter over the salon at night, a small queue of figures at the door","WS","low","static","night",True,False,
  "о тебе начинают говорить, и к старой маминой вывеске тянется очередь, какой при матери и не бывало."),
 ("F2_SH15","ZARA_YOUNG","reading_room","the young woman telling a desperate client exactly what they crave to hear, the client radiant with relief","OTS","eye","static","night",False,False,
  "ты быстро понимаешь главное правило, людям не нужна правда, людям нужно, чтобы кто-то уверенно их утешил."),
 ("F2_SH16","ZARA_YOUNG","reading_room","close on the young reader's small private smile as a client leaves happy, a flicker of guilt under it","CU","low","push_in","night",False,False,
  "и ты даёшь им это утешение, и берёшь за него деньги, и говоришь себе, что не делаешь ничего дурного."),
 ("F2_SH17","ZARA_YOUNG","reading_room","the young woman pausing mid-reading, a sudden uncanny certainty crossing her face, the chill again","CU","eye","push_in","night",False,True,
  "но иногда, посреди расклада, ты вдруг говоришь то, чего знать не можешь, и оно повисает в воздухе."),
 ("F2_SH18","ZARA_YOUNG","reading_room","a client staring at the young reader in shock as if she has named a secret, candle smoke between them","OTS","over","static","night",False,False,
  "клиентка бледнеет и спрашивает, откуда ты знаешь про брата, а ты и сама не знаешь, откуда, ты не знала."),
 ("F2_SH19","ZARA_YOUNG","reading_room","close on the young woman's unsettled eyes, the forearm chill visible in how she hugs her own arms","CU","low","static","night",False,True,
  "и снова тот холодок по рукам, и ты не понимаешь, дар это, или просто удача, или ты сходишь с ума."),
 ("F2_SH20",None,"back_alley","a wet neon-lit back alley behind the salon at night, pink and green reflections in the puddles, steam from a grate","WS","high","pan_right","night",True,False,
  "ты выходишь подышать в переулок, и ночной неон дрожит в лужах, и ты гонишь от себя этот вопрос."),
 ("F2_SH21","ZARA_YOUNG","reading_room","the young woman shuffling cards alone late at night, deciding something, the neon steady on her face","MCU","eye","push_in","night",False,False,
  "и ты решаешь не думать об этом, дар или нет, какая разница, главное, что работает, и люди идут."),
 ("F2_SH22","ZARA_YOUNG","mother_salon","the young woman gently closing her late mother's shawl into a drawer, taking full ownership of the salon","MCU","eye","static","night",False,False,
  "мать уходит тихо, во сне, и ты остаёшься одна с салоном, с колодой, и с её заветом про свою карту."),
 ("F2_SH23","ZARA_YOUNG","reading_room","close on the young woman setting one card face-down apart from the deck, not turning it, candlelight","ECU","top","push_in","night",False,True,
  "ты откладываешь одну карту рубашкой вверх, свою, и не переворачиваешь, как учила мать, на себя нельзя."),
 ("F2_SH24",None,"strip_mall_night","the bright pink neon palm-and-eye sign humming over the salon at night, the queue longer now, rain starting","WS","low","static","night",True,True,
  "а неоновая ладонь горит над тобой всё ярче, и ты ещё веришь, что держишь свою судьбу в своих руках."),
]

seed_act("cold_open",      PAL_DEAD,     COLD, render_mode="animated")
seed_act("act01_fool",     PAL_FOOL,     A1,   render_mode="animated")
seed_act("act02_magician", PAL_MAGICIAN, A2,   render_mode="animated")
