# -*- coding: utf-8 -*-
"""layoff act A2 climb (19 лет: ты стал должностью). PYTHONIOENCODING=utf-8 python scripts/_seed_layoff_A2.py"""
from _layoff_engine import seed_act
PAL="muted neutral office palette, grey and beige tones, flat daylight through tinted glass, thin even shadows"
S=[
 ("A2_SH01","GEROY_MAIN","turnstile_lobby","a close-up of the older man pressing his worn access card on a blue lanyard to the turnstile reader, a routine green light","ECU","eye","static","morning",False,False,
  "проходят годы, а каждое утро всё то же — ты прикладываешь пропуск к турникету, и звучит тот же короткий писк."),
 ("A2_SH02","GEROY_MAIN","open_floor","a wide shot of the man at his desk among long rows of identical desks, older now, settled into place","WS","high","static","day",False,False,
  "к тридцати пяти ты знаешь на этом этаже каждый стол, каждую розетку и каждый звук старого кондиционера."),
 ("A2_SH03","GEROY_MAIN","your_desk","a medium close-up of the man at his cluttered desk, a chipped mug and a faded family photo beside the monitor","MCU","eye","static","day",False,False,
  "твоя кружка давно треснула, но ты её не меняешь, а рядом стоит фотография жены, которую ты почти не видишь."),
 ("A2_SH04",None,"your_desk","a top-down macro insert of a cracked office mug, a faded framed photo and a wall calendar full of crossed-out years","INSERT","top","static","day",True,False,
  "на столе всё та же треснувшая кружка, выцветшее фото и календарь, где год сменяет год без перемен."),
 ("A2_SH05","BOSS_BASE","open_floor","a medium shot of a heavyset balding boss with rolled-up sleeves clapping a hand on someone's shoulder, a chunky old watch on his wrist","MS","eye","static","day",False,False,
  "начальник хлопает тебя по плечу и называет надёжным, и ты годами носишь это слово как медаль."),
 ("A2_SH06","GEROY_MAIN","open_floor","a close-up of the man's face accepting the praise with a modest proud smile","CU","eye","push_in","day",False,False,
  "ты улыбаешься, потому что надёжный звучит почти как незаменимый, и эту разницу ты решаешь не замечать."),
 ("A2_SH07",None,"open_floor","a wide night view of the whole dark open office floor with a single desk lamp glowing in the distance","WS","eye","static","night",True,False,
  "в десять вечера на всём этаже горит одна лампа, и это твоя лампа, и ты этим даже гордишься."),
 ("A2_SH08","GEROY_MAIN","your_desk","a medium close-up of the man working alone late at his lit desk in the dark office","MCU","eye","push_in","night",False,False,
  "ты остаёшься после всех, доделываешь чужое, и тебе кажется, что без тебя тут всё развалится."),
 ("A2_SH09",None,"home_kitchen","a macro insert of a plate of cold dinner on a kitchen table, covered with an upturned bowl to keep it","ECU","top","static","night",True,False,
  "дома на кухне стоит накрытая тарелка с остывшим ужином, который тебе оставили и не дождались."),
 ("A2_SH10","WIFE_BASE","home_kitchen","a medium shot of a woman with dark auburn hair sitting alone at the kitchen table, a phone face down before her","MS","eye","static","night",False,False,
  "жена сидит за столом с телефоном экраном вниз и уже не спрашивает, во сколько ты сегодня будешь."),
 ("A2_SH11","GEROY_MAIN","home_hallway","a close-up of the man in the dim entry hall after midnight, loosening his tie, the access card still at his chest","CU","eye","static","night",False,False,
  "ты возвращаешься за полночь, в темноте стягиваешь галстук, и пропуск всё ещё висит у тебя на груди."),
 ("A2_SH12",None,"street_tower","a wide morning view of the glass office tower from the street, bare autumn trees, a grey commuting sky","WS","low","static","morning",True,False,
  "снова утро, снова та же башня, и ты уже не помнишь, сколько таких одинаковых утр прошло."),
 ("A2_SH13","GEROY_MAIN","open_floor","a medium close-up of the man shaking hands with an unseen younger colleague, a tight controlled smile","MCU","eye","static","day",False,False,
  "мимо тебя на повышение уходит парень, который пришёл на десять лет позже, и ты жмёшь ему руку."),
 ("A2_SH14","GEROY_MAIN","your_desk","a close-up of the man's face as he tells himself something, eyes lowered to his keyboard","CU","eye","push_in","day",False,False,
  "ты говоришь себе, что верность важнее должности, и сам не замечаешь, как оправдание становится привычкой."),
 ("A2_SH15","PALYCH_BASE","open_floor","a medium shot of a kindly older man with a grey moustache holding a battered steel thermos, talking warmly","MS","eye","static","day",False,False,
  "палыч с вечным термосом говорит, что отдал конторе тридцать лет, и ты слушаешь его как пример, а не как предупреждение."),
 ("A2_SH16",None,"open_floor","a macro insert of a battered steel thermos on a desk beside a small stack of yellowing long-service certificates","INSERT","top","static","day",True,False,
  "на полке стоит его термос рядом со стопкой грамот за выслугу, которые никто давно не читает."),
 ("A2_SH17","GEROY_MAIN","your_desk","a wide shot of the man filing papers at his desk, the wall calendar prominent behind him","WS","eye","static","day",False,False,
  "ты подшиваешь бумаги, год за годом, и на стенном календаре цифры меняются быстрее, чем ты успеваешь заметить."),
 ("A2_SH18","GEROY_MAIN","your_desk","a medium close-up of the man catching his own reflection in a dark switched-off monitor, greyer at the temples","MCU","eye","push_in","day",False,False,
  "в чёрном выключенном мониторе ты ловишь своё отражение и впервые видишь, как поседели виски."),
 ("A2_SH19","GEROY_MAIN","your_desk","a close-up of the tired man's face, the access card glowing faintly at the edge of frame","CU","eye","push_in","day",False,True,
  "ты уже не помнишь, кем ты был до этого пропуска, и кем стал бы, если бы однажды его снял."),
 ("A2_SH20",None,"open_floor","an extreme wide top-down view of the vast office floor, hundreds of identical desks in a grid","EWS","top","static","day",True,True,
  "сверху этот этаж — сотни одинаковых столов, и ты всего один из них, хоть и веришь, что особенный."),
]
if __name__=="__main__": seed_act("climb", PAL, S, render_mode="animated")
