# -*- coding: utf-8 -*-
"""donor A10 dasha + A11 coda. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_donor_A10A11.py"""
from _donor_engine import seed_act

P_DASHA="cold confrontation palette, one kitchen bulb and pale evening, two faces sharing the same eyes"
P_CODA="final hollow palette, a single low bulb over a table against deep night, quiet devastation"

DASHA=[
 ("A10_SH01","NIKA_OLD","front_door","a medium shot of the older woman opening her door to a young stranger on the landing","MS","eye","static","night",False,False,
  "ты открываешь дверь, и на пороге стоит девятнадцатилетняя девушка, которую ты никогда прежде не видела."),
 ("A10_SH02","DASHA_BASE","front_door","a medium close-up of a nineteen-year-old with auburn curls and pale blue eyes holding a yellow envelope","MCU","eye","static","night",False,True,
  "у неё рыжие вьющиеся волосы, жёлтый конверт в руках и твои собственные светло-голубые глаза."),
 ("A10_SH03","NIKA_OLD","front_door","a close-up of the older woman staring into the girl's eyes as into a mirror, unable to breathe","CU","eye","push_in","night",False,False,
  "ты смотришь в эти глаза, как в зеркало, отставшее от тебя на тридцать лет, и не можешь вдохнуть."),
 ("A10_SH04","DASHA_BASE","front_door","a medium shot of the nervous young woman asking a quiet question on the landing","MS","eye","static","night",False,False,
  "девушка называет своё имя, Даша, и тихо спрашивает, не делала ли ты когда-то донорство."),
 ("A10_SH05",None,None,"an extreme close-up macro insert of a yellow envelope of DNA match printouts held in young hands, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,True,
  "в жёлтом конверте у неё распечатки теста, где ты стоишь как совпадение с пометкой мать."),
 ("A10_SH06","NIKA_OLD","front_door","a close-up of the older woman unable to form the denial she rehearsed for years","CU","eye","static","night",False,False,
  "тридцать лет ты готовила слова отрицания, но перед этим лицом язык не поворачивается солгать."),
 ("A10_SH07","NIKA_OLD","kitchen_night","a medium shot of the older woman letting the girl into the kitchen, a jar on the shelf behind","MS","eye","static","night",False,False,
  "ты впускаешь её на кухню, где на полке стоит банка, и ставишь чайник дрожащими руками."),
 ("A10_SH08","DASHA_BASE","kitchen_night","a medium close-up of the young woman studying the older woman's face hungrily","MCU","eye","static","night",False,False,
  "даша разглядывает тебя жадно, ищет в твоём лице свои черты и находит их одну за другой."),
 ("A10_SH09","DASHA_BASE","kitchen_night","a close-up of the young woman speaking about her upbringing, searching","CU","eye","static","night",False,False,
  "она рассказывает, что росла в хорошей семье, но всегда хотела знать, от кого её глаза."),
 ("A10_SH10","NIKA_OLD","kitchen_night","a medium close-up of the older woman listening, guilt heavy on her face","MCU","eye","static","night",False,False,
  "ты слушаешь и понимаешь, что для неё ты не незнакомка, а половина всего, чем она является."),
 ("A10_SH11","DASHA_BASE","kitchen_night","a medium shot of the young woman explaining the sibling network she found","MS","eye","static","night",False,False,
  "даша говорит, что нашла по тесту уже больше тридцати братьев и сестёр по всей стране."),
 ("A10_SH12",None,None,"an extreme close-up macro insert of a phone screen showing a sibling group chat full of young faces, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,True,
  "она показывает телефон, где в общем чате десятки молодых лиц, и у каждого твои глаза."),
 ("A10_SH13","NIKA_OLD","kitchen_night","a close-up of the older woman as the abstract number turns into living people","CU","eye","static","night",False,False,
  "сорок три номерка из банки вдруг превращаются в живых людей, которые ищут друг друга и тебя."),
 ("A10_SH14","DASHA_BASE","kitchen_night","a medium close-up of the young woman asking why, hurt but not angry","MCU","eye","static","night",False,False,
  "она спрашивает без злости, только с болью, зачем ты делала это так много раз подряд."),
 ("A10_SH15","NIKA_OLD","kitchen_night","a close-up of the older woman with no good answer to give","CU","eye","static","night",False,False,
  "ты хочешь сказать про бедность, но вспоминаешь, что делала это просто ради лёгких денег."),
 ("A10_SH16",None,"kitchen_night","a wide view of the two women at a kitchen table with a glass jar of tabs on the shelf behind","WS","eye","static","night",True,True,
  "вы сидите за одним столом, а за спиной у тебя стоит банка с номерами всех её братьев."),
 ("A10_SH17","DASHA_BASE","kitchen_night","a medium shot of the young woman asking about family medical history","MS","eye","static","night",False,False,
  "даша расспрашивает про болезни в роду, потому что её дети однажды спросят про свою кровь."),
 ("A10_SH18","NIKA_OLD","kitchen_night","a medium close-up of the older woman answering honestly for the first time in her life","MCU","eye","static","night",False,False,
  "и ты впервые в жизни честно рассказываешь незнакомке всё о себе, потому что она имеет право."),
 ("A10_SH19","DASHA_BASE","kitchen_night","a close-up of the young woman, neither forgiving nor blaming, only needing to know","CU","eye","static","night",False,False,
  "она не прощает и не обвиняет, она просто хочет знать, чьё лицо носит с самого рождения."),
 ("A10_SH20","NIKA_OLD","kitchen_night","a close-up of the older woman seeing all she gave away in the girl before her","CU","eye","static","night",False,False,
  "и ты понимаешь, что вот она, твоя дочь по крови, сидит рядом и никогда не звала тебя мамой."),
 ("A10_SH21","DASHA_BASE","front_door","a medium shot of the young woman preparing to leave at the door","MS","eye","static","night",False,False,
  "перед уходом даша говорит, что остальные тоже хотят однажды увидеть своего донора живым."),
 ("A10_SH22",None,None,"an extreme close-up macro insert of a photograph and a phone number left on a kitchen table, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,True,
  "она оставляет на столе свою фотографию и номер телефона на случай, если ты когда-нибудь захочешь."),
 ("A10_SH23","NIKA_OLD","front_door","a medium shot of the older woman watching the girl descend the stairwell","MS","eye","static","night",False,False,
  "ты стоишь в дверях и смотришь ей вслед, как когда-то смотрела вслед уходящему Антону."),
 ("A10_SH24",None,"front_door","a wide view of an empty apartment landing after the girl has gone","WS","eye","static","night",True,False,
  "дверь закрывается, шаги стихают на лестнице, и ты остаёшься одна с её фотографией и банкой."),
 ("A10_SH25","NIKA_OLD","kitchen_night","a close-up of the older woman at the table holding the girl's photograph, finally letting herself weep","CU","eye","push_in","night",False,False,
  "ты садишься за стол, берёшь фотографию девочки со своими глазами и наконец разрешаешь себе заплакать."),
 ("A10_SH26","NIKA_OLD","kitchen_night","a medium close-up of the woman of forty-eight beside the jar and the photograph","MCU","eye","static","night",False,True,
  "тебе сорок восемь, у тебя сорок три ребёнка по стране, и первая из них только что ушла."),
]

CODA=[
 ("A11_SH01",None,"kitchen_night","a wide establishing view of a dim kitchen at night, a table under one low bulb with a jar and a photo","WS","eye","push_in","night",True,False,
  "тебе сорок восемь, и вот вся твоя жизнь на одном кухонном столе под тусклой лампой."),
 ("A11_SH02",None,None,"an extreme close-up macro insert of a glass jar of forty-three paper number tabs beside a single photograph of a pale-eyed girl, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,True,
  "стеклянная банка с сорока тремя номерками и одна фотография девочки с твоими глазами."),
 ("A11_SH03","NIKA_OLD","kitchen_night","a medium close-up of the older woman looking down at the jar and the photograph","MCU","eye","static","night",False,False,
  "сорок три ребёнка носят твоё лицо по стране, которая так и не узнала твоего имени."),
 ("A11_SH04","NIKA_OLD","kitchen_night","a close-up of the older woman's worn face in the low light","CU","eye","static","night",False,False,
  "и ни один из них не твой, потому что своих ты распродала по клеткам, ещё их не родив."),
 ("A11_SH05",None,None,"an extreme close-up macro insert of a pale-blue enamel forget-me-not brooch resting beside the glass jar, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,False,
  "рядом лежит брошка-незабудка от матери, и только теперь ты понимаешь её горькую насмешку."),
 ("A11_SH06","NIKA_OLD","kitchen_night","a medium shot of the older woman picking up the girl's photograph in both hands","MS","eye","static","night",False,False,
  "ты берёшь фотографию Даши и думаешь, наберёшь ли ты когда-нибудь тот оставленный номер."),
 ("A11_SH07","NIKA_OLD","kitchen_night","a medium close-up of the older woman turning to address the viewer directly","MCU","eye","static","night",False,False,
  "если ты сейчас думаешь, что лёгкие деньги ничего у тебя не отнимут, послушай меня внимательно."),
 ("A11_SH08","NIKA_OLD","kitchen_night","a close-up of the older woman speaking straight to the viewer, worn and honest","CU","eye","push_in","night",False,False,
  "тело помнит всё, и однажды оно предъявит счёт, который нельзя оплатить никаким конвертом."),
 ("A11_SH09",None,"city_street","a wide view of a vast sleeping city at night, countless lit windows","WS","eye","static","night",True,False,
  "где-то в этом огромном городе спят твои дети, и ты для них — только совпадение в тесте."),
 ("A11_SH10","NIKA_OLD","kitchen_night","a close-up of the older woman with a final quiet understanding","CU","eye","static","night",False,False,
  "ты пряталась за номером всю жизнь, а оказалось, что за этим номером стояли живые люди."),
 ("A11_SH11",None,None,"an extreme close-up macro insert of a glass jar of paper tabs and a photograph side by side under a lamp, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,True,
  "банка с номерками и фотография дочери — вот и всё, что ты собрала за сорок восемь лет."),
 ("A11_SH12","NIKA_OLD","kitchen_night","a medium close-up of the older woman addressing the viewer with quiet urgency","MCU","eye","push_in","night",False,False,
  "подумай об этом раньше, чем я, пока твоё тело ещё умеет прощать, и не повторяй моих ошибок."),
 ("A11_SH13",None,"kitchen_night","a wide pulling-out view of the woman alone at the table as the light lowers","WS","eye","pull_out","night",True,False,
  "ты гасишь лампу на кухне, но история, которую ты только что услышала, уже никуда не денется."),
 ("A11_SH14",None,None,"an extreme close-up macro insert of a glass jar of paper tabs fading into darkness on a table, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,True,
  "эта история вымышлена, все совпадения случайны, и всё же где-то она происходит прямо сейчас."),
]

if __name__=="__main__":
    seed_act("dasha", P_DASHA, DASHA, render_mode="static")
    seed_act("coda",  P_CODA, CODA, render_mode="static")
