# -*- coding: utf-8 -*-
"""surrogate A6 bond + A7 third. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_surrogate_A6A7.py"""
from _surrogate_engine import seed_act

P_B="quiet aching palette, warm lamplight and deep private shadow, tender and heavy"
P_3="hardening palette, cold clinic white and grey with a last flicker of warmth going out"

BOND=[
 ("A6_SH01",None,"small_town_street","a wide view of a poor grey small-town street of low buildings under a flat sky, worn and ordinary","WS","eye","push_in","day",True,False,
  "между заказами проходит время, ты растишь Мишу, берёшься за любую работу, но денег снова не хватает."),
 ("A6_SH02","HERO_MID","poor_flat","a medium shot of the woman of thirty-three laying a tin box's contents out on a table by lamplight","MS","eye","static","night",False,False,
  "по вечерам ты достаёшь жестяную коробку и раскладываешь на столе два браслета и две пинетки."),
 ("A6_SH03",None,None,"an extreme close-up macro insert of two hospital bracelets and two tiny booties laid out on a table, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "ты придумала им имена, которых им никто не давал, и шепчешь их только когда никого нет."),
 ("A6_SH04","HERO_MID","poor_flat","a close-up of the woman's face full of hidden longing over the box","CU","eye","push_in","night",False,False,
  "где-то растут двое детей с твоими глазами, и ты никогда не узнаешь, какими они станут."),
 ("A6_SH05",None,"small_town_street","a wide view of an ordinary street where a blurred child plays in the distance, seen from far off","WS","eye","pan_left","day",True,False,
  "иногда на улице ты вглядываешься в чужих малышей и ищешь в них знакомые черты."),
 ("A6_SH06","HERO_MID","poor_flat","a medium close-up of the tired woman pressing a hand to her aching back","MCU","eye","static","day",False,False,
  "тело после двух родов уже не то, спина болит, врачи говорят про осложнения и советуют беречься."),
 ("A6_SH07","HERO_MID","poor_flat","a close-up of the woman's weary face, unable to afford rest","CU","eye","static","day",False,False,
  "но беречься — это роскошь, которой у тебя нет, потому что счета не умеют ждать."),
 ("A6_SH08",None,None,"an extreme close-up macro insert of a small medicine cabinet shelf crowded with pill packets, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "в аптечке всё больше таблеток, а на теле всё больше следов от того, что ты делала."),
 ("A6_SH09","HERO_MID","poor_flat","a medium shot of the woman watching over her quiet growing son from a doorway","MS","eye","static","day",False,False,
  "Миша растёт хорошим, тихим мальчиком, и ты боишься, что однажды он узнает, чем ты платила за его жизнь."),
 ("A6_SH10","HERO_MID","kitchen_night","a close-up of the woman hiding the tin box away, the secret weighing on her","CU","eye","push_in","night",False,False,
  "ты прячешь коробку всё дальше, но тайна давит, и держать её в себе всё тяжелее год от года."),
 ("A6_SH11",None,"kitchen_night","a wide view of a dim poor kitchen at night with bills and a tin box on the table under a low bulb","WS","eye","static","night",True,False,
  "ночная кухня знает про тебя всё, здесь ты считаешь деньги и здесь оплакиваешь отданных детей."),
 ("A6_SH12","HERO_MID","kitchen_night","a medium close-up of the woman trying to justify herself in the low light","MCU","eye","static","night",False,False,
  "ты убеждаешь себя, что была хорошей суррогатной матерью, что дала бездетным семьям счастье."),
 ("A6_SH13","HERO_MID","kitchen_night","a close-up of the woman's face as the justification fails her","CU","eye","static","night",False,False,
  "но по ночам это звучит как оправдание, а не как правда, и ты сама это чувствуешь."),
 ("A6_SH14",None,None,"an extreme close-up macro insert of an empty photo frame lying face-up on a table, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "у тебя нет ни одной их фотографии, ни адреса, ничего, только два браслета и два имени в голове."),
 ("A6_SH15","HERO_MID","poor_flat","a medium shot of the woman facing a fresh stack of debts in the poor flat","MS","eye","static","day",False,False,
  "деньги за второго давно ушли, долги подросли снова, и знакомая яма опять раскрывается под ногами."),
 ("A6_SH16",None,"small_town_street","a wide view of a poorer, emptier grey small-town street under an overcast sky","WS","eye","static","day",True,False,
  "посёлок нищает вместе с тобой, работы всё меньше, а цены всё выше каждый месяц."),
 ("A6_SH17","HERO_MID","poor_flat","a medium close-up of the woman looking at a ringing phone in her hand","MCU","eye","static","day",False,False,
  "и однажды телефон звонит сам, это Инна Сергеевна, и ты понимаешь, зачем она звонит."),
 ("A6_SH18","HERO_MID","poor_flat","a medium shot of the woman holding a finger over the reject button, then answering","MS","eye","static","day",False,False,
  "ты знаешь, что надо отказаться, кладёшь палец над кнопкой сброса и всё-таки отвечаешь."),
 ("A6_SH19",None,None,"an extreme close-up macro insert of a ringing mobile phone screen showing an incoming call, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "на экране светится знакомый номер, и этот звонок решает всё, ещё до того, как ты сказала слово."),
 ("A6_SH20","HERO_MID","poor_flat","a close-up of the woman of thirty-three answering the call, sealing the third time","CU","eye","push_in","day",False,True,
  "тебе тридцать три, ты снимаешь трубку, и этим движением подписываешь себе третий, самый страшный раз."),
]

THIRD=[
 ("A7_SH01",None,"coordinator_office","a wide view of the tidy agency office with a glass desk and a city window, cool and businesslike","WS","eye","push_in","day",True,False,
  "в тридцать пять ты в третий раз в этом офисе, и Инна Сергеевна больше не притворяется, что заботится о тебе."),
 ("A7_SH02","COORD_BASE","coordinator_office","a medium close-up of the coordinator speaking plainly across the desk, a tablet in hand","MCU","over","static","day",False,False,
  "она говорит прямо, что это самая крупная сумма из всех, богатая пара платит за тебя как за редкость."),
 ("A7_SH03","HERO_MID","coordinator_office","a close-up of the woman of thirty-five weighing an enormous offer","CU","eye","static","day",False,False,
  "сумма такая, что можно закрыть все долги, починить крышу и отложить Мише на учёбу."),
 ("A7_SH04",None,None,"an extreme close-up macro insert of a thick contract lying on a glass desk with a pen, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "на столе договор толще прежних, и цифры в нём такие, что кружится голова."),
 ("A7_SH05","COORD_BASE","coordinator_office","a medium shot of the coordinator pressing gently, flattering the woman","MS","over","static","day",False,False,
  "Инна Сергеевна давит мягко, говорит, что ты профессионал, что твоё тело создано для этого."),
 ("A7_SH06","HERO_MID","coordinator_office","a close-up of the woman realizing she is only an incubator to them","CU","eye","push_in","day",False,False,
  "ты слышишь слово профессионал, и до тебя доходит, что для них ты давно не человек, а инкубатор."),
 ("A7_SH07",None,"coordinator_office","a wide view through the office window over a wealthy indifferent city, cool daylight","WS","eye","static","day",True,False,
  "за окном чужой богатый город, которому нужны твои роды, но не нужна ты сама."),
 ("A7_SH08","HERO_MID","coordinator_office","a medium close-up of the woman hesitating longer than before, her body warning her","MCU","eye","static","day",False,False,
  "ты колеблешься дольше, чем в прошлые разы, потому что тело уже устало и предупреждает тебя болью."),
 ("A7_SH09","HERO_MID","kitchen_night","a close-up of the woman doing the grim arithmetic again at night","CU","eye","static","night",False,False,
  "врачи говорили не рисковать больше, но крыша течёт, а сын взрослеет, и ты снова считаешь."),
 ("A7_SH10",None,None,"an extreme close-up macro insert of a bucket catching drips under a water-stained leaking ceiling, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "дома ты подставляешь ведро под текущую крышу, и отказаться от таких денег уже не выходит."),
 ("A7_SH11","HERO_MID","kitchen_night","a medium shot of the woman watching her sleeping son at night, deciding","MS","eye","static","night",False,False,
  "ночью ты смотришь на спящего Мишу и решаешь, что ещё один раз тебя не убьёт."),
 ("A7_SH12","HERO_MID","kitchen_night","a close-up of the woman's face pushing away her own broken promises","CU","eye","static","night",False,False,
  "ты гонишь мысль, что каждый раз обещала это в последний, и каждый раз возвращалась сюда."),
 ("A7_SH13",None,"small_town_street","a wide view of a sleeping grey small-town street at night, a leaking roofline against the sky","WS","eye","static","night",True,False,
  "посёлок спит, крыша течёт, коробка с двумя браслетами ждёт третьего, и ты уже всё решила."),
 ("A7_SH14","COORD_BASE","coordinator_office","a medium close-up of the coordinator shaking the woman's hand, pleased with the deal","MCU","over","static","day",False,False,
  "Инна Сергеевна довольна, жмёт тебе руку и говорит, что заказчики будут очень, очень благодарны."),
 ("A7_SH15",None,None,"an extreme close-up macro insert of a pen signing a thick contract for the third time, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,True,
  "ты в третий раз ставишь подпись, и теперь это уже не беда, а просто твоя работа."),
 ("A7_SH16","HERO_MID","coordinator_office","a close-up of the woman's face as the last honest part of her goes quiet","CU","eye","push_in","day",False,False,
  "где-то внутри последняя честная часть тебя окончательно замолкает и уступает место холодному расчёту."),
 ("A7_SH17","HERO_MID","clinic_room","a medium shot of the woman on the clinic couch again, feeling almost nothing now","MS","eye","static","day",False,False,
  "снова клиника, снова перенос, только теперь ты почти ничего не чувствуешь, кроме тупой усталости."),
 ("A7_SH18",None,None,"an extreme close-up macro insert of a hand resting on an early pregnant belly under a plain dress, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "третий чужой ребёнок поселяется внутри, и на этот раз ты запрещаешь себе его любить."),
 ("A7_SH19","HERO_MID","kitchen_night","a medium shot of the woman reluctantly knitting a third tiny bootie by lamplight, hating herself","MS","eye","static","night",False,False,
  "но запрет не работает, и ты снова вяжешь пинетку, третью, и ненавидишь себя за эту слабость."),
 ("A7_SH20","HERO_MID","poor_flat","a close-up of the woman carrying the pregnancy hard, her body failing, jaw set","CU","eye","static","day",False,False,
  "ты носишь его тяжело, тело сдаёт, врачи хмурятся, но ты доводишь до срока, стиснув зубы."),
 ("A7_SH21",None,"clinic_corridor","a wide view of a hushed clinic corridor with empty chairs and closed doors, cold light","WS","eye","static","day",True,False,
  "месяцы тянутся дольше прежних, и впервые тебе по-настоящему страшно за собственное здоровье."),
 ("A7_SH22","HERO_MID","poor_flat","a close-up of the pregnant woman of thirty-five, worn and afraid, awaiting the third child","CU","eye","push_in","day",False,True,
  "тебе тридцать пять, ты ждёшь третьего чужого ребёнка, и не знаешь, что он заберёт больше, чем деньги."),
]

if __name__=="__main__":
    seed_act("bond",  P_B, BOND,  render_mode="static")
    seed_act("third", P_3, THIRD, render_mode="static")
