# -*- coding: utf-8 -*-
"""announcer batch E: catastrophe (synthetic voice replaces her) + aftermath (anonymous passenger) + coda. static."""
from _announcer_engine import seed_act

PAL_CAT="cold sterile palette, blue server glow and harsh fluorescent against old marble, the warmth drained out"
CA=[
 ("CA_SH01",None,"automation_room","grey server racks switching on, blue indicators flaring to life in the cold room","EWS","eye","push_in","day",True,True,
  "в две тысячи двадцать шестом за стеной включают серые шкафы, и вокзал получает новый голос."),
 ("CA_SH02","ANNOUNCER_OLD","announcer_booth","young managers in suits coming up to the booth to tell the old announcer the news","MS","eye","static","day",False,False,
  "к тебе в будку поднимаются молодые в галстуках и говорят, что объявления теперь автоматические."),
 ("CA_SH03","ANNOUNCER_OLD","announcer_booth","close on the old announcer not yet understanding the word automatic","MCU","eye","static","day",False,False,
  "тебе шестьдесят один, и ты не сразу понимаешь, что значит автоматические, ведь голос нужен живой."),
 ("CA_SH04",None,"automation_room","a flat speaker on a server rack playing a recorded station announcement","INSERT","eye","push_in","day",True,True,
  "из новых колонок звучит объявление, и ты холодеешь, потому что это твой голос, а говоришь не ты."),
 ("CA_SH05","ANNOUNCER_OLD","announcer_booth","close on the old announcer's horror of recognition","CU","eye","push_in","day",False,False,
  "они собрали из твоих записей машину, что говорит твоим голосом любые фразы, и ты ей не нужна."),
 ("CA_SH06","ANNOUNCER_OLD","announcer_booth","the old announcer asked to record the missing phrases for the archive","MS","eye","static","day",False,False,
  "тебя просят начитать недостающие фразы для архива, и ты понимаешь, что копаешь себе могилу голосом."),
 ("CA_SH07","ANNOUNCER_OLD","announcer_booth","close on the old announcer feeling the full betrayal","CU","eye","push_in","day",False,False,
  "ты сорок лет берегла этот голос для лучшего дня, а его забрали, чтобы заменить им тебя саму."),
 ("CA_SH08",None,"automation_room","the automation system speaking, a soundwave on a monitor","INSERT","eye","push_in","day",True,False,
  "машина произносит твой трёхнотный гонг и твоё внимание на первый путь, ровно, без единой запинки."),
 ("CA_SH09","ANNOUNCER_OLD","announcer_booth","the old announcer's live microphone being switched off, she sits redundant","MCU","eye","static","day",False,False,
  "тебе говорят спасибо за службу, отключают твой микрофон, и впервые за сорок лет он молчит."),
 ("CA_SH10","ANNOUNCER_OLD","announcer_booth","close on the old announcer pressing the dead chime button","CU","eye","push_in","day",False,False,
  "ты нажимаешь латунную кнопку гонга, а по залу плывёт не твой гонг, а его запись, уже без тебя."),
 ("CA_SH11","ANNOUNCER_OLD","concourse_hall","the old woman standing in the hall hearing her own voice announce without her","WS","high","static","day",False,True,
  "ты спускаешься в зал и слышишь сверху свой голос, что объявляет поезда, как будто ты ещё там."),
 ("CA_SH12","ANNOUNCER_OLD","concourse_hall","extreme close on the old woman's face, the uncanny horror of her own disembodied voice","ECU","eye","push_in","day",False,True,
  "это твой голос, твоё тепло, твои паузы, а тебя в будке нет, и никто этого даже не заметил."),
 ("CA_SH13","ANNOUNCER_OLD","concourse_hall","passengers moving to her recorded voice, oblivious to the woman among them","MS","eye","static","day",False,False,
  "пассажиры идут на твой голос, как ходили всегда, и не знают, что женщина рядом и есть этот голос."),
 ("CA_SH14","ANNOUNCER_OLD","concourse_hall","close on the old woman, alive and unneeded","CU","eye","push_in","day",False,False,
  "ты стоишь среди них, живая и ненужная, а мёртвая запись делает твою работу лучше тебя."),
 ("CA_SH15","BLIND_BASE","concourse_hall","the blind man losing his way, misled by the synthetic voice","WS","eye","static","day",False,False,
  "слепой, что ходил на твой голос, теперь сбивается, потому что в записи нет того, что вело его."),
 ("CA_SH16","ANNOUNCER_OLD","concourse_hall","close on the old woman reaching for a microphone that is dead","CU","eye","push_in","day",False,False,
  "ты тянешься к микрофону, чтобы вывести его, а микрофон мёртв, и ты ничем не можешь помочь."),
 ("CA_SH17","ANNOUNCER_OLD","concourse_hall","the old woman guiding the blind man by her bare voice without any microphone","MCU","eye","static","day",False,False,
  "тогда ты подходишь и ведёшь его живым голосом без микрофона, в последний раз, рукой и словом."),
 ("CA_SH18","BLIND_BASE","concourse_hall","close on the blind man recognising the real her, finally meeting the voice","CU","eye","push_in","day",False,True,
  "и слепой узнаёт тебя, настоящую, без динамика, и говорит, что у голоса всё-таки есть лицо."),
 ("CA_SH19","ANNOUNCER_OLD","concourse_hall","close on the old woman, the one recognition coming too late","CU","eye","static","day",False,False,
  "единственный, кто узнал тебя за сорок лет, тебя не видит, и это горше всего на белом свете."),
 ("CA_SH20","ANNOUNCER_OLD","announcer_booth","the old woman packing forty years into one cardboard box","WS","high","static","day",False,False,
  "тебе дают расчёт и просят освободить будку, и ты собираешь сорок лет в одну картонную коробку."),
 ("CA_SH21",None,"announcer_booth","the faded deep-red scarf taken down from its nail beside the microphone","INSERT","eye","push_in","day",False,True,
  "ты снимаешь с гвоздя выцветший тёмно-красный шарф, который так и не надела ни разу на сцену."),
 ("CA_SH22","ANNOUNCER_OLD","announcer_booth","the old woman taking a last look down at the hall from the booth","MCU","high","static","day",False,False,
  "ты в последний раз смотришь из стеклянной будки на зал, что слушал тебя всю твою долгую жизнь."),
 ("CA_SH23","ANNOUNCER_OLD","announcer_booth","close on the old woman, the hall living on by her voice without her","CU","eye","push_in","day",False,False,
  "а зал внизу живёт по твоему голосу и не знает, что тебя в нём уже нет, и больше не будет."),
 ("CA_SH24",None,"automation_room","the server racks humming, holding her voice","INSERT","eye","push_in","day",True,True,
  "твой голос остаётся в серых шкафах, бессмертный и пустой, и будет звучать, когда тебя не станет."),
 ("CA_SH25","ANNOUNCER_OLD","concourse_hall","the old woman walking out through the hall to the sound of her own announcement","MS","eye","track","day",False,False,
  "ты идёшь к выходу, и твой собственный голос объявляет посадку, провожая тебя из твоей же жизни."),
 ("CA_SH26","ANNOUNCER_OLD","concourse_hall","close on the old woman leaving under her own voice as if it were a stranger's","CU","eye","push_in","day",False,False,
  "ты выходишь под свой голос, как под чужой, и впервые он не ведёт тебя, а просто звучит вслед."),
 ("CA_SH27",None,"station_facade","the terminus facade as she leaves, her voice fading behind the doors","WS","eye","static","day",True,False,
  "за дверями вокзала твой голос стихает, а внутри он будет звучать ещё годы, без всякой тебя."),
 ("CA_SH28","ANNOUNCER_OLD","station_facade","the old woman standing on the station steps, redundant","MCU","low","static","day",False,False,
  "ты стоишь на ступенях, и впервые тебя не ждёт ни смена, ни микрофон, ни поезд, совсем никто."),
 ("CA_SH29","ANNOUNCER_OLD","station_facade","close on the old woman, the second silence of her life","CU","eye","push_in","day",False,False,
  "в двадцать четыре у тебя забрали сцену, в шестьдесят один забрали и голос, оставив одну запись."),
 ("CA_SH30","ANNOUNCER_OLD","concourse_hall","the old woman sneaking back into the night hall, the booth dark above","WS","high","static","night",False,False,
  "ночью ты возвращаешься в пустой зал, а будка темна, и за тебя поёт расписание мёртвым голосом."),
 ("CA_SH31",None,"announcer_booth","the dark empty booth at night with its dead microphone","INSERT","eye","push_in","night",False,True,
  "ты больше не можешь подняться в будку, и впервые пустому залу ночью некому петь вживую."),
 ("CA_SH32","ANNOUNCER_OLD","concourse_hall","the old woman trying to sing in the hall as her recorded voice talks over her","MCU","low","static","night",False,False,
  "ты пробуешь запеть в зале сама, и сверху твой записанный голос объявляет поезд и заглушает тебя."),
 ("CA_SH33","ANNOUNCER_OLD","concourse_hall","close on the old woman falling silent, broken","CU","eye","push_in","night",False,False,
  "ты замолкаешь, потому что спорить с собственным голосом, что звучит без тебя, невозможно и страшно."),
 ("CA_SH34",None,"concourse_hall","the hall living on under the recorded voice, indifferent","WS","high","static","day",True,False,
  "вокзал гудит, объявляет, прощается и встречает твоим голосом, а тебя в нём больше нет совсем."),
 ("CA_SH35","ANNOUNCER_OLD","concourse_hall","the old woman leaving the hall for the last time under her own recorded voice","MCU","eye","track","day",False,False,
  "ты уходишь из зала навсегда под звук собственного голоса, и он даже не сбивается тебе вслед."),
 ("CA_SH36",None,"automation_room","the system blinking, holding her voice forever","INSERT","eye","push_in","night",True,True,
  "в серых шкафах твой голос будет жить дольше тебя, и это вся твоя жизнь, отданная вокзалу."),
]

PAL_AFT="muted farewell palette, soft grey daylight through train windows, a quiet thinning warmth"
AF=[
 ("AF_SH01",None,"train_interior","a passenger carriage with landscape sliding past the large windows, soft grey light","EWS","eye","push_in","day",True,False,
  "теперь ты ездишь поездами просто пассажиркой, и впервые в жизни у тебя есть билет в один конец."),
 ("AF_SH02","ANNOUNCER_OLD","train_interior","an old woman sitting anonymously by the train window among other passengers","MCU","eye","static","day",False,False,
  "ты сидишь у окна в обычном вагоне, и никто вокруг не знает, что рядом едет голос вокзала."),
 ("AF_SH03","ANNOUNCER_OLD","train_interior","close on the old woman who spent forty years seeing others off, now travelling herself","CU","eye","push_in","day",False,False,
  "ты сорок лет провожала чужие поезда, а теперь впервые едешь сама, и провожать тебя некому."),
 ("AF_SH04",None,"train_interior","a round ceiling loudspeaker grille in the carriage roof","MS","low","push_in","day",True,True,
  "под потолком вагона круглый динамик, такой же, как те, в которые ты говорила всю свою жизнь."),
 ("AF_SH05","ANNOUNCER_OLD","train_interior","close on the old woman hearing her own recorded voice announce her stop","CU","eye","push_in","day",False,False,
  "и вдруг из динамика твой собственный голос объявляет твою станцию, спокойно, без тебя самой."),
 ("AF_SH06","ANNOUNCER_OLD","train_interior","the old woman softly answering her own voice as fellow passengers glance over","MCU","eye","static","day",False,False,
  "ты отвечаешь своему голосу тихо, как старой подруге, и соседи косятся на странную старуху."),
 ("AF_SH07","ANNOUNCER_OLD","platform_day","the old woman stepping off at her stop, her recorded voice thanking passengers behind her","WS","eye","static","day",False,False,
  "ты выходишь на своей станции, и твой голос за спиной благодарит пассажиров за поездку."),
 ("AF_SH08","ANNOUNCER_OLD","platform_day","close on the old woman, the strange comfort of her voice everywhere","CU","eye","push_in","day",False,False,
  "твой голос провожает тебя на каждой станции страны, и это всё, что от тебя осталось при тебе."),
 ("AF_SH09",None,"departures_board","a modern digital departures board without split-flaps, silent and flat","INSERT","eye","push_in","day",True,False,
  "на вокзалах теперь цифровые табло без щелчков, и живых дикторов не осталось уже почти нигде."),
 ("AF_SH10","ANNOUNCER_OLD","concourse_hall","the old woman revisiting her own great station as a passenger","MCU","eye","static","day",False,False,
  "однажды ты приезжаешь на свой вокзал пассажиркой и стоишь в зале, который вела сорок лет."),
 ("AF_SH11","ANNOUNCER_OLD","concourse_hall","close on the old woman listening to herself overhead while passengers pass","CU","eye","push_in","day",False,False,
  "сверху звучит твой голос, тот же самый, и пассажиры идут на него, как шли всегда, мимо тебя."),
 ("AF_SH12","ANNOUNCER_OLD","concourse_hall","the old woman looking up at the dark empty booth","WS","low","static","day",False,False,
  "ты смотришь наверх, на тёмную пустую будку, из которой больше никто живой не говорит."),
 ("AF_SH13",None,"announcer_booth","the booth behind glass, dark, the microphone under a film of dust like an exhibit","INSERT","eye","push_in","day",True,True,
  "будку за стеклом теперь не открывают, и микрофон в ней стоит, как экспонат, под слоем пыли."),
 ("AF_SH14","ANNOUNCER_OLD","concourse_hall","a small child looking up at the ceiling speaker as the old woman watches","MCU","low","static","day",False,False,
  "маленький мальчик задирает голову к динамику, как когда-то другой, и верит, что это ангел."),
 ("AF_SH15","ANNOUNCER_OLD","concourse_hall","close on the old woman choosing not to break the child's belief","CU","eye","push_in","day",False,False,
  "ты хочешь сказать ему, что ангел это просто усталая женщина, и не говоришь, пусть верит."),
 ("AF_SH16","ANNOUNCER_OLD","concourse_hall","the old woman leaving her own station for the last time","WS","high","static","day",False,False,
  "ты уходишь из своего зала пассажиркой, и твой голос объявляет вслед чужой поезд, а не твой."),
 ("AF_SH17","ANNOUNCER_OLD","train_interior","the old woman riding on, anonymous, peace and grief together","MCU","eye","static","day",False,False,
  "ты едешь дальше, из города в город, и всюду тебя встречает и провожает твой же голос."),
 ("AF_SH18","ANNOUNCER_OLD","train_interior","close on the old woman, the whole bargain of her life laid bare","CU","eye","push_in","day",False,False,
  "ты прожила жизнь голосом для всех и осталась пассажиркой, которую не объявляет никто живой."),
 ("AF_SH19",None,"train_interior","platforms sliding past the train window, the ceiling speaker above","INSERT","eye","push_in","day",True,False,
  "за окном бегут перроны, на которых ты никогда не стояла, и голос твой бежит впереди тебя."),
 ("AF_SH20","ANNOUNCER_OLD","train_interior","the old woman taking the faded deep-red scarf from her bag","MCU","eye","static","day",False,False,
  "ты достаёшь из сумки выцветший тёмно-красный шарф и наконец повязываешь его себе на горло."),
 ("AF_SH21","ANNOUNCER_OLD","train_interior","close on the scarf worn at last for herself alone","CU","eye","push_in","day",False,True,
  "ты надеваешь его не для сцены и не для смены, а просто для себя, впервые за все сорок лет."),
 ("AF_SH22","ANNOUNCER_OLD","platform_night","the old woman stepping onto a night platform in an unknown city, her voice left behind","WS","eye","static","night",False,False,
  "ты выходишь на ночном перроне незнакомого города, и твой голос остаётся позади, в вагоне."),
 ("AF_SH23",None,"platform_night","a deserted night platform under a single lamp, total silence","INSERT","eye","push_in","night",True,False,
  "перрон пуст, и впервые за всю жизнь над тобой не звучит ни одного объявления, только тишина."),
 ("AF_SH24","ANNOUNCER_OLD","platform_night","close on the old woman in the silence she never had","CU","eye","push_in","night",False,False,
  "ты стоишь в тишине, которой у тебя не было сорок лет, и не знаешь, радоваться ей или плакать."),
 ("AF_SH25","ANNOUNCER_OLD","platform_night","the old woman opening her mouth and singing for herself, no microphone","MCU","low","static","night",False,False,
  "и тогда ты впервые поёшь не залу, не записи, а ночному небу, тихо, только для себя одной."),
 ("AF_SH26","ANNOUNCER_OLD","platform_night","a small figure singing alone on the empty night platform","WS","low","push_in","night",False,True,
  "никто не слышит, и впервые тебе всё равно, потому что поёшь ты наконец не для чужих ушей."),
 ("AF_SH27","ANNOUNCER_OLD","platform_night","close on the old woman at peace, only her own voice left","CU","eye","push_in","night",False,False,
  "тебе шестьдесят один, у тебя нет ни сцены, ни будки, ни эфира, и есть только твой собственный голос."),
 ("AF_SH28",None,"platform_night","the single platform lamp, mist, a breath fading in the cold","INSERT","eye","static","night",True,False,
  "твой живой голос тает в ночном воздухе без эха и без динамиков, и это и есть ты, настоящая."),
 ("AF_SH29","ANNOUNCER_OLD","train_interior","the old woman boarding the next train, the journey her own at last","MCU","eye","static","night",False,False,
  "ты садишься в следующий поезд и едешь, куда хочешь сама, без расписания, в первый и последний раз."),
 ("AF_SH30",None,"train_interior","the ceiling speaker overhead, her recorded voice faint and endless","INSERT","low","push_in","night",True,True,
  "а из динамика всё звучит твой голос, бессмертный, и ведёт чужие жизни туда, куда ты не доехала."),
]

PAL_CODA="final hushed palette, a faint speaker glow against deep dark, fading to silence"
CO=[
 ("CO_SH01","ANNOUNCER_OLD","train_interior","the old woman addressing the viewer directly from the train seat","MCU","eye","push_in","night",False,False,
  "если ты сейчас думаешь, что тебя ещё узнают и услышат, послушай старуху из этого вагона."),
 ("CO_SH02","ANNOUNCER_OLD","train_interior","close direct address on the old woman's tired eyes","CU","eye","push_in","night",False,False,
  "не отдавай свой голос целиком чужому расписанию, его запишут и оставят тебя совсем ни с чем."),
 ("CO_SH03",None,"concourse_hall","the great hall with the recorded voice pouring from the speakers","WS","high","static","day",True,False,
  "я говорила со всем городом сорок лет и не сказала ничего своего, ни разу, по-настоящему."),
 ("CO_SH04",None,"announcer_booth","the dark booth and its dead microphone","INSERT","eye","push_in","night",False,True,
  "я берегла голос для лучшего дня, и лучший день так и не настал, а голос забрали без меня."),
 ("CO_SH05","ANNOUNCER_OLD","train_interior","the old woman speaking with weary hard-won wisdom","MCU","eye","static","night",False,False,
  "не будь голосом без человека, лицом без имени, оправой чужих встреч и расставаний."),
 ("CO_SH06","ANNOUNCER_OLD","train_interior","close on the old woman, the heart of her plea","CU","eye","push_in","night",False,False,
  "выйди на свою сцену, спой своё, скажи своё, пока тебя слышат, а не записывают на потом."),
 ("CO_SH07","ANNOUNCER_OLD","platform_night","the old woman singing alone on the empty platform once more","WS","low","push_in","night",False,False,
  "я пою теперь только себе, на пустых перронах, и это мой первый настоящий в жизни концерт."),
 ("CO_SH08","ANNOUNCER_OLD","platform_night","close on the old woman, gentle and final","CU","eye","push_in","night",False,False,
  "и если однажды твой голос зазвучит без тебя, не пугайся, лишь бы ты успел спеть своё."),
 ("CO_SH09",None,"announcer_booth","extreme close on the worn brass chime button, untouched in the dark booth","INSERT","top","push_in","night",False,True,
  "латунная кнопка гонга в пустой будке стёрта моими пальцами, а нажимает её теперь машина."),
 ("CO_SH10","ANNOUNCER_OLD","train_interior","the old woman riding on into the dark, announcing her own way","MCU","eye","static","night",False,False,
  "а я еду дальше, пассажиркой, в город, которого нет в расписании, и сама себе объявляю путь."),
 ("CO_SH11","ANNOUNCER_OLD","train_interior","a final close direct look from the old woman","CU","eye","push_in","night",False,False,
  "береги свой голос, слышишь, и свой день, и своё лицо, не меняй их на любовь чужой толпы."),
 ("CO_SH12",None,"concourse_hall","the empty hall living on by her voice, the lights dimming toward black","WS","high","pull_out","night",True,True,
  "огромный зал живёт моим голосом без меня, и это вся моя жизнь, отданная чужим поездам."),
 ("CO_SH13",None,"announcer_booth","the dead microphone alone in the dark glass booth","INSERT","eye","push_in","night",False,True,
  "остаётся только мёртвый микрофон в тёмной будке и мой голос в серых шкафах, теперь навсегда."),
 ("CO_SH14",None,"announcer_booth","extreme close on the worn-smooth brass chime button","ECU","top","push_in","night",False,True,
  "кнопка гонга стёрта добела за сорок лет, и моего имени на ней нет, как нигде на свете."),
 ("CO_SH15",None,"platform_night","an empty night platform fading, the last train gone into the dark","WS","eye","static","night",True,False,
  "последний поезд уходит в темноту, и мой голос объявляет его уже совсем без меня."),
 ("CO_SH16",None,"concourse_hall","a near-black frame, a faint glow of a loudspeaker dying","INSERT","eye","push_in","night",False,False,
  "эта история вымышлена, все совпадения с реальными людьми и судьбами совершенно случайны."),
 ("CO_SH17",None,"concourse_hall","a dark frame, the faint last shape of the hall","INSERT","eye","static","night",False,False,
  "не отдавай свою жизнь чужому расписанию и не повторяй чужих ошибок, очень тебя прошу."),
 ("CO_SH18",None,"platform_night","the empty night platform fading fully to black, a last faint lamp","WS","eye","pull_out","night",True,True,
  "береги себя, слышишь, и выйди на свою сцену, пока в зале ещё кто-то живой тебя слышит."),
]

seed_act("catastrophe", PAL_CAT,  CA, render_mode="static")
seed_act("aftermath",   PAL_AFT,  AF, render_mode="static")
seed_act("coda",        PAL_CODA, CO, render_mode="static")
