# -*- coding: utf-8 -*-
"""car_flipper — акт 4 (29, покупатель вернулся) и акт 5 (31–34, своя площадка)."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _car_flipper_engine import seed_act

P4 = "an overcast palette of flat grey light, cold concrete and dull green painted metal"
P5 = "a bright commercial palette of clean white light, polished car paint and coloured plastic bunting"

RETURN = [
 ("A4_SH01", None, "market_old",
  "a car market on a flat overcast morning seen from high above, four short rows kept noticeably cleaner than the rest, a hosed strip of asphalt drying between them",
  "EWS","high","pan_left","day",True,False,
  "в двадцать девять у тебя четыре точки, но своей площадки ещё нет."),
 ("A4_SH02", "VIK_ADULT", "market_old",
  "Viktor walking the length of his own row with a folder pressed under one arm, checking wipers and door handles as he goes",
  "MS","eye","track","day",False,False,
  "ты приезжаешь на рынок к семи и уезжаешь последним, каждый день без выходных."),
 ("A4_SH03", "VIK_ADULT", "market_old",
  "Viktor's face in profile going still for a second as he recognises a car somewhere off frame",
  "CU","low","static","day",False,False,
  "за полгода до этого ты продал одному человеку машину с проваренными порогами."),
 ("A4_SH04", None, "market_old",
  "a mud-splashed saloon parked crosswise across a market row with its doors shut and its nose blocking the aisle, other cars lined up neatly behind it",
  "WS","low","static","day",True,False,
  "он пригоняет её обратно в среду и ставит поперёк всего твоего ряда."),
 ("A4_SH05", None, "market_old",
  "the bottom edge of a car door swollen and split open, a broken slab of grey filler hanging away from bubbling metal beneath it",
  "INSERT","low","push_in","day",True,True,
  "нижний край двери вспучило, и шпатлёвка отошла от металла одним целым куском."),
 ("A4_SH06", "VIK_ADULT", "market_old",
  "Viktor walking towards the blocked aisle at an unhurried pace, wiping his hands on a rag and folding it away as he comes",
  "MCU","eye","static","day",False,False,
  "ты подходишь спокойно, потому что за десять лет ты научился подходить спокойно."),
 ("A4_SH07", "VIK_ADULT", "market_old",
  "an unnamed angry man in a padded jacket filling one side of the foreground from behind, his arm thrown out towards the car, Viktor beyond him standing square and unmoved",
  "OTS","over","static","day",False,False,
  "он говорит, что ты продал ему гнилое ведро и требует деньги назад."),
 ("A4_SH08", "VIK_ADULT", "market_old",
  "Viktor's face entirely level, his eyebrows lifting a fraction as he asks a question back",
  "CU","eye","static","day",False,False,
  "ты спрашиваешь его, где в договоре написано, что машина была совсем без ремонта."),
 ("A4_SH09", "VIK_ADULT", "market_old",
  "Viktor opening the folder against his forearm and turning it round so the printed page faces outward",
  "MCU","low","static","day",False,False,
  "в договоре этого нет, потому что ты пишешь договоры уже десять лет."),
 ("A4_SH10", ("VIK_ADULT","GENA_OLD"), "market_old",
  "Viktor holds the open folder out at arm's length while Gena watches from three steps away, leaning on a bonnet with the unlit cigarette between his fingers",
  "WS","eye","static","day",False,False,
  "Гена стоит в трёх шагах, курит и не вмешивается ни одним словом."),
 ("A4_SH11", "GENA_OLD", "market_old",
  "Gena's face relaxed and faintly approving, one eye narrowed, the corner of his mouth flat",
  "CU","eye","static","day",False,False,
  "он смотрит на тебя так, как обычно смотрят на хорошо выученный урок."),
 ("A4_SH12", "VIK_ADULT", "market_old",
  "Viktor closing the folder in one movement and pointing with two fingers towards the market gate",
  "MS","eye","static","day",False,False,
  "ты говоришь ему уходить, и голос у тебя при этом совершенно ровный."),
 ("A4_SH13", None, "market_old",
  "a market aisle cleared again with a fresh set of tyre tracks curving out of it towards the gate, the neat rows closed up on both sides",
  "WS","high","static","day",True,False,
  "он уезжает через сорок минут и больше никогда в этот ряд не возвращается."),
 ("A4_SH14", "LENA_MID", "market_old",
  "Lena standing at the end of the neighbouring row with a cloth shopping bag held in both hands in front of her, staying where the row ends",
  "MCU","eye","static","day",False,False,
  "Лена стоит у соседнего ряда с сумкой, в которой лежит твой обед."),
 ("A4_SH15", "LENA_MID", "market_old",
  "Lena's face holding very still, her eyes fixed on something past the camera, her jaw tight",
  "CU","eye","push_in","day",False,False,
  "она слышала всё от первого слова до последнего и ничего не говорит."),
 ("A4_SH16", ("VIK_ADULT","LENA_MID"), "market_old",
  "Viktor takes the cloth bag by its handles from Lena, who lets go of it and keeps her hands exactly where they were",
  "MS","eye","static","day",False,False,
  "ты берёшь у неё сумку, и вы стоите молча дольше, чем нужно."),
 ("A4_SH17", None, "flat_kitchen",
  "a kitchen at night with two cups on the oilcloth, the lamp low, a chair on one side pushed back at an angle",
  "WS","eye","static","night",True,False,
  "вечером на кухне она первый раз спрашивает тебя про то, что видела."),
 ("A4_SH18", "LENA_MID", "flat_kitchen",
  "Lena sitting with both elbows on the table and her chin on her linked hands, asking in a low even voice",
  "MCU","eye","static","night",False,False,
  "она спрашивает, сколько таких людей будет приезжать к тебе теперь каждый год."),
 ("A4_SH19", "VIK_ADULT", "flat_kitchen",
  "Viktor's face lit from one side by the kitchen lamp, answering flatly with his eyes on the tablecloth",
  "CU","low","static","night",False,True,
  "ты отвечаешь, что никого не заставлял покупать и никому ничего не обещал."),
 ("A4_SH20", "LENA_MID", "flat_kitchen",
  "Lena leaning back off the table with her arms folded, saying one short sentence and stopping",
  "MCU","eye","static","night",False,False,
  "она говорит, что ты обещал, потому что сказал, что брал бы себе."),
 ("A4_SH21", "VIK_ADULT", "flat_kitchen",
  "Viktor's jaw working once, his eyes going to the dark window instead of to her",
  "CU","eye","static","night",False,False,
  "ты злишься при этом не на неё, а на то, что она права."),
 ("A4_SH22", None, "flat_room",
  "a child's corner of a room at night with a night light on the skirting, toy cars lined up along the edge of a rug and a small jacket over a chair back",
  "WS","low","static","night",True,False,
  "в соседней комнате спит пятилетний Денис, и поэтому вы говорите совсем тихо."),
 ("A4_SH23", "OBJ:contract", None,
  "a kitchen table under a low lamp before dawn",
  "INSERT","top","push_in","interior",True,False,
  "утром ты дописываешь в бланк договора ещё две строчки очень мелким шрифтом."),
 ("A4_SH24", "VIK_ADULT", "flat_kitchen",
  "Viktor sitting alone at the kitchen table before sunrise with a ruler and a pen, ruling a line under new small print",
  "MS","eye","static","dawn",False,False,
  "ты сидишь за кухонным столом и правишь бланк, пока все ещё спят."),
 ("A4_SH25", "VIK_ADULT", "flat_kitchen",
  "Viktor's face close in the dawn window light, reading his own added line back to himself",
  "CU","eye","push_in","dawn",False,False,
  "после этих двух строчек вернуть тебе машину обратно станет уже почти невозможно."),
 ("A4_SH26", None, "flat_kitchen",
  "a kitchen table seen wide in early light, covered end to end with squared stacks of blank printed forms and two cardboard folders",
  "WS","high","static","dawn",True,False,
  "ты печатаешь двести таких бланков сразу и раскладываешь их по двум папкам."),
 ("A4_SH27", "VIK_ADULT", "flat_kitchen",
  "Viktor pushing back from the table and standing up with the folders under his arm, already looking at the door",
  "MCU","low","static","dawn",False,False,
  "в двадцать девять лет ты перестаёшь бояться тех, кто приезжает к тебе обратно."),
 ("A4_SH28", None, "dawn_road",
  "a wide flat country road at sunrise seen from very high, a single set of headlights moving along it towards the horizon",
  "EWS","high","pull_out","dawn",True,False,
  "и с этого утра ты начинаешь думать не о машинах, а об объёмах."),
]

LOT = [
 ("A5_SH01", None, "dealer_lot",
  "a bare rented strip of ground beside a suburban road with fresh white parking lines painted on new paving slabs and an empty banner frame at the entrance",
  "WS","eye","static","day",True,False,
  "в тридцать один ты берёшь в аренду кусок земли у выездной дороги."),
 ("A5_SH02", "VIK_ADULT", "dealer_lot",
  "Viktor walking backwards along a wire with both arms up, clipping triangles of coloured plastic onto it one after another",
  "MS","eye","track","day",False,False,
  "ты сам размечаешь места краской и сам вешаешь флажки на натянутую проволоку."),
 ("A5_SH03", None, "dealer_lot",
  "a line of coloured plastic bunting triangles snapping in the wind against a white sky, the wire sagging between two short masts",
  "INSERT","low","static","day",True,False,
  "пластиковые флажки над площадкой хлопают весь день и слышны с самой дороги."),
 ("A5_SH04", "VIK_ADULT", "dealer_lot",
  "Viktor's face tilted up towards the banner frame, measuring it with his eyes, mouth moving on a silent number",
  "CU","low","push_in","day",False,False,
  "человеку с дороги важно, чтобы место выглядело так, будто оно давно тут."),
 ("A5_SH05", None, "office_container",
  "the inside of a site container office newly fitted out, a laminate desk with a kettle at one end, a numbered key cabinet screwed to the wall and a blind half open",
  "WS","eye","static","day",True,False,
  "в вагончике ты ставишь стол, чайник и железный шкафчик с сорока ключами."),
 ("A5_SH06", "VIK_ADULT", "office_container",
  "Viktor standing at the container window with the blind hooked up on one finger, counting the cars outside",
  "MCU","eye","static","day",False,False,
  "через полгода у тебя тут стоит четырнадцать машин, и все они чужие."),
 ("A5_SH07", "OBJ:keys", None,
  "a numbered hook on the inside of an open key cabinet",
  "ECU","low","static","interior",True,False,
  "каждый ключ висит на своём крючке, и на каждом бумажка с ценой."),
 ("A5_SH08", ("VIK_ADULT","GENA_OLD"), "dealer_lot",
  "Viktor shows Gena the rows with his hands still in his pockets while Gena turns slowly on the spot to take the whole lot in",
  "MS","eye","static","day",False,False,
  "Гена приезжает посмотреть и говорит, что ты уже окончательно вырос из рынка."),
 ("A5_SH09", "GENA_OLD", "dealer_lot",
  "Gena's face squinting against the floodlight mast, half impressed and half wary, the unlit cigarette still behind his ear",
  "CU","eye","static","day",False,False,
  "сам он остаётся в четвёртом ряду, потому что боится больших серьёзных бумаг."),
 ("A5_SH10", None, "dealer_lot",
  "a used-car lot from above in the middle of the day, two rows of washed cars with water still drying around their wheels and hoses coiled at the edge",
  "WS","high","pan_right","day",True,False,
  "у тебя работают двое мойщиков, и оба моложе тебя на десять лет."),
 ("A5_SH11", "DEN_KID", "dealer_lot",
  "Denis crouched at a front wheel with a sponge in both hands and a bucket tipped beside him, working the spokes one by one",
  "MS","eye","static","day",False,False,
  "по субботам на площадку приходит Денис, ему девять, и он моет колёса."),
 ("A5_SH12", "DEN_KID", "dealer_lot",
  "Denis's face turned up with wet hair stuck to his forehead, mouthing numbers as he counts something in his fist",
  "CU","low","static","day",False,False,
  "ты платишь ему за каждое вымытое колесо и заставляешь пересчитывать деньги вслух."),
 ("A5_SH13", ("VIK_ADULT","DEN_KID"), "dealer_lot",
  "Viktor stands over an open driver's door while Denis goes up on tiptoe beside him with his chin on the sill, looking in at the dashboard",
  "MCU","eye","static","day",False,False,
  "он спрашивает, почему у одной машины пробег меньше, чем у совсем новой."),
 ("A5_SH14", "VIK_ADULT", "dealer_lot",
  "Viktor's face bent down towards the boy, explaining something easily with a small shrug",
  "CU","eye","static","day",False,True,
  "ты говоришь ему, что цифры на панели ничего не значат, и он верит."),
 ("A5_SH15", None, "dealer_lot",
  "a car lot at dusk with the floodlights just switched off, the bunting hanging still and the paving slabs going flat grey",
  "WS","low","static","dusk",True,False,
  "вечером ты гасишь прожекторы, и площадка снова становится обычным тёмным куском асфальта."),
 ("A5_SH16", "VIK_ADULT", "office_container",
  "Viktor sitting on the wrong side of his own desk with his hands flat on his knees, waiting while somebody off frame turns pages",
  "MS","eye","static","day",False,False,
  "в тридцать три к тебе приходит проверка и сидит в вагончике четыре часа."),
 ("A5_SH17", None, "office_container",
  "a desk covered with opened carbon-copy contracts laid out in a fan, three of them pulled aside and squared into a separate pile",
  "INSERT","top","static","day",True,False,
  "они поднимают одиннадцать твоих договоров и находят в трёх совершенно одинаковый пробег."),
 ("A5_SH18", "VIK_ADULT", "office_container",
  "Viktor's face taking the news with everything held still, only his eyes travelling once across the desk",
  "CU","low","static","day",False,False,
  "штраф ты платишь в тот же самый день, и штраф этот совсем небольшой."),
 ("A5_SH19", "VIK_ADULT", "office_container",
  "Viktor standing alone in the container after they have gone, one hand still resting on the closed folder",
  "MCU","eye","push_in","day",False,False,
  "но теперь твоя фамилия стоит в списке, и это уже не исправить."),
 ("A5_SH20", None, "dealer_lot",
  "a used-car lot in flat afternoon light with every space filled and the office container door standing open at the far end",
  "WS","eye","static","day",True,False,
  "оформлять машины на себя тебе больше нельзя, а торговать надо всё равно."),
 ("A5_SH21", ("VIK_ADULT","LENA_MID"), "flat_kitchen",
  "Viktor slides three printed sheets across the oilcloth to Lena and holds out a pen, and she takes the pen from him with her eyes on his face",
  "MS","eye","static","dusk",False,False,
  "вечером ты кладёшь перед Леной три листа и молча даёшь ей ручку."),
 ("A5_SH22", "LENA_MID", "flat_kitchen",
  "Lena's face glancing up once with mild question in it, already reaching for the paper",
  "CU","eye","static","dusk",False,False,
  "она спрашивает, что это такое, и ты отвечаешь, что это просто аренда."),
 ("A5_SH23", None, "flat_kitchen",
  "a hand-signed line at the bottom of a printed sheet on an oilcloth table, the ballpoint still resting across the paper",
  "ECU","top","static","dusk",True,True,
  "она подписывает не читая, потому что за пятнадцать лет привыкла тебе верить."),
 ("A5_SH24", "VIK_ADULT", "flat_kitchen",
  "Viktor gathering the signed sheets and tapping their edges square against the table, his face turned away from her",
  "MCU","low","static","dusk",False,False,
  "с этого вечера всё, что ты делаешь, юридически делает уже твоя жена."),
 ("A5_SH25", None, "dealer_lot",
  "a car lot photographed from high above at midday, cars packed nose-out in three full rows with a delivery truck backing in at the gate",
  "WS","high","static","day",True,False,
  "за один следующий год через твою площадку проходит сто девяносто чужих машин."),
 ("A5_SH26", "VIK_ADULT", "dealer_lot",
  "Viktor walking the rows with a clipboard, ticking boxes as he walks straight past each car",
  "MS","eye","track","day",False,False,
  "ты уже не помнишь ни одной из них по отдельности, только цифры."),
 ("A5_SH27", "VIK_ADULT", "office_container",
  "Viktor at the desk speaking into a phone tucked under his jaw while writing a figure on a pad",
  "MCU","eye","static","day",False,False,
  "в тридцать четыре года ты впервые называешь приезжающих к тебе людей потоком."),
 ("A5_SH28", "OBJ:driver", None,
  "an opened desk drawer lined with old receipts",
  "INSERT","top","static","interior",True,False,
  "отвёртка с синей изолентой лежит теперь в верхнем ящике твоего рабочего стола."),
 ("A5_SH29", "VIK_ADULT", "office_container",
  "Viktor pushing the drawer shut with his knee while still holding the phone, his eyes on the window",
  "MCU","low","static","day",False,False,
  "ты почти не берёшь её в руки, потому что это делают другие."),
 ("A5_SH30", None, "dealer_lot",
  "a lit used-car lot at dusk seen from very high, the floodlights on, the road beyond it carrying a steady line of headlights",
  "EWS","high","pull_out","dusk",True,False,
  "и этот год оказывается самым спокойным из всех, что у тебя были."),
]

if __name__ == "__main__":
    seed_act("first_return", P4, RETURN)
    seed_act("lot",          P5, LOT)
