# -*- coding: utf-8 -*-
"""webcam A4 daughter + A5 the_cost. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_webcam_A4A5.py"""
from _webcam_engine import seed_act

P_D="warmer real-life palette, soft daytime domestic tones cut by cold neon at night, a divided life"
P_C="draining palette, harsh ring-light white over grey exhaustion, neon glow gone joyless"

DAU=[
 ("A4_SH01",None,"own_apartment","a wide view of a modern apartment in soft daytime light, ordinary and warm, away from the ring light","WS","eye","push_in","day",True,False,
  "в двадцать шесть в твоей жизни появляется обычный парень, который не из этого мира и ничего про Алису не знает."),
 ("A4_SH02",None,"own_apartment","a medium close-up of an ordinary young man smiling warmly in a sunlit apartment, unaware","MCU","over","static","day",True,False,
  "он думает, что ты работаешь из дома в поддержке, и ты долго не решаешься сказать правду."),
 ("A4_SH03","HERO_MID","own_apartment","a close-up of the woman relaxed and bare-faced, feeling like her real self","CU","eye","static","day",False,False,
  "с ним ты снова чувствуешь себя просто Настей, без камеры, без чокера, без роли."),
 ("A4_SH04","HERO_MID","own_apartment","a medium shot of the woman realizing she is pregnant, money suddenly not the point","MS","eye","static","day",False,False,
  "ты беременеешь, и впервые деньги и донаты кажутся тебе не главным в жизни."),
 ("A4_SH05",None,None,"an extreme close-up macro insert of a positive pregnancy test on a clean surface, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "тест показывает две полоски, и ты решаешь оставить ребёнка и попробовать нормальную жизнь."),
 ("A4_SH06",None,"own_apartment","a medium close-up of an ordinary young man's face hardening as he learns the truth, reaching for a bag","MCU","over","static","day",True,False,
  "но когда ты наконец признаёшься ему, чем зарабатываешь, его лицо меняется, и он собирает вещи."),
 ("A4_SH07","HERO_MID","own_apartment","a close-up of the woman watching him leave, unable to argue","CU","eye","static","day",False,False,
  "он не может принять, что тысячи мужчин видели то, что он считал только своим, и уходит."),
 ("A4_SH08",None,"city_street_neon","a wide view of a grey daytime street where a man's blurred figure walks away, not looking back","WS","eye","static","day",True,False,
  "он уходит, как уходят многие, и ты остаёшься беременной, одна, но с квартирой и с работой."),
 ("A4_SH09","HERO_MID","kitchen_home","a medium shot of the woman holding her newborn daughter in a warm home, tender and awed","MS","eye","static","day",False,False,
  "ты рожаешь дочь и называешь её Лизой, и держишь на руках кого-то наконец по-настоящему своего."),
 ("A4_SH10","DAU_CHILD","kitchen_home","a close-up of a tiny brown-haired child gripping her mother's finger, bright and oblivious","CU","high","static","day",False,False,
  "крошечная Лиза сжимает твой палец, и ты клянёшься, что она никогда не узнает про Алису."),
 ("A4_SH11",None,None,"an extreme close-up macro insert of a soft plush toy rabbit on a child's blanket, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "ты покупаешь ей плюшевого зайца, и это первое, что принадлежит только вашей маленькой семье."),
 ("A4_SH12","HERO_MID","own_apartment","a medium shot of the woman drawn back toward the ring light within months of giving birth","MS","eye","static","night",False,False,
  "но декрет короткий, накоплений нет, и уже через пару месяцев кольцевая лампа снова зовёт тебя."),
 ("A4_SH13","HERO_MID","stream_room","a close-up of the woman streaming at night, dividing herself between two mothers","CU","eye","static","night",False,False,
  "ты возвращаешься в эфир по ночам, пока Лиза спит, и делишь сутки между двумя разными матерями."),
 ("A4_SH14",None,None,"an extreme close-up macro insert of a baby monitor standing beside a ring light on a desk, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "на столе рядом стоят радионяня и кольцевая лампа, и это вся твоя двойная жизнь в одном кадре."),
 ("A4_SH15","HERO_MID","stream_room","a medium close-up of the woman in ring-light glow, the sleeping child just beyond the wall","MCU","eye","static","night",False,False,
  "днём ты обычная мама на площадке, а ночью Алиса для тысяч чужих мужчин за стеной от спящей дочери."),
 ("A4_SH16","HERO_MID","kitchen_home","a close-up of the woman justifying the work as being for her daughter","CU","eye","static","day",False,False,
  "ты говоришь себе, что делаешь это ради Лизы, чтобы у неё было всё, чего не было у тебя."),
 ("A4_SH17",None,"kitchen_home","a wide view of a warm ordinary kitchen with a child's drawings and a rabbit cup on the table","WS","eye","static","day",True,False,
  "на кухне детские рисунки и чашка с зайцем, обычная тёплая жизнь, ради которой ты и держишься."),
 ("A4_SH18","MOTHER_BASE","mother_home","a medium close-up of the grey-haired grandmother in a headscarf, helping happily, knowing nothing","MCU","eye","static","day",False,False,
  "мать помогает с внучкой и до сих пор уверена, что дочь работает в приличной удалённой поддержке."),
 ("A4_SH19","HERO_MID","own_apartment","a close-up of the woman living in constant fear of exposure","CU","eye","push_in","day",False,False,
  "ты живёшь в постоянном страхе, что однажды кто-то узнает Алису и расскажет матери или Лизе."),
 ("A4_SH20",None,None,"an extreme close-up macro insert of two mobile phones side by side on a table, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "у тебя два телефона, две переписки, два лица, и склеивать их всё труднее с каждым месяцем."),
 ("A4_SH21","HERO_MID","own_apartment","a medium shot of the exhausted woman unable to stop, a child depending on her now","MS","eye","static","day",False,False,
  "ты всё чаще устаёшь до пустоты, но остановиться не можешь, ведь на тебе теперь ещё и дочь."),
 ("A4_SH22","HERO_MID","own_apartment","a close-up of the woman of twenty-six holding a secret that grows with her child","CU","eye","push_in","day",False,True,
  "тебе двадцать шесть, у тебя есть Лиза и тайна, и эта тайна растёт вместе с ней."),
]

COST=[
 ("A5_SH01",None,"stream_room","a wide view of a stream room under harsh ring-light white, a webcam and screens, industrial and cold","WS","eye","push_in","night",True,False,
  "в двадцать семь эфиры давно перестали быть игрой, это конвейер, на котором ты и товар, и работница."),
 ("A5_SH02","HERO_MID","stream_room","a medium shot of the woman performing desire on camera for faceless viewers, hollow behind the smile","MS","eye","static","night",False,False,
  "каждый вечер ты изображаешь желание, интерес и любовь к людям, которых никогда не видела."),
 ("A5_SH03","HERO_MID","stream_room","a close-up of the woman's performing face, laughing at unfunny jokes","CU","eye","static","night",False,False,
  "ты научилась стонать имена, которые не помнишь, и смеяться над шутками, которые не смешные."),
 ("A5_SH04",None,None,"an extreme close-up macro insert of a glowing chat panel full of demanding messages, text unreadable, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "зрители пишут, что им нужно, и ты выполняешь, пока это в границах, а границы сдвигаются потихоньку."),
 ("A5_SH05","MANAGER_BASE","studio_office","a medium close-up of the manager pressing her to give more, dashboards glowing behind him","MCU","over","static","day",False,False,
  "Стас говорит, что конкуренция растёт, что надо давать больше, иначе зритель уйдёт к другой."),
 ("A5_SH06","HERO_MID","studio_office","a close-up of the woman realizing her share keeps shrinking","CU","eye","static","day",False,False,
  "его процент растёт, платформа берёт своё, и из каждого доната тебе достаётся всё меньше."),
 ("A5_SH07",None,None,"an extreme close-up macro insert of a payout breakdown on a screen showing a small remaining share, numbers unreadable, filling the frame in sharp focus, shallow depth of field","ECU","top","static","day",True,False,
  "ты считаешь и понимаешь, что работаешь всё больше, а на руках остаётся всё меньше денег."),
 ("A5_SH08","HERO_MID","stream_room","a medium shot of the woman trying to go independent, her viewer count collapsing","MS","eye","static","night",False,False,
  "ты пробуешь уйти с платформы, но без Стаса и его студии охваты падают почти до нуля."),
 ("A5_SH09","HERO_MID","stream_room","a close-up of the woman grasping she is a replaceable cog","CU","eye","push_in","night",False,False,
  "оказывается, ты не хозяйка своего дела, а винтик в чужой машине, которая крутится без тебя."),
 ("A5_SH10",None,"studio_office","a wide view of a cam-studio floor of glowing monitors and ring lights, rows of identical setups","WS","eye","pan_right","day",True,False,
  "студия гудит мониторами, десятки девушек в свете ламп, и все они легко заменяемы, включая тебя."),
 ("A5_SH11","PODRUGA_BASE","club_bar","a medium close-up of the jaded jet-black-bob woman warning her over a vape in a dim bar","MCU","over","static","night",False,False,
  "Рита говорит, что копить надо было раньше, что после тридцати в этом деле начинается спуск."),
 ("A5_SH12","HERO_MID","club_bar","a close-up of the woman brushing it off while quietly doing the maths","CU","eye","static","night",False,False,
  "ты отмахиваешься, но по ночам считаешь, сколько ещё лет камера будет тебя кормить."),
 ("A5_SH13",None,None,"an extreme close-up macro insert of a wall calendar with a birthday circled, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "дни рождения ты встречаешь в эфире, потому что праздничные стримы приносят больше всего донатов."),
 ("A5_SH14","HERO_MID","bedroom_dark","a medium shot of the woman removing the choker and makeup after a shift, feeling nothing","MS","eye","static","night",False,False,
  "после смены ты снимаешь чокер, смываешь Алису и не чувствуешь ни радости, ни отдыха, только пустоту."),
 ("A5_SH15","HERO_MID","bedroom_dark","a close-up of the woman's numb exhausted face in the dark","CU","eye","static","night",False,False,
  "близость, которую ты продаёшь тысячам, в собственной постели давно стала тебе противна."),
 ("A5_SH16",None,None,"an extreme close-up macro insert of cold uneaten food and pill packets on a night table, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "ты плохо спишь, ешь на ходу, глушишь тревогу таблетками и списываешь всё на усталость."),
 ("A5_SH17","HERO_MID","stream_room","a medium close-up of the woman wanting to quit but trapped by need","MCU","eye","static","night",False,False,
  "ты хочешь остановиться, но у тебя дочь, аренда, привычка тратить, и ничего, кроме камеры, ты не умеешь."),
 ("A5_SH18","HERO_MID","stream_room","a close-up of the woman promising to quit as she reaches for the switch again","CU","eye","static","night",False,False,
  "каждый раз, гася лампу, ты обещаешь себе бросить, и каждый вечер снова щёлкаешь выключателем."),
 ("A5_SH19",None,None,"an extreme close-up macro insert of a finger clicking a ring-light switch, the white light flooding on, filling the frame in sharp focus, shallow depth of field","ECU","eye","static","night",True,False,
  "щелчок кольцевой лампы стал звуком, от которого тебя уже подташнивает, но ты жмёшь на него снова."),
 ("A5_SH20",None,"bedroom_dark","a wide view of a dark bedroom at dawn, a cooling ring light and a child's door ajar beyond","WS","eye","static","night",True,False,
  "за окном светает, дочь скоро проснётся, а ты только заканчиваешь ночную смену для чужих мужчин."),
 ("A5_SH21","HERO_MID","kitchen_home","a medium shot of the woman making breakfast for her child with the same smile she sold at night","MS","eye","static","day",False,False,
  "утром ты варишь Лизе кашу с той же улыбкой, что дарила ночью незнакомцам, и это пугает тебя."),
 ("A5_SH22","HERO_MID","kitchen_home","a close-up of the woman of twenty-seven caught in a trap of her own making","CU","eye","push_in","day",False,True,
  "тебе двадцать семь, ты в ловушке, которую построила сама, и ключа от неё у тебя нет."),
]

if __name__=="__main__":
    seed_act("daughter", P_D, DAU,  render_mode="static")
    seed_act("the_cost", P_C, COST, render_mode="static")
