# -*- coding: utf-8 -*-
"""mascot batch B: act04_her + act05_family + act06_rising (render static)."""
from _mascot_engine import seed_act

PAL_HER="warm fairground-romance palette, soft string-light gold and dusk violet, tender and a little magical"
A4=[
 ("M4_SH01","MASCOT","fairground","a big grinning plush mascot dancing at a county fair at dusk, string lights glowing, a small crowd delighted","WS","eye","push_in","dusk",False,False,
  "тебе двадцать четыре, и на летней ярмарке ты пляшешь в костюме, и в толпе стоит она, и смеётся."),
 ("M4_SH02","WIFE","fairground","a warm young woman with dark hair laughing and clapping at a mascot's antics under string lights, captivated","MCU","eye","static","dusk",False,False,
  "молодая женщина с тёплыми глазами хохочет над твоими ужимками, и тебе хочется танцевать только для неё."),
 ("M4_SH03","MASCOT","fairground","the plush mascot offering a paper flower to a delighted young woman, playful and shy at once","MS","eye","static","dusk",False,False,
  "ты в кукле осмеливаешься на то, на что без неё не смог бы, протягиваешь ей бумажный цветок с ярмарки."),
 ("M4_SH04","WIFE","fairground","close on the young woman's charmed face accepting a paper flower from the mascot, blushing","CU","eye","push_in","dusk",False,False,
  "она берёт цветок, и говорит кукле, ты самый милый, кого я тут видела, и сердце у тебя заходится."),
 ("M4_SH05",None,"mask_interior","inside the mascot head, the young man's joyful nervous face watching the woman through the eye-mesh","INSERT","eye","push_in","dusk",False,True,
  "сквозь сетку ты смотришь на неё, и впервые тебе хочется снять голову, и впервые тебе страшно это сделать."),
 ("M4_SH06","MAN_YOUNG","fairground","a thin young man having just removed the mascot head, awkward and sweating, trying to talk to the woman","MS","eye","static","night",False,False,
  "после смены ты находишь её, уже без костюма, и хочешь сказать, это был я, но язык немеет, как в детстве."),
 ("M4_SH07","WIFE","fairground","the young woman politely not recognising the awkward thin man before her, looking around for the mascot","MCU","eye","static","night",False,False,
  "она вежливо тебе кивает, и оглядывается, ищет глазами куклу, а не тебя, и ты понимаешь свою беду."),
 ("M4_SH08","MAN_YOUNG","fairground","close on the young man's crushed face realising she liked the mascot, not him","CU","low","push_in","night",False,False,
  "ей понравился он, весёлый зверь, а не ты, тихий и потный, и это знакомо тебе с самого детства."),
 ("M4_SH09","MASCOT","fairground","the next evening, the mascot deliberately seeking the young woman out in the fair crowd, hopeful","WS","eye","track","dusk",False,False,
  "и ты придумываешь хитрость, на следующий вечер снова надеваешь костюм, и снова ищешь её в толпе."),
 ("M4_SH10","MASCOT","fairground","the mascot miming a shy conversation with the laughing young woman by the ferris wheel, gentle","MS","eye","static","dusk",False,False,
  "ты ухаживаешь за ней из-под маски, жестами, без слов, и ей это нравится, и вы видитесь каждый вечер."),
 ("M4_SH11","WIFE","fairground","the young woman talking warmly to the silent mascot as if to a friend, trusting the costume","MCU","over","static","dusk",False,False,
  "она рассказывает кукле всё, ведь кукла молчит и слушает, и не осудит, и тебе так легко быть этим зверем."),
 ("M4_SH12",None,"mask_interior","inside the head, the man's tender face listening to her through the foam, sweat and a soft smile","ECU","eye","push_in","dusk",False,True,
  "ты слушаешь её изнутри, и влюбляешься, и впервые жалеешь, что она любит зверя, а не того, кто внутри."),
 ("M4_SH13","MAN_YOUNG","fairground","the young man gathering courage to remove the head in front of her, hand on the mascot's neck","MS","eye","static","night",False,False,
  "однажды ты решаешься, и снимаешь при ней голову, и говоришь дрожащим голосом, это всё время был я."),
 ("M4_SH14","WIFE","fairground","the young woman startled, then studying the thin shy man's face, uncertain, recalculating","CU","eye","push_in","night",False,False,
  "она долго смотрит на твоё настоящее лицо, и ты ждёшь, что она уйдёт, как уходили все до неё."),
 ("M4_SH15","WIFE","fairground","the woman slowly softening, taking the shy man's hand, choosing the man inside the costume","MCU","eye","static","night",False,False,
  "но она вдруг улыбается, и говорит, так вот ты какой, и берёт тебя за руку, твою настоящую руку."),
 ("M4_SH16","MAN_YOUNG","fairground","close on the young man's overwhelmed face being seen and accepted for the first time, tears","CU","eye","push_in","night",False,True,
  "впервые в жизни кто-то выбрал тебя, а не маску, и ты не знаешь, как с этим быть, и просто плачешь."),
 ("M4_SH17",None,"city_summer","a warm lit diner window at night seen from a quiet street, two figures inside at a booth talking","WS","eye","push_in","night",True,False,
  "вы сидите в закусочной до утра, и ты говоришь больше, чем за всю прошлую жизнь, потому что она слушает."),
 ("M4_SH18","WIFE","family_kitchen","the woman laughing with the young man over coffee in a small kitchen, easy and warm, morning light","MS","eye","static","day",False,False,
  "она смеётся над тем, какой ты неуклюжий без костюма, и тебе не обидно, тебе впервые хорошо без маски."),
 ("M4_SH19","MAN_YOUNG","fairground","the young man and woman walking the emptying fairground hand in hand at night, the mascot suit in a bag","WS","low","track","night",False,False,
  "вы гуляете по гаснущей ярмарке, и костюм лежит в сумке у тебя за спиной, и ты думаешь, может, он мне больше не нужен."),
 ("M4_SH20","MAN_YOUNG","family_kitchen","close on the young man's hopeful face, daring to imagine a life as himself, soft daylight","CU","eye","push_in","day",False,False,
  "ты впервые мечтаешь жить без маски, быть просто собой рядом с ней, и эта мысль кажется тебе огромной."),
 ("M4_SH21",None,"city_summer","a small jewellery-shop window at dusk, a row of cheap rings under a light, a young man's reflection","INSERT","eye","push_in","dusk",False,False,
  "ты копишь на кольцо, простое, дешёвое, и репетируешь предложение перед зеркалом, без всякого костюма."),
 ("M4_SH22","MAN_YOUNG","fairground","the young man proposing to the woman by the lit ferris wheel, kneeling, the suit bag set aside","MS","low","static","dusk",False,True,
  "ты делаешь ей предложение под тем самым колесом, без маски, своими словами, и она говорит да, тебе, не зверю."),
 ("M4_SH23","WIFE","fairground","close on the woman's joyful face saying yes to the unmasked man, the fair lights warm behind her","CU","eye","push_in","dusk",False,False,
  "и на один этот вечер тебе кажется, что маска тебе больше не понадобится, что тебя можно любить просто так."),
 ("M4_SH24",None,"fairground","the lit ferris wheel turning against a dusk sky, the mascot suit bag forgotten on a bench below","EWS","eye","pull_out","dusk",True,True,
  "ты ещё не знаешь, что не снимешь её, что очень скоро снова спрячешься в неё, и уже навсегда."),
]

PAL_FAMILY="warm-but-fraying domestic palette, homey amber shading to lonely blue, the warmth slowly thinning"
A5=[
 ("M5_SH01",None,"family_kitchen","a small modest kitchen decorated for a simple home wedding party, paper garlands, a cake, warm light","EWS","eye","push_in","day",True,False,
  "вы женитесь скромно, дома, и это самый счастливый день, и ты клянёшься быть рядом, настоящим, без маски."),
 ("M5_SH02","WIFE","family_kitchen","the bride and the thin young man cutting a small cake in a kitchen, simple and happy, a few guests implied","MS","eye","static","day",False,False,
  "но кукла кормит вас обоих, и уже через неделю ты снова на смене, и она ужинает одна, в свой медовый месяц."),
 ("M5_SH03","MASCOT","mall_atrium","the plush mascot working a busy mall event, waving, while a phone in its glove buzzes with a missed call","MS","eye","static","day",False,False,
  "ты берёшь все гиги подряд, и пока ты машешь лапой чужим детям, дома звонит телефон, и ты не слышишь."),
 ("M5_SH04",None,"mask_interior","inside the head, the man's face glancing at a missed-call notification glowing faintly, then looking away","INSERT","eye","push_in","day",False,True,
  "сквозь сетку ты видишь пропущенный звонок жены, и говоришь себе, перезвоню после смены, и не перезваниваешь."),
 ("M5_SH05","WIFE","family_kitchen","the woman eating dinner alone at a kitchen table, a second plate cold and untouched across from her","MS","high","static","night",False,False,
  "она всё чаще ест одна, и второй прибор стынет напротив, и она перестаёт спрашивать, когда ты будешь дома."),
 ("M5_SH06","WIFE","family_kitchen","close on the woman's lonely tired face by lamplight, a wedding ring catching the light, waiting","CU","eye","push_in","night",False,False,
  "она выходила за тебя, за человека без маски, а получила куклу, которой нет дома по вечерам и выходным."),
 ("M5_SH07","MAN_YOUNG","family_kitchen","the young man coming home late, exhausted, the costume bag on his shoulder, the house already dark","MS","low","static","night",False,False,
  "ты приходишь за полночь, выжатый, с костюмом за спиной, и она уже спит, и ты не будишь, ты слишком устал."),
 ("M5_SH08","WIFE","family_kitchen","the woman showing the young man a positive pregnancy test in the kitchen doorway, hopeful and afraid","MCU","eye","push_in","day",False,False,
  "а потом она говорит, у нас будет ребёнок, и просит, будь теперь дома, будь отцом, а не куклой."),
 ("M5_SH09","MAN_YOUNG","family_kitchen","close on the young man's face, joy and fear mixed, promising something he isn't sure he can keep","CU","eye","static","day",False,False,
  "и ты обещаешь, конечно, я буду рядом, и сам не веришь себе, ведь маска уже держит тебя крепче семьи."),
 ("M5_SH10",None,"mask_interior","extreme close on a small fresh photo of the wife being taped inside the mascot head beside the eye-mesh","ECU","top","push_in","day",False,True,
  "ты приклеиваешь её фото внутри головы, у самой сетки, чтобы видеть её всё время, хотя бы вот так."),
 ("M5_SH11","MASCOT","minor_field","the plush mascot performing at a minor-league game while the stands cheer, working through dinnertime","WS","eye","pan_right","day",False,False,
  "ребёнок рождается, а ты на выезде, машешь лапой чужим трибунам, и узнаёшь о сыне по телефону из гримёрки."),
 ("M5_SH12",None,"mask_interior","inside the head, the man's face crumpling with emotion at news heard through a phone, sweat and tears","INSERT","eye","push_in","day",False,True,
  "ты стоишь в голове орла, и плачешь от счастья, и тут же выходишь на поле плясать, потому что шоу не ждёт."),
 ("M5_SH13","WIFE","family_kitchen","the woman holding a newborn alone in the kitchen at night, the father's chair empty, tired and tender","MS","high","static","night",False,False,
  "она держит вашего сына одна, ночами, и качает его, и твой стул у кроватки пустует, ты опять на смене."),
 ("M5_SH14","MAN_YOUNG","family_kitchen","the young man home briefly, holding his baby awkwardly, still smelling of foam and sweat from the suit","MCU","eye","static","day",False,False,
  "когда ты дома, ты держишь сына неловко, и от тебя пахнет поролоном и потом, и ты уже думаешь о завтрашнем гиге."),
 ("M5_SH15","WIFE","family_kitchen","the woman watching the young man already packing the costume bag again, her face quietly closing","CU","over","static","day",False,False,
  "она смотрит, как ты снова собираешь костюм, и не упрекает, просто что-то в её лице тихо закрывается."),
 ("M5_SH16","MAN_YOUNG","suburban_street","the young man leaving home at dawn with the costume bag, his wife and baby framed in a lit window behind","WS","low","track","dawn",False,False,
  "ты уходишь на рассвете с сумкой, и в окне остаются они двое, и ты говоришь себе, я делаю это ради них."),
 ("M5_SH17","MASCOT","mall_atrium","the mascot hugging other people's children at an event, warm and generous, giving them what he can't give home","MS","eye","static","day",False,False,
  "и ты обнимаешь чужих детей весь день, щедро, тепло, отдавая им то, чего не успеваешь отдать своему."),
 ("M5_SH18",None,"mask_interior","the man's eyes inside the head watching a little boy in the crowd who looks the age of his own son","INSERT","eye","push_in","day",False,True,
  "иногда в толпе ты видишь мальчишку возраста сына, и сердце сжимается, и ты обнимаешь его чуть крепче нужного."),
 ("M5_SH19","WIFE","family_kitchen","the woman alone teaching the toddler to walk in the kitchen, filming it on a phone for an absent father","MS","eye","static","day",False,False,
  "она снимает на телефон, как сын делает первые шаги, чтобы показать тебе, потому что тебя при этом не было."),
 ("M5_SH20","MAN_YOUNG","dressing_area","the young man watching the first-steps video on a phone in a sweaty dressing room, alone, between gigs","MCU","high","static","day",False,False,
  "ты смотришь это видео в гримёрке между выходами, в мокром костюме, и пропускаешь первые шаги сына дважды."),
 ("M5_SH21","MAN_YOUNG","family_kitchen","close on the young man's guilty tender face, the photo of wife and child clutched in his hand","CU","eye","push_in","night",False,False,
  "ты говоришь себе, ещё пара лет, встану на ноги, и буду дома, и сам не замечаешь, как эти годы тянутся."),
 ("M5_SH22",None,"family_kitchen","a child's crayon family drawing on a fridge where the father figure is drawn wearing a big mascot head","INSERT","eye","push_in","day",False,True,
  "на холодильнике висит рисунок сына, наша семья, и папа на нём нарисован в большой голове зверя, в маске."),
 ("M5_SH23","WIFE","family_kitchen","the woman quietly accepting a life mostly alone, setting one plate now instead of two, resigned","MS","high","static","night",False,False,
  "со временем она ставит на стол один прибор, не два, и перестаёт ждать, и в доме поселяется тихая пустота."),
 ("M5_SH24","MAN_YOUNG","suburban_street","the young man under a streetlight at night heading to yet another gig, the lit family window shrinking behind","WS","high","pull_out","night",True,False,
  "а ты всё уходишь и уходишь в ночь с костюмом за спиной, и окно с твоей семьёй становится всё меньше."),
 ("M5_SH25",None,"mask_interior","the taped photo of wife and child inside the head, curling slightly at the edges with heat and time","ECU","top","static","day",False,True,
  "фото внутри головы желтеет от жары и пота, и однажды ты замечаешь, что знаешь его лучше, чем их живых."),
 ("M5_SH26","MAN_YOUNG","dressing_area","close on the young man's tired face inside the dim dressing room, the mascot head waiting beside him","CU","low","push_in","night",False,True,
  "тебе тридцать, у тебя есть жена и сын, и единственное место, где тебе спокойно, это внутри чужой улыбки."),
]

PAL_RISING="busy event palette, bright commercial colour and stage light, a cheerful surface over growing fatigue"
A6=[
 ("M6_SH01","MASCOT","mall_atrium","the plush mascot headlining a big store-opening event, ribbons and balloons, a large excited crowd","EWS","low","push_in","day",True,False,
  "годы идут, и ты становишься лучшим в городе, тебя зовут на открытия, на корпоративы, нарасхват."),
 ("M6_SH02","MANAGER","mall_atrium","the events manager booking the mascot on a phone, pointing at a busy calendar, all about the costume","MCU","eye","static","day",False,False,
  "менеджер расписывает тебя на месяцы вперёд, и говорит про тебя кукла, а не имя, для всех ты просто костюм."),
 ("M6_SH03","MASCOT","fan_zone","the mascot dancing for a huge cheering crowd at a city festival, a sea of delighted faces","WS","eye","pan_right","day",False,False,
  "толпы растут, тебя любят сотни разом, и в эти минуты ты счастлив, по-настоящему, как только в маске и умеешь."),
 ("M6_SH04",None,"mask_interior","inside the head, the man's aging face streaming with sweat in the heat, eyes still bright with the crowd's love","INSERT","eye","push_in","day",False,True,
  "внутри жара, пот, колени уже ноют от плясок на бетоне, но снаружи ты сияешь, и ради этого терпишь всё."),
 ("M6_SH05","MASCOT","minor_field","the mascot beloved at a packed minor-league stadium, kids reaching over the rail to touch it","WS","low","static","day",False,False,
  "на стадионах дети висят на ограждении, тянутся к тебе, кричат твоё кукольное имя, и ты для них герой."),
 ("M6_SH06","MAN","dressing_area","an older balding man peeling the heavy suit off in a dressing room, knees stiff, hands shaking with fatigue","MS","high","static","day",False,False,
  "тебе уже за сорок, и снимать костюм всё тяжелее, колени не гнутся, руки трясутся, но ты не сбавляешь."),
 ("M6_SH07","MAN","family_kitchen","the balding man at home, a teenager glued to a phone ignoring him, the wife older and quietly distant","MS","eye","static","night",False,False,
  "сын уже подросток, и почти не поднимает на тебя глаз, для него ты вечно усталый отец, которого не было."),
 ("M6_SH08","KID","fan_zone","an excited child at a festival running to hug the big plush mascot, arms wide, pure adoration","WS","low","static","day",False,False,
  "и вот однажды на празднике к тебе бежит обниматься малыш, и сердце твоё обрывается, ведь это твой сын."),
 ("M6_SH09",None,"mask_interior","inside the head, the man's stricken face recognising his own child hugging the costume, unable to speak","ECU","eye","push_in","day",False,True,
  "твой собственный сын обнимает куклу, не зная, что внутри папа, и ты не можешь сказать ему, ты на работе."),
 ("M6_SH10","MASCOT","fan_zone","the mascot gently holding its own child in a hug a beat too long, the crowd none the wiser","MCU","low","static","day",False,False,
  "ты обнимаешь его чуть дольше, чем других, и хочешь шепнуть, это я, сынок, но кукла должна молчать."),
 ("M6_SH11","KID","fan_zone","the child running back happily to his mother, waving at the mascot, never knowing it was his father","WS","eye","static","day",False,False,
  "он машет кукле и убегает к маме, счастливый, и так и не узнаёт, что обнимал родного отца, не зная его."),
 ("M6_SH12","MAN","dressing_area","close on the aging man's devastated face inside the dim dressing room after, the head in his lap","CU","low","push_in","day",False,True,
  "ты садишься в гримёрке с головой на коленях, и впервые думаешь, что подменил собственного сына этой улыбкой."),
 ("M6_SH13","WIFE","family_kitchen","the wife gently telling the tired man at the kitchen table that the boy barely knows him, no anger left","MCU","eye","static","night",False,False,
  "вечером жена говорит тихо, без злости, он тебя почти не знает, ты ему чужой, ты всю жизнь в этой шкуре."),
 ("M6_SH14","MAN","family_kitchen","the man unable to answer his wife, hands open helplessly on the table, the costume bag by the door","CU","eye","static","night",False,False,
  "ты не знаешь, что ответить, ведь она права, ты выбрал чужую любовь толпы вместо тихой любви двоих дома."),
 ("M6_SH15","MAN","suburban_street","the man trying to play ball with his teenage son in the yard, both awkward, the distance between them visible","WS","eye","static","day",False,False,
  "ты пытаешься наверстать, выходишь с сыном во двор, но без маски ты неловкий и чужой, и у вас не клеится."),
 ("M6_SH16","KID","suburban_street","the teenage son drifting back inside, leaving the father alone in the yard with a ball, unbridged","MS","high","static","day",False,False,
  "сын уходит в дом, а ты остаёшься один с мячом, и понимаешь, что говорить с ним умеешь только из-под маски."),
 ("M6_SH17","MASCOT","mall_atrium","the mascot back at work the next day, beloved by strangers' children as its own grows away","WS","eye","static","day",False,False,
  "и ты снова надеваешь костюм, и снова чужие дети любят тебя, пока твой собственный растёт без тебя."),
 ("M6_SH18",None,"mask_interior","the man's tired eyes inside the head watching a father lift his child onto his shoulders in the crowd","INSERT","eye","push_in","day",False,True,
  "сквозь сетку ты видишь, как другой отец сажает сына на плечи, и завидуешь ему так, что щиплет глаза."),
 ("M6_SH19","MANAGER","dressing_area","the manager praising the mascot's popularity, mentioning a huge upcoming opportunity, all business","OTS","eye","static","day",False,False,
  "менеджер хвалит твои сборы, и однажды говорит, есть шанс, отбор на маскота чемпионата мира, поедешь."),
 ("M6_SH20","MAN","dressing_area","close on the aging man's face lighting with a desperate hope at the words World Cup, the dream igniting","CU","low","push_in","day",False,False,
  "чемпионат мира, повторяешь ты, самая большая сцена на земле, миллиарды глаз, и сердце вспыхивает, как в детстве."),
 ("M6_SH21","WIFE","family_kitchen","the wife's worried face hearing the man will be away all summer for the tournament, weary foreboding","MCU","eye","static","night",False,False,
  "жена слышит, что ты уедешь на всё лето, и тихо говорит, опять, и в её голосе уже не злость, а усталость."),
 ("M6_SH22","MAN","family_kitchen","the man promising this is the peak, the last big push, then he'll be home for good, not believing it himself","MCU","eye","static","night",False,False,
  "ты обещаешь, это вершина, последний рывок, и потом я насовсем дома, и снова сам себе не веришь, как всегда."),
 ("M6_SH23",None,"mask_interior","the curling taped photo of wife and son inside the head, the man's reflection faint in the dark","ECU","top","push_in","day",False,True,
  "ты целуешь пожелтевшее фото внутри головы перед выездом, обещаешь им, что это в последний раз, и уезжаешь."),
 ("M6_SH24",None,"city_summer","a hot summer city street with the first World Cup banners going up on lampposts, heat haze rising","EWS","high","pan_right","day",True,True,
  "над городом поднимают флаги чемпионата, наступает то самое жаркое лето, и ты едешь к вершине своей жизни."),
]

seed_act("act04_her",    PAL_HER,    A4)
seed_act("act05_family", PAL_FAMILY, A5)
seed_act("act06_rising", PAL_RISING, A6)
