# -*- coding: utf-8 -*-
"""shuttle expansion wave 1 — interleaved beats (letter-suffix codes), id_region='b'.
PYTHONIOENCODING=utf-8 python scripts/_seed_shuttle_expand.py"""
from _shuttle_engine import seed_act

ACTS=[
 ("cold_open","found-keepsake palette, warm modern spot light over plaid red-white-blue, tender and bright",[
  ("A0_SH02B",None,"new_flat","a wide view of half-unpacked moving boxes down a bright hallway, one labelled in a mother's handwriting","WS","eye","static","day",True,False,
   "переезд у неё уже третий, но антресоли она разбирает первый раз в жизни сама."),
  ("A0_SH05B","VERA_OLD","flat_home","a medium shot of the silver-haired woman in her tidy old kitchen, an enamel teapot mid-pour","MS","eye","static","evening",False,False,
   "в твоей кухне всё на местах, и чай ты завариваешь всё в том же заварнике."),
  ("A0_SH08B","VERA_OLD","flat_home","a medium close-up of the woman closing her eyes briefly, gathering the story in order","MCU","eye","static","evening",False,False,
   "воспоминания у тебя разложены, как товар по полкам, и ты знаешь, с какой начать."),
 ]),
 ("nii","stalled institute palette, dusty drafting grey and winter window blue, one warm desk lamp of habit",[
  ("A1_SH02B",None,"nii_hall","a wide view of the office corridor with dark doorways and one coat left on a communal rack","WS","eye","static","day",True,False,
   "отдел пустеет с каждым месяцем: кто в торговлю, кто в такси, кто в никуда."),
  ("A1_SH05B","GRAN_SH","flat_home","a medium close-up of the grandmother setting a lunch container on the table with quiet authority","MCU","eye","static","evening",False,False,
   "мать носит суп в судочках и повторяет: голодные решения — плохие решения, поешь сперва."),
  ("A1_SH07B",None,"city_90s","a wide view of the market rows below, former office workers behind stalls in good new jackets","WS","high","static","day",True,False,
   "на рынке твои бывшие коллеги торгуют колготками, и у них появились новые куртки."),
  ("A1_SH09B",None,"flat_home","a wide view of the kitchen with the mother listening by the stove, arms folded, kettle steaming","WS","eye","static","evening",True,False,
   "мать выслушивает твой план стоя, у плиты, как слушают сводки, не перебивая."),
  ("A1_SH11B","VERA_YOUNG","flat_home","a medium close-up of the woman guiding checked fabric under a sewing machine needle","MCU","eye","static","night",False,False,
   "строчка у тебя ровная, инженерная, и пуговицу вы пришиваете двойной ниткой, насмерть."),
 ]),
 ("first_run","first-run palette, night highway blues breaking into Laleli lamp gold, nervous and alive",[
  ("A2_SH01B",None,None,"an extreme close-up insert of a long-haul bus ticket held in careful fingers","ECU","eye","static","day",True,False,
   "билет на автобус стоит как две твои невыплаченные зарплаты, и это уже смешно."),
  ("A2_SH04B",None,None,"an extreme close-up insert of tea in a tulip glass set on a crate table, steam curling","ECU","eye","static","day",True,False,
   "чай здесь подают в стеклянных тюльпанах, и первый стакан тебе наливают просто так."),
  ("A2_SH06B",None,"istanbul","a wide view of traders loading plaid bags into a bus in a human chain at dusk","WS","eye","static","evening",True,False,
   "к вечеру сумки грузят в автобус живой цепью, и твоя уходит наверх, под потолок."),
  ("A2_SH09B",None,None,"an extreme close-up insert of a leather jacket passing over a stall into a buyer's hands","ECU","eye","static","day",True,False,
   "первую куртку у тебя покупают за десять минут, не торгуясь, и ты запоминаешь это чувство."),
  ("A2_SH11B",None,"flat_home","a wide view of the night kitchen, banknotes in neat rows under the lamp, a calculator at rest","WS","high","static","night",True,False,
   "ночью ты пересчитываешь всё ещё раз при лампе, и цифры сходятся до копейки."),
  ("A2_SH13B","GRAN_SH","flat_home","a medium close-up of the grandmother inspecting the oilcloth notebook through round glasses","MCU","eye","static","night",False,False,
   "мать смотрит на твою тетрадь через очки и говорит только: почерк не испортила, молодец."),
 ]),
 ("market","market winter palette, steel stall grey and breath steam warmed by jacket leather browns",[
  ("A3_SH01B",None,None,"an extreme close-up insert of a stall post with a painted number twelve","ECU","eye","static","day",True,False,
   "номер места написан краской на стойке, и двенадцать ты с тех пор считаешь счастливым."),
  ("A3_SH04B",None,"home_market","a wide view of the market at full flow, buyers threading the rows, jackets trying on over coats","WS","eye","pan_right","day",True,False,
   "покупатель пошёл косяком: зима близко, и кожанка с рынка — это статус и броня."),
  ("A3_SH06B",None,None,"an extreme close-up insert of a leather flat cap moving above the crowd between stalls","ECU","eye","static","evening",True,False,
   "его кепку видно издали, и ряды передают её приближение, как прогноз погоды."),
  ("A3_SH09B","VERA_YOUNG","home_market","a close-up of the woman's eyes running silent arithmetic over her stall","CU","eye","static","evening",False,False,
   "в себестоимость у тебя входит всё: билет, место, «погода» и амортизация собственной спины."),
  ("A3_SH11B",None,"flat_home","a wide view of the dark bedroom, a note left on a school desk beside a sleeping child's bed","WS","eye","static","night",True,False,
   "уезжая затемно, ты поправляешь Лене одеяло и оставляешь записку с новым словом из Стамбула."),
 ]),
 ("kidok","pre-holiday betrayal palette, festive Laleli gold cut by shuttered-steel grey, cold inside warm",[
  ("A4_SH02B",None,"istanbul","a wide view of a familiar shop interior, tea glasses out, racks of leather in trusted order","WS","eye","static","day",True,False,
   "он поит тебя чаем четвёртый год, и его лавке ты веришь, как своему НИИ."),
  ("A4_SH05B",None,"istanbul","a wide view of the wholesale street trading on at full pitch around one still figure","WS","eye","static","day",True,False,
   "Лалели работает дальше, как ни в чём не бывало, и это почему-то обиднее всего."),
  ("A4_SH07B",None,None,"an extreme close-up insert of frost feathering an empty stall counter","ECU","eye","static","day",True,False,
   "на пустом прилавке за неделю намерзает иней, и соседки смахивают его по-хозяйски."),
  ("A4_SH09B",None,"home_market","a wide view of the January market trading thin but trading, breath steam over the rows","WS","eye","static","day",True,False,
   "январь торгует вяло, но торгует, и каждая проданная куртка возвращает тебе по кусочку."),
  ("A4_SH11B","VERA_YOUNG","home_market","a medium close-up of the woman placing repaid notes into her neighbour's hands, debts squared","MCU","eye","static","day",False,False,
   "долг Вале ты закрываешь к марту, до копейки, и с тех пор вы как родня."),
 ]),
 ("border","checkpoint palette, floodlight white on concrete blue, breath steam and long shadows, tense",[
  ("A5_SH02B",None,"border","a wide view of a queue of women with plaid bags along the inspection lane wall","WS","eye","static","night",True,False,
   "в очереди на досмотр стоят одни женщины, и у каждой дома кто-то ждёт."),
  ("A5_SH05B",None,"border","a wide view of one inspection table with goods laid in perfect display rows, an official pausing","WS","eye","static","night",True,False,
   "твои куртки лежат на столе рядами, как на витрине, и офицер теряет интерес."),
  ("A5_SH08B",None,"bus_int","a wide view of the bus interior asleep after the crossing, dawn grey in the windscreen","WS","eye","static","dawn",True,False,
   "после границы салон спит вповалку, и водитель делает музыку тише, из уважения."),
  ("A5_SH09B","VERA_YOUNG","bus_int","a medium close-up of the woman stitching a patch onto the plaid bag right in her seat","MCU","eye","static","day",False,False,
   "заплатку ты ставишь прямо в автобусе, двойной ниткой, тем же насмертным швом."),
 ]),
 ("daughter","waiting-child palette, school-concert warmth and window-lamp amber against highway dark",[
  ("A6_SH01B",None,None,"an extreme close-up insert of paper snowflakes taped to a stage curtain, two with pencilled letters","ECU","eye","static","evening",True,False,
   "снежинки к концерту Лена вырезала неделю, и две из них — с твоим именем."),
  ("A6_SH04B",None,None,"an extreme close-up insert of a small film camera raised between clapping hands","ECU","eye","static","evening",True,False,
   "плёнку потом проявят, и на восьми кадрах из двадцати четырёх будет Лена."),
  ("A6_SH06B",None,"bus_int","a wide view of the parked bus at a night fuel stop, one reading light on in the dark cabin","WS","eye","static","night",True,False,
   "ты находишь письмо на ночной стоянке, при свете заправки, между двумя границами."),
  ("A6_SH09B",None,None,"an extreme close-up insert of new white trainers set carefully out of the rain by a door","ECU","eye","static","day",True,False,
   "у Лены первой во дворе появляются настоящие кроссовки, и она прячет их от дождя."),
  ("A6_SH11B",None,"flat_home","a wide view of the evening window with a bus pulling in at the stop below","WS","pov","static","evening",True,False,
   "в четверг вечером автобус приходит в девять, и в девять пятнадцать ты дома."),
 ]),
 ("default98","crisis palette, exchange-board red on newsprint grey, one steady pencil line through the panic",[
  ("A7_SH01B",None,None,"an extreme close-up insert of a newspaper front page with one huge word across it","ECU","top","static","day",True,False,
   "газеты пишут слово «дефолт» на первой полосе, и слово это учат все за неделю."),
  ("A7_SH04B","VALYA_BASE","home_market","a close-up of the henna-red woman exhaling, resetting her leopard headband, nodding","CU","eye","static","day",False,False,
   "Валя выдыхает, поправляет ободок и говорит: ну раз оборот, то торгуем дальше."),
  ("A7_SH06B",None,"flat_home","a wide view of the kitchen at night, the notebook open in lamplight, tea set down beside it","WS","eye","static","night",True,False,
   "вечерами ты сводишь тетрадь при лампе, и мать приносит чай, не спрашивая цифр."),
  ("A7_SH08B","VERA_MID","home_market","a medium close-up of the woman shaking hands on a fair price, eyes level","MCU","eye","static","day",False,False,
   "с двумя из ушедших ты потом рассчитаешься сверх цены, когда встанешь твёрдо."),
  ("A7_SH09B",None,None,"an extreme close-up insert of three stall name plates lettered in one draftsman's hand","ECU","eye","static","day",True,False,
   "на трёх местах теперь стоят три твои таблички, выписанные одним чертёжным почерком."),
 ]),
 ("kiosk","settled-trade palette, kiosk lamp amber against bus-stop winter blue, small warm plenty",[
  ("A8_SH01B",None,None,"an extreme close-up insert of a new kiosk key on a ring in a work-worn palm","ECU","top","static","day",True,False,
   "ключ от ларька — первый ключ, который ты заработала, а не получила по ордеру."),
  ("A8_SH04B",None,None,"an extreme close-up insert of pressed school uniforms hung in the barred kiosk window","ECU","eye","static","day",True,False,
   "к августу у тебя очередь за школьной формой, и ты держишь цены божескими."),
  ("A8_SH06B",None,"kiosk_hers","a wide view of the kiosk shuttered for the night, lamplight and bus-stop blue around it","WS","eye","static","evening",True,False,
   "ставню ты закрываешь в восемь и идёшь домой пешком, мимо бывшего НИИ."),
  ("A8_SH09B",None,None,"an extreme close-up insert of cutlery precise on a Sunday tablecloth, three settings apart","ECU","top","static","evening",True,False,
   "тишину за столом ты слышишь лучше любого крика, но не знаешь, чем её заполнить."),
 ]),
 ("store","earned-respect palette, washed shop daylight over ordered racks, one hard cold conversation in it",[
  ("A9_SH01B",None,None,"an extreme close-up insert of a ring of shop keys laid on a proper counter","ECU","top","static","day",True,False,
   "ключей теперь целая связка: магазин, подсобка, касса, и каждый из них заработан по-честному."),
  ("A9_SH04B",None,"store_hers","a wide view down the shop from till to door, racks between two distant figures","WS","eye","static","day",True,False,
   "вы видитесь через весь магазин: ты у кассы, она у дверей, и между вами вешалки."),
  ("A9_SH07B","VERA_MID","store_hers","a medium shot of the woman moving slowly along a rack, hand trailing the jackets","MS","eye","static","night",False,False,
   "ты перебираешь куртки на вешалках и задаёшь себе вопрос, на который нет цифры."),
  ("A9_SH09B",None,"city_90s","a wide view of the sleeping street beyond the shop windows, one phone-box lit","WS","eye","static","night",True,False,
   "город за окнами магазина спит, и где-то в нём не спит твоя дочь."),
 ]),
 ("mend","mending palette, graduation spring light and shop lamp gold, warmth returning by degrees",[
  ("A10_SH03B","VERA_MID","city_90s","a medium close-up of the mother seated among parents at a ceremony, hands quiet in her lap","MCU","eye","static","day",False,False,
   "ты сидишь в актовом зале среди родителей и наконец-то никуда не едешь."),
  ("A10_SH05B",None,"store_hers","a wide view of the busy counter working smoothly, a queue moving without impatience","WS","eye","static","day",True,False,
   "очередь идёт быстро: у Лены экономика в дипломе и рынок в крови."),
  ("A10_SH07B",None,"store_hers","a wide view of the closed shop at night, two chairs pulled to the counter, tea between them","WS","eye","static","night",True,False,
   "магазин ночью тёплый и свой, и говорить в нём почему-то легче, чем дома."),
  ("A10_SH09B",None,None,"an extreme close-up insert of a wooden comb and round glasses laid together on a lace doily","ECU","top","static","day",True,False,
   "после неё остаются гребень, круглые очки и привычка всей семьи держаться прямо."),
 ]),
 ("coda","keepsake palette, modern warm spot light over plaid and amber, the circle closing kindly",[
  ("A11_SH02B",None,"new_flat","a wide view through the new flat's window over a good quiet courtyard at dusk","WS","eye","static","evening",True,False,
   "за её окнами хороший район и тихий двор, и всё это выросло из сумки."),
  ("A11_SH05B","LENA_ADULT","new_flat","a medium shot of the woman on the stepladder lifting the bag onto the mezzanine with both hands","MS","low","static","evening",False,False,
   "она поднимается по стремянке сама и ставит сумку бережно, как ставят документы в архив."),
  ("A11_SH07B",None,"flat_home","a wide view of the old kitchen at night, a finished cup of tea and a phone laid face up","WS","eye","static","night",True,False,
   "ты допиваешь чай на своей кухне, и звонок заканчивается словами: люблю, мам, приезжай."),
 ]),
]

if __name__=="__main__":
    for sk,pal,shots in ACTS:
        seed_act(sk, pal, shots, id_region="b")
