# -*- coding: utf-8 -*-
"""sailor_wife acts: storm (2008, 28) + ashore (2015, 26). ALL animated.
Run: PYTHONIOENCODING=utf-8 python scripts/_seed_sailor_wife_A8A9.py"""
from _sailor_wife_engine import seed_act

PAL8="dread palette of gale green-grey, radio-dial red, candle amber and third-day white"
STORM=[
("A8_SH01",None,"storm_sea",
 "open ocean in a full gale, mountainous grey-green swells with torn white crests, spray blown flat, a low black sky dragging squall curtains across a lost horizon",
 "EWS","eye","static","day",True,True,
 "в марте две тысячи восьмого у дальнего мыса встаёт шторм, каких не видели двадцать лет."),
("A8_SH02","ANNA_MID","anna_kitchen",
 "the wife of forty-eight frozen by the radio, a wooden spoon dripping onto the floor unnoticed, the announcer's cadence hardening mid-bulletin",
 "MS","eye","static","evening",False,False,
 "ты слышишь название района по радио и узнаёшь координаты раньше, чем диктор договаривает.",
 "the spoon dripping a slow spot onto the linoleum, her body turned wholly to the radio's grille"),
("A8_SH03","ANNA_MID","post_office",
 "the wife at the agency window out of hours, a clerk spreading helpless hands behind glass, a handwritten notice about disrupted communications taped to the pane",
 "OTS","over","static","evening",False,False,
 "агент разводит руками через стекло, связи с судном нет со вчерашнего вечера, ждите.",
 "the clerk's palms spreading behind the glass, her reflection over them, the taped notice trembling in a draught"),
("A8_SH04",None,"anna_window_room_80s",
 "the room at night with all lights off except one candle on the windowsill, the harbour beyond the glass swallowed by driving rain, the souvenir shelf in shadow",
 "WS","eye","static","night",True,False,
 "первую ночь ты не ложишься, свеча на подоконнике горит до огарка, порт молчит."),
("A8_SH05","ANNA_MID","anna_window_room_80s",
 "the wife's face lit from below by the windowsill candle, her eyes fixed into the rain-black glass, the pendant held to her lips with both hands",
 "CU","low","static","night",False,True,
 "ты держишь якорёк у самых губ и договариваешься со всеми морями сразу, без слов.",
 "the candle flame bending with a draught, her doubled hands pressing the pendant to her lips"),
("A8_SH06","OLYA_ADULT","anna_kitchen",
 "the grown daughter arrived with an overnight bag, filling a kettle with two red spots high on her cheeks, her phone face-up on the table where she can see it",
 "MS","eye","static","morning",False,False,
 "утром приезжает оля с ночной сумкой, ставит чайник и звонит агенту каждые полчаса.",
 "the kettle filling under her steady hand, her eyes flicking to the face-up phone, jaw set like her father's"),
("A8_SH07","ZINA_BASE","anna_kitchen",
 "the aging copper-haired neighbour sitting close beside the wife, holding her hand on the tabletop with both of hers, saying nothing at all for once",
 "MCU","eye","static","day",False,True,
 "зина приходит и просто сидит рядом, держит твою руку, и это лучшее, что можно сделать.",
 "her two strong hands folding around the wife's one, her thumb moving in slow steady strokes"),
("A8_SH08",None,"harbor_panorama",
 "the harbour on the second day, storm surge slamming the breakwater in white explosions, all work stopped, cranes weathervaned, flags shredded straight",
 "EWS","high","static","day",True,False,
 "на второй день шторм доходит и до вашей бухты, и порт закрывает ворота на штормовые."),
("A8_SH09","ANNA_MID","anna_window_room_80s",
 "the wife standing at the window in the exact spot worn familiar, motionless, the grey day failing around her straight figure, tea cold on the sill",
 "BACK","eye","static","day",False,False,
 "вторые сутки ты стоишь у окна, и соседи снизу узнают время по твоему силуэту.",
 "her silhouette holding against the failing light, rain tracks crawling the glass before her"),
("A8_SH10","OBJ:radiogram",None,
 "an old radiogram form from years ago held in trembling fingers, its twelve capital words half worn away along the fold lines",
 "ECU","top","static","night",False,False,
 "ночью ты перечитываешь его старые радиограммы, в двенадцати казённых словах помещалось столько жизни.",
 "the worn form trembling faintly in the holding fingers, a thumb smoothing one fold line flat"),
("A8_SH11","ANNA_MID","anna_kitchen",
 "the two women and the wife around the kitchen table in small hours, plates untouched, the phone in the centre like a small silent god, the candle moved from the sill",
 "WS","eye","static","night",False,False,
 "третью ночь вы сидите втроём вокруг молчащего телефона, и чай остывает нетронутым кругом.",
 "three still figures ringed around the silent phone, steam dying over the cups, the candle guttering"),
("A8_SH12","OLYA_ADULT","anna_kitchen",
 "the daughter snatching the ringing phone before the first ring finishes, her knuckles white, two older faces rising behind her like moons",
 "MCU","eye","static","morning",False,True,
 "телефон звонит в шесть сорок утра, и оля хватает трубку раньше первого гудка.",
 "her hand snapping the receiver up mid-ring, her spine going rigid, the two faces lifting behind her"),
("A8_SH13","ANNA_MID","anna_kitchen",
 "the wife reading the news off her daughter's unclenching shoulders before any words, her own body starting to fold at the knees toward a chair",
 "MS","eye","static","morning",False,True,
 "по олиной спине ты читаешь ответ раньше слов, вышли на связь, экипаж целый, идут в порт.",
 "the daughter's shoulders unclenching, the wife's knees folding her slowly onto the chair edge"),
("A8_SH14","ANNA_MID","anna_kitchen",
 "the wife on the chair with her face in her hands, not crying, just breathing through her fingers, the neighbour's hand already on her back",
 "CU","eye","static","morning",False,False,
 "ты сидишь, дышишь сквозь пальцы, и трое суток выходят из тебя мелкой частой дрожью.",
 "her breath moving through her laced fingers, her back rising in long waves under the neighbour's palm"),
("A8_SH15",None,"harbor_panorama",
 "the harbour after the storm in strange clean light, the sea exhausted and flat, wreckage of a fish shed strewn along the shore road, gulls walking dazed",
 "EWS","eye","static","day",True,False,
 "шторм уходит так же вдруг, и море к пятнице лежит тихое, будто ничего не знает."),
("A8_SH16",None,"port_quay",
 "a storm-scarred freighter warping in with a crumpled bulwark section and salt-bleached superstructure, tugs nursing it to the wall, a thin crowd waiting silent",
 "WS","eye","static","day",True,False,
 "судно входит в ковш с помятым фальшбортом, и на причале никто не машет, все просто ждут."),
("A8_SH17","VIKTOR_MID","port_quay",
 "the seaman coming down the gangway noticeably greyer, moving carefully like a man carrying something breakable inside, his kit bag light in his hand",
 "MS","eye","static","day",False,True,
 "виктор сходит по трапу совсем седой, и походка у него, как у человека со стеклом внутри.",
 "his careful steps taking the gangway one at a time, his free hand riding the rail all the way down"),
("A8_SH18","ANNA_MID","port_quay",
 "the wife's cheek finding its exact place on her husband's chest, his chin lowering onto her hair, two faces closed around one silence",
 "CU","eye","static","day",False,True,
 "вы обнимаетесь молча, и его сердце под твоей щекой стучит чуть иначе, чем ты помнишь.",
 "her cheek settling into his chest, his chin lowering onto her hair, two pairs of eyes closing"),
("A8_SH19","VIKTOR_MID","anna_kitchen",
 "the seaman at the kitchen table telling nothing, stirring tea that needs no stirring, his eyes going somewhere the kitchen cannot follow",
 "MCU","eye","static","evening",False,False,
 "про сам шторм он не рассказывает ничего, только мешает ложкой чай без сахара.",
 "the spoon circling the glass slowly, his eyes fixed through the table, the tea long past stirred"),
("A8_SH20","ANNA_MID","anna_kitchen",
 "the wife covering her husband's stirring hand, stopping the spoon, asking nothing, the kitchen holding its breath around the joined hands",
 "OTS","over","static","evening",False,False,
 "ты накрываешь его руку своей, ложка замолкает, и вопросов ты не задаёшь никаких.",
 "her hand settling over his, the spoon's circling dying out, his fingers turning to lace with hers"),
("A8_SH21",None,"anna_window_room_80s",
 "the souvenir shelf with a new addition, a small piece of storm-polished sea glass set apart from the carved figures, evening light through it green",
 "INSERT","eye","static","evening",True,False,
 "с этого рейса сувенир один, кусок морского стекла, обкатанный тем самым штормом."),
("A8_SH22","ANNA_MID","anna_window_room_80s",
 "the wife at the table with an old exercise book of years and dates, her pencil totting a private sum, her face very quiet at the result",
 "MS","high","static","night",False,True,
 "этой ночью ты садишься и честно считаешь, из двадцати восьми лет брака вместе вы прожили восемь.",
 "her pencil adding the private column, the total arriving, her hand laying the pencil down flat"),
("A8_SH23",None,"anna_kitchen",
 "an old exercise book page in lamplight, two pencil totals ringed, twenty-eight and eight, nothing else on the page but their distance",
 "INSERT","top","push_in","night",True,True,
 "двадцать восемь и восемь, две цифры стоят на странице и не смотрят друг на друга."),
("A8_SH24","VIKTOR_MID","anna_window_room_80s",
 "the seaman finding the open exercise book in morning light, reading the two ringed totals, his hand slowly closing the cover as if it were heavy",
 "MCU","eye","static","morning",False,False,
 "утром он находит тетрадь, читает две цифры и закрывает её так, будто она из чугуна.",
 "his eyes resting long on the ringed totals, the cover closing by slow degrees under his hand"),
("A8_SH25","VIKTOR_MID","anna_kitchen",
 "the seaman standing before his wife with the exercise book held to his chest, saying the sentence he has never said first, his voice arriving before his courage",
 "MS","eye","static","morning",False,True,
 "он говорит первым, аня, ещё один контракт на замену сменщику, и я списываюсь совсем.",
 "the book pressing to his chest, his weight shifting, the sentence leaving him like a held rope"),
("A8_SH26","ANNA_MID","anna_kitchen",
 "the wife's face at the too-familiar shape of the promise, love and irony and fatigue in one look, her hand reaching to straighten his collar anyway",
 "CU","eye","static","morning",False,False,
 "слово совсем ты взвешиваешь на той же ладони, что и все его последние, и всё же веришь.",
 "her look holding all its layers, her hand rising to straighten his collar in the old gesture"),
("A8_SH27",None,"port_quay",
 "the quay in autumn with a departing freighter already off the wall, one woman's figure by the third bollard neither waving nor leaving, gulls settling around her",
 "EWS","high","static","morning",True,False,
 "осенью он уходит на действительно последний контракт, и причал под тобой знаком до трещин."),
("A8_SH28","ANNA_MID","promenade",
 "the wife walking home along the promenade very slowly, trailing one hand along the painted railing the whole way, the sea flat and polite beside her",
 "WS","eye","track","evening",False,False,
 "домой ты идёшь по набережной, ведя рукой по перилам, и считаешь фонари, их тридцать один.",
 "her hand riding the railing's ridge lamppost by lamppost, her steps unhurried, the sea keeping pace"),
]

PAL9="landing palette of health-form beige, unfamiliar-morning grey, kitchen steam white and armchair moss green"
ASHORE=[
("A9_SH01",None,"seafarers_office",
 "the crewing office of the mid-twenty-tens, flat screens over the old counter, a medical commission door with a queue of seamen holding folders, laminated notices",
 "WS","eye","static","day",True,False,
 "в две тысячи пятнадцатом медкомиссия читает его кардиограмму дольше обычного и зовёт второго врача."),
("A9_SH02","VIKTOR_OLD","seafarers_office",
 "the white-haired seaman of fifty-nine on the bench outside the commission door, turning his seaman's book in both hands, his shoulders learning the word ashore",
 "MCU","eye","static","day",False,True,
 "выходит он с бумагой, где написано вежливо и окончательно, к плаванию не годен.",
 "the seaman's book turning slower and slower in his hands, stopping, his thumb resting on its worn crest"),
("A9_SH03","ANNA_OLD","anna_kitchen",
 "the wife of fifty-five reading the medical form at the kitchen table, relief arriving on her face ahead of tact, her hand pressing the paper flat",
 "CU","eye","static","evening",False,True,
 "ты читаешь заключение, и стыдно сказать, у тебя от слова списан теплеет под ключицей.",
 "her palm smoothing the form flat, the relief surfacing before she can school it, her eyes lifting guilty"),
("A9_SH04","VIKTOR_OLD","anna_window_room_80s",
 "the old seaman standing in the middle of the room on his first shore morning, dressed and shaved by six, nowhere to report, his hands opening and closing",
 "MS","eye","static","morning",False,False,
 "в первое береговое утро он бреется к шести и стоит посреди комнаты без назначения.",
 "his hands opening and closing at his sides, his weight rocking heel to toe like a deck under him"),
("A9_SH05","VIKTOR_OLD","anna_kitchen",
 "the small kitchen wide with every cupboard door standing ajar, the old seaman mid-hunt for a cup at the far shelf, morning sun on the opened chaos",
 "WS","eye","static","morning",False,False,
 "он ищет чашку по всем шкафчикам подряд, тридцать пять лет он был гостем этой кухни.",
 "cupboard doors opening one by one under his hands, his head tilting into each, doors left ajar in his wake"),
("A9_SH06","ANNA_OLD","anna_kitchen",
 "the wife leaning in the doorway watching the cupboard expedition, amusement and heartbreak sharing her face equally, her arms folded soft",
 "MCU","eye","static","morning",False,True,
 "ты смотришь из дверей, как он ищет, и не подсказываешь, пусть кухня знакомится с хозяином.",
 "her shoulder settling into the doorframe, her folded arms easing, a smile fighting sadness to a draw"),
("A9_SH07",None,"anna_kitchen",
 "the kitchen at four in the morning, a kettle steaming alone, a man's silhouette at the dark window standing an old watch out of pure habit",
 "WS","eye","static","night",True,False,
 "в четыре утра он встаёт на вахту, которой нет, и смотрит в окно, пока чайник остывает."),
("A9_SH08","ANNA_OLD","anna_window_room_2020s",
 "the wife waking to the empty bed side and finding it cold, her hand on the sheet, the window figure visible through the door, her face understanding slowly",
 "MCU","eye","static","night",False,False,
 "ты просыпаешься от пустой половины кровати и находишь его на посту у тёмного окна.",
 "her hand testing the cool sheet, her eyes finding the silhouette beyond the door, her breath settling"),
("A9_SH09","ANNA_OLD","anna_window_room_2020s",
 "the wife wrapping a blanket around her husband's shoulders at the dark window and staying under it with him, two silhouettes becoming one lumpy one",
 "MS","eye","static","night",False,True,
 "ты приносишь плед, накидываешь на его плечи и остаёшься внутри, вахту можно нести вдвоём.",
 "the blanket spreading over two sets of shoulders, her head finding his arm, the lump settling"),
("A9_SH10","VIKTOR_OLD","anna_kitchen",
 "the kitchen wide with its shelves re-rigged ship-fashion, cup hooks and twine lashings on every jar, the old seaman presenting the work with a proud sweep",
 "WS","eye","static","day",False,False,
 "за неделю он перештивает кухню по-корабельному, и банки теперь закреплены на случай качки.",
 "his hand sweeping proudly along the lashed shelf, a cup swinging gently on its new hook"),
("A9_SH11","ANNA_OLD","anna_kitchen",
 "the wife discovering her flour tin lashed to a rail, her expression circling through outrage into helpless laughter, the culprit's pride visible beyond",
 "MCU","eye","static","day",False,False,
 "ты находишь муку принайтованной к полке, набираешь воздух ругаться и вместо этого смеёшься.",
 "her hand tugging the lashed tin, her chest filling for battle, the laugh breaking out instead"),
("A9_SH12",None,"courtyard_bench",
 "the courtyard market-day morning, two shopping bags waiting by the bench, an old acacia dropping first yellow leaves on them, sparrows auditing the bags",
 "INSERT","eye","static","morning",True,False,
 "по четвергам вы теперь ходите на рынок вдвоём, и это целая экспедиция с завхозом."),
("A9_SH13","VIKTOR_OLD","courtyard_bench",
 "the old seaman haggling over apples at a market stall edge with international gestures, holding one apple up to the light like a chronometer, the seller charmed",
 "MCU","eye","static","morning",False,False,
 "на рынке он торгуется, как в семи портах сразу, и яблоко проверяет на просвет, как хронометр.",
 "the apple rising to the light in his fingers, his eyebrow cocked at it, his other hand mid-bargain"),
("A9_SH14","ANNA_OLD","promenade",
 "the couple on a promenade bench with the shopping bags, sitting in silence that has stopped being awkward somewhere mid-hour, gulls negotiating at their feet",
 "WS","eye","static","day",False,False,
 "молчать вдвоём вы учитесь дольше, чем говорить, но к зиме и это начинает получаться.",
 "two still figures on the bench, a gull sidestepping closer to the bags, her mitten settling on his sleeve"),
("A9_SH15","VIKTOR_OLD","anna_window_room_2020s",
 "the old seaman placing the twenty-third souvenir, a tiny brass compass, at the very end of the long shelf row, stepping back, squaring it once more",
 "MCU","eye","static","evening",False,True,
 "двадцать третий сувенир, маленький латунный компас, встаёт в конец ряда, и ряд закрыт.",
 "the tiny compass settling at the row's end under his careful fingers, his step back, one last squaring nudge"),
("A9_SH16","ANNA_OLD","anna_window_room_2020s",
 "the wife watching her husband close the souvenir row, her hand finding the pendant, the whole shelf and the whole man finally in one room with her",
 "CU","eye","static","evening",False,True,
 "ты смотришь на полку и на него рядом с ней, впервые всё твоё море стоит в одной комнате.",
 "her fingers closing on the pendant, her eyes travelling the shelf's full length and coming home to him"),
("A9_SH17",None,"anna_kitchen",
 "the kitchen calendar hook by the door holding no calendar for the first time, a lighter square of wallpaper where years of them hung, the pen's ribbon still nailed",
 "INSERT","eye","push_in","day",True,True,
 "календарь у двери вы в этом январе просто не вешаете, зачёркивать больше нечего."),
("A9_SH18","ANNA_OLD","anna_kitchen",
 "the wife's hand rising by habit toward the empty calendar hook with a pen, stopping halfway, lowering, her face catching itself with a small laugh",
 "MCU","eye","static","evening",False,False,
 "рука ещё месяц тянется к гвоздику по вечерам, привычки сорока лет уходят не сразу.",
 "her hand rising with the pen, hanging halfway, lowering, her small laugh at herself arriving"),
("A9_SH19","VIKTOR_OLD","anna_kitchen",
 "the old seaman cooking a proper ship's borscht in a huge pot, apron over his sweater, tasting from the ladle with ceremony, steam fogging the window",
 "MS","eye","static","day",False,False,
 "по воскресеньям он варит борщ на камбузный манер, кастрюлей на весь экипаж, то есть на двоих.",
 "the ladle rising to his lips with full ceremony, his eyes closing at the taste, steam rolling past him"),
("A9_SH20","ANNA_OLD","anna_kitchen",
 "the couple eating at the kitchen table across from each other on an ordinary tuesday, nothing special happening, which is exactly the point, afternoon light mild",
 "WS","eye","static","day",False,False,
 "обыкновенный вторник, обед вдвоём, и ты ловишь мысль, что таких вторников у вас не было.",
 "spoons rising unhurried, his hand passing her the bread without being asked, the light lying easy"),
("A9_SH21","VIKTOR_OLD","promenade",
 "the old seaman at the promenade railing watching a freighter leave harbour, his body leaning after it a degree, then settling back onto his heels ashore",
 "MS","eye","static","evening",False,True,
 "уходящие суда он провожает всем корпусом, на градус наклоняется следом и остаётся.",
 "his frame leaning a slow degree after the ship, holding, easing back onto his heels"),
("A9_SH22","ANNA_OLD","promenade",
 "the wife watching her husband watch the ship, reading the lean and the settling, her hand sliding into the crook of his arm at the exact right second",
 "MCU","eye","static","evening",False,False,
 "ты видишь этот наклон и просто берёшь его под руку, якоря тоже требуют ухода.",
 "her hand sliding into his elbow's crook, his free hand covering hers, the ship shrinking unwatched"),
("A9_SH23",None,"harbor_panorama",
 "the harbour at evening from the promenade, a departed ship clearing the breakwater, its horn's long note almost visible in the cooling air",
 "EWS","eye","static","evening",True,False,
 "гудок уходящего долетает до набережной, и в кои-то веки он адресован не вам."),
("A9_SH24","VIKTOR_OLD","anna_window_room_2020s",
 "the old couple in the two armchairs by the window in lamplight, he mid-story with his hands as ships again, she with mending forgotten in her lap, listening",
 "MS","eye","static","night",False,False,
 "вечерами он рассказывает тебе рейсы по номерам, и ты слушаешь тридцать пять лет с начала.",
 "his hands banking through an old wave, her mending sinking forgotten, her face turned full to him"),
("A9_SH25","ANNA_OLD","anna_window_room_2020s",
 "the wife's listening face in lamplight, hearing a story where she now learns what the storm was, her hand very still on the armrest near his",
 "CU","eye","static","night",False,True,
 "про тот шторм он рассказывает только теперь, и ты наконец узнаёшь свои трое суток с той стороны.",
 "her stillness deepening as the story lands, her hand travelling the armrest to touch his sleeve"),
("A9_SH26",None,"anna_window_room_2020s",
 "the two armchairs by the dark window after midnight, both empty now, two cooling cups on the sill, the souvenir shelf watching over the quiet room",
 "WS","eye","pull_out","night",True,False,
 "к полуночи кресла пустеют, чашки остывают на подоконнике, и дому это нравится."),
]

seed_act("storm",PAL8,STORM)
seed_act("ashore",PAL9,ASHORE)
