# -*- coding: utf-8 -*-
"""car_flipper — акт 2 (рынок, 19–22, первое «как себе брал», Лена) и акт 3 (ремесло, 24–27)."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _car_flipper_engine import seed_act

P2 = "a raw daylight palette of grey overcast, churned brown mud and faded painted metal"
P3 = "a dusty palette of grey primer, white sanding haze and hard yellow lamp light"

MARKET = [
 ("A2_SH01", None, "market_old",
  "an open-air car market seen from high above on a grey morning, long rows of cars parked nose-out with cardboard cards under the wipers, puddles between the rows",
  "EWS","high","pan_right","day",True,False,
  "в девятнадцать ты снимаешь два места в четвёртом ряду и ставишь туда машины."),
 ("A2_SH02", "VIK_TEEN", "market_old",
  "Viktor standing beside a washed saloon at the end of a row with a rag over his shoulder, squaring the wing mirror with two fingers",
  "MS","eye","static","day",False,False,
  "первую свою машину ты покупаешь у соседа по гаражам ровно за половину цены."),
 ("A2_SH03", None, "market_old",
  "a hand-lettered cardboard price card wedged under a windscreen wiper, the numbers written twice and one of them crossed out, rain spots drying on the board",
  "INSERT","top","static","day",True,False,
  "на картонке под дворником ты пишешь цену, которая выше твоей на треть."),
 ("A2_SH04", "VIK_TEEN", "market_old",
  "Viktor's face turned slightly away from the car with his eyes unfocused, working something out behind them",
  "CU","low","push_in","day",False,False,
  "пробег на ней ты поправил накануне вечером, дома, прямо за кухонным столом."),
 ("A2_SH05", ("VIK_TEEN","GENA_BASE"), "market_old",
  "Viktor wipes down a bumper on one knee while Gena watches him work from a folding stool between two cars with a thermos cup in his hand",
  "WS","eye","static","day",False,False,
  "Гена ставит свою машину рядом и весь день молча смотрит, как ты работаешь."),
 ("A2_SH06", "VIK_TEEN", "market_old",
  "Viktor straightening up fast as somebody stops at his car, pulling the rag off his shoulder and pushing it into a pocket",
  "MCU","eye","static","day",False,False,
  "к обеду возле твоей машины останавливается мужчина в пальто и задаёт вопрос."),
 ("A2_SH07", "VIK_TEEN", "market_old",
  "an unnamed buyer in a heavy overcoat filling the foreground from behind with only his shoulder and the back of his head visible, Viktor beyond him on the far side of the car bonnet answering",
  "OTS","over","static","day",False,False,
  "а он не бит, спрашивает он, и смотрит тебе прямо в глаза."),
 ("A2_SH08", "VIK_TEEN", "market_old",
  "Viktor's face holding a completely even expression, his eyes steady, a small nod already finished",
  "CU","eye","push_in","day",False,True,
  "как себе брал, отвечаешь ты, и это оказывается первая твоя настоящая ложь."),
 ("A2_SH09", "VIK_TEEN", "market_old",
  "Viktor's hand and a stranger's hand meeting over a car roof around a folded stack of paper money, both faces out of frame above",
  "ECU","top","static","day",False,False,
  "он отдаёт деньги через крышу, не торгуясь, и уезжает уже через двадцать минут."),
 ("A2_SH10", None, "market_old",
  "a gap in a row of parked cars where a vehicle has just pulled out, a dry rectangle of asphalt left in the middle of the puddles",
  "WS","eye","pull_out","day",True,False,
  "на месте, где она только что стояла, остаётся сухой прямоугольник асфальта посреди луж."),
 ("A2_SH11", "VIK_TEEN", "market_old",
  "Viktor sitting sideways on a car bonnet with his boots off the ground, counting notes into his own lap",
  "MS","low","static","day",False,False,
  "твоя прибыль за один этот день равна четырём месяцам мойки чужих машин."),
 ("A2_SH12", "GENA_BASE", "market_old",
  "Gena's face with a slow single nod, the unlit cigarette still behind his ear, the corners of his eyes creasing",
  "CU","eye","static","day",False,False,
  "Гена медленно кивает и говорит, что теперь тебя от этого уже никто не отучит."),
 ("A2_SH13", None, "market_old",
  "an emptying car market at dusk seen from above, trampled mud between the vacated rows, wet paper price cards trodden into the ground, bunting sagging on its wire",
  "EWS","high","tilt_down","dusk",True,False,
  "рынок пустеет к пяти, и остаются только мокрая бумага и вытоптанная грязь."),
 ("A2_SH14", "VIK_YOUNG", "market_old",
  "Viktor walking down his own short row of three cars with a set of keys spinning on one finger, checking each windscreen card as he passes",
  "MS","eye","track","day",False,False,
  "через два года у тебя уже три машины в ряду и наёмный мойщик."),
 ("A2_SH15", "LENA_YOUNG", "market_old",
  "Lena's face behind the small sliding window of a breeze-block cashier's hut, her eyes down on a ledger, a pen moving steadily",
  "CU","eye","static","day",False,False,
  "деньги за место ты сдаёшь в будку, где сидит кассир по имени Лена."),
 ("A2_SH16", ("VIK_YOUNG","LENA_YOUNG"), "market_old",
  "Viktor leans both forearms on the cashier's hut ledge from outside while Lena, inside the window, flicks through notes with her thumb, her eyes staying down on the ledger",
  "MS","eye","static","day",False,False,
  "ей двадцать два, она считает быстрее тебя и при этом никогда не ошибается."),
 ("A2_SH17", "LENA_YOUNG", "market_old",
  "Lena finally lifting her eyes to the window with the notes still in her hands, one eyebrow going up",
  "CU","eye","push_in","day",False,False,
  "она спрашивает, почему у тебя каждый раз разные машины и одна барсетка."),
 ("A2_SH18", "VIK_YOUNG", "market_old",
  "Viktor caught searching for an answer, his mouth opening and closing once before he speaks",
  "CU","low","static","day",False,False,
  "ты отвечаешь ей честно, и это единственный честный раз за все тридцать лет."),
 ("A2_SH19", None, "market_old",
  "a breeze-block cashier's hut seen low from the queue side, a sliding glass window with a worn metal ledge, a hand-drawn arrow board bolted above it",
  "WS","low","static","day",True,False,
  "через восемь месяцев вы расписываетесь в обычный четверг, между двумя рабочими днями."),
 ("A2_SH20", ("VIK_YOUNG","LENA_YOUNG"), "flat_room",
  "Viktor carries a taped cardboard box in through the doorway while Lena kneels on the bare floorboards unwrapping cups from newspaper",
  "MS","eye","static","day",False,False,
  "свадьбы у вас нет, есть комната, продавленный диван и коробка посуды от её матери."),
 ("A2_SH21", None, "flat_room",
  "a flat oval locket lying open on a folded shirt at the edge of a bed, a tiny photograph set into one half of it",
  "ECU","eye","static","day",True,False,
  "в её медальоне лежит крошечная фотография отца, которого она совсем не помнит."),
 ("A2_SH22", "VIK_YOUNG", "flat_room",
  "Viktor standing at the balcony door in the evening with a full untouched cup in his hand, talking to somebody behind him while facing the glass",
  "MCU","eye","static","dusk",False,False,
  "ты обещаешь ей, что через пять лет у вас будет своя квартира."),
 ("A2_SH23", None, "dawn_road",
  "an empty road at first light with mist lying in the fields, the wet surface holding a single pale reflection of the sky",
  "WS","eye","track","dawn",True,False,
  "каждое утро ты выезжаешь в шесть и возвращаешься затемно, и так пять лет."),
 ("A2_SH24", ("VIK_YOUNG","GENA_BASE"), "market_old",
  "Viktor listens with a folder under his arm while Gena holds up two fingers explaining something to him, the two of them standing between parked cars",
  "MS","eye","static","day",False,False,
  "Гена учит тебя главному правилу: никогда не продавай тому, кто хорошо разбирается."),
 ("A2_SH25", "GENA_BASE", "market_old",
  "Gena's face close, speaking quietly with his chin tucked down, glancing once past the camera",
  "CU","low","static","day",False,True,
  "разбирающийся будет искать подвох, а обычному человеку нужно только твоё спокойное лицо."),
 ("A2_SH26", None, "market_old",
  "a row of hand-written cardboard price cards under a row of wipers, each number formed carefully, one of them already amended",
  "INSERT","top","static","day",True,False,
  "ты учишься писать цену так, чтобы она выглядела уже однажды кому-то уступленной."),
 ("A2_SH27", "VIK_YOUNG", "market_old",
  "Viktor talking to somebody just out of frame with an easy open palm turned upward, entirely relaxed",
  "MCU","eye","push_in","day",False,False,
  "в двадцать два ты произносишь эту фразу по десять раз в день."),
 ("A2_SH28", None, "market_old",
  "the whole car market from very high at dusk, hundreds of roofs in rows, tail lights leaving through a single gate in the fence",
  "EWS","high","pull_out","dusk",True,False,
  "и ни один человек за два года не вернулся к тебе с претензией."),
]

CRAFT = [
 ("A3_SH01", None, "body_shop",
  "a rented body-repair bay with plastic sheeting taped across the doorway, a car shell in grey primer standing on axle stands, a lamp on a stand throwing a hard cone of light",
  "WS","eye","static","day",True,False,
  "в двадцать четыре ты снимаешь покрасочный бокс за городом на два дня в неделю."),
 ("A3_SH02", "VIK_YOUNG", "body_shop",
  "Viktor lying on his side on a folded blanket under a car sill with a welding mask pushed up on his forehead, running a bead along the seam",
  "MS","low","static","day",False,False,
  "ты учишься варить пороги так, что шов не находит потом даже магнит."),
 ("A3_SH03", "OBJ:putty", None,
  "a trestle table crowded with tins under a work lamp",
  "INSERT","top","push_in","interior",True,False,
  "шпатлёвка сохнет двадцать минут, и после неё крыло становится ровным, как новое."),
 ("A3_SH04", "VIK_YOUNG", "body_shop",
  "Viktor holding a sprayed test card up beside a wing at eye height and squinting between the two surfaces",
  "CU","low","static","day",False,False,
  "краску ты подбираешь на глаз и попадаешь с третьего раза из трёх."),
 ("A3_SH05", None, "body_shop",
  "a repair bay filled with hanging white dust in a lamp beam, sanding paper crumpled on the floor, a compressor standing in the corner with its hose coiled",
  "WS","high","static","day",True,False,
  "в боксе всегда висит белая пыль, и через год ты начинаешь по утрам кашлять."),
 ("A3_SH06", ("VIK_YOUNG","GENA_BASE"), "body_shop",
  "Viktor pulls his dust mask down under his chin while Gena, just inside the plastic sheeting, counts cars off on his fingers at him",
  "MCU","eye","static","day",False,False,
  "Гена привозит тебе клиентов и берёт себе десятую часть с каждой машины."),
 ("A3_SH07", "GENA_BASE", "body_shop",
  "Gena's face lit from one side by the work lamp, looking along a repaired wing with one eye closed",
  "CU","eye","static","day",False,False,
  "он говорит, что ты работаешь чище всех, кого он видел за двадцать лет."),
 ("A3_SH08", None, "flood_yard",
  "a flooded parking area seen from high above, rows of car roofs standing out of brown water, debris drifting between them under a flat overcast sky",
  "EWS","high","pan_left","day",True,False,
  "весной приходит большая вода, и за три дня тонет целая городская стоянка."),
 ("A3_SH09", None, "flood_yard",
  "cars standing in brown water up to their door handles with a tide line of silt across every panel, a drowned hedge behind them",
  "WS","low","static","day",True,False,
  "машины стоят в воде по ручки дверей, и хозяева отдают их почти даром."),
 ("A3_SH10", "VIK_YOUNG", "flood_yard",
  "Viktor wading in rubber boots to a hitch and hooking a tow strap onto a submerged towing eye, water to his knees",
  "MS","eye","track","day",False,False,
  "ты покупаешь шесть штук за одну цену и вывозишь их отсюда на тросе."),
 ("A3_SH11", None, "body_shop",
  "a car floor carpet peeled back off the metal pan, a hard tide line of dried silt printed across the steel underneath it",
  "INSERT","top","static","interior",True,True,
  "под ковролином остаётся полоска сухого ила, и её видно только если его поднять."),
 ("A3_SH12", "VIK_YOUNG", "body_shop",
  "Viktor holding a hot air blower into an open car interior with the doors spread wide, a new roll of carpet leaning against the wing",
  "MCU","eye","static","day",False,False,
  "ты сушишь салоны феном, меняешь ковролин и по два дня прогоняешь озоном."),
 ("A3_SH13", "VIK_YOUNG", "body_shop",
  "Viktor leaning into a finished interior and drawing one slow breath through his nose with his eyes shut",
  "CU","low","push_in","day",False,False,
  "через неделю ни один покупатель уже не отличит утопленницу от сухой машины."),
 ("A3_SH14", None, "market_old",
  "six clean cars standing in a short row with fresh cards under their wipers, wet asphalt reflecting them, a queue of two people at the far end",
  "WS","eye","static","day",True,False,
  "все шесть уходят за месяц, и на каждой ты берёшь как за год мойки."),
 ("A3_SH15", "VIK_YOUNG", "market_old",
  "Viktor sitting in an open car door with his feet on the ground, sorting banded bundles into the leather pouch on his knee",
  "MS","eye","static","day",False,False,
  "ты впервые считаешь деньги не пачкой, а стопкой пачек в одной барсетке."),
 ("A3_SH16", "OBJ:barsetka", None,
  "a car seat with a folded jacket pushed to one side",
  "INSERT","top","static","interior",True,False,
  "барсетка перестаёт застёгиваться, и теперь ты каждый вечер стягиваешь её канцелярской резинкой."),
 ("A3_SH17", None, "flat_kitchen",
  "a kitchen late in the evening with one plate under a cloth on the table, the lamp on, a chair pulled out and left standing away from the table",
  "WS","eye","static","night",True,False,
  "дома Лена уже на седьмом месяце, а ты почти не бываешь по вечерам дома."),
 ("A3_SH18", "LENA_YOUNG", "flat_kitchen",
  "Lena sitting sideways at the kitchen table with one hand flat on her stomach, looking at the door instead of the food",
  "MCU","eye","static","night",False,False,
  "она спрашивает только одно: успеешь ли ты к родам, и ты обещаешь."),
 ("A3_SH19", "VIK_YOUNG", "dawn_road",
  "Viktor's face behind a windscreen at night lit green from the dashboard, both eyes fixed far down the road",
  "CU","low","static","night",False,False,
  "в ту ночь ты перегоняешь машину из соседнего города и не успеваешь."),
 ("A3_SH20", None, "flat_room",
  "a pair of tiny knitted socks laid over a warm radiator beside a folded towel, morning light across the wall behind them",
  "ECU","top","static","day",True,False,
  "Денис рождается в ноябре, и ты видишь его только на третьи сутки."),
 ("A3_SH21", "VIK_YOUNG", "flat_room",
  "Viktor standing in a doorway holding a cardboard box against his chest, stopped on the threshold, looking for somewhere to put it down",
  "MS","eye","static","day",False,False,
  "ты стоишь в дверях комнаты с коробкой и не знаешь, куда её поставить."),
 ("A3_SH22", "VIK_YOUNG", "flat_room",
  "Viktor's face over the top edge of the box, his eyes moving around the room and measuring it",
  "CU","eye","push_in","day",False,False,
  "ты думаешь не о сыне, а о том, что нужна квартира побольше."),
 ("A3_SH23", None, "flat_room",
  "an empty two-room flat with bare walls, a roll of wallpaper standing in the corner and light falling across unswept floorboards",
  "WS","high","pan_right","day",True,False,
  "через год вы въезжаете в двухкомнатную квартиру на четвёртом этаже без лифта."),
 ("A3_SH24", ("LENA_YOUNG","VIK_YOUNG"), "flat_kitchen",
  "Lena sets two cups down on the oilcloth while Viktor pulls out a chair opposite her with the leather pouch still on his wrist",
  "MS","eye","static","day",False,False,
  "Лена спрашивает, откуда деньги, и ты отвечаешь ей, что просто много работаешь."),
 ("A3_SH25", "LENA_YOUNG", "flat_kitchen",
  "Lena's face taking the answer in with her expression completely level, her eyes going down to her cup",
  "CU","eye","static","day",False,False,
  "это чистая правда, и поэтому она перестаёт спрашивать на следующие пятнадцать лет."),
 ("A3_SH26", None, "body_shop",
  "a shelf of workshop tins with one tall grey aerosol can standing at the front, its cap off and the nozzle already used",
  "INSERT","eye","static","interior",True,False,
  "на полке у тебя в боксе появляется самый первый баллон серого антигравия."),
 ("A3_SH27", "VIK_YOUNG", "body_shop",
  "Viktor kneeling beside a raised sill with the aerosol upside down, laying an even grey coat along the underbody",
  "MS","low","static","day",False,False,
  "им закрашивают ржавчину снизу, а под машину заглядывает один покупатель из ста."),
 ("A3_SH28", "VIK_YOUNG", "body_shop",
  "Viktor's face turned up towards the lamp with a light coat of grey overspray on his cheekbone, entirely untroubled",
  "CU","low","static","day",False,True,
  "ты перестаёшь называть это враньём и начинаешь называть это обычной предпродажной подготовкой."),
 ("A3_SH29", None, "dawn_road",
  "a straight road at dawn with a low sun behind, telegraph poles stepping to the horizon and a thin band of mist over the fields",
  "WS","low","track","dawn",True,False,
  "в двадцать семь у тебя сорок одна проданная машина за один только год."),
 ("A3_SH30", None, "market_old",
  "the market from very high in the late afternoon, the rows thinning out, long shadows reaching across the churned ground",
  "EWS","high","pull_out","dusk",True,False,
  "и вокруг ни одного человека, который мог бы сказать тебе хоть что-то поперёк."),
]

if __name__ == "__main__":
    seed_act("market", P2, MARKET)
    seed_act("craft",  P3, CRAFT)
