# -*- coding: utf-8 -*-
"""sailor_wife acts: vows (1980, 26) + letters (1982–84, 26). ALL animated.
Run: PYTHONIOENCODING=utf-8 python scripts/_seed_sailor_wife_A2A3.py"""
from _sailor_wife_engine import seed_act

PAL2="tender ceremony palette of white cotton, red carpet runner, brass horn gold and clear may sky"
VOWS=[
("A2_SH01",None,"wedding_hall",
 "the modest civil wedding hall of nineteen-eighty, a red carpet runner leading to the official desk, ribbon bows on borrowed chairs, morning sun through sheer curtains",
 "WS","eye","push_in","morning",True,False,
 "май восьмидесятого, зал бракосочетаний открывается в десять, и ваша очередь самая первая."),
("A2_SH02","ANNA_YOUNG","wedding_hall",
 "the twenty-year-old bride in the neighbour-sewn white dress holding a small bunch of lilies of the valley, breathing carefully, her dark waves pinned high",
 "MCU","eye","static","morning",False,True,
 "ты стоишь в платье, сшитом всем двором, и держишь ландыши так, чтобы не дрожали.",
 "the small bouquet steadying in her doubled grip, her careful breath lifting the lace at her collar"),
("A2_SH03","VIKTOR_YOUNG","wedding_hall",
 "the young seaman in his best uniform putting a thin ring onto the bride's finger with enormous concentration, his weathered hands very careful",
 "OTS","over","static","morning",False,True,
 "виктор надевает тебе кольцо с таким лицом, с каким швартуют судно в узкой гавани.",
 "his big careful fingers guiding the thin ring home, a held breath releasing as it settles"),
("A2_SH04","ANNA_YOUNG","wedding_hall",
 "the bride and groom turning from the desk to a small burst of applause, rice thrown, the accordionist striking up in the corner",
 "WS","eye","static","morning",False,False,
 "вас осыпают рисом девять соседок, две подруги и половина экипажа его будущего судна.",
 "rice scattering through the sunbeam, the couple turning into the applause, the accordion bellows spreading"),
("A2_SH05","ZINA_BASE","wedding_hall",
 "the copper-haired neighbour crying and laughing at once in the front row, dabbing her eyes with the hem of her festive scarf, gold hoops trembling",
 "MCU","eye","static","morning",False,False,
 "зина плачет громче всех и тут же командует, куда ставить салаты и кому нести патефон.",
 "her scarf hem dabbing at running eyes, her other arm already directing traffic toward the door"),
("A2_SH06",None,"courtyard_bench",
 "the courtyard turned into a wedding table under the acacia, pushed-together tables with mismatched cloths, a patefon on a stool, paper lanterns strung between laundry poles",
 "EWS","high","static","evening",True,False,
 "гуляют всем двором до темноты, и даже кот с третьего этажа получает свою котлету."),
("A2_SH07","ANNA_YOUNG","anna_kitchen",
 "the young wife in an apron over her nightgown frying breakfast, laughing over her shoulder at someone beyond the frame, morning sun on the shell-print oilcloth",
 "MS","eye","static","morning",False,False,
 "у вас есть девять дней своей семьи, и ты решаешь прожить их без единой мысли о дате.",
 "her spatula pausing as she laughs over her shoulder, oil sputtering softly, sun warming the oilcloth"),
("A2_SH08","VIKTOR_YOUNG","anna_kitchen",
 "the young husband repairing a kitchen shelf bracket in an undershirt, the swallow tattoo flexing on his forearm, screws held in his lips",
 "MCU","eye","static","morning",False,False,
 "виктор за эти дни чинит в квартире всё, что скрипит, будто оставляет дом в полном порядке.",
 "the screwdriver turning in sure strokes, screws shifting in his lips, the tattooed forearm working"),
("A2_SH09","ANNA_YOUNG","promenade",
 "the young couple walking the promenade close together in evening light, her head on his shoulder, his cap on her head, gulls loafing on the railing",
 "WS","eye","track","evening",False,False,
 "вечерами вы ходите по набережной, и его фуражка на твоей голове сползает тебе на нос.",
 "their slow steps matched, the oversized cap slipping down her brow, his arm steadying her waist"),
("A2_SH10","VIKTOR_YOUNG","promenade",
 "the young seaman fastening a fine chain at his wife's nape, his face grave, a tiny silver anchor catching the sunset between them",
 "MCU","eye","push_in","evening",False,True,
 "накануне рейса он застёгивает на тебе цепочку и говорит, якорёк, чтобы мне было куда возвращаться.",
 "his fingers working the tiny clasp at her nape, the little anchor swinging into the sunset light"),
("A2_SH11","OBJ:anchor_pendant",None,
 "a small bright new silver anchor pendant lying in the hollow of a young throat, the chain fine as thread, sunset warm on the skin",
 "ECU","eye","static","evening",False,True,
 "якорёк ещё новый и острый по краям, у него впереди сорок шесть лет, чтобы стать мягким.",
 "the pendant settling into the hollow of her throat, flaring once as she breathes"),
("A2_SH12",None,"port_quay",
 "the quay at dawn before a departure, a freighter with deck lights still on, cranes motionless, kit bags and families gathering in pools of lamp light",
 "WS","eye","static","morning",True,False,
 "отход назначен на шесть утра, и причал в этот час полон одинаковых тихих семей."),
("A2_SH13","VIKTOR_YOUNG","port_quay",
 "the young seaman at the gangway holding his wife's face in both hands, foreheads together, his kit bag standing between their feet",
 "MCU","eye","static","morning",False,True,
 "он берёт твоё лицо в ладони и говорит, семь месяцев, аня, это же просто семь календарей.",
 "his palms framing her face, foreheads pressing together, the kit bag leaning against their legs"),
("A2_SH14","ANNA_YOUNG","port_quay",
 "the young wife nodding fast with a smile held together by will, her hand pressed flat to his chest, the gangway rail behind him",
 "CU","eye","static","morning",False,False,
 "ты киваешь и улыбаешься, потому что решила твёрдо, он не увезёт в рейс твоих слёз.",
 "her fast small nods, the smile holding its line, her palm pressed flat over his heartbeat"),
("A2_SH15",None,"port_quay",
 "the freighter's stern sliding away from the quay wall, a widening strip of dirty green water, mooring lines splashing free, gulls lifting",
 "MS","low","static","morning",True,False,
 "полоса воды между бортом и стенкой растёт от ладони до улицы за четыре минуты."),
("A2_SH16","ANNA_YOUNG","port_quay",
 "the young wife alone at the bollard where the families are thinning, her hand raised, her figure very straight against the huge departing ship",
 "WS","eye","static","morning",False,True,
 "и тут с рейда судно даёт три длинных гудка, и боцман потом расскажет, это было тебе.",
 "her raised hand freezing at the sound, the great ship's silhouette blurring in the morning haze"),
("A2_SH17","ANNA_YOUNG","anna_window_room_80s",
 "the young wife standing in the middle of the tidy bright room in evening light, suddenly not knowing what to do with her hands, the bed's second pillow untouched",
 "MS","eye","static","evening",False,False,
 "первый вечер одна ты просто стоишь посреди комнаты и учишься дышать в пустой тишине.",
 "her hands lifting, hesitating, settling on her elbows, her eyes travelling the too-tidy room"),
("A2_SH18",None,"anna_kitchen",
 "a ship's calendar pinned by the kitchen door, the first square crossed in pencil, two hundred and nine squares clean ahead, a pencil hanging on a string beside it",
 "INSERT","eye","static","evening",True,False,
 "на календаре у двери ты зачёркиваешь первый квадратик, впереди их двести девять."),
("A2_SH19","ANNA_YOUNG","post_office",
 "the young wife at the post-office counter mailing a fat envelope, standing on tiptoe to watch it weighed on brass scales, other wives queueing behind her",
 "MS","eye","static","day",False,False,
 "письма в его пароходство принимают по средам, и очередь в среду состоит из одних жён.",
 "the envelope tipping onto the brass scale pan, her tiptoe lean over the counter, the queue shifting behind"),
("A2_SH20",None,"harbor_panorama",
 "the harbour in deep winter, ice sheets grinding at the breakwater, cranes rimed white, a channel of black water kept open by a small icebreaking tug",
 "EWS","eye","static","day",True,False,
 "зима запирает бухту льдом, но канал для своих порт держит открытым в любой мороз."),
("A2_SH21","ANNA_YOUNG","anna_window_room_80s",
 "the young wife reading a worn letter in the window light with frost ferns on the glass, a small carved wooden gull already standing alone on the new wall shelf",
 "MCU","eye","static","day",False,False,
 "его письма приходят пачками по три, и ты растягиваешь их, как хлеб в голодный год.",
 "the letter pages turning slowly, frost light on her absorbed face, her free hand touching the pendant"),
("A2_SH22","ZINA_BASE","anna_kitchen",
 "the copper-haired neighbour's strong fingers folding down one by one over the teacup, gold hoops swinging at the frame's edge with the lecture",
 "CU","eye","static","evening",False,False,
 "зина загибает пальцы и учит, борщ ему в первый день, баню во второй, претензии никогда.",
 "her fingers folding down one by one, the teacup pausing mid-air for emphasis, hoops swinging"),
("A2_SH23","ANNA_YOUNG","port_quay",
 "the spring quay wide with families as an arriving freighter's rail crowds with waving crewmen, one young wife rising on tiptoe among them, the water still churning at the stern",
 "WS","eye","static","day",False,True,
 "в марте его судно входит в ковш, и ты находишь его у леера раньше, чем он тебя.",
 "her eyes sweeping the crowded rail and stopping, her arm shooting up, her heels leaving the ground"),
("A2_SH24","VIKTOR_YOUNG","port_quay",
 "the young seaman coming down the gangway with his kit bag and a small parcel held separate and careful, his grin arriving ahead of him",
 "MS","low","static","day",False,False,
 "он сходит по трапу с рюкзаком и отдельным свёртком, который держит, как хрустальный.",
 "his boots taking the gangway steps two at a time, the careful parcel riding high in one hand"),
("A2_SH25","ANNA_YOUNG","anna_window_room_80s",
 "the young couple's four hands lowering one small carved figure onto the wall shelf together, laughter just out of frame",
 "CU","eye","static","evening",False,True,
 "на полку встаёт второй сувенир, и вы торжественно жмёте друг другу руки, как на открытии памятника.",
 "four hands lowering the little figure onto the shelf, a mock-solemn handshake following"),
("A2_SH26",None,"anna_window_room_80s",
 "the wall shelf in lamplight holding exactly two small souvenirs with a whole empty length of wood stretching beside them",
 "INSERT","eye","pull_out","night",True,False,
 "на полке два сувенира и очень много пустого дерева, но об этом ты пока не думаешь."),
]

PAL3="gentle nursery palette of envelope cream, ink blue, swaddle white and lamplit rose"
LETTERS=[
("A3_SH01","ANNA_YOUNG","anna_kitchen",
 "the young wife writing a letter at the kitchen table with one hand resting on her rounded belly, the pencil calendar behind her thick with crossed squares",
 "MS","eye","static","evening",False,True,
 "в восемьдесят втором ты пишешь ему письмо, где после слова здравствуй стоит слово папа.",
 "her pen stopping after the first line, her hand smoothing slow circles on her belly, a smile arriving"),
("A3_SH02","VIKTOR_MID","ship_cabin",
 "a seaman reading a letter under the small cabin lamp, the page trembling although the sea is calm, a family photograph clipped over the fold-down desk",
 "MCU","eye","static","night",False,True,
 "письмо догоняет его через океан, и вахтенный потом божится, что слышал крик радости с юта.",
 "the letter page trembling in his still hands, his eyes going over one line again and again"),
("A3_SH03",None,"ship_bridge",
 "the cargo ship's bridge at night, radar hoods glowing green, the long bow deck running ahead into darkness, stars thick over a calm sea",
 "WS","eye","static","night",True,False,
 "его судно в эту ночь идёт через десятый градус широты, и до дома одиннадцать тысяч миль."),
("A3_SH04","ANNA_YOUNG","courtyard_bench",
 "the young wife on the courtyard bench in late pregnancy, neighbour women around her knitting tiny things, the acacia dropping white petals on the wool",
 "WS","eye","static","day",False,False,
 "двор вяжет твоему ребёнку приданое всем составом, и спицы стучат громче домино.",
 "knitting needles flickering around the bench, petals drifting onto the white wool, her laugh joining the talk"),
("A3_SH05","ZINA_BASE","courtyard_bench",
 "the copper-haired neighbour holding up two impossibly small knitted socks, presenting them to the bench like a trophy, pride and tears mixing",
 "MCU","eye","static","day",False,False,
 "зина поднимает над головой первые крошечные носочки и объявляет на весь двор, морскому роду пополнение.",
 "the tiny socks rising over her head, her chin wobbling once before the triumphant grin wins"),
("A3_SH06",None,"anna_window_room_80s",
 "the bright room readied for a baby, a borrowed cot by the window, ironed swaddles in a stack, the two souvenirs on the shelf keeping watch",
 "WS","eye","push_in","day",True,False,
 "к июлю комната готова, кроватка занимает место у окна, чтобы ребёнку было видно порт."),
("A3_SH07","ANNA_YOUNG","anna_window_room_80s",
 "the young mother by the window with a swaddled newborn, her cheek against the tiny head, exhausted and lit from within, summer light soft on them",
 "MCU","eye","push_in","day",False,True,
 "оля рождается в июле, в четверг, и первым делом вы вдвоём идёте показать ей окно.",
 "her cheek settling on the tiny head, the swaddle stirring, her tired eyes shining over the sill"),
("A3_SH08","OBJ:radiogram",None,
 "a telegraph radiogram form with twelve sparse typed capital words and a purple date stamp, held flat by a man's weathered thumb",
 "ECU","top","static","day",False,True,
 "радиограмма на судно вмещает двенадцать слов, и семь из них — это её имя и вес.",
 "the weathered thumb pressing the form flat, the paper edge lifting slightly in a draught"),
("A3_SH09","VIKTOR_MID","ship_bridge",
 "the seaman on the bridge wing gripping the rail with both hands, looking at the horizon with the radiogram folded into his breast pocket, wind in his fair hair",
 "MS","low","static","day",False,False,
 "он выносит радиограмму на крыло мостика и читает её океану вслух, чтобы было кому разделить.",
 "his hands flexing on the rail, wind pulling his hair, his chest rising with the read-aloud words"),
("A3_SH10","ANNA_YOUNG","anna_kitchen",
 "the young mother writing at the kitchen table with the baby asleep in a wash basket beside her, describing something with her free hand as if he could see",
 "MS","eye","static","night",False,False,
 "ты пишешь ему каждый её день, первый зуб дважды, потому что первое письмо утонуло где-то в тропиках.",
 "her pen hurrying down the page, her free hand sketching the story in the air over the sleeping basket"),
("A3_SH11",None,"post_office",
 "the post-office wall clock over the row of numbered booths, benches of waiting women below it, winter coats steaming in the warmth",
 "WS","eye","static","day",True,False,
 "почта зимой пахнет мокрым сукном и сургучом, и все здесь ждут одного и того же."),
("A3_SH12","ANNA_YOUNG","anna_window_room_80s",
 "the young mother holding a standing baby up at the window, small palm pressed to the glass over the harbour, both looking out",
 "MCU","eye","static","day",False,True,
 "оле восемь месяцев, она умеет говорить дай и мама и знает окно лучше всех игрушек.",
 "the small palm patting the glass, the baby bouncing on her supporting arm, two profiles to the light"),
("A3_SH13",None,"port_quay",
 "a freighter warping slowly to the quay wall in spring light, heaving lines flying, families pressed to the barrier, bollards taking the first loops",
 "EWS","high","static","day",True,False,
 "в апреле восемьдесят третьего судно швартуется девять месяцев и четыре дня спустя."),
("A3_SH14","VIKTOR_MID","port_quay",
 "the seaman stopped dead at the foot of the gangway, staring at the bundle in his wife's arms, his kit bag sliding off his shoulder unnoticed",
 "MS","eye","static","day",False,True,
 "виктор замирает у трапа, потому что уходил он от жены, а встречают его двое.",
 "his kit bag sliding slowly off his shoulder to the concrete, his eyes fixed on the small bundle"),
("A3_SH15","VIKTOR_MID","port_quay",
 "the big seaman taking the baby with terrified ceremony, his weathered hands suddenly enormous around the small body, his wife guiding his elbow",
 "MCU","eye","push_in","day",False,True,
 "он берёт дочь на руки так осторожно, будто она из корабельного компаса, и боится дышать.",
 "his huge hands closing by careful degrees around the baby, his breath held, her hand steadying his elbow"),
("A3_SH16","ANNA_YOUNG","port_quay",
 "the young mother watching her husband and daughter meet, one hand at the pendant on her throat, her laugh and tears arriving together",
 "CU","eye","static","day",False,False,
 "ты смотришь, как знакомятся два самых главных твоих человека, и у тебя щиплет в носу.",
 "her fingers finding the pendant, her laugh breaking wet, her eyes going between the two faces"),
("A3_SH17","VIKTOR_MID","anna_window_room_80s",
 "the seaman on the floor of the bright room building a tower of wooden blocks with the baby, his kit bag still unpacked in the doorway",
 "WS","eye","static","evening",False,False,
 "первые три дня дома он не разбирает рюкзак, потому что руки заняты более важным грузом.",
 "block towers rising and toppling between them, the baby's hands slapping the floor, his laugh rolling low"),
("A3_SH18","OBJ:ship_in_bottle",None,
 "a small sailing ship inside a glass bottle being set onto a wall shelf beside two other souvenirs, thread rigging fine as cobweb",
 "INSERT","eye","static","evening",False,False,
 "третий сувенир — кораблик в бутылке, и оля тянется к нему с первого же дня.",
 "the bottle turning slowly as it settles onto the shelf, the tiny paper flag trembling inside"),
("A3_SH19","ANNA_YOUNG","anna_kitchen",
 "the young family at the kitchen table, the seaman feeding the baby with comic concentration, porridge on his cheek, the mother laughing into her cup",
 "MS","eye","static","morning",False,False,
 "три месяца берега вы живёте, как люди из песен, завтракая втроём каждое утро.",
 "the spoon travelling with naval precision and missing, porridge landing on his cheek, laughter shaking her cup"),
("A3_SH20","VIKTOR_MID","seafarers_office",
 "the seaman's set jaw and his pen signing a contract folder in one hard stroke, the counter's worn edge and an inked stamp waiting beside",
 "CU","eye","static","day",False,False,
 "потом контора выписывает новый рейс, потому что штурманов не хватает, а он лучший.",
 "his pen signing in one hard stroke, the folder turning back across the counter, his jaw working"),
("A3_SH21","ANNA_YOUNG","port_quay",
 "the young mother at the quay barrier holding the toddler up, moving the small arm in a wave toward the departing ship, her own face carefully bright",
 "MS","eye","static","morning",False,True,
 "теперь на причале машете двое, и ты водишь олиной ручкой, пока судно не тает.",
 "the toddler's arm waving in her guiding hand, the ship shrinking beyond, her bright face holding"),
("A3_SH22",None,"harbor_panorama",
 "the harbour in autumn rain, a departed ship far out at the roads, its wake dissolving, wet cranes shining, one umbrella moving along the quay",
 "EWS","eye","static","day",True,False,
 "осенью бухта дышит дождём, и у горизонта суда стоят на рейде, как чужие города."),
("A3_SH23","ANNA_YOUNG","anna_window_room_80s",
 "the young mother reading a letter aloud to the toddler on her lap by the window, pointing at words as if the baby could follow, the shelf of three souvenirs above",
 "MCU","eye","static","evening",False,False,
 "письма ты теперь читаешь оле вслух, и папин почерк она узнаёт раньше, чем буквы.",
 "the letter held open for two readers, her finger travelling the lines, the child's hand slapping the page"),
("A3_SH24","VIKTOR_MID","ship_cabin",
 "the seaman's palms smoothing a child's drawing of a house and a huge sun flat against the steel over his bunk, the family photograph beside it",
 "CU","eye","static","night",False,True,
 "над его койкой теперь висит олин рисунок, дом, солнце и три человечка, взявшиеся за руки.",
 "his palms smoothing the drawing flat against the steel, his thumb pressing down the last corner"),
("A3_SH25","ANNA_YOUNG","anna_kitchen",
 "the young mother teaching the toddler to cross a calendar square with the pencil on its string, small fist in her guiding hand, both very serious",
 "MS","high","static","evening",False,False,
 "вечером вы вместе зачёркиваете квадратик на календаре, и это ваш с ней тайный ритуал.",
 "the guided pencil scratching one careful cross, the toddler's proud fist rising, her kiss landing on the crown"),
("A3_SH26",None,"anna_kitchen",
 "the kitchen calendar in lamplight, three years of pencil crosses layered over reprinted months, the pencil on its string worn to a stub",
 "INSERT","eye","push_in","night",True,False,
 "к восемьдесят четвёртому карандаш у календаря стёрся до огрызка, а сам календарь меняли дважды."),
]

seed_act("vows",PAL2,VOWS)
seed_act("letters",PAL3,LETTERS)
