# -*- coding: utf-8 -*-
"""fortune batch C: act06_devil + act07_justice + act08_tower."""
from _fortune_engine import seed_act

PAL_DEVIL="lurid curse-work neon palette, sickly green and violet glow, oppressive candle red, black-salt shadow"
A6=[
 ("F6_SH01","ZARA_YOUNG","reading_room","the madam gravely leaning toward a frightened client across the candlelit table, green-violet neon glow","MCU","over","push_in","night",False,False,
  "тебе за тридцать, и теперь у тебя есть товар дороже надежды, и называется он снятие порчи."),
 ("F6_SH02","ZARA_YOUNG","reading_room","close on the madam's solemn lowered voice and hard eyes telling a client grave news, candle smoke","CU","eye","static","night",False,False,
  "ты говоришь человеку тихо и страшно, на вас навели порчу, я вижу её ясно, но я смогу её снять."),
 ("F6_SH03",None,"reading_room","extreme close on an egg cracked into a glass of water on velvet, dark threads swirling inside, sickly neon","ECU","top","push_in","night",False,True,
  "ты разбиваешь яйцо в воду, и в мутных нитях белка человек видит свою беду, а ты видишь свой заработок."),
 ("F6_SH04","ZARA_YOUNG","reading_room","the madam performing an elaborate candle-and-salt ritual over a trembling client, theatrical, smoke and green neon","MS","low","static","night",False,False,
  "ты жжёшь свечи, сыплешь чёрную соль, шепчешь, и обставляешь всё так, что не поверить просто нельзя."),
 ("F6_SH05",None,"reading_room","extreme close on a thick envelope of bills pushed across velvet beside black salt and a melted wax figure","INSERT","top","static","night",False,False,
  "первое снятие стоит четыре тысячи, и человек платит с облегчением, лишь бы беда ушла из его дома."),
 ("F6_SH06","ZARA_YOUNG","reading_room","close on the madam's calm eyes pocketing the money, no chill on her arms this time, only practised calm","CU","eye","push_in","night",False,True,
  "и холодок по рукам больше не бежит, ни разу, ты переступила черту так давно, что и забыла, где она была."),
 ("F6_SH07","WIDOW","reading_room","a pale grieving woman in black with a silver locket sitting down at the reading table, red-rimmed eyes, dim neon","MS","eye","push_in","night",False,True,
  "однажды к тебе приходит вдова маргарет, вся в чёрном, с медальоном на шее, и просит поговорить с мужем."),
 ("F6_SH08","WIDOW","reading_room","close on the widow's grief-worn face clutching a silver locket to her chest, candlelight and violet neon","CU","eye","static","night",False,False,
  "она потеряла его полгода назад, и не может ни спать, ни жить, и держится только за этот медальон."),
 ("F6_SH09","ZARA_YOUNG","reading_room","the madam reading the widow's black clothes and locket with a practised sweeping glance, calculating","OTS","over","static","night",False,False,
  "ты считываешь её с одного взгляда, свежее горе, деньги от страховки, и никого, кто бы её удержал от тебя."),
 ("F6_SH10","ZARA_YOUNG","reading_room","the madam gravely telling the widow her husband's soul is trapped by a curse, the widow leaning in desperate","MCU","eye","push_in","night",False,False,
  "и ты говоришь ей, его душа не может уйти, маргарет, её держит порча, но я смогу освободить его, за плату."),
 ("F6_SH11","WIDOW","reading_room","close on the widow's face lighting with terrible hope, tears, gripping the locket, green neon glow","CU","low","push_in","night",False,True,
  "и в её глазах вспыхивает такая надежда, что тебе на миг почти стыдно, но только на один короткий миг."),
 ("F6_SH12",None,"reading_room","extreme close on a widow's trembling hand opening a worn purse, counting out savings onto the velvet","ECU","top","static","night",False,False,
  "она приносит первые четыре тысячи, потом ещё, и ещё, и ты каждый раз находишь новую, более глубокую порчу."),
 ("F6_SH13","ZARA_YOUNG","reading_room","the madam conducting a grander ritual with many candles and black salt around the rapt widow, heavy neon haze","MS","low","static","night",False,False,
  "обряды становятся всё пышнее, всё дороже, и маргарет ходит к тебе как на работу, и тает на глазах."),
 ("F6_SH14","WIDOW","reading_room","the widow looking thinner and shabbier than before, still clutching the locket, handing over a large envelope","MCU","eye","static","night",False,False,
  "через год она отдаёт тебе двенадцать тысяч, последнее, что осталось от мужа, и едва не закладывает медальон."),
 ("F6_SH15",None,"reading_room","extreme close on the widow's silver locket held out hesitantly, then pulled back to her chest, candle glow","ECU","eye","push_in","night",False,True,
  "ты почти забираешь и медальон, но она прижимает его к груди, и ты отступаешь, не из жалости, а чтоб не спугнуть."),
 ("F6_SH16","ZARA_YOUNG","reading_room","close on the madam's face, a buried flicker of conscience instantly smothered by calculation, violet neon","CU","low","push_in","night",False,True,
  "где-то глубоко что-то шевелится в тебе, но ты гасишь это, как гасят свечу двумя пальцами, быстро и привычно."),
 ("F6_SH17",None,"back_alley","a wet green-and-violet neon back alley at night, the madam's silhouette unbothered, money in her coat, steam","WS","high","pan_right","night",True,False,
  "ты выходишь в переулок пересчитать выручку, и неон зеленью дрожит в лужах, и совесть молчит, как немая."),
 ("F6_SH18","ZARA_YOUNG","reading_room","the madam telling the returning widow the curse is deeper still, requiring yet more, calm and merciless","OTS","eye","static","night",False,False,
  "ты говоришь маргарет, что порча пустила корни глубже, чем ты думала, и нужен ещё один, последний обряд."),
 ("F6_SH19","WIDOW","widow_house","the widow alone in a dim house full of her dead husband's photos, counting almost nothing left, the locket on","MS","high","static","day",False,False,
  "она продаёт мужнины часы, его инструменты, его машину, и в её доме остаются только фотографии и медальон."),
 ("F6_SH20","WIDOW","widow_house","close on the widow's hollowed face among framed photos of her late husband, faith and ruin together","CU","eye","push_in","day",False,True,
  "она верит, что вот-вот освободит его душу, и не видит, что ты освобождаешь только её карманы, до дна."),
 ("F6_SH21",None,"reading_room","extreme close on a tarot spread crowned by the devil card face-up amid black salt and dripping candles","INSERT","top","push_in","night",False,True,
  "ты раскладываешь на ночь карты, и наверху ложится дьявол, и ты усмехаешься, мол, просто красивая картинка."),
 ("F6_SH22","ZARA_YOUNG","reading_room","the madam alone after hours telling herself a justification, chin lifted, hard and certain, neon glow","MS","low","static","night",False,False,
  "я даю им надежду, говоришь ты пустому салону, без меня они выли бы в подушку, а так хотя бы во что-то верят."),
 ("F6_SH23","ZARA_YOUNG","zara_apartment","the woman at home stacking bundles of cash into a hidden box, her husband watching uneasily from a doorway","MS","eye","static","night",False,False,
  "дома ты прячешь пачки денег в коробку, и не замечаешь, что сэм стоит в дверях и смотрит на них молча."),
 ("F6_SH24","MAN","zara_apartment","close on the gentle husband's troubled face in the doorway, understanding dawning on him, dim neon","CU","eye","push_in","night",False,False,
  "он давно понял, откуда такие деньги, и однажды тихо спрашивает, зара, чьи это слёзы лежат в твоей коробке."),
 ("F6_SH25","ZARA_YOUNG","zara_apartment","the woman snapping the cash box shut and turning away from her husband, defensive, charm-hung wall behind","MCU","eye","static","night",False,False,
  "ты захлопываешь коробку и говоришь, не лезь не в своё дело, сэм, я кормлю эту семью, а не твои железки."),
 ("F6_SH26","MAN","kitchen_charms","the husband standing alone in the kitchen after the argument, a small daughter peeking from the hall, charms around","WS","eye","static","night",False,False,
  "он замолкает, а из коридора на вас смотрит холли, и впервые твоя дочь видит, как родители стали чужими."),
 ("F6_SH27",None,"widow_house","extreme close on a silver locket lying open on a bare table in a dim house, a faded photo of a man inside","ECU","top","push_in","day",False,True,
  "а у маргарет в пустом доме открыт медальон, и с фотографии смотрит человек, чью душу ты обещала спасти."),
 ("F6_SH28","ZARA_YOUNG","strip_mall_night","the madam stepping out under her bright hand-and-eye neon at night, prosperous and hard, the widow gone","MCU","low","static","night",False,False,
  "ты выходишь под свою сияющую ладонь, богатая, как никогда, и не оглядываешься на сгорбленную спину вдовы."),
 ("F6_SH29",None,"parking_lot_rain","a small black-clad figure of a widow walking away across a rain-soaked neon parking lot into the dark","WS","high","static","night",True,True,
  "маргарет уходит через мокрую неоновую парковку в темноту, и ты ещё не знаешь, что увидишь её последний раз скоро."),
 ("F6_SH30","ZARA_YOUNG","reading_room","the madam locking up, the lone dusty face-down card at the table's edge catching a sliver of neon, untouched","ECU","top","push_in","night",False,True,
  "и своя карта всё лежит рубашкой вверх, и теперь ты боишься её ещё сильнее, чем в день, когда мать тебя предупредила."),
]

PAL_JUSTICE="cold reckoning neon palette, hard white and blue neon against deep shadow, sterile guilty glare"
A7=[
 ("F7_SH01",None,"strip_mall_night","the salon's hand-and-eye neon at night now tinged cold white-blue, the parking lot empty, a hard flat light","WS","low","push_in","night",True,False,
  "колесо фортуны, что подняло тебя так высоко, незаметно начинает поворачиваться вниз, и первой это чувствуешь не ты."),
 ("F7_SH02","WIDOW","widow_house","the widow sitting motionless in a stripped bare room, all photos sold but the locket, empty-eyed, grey light","MS","eye","static","day",False,False,
  "маргарет отдала тебе всё, и порча, конечно, не ушла, потому что её и не было, а муж, конечно, не вернулся."),
 ("F7_SH03","WIDOW","widow_house","close on the widow's broken hollow face realising, perhaps, the truth, the locket cold in her hand","CU","eye","push_in","day",False,True,
  "и однажды она перестаёт приходить, и ты сначала даже рада, одной заботой и одним укором в глазах меньше."),
 ("F7_SH04","ZARA_YOUNG","reading_room","the madam shrugging off the widow's absence, dealing cards for a new client, cold blue neon","MCU","eye","static","night",False,False,
  "ты говоришь себе, наверное, ей полегчало, и берёшь следующего, и следующего, и не считаешь, скольких раздела."),
 ("F7_SH05",None,"diner_neon","a cold neon diner at night, a newspaper folded on the counter, a small grim headline visible, coffee going cold","INSERT","top","push_in","night",False,True,
  "а через месяц в местной газете на последней странице ты видишь её имя, и фотографию, и одно слово, утонула."),
 ("F7_SH06","ZARA_YOUNG","diner_neon","close on the madam frozen over a newspaper in a neon diner booth, the colour draining from her face","CU","eye","push_in","night",False,True,
  "маргарет вошла в реку с камнями в карманах пальто, и медальон, говорят, так и остался у неё на шее."),
 ("F7_SH07","ZARA_YOUNG","diner_neon","the woman gripping the diner counter, the chill on her arms back for the first time in years, neon glare","MCU","low","static","night",False,True,
  "и вот теперь холодок возвращается, бежит по предплечьям, как в юности, только теперь он ледяной."),
 ("F7_SH08",None,"back_alley","a stark white-blue neon alley at night, a lone figure leaning against wet brick, head down, steam rising","WS","high","static","night",True,False,
  "ты стоишь в переулке, и впервые за годы тебе по-настоящему плохо, и ты не знаешь, куда деть свои руки."),
 ("F7_SH09","ZARA_YOUNG","reading_room","the madam staring at the lone face-down card, hand trembling near it, then snatching it back, cold neon","CU","top","push_in","night",False,True,
  "ты тянешься к своей карте, чтобы спросить, виновна ли ты, и в последний миг отдёргиваешь руку, и тебе страшно."),
 ("F7_SH10","ZARA_YOUNG","zara_apartment","the woman drinking alone in her charm-hung apartment, trying to argue herself innocent, harsh neon bleed","MCU","eye","static","night",False,False,
  "ты пьёшь одна, и убеждаешь себя, я не толкала её в воду, она сама, я лишь продавала ей то, чего она просила."),
 ("F7_SH11","ZARA_YOUNG","zara_apartment","close on the woman's haunted face avoiding her own reflection in a dark window, neon doubled in the glass","CU","eye","push_in","night",False,False,
  "карты не врут, говоришь ты вслух, врут руки, что их держат, и впервые мамины слова звучат, как приговор тебе."),
 ("F7_SH12",None,"cemetery_day","a small overcast cemetery, a fresh modest grave with cheap flowers, bare trees, flat grey daylight, no neon","EWS","high","static","day",True,True,
  "ты не идёшь на её похороны, но однажды приезжаешь к могиле тайком, и стоишь поодаль, и не подходишь."),
 ("F7_SH13","ZARA_YOUNG","cemetery_day","the woman standing at a distance from a grave under grey sky, unable to approach, hands knotted","MS","eye","static","day",False,False,
  "на камне её имя и две даты совсем рядом, и ты понимаешь, что часть этого короткого тире между ними, твоя."),
 ("F7_SH14","ZARA_YOUNG","cemetery_day","close on the woman's face at the cemetery, guilt she will not name, dry-eyed and stony, grey light","CU","low","push_in","day",False,False,
  "ты не плачешь, плакать ты разучилась, ты просто кладёшь на чужой камень свои деньги, будто это что-то меняет."),
 ("F7_SH15","ZARA_YOUNG","reading_room","the madam back at the table the next night, hardening herself, dealing curse-work cards again, blue neon","MCU","eye","static","night",False,False,
  "а наутро ты снова открываешь салон, потому что остановиться, значит, признать, и ты снимаешь порчу дальше."),
 ("F7_SH16","ZARA_YOUNG","reading_room","close on the madam's eyes, harder and colder now, something extinguished behind them, neon glare","CU","eye","push_in","night",False,True,
  "только теперь, снимая чужую порчу, ты иногда ловишь себя на мысли, что настоящая порча, может быть, это ты."),
 ("F7_SH17","DAUGHTER","daughter_room","a teenage girl in a plain bare room overhearing her mother work through the wall, hugging her knees, cold light","MS","eye","static","night",False,False,
  "а за стеной растёт холли, и слышит каждый твой обряд, каждое снятие порчи, каждый испуганный голос за стеной."),
 ("F7_SH18","DAUGHTER","daughter_room","close on the teenage girl's resentful frightened face listening to the rituals through the wall, no charms around","CU","eye","push_in","night",False,False,
  "она растёт, зная то, чего не знают клиенты, что её мать не колдунья и не святая, а просто очень ловкая лгунья."),
 ("F7_SH19","MAN","kitchen_charms","the husband packing a small bag quietly at the kitchen table at night, decided, the daughter's door ajar behind","MS","eye","static","night",False,False,
  "сэм всё видит, и всё дольше молчит, и однажды ночью ты застаёшь его за тем, что он собирает сумку."),
 ("F7_SH20","ZARA_YOUNG","kitchen_charms","the woman frozen in the kitchen doorway watching her husband pack, the moment before everything breaks, neon bleed","MCU","over","static","night",False,False,
  "ты стоишь в дверях, и понимаешь, что вот сейчас обвалится всё, что ты строила не из карт, а по-настоящему."),
 ("F7_SH21","MAN","kitchen_charms","the gentle husband turning to face his wife, sad and final, not angry, the packed bag in his hand","CU","eye","push_in","night",False,False,
  "он говорит тихо, я не могу больше жить на деньги чужого горя, и не могу растить на них дочь, прости."),
 ("F7_SH22","ZARA_YOUNG","kitchen_charms","close on the woman's stricken face, reaching to argue, the old defensive lies already rising, neon glow","CU","low","push_in","night",False,False,
  "ты хочешь крикнуть, что кормила его этими деньгами, что без них он никто, но впервые слова застревают в горле."),
 ("F7_SH23",None,"street_night","a man with a single bag walking away down a neon-wet street at night, not looking back, signs glowing","WS","eye","track","night",True,True,
  "и сэм уходит в неоновую ночь с одной сумкой, и не оглядывается, и забирает с собой весь свет твоего дома."),
 ("F7_SH24","ZARA_YOUNG","reading_room","the woman sitting alone at the reading table, the justice card face-up in the spread, staring through it","CU","top","push_in","night",False,True,
  "ты раскладываешь карты дрожащими руками, и сверху ложится справедливость, и ты впервые понимаешь, за что."),
]

PAL_TOWER="fracturing storm-neon palette, harsh red and electric blue clashing, lightning-lit, splintered shadow"
A8=[
 ("F8_SH01",None,"strip_mall_night","the salon's hand-and-eye neon flickering hard under a stormy night sky, red and blue clashing, wind on the lot","WS","low","push_in","night",True,True,
  "башня рушится не сразу, она кренится годами, а потом падает в одну ночь, и ты ещё цепляешься за деньги."),
 ("F8_SH02","ZARA_YOUNG","zara_apartment","the woman alone in the half-empty apartment after her husband left, charms back on every wall, harsh neon","MS","eye","static","night",False,False,
  "после ухода сэма ты снова обвешиваешь дом оберегами, будто можно отвести приметами то, что ты сделала сама."),
 ("F8_SH03","DAUGHTER","daughter_room","a teenage girl furiously stripping superstition trinkets her mother hung on her door, defiant, cold neon","CU","eye","static","day",False,False,
  "холли срывает обереги, что ты вешаешь на её дверь, и кричит, мам, это всё бред, и папа ушёл из-за этого бреда."),
 ("F8_SH04","ZARA_YOUNG","daughter_room","the woman in the doorway hurt and rigid, clutching a charm, facing her rebelling teenage daughter, neon glow","MCU","over","static","day",False,False,
  "ты говоришь, это защита, холли, я оберегаю тебя, а она отвечает, ты обираешь чужих матерей, вот твоя защита."),
 ("F8_SH05","DAUGHTER","daughter_room","close on the teenage girl's furious tearful face, years of resentment breaking loose, bare wall behind","CU","eye","push_in","day",False,False,
  "она бросает тебе в лицо имя маргарет, ту вдову из газеты, и спрашивает, ты ведь знала, что она утонула из-за тебя."),
 ("F8_SH06","ZARA_YOUNG","daughter_room","the woman recoiling as if struck, the accusation landing, unable to deny it to her own child, neon bleed","CU","low","static","day",False,True,
  "и ты не находишь, что ответить родной дочери, потому что и сама задаёшь себе тот же вопрос каждую ночь."),
 ("F8_SH07","DAUGHTER","kitchen_charms","the teenage girl announcing she is leaving to live with her father, backpack on, jaw set, charms around","MS","eye","static","day",False,False,
  "холли собирает рюкзак и говорит, я уеду к папе, и буду жить нормально, без свечей, без вранья, без тебя."),
 ("F8_SH08","ZARA_YOUNG","kitchen_charms","the woman pleading wordlessly, reaching for her daughter who steps back, the kitchen charms trembling","MCU","eye","push_in","day",False,False,
  "ты тянешься к ней, и она отступает, и ты понимаешь, что приметы не уберегли тебя от единственной настоящей беды."),
 ("F8_SH09",None,"bus_stop_neon","a teenage girl with a backpack waiting alone under a cold neon bus shelter at night, a glowing street beyond","WS","eye","static","night",True,True,
  "холли уходит на остановку под холодным неоном, с одним рюкзаком, как когда-то ушёл её отец, той же дорогой."),
 ("F8_SH10","ZARA_YOUNG","bus_stop_neon","close on the woman watching her daughter's bus pull away, the neon doubling in her wet eyes, alone","CU","eye","push_in","night",False,False,
  "ты смотришь, как автобус увозит её в неоновую ночь, и впервые за всю жизнь тебе некому погадать на удачу."),
 ("F8_SH11","ZARA_YOUNG","zara_apartment","the woman alone in the dark charm-hung apartment, surrounded by useless trinkets, hollow, harsh neon bleed","WS","high","static","night",False,False,
  "ты остаёшься одна среди своих оберегов, и они впервые кажутся тебе тем, чем и были всегда, дешёвым хламом."),
 ("F8_SH12","ZARA_YOUNG","reading_room","the woman trying to work the next day with shaking hands, misreading a client, the performance cracking, neon","MCU","eye","static","night",False,False,
  "ты пытаешься работать дальше, но руки дрожат, и слова путаются, и клиенты чувствуют фальшь, и уходят."),
 ("F8_SH13",None,"strip_mall_night","the bright salon neon now with one letter starting to flicker and die, the queue at the door gone, wet lot","WS","low","static","night",True,False,
  "очередь редеет, потом исчезает совсем, и на твоей сияющей вывеске начинает мигать и гаснуть первая буква."),
 ("F8_SH14","ZARA_YOUNG","reading_room","the woman alone in the empty salon at night, dealing cards across the table to an empty chair, flickering neon","MS","high","push_in","night",False,False,
  "ты сидишь вечерами в пустом салоне, и раскладываешь карты сама себе на клиентов, которые уже не придут."),
 ("F8_SH15","ZARA_YOUNG","zara_apartment","close on the woman dialing a phone with hope, then her face falling as it goes unanswered, dim neon","CU","eye","push_in","night",False,False,
  "ты звонишь холли, и сэму, и слушаешь длинные гудки, и оставляешь сообщения, на которые тебе не перезвонят."),
 ("F8_SH16",None,"parking_lot_rain","the strip-mall lot in heavy rain at night, the salon's neon hand flickering and half-dead, reflections breaking","WS","high","static","night",True,True,
  "башня твоя сложилась тихо, без грома, просто однажды некому стало звонить, и нечего стало праздновать."),
 ("F8_SH17","ZARA_YOUNG","reading_room","the woman staring long and hard at the lone face-down card, terrified of it, hand frozen midair, neon","CU","top","push_in","night",False,True,
  "ты снова смотришь на свою карту, рубашкой вверх, и думаешь, может, там ответ, почему всё рассыпалось в прах."),
 ("F8_SH18","ZARA_YOUNG","reading_room","the woman pulling her hand back from the face-down card again, not yet, not yet, hugging her shawl, dim neon","MCU","low","static","night",False,True,
  "но ты опять не решаешься, на себя не гадают, шепчешь ты, и сама уже не знаешь, завет это или просто трусость."),
 ("F8_SH19","ZARA_YOUNG","zara_apartment","an older-looking woman aging in the lonely apartment, grey at her temples now, fewer charms, cold neon","MCU","eye","static","night",False,False,
  "проходят годы в одиночестве, и в зеркало ты стараешься не смотреть, как мать когда-то не смотрела в свои карты."),
 ("F8_SH20",None,"street_night","a quiet neon street at night, most signs dark now, one lone flickering psychic sign among them, wet pavement","WS","eye","pan_right","night",True,False,
  "город меняется, неон вокруг гаснет, открываются другие гадалки, помоложе, поярче, а к тебе уже не идут."),
 ("F8_SH21","ZARA_YOUNG","reading_room","the woman counting a thin handful of bills at the once-lavish table, the prosperity gone, flickering neon","MCU","high","static","night",False,False,
  "денег едва хватает на аренду и неон, и ты впервые за двадцать лет считаешь не пачки, а мятые бумажки."),
 ("F8_SH22",None,"pawn_shop","the interior of a neon-lit pawn shop, a glass case of rings, a hand laying down jewelry for cash","INSERT","top","push_in","night",False,False,
  "ты закладываешь в ломбард свои золотые серьги, шали, всё, кроме маминого кольца с лунным камнем, его ни за что."),
 ("F8_SH23","ZARA_YOUNG","reading_room","close on the woman's tired aging face lit by failing neon, the famous madam now small and alone","CU","low","push_in","night",False,False,
  "от мадам зары, что решала чужие судьбы одним словом, остаётся усталая женщина в гаснущем неоновом углу."),
 ("F8_SH24",None,"parking_lot_rain","the salon's neon hand-and-eye sign with half its letters dead, reflected broken in a rainy parking lot at night","WS","low","static","night",True,True,
  "над тобой догорает твоя ладонь с глазом, буква за буквой, и никто, кроме дождя, этого уже не видит."),
]

seed_act("act06_devil",   PAL_DEVIL,   A6)
seed_act("act07_justice", PAL_JUSTICE, A7)
seed_act("act08_tower",   PAL_TOWER,   A8)
