# -*- coding: utf-8 -*-
"""surrogate A10 son + A11 coda. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_surrogate_A10A11.py"""
from _surrogate_engine import seed_act

P_SON="muted late palette, faded warm browns and cold grey, the quiet of years passed"
P_CODA="final hushed palette, one low warm bulb in deep night, still and bare"

SON=[
 ("A10_SH01",None,"small_town_street","a wide view of a grey small-town street a decade on, worn and quiet under a flat sky","WS","eye","push_in","day",True,False,
  "проходит десять лет, тебе сорок шесть, Мише двадцать два, и он вырос, не зная всей правды."),
 ("A10_SH02","SON_ADULT","poor_flat","a medium shot of a lean guarded young man of twenty-two with dark hair in the poor flat, serious and closed","MS","eye","static","day",False,False,
  "он поступил учиться на те самые деньги и стал серьёзным, немного замкнутым молодым мужчиной."),
 ("A10_SH03","HERO_OLD","poor_flat","a medium close-up of the aged mother of forty-six looking at her grown son with pride and fear","MCU","eye","static","day",False,False,
  "ты гордишься им больше всего на свете и до последнего надеешься, что тайна умрёт вместе с тобой."),
 ("A10_SH04",None,None,"an extreme close-up macro insert of a young man's hand lifting the lid of an old tin box in a wardrobe, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "но однажды он находит в шкафу жестяную коробку и открывает её, думая, что там документы."),
 ("A10_SH05","SON_ADULT","poor_flat","a close-up of the young man's confused face looking down into the tin box","CU","high","static","day",False,False,
  "он видит три больничных браслета и три детские пинетки и не понимает, чьи они и откуда."),
 ("A10_SH06","HERO_OLD","poor_flat","a medium shot of the mother frozen in the doorway seeing her son holding the open box","MS","eye","static","day",False,False,
  "ты входишь и застаёшь его с коробкой в руках, и по твоему лицу он читает всё сразу."),
 ("A10_SH07","SON_ADULT","poor_flat","a close-up of the young man listening as the truth is told, going pale","CU","eye","push_in","day",False,False,
  "ты рассказываешь ему всё, про операцию, про долги, про троих детей, которых ты выносила и отдала."),
 ("A10_SH08","SON_ADULT","poor_flat","a medium close-up of the son looking at his mother as if at a stranger","MCU","eye","static","day",False,False,
  "он слушает молча, бледнеет, и впервые смотрит на тебя так, будто видит чужого человека."),
 ("A10_SH09","HERO_OLD","poor_flat","a close-up of the mother pleading that she did it all for him","CU","eye","static","day",False,False,
  "ты объясняешь, что делала это ради него, чтобы он жил, чтобы у него было будущее."),
 ("A10_SH10","SON_ADULT","poor_flat","a medium shot of the young man reeling from the thought of unknown siblings","MS","eye","static","day",False,False,
  "но он слышит только одно, что где-то у него есть трое братьев и сестёр, которых он никогда не увидит."),
 ("A10_SH11",None,None,"an extreme close-up macro insert of a young man's hands holding three plastic hospital bracelets, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "он держит в руках три браслета чужих детей, и до него доходит, что вырос он ценой их потери."),
 ("A10_SH12","SON_ADULT","poor_flat","a close-up of the son asking a quiet devastating question","CU","eye","push_in","day",False,False,
  "он спрашивает тихо, сколько же стоила его жизнь, и этот вопрос ты будешь слышать до конца."),
 ("A10_SH13","HERO_OLD","poor_flat","a medium shot of the mother unable to answer, ashamed","MS","eye","static","day",False,False,
  "ты не находишь ответа, потому что честный ответ — что ровно столько, сколько три чужих ребёнка."),
 ("A10_SH14","SON_ADULT","poor_flat","a close-up of the young man setting down the box and taking his jacket to leave","CU","eye","static","day",False,False,
  "он кладёт коробку, берёт куртку и уходит, и его красная детская машинка остаётся на полке."),
 ("A10_SH15",None,None,"an extreme close-up macro insert of a small red toy car left alone on a shelf, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "маленькая красная машинка, которую он таскал всё детство, теперь остаётся дома без него."),
 ("A10_SH16",None,"small_town_street","a wide view of a lone young man's blurred figure walking away down a grey street, not looking back","WS","eye","static","day",True,False,
  "он уходит по той же серой улице, по которой когда-то ушёл его отец, и не оборачивается."),
 ("A10_SH17","HERO_OLD","poor_flat","a medium close-up of the aged mother alone, holding a silent phone","MCU","eye","static","day",False,False,
  "он не перестаёт с тобой общаться совсем, но теперь звонит редко, коротко и очень вежливо."),
 ("A10_SH18","HERO_OLD","poor_flat","a close-up of the mother's face, that politeness worse than shouting","CU","eye","push_in","day",False,False,
  "эта вежливость хуже крика, потому что в ней ты слышишь, что потеряла и его тоже."),
 ("A10_SH19",None,"kitchen_night","a wide view of a dim empty poor kitchen at night, a tin box on the table under a low bulb","WS","eye","static","night",True,False,
  "дом снова пустеет, и ты остаёшься одна с коробкой и с тремя именами, которые никому не нужны."),
 ("A10_SH20","HERO_OLD","kitchen_night","a medium close-up of the aged woman alone in the night kitchen, grasping her whole life","MCU","eye","static","night",False,False,
  "ты выносила троих чужих детей, вырастила одного своего и в итоге осталась совсем одна."),
 ("A10_SH21","HERO_OLD","kitchen_night","a close-up of the woman's worn face reckoning who got what","CU","eye","static","night",False,False,
  "богатые семьи получили детей, агентство получило деньги, а ты получила пустой дом и больное тело."),
 ("A10_SH22",None,None,"an extreme close-up macro insert of a tin box holding three bracelets and three tiny booties, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "в жестяной коробке три браслета и три пинетки, и это вся семья, что у тебя теперь есть."),
 ("A10_SH23",None,"small_town_street","a wide view of the same grey small-town street with nowhere to go, under a flat evening sky","WS","eye","static","dusk",True,False,
  "за окном тот же посёлок, из которого некуда идти, и та же жизнь, которую не переиграть."),
 ("A10_SH24","HERO_OLD","kitchen_night","a close-up of the woman of forty-six, her whole life fitting into a tin box","CU","eye","push_in","night",False,True,
  "тебе сорок шесть, и вся твоя жизнь уместилась в жестяную коробку с чужими детскими браслетами."),
]

CODA=[
 ("A11_SH01","HERO_OLD","kitchen_night","a close-up of the woman of forty-six speaking quietly and directly to the viewer in low bulb light","CU","eye","push_in","night",False,False,
  "я рассказала тебе это не для того, чтобы напугать, а чтобы ты знала, чем такое кончается."),
 ("A11_SH02","HERO_OLD","kitchen_night","a medium shot of the woman laying out the box's contents on the night kitchen table","MS","eye","static","night",False,False,
  "сегодня я снова достала жестяную коробку и разложила на столе три браслета и три пинетки."),
 ("A11_SH03",None,None,"an extreme close-up macro insert of three plastic hospital bracelets and three tiny knitted booties laid out together, filling the frame in sharp focus, background out of focus, shallow depth of field, one warm light","ECU","top","push_in","night",True,True,
  "три пластиковых браслета и три крошечные пинетки, от троих детей, которых я родила и никогда не растила."),
 ("A11_SH04","HERO_OLD","kitchen_night","a close-up of the woman's face carrying the weight of three partings","CU","eye","static","night",False,False,
  "трижды я слышала первый крик и трижды отдавала свёрток чужим людям за деньги."),
 ("A11_SH05","HERO_OLD","kitchen_night","a medium close-up of the woman counting her losses aloud","MCU","eye","static","night",False,False,
  "я закрыла долги, спасла и выучила сына, и потеряла и здоровье, и мужа, и его самого."),
 ("A11_SH06","HERO_OLD","kitchen_night","a wide shot of the small aged woman alone at the table in the dim kitchen","WS","eye","pull_out","night",False,False,
  "и вот я сижу одна на кухне в сорок шесть, и вся моя семья — эта жестяная коробка."),
 ("A11_SH07",None,None,"an extreme close-up macro insert of a single tiny knitted bootie resting in an open palm, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,False,
  "я держу на ладони пинетку и думаю о ребёнке, чьё лицо мне даже не показали."),
 ("A11_SH08","HERO_OLD","kitchen_night","a close-up of the woman looking directly at the viewer, worn and honest","CU","eye","push_in","night",False,False,
  "если тебе сейчас предлагают продать девять месяцев и не жалко, подпишись и дослушай до конца."),
 ("A11_SH09","HERO_OLD","kitchen_night","a medium shot of the woman speaking plainly to the viewer in the low light","MS","eye","static","night",False,False,
  "потому что берут у тебя не девять месяцев, а куда больше, и понимаешь ты это слишком поздно."),
 ("A11_SH10",None,None,"an extreme close-up macro insert of hands closing the lid of a tin box, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "я закрываю коробку и убираю её обратно в шкаф, до следующей бессонной ночи."),
 ("A11_SH11",None,"kitchen_night","a wide view of a dim poor kitchen as the last light fades over a bare table, still and quiet","WS","eye","static","night",True,False,
  "свет на кухне гаснет, и три чужих ребёнка спят где-то далеко, не зная обо мне ничего."),
 ("A11_SH12","HERO_OLD","kitchen_night","a close-up of the woman's face, the whole reckoning settled on her","CU","eye","static","night",False,False,
  "моё тело выносило троих, а обнять на старости мне некого, и это и есть вся расплата."),
 ("A11_SH13","HERO_OLD","kitchen_night","a medium shot of the woman sitting alone by a silent phone in the dark kitchen","MS","eye","static","night",False,False,
  "а мой единственный сын позвонит через месяц, спросит, как дела, и снова быстро попрощается."),
 ("A11_SH14","HERO_OLD","kitchen_night","a close-up of the woman's calm final face looking at the viewer in the last low light","CU","eye","push_in","night",False,True,
  "эта история вымышлена, любые совпадения случайны, но такие коробки прямо сейчас стоят в чьих-то шкафах."),
]

if __name__=="__main__":
    seed_act("son",  P_SON,  SON,  render_mode="static")
    seed_act("coda", P_CODA, CODA, render_mode="static")
