# -*- coding: utf-8 -*-
"""Batch 6: act12_edge + act13_after (climax inversion + coda/final image)."""
from _flat_earth_engine import seed_act

PAL_EDGE = "luminous dawn climax palette, radiant gold mist and white spray over cold steel-grey concrete and wet metal"
A12 = [
 ("A12_SH01",None,"dam_spillway","a colossal concrete dam at dawn seen from far off, water pouring over the spillway into golden mist, a tiny lone ragged figure standing at the crest railing","EWS","high","push_in","dawn",True,True,
  "ты стоишь на самом гребне, на краю мира, и под тобой вода переливается через кромку в золотое сияние."),
 ("A12_SH02","RAY","dam_spillway","a ragged man at a dam railing with arms slowly rising, speaking out over a roaring spillway into the dawn mist","MS","low","push_in","dawn",False,False,
  "ты раскидываешь руки, и говоришь вслух, вот он, край, я дошёл, я знал, я всю жизнь знал, что он есть."),
 ("A12_SH03","RAY","dam_spillway","close on a ragged weeping radiant face at the dam crest, lit gold, gazing down at the falling water in awe","CU","low","push_in","dawn",False,True,
  "слёзы текут по твоему лицу, и тебе кажется, что за обрывом воды ты видишь звёзды, целое поле звёзд."),
 ("A12_SH04",None,"dam_spillway","a vast sheet of reservoir water sliding over a concrete spillway lip and plunging into a churning golden basin of mist","EWS","eye","push_in","dawn",True,True,
  "океан уходит вниз ровной стеной, беззвучно, в бесконечность, и нет там никакого изгиба, никакого шара."),
 ("A12_SH05",None,"dam_spillway","extreme close on a yellow steel warning sign bolted to the dam railing reading danger dam keep off, rust at the edges","INSERT","eye","static","dawn",False,True,
  "ты не видишь жёлтую табличку у локтя, ты вообще больше не видишь ничего, кроме своего ровного края."),
 ("A12_SH06","RAY","dam_spillway","a ragged man holding a brass folding ruler out at arm's length over the falling water, measuring the lip of the spillway","MCU","low","push_in","dawn",False,True,
  "ты в последний раз достаёшь дедову линейку, и прикладываешь её к самой кромке, где вода уходит за край."),
 ("A12_SH07",None,"dam_spillway","extreme close on a brass ruler held against the dead-flat line where water meets the edge of the spillway, no curve","ECU","eye","push_in","dawn",False,True,
  "и линия ложится идеально ровно, как тогда на озере, как всегда, ровно, ровно, ровно, до самого конца."),
 ("A12_SH08","RAY","dam_spillway","close on the man's transfigured face, eyes shut, the familiar shiver of vindication, the brass ruler against the dawn","CU","low","static","dawn",False,True,
  "и тот холодок из детства в последний раз бежит по твоей спине, и ты шепчешь, я был прав, я был прав."),
 ("A12_SH09",None,"dam_spillway","far down a wet dam walkway, a dam worker in a hard hat and high-vis vest freezing at the sight of a figure at the rail","WS","eye","static","dawn",False,False,
  "по гребню к тебе идёт рабочий в каске, и застывает, увидев тебя у самых перил, и хватается за рацию."),
 ("A12_SH10",None,"dam_spillway","a worker on a dam walkway speaking urgently into a radio while backing away, glancing toward an unseen figure","MS","eye","static","dawn",False,False,
  "он что-то кричит в рацию, и пятится, а ты улыбаешься ему, ты ведь хочешь только одного, показать ему край."),
 ("A12_SH11",None,"dam_spillway","a security truck and a police cruiser with lights pulling onto a dam access road at dawn, doors opening","WS","high","push_in","dawn",True,False,
  "очень скоро у плотины мигают огни, приезжают машины, выходят люди в форме, и идут по гребню к тебе."),
 ("A12_SH12","RAY","dam_spillway","a radiant ragged man turning from the railing toward approaching figures, beckoning them with an open hand, joyful","MCU","eye","static","dawn",False,False,
  "ты оборачиваешься к ним, и зовёшь рукой, идите сюда, скорее, смотрите, вот же он, край, я нашёл его."),
 ("A12_SH13","RAY","dam_spillway","close on the man's joyful pleading face, pointing back over the falling water, certain they will see it too","CU","low","push_in","dawn",False,False,
  "вы тоже видите, да, спрашиваешь ты их, ну скажите, что видите, вода падает за край, мы все были слепы."),
 ("A12_SH14",None,"dam_spillway","two officers advancing slowly along the dam crest with placating raised hands toward an unseen figure at the rail","WS","eye","push_in","dawn",False,False,
  "они идут медленно, выставив ладони, и говорят с тобой тихо и осторожно, как говорят с тем, кто на краю."),
 ("A12_SH15","RAY","dam_spillway","over a careful outstretched hand of an officer, a serene ragged man at the railing still pointing out at the water","OTS","over","static","dawn",False,False,
  "один из них тянет к тебе руку, и просит отойти от перил, а ты не понимаешь, зачем, ведь ты дома, ты дошёл."),
 ("A12_SH16","RAY","dam_spillway","close on the man's serene fearless face, no resistance, eyes still drawn back toward the golden falling water","CU","eye","static","dawn",False,False,
  "тебе не страшно, ты не сопротивляешься, ты только всё оглядываешься на край, чтобы он никуда не делся."),
 ("A12_SH17",None,"dam_spillway","several uniformed figures gently taking hold of a small ragged man at a dam railing in the gold dawn light","WS","high","static","dawn",True,True,
  "они мягко берут тебя под руки, и ты идёшь с ними, потому что тебе кажется, что теперь это уже не важно."),
 ("A12_SH18","RAY","dam_spillway","a ragged man being eased back from a dam railing by unseen hands, not resisting, smiling back at the spillway","MS","eye","track","dawn",False,False,
  "они уводят тебя от перил, а ты улыбаешься через плечо падающей воде, как улыбаются, прощаясь с домом."),
 ("A12_SH19",None,"dam_spillway","extreme close on a brass folding ruler slipping from an opening hand toward a wet concrete walkway","ECU","high","push_in","dawn",False,True,
  "дедова линейка выскальзывает из твоих пальцев, и падает на мокрый бетон, и остаётся лежать у самого края."),
 ("A12_SH20",None,"dam_spillway","a worn brass ruler lying alone on a wet dam walkway at dawn, golden mist rising beyond the railing behind it","INSERT","top","static","dawn",False,True,
  "она остаётся там, на краю мира, маленькая латунная линейка, которой ты измерил всё, во что верил."),
 ("A12_SH21","RAY","dam_spillway","a calm radiant man having his arms eased into a canvas restraint jacket beside a vehicle at the foot of the dam","MS","eye","static","dawn",False,True,
  "у машины тебе осторожно заводят руки за спину, в плотную холщовую куртку, а ты всё смотришь на воду."),
 ("A12_SH22","RAY","dam_spillway","close on the man's serene radiant face as the restraint is fastened, eyes still turned toward the falling water","CU","low","push_in","dawn",False,True,
  "они затягивают ремни, а тебе спокойно, ведь то, что ты видел, у тебя уже никто не отнимет, никогда."),
 ("A12_SH23",None,"dam_spillway","a restrained man being guided into the back of an ambulance at dawn, the great dam looming behind, lights flashing","WS","eye","static","dawn",True,False,
  "тебя сажают в машину с мигалками, и за стеклом остаётся плотина, и золотой туман над падающей водой."),
 ("A12_SH24",None,"dam_spillway","a great dam seen from far away at full dawn, water pouring into gold mist, tiny vehicles pulling away on the road below","EWS","high","pull_out","dawn",True,True,
  "машины увозят тебя прочь, и плотина становится всё меньше, а вода всё падает и падает за край без конца."),
 ("A12_SH25","RAY","dam_spillway","close on a serene man's face at a small ambulance window looking back at the receding dam and its golden mist","CU","eye","push_in","dawn",False,False,
  "ты смотришь в окошко на уходящий край, и улыбаешься, потому что ты единственный, кто дошёл и увидел."),
 ("A12_SH26","RAY","dam_spillway","extreme close on the man's calm certain eyes reflected in the ambulance glass over the blurred receding water","ECU","eye","push_in","dawn",False,True,
  "и ты говоришь себе тихо, я видел, и теперь это моё навсегда, что бы они со мной ни сделали дальше."),
]

PAL_CELL = "stark clinical white-and-grey palette, flat even institutional light, cold sterile whites with faint grey shadow"
A13 = [
 ("A13_SH01",None,"padded_cell","a plain psychiatric facility corridor by day, pale green-grey walls, a heavy locked door at the end, fluorescent light","WS","eye","push_in","day",True,False,
  "тебя привозят в тихое серое здание на краю города, и ведут длинным коридором за крепкую дверь."),
 ("A13_SH02","RAY","padded_cell","a calm restrained man being walked along an institutional corridor by unseen orderlies, serene, looking at the light","MS","eye","track","day",False,False,
  "ты идёшь спокойно, ты не споришь, ведь ты знаешь то, чего не знает никто из них, и это тебя греет."),
 ("A13_SH03","HALE","padded_cell","a calm doctor in a white coat with a lanyard badge writing on a clipboard, a serene patient seated beyond him","OTS","over","static","day",False,False,
  "доктор хейл задаёт тебе тихие вопросы, и записывает что-то в карту, и кивает, и не верит ни единому слову."),
 ("A13_SH04","RAY","padded_cell","close on a serene man's face looking past the doctor toward a high barred window, a faint private smile","CU","eye","push_in","day",False,False,
  "ты смотришь мимо него в зарешёченное окно, на ровную линию горизонта, и тебе совсем не страшно."),
 ("A13_SH05","LINDA","dawson_kitchen","an older tired woman in a small kitchen turning toward a television, a news report glowing, a hand rising to her mouth","MS","eye","push_in","day",False,False,
  "где-то далеко линда видит сюжет в новостях, мужчина задержан на плотине, и узнаёт тебя, и замирает."),
 ("A13_SH06","LINDA","dawson_kitchen","close on an older woman's grieving face lit by a television, not surprised, an old sorrow surfacing","CU","eye","static","day",False,True,
  "она не удивляется, она давно этого ждала, и в её глазах не злость, а всё та же тихая, усталая жалость."),
 ("A13_SH07",None,"east_nash_street","a young man on a porch lowering a phone from his ear, jaw tight, staring away down an empty street","WS","eye","static","day",False,False,
  "взрослому коди звонят и говорят про отца, и он долго стоит молча, и не знает, что теперь чувствовать."),
 ("A13_SH08",None,"east_nash_street","close on a young man's conflicted face on a porch, looking down at a small worn paper boat held in one hand","CU","high","push_in","day",False,True,
  "у него сохранился твой бумажный кораблик из детства, и он держит его в руке, и впервые за годы плачет."),
 ("A13_SH09",None,"padded_cell","a psychiatric seclusion room with seamless off-white padded walls, a single wired door window, flat even light","WS","eye","push_in","day",True,True,
  "а тебя приводят в мягкую палату, ту самую, белую, тихую, где и начинается эта история, помнишь."),
 ("A13_SH10","RAY","padded_cell","a man in a canvas restraint sitting upright and serene against a padded wall, calm and content, chin lifted","MS","eye","static","day",False,True,
  "ты садишься к стене, спокойный и счастливый, как человек, который наконец дошёл туда, куда шёл всю жизнь."),
 ("A13_SH11","RAY","padded_cell","close on a content certain face against white padding, eyes calm, at peace with everything","CU","eye","push_in","day",False,False,
  "пусть говорят, что я сумасшедший, думаешь ты, я знаю, что я видел, и этого у меня уже не отнять."),
 ("A13_SH12","HALE","padded_cell","a doctor watching through a small wired observation window, clipboard in hand, a calm seated patient beyond","OTS","over","static","day",False,False,
  "доктор смотрит на тебя в дверное окошко, и пишет в карте длинное слово, и уходит по своим делам."),
 ("A13_SH13",None,"padded_cell","a small wired observation window in a heavy door, a serene seated figure small and white-lit beyond the glass","INSERT","eye","push_in","day",True,False,
  "и вот ты снова там, где я начал тебе рассказывать, за крепкой дверью, подальше от тебя и твоих вопросов."),
 ("A13_SH14","RAY","padded_cell","close on a serene man speaking calmly and directly toward the viewer, certain and gentle, white walls around him","CU","eye","push_in","day",False,False,
  "теперь ты знаешь всё, я дошёл, я видел край земли своими глазами, и вода падала за него, в звёзды."),
 ("A13_SH15","RAY","padded_cell","a calm man against the padded wall, half-smiling, talking to the viewer as to an old friend","MCU","eye","static","day",False,False,
  "мне не важно, что они написали в моей карте, важно только то, что я был прав, всю жизнь был прав."),
 ("A13_SH16","RAY","padded_cell","close on the man's gentle certain face addressing the viewer directly, eyes warm and clear","CU","eye","push_in","day",False,False,
  "и я прошу тебя об одном, береги себя, слышишь, и не верь, когда тебе говорят, что земля круглая."),
 ("A13_SH17","RAY","padded_cell","a serene man lifting one finger to the blank off-white padded wall beside him, about to draw","MCU","eye","push_in","day",False,False,
  "а если однажды засомневаешься, просто посмотри на любую воду, на любой горизонт, и увидишь сам."),
 ("A13_SH18",None,"padded_cell","extreme close on a fingertip pressed to seamless white padding, beginning to drag slowly to the side","ECU","eye","track","day",False,True,
  "ты прикладываешь палец к мягкой стене, и медленно ведёшь по ней одну ровную, идеально ровную черту."),
 ("A13_SH19",None,"padded_cell","extreme close on a finger completing a dead-straight horizontal line scuffed across white padded wall","ECU","eye","track","day",False,True,
  "ровную, без единого изгиба, как линия воды, как край мира, как всё, во что ты верил с девяти лет."),
 ("A13_SH20","RAY","padded_cell","a man's peaceful face and shoulders, eyes closed, the faint familiar shiver of recognition, the straight line on the wall behind","MCU","eye","push_in","day",False,True,
  "и тот холодок в последний раз бежит по твоей спине, и ты улыбаешься, потому что ты дома, и ты прав."),
 ("A13_SH21","RAY","padded_cell","a serene man sitting small and still against a white padded wall under flat even light, at perfect peace","WS","high","pull_out","day",False,True,
  "ты сидишь в своей белой комнате, спокойный и счастливый, единственный человек, дошедший до края земли."),
 ("A13_SH22",None,"padded_cell","an empty off-white padded wall in flat even light, a single faint dead-straight finger-line the only mark on it","EWS","eye","push_in","day",True,True,
  "а где-то там, далеко за стеной, за городом, за полями, лежит ровная линия воды, и ждёт следующего, кто поверит."),
 ("A13_SH23",None,"padded_cell","a medium framing of a bare seamless white padded wall section in soft institutional light, the faint straight finger-line crossing it","MS","eye","static","day",True,False,
  "эта история вымышлена, и все совпадения с реальными людьми случайны, не повторяй чужих ошибок."),
 ("A13_SH24",None,"padded_cell","a pure soft off-white field of padded wall fading toward white, the faint straight finger-line dissolving into light","INSERT","eye","push_in","day",True,True,
  "береги себя, слышишь, береги, и иногда всё-таки поглядывай на горизонт, просто на всякий случай."),
]

seed_act("act12_edge",  PAL_EDGE, A12)
seed_act("act13_after", PAL_CELL, A13)
