# -*- coding: utf-8 -*-
"""trucker: cold_open (9) + hired (12) + school_road (12). Run: PYTHONIOENCODING=utf-8 python scripts/_seed_trucker_A0A2.py"""
from _trucker_engine import seed_act

M="MAX_YOUNG"; S="STEP_BASE"; A="ARK_BASE"; MO="MOM_BASE"; I="INSPECTOR_BASE"

# ── COLD OPEN — ночь, весовой пост на 412-м км ─────────────────────────────────
PAL_C="cold blue night palette cut by harsh white floodlight and one amber cab light"
COLD=[
 ("C_SH01",None,"night_highway",
  "a long-haul truck approaching a floodlit roadside weigh station far ahead on a dark two-lane highway, its headlights sweeping the guard rail, the yellow sign board of the post glowing above the barrier",
  "WS","eye","track","night",True,False,
  "четыреста двенадцатый километр, два часа ночи, и жёлтый щит весового поста горит впереди, как приговор, которого ты ждал."),
 ("C_SH02",(M,S),"truck_cab",
  "Maksim, a lanky young driver in fingerless leather gloves, on the left gripping the wheel and downshifting, and Stepanych, a stocky old trucker in a flat tweed cap, on the right sitting very still, the white glow of the post crawling across both faces",
  "MS","eye","static","night",False,False,
  "ты сбрасываешь передачу, а степаныч рядом молчит так, что это молчание громче любого крика."),
 ("C_SH03",None,"weigh_station",
  "a heavy truck standing on the axle-scale strip of a floodlit inspection apron, the barrier arm down, hard white light flattening every shadow around the wheels",
  "WS","high","push_in","night",False,False,
  "весы под колёсами считают твою жизнь в килограммах, и лишних в ней ровно шестьдесят."),
 ("C_SH04",(M,S),"truck_cab",
  "over Maksim's shoulder, Stepanych in his flat tweed cap turning his weathered face from the windshield to look straight at the young man, his grey walrus moustache lit from below by the dashboard",
  "OTS","over","static","night",False,True,
  "он не смотрит на инспектора за стеклом, он смотрит на тебя, и в этом взгляде уже всё написано."),
 ("C_SH05",I,"weigh_station",
  "a road inspector in a grey uniform jacket and peaked cap walking unhurried along the tarpaulin side of the trailer, laying the beam of a long black metal flashlight along the boards",
  "MS","low","track","night",False,False,
  "инспектор идёт вдоль борта не спеша, ему некуда торопиться, это тебе некуда деваться."),
 ("C_SH06",I,"weigh_station",
  "an extreme close-up of the inspector's gloved hand coming to rest on the lead wire seal of the trailer door, the flashlight beam held steady on the stamped metal",
  "ECU","eye","push_in","night",False,True,
  "его ладонь ложится на пломбу борта, и ты слышишь, как рядом тяжело выдыхает степаныч."),
 ("C_SH07",(M,S),"truck_cab",
  "Maksim on the left clenching the thin steering wheel in his father's fingerless gloves, knuckles pale, Stepanych on the right looking down at his own folded hands, both men rimmed by the cold floodlight",
  "MCU","eye","static","night",False,False,
  "ты сидишь в отцовских перчатках, вцепившись в руль, который тебе так и не стал своим."),
 ("C_SH08",None,"weigh_station",
  "the whole inspection post seen from across the empty highway, the truck small under the mast of white floodlights, the booth window glowing, the barrier striped and final",
  "EWS","eye","static","night",True,False,
  "останься до конца и подпишись, а я расскажу, как эта ночь выросла из одной картонной коробки."),
 ("C_SH09","OBJ:box",None,
  "a flashlight beam finding a plain cardboard box hidden in the dark niche behind a spare wheel under a truck bed",
  "INSERT","low","push_in","night",False,True,
  "тебе двадцать два, и три месяца назад ты ещё ни разу не сидел в кабине фуры."),
]

# ── A1 HIRED — долг, база, «посидишь справа» ───────────────────────────────────
PAL_1="grey overcast morning palette with warm sodium accents"
HIRED=[
 ("A1_SH01",MO,"mom_kitchen",
  "a tired woman in a pale headscarf and hospital-blue cardigan laying out payment slips in rows on an oilcloth kitchen table, smoothing each one flat with careful worn hands",
  "MS","eye","push_in","morning",False,False,
  "после похорон отца на кухне остаётся стопка квитанций за его операцию, двести сорок тысяч долга."),
 ("A1_SH02",None,"mom_kitchen",
  "an extreme close-up of a payment slip pinned under a fridge magnet, a long typed sum at the bottom, a tin box of pill blisters blurred beside it",
  "ECU","eye","static","morning",False,False,
  "операция отца не спасла, а двести сорок тысяч долга никуда после похорон не делись."),
 ("A1_SH03",(M,MO),"mom_kitchen",
  "Maksim in a worn denim jacket on the left gently taking the top payment slip from the table, his mother in the pale headscarf on the right watching him with tired downturned eyes",
  "MCU","eye","static","morning",False,True,
  "ты забираешь у матери верхнюю квитанцию и говоришь, что заработаешь сам, ей остаётся поверить."),
 ("A1_SH04",M,"base_yard",
  "a lanky young man in a denim jacket walking in through the gates of a freight base past rows of parked semi-trailers, a folded newspaper ad in his gloved hand",
  "WS","eye","track","morning",False,False,
  "логистическая база на окраине берёт грузчиков и стажёров без всякого опыта, туда ты и приходишь."),
 ("A1_SH05",A,"logist_office",
  "a sleek thin logistics manager with slicked-back dark hair filling out a form at a cluttered container-office desk, his eyes on the phone in his other hand, a space heater glowing orange behind him",
  "MCU","eye","static","day",False,False,
  "логист аркадий оформляет тебя за десять минут, ни разу не оторвав глаз от телефона в руке."),
 ("A1_SH06",(A,M),"logist_office",
  "Arkady on the left sliding a paper form across the desk with one finger, the heavy gold signet ring on his little finger tapping the desktop, Maksim on the right reaching for the pen",
  "MS","eye","static","day",False,False,
  "он двигает тебе бланк через стол, и золотой перстень на мизинце коротко стукает по столешнице."),
 ("A1_SH07",(A,M),"base_yard",
  "Arkady in his glossy black puffer coat on the left leading the way across the gravel yard between trailers, Maksim on the right following a half step behind, both heading toward an old long-nosed truck",
  "WS","eye","track","day",False,False,
  "аркадий ведёт тебя через двор мимо прицепов к самой старой фуре на всей площадке."),
 ("A1_SH08",S,"base_yard",
  "a stocky old trucker in a flat tweed cap and olive quilted vest standing by the front wheel of his truck, one broad hand resting on the warm hood, head tilted as if listening to the engine cool",
  "MS","low","push_in","day",False,False,
  "у переднего колеса стоит коренастый человек в твидовой кепке и слушает, как остывает двигатель."),
 ("A1_SH09",(M,S),"base_yard",
  "Maksim on the left offering his hand in a fingerless leather glove, Stepanych on the right wrapping it whole in his huge weathered palm, the two men measuring each other, the truck's grille behind them",
  "MCU","eye","static","day",False,True,
  "его ладонь накрывает твою перчатку целиком, он говорит, посидишь справа, поглядим, что ты за человек.",
  "the two men holding a slow firm handshake, the older man giving one short nod"),
 ("A1_SH10","OBJ:gloves",None,
  "a pair of worn fingerless driving gloves resting on a young man's knee in a truck cab, the leather creased by another man's grip",
  "INSERT","high","static","day",False,False,
  "перчатки отца тебе пока великоваты, но ты всё равно надел их в первый рабочий день."),
 ("A1_SH11",(M,S),"truck_cab",
  "Maksim sitting straight and nervous in the right seat, Stepanych relaxed behind the wheel on the left, the truck rolling out of the base gates into a pale dawn, both lit by the low sun",
  "MS","eye","static","dawn",False,False,
  "в пять сорок утра фура выкатывается за ворота, и ты впервые в жизни сидишь в кабине справа."),
 ("A1_SH12",None,"roadside_dawn",
  "an empty two-lane highway running straight into low morning mist, a steel guard rail beaded with dew, one pale planet still hanging in the brightening sky",
  "EWS","eye","static","dawn",True,False,
  "впереди девятьсот километров, двенадцать часов пути и человек за рулём, которого ты совсем не знаешь."),
]

# ── A2 SCHOOL_ROAD — дорога-школа, ритуал термоса ──────────────────────────────
PAL_2="warm afternoon gold through the windshield, dusty green fields palette"
SCHOOL=[
 ("A2_SH01",(S,M),"truck_cab",
  "Stepanych on the left driving with two relaxed fingers on the wheel and talking, Maksim on the right listening with his elbow on the door, sunlit fields streaming past the windows",
  "MS","eye","static","day",False,False,
  "степаныч ведёт машину тридцать четвёртый год подряд и говорит о ней спокойно, как о напарнике."),
 ("A2_SH02",(M,S),"truck_cab",
  "over Maksim's shoulder, Stepanych tapping one thick finger against his own ear and then pointing at the dashboard, teaching the young man to listen to the running gear",
  "OTS","over","static","day",False,True,
  "он учит тебя слушать, где стучит подвеска, и повторяет, машина не врёт, врут люди."),
 ("A2_SH03",None,"day_highway",
  "a long straight two-lane highway through flat summer fields, heat shimmer over the bleached asphalt, kilometre posts with peeling paint running to the horizon",
  "WS","eye","track","day",True,False,
  "девятьсот километров укладываются в двенадцать часов, если не жадничать на обгонах и жалеть тормоза."),
 ("A2_SH04",(S,M),"warehouse_ramp",
  "Stepanych on the left running a blunt finger down a waybill on a metal clipboard, Maksim on the right counting shrink-wrapped boxes on a pallet out loud, cold fluorescent light from the roller door",
  "MS","eye","static","day",False,False,
  "на разгрузке он сверяет каждую строчку накладной и заставляет тебя пересчитывать коробки вслух."),
 ("A2_SH05","OBJ:waybill",None,
  "a blunt weathered thumb pressed against a typed cargo line on a carbon-copy waybill form",
  "INSERT","top","static","day",False,True,
  "правило у него одно и очень короткое, в кузове лежит ровно то, что написано в бумаге."),
 ("A2_SH06",(S,M),"truck_stop",
  "Stepanych on the left pulling a dented aluminium thermos from under the seat by the open cab door, Maksim on the right waiting with both hands in his jacket pockets, the canteen wagon lights behind them",
  "WS","eye","static","dusk",False,False,
  "на первом привале он достаёт из-под сиденья мятый алюминиевый термос и откручивает крышку до щелчка."),
 ("A2_SH07","OBJ:thermos",None,
  "steam rising from an open dented aluminium thermos at dusk, the screw-on cup lid set beside it",
  "INSERT","eye","push_in","dusk",False,True,
  "крышка у термоса одна, но к ручке шнурком привязана вторая кружка, эмалированная, для напарника."),
 ("A2_SH08",(S,M),"truck_stop",
  "Stepanych on the left pouring tea from the thermos into a small enamel cup and handing it across, Maksim on the right taking it with both gloved hands, yellow bulb light over the tailgate",
  "MCU","eye","static","dusk",False,True,
  "он наливает тебе первому, и с этого щелчка крышки у вас двоих появляется общий ритуал.",
  "the older man carefully pouring steaming tea into a small enamel cup and handing it to the young man"),
 ("A2_SH09",(M,S),"truck_cab",
  "Maksim on the right writing small numbers in a pocket notebook by the glow of the cab light, Stepanych on the left driving through darkness, oncoming headlights sliding over them",
  "MCU","eye","static","night",False,False,
  "за рейс тебе платят восемнадцать тысяч, и если жить на семь, долг отпустит вас через год."),
 ("A2_SH10",(M,S),"roadside_dawn",
  "Maksim standing on the highway shoulder with a phone pressed to his ear, smiling into the morning mist, Stepanych further back checking a tyre with slow kicks of his boot",
  "WS","eye","static","dawn",False,False,
  "с обочины ты звонишь матери и врёшь, что уже совсем не устаёшь, и она смеётся."),
 ("A2_SH11",None,"night_highway",
  "the headlight cone of a truck carving a pale tunnel through night fields, reflective posts flicking past, the broken centre line pulsing toward the dark",
  "WS","pov","track","night",True,False,
  "ночами трасса сужается до конуса света, и в этом конусе умещается почти вся твоя жизнь."),
 ("A2_SH12",(S,M),"truck_cab",
  "Stepanych on the left glancing over with the first open half-smile under his grey moustache, Maksim on the right laughing at something, the cab warm and easy between them at night",
  "MCU","eye","static","night",False,False,
  "к третьему месяцу степаныч зовёт тебя не стажёром, а напарником, и тебе это дороже премии."),
]

if __name__=="__main__":
    seed_act("cold_open",PAL_C,COLD)
    seed_act("hired",PAL_1,HIRED)
    seed_act("school_road",PAL_2,SCHOOL)

