# -*- coding: utf-8 -*-
"""divorce act A3 cracks (молчание твердеет, отдельные комнаты, несостоявшийся разговор). PYTHONIOENCODING=utf-8 python scripts/_seed_divorce_A3.py"""
from _divorce_engine import seed_act
PAL="cool muted domestic palette, grey-blue and faded warm tones, low even light, quiet hard shadows"
S=[
 ("A3_SH01",None,"bedroom_night","a wide view of a double bed at night with one whole side empty, a pillow and a folded blanket missing from it","WS","eye","static","night",True,False,
  "однажды ночью её половина кровати остаётся пустой, и ты находишь её подушку и плед в гостиной."),
 ("A3_SH02","ZHENA_BASE","living_shared","a medium shot of the woman making up a bed on the living-room sofa, a blanket around her shoulders","MS","eye","static","night",False,False,
  "она стелит себе на диване и говорит, что так высыпается лучше, и ты не споришь и даже втайне рад."),
 ("A3_SH03","MUZH_MAIN","bedroom_night","a close-up of the man lying alone across the whole bed, the cold gap now the entire mattress","CU","high","static","night",False,False,
  "ты лежишь один на всей кровати, и холодная полоса посередине теперь занимает её целиком."),
 ("A3_SH04","SYN_CHILD","living_shared","a medium close-up of a fair-haired boy of seven standing in a doorway watching, a small dinosaur backpack nearby","MCU","eye","static","night",False,False,
  "сын лет семи стоит в дверях и смотрит, как мама устраивается спать на диване под пледом."),
 ("A3_SH05","SYN_CHILD","living_shared","a close-up of the boy's small worried face as he asks a quiet question","CU","low","static","night",False,False,
  "он тихо спрашивает тебя, почему мама теперь спит здесь, а не с тобой, как раньше."),
 ("A3_SH06","MUZH_MAIN","living_shared","a medium close-up of the man giving the boy an easy uncomfortable answer, not meeting his eyes","MCU","eye","static","night",False,False,
  "ты отвечаешь ему первое, что приходит в голову, что так просто удобнее, и сам слышишь, как это звучит."),
 ("A3_SH07",None,"kitchen_mugs","a macro insert of a wall calendar with one date circled in old marker, the date already passed","INSERT","top","static","day",True,False,
  "на кухонном календаре давно обведена дата, годовщина, которую вы оба молча пропустили в этом году."),
 ("A3_SH08","ZHENA_BASE","kitchen_mugs","a close-up of the woman glancing at the circled calendar date for a second, her face still","CU","eye","static","day",False,False,
  "она замечает, что число уже прошло, смотрит на календарь секунду и не говорит ни слова."),
 ("A3_SH09","MUZH_MAIN","kitchen_mugs","a medium shot of the man in the kitchen, a blank trying-to-remember look on his face","MS","eye","static","day",False,False,
  "ты даже не сразу вспоминаешь, что значил этот кружок, и от этого внутри становится совсем пусто."),
 ("A3_SH10",None,"living_shared","a wide view of the living room at dusk with two separate glowing screens lighting opposite corners, a cold gap of empty space between them","WS","eye","static","dusk",True,False,
  "вечером вы вдвоём в одной комнате, но каждый смотрит в свой экран, и между вами метр и целая стена."),
 ("A3_SH11","ZHENA_BASE","living_shared","a medium close-up of the woman setting her phone down and turning to speak, a last attempt on her face","MCU","eye","push_in","dusk",False,False,
  "она вдруг откладывает телефон, поворачивается к тебе и начинает тот самый разговор, который вы откладывали годами."),
 ("A3_SH12","MUZH_MAIN","living_shared","a close-up of the man deflecting, raising a tired hand, looking away","CU","eye","static","dusk",False,False,
  "ты говоришь, что устал и что давай не сейчас, может быть потом, и опять прячешься за этим словом."),
 ("A3_SH13","ZHENA_BASE","living_shared","a close-up of the woman's face quietly closing for good, no anger, just finality","CU","eye","push_in","dusk",False,True,
  "что-то в её лице в этот момент закрывается окончательно, тихо, без хлопка двери."),
 ("A3_SH14","ZHENA_BASE","living_shared","a medium shot of the woman nodding once, picking her phone back up, turning away","MS","eye","static","dusk",False,False,
  "она кивает, перестаёт пытаться, берёт телефон обратно, и больше этот разговор не начнётся никогда."),
 ("A3_SH15","MUZH_MAIN","bedroom_night","an extreme close-up of the man turning the cold gold ring on his finger as he lies awake","ECU","eye","static","night",False,True,
  "ночью ты лежишь один и крутишь на пальце холодное кольцо, которое давно ничего не греет."),
 ("A3_SH16","MUZH_MAIN","bedroom_night","a medium close-up of the man staring at the ceiling, telling himself a reassurance","MCU","eye","static","night",False,False,
  "ты убеждаешь себя, что в любом долгом браке однажды становится тихо и что это совершенно нормально."),
 ("A3_SH17",None,"kitchen_mugs","a wide morning view of a kitchen with two mugs standing at opposite ends of the counter, far apart","WS","eye","static","morning",True,False,
  "по утрам ваши две чашки больше не стоят рядом, а ждут вас на разных концах кухни."),
 ("A3_SH18","SYN_CHILD","living_shared","a medium shot of the boy playing alone on the floor between two silent seated parents","MS","high","static","day",False,False,
  "сын играет один на полу между двумя родителями, которые сидят в тишине и не смотрят друг на друга."),
 ("A3_SH19","MUZH_MAIN","living_shared","a close-up of the man looking across the room at his wife as if at a stranger he shares a flat with","CU","eye","static","dusk",False,False,
  "ты глядишь на неё через комнату, как на соседку по квартире, с которой просто делишь счета и ребёнка."),
 ("A3_SH20",None,"living_shared","an extreme wide dusk view of the apartment split into two quiet lamplit corners, the warmth gone from the room, an empty hush between them","EWS","eye","static","dusk",True,True,
  "вечерами квартира разделена надвое тихими углами, и в каждом сидит по человеку, которые когда-то были мы."),
]
if __name__=="__main__": seed_act("cracks", PAL, S, render_mode="animated")
