# -*- coding: utf-8 -*-
"""announcer batch D: gallery_e (child-fan + stationmaster decline + near-recognition) + turn (the gala). static."""
from _announcer_engine import seed_act

PAL_E="bittersweet fading palette, warm gold thinning to grey, the tenderness of small things ending"
GE=[
 # --- B9 Ребёнок, верящий в голос ---
 ("GE_SH01","CHILDFAN_BASE","concourse_hall","a small child gazing up at a ceiling loudspeaker and pointing, full of wonder","MS","low","static","day",False,False,
  "маленький мальчик задирает голову к динамику под сводом и слушает твой голос, как чудо."),
 ("GE_SH02",None,"concourse_hall","extreme close on a round ceiling loudspeaker grille high in the vaulted roof","INSERT","low","push_in","day",False,True,
  "из круглого динамика под потолком льётся твой голос, и для ребёнка он идёт прямо с неба."),
 ("GE_SH03","CHILDFAN_BASE","concourse_hall","close on the child waving up at the ceiling and asking a question","CU","low","static","day",False,False,
  "он машет потолку рукой и спрашивает маму, где живёт тётя, что знает все поезда на свете."),
 ("GE_SH04","ANNOUNCER_MID","announcer_booth","the announcer hearing the child below through the open booth window, smiling","MCU","high","static","day",False,False,
  "ты слышишь его снизу через открытое окно будки и впервые за день улыбаешься прямо в микрофон."),
 ("GE_SH05","CHILDFAN_BASE","concourse_hall","the child telling his mother the voice is an angel that lives in the station","WS","low","static","day",False,False,
  "он говорит, что это голос ангела, который живёт на вокзале и бережёт всех, кто уезжает."),
 ("GE_SH06","CHILDFAN_BASE","concourse_hall","close on the child waving goodbye up at the loudspeaker as he leaves","CU","low","static","day",False,False,
  "уходя, он машет динамику на прощание, и ты тихо говоришь в микрофон счастливого пути ему."),
 ("GE_SH07","ANNOUNCER_MID","announcer_booth","close on the announcer's bittersweet face","MCU","eye","push_in","day",False,False,
  "для одного ребёнка ты ангел с потолка, а для всех остальных ты часть вокзала, как скамья."),
 ("GE_SH08",None,"concourse_hall","a ceiling loudspeaker with dust drifting in a shaft of light below it","INSERT","low","push_in","day",True,False,
  "ты думаешь, что хорошо быть голосом с неба для того, кто ещё верит, что голоса бывают добрые."),
 ("GE_SH09","ANNOUNCER_MID","announcer_booth","close on the announcer, the bittersweet thought deepening","CU","eye","static","day",False,False,
  "но дети вырастают и перестают слышать ангелов, и однажды этот мальчик пройдёт, не подняв головы."),
 ("GE_SH10","ANNOUNCER_MID","concourse_hall","the announcer at night singing to the empty hall as if the child still listened","WS","low","push_in","night",False,False,
  "ночью ты поёшь пустому залу так, будто внизу всё ещё стоит мальчик и слушает тебя с неба."),
 ("GE_SH11","ANNOUNCER_MID","announcer_booth","close on the announcer wishing to be seen, not just heard","MCU","eye","static","night",False,False,
  "ты понимаешь, что хочешь быть не голосом с потолка, а живым человеком, которого видят в лицо."),
 ("GE_SH12",None,"announcer_booth","the booth window looking down on thousands of oblivious heads in the hall","INSERT","high","push_in","day",True,False,
  "ты смотришь вниз из стеклянной будки на тысячи макушек, и ни одна не поднимется к тебе."),
 # --- B10 Начальник вокзала стареет ---
 ("GE_SH13","STATIONMASTER_BASE","stationmaster_office","the very old stationmaster at his desk walled with city clocks","MS","eye","static","day",False,False,
  "старый начальник вокзала, что когда-то взял тебя за голос, совсем состарился за эти годы."),
 ("GE_SH14","STATIONMASTER_BASE","stationmaster_office","close on the old stationmaster still proud of her, telling the young staff","CU","eye","push_in","day",False,False,
  "он по-прежнему зовёт тебя лучшим голосом дороги и говорит молодым, что вокзал держится на тебе."),
 ("GE_SH15","ANNOUNCER_MID","stationmaster_office","the announcer visiting him, the one who knew her worth","MCU","eye","static","day",False,False,
  "он один знал, чего стоит твой голос, и при нём ты была не мебелью, а человеком при деле."),
 ("GE_SH16",None,"stationmaster_office","extreme close on a wall of ten city clocks, one face stopped","INSERT","eye","push_in","day",False,True,
  "на стене его кабинета часы десяти городов, и один циферблат впервые остановился навсегда."),
 ("GE_SH17","STATIONMASTER_BASE","stationmaster_office","close on the frail stationmaster shaking her hand in farewell","CU","eye","static","day",False,False,
  "перед уходом на покой он жмёт тебе руку и просит беречь голос, его теперь беречь больше некому."),
 ("GE_SH18","STATIONMASTER_BASE","concourse_hall","the old man crossing the great hall for the last time","WS","high","static","day",False,False,
  "он уходит через зал в последний раз, и ты объявляешь по громкой связи спасибо ему одному."),
 ("GE_SH19","ANNOUNCER_MID","stationmaster_office","the new young management arriving in suits","MCU","eye","static","day",False,False,
  "на его место приходят молодые в галстуках, и для них ты строка в смете, а не голос дороги."),
 ("GE_SH20","ANNOUNCER_MID","announcer_booth","close on the announcer exposed under the new accounting eye","CU","eye","push_in","day",False,False,
  "они слушают тебя и считают, во сколько обходится живой диктор, и щёлкают своим калькулятором."),
 ("GE_SH21",None,"automation_room","grey server racks half-installed behind a half-open door, blinking blue","INSERT","eye","push_in","day",True,True,
  "за стеной зала уже монтируют серые шкафы с лампочками, и ты ещё не знаешь, что это для тебя."),
 ("GE_SH22","ANNOUNCER_MID","announcer_booth","the announcer sensing the threat without the old man's protection","MCU","eye","static","day",False,False,
  "ты чувствуешь, что без старика тебя держит только привычка, а привычку легко заменить машиной."),
 ("GE_SH23","ANNOUNCER_MID","announcer_booth","close on the announcer afraid her voice will become unneeded","CU","eye","push_in","day",False,False,
  "впервые за сорок лет ты боишься не за голос, а за то, что голос вот-вот станет совсем ненужным."),
 ("GE_SH24","ANNOUNCER_MID","concourse_hall","the announcer at night singing for the departed stationmaster","WS","low","push_in","night",False,False,
  "ночью ты поёшь пустому залу за старика, что единственный слышал в тебе не диктора, а певицу."),
 ("GE_SH25",None,"stationmaster_office","the stationmaster's empty chair and the stopped clock","INSERT","eye","push_in","night",True,False,
  "его кресло пустует, остановленные часы молчат, и вокзал впервые кажется тебе совсем чужим."),
 ("GE_SH26","ANNOUNCER_MID","announcer_booth","close on the announcer with her last defender now gone","CU","eye","static","night",False,False,
  "ты понимаешь, что человек, который тебя ценил, ушёл, и заступиться за тебя больше некому."),
 # --- B11 Почти-узнавание ---
 ("GE_SH27","ANNOUNCER_MID","concourse_hall","an ordinary woman walking through the hall off-shift, unnoticed by the streaming crowd","WS","eye","track","day",False,False,
  "однажды после смены ты идёшь через зал просто женщиной, и тебя обтекают, не узнавая в лицо."),
 ("GE_SH28","ANNOUNCER_MID","concourse_hall","the woman helping a lost passenger, speaking aloud clearly and warmly","MCU","eye","static","day",False,False,
  "ты помогаешь растерянному пассажиру и говоришь вслух, как привыкла, чётко и очень тепло."),
 ("GE_SH29","ANNOUNCER_MID","concourse_hall","close on the woman as the stranger startles, half-recognising the voice","CU","eye","push_in","day",False,False,
  "пассажир вздрагивает, оборачивается, говорит, что где-то слышал этот голос, и не вспомнит где."),
 ("GE_SH30","ANNOUNCER_MID","concourse_hall","close on the woman almost claiming the voice, then not","MCU","eye","static","day",False,False,
  "ты почти говоришь, что это твой голос звучит тут сорок лет, и не говоришь, и пожимаешь плечами."),
 ("GE_SH31","ANNOUNCER_MID","concourse_hall","close on the woman with her swallowed truth as the stranger leaves","CU","eye","push_in","day",False,False,
  "он уходит, так и не вспомнив, а ты стоишь с твоим знаменитым голосом, которого никто не видит."),
 ("GE_SH32","ANNOUNCER_MID","concourse_hall","the woman standing invisible amid the indifferent crowd","WS","high","static","day",False,False,
  "тебя слышали миллионы, и ни один не повернулся, ведь у голоса нет лица, чтобы его узнать."),
 ("GE_SH33",None,"concourse_hall","loudspeakers high above an oblivious crowd in the hall","INSERT","low","push_in","day",True,True,
  "твой голос льётся сверху на тысячи людей, и ни одному не приходит в голову, что он чей-то."),
 ("GE_SH34","ANNOUNCER_MID","announcer_booth","the announcer back in the booth where she is someone again","MCU","eye","static","day",False,False,
  "ты возвращаешься в будку, где ты кто-то, и понимаешь, что кто-то ты только за этим стеклом."),
 ("GE_SH35","ANNOUNCER_MID","announcer_booth","close on the announcer reckoning the lifelong trade","CU","eye","push_in","day",False,False,
  "сорок лет ты меняла лицо на голос, и теперь у тебя нет ни сцены, ни лица, ни даже имени."),
 ("GE_SH36","ANNOUNCER_MID","concourse_hall","the announcer singing at night now to prove she still exists","WS","low","push_in","night",False,False,
  "ночью ты поёшь пустому залу и впервые поёшь не от счастья, а чтобы доказать, что ты ещё есть."),
 ("GE_SH37",None,"announcer_booth","the faded deep-red silk scarf hung on a nail in the booth","INSERT","eye","push_in","night",True,True,
  "тёмно-красный шарф ты вешаешь на гвоздь в будке, и он выцвел так же, как твоя мечта о сцене."),
 ("GE_SH38","ANNOUNCER_MID","announcer_booth","close on the announcer hearing her replacement being built","MCU","eye","static","night",False,False,
  "ты ещё держишь микрофон, но уже слышишь за стеной, как собирают голос, который тебя заменит."),
 ("GE_SH39","ANNOUNCER_MID","announcer_booth","close on the announcer afraid of falling silent","CU","eye","push_in","night",False,False,
  "и впервые за сорок лет тебе страшно замолчать, потому что без голоса тебя просто не станет."),
 ("GE_SH40",None,"automation_room","grey server racks humming, blue indicators blinking in the dark room","INSERT","eye","push_in","night",True,True,
  "за стеной серые шкафы тихо гудят, и в них уже копят твой голос, по слову, по гонгу, по фразе."),
]

PAL_TURN="deceptive hopeful gala palette, warm stage gold breaking through grey, hope tinted with old fear"
TU=[
 ("TU_SH01",None,"concourse_hall","the great hall being decorated with banners for a centenary gala, a small stage going up","EWS","eye","push_in","day",True,False,
  "на столетие вокзала зал украшают, ставят сцену, и впервые за сорок лет тут будет концерт."),
 ("TU_SH02","ANNOUNCER_OLD","announcer_booth","an event organiser coming up to the booth to invite the announcer to sing","MCU","eye","static","day",False,False,
  "к тебе в будку поднимается распорядитель и предлагает голосу вокзала спеть на юбилее вживую."),
 ("TU_SH03","ANNOUNCER_OLD","announcer_booth","close on the old announcer, disbelief turning to hope","CU","eye","push_in","day",False,False,
  "тебе шестьдесят, и впервые за сорок лет тебя зовут не к микрофону, а на настоящую сцену."),
 ("TU_SH04",None,"concourse_hall","a small stage being built in the middle of the hall beneath the announcer's booth","INSERT","high","push_in","day",False,True,
  "посреди зала, под твоей будкой, сколачивают сцену, и ты смотришь на неё сверху, как на чудо."),
 ("TU_SH05","ANNOUNCER_OLD","music_school","the old announcer practising from old sheet music, her aged voice still obeying","MS","eye","static","day",False,False,
  "ты достаёшь старые ноты, распеваешься тайком, и голос, постаревший, всё ещё слушается тебя."),
 ("TU_SH06","ANNOUNCER_OLD","music_school","close on the old announcer daring to hope she will be seen at last","CU","eye","push_in","day",False,False,
  "ты позволяешь себе поверить, что на склоне лет город наконец увидит тебя, а не только услышит."),
 ("TU_SH07","ANNOUNCER_OLD","announcer_booth","the old announcer tying on the saved deep-red scarf with purpose","MCU","eye","static","day",False,False,
  "ты гладишь тёмно-красный шарф, который берегла для лучшего дня, и думаешь, что день настал."),
 ("TU_SH08","ANNOUNCER_OLD","announcer_booth","close on the old announcer rehearsing nightly toward a real stage at last","CU","eye","push_in","day",False,False,
  "ты репетируешь по ночам в пустом зале, как всегда, но теперь к настоящему выходу на сцену."),
 ("TU_SH09","ANNOUNCER_OLD","concourse_hall","the old announcer singing from the small new stage for the first time at night","WS","low","push_in","night",False,False,
  "ты впервые поёшь не из будки, а со сцены, пусть пока пустому залу, и голос летит свободно."),
 ("TU_SH10",None,"concourse_hall","a gala poster billing the voice of the station, no name printed","INSERT","eye","push_in","day",False,True,
  "на афише юбилея пишут голос вокзала, без имени, но ты впервые будешь не наверху, а в центре."),
 ("TU_SH11","RIVAL_BASE","concourse_hall","the rival, now an aged famous singer, arriving as the gala headliner","MCU","eye","static","day",False,False,
  "но на юбилей приглашают и настоящую звезду, твою однокурсницу, теперь знаменитую певицу."),
 ("TU_SH12","ANNOUNCER_OLD","announcer_booth","close on the old announcer, the old wound reopening beside the rival","CU","eye","push_in","day",False,False,
  "ты снова рядом с той, кого взяли за лицо, и снова боишься, что тебя задвинут в тень."),
 ("TU_SH13","ANNOUNCER_OLD","stationmaster_office","the young management telling her they will use a recording instead","MCU","eye","static","day",False,False,
  "за неделю до юбилея молодые решают, что живьём рискованно, и пустят твой голос в записи."),
 ("TU_SH14","ANNOUNCER_OLD","stationmaster_office","close on the old announcer hearing she will not appear in person","CU","eye","push_in","day",False,False,
  "тебе говорят, что голос твой прозвучит со сцены, а самой выходить не нужно, так надёжнее."),
 ("TU_SH15","ANNOUNCER_OLD","concourse_hall","at the gala her recorded voice plays while the rival bows on the lit stage","WS","eye","static","night",False,False,
  "на юбилее звучит твой голос в записи, а на сцене под него кланяется живая знаменитая звезда."),
 ("TU_SH16",None,"concourse_hall","the lit gala stage and a crowd applauding the singer on it","INSERT","low","push_in","night",True,True,
  "зал аплодирует, и аплодисменты опять достаются лицу на сцене, а не голосу из колонок."),
 ("TU_SH17","ANNOUNCER_OLD","announcer_booth","the old announcer watching her own triumph from the booth above","MCU","high","static","night",False,False,
  "ты смотришь свой собственный триумф сверху, из будки, и снова ты только голос, а не человек."),
 ("TU_SH18","ANNOUNCER_OLD","announcer_booth","close on the old announcer's hope dying","CU","eye","push_in","night",False,False,
  "ты понимаешь, что и в последний раз тебя выпустили не на сцену, а в динамики, как всегда."),
 ("TU_SH19","ANNOUNCER_OLD","concourse_hall","the gala over, the hall emptying, the little stage being struck","WS","eye","static","night",False,False,
  "юбилей кончается, сцену разбирают, и от твоего единственного концерта не остаётся и следа."),
 ("TU_SH20",None,"concourse_hall","bare marble where the stage stood, banners coming down","INSERT","eye","push_in","night",True,False,
  "там, где стояла сцена, снова голый мрамор, и ты так и не ступила на неё ни единого раза."),
 ("TU_SH21","ANNOUNCER_OLD","announcer_booth","the old announcer back at routine announcements, heavier","MCU","eye","static","day",False,False,
  "наутро ты снова объявляешь поезда, и голос твой ровный, а внутри что-то окончательно гаснет."),
 ("TU_SH22","ANNOUNCER_OLD","announcer_booth","close on the old announcer and the deeper second wound","CU","eye","push_in","day",False,False,
  "тяжелее всего не то, что тебя не взяли в двадцать четыре, а что не выпустили и в шестьдесят."),
 ("TU_SH23","ANNOUNCER_OLD","concourse_hall","the old announcer singing at night, the joy gone out of it","WS","low","push_in","night",False,False,
  "ночью ты снова поёшь пустому залу, потому что это единственная сцена, что у тебя осталась."),
 ("TU_SH24","ANNOUNCER_OLD","announcer_booth","close on the old announcer, the night song now a reminder of loss","CU","eye","push_in","night",False,False,
  "и впервые твой ночной концерт не утешает, а только напоминает, чего тебе так и не дали."),
 ("TU_SH25",None,"concourse_hall","the vast empty night hall holding her joyless song","INSERT","high","static","night",True,True,
  "огромный пустой зал слушает тебя, как слушал сорок лет, и это всё, что у тебя есть."),
 ("TU_SH26","RIVAL_BASE","station_facade","the famous rival leaving by car in applause, passing the announcer without knowing her","MCU","eye","static","night",False,False,
  "твоя однокурсница уезжает со славой и проходит мимо тебя, не узнав в старухе тот самый голос."),
 ("TU_SH27","ANNOUNCER_OLD","announcer_booth","close on the old announcer wishing the rival a safe trip over the PA","CU","eye","push_in","night",False,False,
  "ты подаёшь ей в микрофон счастливого пути, и она машет колонкам, не зная, кому она машет."),
 ("TU_SH28","ANNOUNCER_OLD","announcer_booth","the old announcer settling into final acceptance","MCU","eye","static","night",False,False,
  "ты возвращаешься в будку и понимаешь, что сцены не будет уже никогда, ни большой, ни малой."),
 ("TU_SH29","ANNOUNCER_OLD","announcer_booth","close on the old announcer counting the cost of the promised day","CU","eye","push_in","night",False,False,
  "ты прожила сорок лет на обещании лучшего дня, и лучший день прошёл мимо в чужой записи."),
 ("TU_SH30",None,"automation_room","the automation room now nearly complete, racks lit and humming","WS","eye","static","night",True,True,
  "за стеной серые шкафы с твоим голосом почти собраны, и юбилей был их первой репетицией."),
 ("TU_SH31","ANNOUNCER_OLD","announcer_booth","the old announcer beginning to sense the real end coming","MCU","eye","static","day",False,False,
  "ты ещё не знаешь точно, но уже догадываешься, что запись на юбилее делали не ради праздника."),
 ("TU_SH32","ANNOUNCER_OLD","announcer_booth","close on the old announcer realising her whole voice was captured","CU","eye","push_in","day",False,False,
  "твой голос записали начисто, каждую фразу, каждый гонг, и ты сама не поняла тогда зачем."),
 ("TU_SH33",None,"announcer_booth","extreme close on the worn brass chime button under a fingertip","INSERT","top","push_in","day",False,False,
  "ты гладишь латунную кнопку гонга, не зная, что нажимаешь её уже считанные последние разы."),
 ("TU_SH34","ANNOUNCER_OLD","announcer_booth","the old announcer reassuring herself, not hearing the end approach","MCU","eye","static","day",False,False,
  "ты говоришь себе, ещё поработаю, голос ещё крепок, и не слышишь, как за стеной он звучит без тебя."),
]

seed_act("gallery_e", PAL_E, GE, render_mode="static")
seed_act("turn",      PAL_TURN, TU, render_mode="static")
