# -*- coding: utf-8 -*-
"""webcam A2 first_money + A3 ascent. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_webcam_A2A3.py"""
from _webcam_engine import seed_act

P_M="bright seductive neon palette, vivid magenta and cyan glow over new money sheen, glossy and cheap"
P_A="peak neon palette, saturated hot pink and electric blue, dazzling screen glow hiding a cold core"

MONEY=[
 ("A2_SH01",None,"stream_room","a wide view of a small streaming room aglow with a ring light and LED strips, a webcam on a tripod, staged and bright","WS","eye","push_in","night",True,False,
  "за первый месяц ты зарабатываешь столько, что бросаешь и кафе, и почти забываешь про учёбу."),
 ("A2_SH02","HERO_YOUNG","stream_room","a medium shot of the platinum-blonde girl performing to a webcam under a ring light, a practiced bright smile","MS","eye","static","night",False,False,
  "ты выходишь в эфир каждый вечер, и Алиса получается у тебя всё лучше и естественнее."),
 ("A2_SH03","PODRUGA_BASE","own_apartment","a medium close-up of the jet-black-bob woman coaching the girl, a vape pen in hand, cool and knowing","MCU","over","static","day",False,False,
  "Рита учит тебя правилам, никогда не показывай настоящее имя, лицо помни, но сердце держи закрытым."),
 ("A2_SH04","HERO_YOUNG","own_apartment","a close-up of the young woman listening intently to the rules","CU","eye","static","day",False,False,
  "первое правило, говорит она, зритель платит за иллюзию, что ты именно его девочка."),
 ("A2_SH05",None,None,"an extreme close-up macro insert of a plain ID card beside a phone showing a glowing screen handle, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "у тебя теперь два имени, Настя в паспорте и Алиса на экране, и они всё меньше похожи."),
 ("A2_SH06","MANAGER_BASE","studio_office","a medium shot of a slick dark-haired man of forty with a headset and a phone in a monitor-lit studio office","MS","eye","static","day",False,False,
  "появляется Стас, менеджер студии, обещает больше зрителей и техники за свой процент с каждого доната."),
 ("A2_SH07","MANAGER_BASE","studio_office","a medium close-up of the manager speaking coldly, gesturing at dashboards","MCU","over","static","day",False,False,
  "он говорит, что ты товар с коротким сроком годности, и что зарабатывать надо, пока молодая."),
 ("A2_SH08","HERO_YOUNG","studio_office","a close-up of the young woman bristling at the word but tempted by the numbers","CU","eye","static","day",False,False,
  "ты злишься на слово товар, но подписываешь, потому что цифры, которые он показывает, слишком заманчивы."),
 ("A2_SH09",None,None,"an extreme close-up macro insert of a hand signing a studio contract on a desk, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "ты ставишь подпись под договором со студией, и часть твоей свободы уходит вместе с чернилами."),
 ("A2_SH10","HERO_YOUNG","own_apartment","a medium shot of the young woman moving into a nicer apartment with new streaming gear in boxes","MS","eye","static","day",False,False,
  "на первые серьёзные деньги ты снимаешь квартиру получше и покупаешь профессиональную лампу и камеру."),
 ("A2_SH11",None,None,"an extreme close-up macro insert of a large new ring light and a webcam on a tripod, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,False,
  "новая кольцевая лампа больше и ярче старой, и с ней Алиса выглядит совсем как настоящая звезда."),
 ("A2_SH12","HERO_YOUNG","stream_room","a close-up of the young woman carefully adjusting light and angle and smile before a broadcast","CU","eye","static","night",False,False,
  "ты часами настраиваешь свет, ракурс и улыбку, потому что теперь это твоя работа и твой доход."),
 ("A2_SH13","HERO_YOUNG","kitchen_home","a medium shot of the young woman on the phone in an ordinary daytime kitchen, lying lightly","MS","eye","static","day",False,False,
  "ты звонишь матери и говоришь, что устроилась в поддержку, работаешь из дома, всё хорошо."),
 ("A2_SH14","MOTHER_BASE","mother_home","a medium close-up of a grey-haired mother in a headscarf and glasses on a cord, proud and pleased","MCU","eye","static","day",False,False,
  "мать радуется, хвалит тебя перед соседями и говорит, что наконец-то ты нашла нормальную работу."),
 ("A2_SH15","HERO_YOUNG","kitchen_home","a close-up of the young woman on the phone, the double life beginning to weigh on her","CU","eye","push_in","day",False,False,
  "ты слушаешь её гордый голос и впервые чувствуешь, как двойная жизнь начинает давить на плечи."),
 ("A2_SH16",None,None,"an extreme close-up macro insert of a velvet star choker laid beside plain daytime clothes, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "днём ты обычная девушка без макияжа, а вечером надеваешь чокер, и звёздочка включает Алису."),
 ("A2_SH17",None,"city_street_neon","a wide view of a glittering neon city skyline at night, full of light and promise","WS","low","tilt_up","night",True,False,
  "город внизу горит рекламой и обещаниями, и тебе кажется, что ты наконец-то поймала удачу."),
 ("A2_SH18","PODRUGA_BASE","club_bar","a medium shot of the jet-black-bob woman with the girl in a dim neon bar among other models","MS","eye","static","night",False,False,
  "Рита водит тебя по барам, знакомит с другими моделями, и все они говорят, что копят на будущее."),
 ("A2_SH19","HERO_YOUNG","club_bar","a close-up of the young woman noticing the older models' futures never arriving","CU","eye","static","night",False,False,
  "но ты замечаешь, что у тех, кто в деле давно, будущее всё не наступает, а деньги куда-то деваются."),
 ("A2_SH20",None,None,"an extreme close-up macro insert of shopping bags and new gadgets piled on a bed, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "деньги приходят легко и уходят так же легко, на одежду, на технику, на красивую пустоту."),
 ("A2_SH21","HERO_YOUNG","own_apartment","a medium close-up of the young woman careless with money, certain of the future","MCU","eye","static","day",False,False,
  "ты не откладываешь ничего, потому что уверена, что молодость и зрители будут с тобой всегда."),
 ("A2_SH22","HERO_YOUNG","own_apartment","a close-up of the platinum-blonde girl of twenty, two names and her own apartment, feeling she has won","CU","eye","push_in","day",False,True,
  "тебе двадцать, у тебя два имени, своя квартира и чувство, что ты всех обыграла."),
]

ASCENT=[
 ("A3_SH01",None,"own_apartment","a wide view of a sleek modern apartment lit by neon city light through tall windows, cool and glossy","WS","eye","push_in","night",True,False,
  "к двадцати двум ты в топе платформы, тысячи подписчиков ждут каждый твой эфир."),
 ("A3_SH02","HERO_MID","stream_room","a medium shot of the confident platinum-blonde woman of twenty-two directing her own show at the webcam","MS","eye","static","night",False,False,
  "ты уже не дрожишь перед камерой, ты режиссёр своего шоу, и зрители кормят тебя вниманием."),
 ("A3_SH03","HERO_MID","stream_room","a medium close-up of the woman glancing at a chime notification with a bright reflexive smile","MCU","eye","static","night",False,False,
  "дзынь звучит теперь десятки раз за вечер, и каждый звук — это чей-то кусочек одиночества."),
 ("A3_SH04",None,None,"an extreme close-up macro insert of a glowing screen flooded with heart icons and tip alerts, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "экран заливают сердечки и донаты, и на секунду тебе правда кажется, что тебя любят тысячи."),
 ("A3_SH05","HERO_MID","stream_room","a close-up of the woman performing warmly for the camera as if to one person","CU","eye","static","night",False,False,
  "ты знаешь по именам постоянных зрителей и играешь для каждого так, будто он единственный."),
 ("A3_SH06","DONATOR_BASE","donator_room","a medium close-up of a lonely balding man in his fifties in the blue glow of a monitor, headphones on his neck","MCU","eye","static","night",False,False,
  "среди них есть один, которого зовут Король, он одинок, немолод и платит больше всех остальных."),
 ("A3_SH07","DONATOR_BASE","donator_room","a medium shot of the man alone in his dim screen-lit apartment typing long messages","MS","eye","static","night",False,False,
  "он сидит в синем свете монитора, наушники на шее, и пишет тебе каждый день длинные письма."),
 ("A3_SH08","HERO_MID","stream_room","a close-up of the woman answering him sweetly on camera, calculating underneath","CU","eye","static","night",False,False,
  "ты отвечаешь ему ласково, потому что он платит за твою квартиру, сам того не зная."),
 ("A3_SH09",None,None,"an extreme close-up macro insert of a large tip notification lighting up a screen, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "когда Король присылает крупный донат, дзынь звучит по-особому, и ты роняешь ему воздушный поцелуй."),
 ("A3_SH10","HERO_MID","stream_room","a medium shot of the woman spinning a private fantasy for the camera","MS","eye","static","night",False,False,
  "для него ты придумываешь целую историю про вашу особенную связь, которой на самом деле нет."),
 ("A3_SH11","DONATOR_BASE","donator_room","a close-up of the lonely man believing every word, her face filling his screen","CU","eye","push_in","night",False,False,
  "он верит каждому слову, потому что дома у него нет никого, кроме твоего лица на экране."),
 ("A3_SH12",None,"city_street_neon","a wide view of a dazzling neon city street at night, endless light and motion","WS","eye","pan_right","night",True,False,
  "ночной город подмигивает неоном, и кажется, что этот праздник внимания будет длиться вечно."),
 ("A3_SH13","MANAGER_BASE","studio_office","a medium shot of the slick manager pleased at his dashboards, promoting her in the rankings","MS","eye","static","day",False,False,
  "Стас доволен, ты его лучший актив, он поднимает тебя в топах и берёт всё больший процент."),
 ("A3_SH14","HERO_MID","own_apartment","a close-up of the woman buying whatever she wants, not noticing the money vanish","CU","eye","static","day",False,False,
  "ты покупаешь себе всё, что хочешь, и не замечаешь, что почти всё уходит так же быстро."),
 ("A3_SH15",None,None,"an extreme close-up macro insert of a crammed wardrobe of clothes and gadgets, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "шкаф ломится от вещей, счёт пустеет к концу месяца, но ты уверена, что впереди только больше."),
 ("A3_SH16","HERO_MID","stream_room","a medium close-up of the woman smiling through hours of streaming, jaw aching","MCU","eye","static","night",False,False,
  "ты работаешь по шесть часов в эфире, улыбаешься до боли в скулах и называешь это свободой."),
 ("A3_SH17","HERO_MID","stream_room","a close-up of the woman sitting in silence after a stream, unsure where the persona ends","CU","eye","push_in","night",False,False,
  "иногда после стрима ты сидишь в тишине и не можешь вспомнить, где заканчивается Алиса и где ты."),
 ("A3_SH18",None,"stream_room","a wide view of a ring light going dark at dawn in a staged bedroom, quiet after the show","WS","eye","static","night",True,False,
  "кольцевая лампа гаснет под утро, и на несколько часов ты снова становишься просто Настей."),
 ("A3_SH19","HERO_MID","bedroom_dark","a medium shot of the woman alone in a dark bedroom, the persona louder than herself","MS","eye","static","night",False,False,
  "но Настя всё тише, а Алиса всё громче, и как-то ночью ты думаешь о себе уже в третьем лице."),
 ("A3_SH20",None,None,"an extreme close-up macro insert of a mirror reflecting a made-up face with a velvet star choker, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,False,
  "в зеркале на тебя смотрит Алиса с бархатным чокером, и ты не сразу узнаёшь в ней себя."),
 ("A3_SH21","HERO_MID","own_apartment","a medium close-up of the woman of twenty-five at the top, unable to see it is a peak","MCU","eye","static","night",False,False,
  "тебе двадцать пять, ты на самом верху, и оттуда совсем не видно, что это уже вершина."),
 ("A3_SH22","HERO_MID","own_apartment","a close-up of the woman certain it will last forever, telling herself a first big lie","CU","eye","push_in","night",False,True,
  "ты думаешь, что так будет всегда, и это первая большая ложь, которую ты рассказала себе сама."),
]

if __name__=="__main__":
    seed_act("first_money", P_M, MONEY, render_mode="animated")
    seed_act("ascent",      P_A, ASCENT, render_mode="static")
