# -*- coding: utf-8 -*-
"""surrogate A0 cold_open + A1 origin. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_surrogate_A0A1.py"""
from _surrogate_engine import seed_act

P_COLD="hollow warm-grey palette, a single low warm bulb against deep night shadow, muted and quiet"
P_ORIGIN="poor tender palette, faded warm browns and washed grey daylight, threadbare domestic warmth"

COLD=[
 ("A0_SH01","HERO_OLD","kitchen_night","a tired woman of forty-six sitting alone at a plastic-topped kitchen table under a single low bulb at night, an old tin box before her","WS","eye","push_in","night",False,False,
  "тебе сорок шесть, ты сидишь на кухне одна под тусклой лампой, а перед тобой стоит старая жестяная коробка."),
 ("A0_SH02","HERO_OLD","kitchen_night","a medium close-up of the woman's lined face as she lifts the lid of the tin box, a careful private grief","MCU","eye","static","night",False,False,
  "ты открываешь её не каждый день, только когда становится совсем невыносимо молчать об этом."),
 ("A0_SH03",None,None,"an extreme close-up macro insert of an open tin box holding three plastic hospital ID bracelets and three tiny knitted baby booties, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,True,
  "внутри три пластиковых больничных браслета и три крошечные вязаные пинетки, по одной от каждого."),
 ("A0_SH04","HERO_OLD","kitchen_night","a close-up of the woman's face holding back tears in the warm bulb light","CU","eye","static","night",False,False,
  "трое детей, которых ты выносила и родила, но ни одного из них ты никогда не растила."),
 ("A0_SH05","HERO_OLD","kitchen_night","a medium shot of the woman turning her head toward the wall as if hearing a sound through it","MS","eye","static","night",False,False,
  "за стеной у соседей плачет младенец, и твоё тело до сих пор отзывается на этот звук."),
 ("A0_SH06",None,None,"an extreme close-up macro insert of a single tiny hand-knitted baby bootie resting in an open palm, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","push_in","night",True,False,
  "ты держишь на ладони пинетку, которую связала тайком, пока носила чужого ребёнка под сердцем."),
 ("A0_SH07",None,"kitchen_night","a wide view of a poor kitchen wall at night with a child's crayon drawing taped to a cupboard, one warm pool of light","WS","eye","pan_left","night",True,False,
  "на стене висит рисунок твоего единственного сына, который теперь звонит тебе раз в год."),
 ("A0_SH08","HERO_OLD","kitchen_night","a medium close-up of the woman staring into the box, hollow and worn","MCU","eye","static","night",False,False,
  "ты отдала три жизни чужим людям за деньги и думала, что спасаешь этим свою семью."),
 ("A0_SH09","HERO_OLD","kitchen_night","a close-up of the woman's tired eyes, a lifetime of quiet loss behind them","CU","eye","push_in","night",False,False,
  "а осталась в итоге одна, с жестяной коробкой и телом, которое больше не может носить своих."),
 ("A0_SH10","HERO_OLD","kitchen_night","a medium shot of the woman sitting still at the table, the box open before her","MS","eye","static","night",False,False,
  "восемнадцать лет назад тебе двадцать восемь, и ты ещё не знаешь, на что готова ради ребёнка."),
 ("A0_SH11",None,"kitchen_night","a wide view of a dim poor kitchen at night, a cupboard door ajar where a tin box is being put away, quiet shadow","WS","eye","static","night",True,False,
  "коробку ты прячешь обратно в шкаф, но история, которая в ней лежит, никуда не девается."),
 ("A0_SH12",None,None,"an extreme close-up macro insert of three plastic hospital ID bracelets laid side by side, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "три браслета, три имени, которых никто, кроме тебя, не знает, и три матери, которые не ты."),
 ("A0_SH13","HERO_OLD","kitchen_night","a medium close-up of the woman of forty-six turning to face the viewer in the low light","MCU","eye","push_in","night",False,False,
  "если хочешь понять, как женщина отдаёт своих детей одного за другим, останься со мной до конца."),
 ("A0_SH14","HERO_OLD","kitchen_night","a close-up of the woman looking directly at the viewer, worn and honest","CU","eye","push_in","night",False,True,
  "подпишись, и я расскажу тебе всё с самого начала, пока ты не совершила ту же ошибку."),
]

ORIGIN=[
 ("A1_SH01",None,"small_town_street","a wide establishing view of a poor grey small-town street of low buildings and bare trees under a flat sky","WS","eye","push_in","day",True,False,
  "восемнадцать лет назад тебе двадцать восемь, ты живёшь в бедном посёлке с мужем и маленьким сыном."),
 ("A1_SH02","HERO_YOUNG","poor_flat","a medium shot of a kind tired woman of twenty-eight holding her pale six-year-old son on a sagging sofa in a poor flat","MS","eye","static","day",False,False,
  "твоему Мише шесть, он часто болеет, и врачи говорят, что без операции он не выправится."),
 ("A1_SH03","SON_CHILD","poor_flat","a medium close-up of a pale fair-haired six-year-old boy lying under a blanket, clutching a small red toy car","MCU","high","static","day",False,False,
  "он лежит бледный, сжимает свою красную машинку, и ты готова на что угодно, лишь бы он жил."),
 ("A1_SH04","HERO_YOUNG","poor_flat","a close-up of the young mother's desperate worried face beside the sick child","CU","eye","push_in","day",False,False,
  "операция стоит столько, сколько ты не заработаешь и за десять лет на своей работе."),
 ("A1_SH05","MUZH_BASE","poor_flat","a medium shot of a thin buzz-cut man of thirty-two shrugging helplessly in the poor flat, a cigarette behind his ear","MS","eye","static","day",False,False,
  "муж Толя разводит руками, занимает по мелочи и всё чаще пропадает, а денег всё нет."),
 ("A1_SH06",None,"small_town_street","a wide view of an empty grey small-town street with a shuttered kiosk and puddles, weak daylight","WS","eye","pan_right","day",True,False,
  "посёлок серый и пустой, работы нет, и каждый месяц вы всё глубже влезаете в долги."),
 ("A1_SH07",None,None,"an extreme close-up macro insert of a printed classified advertisement offering large payment to surrogate mothers, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "однажды ты видишь объявление, где женщинам предлагают большие деньги за то, чтобы выносить чужого ребёнка."),
 ("A1_SH08","HERO_YOUNG","poor_flat","a close-up of the young woman staring at the advertisement, a dangerous idea taking hold","CU","eye","push_in","day",False,False,
  "сумма в объявлении закрывает операцию Миши целиком, и ещё остаётся, и ты не можешь перестать о ней думать."),
 ("A1_SH09","HERO_YOUNG","kitchen_night","a medium shot of the woman sitting at the kitchen table at night looking toward her sleeping child's room","MS","eye","static","night",False,False,
  "ты сидишь ночью на кухне, смотришь на спящего сына, и решение приходит само, будто выбора и нет."),
 ("A1_SH10",None,"coordinator_office","a wide view of a tidy modern surrogacy agency office with a glass desk, stacked contracts and a city window, cool and clean","WS","eye","push_in","day",True,False,
  "через неделю ты впервые входишь в чистый офис агентства, где всё говорит о деньгах и порядке."),
 ("A1_SH11","COORD_BASE","coordinator_office","a medium close-up of a sleek silver-blonde woman of forty-five with a lanyard ID and a tablet, a cool professional smile","MCU","eye","static","day",False,False,
  "тебя встречает Инна Сергеевна, координатор, с бейджем и планшетом, и улыбкой, за которой один расчёт."),
 ("A1_SH12","COORD_BASE","coordinator_office","a medium shot of the coordinator calmly explaining terms across the glass desk, gesturing at a contract","MS","over","static","day",False,False,
  "она спокойно объясняет, что ты выносишь чужого ребёнка, отдаёшь его при рождении и получаешь деньги."),
 ("A1_SH13","HERO_YOUNG","coordinator_office","a close-up of the young woman nodding as if it were an ordinary job, hiding her unease","CU","eye","static","day",False,False,
  "ты киваешь, будто речь о простой работе, и стараешься не думать, что это будет живой ребёнок."),
 ("A1_SH14",None,None,"an extreme close-up macro insert of a multi-page contract and a pen lying on a glass desk, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "перед тобой ложится договор на много страниц, где ребёнок называется словом, а не именем."),
 ("A1_SH15","COORD_BASE","coordinator_office","a medium close-up of the coordinator reassuring the client with a practiced calm","MCU","over","static","day",False,False,
  "Инна Сергеевна говорит, что так делают многие, что это законно и что ты просто помогаешь другой семье."),
 ("A1_SH16","HERO_YOUNG","coordinator_office","a close-up of the young woman wanting to believe the reassurance, fear under her calm","CU","eye","push_in","day",False,False,
  "ты хочешь верить, что это правда, потому что за этой правдой стоит здоровье твоего сына."),
 ("A1_SH17",None,"coordinator_office","a wide view through a large office window over a wealthy indifferent city, cool daylight","WS","eye","static","day",True,False,
  "за окном чужой богатый город живёт своей жизнью, где такие сделки — обычное дело."),
 ("A1_SH18","HERO_YOUNG","poor_flat","a medium shot of the woman returning to her poor flat, quiet and secretive","MS","eye","static","day",False,False,
  "ты возвращаешься домой и ничего не говоришь мужу, потому что боишься, что он запретит."),
 ("A1_SH19","SON_CHILD","poor_flat","a close-up of the sleeping pale six-year-old boy, his mother's hand stroking his hair","CU","high","static","night",False,False,
  "ты садишься у кровати Миши, гладишь его по голове и обещаешь, что он поправится любой ценой."),
 ("A1_SH20",None,None,"an extreme close-up macro insert of a small red toy car resting on a child's pillow, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,False,
  "его красная машинка лежит рядом на подушке, и ради неё, ради него ты подписываешь всё."),
 ("A1_SH21","HERO_YOUNG","coordinator_office","a medium shot of the young woman signing the contract at the glass desk, her hand steady until the end","MS","over","static","day",False,False,
  "наутро ты ставишь подпись под договором, и рука дрожит только один раз, в самом конце."),
 ("A1_SH22","HERO_YOUNG","coordinator_office","a close-up of the woman's changed face as she leaves the office, no longer only a mother","CU","eye","push_in","day",False,False,
  "ты выходишь из офиса уже не просто матерью Миши, а женщиной, которая продала своё тело в аренду."),
 ("A1_SH23",None,"small_town_street","a wide view of the grey small-town street under the same flat sky, still and unchanged outside","WS","eye","static","day",True,False,
  "посёлок встречает тебя тем же серым небом, но внутри тебя уже всё изменилось навсегда."),
 ("A1_SH24","HERO_YOUNG","poor_flat","a medium close-up of the woman of twenty-eight, hopeful and naive, believing it is only once","MCU","eye","static","day",False,True,
  "тебе двадцать восемь, ты веришь, что это один раз, и глубоко ошибаешься, как ошибаются все."),
]

if __name__=="__main__":
    seed_act("cold_open", P_COLD, COLD, render_mode="animated")
    seed_act("origin",    P_ORIGIN, ORIGIN, render_mode="animated")
