# -*- coding: utf-8 -*-
"""divorce act A2 drift (12 лет: мелкие пропуски, «потом»). PYTHONIOENCODING=utf-8 python scripts/_seed_divorce_A2.py"""
from _divorce_engine import seed_act
PAL="muted domestic palette, warm tones cooling toward grey, soft window light, gentle quiet shadows"
S=[
 ("A2_SH01",None,"living_shared","a wide cosy view of a lived-in family living room in the early years, two coffee cups on the low table, warm clutter","WS","eye","static","day",True,False,
  "первые годы на этой кухне ещё тепло, две чашки стоят рядом, и вы пьёте кофе, не глядя в телефоны."),
 ("A2_SH02","MUZH_MAIN","living_shared","a medium close-up of the man on the sofa reaching for a laptop, half-turned away, a distracted face","MCU","eye","static","day",False,False,
  "ты говоришь поговорим потом и тянешься за ноутбуком, и это потом становится самым частым словом в доме."),
 ("A2_SH03","ZHENA_BASE","living_shared","a close-up of the woman with a black low bun nodding quietly, swallowing what she meant to say","CU","eye","static","day",False,False,
  "она кивает и проглатывает то, что хотела сказать, и таких проглоченных фраз с каждым годом всё больше."),
 ("A2_SH04",None,"kitchen_mugs","a top-down macro insert of two ceramic mugs side by side on a kitchen table, both still warm and used","INSERT","top","static","day",True,False,
  "на столе всё ещё две чашки рядом, обе тёплые, и пока ещё некому из вас пить кофе в одиночку."),
 ("A2_SH05","ZHENA_BASE","living_shared","a medium shot of the woman sitting alone on the sofa later, the space beside her empty","MS","eye","static","dusk",False,False,
  "разговор, который вы отложили, так и не случается, и она привыкает сидеть с этим молча."),
 ("A2_SH06",None,"living_shared","a macro insert of a tiny baby shoe by the door and the rail of a wooden crib in the corner of the room","ECU","eye","static","day",True,False,
  "появляется крошечный ботиночек у двери и кроватка в углу — у вас рождается сын."),
 ("A2_SH07","MUZH_MAIN","living_shared","a wide shot of the man leaving early through the apartment entry hall, pulling on a jacket","WS","eye","static","morning",False,False,
  "ты уходишь на работу всё раньше, потому что так проще, чем сидеть за столом, где стало тихо."),
 ("A2_SH08","SYN_CHILD","living_shared","a medium close-up of a fair-haired boy of about six with a small dinosaur backpack standing by the door, waiting","MCU","eye","static","morning",False,False,
  "сын лет шести стоит у двери с рюкзаком-динозавром и ждёт, когда ты хотя бы посмотришь на него."),
 ("A2_SH09","MUZH_MAIN","living_shared","a close-up of the man crouching to the boy's level with a hurried promise on his face","CU","eye","push_in","morning",False,False,
  "ты обещаешь ему, что в выходные обязательно, и сам уже почти не веришь этому слову."),
 ("A2_SH10","ZHENA_BASE","kitchen_mugs","a medium shot of the woman reheating dinner alone in the kitchen, setting out a single plate","MS","eye","static","night",False,False,
  "она в который раз разогревает ужин на двоих и накрывает только одну тарелку."),
 ("A2_SH11",None,"living_shared","a macro insert of one phone glowing face-up on a sofa arm and another phone lying face-down nearby","INSERT","top","static","night",True,False,
  "твой телефон светится экраном вверх на подлокотнике, а её лежит экраном вниз, и так теперь всегда."),
 ("A2_SH12",None,"bedroom_night","a wide view of a shared double bed at night with a wide cold empty gap down the middle, two bedside lamps","WS","eye","static","night",True,False,
  "ночью между вами в кровати остаётся широкая холодная полоса, которую никто не пытается перейти."),
 ("A2_SH13","MUZH_MAIN","bedroom_night","a medium close-up of the man lying awake with his back turned, eyes open in the low lamp light","MCU","eye","static","night",False,False,
  "ты лежишь спиной к ней и думаешь о работе, потому что про вас двоих думать почему-то страшнее."),
 ("A2_SH14","ZHENA_BASE","bedroom_night","a close-up of the woman staring at the ceiling with open eyes, the cold blue window light on her face","CU","eye","static","night",False,False,
  "она смотрит в потолок с открытыми глазами и уже не помнит, когда ты последний раз её обнял."),
 ("A2_SH15","DRUG_BASE","living_shared","a medium shot of a bald bearded friend on the sofa drawing on a small e-cigarette, speaking bluntly","MS","eye","static","day",False,False,
  "друг, который развёлся год назад, затягивается вейпом и говорит, что всё начинается вот с такой тишины."),
 ("A2_SH16","MUZH_MAIN","living_shared","a close-up of the man waving the warning off with a dismissive half-smile","CU","eye","static","day",False,False,
  "ты отмахиваешься и отвечаешь, что у вас не так, у вас просто устали, и сам себе киваешь."),
 ("A2_SH17","MUZH_MAIN","living_shared","an extreme close-up of the plain gold wedding band on the man's finger, long unnoticed","ECU","eye","push_in","day",False,True,
  "обручальное кольцо всё так же на пальце, но ты давно перестал его замечать, как перестал замечать её."),
 ("A2_SH18","MUZH_MAIN","living_shared","a medium shot of the man passing through the living room, the woman just visible leaving the frame the other way","MS","eye","static","dusk",False,False,
  "проходят годы, вы расходитесь по комнатам, встречаетесь на кухне и говорите только о сыне и о счетах."),
 ("A2_SH19",None,"kitchen_mugs","a macro insert of a single clean mug set apart on a drying rack, alone","INSERT","top","static","dusk",True,False,
  "теперь одна чашка всегда вымыта и убрана отдельно, и кухня запоминает это раньше вас."),
 ("A2_SH20",None,"living_shared","a wide view of the same living room, the same furniture, the warmth visibly drained from the light","WS","eye","static","dusk",True,True,
  "та же мебель, та же квартира, только тепла в ней с каждым годом всё меньше, и вы оба это чувствуете."),
]
if __name__=="__main__": seed_act("drift", PAL, S, render_mode="animated")
