# -*- coding: utf-8 -*-
"""car_flipper — cold_open (ночь на трассе + CTA) и акт 1 (гараж, 17 лет)."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _car_flipper_engine import seed_act

P0 = "a cold night palette of wet black asphalt, turning blue and orange beacon light, sodium haze and deep unlit grass"
P1 = "a warm dim palette of tungsten work light, oil-brown shadow and a cold blue strip of daylight at the door"

COLD = [
 ("A0_SH01", None, "night_crash_site",
  "a stretch of closed night highway seen from high above, three service vehicles standing with blue beacons slowly turning, cones set in a line across one lane, the light sweeping over wet asphalt",
  "EWS","high","push_in","night",True,False,
  "в час двадцать ночи на сто девятом километре стоят три машины с включёнными маячками."),
 ("A0_SH02", None, "night_crash_site",
  "a steel guard rail torn open and bent outward above a grass ditch, deep fresh gouges cut through the turf below it, beacon light pulsing across the twisted metal",
  "WS","low","pan_right","night",True,False,
  "отбойник разорван на четыре метра, и в траве за ним видны глубокие свежие борозды."),
 ("A0_SH03", "VIK_OLD", "night_crash_site",
  "Viktor standing just behind a strip of tape at the edge of the closed lane, a padded jacket pulled on straight over a house vest, his hands hanging empty at his sides while he looks down the embankment",
  "MS","eye","static","night",False,False,
  "ты приехал сюда через сорок минут после звонка, в куртке поверх домашней майки."),
 ("A0_SH04", "VIK_OLD", "night_crash_site",
  "Viktor's face lit from below by turning blue light, his jaw set hard, his eyes moving once to the left and stopping there",
  "CU","low","push_in","night",False,False,
  "тебе сорок пять лет, и ты уже точно знаешь, что именно увидишь там внизу."),
 ("A0_SH05", None, "night_crash_site",
  "a car door mirror folded back on its arm with a long crack running across the glass, a hardened bead of clear adhesive standing along the crack, wet grass pressed against the housing",
  "INSERT","top","static","night",True,True,
  "серебристая машина лежит на боку, и левое зеркало на ней подклеено прозрачным клеем."),
 ("A0_SH06", "VIK_OLD", "night_crash_site",
  "Viktor gripping the plastic tape in both fists and leaning slowly forward over it, his shoulders rising with a breath he is holding",
  "MCU","dutch","static","night",False,False,
  "этот клей ты выдавливал сам, полтора месяца назад, у себя на площадке."),
 ("A0_SH07", None, "night_crash_site",
  "a silver saloon car lying on its side at the bottom of the embankment with its roof turned towards the road, flattened grass sweeping in a long arc behind it",
  "WS","high","tilt_down","night",True,False,
  "ты продал её пятого числа молодой женщине, её мужу и их четырёхлетней дочке."),
 ("A0_SH08", "OBJ:brakeline", None,
  "a torch beam falling across the underside of a car floor pan",
  "INSERT","low","push_in","night",True,True,
  "под днищем у неё насквозь гнилые тормозные трубки, аккуратно замазанные серым антигравием."),
 ("A0_SH09", "VIK_OLD", "night_crash_site",
  "Viktor closing his eyes for two long seconds and opening them again, his mouth pressed into a flat line while blue light crosses his face",
  "CU","eye","static","night",False,True,
  "ты знал про них, когда подписывал бумаги, и всё равно назвал свою цену."),
 ("A0_SH10", "VIK_OLD", "night_crash_site",
  "Viktor from directly behind at the tape line with his shoulders square, the lit wreck small in the ditch far beyond him",
  "BACK","eye","pull_out","night",False,False,
  "ты стоишь за лентой и не говоришь никому из них ни одного слова."),
 ("A0_SH11", "OBJ:backpack", None,
  "wet flattened grass caught in a low torch beam",
  "INSERT","top","push_in","night",True,True,
  "в пятнадцати метрах от машины в мокрой траве лежит жёлтый детский рюкзак."),
 ("A0_SH12", "VIK_OLD", "night_crash_site",
  "Viktor turning his face away from the ditch and lowering his eyes to the asphalt just in front of his boots",
  "CU","low","static","night",False,False,
  "девочке четыре года, и ехала она сзади, справа, прямо за спиной матери."),
 ("A0_SH13", "VIK_OLD", "night_crash_site",
  "Viktor walking back along the closed lane towards a parked car, passing between two cones with his hands pushed deep into his jacket pockets",
  "MS","high","track","night",False,False,
  "ты разворачиваешься и идёшь к своей машине, потому что стоять здесь больше незачем."),
 ("A0_SH14", "VIK_OLD", "night_crash_site",
  "Viktor sitting behind the wheel of his own car with the engine off, both hands resting on the rim, beacon light still turning beyond the windscreen",
  "MCU","eye","push_in","night",False,False,
  "сейчас я отмотаю двадцать восемь лет назад, к первой цифре, которую я открутил."),
 ("A0_SH15", None, "night_crash_site",
  "the emptied closed lane seen low from the road surface, cones receding, beacon light fading behind, the broken centre line running away into the dark",
  "WS","eye","pull_out","night",True,False,
  "останься со мной до конца, и подпишись, если хочешь узнать, чем это кончилось."),
 ("A0_SH16", "OBJ:odometer", None,
  "a work lamp throwing a hard circle of light onto a scarred bench top",
  "ECU","eye","push_in","interior",True,False,
  "всё это начинается с шести белых цифр на чёрных барабанах и одной отвёртки."),
 ("A0_SH17", None, "garage_row",
  "a long row of private garage boxes at first light with one door standing open and warm light inside it, mist lying over the cracked asphalt between the rows",
  "EWS","high","pan_left","dawn",True,False,
  "тебе семнадцать, и ты живёшь в доме, за которым стоят сорок два гаража."),
 ("A0_SH18", "VIK_TEEN", "garage_row",
  "Viktor washing a stranger's car outside an open garage box, a plastic bucket at his feet, a soaked rag gripped in both hands, sleeves shoved up over reddened forearms",
  "WS","eye","static","day",False,False,
  "отец таксует по ночам, а ты моешь его машину каждое утро перед школой."),
 ("A0_SH19", "VIK_TEEN", "garage_row",
  "Viktor straightening up from a wet bonnet and wiping both palms down his thighs, faint steam rising off the bucket beside him",
  "MCU","low","static","day",False,False,
  "за чужую машину сосед по боксу даёт тебе столько, сколько ты у него попросишь."),
 ("A0_SH20", "VIK_TEEN", "garage_row",
  "Viktor's face turned down towards coins and folded notes lying in his open palm, one corner of his mouth twitching up",
  "CU","eye","push_in","day",False,False,
  "ты просишь мало, потому что ещё не знаешь, сколько стоит чужое спокойствие."),
 ("A0_SH21", "OBJ:barsetka", None,
  "a bent nail driven into a whitewashed garage wall",
  "INSERT","eye","static","interior",True,False,
  "отцовская барсетка висит на гвозде, и ты меряешь её, когда его нет."),
 ("A0_SH22", None, "garage_row",
  "the open doorway of a garage box at dusk with a bare bulb burning inside above an engine on a stand, tools laid out on a folded blanket",
  "WS","low","push_in","dusk",True,False,
  "а в четырнадцатом боксе сидит человек, который через месяц научит тебя всему."),
]

GARAGE = [
 ("A1_SH01", None, "garage_row",
  "the inside of a garage box with the steel door rolled up to waist height, a low bright strip of daylight cutting across the oily floor, an engine on a wooden stand and a radio on a shelf",
  "WS","low","static","day",True,False,
  "в четырнадцатом боксе пахнет соляркой, куревом и растворителем, и там всегда бормочет радио."),
 ("A1_SH02", "GENA_BASE", "garage_row",
  "Gena leaning over an open bonnet with the unlit cigarette behind his ear, both forearms down in the engine bay, turning a spanner in short quick strokes",
  "MS","eye","static","day",False,False,
  "хозяина бокса зовут Гена, ему сорок шесть, и он торгует машинами двадцать лет."),
 ("A1_SH03", ("VIK_TEEN","GENA_BASE"), "garage_row",
  "Viktor stands just inside the doorway with a wet bucket still hanging from one hand while Gena straightens up from the engine and turns his head towards him",
  "MCU","eye","static","day",False,False,
  "он подзывает тебя внутрь, потому что ему нужен кто-то с очень тонкими пальцами."),
 ("A1_SH04", "GENA_BASE", "garage_row",
  "Gena tipping his head back as he talks, one eye narrowed as if against smoke, the cigarette still unlit behind his ear, the flat cap shoved further back on his skull",
  "CU","low","static","day",False,False,
  "Гена говорит, что руки у тебя правильные, а голова пока совершенно пустая."),
 ("A1_SH05", "OBJ:cluster", None,
  "a folded newspaper spread over a workbench under a hooked lamp",
  "INSERT","top","static","interior",True,False,
  "он вынимает приборную панель за десять минут и кладёт её на газету."),
 ("A1_SH06", ("VIK_TEEN","GENA_BASE"), "garage_row",
  "Viktor crouches beside the open driver's door with his knees on a folded sack while Gena sits sideways on the sill above him and points down into the dashboard cavity",
  "WS","eye","static","day",False,False,
  "внутри торчит серый тросик, и Гена пальцем показывает тебе, куда именно он идёт."),
 ("A1_SH07", "GENA_BASE", "garage_row",
  "Gena holding the instrument cluster face-down on his knee and freeing the cable collar with two fingers, the brim of his cap catching the lamp",
  "MS","low","static","day",False,False,
  "двести двадцать тысяч на этих барабанах, говорит он, вообще никому и никогда не нужны."),
 ("A1_SH08", "OBJ:driver", None,
  "a bare hand closing around a taped handle lying on a bench",
  "ECU","eye","push_in","interior",True,False,
  "он даёт тебе отвёртку с ручкой, обмотанной синей изолентой, и отходит в сторону."),
 ("A1_SH09", "VIK_TEEN", "garage_row",
  "Viktor sitting on an upturned crate with the instrument cluster across his knees, the tip of his tongue caught between his teeth, turning the screwdriver a quarter turn at a time",
  "MCU","eye","static","day",False,False,
  "ты крутишь по четверти оборота и слушаешь, как барабаны внутри сухо щёлкают."),
 ("A1_SH10", "OBJ:odometer", None,
  "a lamp burning low over a bench with a hand withdrawing from the edge of the frame",
  "INSERT","eye","push_in","interior",True,True,
  "двести двадцать тысяч превращаются в восемьдесят девять тысяч ровно за одиннадцать минут."),
 ("A1_SH11", "VIK_TEEN", "garage_row",
  "Viktor lifting his face from the cluster with his eyes very still and his mouth flat, lamp light running along one cheek",
  "CU","low","static","day",False,True,
  "ты ждёшь, что внутри тебя что-то дрогнет, но внутри вообще ничего не происходит."),
 ("A1_SH12", None, "garage_row",
  "a garage bay seen from above with the opened instrument cluster lying on newspaper, a crate, a bucket and an open toolbox arranged around a pool of lamp light",
  "WS","high","static","day",True,False,
  "Гена ставит панель обратно и заводит машину, только чтобы проверить, как ходит стрелка."),
 ("A1_SH13", ("GENA_BASE","VIK_TEEN"), "garage_row",
  "Gena counts notes off a folded roll with his thumb into Viktor's flat outstretched hand, Viktor holding his fingers pressed together to take them",
  "MS","eye","static","day",False,False,
  "две тысячи, говорит он, и это ровно за одиннадцать минут твоей работы."),
 ("A1_SH14", "GENA_BASE", "garage_row",
  "Gena's face close to camera with the unlit cigarette shifting as he speaks, one eyebrow raised, entirely calm about it",
  "CU","eye","static","day",False,True,
  "человек покупает не машину, говорит Гена, человек всегда покупает только собственное спокойствие."),
 ("A1_SH15", "VIK_TEEN", "garage_row",
  "Viktor standing with the notes still lying flat on his open palm, looking down at them instead of folding them away",
  "MCU","eye","push_in","day",False,False,
  "за целый месяц мойки ты получаешь меньше, чем сейчас держишь в одной руке."),
 ("A1_SH16", None, "garage_row",
  "the garage rows from high above at dusk, one lit doorway among forty dark ones, wet roofs after rain and housing blocks standing beyond the fence",
  "EWS","high","pan_right","dusk",True,False,
  "ты выходишь из бокса в семь вечера, и вокруг ничего вообще не изменилось."),
 ("A1_SH17", "OBJ:keys", None,
  "a scarred wooden bench top under a single hanging bulb",
  "INSERT","top","static","interior",True,False,
  "на гвозде у Гены висит сорок таких ключей, и каждый из них чего-то стоит."),
 ("A1_SH18", "VIK_TEEN", "garage_row",
  "Viktor walking home down the garage row with both hands in his jacket pockets, kicking a bottle cap ahead of himself along the cracked asphalt",
  "MS","eye","track","dusk",False,False,
  "ты идёшь домой и всю дорогу пересчитываешь в уме то, что уже посчитал."),
 ("A1_SH19", "VIK_TEEN", "garage_row",
  "Viktor stopping under a yard lamp and his eyes unfocused on the empty air in front of him, his breath showing faintly in the cold",
  "CU","eye","static","dusk",False,False,
  "в голове застревает одна очень простая мысль: это можно делать каждый день."),
 ("A1_SH20", None, "flat_kitchen",
  "a small kitchen at night with the pendant lamp lit over an oilcloth table, two plates set out and a kettle just beginning to steam on the stove",
  "WS","eye","static","night",True,False,
  "дома отец спит перед сменой, а на столе стоит его давно остывший ужин."),
 ("A1_SH21", "VIK_TEEN", "flat_kitchen",
  "Viktor easing the kitchen door shut behind himself and sliding folded notes under a sugar tin while still standing",
  "MS","eye","static","night",False,False,
  "ты кладёшь половину под жестянку с сахаром и ничего ему не объясняешь."),
 ("A1_SH22", "VIK_TEEN", "flat_kitchen",
  "Viktor standing over the table with his eyes fixed on the tin, chewing the inside of his cheek",
  "CU","low","push_in","night",False,False,
  "он не спросит откуда, потому что за двадцать лет привык ничего не спрашивать."),
 ("A1_SH23", "OBJ:barsetka", None,
  "the back of a kitchen chair with a work jacket hung over it",
  "ECU","low","push_in","night",True,False,
  "отцовская барсетка лежит на стуле, и утром ты забираешь её с собой."),
 ("A1_SH24", "VIK_TEEN", "garage_row",
  "Viktor arriving at the garage row before sunrise with the leather pouch on his wrist, waiting beside the closed door of one box",
  "MS","eye","static","dawn",False,False,
  "утром ты приходишь к боксу раньше Гены и ждёшь его прямо у ворот."),
 ("A1_SH25", None, "garage_row",
  "the closed steel door of a garage box seen from ground level at dawn, frost along its bottom edge and a padlock hanging open on the hasp",
  "WS","low","tilt_up","dawn",True,False,
  "замок висит открытым, и это значит, что он уже внутри и работает."),
 ("A1_SH26", "VIK_TEEN", "garage_row",
  "Viktor hauling the garage door up with both hands, warm light spilling out across his face and chest",
  "MCU","eye","static","dawn",False,False,
  "ты поднимаешь ворота, и в семнадцать лет у тебя уже есть ремесло."),
 ("A1_SH27", None, "garage_row",
  "the inside face of a garage door with columns of six-figure numbers chalked onto the steel, several of them crossed out, chalk dust on the ledge below",
  "ECU","eye","pan_left","day",True,False,
  "на воротах изнутри мелом написаны цифры, и ты быстро учишься их читать."),
 ("A1_SH28", None, "garage_row",
  "an open garage row seen down its length in flat daylight, cars parked nose-in at every third box and a hose snaking across the asphalt",
  "WS","eye","pull_out","day",True,False,
  "через полгода ты сможешь сделать это быстрее Гены и заметно аккуратнее его."),
]

if __name__ == "__main__":
    seed_act("cold_open", P0, COLD)
    seed_act("garage",    P1, GARAGE)
