# -*- coding: utf-8 -*-
"""fortune batch D: act09_moon + act10_death."""
from _fortune_engine import seed_act

PAL_MOON="paranoid moon-neon palette, cold cyan and sickly green glow, deep blue shadow, uneasy flicker"
A9=[
 ("F9_SH01","ZARA_YOUNG","zara_apartment","an aging woman with grey at her temples sitting awake at night surrounded by protective charms, cold cyan neon bleed","MCU","eye","push_in","night",False,False,
  "одиночество делает тебя суеверной, как твои самые жалкие клиенты, и ты сама теперь живёшь в приметах."),
 ("F9_SH02","ZARA_YOUNG","kitchen_charms","the aging woman laying fresh salt lines along a windowsill at night, anxious, charms multiplying around her","MS","eye","static","night",False,False,
  "ты сыплешь соль на подоконники, не наступаешь на трещины, плюёшь через плечо, и сама в это веришь."),
 ("F9_SH03","ZARA_YOUNG","reading_room","close on the woman's haunted eyes watching the lone face-down card as if it could harm her, cyan neon glow","CU","low","push_in","night",False,True,
  "ты боишься своей карты так, что обходишь стол стороной, и накрываешь её платком, чтобы не смотрела."),
 ("F9_SH04",None,"reading_room","extreme close on a worn tarot card lying face-down on velvet, half-covered by a dark cloth, eerie green neon","ECU","top","push_in","night",False,True,
  "на себя не гадают, повторяешь ты, но теперь это не завет матери, а просто страх узнать, чем всё кончится."),
 ("F9_SH05","ZARA_YOUNG","reading_room","the woman giving a thin reading to one of her last few clients, the old confidence gone, jittery, dim neon","MS","eye","static","night",False,False,
  "редкие клиенты ещё заходят, и ты гадаешь им, но теперь сама вслушиваешься в свои слова, а вдруг сбудется."),
 ("F9_SH06","ZARA_YOUNG","reading_room","close on the woman pausing mid-reading, the uncanny chill seizing her again, dread on her face this time","CU","eye","push_in","night",False,True,
  "и когда тот холодок снова находит, ты больше не радуешься ему, ты его боишься, потому что он приносит беду."),
 ("F9_SH07","ZARA_YOUNG","reading_room","a frightened client backing away as the woman blurts an ominous warning she did not mean to say, green neon","OTS","over","static","night",False,False,
  "однажды ты выпаливаешь клиентке, не отпускайте сына на воду, и сама пугаешься, и она уходит в слезах."),
 ("F9_SH08","ZARA_YOUNG","back_alley","the aging woman alone in a sickly-green neon alley at night, pressing her hands to her temples, overwhelmed","WS","high","static","night",True,False,
  "ты больше не понимаешь, дар это, проклятие, или ты просто сходишь с ума в одиночестве, как старая мать."),
 ("F9_SH09","ZARA_YOUNG","zara_apartment","the woman searching old boxes for a photo of her daughter, lonely, charms and cold neon all around","MCU","eye","static","night",False,False,
  "ты роешься в коробках, ищешь фотографии холли, и понимаешь, что не видела дочь живьём уже много лет."),
 ("F9_SH10",None,"zara_apartment","extreme close on an old photograph of a young girl held in an aging ringed hand, cyan neon glow on it","ECU","top","push_in","night",False,True,
  "на снимке холли совсем маленькая, среди свечей, и ты не помнишь, когда в последний раз слышала её голос."),
 ("F9_SH11","ZARA_YOUNG","zara_apartment","the woman dialing a phone with trembling hope late at night, then lowering it as it rings out, dim neon","CU","eye","push_in","night",False,False,
  "ты набираешь её номер, и слушаешь гудки, и кладёшь трубку до того, как включится автоответчик, каждый раз."),
 ("F9_SH12",None,"street_night","a cold cyan-green neon street at night, mostly dark signs, a lone bright new psychic sign down the block","WS","eye","pan_right","night",True,False,
  "в конце улицы зажигается новая яркая вывеска, молодая гадалка, и твои последние клиенты уходят к ней."),
 ("F9_SH13","ZARA_YOUNG","salon_dying","the woman standing in her dimming salon watching her own neon flicker, the new rival's glow brighter outside","MS","low","static","night",False,False,
  "ты смотришь на её сияющую ладонь в окне, и узнаёшь в ней себя молодую, и понимаешь, что колесо повернулось."),
 ("F9_SH14","ZARA_YOUNG","reading_room","close on the aging woman's face, equal parts envy and warning toward the unseen young rival, cold neon","CU","eye","push_in","night",False,False,
  "тебе хочется крикнуть ей через улицу, девочка, беги, пока не поздно, но ты молчишь, ведь когда-то не убежала сама."),
 ("F9_SH15","ZARA_YOUNG","zara_apartment","the woman covering a mirror with a cloth at night, avoiding her own reflection, charms and neon around","MCU","eye","static","night",False,False,
  "ты завешиваешь зеркала, как мать завешивала, и не смотришь ни в стекло, ни в шар, ни в свою накрытую карту."),
 ("F9_SH16","ZARA_YOUNG","reading_room","the woman sitting in the dark salon listening to rain, the moon card face-up in an abandoned spread, cyan neon","CU","top","static","night",False,True,
  "однажды ночью ты тасуешь карты от тоски, и сверху ложится луна, аркан обмана, страха и долгой тёмной воды."),
 ("F9_SH17",None,"reading_room","extreme close on the moon tarot card face-up on velvet, two towers and a dark path, sickly green neon shimmer","INSERT","top","push_in","night",False,True,
  "луна, говоришь ты вслух, карта тех, кто всю жизнь шёл в темноте, принимая обман за свет, и ты усмехаешься горько."),
 ("F9_SH18","ZARA_YOUNG","kitchen_charms","the woman eating alone at the charm-hung kitchen table at midnight, the chair across from her empty, dim neon","MS","high","static","night",False,False,
  "ты ужинаешь одна под оберегами, и место сэма пусто, и место холли пусто, и обереги не вернут ни того, ни другого."),
 ("F9_SH19","ZARA_YOUNG","zara_apartment","close on the aging woman's sleepless face lit by cold neon through the blinds, haunted by the unread card","CU","low","push_in","night",False,False,
  "и каждую ночь тебя точит один вопрос, что лежит на твоей карте, и каждую ночь ты не находишь смелости узнать."),
 ("F9_SH20",None,"parking_lot_rain","a half-dead salon neon sign reflected broken in a rainy lot at night, the rival's bright sign glowing far behind","WS","high","static","night",True,True,
  "твоя ладонь с глазом гаснет буква за буквой, и в лужах теперь дрожит чужой, молодой, чужой яркий свет."),
 ("F9_SH21","ZARA_YOUNG","reading_room","the woman reaching toward the covered face-down card, fingertips brushing the cloth, then stopping, cyan neon","ECU","top","push_in","night",False,True,
  "ты снимаешь платок с карты, и кладёшь пальцы на рубашку, и сердце колотится, и ты опять, опять не решаешься."),
 ("F9_SH22","ZARA_YOUNG","reading_room","close on the woman's frightened resigned face, recovering the card with the cloth again, alone in cold neon","CU","eye","static","night",False,False,
  "ещё не время, шепчешь ты себе, как будто карта сама скажет тебе, когда придёт пора её перевернуть."),
 ("F9_SH23",None,"street_night","a desolate cyan-green neon street late at night, rain falling, a single dim flickering psychic sign, wet asphalt","WS","eye","push_in","night",True,False,
  "годы идут под мигающим неоном, и ты ждёшь не клиентов уже, а просто хоть какого-нибудь знака, хоть звонка."),
 ("F9_SH24","ZARA_YOUNG","zara_apartment","the aging woman asleep in a chair by the window, the phone in her lap, cold neon washing over her, alone","MCU","high","push_in","night",False,False,
  "ты засыпаешь в кресле с телефоном в руках, и тебе снятся свечи, и мамин голос, на себя смотреть страшнее всего."),
]

PAL_DEATH="cold mourning neon palette, desaturated blue and grey with a single cold white neon, candle-cold shadow"
A10=[
 ("F10_SH01","ZARA_OLD","zara_apartment","an old woman jolting awake in a chair at night, hand to her chest, the forearm chill seizing her hard, cold neon","MCU","low","push_in","night",False,True,
  "однажды среди ночи ты просыпаешься от того, что холодок ножом проходит по рукам, сильнее, чем когда-либо в жизни."),
 ("F10_SH02","ZARA_OLD","zara_apartment","close on the old woman's stricken face in the dark, certain something terrible has just happened, blue neon","CU","eye","push_in","night",False,True,
  "и ты точно знаешь, всем телом знаешь, что где-то только что случилось непоправимое, и оно касается тебя."),
 ("F10_SH03","ZARA_OLD","zara_apartment","the old woman sitting rigid by the phone before dawn, waiting for a call she dreads, charms dim around her","MS","eye","static","night",False,False,
  "ты сидишь у телефона до рассвета, и не гадаешь, и не молишься, ты просто ждёшь, и тебе очень страшно."),
 ("F10_SH04",None,"zara_apartment","extreme close on a telephone ringing in the grey dawn light, an aging hand frozen above it, cold neon fading","ECU","top","push_in","dawn",False,True,
  "телефон звонит на рассвете, и ты снимаешь трубку, и слышишь голос холли, первый за много лет, и он чужой."),
 ("F10_SH05","ZARA_OLD","zara_apartment","the old woman gripping the phone, face collapsing as she hears the news, dawn light and dead neon around","MS","eye","static","dawn",False,False,
  "она говорит сквозь слёзы, мама, папа умер этой ночью, сердце, и ты понимаешь, что холодок был о нём."),
 ("F10_SH06","ZARA_OLD","zara_apartment","close on the old woman's shattered face, the phone slipping, learning her estranged husband died the very hour she woke","CU","low","push_in","dawn",False,True,
  "сэм умер ровно тогда, когда тебя разбудил холодок, и ты так и не знаешь, дар это был, или просто любящее сердце."),
 ("F10_SH07",None,"cemetery_day","an overcast cemetery, a modest fresh grave with flowers, a small gathering of mourners at a distance, no neon, grey","EWS","high","static","day",True,True,
  "ты приезжаешь на похороны сэма, и стоишь в стороне, как когда-то у могилы вдовы, чужая на собственном горе."),
 ("F10_SH08","DAUGHTER","cemetery_day","a grown daughter in mourning black standing rigid at a graveside, refusing to look at an approaching old woman","MS","eye","static","day",False,False,
  "у могилы стоит холли, совсем взрослая, и ты идёшь к ней через всё кладбище, и ноги у тебя подкашиваются."),
 ("F10_SH09","ZARA_OLD","cemetery_day","the old woman reaching a trembling hand toward her grown daughter at the grave, the daughter not turning, grey light","OTS","over","static","day",False,False,
  "ты касаешься её рукава, и говоришь, холли, девочка моя, и она отвечает, не сейчас, мама, и не оборачивается."),
 ("F10_SH10","DAUGHTER","cemetery_day","close on the grown daughter's cold grief-locked face, years of distance in it, refusing reconciliation, grey light","CU","eye","push_in","day",False,False,
  "в её лице нет ненависти, есть кое-что хуже, усталое равнодушие, как когда-то у вдовы, уходящей в дождь."),
 ("F10_SH11","ZARA_OLD","cemetery_day","the old woman standing alone as mourners disperse and her daughter walks away, left at the grave, grey sky","WS","high","static","day",False,False,
  "люди расходятся, холли уезжает, и ты остаёшься одна у свежей земли, как осталась одна вообще со всем на свете."),
 ("F10_SH12","ZARA_OLD","cemetery_day","close on the old woman's dry stony face at the grave, the moonstone ring on her clasped hands, unable to weep","CU","low","push_in","day",False,True,
  "ты не плачешь, ты разучилась, ты только крутишь на пальце мамино кольцо, и шепчешь сэму, прости, я всё проиграла."),
 ("F10_SH13",None,"cemetery_day","extreme close on a moonstone ring turning on an old finger above fresh grave soil, grey daylight","ECU","top","static","day",False,True,
  "кольцо с лунным камнем холодит палец, единственное, что осталось от матери, от ремесла, от всей твоей жизни."),
 ("F10_SH14","ZARA_OLD","street_night","the old woman walking home alone through a dim neon street at night after the funeral, smaller than ever","WS","eye","track","night",True,False,
  "ты возвращаешься в город под неон, и впервые он кажется тебе не домом, а холодной чужой вывеской над пустотой."),
 ("F10_SH15","ZARA_OLD","reading_room","the old woman entering the dark salon and sitting before the lone face-down card, the death card face-up beside it","MCU","eye","push_in","night",False,True,
  "ты приходишь в салон, и тасуешь колоду в темноте, и сверху ложится смерть, тринадцатый аркан, и ты не вздрагиваешь."),
 ("F10_SH16",None,"reading_room","extreme close on the death tarot card face-up on velvet beside the lone face-down card, cold neon shimmer","INSERT","top","push_in","night",False,True,
  "смерть, говоришь ты, карта не конца, а перемены, только менять в твоей жизни уже почти нечего, и некому."),
 ("F10_SH17","ZARA_OLD","reading_room","the old woman's hand hovering over her own face-down card, closer than ever, the death card beside it, cold neon","ECU","top","push_in","night",False,True,
  "и ты впервые думаешь, может, теперь и пора, может, мне уже нечего терять, и можно наконец её перевернуть."),
 ("F10_SH18","ZARA_OLD","reading_room","the old woman pulling back from the card one last time, saving it, a strange resolve forming, cold neon","MCU","low","static","night",False,True,
  "но ты убираешь руку, не от страха теперь, а потому что решаешь, эту карту я переверну в самом конце, и не раньше."),
 ("F10_SH19","ZARA_OLD","zara_apartment","the old woman taking down the charms and salt one by one in the grey dawn, done with superstition, dead neon","MS","eye","static","dawn",False,False,
  "ты снимаешь обереги со стен, всё до единого, ссыпаешь соль с подоконников, они не спасли никого, и тебя не спасут."),
 ("F10_SH20","ZARA_OLD","zara_apartment","close on the old woman's face, hollow and clear-eyed for the first time, no charms left around her, grey light","CU","eye","push_in","dawn",False,False,
  "впервые в жизни ты остаёшься без примет, без оберегов, без надежды, наедине с тем, что натворила за все эти годы."),
 ("F10_SH21",None,"widow_house","extreme close on a faded newspaper clipping of the drowned widow, kept all these years, an old hand smoothing it","ECU","top","push_in","day",False,True,
  "ты достаёшь старую вырезку про маргарет, что хранила все эти годы, и понимаешь, что хранила её, как приговор."),
 ("F10_SH22","ZARA_OLD","reading_room","the old woman sitting very still in the empty dark salon, the lone face-down card before her, deciding to wait","MCU","high","static","night",False,False,
  "ты решаешь дожить до конца честно, без чужих денег, без снятия порчи, и узнать свою карту последней, не первой."),
 ("F10_SH23",None,"strip_mall_night","the salon's neon hand-and-eye now mostly dark, only a few letters weakly glowing, the cold parking lot empty","WS","low","static","night",True,True,
  "над тобой едва теплится твоя ладонь с глазом, почти совсем погасшая, и стрелка часов идёт к самой долгой ночи."),
 ("F10_SH24","ZARA_OLD","reading_room","close on the old woman's resolved quiet face in the dying neon, ready to live out the end and turn the card last","CU","low","push_in","night",False,False,
  "и ты ждёшь свою последнюю ночь, ту самую, с которой я начала тебе этот рассказ, помнишь, под дождём и неоном."),
]

seed_act("act09_moon",  PAL_MOON,  A9)
seed_act("act10_death", PAL_DEATH, A10)
