# -*- coding: utf-8 -*-
"""divorce act A6 aftermath (однушка, передача сына, бледнеющая полоса). PYTHONIOENCODING=utf-8 python scripts/_seed_divorce_A6.py"""
from _divorce_engine import seed_act
PAL="hollow muted domestic palette, desaturated grey-blue and washed beige, flat tired light, long empty shadows"
S=[
 ("A6_SH01",None,"rented_flat","a wide view of a bare rented one-room flat with one chair, a folding table and half-unpacked boxes","WS","eye","static","morning",True,False,
  "теперь твой дом — съёмная однушка с одним стулом и коробками, которые ты так и не разобрал."),
 ("A6_SH02","MUZH_MAIN","rented_flat","a medium close-up of the man waking alone on a narrow single bed in the grey morning","MCU","eye","static","morning",False,False,
  "ты просыпаешься один на узкой кровати, и первые секунды по привычке ищешь рукой её половину."),
 ("A6_SH03","MUZH_MAIN","rented_flat","an extreme close-up of the man's left hand, the pale band where the ring was, his thumb rubbing the bare spot","ECU","eye","static","morning",False,True,
  "на пальце осталась бледная полоса от кольца, и ты всё ещё машинально трёшь это голое место большим пальцем."),
 ("A6_SH04","MUZH_MAIN","rented_flat","a medium shot of the man making coffee in a single mug at a small kitchenette counter","MS","eye","static","morning",False,False,
  "ты варишь кофе в одной кружке, потому что вторую сюда покупать просто незачем."),
 ("A6_SH05",None,"rented_flat","a macro insert of a single mug standing alone on a bare kitchenette counter, an empty space beside it","INSERT","top","static","morning",True,False,
  "на голой столешнице стоит одна твоя чашка, и место рядом, где могла бы стоять вторая, пустует."),
 ("A6_SH06",None,"playground_handoff","a wide view of a residential courtyard playground with a swing set and a slide, the weekend exchange spot","WS","eye","static","day",True,False,
  "по субботам ты приезжаешь во двор с детской площадкой, где теперь забираешь сына на выходные."),
 ("A6_SH07","MUZH_MAIN","playground_handoff","a medium shot of the man waiting by the swings, scanning the courtyard for a familiar backpack","MS","eye","static","day",False,False,
  "ты стоишь у качелей и ждёшь, высматривая знакомый рюкзак-динозавр в толпе чужих родителей."),
 ("A6_SH08","SYN_CHILD","playground_handoff","a medium close-up of the fair-haired boy running up, the dinosaur backpack bouncing on his shoulders","MCU","eye","static","day",False,False,
  "сын выбегает к тебе, рюкзак подпрыгивает на спине, и на пару секунд всё снова становится правильным."),
 ("A6_SH09","MUZH_MAIN","playground_handoff","a close-up of the man hugging his son a beat too long, eyes shut","CU","eye","static","day",False,False,
  "ты обнимаешь его на секунду дольше, чем нужно, и стараешься, чтобы он не заметил, как ты соскучился."),
 ("A6_SH10","SYN_CHILD","car_curb","a medium shot of the boy buckled in the back seat of a car, the dinosaur backpack beside him","MS","eye","static","day",False,False,
  "в машине он сидит сзади, между двумя домами, и возит этот рюкзак из одной квартиры в другую."),
 ("A6_SH11",None,"car_curb","a macro insert of the dinosaur backpack open on a car back seat, two toothbrushes packed inside for two homes","INSERT","top","static","day",True,False,
  "на заднем сиденье лежит рюкзак-динозавр, собранный сразу на два дома, с двумя зубными щётками внутри."),
 ("A6_SH12","SYN_CHILD","car_curb","a close-up of the boy's serious trusting face as he asks a quiet question from the back seat","CU","eye","static","day",False,False,
  "сын спрашивает, какой дом теперь настоящий, твой или мамин, и смотрит на тебя серьёзно и доверчиво."),
 ("A6_SH13","MUZH_MAIN","car_curb","a medium close-up of the man at the wheel with no answer, looking into the rear mirror","MCU","eye","static","day",False,False,
  "ты молчишь, потому что у тебя нет честного ответа, который не ранил бы его ещё сильнее."),
 ("A6_SH14",None,"rented_flat","a wide night view of the bare rented flat, empty and echoing after the boy has gone back","WS","eye","static","night",True,False,
  "вечером, когда ты отвозишь его обратно, однушка встречает тебя той же гулкой тишиной."),
 ("A6_SH15","MUZH_MAIN","rented_flat","a medium close-up of the man scrolling old photographs on his phone in the dark, the screen lighting his face","MCU","eye","static","night",False,False,
  "ты листаешь в телефоне старые фотографии, где вы втроём ещё смеётесь и сидите близко."),
 ("A6_SH16",None,"rented_flat","a macro insert of a phone screen showing an old happy family photo of an embrace","INSERT","eye","static","night",True,False,
  "на экране светится старый снимок, где вы стоите обнявшись, и ты не помнишь, кто вас тогда снимал."),
 ("A6_SH17","MUZH_MAIN","rented_flat","a close-up of the man's face in the phone glow, the pale ring band catching the light","CU","eye","static","night",False,False,
  "ты смотришь на это фото в темноте, и бледная полоса на пальце светится в свете экрана."),
 ("A6_SH18","ZHENA_BASE","playground_handoff","a medium shot of the woman in the courtyard laughing lightly, looking easier and freer","MS","eye","static","day",False,False,
  "через несколько недель ты видишь её во дворе, и она смеётся легко, как будто без тебя ей дышится свободнее."),
 ("A6_SH19","MUZH_MAIN","playground_handoff","a close-up of the man watching from a distance, a quiet ache on his face","CU","over","static","day",False,False,
  "ты понимаешь, что ей стало легче, и от этой мысли внутри тянет сильнее, чем от самого развода."),
 ("A6_SH20","MUZH_MAIN","rented_flat","an extreme close-up of the man's left hand, the pale ring band now almost faded into the skin","ECU","eye","static","day",False,True,
  "полоса на пальце постепенно бледнеет и почти сравнивается с кожей, как будто кольца и не было."),
 ("A6_SH21","MUZH_MAIN","rented_flat","a medium close-up of the man sitting quietly in the rented flat, settled into a permanent emptiness","MCU","eye","static","dusk",False,False,
  "проходят месяцы, и ты привыкаешь, что тишина в этой квартире — это теперь просто твоя жизнь."),
 ("A6_SH22","MUZH_MAIN","rented_flat","an extreme wide dusk view of the man sitting small at a folding table with one mug, lit city windows beyond","EWS","eye","static","dusk",False,True,
  "за окном горят чужие тёплые окна, а ты сидишь за раскладным столом с одной чашкой, и впереди выходные без сына."),
]
if __name__=="__main__": seed_act("aftermath", PAL, S, render_mode="static")
