# -*- coding: utf-8 -*-
"""teacher acts: cold_open (2026, 14 shots) + chalk (1975, 30 shots). Both ANIMATED (hook prefix).
Run: PYTHONIOENCODING=utf-8 python scripts/_seed_teacher_A0A1.py"""
from _teacher_engine import seed_act

PAL0="muted march-morning palette of pale grey window light, warm tea-coloured lamplight and thawing snow blue"
COLD=[
("C_SH01","LIDA_OLD","lida_kitchen",
 "a thin upright woman of fifty-eight sitting at a small kitchen table in a shaft of pale morning sun, steam rising from two cups of tea, a school exercise notebook open between them, dust motes drifting in the light",
 "WS","eye","push_in","morning",False,True,
 "март две тысячи двадцать шестого, твоя кухня, за окном тают последние серые сугробы.",
 "steam curling slowly from the tea cups, dust motes drifting through the sunbeam, the woman's shoulders rising with a quiet breath"),
("C_SH02","PUPIL_BASE","lida_kitchen",
 "a small curly-haired schoolboy of ten hunched over an exercise notebook at a kitchen table, tongue pressed in concentration, gripping a pencil in his fist, a bright puffy jacket hung on the chair behind him",
 "MCU","high","static","morning",False,False,
 "напротив тебя сопит чужой десятилетний мальчик и выводит буквы так, будто копает траншею.",
 "the boy's pencil hand moving in short effortful strokes, his brow furrowing, the page trembling slightly under his fist"),
("C_SH03","OBJ:red_pen",None,
 "a woman's aged hand guiding a red ballpoint pen along a line of a child's handwriting in an open exercise notebook",
 "INSERT","top","static","morning",False,False,
 "ты ведёшь красной ручкой по его строчкам, и рука сама находит каждую ошибку за секунду.",
 "the red pen tip sliding along the written line, pausing, underlining one word with two firm strokes"),
("C_SH04","LIDA_OLD","lida_kitchen",
 "a close portrait of the fifty-eight-year-old woman reading a child's notebook through slim glasses, calm grey eyes moving along the lines, silver-streaked chestnut hair pinned back, faint window light on her face",
 "CU","eye","static","morning",False,False,
 "тебе пятьдесят восемь, и таких тетрадей через твои руки прошло больше, чем дней в твоей жизни.",
 "her eyes travelling steadily along the lines, a slight tilt of the head, the light shifting softly on her glasses"),
("C_SH05","PUPIL_BASE","lida_kitchen",
 "over the woman's cardiganed shoulder, the ten-year-old boy erasing a word and blowing rubber crumbs off the notebook page, the kitchen window bright behind him",
 "OTS","over","static","morning",False,False,
 "за этот час его родители платят столько, сколько школа платила тебе за целый день.",
 "the boy blowing eraser crumbs off the page, brushing them away with the side of his hand"),
("C_SH06",None,"lida_kitchen",
 "a handwritten weekly pupil list pinned by a magnet to an old refrigerator door, seven names in a teacher's even hand, a kitchen towel on a hook beside it",
 "INSERT","eye","static","morning",True,False,
 "на холодильнике магнитом прижат список учеников на неделю, семь фамилий, и все чужие.",
 "the paper list stirring faintly in a draught, the magnet holding, light flickering across the fridge enamel"),
("C_SH07","PUPIL_BASE","lida_kitchen",
 "the curly-haired boy lifting his head from the notebook and looking straight up at his tutor with open direct eyes, pencil still in his fist",
 "MCU","low","static","morning",False,False,
 "мальчик вдруг поднимает голову от тетради и смотрит на тебя со взрослой прямотой.",
 "the boy raising his head in one small motion, blinking once, holding a steady open gaze"),
("C_SH08","LIDA_OLD","lida_kitchen",
 "the woman of fifty-eight caught mid-breath, lips slightly parted, the red pen stopped above the page, her eyes gone still",
 "CU","eye","push_in","morning",False,True,
 "а свои дети у вас есть, спрашивает он просто, как спрашивают который час.",
 "her breath catching, the pen hovering motionless above the page, her eyes slowly losing focus"),
("C_SH09","OBJ:medal",None,
 "a thin silver ring with a small amber stone on an aged right hand resting motionless on an open exercise notebook beside a stopped red pen",
 "ECU","top","static","morning",False,False,
 "твои пальцы замирают на красной ручке, и старое серебряное кольцо с янтарём холодит кожу.",
 "the fingers pressing very slightly into the page, the amber catching a point of window light"),
("C_SH10","LIDA_OLD","lida_kitchen",
 "the kitchen seen from behind the seated woman, her straight back and pinned silver-chestnut hair, the boy a soft shape across the table, a tap over the sink catching light",
 "BACK","eye","static","morning",False,False,
 "в кухне становится так тихо, что слышно, как капает вода из крана в мойку.",
 "a single water drop gathering on the tap and falling, the woman's back utterly still"),
("C_SH11","LIDA_OLD","lida_kitchen",
 "the woman looking out through the kitchen window at a school building across the courtyard, bare poplars between, her reflection faint in the glass",
 "MCU","eye","static","morning",False,False,
 "ты смотришь в окно на школу через двор, где тридцать четыре года звенел твой звонок.",
 "her gaze lifting toward the school across the yard, a bus passing as a soft reflection over the glass"),
("C_SH12","OBJ:chalk",None,
 "a short stub of white blackboard chalk lying in the woollen pocket of a dark cardigan, the pocket edge pulled gently open by a thumb",
 "ECU","top","push_in","morning",False,True,
 "в кармане кардигана лежит начатый кусок мела, ты носишь его с собой уже два года.",
 "the thumb easing the pocket open, the chalk stub rolling a few millimetres and settling in the wool"),
("C_SH13","LIDA_OLD","lida_kitchen",
 "the woman of fifty-eight straightening her teacher's back and drawing a slow breath before answering, morning light along her profile",
 "MS","eye","static","morning",False,False,
 "прежде чем ты ответишь мальчику, я расскажу тебе всю твою жизнь с самого начала.",
 "her spine straightening by degrees, a long slow inhale, her chin lifting a little"),
("C_SH14",None,"lida_kitchen",
 "the small kitchen from the doorway, two figures at the sunlit table rendered soft and distant, steam and dust in the light shaft between them",
 "WS","eye","pull_out","morning",True,False,
 "останься со мной до конца, подпишись, эта история займёт сорок минут, а прожита за пятьдесят лет.",
 "the light shaft breathing with drifting dust, steam rising and thinning, the scene slowly widening"),
]

PAL1="warm seventies palette of honey wood, chalk white, deep blackboard green and stove-fire amber"
CHALK=[
("A1_SH01",None,"village_street",
 "a quiet unpaved settlement street on a September morning of nineteen seventy-five, low timber houses with carved window frames, geese by a ditch, long shadows on ruts, a distant grain elevator against a pale sky",
 "EWS","high","pan_right","morning",True,False,
 "тысяча девятьсот семьдесят пятый, посёлок, где всё слышно от одного конца до другого."),
("A1_SH02","MAMA_BASE","village_kitchen",
 "a fifty-year-old seamstress at a treadle sewing machine finishing a small dark school pinafore by lamplight, pins held in her lips, a grey downy shawl over her shoulders",
 "MS","eye","push_in","night",False,False,
 "мама дошивает твою школьную форму за полночь, потому что готовую вам не по карману.",
 "the treadle rocking steadily, fabric feeding under the needle, her hands guiding the small dark dress"),
("A1_SH03","LIDA_KID","village_kitchen",
 "a seven-year-old girl with chestnut braids and big white ribbon bows standing very straight in a new dark pinafore, arms at her sides, lamplight warm on her serious face",
 "MCU","low","static","night",False,True,
 "тебе семь лет, банты накрахмалены, и ты стоишь в новой форме прямо, как струна.",
 "the girl holding herself perfectly still, only her eyes shining and the ribbon bows trembling faintly"),
("A1_SH04","OBJ:medal",None,
 "two white satin ribbon bows freshly ironed lying on dark pressed fabric beside a folded white collar and a small posy of garden asters",
 "INSERT","top","static","night",False,False,
 "на стуле с вечера разложено всё до последней ленточки, чтобы утром ничего не забыть."),
("A1_SH05",None,"village_school_yard",
 "the gravel yard of a single-storey timber village school on the first of September, painted stones along the path, a rowan tree by the gate, morning frost steaming off the grass in thin sun",
 "WS","eye","static","morning",True,False,
 "первое сентября в посёлке пахнет астрами, свежей краской и дымом первых осенних печей."),
("A1_SH06","LIDA_KID","village_school_yard",
 "the seven-year-old girl with braids clutching a bunch of purple asters bigger than her face, peeking over the flowers with wide grey eyes",
 "CU","eye","static","morning",False,True,
 "ты несёшь букет астр размером с себя и видишь над ним только высокое крыльцо школы.",
 "the aster heads nodding as she walks, her eyes appearing and hiding behind the blooms"),
("A1_SH07","TAMARA_BASE","village_school_yard",
 "a stately schoolmistress of fifty-five with a high silver bun and pearl clip earrings standing on worn wooden school steps, a hand bell in her hand, greeting a line of first-graders",
 "MS","low","static","morning",False,False,
 "на крыльце стоит тамара павловна, и звонок в её руке блестит, как маленькое солнце.",
 "the schoolmistress lifting the brass bell and swinging it in small measured arcs, her skirt stirring in the breeze"),
("A1_SH08","OBJ:brass_bell",None,
 "a small brass hand bell with a red ribbon bow swinging mid-ring against a blurred September sky, sunlight flaring off the polished metal",
 "ECU","low","static","morning",False,True,
 "этот звонок ты будешь слышать пятьдесят один год, но пока он звенит только для тебя.",
 "the bell swinging through its arc, the ribbon fluttering, light flashing off the brass with each swing"),
("A1_SH09",None,"classroom_soviet",
 "rows of worn wooden lift-lid desks in a small village classroom, morning sun laying warm stripes across scarred desktops, a tall tiled stove in the corner, geraniums on deep sills",
 "WS","eye","pan_left","morning",True,False,
 "в классе двенадцать парт, и за каждой уже сидит чья-то отглаженная спина."),
("A1_SH10","LIDA_KID","classroom_soviet",
 "the seven-year-old girl seated at a front wooden desk with her hands folded one on the other exactly as taught, braids straight down her back, looking up with total attention",
 "MCU","eye","push_in","morning",False,False,
 "ты садишься за первую парту и складываешь руки так, будто от этого зависит жизнь.",
 "her small hands settling one over the other on the desk lid, her chin lifting attentively"),
("A1_SH11","TAMARA_BASE","classroom_soviet",
 "the silver-haired schoolmistress writing large clean letters on a dark green blackboard, her green suit sleeve dusted faintly white, morning light across the board",
 "MS","eye","static","morning",False,False,
 "тамара павловна пишет на доске первое слово, и мел стучит спокойно, как метроном.",
 "her hand travelling across the board in even strokes, chalk dust drifting from the letters as they appear"),
("A1_SH12","LIDA_KID","classroom_soviet",
 "the girl with braids watching the blackboard with parted lips, window light in her grey eyes, the reflection of white letters faintly in them",
 "CU","eye","static","morning",False,False,
 "ты смотришь, как из-под мела рождаются буквы, и забываешь дышать от такой красоты.",
 "her lips parting slowly, her eyes tracking left to right along the invisible line of letters"),
("A1_SH13","TAMARA_BASE","classroom_soviet",
 "the schoolmistress bending to a front desk and placing a piece of white chalk into a small child's hand, folding the small fingers around it with both her hands",
 "OTS","over","static","morning",False,True,
 "после урока тамара павловна вкладывает тебе в пальцы мел и говорит, напиши своё имя.",
 "her weathered hands closing the child's fingers around the chalk stub, one gentle pat on the small fist"),
("A1_SH14","OBJ:chalk",None,
 "a child's small fingers holding a fresh piece of white chalk, fine white dust already on the fingertips, a dark green blackboard blurred beyond",
 "ECU","eye","push_in","day",False,True,
 "мел сухой и лёгкий, он немного скрипит, и с этого скрипа начинается вся твоя жизнь.",
 "the small fingers adjusting their grip on the chalk, a breath of white dust falling from the tip"),
("A1_SH15","LIDA_KID","classroom_soviet",
 "the seven-year-old girl on tiptoe at the tall blackboard writing large uneven letters, braids swinging, chalk line wobbling but determined",
 "MS","low","static","day",False,True,
 "ты выводишь на доске четыре буквы своего имени, встав на цыпочки до самого верха.",
 "the girl stretching on tiptoe, her arm reaching up, wobbly white letters growing one by one on the green board"),
("A1_SH16",None,"classroom_soviet",
 "a child's large uneven name written in white chalk on a dark green blackboard, afternoon sun striping the board, chalk dust settling in the light",
 "INSERT","eye","static","day",True,False,
 "буквы выходят кривые и огромные, но это первые буквы, которые ты подарила доске."),
("A1_SH17","TAMARA_BASE","classroom_soviet",
 "the silver-haired schoolmistress looking at the child's writing on the board with a restrained warm smile, arms folded, pearl clips catching light",
 "MCU","eye","static","day",False,False,
 "тамара павловна смотрит на твои буквы дольше, чем на чьи-либо ещё в этом классе.",
 "her arms unfolding slowly, a small nod, the restrained smile deepening at the corners"),
("A1_SH18","LIDA_KID","school_corridor",
 "the small girl with braids walking down a long school corridor holding her first notebook against her chest like a treasure, red-brown painted floor shining",
 "WS","eye","track","day",False,False,
 "домой ты несёшь первую тетрадь с первой пятёркой, прижимая её к груди, как птицу.",
 "the girl walking briskly down the corridor, the notebook pressed to her chest, her braids bouncing with each step"),
("A1_SH19","MAMA_BASE","village_kitchen",
 "the seamstress mother at the village kitchen table holding a child's notebook to the lamp, sewing glasses pushed up, her rough finger tracing the red mark of a five",
 "MCU","eye","static","evening",False,False,
 "мама трёт пятёрку пальцем, будто проверяя, настоящая ли, и прячет улыбку в уголках губ.",
 "her fingertip passing over the red mark, the notebook tilting toward the lamp, a smile pressed down at the corners"),
("A1_SH20","LIDA_KID","village_kitchen",
 "the girl of seven kneeling on a stool at the kitchen table, lining up three rag dolls against the samovar and holding a tiny slate board before them",
 "MS","high","static","evening",False,True,
 "вечерами ты сажаешь трёх тряпичных кукол в ряд и учишь их всему, что узнала за день.",
 "the girl straightening a rag doll, tapping the tiny slate with a stick, her lips moving in silent instruction"),
("A1_SH21",None,"village_kitchen",
 "three rag dolls propped in a row on a kitchen bench, a tiny slate board with a chalked letter leaning before them, warm lamplight and the shadow of a child's gesturing arm on the wall",
 "INSERT","eye","static","evening",True,False,
 "куклы слушают лучше всех в посёлке, ни одна ни разу не спросила, можно выйти."),
("A1_SH22","LIDA_KID","village_street",
 "the girl with braids running along the settlement street through falling golden birch leaves, satchel bouncing on her back, geese scattering from a puddle",
 "WS","eye","track","day",False,False,
 "осень тебе теперь измеряется не грибами и картошкой, а прописями и страницами букваря.",
 "the girl running through drifting leaves, her satchel bouncing, geese flapping heavily out of her way"),
("A1_SH23","LIDA_KID","classroom_soviet",
 "the girl standing beside her desk answering, chin up, one hand behind her back and the other raised holding a ruler like a pointer, winter light on frosted windows",
 "MS","eye","static","day",False,False,
 "к зиме ты отвечаешь у доски так, что тамара павловна ставит тебя в пример старшим.",
 "the girl lifting the ruler like a pointer, her chin rising, her weight settling into a firm stance"),
("A1_SH24","OBJ:chalk",None,
 "a wooden chalk box on a blackboard rail holding neat white sticks, one stub worn round shorter than the rest, frost patterns on the window beyond",
 "ECU","eye","static","day",False,False,
 "свой первый кусок мела ты не выбрасываешь, а хранишь в пенале, как драгоценный камень."),
("A1_SH25","TAMARA_BASE","classroom_soviet",
 "the silver-haired schoolmistress by the warm tiled stove after lessons, holding a glass of tea in a metal holder, speaking gently to someone small out of frame",
 "MCU","eye","static","evening",False,False,
 "однажды после уроков тамара павловна говорит тебе, из тебя выйдет учитель, лидочка.",
 "steam rising from the tea glass, her head inclining kindly, firelight from the stove door playing on her suit"),
("A1_SH26","LIDA_KID","classroom_soviet",
 "the seven-year-old girl looking up wide-eyed by the stove, clutching her satchel strap with both mittened hands, cheeks red from the warmth",
 "CU","low","static","evening",False,False,
 "ты не отвечаешь, но уносишь эти слова домой под пальто, ближе к самому сердцу.",
 "her mittened hands tightening on the strap, her red cheeks lifting with a held-back smile"),
("A1_SH27",None,"village_street",
 "the settlement street at blue winter dusk, snow squeaking paths between drifts, warm yellow windows lighting one by one, chimney smoke standing straight in the frost",
 "EWS","eye","static","evening",True,False,
 "зимой посёлок засыпает в шесть, и только в вашем окне ещё горит жёлтый свет."),
("A1_SH28","LIDA_KID","village_kitchen",
 "the girl asleep at the kitchen table over an open primer, cheek on her arm, the lamp low, her mother's grey shawl laid over her small shoulders",
 "MS","high","push_in","night",False,True,
 "ты засыпаешь над букварём, и мама укрывает тебя платком, не отрывая от книги.",
 "the lamp flame breathing softly, the shawl settling over the child's shoulders, her sleeping face at peace"),
("A1_SH29","OBJ:chalk",None,
 "a small piece of white chalk resting in an open pencil case beside two pencils and a pen nib, lamplight warm on the worn tin box",
 "INSERT","top","push_in","night",False,True,
 "в пенале рядом с карандашами лежит мел, и во сне ты снова пишешь своё имя на доске.",
 "lamplight flickering gently over the tin pencil case, the chalk stub luminous against the dark lining"),
("A1_SH30",None,"village_school_yard",
 "the timber village school under deep snow at night, one window faintly lit, the rowan tree bare and black against a violet sky full of low stars",
 "WS","eye","pull_out","night",True,False,
 "тебе семь лет, и ты уже точно знаешь, кем будешь, а это знает не каждый взрослый."),
]

seed_act("cold_open",PAL0,COLD,render_mode="animated")
seed_act("chalk",PAL1,CHALK,render_mode="animated")
