# -*- coding: utf-8 -*-
"""surrogate A2 first_contract + A3 first_birth. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_surrogate_A2A3.py"""
from _surrogate_engine import seed_act

P_C2="clean clinical palette, cool clinic whites softened by warm lamps, quiet expensive stillness"
P_C3="charged tender palette, pale hospital green and warm skin tones against cold night, bittersweet"

C2=[
 ("A2_SH01",None,"clinic_room","a wide view of a clean private fertility clinic room, an examination couch under soft light, a desk and monitor, pale walls","WS","eye","push_in","day",True,False,
  "клиника встречает тебя чистотой, мягким светом и спокойными голосами, будто здесь не решают ничью судьбу."),
 ("A2_SH02","HERO_YOUNG","clinic_room","a medium shot of the nervous young woman of twenty-eight sitting on the edge of a clinic couch","MS","eye","static","day",False,False,
  "тебе объясняют, что в тебя перенесут чужого зародыша, и ты выносишь ребёнка, в котором нет ни капли твоего."),
 ("A2_SH03","COORD_BASE","clinic_room","a medium close-up of the silver-blonde coordinator with a tablet, cool and businesslike, in the clinic","MCU","over","static","day",False,False,
  "Инна Сергеевна повторяет, что это только медицина и деньги, и просит не привязываться заранее."),
 ("A2_SH04","HERO_YOUNG","clinic_room","a close-up of the young woman promising quietly, uncertainty behind her eyes","CU","eye","push_in","day",False,False,
  "ты обещаешь не привязываться, ещё не зная, что тело слушается сердца, а не договора."),
 ("A2_SH05",None,None,"an extreme close-up macro insert of a positive pregnancy test lying on a clean surface, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "через пару недель тест показывает две полоски, и внутри тебя начинает расти чужая жизнь."),
 ("A2_SH06","HERO_YOUNG","poor_flat","a medium shot of the young woman resting a hand on her belly in the poor flat, tender despite herself","MS","eye","static","day",False,False,
  "дома ты кладёшь руку на живот и незаметно для себя начинаешь говорить с ним, как со своим."),
 ("A2_SH07",None,"small_town_street","a wide view of a quiet grey small-town street, unaware and ordinary under a flat sky","WS","eye","pan_left","day",True,False,
  "посёлок ничего не замечает, а ты носишь тайну под сердцем и под просторной одеждой."),
 ("A2_SH08","RICHW_BASE","clinic_corridor","a medium close-up of an elegant intended mother of thirty-eight with a glossy black chignon and a pale silk scarf, anxious and hopeful","MCU","eye","static","day",False,False,
  "однажды в коридоре тебя знакомят с заказчицей, элегантной женщиной с бледным шёлковым платком."),
 ("A2_SH09","HERO_YOUNG","clinic_corridor","a close-up of the young woman meeting the intended mother's hopeful gaze, pity and fear mixed","CU","eye","push_in","day",False,False,
  "она смотрит на твой живот с такой надеждой, что тебе становится и жалко её, и страшно за себя."),
 ("A2_SH10","RICHW_BASE","clinic_corridor","a medium shot of the intended mother speaking softly in the clinic corridor, longing in her face","MS","over","static","day",False,False,
  "заказчица годами не могла родить сама, и теперь её ребёнок растёт в чужом, в твоём теле."),
 ("A2_SH11",None,None,"an extreme close-up macro insert of a plain paper envelope of cash and a bank card on a table, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "тебе выдают первую часть денег, и ты сразу переводишь её на операцию Мише."),
 ("A2_SH12","HERO_YOUNG","hospital_room","a close-up of the young woman exhaling with relief in a hospital corridor","CU","eye","static","day",False,False,
  "Мишу берут на операцию, она проходит хорошо, и впервые за год ты выдыхаешь."),
 ("A2_SH13","SON_CHILD","hospital_room","a medium shot of the pale six-year-old boy sitting up in a hospital bed, rolling his little red toy car on the blanket, cheeks pinker","MS","high","static","day",False,False,
  "в палате Миша уже сидит и катает по одеялу свою красную машинку, и щёки у него розовеют."),
 ("A2_SH14","HERO_YOUNG","hospital_room","a close-up of the mother watching her recovering son, convincing herself it was worth it","CU","eye","push_in","day",False,False,
  "ты смотришь на него и убеждаешь себя, что чужой ребёнок в животе — справедливая цена за это."),
 ("A2_SH15",None,None,"an extreme close-up macro insert of a pregnant belly under a plain dress with a hand resting on it, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "но чужой ребёнок толкается внутри всё сильнее, и не понимает, что он не твой."),
 ("A2_SH16","HERO_YOUNG","kitchen_night","a medium shot of the woman sitting at the kitchen table at night, a hand on her belly, talking softly to it","MS","eye","static","night",False,False,
  "по ночам ты говоришь ему не привыкать к тебе, потому что скоро придётся расстаться."),
 ("A2_SH17",None,"clinic_corridor","a wide view of a hushed clinic corridor with empty chairs and closed doors, cool light","WS","eye","static","day",True,False,
  "месяцы идут один за другим, живот растёт, и день, которого ты боишься, приближается неотвратимо."),
 ("A2_SH18","COORD_BASE","coordinator_office","a medium close-up of the coordinator looking pleased across her desk, hinting at more","MCU","over","static","day",False,False,
  "Инна Сергеевна довольна, называет тебя надёжной и намекает, что после этого можно и повторить."),
 ("A2_SH19","HERO_YOUNG","coordinator_office","a close-up of the young woman waving off the suggestion, certain it is a one-time thing","CU","eye","static","day",False,False,
  "ты отмахиваешься, ведь это в первый и последний раз, так ты обещала себе и Мише."),
 ("A2_SH20",None,None,"an extreme close-up macro insert of hands knitting a tiny baby bootie by lamplight, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "по вечерам ты тайком вяжешь одну крошечную пинетку, чтобы оставить себе хоть что-то на память."),
 ("A2_SH21","HERO_YOUNG","poor_flat","a medium shot of the woman tucking a knitted bootie into a small tin box in the poor flat","MS","eye","static","night",False,False,
  "ты прячешь пинетку в жестяную коробку и стараешься не думать, что будет, когда его заберут."),
 ("A2_SH22","HERO_YOUNG","poor_flat","a close-up of the pregnant woman of twenty-eight, tender and afraid, awaiting a child she must give away","CU","eye","push_in","day",False,True,
  "тебе двадцать восемь, ты ждёшь чужого ребёнка как своего, и это твоя главная, ещё не понятая ошибка."),
]

C3=[
 ("A3_SH01",None,"maternity_ward","a wide view of a maternity ward corridor at night, pale green walls, empty gurneys and a closed delivery-room door","WS","eye","push_in","night",True,False,
  "в двадцать девять начинаются схватки, и тебя увозят в родильное отделение среди ночи."),
 ("A3_SH02","HERO_YOUNG","maternity_ward","a medium shot of the young woman in labour on a hospital bed, alone but for masked staff, exhausted","MS","eye","static","night",False,False,
  "ты рожаешь чужого ребёнка одна, без мужа, без матери, только чужие люди в масках вокруг."),
 ("A3_SH03",None,None,"an extreme close-up macro insert of a plastic hospital ID bracelet fastened around a woman's wrist, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,False,
  "на твоём запястье пластиковый браслет с чужой фамилией, потому что ребёнок уже записан не на тебя."),
 ("A3_SH04","HERO_YOUNG","maternity_ward","a close-up of the woman's face at the moment she hears the first cry, love and loss at once","CU","eye","push_in","night",False,True,
  "ты слышишь первый крик и на одну секунду забываешь, что этот ребёнок не твой."),
 ("A3_SH05",None,"maternity_ward","a medium shot of a masked nurse lifting a swaddled newborn and carrying it away down the ward","MS","over","static","night",True,False,
  "медсестра поднимает свёрток, показывает его тебе издалека и тут же уносит к другим."),
 ("A3_SH06","HERO_YOUNG","maternity_ward","a close-up of the woman reaching out weakly from the bed as the baby is taken","CU","eye","push_in","night",False,False,
  "ты тянешь к нему руки, но тебе мягко напоминают, что трогать нельзя, так в договоре."),
 ("A3_SH07",None,None,"an extreme close-up macro insert of small scissors snipping a plastic hospital ID bracelet off a woman's wrist, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,True,
  "медсестра срезает браслет с твоей руки, и вместе с ним у тебя забирают всякое право на него."),
 ("A3_SH08","HERO_YOUNG","hospital_room","a medium shot of the woman moved to a plain recovery room with no cradle, only an empty stillness","MS","eye","static","day",False,False,
  "тебя переводят в палату, где нет ни колыбели, ни ребёнка, только пустая тишина и капельница."),
 ("A3_SH09",None,"hospital_room","a wide view of a plain post-natal hospital room with a narrow bed and a window, empty where a cradle should be","WS","eye","static","day",True,False,
  "за стеной плачут чужие младенцы, а у тебя под окном пусто, и грудь болит от ненужного молока."),
 ("A3_SH10","RICHW_BASE","rich_home","a medium close-up of the elegant intended mother cradling a newborn in a bright wealthy home, weeping with joy","MCU","eye","static","day",False,False,
  "где-то в большом светлом доме заказчица впервые берёт на руки ребёнка, которого выносила ты."),
 ("A3_SH11","RICHW_BASE","rich_home","a close-up of the intended mother's tearful joyful face over the swaddled baby","CU","eye","push_in","day",False,False,
  "она плачет от счастья и обещает себе, что малыш никогда не узнает, из какого он живота."),
 ("A3_SH12",None,None,"an extreme close-up macro insert of a bank card and a plain envelope of cash on a table, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "тебе переводят вторую, самую большую часть денег, и на счету появляется сумма, которой ты никогда не держала."),
 ("A3_SH13","HERO_YOUNG","poor_flat","a medium shot of the woman home again with empty arms, standing lost in the poor flat","MS","eye","static","day",False,False,
  "ты возвращаешься домой с деньгами, с пустыми руками и с телом, которое ищет ребёнка по ночам."),
 ("A3_SH14","SON_CHILD","poor_flat","a close-up of the now healthy fair-haired boy laughing as he plays on the floor with his red toy car","CU","high","static","day",False,False,
  "зато Миша здоров, бегает и смеётся, и ты говоришь себе, что ради этого всё и затевалось."),
 ("A3_SH15",None,None,"an extreme close-up macro insert of a snipped hospital bracelet and a tiny knitted bootie placed together into a tin box, filling the frame in sharp focus, shallow depth of field","ECU","top","static","day",True,False,
  "ты кладёшь в жестяную коробку срезанный браслет и связанную пинетку, первую из тех, что там будут."),
 ("A3_SH16","HERO_YOUNG","kitchen_night","a medium shot of the woman alone at the night kitchen table, lost in thought","MS","eye","static","night",False,False,
  "по ночам ты придумываешь ему имя, хотя знаешь, что называть его будут совсем иначе и не ты."),
 ("A3_SH17",None,"small_town_street","a wide view of the grey small-town street living on unchanged under a flat sky","WS","eye","pan_right","day",True,False,
  "посёлок живёт как жил, никто не знает, что ты только что отдала ребёнка чужим людям за деньги."),
 ("A3_SH18","MUZH_BASE","poor_flat","a medium close-up of the buzz-cut husband looking at his wife heavily, a cigarette behind his ear, resentment building","MCU","over","static","day",False,False,
  "Толя догадывается, откуда деньги, смотрит на тебя тяжело и начинает пить сильнее прежнего."),
 ("A3_SH19","HERO_YOUNG","poor_flat","a close-up of the woman trying to explain herself to her husband, a coldness opening between them","CU","eye","static","day",False,False,
  "ты говоришь ему, что сделала это ради семьи, но между вами уже пролегло что-то холодное."),
 ("A3_SH20",None,None,"an extreme close-up macro insert of empty bottles on a table and a cigarette resting on the edge, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "на столе всё чаще пустые бутылки, а его сигарета за ухом становится единственным, что от него остаётся."),
 ("A3_SH21","HERO_YOUNG","poor_flat","a medium shot of the woman standing in the poor flat trying to reassure herself","MS","eye","static","day",False,False,
  "ты убеждаешь себя, что худшее позади, что это был один раз и больше никогда."),
 ("A3_SH22","HERO_YOUNG","poor_flat","a close-up of the woman of twenty-nine, a healthy son and a broken marriage, unaware of what comes","CU","eye","push_in","day",False,True,
  "тебе двадцать девять, у тебя здоровый сын и разбитый брак, и ты ещё не знаешь, что это только начало."),
]

if __name__=="__main__":
    seed_act("first_contract", P_C2, C2, render_mode="animated")
    seed_act("first_birth",    P_C3, C3, render_mode="static")
