# -*- coding: utf-8 -*-
"""lottery atmosphere breathers — act tails A1..A10, id_region='a'. §5.1a unique schemes per act, all with VO.
PYTHONIOENCODING=utf-8 python scripts/_seed_lottery_atmo.py"""
from _lottery_engine import seed_act

ACTS=[
 ("origin",1,"nineties flashback palette, faded newsprint grey and warm kiosk amber, nostalgic worn browns",[
  ("a wide view of a spontaneous Friday market by the factory gate, goods sold off crates in flat light","WS","eye","push_in","day",
   "у заводской проходной по пятницам торгуют с ящиков семечками, носками и надеждой."),
  ("an extreme close-up insert of a worn five-rouble note smoothed flat on a kiosk tray","ECU","top","static","day",
   "пять рублей девяносто восьмого — это два хлеба, или билет, или полпачки сигарет."),
  ("a medium view of a kitchen radio on the fridge, a hand turning the dial past voices to music","MS","eye","static","evening",
   "по кухонному радио каждый вечер обещают стабилизацию, и отец крутит ручку до музыки."),
  ("a wide view of the courtyard at dusk, a domino table under a tin lamp, entrances glowing weakly","WS","eye","static","evening",
   "во дворе стучат домино и подъездные разговоры, и все живут одинаково небогато."),
  ("an extreme close-up insert of a flat cap on a hallway nail, the nail head polished bright","ECU","eye","push_in","evening",
   "кепку отец вешает всегда на один гвоздь, и шляпка гвоздя отполирована за годы."),
  ("a medium view of the kiosk window from inside the queue, a lucky pen on a string by the tray","MS","pov","static","day",
   "продавщица в киоске знает отца по имени и держит для него счастливую ручку."),
 ]),
 ("win",2,"ordinary-life palette, warm kitchen bulb and workshop steel, one sudden gold accent cutting through",[
  ("an extreme close-up insert of a machinist's pocket contents laid out: pass, travel card, tape measure, one ticket","ECU","top","static","day",
   "в твоих карманах порядок наладчика: пропуск, проездной, рулетка и билетик по пятницам."),
  ("a medium view of the factory canteen at lunch, trays sliding, a queue bending toward the counter","MS","eye","pan_right","day",
   "в заводской столовой по четвергам котлеты, и очередь к ним длиннее, чем к кассе."),
  ("a wide view of the evening city with minibuses full of lit windows heading for the districts","WS","eye","track","evening",
   "город после смены едет домой в жёлтых окнах, и ты в нём — один из всех."),
  ("an extreme close-up insert of a mortgage schedule on a fridge, half the lines struck, a horseshoe magnet","ECU","eye","static","day",
   "ипотечный график на холодильнике зачёркнут ровно наполовину, и магнитом ему служит подкова."),
  ("a medium view of a teenager's desk with homework under big headphones, a lamp circle on the page","MS","high","static","evening",
   "Максим делает уроки в наушниках, и его наушники — главная роскошь этой квартиры."),
  ("a wide view of the five-storey courtyard at night, windows going dark floor by floor","WS","low","static","night",
   "двор засыпает рано: работягам вставать, и окна гаснут этажами, как по команде."),
 ]),
 ("fire_bridges",3,"new-money palette, showroom white and champagne gold over glass, glossy and slightly cold",[
  ("a medium view of a chrome multi-drink coffee machine on marble, one plain black cup beneath it","MS","eye","static","day",
   "кофе-машина в пентхаусе умеет двадцать напитков, и ты пьёшь один — чёрный."),
  ("a wide view of the city grid from the thirtieth floor, one small industrial rectangle among the blocks","WS","high","static","day",
   "с тридцатого этажа город похож на схему, и твой завод в ней — маленький прямоугольник."),
  ("an extreme close-up insert of a stack of rent invoices on thick paper, embossed letterhead","ECU","top","static","day",
   "счета за аренду приходят каждое первое число, красивые, на плотной бумаге, безжалостные."),
  ("a medium view of a waiter's trolley gliding toward a regular's table in golden light","MS","eye","track","night",
   "в ресторане тебя уже узнают, и это льстит ровно до первого счёта месяца."),
  ("a wide view of the private school drive at drop-off, polished cars idling in a patient line","WS","eye","static","day",
   "у частной школы утром пахнет чужими духами, и ты паркуешься чуть в стороне."),
  ("an extreme close-up insert of borscht served in an angular designer plate, sour cream swirled by habit","ECU","top","static","evening",
   "борщ в дизайнерской тарелке выглядит гостем, и Таня подаёт его с усмешкой."),
 ]),
 ("vultures",4,"pressed-upon palette, doorbell yellow and hallway grey, too many coats in the light, crowded warm-cold",[
  ("an extreme close-up insert of a folded letter pushed halfway under a tall door","ECU","eye","static","day",
   "письма с просьбами подсовывают прямо под дверь, и почерк в них жалобнее орфографии."),
  ("a wide view of the upscale entrance in early winter, pavement empty, a concierge behind glass","WS","eye","static","day",
   "к зиме у подъезда снова пусто, и консьерж скучает по слову «передайте»."),
  ("a medium view of a phone ringing to itself inside a drawer, its light pulsing through the seam","MS","eye","push_in","evening",
   "Таня заводит второй номер для своих, и старый телефон звонит теперь в ящике."),
  ("an extreme close-up insert of a notebook spread with tick marks down the margin, one column empty","ECU","top","static","day",
   "галочек «дал» в блокноте тридцать одна, галочек «вернул» — ни одной, и это статистика."),
  ("a wide view of the emptied banquet room after guests, chairs skewed, one waiter clearing glasses","WS","eye","pan_left","night",
   "после банкетов остаются счета и фотографии, где ты всегда чуть в стороне от веселья."),
  ("a medium view of a man's silhouette with a tea cup at the glass wall, dawn behind the city","MS","eye","static","dawn",
   "по утрам ты пьёшь чай у стекла и всё чаще смотришь в сторону завода."),
 ]),
 ("partner",5,"promised-return palette, blueprint blue and banner gloss over raw earth brown, persuasive and hollow",[
  ("a wide view of the four-hectare site in winter panorama, water standing over most of it","WS","high","static","day",
   "стройка твоей мечты занимает четыре гектара, и три из них — это лужа."),
  ("a medium view of a locked site office cabin, a notice on its door bleached unreadable","MS","eye","static","day",
   "прорабский вагончик заперт с самого октября, и объявление на его двери выцвело до вежливости."),
  ("an extreme close-up insert of the investor sticker on a folder, its edges curling, glue gone yellow","ECU","eye","static","day",
   "наклейка «инвестор» на папке блестит, как фантик, и клей у неё уже жёлтый."),
  ("a wide view of a prestigious office-centre lobby, marble and turnstiles, a reception desk far away","WS","eye","push_in","day",
   "офис Аркадия занимает полэтажа в центре, и секретарша там вежлива, как автоответчик."),
  ("a medium view of pencil percentages worked over a scrap of paper under a designer lamp","MS","top","static","night",
   "по вечерам ты пересчитываешь проценты на бумажке, и бумажка соглашается, а жизнь нет."),
  ("an extreme close-up insert of a phone screen mid-call, the timer counting over an unanswered name","ECU","pov","static","night",
   "гудки в трубке длинные, ровные, терпеливые, и ты слушаешь их дольше, чем надо."),
 ]),
 ("no_return",6,"felt-green palette, deep casino green and brass under low cones of light, windowless timeless dark",[
  ("a medium view of a casino cloakroom rail of dark coats, one numbered tag turned face out","MS","eye","static","night",
   "в гардеробе казино твоё пальто висит среди таких же, и номерок у него постоянный."),
  ("an extreme close-up insert of an untouched complimentary drink sweating on a side table by the felt","ECU","eye","static","night",
   "выпивку здесь приносят бесплатно, и это единственное, что ты так и не начал."),
  ("a wide view of the casino parking at dawn, a handful of cars frosted under pale sky","WS","eye","static","dawn",
   "на стоянке казино рассвет всегда застаёт одни и те же машины, включая твою."),
  ("a medium view of a penthouse bathroom counter at seven, coffee steaming beside a razor","MS","eye","static","day",
   "домой ты приезжаешь к семи, душ, кофе, и лицо в порядке, а глаза нет."),
  ("an extreme close-up insert of an odometer glowing a long night figure on a leather dashboard","ECU","pov","static","night",
   "пробег кайена растёт ночами, и заправщик на кольце здоровается с тобой, как с таксистом."),
  ("a wide view of the neon night centre, signs burning over wet asphalt and slow taxis","WS","eye","pan_right","night",
   "ночной центр города горит для таких, как ты, и счёт за этот свет приходит утром."),
 ]),
 ("collapse",7,"emptying palette, packing-box brown and glass grey, warm things leaving cold rooms",[
  ("an extreme close-up insert of a child's third-grade drawing found in a box: a house, a chimney, three figures","ECU","top","static","day",
   "среди вещей находится рисунок Максима из третьего класса: дом, труба, трое у дома."),
  ("a medium view of open empty wardrobes, wire hangers trembling faintly in a draught","MS","eye","static","day",
   "шкафы стоят с открытыми дверцами, и вешалки в них звенят от сквозняка."),
  ("a wide view of a grey institutional building with a short queue at its single door","WS","eye","static","day",
   "здание следствия серое и вежливое, и очередь в него записывается на месяц вперёд."),
  ("a medium view of the penthouse kitchen on the last evening, one stool, one plate, one lamp","MS","eye","static","evening",
   "последний вечер в пентхаусе ты проводишь на кухне, единственной комнате по росту."),
  ("a wide view of the snowed-over pit, white and level, crane frozen above it like a mast","WS","eye","static","day",
   "котлован заносит снегом ровно и по-хозяйски, и он становится похож на тихое озеро."),
  ("an extreme close-up insert of a key set passing across a manager's desk against a signed receipt","ECU","top","static","day",
   "ключи ты сдаёшь управляющему под расписку, и расписка — единственная бумага за год без потерь."),
 ]),
 ("bottom",8,"stripped-bare palette, dormitory beige and document grey, one warm bulb of dignity",[
  ("a wide view of a U-shaped workers' dormitory at evening, laundry lines crossing the inner yard","WS","eye","push_in","evening",
   "общага стоит буквой «п», и в её дворе сушится бельё всех этажей сразу."),
  ("an extreme close-up insert of an immersion heater coil steaming in a single mug","ECU","eye","static","evening",
   "кипятильник в кружке — техника твоей юности, и руки помнят её без инструкции."),
  ("a medium view of a dormitory wall with a radio murmuring beyond it, a boot by the door","MS","eye","static","night",
   "за стеной у соседа радио и храп по очереди, и оба звука честные."),
  ("an extreme close-up insert of small change sorted into neat columns on a table edge","ECU","top","static","evening",
   "мелочь на столе разложена столбиками до получки, и в этом есть спокойствие цеха."),
  ("a medium view of a six a.m. bus stop, thermoses and work jackets, breath steaming under the sign","MS","eye","static","dawn",
   "на остановке в шесть утра все свои: спецовки, термосы, невыспавшиеся добрые лица."),
  ("a wide view of the factory checkpoint seen across the road through thin morning fog","WS","eye","static","dawn",
   "проходная через дорогу от остановки, и ты пока выходишь на одну раньше."),
 ]),
 ("return",9,"homecoming palette, workshop steel and warm sodium, oil-dark browns with steady morning light",[
  ("a medium view of an opened old locker: a hard hat, a mug, a calendar stopped four years ago","MS","eye","static","day",
   "твой шкафчик стоял запертым, и внутри нашлись каска, кружка и календарь за тот год."),
  ("a wide view of the canteen at shift lunch, trays and steam and the good noise of tired people","WS","eye","static","day",
   "в столовой гул смены и запах котлет, и никто не смотрит на тебя дольше секунды."),
  ("an extreme close-up insert of a stores requisition slip for one set of work overalls","ECU","top","static","day",
   "новую спецовку выдают по талону, и кладовщица ворчит беззлобно: возвращаются тут всякие."),
  ("a wide view of the winter district at night, unbroken snow under lamps between the dorm and the stop","WS","eye","static","night",
   "зимний район у общаги тих, и снег под фонарями лежит нетронутый до утренней смены."),
  ("an extreme close-up insert of a second schedule line ruled through with the same neat stroke","ECU","top","static","day",
   "вторая строка графика зачёркивается заметно легче первой, и это, похоже, общий закон жизни."),
  ("a medium view of the checkpoint booth, a guard's easy nod toward the turnstile","MS","eye","static","dawn",
   "охранник на проходной больше не спрашивает про выигрыш, и это лучший комплимент."),
 ]),
 ("rebuild",10,"mended palette, spring light over machine steel, modest warm colors coming back",[
  ("an extreme close-up insert of two hard hats on one workbench, the newer one askew","ECU","eye","static","day",
   "на верстаке теперь две каски, и младшая вечно валяется не там, где положено."),
  ("a wide view of five trainees clustered at the shop notice board, a foreman gesturing them on","WS","eye","static","day",
   "практикантов в цеху пятеро, и мастер гоняет их с той же нежной свирепостью."),
  ("a medium view of a five-storey entrance hall, fresh whitewash, a soup smell down the stairs","MS","eye","static","day",
   "подъезд у Тани пахнет побелкой и супом, и этот запах тебя больше не ранит."),
  ("a wide view of a summer park path with families strolling, a kvass barrel under a tree","WS","eye","pan_left","day",
   "в парке по субботам город гуляет семьями, и ты учишься смотреть на это спокойно."),
  ("an extreme close-up insert of a cake box balanced on bus-seat knees, string held by a thumb","ECU","top","static","day",
   "торт ты возишь теперь на автобусе, и коробка ни разу не помялась."),
  ("a medium view of a young machinist working alone at a lathe, a first passed gauge on the board behind","MS","eye","static","day",
   "к осени Максим точит сам, и его первый допуск мастер вешает на доску."),
 ]),
]

if __name__=="__main__":
    for sk,ai,pal,items in ACTS:
        shots=[("A%d_SZ5%d"%(ai,i+1), None, None, subj, st, ang, mv, tod, True, False, narr)
               for i,(subj,st,ang,mv,tod,narr) in enumerate(items[:4])]  # max 4 per act tail (user 2026-07-04)
        seed_act(sk, pal, shots, render_mode="static", id_region="a")
