# -*- coding: utf-8 -*-
"""car_flipper — акт 6 (40–43, сын в деле, площадка на Дениса) и акт 7 (44, похороны Гены, попытка выйти)."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _car_flipper_engine import seed_act

P6 = "a warm evening palette of low sun on paintwork, long shadows and amber floodlight"
P7 = "a drained autumn palette of wet grey, dark green and a pale washed-out sky"

SON = [
 ("A6_SH01", None, "dealer_lot",
  "an established used-car lot in low evening sun, a repainted banner frame at the gate, thirty spaces filled, the paving slabs worn smooth along the walking lines",
  "WS","eye","static","dusk",True,False,
  "в сорок ты уже девять лет стоишь на одном и том же месте."),
 ("A6_SH02", "VIK_MID", "dealer_lot",
  "Viktor walking the rows in the evening with a phone against his ear, tapping wing mirrors straight with one knuckle as he passes",
  "MS","eye","track","dusk",False,False,
  "у тебя тридцать мест, наёмный мойщик и отдельный человек, который возит машины."),
 ("A6_SH03", "VIK_MID", "dealer_lot",
  "Viktor's face in warm low sun, clean and unhurried, his hands and cuffs spotless",
  "CU","low","static","dusk",False,False,
  "ты не ремонтируешь сам уже пять лет и почти забыл запах шпатлёвки."),
 ("A6_SH04", None, "flat_kitchen",
  "a kitchen in the evening with three plates set out and one chair standing empty, an unopened envelope propped against the sugar tin",
  "WS","eye","static","night",True,False,
  "Денису шестнадцать, и в апреле его отчисляют из колледжа за одни прогулы."),
 ("A6_SH05", "DEN_TEEN", "flat_kitchen",
  "Denis sitting sideways on a kitchen chair with one arm over its back, talking with his chin up and a flat unapologetic stare",
  "MCU","eye","static","night",False,False,
  "он говорит, что учиться не будет, потому что видел, сколько ты зарабатываешь."),
 ("A6_SH06", "LENA_ADULT", "flat_kitchen",
  "Lena's face turned towards the camera and waiting, her mouth closed, her eyes moving to somebody off frame",
  "CU","eye","static","night",False,False,
  "Лена смотрит на тебя и ждёт, что ты его сейчас же остановишь."),
 ("A6_SH07", "VIK_MID", "flat_kitchen",
  "Viktor standing at the counter with his back half turned, taking a long time to put down a cup",
  "MS","low","static","night",False,False,
  "ты молчишь ровно четыре секунды, и этого короткого молчания хватает им обоим."),
 ("A6_SH08", None, "dealer_lot",
  "a closed car lot at seven in the morning with the gate still on its rollers, frost on the bunting wire and one long shadow across the empty apron",
  "WS","eye","static","dawn",True,False,
  "в понедельник он приходит на площадку в семь утра и ждёт у ворот."),
 ("A6_SH09", ("VIK_MID","DEN_TEEN"), "dealer_lot",
  "Viktor holds out a bucket by the handle and Denis takes it from him with one hand, already looking past him at the first car",
  "MS","eye","static","day",False,False,
  "ты даёшь ему ведро и говоришь ему, что начинают тут абсолютно все одинаково."),
 ("A6_SH10", "DEN_TEEN", "dealer_lot",
  "Denis's face streaked with drying foam, jaw set, working with his eyes down and his jaw set",
  "CU","low","static","day",False,False,
  "он моет девять машин за один день и не жалуется тебе ни разу."),
 ("A6_SH11", None, "office_container",
  "an open key cabinet with every hook filled, the paper tags all turned the same way and numbered in one hand",
  "INSERT","top","static","day",True,False,
  "через месяц он знает все тридцать машин по номерам их ключей наизусть."),
 ("A6_SH12", ("DEN_TEEN","VIK_MID"), "office_container",
  "Denis leans over the desk explaining something to a customer out of frame while Viktor stands back against the key cabinet with his arms folded, listening to him",
  "MCU","eye","static","day",False,False,
  "в семнадцать он впервые сам разговаривает с покупателем, а ты стоишь рядом."),
 ("A6_SH13", "DEN_TEEN", "office_container",
  "Denis's face open and calm mid-sentence, holding steady eye contact with somebody past the camera",
  "CU","eye","push_in","day",False,True,
  "он говорит спокойнее тебя и врёт лучше тебя, и ты это слышишь."),
 ("A6_SH14", "VIK_MID", "office_container",
  "Viktor watching from the wall with something close to pride moving across his face",
  "MCU","eye","static","day",False,False,
  "ты ждёшь, что станет стыдно, а вместо стыда приходит что-то похожее на гордость."),
 ("A6_SH15", None, "dealer_lot",
  "a car lot from above just after the floodlights die, the rows going dark row by row and one figureless gate standing half rolled",
  "WS","high","static","dusk",True,False,
  "вы закрываете площадку вдвоём, и прожекторы на ночь теперь выключает уже он."),
 ("A6_SH16", ("VIK_MID","DEN_TEEN"), "dealer_lot",
  "Viktor crouches at a rear sill running his thumb along the underbody while Denis squats opposite him holding a torch low on the metal",
  "MS","low","static","dusk",False,False,
  "он спрашивает, зачем нужен баллон антигравия, если ржавчина под ним всё равно есть."),
 ("A6_SH17", "VIK_MID", "dealer_lot",
  "Viktor's face lit from below by the torch, explaining it patiently as a piece of craft",
  "CU","low","static","dusk",False,False,
  "ты объясняешь, что покупателю нужно вовсе не отсутствие ржавчины, а её невидимость."),
 ("A6_SH18", None, "office_container",
  "an official envelope slit open on a desk with a folded printed summons half drawn out of it, a mug pushed aside to make room",
  "WS","eye","static","day",True,False,
  "через год Лене приходит бумага из суда по чужому иску о возврате."),
 ("A6_SH19", "LENA_ADULT", "office_container",
  "Lena standing at the desk reading a sheet held in both hands, her lips moving through it a second time",
  "MCU","eye","static","day",False,False,
  "она читает её дважды и первый раз за пятнадцать лет повышает голос."),
 ("A6_SH20", "LENA_ADULT", "office_container",
  "Lena's face hard and level, one hand striking the desk flat once as she finishes speaking",
  "CU","eye","push_in","day",False,False,
  "она требует убрать её фамилию отовсюду, где стоит хотя бы одна машина."),
 ("A6_SH21", ("VIK_MID","LENA_ADULT"), "office_container",
  "Viktor raises both palms towards Lena in a settling gesture while she turns away from him towards the container door",
  "MS","eye","static","day",False,False,
  "ты обещаешь переоформить всё в течение недели, и ты действительно всё переоформляешь."),
 ("A6_SH22", None, "office_container",
  "a desk covered with printed transfer forms squared into three piles, a pen laid across the top sheet and a stamp pad open beside them",
  "WS","low","static","day",True,False,
  "переоформить всё можно только на человека, у которого чистая фамилия и восемнадцать лет."),
 ("A6_SH23", "DEN_ADULT", "office_container",
  "Denis sitting at the desk in his father's chair with the red cap backwards, pulling the first pile towards himself",
  "MS","eye","static","day",False,False,
  "Денису девятнадцать лет, и он единственный такой человек во всей твоей семье."),
 ("A6_SH24", "OBJ:contract", None,
  "an office desk under a strip light with a stamp pad open at the edge",
  "INSERT","top","push_in","interior",True,False,
  "он подписывает четырнадцать листов подряд и не читает при этом ни строчки."),
 ("A6_SH25", "DEN_ADULT", "office_container",
  "Denis's face bent over the paperwork, entirely untroubled, signing at the speed of somebody copying a shape",
  "CU","eye","static","day",False,True,
  "он подписывает точно так же, как когда-то подписала мать: потому что доверяет."),
 ("A6_SH26", "VIK_MID", "office_container",
  "Viktor standing behind the chair with one hand on its back, sliding the next sheet forward with two fingers",
  "MCU","low","static","day",False,False,
  "ты видишь эту рифму и всё равно кладёшь перед ним следующий лист."),
 ("A6_SH27", None, "dealer_lot",
  "a used-car lot at dusk with a new name board freshly bolted onto the banner frame, the paint on its brackets still bright",
  "WS","eye","static","dusk",True,False,
  "с этого дня площадка, все машины и все договоры принадлежат твоему сыну."),
 ("A6_SH28", ("VIK_MID","DEN_ADULT"), "dealer_lot",
  "Viktor leans against a wing with his arms crossed while Denis faces him and repeats something back to him with a half smile",
  "WS","eye","static","dusk",False,False,
  "ты учишь его самой последней вещи, которой тебя когда-то научил сам Гена."),
 ("A6_SH29", "DEN_ADULT", "dealer_lot",
  "Denis's face saying four words with easy warmth, his eyes completely steady",
  "CU","eye","static","dusk",False,True,
  "как себе брал, повторяет он за тобой, и у него получается лучше."),
 ("A6_SH30", None, "dealer_lot",
  "a lit car lot at night from very high, the floodlights burning over full rows and the road beyond running away into darkness",
  "EWS","high","pull_out","night",True,False,
  "в сорок три ты первый раз за двадцать лет спишь спокойно всю ночь."),
]

QUIT = [
 ("A7_SH01", None, "market_old",
  "an old car market on a wet October morning seen from high above, half the rows empty, puddles standing where cars used to be",
  "EWS","high","pan_left","day",True,False,
  "Гена умирает в октябре, в среду, у себя в четвёртом ряду на стуле."),
 ("A7_SH02", None, "market_old",
  "an empty folding stool standing between two parked cars with a dented thermos cup left upright on the ground beside it",
  "INSERT","low","static","day",True,True,
  "его складной стул стоит на месте ещё четыре дня, и его не убирают."),
 ("A7_SH03", "OBJ:wreath", None,
  "a low painted metal grave fence on a windy slope",
  "INSERT","eye","static","day",True,False,
  "на похороны приходит одиннадцать человек, и девять из них должны ему деньги."),
 ("A7_SH04", "VIK_OLD", "cemetery",
  "Viktor standing at a grave fence with his cap held in both hands in front of him, wind pulling at his coat",
  "MS","eye","static","day",False,False,
  "ты стоишь у ограды и считаешь, сколько из его учеников тут стоят."),
 ("A7_SH05", "VIK_OLD", "cemetery",
  "Viktor's face in flat grey daylight, working through a count behind his eyes and arriving somewhere that tightens his mouth",
  "CU","low","static","day",False,False,
  "выходит, что ты один, потому что все остальные просто у него покупали."),
 ("A7_SH06", None, "cemetery",
  "a hillside cemetery seen from above with the ring road far below it, slow traffic moving along the road in both directions",
  "WS","high","pull_out","day",True,False,
  "внизу от кладбища хорошо видно кольцевую, и по ней всё время идут машины."),
 ("A7_SH07", "VIK_OLD", "cemetery",
  "Viktor putting his cap back on and standing a moment longer than the others, deciding something with his eyes on the road below",
  "MCU","eye","static","day",False,True,
  "в сорок четыре ты решаешь, что больше не будешь трогать ни одного одометра."),
 ("A7_SH08", None, "dealer_lot",
  "a car lot on a cold clear morning with a new printed sheet taped inside the office window and the rows only two thirds full",
  "WS","eye","static","day",True,False,
  "ты объявляешь, что твоя площадка переходит на честную комиссию уже с ноября."),
 ("A7_SH09", ("VIK_OLD","DEN_ADULT"), "dealer_lot",
  "Viktor talks with one hand held flat in the air while Denis listens facing him with his arms down and his jaw tight",
  "MS","eye","static","day",False,False,
  "Денис слушает молча и спрашивает, кто будет платить аренду уже в декабре."),
 ("A7_SH10", None, "office_container",
  "a printed diagnostic report lying on a desk with a whole column of faults ticked and circled, a highlighter uncapped beside it",
  "INSERT","top","static","day",True,False,
  "теперь каждую машину ты гонишь на диагностику и печатаешь по ней честный отчёт."),
 ("A7_SH11", "VIK_OLD", "office_container",
  "Viktor's face across the desk watching somebody read the report, his own expression carefully neutral",
  "CU","eye","static","day",False,False,
  "в отчёте написано всё, и покупатели читают его и уезжают куда-то дальше."),
 ("A7_SH12", None, "dealer_lot",
  "a half-emptied car lot from above with wide gaps between the remaining cars and weeds coming up through the joints of the paving slabs",
  "WS","high","static","day",True,False,
  "за весь ноябрь ты продаёшь четыре машины вместо своих обычных двадцати двух."),
 ("A7_SH13", "VIK_OLD", "office_container",
  "Viktor counting the contents of a cash tin twice and closing it with the contents left inside",
  "MS","eye","static","day",False,False,
  "в декабре ты не платишь мойщику и просишь его подождать до января."),
 ("A7_SH14", "DEN_ADULT", "office_container",
  "Denis standing over the desk with a payment schedule held down under two fingers, reading a number off it",
  "MCU","eye","static","day",False,False,
  "Денис говорит, что за площадку осталось тридцать выплат и они на нём."),
 ("A7_SH15", "DEN_ADULT", "office_container",
  "Denis's face very calm and very cold, holding the pause exactly as long as it needs",
  "CU","eye","push_in","day",False,True,
  "он впервые говорит с тобой так, как ты когда-то говорил с покупателями."),
 ("A7_SH16", None, "flat_kitchen",
  "a kitchen at night with one cup of tea steaming on the oilcloth and the other side of the table cleared and empty",
  "WS","eye","static","night",True,False,
  "дома Лена ставит перед тобой чай и ничего не спрашивает про работу."),
 ("A7_SH17", "LENA_ADULT", "flat_kitchen",
  "Lena standing at the stove with her back three-quarters to the room, saying it over her shoulder with her back to the room",
  "MCU","eye","static","night",False,False,
  "она говорит, что три месяца — это уже больше, чем ты обещал."),
 ("A7_SH18", "VIK_OLD", "flat_kitchen",
  "Viktor's face lowered over the cup, his eyes open and fixed on the empty tablecloth",
  "CU","low","static","night",False,False,
  "ты не отвечаешь ей, потому что знаешь, что уже согласился внутри себя."),
 ("A7_SH19", None, "flood_yard",
  "a flooded yard in February seen from high above, brown water between the buildings and car roofs standing out of it in a broken grid",
  "EWS","high","pan_right","day",True,False,
  "в феврале большая вода приходит во второй раз за всю твою жизнь."),
 ("A7_SH20", None, "flood_yard",
  "six cars standing in flood water to their sills with a silver saloon nearest the camera, its paint still bright above the tide line",
  "WS","low","static","day",True,True,
  "шесть машин стоят в воде, и одна из них серебристая, почти новая."),
 ("A7_SH21", "VIK_OLD", "flood_yard",
  "Viktor standing at the water's edge in rubber boots with his hands in his pockets, standing right at the edge of the water",
  "MS","eye","track","day",False,False,
  "ты приезжаешь туда просто посмотреть и всю дорогу повторяешь себе, что только посмотришь."),
 ("A7_SH22", "OBJ:brakeline", None,
  "a sheet of flattened cardboard laid on wet ground beneath a car sill",
  "INSERT","top","static","day",True,True,
  "ты ложишься под неё на картон и видишь трубки насквозь рыжими от ржавчины."),
 ("A7_SH23", "VIK_OLD", "flood_yard",
  "Viktor lying on his back on cardboard under a car with a torch resting on his chest, staring straight up at the floor pan",
  "CU","low","static","day",False,True,
  "ты лежишь под ней двадцать минут и не вылезаешь, чтобы не решать."),
 ("A7_SH24", "VIK_OLD", "flood_yard",
  "Viktor sitting up out from under the car and wiping his hands slowly on a rag, doing arithmetic with his mouth shut",
  "MCU","eye","static","day",False,False,
  "замена этих трубок стоит столько, что такую машину проще вообще не покупать."),
 ("A7_SH25", None, "body_shop",
  "a single tall grey aerosol can standing alone at the front of a workshop shelf, its cap already off and the nozzle crusted",
  "INSERT","eye","push_in","interior",True,True,
  "а один баллон серого антигравия стоит примерно столько же, сколько твой обед."),
 ("A7_SH26", "VIK_OLD", "body_shop",
  "Viktor pushing a rolled length of plastic sheeting across the bay doorway at night, sealing the gap with tape",
  "MS","low","static","night",False,False,
  "ты покупаешь все шесть и увозишь их в бокс той же ночью."),
 ("A7_SH27", "VIK_OLD", "body_shop",
  "Viktor's face under the work lamp with the can already in his hand, every argument already finished in it",
  "CU","eye","push_in","night",False,True,
  "три месяца твоей честной работы заканчиваются в четверг, в половине третьего дня."),
 ("A7_SH28", None, "dawn_road",
  "a long empty road at first light seen from very high, the surface wet and the fields still under mist on both sides",
  "EWS","high","static","dawn",True,False,
  "и до той трассы на сто девятом километре остаётся ровно восемь недель."),
]

if __name__ == "__main__":
    seed_act("son",  P6, SON)
    seed_act("quit", P7, QUIT)
