# -*- coding: utf-8 -*-
"""Batch 5: act10_road + act11_water (Part III — journey)."""
from _flat_earth_engine import seed_act

PAL_ROAD = "sun-bleached road palette, dusty heat haze by day and neon-motel amber by night, faded asphalt and kudzu green"
A10 = [
 ("A10_SH01",None,"interstate_south","a tiny lone figure with a rucksack walking the shoulder of an immense flat highway under a huge bleached sky","EWS","high","push_in","day",True,True,
  "ты идёшь на юг пешком и автостопом, по обочинам бесконечных ровных дорог, день за днём."),
 ("A10_SH02","RAY","interstate_south","a man with a rucksack thumbing for a ride at a sun-blasted roadside, hopeful, the road flat behind him","MCU","low","static","day",False,False,
  "на третий день тебя подбирает дальнобойщик, и первое, что ты делаешь, рассказываешь ему про край земли."),
 ("A10_SH03","RAY","interstate_south","a man in a truck cab talking animatedly with his hands to an unseen driver, the flat road streaming past the windshield","MS","eye","static","day",False,False,
  "ты объясняешь ему про ровную воду и про лёд по краю, а он только хмыкает и прибавляет газу."),
 ("A10_SH04",None,"interstate_south","a battered pickup pulling away down a flat highway, leaving a small figure alone at a dusty junction","WS","high","static","day",True,False,
  "он высаживает тебя у развязки раньше, чем обещал, и уезжает, и ты снова один на ровной дороге."),
 ("A10_SH05",None,"roadside_motel","a cheap single-storey motel at night, a buzzing neon vacancy sign, a row of doors, moths around the lamps","WS","eye","push_in","night",True,False,
  "ночуешь в придорожных мотелях по тридцать долларов, и денег в рюкзаке становится всё меньше."),
 ("A10_SH06","RAY","roadside_motel","a man sitting on a sagging motel bed counting a thinning roll of cash under a bare bulb, rucksack open","MS","high","static","night",False,False,
  "ты пересчитываешь деньги на продавленной кровати, двенадцать тысяч тают, но тебе всё равно, ты близко."),
 ("A10_SH07",None,"roadside_motel","extreme close on a thinning fold of bills and a worn motel key on a stained bedside table","ECU","top","push_in","night",False,True,
  "ты тратишь только на воду и консервы, всё остальное бережёшь на последний рывок к самому краю."),
 ("A10_SH08","RAY","roadside_motel","a man at a dark motel window holding a brass ruler up against the flat night horizon beyond the parking lot","MCU","eye","push_in","night",False,True,
  "перед сном ты прикладываешь линейку к ночному горизонту, и он ровный, и ты засыпаешь спокойно."),
 ("A10_SH09",None,"rural_gas_south","a lonely rural gas station baking at midday, one old pump, a sagging clapboard store, a kudzu-choked fence","WS","eye","pan_right","day",True,False,
  "днём ты заходишь на глухие заправки, чтобы набрать воды и купить банку фасоли, и тебя сторонятся."),
 ("A10_SH10","RAY","rural_gas_south","a ragged bearded man at a store counter, a clerk leaning back from him warily, hand near the phone","OTS","eye","static","day",False,False,
  "ты оброс, осунулся, и продавец за прилавком отступает, и держит руку поближе к телефону, на всякий случай."),
 ("A10_SH11","RAY","rural_gas_south","close on a man's sunburnt dirty face with a growing beard and bright fixed eyes, reflected in a counter mirror","CU","eye","push_in","day",False,False,
  "ты ловишь своё отражение в зеркале у кассы, и не сразу узнаёшь себя, но глаза у тебя ясные, как никогда."),
 ("A10_SH12",None,"rural_gas_south","a ragged man sitting alone on the kerb outside a gas station eating cold beans from a can, a wide berth around him","WS","high","static","day",False,False,
  "ты ешь холодную фасоль на бордюре, и люди обходят тебя по дуге, как обходили когда-то на родной улице."),
 ("A10_SH13",None,"ridge_overlook","a wide southern vista from a low rise, flat hazy land rolling to a dead-level horizon, heat shimmer","EWS","high","pan_left","day",True,True,
  "с каждого пригорка ты смотришь на юг, и горизонт там ровный, как натянутая нить, и манит тебя дальше."),
 ("A10_SH14",None,"ridge_overlook","extreme close on a brass ruler held against a distant flat hazy horizon line, no curvature at all","ECU","eye","push_in","day",False,True,
  "ты прикладываешь линейку к дальней черте, и она ровная, и тот детский холодок не отпускает тебя ни на день."),
 ("A10_SH15","RAY","interstate_south","a more ragged man trudging a long empty road at dusk, rucksack heavier, shadow stretched far behind","MS","low","track","dusk",False,False,
  "проходит неделя, другая, ты весь в пыли, борода свалялась, но ты идёшь, потому что вода уже близко."),
 ("A10_SH16",None,"interstate_south","two travelers at a roadside rest stop stepping back from a ragged bearded man who gestures at the horizon","WS","eye","static","dusk",False,False,
  "на стоянке ты пытаешься рассказать паре проезжих про край мира, и они торопливо садятся в машину."),
 ("A10_SH17","RAY","interstate_south","close on the bearded man smiling gently after the departed travelers, utterly unbothered, certain","CU","low","push_in","dusk",False,False,
  "ты улыбаешься им вслед, ничего, говоришь ты себе, скоро я увижу край, и тогда поверят все до единого."),
 ("A10_SH18",None,"roadside_motel","a seedier motel in the rain at night, half the neon dead, a single lit window, puddles in the lot","WS","eye","push_in","night",True,False,
  "дожди догоняют тебя на юге, и ты пережидаешь их в самых дешёвых мотелях, считая каждый доллар."),
 ("A10_SH19","RAY","roadside_motel","a man drying out by a heater with a route map spread on a motel bed, tracing a line toward a large body of water","MS","high","static","night",False,False,
  "ты сушишь карту на батарее, и ведёшь пальцем к большому синему пятну воды, до него совсем недалеко."),
 ("A10_SH20",None,"roadside_motel","extreme close on a route map, a vast reservoir circled in marker, a hand-written note reading big water near","ECU","top","push_in","night",False,True,
  "большая вода, написал ты на карте, и за ней, по краю, должна лежать стена льда, и за ней сам край."),
 ("A10_SH21","RAY","roadside_motel","close on a man's gaunt elated face lit by a heater glow, certain the end of the road is near","CU","low","push_in","night",False,False,
  "ты почти не спишь от волнения, как ребёнок перед праздником, ведь завтра ты выйдешь к самой воде."),
 ("A10_SH22",None,"rural_gas_south","a near-broke ragged man buying a jug of water and two cans at a rural store, emptying his last small bills","MS","eye","static","day",False,False,
  "на последней заправке ты тратишь почти всё, что осталось, на воду и две банки, и идёшь дальше налегке."),
 ("A10_SH23",None,"rural_gas_south","extreme close on a few crumpled small bills and coins counted out on a worn store counter","ECU","top","push_in","day",False,True,
  "от двенадцати тысяч остаётся горстка мелочи, но деньги тебе больше и не нужны, дальше дорога бесплатна."),
 ("A10_SH24",None,"reservoir_shore_south","a back road ending at a treeline beyond which a vast sheet of flat water gleams silver through the trunks","WS","eye","push_in","dusk",True,False,
  "просёлок выводит тебя к стене сосен, и за ними что-то широко блестит, ровное и огромное, как небо легло наземь."),
 ("A10_SH25","RAY","reservoir_shore_south","a ragged man pushing through pines toward a brightening gap, the gleam of huge water ahead lighting his face","MCU","low","push_in","dusk",False,False,
  "ты продираешься через сосны на этот блеск, и сердце колотится, как тогда, в девять лет, на пирсе."),
 ("A10_SH26","RAY","reservoir_shore_south","close on a man's awestruck face catching the first wide light of an immense flat water through the trees","CU","eye","push_in","dusk",False,True,
  "ты выходишь из-за деревьев, и видишь её, огромную ровную воду до самого горизонта, и тот холодок накрывает тебя с головой."),
 ("A10_SH27",None,"reservoir_shore_south","an immense flat reservoir revealed at dusk through a gap in dark pines, water stretching to a level glowing horizon","EWS","eye","pull_out","dusk",True,True,
  "вот она, большая вода, ровная, как стол, без единого изгиба, и где-то там, по краю, тебя ждёт мир, что кончается."),
 ("A10_SH28","RAY","reservoir_shore_south","a small ragged figure standing at the open water's edge at dusk, arms slowly spreading, rucksack at his feet","WS","low","static","dusk",False,True,
  "ты опускаешь рюкзак на гальку, и разводишь руки, и стоишь так, и тебе кажется, что вся жизнь вела сюда."),
 ("A10_SH29",None,"reservoir_shore_south","extreme close on weathered hands folding an old map into a small paper boat at the water's edge","ECU","top","push_in","dusk",False,True,
  "ты складываешь из старой карты бумажный кораблик, такой же, как когда-то для коди, и пускаешь на воду."),
 ("A10_SH30",None,"reservoir_shore_south","a small paper boat drifting straight out on dead-flat dusk water, a ragged figure watching from the shore behind","WS","high","static","dusk",False,True,
  "кораблик уходит по ровной глади прямо, никуда не сворачивая, и на секунду тебе до боли не хватает сына."),
]

PAL_WATER = "vast cold-water palette, grey reservoir dawn and silver storm light, deep teal and pewter, sparse cold tones"
A11 = [
 ("A11_SH01",None,"reservoir_shore_south","an immense flat reservoir at grey dawn, dead-calm water reaching a perfectly level horizon, thin cold mist, broken reeds","EWS","eye","push_in","dawn",True,True,
  "на рассвете большая вода лежит перед тобой ровная и серая, до самого края света, и ты идёшь к ней."),
 ("A11_SH02","RAY","reservoir_shore_south","a gaunt ragged man walking out onto the open gravel shore toward the vast flat water, awed and small","MS","low","track","dawn",False,False,
  "ты выходишь на открытый берег, и под ногами хрустит галька, и впереди только вода и ровная черта."),
 ("A11_SH03","RAY","reservoir_shore_south","a man raising a brass folding ruler at arm's length against the dead-flat horizon over the huge reservoir","MCU","low","push_in","dawn",False,True,
  "ты достаёшь дедову линейку, и прикладываешь её к самой дальней кромке воды, как тогда, в девять лет."),
 ("A11_SH04",None,"reservoir_shore_south","extreme close on a brass ruler edge against a vast dead-level waterline, the two lines meeting with no curve","ECU","eye","push_in","dawn",False,True,
  "и линия ложится ровно, ни на волос изгиба, на много миль воды, ровно, ровно, как всё, что ты говорил."),
 ("A11_SH05","RAY","reservoir_shore_south","close on a ragged man's weeping certain face at dawn, tears on dirty cheeks, the flat water glowing behind","CU","eye","push_in","dawn",False,True,
  "и ты плачешь, и шепчешь, вот, я же говорил, ровно, я почти дома, и тот холодок поёт по всей спине."),
 ("A11_SH06","RAY","reservoir_shore_south","a tiny figure standing arms wide at the edge of an immense flat dawn reservoir, utterly alone, exalted","EWS","high","pull_out","dawn",False,True,
  "ты стоишь один на краю огромной ровной воды, и тебе хочется крикнуть на весь мир, что ты был прав."),
 ("A11_SH07","RAY","reservoir_shore_south","a man shielding his eyes scanning far down the shoreline where a faint grey concrete wall spans the water","MCU","eye","static","day",False,False,
  "ты вглядываешься вдаль вдоль воды, и там, на самом юге, серой нитью лежит что-то огромное поперёк."),
 ("A11_SH08",None,"reservoir_shore_south","far across flat water, the distant low silhouette of a massive concrete dam spanning the horizon in haze","EWS","eye","push_in","day",False,True,
  "это стена, говоришь ты себе, та самая стена по краю, за которой вода уходит вниз, и ты идёшь к ней."),
 ("A11_SH09","RAY","reservoir_shore_south","a fisherman on far rocks turning to gesture warily downstream toward the distant dam at a ragged approaching man","WS","eye","static","day",False,False,
  "одинокий рыбак машет тебе рукой, не ходи туда, кричит он, там плотина, там опасно, но ты только киваешь."),
 ("A11_SH10","RAY","reservoir_shore_south","close on a ragged man's fixed eyes locked on the distant dam, deaf to warning, certain it is the edge","CU","low","push_in","day",False,False,
  "ты слышишь, плотина, и думаешь, нет, это не плотина, это и есть край, где вода переливается за мир."),
 ("A11_SH11","RAY","reservoir_shore_south","a man trudging along an endless gravel shoreline toward a far wall, the reservoir vast and flat beside him","WS","low","track","day",False,False,
  "ты идёшь вдоль воды весь день, и стена медленно растёт впереди, и ты не чувствуешь ни голода, ни ног."),
 ("A11_SH12",None,"reservoir_shore_south","a small driftwood fire on a dark shore at night, a huddled figure beside it, the flat black water beyond","WS","eye","push_in","night",True,False,
  "ты ночуешь у воды, разводишь костерок из плавника, и доедаешь последнюю банку, глядя на тёмную ровную гладь."),
 ("A11_SH13","RAY","reservoir_shore_south","close on a gaunt man's face lit orange by a small shore fire at night, eating the last of a can, eyes far away","CU","low","static","night",False,False,
  "еды больше нет, и денег нет, но тебе всё равно, ведь до края, ты уверен, остался один последний переход."),
 ("A11_SH14",None,"reservoir_shore_south","extreme close on an empty tin can tipped over on wet gravel beside the dying embers of a small fire","ECU","top","push_in","night",False,True,
  "пустая банка катится по гальке, и ты засыпаешь под открытым небом, и тебе снится отец у воды."),
 ("A11_SH15",None,"reservoir_shore_south","a grey overcast day over flat water, a lone weakened figure trudging the shore, the dam noticeably larger ahead","WS","high","static","day",True,False,
  "наутро ты идёшь дальше, шатаясь, и стена впереди уже огромна, и ты слышишь сквозь ветер далёкий гул."),
 ("A11_SH16",None,"reservoir_shore_south","heavy storm clouds massing over a vast flat reservoir, the light turning silver and bruised, wind on the water","EWS","eye","pan_right","day",True,True,
  "над водой собирается гроза, свет становится серебряным и злым, и ветер гонит по ровной глади рябь."),
 ("A11_SH17","RAY","reservoir_shore_south","a ragged man pushing into a rising wind toward a growing distant roar, hair and beard whipping","MS","low","push_in","day",False,False,
  "ты идёшь навстречу ветру, на нарастающий рёв падающей воды, и тебе кажется, что мир зовёт тебя по имени."),
 ("A11_SH18","RAY","reservoir_shore_south","close on a man's exalted unafraid face in the storm wind, eyes wide toward the unseen roar ahead","CU","low","push_in","day",False,False,
  "слышишь, говоришь ты ветру, это вода падает за край, я же говорил, я всю жизнь говорил, и вот он."),
 ("A11_SH19",None,"reservoir_shore_south","a small figure walking through driving night rain toward a faint thunder of falling water, lit by far lightning","WS","eye","track","night",True,True,
  "к ночи разражается буря, и ты бредёшь под ливнем на грохот воды, и молнии выхватывают что-то огромное."),
 ("A11_SH20",None,"dam_spillway","a flash of lightning revealing the vast silhouette of a great concrete dam spanning black storm water ahead","EWS","low","static","night",True,True,
  "вспышка, и ты видишь её целиком, гигантскую стену поперёк всего мира, и за ней, ты уверен, обрыв."),
 ("A11_SH21","RAY","dam_spillway","close on a rain-soaked man's awestruck face lit blue-white by lightning, staring up at the looming dam","CU","low","push_in","night",False,False,
  "ты стоишь под ней, крошечный, мокрый насквозь, и смеёшься от счастья, потому что дошёл, ты всё-таки дошёл."),
 ("A11_SH22","RAY","dam_spillway","a small ragged figure beginning to climb a wet rocky embankment toward the base of an immense dam in the storm","WS","low","push_in","night",False,False,
  "ты карабкаешься по мокрым камням к подножию стены, цепляясь руками, и линейка зажата у тебя в кулаке."),
 ("A11_SH23",None,"dam_spillway","extreme close on a weathered hand gripping a wet concrete step, knuckles white, rain streaming over it","ECU","over","push_in","night",False,True,
  "пальцы скользят по мокрому бетону, но ты лезешь выше, к самому гребню, туда, где вода уходит за край."),
 ("A11_SH24",None,"dam_spillway","the colossal base of a dam at night, water thundering down into a churning basin, a tiny figure dwarfed below","EWS","low","tilt_up","night",True,True,
  "над тобой ревёт водосброс, тонны воды рушатся вниз в кипящую тьму, и этот рёв заглушает всё на свете."),
 ("A11_SH25","RAY","dam_spillway","a soaked man on a steel walkway stair gazing up the towering dam wall, certain the edge waits at the top","MCU","low","push_in","night",False,False,
  "ты задираешь голову на эту стену до самого неба, и знаешь, там, наверху, и есть край земли, осталось дойти."),
 ("A11_SH26","RAY","dam_spillway","close on a man's exhausted certain face streaming with rain, eyes fixed upward, near the end of his strength","CU","eye","push_in","night",False,False,
  "ноги не держат, грудь горит, но ты лезешь, ступень за ступенью, ведь всю жизнь ты шёл именно сюда."),
 ("A11_SH27",None,"dam_spillway","a long wet steel walkway staircase climbing the face of a dam into storm darkness, a tiny figure low on it","WS","low","tilt_up","night",False,False,
  "лестница вдоль стены уходит вверх во тьму, и ты считаешь ступени, как считал когда-то градусы кривизны."),
 ("A11_SH28",None,"reservoir_shore_south","the storm breaking over a vast flat reservoir before dawn, the first thin grey light along a dead-level horizon","EWS","eye","pan_left","dawn",True,True,
  "буря выдыхается под утро, и над ровной водой проступает первый серый свет, тонкий, как лезвие."),
 ("A11_SH29","RAY","dam_spillway","a spent man nearing the top of a long dam stairway as the rain thins, the roar of water louder above","MCU","low","push_in","dawn",False,False,
  "ты почти наверху, дождь редеет, рёв воды всё громче, и за гребнем уже светлеет, и сердце рвётся из груди."),
 ("A11_SH30",None,"dam_spillway","extreme close on a trembling hand closing around the cold wet top railing of a dam as first light breaks","ECU","eye","push_in","dawn",False,True,
  "и вот твоя рука ложится на верхние перила, холодные и мокрые, и за ними светлеет самый край мира."),
 ("A11_SH31","RAY","dam_spillway","a ragged man pulling himself up onto the broad top walkway of a great dam at first light, swaying, alive","WS","low","push_in","dawn",False,True,
  "ты вытягиваешь себя наверх, на широкий гребень плотины, и встаёшь, шатаясь, на самой высокой точке."),
 ("A11_SH32","RAY","dam_spillway","close on a man's face as dawn light hits it at the top of the dam, awe dawning, the roar of falling water around him","CU","low","push_in","dawn",False,True,
  "ты поднимаешь голову, и впереди, за гребнем, вода уходит вниз, в светящийся туман, и у тебя перехватывает дыхание."),
 ("A11_SH33",None,"dam_spillway","from a man's vantage at the dam crest, a vast sheet of water pouring over the edge into a golden abyss of mist","EWS","eye","push_in","dawn",True,True,
  "огромная ровная вода переливается через кромку и беззвучно падает вниз, в золотое сияние, без конца, без дна."),
 ("A11_SH34","RAY","dam_spillway","close on a man's transfigured weeping face at the dam crest in golden dawn light, looking out over the falling water","CU","low","push_in","dawn",False,True,
  "и ты понимаешь, что дошёл, что вот он, край земли, и что ты был прав, прав всю свою жизнь, до последнего слова."),
]

seed_act("act10_road",  PAL_ROAD,  A10)
seed_act("act11_water", PAL_WATER, A11)
