# -*- coding: utf-8 -*-
"""coffee atmosphere breathers — act tails A1..A10, id_region='a'.
§5.1a: every act has its OWN scale scheme, angles, moves and subject pool. Every insert carries VO.
PYTHONIOENCODING=utf-8 python scripts/_seed_coffee_atmo.py"""
from _coffee_engine import seed_act

ACTS=[
 ("origin",1,"childhood summer palette, amber kitchen light and green courtyard, copper and cinnamon browns, storybook warm",[
  ("a medium view of the grandmother's shelf with labelled jars of beans and cinnamon arranged by height","MS","eye","pan_right","day",
   "банки с зерном и корицей стоят у бабушки по росту, как класс на школьной фотографии."),
  ("an extreme close-up insert of a half-finished cocoa cup on a sunny windowsill beside geraniums","ECU","eye","static","evening",
   "какао ты допиваешь на подоконнике, где солнце дольше всего держится по вечерам."),
  ("a wide view of the green courtyard at noon, a rope swing moving slightly, clover and chalk drawings","WS","low","static","day",
   "лето пахнет клевером и мелом, и каждый день умещает в себя целую маленькую жизнь."),
  ("an extreme close-up insert of a chalk drawing of a steaming cup on sun-warmed asphalt","ECU","top","push_in","day",
   "мелом на асфальте нарисована чашка с паром, и дождь щадит её почти неделю."),
  ("a medium view of a school notebook and pencils on the round family table under the warm lamp","MS","high","static","evening",
   "уроки ты делаешь быстро и честно, потому что после уроков — кухня и турка."),
  ("a wide view of the grandmother's kitchen at early morning, low sun laid across the scrubbed table","WS","eye","push_in","day",
   "утро у бабушки начинается со скрипа половиц и запаха, ради которого стоит просыпаться."),
 ]),
 ("barista",2,"busy chain-cafe palette, clean retail whites warmed by espresso browns and steam, brisk and bright",[
  ("an extreme close-up insert of a trainee name badge pinned to a dark work apron","ECU","eye","static","day",
   "на твоём бейдже написано «стажёр», и ты носишь его, как будущую вывеску."),
  ("a wide view of the main street at seven in the morning, bakery light, a street sweeper's cart, long shadows","WS","eye","pan_left","dawn",
   "город в семь утра принадлежит пекарям, дворникам и бариста, и это хорошая компания."),
  ("a medium view of the coffee-bar counter being polished to a shine, cloth and steel in window light","MS","eye","static","day",
   "стойку ты натираешь до блеска даже там, где никто не видит, привычка от бабушки."),
  ("an extreme close-up insert of tip coins dropping into a tin money box with a taped label","ECU","top","static","evening",
   "чаевые за улыбку отправляются в ту же жестяную банку, монетка к монетке, без исключений."),
  ("a wide view of the empty corner unit with a faded rental notice curling in the arched window","WS","eye","static","day",
   "пустой угловой зал так и стоит с табличкой об аренде, и табличка выгорает на солнце."),
  ("a medium view of practice saucers with foam patterns lined up beside an old button phone taking a photo","MS","high","static","night",
   "лучшие узоры ты фотографируешь на кнопочный телефон, и это твоё первое портфолио."),
 ]),
 ("championship",3,"competition palette, stage spotlight gold over polished steel, confetti warmth, festive and keen",[
  ("a wide view of a registration table with a row of trophy cups shining under the hall lights","WS","eye","push_in","day",
   "кубки на регистрации стоят в ряд и блестят так, что в них хочется заглянуть."),
  ("a medium view of the roaster listening at his turning drum, one hand raised for the exact click","MS","eye","static","day",
   "старик у барабана слушает зерно, как радио, и останавливает обжарку по одному щелчку."),
  ("an extreme close-up insert of a participant badge pinned beside a single old button on an apron strap","ECU","eye","static","day",
   "значок участника ты прикалываешь на фартук рядом с первой пуговицей-сдачей из детства."),
  ("a wide view of the winter main street strung with garlands, cafe windows glowing warmest on the block","WS","eye","tilt_down","evening",
   "зимний город развешивает гирлянды, и витрины кофеен светятся в нём теплее всего."),
  ("an extreme close-up insert of a notebook page with a line underlined twice in red pencil","ECU","top","static","night",
   "на сорок третьей странице тетради выведено красным: главное — место у окна."),
  ("a medium view of the round family table with spread calculations and two teacups gone cold","MS","eye","pan_right","evening",
   "отец проверяет твои расчёты по вечерам и всё реже находит, к чему придраться."),
 ]),
 ("opening",4,"fresh-start palette, wet yellow paint and raw wood, copper lamps against dusty golden light, hopeful bright",[
  ("a medium view of ladders and paint rollers resting at evening, the yellow wall half glowing","MS","eye","pan_left","evening",
   "после каждого рабочего дня вы устраиваете ревизию: что покрашено, что придумано, что съедено."),
  ("a wide view of the street corner before opening hour, bakery light opposite, bundles of newspapers, a first bus","WS","eye","static","dawn",
   "угол просыпается раньше твоей вывески: пекарня напротив, связки утренних газет, первые полупустые автобусы."),
  ("an extreme close-up insert of new cups being lifted from straw packing like ornaments","ECU","top","static","day",
   "новые чашки вы распаковываете, как ёлочные игрушки, и ни одна не бьётся, к счастью."),
  ("a wide view of the finished cafe standing ready and silent the night before opening, chairs squared","WS","eye","push_in","night",
   "накануне открытия зал стоит готовый и тихий, и вы обходите его на цыпочках."),
  ("a medium view of a forty-line checklist on a clipboard, most boxes ticked in red","MS","high","static","night",
   "у Жени чек-лист открытия на сорок пунктов, и напротив последнего написано: выдохнуть."),
  ("an extreme close-up insert of a door key on a small wooden sun keyring resting in a palm","ECU","eye","push_in","day",
   "ключ от зала переезжает на брелок-солнышко, и с этого дня он больше не чужой."),
 ]),
 ("black_streak",5,"candlelit trial palette, deep blue night water and warm candle amber, courage colors over cold, never grim",[
  ("an extreme close-up insert of a candle in a glass jar burning steadily on the wooden counter","ECU","eye","static","night",
   "свечи после потопа вы оставляете на стойке насовсем, они оказались к лицу залу."),
  ("a medium view of floorboards propped to dry with a hair dryer resting between them","MS","high","static","day",
   "доски пола вы сушите феном по очереди, и у каждой появляется имя."),
  ("a wide view of the winter street with the cafe window glowing defiantly warm against blue dusk","WS","eye","static","evening",
   "в самые тонкие дни окно кофейни светится, как ни в чём не бывало, назло арифметике."),
  ("an extreme close-up insert of a payment schedule inside a cupboard door, lines ticked with small sun stickers","ECU","pov","push_in","day",
   "график платежей висит изнутри шкафа, и каждую закрытую строку вы отмечаете наклейкой-солнышком."),
  ("a wide view of the grey discount storefront next door, posters bright, room dim behind them","WS","eye","pan_right","day",
   "серая витрина за стеной сияет скидками, но пахнет оттуда почему-то только картоном."),
  ("a medium view of the chalkboard menu being refreshed with a steady hand, a new sun taking shape","MS","eye","static","day",
   "меловое солнышко ты обновляешь каждое утро, и рука ни разу не дрогнула."),
 ]),
 ("regulars",6,"lived-in warmth palette, honey wood and copper lamplight, chalk white and cinnamon brown, easy golden",[
  ("a wide view of morning light crossing the six tables one by one, the window table first","WS","eye","push_in","day",
   "утренний свет ложится на шесть столиков по расписанию, начиная со столика бабушки."),
  ("an extreme close-up insert of a named dog saucer by the door, licked spotless","ECU","top","static","day",
   "у двери теперь стоит именное блюдце пса, и почтальон делает крюк ради этого."),
  ("a medium view of two tables pushed together under books and notes, cups holding the pages down","MS","eye","static","evening",
   "студенты сдвигают два столика перед сессией, и ты продлеваешь им вечер до последнего конспекта."),
  ("an extreme close-up insert of a framed newspaper clipping, its margins covered in signatures","ECU","eye","push_in","day",
   "на полях газетной вырезки уже сорок подписей, и место осталось только сверху."),
  ("a medium view of flower boxes under the arched window being watered from a tin can","MS","low","static","dawn",
   "цветы в ящиках под окном ты поливаешь до открытия, пока на улице только пекарь."),
  ("a wide view of the corner at dusk as string lights come on over the pavement","WS","eye","tilt_up","evening",
   "над углом загораются гирлянды, и прохожие сбавляют шаг именно на этом месте, проверено."),
 ]),
 ("pandemic",7,"quiet-streets palette, soft grey empty city warmed by one amber takeaway window, hopeful through stillness",[
  ("a medium view of the takeaway window opening at seven sharp, shutters folding back onto a quiet street","MS","eye","static","dawn",
   "окно навынос открывается ровно в семь, и первый стакан всегда уходит дворнику с соседней улицы."),
  ("an extreme close-up insert of chalk waiting marks on wet asphalt, freshly redrawn","ECU","top","static","day",
   "меловые метки на асфальте вы обновляете после каждого дождя, и они складываются в дорожку."),
  ("a wide view of the empty main square with pigeons walking unhurried across the middle","WS","eye","static","day",
   "площадь стоит пустая, и голуби ходят по ней пешком, как хозяева положения."),
  ("a medium view of the takeaway window worked in rubber gloves, a ruler-straight foam sun going out","MS","eye","push_in","day",
   "по выходным к окну встаёт Женя, и у неё солнышки выходят строго по линейке."),
  ("an extreme close-up insert of hospital-bound cup sleeves marked with ward names and small suns","ECU","eye","static","dawn",
   "на стаканах для больницы вы пишете имена смен: хирургия, приёмное, терапия, и всем солнышко."),
  ("a wide view of the dark evening street with the one amber takeaway window glowing at the corner","WS","eye","pull_out","night",
   "вечерами город тих, и твоё окно горит в нём, как дежурная лампа."),
 ]),
 ("partner",8,"two-points palette, rain-washed bridge blues warmed by skylight gold and fresh wood, adventurous bright",[
  ("a wide view of the second cafe's skylight column of sun moving across fresh floorboards","WS","eye","static","day",
   "свет из потолочного фонаря ходит по второй точке весь день, как медленная стрелка."),
  ("a medium view of a training station at the second cafe, three pitchers and a strict spoon laid out","MS","eye","static","day",
   "новых бариста для второй точки Марк дрессирует лично и выпускает каждого с ложечкой."),
  ("an extreme close-up insert of two door keys on one ring lying in a bicycle basket","ECU","top","static","day",
   "ключи от двух дверей висят у тебя на одном кольце и звенят в такт педалям."),
  ("a medium view of a bicycle leaned at the bridge rail, river mist thinning in morning light","MS","eye","pan_right","dawn",
   "маршрут ты можешь проехать с закрытыми глазами: мост, поворот, запах реки, запах корицы."),
  ("a wide view of two warm-lit cafe corners in two different districts under the same evening sky","WS","high","static","evening",
   "в двух районах города теперь пахнет одинаково, и люди спорят, где солнышки ровнее."),
  ("an extreme close-up insert of a ledger page with two income columns climbing in neat pencil","ECU","pov","push_in","night",
   "в таблице Жени две колонки доходов, и обе растут, не мешая друг другу."),
 ]),
 ("franchise",9,"growing-network palette, loft sunlight over bean-sack burlap and map pins, confident amber and green",[
  ("an extreme close-up insert of a folder of letters labelled in warm handwriting","ECU","eye","static","day",
   "письма о франшизе Женя складывает в папку с надписью: люди, с которыми по пути."),
  ("a wide view of the loft filling with morning sun and first-roast steam from the corner drum","WS","eye","push_in","day",
   "штаб просыпается от запаха первой обжарки, и совещания назначают на после кофе."),
  ("a medium view of the teaching corner mid-lesson, steam rising, a metronome-steady hand keeping count","MS","eye","static","day",
   "в учебном углу шипит молоко, и Марк считает вслух до восьми, как метроном."),
  ("a wide view through a train window of passing towns, a notebook open on the fold-down table","WS","pov","track","day",
   "в новые города ты ездишь поездом и всю дорогу смотришь, где люди пьют кофе."),
  ("an extreme close-up insert of a franchise booklet cover with a photographed copper cezve on it","ECU","top","static","day",
   "на обложке франшизного буклета не графики, а бабушкина турка, и это честная реклама."),
  ("a medium view of a phone propped by a loft window, a gallery of first-cup photos glowing on it","MS","eye","static","evening",
   "каждый вечер тебе присылают фото первых чашек из новых точек, и ты отвечаешь каждому."),
 ]),
 ("triumph",10,"award-evening palette, festive gold and deep warm red over copper, proud and glowing, never pompous",[
  ("a wide view of the first cafe on a Saturday morning, three aproned figures behind one small counter","WS","eye","push_in","day",
   "по субботам в первой кофейне смена легенд: за машиной ты, Марк и его лучшая выпускница."),
  ("an extreme close-up insert of a small golden cup trophy on a shelf, a copper cezve gleaming above it","ECU","eye","static","day",
   "золотую чашку протирают от пыли реже, чем турку, и это правильный порядок вещей."),
  ("a medium view of a franchise cafe run by a former chain manager, warm and busy, a name badge retired in a frame","MS","eye","static","day",
   "бывший сетевик оказывается старательным франчайзи и звонит тебе чаще всех, по делу и без."),
  ("a wide view of the city from a hill at dusk, warm window lights scattered down the slopes","WS","eye","static","evening",
   "с холма видно полгорода, и в сумерках ты можешь пересчитать свои окна по огням."),
  ("a medium view of the great-grandmother's window table set and waiting, afternoon light on the gold-rimmed cup","MS","eye","pan_left","day",
   "бабушка приходит по вторникам и четвергам, и её столик в эти дни не бронируют."),
  ("an extreme close-up insert of a gold-rimmed porcelain cup being dried by hand with a soft cloth","ECU","eye","push_in","day",
   "чашку с золотым ободком моют только вручную, и все новенькие знают почему."),
 ]),
]

if __name__=="__main__":
    for sk,ai,pal,items in ACTS:
        shots=[("A%d_SZ5%d"%(ai,i+1), None, None, subj, st, ang, mv, tod, True, False, narr)
               for i,(subj,st,ang,mv,tod,narr) in enumerate(items[:4])]  # max 4 per act tail (user 2026-07-04)
        seed_act(sk, pal, shots, render_mode="static", id_region="a")
