# -*- coding: utf-8 -*-
"""cloakroom batch A: cold_open(+CTA) + origin. animated."""
from _cloakroom_engine import seed_act

PAL_NIGHT="cold ghost-light palette, a single warm bulb pool against a deep blue-black auditorium dark, dust drifting in the beam, lonely"
COLD=[
 ("M0_SH01",None,"stage_empty","the vast dark auditorium of eight hundred empty red velvet seats and gilded boxes seen from the stage, a single ghost-light bulb burning","EWS","eye","push_in","night",True,True,
  "ты выходишь на сцену в чужом пальто, и восемьсот кресел молчат, как молчали всегда."),
 ("M0_SH02","CLOAK_OLD","stage_empty","the old cloakroom attendant standing centre stage in a borrowed overcoat under the lone ghost-light, facing the dark empty house","MS","low","push_in","night",False,False,
  "тебе шестьдесят один, и это лучший зал города, потому что отсюда никто не уходит до антракта."),
 ("M0_SH03","CLOAK_OLD","stage_empty","close on the old man's lips moving in a soundless hoarse whisper as he plays a monologue","CU","eye","push_in","night",False,False,
  "ты играешь шёпотом, и заднего ряда тут нет, тебя всё равно никто никогда не услышит."),
 ("M0_SH04","CLOAK_OLD","stage_empty","a wide view of the small lone figure on the great stage beginning an actor's gesture under the ghost-light","WS","low","static","night",False,False,
  "тридцать семь лет ты подавал чужие пальто, а ночью на этой сцене играешь только один."),
 ("M0_SH05",None,"stage_empty","extreme close on a worn brass numbered cloakroom token held in an old man's open palm","INSERT","top","push_in","night",True,True,
  "в кармане чужого смокинга лежит латунный номерок, и это твой единственный реквизит."),
 ("M0_SH06","CLOAK_OLD","stage_empty","close on the old attendant's hands smoothing the lapel of the borrowed coat with an actor's care","MCU","high","static","night",False,False,
  "ты разглаживаешь чужое пальто ладонью, как костюм, потому что иначе ты уже не умеешь."),
 ("M0_SH07","CLOAK_OLD","stage_empty","extreme close on the old man's working throat and mouth as only a dry hoarse rasp comes out","ECU","eye","push_in","night",False,False,
  "из горла выходит только сип, и в пустом зале этого сипа хватает с большим запасом."),
 ("M0_SH08",None,"auditorium","the gilded empty theatre boxes rising tier on tier into darkness, fine dust drifting in dim light","WS","low","tilt_up","night",True,True,
  "золочёные ложи пустуют ярус за ярусом, и каждая из них смотрит мимо тебя."),
 ("M0_SH09","CLOAK_OLD","stage_empty","the old attendant making a small formal bow toward the dark sea of empty seats","MS","eye","static","night",False,False,
  "ты кланяешься восьмистам пустым креслам, и они отвечают тебе одной только полной тишиной."),
 ("M0_SH10","CLOAK_OLD","stage_empty","close on the old man's face after the bow, head tilted, listening for an applause that will not come","CU","eye","push_in","night",False,False,
  "ты замираешь и ждёшь хлопка, хотя знаешь, что хлопать тут давно уже некому."),
 ("M0_SH11",None,"stage_empty","the lone ghost-light bulb burning on its tall stand on the empty stage in the dark","INSERT","eye","static","night",True,False,
  "одна дежурная лампа горит на сцене всю ночь, чтобы театр не оставался в полной темноте."),
 ("M0_SH12","CLOAK_OLD","stage_empty","a wide shot as the old man lowers his arms, the performance over, shrinking back into an ordinary old man","WS","high","pull_out","night",False,False,
  "спектакль окончен, ты опускаешь руки и снова становишься просто стариком в чужом пальто."),
 ("M0_SH13","CLOAK_OLD","stage_empty","the old attendant turning his face slightly toward the viewer, beginning to speak directly","MCU","eye","push_in","night",False,False,
  "если хочешь знать, как ты оказался по эту сторону вешалки, останься со мной до конца."),
 ("M0_SH14","CLOAK_OLD","stage_empty","a direct close on the old man's tired pleading eyes meeting the camera","CU","eye","push_in","night",False,False,
  "подпишись и досмотри, потому что эту историю, кроме тебя, рассказать уже совсем некому."),
 ("M0_SH15",None,"backstage_lost","a long backstage rail crowded with unclaimed overcoats of every era under a single caged work-light","EWS","eye","track","night",True,False,
  "это пальто ты снял с вешалки забытых вещей, как снимаешь каждую ночь чужую жизнь."),
 ("M0_SH16",None,"cloakroom_counter","rows of numbered brass cloakroom hooks climbing the wall, one hook at the end conspicuously bare","INSERT","eye","push_in","night",True,True,
  "а вон тот крючок, номер первый, ты держишь пустым уже целых тридцать семь лет."),
 ("M0_SH17","CLOAK_OLD","cloakroom_counter","the old attendant standing behind his cloakroom counter at night, one hand resting on the brass rail","MS","eye","static","night",False,False,
  "за этой стойкой прошла вся твоя жизнь, а ты всё ждёшь, что однажды выкрикнут твоё имя."),
 ("M0_SH18","CLOAK_OLD","cloakroom_counter","close on the old man's eyes turned toward the single empty brass hook number one","CU","eye","push_in","night",False,False,
  "крючок номер один ждёт твоё пальто, как ты ждал свою роль, и оба так и не дождались."),
 ("M0_SH19",None,"foyer_marble","the grand marble theatre foyer at night, chandeliers dimmed, the sweeping staircase deserted","WS","high","pan_left","night",True,False,
  "ночью театр огромен и пуст, и принадлежит тебе одному, как никогда не принадлежал днём."),
 ("M0_SH20","CLOAK_OLD","foyer_marble","the old attendant crossing the empty marble foyer alone, small beneath the high painted ceiling","MCU","high","track","night",False,False,
  "ты идёшь по мрамору один, шаги отдаются под потолком, и это единственные твои аплодисменты."),
 ("M0_SH21",None,"cloakroom_counter","an extreme close as a brass numbered token is set down on the worn wooden counter","INSERT","top","push_in","night",True,True,
  "ты кладёшь номерок на стойку, и завтра снова раздашь восемьсот таких же чужим людям."),
 ("M0_SH22","CLOAK_OLD","stage_empty","the old man from behind, small under the great proscenium arch, facing the dark house once more","BACK","low","pull_out","night",False,False,
  "а пока досмотри со мной, как мальчик, которого не брали на роли, стал чужой вешалкой."),
]

PAL_SCHOOL="warm nostalgic late-1980s palette, honey afternoon light and floating dust, hopeful amber and soft shadow"
PAL_CLINIC="cold clinical palette, pale green tile and steel, flat sterile light, drained of warmth"
PAL_OFFICE="dim scholarly amber palette, warm desk lamp, deep velvet shadow, old photographs"
A1=[
 # --- 1987 училище ---
 ("A1_SH01",None,"theatre_school","a worn 1980s acting-school rehearsal studio, a long wall of mirrors and a ballet barre, honey afternoon light through tall windows","EWS","eye","push_in","day",True,False,
  "тысяча девятьсот восемьдесят седьмой, тебе двадцать два, и весь курс уверен, что ты будешь великим."),
 ("A1_SH02","CLOAK_YOUNG","theatre_school","a hopeful young man of twenty-two declaiming a monologue in the rehearsal studio, classmates watching from folding chairs","MS","low","static","day",False,False,
  "ты читаешь монолог, и педагог замолкает на полуслове, и говорит, что такого голоса не слышал давно."),
 ("A1_SH03","CLOAK_YOUNG","theatre_school","close on the young man's face mid-monologue, alive and certain, the voice filling the room","CU","eye","push_in","day",False,False,
  "голос у тебя сильный и чистый, и достаёт до последнего ряда без всякого микрофона."),
 ("A1_SH04",None,"theatre_school","an acting class on folding chairs applauding warmly toward an unseen performer, mirrors behind them","WS","high","static","day",False,False,
  "однокурсники хлопают, а педагог жмёт тебе руку и обещает, что в этом сезоне ты получишь главную роль."),
 ("A1_SH05","CLOAK_YOUNG","theatre_school","the young man laughing with two classmates by the piano in the studio, easy and happy","MCU","eye","static","day",False,False,
  "тебе двадцать два, и кажется, что весь театр уже твой, надо только дождаться премьеры."),
 ("A1_SH06",None,"theatre_school","extreme close on a cast list pinned to a studio wall, one name at the top of the leading role","INSERT","eye","push_in","day",False,True,
  "твою фамилию вешают первой в списке на главную роль, и ты переписываешь её себе в тетрадь."),
 ("A1_SH07","CLOAK_YOUNG","dressing_mirror","the young man trying a costume before a bulb-framed dressing mirror, thrilled at his reflection","MS","eye","push_in","day",False,False,
  "ты примеряешь костюм перед зеркалом в лампах, и впервые видишь не студента, а настоящего артиста."),
 ("A1_SH08","CLOAK_YOUNG","stage_empty","the young man alone on the lit stage rehearsing his lines to the empty house, full of voice and hope","WS","low","push_in","day",False,True,
  "ты репетируешь один на сцене, и твой голос наполняет зал до самых верхних лож."),
 ("A1_SH09","CLOAK_YOUNG","stage_empty","close on the young man's joyful face on stage, eyes lifted to the upper tiers","CU","low","static","day",False,False,
  "ты уже слышишь, как через месяц эти кресла заполнятся, и все восемьсот будут смотреть на тебя."),
 # --- 1989 горло / клиника ---
 ("A1_SH10","CLOAK_YOUNG","theatre_school","the young man pausing in rehearsal, a hand to his throat, his voice catching and failing","MCU","eye","static","day",False,False,
  "за две недели до премьеры голос начинает садиться, и к вечеру ты уже сипишь, как простуженный."),
 ("A1_SH11","CLOAK_YOUNG","theatre_school","close on the young man's worried face as he tries to speak and only a rasp comes out","CU","eye","push_in","day",False,False,
  "ты думаешь, что это простуда, пьёшь горячее с мёдом, и ждёшь, что к утру всё пройдёт само."),
 ("A1_SH12",None,"hospital_throat","a spare late-1980s clinic examination room, a metal bed and an articulated throat-lamp on a steel arm, pale green tiles","EWS","eye","push_in","day",True,False,
  "но не проходит, и в восемьдесят девятом, в двадцать четыре, ты впервые ложишься под нож на связки."),
 ("A1_SH13","CLOAK_YOUNG","hospital_throat","the young man sitting on the edge of the clinic bed under the cold throat-lamp, anxious and small","MS","high","static","day",False,False,
  "врач говорит, что операция простая, и ты подписываешь согласие, и веришь, что к сезону встанешь."),
 ("A1_SH14","CLOAK_YOUNG","hospital_throat","close on the young man's frightened eyes under the clinical light before the procedure","CU","eye","push_in","day",False,False,
  "ты лежишь под холодной лампой и повторяешь про себя монолог, чтобы не забыть его к выписке."),
 ("A1_SH15",None,"hospital_throat","extreme close on a steel instrument trolley with surgical tools laid in a row under sterile light","INSERT","top","push_in","day",True,True,
  "что-то идёт не так, заносят инфекцию, и связки заживают рубцом, и голос больше не возвращается."),
 ("A1_SH16","CLOAK_YOUNG","hospital_throat","the young man in the clinic bed afterward trying to speak, only a broken hoarse whisper emerging","MCU","eye","static","night",False,False,
  "ты открываешь рот, чтобы позвать сестру, и из тебя выходит только чужой надломленный шёпот."),
 ("A1_SH17","CLOAK_YOUNG","hospital_throat","close on the young man's stricken face as he realises his voice is gone for good","CU","eye","push_in","night",False,True,
  "ты пробуешь снова и снова, громче, ещё громче, и понимаешь, что громче уже не будет никогда."),
 ("A1_SH18",None,"hospital_throat","a small high frosted clinic window with cold grey daylight, the room bare and silent","INSERT","high","static","day",True,False,
  "тебе двадцать четыре, и за одним окном остаётся вся жизнь, которую ты уже не сыграешь."),
 ("A1_SH19","CLOAK_YOUNG","street_cobble","the young man walking alone across the cobbled square before the theatre, head down in the rain","WS","high","track","day",False,False,
  "режиссёр отдаёт твою роль другому, мягко, виновато, и ты не находишь чем возразить, кроме сипа."),
 ("A1_SH20","CLOAK_YOUNG","street_cobble","close on the young man's hollow face in the rain, the theatre facade blurred behind him","CU","eye","push_in","day",False,False,
  "ты стоишь под дождём напротив театра и впервые в жизни не знаешь, куда тебе теперь идти."),
 # --- главреж оставляет, вешалка ---
 ("A1_SH21",None,"director_office","a cluttered old theatre director's office, a heavy desk buried in scripts, walls of framed production photos, warm lamp","EWS","eye","push_in","day",True,False,
  "через неделю старый главреж зовёт тебя к себе, и ты идёшь, думая, что это конец, прощание."),
 ("A1_SH22","DIRECTOR_BASE","director_office","the old white-goatee director behind his desk in half-moon glasses, regarding the young man with heavy kindness","MS","eye","static","day",False,False,
  "он смотрит на тебя поверх очков и долго молчит, и в этом молчании ты уже слышишь жалость."),
 ("A1_SH23","CLOAK_YOUNG","director_office","the young man standing before the director's desk, shoulders down, waiting to be dismissed","MCU","high","static","day",False,False,
  "ты ждёшь слов прощания, а он вдруг говорит, что театр начинается с вешалки, и протягивает тебе ключи."),
 ("A1_SH24","DIRECTOR_BASE","director_office","close on the old director's kind shrewd heavy-lidded eyes as he speaks gently","CU","eye","push_in","day",False,False,
  "он говорит, оставайся при театре гардеробщиком, голос не нужен, чтобы подавать людям их пальто."),
 ("A1_SH25","CLOAK_YOUNG","director_office","close on the young man's face taking the offer in, hurt and grateful at once","CU","low","static","day",False,False,
  "ты слышишь в этих словах и милость, и приговор, и киваешь, потому что идти тебе всё равно некуда."),
 ("A1_SH26",None,"cloakroom_counter","the long empty cloakroom counter with its brass rail and rows of bare numbered hooks, seen for the first time","EWS","eye","push_in","day",True,True,
  "так ты впервые встаёшь за эту стойку, и думаешь, что это на сезон, пока не починят голос."),
 ("A1_SH27","CLOAK_YOUNG","cloakroom_counter","the young man behind the counter receiving a coat across the brass rail from an unseen patron","OTS","eye","static","day",False,False,
  "первый зритель протягивает тебе пальто через стойку, и ты впервые в жизни принимаешь чужую вещь."),
 ("A1_SH28","CLOAK_YOUNG","cloakroom_counter","close on the young man's hands taking a heavy coat, uncertain, an actor's hands learning a servant's task","MCU","high","static","day",False,False,
  "ты берёшь его, неловко, и не знаешь ещё, что этот жест ты повторишь миллион раз за тридцать семь лет."),
 ("A1_SH29",None,"cloakroom_counter","extreme close on a single brass numbered token being handed across the counter","INSERT","top","push_in","day",True,False,
  "взамен ты отдаёшь ему латунный номерок, и эта мелочь станет на годы твоей единственной репликой."),
 ("A1_SH30","CLOAK_YOUNG","cloakroom_counter","the young man hanging the coat on a numbered hook, smoothing it flat with his palm out of habit","MS","eye","static","day",False,False,
  "ты вешаешь пальто и невольно разглаживаешь его ладонью, как костюм, и эта привычка останется навсегда."),
 ("A1_SH31","CLOAK_YOUNG","dressing_mirror","the young man sewing a dark velvet collar onto a plain maroon cloakroom smock at the dressing mirror at night","MCU","high","static","night",False,True,
  "по ночам ты подшиваешь к казённому халату бархатный воротник, чтобы не выглядеть совсем уж слугой."),
 ("A1_SH32","CLOAK_YOUNG","dressing_mirror","close on the young man's face in the bulb-framed mirror wearing the maroon smock with its new velvet collar","CU","eye","push_in","night",False,False,
  "в зеркале ты убеждаешь себя, что ты артист на вынужденном перерыве, а не гардеробщик навсегда."),
 ("A1_SH33","CLOAK_YOUNG","cloakroom_counter","the young man leaving a single brass hook deliberately empty at the end of the row","INSERT","eye","push_in","day",False,True,
  "и один крючок, самый первый, ты с первого дня держишь пустым, для пальто, которое однажды повесишь сам."),
 ("A1_SH34","CLOAK_YOUNG","auditorium","the young man slipping into the back of the dark auditorium to watch a rehearsal from the shadows","WS","high","static","day",False,False,
  "в свободный час ты прокрадываешься в зал и смотришь чужие репетиции из темноты последнего ряда."),
 ("A1_SH35","CLOAK_YOUNG","auditorium","close on the young man's face in the dark watching the stage, mouthing another actor's lines silently","CU","eye","push_in","day",False,False,
  "ты беззвучно повторяешь за актёрами их реплики, и твой шёпот теряется в бархате кресел."),
 ("A1_SH36",None,"stage_empty","the empty stage seen from the wings at night, the ghost-light burning, waiting","EWS","eye","push_in","night",True,False,
  "а ночью, когда все уходят, ты впервые выходишь на пустую сцену, просто чтобы постоять на досках."),
 ("A1_SH37","CLOAK_YOUNG","stage_empty","the young man standing alone centre stage at night under the ghost-light, testing a whispered line","MS","low","push_in","night",False,True,
  "ты пробуешь монолог шёпотом, и пустой зал слушает, и впервые тебе кажется, что этого почти хватает."),
 ("A1_SH38","CLOAK_YOUNG","stage_empty","close on the young man's face on the dark stage, eyes shining, half an actor still","CU","low","static","night",False,False,
  "ты говоришь себе, что это временно, ещё сезон, ещё операция, и ты вернёшься на эти доски по-настоящему."),
 ("A1_SH39",None,"street_cobble","the theatre facade across the cobbled square at dusk, lit windows, an advertising column of playbills","WS","eye","pan_right","dusk",True,False,
  "но сезон проходит, и второй, и пятый, и голос не возвращается, и ты привыкаешь раздавать номерки."),
 ("A1_SH40","CLOAK_YOUNG","cloakroom_counter","the young man behind the counter watching elegant patrons pass toward the auditorium without seeing him","WS","eye","static","dusk",False,False,
  "каждый вечер мимо тебя проходят к залу нарядные люди, и ни один не смотрит тебе в лицо."),
 ("A1_SH41","CLOAK_YOUNG","cloakroom_counter","close on the young man learning to read a patron by their coat, fingers on expensive fabric","MCU","eye","push_in","dusk",False,False,
  "ты учишься читать людей по их пальто, по ткани, по запаху, по тому, как они суют тебе номерок."),
 ("A1_SH42","CLOAK_YOUNG","cloakroom_counter","close on the young man's quietly observant face behind the counter, cataloguing the crowd","CU","eye","static","dusk",False,False,
  "ты понимаешь, что пальто говорит о человеке больше, чем он сам когда-либо решится сказать."),
 ("A1_SH43",None,"cloakroom_counter","a dense wall of hanging coats of every kind on the numbered hooks, a quiet ordered archive","WS","eye","pan_left","dusk",True,True,
  "и постепенно эта стена чужих пальто становится тебе ближе, чем сцена, на которую тебя не пустили."),
 ("A1_SH44","CLOAK_YOUNG","backstage_lost","the young man taking an unclaimed coat off the lost-property rail backstage at night, considering it","MS","eye","static","night",False,False,
  "однажды ночью ты снимаешь с вешалки невостребованное пальто и впервые надеваешь чужую жизнь на себя."),
 ("A1_SH45","CLOAK_YOUNG","stage_empty","the young man on the empty stage at night wearing the stranger's coat, beginning to play its owner","WS","low","push_in","night",False,True,
  "ты выходишь в нём на сцену и играешь его хозяина, и пустой зал впервые получает своего актёра."),
 ("A1_SH46","CLOAK_YOUNG","stage_empty","close on the young man's transformed face on the dark stage, fully in character as someone else","CU","eye","push_in","night",False,False,
  "ты находишь, что чужая жизнь идёт тебе лучше своей, и в чужом пальто шёпот звучит почти как голос."),
 ("A1_SH47",None,"stage_empty","the empty velvet seats from the stage at night, one ghost-light, profound silence","EWS","eye","static","night",True,False,
  "так начинается твой ночной театр, тайный, на одного зрителя, который и есть ты сам."),
 ("A1_SH48","CLOAK_YOUNG","cloakroom_counter","the young man back behind the counter by day, smoothing a coat, his secret kept","MCU","high","static","day",False,False,
  "днём ты снова просто гардеробщик, разглаживаешь чужие пальто и держишь крючок номер один пустым."),
 ("A1_SH49","CLOAK_YOUNG","cloakroom_counter","close on the young man's face behind the counter, hope thinning into patience","CU","eye","push_in","day",False,False,
  "ты ещё ждёшь, что выкрикнут твоё имя, но ждёшь уже тише, и сам этого пока не замечаешь."),
 ("A1_SH50",None,"cloakroom_counter","the single deliberately empty brass hook number one among the full ranks of coats","INSERT","eye","push_in","day",False,True,
  "тебе двадцать пять, крючок номер один пуст, и впереди ещё тридцать шесть лет этой тишины."),
]

seed_act("cold_open", PAL_NIGHT,  COLD, render_mode="animated")
seed_act("origin",    PAL_SCHOOL, A1,   render_mode="animated")
