# -*- coding: utf-8 -*-
"""layoff act A3 signs (Палыча убрали, сменщик, встреча без темы). PYTHONIOENCODING=utf-8 python scripts/_seed_layoff_A3.py"""
from _layoff_engine import seed_act
PAL="cooling office palette, grey-blue and muted steel, overcast daylight, lengthening uneasy shadows"
S=[
 ("A3_SH01","BOSS_BASE","open_floor","a medium shot of a balding heavyset boss on a hushed phone call, half-turned away, a chunky watch on his wrist","MS","eye","static","day",False,False,
  "в начале года начальник всё чаще говорит по телефону вполголоса и отворачивается, когда ты проходишь мимо."),
 ("A3_SH02",None,"open_floor","a macro insert of a glass meeting room with its blinds fully drawn, the dim shapes of seated people behind them","INSERT","eye","static","day",True,False,
  "в стеклянной переговорке который день сидят люди из головного офиса, и жалюзи там всегда опущены."),
 ("A3_SH03","GEROY_MAIN","your_desk","a medium close-up of the man at his desk glancing toward the closed meeting room, a flicker of unease","MCU","eye","static","day",False,False,
  "ты ловишь в воздухе слово реструктуризация и говоришь себе, что тебя это точно не коснётся."),
 ("A3_SH04","PALYCH_BASE","open_floor","a wide shot of a kindly grey-moustached older man packing a small cardboard box at his desk, a battered thermos on top","WS","eye","static","day",False,False,
  "палыч молча складывает в коробку фотографию и термос, проработав в конторе ровно тридцать лет."),
 ("A3_SH05","PALYCH_BASE","open_floor","a close-up of the old man's tired warm smile as he speaks, the thermos in his hands","CU","eye","static","day",False,False,
  "он улыбается тебе устало и говорит, что оптимизация это просто слово, за которым стоит чей-то стол."),
 ("A3_SH06",None,"open_floor","a macro insert of a cleared empty desk and a pale clean rectangle on the partition wall where a certificate hung","INSERT","top","static","day",True,False,
  "на его месте остаётся пустой стол и светлый прямоугольник на стене, где висела его грамота."),
 ("A3_SH07","GEROY_MAIN","open_floor","a medium shot of the man standing and watching an unseen colleague leave, no farewell crowd around","MS","eye","static","day",False,False,
  "ты смотришь, как он уходит, и никто не устраивает проводов, будто человека просто отключили от сети."),
 ("A3_SH08",None,"open_floor","an extreme close-up of a single forgotten paperclip on a bare cleared desk surface","ECU","top","static","day",True,False,
  "на опустевшем столе лежит один забытый скрепыш, и через день стол займёт кто-то другой."),
 ("A3_SH09","REPL_BASE","open_floor","a wide shot of a confident young man with an undercut and white earbuds settling in at the next desk","WS","eye","static","day",False,False,
  "к твоему ряду подсаживают парня лет двадцати пяти, в белых наушниках, и он сразу чувствует себя как дома."),
 ("A3_SH10","REPL_BASE","open_floor","a medium close-up of the young man nodding without removing an earbud, a casual easy face","MCU","eye","static","day",False,False,
  "он кивает тебе, не вынимая наушник, и спрашивает, где тут кофемашина, а не где сидит начальник."),
 ("A3_SH11","GEROY_MAIN","open_floor","a close-up of the older man offering help, a slightly forced helpful expression","CU","eye","static","day",False,False,
  "ты предлагаешь показать ему, как тут всё устроено, а он отвечает, что разберётся сам по инструкции."),
 ("A3_SH12","GEROY_MAIN","open_floor","a medium shot of the older man leaning to explain at the young man's monitor, a faint dawning unease","MS","over","static","day",False,False,
  "ты всё равно вводишь его в курс дела и замечаешь, что он делает за час то, на что у тебя уходит полдня."),
 ("A3_SH13",None,"your_desk","a macro insert of a desk calendar screen showing a new untitled meeting block, just a time and an empty subject line","INSERT","top","static","day",True,False,
  "в твоём календаре появляется новая встреча без названия, просто время и пустая строка темы."),
 ("A3_SH14","GEROY_MAIN","your_desk","a close-up of the man staring at the screen, trying to convince himself it is nothing","CU","eye","push_in","day",False,False,
  "ты смотришь на эту пустую строку и убеждаешь себя, что речь наверняка про новый проект."),
 ("A3_SH15","BOSS_BASE","open_floor","a medium shot of the boss walking past, looking somewhere above the man and not greeting him","MS","eye","track","day",False,False,
  "начальник проходит мимо твоего стола, смотрит куда-то поверх тебя и не здоровается, как обычно."),
 ("A3_SH16","GEROY_MAIN","your_desk","a medium close-up of the man at his desk silently reassuring himself, a tense jaw","MCU","eye","static","day",False,False,
  "ты повторяешь про себя, что ты тут девятнадцать лет и что надёжных не увольняют."),
 ("A3_SH17","GEROY_MAIN","your_desk","an extreme close-up of the man's fingers gripping the access card at his chest a little too tightly","ECU","eye","push_in","day",False,True,
  "твоя рука снова находит пропуск на груди, но в этот раз пальцы сжимают его чуть крепче."),
 ("A3_SH18",None,"open_floor","a wide dusk view of the office floor, one desk lamp lit beside a dark emptied desk nearby","WS","eye","static","dusk",True,False,
  "к вечеру на этаже опять горит твоя лампа, а рядом тёмным пятном стоит пустой стол палыча."),
 ("A3_SH19","GEROY_MAIN","your_desk","a medium close-up of the man working late, the old certainty visibly thinner on his face","MCU","eye","static","night",False,False,
  "ты остаёшься дольше всех, как всегда, только прежней уверенности в этом уже почти не осталось."),
 ("A3_SH20","GEROY_MAIN","street_tower","an extreme wide dusk view of the lit glass tower with hundreds of windows, the tiny lone figure of the man standing on the pavement far below","EWS","low","static","dusk",False,True,
  "башня светится в сумерках сотнями окон, ты стоишь под ней совсем маленький, а завтра та самая встреча."),
]
if __name__=="__main__": seed_act("signs", PAL, S, render_mode="animated")
