# -*- coding: utf-8 -*-
"""Batch 4: act08_alone + act09_rush (Part II)."""
from _flat_earth_engine import seed_act

PAL_ALONE = "hollow isolated palette, single-lamp warmth in a cold empty house, grey-brown loneliness"
A8 = [
 ("A8_SH01",None,"dawson_house_living","a man alone at night in a map-covered living room emptied of furniture, sitting cross-legged among his charts","WS","high","push_in","night",False,False,
  "теперь ты совсем один в пустом доме, и говорить тебе не с кем, кроме своих карт на стенах."),
 ("A8_SH02","RAY","dawson_house_living","a man setting up a phone on a stack of books to film himself, speaking earnestly into the lens, the map behind","MCU","eye","static","night",False,False,
  "и ты начинаешь снимать себя на телефон, для тех, кто однажды захочет узнать, как всё было на самом деле."),
 ("A8_SH03","RAY","dawson_house_living","close on the man's earnest lit face speaking directly to a camera lens, certain, the charts blurred behind","CU","eye","push_in","night",False,False,
  "если ты смотришь эту запись, говоришь ты в камеру, значит, я уже дошёл, и значит, я был прав."),
 ("A8_SH04",None,"dawson_house_living","extreme close on a phone screen showing the man recording himself among the maps, a red record dot blinking","INSERT","eye","static","night",False,True,
  "ты записываешь часы и часы, и складываешь их в коробку, своё завещание тем, кто поверит после тебя."),
 ("A8_SH05",None,"movement_backroom","the exterior of a dark shuttered strip-mall storefront at dusk, a faded for-lease sign taped inside the glass","WS","eye","push_in","dusk",True,False,
  "ты идёшь во вторник на собрание, как все эти годы, и находишь подсобку тёмной и запертой наглухо."),
 ("A8_SH06","RAY","movement_backroom","a man cupping his hands to the dark glass of a closed shop, peering in at stacked empty chairs, confused","MCU","over","push_in","dusk",False,False,
  "ты прижимаешься к стеклу, а внутри пусто, стулья свалены в угол, и баннера со стены давно нет."),
 ("A8_SH07",None,"east_nash_street","a stranger on a sidewalk shrugging and walking away from another man outside a closed shop at dusk","WS","eye","static","dusk",False,False,
  "прохожий, из ваших бывших, говорит тебе, ты что, не слышал, эрл пропал ещё месяц назад, с деньгами."),
 ("A8_SH08",None,"east_nash_street","extreme close on a local newspaper page, a headline about a flat-earth organiser vanishing with members' funds","INSERT","top","push_in","dusk",False,True,
  "в местной газете заметка, организатор движения исчез, прихватив кассу съезда и взносы за приборы."),
 ("A8_SH09","RAY","east_nash_street","a man sitting heavily on a curb at dusk, staring at a small enamel pin in his open palm, stunned","MCU","high","static","dusk",False,False,
  "ты садишься на бордюр, и держишь на ладони его значок, тот самый, плоский диск, и не знаешь, что думать."),
 ("A8_SH10",None,"east_nash_street","extreme close on a flat-earth disc enamel pin lying in a man's dirty open palm under fading light","ECU","top","push_in","dusk",False,True,
  "оказывается, эрл просто продавал вам веру, по сорок, по двести долларов, и в неё-то сам и не верил."),
 ("A8_SH11","RAY","east_nash_street","close on the man's face moving from betrayal to a strange hardening calm, jaw setting","CU","eye","push_in","dusk",False,False,
  "но ты говоришь себе, эрл был слаб, его сломали или купили, а правда от этого не стала менее ровной."),
 ("A8_SH12","RAY","east_nash_street","a lone man walking home down a darkening street, smaller now, the disc pin closed in his fist","WS","eye","track","night",False,False,
  "ты идёшь домой один, и впервые понимаешь, что между тобой и всем миром не осталось ни одного человека."),
 ("A8_SH13","RAY","dawson_house_living","a man pulling a pinned group photo down from the map wall and looking at it, the empty house around him","MCU","eye","static","night",False,False,
  "дома ты снимаешь со стены вашу общую фотографию, своих, и долго смотришь на лица, которых больше нет."),
 ("A8_SH14",None,"dawson_house_living","extreme close on a man's hand dropping a creased group photo into a box, the smiling faces face-down","ECU","high","static","night",False,True,
  "ты кладёшь её лицом вниз в коробку, и говоришь, ничего, я не нуждаюсь в них, я увижу всё сам."),
 ("A8_SH15","RAY","dawson_house_living","a man spreading a huge map flat across the bare floor and kneeling over it with a marker, focused","WS","high","push_in","night",False,False,
  "ты раскладываешь на полу огромную карту, и впервые чертишь не доказательство, а маршрут, на юг."),
 ("A8_SH16",None,"dawson_house_living","extreme close on a finger tracing a route down a flat-disc map from a northern city toward the icy southern rim","ECU","top","push_in","night",False,True,
  "твой палец ведёт линию от нэшвилла вниз, к большой воде, и дальше, к самому кольцу льда по краю."),
 ("A8_SH17","RAY","dawson_house_living","a man kneeling back from the map on the floor, eyes alight with a calm fixed purpose, no longer despairing","MCU","low","push_in","night",False,False,
  "хватит спорить с ними, говоришь ты вслух пустому дому, я просто дойду до края и увижу его своими глазами."),
 ("A8_SH18",None,"dawson_house_living","a single lamp burning over a man bent all night over a route map on the bare floor, the window dark","WS","high","static","night",True,False,
  "ты не спишь всю ночь, считаешь мили, автобусы, деньги, и впервые за годы у тебя есть ясный план."),
 ("A8_SH19",None,"dawson_house_living","extreme close on a worn brass folding ruler laid carefully across the southern edge of the floor map","INSERT","top","push_in","night",False,True,
  "ты кладёшь дедову линейку поперёк карты, на самый край, и тебе кажется, что отец одобрил бы это."),
 ("A8_SH20","RAY","dawson_house_living","close on a man's calm certain face at first light, decision made, the route map glowing at the window","CU","low","push_in","dawn",False,False,
  "к рассвету решение принято, и тебе спокойно, спокойнее, чем было все эти годы споров и обид."),
 ("A8_SH21",None,"ridge_overlook","a flat misted dawn vista of southern farmland under an immense level horizon, a road running away to the south","EWS","eye","pan_right","dawn",True,False,
  "где-то там, далеко на юге, лежит ровная линия, к которой ты шёл всю жизнь, и теперь ты к ней пойдёшь."),
 ("A8_SH22","RAY","dawson_house_living","a man rolling up the route map decisively in the bare dawn-lit room, rucksack waiting by the door","MCU","eye","static","dawn",False,False,
  "ты сворачиваешь карту, и смотришь на рюкзак у двери, и понимаешь, что держит тебя здесь уже ничего."),
]

PAL_RUSH = "stripped transitional palette, cold morning greys and sodium-lamp amber, bare walls and asphalt"
A9 = [
 ("A9_SH01",None,"east_nash_street","a modest Nashville house with a bank repossession notice and a realtor sign staked in the bare front yard","WS","eye","push_in","day",False,False,
  "банк забирает дом за твои долги, девяносто восемь тысяч ушли коту под хвост, и тебе уже всё равно."),
 ("A9_SH02","RAY","dawson_kitchen","a man laying a set of house keys on a desk before an official's hand, calm, signing a paper","OTS","over","static","day",False,False,
  "ты отдаёшь ключи без сожаления, тебе не нужен дом, тебе нужна только дорога на юг, к краю."),
 ("A9_SH03",None,"east_nash_street","a front-lawn sale of telescopes, lasers, levels and old furniture spread on blankets, price tags on everything","WS","high","pan_right","day",False,False,
  "ты выносишь на газон все свои приборы, телескопы, лазеры, уровни, и продаёшь за бесценок прохожим."),
 ("A9_SH04","RAY","east_nash_street","a man handing a boxed laser device to a stranger and taking folded bills without a second glance","MCU","eye","static","day",False,False,
  "ты отдаёшь за двадцатку прибор, за который платил три сотни, и тебе не жалко, всё это уже не нужно."),
 ("A9_SH05",None,"east_nash_street","extreme close on a thin roll of cash being counted into a weathered hand over a blanket of sale goods","ECU","top","push_in","day",False,True,
  "к вечеру у тебя на руках двенадцать тысяч наличными, и это всё, что осталось от целой жизни."),
 ("A9_SH06",None,"dawson_house_living","extreme close on a rucksack being packed on a bare floor: a folded map, canned food, a roll of cash, the brass ruler on top","INSERT","top","push_in","day",False,True,
  "ты собираешь рюкзак, карта, консервы, деньги, и сверху, бережнее всего, отцовскую латунную линейку."),
 ("A9_SH07","RAY","dawson_house_living","a man standing in the middle of a completely stripped empty house taking one long last look around","WS","eye","pull_out","day",False,False,
  "ты стоишь посреди голых стен, где ещё видны светлые прямоугольники от снятых карт и фотографий."),
 ("A9_SH08",None,"dawson_house_living","extreme close on faded clean rectangles on a wall where maps and family photos used to hang for years","ECU","eye","pan_left","day",False,True,
  "на обоях остались бледные следы, контур твоей жизни, и контур семьи, которую ты не сумел удержать."),
 ("A9_SH09","RAY","east_nash_street","a man at a payphone on a street corner, receiver to his ear, waiting, no answer coming, rucksack on his back","MCU","eye","static","day",False,False,
  "у телефона-автомата ты набираешь номер линды, и слушаешь гудки, и никто не берёт трубку, никто."),
 ("A9_SH10","RAY","east_nash_street","close on the man's face at the payphone leaving a quiet message into silence, the receiver against his cheek","CU","eye","push_in","day",False,False,
  "ты говоришь в трубку, я ухожу доказать, и когда докажу, вернусь, и тогда ты поймёшь, и коди поймёт."),
 ("A9_SH11",None,"east_nash_street","a man with a full rucksack walking away down an empty Nashville street at dawn, back to the camera","WS","low","track","dawn",False,True,
  "и ранним утром ты уходишь пешком, с рюкзаком за спиной, не оборачиваясь на пустой бывший дом."),
 ("A9_SH12",None,"greyhound_station","a worn intercity bus terminal at night, a long ticket counter, a backlit departures board, rows of plastic seats","WS","eye","push_in","night",False,False,
  "к ночи ты на автовокзале грейхаунд, под гудящими лампами, среди таких же, кому некуда возвращаться."),
 ("A9_SH13","RAY","greyhound_station","a man at a ticket counter sliding cash under the glass, the clerk's hand pushing back a single ticket","OTS","over","static","night",False,False,
  "ты берёшь билет в один конец, как можно дальше на юг, к большой воде, и платишь наличными."),
 ("A9_SH14",None,"greyhound_station","extreme close on a one-way bus ticket held in a weathered hand, a southern destination printed across it","INSERT","top","push_in","night",False,True,
  "в один конец, написано на билете, и эти три слова кажутся тебе самыми честными за всю твою жизнь."),
 ("A9_SH15","RAY","greyhound_station","a man sitting alone in a row of empty plastic terminal seats under harsh fluorescent light, rucksack at his feet","WS","high","static","night",False,False,
  "ты ждёшь свой рейс один в ряду пустых кресел, и тебе не страшно, тебе впервые легко и ясно."),
 ("A9_SH16","RAY","greyhound_station","close on the man watching a flickering departures board, the brass ruler poking from his open rucksack","CU","low","push_in","night",False,False,
  "на табло мигают южные города, и каждый из них на шаг ближе к краю, и сердце у тебя заходится, как в детстве."),
 ("A9_SH17",None,"greyhound_station","a long intercity coach pulling up to a platform under sodium lights, its door hissing open, exhaust drifting","WS","low","static","night",True,False,
  "подаётся ночной автобус, открывает двери, и ты заходишь первым, и занимаешь место у самого окна."),
 ("A9_SH18","RAY","interstate_south","a man at a dark bus window watching city lights slide past, his faint reflection over the glass","MS","eye","static","night",False,False,
  "город уплывает за стеклом, огни, развязки, и ты смотришь, как всё это остаётся позади навсегда."),
 ("A9_SH19","RAY","interstate_south","close on a man's gaunt certain face reflected in the dark bus window over the passing night","CU","eye","push_in","night",False,False,
  "в чёрном стекле твоё отражение, и за ним ровная тёмная земля, и ты шепчешь, я иду, я наконец иду."),
 ("A9_SH20",None,"interstate_south","a long straight interstate at first light seen from a moving bus, the road running dead level to a vanishing point","EWS","eye","push_in","dawn",True,True,
  "на рассвете шоссе уходит ровно в точку на горизонте, и нигде, нигде оно не загибается вниз, ты проверял."),
 ("A9_SH21","RAY","interstate_south","a man pressing a brass folding ruler against the bus window, aligning it to the flat dawn horizon outside","MCU","eye","push_in","dawn",False,True,
  "ты прикладываешь линейку к стеклу, к линии горизонта, и она ложится ровно, и тот холодок снова с тобой."),
 ("A9_SH22",None,"interstate_south","flat southern farmland streaming past a bus window at dawn under an enormous level sky, fences and silos","WS","eye","pan_left","dawn",True,False,
  "земля за окном всё ровнее, всё ниже, поля без конца, и ты чувствуешь, что приближаешься к чему-то огромному."),
 ("A9_SH23","RAY","interstate_south","a man dozing against a bus window in dawn light, the rucksack hugged to his chest, the ruler in his hand","CU","eye","static","dawn",False,False,
  "ты задрёмываешь, прижав рюкзак к груди, и тебе снится ровная вода, всё ближе, всё шире, всё южнее."),
 ("A9_SH24",None,"rural_gas_south","a lonely rural gas station at midday seen from a slowing bus, one pump, a sagging clapboard store, kudzu fence","WS","high","static","day",True,False,
  "автобус высаживает тебя на глухой южной заправке, дальше его маршрут не идёт, дальше только ты сам."),
 ("A9_SH25","RAY","rural_gas_south","a man stepping down from a bus onto a cracked rural forecourt with his rucksack, squinting at the bright south","MS","low","static","day",False,False,
  "ты ступаешь на горячий потрескавшийся асфальт, и юг встречает тебя зноем, тишиной и пустой дорогой."),
 ("A9_SH26","RAY","rural_gas_south","close on a man's resolute sunburnt face looking down a long empty southern road, the ruler gripped in his fist","CU","low","push_in","day",False,True,
  "ты смотришь на дорогу, что уходит ровно к югу, сжимаешь линейку, и идёшь дальше пешком, к самому краю."),
]

seed_act("act08_alone", PAL_ALONE, A8)
seed_act("act09_rush",  PAL_RUSH,  A9)
