# -*- coding: utf-8 -*-
"""coffee A2 barista (18) + A3 championship (21). Run: PYTHONIOENCODING=utf-8 python scripts/_seed_coffee_A2A3.py"""
from _coffee_engine import seed_act

P_BARISTA="busy chain-cafe palette, clean retail whites warmed by espresso browns and steam, brisk and bright"
P_CHAMP="competition palette, stage spotlight gold over polished steel, confetti warmth, festive and keen"

BARISTA=[
 ("A2_SH01",None,"chain_cafe","a wide establishing view of a busy corporate coffee bar at morning rush, twin espresso machines steaming, a queue at the counter","WS","eye","push_in","day",True,False,
  "в восемнадцать ты надеваешь форменный фартук сетевой кофейни и встаёшь за высокую стойку."),
 ("A2_SH02","MARK_BASE","chain_cafe","a medium close-up of a calm grey-moustached barista of forty-five with a coffee-bean tattoo, sizing up a new trainee kindly","MCU","eye","static","day",False,False,
  "твой наставник Марк: сорок пять лет, седые усы и кофейное зерно, вытатуированное на предплечье."),
 ("A2_SH03","MARK_BASE","chain_cafe","a close-up of the moustached barista tilting a steel milk pitcher to a trainee's ear at the steam wand","CU","eye","static","day",False,False,
  "он учит взбивать молоко по звуку: правильная пена шипит, как прибой, а не свистит."),
 ("A2_SH04","ASYA_TEEN","chain_cafe","a medium shot of a copper-haired young barista in a cap working the machine flat out, cups queuing on the rail","MS","eye","static","day",False,False,
  "в первую смену через твои руки проходит двести стаканов, и к вечеру дрожат запястья."),
 ("A2_SH05",None,None,"an extreme close-up insert of spoiled milk being poured away into a steel sink, steam still rising","ECU","top","static","day",True,False,
  "восемь порций за день уходят в раковину, и ты каждый раз молча наливаешь заново."),
 ("A2_SH06",None,"chain_cafe","a wide view of the coffee bar at closing, chairs going up, one window still amber against the blue street","WS","eye","tilt_down","evening",True,False,
  "смена заканчивается в десять, и ты идёшь домой, пропахшая кофе насквозь и очень счастливая."),
 ("A2_SH07","ASYA_TEEN","family_flat","a medium shot of the young woman practising latte pours at the family stove at night, saucers lined up like students","MS","high","static","night",False,False,
  "по ночам ты тренируешь руку дома: турка, ложечка корицы и шеренга блюдец для узоров."),
 ("A2_SH08","OBJ:cinnamon",None,"an extreme close-up macro insert of the cinnamon jar nearly empty, its hand-written label worn soft at the corners","ECU","eye","static","night",True,False,
  "баночка корицы пустеет за месяц, и бабушкина этикетка совсем стёрлась по краям."),
 ("A2_SH09","ASYA_TEEN","chain_cafe","a medium close-up of the young barista setting a double shot with a cinnamon sun before a grumpy coat-shouldered customer seen from behind","MCU","eye","static","day",False,False,
  "самого хмурого гостя утренней очереди ты побеждаешь двойным с солнышком, и он начинает здороваться."),
 ("A2_SH10","ASYA_TEEN","chain_cafe","a close-up of the young barista's freckled conspiratorial wink over the counter steam","CU","eye","push_in","day",False,False,
  "у тебя появляется собственная примета: если первое солнышко вышло ровным, день будет добрым."),
 ("A2_SH11",None,"chain_cafe","a wide view of the counter with a queue visibly bending toward one end of the bar","WS","high","static","day",True,False,
  "постоянные гости начинают вставать в очередь именно к твоей машине, и это замечают все."),
 ("A2_SH12","ASYA_TEEN","chain_cafe","a medium shot of the young barista handing over two cups at once, greeting someone by name past the till","MS","eye","static","day",False,False,
  "ты запоминаешь, кто пьёт двойной без сахара, а кто просит тёплое молоко для собаки."),
 ("A2_SH13",None,None,"an extreme close-up insert of a tin money box with a taped paper label, a young hand pressing coins in","ECU","top","static","evening",True,True,
  "с каждой смены ты откладываешь в жестяную банку с надписью на крышке: на кофейню."),
 ("A2_SH14","ASYA_TEEN","gran_kitchen","a medium shot of the young woman at the grandmother's table with a cake box and a proud written list","MS","eye","static","day",False,False,
  "с первой зарплаты ты везёшь бабушке коробку эклеров и подробный отчёт о каждой смене."),
 ("A2_SH15","GRAN_BASE","gran_kitchen","a close-up of the grandmother listening with narrowed happy eyes, pushing a refilled cinnamon jar across the table","CU","eye","push_in","day",False,False,
  "бабушка слушает про двести стаканов, качает головой и досыпает тебе корицы в дорогу."),
 ("A2_SH16",None,"street_corner","a wide view of a street corner with an empty shop unit, a huge dusty arched window catching the sunset","WS","eye","static","evening",True,False,
  "по дороге домой ты каждый вечер проходишь мимо пустого углового зала с огромным окном."),
 ("A2_SH17","ASYA_TEEN","street_corner","a medium close-up of the young woman at the dusty glass, palm resting on it, eyes mapping the room inside","MCU","eye","push_in","evening",False,True,
  "ты прикладываешь ладонь к пыльному стеклу и мысленно расставляешь внутри шесть столиков."),
 ("A2_SH18",None,None,"an extreme close-up insert of a palm print left on dusty glass, warm light glowing through the mark","ECU","eye","static","evening",True,False,
  "на стекле остаётся след твоей ладони, и ты не стираешь его, уходя."),
 ("A2_SH19",None,"empty_unit","a wide view through the window of a bare wooden floor with a long square of evening sun lying across it","WS","pov","static","evening",True,False,
  "зал стоит пустой третий год, и по его дощатому полу днями ползёт только квадрат солнца."),
 ("A2_SH20","ASYA_TEEN","chain_cafe","a medium shot of the young barista taking a weekend shift, two schedules pinned above her station","MS","eye","static","day",False,False,
  "ты берёшь дополнительные смены по выходным, и банка тяжелеет медленно, но очень честно."),
 ("A2_SH21",None,None,"an extreme close-up insert of a paper wall calendar with every square filled in neat pencil handwriting","ECU","top","push_in","day",True,False,
  "в твоём календаре нет пустых клеток: смена, тренировка, смена, и так два года подряд."),
]

CHAMP=[
 ("A3_SH01",None,"champ_hall","a wide establishing view of a bright barista championship hall, stage workstations under spotlights, banners and an audience","WS","eye","push_in","day",True,False,
  "в двадцать один ты впервые выходишь на городской чемпионат бариста под настоящие софиты."),
 ("A3_SH02","ASYA_TEEN","champ_hall","a medium shot of the copper-haired competitor at her stage station, laying out pitchers with shaking care","MS","eye","static","day",False,False,
  "на станции перед тобой таймер, блестящий питчер и десять минут на всю твою программу."),
 ("A3_SH03",None,None,"an extreme close-up insert of a stage countdown timer beside a polished espresso machine, digits glowing","ECU","eye","static","day",True,False,
  "регламент простой: десять минут, четыре напитка и судьи, которые не улыбаются до объявления мест."),
 ("A3_SH04","ASYA_TEEN","champ_hall","a medium close-up of the competitor mid-flow, pouring milk with a steady lowered wrist, spotlight on her hands","MCU","eye","push_in","day",False,False,
  "руки вспоминают всё сами: две тысячи ночных блюдец на родительской кухне были не зря."),
 ("A3_SH05",None,None,"an extreme close-up insert of a spoon of cinnamon finishing a neat sun on a competition cappuccino","ECU","top","push_in","day",True,True,
  "на финальной чашке ты рисуешь корицей солнышко, хотя все вокруг рисуют сердца и листья."),
 ("A3_SH06",None,"champ_hall","a medium view of the judges' table from behind, one judge reaching back for a particular cup a second time","MS","over","static","day",True,False,
  "судьи пробуют молча, и один из них возвращается к твоей чашке во второй раз."),
 ("A3_SH07",None,None,"an extreme close-up insert of a results board with a name lit on the second line, applause blurred beyond","ECU","eye","static","day",True,False,
  "на табло твоя фамилия загорается второй строкой, и зал хлопает громче, чем первой."),
 ("A3_SH08",None,"champ_hall","a wide view of the hall on its feet applauding toward the stage stations, confetti light in the beams","WS","low","static","day",True,False,
  "второе место на первом же чемпионате — это почти победа, говорят все вокруг тебе хором."),
 ("A3_SH09","ASYA_TEEN","champ_hall","a medium close-up of the competitor holding her diploma, smile real but jaw set on something","MCU","eye","static","day",False,False,
  "второе место жжётся ровно десять минут, и ты специально засекаешь их по чемпионатному таймеру."),
 ("A3_SH10","ASYA_TEEN","champ_hall","a close-up of the young woman sitting on the stage edge in the emptying hall, diploma across her knees","CU","eye","push_in","evening",False,False,
  "когда зал пустеет, ты сидишь на краю сцены, и злиться оказывается совершенно не на кого."),
 ("A3_SH11",None,"champ_hall","a wide view of the hall after the event, folded chairs, one worklight, long quiet shadows","WS","eye","pan_left","evening",True,False,
  "остаются рабочий свет, запах кофе на весь зал и одна простая мысль про своё."),
 ("A3_SH12","MARK_BASE","champ_hall","a medium shot of the grey-moustached mentor sitting down beside her on the stage edge, unhurried","MS","eye","static","evening",False,True,
  "Марк находит тебя там, садится рядом и говорит негромко: сети начинаются с одной турки."),
 ("A3_SH13","ASYA_TEEN","champ_hall","a close-up of the young woman's face as the sentence lands, resolve replacing the sting","CU","eye","push_in","evening",False,False,
  "в эту самую минуту обида дорастает до решения: хватит просто копить, пора считать."),
 ("A3_SH14","ASYA_TEEN","family_flat","a medium shot of the young woman opening a fat new notebook at the round table, pencils sharpened in a row","MS","high","static","night",False,False,
  "дома ты заводишь толстую тетрадь и пишешь на первой странице: моя кофейня, план."),
 ("A3_SH15","OBJ:notebook",None,"an extreme close-up macro insert of the fat notebook bursting with clippings and sketches, a rubber band straining around it","ECU","top","static","night",True,True,
  "за зиму тетрадь распухает до девяноста страниц: аренда, машина, зерно, чашки, вывеска."),
 ("A3_SH16",None,"city_bright","a wide view of the pastel main street in crisp winter sun, café windows glowing along the block","WS","eye","pan_right","day",True,False,
  "ты ходишь по городу и считаешь чужие окна, столики и улыбки гостей на выходе."),
 ("A3_SH17","ASYA_TEEN","market_beans","a medium shot of the young woman at a roastery counter, shaking hands with someone across sacks of beans","MS","eye","static","day",False,False,
  "у старого обжарщика ты выторговываешь право покупать зерно мелкими партиями, но всегда свежим."),
 ("A3_SH18",None,None,"an extreme close-up insert of light-roasted coffee beans poured into small cupped hands, steamy roastery light","ECU","eye","push_in","day",True,False,
  "он высыпает тебе в ладони горсть светлой обжарки и велит нюхать, пока тёплая."),
]

if __name__=="__main__":
    seed_act("barista",P_BARISTA,BARISTA)
    seed_act("championship",P_CHAMP,CHAMP)
