# -*- coding: utf-8 -*-
"""surrogate A8 third_birth + A9 barren. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_surrogate_A8A9.py"""
from _surrogate_engine import seed_act

P_TB="raw broken palette, pale hospital green and blood-warm skin against cold, the moment it all breaks"
P_BAR="grief-emptied palette, cold grey-blue and washed white, the flat silence after loss"

TB=[
 ("A8_SH01",None,"maternity_ward","a wide view of a tense maternity ward at night, pale green walls and staff moving urgently past a delivery-room door","WS","eye","push_in","night",True,False,
  "в тридцать шесть третьи роды даются тяжело, врачи напряжены, и что-то в этот раз идёт не так."),
 ("A8_SH02","HERO_MID","maternity_ward","a medium shot of the woman of thirty-six in a long hard labour on a hospital bed, drained and pale","MS","eye","static","night",False,False,
  "ты рожаешь долго и мучительно, теряешь много крови, и на секунду тебе кажется, что не выживешь."),
 ("A8_SH03",None,None,"an extreme close-up macro insert of a hospital ID bracelet on a pale wrist gripping the bed rail, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,False,
  "на запястье снова браслет с чужой фамилией, и ты цепляешься за него взглядом, чтобы не потерять сознание."),
 ("A8_SH04","HERO_MID","maternity_ward","a close-up of the exhausted woman reaching weakly toward the newborn at the first cry","CU","eye","push_in","night",False,False,
  "ты слышишь третий первый крик и, обессиленная, всё-таки тянешься к свёртку руками."),
 ("A8_SH05",None,"maternity_ward","a medium shot of a masked nurse hesitating, briefly laying a swaddled newborn on the mother's chest","MS","over","static","night",True,False,
  "в этот раз медсестра медлит и на миг кладёт свёрток тебе на грудь, чтобы ты отдышалась."),
 ("A8_SH06","HERO_MID","maternity_ward","a close-up of the woman holding the swaddle a second too long, something breaking in her face","CU","eye","push_in","night",False,True,
  "и ты держишь его на секунду дольше, чем можно, вдыхаешь запах, и внутри что-то ломается навсегда."),
 ("A8_SH07",None,None,"an extreme close-up macro insert of a newborn's tiny hand gripping an adult finger, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","push_in","night",True,False,
  "крошечная рука сжимает твой палец, и в это мгновение договор, деньги и правила перестают что-либо значить."),
 ("A8_SH08",None,"maternity_ward","a medium shot of a nurse gently carrying the swaddled newborn away down the ward","MS","over","static","night",True,False,
  "но его забирают, как забирали прежних, и твоя рука остаётся пустой, сжатой в кулак."),
 ("A8_SH09",None,None,"an extreme close-up macro insert of small scissors snipping a third hospital ID bracelet off a wrist, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,True,
  "медсестра срезает третий браслет, и вместе с ним из тебя будто вырезают что-то живое."),
 ("A8_SH10","HERO_MID","hospital_room","a close-up of the woman weeping silently into a pillow so she is not heard","CU","eye","static","night",False,False,
  "ты не плачешь, ты воешь тихо, в подушку, чтобы не услышали, и не можешь остановиться."),
 ("A8_SH11",None,"hospital_room","a wide view of a bare recovery room with a drip stand and an empty space where a cradle should be","WS","eye","static","day",True,False,
  "палата, капельница, пустота, и впервые тебе всё равно, заплатили тебе или нет."),
 ("A8_SH12","RICHW_BASE","rich_home","a medium close-up of a third intended mother weeping with joy over a newborn in a bright home","MCU","eye","static","day",False,False,
  "где-то в большом доме третья пара плачет от счастья над ребёнком, которого ты родила."),
 ("A8_SH13","RICHW_BASE","rich_home","a close-up of the intended mother's joyful tearful face over the swaddled baby","CU","eye","push_in","day",False,False,
  "они дают ему имя, комнату, будущее, и никогда не расскажут, чьё тело дало ему жизнь."),
 ("A8_SH14",None,None,"an extreme close-up macro insert of a tin box holding three hospital bracelets and three tiny booties, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "в жестяной коробке теперь три браслета и три пинетки, от троих детей, которых забрали чужие."),
 ("A8_SH15","HERO_MID","hospital_room","a medium shot of a doctor speaking gravely to the woman in the recovery room","MS","over","static","day",False,False,
  "врачи говорят, что роды прошли с тяжёлыми осложнениями, и что тебе нужно серьёзно обследоваться."),
 ("A8_SH16","HERO_MID","hospital_room","a close-up of the woman not hearing the doctor, still lost in the cry and the smell","CU","eye","static","day",False,False,
  "ты киваешь, но не слышишь их, потому что внутри всё ещё стоит тот крик и тот запах."),
 ("A8_SH17",None,"small_town_street","a wide view of a grey small-town street under a flat sky, quiet and unknowing","WS","eye","static","day",True,False,
  "тебя привозят домой в посёлок, где никто не знает, что ты только что похоронила себя живьём."),
 ("A8_SH18","HERO_MID","poor_flat","a medium close-up of the pale worn mother met at the door by her teenage son","MCU","eye","static","day",False,False,
  "Миша, уже подросток, встречает тебя на пороге и спрашивает, почему ты такая бледная."),
 ("A8_SH19","HERO_MID","poor_flat","a close-up of the woman lying to her son one last big time","CU","eye","static","day",False,False,
  "ты говоришь, что просто устала на работе, и это последняя большая ложь между вами."),
 ("A8_SH20",None,None,"an extreme close-up macro insert of a bank card and a thick envelope of cash on a table, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "на счету теперь самая большая сумма в твоей жизни, а внутри самая большая дыра."),
 ("A8_SH21","HERO_MID","kitchen_night","a medium shot of the woman sitting numb at the night kitchen table, feeling nothing","MS","eye","static","night",False,False,
  "крышу чинят, долги закрыты, Мише хватит на учёбу, а ты сидишь и не чувствуешь ничего."),
 ("A8_SH22","HERO_MID","kitchen_night","a close-up of the woman swearing never again, too late this time","CU","eye","static","night",False,False,
  "ты клянёшься, что больше никогда, и в этот раз, слишком поздно, это оказывается правдой."),
 ("A8_SH23",None,"kitchen_night","a wide view of a dim kitchen at night, an open tin box of three bracelets on the table under a low bulb","WS","eye","static","night",True,False,
  "жестяная коробка с тремя браслетами стоит на столе, и ты не можешь заставить себя её закрыть."),
 ("A8_SH24","HERO_MID","kitchen_night","a close-up of the woman of thirty-six, hollowed out, not yet knowing the full price","CU","eye","push_in","night",False,True,
  "тебе тридцать шесть, ты отдала третьего ребёнка, и скоро узнаешь, что заплатила за это собой."),
]

BAR=[
 ("A9_SH01",None,"doctor_office_bad","a wide view of a sober doctor's office with scan images on a lightbox and two chairs, cold even light","WS","eye","push_in","day",True,False,
  "через несколько недель тебя вызывают в кабинет врача, и по его лицу ты сразу всё понимаешь."),
 ("A9_SH02",None,"doctor_office_bad","a medium close-up of a grave doctor laying out scan images at a desk, choosing careful words","MCU","over","static","day",True,False,
  "врач раскладывает снимки, говорит осторожно про последствия третьих тяжёлых родов и про твоё здоровье."),
 ("A9_SH03","HERO_MID","doctor_office_bad","a close-up of the woman's face as the floor drops out from under her","CU","eye","push_in","day",False,False,
  "он произносит слово, от которого пол уходит из-под ног, ты больше не сможешь выносить своего ребёнка."),
 ("A9_SH04",None,None,"an extreme close-up macro insert of medical scan images clipped to a lightbox, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "на снимках то, что ты сделала со своим телом, отдавая чужих детей за деньги."),
 ("A9_SH05","HERO_MID","doctor_office_bad","a medium shot of the woman staring blankly at the wall of the office","MS","eye","static","day",False,False,
  "ты сидишь и смотришь в стену, и до тебя доходит горькая, поздняя ирония этой цены."),
 ("A9_SH06","HERO_MID","doctor_office_bad","a close-up of the woman absorbing the irreversible loss","CU","eye","static","day",False,False,
  "ты выносила троих чужих, а своего собственного второго ребёнка тебе уже не родить никогда."),
 ("A9_SH07",None,"small_town_street","a wide view of a flat grey small-town street drained of colour and sound, dead still","WS","eye","static","day",True,False,
  "ты выходишь на серую улицу, и мир вокруг стал плоским, будто из него вынули звук."),
 ("A9_SH08","HERO_MID","poor_flat","a medium close-up of the woman remembering a hope she always secretly held","MCU","eye","static","day",False,False,
  "ты всегда думала, что после всего ещё родишь для себя, для души, когда наладится."),
 ("A9_SH09","HERO_MID","poor_flat","a close-up of the woman as that secret hope is taken from her forever","CU","eye","push_in","day",False,False,
  "эта тайная надежда держала тебя все годы, и вот теперь её у тебя отняли навсегда."),
 ("A9_SH10",None,None,"an extreme close-up macro insert of a small folded baby garment kept in a drawer, never used, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "ты купила когда-то тайком маленькую распашонку для будущего своего, и теперь она не пригодится."),
 ("A9_SH11","HERO_MID","kitchen_night","a medium shot of the woman taking out the tin box of three bracelets at the night table","MS","eye","static","night",False,False,
  "дома ты достаёшь коробку с тремя браслетами и понимаешь, чем именно ты за них расплатилась."),
 ("A9_SH12","HERO_MID","kitchen_night","a close-up of the woman's face, her own family ended at one son","CU","eye","static","night",False,False,
  "три чужих ребёнка живут где-то счастливо, а твоя собственная семья закончилась на одном сыне."),
 ("A9_SH13",None,"kitchen_night","a wide view of a dim night kitchen, a low bulb over a tin box, deep silence in the shadows","WS","eye","static","night",True,False,
  "ночная кухня, тусклая лампа, коробка, и тишина, в которой громко звучит слово никогда."),
 ("A9_SH14","HERO_MID","kitchen_night","a medium close-up of the woman keeping the truth to herself, unable to confess","MCU","eye","static","night",False,False,
  "ты не рассказываешь об этом никому, потому что рассказать значит признать, что ты сама во всём виновата."),
 ("A9_SH15","HERO_MID","poor_flat","a close-up of the woman abandoned by everyone who used her","CU","eye","static","day",False,False,
  "Толя давно ушёл, заказчики забыли твоё имя, а Инна Сергеевна больше не звонит, ты им не нужна."),
 ("A9_SH16",None,None,"an extreme close-up macro insert of a silent dark mobile phone on a table with no calls, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "телефон молчит, ведь ты отработанный материал, из которого выжали всё, что можно."),
 ("A9_SH17","HERO_MID","poor_flat","a medium shot of the worn woman of thirty-seven alone in the poor flat with a tin box","MS","eye","static","day",False,False,
  "тебе тридцать семь, у тебя один сын, пустое тело и жестяная коробка чужого детства."),
 ("A9_SH18","HERO_MID","poor_flat","a close-up of the woman grasping the true scope of what she sold","CU","eye","push_in","day",False,False,
  "ты думала, что продаёшь только девять месяцев, а продала возможность быть матерью ещё раз."),
 ("A9_SH19",None,"small_town_street","a wide view of a grey small-town street living out its dull days under an overcast sky","WS","eye","static","day",True,False,
  "посёлок доживает свои серые дни, и ты доживаешь их вместе с ним, тихо и незаметно."),
 ("A9_SH20","HERO_MID","kitchen_night","a close-up of the woman of thirty-seven, the full price finally understood","CU","eye","push_in","night",False,True,
  "это и есть цена, которую тебе никто не назвал заранее, и заплатила ты её целиком."),
]

if __name__=="__main__":
    seed_act("third_birth", P_TB, TB, render_mode="static")
    seed_act("barren",      P_BAR, BAR, render_mode="static")
