# -*- coding: utf-8 -*-
"""coffee expansion wave — interleaved extra beats per act, codes with letter suffixes (A1_SH05B sorts between SH05 and SH06).
id_region='b'. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_coffee_expand.py"""
from _coffee_engine import seed_act

ACTS=[
 ("cold_open","golden opening-morning palette, honey sunlight and copper gleam, orange cups against cream, festive warm",[
  ("A0_SH06B","ASYA_ADULT","new_cafe47","a medium shot of the owner carrying a tray of tiny tasting cups out of the door toward the queue","MS","eye","track","day",False,False,
   "первым в очереди ты выносишь поднос с маленькими пробными чашками, за счёт заведения, по традиции."),
  ("A0_SH06C",None,None,"an extreme close-up insert of tiny tasting cups being lifted from a tray by mittened hands","ECU","eye","static","day",True,False,
   "маленькие чашки расходятся по варежкам и перчаткам, и очередь становится похожа на праздник."),
 ]),
 ("origin","childhood summer palette, amber kitchen light and green courtyard, copper and cinnamon browns, storybook warm",[
  ("A1_SH05B","GRAN_BASE","gran_kitchen","a medium shot of the grandmother lifting the cezve off the flame at the exact right second, teaching with her eyebrows","MS","eye","static","day",False,False,
   "бабушка говорит, что у каждого кофе есть характер, и твоё дело — с ним договориться."),
  ("A1_SH07B",None,"yard_home","a wide view of neighbourhood children queuing solemnly at the cardboard window, one holding a leaf as money","WS","eye","static","day",True,False,
   "соседские дети выстраиваются в очередь понарошку, и очередь эта — самая честная в городе."),
  ("A1_SH09B","ASYA_KID","yard_home","a close-up of the girl in the yellow beret handing over button change with full ceremony","CU","eye","static","day",False,False,
   "ты выдаёшь ему сдачу пуговицами и чек на листике в клеточку, всё по-настоящему."),
  ("A1_SH13B",None,"family_flat","a wide view of the warm flat at night, the girl's silhouette copying words into a notebook under the lamp","WS","eye","static","night",True,False,
   "эту фразу про людей ты запишешь на первой странице всех своих будущих тетрадей."),
  ("A1_SH16B",None,None,"an extreme close-up insert of a candy tin cash box with small coins sorted into neat rows","ECU","top","static","day",True,False,
   "в жестянке из-под леденцов у тебя касса: монетки лежат по достоинству, как в банке."),
  ("A1_SH17B",None,None,"an extreme close-up insert of two pigeons at a saucer of water beside a cardboard cafe wall","ECU","eye","static","day",True,False,
   "голуби прилетают ровно в полдень, как по расписанию, и ты записываешь их в постоянные."),
  ("A1_SH20B","ASYA_KID","gran_kitchen","a close-up of the girl at the sunset window, chin on her folded arms, entirely decided","CU","eye","push_in","evening",False,False,
   "с этого вечера ты точно знаешь, какой будет твоя жизнь, и ни разу не передумаешь."),
  ("A1_SH23B",None,None,"an extreme close-up insert of a father's neat handwriting under a child's drawing: one approving word and a date","ECU","top","static","evening",True,False,
   "подпись отца ты найдёшь через двадцать лет, разбирая тетради, и будешь долго улыбаться."),
 ]),
 ("barista","busy chain-cafe palette, clean retail whites warmed by espresso browns and steam, brisk and bright",[
  ("A2_SH03B",None,"chain_cafe","a wide view of the training corner of the coffee bar, laminated guides and rows of labelled milk jugs","WS","eye","static","day",True,False,
   "первую неделю ты только пробиваешь заказы и учишься не путать двенадцать видов молока."),
  ("A2_SH06B","ASYA_TEEN","city_bright","a close-up of the young barista asleep against a bus window, streetlights sliding over her cap","CU","eye","static","night",False,False,
   "в автобусе ты засыпаешь на два круга, и кондуктор будит тебя уже по-свойски."),
  ("A2_SH08B",None,"family_flat","a wide view of the family kitchen at night, saucers of practice foam lined along the counter, a light left on","WS","eye","static","night",True,False,
   "родители привыкают к запаху кофе на ночной кухне и делают вид, что спят."),
  ("A2_SH10B","MARK_BASE","chain_cafe","a medium shot of the moustached mentor pretending to check stock while watching the trainee's station","MS","eye","static","day",False,False,
   "Марк делает вид, что не смотрит, но пересаживает тебя на самую бойкую машину."),
  ("A2_SH12B",None,None,"an extreme close-up insert of a takeaway cup with a name written large and warm in marker","ECU","eye","static","day",True,False,
   "на стаканах ты пишешь имена с самого начала, задолго до того, как это станет модой."),
  ("A2_SH15B","GRAN_BASE","gran_kitchen","a medium close-up of the grandmother wagging a teaching finger over the tea, eyes smiling","MCU","eye","static","day",False,False,
   "бабушка советует не торопиться со своей кофейней: место должно само тебя позвать."),
  ("A2_SH19B","ASYA_TEEN","street_corner","a close-up of the young woman smiling at the dusty glass, breath fogging a small circle on it","CU","eye","push_in","evening",False,False,
   "ты говоришь стеклу: подожди меня ещё немного, я коплю быстро, как могу."),
  ("A2_SH20B",None,"chain_cafe","a wide view of the coffee bar on a weekend morning, double staff, trays of cups moving like clockwork","WS","high","static","day",True,False,
   "выходных у тебя нет два года, но усталость от мечты — это другая усталость."),
 ]),
 ("championship","competition palette, stage spotlight gold over polished steel, confetti warmth, festive and keen",[
  ("A3_SH02B",None,"champ_hall","a wide view of twenty stage stations warming up at once, steam rising into the spotlights","WS","high","static","day",True,False,
   "вокруг двадцать станций, лучшие руки города, и у половины стаж больше твоего возраста."),
  ("A3_SH04B",None,None,"an extreme close-up insert of milk spinning a perfect vortex inside a steel pitcher","ECU","top","static","day",True,False,
   "молоко закручивается в питчере ровной воронкой, и руки сами знают, когда остановиться."),
  ("A3_SH07B","ASYA_TEEN","champ_hall","a medium close-up of the competitor rereading the results board, lips moving over the second line","MCU","eye","static","day",False,False,
   "ты трижды перечитываешь табло, потому что вторая строка — это твоя фамилия, честное слово."),
  ("A3_SH12B",None,"champ_hall","a wide view of two figures side by side on the stage edge under a single worklight","WS","eye","static","evening",True,False,
   "вы сидите вдвоём на краю сцены, и рабочий свет вам вполне заменяет софиты."),
  ("A3_SH13B",None,"city_bright","a wide view of the night main street, shop signs dark, one figure walking the middle of the empty pavement","WS","eye","track","night",True,False,
   "домой ты идёшь пешком через весь ночной город, репетируя вслух разговор с банком."),
  ("A3_SH15B","ASYA_TEEN","family_flat","a medium shot of the young woman doing sums aloud at the table while her father slides a written problem across","MS","eye","static","evening",False,False,
   "ты считаешь вслух по вечерам, и отец начинает подкидывать тебе задачки про аренду."),
  ("A3_SH17B",None,"market_beans","a wide view of the little roastery full of warm haze, a short queue inside just breathing the air","WS","eye","static","day",True,False,
   "в лавке обжарщика пахнет так, что очередь стоит даже за запахом, без покупок."),
  ("A3_SH18B","ASYA_TEEN","market_beans","a medium close-up of the young woman smelling a warm handful of beans with her eyes closed","MCU","eye","push_in","day",False,False,
   "ты нюхаешь тёплую горсть с закрытыми глазами, и это лучший запах после бабушкиной кухни."),
 ]),
 ("opening","fresh-start palette, wet yellow paint and raw wood, copper lamps against dusty golden light, hopeful bright",[
  ("A4_SH03B",None,"bank_office","a wide view of the quiet loan office, sun through the blinds striping the fanned pages on the desk","WS","eye","static","day",True,False,
   "в тишине слышно, как за стеной считают чужие проценты, а здесь листают твою мечту."),
  ("A4_SH07B",None,None,"an extreme close-up insert of a worn brass door key lying across an open palm","ECU","top","static","day",True,False,
   "ключ ложится в ладонь тяжело и правильно, как будто он всегда был твоим."),
  ("A4_SH12B",None,"korica_cafe","a wide view of the renovation on a Saturday, friends on ladders, paint rollers up, pies waiting on a crate","WS","eye","pan_right","day",True,False,
   "по субботам зал полон друзей с кистями, и платишь ты им пирогами и какао."),
  ("A4_SH14B","ZHENYA_BASE","korica_cafe","a medium close-up of the red-glassed partner totting numbers beside the chalkboard menu, sighing fondly","MCU","eye","static","day",False,False,
   "Женя пересчитывает себестоимость каждого солнышка, вздыхает громко, но солнышки в меню не трогает."),
  ("A4_SH17B",None,"korica_cafe","a wide view of the grandmother settled at the best window table, her headscarf bright against the glass","WS","eye","static","day",True,False,
   "ты усаживаешь её за лучший столик у окна, который с этого дня — её."),
  ("A4_SH20B","ASYA_YOUNG","korica_cafe","a medium shot of the young owner carrying the verdict through her day, shoulders lighter, pouring for the next guest","MS","eye","static","day",False,False,
   "этот вердикт ты вспоминаешь потом в каждый трудный день, и он всегда помогает."),
  ("A4_SH22B",None,"street_corner","a wide view from across the street of the small lit cafe at night, six tables glowing behind the arched window","WS","eye","static","night",True,False,
   "ночью ты долго не уходишь и смотришь с улицы на свои освещённые шесть столиков."),
 ]),
 ("black_streak","candlelit trial palette, deep blue night water and warm candle amber, courage colors over cold, never grim",[
  ("A5_SH02B",None,"street_corner","a wide view of the winter street, scarves and steam, the cafe window glowing stubbornly warm","WS","eye","static","day",True,False,
   "зима в тот год длинная, и город прячет нос в шарфы до самого марта."),
  ("A5_SH06B",None,"rival_cafe","a wide view of a discount queue at the grey unit, heads down, cups identical","WS","eye","static","day",True,False,
   "у сетевика очередь из экономных, и ты их не винишь: полцены есть полцены."),
  ("A5_SH11B",None,"korica_cafe","a wide view of the flooded room at four in the morning, candles on the counter, buckets resting, two tired figures sitting up on the bar","WS","eye","static","night",True,False,
   "в четыре утра вы сидите на стойке, мокрые и довольные, как после похода."),
  ("A5_SH14B","ASYA_YOUNG","korica_cafe","a medium close-up of the young owner slicing the gifted pie into many pieces at the counter","MCU","eye","static","day",False,False,
   "ты режешь этот пирог на всех, кто пришёл помогать, и он оказывается со смыслом: с корицей."),
  ("A5_SH19B","ZHENYA_BASE","korica_cafe","a close-up of the red-glassed partner taking her glasses off, answering the decision with a plan","CU","eye","static","night",False,False,
   "Женя выслушивает твоё «теплее», снимает очки и говорит: тогда считаем не цены, а поводы возвращаться."),
  ("A5_SH21B",None,"street_corner","a wide view of passers-by pausing at the chalk-written window, a small queue reassembling at the door","WS","eye","static","day",True,False,
   "прохожие читают, улыбаются, и к полудню у окна снова собирается небольшая очередь."),
  ("A5_SH24B",None,None,"an extreme close-up insert of two cocoa cups side by side on the window table, steam mixing above them","ECU","eye","static","evening",True,False,
   "какао вы допиваете медленно, никуда не спеша, и это лучший вечер за всю зиму."),
 ]),
 ("regulars","lived-in warmth palette, honey wood and copper lamplight, chalk white and cinnamon brown, easy golden",[
  ("A6_SH03B",None,"korica_cafe","a wide view of the morning room with distinct regulars' corners, coats on familiar hooks","WS","eye","pan_left","day",True,False,
   "у каждого постоянного своё время: пекарь до шести, студенты после трёх, пенсионеры в полдень."),
  ("A6_SH06B",None,None,"an extreme close-up insert of a hand carrying two orange cups, one balanced on the other","ECU","eye","static","day",True,False,
   "постоянные научились брать два стакана: себе и тому, кто сегодня не смог прийти."),
  ("A6_SH09B","MARK_BASE","korica_cafe","a close-up of the moustached barista inspecting a cinnamon spoon with mock severity","CU","eye","static","day",False,False,
   "он ворчит, что у тебя ложечки не по уставу, и тут же заказывает такие же себе."),
  ("A6_SH11B",None,"street_corner","a wide view of the quiet night street, lamps off one by one, a single warm window still lit","WS","eye","tilt_down","night",True,False,
   "к ночи квартал стихает, и твоё окно гаснет в нём последним, после фонарей."),
  ("A6_SH13B","ASYA_YOUNG","korica_cafe","a medium shot of the owner pinning the newspaper clipping by the till as guests lean in to sign it","MS","eye","static","day",False,False,
   "вырезку вы вешаете у кассы, и гости расписываются на полях, как на дипломе."),
  ("A6_SH15B",None,"street_corner","a wide view of two shopfronts side by side, one grey and dim, one warm and busy","WS","eye","static","day",True,False,
   "две витрины стоят рядом, как два ответа на один вопрос, и город выбирает сам."),
  ("A6_SH16B","ASYA_YOUNG","korica_cafe","a medium close-up of the owner and a till roll unspooled like a scarf between laughing hands","MCU","eye","static","evening",False,False,
   "в конце месяца Женя показывает ленту длиной с шарф, и вы съедаете торт без повода."),
 ]),
 ("pandemic","quiet-streets palette, soft grey empty city warmed by one amber takeaway window, hopeful through stillness",[
  ("A7_SH03B","ASYA_YOUNG","street_corner","a medium shot of the owner on her knees chalking neat waiting marks along the pavement","MS","high","static","day",False,False,
   "разметку на асфальте ты рисуешь сама тем же мелом, что и солнышки на доске."),
  ("A7_SH05B",None,"street_corner","a wide view of the spaced queue under a row of unexpectedly bright umbrellas in thin rain","WS","eye","static","day",True,False,
   "зонтики в очереди почему-то все яркие, и серые утра перестают быть серыми."),
  ("A7_SH09B",None,"city_bright","a wide view of a small car crossing the empty dawn city with boxes on the back seat","WS","eye","track","dawn",True,False,
   "путь до больницы занимает у него двадцать минут, и кофе доезжает ещё горячим."),
  ("A7_SH10B",None,"street_corner","a wide view of the takeaway corner at dawn as the loaded car pulls away, steam trailing","WS","eye","static","dawn",True,False,
   "коробки едут через пустой город, и охрана больницы уже знает машину Марка в лицо."),
  ("A7_SH12B","ZHENYA_BASE","korica_cafe","a medium close-up of the partner underlining a ledger line twice and turning the book to show it","MCU","eye","static","night",False,False,
   "Женя записывает эти стаканы в графу «правильные расходы» и запрещает тебе её сокращать."),
  ("A7_SH14B",None,"korica_cafe","a wide view of the room refilling with voices, the marmalade cat reclaiming the windowsill","WS","eye","static","day",True,False,
   "зал наполняется голосами за девять минут, и кот занимает подоконник по старой памяти."),
  ("A7_SH16B",None,None,"an extreme close-up insert of a small framed handwritten note hung beside a framed newspaper clipping","ECU","eye","push_in","evening",True,False,
   "записку из окна вы потом вставите в рамку рядом с газетной вырезкой."),
 ]),
 ("partner","two-points palette, rain-washed bridge blues warmed by skylight gold and fresh wood, adventurous bright",[
  ("A8_SH03B","ASYA_YOUNG","korica_cafe","a medium close-up of the young owner wide awake at the dark counter, sketching layouts on a napkin","MCU","eye","static","night",False,False,
   "ты не спишь полночи, и это не тревога, а чистые, звонкие планы."),
  ("A8_SH05B",None,"second_cafe","a wide view of the narrow room with a column of skylight sun landing where the machine will stand","WS","eye","static","day",True,False,
   "свет из потолочного фонаря падает столбом прямо туда, где встанет машина, и это решает всё."),
  ("A8_SH07B",None,None,"an extreme close-up insert of two copper cezves nose to nose on a workbench, one old and dented, one new","ECU","eye","static","day",True,False,
   "старшая турка остаётся в первой кофейне, и вы возите её младшей сестре гостинцы: корицу."),
  ("A8_SH08B","ASYA_YOUNG","second_cafe","a medium shot of the owner handing hot cocoa out of the new door to the front of the rain queue","MS","eye","static","day",False,False,
   "ты выносишь первым в очереди горячее какао за терпение, и дождь сразу становится декорацией."),
  ("A8_SH10B",None,"city_bright","a wide view of the morning bridge in soft river mist, a cyclist lane marked along its edge","WS","eye","static","dawn",True,False,
   "утренний мост встречает тебя туманом с реки, и ты знаешь на нём каждую заклёпку."),
  ("A8_SH12B","ASYA_YOUNG","city_bright","a close-up of the owner paused mid-bridge at sunset, looking from one lit corner to the other","CU","eye","push_in","evening",False,False,
   "иногда ты останавливаешься на середине моста просто затем, чтобы посмотреть на оба своих окна."),
 ]),
 ("franchise","growing-network palette, loft sunlight over bean-sack burlap and map pins, confident amber and green",[
  ("A9_SH03B",None,"hq_loft","a wide view of the long loft table set with cups for candidates, sun across friendly paperwork","WS","eye","static","day",True,False,
   "кандидатов вы поите кофе три часа и спрашиваете не про выручку, а про бабушек."),
  ("A9_SH05B","ASYA_ADULT","hq_loft","a medium close-up of the woman paging through the standards book, finger tapping the first line","MCU","eye","static","day",False,False,
   "дальше в книге сорок страниц про зерно и молоко, но первый пункт — самый строгий."),
  ("A9_SH06B",None,None,"an extreme close-up insert of a burlap sack corner with a small stencilled sun in yellow paint","ECU","eye","static","day",True,False,
   "на каждом мешке старик теперь ставит трафаретом маленькое солнышко, говорит, сам придумал."),
  ("A9_SH08B",None,"hq_loft","a wide view of the loft settling back to work after a visitor, cups collected, the map catching the sun","WS","eye","pan_left","day",True,False,
   "инвестор уезжает, качая головой, а сеть продолжает расти так, как растут деревья: без рывков."),
  ("A9_SH10B","MARK_BASE","hq_loft","a medium close-up of the moustached trainer presenting a small cinnamon spoon like a medal","MCU","eye","static","day",False,False,
   "каждому выпускнику Марк вручает ложечку для корицы, и это уже почти орден."),
  ("A9_SH11B","ASYA_ADULT","second_cafe","a close-up of the woman brewing the ceremonial first cezve at a regional opening, focused and glad","CU","eye","push_in","day",False,False,
   "на каждое открытие ты приезжаешь сама и первую чашку варишь лично, в турке."),
  ("A9_SH12B",None,None,"an extreme close-up insert of a wall map corner, pencil names written beside each of the pins","ECU","eye","static","evening",True,False,
   "на карте двенадцать булавок, и возле каждой Женя карандашом пишет имя, а не номер."),
 ]),
 ("triumph","award-evening palette, festive gold and deep warm red over copper, proud and glowing, never pompous",[
  ("A10_SH01B",None,None,"an extreme close-up insert of an opened award envelope, a card lifted into stage light","ECU","eye","static","evening",True,False,
   "когда со сцены читают название твоей сети, Женя сжимает твою руку до хруста."),
  ("A10_SH03B",None,"korica_cafe","a wide view of the first cafe with all six tables pushed together for one long family feast","WS","eye","push_in","evening",True,False,
   "праздновать вы едете не в ресторан, а в первую кофейню, сдвинув все шесть столиков."),
  ("A10_SH07B","ASYA_ADULT","korica_cafe","a medium close-up of the woman praising the trembling student honestly across the counter","MCU","eye","static","day",False,False,
   "ты хвалишь его честно, потому что кривое солнышко от старания дороже ровного от привычки."),
  ("A10_SH08B",None,None,"an extreme close-up insert of a single taped coin inside a cash drawer, worn smooth by respectful glances","ECU","top","static","day",True,False,
   "заклеенная монетка первого дня всё ещё в кассе, и новенькие бариста считают её талисманом."),
  ("A10_SH10B",None,"korica_cafe","a wide view of guests posing for photos under the framed cardboard menu above the till","WS","eye","static","day",True,False,
   "гости фотографируются под рамкой, и никто не верит, что какао стоило две монетки."),
  ("A10_SH12B","ASYA_ADULT","korica_cafe","a medium shot of the woman sitting down beside the great-grandmother with her own cup, apron still on","MS","eye","static","day",False,False,
   "ты садишься к ней со своей чашкой, и полчаса сеть прекрасно живёт без тебя."),
 ]),
 ("coda","golden epilogue palette, sunset honey over brass and steam, one small sky-blue accent, tender bright",[
  ("A11_SH02B",None,None,"an extreme close-up insert of the takeaway window glowing amber onto the darkening pavement","ECU","eye","static","evening",True,False,
   "окошко навынос светится на тёмной улице тем же светом, каким светилась бабушкина кухня."),
  ("A11_SH08B",None,None,"an extreme close-up insert of four small coins laid gently on top of a taped coin in a cash drawer","ECU","top","static","evening",True,False,
   "её четыре монетки ты кладёшь в кассу поверх заклеенной первой, пусть дружат."),
  ("A11_SH09B",None,"new_cafe47","a wide view of the emptying golden street, string lights on, steam rising slow from the window counter","WS","eye","static","evening",True,False,
   "улица пустеет, пахнет корицей и поздним летом, и торопиться тебе больше некуда."),
 ]),
]

if __name__=="__main__":
    for sk,pal,shots in ACTS:
        seed_act(sk, pal, shots, id_region="b")
