# -*- coding: utf-8 -*-
"""donor A2 first_cycle + A3 easy_money. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_donor_A2A3.py"""
from _donor_engine import seed_act

P_FIRST="cold clinical palette, sterile blue-white light and pale walls, a thin unease under the calm"
P_EASY="brightening cool palette, cleaner light and small new comforts, a false easy confidence"

FIRST=[
 ("A2_SH01",None,"clinic_corridor","a wide establishing view of a clean pale clinic corridor with cold recessed light and closed numbered doors","WS","eye","push_in","day",True,False,
  "через месяц ты снова в клинике, и на этот раз всё уже по-настоящему, а не на бумаге."),
 ("A2_SH02","NIKA_YOUNG","clinic_consult","a medium shot of the young woman receiving a small boxed kit across a clinic desk from a nurse's hands","MS","eye","static","day",False,False,
  "тебе выдают коробку с уколами и объясняют, что колоть себя нужно каждый вечер строго по часам."),
 ("A2_SH03",None,None,"an extreme close-up macro insert of a boxed hormone injection kit lying inside a fridge door beside milk and bread, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "коробка лежит в холодильнике между молоком и хлебом, будто это самая обычная вещь на свете."),
 ("A2_SH04","NIKA_YOUNG","student_dorm","a close-up of the young woman marking a wall calendar in the dim dorm at night","CU","eye","push_in","night",False,False,
  "каждый вечер ты ставишь галочку в календаре и чувствуешь, как тело становится тяжёлым и чужим."),
 ("A2_SH05",None,"student_dorm","a wide view of a dorm wall calendar covered in small ticked marks under thin daylight","WS","eye","static","day",True,False,
  "врачи называют это стимуляцией, и десять дней твоё тело работает не на тебя, а на программу."),
 ("A2_SH06","NIKA_YOUNG","clinic_corridor","a medium shot of the young woman sitting among empty chairs in the clinic corridor each morning","MS","eye","static","day",False,False,
  "каждое утро ты приходишь на осмотр, тебя смотрят на мониторе и считают, сколько уже созрело."),
 ("A2_SH07",None,"clinic_procedure","an extreme close-up macro insert of a clinic monitor screen showing dark clustered dots, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "на экране гроздья тёмных точек, и медсёстры говорят о них как об урожае, а не о твоих детях."),
 ("A2_SH08","NIKA_YOUNG","clinic_consult","a medium close-up of the tired young woman listening to a nurse across the desk","MCU","eye","static","day",False,False,
  "тебе говорят, что созрело очень много, что ты отличный донор и что забор назначен на утро."),
 ("A2_SH09",None,"clinic_procedure","a wide view of a clean clinical procedure room with a reclined padded couch under a bright cold overhead lamp and a closed door","WS","eye","push_in","day",True,True,
  "в назначенный день тебя ведут в процедурную, где холодная кушетка и очень яркая лампа над ней."),
 ("A2_SH10","NIKA_YOUNG","clinic_procedure","a close-up of the young woman's face on the couch as her eyes drift shut under the cold lamp","CU","high","static","day",False,False,
  "тебе считают до десяти, свет плывёт, и ты засыпаешь под чужими руками в тонких перчатках."),
 ("A2_SH11",None,"clinic_corridor","an extreme close-up macro insert of a closed white procedure-room door with a small number, seen from the corridor, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "за этой закрытой дверью у тебя забирают то, из чего могли бы вырасти твои собственные дети."),
 ("A2_SH12","NIKA_YOUNG","clinic_consult","a medium shot of the groggy young woman waking on a chair with a paper cup of tea","MS","eye","static","day",False,False,
  "ты просыпаешься через час, тебе дают сладкий тёплый чай и говорят, что всё прошло прекрасно."),
 ("A2_SH13","MARTA_BASE","clinic_consult","a medium close-up of the coordinator arriving with a plain envelope and a satisfied smile","MCU","eye","static","day",False,False,
  "приходит Марта Львовна с конвертом и хвалит тебя так, будто ты сдала очень трудный экзамен."),
 ("A2_SH14",None,None,"an extreme close-up macro insert of a plain sealed envelope resting on a clinic desk, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,True,
  "в конверте столько денег, сколько ты не видела никогда, больше твоей стипендии за целый год."),
 ("A2_SH15","NIKA_YOUNG","clinic_consult","a close-up of the young woman holding the envelope, relief and no guilt on her face","CU","eye","push_in","day",False,False,
  "ты держишь конверт и чувствуешь только облегчение, а никакой тревоги, и это тебя даже радует."),
 ("A2_SH16","NIKA_YOUNG","clinic_consult","a medium shot of the young woman receiving her copy of the paperwork across the desk","MS","eye","static","day",False,False,
  "тебе отдают твою копию бумаг, и в углу приклеен маленький номер твоего самого первого цикла."),
 ("A2_SH17",None,None,"an extreme close-up macro insert of fingers peeling a small paper number tab off the corner of a folder, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","push_in","day",True,False,
  "ты отклеиваешь этот номерок ногтем и сама не знаешь, зачем оставляешь его себе на память."),
 ("A2_SH18","NIKA_YOUNG","student_dorm","a medium shot of the young woman dropping a small paper tab into an empty glass jar in the dorm","MS","eye","static","night",False,True,
  "дома ты бросаешь бумажку в пустую стеклянную банку, и звук выходит неожиданно громким в тишине."),
 ("A2_SH19",None,"student_dorm","an extreme close-up macro insert of a single paper number tab lying at the bottom of an empty glass jar, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "на дне банки лежит один номерок, и ты думаешь, что он так и останется там единственным."),
 ("A2_SH20","NIKA_YOUNG","student_dorm","a close-up of the young woman paying off a debt on her phone, breathing out in relief","CU","eye","static","night",False,False,
  "наутро ты закрываешь весь долг за общежитие и впервые за целый год дышишь по-настоящему спокойно."),
 ("A2_SH21","NIKA_YOUNG","city_street","a medium shot of the young woman walking lightly along a grey city street, unburdened","MS","eye","push_in","day",False,False,
  "ты идёшь по городу налегке и думаешь, что нашла лёгкий способ больше не считать каждую копейку."),
 ("A2_SH22","NIKA_YOUNG","student_dorm","a medium close-up of the woman of twenty-one, body not yet aching, already planning the next time","MCU","eye","static","night",False,True,
  "тебе двадцать один, тело ещё совсем не болит, и ты уже прикидываешь, когда позвонишь им снова."),
]

EASY=[
 ("A3_SH01",None,"city_street","a wide establishing view of a grey city street, a little brighter, ordinary daytime traffic","WS","eye","push_in","day",True,False,
  "в двадцать два ты уже не считаешь это подвигом, ты считаешь это работой, и очень неплохой."),
 ("A3_SH02","NIKA_YOUNG","clinic_corridor","a medium shot of the young woman walking confidently into the clinic corridor like a regular","MS","eye","static","day",False,False,
  "ты входишь в клинику как к себе домой, а медсёстры уже здороваются с тобой по имени."),
 ("A3_SH03","MARTA_BASE","recruiter_office","a medium close-up of the coordinator greeting the young woman warmly in a glossy office","MCU","eye","static","day",False,False,
  "марта Львовна встречает тебя как любимую клиентку и говорит, что таких здоровых доноров мало."),
 ("A3_SH04",None,None,"an extreme close-up macro insert of a new donor folder with a higher printed number on the tab, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "тебе заводят новую папку с новым номером, и ты уже не первый цикл, а постоянный проверенный донор."),
 ("A3_SH05","NIKA_YOUNG","clinic_consult","a close-up of the young woman signing a consent form without reading it, casual and quick","CU","eye","static","day",False,False,
  "ты подписываешь согласие не читая, потому что знаешь наизусть каждое слово про одни лишь клетки."),
 ("A3_SH06",None,"clinic_procedure","a wide view of the same clinical procedure room with the reclined couch under the cold bright lamp","WS","eye","static","day",True,False,
  "та же процедурная, та же яркая лампа, и закрытая дверь давно перестала тебя пугать."),
 ("A3_SH07","NIKA_YOUNG","clinic_consult","a medium shot of the young woman waking after a retrieval, already checking her phone","MS","eye","static","day",False,False,
  "ты просыпаешься, выпиваешь свой сладкий чай и через час уже едешь по своим обычным делам."),
 ("A3_SH08",None,None,"an extreme close-up macro insert of a thicker plain envelope of money on a table, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "конверт стал совсем привычным, и ты научилась не спрашивать, кому именно уходят твои клетки."),
 ("A3_SH09","NIKA_YOUNG","city_street","a medium shot of the young woman buying a new coat and phone in a bright shop window street","MS","eye","push_in","day",False,False,
  "на эти деньги ты покупаешь новый телефон и пальто и впервые чувствуешь себя настоящей взрослой."),
 ("A3_SH10",None,"student_dorm","an extreme close-up macro insert of a glass jar on a shelf holding five small curled paper tabs, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,True,
  "в банке на полке уже пять номерков, и ты бросаешь туда шестой почти не глядя."),
 ("A3_SH11","NIKA_YOUNG","student_dorm","a close-up of the young woman glancing at the jar on the shelf, brushing off a thought","CU","eye","static","day",False,False,
  "иногда ты смотришь на банку и говоришь себе, что это просто цифры, а вовсе не люди."),
 ("A3_SH12",None,"city_street","a wide view of a grey city street through changing seasons, bare trees then wet leaves","WS","eye","pan_right","day",True,False,
  "проходит год, потом второй, и каждые несколько месяцев ты снова ложишься под ту же лампу."),
 ("A3_SH13","NIKA_YOUNG","clinic_consult","a medium close-up of the young woman waving off a young nurse's quiet concern with a laugh","MCU","eye","static","day",False,False,
  "молодая медсестра однажды тихо советует тебе поберечь себя, но ты только смеёшься в ответ."),
 ("A3_SH14","MARTA_BASE","recruiter_office","a medium shot of the coordinator across the glass desk offering more money with a smooth gesture","MS","over","static","day",False,False,
  "марта Львовна говорит, что за редкие светлые глаза заказчики готовы платить тебе ещё больше."),
 ("A3_SH15",None,None,"an extreme close-up macro insert of a donor profile card showing traits and a small portrait photo, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "твои светлые волосы и голубые глаза стоят в их списке дороже, будто ты породистая лошадь."),
 ("A3_SH16","NIKA_YOUNG","clinic_consult","a close-up of the young woman looking flattered yet faintly uneasy at the desk","CU","eye","static","day",False,False,
  "тебе льстит, что ты дорогой донор, и ты стараешься не думать, что именно в тебе покупают."),
 ("A3_SH17",None,"clinic_corridor","a wide view of a clinic corridor with several young women waiting apart on the chairs","WS","eye","static","day",True,False,
  "в коридоре сидят такие же девчонки, как ты, и никто из вас не смотрит друг другу в глаза."),
 ("A3_SH18","NIKA_YOUNG","clinic_procedure","a medium shot of the young woman going through yet another routine retrieval, tired","MS","eye","static","day",False,False,
  "ты сдаёшь цикл за циклом, и тело каждый раз восстанавливается всё дольше и всё тяжелее."),
 ("A3_SH19",None,"student_dorm","an extreme close-up macro insert of a glass jar now holding more than ten curled paper tabs, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,True,
  "к двадцати четырём в банке уже больше десяти номерков, и ты перестаёшь их пересчитывать."),
 ("A3_SH20","NIKA_YOUNG","student_dorm","a close-up of the young woman at night counting only banknotes, indifferent to the jar","CU","eye","static","night",False,False,
  "ты пересчитываешь только деньги, потому что деньги — единственное, что ты получаешь взамен."),
 ("A3_SH21",None,"city_street","a wide view of a large city at night, countless lit windows stretching to the horizon","WS","eye","static","night",True,False,
  "город огромный, и тебе кажется, что твои клетки растворяются в нём бесследно и навсегда."),
 ("A3_SH22","NIKA_YOUNG","nika_flat","a medium shot of the young woman moving into her first small rented room with a few boxes","MS","eye","static","day",False,False,
  "ты снимаешь свою первую комнату и говоришь матери, что нашла себе очень хорошую подработку."),
 ("A3_SH23","NIKA_YOUNG","nika_flat","a medium close-up of the young woman placing her mother's brooch into a drawer, avoiding it","MCU","eye","static","day",False,False,
  "брошка-незабудка лежит в ящике, потому что смотреть на неё почему-то стало неловко и стыдно."),
 ("A3_SH24","NIKA_YOUNG","nika_flat","a close-up of the woman of twenty-four, sure everything is under control","CU","eye","static","day",False,True,
  "тебе двадцать четыре, ты уверена, что всё под контролем, и это твоя самая главная ошибка."),
]

if __name__=="__main__":
    seed_act("first_cycle", P_FIRST, FIRST, render_mode="animated")
    seed_act("easy_money",  P_EASY, EASY, render_mode="static")
