# -*- coding: utf-8 -*-
"""webcam A8 podruga + A9 exposed. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_webcam_A8A9.py"""
from _webcam_engine import seed_act

P_P="ruined neon palette, dead grey and sickly leftover glow, the aftermath of a burned-out life"
P_E="cold exposure palette, harsh daylight and clinical screen glow, the neon mask stripped away in public"

POD=[
 ("A8_SH01",None,"club_bar","a wide view of a dim run-down bar and a squalid streaming corner beyond, faded neon and grime","WS","eye","push_in","night",True,False,
  "Рите тридцать пять, и её история — это твоё будущее, если ты не остановишься сейчас."),
 ("A8_SH02","PODRUGA_BASE","stream_room","a medium shot of the jet-black-bob woman streaming from a messy dim room to an almost empty audience","MS","eye","static","night",False,False,
  "когда-то она была топом, а теперь стримит из грязной комнаты почти впустую, за копейки."),
 ("A8_SH03","PODRUGA_BASE","stream_room","a close-up of the jaded woman's worn face, forgotten by the fans who adored her","CU","eye","static","night",False,False,
  "зрители, которые её обожали, давно ушли к молодым, и никто из них не вспомнил её имени."),
 ("A8_SH04",None,None,"an extreme close-up macro insert of a vape pen and empty bottles beside a dusty ring light, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "в её квартире бардак, пустые бутылки и вейп, и та же кольцевая лампа, только пыльная."),
 ("A8_SH05","HERO_MID","stream_room","a medium close-up of the woman bringing food and money to her old mentor, worried","MCU","over","static","day",False,False,
  "ты приносишь ей денег и еды, потому что помнишь, как она когда-то ввела тебя в это дело."),
 ("A8_SH06","PODRUGA_BASE","stream_room","a close-up of the ruined woman speaking without bitterness, full of regret","CU","eye","static","day",False,False,
  "Рита говорит без злости, что зря не ушла вовремя, что надо было копить и учиться другому."),
 ("A8_SH07",None,"city_street_neon","a wide view of a neon city street at night, its glow indifferent and cold","WS","eye","static","night",True,False,
  "за окном тот же неон, что когда-то обещал ей красивую жизнь, а оставил в долгах и одиночестве."),
 ("A8_SH08","PODRUGA_BASE","stream_room","a medium close-up of the woman as her old clips are dredged up and posted publicly","MCU","eye","static","day",False,False,
  "однажды её ролики без спроса собирают и выкладывают на всеобщее обозрение под настоящим именем."),
 ("A8_SH09","HERO_MID","stream_room","a close-up of the woman watching her friend be recognized and shunned","CU","eye","static","day",False,False,
  "её узнают в родном городе, родные отворачиваются, а работу нигде больше не берут."),
 ("A8_SH10",None,None,"an extreme close-up macro insert of a phone screen spreading a shaming post with a face, text unreadable, filling the frame in sharp focus, shallow depth of field","ECU","top","static","day",True,False,
  "её лицо расходится по чатам с подписями, от которых хочется провалиться сквозь землю."),
 ("A8_SH11","PODRUGA_BASE","bedroom_dark","a medium shot of the woman shut in a dark flat with curtains drawn, not answering","MS","eye","static","night",False,False,
  "Рита перестаёт выходить из дома, не отвечает на звонки, и ты чувствуешь недоброе."),
 ("A8_SH12","HERO_MID","bedroom_dark","a close-up of the woman arriving to a dark flat, dread on her face","CU","eye","push_in","night",False,False,
  "ты приезжаешь к ней и застаёшь тёмную квартиру, задёрнутые шторы и очень нехорошую тишину."),
 ("A8_SH13",None,"bedroom_dark","a wide view of a dark squalid flat with drawn curtains and an ambulance glow outside the window","WS","eye","static","night",True,False,
  "её увозят на скорой, и говорят коротко, что она сама не хотела больше жить."),
 ("A8_SH14","HERO_MID","stream_room","a medium close-up of the woman at a hospital bedside, shaken to the core","MCU","eye","static","day",False,False,
  "Рита выживает, но той, что учила тебя правилам, больше нет, осталась пустая, сломанная женщина."),
 ("A8_SH15","HERO_MID","stream_room","a close-up of the woman seeing exactly where her own road leads","CU","eye","static","day",False,False,
  "ты сидишь у её постели и видишь, куда ведёт дорога, по которой ты идёшь уже пятнадцать лет."),
 ("A8_SH16",None,None,"an extreme close-up macro insert of a vape pen kept in a palm like a keepsake, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "ты забираешь её вейп на память, как будто это поможет тебе не повторить её путь."),
 ("A8_SH17","HERO_MID","own_apartment","a medium shot of the woman resolving to quit the profession and start over","MS","eye","static","day",False,False,
  "ты клянёшься себе уйти из профессии, копить деньги, выучиться на что-то другое, начать нормальную жизнь."),
 ("A8_SH18","HERO_MID","stream_room","a medium close-up of the woman facing bills the next morning, reaching for the switch again","MCU","eye","static","day",False,False,
  "но наутро приходят счета, аренда и садик Лизы, и ты снова щёлкаешь кольцевой лампой."),
 ("A8_SH19",None,None,"an extreme close-up macro insert of a ring light flooding on with white light, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,False,
  "белый свет заливает лицо, дзынь звенит, и обещание уйти растворяется до следующего срыва."),
 ("A8_SH20","HERO_MID","stream_room","a close-up of the woman of thirty-two walking toward the fate she just witnessed","CU","eye","push_in","night",False,True,
  "тебе тридцать два, ты видела своё будущее в чужой сломанной судьбе и всё равно идёшь к нему."),
]

EXP=[
 ("A9_SH01",None,"school_gate","a wide view of an ordinary school gate and yard in daytime, a low fence and parents' cars, plain light","WS","eye","push_in","day",True,False,
  "в тридцать три твоя двойная жизнь рушится в один обычный день у школьных ворот."),
 ("A9_SH02","HERO_OLD","school_gate","a medium shot of the woman as a plain everyday mother in a coat waiting at the school gate","MS","eye","static","day",False,False,
  "ты приходишь за Лизой, как всегда, обычная мама в куртке, без всякой Алисы и чокера."),
 ("A9_SH03",None,"school_gate","a medium close-up of another parent staring hard and showing a phone to a second parent, judgemental","MCU","over","static","day",True,False,
  "и одна из мам смотрит на тебя слишком пристально, а потом достаёт телефон и что-то показывает другой."),
 ("A9_SH04","HERO_OLD","school_gate","a close-up of the woman realizing from their faces that she has been recognized","CU","eye","push_in","day",False,False,
  "ты понимаешь по их лицам, что тебя узнали, что кто-то сопоставил Настю с Алисой из сети."),
 ("A9_SH05",None,None,"an extreme close-up macro insert of a phone screen turned toward the viewer showing a paused stream, text unreadable, filling the frame in sharp focus, shallow depth of field","ECU","eye","static","day",True,False,
  "на экране твой стрим, поставленный на паузу, и твоё имя, написанное чужими злыми руками."),
 ("A9_SH06","HERO_OLD","school_gate","a medium shot of the woman standing exposed as the news begins to spread around her","MS","eye","static","day",False,False,
  "к вечеру ссылка расходится по родительскому чату, потом по всему району, потом дальше."),
 ("A9_SH07","DAU_CHILD","kitchen_home","a close-up of a small brown-haired girl of seven crying, clutching her plush rabbit","CU","high","static","day",False,False,
  "на следующий день Лиза приходит из школы в слезах, потому что дети сказали ей что-то про маму."),
 ("A9_SH08","HERO_OLD","kitchen_home","a medium close-up of the mother with no strength left to lie to her child","MCU","eye","static","day",False,False,
  "она спрашивает, правда ли то, что показывали в телефоне, и у тебя нет сил соврать ей снова."),
 ("A9_SH09",None,None,"an extreme close-up macro insert of a child's plush rabbit held tightly against a small chest, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "Лиза прижимает своего зайца и смотрит на тебя так, как раньше смотрела только на чужих."),
 ("A9_SH10","HERO_OLD","kitchen_home","a medium shot of the woman trying to explain the unexplainable to a small child","MS","eye","static","day",False,False,
  "ты пытаешься объяснить необъяснимое семилетнему ребёнку и понимаешь, что слов таких нет."),
 ("A9_SH11",None,"city_street_neon","a wide view of an ordinary daytime street where strangers glance and recognize, cold and public","WS","eye","static","day",True,False,
  "новость катится дальше, и вот уже незнакомые люди узнают тебя на улице и в магазине."),
 ("A9_SH12","MOTHER_BASE","mother_home","a medium close-up of the grey-haired mother frozen with a phone, having seen everything","MCU","eye","static","day",False,False,
  "звонит мать, и по её молчанию в трубке ты сразу понимаешь, что она тоже всё увидела."),
 ("A9_SH13","HERO_OLD","kitchen_home","a close-up of the woman on the phone hearing her mother's quiet devastating question","CU","eye","static","day",False,False,
  "мать не кричит, она просто спрашивает, как ты могла, и это хуже любого крика на свете."),
 ("A9_SH14","MOTHER_BASE","mother_home","a medium close-up of the mother speaking with quiet shame and hurt","MCU","eye","static","day",False,False,
  "она говорит, что ей стыдно смотреть в глаза соседям, и что она не так тебя растила."),
 ("A9_SH15",None,None,"an extreme close-up macro insert of a framed family photo turned face-down on a shelf, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "дома у матери твоя фотография теперь лежит лицом вниз, и это её тихий приговор."),
 ("A9_SH16","HERO_OLD","studio_office","a medium shot of the woman being coldly dropped by the studio, the manager turning away","MS","over","static","day",False,False,
  "студия и Стас мгновенно от тебя избавляются, потому что публичный скандал вредит их бизнесу."),
 ("A9_SH17","HERO_OLD","studio_office","a close-up of the woman discarded after fifteen years of profit","CU","eye","static","day",False,False,
  "за пятнадцать лет ты принесла им целое состояние, а выбросили тебя за один день без разговоров."),
 ("A9_SH18",None,"stream_room","a wide view of a dark switched-off ring light in a dim room, quietly threatening now","WS","eye","static","night",True,False,
  "кольцевая лампа стоит выключенная, и впервые ты боишься её включить, ведь теперь тебя знают в лицо."),
 ("A9_SH19","HERO_OLD","bedroom_dark","a medium close-up of the woman as her stage name becomes a brand of shame","MCU","eye","static","night",False,False,
  "имя Алиса, которое кормило тебя всю взрослую жизнь, за неделю превращается в клеймо."),
 ("A9_SH20","HERO_OLD","bedroom_dark","a medium shot of the woman losing work, reputation and family all at once","MS","eye","static","night",False,False,
  "ты теряешь работу, репутацию и остатки семьи почти одновременно, и держаться больше не за что."),
 ("A9_SH21",None,None,"an extreme close-up macro insert of a velvet star choker being dropped into a drawer, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "ты снимаешь бархатный чокер и бросаешь его в ящик, но Алиса уже приклеилась к тебе намертво."),
 ("A9_SH22","HERO_OLD","bedroom_dark","a close-up of the woman of thirty-three, exposed to everyone but ashamed before only one person","CU","eye","push_in","night",False,True,
  "тебе тридцать три, тайна раскрыта, и оказывается, что скрывать было не стыдно только от одного человека, от дочери."),
]

if __name__=="__main__":
    seed_act("podruga", P_P, POD, render_mode="static")
    seed_act("exposed", P_E, EXP, render_mode="static")
