# -*- coding: utf-8 -*-
"""car_flipper — акты 8–11: продажа Ане, экспертиза, суд, финал."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _car_flipper_engine import seed_act

P8  = "a soft late-summer palette of warm low sun, dust hanging in the air and pale blue shade"
P9  = "a hard clinical palette of flat white strip light, bare steel grey and cold shadow"
P10 = "a pale institutional palette of green walls, worn brown linoleum and grey window light"
P11 = "a washed-out palette of wet concrete, soap white and thin winter daylight"

SALE = [
 ("A8_SH01", None, "body_shop",
  "a repair bay with a silver saloon up on axle stands under plastic sheeting, masking paper along its panel edges and a lamp burning at the sill",
  "WS","eye","static","day",True,False,
  "две недели ты приводишь серебристую в порядок, и она становится как новая."),
 ("A8_SH02", "VIK_OLD", "body_shop",
  "Viktor lying under a raised sill with a welding mask down, drawing a slow bead along a fresh patch of metal",
  "MS","low","static","day",False,False,
  "пороги ты варишь сам, потому что руки помнят всё через двадцать лет."),
 ("A8_SH03", "OBJ:brakeline", None,
  "a car underbody lit hard from one side by a portable lamp",
  "INSERT","eye","pull_out","interior",True,True,
  "трубки ты не меняешь, ты закрашиваешь их из баллона за четыре минуты."),
 ("A8_SH04", "VIK_OLD", "body_shop",
  "Viktor's face under the lamp with the aerosol can still hissing in his hand, looking at what he has just covered",
  "CU","eye","static","night",False,True,
  "ты делаешь это совсем один, ночью, и никому об этом не говоришь."),
 ("A8_SH05", "VIK_OLD", "body_shop",
  "Viktor squeezing a bead of clear adhesive along a cracked mirror glass and drawing the excess off with his thumb",
  "MS","eye","static","night",False,False,
  "треснувшее зеркало ты подклеиваешь прозрачным клеем и потом аккуратно снимаешь пальцем лишнее."),
 ("A8_SH06", "VIK_OLD", "body_shop",
  "Viktor at a bench before dawn with an instrument cluster face-down in front of him, sleeves rolled, working at an even unhurried pace",
  "MCU","eye","static","dawn",False,False,
  "приборку ты снимаешь в последнюю очередь, уже под утро, за десять минут."),
 ("A8_SH07", "OBJ:odometer", None,
  "a bench top before dawn with a lamp pulled low over it",
  "INSERT","low","static","interior",True,True,
  "двести четырнадцать тысяч превращаются в девяносто шесть, и это твоя последняя скрутка."),
 ("A8_SH08", None, "dealer_lot",
  "a car lot in the morning with a polished silver saloon standing second from the right, sunlight running along its clean flank",
  "WS","eye","static","day",True,False,
  "утром она стоит на площадке второй справа и блестит лучше всех остальных."),
 ("A8_SH09", "DEN_ADULT", "dealer_lot",
  "Denis tucking a fresh price card under a windscreen wiper and stepping back to check it sits straight",
  "MCU","eye","static","day",False,False,
  "Денис вешает на неё картонку с ценой и говорит, что уйдёт за неделю."),
 ("A8_SH10", None, "dealer_lot",
  "a used-car lot from very high in the afternoon with one gap already opening in the second row and a family car parked at the gate",
  "EWS","high","pan_left","day",True,False,
  "она уходит за пять дней, и приезжает за ней совсем молодая семья."),
 ("A8_SH11", "ANYA_BASE", "dealer_lot",
  "Anya walking slowly along the flank of the silver car with the yellow bear rucksack hanging from one hand, looking at the panel gaps",
  "MS","eye","static","day",False,False,
  "её зовут Аня, ей двадцать семь, и она приезжает с мужем и дочкой."),
 ("A8_SH12", "ANYA_BASE", "dealer_lot",
  "Anya crouched at a front wheel arch with her head tilted right down, trying to see under the car",
  "CU","low","static","day",False,False,
  "она ходит вокруг машины и заглядывает под неё, потому что так сказал отец."),
 ("A8_SH13", "OBJ:backpack", None,
  "a rear car seat with the door standing open to the sun",
  "INSERT","eye","static","interior",True,True,
  "дочка сразу залезает назад и ставит рядом с собой свой жёлтый рюкзак-медвежонок."),
 ("A8_SH14", ("VIK_OLD","ANYA_BASE"), "dealer_lot",
  "Viktor holds the bonnet up on its stay and points into the engine bay while Anya leans in beside him with her hands behind her back",
  "MS","eye","static","day",False,False,
  "ты открываешь ей капот и подробно показываешь всё, что можно ей показывать."),
 ("A8_SH15", None, "roadside_day",
  "a wide gravel lay-by beside a suburban road with fresh tyre tracks curving in off the asphalt and poplars standing behind the fence",
  "WS","eye","track","day",True,False,
  "на тест-драйв они едут четыре километра до кольца и столько же обратно."),
 ("A8_SH16", "ANYA_BASE", "roadside_day",
  "Anya behind the wheel with both hands at ten and two, listening to the engine rather than watching the road",
  "MCU","eye","static","day",False,False,
  "машина едет ровно, потому что ровно она и едет, дело не в этом."),
 ("A8_SH17", "ANYA_BASE", "roadside_day",
  "Anya turning her head at the lay-by with the engine just switched off, her expression open and direct",
  "CU","eye","push_in","day",False,False,
  "на обочине она поворачивается к тебе и задаёт тебе тот самый вопрос."),
 ("A8_SH18", "VIK_OLD", "roadside_day",
  "Anya's shoulder and the back of her head filling one side of the foreground, Viktor beyond her standing at the open door with one hand on the roof",
  "OTS","over","static","day",False,False,
  "а он не бит, спрашивает она, и смотрит тебе прямо в глаза."),
 ("A8_SH19", "VIK_OLD", "roadside_day",
  "Viktor's face entirely at ease, the same four words leaving it as easily as breathing",
  "CU","eye","static","day",False,True,
  "как себе брал, отвечаешь ты, и это твоя тысяча первая такая фраза."),
 ("A8_SH20", "VIK_OLD", "roadside_day",
  "Viktor's hand still resting on the door frame, his eyes moving once towards the front wheel arch and away again",
  "MCU","eye","static","day",False,False,
  "на этой фразе у тебя есть две секунды, чтобы сказать про трубки."),
 ("A8_SH21", "VIK_OLD", "roadside_day",
  "Viktor's mouth closing on an unspoken word, his jaw settling back into place",
  "CU","low","push_in","day",False,True,
  "ты не говоришь, и через две секунды говорить об этом становится поздно."),
 ("A8_SH22", ("DEN_ADULT","ANYA_BASE"), "office_container",
  "Denis fills in a carbon-copy form on the desk while Anya sits opposite him with her bag on her knees, watching the pen move",
  "MS","eye","static","day",False,False,
  "договор оформляет Денис, потому что площадка и все машины оформлены на него."),
 ("A8_SH23", "OBJ:contract", None,
  "an office desk with a carbon sheet peeled halfway back",
  "INSERT","low","push_in","interior",True,True,
  "в графе продавца стоит его фамилия, а рядом с ней стоит его подпись."),
 ("A8_SH24", "DEN_ADULT", "office_container",
  "Denis standing up to shake a hand across the desk, open and friendly, entirely unaware",
  "CU","eye","static","day",False,False,
  "он подписывает и жмёт ей руку, и он при этом ничего не знает."),
 ("A8_SH25", "VIK_OLD", "office_container",
  "Viktor standing back at the key cabinet with a key still hooked on one finger, looking out of the window instead of at the desk",
  "MCU","low","static","day",False,False,
  "ты стоишь у шкафчика с ключами и смотришь в окно на дорогу."),
 ("A8_SH26", None, "dealer_lot",
  "an empty space in a car lot row with fresh tyre marks leading out to the gate, the sliding gate rolled fully open onto the road",
  "WS","eye","static","dusk",True,False,
  "они выезжают в семнадцать сорок, и дочка машет тебе из заднего окна."),
 ("A8_SH27", "VIK_OLD", "dealer_lot",
  "Viktor's face raising a short flat wave, the smile arriving a moment after the hand",
  "CU","eye","static","dusk",False,False,
  "ты машешь в ответ, потому что все продавцы на свете машут в ответ."),
 ("A8_SH28", None, "dawn_road",
  "a long open road at dusk from very high with one pair of tail lights far down it and the fields going dark on both sides",
  "EWS","high","pull_out","dusk",True,False,
  "между этой минутой и тем сто девятым километром остаётся ровно пять недель."),
]

CRASH = [
 ("A9_SH01", None, "night_crash_site",
  "a recovery truck standing on the closed lane before dawn with its boom raised and its amber lamps on, a bare steel deck angled down towards the ditch",
  "WS","low","static","night",True,False,
  "машину поднимают в четыре утра и увозят на закрытую стоянку под замок."),
 ("A9_SH02", None, "night_crash_site",
  "a heap of swept glass and broken plastic trim gathered against the kerb with the mouth of an open sack beside it",
  "INSERT","top","static","night",True,False,
  "осколки и куски пластика сметают в мешок, и дорогу открывают в шесть."),
 ("A9_SH03", None, "expert_bay",
  "an examination bay under bright shadowless strip lighting with a damaged silver car raised chest-high on a two-post lift, numbered markers on the floor",
  "EWS","high","static","day",True,False,
  "через два дня её ставят на подъёмник в боксе государственной автотехнической экспертизы."),
 ("A9_SH04", "IGOR_BASE", "expert_bay",
  "Igor standing under the raised car with a torch in one hand and a clipboard against his hip, working along the underbody from front to back",
  "MS","eye","static","day",False,False,
  "эксперта зовут Игорь Петрович, ему пятьдесят, и работает он совсем без спешки."),
 ("A9_SH05", "IGOR_BASE", "expert_bay",
  "Igor's face lit from below by the torch, the reading glasses down on his nose, his mouth closed",
  "CU","low","static","day",False,False,
  "он смотрит машину снизу восемь часов и всё это время просто молчит."),
 ("A9_SH06", None, "expert_bay",
  "a steel brake line under a car floor with a grey coating scraped away in a short bright stripe, orange rust crumbling out from under the edge of the paint",
  "INSERT","low","push_in","day",True,True,
  "под фонарём он соскабливает серый слой и находит под ним рыжую труху."),
 ("A9_SH07", "IGOR_BASE", "expert_bay",
  "Igor holding a camera up one-handed to the underbody and then writing four short lines onto a form",
  "MCU","eye","static","day",False,False,
  "он фотографирует место разрыва и записывает в свой протокол ровно четыре строчки."),
 ("A9_SH08", None, "expert_bay",
  "a structural chassis rail seen from directly below with an old welded seam running across it, twice overpainted and cracked open along the join",
  "INSERT","top","static","day",True,True,
  "на лонжероне он находит старый шов, который когда-то заварили и закрасили дважды."),
 ("A9_SH09", None, "expert_bay",
  "an examination bay with a damaged car high on the lift and a bench beneath it laid out with numbered parts on white paper",
  "WS","eye","static","day",True,False,
  "эта машина была в тяжёлой аварии ещё за шесть лет до того дня."),
 ("A9_SH10", "IGOR_BASE", "expert_bay",
  "Igor at a desk in the corner of the bay turning a printed service history round to read a figure twice",
  "CU","eye","static","day",False,False,
  "он поднимает историю обслуживания и видит в ней двести четырнадцать тысяч пробега."),
 ("A9_SH11", "OBJ:cluster", None,
  "a steel evidence bench spread with clean white paper",
  "INSERT","eye","static","interior",True,True,
  "на панели у неё стоит девяносто шесть, и разница тут видна сразу."),
 ("A9_SH12", "IGOR_BASE", "expert_bay",
  "Igor signing the last page of a report and squaring the sheets against the desk with a blank official face",
  "MCU","eye","push_in","day",False,True,
  "он не ищет виноватого, он просто пишет то, что нашёл, и подписывает."),
 ("A9_SH13", None, "court_corridor",
  "a case folder open on a bench with a carbon-copy sale contract clipped inside it, the seller line filled in by hand",
  "INSERT","top","static","day",True,False,
  "к делу подшивают договор, и в графе продавца стоит там одна фамилия."),
 ("A9_SH14", None, "court_corridor",
  "a long institutional corridor with pale green walls, a row of empty wooden benches and a barred window throwing a grid onto the linoleum",
  "WS","eye","static","day",True,False,
  "фамилия эта совсем не твоя, потому что ты не имел права продавать."),
 ("A9_SH15", "DEN_ADULT", "court_corridor",
  "Denis walking the corridor alone with a folded summons in his fist, checking the numbered plates on the doors",
  "MS","eye","static","day",False,False,
  "Дениса вызывают повесткой уже в понедельник, и едет он туда совершенно один."),
 ("A9_SH16", "DEN_ADULT", "court_corridor",
  "Denis's face taking in a question that lands on him blankly, his eyebrows drawing together",
  "CU","eye","static","day",False,False,
  "он не понимает вопросов, потому что машину он в глаза не видел."),
 ("A9_SH17", "DEN_ADULT", "court_corridor",
  "Denis talking with both hands open in front of him, explaining plainly and too fast",
  "MCU","eye","static","day",False,False,
  "он говорит правду: подписал, продал, деньги отдал отцу в тот же день."),
 ("A9_SH18", "VIK_OLD", "court_corridor",
  "Viktor sitting on a corridor bench with his cap between his knees, hearing his son's voice through a closed door",
  "CU","low","static","day",False,True,
  "эта его правда звучит ровно как признание, и записывают её именно так."),
 ("A9_SH19", None, "court_corridor",
  "a corridor from high above with one occupied bench, a long stretch of empty linoleum and a clock high on the far wall",
  "WS","high","static","day",True,False,
  "ты сидишь в коридоре на скамейке и ждёшь его целых четыре часа."),
 ("A9_SH20", "ANYA_BASE", "court_corridor",
  "Anya sitting at the far end of the corridor with the yellow bear rucksack upright on the bench beside her, both hands flat on her knees",
  "MS","eye","static","day",False,True,
  "в конце коридора сидит Аня, и рядом с ней стоит жёлтый рюкзак."),
 ("A9_SH21", "ANYA_BASE", "court_corridor",
  "Anya's face very still and very tired, her eyes on the closed door and nowhere else",
  "CU","eye","push_in","day",False,False,
  "её муж не выжил, а дочку вытащили из детского кресла живой и целой."),
 ("A9_SH22", "VIK_OLD", "court_corridor",
  "Viktor standing up off the bench and taking three steps down the corridor before stopping dead",
  "MCU","eye","static","day",False,False,
  "ты встаёшь и делаешь три шага в её сторону, и там останавливаешься."),
 ("A9_SH23", "VIK_OLD", "court_corridor",
  "Viktor's face working through and discarding the first sentence, then the second, then sitting back down",
  "CU","eye","static","day",False,False,
  "ты не знаешь, что вообще говорят в таких случаях, и садишься обратно."),
 ("A9_SH24", None, "court_corridor",
  "a corridor seen low along the floor with a stretch of worn linoleum, a bench leg and the grid of window light lying across it",
  "WS","low","static","day",True,False,
  "она проходит мимо тебя по коридору и даже не знает, кто ты."),
 ("A9_SH25", ("VIK_OLD","DEN_ADULT"), "court_corridor",
  "Viktor rises off the corridor bench as Denis stops a metre short of him with the office door still swinging behind him",
  "MS","eye","static","day",False,False,
  "Денис выходит из кабинета и первый раз в жизни спрашивает у тебя прямо."),
 ("A9_SH26", "DEN_ADULT", "court_corridor",
  "Denis's face asking one short question with only patience on his face",
  "CU","eye","static","day",False,True,
  "он спрашивает, что было под этой машиной, и ты отвечаешь ему честно."),
 ("A9_SH27", "VIK_OLD", "court_corridor",
  "Viktor talking steadily with his eyes down on the linoleum, getting through all of it in one unbroken run",
  "MCU","low","static","day",False,False,
  "ты рассказываешь ему всё за две минуты, и он слушает не перебивая."),
 ("A9_SH28", None, "dawn_road",
  "an empty road at dusk from very high with the light going out of the fields and the lanes standing empty",
  "EWS","high","pull_out","dusk",True,False,
  "а потом он встаёт и уходит, и до суда вы не разговариваете."),
]

VERDICT = [
 ("A10_SH01", None, "courtroom",
  "a small plain courtroom with pale wood panelling, an empty raised bench, rows of spectator seats and half-closed blinds on tall windows",
  "WS","eye","static","day",True,False,
  "суд идёт семь месяцев, и за это время ты продаёшь всё, что можно."),
 ("A10_SH02", "VIK_OLD", "court_corridor",
  "Viktor standing in the corridor talking to a lawyer out of frame, one hand tapping his own chest twice",
  "MS","eye","static","day",False,False,
  "ты нанимаешь адвоката и говоришь ему, что во всём виноват ты один."),
 ("A10_SH03", "VIK_OLD", "court_corridor",
  "Viktor's face receiving an answer he cannot argue with, the tapping hand dropping back to his side",
  "CU","low","static","day",False,False,
  "адвокат объясняет, что твоей подписи нет ни на одном листе этого дела."),
 ("A10_SH04", None, "courtroom",
  "a case file open on a table with numbered pages fanned under a paper clip, a pencil laid diagonally across them",
  "INSERT","top","static","day",True,False,
  "в деле сто восемьдесят листов, и твоя фамилия там вообще не встречается."),
 ("A10_SH05", "VIK_OLD", "courtroom",
  "Viktor sitting in the spectator row with his hands hanging between his knees, staring at the back of the bench in front of him",
  "MCU","eye","static","day",False,True,
  "ты тридцать лет строил всё так, чтобы тебя не было на бумаге."),
 ("A10_SH06", "VIK_OLD", "courtroom",
  "Viktor's face going slack as the whole shape of it lands on him at once",
  "CU","eye","push_in","day",False,True,
  "и теперь тебя действительно нет там, где именно сейчас надо было быть."),
 ("A10_SH07", None, "courtroom",
  "a courtroom from above with eleven occupied seats scattered through the rows and a clerk's table stacked with folders",
  "WS","high","static","day",True,False,
  "в зал приходят четырнадцать человек, и восемь из них пришли по повесткам."),
 ("A10_SH08", "ANYA_BASE", "courtroom",
  "Anya sitting straight-backed in the front row with the yellow rucksack held on her lap in both arms",
  "MS","eye","static","day",False,False,
  "Аня сидит в первом ряду и ни разу не смотрит в твою сторону."),
 ("A10_SH09", "ANYA_BASE", "courtroom",
  "Anya's face speaking evenly from a standing position entirely from memory, looking straight ahead",
  "CU","eye","static","day",False,True,
  "она говорит четыре минуты, и после неё в зале становится очень тихо."),
 ("A10_SH10", "DEN_ADULT", "courtroom",
  "Denis standing inside a low railed enclosure in the same black work jacket, hands loose, the red cap gone",
  "MS","eye","static","day",False,False,
  "Денис стоит за оградкой в той же самой чёрной куртке и молчит."),
 ("A10_SH11", "DEN_ADULT", "courtroom",
  "Denis's face facing the bench, calm and closed, his face shut to the room",
  "CU","low","static","day",False,False,
  "ему двадцать два, и он не сказал про тебя ни одного слова."),
 ("A10_SH12", None, "courtroom",
  "a courtroom bench with a folded printed judgment lying on it beside a water glass and a wall clock visible above the door",
  "WS","eye","static","day",True,False,
  "приговор читают в четверг утром, и чтение его занимает ровно девять минут."),
 ("A10_SH13", "VIK_OLD", "courtroom",
  "Viktor standing among the risen spectators with his hands at his sides, hearing a number and standing perfectly still",
  "CU","eye","static","day",False,True,
  "четыре года, и ты слышишь это стоя, потому что встали все вокруг."),
 ("A10_SH14", None, "courtroom",
  "a side door in a courtroom wall standing just ajar and then closed, the enclosure beside it empty, chairs pushed back",
  "WS","low","static","day",True,False,
  "его уводят через боковую дверь, и эта дверь потом закрывается совершенно бесшумно."),
 ("A10_SH15", "LENA_ADULT", "court_corridor",
  "Lena standing in the corridor with her coat already buttoned and her bag on her shoulder, entirely dry-eyed",
  "MCU","eye","static","day",False,False,
  "Лена стоит в коридоре и не плачет, потому что плакала все семь месяцев."),
 ("A10_SH16", "LENA_ADULT", "court_corridor",
  "Lena's face saying one short sentence and then closing, the locket showing at her collar",
  "CU","eye","push_in","day",False,True,
  "она произносит одну фразу и потом молчит с тобой целых два года."),
 ("A10_SH17", ("VIK_OLD","LENA_ADULT"), "court_corridor",
  "Viktor half turns towards Lena while she keeps facing the far end of the corridor and speaks past him",
  "MS","eye","static","day",False,False,
  "она говорит, что подписала тогда не читая, и это её вина тоже."),
 ("A10_SH18", "VIK_OLD", "court_corridor",
  "Viktor's mouth opening on an objection that dies there, his hand lifting halfway and stopping",
  "CU","low","static","day",False,False,
  "ты хочешь сказать ей, что это не так, и не находишь слов."),
 ("A10_SH19", None, "flat_room",
  "a living room with one wardrobe door left open, empty hangers on the rail and a rectangle of clean floor where a case has stood",
  "WS","eye","static","day",True,False,
  "через месяц она уезжает к сестре и забирает оттуда только свои вещи."),
 ("A10_SH20", None, "flat_room",
  "a papered wall with one pale unfaded rectangle on it and a small nail left in the middle of the pale patch",
  "INSERT","top","static","day",True,True,
  "на стене остаётся светлый прямоугольник на месте той фотографии, которую она сняла."),
 ("A10_SH21", None, "dealer_lot",
  "a car lot from very high with an official notice taped to the gate, most spaces empty and a tow truck backed up to the last row",
  "EWS","high","pan_right","day",True,False,
  "площадку забирают за долги в августе, вместе со всеми её четырнадцатью машинами."),
 ("A10_SH22", "VIK_OLD", "dealer_lot",
  "Viktor up on a short stepladder unbolting a name board from the banner frame, holding it under one arm as it comes free",
  "MS","eye","static","day",False,False,
  "ты снимаешь баннер сам, потому что его всё равно больше некому снимать."),
 ("A10_SH23", "OBJ:keys", None,
  "an emptied key cabinet with an inventory sheet taped inside its door",
  "INSERT","eye","static","interior",True,False,
  "сорок ключей ты сдаёшь по описи и расписываешься за каждый из них."),
 ("A10_SH24", "VIK_OLD", "dealer_lot",
  "Viktor standing on the empty apron with the leather pouch on his wrist and his hands otherwise empty",
  "MS","low","static","dusk",False,False,
  "в сорок шесть у тебя остаётся барсетка, куртка и восемь невыплаченных выплат."),
 ("A10_SH25", "VIK_OLD", "dealer_lot",
  "Viktor pulling the sliding gate across on its rollers and threading somebody else's padlock through the hasp",
  "MCU","eye","static","dusk",False,False,
  "ты выходишь с площадки последним и закрываешь ворота уже на чужой замок."),
 ("A10_SH26", None, "dealer_lot",
  "an emptied car lot at dusk with the bunting still strung overhead above bare painted parking lines",
  "WS","eye","pull_out","dusk",True,True,
  "а флажки на проволоке остаются висеть, потому что их никто не снял."),
]

CODA = [
 ("A11_SH01", None, "car_wash",
  "a two-bay hand car wash under a corrugated canopy seen from high above, wet concrete running with grey foam towards a floor drain",
  "EWS","high","static","day",True,False,
  "в сорок семь ты моешь машины на мойке у выезда из города."),
 ("A11_SH02", "VIK_OLD", "car_wash",
  "Viktor in rubber boots and a wet apron working a long-handled brush across a roof, both hands high on the shaft",
  "MS","eye","static","day",False,False,
  "смена двенадцать часов и четыреста за смену, и пока тебя это устраивает."),
 ("A11_SH03", None, "car_wash",
  "a sheet of white foam sliding down a bonnet and carrying a curtain of road dirt with it towards the sill",
  "INSERT","top","static","day",True,False,
  "пена сходит по капоту вниз и уносит с собой чужую дорожную грязь."),
 ("A11_SH04", "VIK_OLD", "car_wash",
  "Viktor's face close through the drifting spray, reading a car the way he always has, his mouth shut",
  "CU","low","static","day",False,False,
  "ты знаешь про каждую машину больше, чем её хозяин, и всегда молчишь."),
 ("A11_SH05", None, "car_wash",
  "a wash bay from ground level with a car nose-in under the canopy and a plastic curtain hanging half across the entrance",
  "WS","low","static","day",True,False,
  "иногда сюда заезжают люди, которым ты когда-то сам продал одну из этих машин."),
 ("A11_SH06", "VIK_OLD", "car_wash",
  "Viktor stepping back from a window with the brush lowered, looking at a driver who looks straight through him",
  "MCU","eye","static","day",False,False,
  "они тебя не узнают, потому что в резиновых сапогах ты другой человек."),
 ("A11_SH07", "OBJ:barsetka", None,
  "an open metal locker door in a damp changing room",
  "INSERT","eye","static","interior",True,True,
  "барсетка лежит в шкафчике, и в ней теперь только ключ от комнаты."),
 ("A11_SH08", None, "prison_visit",
  "a bare visiting room with a long partition of scratched glass, low stools bolted to the floor and a handset hanging on an armoured cord",
  "WS","eye","static","day",True,False,
  "раз в два месяца ты ездишь к сыну, четыре часа туда автобусом."),
 ("A11_SH09", "VIK_OLD", "prison_visit",
  "Viktor sitting down on a bolted stool and lifting the handset off its hook with both hands",
  "MS","eye","static","day",False,False,
  "свидание длится сорок минут, и говорить надо через трубку на коротком шнуре."),
 ("A11_SH10", "VIK_OLD", "prison_visit",
  "Viktor's face at the scratched glass with the handset already at his ear and the far side still empty",
  "CU","eye","static","day",False,False,
  "первые три раза он выходил и садился, но трубку так и не поднимал."),
 ("A11_SH11", "DEN_ADULT", "prison_visit",
  "Denis on the far side of the glass reaching for the handset and settling it against his shoulder",
  "MCU","eye","static","day",False,False,
  "на четвёртый раз он поднял и спросил только, как здоровье у матери."),
 ("A11_SH12", ("VIK_OLD","DEN_ADULT"), "prison_visit",
  "Viktor holds the handset to his ear on the near side of the partition while Denis, beyond the scratched glass, holds his own handset up and answers him",
  "MS","eye","static","day",False,False,
  "вы говорите про мать, про погоду и про то, что дают есть."),
 ("A11_SH13", "DEN_ADULT", "prison_visit",
  "Denis's face through the glass, easy and neutral, keeping the conversation exactly where it is",
  "CU","eye","static","day",False,False,
  "про ту машину вы не говорите ни разу за весь этот год."),
 ("A11_SH14", "VIK_OLD", "prison_visit",
  "Viktor leaning in closer to the glass with the handset pressed hard against his ear, asking something at last",
  "MCU","low","static","day",False,False,
  "в последнее свидание ты спрашиваешь у него, что он будет делать после."),
 ("A11_SH15", "DEN_ADULT", "prison_visit",
  "Denis's face answering straight away, a small shrug moving one shoulder",
  "CU","eye","push_in","day",False,True,
  "он говорит, что пойдёт торговать машинами, потому что больше ничего не умеет."),
 ("A11_SH16", "VIK_OLD", "prison_visit",
  "Viktor's mouth asking one more question while his free hand flattens on the counter",
  "MCU","eye","static","day",False,False,
  "ты спрашиваешь его, как он будет отвечать, если его спросят про пробег."),
 ("A11_SH17", "DEN_ADULT", "prison_visit",
  "Denis's face saying four short words through the glass and then setting the handset back on its hook",
  "CU","eye","static","day",False,True,
  "как себе брал, отвечает он тебе через стекло, и кладёт трубку обратно."),
 ("A11_SH18", None, "prison_visit",
  "an empty stool on the far side of a scratched glass partition with a handset swinging slowly on its cord",
  "WS","high","static","day",True,True,
  "ты сидишь ещё минуту с трубкой в руке, хотя там уже пусто."),
 ("A11_SH19", "VIK_OLD", "car_wash",
  "Viktor standing in the wash bay with the hose slack in one hand, looking straight down the lens for the first time",
  "MCU","eye","static","day",False,True,
  "если ты сейчас думаешь, что у тебя всё под контролем, послушай меня."),
 ("A11_SH20", "VIK_OLD", "car_wash",
  "Viktor's face close, speaking quietly and directly at the camera in a plain flat register",
  "CU","eye","push_in","day",False,True,
  "за тридцать лет мне ни разу не было страшно, ни одной минуты."),
 ("A11_SH21", None, "night_crash_site",
  "a dark empty two-lane road at night with a repaired guard rail catching a little light, the lanes standing completely empty",
  "WS","low","static","night",True,False,
  "страшно становится ровно один раз, ночью, на сто девятом километре обычной трассы."),
 ("A11_SH22", "VIK_OLD", "car_wash",
  "Viktor letting the hose sink towards the wet concrete, his shoulders coming down as he stops talking",
  "MCU","low","static","day",False,False,
  "и в этот момент менять уже нечего, потому что всё уже сделано."),
 ("A11_SH23", "VIK_OLD", "car_wash",
  "Viktor standing small in the open mouth of the wash bay in rubber boots with the hose lowered to the concrete, cars passing on the road behind him with paper price cards taped to their mirrors",
  "WS","low","pull_out","day",False,True,
  "ты опускаешь шланг, а мимо едут машины с бумажками на боковых зеркалах."),
 ("A11_SH24", None, "car_wash",
  "a car wash canopy seen from very high with the wet apron below it and a steady line of traffic on the road beyond",
  "EWS","high","pull_out","day",True,False,
  "эта история вымышлена, все совпадения случайны, и ты не повторяй чужих ошибок."),
]

if __name__ == "__main__":
    seed_act("sale",    P8,  SALE)
    seed_act("crash",   P9,  CRASH)
    seed_act("verdict", P10, VERDICT)
    seed_act("coda",    P11, CODA)
