# -*- coding: utf-8 -*-
"""announcer batch A: cold_open(+CTA) + origin. animated."""
from _announcer_engine import seed_act

PAL_NIGHT="cold blue-night station palette, a warm pool of light in the glass booth against the dark vaulted hall, drifting steam, lonely"
COLD=[
 ("A0_SH01",None,"concourse_hall","the vast empty marble concourse of a grand railway terminus seen from high above at night, a huge split-flap board and a great clock under a vaulted glass roof","EWS","high","push_in","night",True,True,
  "ты говоришь, и весь вокзал слышит тебя, и ни один человек не знает твоего лица."),
 ("A0_SH02","ANNOUNCER_OLD","announcer_booth","an old woman in a glass announcer's booth leaning to a heavy microphone, the marble hall glowing far below the window","MS","high","push_in","night",False,False,
  "тебе шестьдесят один, и сорок лет твой голос ведёт этот город от поезда к поезду."),
 ("A0_SH03",None,"announcer_booth","extreme close on a worn brass chime button under an old woman's pressing fingertip","INSERT","top","push_in","night",True,True,
  "ты нажимаешь латунную кнопку, и по залу плывёт твой трёхнотный гонг, знакомый каждому."),
 ("A0_SH04","ANNOUNCER_OLD","announcer_booth","close on the old announcer's lips at the microphone speaking the ritual phrase","CU","eye","push_in","night",False,False,
  "внимание, говоришь ты, на первый путь прибывает поезд, и тысячи голов поднимаются на звук."),
 ("A0_SH05",None,"concourse_hall","the great station clock and the soaring iron-glass roof of the night concourse, empty marble below","WS","low","tilt_up","night",True,False,
  "они слышат тебя каждый день всю жизнь, на свадьбу, на похороны, на войну и обратно."),
 ("A0_SH06","ANNOUNCER_OLD","announcer_booth","the old announcer looking down through the booth glass at the hall below","MCU","high","static","night",False,False,
  "ты видишь их всех сверху, через стекло, а они тебя никогда, ты просто голос с потолка."),
 ("A0_SH07",None,"departures_board","a huge mechanical split-flap departures board flipping through destinations and times","INSERT","eye","push_in","night",True,True,
  "табло щёлкает, рейс за рейсом, и в этих щелчках вся жизнь города уезжает и приезжает."),
 ("A0_SH08","ANNOUNCER_OLD","announcer_booth","close on the old woman's faded deep-red silk scarf knotted at her throat","CU","eye","static","night",False,False,
  "ты бережёшь горло тёмно-красным шарфом, потому что голос это всё, что у тебя есть."),
 ("A0_SH09","ANNOUNCER_OLD","announcer_booth","a wide view of the lone old announcer in the glass booth with the live microphone after hours","MS","eye","static","night",False,False,
  "после смены, когда вокзал засыпает, ты остаёшься одна с живым микрофоном в руке."),
 ("A0_SH10","ANNOUNCER_OLD","concourse_hall","the old woman standing in the empty marble hall at night singing up into the great vault","WS","low","push_in","night",False,True,
  "и тогда ты поёшь пустому залу то, что не спела со сцены, и зал слушает только тебя."),
 ("A0_SH11","ANNOUNCER_OLD","concourse_hall","close on the old announcer singing with her eyes closed in the empty hall","CU","eye","push_in","night",False,False,
  "это единственные минуты в сутках, когда голос принадлежит тебе, а не чужому расписанию."),
 ("A0_SH12",None,"concourse_hall","the immense empty night concourse holding a single unheard song, dust in moonlit shafts","EWS","high","pull_out","night",True,False,
  "огромный мраморный зал слушает тебя, и больше тебя не слышит никто на белом свете."),
 ("A0_SH13","ANNOUNCER_OLD","announcer_booth","the old announcer turning her face toward the viewer to speak directly","MCU","eye","push_in","night",False,False,
  "если хочешь знать, как голос может прожить целую жизнь без человека, останься со мной."),
 ("A0_SH14","ANNOUNCER_OLD","announcer_booth","a direct close on the old woman's tired eyes meeting the camera","CU","eye","push_in","night",False,False,
  "подпишись и досмотри, потому что мой голос ты, может быть, уже слышал, а меня нет."),
 ("A0_SH15",None,"announcer_booth","the dead-quiet booth at night, the microphone and a typed schedule sheet under a lamp","INSERT","eye","static","night",True,False,
  "вся моя жизнь прошла в этой стеклянной будке над залом, между прибытием и отправлением."),
 ("A0_SH16",None,"station_facade","the grand terminus facade and lit clock tower across the cobbled square at night","WS","low","push_in","night",True,True,
  "а начинается всё с девочки, которая хотела петь так, чтобы её услышали и запомнили в лицо."),
 ("A0_SH17","ANNOUNCER_OLD","announcer_booth","the old announcer looking down over the hall, ready to tell her story","MS","eye","static","night",False,False,
  "досмотри со мной, как этот голос стал голосом вокзала и потерял по дороге своё лицо."),
 ("A0_SH18",None,"concourse_hall","the giant round station clock reading midnight over the empty hall","INSERT","low","push_in","night",True,False,
  "большие часы над залом показывают полночь, и последний поезд уже ушёл без пассажиров."),
 ("A0_SH19","ANNOUNCER_OLD","announcer_booth","close on the old woman switching off the booth lamp, weary","CU","eye","static","night",False,False,
  "ты гасишь свет в будке последней и спускаешься в пустой зал, где тебя никто не ждёт."),
 ("A0_SH20","ANNOUNCER_OLD","concourse_hall","a small lone figure crossing the vast empty marble hall, glancing up at the speakers","WS","high","track","night",False,False,
  "ты идёшь домой через зал, в котором всю жизнь звучала, и шаги твои тонут под сводом."),
 ("A0_SH21",None,"platform_night","a deserted night platform with a single pool of lamplight and faint mist","INSERT","eye","push_in","night",True,True,
  "перрон пуст, и только твой голос ещё висит в воздухе эхом последнего объявления."),
 ("A0_SH22","ANNOUNCER_OLD","station_facade","the old woman pausing on the station steps to look back at the lit terminus","MCU","low","static","night",False,False,
  "ты оборачиваешься на вокзал, светящийся в темноте, и он отвечает тебе эхом твоего же голоса."),
]

PAL_SCHOOL="warm nostalgic 1985 palette, honey afternoon light and floating dust, hopeful amber and soft shadow"
A1=[
 ("A1_SH01",None,"music_school","a worn 1980s vocal-conservatory rehearsal room, a black upright piano, tall curtained windows, faded recital photographs","EWS","eye","push_in","day",True,False,
  "тысяча девятьсот восемьдесят пятый, тебе двадцать четыре, и у тебя голос, каких очень мало."),
 ("A1_SH02","ANNOUNCER_YOUNG","music_school","a radiant young woman singing beside the upright piano in the rehearsal room","MS","low","static","day",False,False,
  "ты поёшь в вокальной школе так, что преподаватель замолкает, и тебе прочат большую сцену."),
 ("A1_SH03","ANNOUNCER_YOUNG","music_school","close on the young woman's face mid-song, alive and certain","CU","eye","push_in","day",False,False,
  "голос у тебя чистый и сильный, и ты уже видишь своё имя на афишах оперного театра."),
 ("A1_SH04","RIVAL_BASE","music_school","a poised polished classmate with a conservatory pin watching, composed and elegant","MCU","eye","static","day",False,False,
  "рядом учится другая, с меньшим голосом, но с лицом и осанкой для сцены, и это решит всё."),
 ("A1_SH05",None,"music_school","a bare audition stage with an empty row of committee chairs and a single lamp","WS","eye","push_in","day",True,False,
  "приходит день прослушивания в театр, и ты выходишь, и поёшь лучше всех в зале."),
 ("A1_SH06","ANNOUNCER_YOUNG","music_school","close on the young woman's hopeful face faltering as she hears the verdict","CU","eye","push_in","day",False,False,
  "но комиссия смотрит не на голос, а на тебя, и качает головой, и говорит обидное."),
 ("A1_SH07","ANNOUNCER_YOUNG","music_school","the young woman standing alone on the audition stage taking the rejection","MCU","eye","static","day",False,False,
  "они говорят, что голос у тебя для объявлений, а не для сцены, и берут ту, с осанкой."),
 ("A1_SH08","RIVAL_BASE","music_school","the accepted rival glowing with success, the conservatory pin on her lapel","CU","eye","static","day",False,False,
  "однокурсницу берут в театр, и через год её имя уже на афишах, а твоё нигде."),
 ("A1_SH09","ANNOUNCER_YOUNG","station_facade","the young woman wandering toward the railway terminus, lost and aimless","WS","eye","track","day",False,False,
  "ты бродишь по городу, не зная, куда деть свой голос, и ноги приводят тебя на вокзал."),
 ("A1_SH10",None,"concourse_hall","the immense humming daytime concourse, the split-flap board and vaulted roof, overwhelming","EWS","low","tilt_up","day",True,True,
  "огромный зал гудит под сводом, и впервые ты слышишь, как объявляют поезда живым голосом."),
 ("A1_SH11","STATIONMASTER_BASE","concourse_hall","an old stationmaster with a brass whistle on a lanyard noticing the young woman","MS","eye","static","day",False,False,
  "старый начальник вокзала со свистком на шнуре слышит, как ты повторяешь объявление вполголоса."),
 ("A1_SH12","STATIONMASTER_BASE","concourse_hall","close on the old stationmaster's kind shrewd face turning toward her","CU","eye","push_in","day",False,False,
  "он оборачивается, потому что таким голосом тут никто не говорил, и спрашивает, кто ты."),
 ("A1_SH13","ANNOUNCER_YOUNG","stationmaster_office","the young woman before a desk in an office walled with clocks of different cities","MCU","eye","static","day",False,False,
  "он ведёт тебя в кабинет, где на стене десяток часов разных городов, и предлагает работу."),
 ("A1_SH14","STATIONMASTER_BASE","stationmaster_office","close on the stationmaster offering the job, warm and certain","CU","eye","static","day",False,False,
  "он говорит, голос у тебя редкий, нам нужен такой над залом, иди в дикторскую будку."),
 ("A1_SH15","ANNOUNCER_YOUNG","announcer_booth","the young woman entering the glass booth above the hall for the first time","WS","eye","push_in","day",False,False,
  "ты поднимаешься в стеклянную будку над залом, и весь вокзал лежит у тебя под ногами."),
 ("A1_SH16",None,"announcer_booth","the heavy bakelite microphone and the brass chime button waiting in the booth","INSERT","eye","push_in","day",False,True,
  "перед тобой тяжёлый микрофон и латунная кнопка гонга, и это твоя новая единственная сцена."),
 ("A1_SH17","ANNOUNCER_YOUNG","announcer_booth","the young woman pressing the chime button for the first time","MCU","eye","static","day",False,False,
  "ты нажимаешь кнопку, плывёт трёхнотный гонг, и впервые твой голос наполняет весь зал."),
 ("A1_SH18","ANNOUNCER_YOUNG","announcer_booth","close on the young woman's face speaking her first announcement","CU","eye","push_in","day",False,False,
  "внимание, говоришь ты, и тысяча человек внизу поднимает головы, и слушает тебя одну."),
 ("A1_SH19",None,"concourse_hall","the daytime hall below with heads turned up toward the ceiling loudspeakers","WS","high","static","day",True,False,
  "впервые тебя слушают тысячи, и это почти как сцена, только тебя при этом совсем не видно."),
 ("A1_SH20","ANNOUNCER_YOUNG","announcer_booth","the young woman realising the bargain of the voice, quiet","MCU","eye","push_in","day",False,False,
  "ты понимаешь, что голос твой услышат все, а лицо твоё не увидит никто и никогда."),
 ("A1_SH21",None,"announcer_booth","the booth window looking down over the hall like a theatre box","INSERT","high","static","day",True,False,
  "из будки ты видишь всех, как из ложи, в которую тебя так и не пустили на сцену."),
 ("A1_SH22","ANNOUNCER_YOUNG","announcer_booth","close on the young woman tying the deep-red silk scarf at her throat","CU","eye","push_in","day",False,True,
  "ты повязываешь тёмно-красный шарф на горло и клянёшься беречь голос для лучшего дня."),
 ("A1_SH23","ANNOUNCER_YOUNG","announcer_booth","the young woman settling into the booth chair at the microphone","MS","eye","static","day",False,False,
  "ты говоришь себе, что это на время, пока не позовут на сцену, и остаёшься на сорок лет."),
 ("A1_SH24","ANNOUNCER_YOUNG","platform_day","the young announcer watching a train and its passengers from the booth window above","WS","high","static","day",False,False,
  "ты учишься читать людей сверху, по тому, на какой поезд они бегут и кого встречают."),
 ("A1_SH25","ANNOUNCER_YOUNG","announcer_booth","close on the young woman observing the crowd through the glass","CU","eye","push_in","day",False,False,
  "ты узнаёшь их по чемоданам, по слезам, по букетам, и голос твой ведёт их, не зная имён."),
 ("A1_SH26",None,"departures_board","the split-flap board flipping as a new train is announced","INSERT","eye","push_in","day",True,False,
  "табло щёлкает, и ты подаёшь голос к каждой строке, и город привыкает к тебе, как к дыханию."),
 ("A1_SH27","ANNOUNCER_YOUNG","announcer_booth","the young woman working a long shift at the microphone","MS","eye","static","day",False,False,
  "ты работаешь по двенадцать часов, объявляешь сотни рейсов, и голос твой не устаёт никогда."),
 ("A1_SH28","ANNOUNCER_YOUNG","announcer_booth","close on the young woman softly singing along to a radio in the booth","CU","eye","static","day",False,False,
  "по радио в будке поёт твоя однокурсница, и ты подпеваешь ей тихо, чтобы никто не слышал."),
 ("A1_SH29","ANNOUNCER_YOUNG","announcer_booth","close on the young woman's bittersweet face listening","MCU","eye","push_in","day",False,False,
  "у неё лицо на афишах, а у тебя голос над залом, и ты убеждаешь себя, что это почти то же."),
 ("A1_SH30",None,"concourse_hall","the empty marble hall at night after the last train, dim and vast","WS","high","static","night",True,True,
  "а ночью, когда уходит последний поезд и гаснет зал, ты остаёшься одна с живым микрофоном."),
 ("A1_SH31","ANNOUNCER_YOUNG","concourse_hall","the young woman singing up into the empty night hall for the first time","MCU","low","push_in","night",False,True,
  "и ты впервые поёшь пустому вокзалу арию, которую не спела на том прослушивании."),
 ("A1_SH32","ANNOUNCER_YOUNG","concourse_hall","close on the young woman singing with closed eyes, free in the empty hall","CU","eye","push_in","night",False,False,
  "голос летит под свод и возвращается эхом, и пустой зал даёт тебе то, чего не дал театр."),
 ("A1_SH33",None,"concourse_hall","the vast empty hall holding her song, dust in the dim light","EWS","high","pull_out","night",True,False,
  "мраморный пол и пустые скамьи слушают тебя, и тебе впервые за целый год легко."),
 ("A1_SH34","ANNOUNCER_YOUNG","announcer_booth","the young woman back at announcements by day, composed","MCU","eye","static","day",False,False,
  "днём ты снова голос с потолка, безымянный, а ночью на пустой сцене ты наконец певица."),
 ("A1_SH35","ANNOUNCER_YOUNG","announcer_booth","close on the young woman promising herself the stage will come","CU","eye","push_in","day",False,False,
  "ты говоришь себе, ещё год, ещё прослушивание, и ты выйдешь на сцену по-настоящему."),
 ("A1_SH36",None,"station_facade","the terminus facade across the seasons, light changing on the stone","INSERT","eye","pan_right","day",True,False,
  "но проходит год, и второй, и пятый, и тебя зовут только к микрофону, и ты привыкаешь."),
 ("A1_SH37","STATIONMASTER_BASE","announcer_booth","the older stationmaster praising the announcer at her booth","MS","eye","static","day",False,False,
  "начальник вокзала зовёт тебя лучшим голосом за сто лет дороги, и ты этим живёшь."),
 ("A1_SH38","ANNOUNCER_YOUNG","announcer_booth","close on the young woman settling into the bargain","CU","eye","push_in","day",False,False,
  "тебе двадцать девять, у тебя нет лица для города, зато есть голос, который знают все."),
 ("A1_SH39",None,"platform_day","a departing train wreathed in steam under the great trainshed","WS","low","static","day",True,True,
  "ты ещё не знаешь, что этот голос проживёт твою жизнь вместо тебя и доживёт без тебя."),
 ("A1_SH40","ANNOUNCER_YOUNG","announcer_booth","the young woman watching the hall, learning to love it from above","MCU","high","static","day",False,False,
  "ты привыкаешь любить их всех сверху, безответно, объявляя чужие встречи и расставания."),
 ("A1_SH41","ANNOUNCER_YOUNG","announcer_booth","close on the young woman keeping the discipline of the voice","CU","eye","static","day",False,False,
  "ты не куришь, не пьёшь холодного, спишь с шарфом на горле, чтобы голос звучал ровно."),
 ("A1_SH42","ANNOUNCER_YOUNG","concourse_hall","the young announcer watching a tearful farewell on the floor below","WS","high","static","day",False,False,
  "ты смотришь сверху, как внизу прощаются, и ведёшь их голосом, и завидуешь их слезам."),
 ("A1_SH43",None,"departures_board","a delayed train flipping up on the split-flap board","INSERT","eye","push_in","day",True,False,
  "ты объявляешь опоздания и отмены, и от твоего голоса зависит, побежит человек или сядет ждать."),
 ("A1_SH44","ANNOUNCER_YOUNG","announcer_booth","the young woman calming a crowd with a single word into the microphone","MCU","eye","static","day",False,False,
  "одним словом в микрофон ты можешь успокоить целый перрон или поднять его на ноги."),
 ("A1_SH45","ANNOUNCER_YOUNG","announcer_booth","close on the young woman alone in the booth, loneliness creeping in","CU","eye","push_in","day",False,False,
  "но в будке ты всегда одна, говоришь с тысячами, и не с кем сказать простое, не для эфира."),
 ("A1_SH46","ANNOUNCER_YOUNG","concourse_hall","the young woman singing again to the empty night hall, her secret ritual","WS","low","push_in","night",False,False,
  "каждую ночь ты поёшь пустому залу, и это становится твоей тайной второй жизнью."),
 ("A1_SH47",None,"concourse_hall","the empty night hall and the great stopped-seeming clock holding her unheard song","INSERT","low","push_in","night",True,True,
  "никто не слышит этих ночных концертов, кроме мрамора, эха и больших настенных часов."),
 ("A1_SH48","ANNOUNCER_YOUNG","announcer_booth","close on the young woman, the bargain quietly sealed","MCU","eye","static","night",False,False,
  "ты выбираешь этот вокзал, эту будку, этот голос, и не замечаешь, как выбираешь это навсегда."),
 ("A1_SH49","ANNOUNCER_YOUNG","announcer_booth","close on the young woman's face, hope narrowing into habit","CU","eye","push_in","night",False,False,
  "тебе кажется, что лучше быть голосом, который любят все, чем лицом, которое не нужно никому."),
 ("A1_SH50",None,"announcer_booth","the empty booth at dawn, the microphone waiting under a grey light","INSERT","eye","push_in","day",True,True,
  "тебе двадцать девять, впереди ещё тридцать два года объявлений и ни одного твоего концерта."),
]

seed_act("cold_open", PAL_NIGHT,  COLD, render_mode="animated")
seed_act("origin",    PAL_SCHOOL, A1,   render_mode="animated")
