# -*- coding: utf-8 -*-
"""lottery A0 cold_open + A1 origin + A2 win + A3 fire_bridges. PYTHONIOENCODING=utf-8 python scripts/_seed_lottery_A0A3.py"""
from _lottery_engine import seed_act

P_COLD="dawn shift palette, cold blue morning steel warmed by sodium checkpoint light, worn and settled"
P_ORIGIN="nineties flashback palette, faded newsprint grey and warm kiosk amber, nostalgic worn browns"
P_WIN="ordinary-life palette, warm kitchen bulb and workshop steel, one sudden gold accent cutting through"
P_BRIDGES="new-money palette, showroom white and champagne gold over glass, glossy and slightly cold"

COLD=[
 ("A0_SH01",None,"factory_gate","a wide establishing view of a factory checkpoint at six in the morning, a queue of workers at steel turnstiles under sodium light","WS","eye","push_in","dawn",True,False,
  "шесть утра, проходная завода, и ты стоишь в очереди рабочих с новеньким пропуском в руке."),
 ("A0_SH02","HERO_BACK","factory_gate","a medium close-up of a weathered grey-templed man of forty-six holding a fresh pass card, a guard glancing at him twice","MCU","eye","static","dawn",False,False,
  "тебе сорок шесть, фото на пропуске ещё глянцевое, и охранник смотрит на тебя дважды."),
 ("A0_SH03","OBJ:pass_card",None,"an extreme close-up macro insert of a brand-new factory pass card with a glossy photo corner","ECU","eye","static","dawn",True,False,
  "четыре года назад ты выбросил старый пропуск в урну у этих же турникетов, с размахом."),
 ("A0_SH04","HERO_BACK","factory_gate","a medium shot of the man passing the clicking turnstile, shoulders easing as he crosses","MS","eye","track","dawn",False,False,
  "загорается зелёный, турникет щёлкает, и ты вдыхаешь заводской воздух, как будто вернулся с войны."),
 ("A0_SH05","HERO_BACK","factory_gate","a close-up of the man's calm settled face answering a question over his shoulder","CU","eye","push_in","dawn",False,False,
  "охранник всё-таки спрашивает: ты же вроде выиграл, — и ты отвечаешь: выиграл, вроде."),
 ("A0_SH06",None,"factory_shop","a wide view of the machine shop waking up, high sooty windows letting in first light over ranks of lathes","WS","eye","pan_right","dawn",True,False,
  "в цеху всё те же станки, тот же запах масла и стружки, и это лучший запах за четыре года."),
 ("A0_SH07","OBJ:ticket_frame",None,"an extreme close-up macro insert of a thin gilded frame lying glass-down in a steel tool drawer","ECU","top","static","day",True,True,
  "в ящике для инструмента у станка лежит рамка с лотерейным билетом, стеклом вниз."),
 ("A0_SH08","HERO_BACK","factory_shop","a medium close-up of the man looking down into the open tool drawer, jaw set evenly","MCU","high","static","day",False,False,
  "в этой рамке семьдесят три миллиона четыреста тысяч: шесть чисел, один вечер и вся жизнь."),
 ("A0_SH09",None,"factory_shop","a wide view down the shop aisle, machines and yellow floor lines receding into work-light haze","WS","low","static","day",True,False,
  "как эти миллионы поместились обратно в ящик для ключей, я расскажу тебе по порядку."),
 ("A0_SH10","HERO_BACK","factory_shop","a medium close-up of the man turning to the viewer, wiping his hands on a rag","MCU","eye","push_in","day",False,False,
  "останься со мной до конца, если хоть раз держал в руках лотерейный билет."),
 ("A0_SH11","HERO_BACK","factory_shop","a close-up of the man's steady grey eyes, work light warm on a lined face","CU","eye","push_in","day",False,False,
  "подпишись, мне эта история обошлась в семьдесят три миллиона, тебе достанется бесплатно."),
 ("A0_SH12",None,"factory_gate","a wide view of the checkpoint from outside at sunrise, workers streaming in under the lightening sky","WS","eye","pull_out","dawn",True,False,
  "а началась она не с выигрыша, а с отца, киоска и одной фразы в девяносто восьмом."),
]

ORIGIN=[
 ("A1_SH01",None,"city_street","a wide establishing view of a regional-city street in the late nineties, low facades, overhead wires, a bus with a route board","WS","eye","push_in","day",True,False,
  "девяносто восьмой, тебе восемнадцать, вы с отцом идёте с завода одной сменой."),
 ("A1_SH02","FATHER_BASE","kiosk","a medium close-up of a wiry flat-capped workman of fifty at a lottery kiosk window, a folded newspaper under his arm","MCU","eye","static","day",False,False,
  "каждую пятницу после кассы отец подходит к лотерейному киоску, и это целый ритуал."),
 ("A1_SH03",None,None,"an extreme close-up insert of a few coins laid out precisely on a worn kiosk coin tray","ECU","top","static","day",True,False,
  "он выкладывает на лоток ровно пять рублей, никогда больше, хоть карман и звенит."),
 ("A1_SH04","FATHER_BASE","kiosk","a medium shot of the flat-capped father raising a teaching finger at his lanky son by the kiosk","MS","eye","static","day",False,True,
  "и говорит тебе своё всегдашнее: запомни, с получки — один, больше — уже жадность."),
 ("A1_SH05","HERO_YOUNG","kiosk","a close-up of a lanky eighteen-year-old nodding along, eyes elsewhere, half-listening","CU","eye","push_in","day",False,False,
  "ты киваешь, как кивают отцам, вполуха, и запоминаешь эту фразу на всю жизнь."),
 ("A1_SH06",None,"kiosk","a wide view of the little kiosk with faded winner posters, huge printed sums bleached by sun","WS","eye","static","day",True,False,
  "на киоске выцветшие плакаты победителей, и отец говорит, что улыбки там нарисованные."),
 ("A1_SH07","FATHER_BASE","khrush_kitchen","a medium close-up of the father checking draw numbers against a newspaper at the oilcloth table, pencil in hand","MCU","eye","static","evening",False,False,
  "по воскресеньям он сверяет числа с газетой, проигрывает и совершенно не расстраивается."),
 ("A1_SH08",None,None,"an extreme close-up insert of a newspaper lottery results table with pencil ticks beside the rows","ECU","top","static","evening",True,True,
  "отец говорит: я плачу пять рублей за вечер надежды, и это честная цена."),
 ("A1_SH09","HERO_YOUNG","city_street","a medium shot of father and son walking home along the evening street, same stride, different heights","MS","eye","track","evening",False,False,
  "эта арифметика кажется тебе стариковской ерундой, но пятница за пятницей въедается в кожу."),
 ("A1_SH10",None,"khrush_kitchen","a wide view of the small warm kitchen in the evening, a kettle steaming, two places cleared","WS","eye","static","evening",True,False,
  "отец умрёт в две тысячи пятнадцатом, так ни разу крупно и не выиграв."),
 ("A1_SH11",None,None,"an extreme close-up insert of an eight-panel flat cap hanging on a hallway hook","ECU","eye","push_in","evening",True,False,
  "тебе останутся его кепка, его разряд наладчика и привычка: с получки — один билетик."),
 ("A1_SH12","HERO_WORK","kiosk","a medium shot of a solid machinist of forty-two stepping up to the same kiosk window with the same stride","MS","eye","static","day",False,False,
  "двадцать четыре года спустя ты подходишь к тому же киоску тем же отцовским шагом."),
]

WIN=[
 ("A2_SH01",None,"factory_shop","a wide establishing view of the machine shop in full swing, chips flying at a lathe, hoists moving","WS","eye","push_in","day",True,False,
  "две тысячи двадцать второй: тебе сорок два, ты наладчик высшего разряда, зарплата шестьдесят восемь."),
 ("A2_SH02","HERO_WORK","factory_shop","a medium shot of the machinist leaning an ear to a running machine, hand resting on the housing","MS","eye","static","day",False,False,
  "станки ты слышишь, как врач сердце, и очередь на твою настройку — на неделю вперёд."),
 ("A2_SH03","OBJ:wrench",None,"an extreme close-up macro insert of a big adjustable wrench with a palm-polished handle on a workbench","ECU","top","static","day",True,False,
  "твой разводной ключ отполирован ладонью до блеска, и подмастерья зовут его именным."),
 ("A2_SH04","TANYA_BASE","khrush_kitchen","a medium close-up of a warm braided woman of thirty-eight at the stove, glancing back with a smile","MCU","eye","static","evening",False,False,
  "дома тебя ждут Таня, пятнадцатилетний Максим в наушниках и ипотека, закрытая наполовину."),
 ("A2_SH05",None,"khrush_kitchen","a wide view of the family supper at the oilcloth table, a cake box open, three cups out","WS","eye","static","evening",True,False,
  "по пятницам ты приносишь зарплату, билетик и торт, и это называется хорошая жизнь."),
 ("A2_SH06",None,None,"an extreme close-up insert of a lottery ticket passed under a kiosk window, change sliding back","ECU","eye","static","day",True,False,
  "билет в ту пятницу стоит сто пятьдесят, и продавщица желает удачи, как всегда, не глядя."),
 ("A2_SH07","HERO_WORK","kiosk","a medium close-up of the machinist tucking a single ticket into the chest pocket of his work jacket","MCU","eye","static","day",False,False,
  "ты берёшь один, по отцовскому правилу, и суёшь его в нагрудный карман спецовки."),
 ("A2_SH08",None,"khrush_kitchen","a wide view of the kitchen on Sunday evening, a TV glow from the next room, a man's legs under the sink","WS","eye","static","evening",True,False,
  "вечером воскресенья по телевизору крутят барабан, а ты чинишь кран и не смотришь."),
 ("A2_SH09","TANYA_BASE","khrush_kitchen","a medium shot of the braided woman rising from the TV with a ticket in her hand, face gone strange","MS","eye","static","evening",False,False,
  "Таня сверяет числа скорее из вежливости, а потом зовёт тебя странным севшим голосом."),
 ("A2_SH10",None,None,"an extreme close-up insert of a lottery ticket held beside a TV screen, six numbers lining up","ECU","pov","push_in","evening",True,True,
  "шесть чисел на билете совпадают с шестью числами на экране, все шесть, по порядку."),
 ("A2_SH11","HERO_WORK","khrush_kitchen","a medium close-up of the machinist frozen with wet hands and a wrench, staring at the ticket","MCU","eye","static","evening",False,False,
  "ты стоишь с мокрыми руками и просишь Таню перечитать вслух ещё четыре раза."),
 ("A2_SH12","TANYA_BASE","khrush_kitchen","a close-up of the woman laughing and crying at once, palm pressed to her mouth","CU","eye","push_in","evening",False,False,
  "Таня читает, смеётся, плачет и зажимает рот ладонью, чтобы не разбудить Максима."),
 ("A2_SH13",None,"khrush_kitchen","a wide view of two figures whispering at the kitchen table long after midnight, tea untouched","WS","eye","static","night",True,False,
  "вы сидите на кухне до трёх ночи, шёпотом, как заговорщики, и боитесь трогать билет."),
 ("A2_SH14",None,None,"an extreme close-up insert of a lottery ticket sealed into a buckwheat jar on a pantry shelf","ECU","eye","static","night",True,False,
  "на ночь билет прячется в банку из-под гречки, и это самая дорогая гречка страны."),
 ("A2_SH15","HERO_WORK","khrush_kitchen","a medium close-up of the machinist on the phone at the window, standing very straight, listening","MCU","eye","static","day",False,False,
  "утром ты звонишь на горячую линию, и вежливый голос называет сумму: семьдесят три четыреста."),
 ("A2_SH16",None,None,"an extreme close-up insert of a calculator showing a long figure, a pencil noting a percentage beside it","ECU","top","static","day",True,False,
  "минус тринадцать процентов налога, и на счёт ложится шестьдесят три миллиона восемьсот пятьдесят восемь."),
 ("A2_SH17",None,"city_street","a wide view of the ordinary street on a weekday morning, buses and pedestrians about their business","WS","eye","pan_left","day",True,False,
  "неделю вы живёте, как жили: смена, школа, борщ, только гречку никто не трогает."),
 ("A2_SH18","HERO_WORK","factory_shop","a medium shot of the machinist at his lathe hiding a smile badly, a colleague eyeing him","MS","eye","static","day",False,False,
  "в цеху ты молчишь, но улыбаешься так, что мастер спрашивает, не влюбился ли."),
 ("A2_SH19","HERO_WORK","khrush_kitchen","a close-up of the man lying awake in lamplight, eyes open at the ceiling","CU","eye","push_in","night",False,False,
  "по ночам ты лежишь и впервые в жизни не знаешь, что делать с завтра."),
 ("A2_SH20","TANYA_BASE","khrush_kitchen","a medium close-up of the woman speaking quietly across the pillow shadows, braid undone","MCU","eye","static","night",False,True,
  "Таня говорит тихо: только давай останемся собой, — и ты ей, конечно, обещаешь."),
 ("A2_SH21",None,None,"an extreme close-up insert of a phone screen with a bank deposit notification, a very long number","ECU","pov","static","day",True,False,
  "в четверг приходит смс о зачислении, и в нём не помещаются все нули без переноса."),
 ("A2_SH22",None,"khrush_kitchen","a wide view of the little kitchen at supper, three bowls of borscht steaming, the radio murmuring","WS","eye","pull_out","evening",True,False,
  "потом ты будешь вспоминать этот вечер с борщом как последний спокойный на четыре года."),
]

BRIDGES=[
 ("A3_SH01",None,"factory_shop","a wide establishing view of the shop on a Monday morning, lockers open, shift settling in","WS","eye","push_in","day",True,False,
  "в понедельник ты приходишь в цех в последний раз, но пока об этом знаешь только ты."),
 ("A3_SH02","HERO_WORK","factory_shop","a medium shot of the machinist laying a single sheet on the foreman's desk, standing square","MS","eye","static","day",False,False,
  "заявление ты кладёшь мастеру на стол с таким лицом, что он не спорит."),
 ("A3_SH03","MASTER_BASE","factory_shop","a close-up of a stocky thick-spectacled foreman looking up over his glasses, unhurried","CU","eye","static","day",False,True,
  "мастер смотрит поверх толстых очков и говорит одно: станок твой никому не отдам, вернёшься."),
 ("A3_SH04","HERO_WORK","factory_shop","a medium close-up of the machinist grinning too wide, a careless goodbye gesture at the aisle","MCU","eye","static","day",False,False,
  "на прощание ты проставляешься всему цеху и говоришь мастеру пару лишних слов про начальство."),
 ("A3_SH05",None,"restaurant","a wide view of a private dining room mid-celebration, a long crowded table under golden lamps","WS","eye","static","night",True,False,
  "банкет на сорок человек в ресторане, где раньше ты был два раза, оба на юбилеях."),
 ("A3_SH06",None,None,"an extreme close-up insert of a leather bill folder with a thick receipt and banknotes laid on top carelessly","ECU","top","static","night",True,False,
  "счёт за вечер — двести сорок тысяч, и ты оставляешь сверху, не глядя, как в кино."),
 ("A3_SH07","HERO_RICH","city_street","a medium close-up of the man in a new cashmere coat outside a boutique, standing like a workman in costume","MCU","eye","static","day",False,False,
  "кашемировое пальто садится на тебя, как чужая роль, но продавщица говорит: ваше."),
 ("A3_SH08",None,"penthouse","a wide view of the rented penthouse living room, floor-to-ceiling night city, a vast white sofa","WS","eye","pan_right","night",True,False,
  "вы переезжаете в пентхаус за четыреста тысяч в месяц, потому что можете."),
 ("A3_SH09",None,None,"an extreme close-up insert of luxury car keys with a crest dropping into an open palm","ECU","eye","static","day",True,False,
  "ключи от нового кайена ложатся в ладонь, девять миллионов семьсот, самый счастливый звон."),
 ("A3_SH10","HERO_RICH","car_lux","a medium shot of the man driving the luxury SUV high above the traffic, city sliding over the glass","MS","eye","static","day",False,False,
  "ты едешь по городу выше всех, и город из этого кресла выглядит починенным."),
 ("A3_SH11",None,"school_gate_priv","a wide view of tall wrought-iron private school gates, polished cars queuing at drop-off","WS","eye","static","day",True,False,
  "Максима вы переводите в частную школу за миллион двести в год, для будущего."),
 ("A3_SH12","SON_TEEN","school_gate_priv","a medium close-up of a gangly teenager in a stiff new uniform at the gates, headphones on his neck","MCU","eye","static","day",False,False,
  "Максим стоит у кованых ворот в новой форме и просит не провожать его до дверей."),
 ("A3_SH13","TANYA_BASE","penthouse","a close-up of the braided woman touching a marble counter carefully, like an exhibit","CU","eye","static","day",False,False,
  "Таня ходит по пентхаусу, как по музею, и готовит борщ на индукции с недоверием."),
 ("A3_SH14",None,"penthouse","a wide view of the night city beyond the glass wall, one man's small reflection-less silhouette at the window","WS","low","static","night",True,False,
  "по вечерам за стеклом лежит весь город, но смотреть на него почему-то не с кем."),
 ("A3_SH15","OBJ:ticket_frame",None,"an extreme close-up macro insert of the laminated ticket in a gilded frame hung on a pale designer wall","ECU","eye","push_in","day",True,True,
  "билет ты ламинируешь и вешаешь в золочёной рамке в гостиной, на самом видном месте."),
 ("A3_SH16","HERO_RICH","penthouse","a medium close-up of the man mid-story before the frame, glass in hand, gesturing wide","MCU","eye","static","night",False,False,
  "гостям ты рассказываешь историю выигрыша, и с каждым разом она становится всё длиннее."),
]

if __name__=="__main__":
    seed_act("cold_open",P_COLD,COLD)
    seed_act("origin",P_ORIGIN,ORIGIN)
    seed_act("win",P_WIN,WIN)
    seed_act("fire_bridges",P_BRIDGES,BRIDGES)
