# -*- coding: utf-8 -*-
"""donor A4 limit + A5 anton. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_donor_A4A5.py"""
from _donor_engine import seed_act

P_LIMIT="hardening cold palette, sterile clinic whites and grey travel light, greed edging out warmth"
P_ANTON="tentative warming palette, a first real domestic warmth against a cold secret underneath"

LIMIT=[
 ("A4_SH01",None,"doctor_office_bad","a wide establishing view of a sober doctor's office with a desk, an open folder and scan images on a cold lightbox","WS","eye","push_in","day",True,False,
  "в двадцать пять тебя впервые сажают напротив и говорят, что по закону донору положен предел циклов."),
 ("A4_SH02","VRACH_BASE","doctor_office_bad","a medium close-up of a grey-bearded doctor in half-moon glasses explaining gravely across the desk","MCU","eye","static","day",False,False,
  "врач с седой бородой объясняет, что ты почти у самой черты и что сдавать дальше уже опасно."),
 ("A4_SH03","NIKA_MID","doctor_office_bad","a close-up of the woman listening, disappointed rather than frightened","CU","eye","static","day",False,False,
  "ты слушаешь про предел и думаешь не о здоровье, а о том, что лёгкие деньги вот-вот кончатся."),
 ("A4_SH04",None,"clinic_corridor","a wide view of a pale clinic corridor as a figure leaves through the frosted doors","WS","eye","static","day",True,False,
  "ты выходишь из клиники злая, будто у тебя отнимают работу, а вовсе не берегут твоё тело."),
 ("A4_SH05","MARTA_BASE","recruiter_office","a medium close-up of the coordinator on the phone in her glossy office, a low confidential smile","MCU","eye","static","night",False,False,
  "марта Львовна звонит тебе вечером и говорит, что предел легко обойти, если знать нужные места."),
 ("A4_SH06","MARTA_BASE","recruiter_office","a medium shot of the coordinator explaining a scheme across the glass desk, gesturing calmly","MS","over","static","day",False,False,
  "она объясняет, что клиники в разных городах не делятся списками и не видят друг друга совсем."),
 ("A4_SH07",None,None,"an extreme close-up macro insert of a train ticket and a folded map lying on a glass desk, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "тебе достаточно сменить клинику, чуть поправить анкету, и никакой предел тебя больше не догонит."),
 ("A4_SH08","NIKA_MID","recruiter_office","a close-up of the woman weighing the offer, then giving a small hard nod","CU","eye","push_in","day",False,False,
  "ты киваешь, потому что деньги сильнее страха, и в этот вечер ты переступаешь настоящую черту."),
 ("A4_SH09",None,"city_street","a wide view of a railway station forecourt in another grey city under a flat sky","WS","eye","push_in","day",True,False,
  "ты начинаешь ездить в другие города, где тебя никто не знает и ни о чём не расспрашивает."),
 ("A4_SH10","NIKA_MID","clinic_consult","a medium shot of the woman calmly giving details at a new clinic desk","MS","eye","static","day",False,False,
  "в новой клинике ты называешь себя чуть иначе и сдаёшь так, будто это твой самый первый раз."),
 ("A4_SH11",None,None,"an extreme close-up macro insert of two donor folders side by side with two different printed numbers, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "теперь у тебя несколько номеров в разных городах, и ни один список не знает обо всех сразу."),
 ("A4_SH12","NIKA_MID","clinic_procedure","a close-up of the woman's paler face on the couch under the cold lamp, more worn than before","CU","high","static","day",False,False,
  "тело после каждого раза восстанавливается всё дольше, и однажды ты теряешь сознание прямо в поезде."),
 ("A4_SH13",None,"city_street","a wide view of an empty station platform bench under a grey overcast sky","WS","eye","static","day",True,False,
  "ты приходишь в себя на вокзальной лавке, пугаешься на минуту и всё равно едешь дальше."),
 ("A4_SH14","NIKA_MID","clinic_consult","a medium close-up of the woman being reassured by an unknowing new nurse","MCU","eye","static","day",False,False,
  "врачи в новых клиниках не знают твоей истории и уверяют, что ты идеально здорова для донора."),
 ("A4_SH15","MARTA_BASE","recruiter_office","a medium shot of the coordinator counting her share across the desk with satisfaction","MS","eye","static","day",False,False,
  "марта Львовна получает свою долю с каждого города и называет тебя своей золотой девочкой."),
 ("A4_SH16",None,None,"an extreme close-up macro insert of several plain money envelopes stacked on a table, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "конвертов становится всё больше, ты покупаешь всё что хочешь, но радости в этом всё меньше."),
 ("A4_SH17","NIKA_MID","nika_flat","a close-up of the woman sitting alone among new possessions, hollow-eyed","CU","eye","static","night",False,False,
  "ты сидишь среди новых вещей одна и впервые ловишь себя на том, что внутри совсем пусто."),
 ("A4_SH18","NIKA_MID","nika_flat","a medium shot of the woman dropping several paper tabs into a filling glass jar","MS","eye","static","night",False,False,
  "в банке уже за двадцать номерков, и часть из них с чужих бланков из совсем других городов."),
 ("A4_SH19",None,"nika_flat","an extreme close-up macro insert of a glass jar over half full of curled paper number tabs, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,True,
  "ты давно не помнишь, сколько раз ложилась под лампу, и просто окончательно перестаёшь вести счёт."),
 ("A4_SH20","NIKA_MID","nika_flat","a medium close-up of the woman pushing a small brooch deeper into a drawer, not looking at it","MCU","eye","static","night",False,False,
  "брошку матери ты задвигаешь глубже в ящик, чтобы случайно не наткнуться на неё взглядом."),
 ("A4_SH21",None,"city_street","a wide panning view of anonymous city rooftops across several unnamed towns","WS","eye","pan_right","day",True,False,
  "в разных городах живут семьи, которым ты нужна была только как набор подходящих клеток."),
 ("A4_SH22","NIKA_MID","clinic_corridor","a medium shot of the woman walking a clinic corridor mechanically, going through the motions","MS","eye","static","day",False,False,
  "ты продолжаешь ездить и сдавать, будто заведённая, и уже не считаешь это чем-то особенным."),
 ("A4_SH23",None,"clinic_procedure","a wide view of an empty clinical procedure room with the cold lamp switched off","WS","eye","static","day",True,False,
  "ты не знаешь, что каждый лишний цикл тихо забирает у тебя саму возможность родить своего."),
 ("A4_SH24","NIKA_MID","nika_flat","a close-up of the woman of twenty-five, sure she has outsmarted everyone","CU","eye","static","night",False,True,
  "тебе двадцать пять, ты думаешь, что перехитрила всех, а перехитрила только саму себя."),
]

ANTON=[
 ("A5_SH01",None,"city_street","a wide establishing view of a brighter city street on an ordinary clear day","WS","eye","push_in","day",True,False,
  "в тридцать у тебя есть накопления, съёмная квартира и жизнь, которая со стороны выглядит нормальной."),
 ("A5_SH02","NIKA_MID","cafe_meeting","a medium shot of the woman meeting a warm man across a small café table","MS","eye","static","day",False,False,
  "однажды в кафе тебя знакомят с Антоном, спокойным тёплым человеком, который сразу тебе нравится."),
 ("A5_SH03","ANTON_BASE","cafe_meeting","a medium close-up of a kind stubbled man of thirty-five drinking from a chipped blue enamel mug","MCU","eye","static","day",False,False,
  "у Антона щербатая синяя кружка, из которой он пьёт даже чужой кофе, и добрая усталая улыбка."),
 ("A5_SH04",None,None,"an extreme close-up macro insert of two coffee cups on a café table, one a chipped blue enamel mug, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "вы сидите в кафе до закрытия, и ты впервые за годы говоришь с кем-то не о деньгах."),
 ("A5_SH05","NIKA_MID","nika_flat","a close-up of the woman's softened face, falling in love","CU","eye","push_in","night",False,False,
  "ты влюбляешься быстро и сильно и хочешь, чтобы рядом с ним ты была чистой, совсем без прошлого."),
 ("A5_SH06","ANTON_BASE","nika_flat","a medium shot of the man carrying books and his blue mug into her flat, moving in","MS","eye","static","day",False,False,
  "антон перевозит к тебе свои книги и кружку, и квартира впервые становится тёплой и живой."),
 ("A5_SH07","NIKA_MID","nika_flat","a medium close-up of the woman hiding a glass jar on a high shelf, glancing over her shoulder","MCU","eye","static","day",False,False,
  "ты прячешь банку с номерками на антресоль и говоришь себе, что всё это осталось в прошлом."),
 ("A5_SH08",None,"nika_flat","an extreme close-up macro insert of a glass jar of paper tabs pushed to the very back of a high shelf behind old boxes, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "банка стоит в самой глубине шкафа, за старыми коробками, куда Антон никогда не полезет."),
 ("A5_SH09","ANTON_BASE","nika_flat","a medium shot of the man speaking gently about the future over dinner","MS","eye","static","night",False,False,
  "антон осторожно говорит, что когда-нибудь хотел бы детей, двоих, и обязательно с твоими глазами."),
 ("A5_SH10","NIKA_MID","nika_flat","a close-up of the woman freezing behind a smile, something going cold inside","CU","eye","static","night",False,False,
  "ты улыбаешься и переводишь тему, а внутри холодеет, потому что твоих глаз уже слишком много где."),
 ("A5_SH11",None,"city_street","a wide panning view of a railway station under a flat sky, a secret departure","WS","eye","pan_left","day",True,False,
  "ты говоришь, что уезжаешь по работе, а сама едешь в другой город на ещё один цикл."),
 ("A5_SH12","NIKA_MID","clinic_consult","a medium shot of the woman at a clinic desk, older now for a donor","MS","eye","static","day",False,False,
  "тебе тридцать, для донора это уже много, но за светлые глаза закрывают глаза и на возраст."),
 ("A5_SH13",None,"clinic_procedure","an extreme close-up macro insert of the cold bright procedure lamp above an empty couch, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","low","static","day",True,False,
  "ты ложишься под ту же лампу, зная, что дома ждёт человек, которому ты об этом не скажешь."),
 ("A5_SH14","NIKA_MID","clinic_corridor","a close-up of the woman on the phone in the clinic corridor, forcing a bright voice","CU","eye","static","day",False,False,
  "ты звонишь Антону из коридора клиники и бодрым голосом врёшь, что совещание прошло отлично."),
 ("A5_SH15","ANTON_BASE","nika_flat","a medium shot of the man waiting with dinner and his blue mug, trusting and unaware","MS","eye","static","night",False,False,
  "антон встречает тебя с ужином и своей синей кружкой и совершенно ни о чём не подозревает."),
 ("A5_SH16","NIKA_MID","nika_flat","a medium close-up of the woman eating and smiling, the lie sitting heavy for the first time","MCU","eye","static","night",False,False,
  "ты ешь и улыбаешься, и впервые ложь даётся тебе тяжело, потому что этого человека ты любишь."),
 ("A5_SH17",None,"nika_flat","an extreme close-up macro insert of a hand dropping one more paper tab into a hidden jar at night, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,True,
  "ночью ты тайком добавляешь в банку ещё один номерок, пока Антон спит в соседней комнате."),
 ("A5_SH18","NIKA_MID","nika_flat","a close-up of the woman watching the sleeping man, a private promise on her face","CU","eye","static","night",False,False,
  "ты смотришь на спящего Антона и обещаешь себе, что этот цикл был точно самым последним."),
 ("A5_SH19",None,"city_street","a wide view of a quiet city street at early morning, cool light","WS","eye","static","day",True,False,
  "но деньги за один цикл всё ещё больше, чем он приносит домой за несколько месяцев работы."),
 ("A5_SH20","NIKA_MID","nika_flat","a medium shot of the woman pinning her mother's brooch on only while alone in the flat","MS","eye","static","day",False,False,
  "брошку матери ты надеваешь только когда Антона нет дома, будто прячешь от неё вторую жизнь."),
 ("A5_SH21","ANTON_BASE","nika_flat","a medium close-up of the man speaking with quiet hope, a small ring box implied in his hands","MCU","eye","static","night",False,False,
  "антон говорит, что хочет на тебе жениться и состариться рядом, и ты плачешь от счастья и страха."),
 ("A5_SH22","NIKA_MID","nika_flat","a close-up of the woman saying yes through tears, resolving to stop for good","CU","eye","push_in","night",False,False,
  "ты говоришь да и клянёшься себе, что с прошлым покончено и что теперь будет только он один."),
 ("A5_SH23",None,"nika_flat","a wide view of the modest flat looking warm and lived-in, a real home at last","WS","eye","static","night",True,False,
  "квартира впервые похожа на настоящий дом, и ты почти веришь, что честно его заслужила."),
 ("A5_SH24","NIKA_MID","nika_flat","a medium close-up of the woman of thirty, believing she is starting a clean new life","MCU","eye","static","night",False,True,
  "тебе тридцать, ты думаешь, что начинаешь новую чистую жизнь, и не знаешь, что уже поздно."),
]

if __name__=="__main__":
    seed_act("limit", P_LIMIT, LIMIT, render_mode="static")
    seed_act("anton", P_ANTON, ANTON, render_mode="static")
