# -*- coding: utf-8 -*-
"""donor A8 count + A9 dna_era. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_donor_A8A9.py"""
from _donor_engine import seed_act

P_COUNT="cold lonely palette, one bulb over a table against deep empty shadow, the freezing hum of memory"
P_DNA="grey anxious palette, cold screen-light in a lonely flat, a mounting dread with nowhere to hide"

COUNT=[
 ("A8_SH01",None,"nika_flat","a wide establishing view of an empty modest flat at night, one lamp on, silence pressing in","WS","eye","push_in","night",True,False,
  "тебе тридцать пять, ты давно совсем одна, и по вечерам квартира звенит от пустоты."),
 ("A8_SH02","NIKA_MID","nika_flat","a medium shot of the woman lifting a glass jar down from a high shelf","MS","eye","static","night",False,False,
  "однажды ночью ты достаёшь с антресоли ту самую банку, которую когда-то прятала от Антона."),
 ("A8_SH03",None,None,"an extreme close-up macro insert of a glass jar full of curled paper number tabs set on a table under a lamp, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "ты ставишь её на стол под лампу, и в ней тихо шуршат десятки скрученных бумажных номерков."),
 ("A8_SH04","NIKA_MID","nika_flat","a close-up of the woman steeling herself to count them at last","CU","eye","static","night",False,False,
  "впервые за все годы ты решаешься высыпать их и сосчитать, сколько же на самом деле было."),
 ("A8_SH05","NIKA_MID","nika_flat","a medium shot of the woman laying paper tabs one by one in a long row on the table","MS","high","static","night",False,False,
  "номерки рассыпаются по столу горкой, и ты раскладываешь их по одному в длинный ровный ряд."),
 ("A8_SH06",None,None,"an extreme close-up macro insert of rows of curled paper number tabs spread across a table, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,True,
  "ты считаешь их вслух, и на числе сорок три твой голос впервые за весь вечер срывается."),
 ("A8_SH07","NIKA_MID","nika_flat","a close-up of the woman's stricken face as the number lands","CU","eye","static","night",False,False,
  "сорок три раза, сорок три ребёнка, которых ты когда-то отдала за конверты с чужими деньгами."),
 ("A8_SH08","NIKA_MID","nika_flat","a medium close-up of the woman trying and failing to picture the faces","MCU","eye","static","night",False,False,
  "ты сидишь и пытаешься представить сорок три живых лица и не можешь вообразить ни одного."),
 ("A8_SH09",None,"cryo_lab","a wide push-in view of a cold cryogenic laboratory with steel tanks and frosted numbered vials in blue light","WS","eye","push_in","night",True,True,
  "ты вспоминаешь холодную лабораторию, где твои клетки лежали в пронумерованных запотевших пробирках."),
 ("A8_SH10",None,"cryo_lab","an extreme close-up macro insert of a wall of frosted glass vials each marked with a small number, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,False,
  "стеллаж с ампулами гудел ровным ледяным гулом, и каждая ампула была подписана своим номером."),
 ("A8_SH11","NIKA_MID","nika_flat","a close-up of the woman with her eyes shut, the cold hum still inside her","CU","eye","static","night",False,False,
  "этот гул ты слышишь до сих пор, стоит закрыть глаза, будто он навсегда поселился внутри."),
 ("A8_SH12",None,"cryo_lab","a wide view of a cold blue cryo laboratory, empty and inhuman, vapour drifting low","WS","eye","static","night",True,False,
  "где-то из этих пробирок выросли живые дети, а сами пробирки были холоднее всего на свете."),
 ("A8_SH13","NIKA_MID","nika_flat","a medium shot of the woman back at the table of paper tabs, a terrible clarity dawning","MS","eye","static","night",False,False,
  "ты возвращаешься к столу, где лежат сорок три бумажки, и понимаешь одну простую страшную вещь."),
 ("A8_SH14","NIKA_MID","nika_flat","a medium close-up of the woman's face as the truth settles","MCU","eye","static","night",False,False,
  "у тебя нет ни одного своего ребёнка, а по стране их сорок три, и все с твоим лицом."),
 ("A8_SH15",None,None,"an extreme close-up macro insert of curled paper number tabs arranged like a strange family album, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "эти бумажки — единственный семейный альбом, который ты собрала за всю свою жизнь."),
 ("A8_SH16","NIKA_MID","nika_flat","a close-up of the woman weeping quietly at the table","CU","eye","static","night",False,False,
  "ты плачешь не о деньгах и не об Антоне, а о том, чего уже никогда нельзя вернуть."),
 ("A8_SH17","NIKA_MID","nika_flat","a medium shot of the woman gently sweeping the tabs back into the jar","MS","eye","static","night",False,False,
  "ты сгребаешь номерки обратно в банку бережно, будто это и правда чьи-то настоящие имена."),
 ("A8_SH18",None,None,"an extreme close-up macro insert of a hand closing the lid on a jar full of paper tabs, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,True,
  "банка снова полна, ты закрываешь крышку, и сорок три номера остаются в темноте на полке."),
 ("A8_SH19","NIKA_MID","nika_flat","a medium close-up of the woman placing the jar in plain sight like a monument","MCU","eye","static","night",False,False,
  "но теперь ты не прячешь её на антресоль, а ставишь на видное место, будто памятник."),
 ("A8_SH20",None,"city_street","a wide view of a vast city at night, countless lit windows, out the flat window","WS","eye","static","night",True,False,
  "за окном тот же огромный город, где-то в нём эти дети растут и зовут мамами других."),
 ("A8_SH21","NIKA_MID","nika_flat","a close-up of the woman with a new fear dawning behind her eyes","CU","eye","static","night",False,False,
  "и впервые ты думаешь о том, что кто-то из них однажды может захотеть тебя найти."),
 ("A8_SH22","NIKA_MID","nika_flat","a medium close-up of the woman of thirty-five beside her jar, a whole country of unknown children behind her","MCU","eye","static","night",False,True,
  "тебе тридцать пять, у тебя есть банка с номерками и целая страна детей, которых ты не знаешь."),
]

DNA=[
 ("A9_SH01",None,"city_street","a wide establishing view of a grey city street on an ordinary older day, years later","WS","eye","push_in","day",True,False,
  "проходят годы, тебе уже за сорок, и твоя жизнь — это работа, тишина и банка на полке."),
 ("A9_SH02","NIKA_OLD","nika_flat","a medium shot of the older woman living a quiet ordinary life at home","MS","eye","static","day",False,False,
  "ты работаешь на обычной работе, стареешь одна и почти научилась не думать о прошлом."),
 ("A9_SH03",None,"nika_flat","an extreme close-up macro insert of a news screen showing a spit-in-a-tube DNA ancestry kit, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "но однажды из каждого экрана начинают говорить про тесты, где по слюне узнают всю родню."),
 ("A9_SH04","NIKA_OLD","nika_flat","a close-up of the older woman freezing with a mug in her hand","CU","eye","static","day",False,False,
  "ты слышишь слово донор в новостях и застываешь с чашкой в руке посреди своей кухни."),
 ("A9_SH05",None,"nika_flat","a wide view of a dim flat lit by the cold glow of a documentary on a screen","WS","eye","static","night",True,False,
  "по телевизору поздно ночью показывают документальный фильм о детях, зачатых от анонимных доноров."),
 ("A9_SH06","NIKA_OLD","nika_flat","a medium shot of the older woman watching the screen, barely breathing","MS","eye","static","night",False,False,
  "ты смотришь его до самого конца, не дыша, потому что речь идёт как будто прямо о тебе."),
 ("A9_SH07","NIKA_OLD","nika_flat","a medium close-up of the woman's stricken face lit by the screen","MCU","eye","static","night",False,False,
  "выросшие дети находят друг друга по тесту и собираются в группы по десять, двадцать человек."),
 ("A9_SH08",None,None,"an extreme close-up macro insert of a screen showing a sibling-group chat with dozens of small avatars, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,True,
  "на экране показывают чат, где полсотни братьев и сестёр ищут одного общего донора."),
 ("A9_SH09","NIKA_OLD","nika_flat","a close-up of the older woman as the promised anonymity crumbles in her face","CU","eye","static","night",False,False,
  "тебе обещали, что это навсегда анонимно, но капля слюны отменила все те обещания разом."),
 ("A9_SH10",None,"city_street","a wide view of a busy city that now feels traceable and exposed under flat light","WS","eye","static","day",True,False,
  "мир, где ты пряталась за номером, исчез, и теперь этот номер ведёт прямо к твоему лицу."),
 ("A9_SH11","NIKA_OLD","nika_flat","a medium shot of the older woman reading forums late at night by phone-light","MS","eye","static","night",False,False,
  "ночами ты читаешь форумы этих детей и узнаёшь, как легко они выходят на своих доноров."),
 ("A9_SH12","NIKA_OLD","nika_flat","a medium close-up of the woman realizing the scale of what is coming","MCU","eye","static","night",False,False,
  "ты понимаешь, что твоих детей по стране десятки и любой из них может искать именно тебя."),
 ("A9_SH13",None,None,"an extreme close-up macro insert of an old clinic business card, faded and disconnected, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "клиники давно закрылись или сменили вывески, и защищать твою тайну больше совсем некому."),
 ("A9_SH14","NIKA_OLD","nika_flat","a close-up of the older woman flinching at a sound, fear now constant","CU","eye","static","day",False,False,
  "теперь ты вздрагиваешь от каждого звонка в дверь и от каждого письма от незнакомых людей."),
 ("A9_SH15",None,"front_door","a wide view of an apartment front door from inside the hallway, dread hanging over it","WS","eye","static","day",True,False,
  "дверь квартиры превращается для тебя в самое страшное место, откуда придёт однажды расплата."),
 ("A9_SH16","NIKA_OLD","nika_flat","a medium shot of the older woman holding an unopened DNA test kit, considering it","MS","eye","static","day",False,False,
  "ты сама держишь в руках такой же тест и думаешь узнать, сколько же их на самом деле."),
 ("A9_SH17","NIKA_OLD","nika_flat","a close-up of the woman's hands setting the kit down, unable to go through with it","CU","eye","static","day",False,False,
  "но ты не решаешься плюнуть в пробирку, потому что боишься увидеть настоящую цифру."),
 ("A9_SH18",None,None,"an extreme close-up macro insert of an unopened DNA test kit lying in a drawer beside a small brooch, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "нераспечатанный тест ложится в тот же ящик, где когда-то пряталась брошка твоей матери."),
 ("A9_SH19","NIKA_OLD","nika_flat","a medium close-up of the older woman resigned to simply waiting","MCU","eye","static","day",False,False,
  "и ты начинаешь просто ждать, зная, что рано или поздно кто-то из них тебя всё-таки найдёт."),
 ("A9_SH20",None,"city_street","a wide panning view of a city crowd of young people passing under flat daylight","WS","eye","pan_right","day",True,False,
  "по улицам ходят молодые люди с твоими глазами, и ты вглядываешься теперь в каждое лицо."),
 ("A9_SH21","NIKA_OLD","city_street","a medium shot of the older woman scanning faces in a street crowd, afraid","MS","eye","static","day",False,False,
  "ты ищешь в толпе свои черты и боишься их найти сильнее, чем чего-либо ещё в жизни."),
 ("A9_SH22","NIKA_OLD","nika_flat","a close-up of the older woman worn down by years of waiting for a knock","CU","eye","static","night",False,False,
  "к сорока шести ты уже не живёшь, а ждёшь стука, как долгие годы ждут приговора."),
 ("A9_SH23",None,"front_door","an extreme close-up macro insert of a shadow of feet under an apartment door on a landing, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,True,
  "и однажды поздним вечером на твоей лестничной площадке действительно раздаются чьи-то медленные шаги."),
 ("A9_SH24","NIKA_OLD","front_door","a medium close-up of the older woman of forty-eight at the door as a knock comes","MCU","eye","static","night",False,True,
  "тебе сорок восемь, в дверь стучат, и ты понимаешь, что то самое, чего ты ждала, пришло."),
]

if __name__=="__main__":
    seed_act("count",   P_COUNT, COUNT, render_mode="static")
    seed_act("dna_era", P_DNA, DNA, render_mode="static")
