# -*- coding: utf-8 -*-
"""trucker: offer (12) + first_box (12) + escalation (11). Run: PYTHONIOENCODING=utf-8 python scripts/_seed_trucker_A3A5.py"""
from _trucker_engine import seed_act

M="MAX_YOUNG"; S="STEP_BASE"; A="ARK_BASE"; MO="MOM_BASE"

# ── A3 OFFER — «одна коробка — сорок тысяч» ────────────────────────────────────
PAL_3="flat warehouse fluorescent palette with cold green shadows"
OFFER=[
 ("A3_SH01",None,"warehouse_ramp",
  "a loading ramp at the start of a shift, a forklift setting a shrink-wrapped pallet by the open trailer doors, chalk tally marks by the roller door, cold fluorescent light",
  "WS","eye","static","morning",False,False,
  "одиннадцатый рейс начинается как любой другой, с погрузки у рампы и проверки пломб."),
 ("A3_SH02",(A,M),"warehouse_ramp",
  "Arkady in his glossy puffer coat on the left stepping close to Maksim by a pallet stack, one hand on the young man's shoulder steering him out of the light, phone dark in his other hand for once",
  "MS","eye","static","morning",False,False,
  "аркадий ловит тебя одного у рампы, пока степаныч подписывает бумаги в глубине склада."),
 ("A3_SH03",(A,M),"warehouse_ramp",
  "Arkady on the left speaking quietly almost into Maksim's ear, the gold signet ring catching the light as he holds up one finger, Maksim on the right gone very still",
  "CU","eye","push_in","morning",False,True,
  "он говорит тихо и просто, одна коробка за запаской, сорок тысяч, старому знать незачем."),
 ("A3_SH04",(A,M),"warehouse_ramp",
  "Maksim on the right stepping back with a short shake of his head, Arkady on the left already turning away unhurt, sliding the phone back into his palm like a card",
  "MS","eye","static","morning",False,False,
  "ты отвечаешь нет и отходишь, но цифра сорок уже осталась стоять у тебя в голове."),
 ("A3_SH05",(S,M),"truck_cab",
  "the whole cab seen wide through the windshield, Stepanych on the left driving in easy silence, Maksim on the right staring out of the side window at the fields, the road reflected across the glass between them",
  "WS","eye","static","day",False,False,
  "весь обратный рейс ты отмалчиваешься, и степаныч не лезет с расспросами, он умеет ждать."),
 ("A3_SH06",MO,"mom_kitchen",
  "the tired mother in her pale headscarf splitting a pill blister in half with a kitchen knife over the oilcloth, the tin box open beside her, evening light through thin curtains",
  "MS","high","push_in","evening",False,True,
  "дома мать делит блистер таблеток ножом пополам, чтобы упаковки хватило на две недели."),
 ("A3_SH07",None,"mom_kitchen",
  "an extreme close-up of the payment slip under the fridge magnet, a column of crossed-out sums pencilled beside the typed total",
  "ECU","eye","static","evening",False,False,
  "ты гасишь по одиннадцать с рейса, но к одиннадцатому рейсу долг похудел лишь до ста тридцати."),
 ("A3_SH08",M,"mom_kitchen",
  "Maksim lying awake on a fold-out bed by the kitchen wall, eyes open at the ceiling, the streetlight drawing the window frame across him",
  "MCU","high","static","night",False,False,
  "ночью ты не спишь и повторяешь себе, что один раз это ещё не дорога."),
 ("A3_SH09",None,"base_yard",
  "the freight base at first light, sodium lamps still on over the gravel, rows of trailers in mist, one lit window in the container office",
  "EWS","eye","static","dawn",True,False,
  "утром ты приходишь на базу за час до смены, хотя сам себе в этом не признаёшься."),
 ("A3_SH10",(M,A),"logist_office",
  "Maksim on the left standing in the office doorway saying two words, Arkady on the right nodding once behind the desk without surprise, the space heater glowing between them",
  "MS","eye","static","morning",False,True,
  "в каморке логиста ты говоришь, один раз, и аркадий кивает так, будто слышал это уже не раз."),
 ("A3_SH11",A,"logist_office",
  "an extreme close-up of Arkady's hand with the gold signet ring opening a small wall safe with a key and pencilling a line into a thin worn notebook",
  "ECU","eye","static","morning",False,False,
  "он открывает ключом маленький сейф и вписывает тебя в тетрадь, которой нет ни в одной бухгалтерии."),
 ("A3_SH12",None,"night_highway",
  "a truck's tail lights shrinking down a dark highway between black fields, the last red points swallowed by distance",
  "WS","eye","static","night",True,False,
  "так на одиннадцатом рейсе в твоей жизни появляется груз, которого нет в накладной."),
]

# ── A4 FIRST_BOX — первая коробка, конверт, «премия» ───────────────────────────
PAL_4="tense dusk palette, violet sky over red tail-lights"
FIRSTBOX=[
 ("A4_SH01","OBJ:box",None,
  "two hands sliding a plain cardboard box into the dark niche behind a spare wheel under a truck bed at dawn",
  "INSERT","low","static","dawn",False,True,
  "первая коробка встаёт за запаску в шесть десять утра, пока на рампе подписывают накладную."),
 ("A4_SH02",(S,M),"warehouse_ramp",
  "Stepanych on the left at the ramp signing the waybill against a pallet, unhurried and trusting, while far behind him on the right Maksim straightens up too quickly from the side of the truck",
  "WS","eye","static","dawn",False,False,
  "степаныч ставит подпись под каждой строчкой, он верит бумаге, потому что привык верить тебе."),
 ("A4_SH03",(M,S),"truck_cab",
  "Maksim on the right checking the side mirror for the third time in a minute, Stepanych on the left noticing the glance and saying nothing, morning light hard on the windshield",
  "MCU","eye","static","day",False,False,
  "в этом рейсе ты смотришь в зеркала чаще, чем на дорогу, и степаныч это видит."),
 ("A4_SH04",(S,M),"truck_cab",
  "over Maksim's shoulder, Stepanych telling an old road story with one hand lifting off the wheel to draw it, his moustache moving, the young man's reflection unfocused in the windshield",
  "OTS","over","static","day",False,False,
  "он рассказывает про свои тридцать четыре года за рулём, а ты сегодня слышишь через слово."),
 ("A4_SH05",None,"weigh_station",
  "the weigh station in daylight with the barrier arm raised, a green light over the lane, the axle scales strip empty and wet after rain",
  "WS","eye","static","day",False,False,
  "весовой пост на четыреста двенадцатом проходит зелёным, и ты выдыхаешь только через десять километров."),
 ("A4_SH06",(M,S),"truck_cab",
  "Maksim on the right and Stepanych on the left riding through dusk in two different silences, the dashboard lights coming on between them, violet sky ahead",
  "MS","eye","push_in","dusk",False,True,
  "до самой базы вы молчите о разном, он о машине, ты о коробке за запаской."),
 ("A4_SH07",(A,M),"base_yard",
  "Arkady on the left passing a thick envelope into Maksim's hand in the shadow between two trailers, looking off at the yard lights, Maksim on the right taking it without a word",
  "MCU","eye","static","night",False,False,
  "на базе аркадий, не глядя, суёт тебе конверт, будто вы всего лишь поздоровались за руку."),
 ("A4_SH08",None,"base_yard",
  "an extreme close-up of a sealed paper envelope held in a fingerless leather glove under a sodium lamp, the paper dented by a tight grip",
  "ECU","eye","static","night",False,False,
  "в конверте ровно сорок, больше, чем ты приносил матери за два месяца честной работы."),
 ("A4_SH09",(M,MO),"mom_kitchen",
  "Maksim on the left laying money on the oilcloth table and looking at the window instead of his mother, the mother on the right frozen with a dish towel in her hands",
  "MS","eye","static","evening",False,False,
  "дома ты кладёшь деньги на клеёнку и говоришь слово премия, не глядя матери в глаза."),
 ("A4_SH10",MO,"mom_kitchen",
  "the mother's tired face opening into a real smile for the first time in a long while, her hand resting flat on the money as if it could cool down",
  "CU","eye","push_in","evening",False,True,
  "мать впервые за год улыбается по-настоящему, и от этой улыбки тебе становится только хуже."),
 ("A4_SH11",M,"mom_kitchen",
  "Maksim sitting alone at the kitchen table late at night, crossing out one sum and writing a smaller one on the payment slip by the light over the stove",
  "MS","eye","static","night",False,False,
  "ты вычитаешь из долга сорок, остаётся девяносто, и цифра тает быстрее, чем привыкает совесть."),
 ("A4_SH12",(A,M),"base_yard",
  "Arkady on the left raising an eyebrow with half a smile by the office door, Maksim on the right nodding before the question is even finished, morning bustle of the yard behind them",
  "WS","eye","static","morning",False,False,
  "через неделю аркадий спрашивает, повторим ли, и ты соглашаешься быстрее, чем в первый раз."),
]

# ── A5 ESCALATION — три коробки, сломанный ритуал, 60 кг ───────────────────────
PAL_5="hard noon light palette, bleached asphalt and sharp shadows"
ESCAL=[
 ("A5_SH01","OBJ:box",None,
  "three identical plain cardboard boxes stacked tight in the niche behind the spare wheel, grey tape edges catching a work lamp",
  "INSERT","low","push_in","dawn",False,True,
  "коробок за запаской уже три, и сто двадцать тысяч за рейс заглушают любые твои клятвы."),
 ("A5_SH02",(M,S),"truck_cab",
  "the whole cab seen wide through the windshield in hard noon light, Maksim on the right with his jaw set staring ahead, Stepanych on the left driving, the shadow of the cab frame cutting the seat between them",
  "WS","eye","static","day",False,False,
  "каждый рейс ты обещаешь себе, что этот последний, и каждую погрузку соглашаешься снова."),
 ("A5_SH03",(M,S),"truck_cab",
  "over Stepanych's shoulder, Maksim on the right folding a thin stack of paid receipts into his notebook, allowing himself one small tight smile",
  "OTS","over","static","day",False,False,
  "долг тает втрое быстрее честного, и ты уже почти видишь кухню матери без квитанций."),
 ("A5_SH04",(S,M),"truck_stop",
  "Stepanych on the left holding out the small enamel cup on its shoelace by the tailgate, Maksim on the right waving it off without meeting his eyes, dusk settling over the parked trucks",
  "MS","eye","static","dusk",False,True,
  "на привале степаныч по привычке наливает вторую кружку, а ты вдруг говоришь, не хочу."),
 ("A5_SH05",S,"truck_stop",
  "Stepanych's weathered face under the tweed cap as he slowly pours the tea out onto the gravel and screws the thermos lid back down without a word",
  "CU","eye","push_in","dusk",False,True,
  "он молча выливает чай на гравий и завинчивает крышку так медленно, что у тебя звенит в ушах.",
  "the older man slowly tipping the cup, tea splashing on gravel, then screwing the lid down with deliberate calm"),
 ("A5_SH06","OBJ:thermos",None,
  "the dented aluminium thermos standing closed on a tailgate at dusk, the enamel cup hanging still on its shoelace",
  "INSERT","eye","static","dusk",False,False,
  "щелчок крышки, который три месяца означал привал, впервые звучит как закрытая дверь."),
 ("A5_SH07",(S,M),"truck_cab",
  "Stepanych on the left and Maksim on the right riding through the night without a word, the dashboard glow the only thing moving between their faces",
  "MS","eye","static","night",False,False,
  "до самой базы вы не говорите ни слова, и это молчание тяжелее любого разговора."),
 ("A5_SH08",None,"day_highway",
  "the highway stretching flat and endless under a white afternoon sky, a windbreak of poplars far off, wires dipping pole to pole along the shoulder",
  "EWS","eye","track","day",True,False,
  "девятьсот километров вы проезжаете за те же двенадцать часов, но теперь они тянутся, как сутки."),
 ("A5_SH09",(S,M),"truck_cab",
  "Stepanych on the left speaking straight into the windshield with both hands on the wheel, Maksim on the right going cold in his seat, night road unrolling ahead of them",
  "MCU","eye","push_in","night",False,True,
  "на обратном он говорит в лобовое стекло, она на весах на шестьдесят кило тяжелее накладной."),
 ("A5_SH10",(S,M),"truck_cab",
  "over Maksim's shoulder, Stepanych's face in profile lit by the dashboard, calm and heavy, eyes never leaving the road",
  "OTS","over","static","night",False,False,
  "я её тридцать лет чувствую, добавляет он, и больше в тот вечер не говорит ничего."),
 ("A5_SH11",M,"truck_cab",
  "Maksim's face against the dark side window, streetlights sliding over it, his mouth half-opening on a word that never comes out",
  "CU","eye","static","night",False,False,
  "ты открываешь рот, чтобы соврать про запчасти, и не находишь в себе даже вранья."),
]

if __name__=="__main__":
    seed_act("offer",PAL_3,OFFER)
    seed_act("first_box",PAL_4,FIRSTBOX)
    seed_act("escalation",PAL_5,ESCAL)
