# -*- coding: utf-8 -*-
"""caregiver — акты 4–7: дочь, переезд, колокольчик по ночам, ненаписанная бумага."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _caregiver_engine import seed_act

P4 = "a hard urban palette of white phone glare, bleached hair and flat grey street daylight"
P5 = "a muted enclosed palette of dust-coloured drapes, brown varnished furniture and one warm lamp"
P6 = "a night palette of a single low bedside lamp, deep brown shadow and cold blue at the window"
P7 = "a dry official palette of green desk-lamp light, buff paper and dark varnished wood"

DAUGHTER = [
 ("A4_SH01", None, "marina_flat",
  "a bare rented room with a mattress on a low frame, an open clothes rail and a folding table cleared and wiped for something",
  "WS","eye","static","day",True,False,
  "Марине девятнадцать лет, и её день рождения приходится на третью субботу мая."),
 ("A4_SH02", "MAR_YOUNG", "marina_flat",
  "Marina talking into a phone held on her shoulder while she pushes the folding table into the middle of the room",
  "MCU","eye","static","day",False,False,
  "она зовёт тебя за две недели и говорит, что будет всего четверо."),
 ("A4_SH03", "NAD_START", "val_kitchen",
  "Nadezhda's face lighting up at the kitchen table with the phone still at her ear, already making a plan",
  "CU","eye","static","day",False,False,
  "ты обещаешь ей приехать и на радостях покупаешь ей чайник со свистком."),
 ("A4_SH04", None, "val_hall",
  "a boxed kettle in printed cardboard standing in a hallway corner beside the coat rack with a fine film of dust across its top",
  "INSERT","top","static","day",True,False,
  "коробка стоит в прихожей три недели и постепенно покрывается тонкой серой пылью."),
 ("A4_SH05", ("NAD_START","VAL_START"), "val_room",
  "Nadezhda straightens the coverlet at the foot of the bed while Valentina, propped up against the pillows, mentions something in passing with her eyes on the window",
  "MS","eye","static","dusk",False,False,
  "в пятницу вечером Валентина Степановна вдруг говорит, что ей с утра нехорошо."),
 ("A4_SH06", "VAL_START", "val_room",
  "Valentina's face saying it lightly and then turning to the window, her face perfectly smooth",
  "CU","low","static","dusk",False,False,
  "она не просит остаться, она просто говорит это и смотрит в сторону."),
 ("A4_SH07", "NAD_START", "val_room",
  "Nadezhda standing in the doorway with the phone at her ear and one hand pressed flat against the frame",
  "MCU","eye","static","dusk",False,False,
  "ты звонишь в агентство, и подменная сиделка стоит восемьсот за одни сутки."),
 ("A4_SH08", None, "val_kitchen",
  "an opened kitchen drawer with a folded envelope of banded notes lying under a tea towel and a pencil-written note on top of it",
  "INSERT","top","static","day",True,False,
  "восемьсот — это ровно те деньги, которые ты откладывала дочери на лето."),
 ("A4_SH09", "NAD_START", "val_kitchen",
  "Nadezhda closing the drawer with her hip and putting the phone face-down on the oilcloth",
  "CU","eye","static","day",False,True,
  "ты остаёшься, и всё это решение занимает у тебя меньше одной минуты."),
 ("A4_SH10", None, "marina_flat",
  "a folding table laid with four plates and four glasses in a rented room, one chair standing empty and pushed slightly back from the table",
  "WS","eye","static","night",True,True,
  "в субботу у Марины четыре тарелки на столе и один свободный стул."),
 ("A4_SH11", "MAR_YOUNG", "marina_flat",
  "Marina holding the phone slightly away from her ear in a loud room, answering in a level voice",
  "MCU","eye","static","night",False,False,
  "ты звонишь ей в девять вечера, и она говорит, что всё нормально."),
 ("A4_SH12", "MAR_YOUNG", "marina_flat",
  "Marina's face going carefully blank as she keeps her voice even to the end of the call",
  "CU","eye","push_in","night",False,False,
  "голос у неё ровный, и именно по этому голосу ты всё и понимаешь."),
 ("A4_SH13", "NAD_START", "val_room",
  "Nadezhda sitting on the edge of a folding bed in the half-dark, typing a long message with two thumbs",
  "MS","low","static","night",False,False,
  "ты переводишь ей деньги в половине десятого и пишешь ей длинное сообщение."),
 ("A4_SH14", None, "val_room",
  "a phone lying face-up on a bedside chair showing a sent message with a single grey tick beside it and empty space below",
  "INSERT","top","static","night",True,False,
  "твоё сообщение остаётся непрочитанным одиннадцать дней подряд, а деньги она принимает сразу."),
 ("A4_SH15", None, "courtyard",
  "an apartment courtyard in early summer with the poplars in full leaf, both benches empty and washing hanging on a balcony above",
  "WS","eye","static","day",True,False,
  "следующие три недели она не берёт трубку и отвечает только словом занята."),
 ("A4_SH16", "NAD_START", "bus_stop",
  "Nadezhda standing at a bus shelter with a shopping bag between her feet, checking the timetable behind cracked glass",
  "MS","eye","track","day",False,False,
  "в июне ты выкраиваешь один день и едешь к ней через весь город."),
 ("A4_SH17", None, "marina_flat",
  "a shared flat corridor with three closed doors and a communal kitchen visible at the end, shoes of three different sizes by the wall",
  "WS","low","static","day",True,False,
  "она снимает комнату в квартире, где на общей кухне живут ещё двое."),
 ("A4_SH18", ("MAR_YOUNG","NAD_START"), "marina_flat",
  "Marina sits cross-legged on the mattress with her back to the wall while Nadezhda lowers herself onto the edge of it beside her, keeping her coat on",
  "MS","eye","static","day",False,False,
  "вы сидите вдвоём на матрасе, потому что стула в комнате всего один."),
 ("A4_SH19", "MAR_YOUNG", "marina_flat",
  "Marina's face asking a flat question with the headphones still around her neck, watching for the answer",
  "CU","eye","static","day",False,False,
  "она спрашивает, как здоровье у бабушки, и это звучит совсем не смешно."),
 ("A4_SH20", "NAD_START", "marina_flat",
  "Nadezhda explaining with both hands turned up, going on longer than the explanation needs",
  "MCU","eye","static","day",False,False,
  "ты объясняешь ей, что это просто работа, и объясняешь ей слишком долго."),
 ("A4_SH21", "MAR_YOUNG", "marina_flat",
  "Marina's face saying one flat sentence and standing up out of frame on the last word",
  "CU","low","static","day",False,True,
  "ты живёшь у неё, а не у нас, говорит Марина и встаёт."),
 ("A4_SH22", "NAD_START", "marina_flat",
  "Nadezhda left sitting on the mattress alone, her mouth open and empty of an answer",
  "CU","eye","static","day",False,False,
  "ты не находишь ответа, потому что ответа на это и правда нет."),
 ("A4_SH23", None, "bus_stop",
  "a bus shelter at dusk with wet asphalt at the kerb, an empty metal bench and apartment blocks lit up behind the grass strip",
  "WS","eye","static","dusk",True,False,
  "обратно ты едешь на двух автобусах и приезжаешь ровно к семи вечера."),
 ("A4_SH24", "NAD_START", "val_hall",
  "Nadezhda turning her key in a familiar lock and stopping in the doorway with her coat half off",
  "MCU","eye","static","dusk",False,False,
  "ты открываешь дверь своим ключом, и колокольчик звонит уже через две секунды."),
 ("A4_SH25", "OBJ:bell", None,
  "a bedside cabinet in the last of the evening light",
  "INSERT","eye","push_in","interior",True,False,
  "он звонит один раз, коротко, и это значит, что она тебя ждала."),
 ("A4_SH26", ("VAL_START","NAD_START"), "val_room",
  "Valentina asks from the bed with her book closed on her lap while Nadezhda answers from the doorway, still holding her coat",
  "MS","eye","static","dusk",False,False,
  "Валентина Степановна спрашивает, как всё прошло, и ты говоришь ей, что хорошо."),
 ("A4_SH27", "NAD_START", "val_room",
  "Nadezhda's face reading aloud by the lamp, keeping her eyes on the page and going on past the usual stopping point",
  "CU","low","static","dusk",False,False,
  "в тот вечер ты читаешь ей вслух на четыре страницы больше обычного."),
 ("A4_SH28", None, "val_hall",
  "a hallway corner from a distance with a boxed kettle still standing unopened beside the coat rack under the outdoor clothes",
  "EWS","high","pull_out","night",True,True,
  "а чайник со свистком так и остаётся стоять у тебя в прихожей."),
]

DEEPER = [
 ("A5_SH01", None, "courtyard",
  "an apartment courtyard from very high in autumn with leaves down along the kerbs and one path worn across the grass to the porch",
  "EWS","high","pan_left","day",True,False,
  "на четвёртый год ты бываешь у себя дома два раза в неделю."),
 ("A5_SH02", "NAD_MID", "nad_room",
  "Nadezhda unhooking a curtain from its rail with both arms raised, four packed bags already standing by the door",
  "MS","eye","static","day",False,False,
  "ты собираешь свою комнату в четыре сумки и сама снимаешь с окна занавески."),
 ("A5_SH03", None, "nad_room",
  "a papered wall with one clean unfaded rectangle where a mirror hung and a bent nail left in the middle of it",
  "INSERT","top","static","day",True,False,
  "на стене остаётся светлый прямоугольник, и ты его ничем уже не закрываешь."),
 ("A5_SH04", "NAD_MID", "nad_room",
  "Nadezhda's face taking a last look round an emptied room from the doorway, one bag strap over her shoulder",
  "CU","low","static","day",False,False,
  "от своей комнаты ты в тот же месяц отказываешься, и эти деньги уходят дочери."),
 ("A5_SH05", None, "val_room",
  "a bedroom corner behind a dark sideboard with four packed bags stacked into it and a folding camp bed leaning against the wall",
  "WS","eye","static","day",True,False,
  "все твои вещи помещаются в один угол её комнаты, прямо за сервант."),
 ("A5_SH06", "NAD_MID", "val_room",
  "Nadezhda unfolding a camp bed on the floor two metres from a high iron bed and testing it with her hand",
  "MS","eye","static","night",False,False,
  "спишь ты теперь на раскладушке, в двух метрах от её высокой кровати."),
 ("A5_SH07", "VAL_START", "val_room",
  "Valentina watching from the bed in lamplight and saying a word she is using for the first time",
  "MCU","eye","static","night",False,False,
  "ей восемьдесят три, и она в первый раз называет тебя своей дочкой."),
 ("A5_SH08", "NAD_MID", "val_room",
  "Nadezhda's face receiving it, deciding in half a second to let it stand",
  "CU","eye","push_in","night",False,True,
  "ты не поправляешь её, и с этого вечера она говорит так всегда."),
 ("A5_SH09", None, "val_kitchen",
  "a kitchen from above with two plates, two cups and two toothbrushes standing in one glass on the windowsill",
  "WS","high","static","day",True,False,
  "на кухне теперь две тарелки, две чашки и две зубные щётки в стакане."),
 ("A5_SH10", "OBJ:watchpin", None,
  "the breast pocket of a worn home housecoat in flat daylight",
  "INSERT","eye","static","interior",True,False,
  "часы-брошь ты перекалываешь на домашний халат и носишь их теперь и дома."),
 ("A5_SH11", "NAD_MID", "val_hall",
  "Nadezhda standing at the hallway shelf with the handset to her ear, answering in short single words",
  "MS","eye","static","day",False,False,
  "раз в квартал звонит Олег и спрашивает три вещи по одному списку."),
 ("A5_SH12", "NAD_MID", "val_hall",
  "Nadezhda's face on the phone going through an answer she has given many times",
  "CU","eye","static","day",False,False,
  "давление, аппетит и деньги — на этом каждый его разговор всегда заканчивается."),
 ("A5_SH13", None, "stairwell",
  "a landing letterbox slot with a folded transfer slip half pushed through it and a worn handrail running past",
  "WS","eye","static","day",True,False,
  "деньги он переводит первого числа и никогда не задерживает их ни дня."),
 ("A5_SH14", "ZINA_BASE", "stairwell",
  "Zina standing in her doorway in her flowered apron, asking something with her arms folded across her chest",
  "MCU","eye","static","day",False,False,
  "Зина на площадке прямо спрашивает тебя, оформила ли ты хоть какую-нибудь бумагу."),
 ("A5_SH15", "NAD_MID", "stairwell",
  "Nadezhda's face giving a short embarrassed answer and looking at the floor after it",
  "CU","eye","static","day",False,False,
  "ты говоришь, что тебе неудобно, и Зина смотрит на тебя очень долго."),
 ("A5_SH16", ("ZINA_BASE","NAD_MID"), "stairwell",
  "Zina says one more thing over her shoulder and pulls her door to while Nadezhda stays on the landing with the shopping bag still in her hand",
  "MS","eye","static","day",False,False,
  "она говорит, что неудобно тебе будет как раз потом, и уходит к себе."),
 ("A5_SH17", None, "pharmacy",
  "a neighbourhood pharmacy counter with a lit price board above it, ranks of labelled drawers behind and a chair by the door",
  "WS","eye","static","day",True,False,
  "в аптеке тебя давно знают по имени и откладывают её лекарства заранее."),
 ("A5_SH18", "NAD_MID", "pharmacy",
  "Nadezhda loading a dozen boxes from the counter into a cloth bag, checking each name against a list",
  "MS","eye","static","day",False,False,
  "ты берёшь сразу на целый месяц, потому что ходить дважды уже некогда."),
 ("A5_SH19", "OBJ:pillbox", None,
  "a kitchen table with foil strips and a written list spread beside it",
  "INSERT","top","static","interior",True,False,
  "в контейнере теперь не двенадцать таблеток в день, а целых пятнадцать штук."),
 ("A5_SH20", "LUDA_BASE", "pharmacy",
  "Luda turning round in the pharmacy queue with the burgundy shopper on her shoulder, recognising somebody",
  "MCU","eye","static","day",False,False,
  "в аптеке ты сталкиваешься с Людой, вы вместе учились двадцать лет назад."),
 ("A5_SH21", ("LUDA_BASE","NAD_MID"), "pharmacy",
  "Luda talks fast and cheerfully with the shopper bag swinging while Nadezhda listens holding her own bag with both hands",
  "MS","eye","static","day",False,False,
  "Люда работает по сменам, двое суток через двое, и хорошо при этом высыпается."),
 ("A5_SH22", "LUDA_BASE", "pharmacy",
  "Luda's face going serious for one sentence, her eyebrows up",
  "CU","eye","static","day",False,False,
  "она говорит, что таких, как ты, агентство держит до самого последнего дня."),
 ("A5_SH23", "NAD_MID", "pharmacy",
  "Nadezhda's face answering and hearing how it sounds while she is still saying it",
  "CU","low","static","day",False,True,
  "ты отвечаешь, что тут не работа, и сама слышишь, как это звучит."),
 ("A5_SH24", None, "val_room",
  "a lamplit bedroom at dusk seen from the hall doorway with the bed turned down and a book waiting closed on the coverlet",
  "WS","eye","static","dusk",True,False,
  "вечером ты возвращаешься, и в этой квартире тебя ждут, а дома никто."),
 ("A5_SH25", ("VAL_START","NAD_MID"), "val_room",
  "Valentina holds an unopened book flat on her lap and waits while Nadezhda comes in and takes the chair beside the bed",
  "MS","eye","static","dusk",False,False,
  "она держит книгу на коленях и не открывает её до твоего прихода."),
 ("A5_SH26", "VAL_START", "val_room",
  "Valentina's hand slipping off the page as she tries to hold it flat, her face patient about it",
  "CU","eye","static","dusk",False,False,
  "читать сама она уже не может, потому что не удерживает даже страницу."),
 ("A5_SH27", "NAD_MID", "val_room",
  "Nadezhda reading aloud by lamplight with her eyes lifting off the page every few lines",
  "MCU","low","static","dusk",False,False,
  "ты читаешь ей вслух каждый вечер и уже знаешь эту книгу наизусть."),
 ("A5_SH28", None, "val_room",
  "a low camp bed made up on the floor beside a high iron bed with a book left open face-down between them",
  "INSERT","top","static","night",True,False,
  "раскладушка стоит так, чтобы ты слышала её дыхание, даже совсем не просыпаясь."),
 ("A5_SH29", "NAD_MID", "val_room",
  "Nadezhda lying awake on the camp bed in the dark with her eyes open towards the bed above her",
  "MS","eye","static","night",False,False,
  "за весь четвёртый год ты ночуешь у себя дома всего двенадцать раз."),
 ("A5_SH30", None, "winter_yard",
  "a snowbound courtyard from very high at night with one window lit on the fourth floor and lamplight turning in the falling snow",
  "EWS","high","pull_out","night",True,False,
  "а колокольчик к этому времени звонит уже по шесть раз за ночь."),
]

BELL = [
 ("A6_SH01", None, "val_room",
  "a bedroom at night lit only by a low bedside lamp, a camp bed made up on the floor and the door left open onto a dark hall",
  "WS","eye","static","night",True,False,
  "на шестой год ночь перестаёт быть тем временем, когда ты вообще спишь."),
 ("A6_SH02", "OBJ:bell", None,
  "a bedside cabinet under a low night lamp",
  "INSERT","low","static","interior",True,True,
  "колокольчик звонит в час, в два, в три и в половине пятого."),
 ("A6_SH03", "NAD_MID", "val_room",
  "Nadezhda sitting up off the camp bed in one movement in the dark and reaching for the lamp switch",
  "MS","eye","static","night",False,False,
  "ты встаёшь на каждый звонок и каждый раз включаешь только один ночник."),
 ("A6_SH04", "VAL_END", "val_room",
  "Valentina's face on the pillow calling a name into the dark, her eyes open and drifting past the ceiling",
  "CU","low","static","night",False,False,
  "ей восемьдесят пять, она путает день с ночью и зовёт по имени мужа."),
 ("A6_SH05", "NAD_MID", "val_room",
  "Nadezhda leaning over the bed and answering to somebody else's name in a low steady voice",
  "MCU","eye","static","night",False,True,
  "ты отзываешься на его имя, потому что так она гораздо быстрее засыпает."),
 ("A6_SH06", None, "val_room",
  "a bedroom from above at night with a strip of worn floorboard between a camp bed and a high bed, the varnish walked pale along it",
  "WS","high","static","night",True,False,
  "за одну ночь ты проходишь от раскладушки до её кровати двадцать раз."),
 ("A6_SH07", None, "val_kitchen",
  "a squared exercise book open on a kitchen table at dawn with the last dated column left half filled and the pen lying across it",
  "ECU","top","static","dawn",True,False,
  "в тетради ты перестаёшь записывать ночи, потому что их просто некуда вписывать."),
 ("A6_SH08", "NAD_MID", "val_kitchen",
  "Nadezhda drinking tea standing up at the kitchen counter with her hip against it, eyes half closed",
  "MS","eye","static","dawn",False,False,
  "утром ты пьёшь чай стоя, потому что сидя ты сразу же засыпаешь."),
 ("A6_SH09", "NAD_MID", "val_kitchen",
  "Nadezhda's face at dawn, grey and slack, her eyelids dropping and catching again",
  "CU","eye","static","dawn",False,False,
  "тебе ровно пятьдесят, и ты дважды за месяц роняешь на пол блистер."),
 ("A6_SH10", None, "val_kitchen",
  "loose tablets scattered across kitchen floorboards under a table with a dropped foil strip beside a chair leg",
  "INSERT","top","static","dawn",True,False,
  "таблетки катятся под стол, и ты собираешь их на четвереньках очень долго."),
 ("A6_SH11", "NAD_MID", "val_kitchen",
  "Nadezhda sitting motionless at the kitchen table with the pill organiser open in front of her, working out what she has done",
  "MCU","low","static","dawn",False,True,
  "один раз ты даёшь ей вечернюю таблетку утром и потом сидишь час."),
 ("A6_SH12", None, "clinic_corridor",
  "a clinic corridor with a full row of joined plastic chairs, numbered doors along one side and a tall window at the far end",
  "WS","eye","static","day",True,False,
  "в поликлинике талон дают только через две недели, и вы эти недели ждёте."),
 ("A6_SH13", ("NAD_MID","VAL_END"), "clinic_corridor",
  "Nadezhda stands beside a wheelchair against the corridor wall while Valentina sits in it wrapped in a coat, holding on to Nadezhda's sleeve",
  "MS","eye","static","day",False,False,
  "она сидит в коляске, ты стоишь рядом, и очередь идёт четыре часа."),
 ("A6_SH14", "VAL_END", "clinic_corridor",
  "Valentina's hand and face in the wheelchair, her fingers closed hard on a grey sleeve and holding on",
  "CU","eye","static","day",False,False,
  "она держит тебя за рукав всю очередь и не отпускает ни разу."),
 ("A6_SH15", "LUDA_BASE", "clinic_corridor",
  "Luda coming down the corridor with the burgundy shopper and stopping short when she sees who it is",
  "MCU","eye","static","day",False,False,
  "в коридоре ты снова встречаешь Люду, она приехала сюда со своим подопечным."),
 ("A6_SH16", ("LUDA_BASE","NAD_MID"), "clinic_corridor",
  "Luda looks Nadezhda over from head to foot and says something blunt while Nadezhda stands there taking it with her hands full",
  "MS","eye","static","day",False,False,
  "Люда смотрит на тебя и говорит, что ты стала на себя непохожа."),
 ("A6_SH17", "LUDA_BASE", "clinic_corridor",
  "Luda's face making an offer quietly, counting the days out on two fingers",
  "CU","low","static","day",False,False,
  "она предлагает тебе место в своей смене, с нормальным графиком и двумя выходными."),
 ("A6_SH18", "NAD_MID", "clinic_corridor",
  "Nadezhda's face doing the arithmetic behind her eyes with her mouth shut",
  "CU","eye","static","day",False,False,
  "там платят заметно меньше, но там ты будешь спать двое суток подряд."),
 ("A6_SH19", None, "courtyard",
  "a courtyard bench at dusk with one seat worn smooth and the poplars going dark against a violet sky",
  "WS","eye","static","dusk",True,False,
  "ты думаешь об этом ровно три дня и всё это время считаешь."),
 ("A6_SH20", "NAD_MID", "courtyard",
  "Nadezhda sitting alone on the courtyard bench in her coat, staring at the porch door of her own block",
  "MCU","eye","static","dusk",False,True,
  "если уйти сейчас, то шесть лет ухода не будут стоить вообще ничего."),
 ("A6_SH21", "NAD_MID", "courtyard",
  "Nadezhda's face in the last light, holding a thought behind a closed mouth",
  "CU","low","push_in","dusk",False,True,
  "та квартира на первом этаже стоит пустая, и ключ от неё у Валентины."),
 ("A6_SH22", None, "val_room",
  "a bedroom at night with a phone lying face-down on a chair and the bedside lamp turned to the wall",
  "WS","eye","static","night",True,False,
  "ты отказываешь Люде по телефону и делаешь это очень быстро и твёрдо."),
 ("A6_SH23", "NAD_MID", "val_room",
  "Nadezhda lying on the camp bed fully dressed with her eyes open, counting something on her fingers in the dark",
  "MS","eye","static","night",False,False,
  "в тот же вечер колокольчик звонит двадцать раз, и ты их считаешь."),
 ("A6_SH24", "OBJ:bell", None,
  "a bedside cabinet edge caught in the very last of a dimmed lamp",
  "ECU","low","push_in","interior",True,True,
  "двадцать за ночь — это твой предел, и так продолжается ещё два года."),
 ("A6_SH25", "NAD_MID", "val_room",
  "Nadezhda's face lying down again in her housecoat with the buttons still done up to the throat",
  "CU","eye","static","night",False,False,
  "ты перестаёшь раздеваться на ночь и спишь в халате, чтобы вставать быстрее."),
 ("A6_SH26", "MAR_ADULT", "marina_flat",
  "Marina at a table in a better room with a phone lying beside her elbow, screen dark, her hand resting beside it",
  "MCU","eye","static","night",False,False,
  "Марине двадцать пять, и она не звонит тебе на твой день рождения."),
 ("A6_SH27", "NAD_MID", "val_room",
  "Nadezhda's face in the dark, entirely calm about it, working out what date it is",
  "CU","eye","static","night",False,False,
  "ты не обижаешься, потому что сама уже не помнишь, какое сегодня число."),
 ("A6_SH28", None, "winter_yard",
  "a courtyard deep in snow at night with the benches buried and one narrow path kept clear to the porch",
  "WS","low","static","night",True,False,
  "зима на седьмой год стоит длинная, и ты выходишь во двор дважды."),
 ("A6_SH29", "NAD_MID", "val_room",
  "Nadezhda asleep sitting upright on a hard chair beside the bed with her chin down on her chest",
  "MS","low","static","night",False,True,
  "в феврале ты первый раз засыпаешь сидя на стуле рядом с кроватью."),
 ("A6_SH30", None, "winter_yard",
  "a snowed-in courtyard from very high before dawn with a single lit window and the lamp cone empty below it",
  "EWS","high","pull_out","night",True,False,
  "а колокольчик всё звонит, и ты просыпаешься от него всё равно мгновенно."),
]

PAPERS = [
 ("A7_SH01", None, "stairwell",
  "a landing in flat daylight with two doors facing each other and a shopping bag set down on the concrete between them",
  "WS","eye","static","day",True,False,
  "на восьмой год Зина ловит тебя на площадке и говорит без предисловий."),
 ("A7_SH02", "ZINA_BASE", "stairwell",
  "Zina leaning in close on the landing with her glasses pushed up, telling a story she clearly means as a warning",
  "MCU","eye","static","day",False,False,
  "она говорит, что её знакомая ухаживала одиннадцать лет и осталась ни с чем."),
 ("A7_SH03", "NAD_MID", "stairwell",
  "Nadezhda's face giving the answer she always gives with the certainty gone out of it",
  "CU","eye","static","day",False,False,
  "ты отвечаешь, что у вас другое, и сама этому уже не веришь."),
 ("A7_SH04", None, "val_room",
  "a bedroom at dusk with a chair drawn right up to the bedside and the lamp turned low on the cabinet",
  "WS","eye","static","dusk",True,False,
  "вечером ты садишься к её кровати и говоришь про бумагу первый раз."),
 ("A7_SH05", ("NAD_MID","VAL_END"), "val_room",
  "Nadezhda leans forward from the bedside chair and says something short and prepared while Valentina listens from the pillows with her eyes on the ceiling",
  "MS","eye","static","dusk",False,False,
  "ты говоришь тихо и коротко, потому что готовила эту фразу три недели."),
 ("A7_SH06", "VAL_END", "val_room",
  "Valentina's face agreeing easily and moving straight on, her hand patting the coverlet twice",
  "CU","eye","static","dusk",False,True,
  "она отвечает, что конечно, и что оформим всё сразу после Нового года."),
 ("A7_SH07", "NAD_MID", "val_room",
  "Nadezhda sitting back in the chair with relief loosening her shoulders, nodding more than once",
  "MCU","eye","static","dusk",False,False,
  "до Нового года остаётся семь недель, и ты спокойно соглашаешься столько подождать."),
 ("A7_SH08", None, "val_kitchen",
  "a wall calendar in a kitchen with one date in January ringed twice in soft pencil and the pencil hanging on a string beside it",
  "INSERT","top","static","night",True,True,
  "на кухонном календаре ты обводишь простым карандашом одно число в конце января."),
 ("A7_SH09", None, "winter_yard",
  "a snowed courtyard at night with distant fireworks lighting the sky above the roofs and every window in the block lit",
  "WS","eye","static","night",True,False,
  "Новый год вы встречаете вдвоём, и она засыпает уже в одиннадцать вечера."),
 ("A7_SH10", "NAD_MID", "val_kitchen",
  "Nadezhda sitting alone at the kitchen table before midnight with one cup, listening to the window",
  "MS","eye","static","night",False,False,
  "ты сидишь на кухне до двенадцати и слушаешь во дворе чужие фейерверки."),
 ("A7_SH11", "NAD_MID", "val_kitchen",
  "Nadezhda's face lit faintly from the window by somebody else's fireworks, counting years instead of watching",
  "CU","low","static","night",False,False,
  "тебе пятьдесят два, и ты впервые считаешь, сколько тебе ещё осталось работать."),
 ("A7_SH12", None, "notary_office",
  "a notary's office with a heavy desk under a green-shaded lamp, glass-fronted cabinets of registers and two upright chairs facing the desk",
  "WS","eye","static","day",True,False,
  "в январе ты находишь нотариуса, который выезжает на дом за отдельную плату."),
 ("A7_SH13", "NAD_MID", "notary_office",
  "Nadezhda counting notes out onto the corner of a notary's desk and writing a day and a time in her own notebook",
  "MS","eye","static","day",False,False,
  "ты платишь ему сама и договариваешься на четверг, на два часа дня."),
 ("A7_SH14", None, "val_room",
  "a bedside cabinet with a covered glass of water, a closed document folder set square beside it and the bed made up behind",
  "INSERT","top","static","day",True,False,
  "в четверг она с утра не узнаёт тебя и просит позвать мужа."),
 ("A7_SH15", "VAL_END", "val_room",
  "Valentina's face looking politely at a face she fails to recognise, asking for somebody long gone",
  "CU","low","static","day",False,True,
  "нотариус сидит на кухне двадцать минут, пьёт чай и уезжает обратно ни с чем."),
 ("A7_SH16", "NAD_MID", "val_hall",
  "Nadezhda holding the front door open and listening to an explanation given on the threshold",
  "MCU","eye","static","day",False,False,
  "он говорит, что в таком состоянии её подпись всё равно оспорят родственники."),
 ("A7_SH17", None, "val_room",
  "a bedroom from above the following week with the bed neatly made, the chair squared to it and everything ready and standing unused",
  "WS","high","static","day",True,False,
  "на следующей неделе она в полном сознании, но нотариус занят до марта."),
 ("A7_SH18", "NAD_MID", "val_kitchen",
  "Nadezhda crossing a date off the calendar and writing another one under it in the same pencil",
  "MS","eye","static","day",False,False,
  "в марте она снова плохая, и вы переносите ещё на один раз."),
 ("A7_SH19", "NAD_MID", "val_kitchen",
  "Nadezhda's face at the calendar, patient, entirely certain there is still time",
  "CU","eye","static","day",False,False,
  "так это переносится четыре раза, и каждый раз кажется, что ещё успеется."),
 ("A7_SH20", None, "stairwell",
  "a landing with a good pair of city shoes set neatly by the door among the household slippers",
  "WS","eye","static","day",True,False,
  "в мае к вам приезжает Олег, первый раз за целых одиннадцать месяцев подряд."),
 ("A7_SH21", "OLEG_BASE", "val_room",
  "Oleg coming out of the bedroom with a stiff document folder held flat against his chest, pulling the door to behind him",
  "MCU","eye","static","day",False,False,
  "он сидит у неё сорок минут и выходит из комнаты с папкой."),
 ("A7_SH22", "OBJ:will", None,
  "an opened cardboard document folder on a hallway shelf under a hard light",
  "INSERT","top","static","interior",True,True,
  "в папке лежат её документы, и он забирает их к себе на хранение."),
 ("A7_SH23", ("NAD_MID","OLEG_BASE"), "val_hall",
  "Nadezhda stops Oleg in the hallway with a question while he goes on putting his coat on with the folder under his arm",
  "MS","eye","static","day",False,False,
  "ты спрашиваешь его про ту квартиру на первом этаже, прямо в прихожей."),
 ("A7_SH24", "OLEG_BASE", "val_hall",
  "Oleg's face giving a warm, entirely unspecific answer and thanking her for everything",
  "CU","eye","static","day",False,True,
  "он говорит, что мама всё решила давно, и благодарит тебя за уход."),
 ("A7_SH25", "NAD_MID", "val_hall",
  "Nadezhda's face taking the sentence the way she wants to take it, her shoulders coming down",
  "CU","low","static","day",False,True,
  "ты слышишь в этой фразе именно то, что хочешь услышать, и успокаиваешься."),
 ("A7_SH26", None, "courtyard",
  "a courtyard in May with a car pulling out through the arch, leaf shadow moving across the empty parking strip behind it",
  "WS","eye","pull_out","day",True,False,
  "он уезжает через час, и папку он увозит с собой в машине."),
 ("A7_SH27", "NAD_MID", "val_kitchen",
  "Nadezhda rubbing a pencil ring off a calendar square with her thumb until the paper greys",
  "MCU","eye","static","dusk",False,False,
  "вечером ты стираешь с календаря обведённое число и больше его не обводишь."),
 ("A7_SH28", None, "courtyard",
  "an apartment courtyard from very high at dusk with the windows coming on one by one across the block",
  "EWS","high","static","dusk",True,False,
  "а бумагу вы так и не оформите ни разу за весь девятый год."),
]

if __name__ == "__main__":
    seed_act("daughter", P4, DAUGHTER)
    seed_act("deeper",   P5, DEEPER)
    seed_act("bell",     P6, BELL)
    seed_act("papers",   P7, PAPERS)
