# -*- coding: utf-8 -*-
"""cloakroom batch B: gallery_a (coat-man + widow) + gallery_b (prov-girl + critic). static."""
from _cloakroom_engine import seed_act

PAL_A="warm chandelier-gold arrivals palette, brass and deep red velvet, polished marble, an evening of elegant arrivals"
GA=[
 # --- B1 Человек с новым пальто ---
 ("GA_SH01",None,"foyer_marble","a Habsburg-era theatre foyer on an evening of arrivals, elegant patrons crossing the marble under chandeliers","EWS","high","push_in","dusk",True,False,
  "теперь тебе за сорок, и ты знаешь в лицо каждого, кто ходит сюда из года в год."),
 ("GA_SH02","COATMAN_MID","cloakroom_counter","a smooth charming man in a brand-new overcoat handing it across the brass rail, a well-dressed woman on his arm","MS","eye","static","dusk",False,False,
  "этот приходит дважды в месяц, и каждый раз протягивает тебе новое пальто и новую женщину."),
 ("GA_SH03",None,"cloakroom_counter","extreme close on a small paper price tag still tucked into the sleeve of a brand-new coat","INSERT","top","push_in","dusk",True,True,
  "на рукаве иногда забыта бирка, и ты молча срезаешь её, прежде чем повесить пальто на крючок."),
 ("GA_SH04","COATMAN_MID","cloakroom_counter","close on the man's confident charming face as he winks and pockets the brass token","CU","eye","static","dusk",False,False,
  "он подмигивает тебе, как сообщнику, будто вы вдвоём храните какую-то общую весёлую тайну."),
 ("GA_SH05","CLOAK_MID","cloakroom_counter","the attendant taking the new coat across the rail, his reading eyes already at work on the collar","MCU","eye","static","dusk",False,False,
  "ты принимаешь пальто и по запаху воротника уже знаешь, что женщина сегодня снова совсем другая."),
 ("GA_SH06",None,"cloakroom_counter","close on the attendant's hand finding a hotel keycard in the inner pocket of the coat","INSERT","high","push_in","dusk",True,False,
  "в кармане ты находишь ключ-карту от двести седьмого номера и духи, которых не было в прошлый раз."),
 ("GA_SH07","COATMAN_MID","foyer_marble","the man leading his companion toward the auditorium doors, not glancing back","WS","eye","static","dusk",False,False,
  "он ведёт её к залу, не оборачиваясь, и тебе остаются его пальто и его маленький грязный секрет."),
 ("GA_SH08","CLOAK_MID","cloakroom_counter","close on the attendant smoothing the new coat flat on its hook beside many others","CU","high","static","dusk",False,False,
  "ты разглаживаешь пальто ладонью и вешаешь рядом с десятком других, что он сносил у тебя за годы."),
 ("GA_SH09","COATMAN_MID","cloakroom_counter","the man on another visit with a younger woman, an even costlier new coat over the rail","MS","eye","static","dusk",False,False,
  "в следующий раз женщина моложе, пальто дороже, а номерок он берёт уже не глядя на тебя."),
 ("GA_SH10",None,"cloakroom_counter","extreme close on a child's crayon drawing found folded in a coat pocket, the word for papa written on it","INSERT","top","push_in","dusk",False,True,
  "однажды в кармане ты находишь детский рисунок, где подписано папа, и долго держишь его в руках."),
 ("GA_SH11","CLOAK_MID","cloakroom_counter","close on the attendant's troubled face as he refolds the child's drawing and says nothing","CU","eye","push_in","dusk",False,False,
  "ты кладёшь рисунок обратно в карман и ничего не говоришь, потому что гардеробщик не говорит ничего."),
 ("GA_SH12","COATMAN_MID","foyer_marble","the man at a distance across the foyer laughing with yet another companion","WS","high","static","dusk",False,False,
  "ты ведёшь счёт его пальто, как годовым кольцам на спиле, и по ним читаешь, как стынет его жизнь."),
 ("GA_SH13","COATMAN_OLD","cloakroom_counter","years later, an older diminished man in a plain coat handing it over alone, hands unsteady","MCU","eye","static","night",False,False,
  "проходит двадцать лет, и однажды он приходит один, без женщины, в простом сером пальто."),
 ("GA_SH14","COATMAN_OLD","cloakroom_counter","close on the old man's hollow ageing face fumbling for his token, no wink left in him","CU","eye","push_in","night",False,False,
  "он больше не подмигивает, долго ищет в кармане номерок, и руки у него заметно дрожат."),
 ("GA_SH15",None,"cloakroom_counter","extreme close on a worn old camel overcoat on a hook, the same coat from twenty years before","INSERT","eye","push_in","night",False,True,
  "и пальто на нём то самое, верблюжье, в котором он пришёл сюда впервые, ещё совсем молодым."),
 ("GA_SH16","CLOAK_MID","cloakroom_counter","the attendant recognising the old camel coat with a quiet ache before recognising the man","MS","eye","static","night",False,False,
  "ты узнаёшь это пальто раньше, чем его лицо, и понимаешь, что все женщины давным-давно ушли."),
 ("GA_SH17","COATMAN_OLD","cloakroom_counter","close on the old man looking at the empty hook beside his, where her coat once always hung","CU","eye","static","night",False,False,
  "он смотрит на пустой соседний крючок, где когда-то висели их пальто, и долго ничего не говорит."),
 ("GA_SH18","COATMAN_OLD","foyer_marble","the stooped old man walking alone toward the auditorium, no companion at his side","BACK","low","track","night",False,False,
  "он идёт в зал один, и ты впервые вешаешь его пальто без соседнего, рядом теперь пусто."),
 ("GA_SH19","CLOAK_MID","cloakroom_counter","close on the attendant's quiet face watching the old man go","CU","eye","push_in","night",False,False,
  "и ты думаешь, что человек снашивает женщин, как пальто, а в конце остаётся в самом первом."),
 ("GA_SH20","CLOAK_MID","stage_empty","the attendant at night on the empty stage wearing the man's old coat, beginning to play him","WS","low","push_in","night",False,False,
  "ночью ты надеваешь его старое пальто и играешь его на сцене, со всеми его женщинами разом."),
 ("GA_SH21","CLOAK_MID","stage_empty","the attendant as the coat-man charming the empty house, a confident wink to the dark seats","MS","low","static","night",False,False,
  "ты подмигиваешь пустым креслам его подмигиванием и впервые понимаешь его до самого дна."),
 ("GA_SH22","CLOAK_MID","stage_empty","close on the attendant's face playing the coat-man, hollow charm over emptiness","CU","eye","push_in","night",False,False,
  "и в его пустоте ты узнаёшь свою, потому что вы оба всю жизнь ждали не тех, кто к вам приходил."),
 # --- B2 Вдова с двумя номерками ---
 ("GA_SH23","WIDOW_BASE","cloakroom_counter","a dignified woman in dark wool handing over two coats, a grey man's coat folded over her right arm","MS","eye","static","dusk",False,False,
  "а эта приходит одна и сдаёт сразу два пальто, своё и мужское серое, что несёт на руке."),
 ("GA_SH24",None,"cloakroom_counter","extreme close on a folded grey man's overcoat carried tenderly over a woman's right arm","INSERT","high","push_in","dusk",False,True,
  "серое мужское пальто она держит сложенным на правой руке, бережно, как держат под локоть живого."),
 ("GA_SH25","WIDOW_BASE","cloakroom_counter","close on the widow's composed grieving face as she accepts two brass tokens","CU","eye","static","dusk",False,False,
  "ты даёшь ей два номерка, и она кивает, будто муж просто отошёл купить программку в буфете."),
 ("GA_SH26","CLOAK_MID","cloakroom_counter","the attendant hanging the grey coat beside hers, smoothing both flat with his palm","MS","eye","static","dusk",False,False,
  "ты вешаешь серое рядом с её, разглаживаешь оба ладонью и оставляешь между ними ровно ладонь."),
 ("GA_SH27",None,"cloakroom_counter","two coats hanging side by side on adjacent numbered hooks, a woman's and a grey man's","WS","eye","pan_right","dusk",True,True,
  "и весь спектакль два пальто висят рядом, как пара, что всё ещё ходит в театр вдвоём."),
 ("GA_SH28","WIDOW_BASE","auditorium","the widow taking her seat in the tiered velvet rows, an empty seat kept beside her with a playbill on it","MCU","high","static","dusk",False,False,
  "в зале рядом с ней пустует одно кресло, и она кладёт на него программку, как кладут на колени."),
 ("GA_SH29","WIDOW_BASE","auditorium","close on the widow watching the stage alone, leaning slightly toward the empty seat","CU","eye","push_in","dusk",False,False,
  "она смотрит спектакль за двоих и в антракте тихо пересказывает пустому креслу, что было смешного."),
 ("GA_SH30",None,"cloakroom_counter","close on two brass tokens held apart in the attendant's hand from the rest","INSERT","top","static","dusk",True,False,
  "ты держишь её два номерка отдельно от прочих, чтобы не перепутать и вернуть в правильные руки."),
 ("GA_SH31","CLOAK_MID","cloakroom_counter","the attendant returning both coats to the widow after the performance","MS","eye","static","night",False,False,
  "после спектакля ты подаёшь ей оба пальто, и она надевает своё, а серое снова берёт на руку."),
 ("GA_SH32","WIDOW_BASE","cloakroom_counter","close on the widow pressing the grey coat briefly to her face, breathing it in","CU","eye","push_in","night",False,False,
  "она на миг прижимает серое пальто к лицу, вдыхает, и ты отводишь глаза, чтобы не мешать ей."),
 ("GA_SH33","WIDOW_BASE","street_cobble","the widow crossing the night square with the grey coat over her arm, looking like two from behind","WS","high","track","night",False,False,
  "она уходит через площадь с пальто на руке, и со спины кажется, что их всё-таки двое."),
 ("GA_SH34","WIDOW_BASE","cloakroom_counter","a winter visit, something changed in the widow's face as she approaches the counter","MCU","eye","static","night",False,False,
  "так длится четыре сезона, а в пятую зиму в её лице что-то меняется, и ты сразу это видишь."),
 ("GA_SH35",None,"cloakroom_counter","extreme close on a single coat handed across the rail and one brass token offered back","INSERT","eye","push_in","night",False,True,
  "в тот вечер она протягивает одно пальто, своё, и просит один номерок, и ты понимаешь всё."),
 ("GA_SH36","CLOAK_MID","cloakroom_counter","the attendant's hands taking only one coat, his eyes drifting to the bare hook beside it","MCU","high","static","night",False,False,
  "ты берёшь одно пальто и невольно смотришь на соседний крючок, который теперь останется пустым."),
 ("GA_SH37","WIDOW_BASE","cloakroom_counter","close on the widow's face, drier now and more alone, lighter by one coat","CU","eye","push_in","night",False,False,
  "она не плачет, она просто стала на одно пальто легче, и эта лёгкость тяжелее всего на свете."),
 ("GA_SH38","CLOAK_MID","cloakroom_counter","the attendant hanging her single coat and leaving the neighbouring hook deliberately bare","MS","eye","static","night",False,False,
  "ты вешаешь её одинокое пальто и оставляешь соседний крючок пустым, как она оставила то кресло."),
 ("GA_SH39",None,"auditorium","a row in the auditorium with two empty velvet seats together, dim house-light","WS","high","static","night",True,False,
  "теперь в зале пустуют уже два кресла рядом, и она садится чуть в стороне от них обоих."),
 ("GA_SH40","CLOAK_MID","stage_empty","the attendant at night with a grey coat over his arm, beginning to play the widow","MCU","eye","static","night",False,False,
  "ночью ты берёшь чьё-то серое пальто на руку и играешь её, что носит мужа на сгибе локтя."),
 ("GA_SH41","CLOAK_MID","stage_empty","close on the attendant pressing a coat to his face in the widow's gesture, playing to the dark","CU","eye","push_in","night",False,False,
  "ты прижимаешь чужое пальто к лицу её жестом, и пустой зал смотрит, как ты тоскуешь по тому, чего не было."),
 ("GA_SH42",None,"stage_empty","a grey coat laid over an empty chair on the dark stage under the ghost-light","INSERT","eye","push_in","night",False,True,
  "ты кладёшь серое пальто на пустой стул на сцене, и это твоя лучшая партнёрша за все годы."),
]

PAL_B="cool faded-plush palette, dim gold house-light, worn velvet and old paper, a wry chill in the air"
GB=[
 # --- B3 Провинциалка ---
 ("GB_SH01",None,"foyer_marble","a premiere-night foyer with a well-dressed crowd crossing the marble toward the staircase","EWS","high","push_in","dusk",True,False,
  "в начале девяностых сюда приходит девушка, что копит на верхний ярус по три месяца."),
 ("GB_SH02","PROVGIRL_YOUNG","cloakroom_counter","an earnest provincial young woman handing over a re-tailored turned coat with mismatched buttons","MS","eye","static","dusk",False,False,
  "она протягивает тебе пальто, перешитое из материнского, с пуговицами все до одной разными."),
 ("GB_SH03",None,"cloakroom_counter","extreme close on a coat front with several mismatched re-sewn buttons in slightly different threads","INSERT","top","push_in","dusk",False,True,
  "пуговицы пришиты разные, аккуратно, нитки чуть разного цвета, и ты замечаешь это сразу."),
 ("GB_SH04","PROVGIRL_YOUNG","cloakroom_counter","close on the young woman's hopeful nervous face, holding herself very straight","CU","eye","static","dusk",False,False,
  "она стесняется этого пальто и держится прямо, как держатся те, кому очень важно быть здесь."),
 ("GB_SH05","CLOAK_MID","cloakroom_counter","the attendant deliberately hanging her coat on the very best hook and offering the lowest-numbered token","MCU","eye","static","dusk",False,False,
  "ты вешаешь её перешитое пальто на лучший крючок и даёшь номерок поменьше, как примадонне."),
 ("GB_SH06","PROVGIRL_YOUNG","cloakroom_counter","close on the young woman lighting up at the small kindness, straightening her shoulders","CU","eye","push_in","dusk",False,False,
  "она замечает это и вспыхивает от радости, и впервые за весь вечер расправляет плечи."),
 ("GB_SH07","PROVGIRL_YOUNG","auditorium","the young woman up in the gallery leaning over the rail, enraptured by the stage below","WS","high","static","dusk",False,False,
  "наверху она перевешивается через перила и смотрит вниз так, будто это её собственная премьера."),
 ("GB_SH08",None,"auditorium","close on the lowest-numbered brass token clutched in a young woman's hand through the show","INSERT","eye","push_in","dusk",False,False,
  "маленький номерок она сжимает весь спектакль, как пропуск в жизнь, которой у неё пока нет."),
 ("GB_SH09","PROVGIRL_YOUNG","cloakroom_counter","the young woman shyly returning the token, thanking the attendant twice","MS","eye","static","night",False,False,
  "после спектакля она благодарит тебя дважды и уходит, не зная, что ты дал ей чужое место."),
 ("GB_SH10","CLOAK_MID","cloakroom_counter","close on the attendant's face watching her go, a rare warmth in his tired eyes","CU","eye","push_in","night",False,False,
  "ты смотришь ей вслед и думаешь, что хоть кому-то этот театр сегодня дал то, за чем шли."),
 ("GB_SH11",None,"street_cobble","a young woman crossing the night square on foot, glowing, the lit theatre behind her","WS","high","static","night",True,False,
  "она идёт через площадь домой пешком, чтобы не тратить на трамвай последние свои кроны."),
 ("GB_SH12","CLOAK_MID","stage_empty","the attendant at night playing the young woman, clutching an imaginary token to his chest","MCU","eye","static","night",False,False,
  "ночью ты играешь её, девочку с разными пуговицами, что сжимает номерок, как лотерейный билет."),
 ("GB_SH13","CLOAK_MID","stage_empty","close on the attendant leaning over an imagined gallery rail with a newcomer's wonder","CU","low","push_in","night",False,False,
  "ты перевешиваешься через несуществующие перила и смотришь вниз глазами той, кому всё это в новинку."),
 ("GB_SH14",None,"foyer_marble","a framed playbill on a brass stand marking the passing of fifteen seasons","INSERT","eye","push_in","day",True,False,
  "проходит пятнадцать лет, пуговицы и трамваи остаются в прошлом, и однажды она входит другой."),
 ("GB_SH15","PROVGIRL_RICH","cloakroom_counter","a polished wealthy woman in furs handing over an expensive fur coat without a glance","MS","eye","static","dusk",False,False,
  "теперь она в мехах, в дорогой стрижке, и протягивает тебе шубу, не глядя в твою сторону."),
 ("GB_SH16","PROVGIRL_RICH","cloakroom_counter","close on the wealthy woman's cool composed face, no flicker of recognition","CU","eye","static","dusk",False,False,
  "она тебя не узнаёт, того, кто дал ей лучший крючок, когда у неё не было совсем ничего."),
 ("GB_SH17",None,"cloakroom_counter","extreme close on a single coin left on a small brass tipping saucer on the counter","INSERT","top","push_in","dusk",False,True,
  "она оставляет на блюдце десять крон чаевых и идёт к залу, и ты для неё теперь просто прислуга."),
 ("GB_SH18","CLOAK_MID","cloakroom_counter","the attendant looking from the coin on the saucer to the woman's departing back","MCU","eye","static","dusk",False,False,
  "ты смотришь на монету и на её спину и решаешь не напоминать ей про разные пуговицы."),
 ("GB_SH19","CLOAK_MID","cloakroom_counter","close on the attendant's quiet face, the small grief of being forgotten","CU","eye","push_in","dusk",False,False,
  "ты вешаешь её шубу на тот же самый лучший крючок, молча, и это твой единственный ей ответ."),
 ("GB_SH20",None,"cloakroom_counter","a fur coat hanging on the best hook where a humble turned coat once hung","WS","eye","pan_left","dusk",True,True,
  "на том крючке когда-то висело перешитое пальто, и об этом теперь помнишь только ты один."),
 # --- B4 Критик ---
 ("GB_SH21","CRITIC_BASE","cloakroom_counter","a sour fastidious man at the counter handing over a coat but keeping a checked scarf wound at his throat","MS","eye","static","dusk",False,False,
  "критик приходит на каждую премьеру и никогда не сдаёт свой клетчатый шарф, ни зимой, ни летом."),
 ("GB_SH22",None,"cloakroom_counter","extreme close on a worn checked woollen scarf and a small notebook in a coat pocket","INSERT","top","push_in","dusk",False,True,
  "шарф клетчатый, потёртый, и блокнотик в кармане, и от него всегда пахнет холодными сигаретами."),
 ("GB_SH23","CRITIC_BASE","cloakroom_counter","close on the critic's narrow eyes behind glasses, keeping the scarf on as if for protection","CU","eye","static","dusk",False,False,
  "он сдаёт пальто, но шарф оставляет на себе, будто боится, что без него ты прочтёшь его насквозь."),
 ("GB_SH24","CLOAK_MID","cloakroom_counter","the attendant taking the critic's coat, quietly noting the man","MCU","eye","static","dusk",False,False,
  "ты принимаешь его пальто и уже знаешь, что завтра он напишет ровно наоборот тому, что почувствует."),
 ("GB_SH25","CRITIC_BASE","auditorium","the critic in an aisle seat scribbling in his notebook in the dark without looking at the page","WS","high","static","dusk",False,False,
  "в зале он сидит с краю, с блокнотом, и пишет в темноте, не глядя на страницу под рукой."),
 ("GB_SH26","CRITIC_BASE","auditorium","close on the critic's face at the curtain call betraying genuine helpless delight","CU","eye","push_in","night",False,False,
  "но на поклонах ты видишь его лицо из-за кулис, и оно сияет, по-настоящему, против его воли."),
 ("GB_SH27",None,"cloakroom_counter","extreme close on a newspaper page with a harsh theatre-review headline the next morning","INSERT","eye","push_in","day",False,False,
  "а наутро в газете он называет спектакль провалом и подбирает самые ядовитые свои слова."),
 ("GB_SH28","CLOAK_MID","cloakroom_counter","the attendant reading the newspaper behind the counter, shaking his head, unsurprised","MS","eye","static","day",False,False,
  "ты читаешь рецензию за стойкой и качаешь головой, потому что лицо его врёт хуже, чем перо."),
 ("GB_SH29","CRITIC_BASE","cloakroom_counter","the same man at another premiere in the same scarf, a season later","CU","eye","static","dusk",False,False,
  "он приходит снова и снова, годами, в том же шарфе, и каждый раз восхищается тайком и ругает вслух."),
 ("GB_SH30","CLOAK_MID","cloakroom_counter","the attendant handing the coat back, the scarf still wound at the critic's throat","MCU","eye","static","night",False,False,
  "ты подаёшь ему пальто и думаешь, что вы похожи, оба прячете то, что чувствуете, под чем-нибудь."),
 ("GB_SH31",None,"stage_empty","the empty stage at night, a checked scarf draped over the ghost-light stand","WS","eye","push_in","night",True,False,
  "ночью ты играешь его, человека в шарфе, что аплодирует одной рукой, а другой пишет разнос."),
 ("GB_SH32","CLOAK_MID","stage_empty","the attendant at night playing the critic, scribbling in the air and beaming at once","MCU","eye","static","night",False,False,
  "ты хвалишь пустой зал шёпотом и тут же ругаешь его в блокнот, и обе роли тебе одинаково знакомы."),
 ("GB_SH33","CLOAK_MID","stage_empty","close on the attendant's face holding two contradictory expressions, the doubled mask","CU","eye","push_in","night",False,False,
  "ты понимаешь его лучше всех в этом городе, потому что сам всю жизнь улыбаешься не тем, чем живёшь."),
 ("GB_SH34",None,"cloakroom_counter","extreme close on the checked scarf left forgotten on the wooden counter","INSERT","top","push_in","night",False,True,
  "однажды он забывает шарф на стойке, и ты вешаешь его на крючок и хранишь до самого нового сезона."),
 ("GB_SH35","CRITIC_BASE","cloakroom_counter","the critic returning for his scarf, oddly bare and aged at the throat without it","MS","eye","static","day",False,False,
  "он возвращается за шарфом через неделю, и без него у горла он будто раздет и сильно постарел."),
 ("GB_SH36","CRITIC_BASE","cloakroom_counter","close on the critic almost human without his scarf, meeting the attendant's eyes","CU","eye","push_in","day",False,False,
  "без шарфа он впервые смотрит тебе в лицо и тихо благодарит, и это всё, что между вами будет."),
 ("GB_SH37",None,"foyer_marble","the grand foyer emptying after a premiere, scattered programmes on the marble","WS","high","static","night",True,False,
  "ты возвращаешь ему шарф, он повязывает его и снова становится тем, кто врёт за деньги."),
 ("GB_SH38","CLOAK_MID","cloakroom_counter","the attendant alone after closing, folding a forgotten coat over his arm","MCU","eye","static","night",False,False,
  "а ты остаёшься со своей стойкой и думаешь, что честнее всех тут только пальто на крючках."),
]

seed_act("gallery_a", PAL_A, GA, render_mode="static")
seed_act("gallery_b", PAL_B, GB, render_mode="static")
