# -*- coding: utf-8 -*-
"""layoff act A6 aftermath (пустые будни, центр занятости, мёртвая карта). PYTHONIOENCODING=utf-8 python scripts/_seed_layoff_A6.py"""
from _layoff_engine import seed_act
PAL="hollow muted palette, desaturated grey and washed beige, flat tired daylight, long empty shadows"
S=[
 ("A6_SH01",None,"home_kitchen","a macro insert of a dead plastic access card on a blue lanyard lying in a kitchen drawer among old receipts","ECU","top","static","morning",True,False,
  "теперь по утрам нет турникета, к которому нужно приложить пропуск, и эта тишина оглушает сильнее будильника."),
 ("A6_SH02","GEROY_MAIN","bedroom_night","a medium close-up of the man waking at the same hour out of habit, sitting up in the grey morning","MCU","eye","static","morning",False,False,
  "ты по привычке просыпаешься в семь, бреешься, надеваешь рубашку, а потом вспоминаешь, что идти тебе некуда."),
 ("A6_SH03","GEROY_MAIN","bedroom_night","a close-up of the man sitting on the edge of the bed already dressed, lost with nowhere to go","CU","eye","static","morning",False,False,
  "ты сидишь на краю кровати уже одетый и впервые за двадцать лет не знаешь, чем занять это утро."),
 ("A6_SH04",None,"street_tower","a wide view of the distant glass office tower on the skyline, seen now from far away","WS","eye","static","day",True,False,
  "стеклянная башня всё так же стоит на горизонте, только теперь ты смотришь на неё, как чужой человек."),
 ("A6_SH05","GEROY_MAIN","job_center","a medium shot of the man taking a paper number ticket at a municipal employment office counter","MS","eye","static","day",False,False,
  "ты берёшь талончик с номером в центре занятости и садишься в очередь, которую раньше видел только в новостях."),
 ("A6_SH06",None,"job_center","a macro insert of a paper queue ticket reading number eighty-four and a flickering vacancies board behind it","INSERT","eye","static","day",True,False,
  "в руке у тебя бумажный талон с номером восемьдесят четыре, а на табло мигают чужие фамилии и вакансии."),
 ("A6_SH07","GEROY_MAIN","job_center","a medium close-up of the man waiting in a row of much younger applicants, feeling out of place","MCU","eye","static","day",False,False,
  "вокруг тебя сидят люди вдвое моложе, и ты впервые чувствуешь себя в этой очереди лишним и старым."),
 ("A6_SH08","GEROY_MAIN","job_center","a close-up of the man's face hearing a polite rejection across a counter","CU","eye","static","day",False,False,
  "девушка за стойкой вежливо говорит, что в твоей сфере сейчас ищут кандидатов помоложе и подешевле."),
 ("A6_SH09","GEROY_MAIN","home_kitchen","a medium shot of the man filling out job applications at his kitchen table, a laptop open","MS","eye","static","day",False,False,
  "дома ты заполняешь за кухонным столом анкету за анкетой, вспоминая, как сам когда-то отсеивал такие же."),
 ("A6_SH10",None,"home_kitchen","a macro insert of a laptop screen showing yet another short rejection email","INSERT","top","static","day",True,False,
  "на экране ноутбука загорается очередной ответ — к сожалению, мы выбрали другого кандидата."),
 ("A6_SH11","GEROY_MAIN","home_kitchen","a close-up of the man reading the rejection, a tired bitter recognition on his face","CU","eye","static","day",False,False,
  "ты читаешь этот отказ уже в десятый раз, и от того, что сам писал когда-то такие же письма, не легче."),
 ("A6_SH12","WIFE_BASE","home_kitchen","a medium shot of the auburn-haired wife coming home late and tired, setting down a bag","MS","eye","static","night",False,False,
  "жена возвращается поздно, она теперь берёт лишние смены, и вы оба молчите об этом за ужином."),
 ("A6_SH13","GEROY_MAIN","home_kitchen","a close-up of the man unable to meet his wife's eyes across the kitchen","CU","eye","static","night",False,False,
  "ты не можешь поднять на неё глаза, потому что впервые за двенадцать лет не ты приносишь в дом деньги."),
 ("A6_SH14",None,"home_kitchen","a macro insert of a severance pay envelope on a shelf, visibly thinner than before","INSERT","top","static","day",True,False,
  "в ящике лежит конверт с выходным пособием, и с каждым месяцем он становится заметно тоньше."),
 ("A6_SH15","GEROY_MAIN","home_hallway","a medium close-up of the man on the phone in the hallway, forcing a cheerful voice","MCU","eye","static","day",False,False,
  "звонит старый друг, спрашивает, как дела, и ты бодро отвечаешь, что всё нормально, просто в поиске."),
 ("A6_SH16",None,"street_tower","a wide street view of the glass tower as a passerby hurries past it with quickened step","WS","eye","static","day",True,False,
  "иногда ты проходишь мимо своей бывшей башни и ускоряешь шаг, будто боишься, что тебя узнают."),
 ("A6_SH17","GEROY_MAIN","turnstile_lobby","a medium close-up of the man standing outside across from the lobby, watching others tap their cards","MCU","over","static","day",False,False,
  "ты останавливаешься через дорогу от стеклянных дверей и смотришь, как другие прикладывают свои пропуска."),
 ("A6_SH18","GEROY_MAIN","turnstile_lobby","a close-up of the man's face listening to the faint turnstile beep that is no longer his","CU","eye","static","day",False,False,
  "оттуда долетает тот самый короткий писк турникета, только теперь он отзывается уже не тебе."),
 ("A6_SH19","GEROY_MAIN","home_kitchen","a medium shot of the man pulling open a kitchen drawer and finding his old access card among receipts","MS","eye","static","day",False,False,
  "спустя несколько месяцев ты выдвигаешь кухонный ящик и находишь там свой старый пропуск среди чеков."),
 ("A6_SH20","GEROY_MAIN","home_kitchen","an extreme close-up of the man's finger running over the dead access card, no green light","ECU","top","static","day",False,True,
  "ты проводишь пальцем по мёртвой карте, на которой больше не загорится зелёный и не прозвучит писк."),
 ("A6_SH21","GEROY_MAIN","home_kitchen","a close-up of the man's hollow face holding the dead card, the routine that defined him gone","CU","eye","push_in","day",False,True,
  "ты сидишь с этой картой в руке, и внутри ровно та тихая пустая пропасть, которой раньше так боялся."),
 ("A6_SH22","GEROY_MAIN","home_kitchen","an extreme wide dusk view of the small kitchen, the lone figure of the man sitting small at the table, lit city windows beyond the glass","EWS","eye","static","dusk",False,True,
  "за окном города зажигаются чужие окна, а ты сидишь за кухонным столом один, и впереди очень длинный день."),
]
if __name__=="__main__": seed_act("aftermath", PAL, S, render_mode="static")
