# -*- coding: utf-8 -*-
"""teacher acts: sugar (1994–96, 34 shots) + gate (1999, 32 shots). Static (Ken Burns).
Run: PYTHONIOENCODING=utf-8 python scripts/_seed_teacher_A4A5.py"""
from _teacher_engine import seed_act

PAL4="cold nineties palette of slush grey, tarpaulin stripe blue, dim bulb amber and sugar-sack white"
SUGAR=[
("A4_SH01","LIDA_YOUNG","wedding_cafe",
 "a bride of twenty-six in a simple white dress and a young sandy-ginger engineer in an ill-fitting suit at a pushed-together cafe table, paper garlands, salads in cut-glass bowls, low afternoon sun",
 "WS","eye","static","day",False,True,
 "в девяносто четвёртом ты выходишь за володю, инженера, и свадьба у вас на двадцать гостей."),
("A4_SH02","VOLODYA_YOUNG","wedding_cafe",
 "the young engineer groom raising a toast glass, steel chronograph on his right wrist, his open freckled face flushed and happy, tinsel-framed mirror behind",
 "MCU","eye","static","day",False,False,
 "володя поднимает тост и обещает, что через пять лет у вас будет своя двухкомнатная."),
("A4_SH03","LIDA_YOUNG","wedding_cafe",
 "the bride laughing over a homemade greeting card signed by a whole school class, childish signatures crowding the paper, her amber ring bright on her hand",
 "CU","eye","static","day",False,False,
 "твой седьмой б передаёт самодельную открытку, где расписались все тридцать четыре, даже саня."),
("A4_SH04",None,"lida_kitchen",
 "a small kitchen morning, two plates and two cups laid out, a man's jacket over one chair and a stack of exercise notebooks pushed to the table's far end",
 "INSERT","eye","static","morning",True,False,
 "теперь на твоей кухне два прибора, и тетради впервые уступают край стола другому человеку."),
("A4_SH05","LIDA_YOUNG","classroom_hers_90s",
 "the teacher at her desk before lessons counting a thin fold of banknotes twice, her lips moving, the class register open beside her",
 "MS","high","static","morning",False,False,
 "в девяносто пятом зарплату начинают задерживать, сначала на неделю, потом на месяц."),
("A4_SH06","LIDA_YOUNG","teachers_room",
 "teachers around the staff-room table in coats, a pay ledger open and untouched in the middle, steam from cups, faces tired and closed",
 "WS","eye","static","day",False,False,
 "в учительской висит одно и то же слово, обещали, его передают, как сводку с фронта."),
("A4_SH07","VOLODYA_YOUNG","lida_kitchen",
 "the young engineer at the kitchen table with a newspaper of job listings, circling advertisements with a pencil, jaw set, dinner untouched",
 "MCU","eye","static","evening",False,False,
 "заводу володи тоже платят через раз, и он вечерами обводит объявления карандашом.",
 "his pencil circling one listing, then hovering, his jaw working silently over the newsprint"),
("A4_SH08",None,"market_90s",
 "an open-air clothes market in winter slush, rows of stalls under striped tarpaulins hung with shiny tracksuits, checkered shuttle bags stacked as counters, traders' breath steaming",
 "EWS","eye","pan_right","day",True,False,
 "полгорода теперь стоит на вещевом рынке, и у половины прилавков высшее образование."),
("A4_SH09","LIDA_YOUNG","market_90s",
 "the teacher in her modest coat pricing a pair of jeans at a stall, holding them awkwardly, her chalk-dusted fingers pale against the dark denim",
 "MS","eye","static","day",False,True,
 "ты приценяешься к джинсам и замечаешь, что пальцы у тебя, как всегда, в меловой пыли."),
("A4_SH10","LIDA_YOUNG","market_90s",
 "a stallholder woman recognising the teacher across the hung tracksuits, both women freezing a beat, steam of breath between them, fingerless gloves on the trader's hands",
 "CU","eye","static","day",False,False,
 "за прилавком стоит алла сергеевна, которая пять лет вела у вас в школе математику."),
("A4_SH11","LIDA_YOUNG","market_90s",
 "the two women talking over the stall counter of checkered bags, the trader pressing a thermos cup of tea into the teacher's cold hands",
 "OTS","over","static","day",False,False,
 "она наливает тебе чай из термоса и говорит, здесь за день выходит как в школе за месяц.",
 "the thermos cup passing between gloved and bare hands, steam rising, fingers closing around the warmth"),
("A4_SH12","LIDA_YOUNG","street_winter",
 "the teacher walking home through winter dusk with empty hands, past the bent streetlamp, her breath a slow ribbon, the school's lit windows far behind her",
 "WS","eye","track","evening",False,False,
 "ты идёшь домой без джинсов и всю дорогу споришь сама с собой, и обе стороны правы."),
("A4_SH13","VOLODYA_YOUNG","lida_kitchen",
 "the young engineer speaking earnestly across the kitchen table, palms open, the job newspaper folded to a circled advertisement between the plates",
 "MCU","eye","static","evening",False,False,
 "володя говорит мягко, уйди на рынок хоть на год, люди же выходят, и никто не умер.",
 "his open palms lifting slightly with each phrase, the folded newspaper sliding an inch toward her side"),
("A4_SH14","LIDA_YOUNG","lida_kitchen",
 "the teacher across the table, hands folded on a stack of exercise notebooks as if on a small barricade, her face gentle and immovable",
 "CU","eye","static","evening",False,True,
 "ты кладёшь руки на стопку тетрадей и отвечаешь, а моих тридцать четыре куда, володя."),
("A4_SH15",None,"school_corridor",
 "the school corridor with a handwritten notice taped to the staff-room door, teachers gathered reading it, coats still on, winter light flat along the painted floor",
 "WS","eye","static","day",True,False,
 "в феврале девяносто шестого на дверях учительской вешают объявление про выдачу натурой."),
("A4_SH16","OBJ:sugar_sack",None,
 "a heavy white woven sack of sugar standing on staff-room scales, stencilled black lettering, a clipboard list of teachers' names beside it",
 "INSERT","eye","static","day",False,True,
 "за пять месяцев зарплаты школе привозят сахар, по два мешка по пятьдесят кило на человека."),
("A4_SH17","LIDA_YOUNG","teachers_room",
 "the teacher signing a clipboard list beside the sugar sacks, her amber ring against the rough white weave, colleagues queueing behind her with sledges and trolleys",
 "MS","eye","static","day",False,False,
 "ты расписываешься за свои сто килограммов сладкой зарплаты и не знаешь, плакать или смеяться.",
 "her pen signing the list, her free hand resting on the strained white weave of the sack"),
("A4_SH18","SANYA_KID","school_yard",
 "the stocky black-haired thirteen-year-old with his one-strap backpack dragging a childs sledge across the school yard toward the entrance steps, snow trampled around",
 "MS","eye","static","day",False,False,
 "у крыльца тебя караулит саня с санками, он уже всё знает, в этой школе всё знают все."),
("A4_SH19","LIDA_YOUNG","street_winter",
 "the teacher and the boy hauling two white sugar sacks lashed to a small sledge through winter dusk, both leaning into the rope, breath steaming in the lamplight",
 "WS","eye","track","evening",False,True,
 "вы везёте мешки через двор на санках, и саня командует дорогой, как заправский экспедитор.",
 "the sledge runners cutting through trodden snow, two figures leaning into the rope, the sacks swaying gently"),
("A4_SH20","SANYA_KID","street_winter",
 "the boy of thirteen grinning over his shoulder in the lamplight, rope over his shoulder, snowflakes settling on his black crew cut",
 "MCU","low","static","evening",False,False,
 "он оборачивается и говорит, лидия андреевна, а сладко жить вы теперь будете, зуб даю.",
 "his grin flashing over the shoulder, the rope tightening, snowflakes drifting past his face"),
("A4_SH21","LIDA_YOUNG","street_winter",
 "the teacher laughing openly in the winter street, head back, holding the sledge rope, the first real laugh in a long month",
 "CU","eye","static","evening",False,False,
 "ты смеёшься на всю улицу, впервые за эту зиму, и смех виден в воздухе, как пар.",
 "her head tipping back in a full laugh, breath blooming white, the rope slack in her mitten"),
("A4_SH22",None,"lida_kitchen",
 "two white sugar sacks standing in the corner of a small kitchen like furniture, a doily and a potted violet placed on top of one in domestic surrender",
 "INSERT","eye","static","night",True,False,
 "мешки поселяются в углу кухни, и через неделю володя ставит на них горшок с фиалкой."),
("A4_SH23","LIDA_YOUNG","lida_kitchen",
 "the teacher ladling sugar from an opened sack into jars, a row of filled jars on the table labelled in her even teacher's hand, lamplight warm",
 "MS","eye","static","night",False,False,
 "ты фасуешь зарплату по банкам и подписываешь их своим учительским почерком, сахар, сахар, сахар.",
 "the ladle dipping and pouring in a steady rhythm, sugar hissing into the jar, her writing hand labelling"),
("A4_SH24","MAMA_BASE","village_kitchen",
 "the aging mother at her village kitchen table unpacking a city parcel of sugar jars, pressing one to her cheek, sewing glasses pushed up, the shawl on her shoulders",
 "MCU","eye","static","day",False,False,
 "маме ты отвозишь шесть банок и говоришь, что в городе теперь так модно, с получки сладкое.",
 "her rough hands turning the labelled jar, pressing it briefly to her cheek, a shake of the head"),
("A4_SH25","LIDA_YOUNG","classroom_hers_90s",
 "the teacher giving a lesson with full animation before her class, chalk in hand, coat hanging by the door still dusted with snow, the room alive around her",
 "WS","eye","static","day",False,False,
 "а утром ты снова у доски, потому что программе всё равно, платят тебе или нет.",
 "her chalk hand sweeping through a diagram, her body turning between board and class in easy rhythm"),
("A4_SH26","KATYA_KID","classroom_hers_90s",
 "the copper-haired sixteen-year-old in round glasses reading an essay aloud standing at her desk, the class turned toward her, winter sun through tall frames",
 "MS","eye","static","day",False,False,
 "катя читает вслух сочинение о будущем, и в классе тихо, как перед первым снегом.",
 "the pages trembling faintly in her hands, her voice carrying, heads turning toward her one by one"),
("A4_SH27","LIDA_YOUNG","classroom_hers_90s",
 "the teacher listening to the reading girl from beside the blackboard, arms folded softly, chalk stub in one hand, her eyes bright with held pride",
 "MCU","eye","static","day",False,True,
 "ты слушаешь её и думаешь, вот ради этой тишины ты и не ушла на рынок.",
 "her arms folding softly, the chalk stub turning once in her fingers, her eyes steady on the girl"),
("A4_SH28","OBJ:red_pen",None,
 "a red ballpoint pen lying across an open essay notebook, the margin filled with careful red notes in a fine teacher's hand, lamplight",
 "ECU","top","static","night",False,False,
 "проверка одной катиной работы занимает у тебя дольше, чем весь остальной класс вместе."),
("A4_SH29","VOLODYA_YOUNG","lida_kitchen",
 "the engineer husband asleep in a kitchen chair by the radio, the job newspaper fallen open on his chest, his chronograph watch glinting in lamplight",
 "MS","eye","static","night",False,False,
 "володя устраивается во вторую смену в депо, и вы теперь видитесь короче, чем перемена.",
 "the newspaper rising and falling on his chest, the radio dial glowing, his watch hand slack over the armrest"),
("A4_SH30","LIDA_YOUNG","lida_kitchen",
 "the teacher covering her sleeping husband with a blanket, then returning to the lamplit end of the table where the notebook stack waits",
 "WS","eye","static","night",False,False,
 "ты укрываешь его пледом и возвращаешься к тетрадям, у каждого из вас своя вахта.",
 "the blanket settling over his shoulders, her figure crossing back into the lamplight, a chair drawn in softly"),
("A4_SH31",None,"street_winter",
 "the winter street at deep night, all windows dark except one warm kitchen window on a low floor, snow falling straight and unhurried through the lamplight",
 "EWS","eye","static","night",True,False,
 "в девяносто шестом вся улица засыпает рано, свет до полуночи горит только у проверяющих тетради."),
("A4_SH32","LIDA_YOUNG","school_yard",
 "the teacher greeting her class by the young maple in early autumn, the tree now twice a child's height, asters again in dozens of small fists",
 "MS","eye","static","morning",False,False,
 "приходит новый сентябрь, твой класс уже девятый, а клён под окнами догнал второй этаж."),
("A4_SH33","LIDA_YOUNG","classroom_hers_90s",
 "the teacher wiping the green board at dusk with a wide calm stroke, the day's writing dissolving into wet streaks, her silhouette straight against the tall window",
 "BACK","eye","static","evening",False,False,
 "ты стираешь с доски прожитый день и думаешь, что худшее время вы, кажется, пережили.",
 "the wet rag travelling in wide even arcs, white writing dissolving into streaks, her back straight and still"),
("A4_SH34","OBJ:chalk",None,
 "a chalk stub and a red pen lying together in an open drawer beside a folded squared-paper plan gone soft at the folds, drawer wood worn smooth",
 "INSERT","top","push_in","evening",False,True,
 "план на листке в клетку переезжает в ящик стола, но ты всё ещё знаешь его наизусть."),
]

PAL5="polished late-nineties palette of office beige, blind-sliced daylight, cold steel grey and contract-paper white"
GATE=[
("A5_SH01",None,"school_yard",
 "the city-edge school in early autumn of nineteen ninety-nine, the young maple half the height of the building now, pupils streaming in past the flagpole",
 "EWS","high","static","morning",True,False,
 "девяносто девятый, тебе тридцать один, и у тебя новый классный, восьмой б, тридцать голов."),
("A5_SH02","LIDA_MID","classroom_hers_90s",
 "the teacher of thirty-one with the first grey strand at her temple calling the register in her classroom, morning sun on thirty young heads",
 "MS","eye","static","morning",False,False,
 "ты знаешь их всех по именам с первой недели и половину их родителей ещё по прошлым выпускам.",
 "her finger travelling down the register as she calls, her eyes lifting to each answering face"),
("A5_SH03","LIDA_MID","teachers_room",
 "the teacher called to the staff-room telephone, receiver to her ear, colleagues glancing over their cups, her face going carefully neutral",
 "MCU","eye","static","day",False,False,
 "в октябре тебя зовут к телефону, и вежливый голос называет тебя по имени и отчеству.",
 "the receiver pressing closer to her ear, her free hand finding the table edge, her face smoothing to neutral"),
("A5_SH04",None,"gym_office",
 "a renovated private-school director's office, a wide polished desk with a leather blotter, framed licenses on freshly painted walls, vertical blinds slicing bright daylight",
 "WS","eye","static","day",True,False,
 "частная гимназия занимает бывший детсад в центре, и там пахнет краской и другими деньгами."),
("A5_SH05","LIDA_MID","gym_office",
 "the teacher seated in an upholstered visitor chair, upright as at an exam, her plain cardigan against the polished office, hands folded on her worn handbag",
 "MS","eye","static","day",False,False,
 "тебя приглашают завучем, со своими часами литературы, и ты сидишь прямо, как на экзамене.",
 "her hands folding tighter on the handbag, her spine finding the chair's edge, her chin level"),
("A5_SH06",None,"gym_office",
 "a contract laid on a leather blotter, a heavy pen resting across it, a salary figure circled in confident ink, blind-sliced light banding the paper",
 "INSERT","top","push_in","day",False,True,
 "в договоре стоит цифра в шесть раз больше твоей ставки, обведённая уверенным кружком."),
("A5_SH07","LIDA_MID","gym_office",
 "the teacher's eyes moving over the contract, the circled figure reflected as a pale band in her reading glasses, her face very still",
 "CU","eye","static","day",False,False,
 "ты читаешь цифру и сразу видишь мамины лекарства, новую крышу в посёлке и отпуск у моря.",
 "her eyes travelling the contract line by line, stopping on the circle, her breath going shallow"),
("A5_SH08","LIDA_MID","gym_office",
 "a manicured hand extending a heavy pen across the desk toward the teacher, her own hand rising to meet it with white chalk dust plain on the fingers",
 "OTS","over","static","day",False,True,
 "директор протягивает ручку, и ты видишь свои пальцы, на них, как всегда, меловая пыль."),
("A5_SH09","OBJ:chalk",None,
 "fingertips pale with fine white chalk dust hovering an inch above a heavy black pen on a contract, the circled figure blurred beneath",
 "ECU","top","static","day",False,True,
 "меловая пыль на пальцах старше этого кабинета, старше гимназии и старше самой цифры."),
("A5_SH10","LIDA_MID","gym_office",
 "the teacher lowering her hand short of the pen and asking something instead, her face polite and closed, the director's shape soft beyond the desk",
 "MCU","eye","static","day",False,False,
 "ты не берёшь ручку, ты просишь один день подумать, и голос твой ровнее, чем тебе внутри.",
 "her hand settling back onto the handbag, her chin lifting politely, her thumb finding the amber ring"),
("A5_SH11","LIDA_MID","street_winter",
 "the teacher walking from the renovated building through late autumn streets, coat collar up, past the bent streetlamp, leaves scuttling dry along the path",
 "WS","eye","track","evening",False,False,
 "до дома сорок минут пешком, и всю дорогу цифра идёт рядом с тобой, как попутчица.",
 "her steps steady past the lamp, dry leaves tumbling across the path ahead of her, her collar pressed up"),
("A5_SH12","VOLODYA_YOUNG","lida_kitchen",
 "the engineer husband leaning forward across the kitchen table, animated, tapping the oilcloth with one finger, hope plain on his freckled face",
 "MCU","eye","static","evening",False,False,
 "володя стучит пальцем по клеёнке и повторяет, лида, таких предложений два раза не делают.",
 "his finger tapping the oilcloth in rhythm with his words, his eyebrows up, his body leaning in"),
("A5_SH13","LIDA_MID","lida_kitchen",
 "the teacher at the kitchen table with a letter from her mother unfolded beside a pharmacy receipt, her thumb turning the amber ring slowly",
 "CU","high","static","evening",False,False,
 "на столе мамино письмо, где между строк аккуратно спрятана цена сердечных лекарств.",
 "her thumb turning the amber ring in slow circles, her eyes resting on the letter's even lines"),
("A5_SH14","LIDA_MID","lida_kitchen",
 "the teacher checking exercise books deep at night, the stack tall, her cheek propped on one hand, the kitchen dark beyond the lamp circle",
 "MS","eye","static","night",False,False,
 "ночью ты проверяешь тетради восьмого б и ловишь себя на том, что запоминаешь почерки прощально.",
 "her red pen slowing on the page, her cheek settling heavier on her palm, her eyes lingering on the writing"),
("A5_SH15","OBJ:notebooks",None,
 "a stack of exercise notebooks with one open on top, a boy's uneven handwriting struggling through an essay, red teacher's notes gentle in the margin",
 "INSERT","top","static","night",False,False,
 "в верхней тетради мальчик, у которого дома пьют, впервые написал сочинение до конца."),
("A5_SH16","LIDA_MID","lida_kitchen",
 "the teacher standing at the dark kitchen window with a cooling cup, her reflection doubled faintly against the courtyard lights, the notebook stack behind her",
 "MCU","eye","static","night",False,True,
 "ты стоишь у тёмного окна и спрашиваешь себя честно, кто доведёт их, если не ты.",
 "steam thinning from the cup in her hands, her reflection steady in the dark glass, courtyard lights trembling"),
("A5_SH17",None,"lida_kitchen",
 "the kitchen at first grey light, an untouched bed visible through the doorway, a burned-down lamp still on over the finished notebook stack",
 "WS","eye","static","morning",True,False,
 "к утру стопка проверена вся, постель не тронута, а решение стоит в тебе уже готовое."),
("A5_SH18","LIDA_MID","school_corridor",
 "the teacher walking the school corridor in morning light, coat still on, past the framed class photographs, her step even and unhurried",
 "WS","eye","track","morning",False,False,
 "утром ты идёшь по коридору мимо рамок с выпусками и здороваешься с каждым уборщицыным ведром.",
 "her even steps carrying her past frame after frame, her head nodding small greetings along the way"),
("A5_SH19","LIDA_MID","classroom_hers_90s",
 "the teacher pausing in her classroom doorway, thirty heads turning to her as one, morning sun across the desks and the washed green board",
 "MS","eye","static","morning",False,True,
 "ты открываешь дверь класса, тридцать голов поворачиваются разом, и всё становится просто.",
 "the door swinging open under her hand, thirty faces lifting toward her, light flooding the row of desks"),
("A5_SH20","LIDA_MID","teachers_room",
 "the teacher at the staff-room telephone, her back straight, one finger pressed to her other ear against the room's noise, her face calm and finished",
 "MCU","eye","static","day",False,True,
 "на перемене ты звонишь в гимназию и говоришь спасибо, но у меня здесь восьмой класс.",
 "her finger pressing to her free ear, her chin steady, the cord swaying gently as she speaks"),
("A5_SH21",None,"gym_office",
 "the director's office seen empty, the contract being slid back into a folder by manicured hands, the heavy pen returned to its stand, blinds banding the desk",
 "INSERT","eye","static","day",True,False,
 "на том конце вежливо помолчали и сказали, что второй раз таких предложений не делают."),
("A5_SH22","LIDA_MID","classroom_hers_90s",
 "the teacher writing the day's lesson topic large and clean on the green board, her back to the camera, chalk line firm, sun in the tall windows",
 "BACK","eye","static","day",False,True,
 "ты возвращаешься в класс и пишешь тему урока, и мел стучит спокойно, как метроном.",
 "her chalk hand travelling firm and even, white letters growing across the green, dust drifting from the line"),
("A5_SH23","SANYA_KID","school_yard",
 "the sixteen-year-old black-haired youth, taller now, backpack still on one shoulder, waving to the teacher across the wide yard from a distant group of leavers by the gate",
 "WS","eye","static","day",False,False,
 "саня заканчивает девятый и уходит в ремесленное, на прощание он жмёт тебе руку, как мужик.",
 "his arm lifting in a wide wave across the yard, his grin flashing, the group by the gate turning"),
("A5_SH24","LIDA_MID","school_yard",
 "the teacher shaking the youth's hand at the school gate with mock ceremony and real warmth, the maple above them full and rustling",
 "OTS","over","static","day",False,False,
 "ты говоришь ему, саня, из тебя выйдет толк, и он впервые не находит, что ответить.",
 "the handshake holding a beat longer than ceremony, his cocky posture softening, leaves stirring above them"),
("A5_SH25","KATYA_KID","school_yard",
 "the copper-haired girl in round glasses, now a graduate with a ribbon sash, holding a bouquet, standing with the teacher by the maple for a photograph",
 "MS","eye","static","day",False,False,
 "катин выпуск уходит годом раньше, она поступает на филологию, на ту самую, на твою.",
 "the two women settling shoulder to shoulder for the photograph, the bouquet passing between their hands"),
("A5_SH26","LIDA_MID","school_yard",
 "the teacher watching the graduates scatter through the school gate, her hand shielding her eyes against the sun, her smile complicated",
 "CU","eye","static","day",False,False,
 "ты смотришь ей вслед и радуешься так сильно, что почти не слышно, как немного жаль.",
 "her hand rising against the sun, her eyes following the white ribbons out the gate, her smile flickering"),
("A5_SH27",None,"classroom_hers_90s",
 "the empty summer classroom, chairs up on desks, the washed board holding only a date in the corner, the maple's green pressing at the tall windows",
 "WS","eye","pull_out","day",True,False,
 "летом класс пустеет, и только дата в углу доски помнит, что год был прожит не зря."),
("A5_SH28","LIDA_MID","village_kitchen",
 "the teacher visiting her mother, unpacking city medicines onto the village kitchen table, the mother's hand waving protest, the shawl slipping",
 "MS","eye","static","day",False,False,
 "лекарства маме ты всё равно покупаешь, просто теперь на это уходит вся первая половина лета.",
 "medicine boxes lining up one by one from the bag, her mother's hand batting weakly at the extravagance"),
("A5_SH29","MAMA_BASE","village_kitchen",
 "the aging mother holding her daughter's hand across the table, thumb moving over the amber ring, her eyes searching the tired younger face",
 "CU","eye","static","evening",False,False,
 "мама крутит кольцо на твоём пальце и спрашивает тихо, а своё-то у тебя когда будет, лида.",
 "her worn thumb turning the amber ring slowly, her eyes lifting from the ring to her daughter's face"),
("A5_SH30","LIDA_MID","village_kitchen",
 "the teacher answering with a light deflecting smile, gathering cups, the lamplight catching the grey strand at her temple",
 "MCU","eye","static","evening",False,False,
 "ты отвечаешь, мама, у меня своих семьдесят человек, и встаёшь мыть чашки раньше ответа.",
 "her smile deflecting lightly, her hands gathering cups in one practised sweep, her face turning to the basin"),
("A5_SH31",None,"village_street",
 "the settlement street at late dusk in summer, the mother's lit kitchen window and the sound-implied rattle of a treadle machine, moths around the lamp over the gate",
 "EWS","eye","static","evening",True,False,
 "мамина машинка стучит до темноты, в посёлке на слух знают, у кого какая старость."),
("A5_SH32","OBJ:chalk",None,
 "a september desk drawer sliding open on a fresh box of chalk, a red pen, and the softened squared-paper plan now lying face down at the back",
 "INSERT","top","push_in","morning",False,True,
 "в сентябре ящик стола встречает тебя новым мелом, а листок с планом лежит уже лицом вниз."),
]

seed_act("sugar",PAL4,SUGAR,render_mode="animated")
seed_act("gate",PAL5,GATE,render_mode="animated")
