# -*- coding: utf-8 -*-
"""cloakroom batch C: gallery_c (father+daughter + nouveau) + gallery_d (primas + gadalka cameo). static."""
from _cloakroom_engine import seed_act

PAL_C="tender amber yearly-ritual palette, warm soft brown and gold, a worn glow of small private occasions"
GC=[
 # --- B5 Отец и дочь раз в год ---
 ("GC_SH01",None,"street_cobble","the cobbled theatre square in early autumn, fallen leaves on the stones, the lit facade beyond","EWS","high","push_in","day",True,False,
  "каждый год в один и тот же день, в начале октября, к театру приходят эти двое."),
 ("GC_SH02","FATHER_MID","cloakroom_counter","a careworn father handing over two coats at the counter, a small girl at his side in a neat buttoned coat","MS","eye","static","day",False,False,
  "отец приводит дочь на её день рождения, раз в год, и это их единственный выход вдвоём."),
 ("GC_SH03",None,"cloakroom_counter","extreme close on a father's hands slowly buttoning the top button of a small child's coat","INSERT","high","push_in","day",False,True,
  "у стойки он застёгивает ей верхнюю пуговицу, медленно, как застёгивают самое дорогое на свете."),
 ("GC_SH04","DGTR_CHILD","foyer_marble","close on a delighted little girl's upturned face gazing at the chandeliers, mouth open","CU","low","static","day",False,False,
  "девочке семь, она впервые в театре, и смотрит на люстры, задрав голову и приоткрыв рот."),
 ("GC_SH05","CLOAK_MID","cloakroom_counter","the attendant gently taking the two coats, a child's and a father's, hanging them together","MCU","eye","static","day",False,False,
  "ты принимаешь их два пальто, детское и отцовское, и вешаешь рядом, как и полагается семье."),
 ("GC_SH06","FATHER_MID","auditorium","close on the father's tired tender face turned toward his daughter rather than the stage","CU","eye","push_in","day",False,False,
  "отец смотрит не на сцену, а на дочь, весь спектакль, и для него весь спектакль это она."),
 ("GC_SH07","DGTR_CHILD","auditorium","a small child kneeling up on a velvet seat to see the stage better, rapt","WS","high","static","day",False,False,
  "в зале она встаёт коленками на кресло, чтобы видеть, и он не делает ей ни одного замечания."),
 ("GC_SH08",None,"cloakroom_counter","extreme close on a small birthday ribbon pinned to a child's coat collar on a hook","INSERT","eye","push_in","day",False,False,
  "на воротнике её пальто маленький праздничный бант, и ты понимаешь, что сегодня её день рождения."),
 ("GC_SH09","FATHER_MID","cloakroom_counter","the father a year later buttoning the coat of a slightly taller girl, stooping a little more","MS","eye","static","day",False,False,
  "на следующий год она на голову выше, и пуговицу он застёгивает ей уже чуть нагибаясь к ней."),
 ("GC_SH10",None,"cloakroom_counter","extreme close on the same buttoning hands fastening a slightly larger coat","INSERT","high","push_in","day",False,False,
  "каждый год то же самое, тот же день, та же пуговица, и каждый раз пальто чуть больше прежнего."),
 ("GC_SH11","DGTR_TEEN","cloakroom_counter","close on a fifteen-year-old girl mildly self-conscious as her father buttons her coat in public","CU","eye","static","day",False,False,
  "ей пятнадцать, она уже стесняется, что отец застёгивает ей пуговицу при чужих, но всё же терпит."),
 ("GC_SH12","FATHER_MID","cloakroom_counter","the father continuing the ritual a little sadly, still seeing the seven-year-old in her","MCU","eye","static","day",False,False,
  "он это чувствует и всё равно застёгивает, потому что для него она по-прежнему та семилетняя девочка."),
 ("GC_SH13","DGTR_TEEN","auditorium","a teenage girl watching the stage, her father watching her from the next seat","WS","high","static","day",False,False,
  "в зале он по-прежнему смотрит на неё, а не на сцену, и ты по-прежнему видишь это от стойки."),
 ("GC_SH14","CLOAK_MID","cloakroom_counter","close on the attendant quietly moved, waiting for this one evening each year","CU","eye","push_in","day",False,False,
  "ты ждёшь этот один вечер в году, потому что в нём есть то, чего у тебя самого так и не случилось."),
 ("GC_SH15","FATHER_OLD","cloakroom_counter","years later, a bent frail old father entering on his grown daughter's arm","MCU","eye","static","day",False,False,
  "проходят годы, и однажды в начале октября отец входит согнутый, опираясь на её руку."),
 ("GC_SH16","FATHER_OLD","cloakroom_counter","the frail old father struggling with his coat, his hands no longer obeying the buttons","MCU","high","static","day",False,False,
  "теперь он еле снимает пальто, руки у него уже не слушаются, и пуговицы ему совсем не даются."),
 ("GC_SH17",None,"cloakroom_counter","extreme close on a grown woman's hands buttoning the top button of an old man's coat","INSERT","high","push_in","day",False,True,
  "и тогда дочь, уже взрослая, сама застёгивает ему верхнюю пуговицу, тем же самым медленным движением."),
 ("GC_SH18","DGTR_ADULT","cloakroom_counter","close on the adult daughter's caring face as she fastens her old father's coat, the ritual reversed","CU","eye","static","day",False,False,
  "ей тридцать, и она проделывает это так же бережно, как когда-то он проделывал это с ней."),
 ("GC_SH19","DGTR_ADULT","auditorium","the grown daughter now watching her dozing father rather than the stage","MS","eye","static","day",False,False,
  "теперь в зале она смотрит на него, а не на сцену, и круг, который ты видел тридцать лет, замкнулся."),
 ("GC_SH20","FATHER_OLD","street_cobble","the two leaving slowly across the autumn square, she supporting him under the arm","WS","high","track","dusk",False,False,
  "они уходят через площадь медленно, она ведёт его под руку, и листья падают им прямо под ноги."),
 ("GC_SH21","CLOAK_MID","stage_empty","the attendant at night buttoning the top button of an empty coat on stage with a slow tender gesture","CU","eye","push_in","night",False,False,
  "ночью ты застёгиваешь верхнюю пуговицу пустому пальто на сцене, тем самым отцовским медленным движением."),
 ("GC_SH22",None,"stage_empty","a child's small coat and a father's coat laid together on a chair on the dark stage","INSERT","eye","push_in","night",False,True,
  "ты кладёшь рядом детское и стариковское пальто, и пустой зал смотрит на целую жизнь между ними."),
 # --- B6 Нувориш транзита ---
 ("GC_SH23","NOUVEAU_BASE","cloakroom_counter","a heavyset newly-rich man in a camel overcoat shoving it across the rail, a heavy gold ring on his hand","MS","eye","static","dusk",False,False,
  "в девяностые приходит другой, грузный, в верблюжьем пальто, с тяжёлым перстнем на правой руке."),
 ("GC_SH24",None,"cloakroom_counter","extreme close on a heavy gold signet ring and the camel coat thrust across the counter","INSERT","top","push_in","dusk",False,True,
  "перстень золотой, во всю фалангу, и пальто кэмел, и он швыряет их тебе через стойку не глядя."),
 ("GC_SH25","NOUVEAU_BASE","cloakroom_counter","close on the man's florid impatient face demanding his coat ahead of the queue","CU","eye","static","dusk",False,False,
  "он требует своё пальто вперёд всей очереди и суёт тебе пятьдесят крон, чтобы ты подал ему первым."),
 ("GC_SH26","CLOAK_MID","cloakroom_counter","the attendant pocketing the note expressionlessly and serving the queue in order anyway","MCU","eye","static","dusk",False,False,
  "ты берёшь пятьдесят крон, киваешь и всё равно подаёшь по очереди, и он этого даже не замечает."),
 ("GC_SH27","NOUVEAU_BASE","foyer_marble","the man holding court loudly in the foyer so that everyone can hear him","WS","high","static","dusk",False,False,
  "в фойе он говорит громко, чтобы слышали все, и театр для него витрина, а вовсе не сцена."),
 ("GC_SH28",None,"cloakroom_counter","the costly camel coat hanging conspicuously among plainer coats on the hooks","INSERT","eye","push_in","dusk",False,False,
  "его пальто висит у тебя дороже всех на этой стене, и пахнет деньгами и резким одеколоном."),
 ("GC_SH29","NOUVEAU_BASE","cloakroom_counter","close on the man's face, a flicker of something hunted behind the bluster","CU","eye","push_in","dusk",False,False,
  "иногда сквозь его напор проступает что-то загнанное, будто он всё время ждёт стука в дверь."),
 ("GC_SH30","CLOAK_MID","cloakroom_counter","the attendant reading the man's fear under the wealth as he hangs the camel coat","MS","eye","static","dusk",False,False,
  "ты читаешь по его пальто не богатство, а страх, и понимаешь, что так очень долго не носят."),
 ("GC_SH31",None,"street_cobble","a black car idling outside the theatre on a winter night, exhaust in the cold air","WS","eye","static","night",True,False,
  "за ним у театра всегда ждёт чёрная машина, и однажды зимой она перестаёт приезжать совсем."),
 ("GC_SH32",None,"cloakroom_counter","the camel coat hanging unclaimed on its hook, a thin film of dust on the shoulders","INSERT","eye","push_in","night",False,True,
  "его кэмел остаётся у тебя невостребованным, один номерок без хозяина, до самой поздней весны."),
 ("GC_SH33","CLOAK_MID","cloakroom_counter","the attendant looking at the unclaimed camel coat each night, wondering","MCU","eye","static","night",False,False,
  "каждый вечер ты смотришь на это пальто и не знаешь, сел он, сбежал или его уже нет на свете."),
 ("GC_SH34","CLOAK_MID","cloakroom_counter","close on the attendant's quiet verdict, hands on the brass rail","CU","eye","push_in","night",False,False,
  "и ты думаешь, что можно швырять кроны и требовать первым, а кончить номерком, за которым не придут."),
 ("GC_SH35","CLOAK_MID","backstage_lost","the attendant carrying the camel coat to the crowded lost-property rail backstage","WS","eye","track","night",False,False,
  "весной ты переносишь его пальто на вешалку забытых вещей, к десяткам других ничьих жизней."),
 ("GC_SH36","CLOAK_MID","stage_empty","the attendant at night in the camel coat playing the loud nouveau to the dark seats","MCU","low","static","night",False,False,
  "ночью ты надеваешь его кэмел и играешь его, громкого, с перстнем, что боялся каждого шороха."),
 ("GC_SH37","CLOAK_MID","stage_empty","close on the attendant's face playing the nouveau, the fear showing under the bluster","CU","eye","push_in","night",False,False,
  "ты требуешь у пустого зала пальто вперёд очереди и слышишь в собственном шёпоте чужой ужас."),
 ("GC_SH38",None,"stage_empty","the camel coat draped over the ghost-light stand on the empty stage","INSERT","low","push_in","night",False,False,
  "ты вешаешь кэмел на дежурную лампу, и он висит, как флаг страны, которой больше уже нет."),
]

PAL_D="faded gilt palette, tarnished gold and powder, old perfume and dimming chandeliers, wistful and grand"
GD=[
 # --- B7 Две бывшие примы ---
 ("GD_SH01",None,"auditorium","the tiered gilded velvet boxes of the auditorium, dim and grand, once full of admirers","EWS","low","tilt_up","dusk",True,False,
  "две бывшие примы теперь сидят в зале, там, где когда-то на них смотрел весь город."),
 ("GD_SH02","DIVAA_BASE","cloakroom_counter","a grand old actress in a fox-fur stole handing it across the counter, theatrical and proud","MS","eye","static","dusk",False,False,
  "первая прима сдаёт тебе лисью горжетку со стеклянными глазами, и пахнет старыми театральными духами."),
 ("GD_SH03",None,"cloakroom_counter","extreme close on a fox-fur stole with small glass eyes draped on a hook","INSERT","eye","push_in","dusk",False,True,
  "у горжетки маленькие стеклянные глаза, и они смотрят на тебя честнее, чем все, кто тут бывал."),
 ("GD_SH04","DIVAB_BASE","cloakroom_counter","close on the second former prima, powdered and proud, chin lifted as on her old posters","CU","eye","static","dusk",False,False,
  "вторая прима, в такой же горжетке, подкрашена и горда, и держит подбородок, как держала с афиш."),
 ("GD_SH05","CLOAK_MID","cloakroom_counter","the attendant taking both fox stoles, the same perfume rising from them","MCU","eye","static","dusk",False,False,
  "ты принимаешь обе горжетки, и от них одни и те же духи, которыми когда-то пах весь этот театр."),
 ("GD_SH06","DIVAA_BASE","auditorium","the two primas in their velvet seats whispering together through the performance","WS","high","static","dusk",False,False,
  "в зале они шепчутся весь спектакль, чей нынче выход и чей хуже, чем был когда-то у них."),
 ("GD_SH07","DIVAB_BASE","auditorium","close on one prima's catty delighted whisper behind a jewelled hand","CU","eye","push_in","dusk",False,False,
  "они разбирают молодую актрису по косточкам и тихо радуются, что играли когда-то намного лучше."),
 ("GD_SH08",None,"cloakroom_counter","two fox stoles hanging side by side on the hooks, glass eyes catching the lamplight","INSERT","eye","push_in","dusk",False,False,
  "их горжетки висят у тебя рядом, голова к голове, как они сами полвека сидели в одной гримёрке."),
 ("GD_SH09","DIVAA_BASE","cloakroom_counter","after the show the first prima pausing at the counter, peering closely at the attendant's face","MS","eye","static","night",False,False,
  "после спектакля первая прима вдруг задерживается у стойки и пристально всматривается в твоё лицо."),
 ("GD_SH10","DIVAA_BASE","cloakroom_counter","close on the prima's eyes narrowing as recognition slowly dawns","CU","eye","push_in","night",False,False,
  "она щурится и называет твою фамилию, ту, что стояла первой в списке на главную роль, давно."),
 ("GD_SH11","CLOAK_MID","cloakroom_counter","close on the attendant frozen, named by his surname after thirty silent years","CU","eye","static","night",False,False,
  "ты застываешь, потому что тебя не называли по фамилии тридцать лет, и ты забыл уже, как это звучит."),
 ("GD_SH12","DIVAA_BASE","cloakroom_counter","the prima remembering him from the acting school, the promise he once was","MCU","eye","static","night",False,False,
  "она помнит тебя с училища, помнит твой голос, и спрашивает, отчего ты так и не вышел на сцену."),
 ("GD_SH13","CLOAK_MID","cloakroom_counter","close on the attendant touching his throat, unable to explain, only a rasp","CU","eye","push_in","night",False,False,
  "ты касаешься горла и сипишь в ответ, и ей всё становится ясно без слов, и она отводит глаза."),
 ("GD_SH14","DIVAB_BASE","cloakroom_counter","the second prima gently drawing the first away from the counter","MS","eye","static","night",False,False,
  "вторая прима мягко уводит её, и они уходят, и ты остаёшься со своей фамилией, сказанной вслух."),
 ("GD_SH15","CLOAK_MID","foyer_marble","the attendant standing alone in the foyer afterward holding a fox stole, the named man","WS","high","static","night",False,False,
  "ты долго стоишь, держа в руках чужую горжетку, и фамилия твоя ещё гудит у тебя в голове."),
 ("GD_SH16","CLOAK_MID","cloakroom_counter","close on the attendant's face, the rare wound of being remembered","CU","eye","push_in","night",False,False,
  "хуже забвения только одно, это когда тебя вдруг вспомнят тем, кем ты так и не стал."),
 ("GD_SH17",None,"cloakroom_counter","extreme close on a yellowed acting-school cast-list with a name first on it, kept in a drawer","INSERT","top","push_in","night",False,True,
  "ты достаёшь из ящика пожелтевший список, где твоя фамилия первая, и снова прячешь его подальше."),
 ("GD_SH18","CLOAK_MID","stage_empty","the attendant at night playing both gossiping primas at once with borrowed grand voices","MCU","eye","static","night",False,False,
  "ночью ты играешь обеих прим разом, как они шепчутся, чей выход хуже, двумя чужими голосами."),
 ("GD_SH19","CLOAK_MID","stage_empty","close on the attendant lifting his chin like a diva, addressing the dark house","CU","low","static","night",False,False,
  "ты задираешь подбородок их жестом и говоришь пустому залу, что когда-то и тебя знал весь город."),
 ("GD_SH20",None,"stage_empty","two fox stoles laid on two chairs on the dark stage, their glass eyes glinting","INSERT","eye","push_in","night",False,False,
  "ты кладёшь две горжетки на два стула, и стеклянные глаза смотрят, как ты играешь то, что мог прожить."),
 ("GD_SH21",None,"auditorium","the empty gilded boxes where the two primas once starred, dust in the dim light","WS","low","static","night",True,True,
  "а наверху пустуют ложи, и ты думаешь, что слава тут не спасает, она просто потом дольше падает."),
 ("GD_SH22","CLOAK_MID","cloakroom_counter","the attendant by day smoothing a fur stole on its hook with his palm","MCU","eye","static","day",False,False,
  "днём ты снова разглаживаешь чужие меха ладонью и держишь крючок номер один пустым, как всегда."),
 # --- B8 Камео Гадалка (fortune/ZARA) ---
 ("GD_SH23","ZARA_YOUNG","cloakroom_counter","a striking woman in layered colourful shawls handing over a wrap, a moonstone ring on her right hand","MS","eye","static","dusk",False,False,
  "однажды приходит женщина в слоистых цветных шалях, с кольцом из лунного камня на правой руке."),
 ("GD_SH24",None,"cloakroom_counter","extreme close on a moonstone ring on a hand beside a worn tarot deck","INSERT","top","push_in","dusk",False,True,
  "на правой руке у неё лунный камень, а в другой потрёпанная колода карт, и ты читаешь её сразу."),
 ("GD_SH25","ZARA_YOUNG","cloakroom_counter","close on the fortune-teller's kohl-lined eyes and gold hoop earrings, knowing and amused","CU","eye","static","dusk",False,False,
  "ты видишь по шалям и кольцам гадалку, что живёт с чужого страха, и не веришь ей ни на грош."),
 ("GD_SH26","CLOAK_MID","cloakroom_counter","the attendant taking her colourful wrap, politely sceptical","MCU","eye","static","dusk",False,False,
  "ты принимаешь её пёструю накидку вежливо, как принимаешь любой реквизит чужого ремесла."),
 ("GD_SH27","ZARA_YOUNG","cloakroom_counter","the fortune-teller catching the attendant's hand and turning it to the lamplight to read it","CU","eye","push_in","dusk",False,False,
  "но она вдруг ловит твою ладонь, поворачивает её к свету и говорит, что твоё имя ещё назовут."),
 ("GD_SH28","CLOAK_MID","cloakroom_counter","close on the attendant startled, an old wound touched by her words","CU","eye","static","dusk",False,False,
  "ты вздрагиваешь, потому что именно этого ты и ждёшь у своей стойки всю свою жизнь, чтобы назвали."),
 ("GD_SH29","ZARA_YOUNG","cloakroom_counter","the fortune-teller smiling as the moonstone catches the lamplight","MCU","eye","static","dusk",False,False,
  "она улыбается, лунный камень ловит свет лампы, и она говорит, что зал у тебя уже есть, свой."),
 ("GD_SH30",None,"cloakroom_counter","extreme close on a single tarot card laid face-down on the wooden counter","INSERT","top","push_in","dusk",False,True,
  "она кладёт на стойку одну карту рубашкой вверх и просит её не переворачивать, и уходит в зал."),
 ("GD_SH31","CLOAK_MID","cloakroom_counter","close on the attendant staring at the face-down card all evening, not daring to turn it","CU","eye","push_in","night",False,False,
  "ты весь вечер смотришь на эту карту и не решаешься перевернуть, потому что вдруг там пусто."),
 ("GD_SH32","ZARA_YOUNG","foyer_marble","the fortune-teller leaving across the foyer, her shawls trailing, refusing her change","MS","eye","static","night",False,False,
  "она забирает накидку, не берёт сдачи и говорит, что ты обманываешь зал не больше, чем она сама."),
 ("GD_SH33","CLOAK_MID","cloakroom_counter","close on the attendant, the mirror of two gentle frauds settling on him","CU","eye","push_in","night",False,False,
  "и тебе нечего ей возразить, потому что вы оба даёте людям роль, которой у них нет."),
 ("GD_SH34",None,"stage_empty","a single tarot card laid face-down on an empty velvet seat in the front row, seen from the stage","INSERT","eye","push_in","night",False,False,
  "ночью ты выносишь её карту на сцену и кладёшь рубашкой вверх на пустое кресло в первом ряду."),
 ("GD_SH35","CLOAK_MID","stage_empty","the attendant at night playing the fortune-teller, promising the dark house a future","MCU","eye","static","night",False,False,
  "ты играешь её, гадалку, что обещает чужое будущее, и слышишь, как обещаешь будущее себе."),
 ("GD_SH36","CLOAK_MID","stage_empty","close on the attendant almost believing the prophecy for a moment under the ghost-light","CU","eye","push_in","night",False,True,
  "и на миг ты веришь, что имя твоё ещё назовут, и этого мига тебе хватает, чтобы доиграть до конца."),
]

seed_act("gallery_c", PAL_C, GC, render_mode="static")
seed_act("gallery_d", PAL_D, GD, render_mode="static")
