# -*- coding: utf-8 -*-
"""kept_woman A8 eject + A9 loss. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_kept_woman_A8A9.py"""
from _kept_woman_engine import seed_act

P_EJECT="cold subtracting palette, bleached marble white draining to grey, flat hard daylight losing warmth"
P_LOSS="hollow grief palette, wet grey and washed black, cold colourless overcast light"

EJECT=[
 ("A8_SH01",None,"penthouse_apartment","a wide night view of a high-floor luxury apartment interior with a glittering skyline beyond, cold and beautiful and unstable","WS","eye","push_in","night",True,False,
  "в сорок у тебя ещё есть покровитель и красивая квартира, но ты уже чувствуешь, как земля уходит."),
 ("A8_SH02","VIKA_OLD","penthouse_apartment","a medium shot of the woman of forty-three standing alone in a cold expensive apartment, holding a silent phone","MS","eye","static","night",False,False,
  "твой последний мужчина всё реже приезжает и всё дольше молчит в телефон, и ты знаешь, что это значит."),
 ("A8_SH03",None,"penthouse_apartment","a medium close-up of a well-dressed older man standing coolly by an apartment window, delivering cold news","MCU","over","static","day",True,False,
  "однажды он приходит и говорит, что встретил другую, и что квартиру придётся освободить до конца месяца."),
 ("A8_SH04","VIKA_OLD","penthouse_apartment","a close-up of the woman receiving the blow without a scene, a composed frozen dignity","CU","eye","push_in","day",False,False,
  "ты не устраиваешь сцен, Лера учила уходить с достоинством, только достоинство теперь всё, что у тебя есть."),
 ("A8_SH05","RIVAL_BASE","penthouse_apartment","a medium close-up of a fresh radiant young woman of twenty-four with dark auburn hair and glowing skin, hopeful in the doorway","MCU","eye","static","day",False,False,
  "её зовут иначе, но это ты в девятнадцать, те же широкие глаза, та же дешёвая надежда на золото."),
 ("A8_SH06","VIKA_OLD","penthouse_apartment","a close-up of the older woman looking at the young replacement, wanting to warn her","CU","eye","push_in","day",False,False,
  "ты смотришь на неё и хочешь предупредить, но и тебя когда-то никто не сумел отговорить."),
 ("A8_SH07","VIKA_OLD","penthouse_apartment","a wide shot of the woman packing belongings in the half-emptied luxury apartment, boxes on the marble floor","WS","high","static","day",False,False,
  "ты собираешь вещи в квартире, которая никогда не была твоей, и вдруг видишь, как мало у тебя своего."),
 ("A8_SH08",None,None,"an extreme close-up macro insert of expensive handbags and shoe boxes packed into moving boxes, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "двадцать восемь дорогих сумок, гора обуви, и ни одной фотографии, ни одного письма, ни одной живой памяти."),
 ("A8_SH09","VIKA_OLD","penthouse_apartment","a medium shot of the woman setting keys down on a marble counter and turning to leave","MS","eye","static","day",False,False,
  "ты кладёшь ключи на стойку, как клала когда-то надежды, и выходишь из красивой жизни навсегда."),
 ("A8_SH10",None,None,"an extreme close-up macro insert of a set of apartment keys left on a marble counter, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "на мраморной стойке остаются ключи, которых у тебя всё равно никогда по-настоящему не было."),
 ("A8_SH11","VIKA_OLD",None,"a wide shot of the woman climbing into a plain ordinary taxi packed with cardboard boxes on a grey street","WS","eye","static","day",False,False,
  "ты садишься в такси, набитое коробками, и в последний раз слышишь тот самый щелчок замка."),
 ("A8_SH12",None,None,"an extreme close-up macro insert of a plain worn car-door lock latch dropping shut in an ordinary taxi, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "только теперь этот щелчок не запирает тебя в роскоши, а просто везёт в чужую съёмную комнату."),
 ("A8_SH13","VIKA_OLD","rented_studio","a wide shot of the woman standing in the doorway of a cramped rented studio crowded with her expensive things","WS","low","push_in","day",False,False,
  "в сорок один ты переезжаешь в съёмную студию, одну комнату, где твои сумки занимают больше места, чем ты."),
 ("A8_SH14","VIKA_OLD","rented_studio","a medium shot of the woman hanging designer handbags along a rail on a cheap wall in the little studio","MS","eye","static","day",False,False,
  "ты развешиваешь сумки вдоль стены, как трофеи войны, которую, оказывается, ты всё это время проигрывала."),
 ("A8_SH15",None,None,"an extreme close-up macro insert of expensive handbags hanging on a cheap wall rail in a poor room, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "дорогие сумки на дешёвой стене выглядят нелепо, как ты сама выглядишь в этой чужой комнате."),
 ("A8_SH16","VIKA_OLD","rented_studio","a close-up of the woman taking stock of her empty life in the little studio, a bleak clarity","CU","eye","push_in","day",False,False,
  "в сорок один у тебя нет ни мужа, ни детей, ни профессии, ни пенсии, ни одного близкого человека."),
 ("A8_SH17","VIKA_OLD","rented_studio","a medium shot of the woman standing at the small studio window over a grey courtyard","MS","eye","static","day",False,False,
  "есть только красота, которая почти кончилась, и вещи, которые никому, кроме тебя, уже не нужны."),
 ("A8_SH18",None,"rented_studio","a wide view from a small window onto an ordinary courtyard where plain people go about ordinary lives, grey daylight","WS","high","static","day",True,False,
  "за окном обычный двор, обычные люди с обычной, некрасивой, но своей жизнью, которой у тебя нет."),
 ("A8_SH19","VIKA_OLD","rented_studio","a medium close-up of the woman sitting on the narrow bed trying to count something and losing the number","MCU","eye","static","day",False,False,
  "ты пробуешь считать, сколько мужчин прошло за двадцать два года, и сбиваешься, и это не стыдно, а пусто."),
 ("A8_SH20","VIKA_OLD","rented_studio","a close-up of the woman's tired face as she realizes she has run out of people to call","CU","eye","static","day",False,False,
  "ни один из них не помнит твоего имени, и ни к одному ты не можешь прийти и попросить о помощи."),
 ("A8_SH21",None,None,"an extreme close-up macro insert of a thin gold chain around an older woman's bare ankle in dim room light, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "на щиколотке всё та же цепочка, единственное, что осталось с того первого вечера двадцать два года назад."),
 ("A8_SH22","VIKA_OLD","rented_studio","a medium close-up of the woman sitting on a narrow bed among expensive bags, lost and still","MCU","eye","push_in","day",False,True,
  "ты садишься на узкую кровать среди чужого золота и впервые за жизнь не знаешь, что делать дальше."),
]

LOSS=[
 ("A9_SH01","VIKA_OLD","rented_studio","a medium shot of the woman of forty-three standing frozen with a phone to her ear in the little studio","MS","eye","static","day",False,False,
  "в сорок три тебе звонят из посёлка и говорят, что мать умерла ночью, одна, во сне."),
 ("A9_SH02","VIKA_OLD","rented_studio","a close-up of the woman sinking down among her bags as the news lands","CU","eye","push_in","day",False,False,
  "ты садишься на пол среди сумок, и до тебя доходит, что последний любивший тебя человек ушёл."),
 ("A9_SH03","VIKA_OLD","bus_station","a wide shot of the woman in an expensive black coat boarding an intercity coach at a shabby platform","WS","low","static","day",False,False,
  "ты снова едешь в тот автобус, только теперь навсегда опоздала сказать матери правду."),
 ("A9_SH04",None,"cemetery","a wide view of a modest provincial cemetery under bare trees, a fresh earth mound with a plain temporary marker, grey sky","WS","eye","push_in","day",True,False,
  "на кладбище под голыми деревьями свежий холмик и простой временный крест, и почти никого вокруг."),
 ("A9_SH05","VIKA_OLD","cemetery","a medium shot of the woman standing at a fresh grave in an expensive black coat, out of place among plain mourners","MS","eye","static","day",False,False,
  "ты стоишь у могилы в дорогом чёрном пальто, и соседки шепчутся, что дочь-то, видать, богатая."),
 ("A9_SH06","VIKA_OLD","cemetery","a close-up of the woman's grieving face at the graveside in cold grey light","CU","eye","push_in","day",False,False,
  "а ты стоишь и думаешь, что отдала бы все эти сумки за один честный разговор с ней."),
 ("A9_SH07",None,None,"an extreme close-up macro insert of a faded floral cardigan and reading glasses on a beaded cord folded together, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "тебе отдают её вещи, выцветший кардиган и очки на шнурке, и это всё её наследство."),
 ("A9_SH08","VIKA_OLD","cemetery","a medium shot of the woman standing alone at the grave after the others have gone","MS","eye","static","day",False,False,
  "мать так и не узнала, кем ты была, и теперь ты рада хотя бы этому, единственному."),
 ("A9_SH09",None,"cemetery","a wide view of a bleak provincial cemetery, plastic flowers on wet clay under a low grey sky, silent and still","WS","high","static","day",True,False,
  "серое небо, мокрая глина, пластиковые цветы, и тишина, в которой некому больше врать."),
 ("A9_SH10","VIKA_OLD","rented_studio","a medium shot of the woman back in the studio deciding to sell her handbags, laying them out on the bed","MS","eye","static","day",False,False,
  "вернувшись, ты решаешь продать сумки, потому что деньги кончились, а работать ты так и не научилась."),
 ("A9_SH11",None,"rented_studio","a medium close-up of a bored second-hand buyer examining a luxury handbag with a loupe, dismissive and unimpressed","MCU","over","static","day",True,False,
  "скупщик вертит их в руках и называет цену, за которую ты когда-то не купила бы и одной."),
 ("A9_SH12",None,None,"an extreme close-up macro insert of a used luxury handbag with a small low resale price sticker, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "оказывается, чужие подарки почти ничего не стоят, как только сходит блеск новизны."),
 ("A9_SH13","VIKA_OLD","rented_studio","a close-up of the woman's bitter face understanding what her collection is really worth","CU","eye","push_in","day",False,False,
  "двадцать два года ты собирала золото, которое в один день превратилось в кучу ненужного старья."),
 ("A9_SH14","VIKA_OLD","rented_studio","a medium shot of the woman selling off most bags and keeping only a couple on the rail","MS","eye","static","day",False,False,
  "ты продаёшь почти всё за бесценок и оставляешь пару сумок, чтобы хоть что-то напоминало о той жизни."),
 ("A9_SH15",None,"rented_studio","a wide view of a nearly empty wall rail with bare hooks in a poor rented room, grey light","WS","eye","static","day",True,False,
  "стена пустеет, крючки без сумок торчат голо, и комната становится ещё более чужой."),
 ("A9_SH16","VIKA_OLD","rented_studio","a medium close-up of the woman of forty-three sitting hollow in the emptying studio","MCU","eye","static","day",False,False,
  "в сорок три у тебя не осталось ни матери, ни денег, ни красоты, за которую платили."),
 ("A9_SH17","VIKA_OLD","rented_studio","a close-up of the woman looking down toward her ankle, a quiet exhaustion","CU","eye","static","day",False,False,
  "есть только ты, узкая кровать и цепочка на щиколотке, которую ты почему-то так и не сняла."),
 ("A9_SH18",None,None,"an extreme close-up macro insert of a thin gold chain around a bare ankle catching dim dusk light, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","dusk",True,True,
  "золото на щиколотке тускло блестит в сумерках, последний свидетель того, с чего всё началось."),
]

if __name__=="__main__":
    seed_act("eject", P_EJECT, EJECT, render_mode="static")
    seed_act("loss",  P_LOSS,  LOSS,  render_mode="static")
