# -*- coding: utf-8 -*-
"""lottery expansion wave — interleaved beats (letter-suffix codes), id_region='b'.
PYTHONIOENCODING=utf-8 python scripts/_seed_lottery_expand.py"""
from _lottery_engine import seed_act

ACTS=[
 ("cold_open","dawn shift palette, cold blue morning steel warmed by sodium checkpoint light, worn and settled",[
  ("A0_SH03B",None,"factory_gate","a wide view of the worker queue at the turnstiles, thermoses and tool bags, easy morning talk","WS","eye","static","dawn",True,False,
   "в очереди смены говорят про хоккей и рассаду, и никто не говорит про деньги."),
  ("A0_SH06B","HERO_BACK","factory_shop","a medium shot of the man walking his aisle past an honour board with faded photo slots","MS","eye","track","day",False,False,
   "ты идёшь к своему пролёту мимо доски почёта, на которой когда-то висел."),
  ("A0_SH08B",None,None,"an extreme close-up insert of workman's hands settling onto a lathe bed with familiar weight","ECU","eye","static","day",True,False,
   "ладони ложатся на станину привычно, как ключ в замок, который никто не менял."),
  ("A0_SH11B","HERO_BACK","factory_shop","a medium close-up of the man lowering safety glasses, the world narrowing to the work","MCU","eye","static","day",False,False,
   "ты надеваешь защитные очки, и мир сужается до детали, резца и допуска."),
 ]),
 ("origin","nineties flashback palette, faded newsprint grey and warm kiosk amber, nostalgic worn browns",[
  ("A1_SH01B",None,None,"an extreme close-up insert of two pairs of work boots striding in step on cracked pavement","ECU","low","track","day",True,False,
   "у вас с отцом одинаковый шаг, и соседи по двору зовут вас «наладчики»."),
  ("A1_SH04B",None,"kiosk","a wide view of a small Friday queue of workmen at the kiosk window, coins ready","WS","eye","static","day",True,False,
   "у киоска по пятницам своя очередь: такие же работяги с пятёрками наготове."),
  ("A1_SH06B",None,None,"an extreme close-up insert of a grey nineties lottery slip with a number grid, held like a document","ECU","eye","static","day",True,False,
   "билет девяносто восьмого — серая бумажка с сеткой чисел, а держат её, как документ."),
  ("A1_SH07B",None,"khrush_kitchen","a wide view of the Sunday-evening kitchen, tea and a spread newspaper, laughter around the table","WS","eye","static","evening",True,False,
   "воскресный вечер устроен так: чай, газета, сверка, и вся кухня смеётся над вашей биржей."),
  ("A1_SH09B","HERO_YOUNG","city_street","a close-up of the eighteen-year-old's easy grin under a streetlight, collar up","CU","eye","push_in","evening",False,False,
   "тебе восемнадцать, у тебя вся жизнь впереди, и пять рублей кажутся смешными деньгами."),
  ("A1_SH10B","FATHER_BASE","khrush_kitchen","a medium close-up of the flat-capped father with his tea at the window, content and unhurried","MCU","eye","static","evening",False,False,
   "он доработает до пенсии, вырастит тебя в наладчики и будет этим горд вслух."),
  ("A1_SH11B",None,"city_street","a wide view of the same street two decades on, plastic windows and new signs, the old kiosk unchanged","WS","eye","pan_right","day",True,False,
   "город за двадцать четыре года переоденется в стеклопакеты, а киоск переживёт всех."),
  ("A1_SH12B",None,None,"an extreme close-up insert of a modern lottery ticket sliding into a work jacket's chest pocket","ECU","eye","static","day",True,False,
   "билет за сто пятьдесят ложится в нагрудный карман, туда же, куда у отца."),
 ]),
 ("win","ordinary-life palette, warm kitchen bulb and workshop steel, one sudden gold accent cutting through",[
  ("A2_SH02B",None,"factory_shop","a wide view of the man's section running smooth, apprentices at neighbouring machines glancing over","WS","eye","static","day",True,False,
   "на участке ты главный по точности, и брак у смены падает, когда ты в графике."),
  ("A2_SH04B",None,None,"an extreme close-up insert of big headphones hung on a hallway hook beside a school backpack","ECU","eye","static","evening",True,False,
   "Максим в свои пятнадцать разговаривает наушниками, но борщ ест, не снимая улыбки."),
  ("A2_SH07B",None,None,"an extreme close-up insert of a ticket corner peeking from a work jacket chest pocket on a locker hook","ECU","eye","static","day",True,False,
   "всю неделю билет ездит с тобой на смену и обратно, забытый, как проездной."),
  ("A2_SH10B",None,"khrush_kitchen","a wide view of the small living room, the TV playing to an empty armchair, draw drums spinning","WS","eye","static","evening",True,False,
   "в комнате работает телевизор для никого, и барабан крутится уже следующему счастливцу."),
  ("A2_SH12B","HERO_WORK","khrush_kitchen","a medium close-up of the machinist lowering himself onto a stool in the middle of the kitchen","MCU","eye","static","evening",False,False,
   "ты садишься на табурет посреди кухни, потому что ноги решают сесть сами."),
  ("A2_SH14B",None,"khrush_kitchen","a wide view of an ordinary weekday breakfast, three cups, sugar spilled beside one of them","WS","high","static","day",True,False,
   "утром вы завтракаете, как обычно, только сахар в чай кладёте мимо чашки."),
  ("A2_SH16B","TANYA_BASE","khrush_kitchen","a medium close-up of the braided woman writing a short careful list, then setting the pen down","MCU","eye","static","evening",False,False,
   "Таня пишет на листке скромный список: ипотека, зубы маме, море, и откладывает ручку."),
  ("A2_SH18B",None,"city_street","a wide view of the evening street, a man's silhouette passing the same entrance twice","WS","eye","static","evening",True,False,
   "по дороге домой ты дважды проходишь мимо своего подъезда, забыв, где живёшь."),
  ("A2_SH20B",None,"khrush_kitchen","a wide view of the dark kitchen with two figures at the table, one lamp, lowered voices","WS","eye","static","night",True,False,
   "вы решаете пока никому не говорить, и это единственное решение, которое окажется верным."),
  ("A2_SH21B","HERO_WORK","city_street","a medium close-up of the man walking with a palm held flat over his chest pocket","MCU","eye","track","day",False,False,
   "билет уезжает в офис лотереи в кармане у груди, и карман ты придерживаешь ладонью."),
 ]),
 ("fire_bridges","new-money palette, showroom white and champagne gold over glass, glossy and slightly cold",[
  ("A3_SH02B",None,"factory_shop","a wide view of the shop gone quiet mid-shift, faces turned toward one man at the foreman's door","WS","eye","static","day",True,False,
   "новость про выигрыш добегает до цеха за перекур, и у станков становится тихо."),
  ("A3_SH04B",None,None,"an extreme close-up insert of a restaurant reservation book open on a full-page booking","ECU","top","static","day",True,False,
   "ресторан ты бронируешь целиком, впервые в жизни произнося слово «полностью» в трубку."),
  ("A3_SH06B",None,"restaurant","a wide view of the long table mid-toast, glasses up, half the faces unfamiliar to the host","WS","eye","static","night",True,False,
   "тосты за тебя поднимают люди, половину которых ты видишь второй раз в жизни."),
  ("A3_SH07B",None,None,"an extreme close-up insert of a six-figure price tag hanging from a cashmere sleeve","ECU","eye","static","day",True,False,
   "на ценнике пальто шесть цифр, и ты больше не переводишь их в зарплаты."),
  ("A3_SH09B",None,"city_street","a wide view of a glass car showroom at dusk, one customer attended by a quiet ring of staff","WS","eye","static","evening",True,False,
   "в автосалоне тебя обслуживают, как хирурга перед операцией: тихо, быстро и с уважением."),
  ("A3_SH10B",None,None,"an extreme close-up insert of workman's hands with an old milling scar resting on a leather steering wheel","ECU","top","static","day",True,False,
   "руки на руле те же, со шрамом от фрезы, и это пока единственное прежнее."),
  ("A3_SH12B",None,"penthouse","a wide view of four modest cardboard boxes lost in the middle of a vast designer living room","WS","eye","static","day",True,False,
   "вещей из хрущёвки набирается на четыре коробки, и в пентхаусе они теряются, как туристы."),
  ("A3_SH13B","TANYA_BASE","penthouse","a medium shot of the braided woman at the induction hob, steam rising from a familiar pot","MS","eye","static","evening",False,False,
   "борщ на индукции выходит тот же, и это единственная комната, где пахнет домом."),
  ("A3_SH14B","HERO_RICH","penthouse","a medium close-up of the man with an untouched whisky beside a finished cup of tea","MCU","eye","static","night",False,False,
   "ты наливаешь себе дорогой виски, который советовали, а допиваешь всё равно чай, который привык."),
  ("A3_SH16B",None,"penthouse","a wide view of the night living room, the gilded frame catching the city glow opposite the glass wall","WS","low","static","night",True,False,
   "рамка с билетом висит напротив окон, и по ночам в её стекле горит город."),
 ]),
 ("vultures","pressed-upon palette, doorbell yellow and hallway grey, too many coats in the light, crowded warm-cold",[
  ("A4_SH01B",None,None,"an extreme close-up insert of an intercom panel with a finger hovering over the call button","ECU","eye","static","day",True,False,
   "домофон звонит теперь чаще телефона, и консьерж внизу выучил слово «передайте» наизусть."),
  ("A4_SH03B",None,"penthouse","a wide view of tea with the brother on the white sofa, his eyes drifting to the gilded frame","WS","eye","static","day",True,False,
   "Витя рассказывает про автомойку сорок минут, и все сорок минут смотрит на рамку с билетом."),
  ("A4_SH05B","HERO_RICH","penthouse","a medium close-up of the man at the glass wall after the door has closed, replaying the visit","MCU","eye","static","evening",False,False,
   "вечером до тебя доходит, что ты не спросил ни адреса мойки, ни сроков."),
  ("A4_SH06B",None,None,"an extreme close-up insert of four untouched cake boxes stacked in a huge empty fridge","ECU","eye","static","day",True,False,
   "тортов в холодильнике скапливается четыре штуки: с ними приходят, но их не едят."),
  ("A4_SH08B",None,"city_street","a wide view of the upscale entrance with one patient figure holding a folder by the door","WS","eye","static","day",True,False,
   "по субботам под подъездом дежурит человек с папкой «инвестиции в блокчейн» и ждёт."),
  ("A4_SH10B","HERO_RICH","restaurant","a medium shot of the host slumped back at the loud table, smile worn to the metal","MS","eye","static","night",False,False,
   "ты начинаешь уставать от этих застолий сильнее, чем уставал когда-то от смен."),
  ("A4_SH11B",None,"penthouse","a wide view of the dark quiet living room, a phone face-down on the marble, city lights beyond","WS","eye","static","night",True,False,
   "в выключенном телефоне тихо, и эта тишина — первая покупка, которая тебе действительно нравится."),
  ("A4_SH13B","TANYA_BASE","penthouse","a medium close-up of the braided woman speaking evenly over a cooling cup","MCU","eye","static","evening",False,False,
   "Таня говорит про Витю без злости: он не вор, он просто слабый, как все они."),
  ("A4_SH15B",None,"city_street","a wide view of the autumn street, leaves down the gutter, the entrance clear of visitors at last","WS","eye","pan_left","day",True,False,
   "к осени просители редеют: у денег, как у мёда, есть сезон, и он проходит."),
  ("A4_SH16B","HERO_RICH","penthouse","a medium close-up of the man closing the squared notebook and squaring it away in a drawer","MCU","eye","static","evening",False,False,
   "блокнот ты убираешь в ящик и решаешь, что деньги пора не раздавать, а вложить."),
 ]),
 ("partner","promised-return palette, blueprint blue and banner gloss over raw earth brown, persuasive and hollow",[
  ("A5_SH01B",None,None,"an extreme close-up insert of an embossed recommendation card propped against a coffee cup","ECU","eye","static","evening",True,False,
   "рекомендация исходит от людей, у которых ты был на юбилее, и это заменяет проверку."),
  ("A5_SH02B",None,"restaurant","a wide view of the discreet corner table, two men and one folder, waiters keeping distance","WS","eye","static","evening",True,False,
   "он не просит денег, и это первое, что подкупает: все просили, он предлагает."),
  ("A5_SH04B",None,None,"an extreme close-up insert of three figures written on a napkin with a heavy fountain pen","ECU","top","static","evening",True,False,
   "на салфетке он пишет три цифры, и сорок процентов выглядят на ней, как закон природы."),
  ("A5_SH06B",None,"pit","a wide view of the luxury SUV rolling slowly along the site fence, banner renders sliding past the glass","WS","eye","track","day",True,False,
   "вы объезжаете площадку на твоём кайене, и Аркадий говорит о ней «наша земля»."),
  ("A5_SH08B","ARKADIY_BASE","pit","a medium close-up of the white-scarfed man pressing an investor sticker onto a folder with ceremony","MCU","eye","static","day",False,False,
   "наклейку «инвестор» на папку клеит сам Аркадий, торжественно, как орден на грудь."),
  ("A5_SH09B",None,None,"an extreme close-up insert of a phone photographing an excavator bucket lifting the first earth","ECU","pov","static","day",True,False,
   "первый ковш земли ты фотографируешь на телефон, как когда-то фотографировал новорождённого Максима."),
  ("A5_SH11B","HERO_RICH","penthouse","a medium close-up of the man reading a glossy report over tea, lips moving on the fine print","MCU","eye","static","evening",False,False,
   "в отчётах есть слова «освоение» и «динамика», и нет слов «кирпич» и «бетон»."),
  ("A5_SH12B",None,None,"an extreme close-up insert of a guard-hut window with a friendly dog's nose at the gap","ECU","eye","static","day",True,False,
   "сторож на площадке дружелюбный, собака тоже, и оба не знают, где Аркадий."),
  ("A5_SH13B",None,"penthouse","a wide view of the marble counter at night, the sealed folder open under a single lamp","WS","eye","static","night",True,False,
   "папка с синими печатями лежит на мраморе, и ты листаешь её уже другими глазами."),
  ("A5_SH14B","HERO_RICH","car_lux","a medium shot of the man driving with the folder on the passenger seat, face set for questions","MS","eye","static","day",False,False,
   "утром ты везёшь папку юристу и по дороге репетируешь вопросы, которых не задал раньше."),
 ]),
 ("no_return","felt-green palette, deep casino green and brass under low cones of light, windowless timeless dark",[
  ("A6_SH01B",None,None,"an extreme close-up insert of a velvet rope being unhooked before polished shoes","ECU","low","static","night",True,False,
   "у входа бархатный канат, и охрана открывает его перед тобой с полупоклоном."),
  ("A6_SH02B",None,"casino","a wide view of the roulette table mid-play, chips scattered, faces green-lit and intent","WS","eye","static","night",True,False,
   "минус двести за вечер смешат тебя: подумаешь, столько стоил банкет для цеха."),
  ("A6_SH03B","HERO_RICH","casino","a medium close-up of the man at the cashier's cage, notes going one way, chips the other","MCU","eye","static","night",False,False,
   "кассирша пересчитывает твои деньги в фишки быстро и ласково, как медсестра перед уколом."),
  ("A6_SH04B",None,"casino","a wide view of the floor on a winning night, a small crowd drawn to one hot table","WS","eye","push_in","night",True,False,
   "во второй вечер ты выигрываешь триста, и это худшее, что могло случиться."),
  ("A6_SH06B",None,None,"an extreme close-up insert of a wristwatch left on the cashier's tray under the grille","ECU","top","static","night",True,False,
   "часы ты однажды оставляешь в залог у кассы, и ловишь себя на том, что не стыдно."),
  ("A6_SH08B","HERO_RICH","casino","a medium shot of the man turning from the table with empty hands, shoulders squared against the loss","MS","eye","static","night",False,False,
   "красное выпадает исправно через раз, но твой раз всё время оказывается соседним."),
  ("A6_SH09B",None,None,"an extreme close-up insert of a thumb typing a short familiar message on a phone one-handed","ECU","pov","static","night",True,False,
   "смс «задержусь, работа» ты набираешь уже без паузы, большим пальцем, одной рукой."),
  ("A6_SH10B",None,"penthouse","a wide view of the dinner table with three places and cutlery the loudest thing in the room","WS","eye","static","evening",True,False,
   "за ужином теперь слышно вилки, и Максим смотрит то на мать, то на тебя."),
  ("A6_SH11B",None,"city_street","a wide view of a night ATM alcove, one figure hunched at the glow with cards in hand","WS","eye","static","night",True,False,
   "у ночного банкомата ты стоишь с третьей картой и договариваешься с лимитами, как с людьми."),
  ("A6_SH12B",None,None,"an extreme close-up insert of the framed ticket glass catching passing headlights in a dark room","ECU","eye","static","night",True,False,
   "стекло рамки ловит свет фар с улицы, и шесть чисел вспыхивают и гаснут."),
 ]),
 ("collapse","emptying palette, packing-box brown and glass grey, warm things leaving cold rooms",[
  ("A7_SH01B",None,None,"an extreme close-up insert of packing tape screeching across a cardboard box seam","ECU","eye","static","day",True,False,
   "скотч визжит по коробкам весь вечер, и это единственный звук в огромной квартире."),
  ("A7_SH02B",None,"penthouse","a wide view of the entry hall with three figures and suitcases, one nod exchanged across it","WS","eye","static","day",True,False,
   "Максим на прощание кивает тебе, как знакомому, и этот кивок больнее всех слов."),
  ("A7_SH04B","HERO_RICH","penthouse","a close-up of the man lying awake on the white sofa under a thrown coat","CU","high","static","night",False,False,
   "ты ночуешь на белом диване, потому что спальня без её вещей слишком большая."),
  ("A7_SH05B","HERO_RICH","city_street","a medium close-up of the man in an institutional corridor among strangers holding identical folders","MCU","eye","static","day",False,False,
   "в коридоре следствия ты встречаешь ещё троих «инвесторов», и у всех твоя папка."),
  ("A7_SH07B",None,None,"an extreme close-up insert of a legal invoice, one itemised line under a reading thumb","ECU","pov","static","day",True,False,
   "счёт юриста — четыреста тысяч, и в нём есть строка «анализ перспектив», перспектив ноль."),
  ("A7_SH08B",None,None,"an extreme close-up insert of a signature going onto a sale contract with a familiar heavy pen","ECU","eye","static","day",True,False,
   "подпись под продажей ты ставишь той же ручкой, что под инвестициями, назло себе."),
  ("A7_SH09B",None,"city_street","a wide view of two men passing on opposite pavements of one street, neither turning","WS","eye","static","day",True,False,
   "вы с Витей теперь ходите по разным сторонам одной улицы, как чужие державы."),
  ("A7_SH10B","HERO_RICH","city_street","a medium shot of the man walking away from a lit entrance into the rain, hands in pockets","MS","eye","track","night",False,False,
   "просить у брата то, что ему дарил, ты не станешь, и он это знает."),
  ("A7_SH11B","HERO_RICH","penthouse","a medium close-up of the man in the lift with one box, meeting a sympathetic glance","MCU","eye","static","day",False,False,
   "в лифте вниз ты едешь с одной коробкой и ловишь взгляд консьержа — сочувственный."),
  ("A7_SH12B",None,"city_street","a wide view of a plain highrise district by the ring road, laundry on balconies, honest evening light","WS","eye","static","evening",True,False,
   "ты снимаешь однушку у кольцевой, и город из её окна выглядит честнее."),
 ]),
 ("bottom","stripped-bare palette, dormitory beige and document grey, one warm bulb of dignity",[
  ("A8_SH01B",None,None,"an extreme close-up insert of four enforcement writs fanned on a desk, names typed clean","ECU","top","static","day",True,False,
   "исполнительных листов ровно четыре, и на каждом твоя фамилия напечатана без единой ошибки."),
  ("A8_SH02B",None,"bailiff_office","a wide view of the corridor bench line outside the office, folders on knees, patient faces","WS","eye","static","day",True,False,
   "в коридоре у приставов сидят такие же, как ты, только без истории про миллионы."),
  ("A8_SH04B",None,None,"an extreme close-up insert of a phone screen playing a tow-truck video in a residents' chat","ECU","pov","static","day",True,False,
   "видео с эвакуатором набирает в домовом чате сто сорок просмотров и семь смайликов."),
  ("A8_SH05B","HERO_RICH","dorm_room","a medium shot of the man carrying one box up a dormitory stairwell, pausing at a turn","MS","low","static","day",False,False,
   "коробку ты заносишь на четвёртый этаж пешком, и рамка в ней позвякивает на поворотах."),
  ("A8_SH06B",None,"dorm_room","a wide view of the dormitory corridor at supper time, doors ajar, steam and radio voices","WS","eye","static","evening",True,False,
   "по вечерам в общаге пахнет чужими ужинами, и этот запах добрее, чем был ресторанный."),
  ("A8_SH07B",None,"city_street","a wide view of the plain district at night, garages and poplars, a corner shop going dark","WS","eye","static","night",True,False,
   "район у общаги простой: гаражи, тополя, магазин до десяти, и никто не просит в долг."),
  ("A8_SH09B",None,None,"an extreme close-up insert of new work boots by a dormitory door, laces still stiff","ECU","eye","static","day",True,False,
   "первой твоей покупкой после описи становятся рабочие ботинки, сорок третий размер, по акции."),
  ("A8_SH10B","HERO_RICH","factory_gate","a close-up of the man across the road breathing in toward the checkpoint, eyes soft","CU","eye","push_in","dawn",False,False,
   "через дорогу от проходной пахнет металлом и маслом, и ты стоишь, как у воды."),
 ]),
 ("return","homecoming palette, workshop steel and warm sodium, oil-dark browns with steady morning light",[
  ("A9_SH01B",None,None,"an extreme close-up insert of a clean work jacket laid out on a dormitory bed the night before","ECU","top","static","night",True,False,
   "куртку ты готовишь с вечера, как школьник форму, и сам над собой смеёшься."),
  ("A9_SH04B",None,"factory_shop","a wide view of the shop aisle with faces lifting from machines toward two men walking it","WS","eye","track","day",True,False,
   "цех провожает вас взглядами до самого пролёта, и в них нет ни одного злого."),
  ("A9_SH06B",None,None,"an extreme close-up insert of a name tag still bolted to a lathe bed, dust wiped by a thumb","ECU","eye","static","day",True,False,
   "на станине так и висит бирка с твоей фамилией, никто не удосужился снять."),
  ("A9_SH07B",None,"factory_shop","a wide view of the shop mid-shift with one more machine running in the row, sparks and rhythm","WS","eye","static","day",True,False,
   "к обеду ты уже в ритме смены, и обед в столовой кажется банкетом."),
  ("A9_SH09B",None,"factory_gate","a wide view of the checkpoint at winter evening, lamps warm over the outbound shift","WS","eye","static","evening",True,False,
   "после смены хочется не в казино и не в ресторан, а спать, и это счастье."),
  ("A9_SH10B","MASTER_BASE","factory_shop","a medium close-up of the foreman at the open locker glancing at the taped schedule, gruff and kind","MCU","eye","static","day",False,False,
   "мастер видит график в твоём шкафчике, хмыкает и добавляет тебе ночные подработки."),
  ("A9_SH11B",None,None,"an extreme close-up insert of a ruler guiding a pen through the first line of a payment schedule","ECU","top","static","day",True,False,
   "первую строку графика ты зачёркиваешь линейкой, ровно, как чертёжник, с уважением к цифре."),
  ("A9_SH12B",None,"dorm_room","a wide view of the small room at night, the flat cap on its nail, streetlight striping the blanket","WS","eye","static","night",True,False,
   "над кроватью висит отцовская кепка, и сны тебе снятся теперь про допуски, а не про красное."),
 ]),
 ("rebuild","mended palette, spring light over machine steel, modest warm colors coming back",[
  ("A10_SH01B",None,None,"an extreme close-up insert of a trainee list on a notice board, one surname repeating a line lower","ECU","eye","static","day",True,False,
   "в списке практикантов твоя фамилия повторяется строчкой ниже, и мастер выдерживает паузу."),
  ("A10_SH03B",None,"factory_shop","a wide view of father and son working neighbouring stations in silence, the shop flowing around them","WS","eye","static","day",True,False,
   "первую неделю вы работаете рядом молча, и цех делает вид, что так и надо."),
  ("A10_SH05B","SON_GROWN","factory_shop","a medium close-up of the young man asking a work question across the machine, formal and careful","MCU","eye","static","day",False,False,
   "однажды он спрашивает про конусность не «пап», а «мастер», и это тоже шаг."),
  ("A10_SH06B",None,None,"an extreme close-up insert of a soup pot steaming on a familiar old stove","ECU","eye","static","day",True,False,
   "борщ у Тани тот же, что в хрущёвке, и запах его слышно с третьего этажа."),
  ("A10_SH07B",None,"city_street","a wide view of a five-storey block at dusk, one kitchen window glowing yellow on the third floor","WS","low","static","evening",True,False,
   "в её окнах горит жёлтый свет, и ты научился радоваться ему с улицы."),
  ("A10_SH08B","HERO_BACK","factory_shop","a medium close-up of the man folding a payslip into his breast pocket, arithmetic settled","MCU","eye","static","day",False,False,
   "деньги снова стали понятными: заработал, отдал по графику, отложил на ботинки сыну."),
  ("A10_SH09B",None,None,"an extreme close-up insert of fresh winner posters on the kiosk, bigger sums, newer smiles","ECU","eye","static","day",True,False,
   "на киоске висят новые плакаты с новыми улыбками, и суммы на них ещё больше."),
  ("A10_SH10B",None,"city_street","a wide view of the summer evening street with one unhurried figure walking home along it","WS","eye","track","evening",True,False,
   "ты идёшь домой пешком, насвистывая, и встречные не знают, что мимо прошло семьдесят три миллиона."),
 ]),
 ("coda","dawn circle palette, cold blue morning breaking into working gold, settled and clear",[
  ("A11_SH04B",None,"factory_gate","a wide view of the shift flowing through the turnstiles one by one under the checkpoint lamps","WS","eye","static","dawn",True,False,
   "смена течёт через турникеты по одному, и у каждого за спиной своя история."),
  ("A11_SH06B","HERO_BACK","factory_shop","a close-up of the older man's hand resting briefly on the newcomer's shoulder by the bench","CU","eye","static","day",False,False,
   "паренёк кивает так же вполуха, как ты в восемнадцатом, и точно так же запомнит."),
  ("A11_SH08B","HERO_BACK","factory_shop","a medium shot of the man bringing his lathe up to speed, first chips curling off bright","MS","eye","static","day",False,False,
   "станок отзывается с пол-оборота, и смена номер две тысячи какая-то начинается, как первая."),
 ]),
]

if __name__=="__main__":
    for sk,pal,shots in ACTS:
        seed_act(sk, pal, shots, id_region="b")
