# -*- coding: utf-8 -*-
"""sailor_wife acts: learning (2016–25, 24) + coda (2026, 18). ALL animated.
Run: PYTHONIOENCODING=utf-8 python scripts/_seed_sailor_wife_A10A11.py"""
from _sailor_wife_engine import seed_act

PAL10="mellow palette of promenade gold hour, grandchild bright stripes, tea steam white and acacia green"
LEARNING=[
("A10_SH01",None,"promenade",
 "the promenade in golden evening hour, benches filling with unhurried couples, the lighthouse warming up its first turn, the sea laid out flat and generous",
 "EWS","eye","pan_left","evening",True,False,
 "берег принимает вас в свой распорядок, и набережная выучивает ваши шаги за одно лето."),
("A10_SH02","VIKTOR_OLD","promenade",
 "the old seaman walking the seafront with his wife, mid-story, drawing a harbour of another hemisphere in the air with both hands, his cane hooked unused on his arm",
 "MS","eye","track","evening",False,False,
 "каждый вечер он выгуливает тебе по одному порту, сегодня, судя по жестам, что-то тропическое.",
 "his hands raising piers and palm trees out of the evening air, the cane swinging forgotten on his elbow"),
("A10_SH03","ANNA_OLD","promenade",
 "the wife listening with her arm through his, watching the story more than the sea, her laugh arriving at the right harbours",
 "MCU","eye","static","evening",False,False,
 "ты знала этого человека сорок лет по письмам, а теперь читаешь полное собрание сочинений.",
 "her arm settling deeper through his, her face turning up at the story's turn, her laugh landing"),
("A10_SH04",None,"anna_window_room_2020s",
 "a baby's crib set up in the corner of the window room for visits, a mobile of tiny paper ships turning slowly over it in a draught",
 "INSERT","eye","static","day",True,True,
 "в восемнадцатом году у оли рождается дочка, и над кроваткой у вас кружат бумажные кораблики."),
("A10_SH05","VIKTOR_OLD","anna_window_room_2020s",
 "the old seaman holding a swaddled infant with the terrified ceremony of decades ago, his white beard bent low, one tiny fist gripping his finger",
 "MCU","eye","push_in","day",False,True,
 "внучку он берёт на руки той же испуганной хваткой, что и олю тридцать шесть лет назад.",
 "the tiny fist closing around his weathered finger, his breath held, his beard lowering by degrees"),
("A10_SH06","ANNA_OLD","anna_window_room_2020s",
 "the wife watching the old seaman and the infant, her hand at her mouth holding a smile that leaks anyway, sunlight pooling around the armchair",
 "CU","eye","static","day",False,False,
 "ты смотришь на них и думаешь, вот теперь он никуда от этого причала не денется.",
 "her hand pressing the leaking smile, her shoulders easing down, sun trembling on her lashes"),
("A10_SH07","VNUCHKA_BASE","promenade",
 "a curly-haired girl of five racing gulls along the promenade, arms out like wings, two old figures keeping pace far behind her",
 "WS","eye","track","day",False,False,
 "внучка растёт у моря, как ты когда-то, и чайки уступают ей набережную без боя.",
 "her small arms spreading into wings mid-run, gulls lifting lazily ahead, the old couple trailing far back"),
("A10_SH08","VIKTOR_OLD","courtyard_bench",
 "the old seaman and the small girl building a model boat on the courtyard bench, glue, thread and tiny clamps between them, two tongues out in identical concentration",
 "MS","eye","static","day",False,True,
 "по субботам они строят кораблик, и языки у обоих высунуты под одним углом.",
 "four hands negotiating a thread through tiny rigging, two tongues tracking the work at the same angle"),
("A10_SH09","OBJ:ship_in_bottle",None,
 "a homemade model boat of pale wood with thread rigging and a scrap-cloth sail, held up finished into the sunlight by a small hand and a weathered one together",
 "ECU","low","static","day",False,False,
 "готовый кораблик поднимают к солнцу в четыре руки, и он немедленно получает имя, бабушка.",
 "the little boat rising into the sun in the doubled grip, its cloth sail filling with light"),
("A10_SH10","ANNA_OLD","anna_kitchen",
 "the wife baking with the small girl standing on a stool, flour on two noses, the old seaman reading instructions aloud from a folded paper with naval gravity",
 "WS","eye","static","day",False,False,
 "пирог по воскресеньям вы печёте втроём, и он зачитывает рецепт голосом судовой роли.",
 "flour dust hanging in the sun, the girl's stool wobbling with enthusiasm, the recipe paper rising like an order"),
("A10_SH11","ZINA_BASE","courtyard_bench",
 "the neighbour now grey under the copper rinse, slower, holding court from the bench with a walking stick for a sceptre, her hoops still gold",
 "MCU","eye","static","day",False,False,
 "зина сдаёт двор по описи новым бабушкам, но трон на лавочке оставляет за собой.",
 "her stick tapping a point of order, the hoops swinging with the old authority, her laugh rolling out"),
("A10_SH12","ANNA_OLD","courtyard_bench",
 "the two old friends on the bench shoulder to shoulder in autumn sun, a shared shawl over both laps, tea from one thermos, forty years of talk idling",
 "MS","eye","static","day",False,False,
 "вы с зиной сидите под акацией, как в семьдесят восьмом, только теперь спешить некуда.",
 "the shared shawl tugging gently as they settle, two cups touching in a small toast, leaves drifting"),
("A10_SH13",None,"harbor_panorama",
 "the modern harbour bright with container gantries and a white ferry leaving, the old crane line still standing at the historic end, the bay glittering",
 "EWS","high","static","day",True,False,
 "порт помолодел без вас, контейнеры, паром до островов, но гудки остались прежней породы."),
("A10_SH14","ANNA_OLD","anna_window_room_2020s",
 "the wife at the window at the sound of a horn, caught mid-rise from the armchair, then lowering herself back with deliberate humour, her husband's eyes on her",
 "MS","eye","static","day",False,True,
 "на гудки ты всё ещё привстаёшь, но теперь садишься обратно, и вы оба делаете вид, что нет.",
 "her body catching itself mid-rise, lowering back with theatrical dignity, his eyebrow lifting across the room"),
("A10_SH15","VIKTOR_OLD","anna_window_room_2020s",
 "the old seaman's face over the lowered newspaper edge, a smile hiding in the white beard, one eye sliding sideways toward his wife",
 "CU","eye","static","day",False,False,
 "он прячет улыбку в бороду и говорит газете, а я, между прочим, всё видел, аня.",
 "the paper lowering an inch, the hidden smile surfacing in the beard, his eyes sliding to her over the page"),
("A10_SH16","OLYA_ADULT","anna_kitchen",
 "the grown daughter visiting, her thin red scarf on the hook by the door, teaching her mother a video call on a tablet, three generations of hands over one screen",
 "MS","eye","static","day",False,False,
 "оля учит тебя видеозвонкам, и теперь море можно показывать ей прямо из окна.",
 "three sets of hands negotiating the tablet, the screen flaring on, the daughter's laugh guiding fingers"),
("A10_SH17","ANNA_OLD","promenade",
 "the old couple on their bench at the lighthouse end at dusk, his arm along the backrest behind her, the beam beginning its patient sweep over them",
 "WS","eye","static","evening",False,False,
 "у вас теперь есть своя скамейка у маяка, и смотритель здоровается с вами, как с коллегами.",
 "the lighthouse beam sweeping its first slow arc over the still couple, gulls settling for the night"),
("A10_SH18","VIKTOR_OLD","promenade",
 "the old seaman watching the horizon soften into dusk, his face at rest in a way it never managed between contracts, the swallow tattoo pale on his folded forearm",
 "CU","eye","static","evening",False,True,
 "он смотрит на горизонт спокойно, впервые не примеряя его на себя, и это твоя победа.",
 "his gaze resting on the far water without leaning after it, the folded forearms settling, peace holding"),
("A10_SH19",None,"anna_window_room_2020s",
 "the window room on new year's eve, a small tree's lights doubling in the dark window over the harbour's own lights, gifts of childish wrapping under it",
 "WS","eye","static","night",True,False,
 "новый год теперь встречают у вас, всей семьёй, и порт в полночь гудит уже по традиции."),
("A10_SH20","VNUCHKA_BASE","anna_window_room_2020s",
 "the curly-haired girl of seven conducting the midnight harbour horns from the windowsill with a sparkler, the family's laughter warm behind her",
 "MCU","low","static","night",False,True,
 "в полночь внучка дирижирует гудками с подоконника, и порт слушается её лучше оркестра.",
 "the sparkler carving bright arcs, her small arms conducting the unseen ships, laughter shaking the lamplight"),
("A10_SH21","ANNA_OLD","anna_window_room_2020s",
 "the wife and the old seaman in the two armchairs at the year's last hour, hands joined across the gap between armrests, the tree lights idling over them",
 "MCU","eye","static","night",False,False,
 "вы сидите в креслах, держась за руки через подлокотники, и молчание у вас теперь общее.",
 "their joined hands swinging once gently in the gap, tree lights sliding colour across two calm faces"),
("A10_SH22",None,"promenade",
 "the promenade under january snow at noon, one cleared path along the railing, two sets of unhurried footprints side by side its whole length",
 "EWS","high","static","day",True,False,
 "зимой набережную чистят к десяти, и первые следы на ней каждый день одни и те же."),
("A10_SH23","ANNA_OLD","anna_kitchen",
 "the wife penning something at the kitchen table in an exercise book, unhurried, the old seaman's borscht pot steaming behind, her face lit with private industry",
 "MCU","eye","static","day",False,False,
 "по вечерам ты записываешь его рейсы в тетрадь, по номерам, пусть внучка потом прочтёт.",
 "her pen travelling steady lines, steam drifting past from the pot, her lips repeating a ship's name"),
("A10_SH24",None,"anna_window_room_2020s",
 "the souvenir shelf in low winter sun, all twenty-three pieces and the sea glass and the champagne cork, dust-free, a child's paper boat newly moored at the far end",
 "INSERT","eye","pan_right","day",True,True,
 "на полке двадцать три сувенира, штормовое стекло, пробка и один бумажный кораблик, флот в сборе."),
]

PAL11="quiet resolution palette of fog pearl, window light silver, tea amber and anchor-silver grey"
CODA=[
("A11_SH01","VNUCHKA_BASE","anna_window_room_2020s",
 "the curly-haired girl of eight waiting for her answer at the table, the photo album open between her elbows, fog light soft on her expectant face",
 "MCU","eye","static","morning",False,False,
 "внучка ждёт ответа над раскрытым альбомом, и торопить тебя она не собирается.",
 "her chin resting on her stacked fists, her eyes steady up at her grandmother, one page lifting in a draught"),
("A11_SH02","ANNA_OLD","anna_window_room_2020s",
 "the old woman beginning her answer with her hand on the album's first page, a young sailor and a girl in a summer dress smiling up through the years",
 "MCU","high","static","morning",False,True,
 "потому что сорок лет, отвечаешь ты, я жила от гудка до гудка, вот от этого танца.",
 "her palm smoothing the first album page, the two young faces surfacing under her touch"),
("A11_SH03","VNUCHKA_BASE","anna_window_room_2020s",
 "the girl leaning over the album photograph, looking from the young sailor to the sleeping old man in the armchair and back, arithmetic dawning on her face",
 "CU","eye","static","morning",False,False,
 "она смотрит на молодого моряка в альбоме, потом на дедушку в кресле, и глаза у неё круглеют.",
 "her head swivelling from page to armchair and back, her mouth opening slowly at the discovery"),
("A11_SH04","VIKTOR_OLD","anna_window_room_2020s",
 "the old seaman awake after all in his armchair, one eye open toward the album party, the newspaper untouched on his chest, a smile starting in the beard",
 "MCU","eye","static","morning",False,False,
 "дедушка, оказывается, не спит, и из кресла сообщает, в семьдесят восьмом я был неотразим.",
 "his one open eye glinting toward the table, the beard's smile widening, the newspaper rising with a chuckle"),
("A11_SH05","ANNA_OLD","anna_window_room_2020s",
 "the old woman laughing across the room at her husband, the album page held up as evidence, forty-eight years of argument and love in one look between armchair and table",
 "MS","eye","static","morning",False,False,
 "ты поднимаешь альбом, как вещественное доказательство, и смеёшься, неотразим, только ноги отдавил.",
 "the album rising in her hands as evidence, her laugh crossing the room, his mock-offended shrug answering"),
("A11_SH06","VNUCHKA_BASE","anna_window_room_2020s",
 "the girl climbing between the two armchairs with the album, settling herself as the bridge between grandmother and grandfather, pointing at photographs for stories",
 "WS","eye","static","day",False,False,
 "внучка перебирается с альбомом к креслам и требует историю про каждую фотографию по очереди.",
 "her small body wedging happily between the armchairs, the album spreading across two sets of knees"),
("A11_SH07","VIKTOR_OLD","anna_window_room_2020s",
 "the old seaman's finger on a photograph of a ship, beginning a story, the girl's head against his sleeve, the swallow tattoo just showing at his pushed-up cuff",
 "CU","eye","static","day",False,False,
 "он ведёт пальцем по фотографии и начинает, а это, брат, было на пятом рейсе, в тропиках.",
 "his finger tracing the ship's line on the photo, the girl's head settling into his sleeve, the story gathering way"),
("A11_SH08","ANNA_OLD","anna_kitchen",
 "the old woman making tea for three in her kitchen, moving without hurry, the lashed jars and the seaman's borscht pot all long since hers too",
 "MS","eye","static","day",False,False,
 "ты завариваешь чай на троих и думаешь, что слово ждать наконец сменило в доме профессию.",
 "the teapot filling in her unhurried hands, steam climbing past the lashed shelf, three cups lining up"),
("A11_SH09",None,"anna_kitchen",
 "three cups of tea steaming on a tray by the kitchen window, the fog outside beginning to thin, a gull walking the outer sill like a sentry",
 "INSERT","eye","static","day",True,False,
 "чай на троих, туман за окном редеет, и чайка на карнизе несёт свою вахту исправно."),
("A11_SH10","ANNA_OLD","anna_window_room_2020s",
 "the old woman handing cups into two sets of hands at the armchairs, the room warm with story mid-flow, fog light silvering toward sun at the window",
 "WS","eye","static","day",False,False,
 "ты раздаёшь чай слушателям, история идёт уже про девятый рейс, и конца ей не предвидится.",
 "cups passing into reaching hands, the story's gestures resuming around them, light warming at the glass"),
("A11_SH11","OBJ:anchor_pendant",None,
 "the small silver anchor pendant at an old throat catching a first direct ray as the fog opens, its worn edges soft as sea glass",
 "ECU","eye","push_in","day",False,True,
 "якорёк на твоей шее ловит первый луч из тумана, сорок шесть лет, и всё ещё держит.",
 "the pendant flaring gently as the ray finds it, rising and settling with an unhurried breath"),
("A11_SH12",None,"harbor_panorama",
 "the harbour emerging from thinning fog into pale sun, water finding its silver, a big ship standing in from sea toward the breakwater gap, gulls waking up the sky",
 "EWS","high","static","day",True,False,
 "к полудню туман поднимается, и в ворота порта встаёт с моря большое белое судно."),
("A11_SH13","VNUCHKA_BASE","anna_window_room_2020s",
 "the girl at the window pointing at the arriving ship, bouncing on her toes, calling the grown-ups to see, her curls against the brightening glass",
 "MCU","low","static","day",False,False,
 "внучка первой замечает его в окне и подпрыгивает, смотрите, смотрите, какой идёт.",
 "her arm shooting toward the glass, her toes bouncing, curls jumping against the light"),
("A11_SH14","ANNA_OLD","anna_window_room_2020s",
 "the two armchairs by the window with the old couple in them and the girl between, all three faces turned to the harbour, the ship crossing the window's frame",
 "WS","eye","static","day",False,True,
 "вы смотрите на него втроём из кресел, и вставать к окну сегодня никому не нужно.",
 "the ship sliding slow across the window's width, three faces following it, steam rising from forgotten cups"),
("A11_SH15",None,"anna_window_room_2020s",
 "the arriving ship framed exactly in the window over the souvenir shelf, its horn's long note almost visible, the twenty-three souvenirs lined beneath like a crew at muster",
 "INSERT","eye","static","day",True,True,
 "судно даёт длинный входной гудок, и весь флот на полке встречает его по стойке смирно."),
("A11_SH16","ANNA_OLD","anna_window_room_2020s",
 "the old woman listening to the horn from her armchair, seated, her husband's hand arriving on her shoulder from behind, her own hand rising to cover it",
 "CU","eye","push_in","day",False,True,
 "гудок плывёт над крышами, и впервые за сорок шесть лет ты слушаешь его сидя.",
 "her body staying settled in the chair, his hand landing on her shoulder, her palm rising to hold it there"),
("A11_SH17","ANNA_OLD","anna_window_room_2020s",
 "the room in full noon light, the couple's joined hands on the shoulder, the girl leaning on the sill, the ship passing, the shelf shining, everything in its place at last",
 "WS","eye","pull_out","day",False,False,
 "вот и вся твоя жизнь, от гудка до гудка, и если она тебя тронула, подпишись на канал.",
 "the joined hands holding, the ship clearing the frame, noon light settling over the whole room at once"),
("A11_SH18",None,"harbor_panorama",
 "the harbour in full clear light, the white ship made fast at her berth, cranes turning to work, the town and the water going about their shared day",
 "EWS","high","pull_out","day",True,False,
 "эта история вымышлена, все совпадения с реальными людьми и событиями случайны, не повторяй чужих ошибок."),
]

seed_act("learning",PAL10,LEARNING)
seed_act("coda",PAL11,CODA)
