# -*- coding: utf-8 -*-
"""teacher acts: medal (1985, 30 shots, ANIMATED — конец анимированного префикса) + first_bell (1990–93, 30 shots, static).
Run: PYTHONIOENCODING=utf-8 python scripts/_seed_teacher_A2A3.py"""
from _teacher_engine import seed_act

PAL2="bright late-spring palette of lilac bloom, gold evening lamplight, worn timber grey and exam-paper white"
MEDAL=[
("A2_SH01",None,"village_street",
 "the settlement street in late may of nineteen eighty-five, lilac bushes foaming over leaning fences, laundry lines catching a warm wind, puddle mirrors full of fast clouds",
 "EWS","eye","pan_left","day",True,False,
 "май восемьдесят пятого, посёлку сирень по пояс, а тебе семнадцать и остался один экзамен."),
("A2_SH02","LIDA_YOUNG","village_kitchen",
 "a slender seventeen-year-old with a chestnut ponytail writing an essay at the kitchen table by lamplight, three open books propped against the samovar, her finger holding a line in one of them",
 "MS","eye","push_in","night",False,False,
 "ты пишешь выпускное сочинение ночью, потому что днём в доме гудит мамина швейная машинка.",
 "her pen moving in quick sure lines, her other hand holding a page flat, the lamp flame steady beside her"),
("A2_SH03","LIDA_YOUNG","village_kitchen",
 "the young woman reading from thick library volumes stacked on the kitchen table, absorbed, twirling the end of her ponytail, moths tapping the lamp glass",
 "MCU","eye","static","night",False,False,
 "в районной библиотеке тебе уже нечего брать, ты перечитала все три полки с литературой.",
 "her eyes running down the page, a hand rising absently to twirl the ponytail, a moth flickering at the lamp"),
("A2_SH04",None,"village_kitchen",
 "a framed photograph of a man on a whitewashed wall with a strip of black ribbon across one corner, a dried sprig of wormwood tucked behind the frame",
 "INSERT","eye","static","night",True,False,
 "отца нет уже три года, с тех пор мамина машинка стучит и по ночам тоже."),
("A2_SH05","MAMA_BASE","village_kitchen",
 "the fifty-year-old seamstress pausing over the treadle machine to press a fist to her chest, breathing carefully, her grey shawl slipping from one shoulder",
 "MCU","eye","static","night",False,False,
 "мама всё чаще останавливается посреди строчки и пережидает, приложив кулак к груди.",
 "her fist pressing slowly to her chest, her breathing measured, the shawl sliding softly off one shoulder"),
("A2_SH06","TAMARA_BASE","classroom_soviet",
 "the aging schoolmistress, silver bun now white, holding a student's essay and speaking earnestly across the teacher's desk, afternoon sun on stacked exam papers",
 "MS","eye","static","day",False,False,
 "тамара павловна держит твоё сочинение и говорит, тебе дорога в университет, в самый главный.",
 "her hand lifting the essay pages slightly, tapping them once with the back of her fingers for emphasis"),
("A2_SH07","LIDA_YOUNG","classroom_soviet",
 "the seventeen-year-old at the blackboard solving an exam problem with confident chalk strokes, her ponytail swaying, classmates' desks empty around her in consultation hour",
 "WS","eye","static","day",False,False,
 "ты сдаёшь все выпускные на отлично, и слово медаль в учительской произносят как решённое.",
 "her arm sweeping through confident chalk lines, dust drifting, her weight shifting as the solution grows"),
("A2_SH08","OBJ:medal",None,
 "a small gold school medal on a faded watered ribbon lying in a velvet-lined case held open in two hands, sunlight from a tall window flaring on the gold",
 "ECU","eye","push_in","day",False,True,
 "в июне тебе вручают золотую медаль, единственную на весь выпуск восемьдесят пятого года.",
 "the case tilting slowly in the hands, the gold disc catching and releasing a blade of sunlight"),
("A2_SH09","LIDA_YOUNG","assembly_hall",
 "the seventeen-year-old standing on a low school stage in her best dress, holding the medal case, dazzled by applause, paper flower garlands along the stage edge",
 "MS","low","static","day",False,True,
 "ты стоишь на сцене, зал хлопает, и будущее кажется прямой светлой дорогой без поворотов.",
 "her fingers tightening on the medal case, a shy bow of the head, garlands stirring in warm air"),
("A2_SH10","MAMA_BASE","assembly_hall",
 "the seamstress mother in her one good dress standing at the back of the school hall, clapping with work-rough hands, eyes bright, the grey shawl folded over her arm",
 "MCU","eye","static","day",False,False,
 "мама хлопает из последнего ряда так, что ладоням, наверное, больно до самого вечера.",
 "her rough hands meeting in firm proud claps, her chin trembling once before she lifts it"),
("A2_SH11",None,"village_kitchen",
 "a kitchen table at night with a sheet of paper covered in pencilled sums, a train timetable booklet, a worn purse opened flat and empty beside a cooling teapot",
 "INSERT","top","static","night",True,False,
 "вечером вы считаете на бумажке столичную жизнь, билет, угол, еду, и цифры не сходятся."),
("A2_SH12","MAMA_BASE","village_kitchen",
 "the mother sitting with her hands flat on the pencilled sums, looking down, guilt in the set of her shoulders, lamplight deepening the lines of her face",
 "MCU","high","static","night",False,False,
 "мама смотрит в эти цифры и говорит тихо, не тяни я одна, выучила бы тебя где угодно.",
 "her palms pressing flat on the paper, her shoulders sinking, her head bowing slowly over the sums"),
("A2_SH13","LIDA_YOUNG","village_kitchen",
 "the seventeen-year-old covering her mother's rough hand with her own young one across the table of sums, her face resolving into a firm gentle smile",
 "OTS","over","static","night",False,True,
 "ты накрываешь её руку своей и говоришь, есть пединститут в областном, стипендия и общежитие.",
 "her young hand settling over the rough one, a small squeeze, her chin lifting with the decision"),
("A2_SH14","LIDA_YOUNG","village_kitchen",
 "the young woman speaking with bright certainty, counting on three raised fingers, lamplight warm on her earnest face",
 "CU","eye","static","night",False,False,
 "отработаю три года по распределению, а потом аспирантура, это же всего три года, мама.",
 "three fingers rising one by one as she counts, her eyebrows lifting with bright conviction"),
("A2_SH15","MAMA_BASE","village_kitchen",
 "the mother drawing a thin silver ring with a small amber stone from a knotted handkerchief and holding it out across the lamplight",
 "MCU","eye","push_in","night",False,True,
 "тогда мама развязывает платок и достаёт бабушкино серебряное кольцо с капелькой янтаря.",
 "the knotted handkerchief opening fold by fold, the small ring emerging into the lamplight"),
("A2_SH16","OBJ:medal",None,
 "a thin silver ring with a small amber stone being slid onto a young right hand, the amber glowing like a drop of honey in lamplight",
 "ECU","top","static","night",False,True,
 "янтарь тёплый, как будто в нём заперт кусочек лета, и кольцо садится точно по пальцу.",
 "the ring sliding slowly over the knuckle and settling, the amber flaring softly as it turns to the light"),
("A2_SH17","LIDA_YOUNG","village_street",
 "the young woman with a battered suitcase standing on the settlement street at dawn beside her mother, a long-distance bus waiting with its door open, mist over the ditches",
 "WS","eye","static","morning",False,False,
 "в августе ты стоишь с чемоданом у автобуса, и посёлок вдруг кажется очень маленьким.",
 "mist drifting low over the road, the bus door standing open, her grip shifting on the suitcase handle"),
("A2_SH18","MAMA_BASE","village_street",
 "the mother tucking a wrapped parcel of food into her daughter's bag and smoothing the girl's collar twice with quick worried hands, the grey shawl tight around her shoulders",
 "MCU","eye","static","morning",False,False,
 "мама суёт тебе свёрток с пирожками и дважды поправляет воротник, который и так ровный.",
 "her quick hands tucking the parcel deep, then smoothing the collar twice, reluctant to let go"),
("A2_SH19",None,"village_street",
 "a long-distance bus pulling away down the rutted settlement road, a small figure waving in its dusty rear window, geese scattering, the grain elevator far against the morning sky",
 "EWS","high","static","morning",True,False,
 "автобус трогается, и ты машешь в пыльное окно, пока мама не становится точкой."),
("A2_SH20",None,"institute_hall",
 "a steep tiered lecture hall of a pedagogical institute, dusty shafts of light over long curved benches, a wide triple blackboard, plaster busts on a shelf",
 "WS","low","tilt_up","day",True,False,
 "аудитория пединститута вмещает двести человек, это два твоих посёлка на одних скамейках."),
("A2_SH21","LIDA_YOUNG","institute_hall",
 "the young student in the front bench writing fast in a thick notebook, surrounded by students, her amber ring catching a shaft of light as her pen flies",
 "MCU","eye","static","day",False,False,
 "ты записываешь лекции до последнего слова, и конспекты твои к зиме ходят по всему курсу.",
 "her pen racing along the notebook line, page corners lifting, the amber ring flickering in the light shaft"),
("A2_SH22","LIDA_YOUNG","institute_hall",
 "the young woman standing at the triple blackboard before the tiered hall, chalk in hand, mid-explanation, older students listening from the benches",
 "MS","eye","static","day",False,False,
 "на третьем курсе преподаватель сажает тебя вести семинар у первокурсников вместо себя.",
 "her chalk hand moving between board and audience, her posture opening as the explanation lands"),
("A2_SH23","OBJ:chalk",None,
 "a young woman's fingers with a thin amber ring rolling a piece of white chalk slowly, white dust settling on the knuckles, a triple blackboard blurred behind",
 "ECU","eye","static","day",False,True,
 "мел ложится в твои пальцы так, будто ждал их все эти годы где-то в коробке.",
 "the chalk rolling slowly between the fingers, a fine sift of dust falling past the amber ring"),
("A2_SH24","LIDA_YOUNG","lida_kitchen",
 "the student at a narrow table writing a letter by lamplight, an envelope with a stamp ready beside her, a small photograph of her mother propped against a cup",
 "MS","eye","static","night",False,False,
 "каждое воскресенье ты пишешь маме письмо и вкладываешь в конверт половину стипендии.",
 "her pen finishing a line, her hand folding the letter with care, fingers pressing the crease flat"),
("A2_SH25",None,"street_winter",
 "a provincial city street in winter dusk, trodden snow paths between low blocks, a bent streetlamp with a cold halo, warm windows lighting one by one",
 "EWS","eye","static","evening",True,False,
 "город больше посёлка в сто раз, но общежитие, институт и почта, вот и весь твой город."),
("A2_SH26","LIDA_YOUNG","classroom_hers_90s",
 "the student-teacher on her first school practice standing before an unfamiliar class, holding the register like a shield, sun through tall painted window frames",
 "WS","eye","static","day",False,False,
 "на четвёртом курсе тебя ставят на практику в настоящий класс, и колени дрожат под юбкой.",
 "the register pressed to her chest lowering by degrees, her shoulders unlocking as she begins to speak"),
("A2_SH27","LIDA_YOUNG","classroom_hers_90s",
 "the young woman mid-lesson at the green chalkboard, turned to the class with chalk raised, her face lit and alive, morning light across chalk dust",
 "MCU","eye","push_in","day",False,True,
 "через десять минут дрожь проходит, и ты вдруг слышишь, как класс дышит вместе с тобой.",
 "her raised chalk hand steadying, her face lifting into focus, dust motes drifting through the light between her and the class"),
("A2_SH28","LIDA_YOUNG","institute_hall",
 "the young woman receiving a red diploma folder at a lectern, a handshake mid-frame, the tiered hall soft behind, her amber ring visible on the receiving hand",
 "MS","low","static","day",False,True,
 "летом девяностого ты получаешь красный диплом, и в графе распределение стоит школа на окраине.",
 "the red folder passing into her hand, the handshake firm, her fingers closing on the diploma"),
("A2_SH29","LIDA_YOUNG","street_winter",
 "the graduate walking a summer evening street with the red diploma under her arm, jacket over her shoulder, her step long and light past the bent streetlamp",
 "WS","eye","track","evening",False,False,
 "ты идёшь по городу с дипломом под мышкой и репетируешь слово аспирантура на разные лады.",
 "her long light steps carrying her past the lamp, the diploma folder swinging gently under her arm"),
("A2_SH30",None,"lida_kitchen",
 "a red diploma folder lying open on a narrow kitchen table beside a train timetable and a neatly written three-year plan on a sheet of squared paper, lamplight",
 "INSERT","top","push_in","night",True,False,
 "на листке в клетку написан план, три года школы, потом наука, и подчёркнуто два раза."),
]

PAL3="crisp september palette of aster purple, fresh chalk white, notebook blue and pale morning sky"
BELL=[
("A3_SH01",None,"school_yard",
 "the paved yard of a city-edge secondary school on the first of september nineteen-ninety, lines of pupils with flowers forming up, a flagpole, long morning shadows on cracked asphalt",
 "EWS","high","static","morning",True,False,
 "первое сентября девяностого, школа на окраине, и на линейке шестьсот незнакомых лиц."),
("A3_SH02","LIDA_YOUNG","school_yard",
 "the twenty-two-year-old teacher in a modest wool skirt standing stiffly at the edge of the assembly, clutching a class register, pupils' flowers bright around her",
 "MS","eye","push_in","morning",False,True,
 "тебе двадцать два, у тебя журнал, указка и класс, в котором ты моложе некоторых второгодников."),
("A3_SH03","LIDA_YOUNG","classroom_hers_90s",
 "the young teacher opening a fresh cardboard box of white chalk at her new desk, lifting the lid like a jewel case, tall painted windows bright behind",
 "MCU","eye","static","morning",False,True,
 "в столе тебя ждёт новая коробка мела, первая твоя собственная, и ты открываешь её, как шкатулку.",
 "the cardboard lid lifting slowly, rows of white sticks appearing, her fingertips brushing across them once"),
("A3_SH04","OBJ:chalk",None,
 "a fresh unbroken stick of white chalk held between young fingers with a thin amber ring, a dark green board waiting blurred beyond",
 "ECU","eye","push_in","morning",False,False,
 "ты берёшь первый кусок, и он ложится в пальцы точно так же, как тогда, в семьдесят пятом."),
("A3_SH05","LIDA_YOUNG","classroom_hers_90s",
 "the young teacher writing her own name large and clean at the top of the green chalkboard, her back straight, the class blurred and restless beyond her shoulder",
 "OTS","over","static","morning",False,True,
 "ты пишешь на доске своё имя, теперь с отчеством, и класс за спиной притихает на секунду.",
 "her hand travelling in even confident strokes, the letters of her name appearing, a hush settling behind her"),
("A3_SH06","SANYA_KID","classroom_hers_90s",
 "a stocky thirteen-year-old with a rough black crew cut lounging at a back desk, backpack on one shoulder even seated, testing the new teacher with an insolent grin",
 "CU","low","static","day",False,False,
 "с задней парты тебя изучает саня, гроза шестых классов, и ухмылка у него профессиональная.",
 "his grin widening slowly, his chair tipping back a lazy centimetre, his eyes tracking the new teacher"),
("A3_SH07","LIDA_YOUNG","classroom_hers_90s",
 "the young teacher standing calmly beside the insolent boy's desk, not raising her voice, one hand resting on his notebook, the class watching breathless",
 "MS","eye","static","day",False,False,
 "ты не кричишь, ты просто стоишь рядом и ждёшь, и через минуту тишина побеждает его.",
 "her hand resting still on the notebook, her weight patient and planted, the boy's grin fading by degrees"),
("A3_SH08",None,"classroom_hers_90s",
 "a class register open on a teacher's desk with thirty-four names in a fresh even column, a red pen lying across it, morning sun striping the page",
 "INSERT","top","static","day",True,False,
 "в девяносто первом тебе дают классное руководство, пятый б, тридцать четыре фамилии столбиком."),
("A3_SH09","LIDA_YOUNG","school_yard",
 "the young class teacher surrounded by her fifth-graders on the school steps, drowning in bunches of purple asters, laughing over the blooms",
 "WS","eye","static","morning",False,True,
 "на твоё первое классное первое сентября тебе дарят столько астр, что не видно рук.",
 "aster bunches piling into her arms, her laugh breaking free over the flowers, children pressing closer"),
("A3_SH10","LIDA_YOUNG","teachers_room",
 "the young teacher at the staff-room table among older colleagues, tea in mismatched cups, her corner of the green baize covered in exercise books she is checking",
 "MS","eye","static","evening",False,False,
 "в учительской тебе достаётся угол стола у окна, и старшие зовут тебя пока просто лидочка.",
 "her red pen working through a notebook, steam rising from cups, an older colleague passing behind her chair"),
("A3_SH11","LIDA_YOUNG","lida_kitchen",
 "the young teacher at her narrow kitchen table at night, a stack of exercise notebooks at her elbow, checking by lamplight, tea gone cold beside the red pen",
 "MS","eye","push_in","night",False,False,
 "вечерами ты проверяешь тетради и замечаешь, что чай остывает раньше, чем кончается стопка.",
 "her pen ticking small marks down a page, her free hand turning it, the notebook stack barely shrinking"),
("A3_SH12","OBJ:notebooks",None,
 "a tall stack of thin exercise notebooks in pale-green and blue covers on a kitchen table, a red pen resting on top, lamplight warm on the worn corners",
 "INSERT","eye","static","night",False,False,
 "стопка за пятым б ростом с самовар, и завтра она вырастет снова, как трава за косой."),
("A3_SH13","LIDA_YOUNG","classroom_hers_90s",
 "the young teacher reading aloud to her class, perched on the front edge of her desk with an open book, pupils leaning forward on their elbows, winter light on frosted panes",
 "WS","eye","static","day",False,False,
 "ты читаешь им вслух после уроков, и даже саня слушает, спрятав ухмылку в воротник.",
 "the pages turning slowly in her hands, children's heads tilting forward, frost light soft across the room"),
("A3_SH14","KATYA_KID","classroom_hers_90s",
 "a slight copper-haired girl in round thin-rimmed glasses at a front desk, hand raised straight and certain, a book held to her chest with the other arm",
 "MCU","eye","static","day",False,False,
 "на первой парте тянет руку катя, рыжая и серьёзная, она задаёт вопросы лучше учебника.",
 "her hand rising straight and unwavering, her chin lifting, glasses flashing as she looks up"),
("A3_SH15","LIDA_YOUNG","classroom_hers_90s",
 "the young teacher bending over the copper-haired girl's desk, pointing at a line in her open book, both faces lit by the same window light",
 "OTS","over","static","day",False,False,
 "ты подсовываешь кате книги из своей студенческой сумки и узнаёшь в ней себя до дрожи.",
 "her finger tracing a line in the girl's book, the girl's braid bending closer, two heads settling over one page"),
("A3_SH16",None,"street_winter",
 "the street outside the school in winter dusk, teacher-height footprints and dozens of small ones crossing in trodden snow, warm windows and a bent streetlamp",
 "EWS","eye","static","evening",True,False,
 "домой ты идёшь в темноте, и снег на твоей улице истоптан маленькими следами твоего класса."),
("A3_SH17","LIDA_YOUNG","lida_kitchen",
 "the young teacher pinning a small tear-off calendar to the kitchen wall, marking a neat cross on a date, her three-year plan sheet pinned beside it",
 "MCU","eye","static","evening",False,False,
 "на стене висит календарик, где ты честно вычёркиваешь месяцы до конца распределения.",
 "her pen drawing one small firm cross on the calendar, her eyes moving to the pinned plan beside it"),
("A3_SH18","LIDA_YOUNG","institute_hall",
 "the young teacher visiting her old institute, talking with a professor at the foot of the tiered hall, holding a list of postgraduate entrance requirements",
 "MS","eye","static","day",False,False,
 "весной ты берёшь в институте список требований в аспирантуру и учишь его наизусть, как стихи.",
 "the requirement sheet passing between hands, her head bowing over it, the professor gesturing up toward the board"),
("A3_SH19","LIDA_YOUNG","classroom_hers_90s",
 "the young teacher and her class planting a thin sapling seen through the classroom window, small figures with a spade and a watering can in the school yard beyond the glass",
 "WS","eye","static","day",False,False,
 "с классом вы сажаете под окнами тонкий клён, и саня зачем-то отдаёт ему честь лопатой.",
 "small figures beyond the glass tamping soil around the sapling, a watering can tipping, the thin trunk swaying"),
("A3_SH20","SANYA_KID","classroom_hers_90s",
 "the black-haired boy at the blackboard struggling through a problem, tongue in cheek, the young teacher's hand visible pointing him one step further along the chalk line",
 "MS","eye","static","day",False,False,
 "ты тянешь саню на тройки так упрямо, что однажды он от неожиданности получает четыре.",
 "his chalk hand hesitating, then adding one more figure, his shoulders straightening in disbelief"),
("A3_SH21","LIDA_YOUNG","teachers_room",
 "the young teacher listening at the staff-room table as an older colleague taps a postgraduate brochure lying on the green baize, tea steaming between them",
 "CU","eye","static","evening",False,False,
 "завуч листает твою аспирантскую брошюру и говорит без злобы, сначала выпусти свой класс.",
 "the older hand tapping the brochure twice, her own hand drawing it slowly back across the baize"),
("A3_SH22","LIDA_YOUNG","lida_kitchen",
 "the young teacher at her kitchen wall moving the pinned three-year plan sheet one hook lower, beneath the calendar, her face quiet and reasonable",
 "MS","eye","static","night",False,True,
 "ты переносишь аспирантуру на следующий год, в первый раз, и это кажется просто здравым смыслом.",
 "her hands unpinning the plan sheet and repinning it lower, smoothing the paper flat against the wall"),
("A3_SH23",None,"lida_kitchen",
 "a squared paper plan pinned low on a kitchen wall, the word for postgraduate study visible with a new pencilled date squeezed above the old crossed one, lamplight",
 "INSERT","eye","push_in","night",True,False,
 "на листке в клетку появляется вторая дата, аккуратная, карандашом, чтобы легко было поправить."),
("A3_SH24","LIDA_YOUNG","school_yard",
 "the young teacher with her class of now six-graders around the young maple, taller by a head, autumn leaves bright, children horsing around the thin trunk",
 "WS","eye","static","day",False,False,
 "твой пятый б становится шестым, потом седьмым, и клён под окнами обгоняет их в росте.",
 "children circling the young maple, one leaping to touch its crown, leaves shaking loose and drifting"),
("A3_SH25","LIDA_YOUNG","classroom_hers_90s",
 "the teacher of twenty-five checking a stack of essays at her classroom desk after lessons, winter twilight blue in the tall windows, one lamp lit over her work",
 "MS","high","static","evening",False,False,
 "к девяносто третьему ты проверила столько сочинений, что почерк любого узнаёшь со спины.",
 "her pen pausing over a page, her head tilting in recognition, the lamp humming softly over the essays"),
("A3_SH26","KATYA_KID","school_corridor",
 "the copper-haired girl with round glasses reading a wall newspaper far down the long school corridor, small against the receding doors, afternoon light pooling along the painted floor",
 "WS","eye","static","day",False,False,
 "катя выигрывает городскую олимпиаду, и её сочинение вешают в коридоре под стеклом.",
 "her head tilting as she reads her own printed lines, her fingers adjusting the book under her arm"),
("A3_SH27","LIDA_YOUNG","school_corridor",
 "the young teacher standing before the framed essay in the corridor, hands clasped behind her back in unconscious copy of her own first teacher, smiling faintly",
 "MCU","eye","static","day",False,True,
 "ты стоишь перед её сочинением, сложив руки за спиной, точно как тамара павловна когда-то.",
 "her clasped hands settling at the small of her back, her chin rising, the faint smile deepening"),
("A3_SH28",None,"classroom_hers_90s",
 "the empty classroom at dusk, chairs upturned on desks, the green board washed clean and drying in streaks, a forgotten purple aster lying on the front desk",
 "WS","eye","pull_out","evening",True,False,
 "третий год распределения кончается в июне, и заявление об уходе так и лежит ненаписанным."),
("A3_SH29","LIDA_YOUNG","classroom_hers_90s",
 "the young teacher alone in the dusk classroom, holding the washed-out rag over the chalk rail, looking at the clean board with the calm of a decision already made",
 "MS","eye","push_in","evening",False,True,
 "ты решаешь остаться ещё на год, всего на один, чтобы довести их до экзаменов.",
 "the rag settling folded on the chalk rail, her hand smoothing it flat, her gaze steady on the clean board"),
("A3_SH30","OBJ:chalk",None,
 "a wooden box of chalk on the rail of a washed green board at dusk, most sticks worn to stubs, one long stick left standing upright in the corner slot",
 "ECU","eye","static","evening",False,False,
 "в коробке за три года не осталось целых кусков, кроме одного, который ты бережёшь."),
]

seed_act("medal",PAL2,MEDAL,render_mode="animated")
seed_act("first_bell",PAL3,BELL,render_mode="animated")
