# -*- coding: utf-8 -*-
"""webcam A10 aftermath + A11 coda. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_webcam_A10A11.py"""
from _webcam_engine import seed_act

P_AFT="burned-out palette, dead grey and cold blue, the neon gone, only leftover ash-light"
P_CODA="final dark palette, one last ring-light glow fading to black, still and bare"

AFT=[
 ("A10_SH01",None,"own_apartment","a wide view of a downsized dim apartment with packing boxes, the neon gone, cold grey light","WS","eye","push_in","day",True,False,
  "в тридцать четыре ты никому не нужна, ни зрителям, ни студии, ни тем тысячам, что клялись в любви."),
 ("A10_SH02","HERO_OLD","stream_room","a medium shot of the woman trying to stream under a new name, the room feeling like a trap","MS","eye","static","night",False,False,
  "ты пробуешь стримить под новым именем, но лицо помнят, и каждый эфир превращается в травлю."),
 ("A10_SH03","HERO_OLD","stream_room","a close-up of the woman realizing the internet never lets her go","CU","eye","static","night",False,False,
  "оказывается, из интернета нельзя уйти, всё, что ты снимала за пятнадцать лет, осталось там навсегда."),
 ("A10_SH04",None,None,"an extreme close-up macro insert of an empty jar and a phone showing an empty balance, numbers unreadable, filling the frame in sharp focus, shallow depth of field","ECU","top","static","day",True,False,
  "ты открываешь счёт и видишь пустоту, ведь ты всегда тратила и никогда не копила на потом."),
 ("A10_SH05","HERO_OLD","own_apartment","a medium shot of the woman selling off expensive things cheaply among moving boxes","MS","eye","static","day",False,False,
  "квартиру приходится менять на дешёвую, дорогие вещи ты продаёшь за бесценок, как чужие подарки."),
 ("A10_SH06","HERO_OLD","own_apartment","a close-up of the woman facing fifteen blank years with nothing she can put on a resume","CU","eye","static","day",False,False,
  "профессии у тебя нет, в резюме пятнадцать лет пустоты, которую нельзя никому показать."),
 ("A10_SH07",None,"city_street_neon","a wide view of an ordinary daytime street, cold and public, no welcome in it","WS","eye","static","day",True,False,
  "ты ищешь обычную работу, но стоит кому-то узнать твоё лицо, и разговор сразу заканчивается."),
 ("A10_SH08","HERO_OLD","bedroom_dark","a medium close-up of the woman alone, abandoned by every fan who claimed to love her","MCU","eye","static","night",False,False,
  "те, кто присылал тебе донаты и писал про любовь, испарились в ту же секунду, как всё вскрылось."),
 ("A10_SH09","HERO_OLD","bedroom_dark","a close-up of the woman's face, not one of thousands there when it mattered","CU","eye","push_in","night",False,False,
  "ни один из тысяч поклонников не подал тебе руки, когда ты действительно осталась ни с чем."),
 ("A10_SH10","DAU_CHILD","kitchen_home","a medium shot of a quiet seven-year-old girl avoiding her mother's eyes at a kitchen table","MS","eye","static","day",False,False,
  "Лиза растёт молчаливой, в школе её дразнят из-за тебя, и она всё реже смотрит тебе в глаза."),
 ("A10_SH11","HERO_OLD","kitchen_home","a close-up of the woman watching her daughter be ashamed of her","CU","eye","static","day",False,False,
  "ты видишь, как дочь стыдится собственной матери, и это больнее всего, что ты пережила."),
 ("A10_SH12",None,None,"an extreme close-up macro insert of a plush toy rabbit abandoned in a corner, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "плюшевый заяц, которого вы делили, теперь лежит в углу, и Лиза давно к нему не подходит."),
 ("A10_SH13","MOTHER_BASE","mother_home","a medium close-up of the grey-haired mother helping stiffly, unable to forgive","MCU","eye","static","day",False,False,
  "мать общается с тобой сквозь зубы, помогает с Лизой, но простить и понять тебя не может."),
 ("A10_SH14","HERO_OLD","mother_home","a close-up of the woman who has lost her mother's trust for good","CU","eye","static","day",False,False,
  "ты потеряла её доверие так же, как потеряла всё остальное, тихо и, кажется, навсегда."),
 ("A10_SH15",None,"bedroom_dark","a wide view of a dark bedroom at night with a dead monitor, silent, no notifications","WS","eye","static","night",True,False,
  "по ночам ты лежишь в темноте, и в тишине нет ни одного дзынь, к которому ты привыкла."),
 ("A10_SH16","HERO_OLD","bedroom_dark","a medium close-up of the woman imagining her daughter's future search","MCU","eye","static","night",False,False,
  "ты представляешь, как Лиза станет подростком и будет искать в сети то, что ты натворила."),
 ("A10_SH17","DAU_TEEN","bedroom_dark","a close-up of an imagined guarded teenage girl of fifteen ashamed of her family name, wary hurt eyes","CU","eye","push_in","night",False,False,
  "ты видишь её взрослой, стыдящейся своей фамилии, и понимаешь, что оставила ей это в наследство."),
 ("A10_SH18","HERO_OLD","bedroom_dark","a medium close-up of the woman counting what fifteen years bought her, nothing","MCU","eye","static","night",False,False,
  "пятнадцать лет камеры не купили тебе ни будущего, ни семьи, ни даже спокойной старости."),
 ("A10_SH19",None,None,"an extreme close-up macro insert of a dead ring light standing in a corner, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,False,
  "кольцевая лампа стоит в углу мёртвая, и ты не можешь ни выбросить её, ни включить снова."),
 ("A10_SH20","HERO_OLD","own_apartment","a medium shot of the woman sitting among boxes as her whole adult life is gone into screens","MS","eye","static","day",False,False,
  "ты сидишь среди коробок и понимаешь, что вся твоя взрослая жизнь ушла в чужие экраны бесследно."),
 ("A10_SH21","HERO_OLD","own_apartment","a close-up of the woman watched by thousands yet alone when it counted","CU","eye","static","day",False,False,
  "тысячи людей смотрели на тебя каждый вечер, а рядом в трудный час не оказалось никого."),
 ("A10_SH22",None,None,"an extreme close-up macro insert of a velvet star choker lying in an open drawer, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "в ящике лежит бархатный чокер со звёздочкой, костюм Алисы, которую больше никто не хочет смотреть."),
 ("A10_SH23",None,"own_apartment","a wide view of a neon city glowing through a window, promising the same short tale to other girls","WS","eye","static","night",True,False,
  "за окном чужой город горит рекламой, обещая другим девочкам ту же лёгкую и короткую сказку."),
 ("A10_SH24","HERO_OLD","own_apartment","a close-up of the woman of thirty-four, her whole life reduced to a dead lamp and a choker","CU","eye","push_in","day",False,True,
  "тебе тридцать четыре, и вся твоя жизнь уместилась в мёртвую лампу и чокер в ящике стола."),
]

CODA=[
 ("A11_SH01","HERO_OLD","stream_room","a close-up of the woman of thirty-four speaking quietly and directly to the viewer in dim light","CU","eye","push_in","night",False,False,
  "я рассказала тебе это не чтобы напугать, а чтобы ты поняла, куда ведут лёгкие деньги в камеру."),
 ("A11_SH02","HERO_OLD","stream_room","a medium shot of the woman sitting before a ring light one last time, not for viewers","MS","eye","static","night",False,False,
  "сегодня я в последний раз села перед кольцевой лампой, уже не ради зрителей, а ради тебя."),
 ("A11_SH03",None,None,"an extreme close-up macro insert of a finger resting on a ring-light switch, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","push_in","night",True,False,
  "мой палец лежит на выключателе лампы, которая пятнадцать лет решала, кто я в этот вечер."),
 ("A11_SH04","HERO_OLD","stream_room","a close-up of the woman still wearing the velvet star choker she could never take off","CU","eye","static","night",False,False,
  "на шее всё ещё бархатный чокер, костюм Алисы, которую я так и не смогла с себя снять."),
 ("A11_SH05","HERO_OLD","stream_room","a medium close-up of the woman clicking the switch as the light dies for the last time","MCU","eye","static","night",False,False,
  "я щёлкаю выключателем, и кольцевая лампа гаснет в последний раз, тихо, без единого дзынь."),
 ("A11_SH06",None,None,"an extreme close-up macro insert of a ring light going dark to black in a dim room, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,True,
  "свет уходит, экран становится чёрным, и в этой темноте наконец нет ни одного чужого взгляда."),
 ("A11_SH07","HERO_OLD","bedroom_dark","a wide shot of the woman sitting alone in the dark, the bright girl of nineteen long gone","WS","eye","pull_out","night",False,False,
  "я сижу в темноте одна, и той весёлой девочки из девятнадцати лет во мне давно уже нет."),
 ("A11_SH08","HERO_OLD","bedroom_dark","a close-up of the woman looking directly at the viewer, worn and honest","CU","eye","push_in","night",False,False,
  "если тебе сейчас говорят, что камера — это лёгкие деньги и свобода, подпишись и дослушай."),
 ("A11_SH09","HERO_OLD","bedroom_dark","a medium shot of the woman speaking plainly to the viewer in the dark","MS","eye","static","night",False,False,
  "потому что берут у тебя годы, лицо, имя и семью, а отдают лайки, которые гаснут за секунду."),
 ("A11_SH10",None,None,"an extreme close-up macro insert of a velvet choker laid on a dark desk beside a dead ring light, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "я кладу бархатный чокер на стол в темноте, рядом с мёртвой лампой, и больше его не надену."),
 ("A11_SH11",None,"stream_room","a wide view of a dark empty streaming room, the fairy lights off, still and hollow","WS","eye","static","night",True,False,
  "комната, где я провела полжизни перед камерой, стоит тёмная и пустая, как и я сама."),
 ("A11_SH12","HERO_OLD","bedroom_dark","a close-up of the woman glancing toward the wall behind which her daughter sleeps","CU","eye","static","night",False,False,
  "за стеной спит моя дочь, которая теперь всё знает, и это единственный зритель, чьё мнение важно."),
 ("A11_SH13","HERO_OLD","bedroom_dark","a medium shot of the woman quiet in the dark, one true thing left to her","MS","eye","static","night",False,False,
  "ей я больше не солгу, и это, кажется, единственное, что у меня осталось настоящего."),
 ("A11_SH14","HERO_OLD","bedroom_dark","a close-up of the woman's calm final face looking at the viewer in the last faint light","CU","eye","push_in","night",False,True,
  "эта история вымышлена, любые совпадения случайны, но чья-то лампа прямо сейчас включается в первый раз."),
]

if __name__=="__main__":
    seed_act("aftermath", P_AFT, AFT, render_mode="static")
    seed_act("coda",      P_CODA, CODA, render_mode="static")
