# -*- coding: utf-8 -*-
"""Batch 2: act02_youth + act03_linda + act04_movement."""
from _flat_earth_engine import seed_act

PAL_YOUTH = "muted late-1990s palette, cool fluorescent and warm tungsten mix, faded denim blue and tobacco brown, grainy"
A2 = [
 ("A2_SH01",None,"tv_repair_shop","a cramped electronics repair shop crowded with opened CRT television sets on metal shelves, a soldering bench, buzzing fluorescent tubes","WS","eye","pan_right","day",True,False,
  "тебе семнадцать, ты бросаешь школу и идёшь чинить телевизоры в мастерскую на окраине."),
 ("A2_SH02","RAY_YOUNG","tv_repair_shop","a wiry young man in a checked shirt bent over a soldering bench, the back off a television, iron in hand","MS","eye","static","day",False,False,
  "ты целыми днями чинишь экраны, и каждый день думаешь, какую же ложь они показывают людям по вечерам."),
 ("A2_SH03","RAY_YOUNG","tv_repair_shop","close on the young man's steady hands and intent face inside the glowing guts of an old television set","CU","over","push_in","day",False,False,
  "ты знаешь эту коробку изнутри, до последнего провода, и потому веришь ей ещё меньше, чем другие."),
 ("A2_SH04","RAY_YOUNG","tv_repair_shop","the young repairman leaning across the counter lecturing a tired customer who clutches a small television, edging back","OTS","eye","static","day",False,False,
  "ты возвращаешь клиенту телевизор и бесплатно объясняешь, что новости по нему врут про форму земли."),
 ("A2_SH05",None,"tv_repair_shop","a customer hurrying out the shop door with a television under one arm, glancing back warily, the bell still swinging","WS","eye","static","day",False,False,
  "клиент кивает, забирает свой ящик и больше не возвращается, и так уходит почти каждый из них."),
 ("A2_SH06",None,"tv_repair_shop","extreme close on a repaired television screen showing a spinning globe on an evening news broadcast","INSERT","eye","static","night",False,True,
  "по вечерам с каждого починенного экрана на тебя смотрит один и тот же крутящийся синий шар."),
 ("A2_SH07","RAY_YOUNG","tv_repair_shop","the young man standing alone in the dark shop lit only by the glow of the globe on the screen, arms folded, certain","MCU","low","push_in","night",False,False,
  "и каждый раз ты говоришь вслух пустой мастерской, нет, ребята, это просто красивая картинка."),
 ("A2_SH08",None,"public_library","tall metal stacks of bound reference volumes in a quiet public library, long wooden tables with green-shaded lamps","WS","high","pan_left","day",True,False,
  "по выходным ты сидишь в библиотеке от открытия до закрытия, и собираешь свою папку с доказательствами."),
 ("A2_SH09","RAY_YOUNG","public_library","the young man hunched at a microfiche reader, scribbling in a thick notebook, surrounded by open books","MS","eye","static","day",False,False,
  "ты выписываешь старые карты, опыты с водой, цитаты, и тебе кажется, что узор складывается сам собой."),
 ("A2_SH10",None,"public_library","extreme close on a notebook page dense with hand-drawn flat discs, ruler lines across seas, and underlined notes","ECU","top","push_in","day",False,True,
  "к двадцати годам твоя папка толще библии, и в ней одна простая мысль, линия воды всегда ровная."),
 ("A2_SH11",None,"dawson_house_living","a modest rented living room where one wall is beginning to fill with pinned maps and a few clippings on a corkboard","WS","eye","push_in","day",False,False,
  "ты снимаешь комнату, и первое, что вешаешь на стену, это большая карта мира без всякого изгиба."),
 ("A2_SH12","RAY_YOUNG","dawson_house_living","the young man pressing a pin into a wall map, head tilted, lips moving as he talks himself through it","CU","eye","static","day",False,False,
  "ты соединяешь точки красной нитью, и каждая ниточка для тебя это ещё один гвоздь в их большую ложь."),
 ("A2_SH13",None,"east_nash_street","an ordinary Nashville street at midday, a young man walking with a roll of charts under his arm, a neighbour on a porch watching warily","WS","eye","track","day",False,False,
  "соседи уже знают тебя, и здороваются осторожно, как здороваются с тем, кого считают чуть тронутым."),
 ("A2_SH14",None,"east_nash_street","two young women crossing to the far sidewalk away from an approaching young man, glancing at each other","MS","high","static","day",False,False,
  "девушки переходят на другую сторону, а ты идёшь своей дорогой, и говоришь себе, что им просто страшно знать правду."),
 ("A2_SH15",None,"percy_priest_lake","a young man crouched on a jetty laying a long carpenter's level on a board sighting along it to the flat far shore","WS","low","static","day",False,True,
  "ты ставишь на пирсе свой первый настоящий опыт, длинный уровень вдоль воды на пятьсот футов."),
 ("A2_SH16",None,"percy_priest_lake","extreme close on a spirit level's bubble sitting dead centre between its lines against the flat water beyond","ECU","eye","push_in","day",False,True,
  "пузырёк замирает ровно посередине, ровно, ни на волос в сторону, и сердце у тебя заходится."),
 ("A2_SH17","RAY_YOUNG","percy_priest_lake","the young man standing on the jetty, fist raised in quiet triumph, the flat lake stretching behind him","MCU","low","push_in","day",False,True,
  "вот оно, говоришь ты воде, ровно, я же знал, и тот детский холодок снова бежит по спине."),
 ("A2_SH18",None,"gas_station_dickerson","the old gas station now run-down at dusk, one pump bagged over, peeling paint, a faded closed sign in the window","WS","eye","push_in","dusk",True,False,
  "отцовская заправка тем временем умирает, большие сети задушили её, и отец сдаёт всё сильнее."),
 ("A2_SH19","FATHER","gas_station_dickerson","the gaunt aging father behind the register coughing into a fist, the shelves half empty, dim light","MS","eye","static","dusk",False,False,
  "он кашляет за кассой, и всё повторяет, держись правды, сынок, она единственное, что у нас не отнять."),
 ("A2_SH20","FATHER","gas_station_dickerson","close on the father's weathered hand gripping the young man's wrist across the counter, urgent and frail","CU","eye","push_in","dusk",False,False,
  "в свой последний год он сжимает твою руку и говорит, ты единственный, кто меня не считал дураком."),
 ("A2_SH21",None,"ridge_overlook","a bleak Tennessee cemetery hillside at grey dawn, a single fresh grave with raw earth and a small marker, flat haze beyond","EWS","high","static","dawn",True,False,
  "ты хоронишь его в двадцать три, и на поминках нет почти никого, только ты и эта ровная даль."),
 ("A2_SH22","RAY_YOUNG","ridge_overlook","the young man standing alone at a fresh graveside in the cold dawn, the brass ruler held in both hands","MCU","eye","static","dawn",False,True,
  "ты стоишь у могилы с его линейкой в руках, и обещаешь, что докажешь то, во что верил он один."),
 ("A2_SH23",None,"ridge_overlook","extreme close on the worn brass folding ruler clasped tight in two hands against a dark coat","ECU","eye","push_in","dawn",False,True,
  "латунь холодит ладони, и в этот момент правда о плоской земле становится всем, что у тебя осталось."),
 ("A2_SH24",None,"dawson_house_living","the rented room at night, the map wall now larger and denser, a single lamp, a young man's shadow across the charts","WS","eye","push_in","night",False,False,
  "ты возвращаешься в комнату с картами, и понимаешь, что теперь некому будет даже выслушать тебя."),
 ("A2_SH25","RAY_YOUNG","dawson_house_living","the young man writing a vow across the bottom of a giant wall map with a marker, jaw set","MCU","low","static","night",False,False,
  "ты пишешь маркером внизу карты одно слово, докажу, и впервые тебе по-настоящему одиноко на свете."),
 ("A2_SH26",None,"east_nash_street","a lit single window in a dark Nashville street at night, the silhouette of a man among hanging charts inside","WS","eye","pull_out","night",True,False,
  "в окне горит свет, единственный на улице, и за ним человек разговаривает с картами, потому что больше не с кем."),
]

PAL_LINDA = "warm hopeful late-1990s palette, soft tungsten gold, optimistic ambers and clean daylight"
A3 = [
 ("A3_SH01","LINDA","tv_repair_shop","a warm woman with a dark chin-length bob setting a broken portable television on the repair counter, smiling shyly","MS","eye","static","day",False,False,
  "однажды в мастерскую заходит линда, с тёплыми глазами и сломанным телевизором, и приносит починить."),
 ("A3_SH02","RAY_YOUNG","tv_repair_shop","the young repairman working on the small television while talking earnestly, a woman waiting and listening, amused","OTS","over","static","day",False,False,
  "ты чинишь её ящик и, как всегда, заодно объясняешь, почему по нему врут, и ждёшь, что она уйдёт."),
 ("A3_SH03","LINDA","tv_repair_shop","close on the woman's face, chin on hand, listening with a soft amused fondness rather than fear","CU","eye","push_in","day",False,False,
  "но линда не уходит, она смеётся, и говорит, ты первый мужчина, который верит хоть во что-то всерьёз."),
 ("A3_SH04",None,"east_nash_street","a young man and woman walking a leafy Nashville street in golden afternoon light, a little apart, talking","WS","eye","track","day",False,False,
  "вы начинаете гулять по вечерам, и ты впервые в жизни рассказываешь кому-то всё, и тебя не гонят."),
 ("A3_SH05",None,"percy_priest_lake","a man showing a woman a brass ruler held against the flat lake horizon on a jetty at golden hour, both small","WS","low","static","dusk",False,True,
  "ты приводишь её на озеро и показываешь линейкой ровную воду, своё главное доказательство любви."),
 ("A3_SH06","LINDA","percy_priest_lake","the woman humouring the man with a tender smile, hugging her own arms in the dusk light by the water","MCU","eye","static","dusk",False,False,
  "она не спорит, она просто смотрит на тебя, и тихо говорит, может, ты и прав, кто его знает."),
 ("A3_SH07","RAY_YOUNG","percy_priest_lake","close on the young man's face lit with rare joy, certain he has been finally understood","CU","eye","push_in","dusk",False,False,
  "и ты решаешь, что она единственная на земле, кто способен увидеть то же, что видишь ты."),
 ("A3_SH08","LINDA","dawson_house_living","the woman standing in the doorway of the map-covered room, smile faltering for a second as she takes in the walls","MS","eye","push_in","day",False,False,
  "ты впервые приводишь её в комнату с картами, и на секунду улыбка её гаснет, но только на секунду."),
 ("A3_SH09","LINDA","dawson_house_living","close on the woman choosing to smile again, eyes moving over the red strings and pinned discs","CU","eye","static","day",False,False,
  "она решает, что это милое чудачество, безобидное хобби, и в этом её главная ошибка, и твоя."),
 ("A3_SH10","RAY_YOUNG","dawson_kitchen","the young man across a small kitchen table holding out a tiny ring box, nervous and earnest, coffee mugs between them","MCU","eye","static","day",False,False,
  "через год ты делаешь ей предложение на кухне за чашкой кофе, без колена, просто протягиваешь коробочку."),
 ("A3_SH11",None,"dawson_kitchen","extreme close on a thin silver wedding band being slid onto a woman's finger across a yellow formica table","ECU","over","push_in","day",False,True,
  "тонкое серебряное кольцо садится ей на палец, простое, дешёвое, ты копил на него три месяца."),
 ("A3_SH12",None,"east_nash_street","a small modest civil wedding outside a county courthouse, a couple on the steps, a few guests, confetti","WS","low","static","day",False,False,
  "вы расписываетесь в ратуше, гостей горстка, и это самый счастливый день в твоей короткой нормальной жизни."),
 ("A3_SH13","LINDA","east_nash_street","close on the bride in a plain cream dress laughing on the courthouse steps, confetti in her dark bob","CU","eye","static","day",False,True,
  "линда смеётся в простом платье, с конфетти в волосах, и ты думаешь, теперь у тебя есть свой человек."),
 ("A3_SH14",None,"dawson_kitchen","a newlywed couple unpacking boxes in a small rented house, the man already taping a map to the kitchen wall","MS","eye","static","day",False,False,
  "вы снимаете домик, и пока линда расставляет тарелки, ты вешаешь на кухне первую карту, по привычке."),
 ("A3_SH15","LINDA","dawson_kitchen","the woman pausing with a plate in hand, watching the man pin a map, a small unreadable look","MCU","eye","push_in","day",False,False,
  "она смотрит, как ты прикалываешь её, и ничего не говорит, но что-то в её лице чуть-чуть меняется."),
 ("A3_SH16",None,"dawson_kitchen","a cosy evening kitchen, a couple at dinner, a television murmuring news, the man gesturing at the screen","WS","eye","static","night",False,False,
  "по вечерам вы ужинаете под новости, и ты беззлобно споришь с диктором, а линда смеётся над тобой."),
 ("A3_SH17","LINDA","dawson_kitchen","close on the woman laughing warmly over dinner, shaking her head at the man off-frame","CU","eye","static","night",False,False,
  "она думает, что с годами это пройдёт, что ты остепенишься, заведёшь нормальные тихие заботы."),
 ("A3_SH18",None,"percy_priest_lake","two small figures sitting close together on a jetty at dusk, the flat lake gold behind them, peaceful","EWS","eye","pull_out","dusk",True,True,
  "и какое-то короткое время так и есть, вы счастливы, и ровная линия воды просто красивый закат."),
 ("A3_SH19","LINDA","percy_priest_lake","close on the woman's hand in the man's on the weathered jetty boards, the thin silver ring catching the last light","ECU","high","push_in","dusk",False,False,
  "её рука в твоей, кольцо ловит последний свет, и ты клянёшься себе беречь её, чего бы это ни стоило."),
 ("A3_SH20",None,"dawson_kitchen","a quiet kitchen at night, the yellow formica table empty except for two coffee mugs and a folded newspaper","WS","high","static","night",True,False,
  "ты ещё не знаешь, что пройдут годы, и за этим самым столом всё для вас и закончится."),
 ("A3_SH21",None,"dawson_kitchen","extreme close on the empty corner of the yellow formica table where a thin silver ring will one day be left","INSERT","top","push_in","night",False,True,
  "ты не знаешь, что однажды это кольцо останется лежать вот здесь, на этом столе, без неё."),
 ("A3_SH22","RAY_YOUNG","dawson_house_living","the young man asleep in a chair under the map wall, content, a wedding photo propped among the charts","MCU","eye","push_in","night",False,False,
  "но пока ты засыпаешь счастливым под своими картами, и тебе кажется, что теперь у тебя есть всё."),
]

PAL_MOVE = "dim earnest meeting-room palette, warm coffee-urn light against cold projector glow, brown veneer and amber"
A4 = [
 ("A4_SH01",None,"gas_station_dickerson","extreme close on a hand-lettered flyer pinned to a gas-station corkboard, a flat disc logo and the words the truth meets tuesdays","INSERT","eye","push_in","day",False,True,
  "тебе тридцать, и однажды на доске у заправки ты видишь листок, истина собирается по вторникам."),
 ("A4_SH02",None,"movement_backroom","the back room of a strip-mall shop set with a ring of metal folding chairs, a pull-down screen, a coffee urn, a flat-earth banner","WS","eye","push_in","night",False,False,
  "ты приходишь во вторник в подсобку за магазином, складные стулья, кофейник, и десяток таких же, как ты."),
 ("A4_SH03","EARL","movement_backroom","a bald heavyset man in smoked aviators and a cheap blazer holding court by a projector, a flat-earth disc pin on his lapel","MS","low","static","night",False,True,
  "перед ними стоит эрл, лысый, в дымчатых очках, и говорит так уверенно, как никто на свете до него."),
 ("A4_SH04","EARL","movement_backroom","close on the man's smoked aviator glasses and the round flat-earth enamel pin glinting on his lapel","CU","eye","push_in","night",False,True,
  "на лацкане у него круглый значок, плоский диск земли, и ты весь вечер не можешь отвести от него глаз."),
 ("A4_SH05","RAY_YOUNG","movement_backroom","a man sitting among the folding chairs leaning forward, face lit by the projector glow, rapt and belonging","OTS","over","push_in","night",False,False,
  "ты слушаешь два часа, не дыша, и впервые в жизни оказываешься среди людей, которые тебя понимают."),
 ("A4_SH06","RAY_YOUNG","movement_backroom","close on the man's face washed by cold projector light, eyes wet with the relief of belonging","CU","eye","push_in","night",False,False,
  "ты чуть не плачешь, тридцать лет ты был один, а тут целая комната кивает каждому твоему слову."),
 ("A4_SH07",None,"movement_backroom","a small circle of seated people nodding together toward an off-frame speaker, a projector beam over their heads","WS","high","static","night",False,False,
  "вы передаёте по кругу папки и опыты, и ты достаёшь свою, и впервые её никто не поднимает на смех."),
 ("A4_SH08",None,"movement_backroom","extreme close on a projector screen showing an azimuthal flat-earth disc map with the ice wall around the rim","INSERT","eye","push_in","night",False,True,
  "на экране карта, плоский круг, а по краю кольцо льда, антарктида как стена, что держит океан."),
 ("A4_SH09","EARL","movement_backroom","the bald man in aviators shaking the newcomer's hand warmly, gripping his shoulder, welcoming him in","MS","eye","static","night",False,False,
  "эрл жмёт тебе руку, говорит, добро пожаловать домой, сынок, и это слово, домой, бьёт тебя под рёбра."),
 ("A4_SH10","RAY_YOUNG","movement_backroom","the man counting cash from his wallet onto a table stacked with pamphlets and enamel pins","MCU","high","static","night",False,False,
  "в первый же вечер ты отдаёшь сорок долларов за брошюры и значок, и уносишь их домой, как святыню."),
 ("A4_SH11",None,"movement_backroom","extreme close on a flat-earth disc enamel pin being fastened onto a worn canvas jacket lapel","ECU","eye","push_in","night",False,True,
  "ты прикалываешь значок на куртку, точно такой же, как у эрла, и теперь ты не один, ты часть своих."),
 ("A4_SH12",None,"east_nash_street","a man walking home through dark Nashville streets at night, energized, a stack of pamphlets under his arm","WS","low","track","night",True,False,
  "ты идёшь домой за полночь, и впервые за годы тебе легко, потому что теперь есть на кого опереться."),
 ("A4_SH13","RAY_YOUNG","dawson_kitchen","an excited man at the kitchen table spreading pamphlets before a woman, talking fast, eyes shining","MCU","eye","static","night",False,False,
  "ты вываливаешь брошюры на кухонный стол перед линдой, и говоришь без умолку про эрла и про своих."),
 ("A4_SH14","LINDA","dawson_kitchen","the woman across the table with a careful smile that does not reach her eyes, holding her coffee with both hands","CU","eye","push_in","night",False,False,
  "линда улыбается осторожно, и спрашивает, сколько стоят эти брошюры, и ты впервые ей не отвечаешь."),
 ("A4_SH15","RAY_YOUNG","movement_backroom","the man now helping unfold chairs and set up the projector before a meeting, at home among the group","MS","eye","static","night",False,False,
  "очень скоро ты приходишь раньше всех, расставляешь стулья, варишь кофе, ты уже свой в этом кругу."),
 ("A4_SH16","EARL","movement_backroom","the bald man in aviators leaning in close to confide in the younger man, an arm around his shoulders","OTS","over","static","night",False,False,
  "эрл выделяет тебя, обнимает за плечи, шепчет, ты особенный, рэй, ты пойдёшь дальше всех нас."),
 ("A4_SH17","EARL","movement_backroom","close on the bald man's smoked aviators reflecting the rapt younger man's face in two small ovals","CU","eye","push_in","night",False,True,
  "в его тёмных очках ты видишь только своё отражение, и тебе это даже нравится, ты ему веришь весь."),
 ("A4_SH18",None,"movement_backroom","a small group posing for a photo under a hand-painted flat-earth banner, arms over shoulders, proud","WS","eye","static","night",False,False,
  "вы фотографируетесь под самодельным баннером, плечом к плечу, и ты в самом центре, рядом с эрлом."),
 ("A4_SH19",None,"dawson_house_living","the home map wall now huge and meticulously organized with labels, photos of the group pinned among the charts","WS","eye","pan_right","day",False,False,
  "дома твоя стена растёт, теперь на ней не только карты, но и фотографии своих, твоей новой семьи."),
 ("A4_SH20","RAY_YOUNG","dawson_house_living","the man on a landline phone taking notes eagerly, ordering something, cash and a catalogue on the desk","MCU","eye","static","day",False,False,
  "ты заказываешь по телефону приборы, лазеры, уровни, всё, чем эрл обещает доказать форму земли."),
 ("A4_SH21",None,"dawson_kitchen","extreme close on a thin stack of dwindling cash beside a mail-order receipt on the formica table","ECU","top","push_in","day",False,False,
  "семейные сбережения тают по сорок, по двести долларов, и ты прячешь чеки в карман, как когда-то отец."),
 ("A4_SH22","EARL","movement_backroom","the bald man selling glossy conference tickets from a folder to eager members, the younger man first in line","MS","eye","static","night",False,False,
  "эрл объявляет большой съезд плоскоземельщиков, билет двести долларов, и ты записываешься первым."),
 ("A4_SH23","RAY_YOUNG","movement_backroom","close on the man's hopeful shining face as he pockets a glossy conference ticket like a treasure","CU","low","push_in","night",False,False,
  "ты держишь билет, как приглашение в рай, и думаешь, вот теперь всё точно изменится, вот теперь увидят."),
 ("A4_SH24",None,"movement_backroom","extreme close on a glossy flat-earth conference ticket with a disc logo and a date, held in two hands","INSERT","top","static","night",False,True,
  "на билете нарисован тот самый плоский круг, и ты ещё не знаешь, что эрл просто продаёт вам мечту."),
 ("A4_SH25",None,"east_nash_street","two men leafleting houses along a Nashville street in daylight, porches silent, no doors opening","WS","high","static","day",False,False,
  "по выходным вы разносите листовки по домам, и двери не открываются, но тебя это совсем не смущает."),
 ("A4_SH26","RAY_YOUNG","east_nash_street","the man smiling undeterred on an empty porch, sliding a leaflet under a closed door, certain","MCU","low","push_in","day",False,False,
  "ты подсовываешь листок под дверь и улыбаешься, ничего, говоришь ты себе, однажды они все увидят."),
]

seed_act("act02_youth",   PAL_YOUTH, A2)
seed_act("act03_linda",   PAL_LINDA, A3)
seed_act("act04_movement",PAL_MOVE,  A4)
