# -*- coding: utf-8 -*-
"""teacher acts: tutor (2014, 26 shots) + aula (2018–20, 26 shots). Static.
Run: PYTHONIOENCODING=utf-8 python scripts/_seed_teacher_A8A9.py"""
from _teacher_engine import seed_act

PAL8="glossy palette of dark cabinet lacquer, marble white, chandelier gold and notebook pale-green"
TUTOR=[
("A8_SH01",None,"school_yard",
 "a heavy black SUV parked incongruously at the school gate among teachers' bicycles, autumn maple leaves settling on its polished roof",
 "WS","eye","static","day",True,False,
 "в четырнадцатом году у школьных ворот паркуется машина размером с учительскую зарплату за век."),
("A8_SH02","SANYA_RICH","school_yard",
 "the broad man of thirty-one in an expensive black leather jacket waiting by the school steps with flowers held awkwardly upside down, silver chain bright at his collar",
 "MS","eye","static","day",False,False,
 "у крыльца тебя ждёт саня с букетом, который он держит вниз головой, как гаечный ключ.",
 "the flowers swinging gently upside down in his fist, his weight shifting from foot to foot"),
("A8_SH03","LIDA_MID","school_yard",
 "the teacher of forty-six recognising her old pupil, her face opening in unguarded delight, her hand rising to her mouth, the register bag over her shoulder",
 "CU","eye","static","day",False,False,
 "ты узнаёшь его раньше, чем он здоровается, двоечники девяносто шестого не меняют ухмылку.",
 "her hand rising to her mouth over a spreading smile, the bag strap slipping from her shoulder"),
("A8_SH04","SANYA_RICH","school_yard",
 "the broad man talking with sweeping gestures at the school gate, pointing at himself, at the SUV, at the school, laughing at his own story",
 "MS","eye","static","day",False,False,
 "у него три автосалона, жена, дочка и та же манера рассказывать всё сразу и руками.",
 "his arms sweeping between the SUV, the school and his own chest, his laugh shaking the flowers"),
("A8_SH05","SANYA_RICH","school_yard",
 "the man suddenly serious, holding the flowers right way up now, asking something that costs him effort, his free hand kneading the silver chain",
 "MCU","eye","static","day",False,True,
 "потом он мнёт цепь на шее и просит, лидия андреевна, возьмите мою таньку, она тонет.",
 "his fingers kneading the chain link by link, the flowers now held correctly, his grin gone"),
("A8_SH06","LIDA_MID","lida_kitchen",
 "the teacher's hands holding a pharmacy receipt against the lamplight, her mother's letter and a thin pay slip beside it on the oilcloth",
 "INSERT","top","static","night",False,False,
 "вечером ты кладёшь рядом мамин рецепт и свою ставку, и арифметика решает за тебя.",
 "her eyes moving between receipt and pay slip, her finger tracing one line of figures, a slow nod"),
("A8_SH07",None,"sanya_house",
 "an expensive open-plan kitchen and dining room, glossy dark cabinets, a stone island, a huge television, schoolbooks looking small on the vast dining table",
 "WS","eye","pan_left","day",True,False,
 "дом у сани такой, что твоя квартира поместилась бы в его кухне вместе с коридором."),
("A8_SH08","LIDA_MID","sanya_house",
 "the teacher seated at the vast dining table with a nine-year-old girl's exercise book open before her, her worn red pen alien against the stone surface",
 "MS","eye","static","day",False,False,
 "по вторникам и пятницам ты сидишь за каменным столом и учишь санину дочку не бояться букв.",
 "her red pen moving gently along the child's line, her other hand smoothing the page flat on the stone"),
("A8_SH09","LIDA_MID","sanya_house",
 "the teacher's hand and a child's small hand holding the same pencil, tracing a letter together in an exercise book, chandelier light pooling on the page",
 "INSERT","top","static","day",False,True,
 "танька выводит букву, высунув язык, точно как выводил её отец в девяносто шестом."),
("A8_SH10","SANYA_RICH","sanya_house",
 "the broad man leaning in the kitchen archway watching the lesson from a distance, arms crossed, his face soft in a way that does not match the leather jacket",
 "MCU","eye","static","day",False,False,
 "саня смотрит на урок из-за арки с таким лицом, будто в его доме идёт волшебство.",
 "his crossed arms loosening, his shoulder settling into the arch, his eyes fixed on the small lesson"),
("A8_SH11","SANYA_RICH","sanya_house",
 "the man pressing a thick envelope into the teacher's hands at the door with clumsy ceremony, her polite protest visible, his bulk blocking refusal",
 "OTS","over","static","evening",False,False,
 "у двери он суёт тебе конверт и говорит, за час как за день, и не спорьте, я считал.",
 "the envelope pressing into her reluctant hands, his big palms closing her fingers around it"),
("A8_SH12","LIDA_MID","sanya_house",
 "the teacher at the door holding the envelope with two fingers like a strange object, her face working between offence, amusement and simple need",
 "CU","eye","static","evening",False,True,
 "ты держишь конверт двумя пальцами, и в нём лежит ровно то, чего тебе всегда не хватало.",
 "the envelope turning slowly in her two fingers, her jaw setting and releasing, a breath let out"),
("A8_SH13","SANYA_RICH","sanya_house",
 "the man scratching his gelled head at the door, saying something without his grin, the chandelier behind making a crooked halo of him",
 "MCU","eye","static","evening",False,False,
 "вы тогда одна в меня верили, говорит он без ухмылки, а это дороже трёх автосалонов.",
 "his hand working through the gelled hair, his chin dipping, the grin absent for once"),
("A8_SH14","LIDA_MID","street_winter",
 "the teacher walking home from the rich house through first snow, the envelope deep in her bag, her face unresolved between two feelings",
 "WS","eye","track","evening",False,False,
 "домой ты идёшь пешком через первый снег и всю дорогу не знаешь, куда деть глаза.",
 "her steps unhurried through thin first snow, her hand checking the bag strap, her breath slow ribbons"),
("A8_SH15",None,"village_kitchen",
 "the village kitchen table with new medicine boxes arranged in a careful row, a folded shawl, reading glasses on their beaded cord laid beside an opened parcel",
 "INSERT","eye","static","day",True,False,
 "мамины лекарства теперь лежат в доме на месяц вперёд, и посылка приходит без пропусков."),
("A8_SH16","MAMA_BASE","village_kitchen",
 "the old mother of eighty holding a new blood-pressure monitor like a strange bird, reading its box at arm's length through her glasses, the shawl slipping",
 "MCU","eye","static","day",False,False,
 "маме восемьдесят, и она ворчит на новый тонометр, но меряет давление три раза в день.",
 "her hands turning the monitor box at arm's length, her glasses sliding down, a suspicious squint"),
("A8_SH17","LIDA_MID","classroom_hers_2010s",
 "the teacher giving her school lesson with the old full energy, the interactive panel glowing beside the chalk board, her class leaning in",
 "WS","eye","static","day",False,False,
 "в школе ты по-прежнему на ставке с четвертью, и никакой конверт этого не заменяет.",
 "her hand travelling from glowing panel to chalk line, the class following her movement as one"),
("A8_SH18","LIDA_MID","teachers_room",
 "the teacher at the staff-room table where two younger teachers show each other resignation letters, her tea stopped halfway, her eyes on their pages",
 "MS","eye","static","day",False,False,
 "из школы в этот год уходят двое молодых, репетиторство кормит лучше, чем расписание.",
 "the two young hands sliding letters across the baize, her cup pausing at her lips, her eyes lowering"),
("A8_SH19","LIDA_MID","lida_kitchen",
 "the teacher at her kitchen table dividing envelope money into labelled paper strips, her teacher's even hand writing destinations on each strip",
 "MS","high","static","night",False,False,
 "конвертные деньги ты раскладываешь по бумажкам, мама, крыша в посёлке, зимние сапоги.",
 "her hands sorting notes into three labelled strips, the pen adding a word to each in even script"),
("A8_SH20","OBJ:red_pen",None,
 "a worn red pen and a fat white envelope lying side by side on a kitchen table, lamplight equalising them, the pen's chewed cap toward the camera",
 "ECU","eye","static","night",False,True,
 "рядом с конвертом ручка выглядит нищей, но подписи в аттестатах ставят всё-таки ею."),
("A8_SH21","LIDA_MID","sanya_house",
 "the teacher and the small girl high-fiving over a finished exercise book at the stone table, the girl's grin gap-toothed, the teacher's true and open",
 "MS","eye","static","day",False,False,
 "к весне танька читает вслух без запинки, и вы жмёте друг другу пять, как заговорщики.",
 "two palms meeting over the open notebook, the girl bouncing in her chair, the teacher's laugh breaking"),
("A8_SH22","SANYA_RICH","sanya_house",
 "the broad man solemnly shaking the teacher's hand in both of his at the door, the girl hugging her leg, flowers right way up this time on the side table",
 "MCU","eye","static","day",False,False,
 "саня жмёт тебе руку двумя руками и говорит дочке, запомни, таких учителей больше не делают.",
 "her hand disappearing into his two big ones, the child's arms wrapping around the teacher's leg"),
("A8_SH23","LIDA_MID","street_winter",
 "the teacher walking home in spring evening, lighter of step, a child's drawing of a stick-figure teacher sticking out of her bag",
 "WS","eye","track","evening",False,False,
 "домой ты несёшь танькин рисунок, где ты выше дома, и это лучшая рецензия за годы.",
 "her lighter steps past the lamp, the drawing's corner fluttering from the bag, her head a little high"),
("A8_SH24","LIDA_MID","lida_kitchen",
 "the teacher pinning a child's crayon drawing to her kitchen wall beside the old calendar hook, stepping back to judge it level",
 "MCU","eye","static","evening",False,False,
 "рисунок ты вешаешь на гвоздик от старого календарика, и стена сразу становится теплее.",
 "her hands levelling the drawing on the nail, a step back, her head tilting to check the line"),
("A8_SH25",None,"lida_kitchen",
 "the kitchen wall in lamplight, a child's crayon drawing of a giant smiling teacher pinned where a tear-off calendar once hung, the pale calendar ghost still on the wallpaper",
 "INSERT","eye","push_in","night",True,False,
 "на обоях под рисунком остался светлый след от календарика, которым ты мерила три года."),
("A8_SH26","LIDA_MID","lida_kitchen",
 "the teacher of forty-six at her lamplit table looking from the child's drawing to the notebook stack, her face quietly balancing two economies",
 "CU","eye","push_in","night",False,True,
 "тебе сорок шесть, репетиторство платит за жизнь, а школа за то, зачем эта жизнь.",
 "her eyes moving between the pinned drawing and the notebook stack, a slow settling breath"),
]

PAL9="formal palette of dark panelling, projector beam blue, brass warm accents and screen-glow grey"
AULA=[
("A9_SH01",None,"lida_kitchen",
 "a stiff white invitation card with embossed university crest propped against the sugar bowl on a modest kitchen table, morning light across its gilt edge",
 "INSERT","eye","static","morning",True,False,
 "в две тысячи восемнадцатом среди счетов вдруг приходит конверт с золотым гербом столичного университета."),
("A9_SH02","LIDA_MID","lida_kitchen",
 "the teacher of fifty reading the invitation standing up, one hand on her chest bone, her lips moving over the printed lines a second time",
 "MCU","eye","static","morning",False,False,
 "катя защищает докторскую и пишет от руки внизу, приезжайте, без вас всё не так.",
 "her lips rereading the handwritten line, her hand flattening slowly against her breastbone"),
("A9_SH03","LIDA_MID","lida_kitchen",
 "the teacher brushing her one formal jacket by lamplight, the invitation propped before her like sheet music, her good shoes waiting paired by the door",
 "MS","eye","static","night",False,False,
 "ты гладишь свой единственный выходной пиджак и репетируешь перед зеркалом одно слово, поздравляю.",
 "the brush travelling down the jacket's sleeve, her chin lifting as she mouths a silent word"),
("A9_SH04",None,"univer_aula",
 "a grand university assembly hall, dark panelled walls and a high coffered ceiling, steep banks of seats, a long presidium table with green cloth, a glowing projection screen",
 "WS","low","tilt_up","day",True,False,
 "аула университета выше твоей школы вместе с крышей, и потолок здесь в кессонах, как в кино."),
("A9_SH05","KATYA_PROF","univer_aula",
 "the copper-haired woman of thirty-seven at the lectern in a tailored dark-blue suit, round glasses catching the projector beam, commanding the huge hall quietly",
 "MS","low","static","day",False,True,
 "катя стоит за кафедрой так спокойно, будто всю жизнь только это и делала.",
 "her hand turning a page on the lectern, the projector beam shifting across her glasses as she looks up"),
("A9_SH06","LIDA_MID","univer_aula",
 "the teacher in her formal jacket in the last row of the steep hall, sitting very straight, her hands folded on her handbag, small under the coffered ceiling",
 "MCU","eye","static","day",False,False,
 "ты сидишь в последнем ряду, куда сама всегда сажала опоздавших, и не дышишь.",
 "her folded hands tightening on the handbag with each point from the distant lectern, her chin high"),
("A9_SH07","KATYA_PROF","univer_aula",
 "the speaker answering an opponent with a calm precise gesture, the screen of dense text glowing behind her, the presidium leaning together approvingly",
 "WS","eye","static","day",False,False,
 "она отвечает оппонентам так, что старики за зелёным столом переглядываются с удовольствием.",
 "her precise gesture closing an argument, heads at the presidium tilting together, papers settling"),
("A9_SH08","LIDA_MID","univer_aula",
 "the teacher listening in the last row, catching in the speaker's turn of phrase something of her own, her eyes widening a fraction",
 "CU","eye","static","day",False,True,
 "в её обороте про живое слово ты вдруг слышишь собственную интонацию из девяносто пятого.",
 "her eyes widening a fraction, her head tilting toward the distant voice, her breath held"),
("A9_SH09","KATYA_PROF","univer_aula",
 "the new doctor of science at the lectern in applause, raising a hand for quiet, looking up into the last rows searching for one face",
 "MS","eye","static","day",False,True,
 "после решения совета катя поднимает руку и говорит, здесь сидит моя первая учительница.",
 "her raised hand stilling the applause, her eyes sweeping up the banked rows in open search"),
("A9_SH10","LIDA_MID","univer_aula",
 "the whole steep hall turned around toward the teacher in the last row, she half-risen, one hand at her amber ring, caught between pride and mortification",
 "WS","high","static","day",False,True,
 "двести человек оборачиваются к твоему ряду, и ты встаёшь, держась за кольцо, как за перила.",
 "the hall of faces turning in one wave, her body rising unsteadily, her thumb pressed to the ring"),
("A9_SH11","KATYA_PROF","univer_aula",
 "the doctor and her old teacher embracing at the foot of the aula among congratulating clusters, the younger woman's glasses pushed askew against the older shoulder",
 "MCU","eye","static","day",False,False,
 "внизу катя обнимает тебя, съехав очками, и шепчет, это ваша защита тоже, слышите.",
 "the embrace tightening, glasses knocked askew, the younger hands gripping the older shoulders"),
("A9_SH12","LIDA_MID","street_winter",
 "the teacher walking a grand unfamiliar avenue at night with her modest case, looking up at lit university windows, snow beginning in the high lamps",
 "WS","eye","track","night",False,False,
 "вечером ты гуляешь по столице одна и щупаешь в кармане обратный билет, как якорь.",
 "her steps small on the grand avenue, her face lifted to the lit facades, snow drifting into the lamplight"),
("A9_SH13","LIDA_MID","lida_kitchen",
 "the teacher home again placing a photograph from the defence beside the child's crayon drawing on her kitchen wall, adjusting both level",
 "MS","eye","static","evening",False,False,
 "дома ты вешаешь фото с защиты рядом с танькиным рисунком, и они отлично уживаются.",
 "her hands pinning the photograph, then nudging drawing and photo into one level line"),
("A9_SH14",None,"classroom_hers_2010s",
 "the classroom in march twenty-twenty, chairs up on desks mid-week, a paper notice taped to the door glass, spring light over an interrupted lesson diagram on the board",
 "WS","eye","static","day",True,False,
 "в марте двадцатого школу закрывают за одну пятницу, и диаграмма на доске остаётся недописанной."),
("A9_SH15","LIDA_OLD","lida_kitchen",
 "the teacher of fifty-two in reading glasses hunched before an old laptop at her kitchen table, a grid of small pupil faces on the screen, her notes taped around the screen edge",
 "MS","eye","static","day",False,False,
 "уроки переезжают на твою кухню, и весь твой класс теперь помещается в экран ноутбука.",
 "the grid of small faces flickering on the laptop, her finger hunting a key, her head leaning to the screen"),
("A9_SH16","LIDA_OLD","lida_kitchen",
 "the teacher teaching into the laptop camera with full lesson energy, gesturing at a hand-drawn diagram held up to the lens, tea going cold beside",
 "MCU","eye","static","day",False,False,
 "ты ведёшь урок в камеру и держишь перед ней бумажную схему, потому что так виднее.",
 "the paper diagram lifting to the camera, her free hand tracing its arrows, her eyebrows working the lesson"),
("A9_SH17","OBJ:chalk",None,
 "a box of chalk on a classroom rail filmed over with a season's fine dust, one stub lying where a hand left it in march, spring light through empty glass",
 "ECU","eye","push_in","day",False,True,
 "мел лежит в пустом классе нетронутым всю весну, и это неправильно, как остановленные часы."),
("A9_SH18","LIDA_OLD","lida_kitchen",
 "the teacher close to the laptop screen where one small square among the pupil grid stays dark, her finger touching the dark square gently",
 "CU","eye","static","evening",False,False,
 "у мальчика из крайнего квадратика дома нет интернета, и ты возишь ему задания сама.",
 "her fingertip resting on the one dark square in the grid, the other faces flickering around it"),
("A9_SH19","LIDA_OLD","street_winter",
 "the teacher in a cloth mask walking an empty spring street with a folder of printed assignments, the city stilled around her, one magpie crossing the road",
 "WS","eye","track","day",False,False,
 "город стоит пустой, как воскресенье, и только учителя ходят по адресам, как почтальоны.",
 "her steady steps down the empty street, the folder held to her chest, the magpie hopping ahead"),
("A9_SH20","LIDA_OLD","classroom_hers_2010s",
 "the teacher stepping back into her reopened classroom in autumn, standing a moment in the doorway, her hand resting on the nearest desk like a greeting",
 "MS","eye","static","morning",False,True,
 "в сентябре класс открывают, и ты входишь и здороваешься с партами, честно, вслух.",
 "her palm settling on the first desk, patting it twice, her eyes travelling the restored room"),
("A9_SH21","LIDA_OLD","classroom_hers_2010s",
 "the teacher writing the day's date large on the green chalk board, the chalk singing, pupils' heads bright in the morning sun behind her",
 "BACK","eye","static","morning",False,True,
 "ты пишешь на доске дату, и мел стучит после полутора лет так празднично, что класс смеётся.",
 "her chalk hand travelling in glad firm strokes, white dust drifting, young heads turning to each other"),
("A9_SH22","MAMA_BASE","village_kitchen",
 "the very old mother asleep in her chair by the window of the small village kitchen, the shawl over her knees, the treadle machine silent under a folded cloth, afternoon sun across the whole room",
 "WS","eye","static","day",False,False,
 "маме идёт девяносто первый год, и машинку она накрыла платком, как накрывают клетку птицы.",
 "her white head nodding gently in sleep, sun creeping along the folded cloth on the silent machine"),
("A9_SH23","LIDA_OLD","village_kitchen",
 "the teacher sitting on a low stool beside her sleeping mother, holding the old hand with both of hers, thumb over the wedding band, saying nothing",
 "MCU","eye","static","day",False,False,
 "ты сидишь рядом на низкой табуретке и держишь её руку, и обеим этого разговора хватает.",
 "her two hands folded around the old one, her thumb moving slowly over the worn wedding band"),
("A9_SH24",None,"village_street",
 "the settlement street in autumn dusk, the mother's window lit warm, a city bus stop sign new and out of place at the lane's end, leaves crossing the beam of one lamp",
 "EWS","eye","static","evening",True,False,
 "автобус в город теперь ходит дважды в день, и ты успеваешь к маме каждое воскресенье."),
("A9_SH25","LIDA_OLD","classroom_hers_2010s",
 "the teacher at her desk after lessons looking at a printed staff memo, the word for optimisation visible in its header, her reading glasses low on her nose",
 "MCU","eye","static","evening",False,False,
 "а в конце двадцать третьего в учительскую приходит бумага со словом оптимизация в шапке.",
 "her glasses sliding lower as she reads, the memo tilting toward the window light, her mouth thinning"),
("A9_SH26","OBJ:brass_bell",None,
 "a small brass hand bell with a red ribbon bow standing on a staff-room shelf beside stacked class registers, dusk light warming the old metal",
 "ECU","eye","push_in","evening",False,True,
 "звонок на полке в учительской блестит, как в семьдесят пятом, но звенеть ему осталось год."),
]

seed_act("tutor",PAL8,TUTOR,render_mode="animated")
seed_act("aula",PAL9,AULA,render_mode="animated")
