# -*- coding: utf-8 -*-
"""kept_woman A2 lesson + A3 ascent. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_kept_woman_A2A3.py"""
from _kept_woman_engine import seed_act

P_LESSON="cool glossy palette, chrome and marble whites with cold blue shadow and gold accents, sleek clean light"
P_ASCENT="rich seductive palette, warm gold and sea-blue, sunlit luxury with cool night contrast, high gloss"

LESSON=[
 ("A2_SH01","LERA_MID","salon","a glamorous hard-eyed woman of thirty-four reclining in a white salon chair, jet-black straight hair, oversized dark sunglasses worn even indoors","MS","eye","push_in","day",False,False,
  "в салоне ты знакомишься с Лерой, ей тридцать четыре, и тёмные очки она не снимает даже здесь."),
 ("A2_SH02","LERA_MID","salon","a medium close-up of the dark-haired woman in sunglasses talking, cool and knowing, in a bright cosmetology room","MCU","eye","static","day",False,False,
  "Лера в этом деле уже пятнадцать лет и знает про него всё, и она берёт тебя в ученицы."),
 ("A2_SH03","LERA_MID","salon","a close-up of the woman's mouth and jaw as she speaks a hard rule, sunglasses hiding her eyes","CU","eye","push_in","day",False,True,
  "первое правило, говорит она, считай, что это работа, и никогда, слышишь, никогда не влюбляйся."),
 ("A2_SH04","VIKA_YOUNG","salon","a medium shot of the twenty-year-old girl listening intently in the salon, honey-blonde hair, young and eager","MS","over","static","day",False,False,
  "ты киваешь, но в двадцать тебе кажется, что уж с тобой этого точно никогда не случится."),
 ("A2_SH05",None,None,"an extreme close-up macro insert of a pair of oversized dark sunglasses lying folded on a white marble counter, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "на мраморном столе лежат её тёмные очки, за которыми она прячет глаза от всех, даже от себя."),
 ("A2_SH06","LERA_MID","salon","a medium close-up of the sunglasses-wearing woman leaning in to deliver a second rule, cold and certain","MCU","eye","static","day",False,True,
  "второе правило, говорит Лера, твоя молодость — это деньги, а деньги, запомни, всегда однажды кончаются."),
 ("A2_SH07",None,"boutique","a wide interior view of a high-end fashion boutique, glossy shelves of handbags under spotlights, mirrored columns and a velvet bench","WS","eye","pan_right","day",True,False,
  "Лера возит тебя по ресторанам и бутикам и показывает жизнь, ради которой стоит стараться."),
 ("A2_SH08","VIKA_YOUNG","boutique","a medium shot of the young girl and the dark-haired mentor choosing handbags together in a bright boutique","MS","eye","static","day",False,False,
  "в бутике она учит тебя выбирать сумки не по красоте, а по тому, сколько за них потом дадут."),
 ("A2_SH09",None,None,"an extreme close-up macro insert of a single luxury handbag on a spotlit boutique shelf with a price tag on a silk ribbon, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","push_in","day",True,False,
  "ты впервые держишь в руках сумку, которая стоит как подержанная машина, и рука совсем не дрожит."),
 ("A2_SH10","VIKA_YOUNG","boutique","a medium close-up of the twenty-year-old girl smiling as she hands over shopping bags to be carried, careless and pleased","MCU","eye","static","day",False,False,
  "Артур платит за всё, и ты быстро привыкаешь, что чужие деньги тратить куда легче, чем свои."),
 ("A2_SH11","VIKA_YOUNG","penthouse_apartment","a wide shot of the young woman standing in her own new city apartment, boxes and shopping bags around her","WS","low","push_in","day",False,False,
  "к двадцати одному у тебя своя квартира в центре, за которую платит он, и это кажется тебе победой."),
 ("A2_SH12","VIKA_YOUNG","penthouse_apartment","a medium shot of the girl walking through the empty new apartment, running a hand along a bare wall","MS","eye","track","day",False,False,
  "Лера предупреждала, что квартира записана на него, а значит, на самом деле она не твоя."),
 ("A2_SH13",None,None,"an extreme close-up macro insert of a set of apartment keys resting in an open palm, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "ключи от квартиры лежат у тебя в ладони, но ты уже знаешь, что второй комплект есть у него."),
 ("A2_SH14","VIKA_YOUNG","penthouse_apartment","a close-up of the twenty-one-year-old girl speaking warmly into a phone by the window, a practiced soft smile","CU","eye","static","day",False,False,
  "ты звонишь матери и говоришь, что устроилась помощницей в большую фирму, и она радуется за тебя."),
 ("A2_SH15","VIKA_YOUNG","penthouse_apartment","a medium shot of the young woman on the phone at a huge apartment window, the city spread out behind her","MS","eye","static","day",False,False,
  "ты рассказываешь ей про офис, которого нет, про зарплату, которой нет, и ложь даётся тебе легко."),
 ("A2_SH16",None,None,"a wide establishing view of a glittering big city seen from high above at midday, glass towers and distant streets, cold and vast","WS","high","pan_left","day",True,False,
  "за окном тот же огромный город, но теперь ты смотришь на него сверху вниз."),
 ("A2_SH17","VIKA_YOUNG","penthouse_apartment","a medium close-up of the twenty-one-year-old girl looking pleased and confident, arms folded, in her expensive apartment","MCU","low","static","day",False,False,
  "в двадцать один тебе кажется, что ты обыграла всех, что ты умнее и красивее любой из них."),
 ("A2_SH18",None,None,"an extreme close-up macro insert of a delicate thin gold chain around a young woman's bare ankle above an elegant shoe, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "золотая цепочка всё так же на щиколотке, и ты носишь её как знак того, что нужна."),
 ("A2_SH19","LERA_MID","luxury_restaurant","a medium shot of the dark-haired woman in sunglasses at a candlelit restaurant table, delivering a last cold rule","MS","over","static","night",False,False,
  "Лера говорит последнее правило, всегда имей запасного, потому что этот однажды тебя заменит."),
 ("A2_SH20","VIKA_YOUNG","luxury_restaurant","a close-up of the twenty-one-year-old girl laughing lightly, dismissing the warning, candle glow on her face","CU","eye","static","night",False,False,
  "ты смеёшься и думаешь, что это про Леру, а не про тебя, ведь тебе всего двадцать один."),
 ("A2_SH21",None,"luxury_restaurant","a wide night interior of an opulent restaurant, glittering city lights through tall dark windows, candle flames and marble","WS","eye","push_in","night",True,False,
  "город внизу горит огнями, и кажется, что этот блеск и правда будет длиться вечно."),
 ("A2_SH22","VIKA_YOUNG","luxury_restaurant","a medium close-up of the young woman looking quietly certain across the table, glamorous and untroubled","MCU","eye","push_in","night",False,True,
  "ты запоминаешь все правила, кроме одного, что молодость кончается быстрее, чем успеваешь это заметить."),
]

ASCENT=[
 ("A3_SH01",None,"hotel_seaside","a wide view of a luxury seaside hotel suite balcony at dusk over a darkening sea, white linen, two glasses, palm shadows","WS","eye","push_in","dusk",True,False,
  "в двадцать два жизнь превращается в череду перелётов, отелей и моря, за которые ты не платишь ни разу."),
 ("A3_SH02","VIKA_PRIME","hotel_seaside","a medium shot of a beautiful woman in her mid-twenties standing on a hotel balcony over the sea at dusk, elegant and content","MS","eye","static","dusk",False,False,
  "ты стоишь на балконе над чужим тёплым морем и думаешь, что вот она, та самая красивая жизнь."),
 ("A3_SH03","ARTUR_BASE","hotel_seaside","a medium close-up of the silver-haired man of fifty-two standing close behind the woman on the balcony, gesturing at yachts below","MCU","over","static","dusk",False,False,
  "Артур обнимает тебя сзади, показывает на яхты внизу и обещает, что скоро разведётся и всё это станет вашим."),
 ("A3_SH04","VIKA_PRIME","hotel_seaside","a close-up of the mid-twenties woman's face wanting to believe, soft warm dusk light","CU","eye","push_in","dusk",False,False,
  "ты веришь ему, потому что очень хочешь верить, и потому что так проще не думать о будущем."),
 ("A3_SH05",None,"hotel_seaside","an extreme close-up macro insert of two glasses and an ashtray on a low balcony table over a blurred evening sea, filling the frame in sharp focus, shallow depth of field","ECU","top","static","dusk",True,False,
  "на столике два бокала и пепельница, и так проходит каждое лето, одинаково красиво и одинаково чужое."),
 ("A3_SH06",None,None,"a wide establishing view of an empty luxury beach at dawn, calm sea and pale sand, sun low over the water, still and beautiful","WS","low","pan_right","day",True,False,
  "море одно и то же каждый год, только отели дороже, а обещания все те же."),
 ("A3_SH07","VIKA_PRIME","boutique","a medium shot of the mid-twenties woman selecting a handbag in a bright luxury boutique, assured and unhurried","MS","eye","static","day",False,False,
  "между морями ты покупаешь сумки, по одной на каждый его приезд, и складываешь их как трофеи."),
 ("A3_SH08",None,None,"an extreme close-up macro insert of a row of expensive handbags lined on a wardrobe shelf, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","pan_left","day",True,False,
  "к двадцати пяти у тебя уже двенадцать таких сумок, и каждая помнит мужчину, который за неё заплатил."),
 ("A3_SH09","VIKA_PRIME","salon","a medium close-up of the woman in a reclining salon chair under a ring-lit mirror, a beautician's hands at her face","MCU","high","static","day",False,False,
  "ты тратишь всё больше времени на салоны, потому что красота теперь не подарок, а тяжёлая работа."),
 ("A3_SH10","VIKA_PRIME","luxury_restaurant","a wide shot of the elegant woman at a candlelit restaurant while other men glance at her from nearby tables","WS","eye","static","night",False,False,
  "в ресторанах на тебя смотрят и другие мужчины, и ты выбираешь их сама, как Лера и учила."),
 ("A3_SH11","VIKA_PRIME","luxury_restaurant","a medium close-up of the mid-twenties woman coolly weighing a choice across a candlelit table","MCU","eye","static","night",False,False,
  "ты заводишь второго, про запас, и говоришь себе, что это просто страховка, а не предательство."),
 ("A3_SH12",None,None,"an extreme close-up macro insert of two mobile phones lying side by side on a marble surface, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "у тебя появляется второй телефон, и на нём другое имя, другие подарки, другая ложь."),
 ("A3_SH13","VIKA_PRIME","penthouse_apartment","a close-up of the woman's harder, cooler face at a dark apartment window at night","CU","eye","push_in","night",False,False,
  "ты всё реже вспоминаешь мать и посёлок, будто той девочки с автобуса никогда и не было."),
 ("A3_SH14","VIKA_PRIME","car_interior_lux","a medium shot of the elegant woman settling onto dark leather in a luxury car at night, city lights on the glass","MS","eye","static","night",False,False,
  "каждый раз, садясь в очередную машину, ты слышишь тот же щелчок замка и уже не замечаешь его."),
 ("A3_SH15",None,"car_interior_lux","an extreme close-up macro insert of a chrome car-door lock latch dropping shut inside a dark luxury car, filling the frame in sharp focus, ambient glow, shallow depth of field","ECU","eye","static","night",True,False,
  "замок щёлкает, дверь закрывается, и это стало для тебя привычным, как собственное дыхание."),
 ("A3_SH16",None,"penthouse_apartment","a wide night view of a high-floor apartment interior with a glittering city skyline beyond floor-to-ceiling windows","WS","eye","push_in","night",True,False,
  "твоя квартира всё выше, машины всё дороже, и кажется, что кривая идёт только вверх."),
 ("A3_SH17","ARTUR_BASE","luxury_restaurant","a medium close-up of the ageing silver-haired man at a restaurant table, generous but distracted, a gold watch on his wrist","MCU","over","static","night",False,False,
  "Артур стареет, но платит щедро, и ты убеждаешь себя, что вы почти семья, просто без штампа."),
 ("A3_SH18","VIKA_PRIME","luxury_restaurant","a close-up of the woman nodding along, a fixed practiced smile, candlelight on her face","CU","eye","static","night",False,False,
  "он снова обещает развод к следующему лету, и ты снова киваешь, хотя лет уже прошло немало."),
 ("A3_SH19",None,None,"an extreme close-up macro insert of a wall calendar with several months torn away, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "лето сменяет лето, а его жена всё ещё жена, и ты делаешь вид, что не считаешь года."),
 ("A3_SH20","VIKA_PRIME","salon","a medium shot of the woman leaning to a magnifying salon mirror, noticing something at the corner of her eye","MS","eye","push_in","day",False,False,
  "в двадцать шесть ты впервые находишь у глаза тонкую морщинку и пугаешься так, как не пугалась никогда."),
 ("A3_SH21","VIKA_PRIME","salon","a close-up of the woman studying her own face in a magnifying ring-lit mirror, a first flicker of fear","CU","eye","push_in","day",False,False,
  "ты разглядываешь её в увеличительном зеркале, и слова Леры про молодость перестают быть смешными."),
 ("A3_SH22","VIKA_PRIME","salon","a medium close-up of the woman straightening up and composing herself, forcing calm back onto her face","MCU","eye","static","day",False,False,
  "ты говоришь себе, что тебе только двадцать шесть, что у тебя ещё полно времени, и почти веришь."),
 ("A3_SH23",None,"boutique","a wide view of a luxury boutique window glowing at night, glossy displays and mirrored surfaces, cold and inviting","WS","eye","pan_right","night",True,False,
  "витрины сияют, всё блестит и обещает, что так будет всегда, и ты предпочитаешь им верить."),
 ("A3_SH24","VIKA_PRIME","luxury_restaurant","a medium shot of the elegant woman seated across from the silver-haired man at dinner, not noticing his wandering gaze","MS","over","static","night",False,False,
  "ты сидишь напротив Артура в дорогом платье и не замечаешь, что он всё чаще смотрит мимо тебя."),
 ("A3_SH25","VIKA_PRIME","luxury_restaurant","a close-up of the mid-twenties woman looking serenely certain in candlelight, unaware of what is coming","CU","eye","push_in","night",False,True,
  "тебе кажется, что ты на вершине, но вершина, как ты потом поймёшь, это всегда начало спуска."),
 ("A3_SH26",None,None,"an extreme close-up macro insert of a thin gold ankle chain above a very expensive shoe on a marble floor, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","night",True,False,
  "на щиколотке всё та же цепочка, а над ней с каждым годом всё более дорогие, но чужие подарки."),
]

if __name__=="__main__":
    seed_act("lesson", P_LESSON, LESSON, render_mode="animated")
    seed_act("ascent", P_ASCENT, ASCENT, render_mode="animated")
