# -*- coding: utf-8 -*-
"""cloakroom batch D: gallery_e (liga cameo + teen + lobby-man) + turn (point of no return). static."""
from _cloakroom_engine import seed_act

PAL_E="cold post-communist palette, blue-grey neon and worn marble, a thin chill, flat modern light creeping into old gilt"
GE=[
 # --- B9 Камео девушка гонщика (gaz/LIGA) ---
 ("GE_SH01",None,"street_cobble","the cobbled theatre square in deep winter, snow on the stones, the lit facade beyond, a quiet cold evening","EWS","high","push_in","night",True,False,
  "в нулевые приходит рыжая девушка в круглых очках, с тонкой золотой цепочкой на щиколотке."),
 ("GE_SH02","LIGA_BASE","cloakroom_counter","an auburn-haired woman in round glasses handing over a too-thin elegant coat, a gaunt man in a fingerless driving glove beside her","MS","eye","static","night",False,False,
  "она сдаёт слишком тонкое для зимы пальто, а рядом мужчина, от которого пахнет бензином и палёной резиной."),
 ("GE_SH03",None,"cloakroom_counter","extreme close on a thin delicate gold chain around a woman's right ankle as she steps up to the counter","INSERT","low","push_in","night",False,True,
  "на её правой щиколотке тонкая золотая цепочка, и ты запоминаешь её, как запоминаешь тут всех."),
 ("GE_SH04","LIGA_BASE","cloakroom_counter","close on the woman's warm intelligent freckled face behind round glasses, glancing anxiously at her companion","CU","eye","static","night",False,False,
  "она умная и тёплая, и смотрит на своего спутника так, будто он всё время гонит куда-то слишком быстро."),
 ("GE_SH05","CLOAK_MID","cloakroom_counter","the attendant taking her thin coat, noting the petrol smell off the man's worn driving glove","MCU","eye","static","night",False,False,
  "ты принимаешь её лёгкое пальто и чувствуешь, что этот мужчина живёт на скорости, и она за него боится."),
 ("GE_SH06","LIGA_BASE","cloakroom_counter","close on the woman holding her companion's arm, glancing back to check he is still there","CU","eye","push_in","night",False,False,
  "она держит его под локоть и всё время оглядывается, будто проверяет, тут ли он ещё рядом."),
 ("GE_SH07","LIGA_BASE","auditorium","the couple in their velvet seats, the woman leaning against the gaunt man, finally at ease","WS","eye","static","night",False,False,
  "в зале она прислоняется к нему, и впервые за весь вечер у неё спокойное и тихое лицо."),
 ("GE_SH08",None,"auditorium","extreme close on a worn brown fingerless leather driving glove resting on a velvet seat arm","INSERT","high","push_in","night",False,True,
  "у него на правой руке потёртая кожаная перчатка без пальцев, и он не снимает её даже в зале."),
 ("GE_SH09","LIGA_BASE","cloakroom_counter","the couple leaving together after the show, the woman laughing","MS","eye","static","night",False,False,
  "после спектакля они уходят вдвоём, и она смеётся, и ты думаешь, что у неё всё хорошо."),
 ("GE_SH10",None,"street_cobble","snow falling on the empty theatre square between seasons, the same facade","INSERT","eye","push_in","night",True,False,
  "проходит зима, и вторая, и ты привыкаешь к ним, к рыжей и к запаху палёной резины."),
 ("GE_SH11","LIGA_BASE","cloakroom_counter","the woman entering alone a third winter, dressed in black, her face frozen and still","MCU","eye","static","night",False,False,
  "а в третью зиму она входит одна, в чёрном, и пальто на ней тёплое, но лицо у неё застывшее."),
 ("GE_SH12","LIGA_BASE","cloakroom_counter","the woman handing over a single coat, no longer glancing back over her shoulder","MCU","eye","static","night",False,False,
  "она сдаёт одно пальто и больше не оглядывается, потому что проверять ей больше уже некого."),
 ("GE_SH13",None,"cloakroom_counter","extreme close on the same thin gold ankle chain, the one thing unchanged about her","INSERT","low","push_in","night",False,True,
  "ты узнаёшь её по золотой цепочке на щиколотке, она одна на ней и осталась прежней."),
 ("GE_SH14","CLOAK_MID","cloakroom_counter","close on the attendant understanding without asking that the racer is gone","CU","eye","static","night",False,False,
  "ты не спрашиваешь, где он, потому что и так знаешь, что есть скорости, с которых не возвращаются."),
 ("GE_SH15","LIGA_BASE","auditorium","the woman sitting alone in the seats where two once sat, staring at a single point","WS","high","static","night",False,False,
  "в зале она садится туда, где они сидели вдвоём, и весь спектакль смотрит в одну точку."),
 ("GE_SH16","CLOAK_MID","stage_empty","the attendant at night playing the woman, glancing over his shoulder for someone no longer there","MCU","eye","static","night",False,False,
  "ночью ты играешь её, что всё оглядывается на того, кого уже нет, и пустой зал понимает тебя."),
 # --- B10 Подросток в наушниках ---
 ("GE_SH17","TEEN_BOY","cloakroom_counter","a sullen boy in in-ear earphones dragged to the counter by his mother, handing over a jacket","MS","eye","static","dusk",False,False,
  "мать притаскивает сюда подростка в наушниках, и он стоит у стойки, ненавидя каждую минуту."),
 ("GE_SH18",None,"cloakroom_counter","extreme close on small white in-ear earphones in a teenage boy's ears","INSERT","eye","push_in","dusk",False,True,
  "в ушах у него белые наушники, и он не вынимает их, даже когда сдаёт тебе свою куртку."),
 ("GE_SH19","TEEN_BOY","cloakroom_counter","close on the boy's closed bored face staring at the floor","CU","eye","static","dusk",False,False,
  "ему четырнадцать, он смотрит в пол, и всем своим видом говорит, что лучше бы он был где угодно, только не тут."),
 ("GE_SH20","CLOAK_MID","cloakroom_counter","the attendant taking the boy's jacket, recognising the old resistance in him","MCU","eye","static","dusk",False,False,
  "ты принимаешь его куртку и узнаёшь в нём себя, того мальчика, которого тоже никуда не звали."),
 ("GE_SH21","TEEN_BOY","auditorium","the boy slumped in his seat at first, then slowly leaning forward toward the stage","WS","high","static","dusk",False,False,
  "в зале он сперва сидит, развалившись, а потом, незаметно для самого себя, подаётся вперёд."),
 ("GE_SH22","TEEN_BOY","auditorium","close on the boy quietly pulling the earphones out one by one as the stage takes hold of him","CU","eye","push_in","night",False,False,
  "где-то к середине он вынимает один наушник, потом второй, и больше уже их не вставляет."),
 ("GE_SH23",None,"auditorium","extreme close on white earphones stuffed forgotten into a jacket pocket","INSERT","high","push_in","night",False,False,
  "наушники остаются лежать в кармане куртки весь второй акт, и это ты тоже прекрасно замечаешь."),
 ("GE_SH24","TEEN_BOY","cloakroom_counter","the boy collecting his jacket afterward in silence, looking through the wall, changed","MCU","eye","static","night",False,False,
  "после спектакля он забирает куртку молча, но смотрит уже не в пол, а куда-то сквозь стену."),
 ("GE_SH25","CLOAK_MID","stage_empty","the attendant at night playing the boy whom the stage has seized whole for the first time","WS","low","static","night",False,False,
  "ночью ты играешь его, мальчика, которого сцена впервые забрала всего, без остатка."),
 ("GE_SH26","TEEN_GROWN","cloakroom_counter","six years later a quiet young man alone at the counter, no earphones, buying his own way in","MCU","eye","static","day",False,False,
  "проходит шесть лет, и он приходит сам, один, без наушников, и берёт билет на тот же спектакль."),
 ("GE_SH27","TEEN_GROWN","cloakroom_counter","close on the young man's open attentive face, not recognising the attendant","CU","eye","static","day",False,False,
  "он не узнаёт тебя, но ты узнаёшь его, и впервые твоя стойка кого-то к чему-то привела."),
 ("GE_SH28",None,"cloakroom_counter","extreme close on a single ticket to the same play held in a young man's hand","INSERT","top","push_in","day",False,False,
  "он держит один билет на тот самый спектакль, и ты думаешь, что хоть кому-то здесь это пошло впрок."),
 ("GE_SH29","CLOAK_MID","cloakroom_counter","close on the attendant's rare quiet satisfaction as he hangs the young man's coat","MCU","eye","push_in","day",False,False,
  "ты вешаешь его пальто и впервые за годы чувствуешь себя не вешалкой, а частью чьей-то судьбы."),
 # --- B11 Мужчина, не входящий в зал ---
 ("GE_SH30","LOBBY_BASE","cloakroom_counter","a still watchful man checking his coat at the counter, holding no ticket","MS","eye","static","dusk",False,False,
  "этот сдаёт пальто, берёт номерок, но билета у него нет, и в зал он не входит ни разу."),
 ("GE_SH31",None,"cloakroom_counter","extreme close on a brass token alone in an open palm, no ticket stub beside it","INSERT","top","push_in","dusk",False,True,
  "у него на ладони только твой латунный номерок, и больше ничего, ни билета, ни программки."),
 ("GE_SH32","LOBBY_BASE","foyer_marble","close on the man's quiet unreadable face as he settles on a foyer bench","CU","eye","static","dusk",False,False,
  "он садится в фойе на банкетку и сидит весь первый акт, глядя на закрытые двери зала."),
 ("GE_SH33","LOBBY_BASE","foyer_marble","the man sitting alone on a marble foyer bench facing the closed auditorium doors","WS","eye","static","dusk",False,False,
  "он приходит сюда не на спектакль, а просто чтобы побыть рядом с ним, у самых его дверей."),
 ("GE_SH34","CLOAK_MID","cloakroom_counter","the attendant watching the lobby man from the counter, recognising a kinship","MCU","eye","static","dusk",False,False,
  "ты узнаёшь в нём себя и потому никогда не спрашиваешь, чего он ждёт у этих закрытых дверей."),
 ("GE_SH35","LOBBY_BASE","foyer_marble","close on the man rising at intermission, taking his coat, leaving without entering","CU","eye","static","night",False,False,
  "в антракте он встаёт, забирает пальто и уходит, так и не заглянув внутрь даже на одну минуту."),
 ("GE_SH36",None,"foyer_marble","an empty marble foyer bench before the closed auditorium doors","INSERT","eye","push_in","night",True,False,
  "банкетка снова пустеет, и двери зала так и не открылись для него, как не открылась сцена для тебя."),
 ("GE_SH37","CLOAK_MID","stage_empty","the attendant at night playing the lobby man who comes to the doors and never goes in","MS","eye","static","night",False,False,
  "ночью ты играешь его, человека, что приходит к самым дверям и так и не решается войти."),
 ("GE_SH38","CLOAK_MID","stage_empty","close on the attendant's face, the doubled longing of two men at a threshold","CU","eye","push_in","night",False,True,
  "и ты понимаешь, что вы оба всю жизнь стоите у входа в зал, который так и не стал вашим."),
]

PAL_TURN="deceptive spring-thaw palette, a false warm light breaking through grey, hope tinted with cold"
TU=[
 ("TU_SH01",None,"street_cobble","the cobbled theatre square in early spring thaw, melting snow between the stones, pale sun","EWS","high","push_in","day",True,False,
  "однажды весной, на тридцать втором году у вешалки, с тобой случается то, чего ты перестал ждать."),
 ("TU_SH02","CLOAK_MID","dressing_mirror","the attendant alone testing his voice at the dressing mirror, a louder rasp than usual emerging","MCU","eye","static","day",False,False,
  "ты пробуешь голос в гримёрке, и он вдруг хрипит чуть громче обычного, почти как настоящий звук."),
 ("TU_SH03","CLOAK_MID","dressing_mirror","close on the attendant's face, disbelief turning to hope as he repeats a line","CU","eye","push_in","day",False,False,
  "ты повторяешь фразу снова и снова, и тебе кажется, что связки оживают после тридцати лет молчания."),
 ("TU_SH04",None,"foyer_marble","a playbill on a brass stand with a famous actor's name printed large at the top","INSERT","eye","push_in","day",False,True,
  "в это же время на афише появляется фамилия твоего однокурсника, теперь известного на всю страну."),
 ("TU_SH05","CLOAK_MID","foyer_marble","the attendant embraced at the counter by a famous classmate actor who recognises him","MS","eye","static","day",False,False,
  "он узнаёт тебя у стойки, обнимает и говорит, что помнит, каким голосом ты гремел на курсе."),
 ("TU_SH06","CLOAK_MID","foyer_marble","close on the attendant daring to hope as he rasps his news to the classmate","CU","eye","push_in","day",False,False,
  "ты сипишь ему, что голос возвращается, и он загорается и обещает что-нибудь придумать для тебя."),
 ("TU_SH07","CLOAK_MID","director_office","the attendant in the director's office as a tiny wordless walk-on is arranged for him","MCU","eye","static","day",False,False,
  "он говорит с театром, и тебе дают крошечный выход без слов, просто пройти по сцене в толпе."),
 ("TU_SH08","CLOAK_MID","director_office","close on the attendant overwhelmed, sixty years old and offered a stage at last","CU","eye","push_in","day",False,False,
  "тебе шестьдесят, и впервые за тридцать шесть лет тебя выпускают на сцену не ночью, а при зрителях."),
 ("TU_SH09","CLOAK_MID","stage_empty","the attendant rehearsing three steps across the stage at night, obsessively, again and again","WS","eye","push_in","night",False,False,
  "ты репетируешь эти три шага по сцене каждую ночь, как репетируют главную роль всей своей жизни."),
 ("TU_SH10","CLOAK_MID","dressing_mirror","the attendant pressing his costume yet again at the dressing mirror, glowing with purpose","MCU","high","static","night",False,False,
  "ты гладишь свой костюм в сотый раз и думаешь, что вот теперь крючок номер один наконец дождётся."),
 ("TU_SH11","CLOAK_MID","dressing_mirror","close on the attendant rehearsing the louder rasp, the voice holding for now","CU","eye","push_in","night",False,False,
  "ты тренируешь голос каждый вечер, и он держится, и ты позволяешь себе поверить до самого конца."),
 ("TU_SH12",None,"cloakroom_counter","the single empty brass hook number one, soon perhaps to be filled","INSERT","eye","push_in","day",False,True,
  "ты впервые думаешь, на какой крючок повесишь своё пальто, когда выйдешь на сцену по-настоящему."),
 ("TU_SH13","CLOAK_MID","cloakroom_counter","the attendant smoothing patrons' coats with a new lightness, keeping his secret to himself","MS","eye","static","day",False,False,
  "ты никому не говоришь, но разглаживаешь чужие пальто легче, чем за все эти долгие годы."),
 ("TU_SH14","CLOAK_MID","dressing_mirror","close on the attendant a week before, mid-line, his voice catching and dropping","CU","eye","push_in","day",False,False,
  "а за неделю до премьеры, посреди фразы, голос вдруг срывается обратно в один сиплый шёпот."),
 ("TU_SH15","CLOAK_MID","dressing_mirror","close on the attendant in panic forcing the voice louder, nothing coming out","CU","eye","static","day",False,False,
  "ты пробуешь громче, ещё громче, как тогда в двадцать четыре, и снова ничего не выходит."),
 ("TU_SH16","CLOAK_MID","hospital_throat","a doctor under the throat-lamp confirming the scar will not hold, the attendant listening","MCU","eye","static","day",False,False,
  "врач смотрит горло и говорит, что рубец есть рубец, и то, что было, тебе просто почудилось."),
 ("TU_SH17","CLOAK_MID","stage_empty","the attendant standing on the stage where he would have walked, now silent and alone","WS","low","static","night",False,False,
  "ты выходишь на сцену, где должен был пройти при зрителях, и проходишь свои три шага в пустоту."),
 ("TU_SH18",None,"foyer_marble","a revised playbill with the walk-on crowd scene cut, his name nowhere on it","INSERT","eye","push_in","day",False,False,
  "спектакль решают ставить иначе, массовку убирают, и твои три шага вычёркивают вместе с ней."),
 ("TU_SH19","CLOAK_MID","cloakroom_counter","the attendant waiting by the counter phone for a call that does not come","MCU","eye","static","day",False,False,
  "никто тебе не звонит, однокурсник уезжает на гастроли, и ты не решаешься напомнить ему о себе."),
 ("TU_SH20","CLOAK_MID","dressing_mirror","close on the attendant quietly hanging the pressed costume back up for good","CU","eye","push_in","night",False,False,
  "ты снимаешь выглаженный костюм, вешаешь его обратно и больше не достаёшь, и крючок номер один снова пуст."),
 ("TU_SH21",None,"stage_empty","the empty stage with the lone ghost-light burning, hope gone out of it","WS","eye","static","night",True,False,
  "и твой ночной театр на одного зрителя снова становится единственным, где тебя выпускают на сцену."),
 ("TU_SH22","CLOAK_MID","stage_empty","the attendant resuming his nightly performances, heavier and quieter now","MCU","eye","static","night",False,False,
  "ты возвращаешься к чужим пальто и чужим жизням и играешь их ночами, как прежде, только тише."),
 ("TU_SH23","CLOAK_MID","stage_empty","close on the attendant's face, the deep wound of a second loss","CU","eye","push_in","night",False,False,
  "тяжелее всего не потерять голос в двадцать четыре, а поверить в шестьдесят, что он вернулся."),
 ("TU_SH24",None,"dressing_mirror","the pressed costume left hanging on a stand at the bulb-framed mirror, never to be worn","INSERT","eye","push_in","night",False,True,
  "костюм так и висит в гримёрке, выглаженный, как будто всё ещё ждёт твоего единственного выхода."),
 ("TU_SH25",None,"foyer_marble","the foyer packed for the classmate's premiere, a glittering crowd under the chandeliers","EWS","high","push_in","dusk",True,False,
  "наступает та самая премьера, и ты стоишь за стойкой и принимаешь пальто всех, кто пришёл на него."),
 ("TU_SH26","CLOAK_MID","cloakroom_counter","the attendant handing out tokens on the very night he might have performed","MS","eye","static","dusk",False,False,
  "ты раздаёшь номерки в тот самый вечер, когда мог бы стоять не за стойкой, а на сцене."),
 ("TU_SH27","CLOAK_MID","cloakroom_counter","close on the attendant listening to muffled applause through the closed doors","CU","eye","push_in","night",False,False,
  "из-за дверей доносятся аплодисменты, и каждый хлопок этой толпы предназначен не тебе."),
 ("TU_SH28","CLOAK_MID","auditorium","the attendant slipping into the back row to watch the classmate take his ovation","WS","high","static","night",False,False,
  "ты прокрадываешься в зал на последний ряд и смотришь, как однокурсник срывает бурные овации."),
 ("TU_SH29","CLOAK_MID","auditorium","close on the attendant in the dark mouthing the classmate's lines silently along with him","CU","eye","push_in","night",False,False,
  "ты беззвучно повторяешь за ним каждое слово, и твой шёпот тонет в чужих аплодисментах."),
 ("TU_SH30","CLOAK_MID","foyer_marble","the classmate signing programmes surrounded by admirers as the attendant hands him his coat","MCU","eye","static","night",False,False,
  "после спектакля его обступают с программками, а ты подаёшь ему пальто, и он тебя уже не замечает."),
 ("TU_SH31",None,"cloakroom_counter","an expensive coat handed back across the rail with a careless generous tip on the saucer","INSERT","top","push_in","night",False,False,
  "он суёт тебе щедрые чаевые, не глядя, и уходит к машине под руку с молодой актрисой."),
 ("TU_SH32","CLOAK_MID","cloakroom_counter","close on the attendant holding the tip, the final acceptance forming in his face","CU","eye","static","night",False,False,
  "ты держишь его чаевые и понимаешь, что между вами теперь целая сцена, которую тебе уже не перейти."),
 ("TU_SH33","CLOAK_MID","stage_empty","the attendant at night on the empty stage playing the classmate's triumph alone","MCU","low","static","night",False,False,
  "ночью ты выходишь на пустую сцену и играешь его триумф сам, и кланяешься восьмистам пустым креслам."),
 ("TU_SH34","CLOAK_MID","stage_empty","close on the attendant bowing deeply to the silent dark house under the ghost-light","CU","low","push_in","night",False,True,
  "ты кланяешься так глубоко, как он не кланялся, и тишина в ответ оглушительнее любых оваций."),
]

seed_act("gallery_e", PAL_E, GE, render_mode="static")
seed_act("turn",      PAL_TURN, TU, render_mode="static")
