# -*- coding: utf-8 -*-
"""mascot batch D: act10_peak + act11_after + act12_finale (final + reveal + coda)."""
from _mascot_engine import seed_act

PAL_PEAK="blinding World Cup final palette, white-hot stadium glare against cold medical-corridor grey, triumph and collapse"
A10=[
 ("M10_SH01",None,"stadium_bowl","the World Cup final: a colossal stadium packed beyond capacity in blazing heat, the whole planet watching, flags everywhere","EWS","high","push_in","day",True,True,
  "день финала, чаша забита сверх меры, и тебя в этот час смотрит больше людей, чем кого-либо на земле."),
 ("M10_SH02","MASCOT","stadium_bowl","the eagle mascot bursting onto the final's pitch to a planet-shaking roar, arms wide, at the absolute peak","MS","low","push_in","day",False,True,
  "ты выбегаешь на финал, и рёв накрывает тебя как волна, и это вершина вершин, миг, ради которого ты жил."),
 ("M10_SH03","MASCOT","stadium_bowl","the eagle mascot dancing in murderous midday heat, the costume heavy, the grin fixed, pushing past its limit","MS","eye","static","day",False,False,
  "солнце в зените, в голове за пятьдесят, каждый шаг как сквозь кисель, но ты пляшешь, ведь это финал, нельзя слабее."),
 ("M10_SH04",None,"mask_interior","inside the head, the man's face draining grey, vision tunnelling, the mesh-eye world swimming and darkening","INSERT","eye","push_in","day",False,True,
  "внутри темнеет, сетка плывёт, сердце колотится в горле, и ты говоришь себе, ещё немного, дотанцуй, не подведи."),
 ("M10_SH05","MASCOT","stadium_bowl","the eagle mascot swaying hard, a stagger disguised as a clumsy dance, the crowd laughing, not seeing the danger","MCU","eye","static","day",False,False,
  "тебя ведёт, ты шатаешься, и трибуны смеются, думая, что это номер, и никто не понимает, что ты умираешь."),
 ("M10_SH06",None,"mask_interior","inside the head, the man's eyes rolling, the photo of his family the last thing the mesh-light touches","ECU","eye","push_in","day",False,True,
  "последнее, что ты видишь сквозь сетку, перед тем как погаснуть, это покоробленное фото жены и сына у самого глаза."),
 ("M10_SH07","MASCOT","stadium_bowl","the eagle mascot crumpling to the pitch at the edge of the spectacle, the great head tipping over in the grass","WS","high","static","day",False,True,
  "ты падаешь у кромки поля, большая голова орла откатывается по траве, и стадион на миг замирает, не понимая."),
 ("M10_SH08",None,"stadium_tunnel","staff rushing a collapsed mascot off the pitch into a tunnel on a cart, the costume limp, urgency","WS","eye","track","day",True,False,
  "к тебе бегут служащие, увозят с поля в тоннель, прочь от камер, чтобы праздник не запнулся ни на секунду."),
 ("M10_SH09","MAN","stadium_tunnel","the great mascot head pulled off in the tunnel revealing a grey unconscious aging man, medics over him","MS","high","static","day",False,False,
  "в тоннеле с тебя стаскивают голову, и под ней седой старик без сознания, серый, и медики хлопочут над тобой."),
 ("M10_SH10","MANAGER","stadium_tunnel","the manager already grabbing a younger performer, thrusting the eagle costume at them, all about the show","OTS","eye","static","day",False,False,
  "а менеджер уже хватает молодого сменщика, суёт ему костюм, быстрее, надевай, орёл должен вернуться, шоу не ждёт."),
 ("M10_SH11",None,"stadium_tunnel","the eagle head being lifted onto a different, younger performer in the tunnel, the same grin, a new man inside","INSERT","eye","push_in","day",False,True,
  "ту же голову, с твоим фото внутри, надевают на чужого парня, и улыбка орла остаётся прежней, неотличимой."),
 ("M10_SH12","MASCOT","stadium_bowl","the eagle mascot bounding back onto the pitch good as new, the crowd roaring in relief, the show unbroken","WS","low","push_in","day",False,False,
  "орёл выбегает обратно, целый и весёлый, и трибуны облегчённо ревут, и никто, никто не заметил подмены."),
 ("M10_SH13","MAN","dressing_area","the unconscious aging man on a stretcher in a back corridor, anonymous, while the muffled roar continues for the costume","MS","high","static","day",False,False,
  "тебя везут на каталке по коридору, никем, а за стеной глухо ревёт стадион, и ревёт он не тебе, а кукле, что машет вместо тебя."),
 ("M10_SH14","MAN","dressing_area","close on the aging man's grey unconscious face on the stretcher, utterly anonymous under the celebration","CU","low","push_in","day",False,True,
  "сорок лет ты был этой улыбкой, а оказалось, улыбка прекрасно живёт и без тебя, любой влезет в неё и продолжит."),
 ("M10_SH15",None,"city_summer","a hospital corridor, a wall TV showing the eagle mascot celebrating the final, a man's empty wheeled bed nearby","INSERT","eye","push_in","day",False,False,
  "ты приходишь в себя в палате, и на экране орёл скачет на финале, и ты не можешь понять, ты это там или уже не ты."),
 ("M10_SH16","MAN","dressing_area","the aging man awake in a clinic bed watching the mascot on TV lift into the air with the winning team, not him inside","MCU","high","static","day",False,False,
  "по телевизору орёл качается на руках чемпионов в конфетти, и это твой костюм, твоя улыбка, но внутри уже не ты."),
 ("M10_SH17","MAN","dressing_area","close on the aging man's stricken face realising the mascot outlived the man inside it, replaceable","CU","eye","push_in","day",False,False,
  "и ты понимаешь страшное, что любили всегда её, костюм, а ты был лишь сменным телом внутри чужой вечной улыбки."),
 ("M10_SH18",None,"dressing_area","a phone on a clinic bedside showing a curt manager text reading get well, we covered the shift, the show went on","INSERT","top","push_in","day",False,False,
  "менеджер пишет, поправляйся, мы тебя подменили, всё прошло отлично, и ни слова о том, как ты, живой ли ты вообще."),
 ("M10_SH19","MASCOT","stadium_bowl","the eagle mascot at the centre of the final's confetti and trophy celebration, the icon of the whole summer","WS","low","static","day",False,True,
  "орёл становится символом всего турнира, лицом лета для миллиардов, а человек, что его создал, лежит один в палате."),
 ("M10_SH20","MAN","dressing_area","the aging man alone in the dim clinic room after, the TV off, the great roar finally gone silent","MS","high","static","night",False,False,
  "праздник стихает, телевизор гаснет, и впервые за лето вокруг тебя тишина, и в этой тишине ты совсем один."),
 ("M10_SH21","MAN","dressing_area","close on the aging man's hollow face in the dark clinic, the summit reached and nothing left of him","CU","eye","push_in","night",False,False,
  "ты добрался до вершины мира, и с неё видно только одно, что тебя самого там, наверху, не было ни секунды."),
 ("M10_SH22",None,"city_summer","a host city the morning after the final, workers taking down World Cup banners in the heat, the festival over","EWS","high","pan_left","day",True,False,
  "наутро город снимает флаги, праздник кончился, орла увозят, и ты выписываешься из палаты тихо, никем не встреченный."),
 ("M10_SH23","MAN","stadium_parking","the aging man walking alone across a vast emptying hot stadium parking lot, small, discharged, unknown","WS","high","track","day",False,False,
  "ты идёшь один через раскалённую пустую парковку, мимо стадиона, где вчера тебя обожал весь мир, и тебя никто не узнаёт."),
 ("M10_SH24","MAN","stadium_parking","close on the aging man's spent face in the brutal heat, having given everything to a smile that wasn't his","CU","low","push_in","day",False,True,
  "ты отдал этой улыбке сердце, колени, жену, сына, всю жизнь, а она даже не заметила, как ты выпал из неё."),
]

PAL_AFTER="drained aftermath palette, dusty storage greys and a cold museum spotlight, faded and discarded"
A11=[
 ("M11_SH01",None,"museum_case","a glass museum case displaying the World Cup eagle mascot costume upright under warm spotlights, a plaque below","EWS","low","push_in","day",True,True,
  "проходит время, и костюм орла ставят под стекло в музее спорта, как реликвию того великого лета."),
 ("M11_SH02",None,"museum_case","museum visitors crowding to photograph the mascot costume in its glass case, admiring the empty suit","WS","eye","static","day",True,False,
  "люди приходят семьями, фотографируют пустой костюм, восхищаются, и в очереди к стеклу стоит и старик, которого все обтекают."),
 ("M11_SH03","MAN_OLD","museum_case","a frail old man standing among tourists before the glass case, gazing at the costume he wore, unrecognised","MS","eye","push_in","day",False,False,
  "ты стоишь среди туристов и смотришь на свою жизнь под стеклом, на улыбку, в которой прожил сорок лет, и молчишь."),
 ("M11_SH04","MAN_OLD","museum_case","close on the old man's face looking at his own life enshrined in a glass box, a lifetime behind the eyes","CU","eye","push_in","day",False,False,
  "вот она, вся твоя жизнь, под музейным светом, и табличка внизу, и на ней нет твоего имени, нет даже слова человек."),
 ("M11_SH05",None,"museum_case","extreme close on a museum plaque naming the mascot and the tournament, no performer ever credited","INSERT","top","push_in","day",False,True,
  "на табличке имя орла и год турнира, и никого, кто был внутри, ведь кукле не нужен человек, кукла сама себе герой."),
 ("M11_SH06","MAN_OLD","museum_case","the old man quietly telling a passing visitor that he was the one inside, the visitor smiling politely and moving on","OTS","eye","static","day",False,False,
  "ты тихо говоришь соседу по очереди, это был я, я был внутри, а он вежливо кивает и отходит, не поверив старику."),
 ("M11_SH07","MAN_OLD","storage_warehouse","an old man among long warehouse shelves of retired mascot costumes sealed in plastic, dim and dusty","WS","eye","track","day",False,False,
  "а твои прежние костюмы, все эти годы шкур, лежат на складе в пыльном пластике, рядами, как тела, и пахнут поролоном."),
 ("M11_SH08","MAN_OLD","storage_warehouse","the old man laying a hand on an old plastic-wrapped mascot suit on a shelf, a memory, deep shadow","MCU","eye","push_in","day",False,False,
  "ты кладёшь руку на старый костюм под плёнкой, и вспоминаешь, как был в нём счастлив, как тебя любили, не зная."),
 ("M11_SH09","MAN_OLD","family_kitchen","the old man home for good now, sitting at the kitchen table across from his aged wife, a careful distance between them","MS","eye","static","day",False,False,
  "ты возвращаешься домой насовсем, постаревший, с убитыми коленями, и за столом сидит женщина, которую ты почти не знаешь."),
 ("M11_SH10","WIFE","family_kitchen","the aged wife pouring tea for the old man, gentle but distant, decades of his absence settled between them","CU","eye","static","day",False,False,
  "жена наливает тебе чай, тепло и чуждо, и вы молчите, ведь сорок лет ты был дома гостем, а жил внутри чужой головы."),
 ("M11_SH11",None,"family_kitchen","a grown son's framed photo and a brief polite text on a phone on the table, the father a near-stranger to him","INSERT","top","push_in","day",False,False,
  "сын давно взрослый, живёт своей жизнью, и пишет тебе по праздникам коротко, как пишут дальнему родственнику."),
 ("M11_SH12","MAN_OLD","family_kitchen","the old man trying clumsily to talk to his grown son on a video call, no mask to hide behind, awkward and tender","MCU","eye","static","day",False,False,
  "ты звонишь сыну, и впервые без маски пытаешься быть просто отцом, и не умеешь, слова не идут, как не шли всю жизнь."),
 ("M11_SH13","MAN_OLD","family_kitchen","close on the old man's face realising he never built a self that could be loved without a costume","CU","eye","push_in","day",False,False,
  "и ты понимаешь, что разучился быть собой, что научился только прятаться, и теперь, без шкуры, тебя снова не видно."),
 ("M11_SH14","MAN_OLD","family_kitchen","the old man alone watching old World Cup footage of the eagle on TV, unsure which joyful moments were even him","MS","high","static","night",False,False,
  "ты пересматриваешь записи того лета, и не можешь понять, где там ты, а где сменщик, ведь улыбка у орла одна на всех."),
 ("M11_SH15",None,"family_kitchen","a small plush eagle-mascot toy sitting on a shelf in a dim room, its permanent grin catching the lamplight","INSERT","eye","push_in","night",False,True,
  "на полке стоит маленький плюшевый орёл, сувенир, и улыбается тебе той самой улыбкой, что ты носил вместо лица."),
 ("M11_SH16","MAN_OLD","suburban_street","the old man on a walk pausing as a child runs past to hug a NEW mascot outside a shop, the cycle continuing without him","WS","eye","static","day",False,False,
  "на улице ребёнок бежит обниматься к новой кукле у магазина, к новому костюмщику, и колесо крутится дальше, уже без тебя."),
 ("M11_SH17","MAN_OLD","suburban_street","close on the old man watching the new mascot work the crowd, the torch passed, himself entirely forgotten","CU","low","push_in","day",False,False,
  "ты смотришь, как молодой парень в кукле собирает детей, как когда-то ты, и тебя уже не помнит ни один из них."),
 ("M11_SH18","WIFE","family_kitchen","the aged wife quietly caring for the old man, the distance permanent but a worn tenderness remaining","MCU","eye","static","night",False,False,
  "жена осталась с тобой, по привычке, по доброте, и ухаживает за тобой, но того, кого она полюбила тогда, под маской, давно нет."),
 ("M11_SH19","MAN_OLD","storage_warehouse","the old man asking a warehouse keeper to let him keep one old discarded mascot head, holding it like a relic","MS","eye","static","day",False,False,
  "ты выпрашиваешь на складе одну старую списанную голову, и тебе отдают, кому она нужна, кроме тебя, дурака."),
 ("M11_SH20","MAN_OLD","suburban_street","the frail old man carrying a big old mascot head home along a quiet street, the one thing in the world that is his","WS","low","track","dusk",False,True,
  "и ты несёшь эту голову домой по тихой улице, единственное, что у тебя осталось от целой жизни, чужую улыбку."),
 ("M11_SH21","MAN_OLD","family_kitchen","close on the old man's face holding the old mascot head in his lap at home, tender and bereft","CU","eye","push_in","dusk",False,False,
  "ты держишь её на коленях, как держат старого друга, и думаешь, что любил её больше, чем себя, и зря."),
 ("M11_SH22",None,"museum_case","the eagle costume alone in its glass case in a closed dark museum at night, dark and unattended, silent","EWS","eye","pull_out","night",True,True,
  "а твой звёздный костюм стоит ночами в тёмном музее один, под стеклом, и его уже тоже больше никто не обнимает."),
 ("M11_SH23","MAN_OLD","mascot_backroom","the old man setting the salvaged mascot head down on a folding table in a dim back room, the cold-open moment arriving","MS","eye","push_in","night",False,False,
  "ты ставишь спасённую голову на стол в подсобке, и вот ты там, где я начал тебе этот рассказ, в самом конце пути."),
 ("M11_SH24","MAN_OLD","mascot_backroom","close on the old man's quiet face beside the grinning head in the dim room, ready to finally show his own","CU","low","push_in","night",False,True,
  "сорок лет улыбки напрокат, и старик в подсобке, наедине с чужой улыбкой, готовый наконец показать своё лицо."),
]

PAL_FINALE="dim cold back-room palette, cold fluorescent grey-green with one warm patch of light, hushed final stillness"
A12=[
 ("M12_SH01",None,"mascot_backroom","a dim costume back room at night, the old mascot head sitting on a folding table, a hunched old man's silhouette behind it","EWS","eye","push_in","night",True,True,
  "вот мы и вернулись сюда, в подсобку, к этой голове на столе, как я и обещал в самом начале, помнишь."),
 ("M12_SH02","MAN_OLD","mascot_backroom","the bare back of a hunched old man facing the grinning mascot head on the table, his face still turned away","BACK","eye","static","night",False,False,
  "я обещал, что сниму её при тебе, первый и последний раз, и покажу, кто прожил всю жизнь под этой улыбкой."),
 ("M12_SH03",None,"mascot_backroom","extreme close on the painted permanent grin of the old mascot head under a single warm light","ECU","low","push_in","night",False,True,
  "вот эта улыбка, которую любили миллионы, вечная, нарисованная, ни разу не дрогнувшая за сорок лет."),
 ("M12_SH04",None,"mask_interior","extreme close inside the head on the faded warped photo of a wife and son still taped by the eye-mesh","INSERT","eye","push_in","night",False,True,
  "а вот всё, что было внутри неё, темнота, духота, и пожелтевшее фото двоих, мимо которых я прожил свою жизнь."),
 ("M12_SH05","MAN_OLD","mascot_backroom","the old man's hands lifting the great grinning head up and away for the last time, the reveal beginning","MCU","eye","push_in","night",False,True,
  "и теперь я снимаю её, в последний раз, и больше уже не надену, и ты впервые увидишь то, что под ней."),
 ("M12_SH06","MAN_OLD","mascot_backroom","THE REVEAL: an old man's bare face seen at last from the front, gaunt and tired, the grinning head lowered in his hands","CU","eye","push_in","night",False,True,
  "вот моё лицо, обычное, усталое, старое, лицо, которое ты не вспомнишь, потому что не видел его никогда."),
 ("M12_SH07","MAN_OLD","mascot_backroom","close on the old man trying to smile and failing, the muscles unused, the face unable to make the shape","ECU","eye","push_in","night",False,True,
  "я пробую улыбнуться тебе, как улыбался орёл, и не могу, лицо забыло, как это делается, оно разучилось за ненадобностью."),
 ("M12_SH08","MAN_OLD","mascot_backroom","the old man holding the eternally grinning head beside his own unsmiling face, the two side by side","MCU","eye","static","night",False,True,
  "вот мы рядом, я и она, одна улыбается вечно, а другой так и не научился, и угадай, кого из нас любили."),
 ("M12_SH09","MAN_OLD","mascot_backroom","close on the old man's bare honest face speaking directly to the viewer, quiet and unmasked at last","CU","eye","push_in","night",False,False,
  "теперь ты знаешь всё, я был той улыбкой, что тебя обнимала в детстве, а сам прожил жизнь, и меня никто не видел."),
 ("M12_SH10","MAN_OLD","mascot_backroom","the old man addressing the viewer gently, the head set on his knee, a lifetime of hidden tears behind his eyes","MCU","eye","static","night",False,False,
  "я отдал всё, чтобы меня любили, но любили не меня, и я так и не решился просто показать лицо и попросить о любви."),
 ("M12_SH11","MAN_OLD","mascot_backroom","close on the old man's earnest unmasked face giving the viewer one quiet plea","CU","eye","push_in","night",False,False,
  "не прячься за чужой улыбкой так долго, как я, останься со мной до конца, подпишись, и береги себя, настоящего."),
 ("M12_SH12","MAN_OLD","mascot_backroom","the old man gently setting the grinning head down on the table, facing it, finished","MS","eye","static","night",False,False,
  "не дай так, чтобы тебя полюбили только в маске, покажи им лицо, пока есть кому показывать, пока не поздно, как мне."),
 ("M12_SH13",None,"mascot_backroom","extreme close on the old man's tired bare face reflected small in the glassy eye of the grinning mascot head","ECU","eye","push_in","night",False,True,
  "я гляжу в стеклянный глаз орла, и вижу там своё отражение, и это единственное место на свете, где живёт моё лицо."),
 ("M12_SH14","MAN_OLD","mascot_backroom","the frail old man sitting alone and still beside the grinning head in the dim room, at the end of everything","WS","high","pull_out","night",False,True,
  "я сижу один в подсобке, рядом со своей улыбкой напрокат, и впервые за сорок лет на моём лице нет ничьей чужой радости."),
 ("M12_SH15",None,"mascot_backroom","a medium framing of the grinning mascot head alone on the table beside an empty stool under the bulb","MS","eye","static","night",True,False,
  "эта история вымышлена, и все совпадения с реальными людьми случайны, не повторяй чужих ошибок, прошу тебя."),
 ("M12_SH16","MAN_OLD","mascot_backroom","close on the old man's peaceful bare face, eyes closing, finally only himself, no smile borrowed or owed","CU","eye","push_in","night",False,True,
  "береги себя, слышишь, и пусть тебя любят таким, какой ты есть, без маски, в лицо, по-настоящему, пока не поздно."),
 ("M12_SH17",None,"mascot_backroom","the dim back room, the old man a small still silhouette beside the grinning head under a single dying bulb","EWS","eye","push_in","night",True,True,
  "а улыбка останется, она всех нас переживёт, её наденет другой, и будет махать новым детям, и никто не вспомнит, кто был внутри."),
 ("M12_SH18",None,"mask_interior","extreme close on the faded photo and the dark empty inside of the mascot head, the man finally outside it","INSERT","eye","push_in","night",False,True,
  "а ты, если дослушал, не ищи любви из темноты, изнутри чужого лица, выйди на свет, и пусть тебя увидят, и всё."),
]

seed_act("act10_peak",   PAL_PEAK,   A10)
seed_act("act11_after",  PAL_AFTER,  A11)
seed_act("act12_finale", PAL_FINALE, A12)
