# -*- coding: utf-8 -*-
"""collector A8 father (2024) + A9 catastrophe (2026). Run: PYTHONIOENCODING=utf-8 python scripts/_seed_collector_A8A9.py"""
from _collector_engine import seed_act

P_FATHER="mourning palette, black cloth and birch white against wet grey, one warm kitchen amber far away"
P_CATASTROPHE="reckoning palette, ice-blue monitor light cutting into warm kitchen yellow, night and verdict"

FATHER=[
 ("A8_SH01","HERO_OLD","boss_office","a medium close-up of the greying department head answering his rarely-lit personal phone, standing up as he listens","MCU","eye","static","day",False,False,
  "в феврале двадцать четвёртого личный телефон звонит в десять утра, и это мать."),
 ("A8_SH02","HERO_OLD","boss_office","a close-up of the man's face as the words land, the office noise gone from his eyes","CU","eye","push_in","day",False,False,
  "отец умер во сне, в шестьдесят восемь, с вечера поставив чайник на утро."),
 ("A8_SH03",None,"mom_flat","a wide view of the yellow kitchen in morning light, an old kettle standing untouched on the stove","WS","eye","push_in","day",True,True,
  "чайник так и стоит на плите, и мать не разрешает его трогать до похорон."),
 ("A8_SH04","MOM_OLD","mom_flat","a medium shot of the small grey-haired mother held gently by a tall dark-coated man seen from behind","MS","eye","static","day",False,False,
  "ты приезжаешь через четыре часа и обнимаешь мать, ставшую за ночь меньше ростом."),
 ("A8_SH05",None,None,"an extreme close-up insert of a phone screen with a to-do list of funeral errands, items ticked one by one","ECU","top","static","day",True,False,
  "дальше ты делаешь то, что умеешь: списки, звонки, венки, автобус, поминальный зал."),
 ("A8_SH06","HERO_OLD","car","a medium close-up of the man driving in a black coat, a folder of funeral papers on the passenger seat","MCU","eye","static","day",False,False,
  "похороны обходятся в восемьдесят девять тысяч, и ты закрываешь всё одним переводом, не советуясь."),
 ("A8_SH07",None,"cemetery","a wide view of a quiet town cemetery among thin birches, a small dark group of figures by a fresh plot in the distance","WS","eye","static","day",True,False,
  "хоронят отца среди тонких берёз, в старой части, рядом с его родителями."),
 ("A8_SH08","HERO_OLD","cemetery","a close-up of the man's fist at his coat hem, knuckles white around a small brass shape","CU","eye","push_in","day",False,True,
  "у могилы ты стоишь с зажигалкой в кулаке, сжав её до белых костяшек."),
 ("A8_SH09","MOM_OLD","cemetery","a medium close-up of the mother in a black headscarf standing straight, fingers checking the glasses on their cord","MCU","eye","static","day",False,False,
  "мать держится прямо, только всё время трогает очки на шнурке, как проверяет."),
 ("A8_SH10",None,"cemetery","a close-up view of a temporary metal grave marker with a stamped number, fresh dark earth around it","CU","high","static","day",True,False,
  "памятник ставят через год, когда осядет земля, а пока только металлическая табличка с номером."),
 ("A8_SH11","HERO_OLD","mom_flat","a medium shot of the man speaking with relatives around the kitchen table set for a wake, his posture too composed","MS","eye","static","day",False,True,
  "на поминках ты говоришь с роднёй и слышишь у себя интонации рабочих переговоров."),
 ("A8_SH12","HERO_OLD","mom_flat","a close-up of the man stopping himself mid-sentence, eyes dropping to the tablecloth","CU","eye","static","day",False,False,
  "ты осекаешься на середине фразы про сроки и выходишь из кухни в подъезд."),
 ("A8_SH13","HERO_OLD","mom_stairwell","a medium shot of the man alone on the dim stairwell landing, forehead almost touching the cool wall paint","MS","eye","static","day",False,False,
  "в подъезде матери пахнет побелкой и супом, как в девяносто восьмом, и это невыносимо."),
 ("A8_SH14","MOM_OLD","mom_flat","a medium shot of the mother at the kitchen table quietly pushing a thick envelope back across the oilcloth","MS","eye","static","evening",False,False,
  "перед отъездом ты кладёшь на стол конверт с деньгами, и мать тихо отодвигает его обратно."),
 ("A8_SH15","MOM_OLD","mom_flat","a close-up of the mother's soft stubborn face in the warm lamp light, chin slightly raised","CU","eye","push_in","evening",False,False,
  "она говорит: у меня всё есть, ты и так всё оплатил, береги себя."),
 ("A8_SH16",None,"car","a wide view through a windshield of an empty night highway, cats-eyes and darkness beyond the beams","WS","pov","track","night",True,False,
  "ты выезжаешь в ночь, и двести километров до города проходят, как один тёмный коридор."),
 ("A8_SH17","OBJ:lighter",None,"an extreme close-up macro insert of the worn brass lighter lying on a leather passenger seat in passing road light","ECU","eye","static","night",True,False,
  "зажигалка отца лежит теперь на пассажирском сиденье, и ты всю дорогу поглядываешь на неё."),
 ("A8_SH18","HERO_OLD","hero_flat","a medium shot of the man sitting on the couch edge in his coat in the dark flat, city light through the tall windows","MS","eye","static","night",False,False,
  "дома ты садишься в пальто на край дивана и сидишь так до половины четвёртого."),
]

CATASTROPHE=[
 ("A9_SH01",None,"openspace","a wide establishing view of the night office, ranks of dark desks, one lit duty row, the dashboard dimmed","WS","high","push_in","night",True,False,
  "прошло два года, и мы вернулись туда, где началась эта история: ночная смена, выгрузка."),
 ("A9_SH02","HERO_OLD","boss_office","a medium shot of the department head at his desk scrolling a fresh database import, blue light on his face","MS","eye","static","night",False,False,
  "агентство выкупило портфель сети «Деньги сразу», четыре тысячи дел по четверти цены."),
 ("A9_SH03",None,"boss_office","an extreme close-up insert of one highlighted debtor row on the monitor, a small stubborn line of light","ECU","pov","push_in","night",True,True,
  "и в этой выгрузке — карточка: Зинаида Петровна, шестьдесят семь лет, займ сорок семь тысяч."),
 ("A9_SH04","HERO_OLD","boss_office","a medium close-up of the man gone completely still, one hand flat on the desk beside the mouse","MCU","eye","static","night",False,False,
  "ты сидишь неподвижно и смотришь на дату выдачи займа: апрель прошлого года."),
 ("A9_SH05",None,"boss_office","a close-up view of a call-history screen, a long dense column of outgoing call entries","CU","pov","static","night",True,False,
  "в карточке сто восемнадцать исходящих звонков за шестьдесят три дня, и все — твоего отдела."),
 ("A9_SH06","HERO_OLD","boss_office","a medium shot of the man putting on a headset with slow deliberate hands, monitor glow on the ear pad","MS","eye","static","night",False,True,
  "ты надеваешь гарнитуру, открываешь папку записей и нажимаешь ту кнопку, которую боялся всю ночь."),
 ("A9_SH07","HERO_OLD","boss_office","a close-up of the man listening with his eyes shut, jaw working once and going still","CU","eye","push_in","night",False,False,
  "первый звонок майский, вежливый: напоминаем о платеже, и голос матери отвечает: да-да, конечно."),
 ("A9_SH08",None,"mom_flat","a wide view of the yellow kitchen in daylight, an old push-button phone lying on the oilcloth table","WS","eye","static","day",True,False,
  "она разговаривает с коллекторами на той же кухне, где когда-то считали с отцом вполголоса."),
 ("A9_SH09","MOM_OLD","mom_flat","a medium close-up of the grey-haired mother with the phone at her ear, glasses lowered, nodding to the voice","MCU","eye","static","day",False,False,
  "мать извиняется первой, как извинялся Семён Ильич, и обещает заплатить с пенсии."),
 ("A9_SH10","HERO_OLD","boss_office","a close-up of the man's hand slowly closing into a fist on the desk as he listens on","CU","top","push_in","night",False,False,
  "ты слушаешь записи подряд, июнь, июль, август, и слышишь, как меняется её голос."),
 ("A9_SH11","KRIS_BASE","openspace","a medium close-up of the poised jet-black-bobbed operator mid-call at her desk, even and immaculate, violet nails still","MCU","eye","static","night",False,False,
  "с сентября её дело ведёт Кристина, твоя лучшая, аккуратно, строго по регламенту четыре-два."),
 ("A9_SH12",None,"boss_office","an extreme close-up insert of an audio waveform crawling across a monitor, a headset cable curling beneath","ECU","pov","static","night",True,True,
  "в записи от третьего октября Кристина говорит ровным голосом: ничего личного — это просто долг."),
 ("A9_SH13","HERO_OLD","boss_office","a medium shot of the man with the headset set down before him, sitting back in the dark glass office","MS","eye","static","night",False,False,
  "ты снимаешь гарнитуру и сидишь в тёмном кабинете, пока за стеклом работает твоя смена."),
 ("A9_SH14",None,"openspace","a wide view from the glass office over the lit duty row, small headsets bent to small screens","WS","high","static","night",True,False,
  "сорок столов делают четыре тысячи двести звонков в день, и один из номеров — мамин."),
 ("A9_SH15",None,"cemetery","a wide view of the cemetery in spring, birch leaves new, the numbered metal marker still on the settled plot","WS","eye","push_in","day",True,False,
  "теперь про сорок семь тысяч: в апреле прошлого года был год, как умер отец."),
 ("A9_SH16",None,None,"an extreme close-up insert of a granite headstone catalogue page with prices, a corner folded to mark one","ECU","top","static","day",True,False,
  "гранитный памятник с оградкой стоил шестьдесят восемь тысяч, а пенсия у матери двадцать одна."),
 ("A9_SH17","MOM_OLD","mfo_point","a medium close-up of the small grey-haired woman at a microloan counter window, passing papers under thick glass","MCU","eye","static","day",False,True,
  "просить у сына, который и так всё оплатил, она постеснялась и пошла в «Деньги сразу»."),
 ("A9_SH18",None,None,"an extreme close-up insert of a loan agreement page, a wrinkled finger resting under a dense small-print line","ECU","top","push_in","day",True,False,
  "сорок семь тысяч на двенадцать месяцев под три четверти процента в день, мелким шрифтом."),
 ("A9_SH19",None,"cemetery","a wide view of a polished dark granite headstone with an oval portrait, a tidy fenced plot, birches behind","WS","eye","static","day",True,True,
  "памятник поставили к маю, тёмный гранит, и отец смотрит с овального портрета моложе, чем был."),
 ("A9_SH20","MOM_OLD","mom_flat","a medium shot of the mother at the kitchen table sorting payment slips into two small piles, glasses down on her nose","MS","high","static","evening",False,False,
  "первые взносы она платила день в день, потом подорожали лекарства, и весь график поехал."),
 ("A9_SH21","MOM_OLD","mom_flat","a close-up of the mother's quiet face at the window, evening light on the lace curtain beside her","CU","eye","push_in","evening",False,False,
  "она никому не сказала ни слова: в её поколении долг — это стыд, а не строка в таблице."),
 ("A9_SH22","HERO_OLD","boss_office","a medium close-up of the man holding his personal phone with her number typed, thumb over the call key","MCU","eye","static","night",False,False,
  "ты набираешь мамин номер с личного телефона и впервые за много лет не знаешь скрипта."),
 ("A9_SH23","HERO_OLD","boss_office","a close-up of the man lowering the phone from his ear after one ring, screen light dying","CU","eye","static","night",False,False,
  "ты кладёшь трубку после первого гудка, потому что не знаешь, что скажешь после слова мама."),
 ("A9_SH24",None,"hero_flat","a wide view of the empty flat at night, a laptop alone alight on the dining table, the city cold beyond","WS","eye","push_in","night",True,False,
  "до рассвета ты сидишь с выгрузкой и считаешь: с пенями долг уже сто двенадцать тысяч триста четырнадцать."),
 ("A9_SH25","HERO_OLD","hero_flat","a medium shot of the man sitting back from the laptop, staring at the dark ceiling, hands flat on the table","MS","low","static","night",False,False,
  "регламент, который ты подписал, не нарушен ни в одном пункте, и в этом всё дело."),
 ("A9_SH26","OBJ:lighter",None,"an extreme close-up macro insert of the worn brass lighter beside a laptop touchpad in cold screen light","ECU","eye","static","night",True,False,
  "зажигалка лежит рядом с ноутбуком, и ты думаешь про отца и про тот февральский стук."),
 ("A9_SH27","HERO_OLD","hero_flat","a medium close-up of the man's face at first grey light, decision settled in it like set concrete","MCU","eye","push_in","dawn",False,False,
  "к шести утра ты знаешь, что сделаешь в девять, когда откроется бухгалтерия банка."),
 ("A9_SH28",None,"street_90s","a wide view of the waking city street at dawn, first buses, long cold shadows down the asphalt","WS","eye","pan_left","dawn",True,False,
  "в восемь ты бреешься, надеваешь свежую рубашку и едешь в офис раньше всей смены."),
]

if __name__=="__main__":
    seed_act("father",P_FATHER,FATHER)
    seed_act("catastrophe",P_CATASTROPHE,CATASTROPHE)
