# -*- coding: utf-8 -*-
"""kept_woman A4 tighten + A5 mother. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_kept_woman_A4A5.py"""
from _kept_woman_engine import seed_act

P_TIGHTEN="cooling anxious palette, desaturated gold turning to clinical white and cold blue, harder light"
P_MOTHER="warm poor palette, faded floral tones, soft weak provincial daylight, tired warmth"

TIGHTEN=[
 ("A4_SH01",None,"hotel_seaside","a wide view of a luxury seaside hotel lobby and terrace in bright day, marble and glass over a blue sea, sleek and cool","WS","eye","push_in","day",True,False,
  "в двадцать семь ты приезжаешь на побережье, как всегда, но в этот раз что-то в воздухе не так."),
 ("A4_SH02","VIKA_PRIME","hotel_seaside","a medium shot of the mid-twenties woman standing in a hotel lobby noticing something across the room, her poise faltering","MS","eye","static","day",False,False,
  "в лобби ты видишь мужчину своего круга под руку с девочкой лет двадцати, и внутри что-то холодеет."),
 ("A4_SH03","RIVAL_BASE","hotel_seaside","a medium close-up of a fresh radiant young woman of twenty-four with dark auburn hair, dewy glowing skin, laughing brightly","MCU","over","static","day",False,False,
  "она моложе тебя лет на семь, свежая и сияющая, и смотрит на тебя как ты когда-то смотрела на старших."),
 ("A4_SH04","VIKA_PRIME","hotel_seaside","a close-up of the woman's stung face as she realizes she is no longer the youngest in the room","CU","eye","push_in","day",False,False,
  "ты вдруг оказываешься не самой молодой в комнате, и это оказывается больнее любого удара."),
 ("A4_SH05",None,None,"an extreme close-up macro insert of a full untouched wine glass on a hotel nightstand in dim night light, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "на тумбочке стоит нетронутый бокал, ты лежишь в темноте и считаешь, сколько тебе ещё осталось лет."),
 ("A4_SH06",None,"salon","a wide view of a bright cosmetology salon, a reclining treatment chair, a ring-lit mirror and shelves of serums, clinical and cold","WS","eye","pan_left","day",True,False,
  "вернувшись в город, ты идёшь по салонам и клиникам красоты, будто можно откупиться от времени."),
 ("A4_SH07","VIKA_PRIME","salon","a medium shot of the woman reclining in a salon treatment chair under a ring light, a gloved beautician's hands near her face","MS","high","static","day",False,False,
  "уколы, процедуры, кремы дороже машины, ты платишь за каждый год, что пытаешься удержать."),
 ("A4_SH08",None,None,"an extreme close-up macro insert of small syringes and serum bottles lined on a white clinical surface, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "на белом столе выстроились шприцы и баночки, и это теперь твоя новая работа, дороже прежней."),
 ("A4_SH09","VIKA_PRIME","salon","a medium close-up of the woman studying her own face closely in a ring-lit mirror, tense and appraising","MCU","eye","static","day",False,False,
  "ты изучаешь своё лицо каждое утро, как бухгалтер изучает убыток, и цифры не в твою пользу."),
 ("A4_SH10","VIKA_PRIME","salon","a close-up of the woman's face setting into a hard resolve in the salon mirror light","CU","eye","push_in","day",False,False,
  "ты решаешь работать ещё усерднее, брать больше, пока лицо ещё продаётся дорого."),
 ("A4_SH11","VIKA_PRIME","penthouse_apartment","a medium shot of the woman standing frozen in a marble apartment bathroom doorway, a shocked stillness","MS","eye","static","day",False,False,
  "в двадцать восемь ты узнаёшь, что беременна, и первое, что ты чувствуешь, это не радость, а страх."),
 ("A4_SH12",None,None,"an extreme close-up macro insert of a small pregnancy test lying on the edge of a marble sink, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "на краю раковины лежит тест с двумя полосками, и ты смотришь на него как на приговор."),
 ("A4_SH13","VIKA_PRIME","penthouse_apartment","a close-up of the woman's face making a cold hard decision alone in the apartment","CU","eye","push_in","day",False,False,
  "ребёнок не помещается в эту жизнь, ни в квартиру на чужое имя, ни в расписание чужих приездов."),
 ("A4_SH14","VIKA_PRIME","clinic_corridor","a wide shot of the woman sitting alone and composed on a chair in a pale antiseptic clinic corridor","WS","eye","static","day",False,False,
  "через несколько дней ты сидишь в тихом коридоре клиники, где пахнет чистотой и ничем больше."),
 ("A4_SH15","VIKA_PRIME","clinic_corridor","a close-up of the woman waiting in the clinic corridor with an expensive handbag on her lap, a blank held face","CU","eye","static","day",False,False,
  "ты держишь на коленях дорогую сумку и ждёшь, когда назовут номер, будто пришла на обычную процедуру."),
 ("A4_SH16",None,"clinic_corridor","an extreme close-up macro insert of a plain closed white clinic door with a small call-number light beside it, filling the frame in sharp focus, shallow depth of field","ECU","eye","static","day",True,True,
  "белая дверь закрывается за тобой, и ты делаешь выбор, который потом не отменить уже никогда."),
 ("A4_SH17","VIKA_PRIME","penthouse_apartment","a medium shot of the woman pouring a glass of wine alone in a cold empty apartment at night","MS","eye","static","night",False,False,
  "ты возвращаешься в пустую квартиру, наливаешь себе вина и говоришь себе, что так было правильно."),
 ("A4_SH18","VIKA_PRIME","penthouse_apartment","a close-up of the woman's dry-eyed hollow face at a dark window, not crying","CU","eye","push_in","night",False,False,
  "ты не плачешь, потому что Лера учила, что чувства — это роскошь, которую ты себе не позволяешь."),
 ("A4_SH19",None,None,"a wide night view of a glittering city skyline from a high window, cold and indifferent, sheer curtains","WS","eye","push_in","night",True,False,
  "за окном горит тот же город, но что-то в тебе после той двери погасло насовсем."),
 ("A4_SH20","ARTUR_BASE","luxury_restaurant","a medium close-up of the ageing silver-haired man at a restaurant table promising something while looking past the viewer","MCU","over","static","night",False,False,
  "Артур так и не узнаёт, и через неделю снова обещает развод, глядя куда-то поверх твоей головы."),
 ("A4_SH21","VIKA_PRIME","luxury_restaurant","a close-up of the woman noticing the man's gaze drift to a young waitress, hiding her reaction","CU","eye","static","night",False,False,
  "ты замечаешь, что он смотрит на официантку дольше, чем на тебя, и делаешь вид, что не заметила."),
 ("A4_SH22","VIKA_PRIME","salon","a medium shot of the woman back in the salon chair undergoing another procedure, weary and determined","MS","high","static","day",False,False,
  "в двадцать девять ты тратишь на то, чтобы выглядеть на двадцать два, больше, чем зарабатываешь."),
 ("A4_SH23",None,None,"an extreme close-up macro insert of a magnifying mirror reflecting fine lines at the corner of an eye and a tube of concealer, filling the frame in sharp focus, shallow depth of field","ECU","eye","static","day",True,False,
  "зеркало показывает то, что не спрятать за деньги, и ты начинаешь его тихо ненавидеть."),
 ("A4_SH24","VIKA_PRIME","salon","a medium close-up of the still-beautiful woman of twenty-nine composing her face, a new fear behind the eyes","MCU","eye","push_in","day",False,True,
  "тебе двадцать девять, ты всё ещё красива, но впервые начинаешь слышать, как тикают твои часы."),
]

MOTHER=[
 ("A5_SH01","VIKA_MID","bus_station","a wide shot of an elegant woman of thirty-two in an expensive coat stepping off an intercity coach onto a shabby small-town platform","WS","low","static","day",False,False,
  "в тридцать два ты впервые за годы едешь домой, в тот самый посёлок, откуда так рвалась."),
 ("A5_SH02","VIKA_MID","bus_station","a medium shot of the well-dressed woman standing out sharply among the dusty provincial square and plain locals","MS","eye","static","day",False,False,
  "ты стоишь на пыльной площади в дорогом пальто, и соседи оборачиваются, не узнавая ту девочку."),
 ("A5_SH03",None,None,"a wide establishing view of a poor unchanged small town, grey low houses, muddy puddles and bare trees under flat daylight","WS","high","pan_right","day",True,False,
  "посёлок не изменился, те же серые дома, те же лужи, только стал ещё меньше и беднее."),
 ("A5_SH04","MAT_BASE","home_town_kitchen","a medium shot of a worn woman of fifty-five in a faded floral cardigan with reading glasses on a beaded cord, tearful with pride at a kitchen door","MS","eye","static","day",False,False,
  "мать встречает тебя в том же выцветшем кардигане, с очками на шнурке, и плачет от гордости."),
 ("A5_SH05","MAT_BASE","home_town_kitchen","a medium close-up of the grey-haired mother speaking proudly in her cramped kitchen, glasses on their cord","MCU","eye","static","day",False,False,
  "она всем в посёлке рассказывает, что её дочь — большой начальник в столице, и ты не поправляешь."),
 ("A5_SH06","VIKA_MID","home_town_kitchen","a close-up of the elegant daughter smiling and nodding, lying gently, warm poor kitchen light on her face","CU","eye","static","day",False,False,
  "ты киваешь и улыбаешься, и врёшь ей в глаза так же легко, как научилась врать всем остальным."),
 ("A5_SH07","VIKA_MID","home_town_kitchen","a medium shot of the daughter and mother sitting with tea at a small kitchen table with a plastic tablecloth","MS","eye","static","day",False,False,
  "вы пьёте чай на кухне, где ты выросла, и впервые за годы тебе хочется просто остаться здесь."),
 ("A5_SH08",None,None,"an extreme close-up macro insert of a worn woman's cracked work-roughened hands cupping a chipped tea glass, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "руки матери в трещинах и мозолях, и рядом с ними твои ухоженные пальцы кажутся совсем чужими."),
 ("A5_SH09","MAT_BASE","home_town_kitchen","a medium shot of the mother mentioning her worries lightly over tea, gesturing at a water-stained ceiling","MS","eye","static","day",False,False,
  "мать между делом говорит, что крыша течёт и что сердце пошаливает, но денег на врача нет."),
 ("A5_SH10","VIKA_MID","home_town_kitchen","a close-up of the daughter's face quietly deciding, warmth and guilt mixed","CU","eye","push_in","day",False,False,
  "ты молча решаешь оплатить и крышу, и операцию, и лучшего врача, какого только можно найти."),
 ("A5_SH11",None,None,"an extreme close-up macro insert of a thick plain paper envelope stuffed with folded cash left on a worn plastic-covered kitchen table, filling the frame in sharp focus, shallow depth of field","ECU","top","static","day",True,False,
  "ты оставляешь на столе конверт, в котором больше денег, чем мать видела за всю свою жизнь."),
 ("A5_SH12","MAT_BASE","home_town_kitchen","a medium close-up of the mother refusing then tearfully accepting an envelope, confused and moved","MCU","eye","static","day",False,False,
  "мать отказывается, потом плачет и берёт, и тихо спрашивает, откуда у помощницы такие деньги."),
 ("A5_SH13","VIKA_MID","home_town_kitchen","a close-up of the daughter deflecting the question with a practiced smile","CU","eye","static","day",False,False,
  "ты говоришь, что получила премию, и меняешь тему, пока она не успела задать второй вопрос."),
 ("A5_SH14",None,"home_town_kitchen","a wide view of a cramped provincial kitchen wall with a faded child's school photograph in a simple frame, warm poor light","WS","eye","static","day",True,False,
  "на стене висит твоя школьная фотография, девочка с косичками, которая мечтала совсем не об этом."),
 ("A5_SH15",None,None,"an extreme close-up macro insert of an old faded framed school photograph of a young girl with braids, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","push_in","day",True,False,
  "ты смотришь на эту девочку и не можешь понять, в какой именно день ты её потеряла."),
 ("A5_SH16","VIKA_MID","home_town_kitchen","a medium shot of the mother embracing the daughter at the doorway, the daughter stiff in her expensive coat","MS","over","static","day",False,False,
  "на пороге мать обнимает тебя и просит приезжать чаще, и ты обещаешь, зная, что не приедешь."),
 ("A5_SH17","VIKA_MID","home_town_kitchen","a close-up of the daughter's guilty face at the door as she leaves","CU","eye","static","day",False,False,
  "ты уезжаешь с чувством, что предала не только мать, но и ту девочку с фотографии на стене."),
 ("A5_SH18",None,None,"a wide view of a small grey town shrinking away through the rear window of a departing coach, muddy road and low houses","WS","eye","static","day",True,False,
  "автобус увозит тебя обратно в город, и посёлок исчезает в заднем стекле, кажется, навсегда."),
 ("A5_SH19","VIKA_MID",None,"a medium close-up of the elegant woman of thirty-two sitting by a coach window as grey countryside slides past, a guarded closed face","MCU","eye","static","day",False,False,
  "ты возвращаешься к чужим деньгам и чужим мужчинам, потому что больше ты уже ничего не умеешь."),
 ("A5_SH20","VIKA_MID",None,"a close-up of the woman's face against the coach window, a quiet corrosive guilt behind her calm","CU","eye","push_in","day",False,True,
  "ты говоришь себе, что делаешь это ради матери, и почти не замечаешь, что это давно неправда."),
]

if __name__=="__main__":
    seed_act("tighten", P_TIGHTEN, TIGHTEN, render_mode="static")
    seed_act("mother",  P_MOTHER,  MOTHER,  render_mode="static")
