# -*- coding: utf-8 -*-
"""Batch 3: act05_cody + act06_proofs + act07_breaks (Part I climax / descent)."""
from _flat_earth_engine import seed_act

PAL_CODY = "lived-in domestic palette, warm lamps fighting cold cluttered shadow, homey ambers turning anxious"
A5 = [
 ("A5_SH01","LINDA","dawson_kitchen","a pregnant woman with a dark bob sitting at the yellow kitchen table, a man's hand resting on her round belly","WS","eye","push_in","day",False,False,
  "тебе тридцать один, и линда беременна, и на девять месяцев ты почти забываешь про край земли."),
 ("A5_SH02","LINDA","dawson_kitchen","close on the pregnant woman's tired tender face, eyes closed, a faint hopeful smile in warm kitchen light","CU","eye","static","day",False,False,
  "она кладёт твою руку себе на живот, и говорит, давай ради него хотя бы попробуем жить как все."),
 ("A5_SH03","RAY","dawson_house_living","a man in his thirties carrying a wooden bassinet into a living room whose far wall is covered with pinned maps","MS","eye","static","day",False,False,
  "вы приносите домой сына, и ты ставишь его кроватку в той же комнате, где висят твои карты."),
 ("A5_SH04",None,"dawson_house_living","extreme close on a newborn's tiny hand curled around a man's rough finger in soft lamplight","ECU","high","push_in","night",False,True,
  "коди хватает тебя за палец крошечной рукой, и в эту секунду ты любишь его сильнее всего на свете."),
 ("A5_SH05","RAY","dawson_house_living","a man cradling a newborn close in the dim map-lined room at night, whispering against the baby's head","MCU","low","push_in","night",False,False,
  "ты качаешь его ночами и шепчешь ему не колыбельные, а правду, мир плоский, сынок, тебе не соврут."),
 ("A5_SH06",None,"cody_bedroom","extreme close on a folded paper boat tucked into the corner of a baby's crib among soft blankets","INSERT","top","push_in","night",False,True,
  "ты складываешь ему из карты бумажный кораблик, и он становится первой его игрушкой, и его талисманом."),
 ("A5_SH07",None,"dawson_house_living","a living room where pinned maps have spread from one wall onto a second, a crib standing among the charts","WS","eye","pan_right","day",False,False,
  "карты тем временем переползают на вторую стену, потом на третью, и кроватка тонет среди них."),
 ("A5_SH08","LINDA","dawson_house_living","a woman rocking a baby in a chair, glancing up uneasily at the maps creeping across the ceiling corner","MS","eye","static","day",False,False,
  "линда качает коди и всё чаще поднимает глаза на стены, и всё реже что-нибудь про них говорит."),
 ("A5_SH09","LINDA","dawson_house_living","close on the woman's face, tenderness and a deepening worry mixed as she looks past the baby at the walls","CU","eye","push_in","day",False,False,
  "она ещё надеется, что с сыном ты остепенишься, но в глазах у неё уже поселяется тихий страх."),
 ("A5_SH10",None,"percy_priest_lake","a man with a small boy on his shoulders walking out along a jetty at golden hour, the flat lake ahead","WS","low","track","dusk",False,False,
  "коди подрастает, и ты водишь его на то же озеро, на тот же пирс, где когда-то стоял сам в его годы."),
 ("A5_SH11","RAY","percy_priest_lake","a man crouching beside a small boy, guiding the child's hand to hold a brass ruler against the flat water","MCU","eye","static","dusk",False,True,
  "ты вкладываешь ему в ручонку дедову линейку и показываешь, видишь, малыш, вода ровная, как стол."),
 ("A5_SH12","CODY_KID","percy_priest_lake","close on a small freckled boy squinting seriously along a brass ruler at the flat lake, copying his father","CU","low","push_in","dusk",False,False,
  "коди щурится вдоль линейки, очень серьёзно, и говорит, ровно, пап, и ты счастлив до слёз."),
 ("A5_SH13",None,"percy_priest_lake","extreme close on a folded paper boat drifting on dead-flat golden water near a jetty piling","INSERT","high","static","dusk",False,True,
  "он пускает на воду свой бумажный кораблик, и тот плывёт по ровной глади, никуда не сворачивая."),
 ("A5_SH14",None,"dawson_kitchen","a family of three at dinner in a warm kitchen, a child in a booster seat, a pinned map just visible behind","MS","eye","static","night",False,False,
  "несколько лет вы почти счастливы, ужины втроём, смех, и карты только фоном, только по краю стола."),
 ("A5_SH15","CODY_KID","dawson_kitchen","close on a small freckled boy laughing with food on his face at the kitchen table, warm light","CU","eye","static","night",False,False,
  "коди смеётся, и в эти вечера ты почти обычный отец, и тебе кажется, что так может быть всегда."),
 ("A5_SH16",None,"dawson_house_living","a living room now completely covered in maps and red string, a child's toys scattered among the charts on the floor","WS","high","pan_left","day",False,True,
  "но проходит год, другой, и карты захватывают весь дом, и игрушки коди валяются среди красных нитей."),
 ("A5_SH17","RAY","dawson_house_living","a man guiding a small boy's hand to press a pin into a wall map, both absorbed, the room dense with charts","MCU","eye","static","day",False,False,
  "ты учишь коди втыкать булавки в карту, и он делает это старательно, лишь бы побыть рядом с тобой."),
 ("A5_SH18","CODY_KID","dawson_house_living","close on a small boy carefully pushing a pin into a map, tongue between teeth, mimicking his father exactly","CU","over","push_in","day",False,False,
  "он повторяет за тобой каждое слово, мир плоский, нам врут, и ты не слышишь в этом ничего страшного."),
 ("A5_SH19","LINDA","dawson_house_living","a woman standing in a doorway with arms crossed, watching father and son at the map wall, unreadable","MS","eye","static","day",False,False,
  "линда смотрит из дверей, как ты воспитываешь сына, и однажды тихо говорит, не втягивай его, прошу."),
 ("A5_SH20","LINDA","dawson_house_living","close on the woman's face in the doorway, love and fear at war, jaw tight","CU","eye","push_in","day",False,False,
  "ты отмахиваешься, я даю ему правду, а ты хочешь, чтоб его обманывали, как всех, и она замолкает."),
 ("A5_SH21",None,"east_nash_street","a man walking a small boy to school down a Nashville street, a satchel of leaflets over the man's shoulder","WS","eye","track","day",False,False,
  "ты водишь коди в школу, и по дороге раздаёшь соседям листовки, держа сына за руку."),
 ("A5_SH22",None,"east_nash_street","parents at a school gate quietly drawing their children aside as a man and a small boy approach","WS","high","static","day",False,False,
  "у школьных ворот родители отводят своих детей в сторону, и коди впервые это замечает."),
 ("A5_SH23","CODY_KID","east_nash_street","close on a small boy looking up confused as other children are pulled away from him by their parents","CU","low","push_in","day",False,False,
  "он смотрит на тебя снизу вверх и спрашивает, пап, а почему нас все обходят, и ты не находишь слов."),
 ("A5_SH24","LINDA","dawson_kitchen","a woman at the kitchen table spreading out a fan of unpaid bills, a man standing turned half away","MS","eye","static","night",False,False,
  "вечером линда раскладывает на столе счета, и говорит, рэй, мы не тянем, твои приборы съели всё."),
 ("A5_SH25",None,"dawson_kitchen","extreme close on a fan of red-stamped unpaid bills beside a thin fold of remaining cash on the formica","ECU","top","push_in","night",False,True,
  "счета с красными штампами, и тоненькая пачка налички, которой не хватит и до конца месяца."),
 ("A5_SH26","RAY","dawson_kitchen","a man waving a dismissive hand over the bills, certain and unbothered, the wall map behind him","MCU","low","static","night",False,False,
  "а ты говоришь, деньги ерунда, линда, правда важнее денег, и не замечаешь, как у неё опускаются руки."),
 ("A5_SH27","LINDA","dawson_kitchen","close on the woman's clenched jaw and wet eyes as she gathers the bills back up in silence","CU","eye","push_in","night",False,False,
  "она молча собирает счета обратно, и в эту ночь в ней что-то трескается впервые, ещё совсем тихо."),
 ("A5_SH28",None,"percy_priest_lake","a man and a small boy sitting close at the end of a jetty at dusk, the flat lake glowing, a paper boat between them","EWS","eye","pull_out","dusk",True,True,
  "но у воды вы по-прежнему счастливы, и ты обещаешь коди то же, что когда-то обещал себе у этой воды."),
 ("A5_SH29","RAY","percy_priest_lake","a man pointing out across the flat water to a small attentive boy, both lit gold, the ruler in the man's hand","MCU","low","static","dusk",False,False,
  "однажды мы с тобой дойдём до самого края, сынок, и сами увидим, где кончается вода, обещаю."),
 ("A5_SH30","CODY_KID","percy_priest_lake","close on a small boy gazing up trusting and adoring, clutching a folded paper boat to his chest","CU","eye","push_in","dusk",False,True,
  "и коди верит тебе всем сердцем, прижимает кораблик к груди, и говорит, дойдём, пап, обязательно дойдём."),
]

PAL_PROOF = "obsessive cold palette, harsh task-light against grey daylight, anxious steel blues and bleached white"
A6 = [
 ("A6_SH01",None,"movement_backroom","a hotel-style conference room filled with rows of chairs and a big flat-earth disc banner on the stage, a sparse crowd","WS","high","push_in","day",False,False,
  "тебе тридцать пять, и ты едешь на большой съезд, тот самый билет за двести долларов наконец пригодился."),
 ("A6_SH02","RAY","movement_backroom","a man standing dazzled among conference chairs, programme in hand, eyes shining at the stage","MCU","low","push_in","day",False,False,
  "ты стоишь среди сотен таких же, и тебе кажется, что вот она, армия правды, и вы скоро победите."),
 ("A6_SH03","EARL","movement_backroom","the bald man in aviators on a small stage selling books and gadgets from a folding table, microphone in hand","MS","low","static","day",False,True,
  "со сцены эрл продаёт книги, карты, лазеры, по сто, по триста долларов, и зал разбирает всё."),
 ("A6_SH04","RAY","movement_backroom","a man emptying his wallet at a merchandise table, arms full of books and a boxed laser device","WS","high","static","day",False,False,
  "ты спускаешь почти все оставшиеся деньги на приборы, которыми эрл клянётся доказать форму земли."),
 ("A6_SH05",None,"percy_priest_lake","a man alone on a long jetty at night aiming a green laser low across the dead-flat reservoir into the dark","WS","low","static","night",False,True,
  "в ту же ночь ты ставишь главный опыт, светишь лазером вдоль воды на полторы мили, в темноту."),
 ("A6_SH06",None,"percy_priest_lake","extreme close on a green laser dot striking a distant marker post low above the flat black water","ECU","eye","push_in","night",False,True,
  "и луч попадает в метку на дальнем столбе, ровно, не уходит за горизонт, как должен был бы на шаре."),
 ("A6_SH07","RAY","percy_priest_lake","a man on the jetty raising both fists at the night, triumphant and alone, the laser still glowing","MCU","low","push_in","night",False,True,
  "ты кричишь в пустую ночь, ровно, ровно, я доказал, и тот холодок снова продирает тебя до костей."),
 ("A6_SH08",None,"reservoir_shore_south","a man wading knee-deep in cold water at dawn sighting a long carpenter's level along the flat surface","WS","eye","static","dawn",False,False,
  "ты повторяешь опыт бэдфордского уровня, ложишься у самой воды, и снова всё ровно, всё всегда ровно."),
 ("A6_SH09",None,"ridge_overlook","a man releasing a large weather balloon trailing a small camera rig from a hilltop at dawn","WS","low","tilt_up","dawn",False,False,
  "ты запускаешь шар с камерой, чтобы снять горизонт сверху, и копишь на это полгода по доллару."),
 ("A6_SH10",None,"dawson_house_living","extreme close on a paused video frame of a hazy high-altitude horizon, a man's finger tracing it flat on the screen","ECU","eye","push_in","day",False,True,
  "на записи горизонт чуть размыт, но ты ведёшь по нему пальцем и говоришь, видите, ровный, плоский."),
 ("A6_SH11","RAY","tv_repair_shop","a man at the repair-shop counter lecturing the owner instead of working, tools idle, the owner frowning","OTS","eye","static","day",False,False,
  "на работе ты больше не чинишь, ты проповедуешь, и хозяин мастерской терпит тебя последние недели."),
 ("A6_SH12","RAY","tv_repair_shop","a man being handed his final pay envelope across a counter, the owner looking away, the man unbothered","MCU","eye","static","day",False,False,
  "тебя увольняют в тридцать шесть, и ты даже рад, говоришь, теперь займусь правдой на полную."),
 ("A6_SH13",None,"dawson_kitchen","a kitchen table covered with a second-mortgage form, a pen, and a calculator under a hanging lamp","INSERT","top","push_in","night",False,False,
  "чтобы купить ещё приборов, ты берёшь второй заём под дом, и подписываешь, не дочитав до конца."),
 ("A6_SH14","LINDA","dawson_kitchen","a woman in a diner uniform sinking into a kitchen chair after a shift, exhausted, holding her shoes","MS","eye","static","night",False,False,
  "линда выходит на две смены в закусочной, и приходит за полночь, и на твои карты уже не смотрит."),
 ("A6_SH15","LINDA","dawson_kitchen","close on the exhausted woman's face, eyes shut, rubbing the bridge of her nose at the table","CU","eye","static","night",False,False,
  "она тянет дом и сына одна, а ты сидишь в соседней комнате и считаешь градусы кривизны, которой нет."),
 ("A6_SH16","EARL","movement_backroom","the bald man in aviators clapping a hand on the obsessed man's shoulder, encouraging, a new gadget between them","OTS","over","static","night",False,False,
  "эрл звонит, хвалит твои опыты, и подсказывает купить новый прибор, ещё дороже, и ты находишь деньги."),
 ("A6_SH17","RAY","dawson_house_living","a man surrounded by boxes of unopened instruments in the map room, feverishly reading a manual at 3am","MCU","low","push_in","night",False,False,
  "коробки с приборами громоздятся нераспечатанными, но ты покупаешь ещё, тебе всегда мало доказательств."),
 ("A6_SH18",None,"dawson_house_living","extreme close on a corkboard where pins and red string now cover family photos, the maps swallowing everything","ECU","eye","pan_right","day",False,True,
  "красные нити уже затягивают семейные фотографии, лицо линды, лицо коди, всё под слоем твоих карт."),
 ("A6_SH19",None,"reservoir_shore_south","a man standing alone at grey dawn at the water's edge surrounded by tripods and instruments, fog around him","WS","high","static","dawn",True,False,
  "ты ставишь опыт за опытом, и каждый показывает ровно то, что ты хочешь увидеть, и ни на йоту иначе."),
 ("A6_SH20","RAY","reservoir_shore_south","close on the man's gaunt obsessed face at dawn, eyes red from no sleep, certain and feverish","CU","low","push_in","dawn",False,False,
  "ты не спишь ночами, и чем меньше спишь, тем яснее тебе всё видно, тем громче поёт твоя правда."),
 ("A6_SH21","CODY_KID","dawson_house_living","a small boy standing ignored in the doorway of the map room while his father bends over instruments","MS","eye","static","night",False,False,
  "коди заглядывает в комнату, зовёт ужинать, а ты не слышишь, и он уходит один, тихо прикрыв дверь."),
 ("A6_SH22","CODY_KID","dawson_kitchen","a small boy eating dinner alone at the kitchen table while a doorway behind glows with the map room's lamp","WS","high","static","night",False,False,
  "он всё чаще ужинает один, и всё реже зовёт тебя, и ты этого попросту не замечаешь, тебе не до того."),
 ("A6_SH23",None,"dawson_kitchen","extreme close on a child's drawing on the fridge of three stick figures, one scribbled over with red marker","ECU","eye","push_in","night",False,True,
  "на холодильнике висит его рисунок, трое человечков, и однажды одного из них он зачёркивает красным."),
 ("A6_SH24","LINDA","dawson_kitchen","a woman quietly packing a small overnight bag for the boy at the kitchen table, not looking up","MS","eye","static","night",False,False,
  "линда начинает увозить коди к матери на выходные, чтобы он хоть пару дней пожил, как нормальный ребёнок."),
 ("A6_SH25","RAY","dawson_house_living","a man so absorbed in a wall of calculations that he does not notice the house emptying around him","MCU","eye","push_in","day",False,False,
  "ты не замечаешь, что дом пустеет, тебе кажется, что ты на пороге, что край земли уже совсем близко."),
 ("A6_SH26",None,"movement_backroom","an emptier meeting room with fewer chairs occupied, the banner faded, the group thinning out","WS","high","static","night",False,False,
  "движение между тем редеет, своих остаётся всё меньше, кто-то понял, кто-то просто устал верить."),
 ("A6_SH27","EARL","movement_backroom","the bald man in aviators counting a thick fold of cash backstage, away from the dwindling group","MCU","low","static","night",False,False,
  "а эрл всё считает выручку за кулисами, и тебе даже в голову не приходит спросить, куда идут деньги."),
 ("A6_SH28","RAY","dawson_house_living","a feverish man taping a giant new map over the family photos, blotting them out entirely, late at night","MS","low","push_in","night",False,False,
  "ты вешаешь новую огромную карту прямо поверх ваших фотографий, и больше их с этой стены не видно."),
 ("A6_SH29",None,"east_nash_street","a lone lit window in a dark street, a man's silhouette among charts, no other light on the whole block","WS","eye","pull_out","night",True,False,
  "снова в твоём окне горит единственный свет на улице, только теперь в доме за этим окном ты совсем один."),
 ("A6_SH30","RAY","dawson_house_living","a man asleep at his cluttered desk over open instrument manuals, the giant map looming, dawn at the window","MCU","high","static","dawn",False,False,
  "ты засыпаешь над чертежами под утро, и тебе снится ровная линия воды, всё дальше и дальше на юг."),
 ("A6_SH31",None,"ridge_overlook","a vast flat dawn vista of misted farmland under an immense level horizon, telephone wires across the foreground","EWS","high","pan_right","dawn",True,False,
  "во сне горизонт зовёт тебя, ровный, как натянутая нить, и ты идёшь к нему, и никак не доходишь."),
 ("A6_SH32","CODY_KID","percy_priest_lake","a small boy waiting alone on the jetty at dusk with a paper boat, looking back toward the empty path","MCU","eye","static","dusk",False,False,
  "коди ждёт тебя у воды с корабликом, как ты обещал, а ты не приходишь, ты считаешь градусы дома."),
 ("A6_SH33","CODY_KID","percy_priest_lake","close on a small boy's disappointed face at dusk, lowering a paper boat he no longer wants to float","CU","low","push_in","dusk",False,True,
  "он ждёт до темноты, потом идёт домой один, и больше никогда не просит сводить его на озеро."),
 ("A6_SH34",None,"dawson_house_living","extreme close on a forgotten paper boat gathering dust on a shelf beside a stack of instrument boxes","INSERT","top","push_in","day",False,True,
  "его бумажный кораблик пылится на полке, а ты этого не видишь, ты весь уже там, на краю света."),
]

PAL_BREAK = "cold fracturing palette, flat grey north light, drained desaturated blue, all warmth drained away"
A7 = [
 ("A7_SH01","CODY_TEEN","cody_bedroom","a guarded teenage boy in a grey hoodie sitting on his bed, arms crossed, a map of his father's creeping around the door","MS","eye","push_in","day",False,False,
  "коди исполняется четырнадцать, и он давно не верит ни в какой край земли, он просто стыдится тебя."),
 ("A7_SH02","CODY_TEEN","east_nash_street","a teenage boy walking fast and hunched past other kids who laugh and point, hood up against them","WS","eye","track","day",False,False,
  "в школе его зовут сыном психа, и он идёт мимо одноклассников, втянув голову, и делает вид, что не слышит."),
 ("A7_SH03",None,"east_nash_street","a cluster of teenagers laughing and pointing at an off-frame boy near a chain-link fence after school","WS","high","static","day",False,False,
  "его дразнят твоими листовками, твоими опытами, и каждый день он расплачивается за твою правду."),
 ("A7_SH04","CODY_TEEN","dawson_house_living","a teenage boy tearing a pinned map off the wall and throwing it down, shouting, the room dense with charts","MCU","low","push_in","day",False,False,
  "однажды он срывает со стены карту и кричит, всё это бред, папа, над нами смеётся весь город."),
 ("A7_SH05","RAY","dawson_house_living","a man standing stunned but certain among his charts, hand half-raised, hurt rather than angry","MCU","eye","static","day",False,False,
  "ты не злишься, тебе просто больно, и ты тихо говоришь, однажды ты поймёшь, что я был прав, сынок."),
 ("A7_SH06","CODY_TEEN","dawson_house_living","close on the teenage boy's furious wet eyes, jaw shaking, on the edge of tears he refuses to shed","CU","eye","push_in","day",False,False,
  "а он отвечает, мне не нужна твоя правда, мне нужен был отец, и уходит, хлопнув дверью так, что сыплется штукатурка."),
 ("A7_SH07",None,"cody_bedroom","a teenage bedroom stripped bare, posters gone, a packed duffel bag on the stripped bed by an open drawer","WS","eye","push_in","day",False,True,
  "наутро ты находишь его комнату полупустой, и понимаешь, что сын собирает вещи, чтобы уехать с матерью."),
 ("A7_SH08","LINDA","dawson_kitchen","a worn woman standing at the kitchen counter, back to the room, gripping the edge, gathering herself","MCU","over","static","day",False,False,
  "линда стоит у плиты спиной к тебе, и говорит ровным голосом, я больше так не могу, рэй, ни дня."),
 ("A7_SH09","RAY","dawson_kitchen","a man at the kitchen table reaching out a placating hand, still not understanding, the map wall behind","MCU","eye","static","day",False,False,
  "ты говоришь, потерпи ещё немного, я почти доказал, ещё один опыт, и весь мир признает мою правоту."),
 ("A7_SH10","LINDA","dawson_kitchen","the woman turning to face the man, tears on a calm exhausted face, finally certain of her decision","CU","eye","push_in","day",False,False,
  "она поворачивается, и говорит сквозь слёзы, твоя правота забрала наш дом, нашего сына, и меня."),
 ("A7_SH11",None,"dawson_kitchen","extreme close on a red-stamped foreclosure notice lying on the formica table beside a set of house keys","ECU","top","push_in","day",False,True,
  "на столе лежит уведомление банка, дом уходит за твои долги, и тебе нечего на это ответить."),
 ("A7_SH12","LINDA","dawson_house_living","a woman moving through the map-choked living room with a cardboard box, taking down a single framed photo","MS","eye","static","day",False,False,
  "линда ходит по комнате с коробкой, и снимает со стен из-под твоих карт ваши старые фотографии."),
 ("A7_SH13","LINDA","dawson_kitchen","a woman pausing at the kitchen table, sliding a thin silver wedding band off her finger, looking at it","MCU","over","push_in","day",False,True,
  "у двери она снимает с пальца тонкое серебряное кольцо, то самое, на которое ты копил три месяца."),
 ("A7_SH14",None,"dawson_kitchen","extreme close on a thin silver wedding band set down gently on the empty corner of the yellow formica table","ECU","top","push_in","day",False,True,
  "и кладёт его на угол кухонного стола, ровно туда, где ты когда-то протянул ей коробочку, помнишь."),
 ("A7_SH15","CODY_TEEN","east_nash_street","a teenage boy loading a duffel into the back of a car at the curb, not looking back at the house","WS","eye","static","day",False,False,
  "коди молча грузит сумку в машину, и не оборачивается на дом, и не оборачивается на тебя."),
 ("A7_SH16","RAY","east_nash_street","a man standing alone on his porch watching a car pull away down the street, the brass ruler in one hand","MCU","low","static","day",False,False,
  "ты стоишь на крыльце с дедовой линейкой в руке, и смотришь, как машина увозит твою семью за угол."),
 ("A7_SH17","LINDA","east_nash_street","close on the woman in the passenger seat looking back once through the rear window, grief on her face","CU","eye","push_in","day",False,False,
  "линда оборачивается в окне всего один раз, и в её взгляде не злость, а такая усталая, тихая жалость."),
 ("A7_SH18",None,"east_nash_street","an empty residential street after a car has gone, a lone man small on a porch, long afternoon shadows","EWS","high","pull_out","day",True,True,
  "машина скрывается за поворотом, и улица пустеет, и ты остаёшься один на один со своей правдой."),
 ("A7_SH19","RAY","dawson_kitchen","a man entering the silent kitchen, stopping at the sight of the thin silver ring alone on the table","MS","eye","push_in","dusk",False,False,
  "ты возвращаешься на кухню, и видишь на углу стола её кольцо, и долго смотришь на него, не дыша."),
 ("A7_SH20","RAY","dawson_kitchen","close on the man's hand hovering over but not touching the thin silver ring on the formica","ECU","over","push_in","dusk",False,True,
  "ты не берёшь его в руки, ты просто смотришь, и впервые за годы в тебе шевелится что-то похожее на сомнение."),
 ("A7_SH21","RAY","dawson_house_living","a man sinking to the floor of the empty map-covered living room at dusk, surrounded by his charts","WS","high","static","dusk",False,False,
  "ты садишься на пол посреди своих карт, в пустом доме, и впервые слышишь, какая вокруг тишина."),
 ("A7_SH22","RAY","dawson_house_living","close on the man's hollow face lit by dusk, the giant map looming behind, doubt and certainty at war","CU","eye","push_in","dusk",False,False,
  "и на одну секунду тебе приходит мысль, а что, если они все правы, а один я ошибаюсь, всего на секунду."),
 ("A7_SH23",None,"dawson_house_living","extreme close on the giant wall map, a single pin marking a point far to the south at the bottom edge","ECU","eye","push_in","dusk",False,True,
  "но потом твой взгляд падает на карту, на одну точку далеко на юге, где по краю кольцом лежит лёд."),
 ("A7_SH24","RAY","dawson_house_living","a man rising from the floor with new fixed resolve, staring at the southern edge of the map, jaw set","MCU","low","push_in","dusk",False,False,
  "и сомнение гаснет, ты встаёшь, и говоришь пустому дому, хватит спорить, я просто пойду и увижу сам."),
 ("A7_SH25",None,"percy_priest_lake","the flat reservoir at last light, utterly empty, the long jetty dark against a level glowing horizon","EWS","eye","static","dusk",True,True,
  "за окном ровная линия воды лежит, как всегда, и зовёт тебя на юг, туда, где кончается мир."),
 ("A7_SH26",None,"dawson_kitchen","extreme close on the thin silver ring left alone on the table, dust beginning to settle on the formica around it","INSERT","top","static","night",False,True,
  "а кольцо так и остаётся лежать на столе, и ты оставляешь его там, потому что тебе пора в дорогу."),
]

seed_act("act05_cody",   PAL_CODY,  A5)
seed_act("act06_proofs", PAL_PROOF, A6)
seed_act("act07_breaks", PAL_BREAK, A7)
