# -*- coding: utf-8 -*-
"""surrogate A4 husband + A5 second. Run: PYTHONIOENCODING=utf-8 python scripts/_seed_surrogate_A4A5.py"""
from _surrogate_engine import seed_act

P_H="souring domestic palette, faded warm browns turning grey and cold, heavy dim light"
P_2="repeating clinical palette, cool clinic whites and washed grey, a weary sense of the same again"

H=[
 ("A4_SH01",None,"poor_flat","a wide view of a poor flat gone quiet and cold, dishes unwashed and curtains half drawn, heavy dim light","WS","eye","push_in","day",True,False,
  "после первых родов дом становится другим, тише и злее, и в нём поселяется что-то тяжёлое."),
 ("A4_SH02","MUZH_BASE","poor_flat","a medium shot of the buzz-cut husband slumped at a table in the poor flat, resentful and closed","MS","eye","static","day",False,False,
  "Толя не может тебе простить, что ты выносила и отдала чужого ребёнка за деньги."),
 ("A4_SH03","HERO_YOUNG","poor_flat","a close-up of the young woman absorbing his contempt, tired and hurt","CU","eye","static","day",False,False,
  "он говорит, что теперь не знает, кто ты, и что ему стыдно смотреть на соседей."),
 ("A4_SH04","MUZH_BASE","poor_flat","a medium close-up of the husband drinking alone in the evening, a cigarette behind his ear, an empty bottle nearby","MCU","eye","static","night",False,False,
  "он пьёт каждый вечер, и его сигарета за ухом да пустая бутылка на столе — вот и весь разговор."),
 ("A4_SH05",None,None,"an extreme close-up macro insert of empty bottles being gathered from a kitchen table, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "утром ты выносишь пустые бутылки, вечером они появляются снова, и так по кругу без конца."),
 ("A4_SH06","HERO_YOUNG","poor_flat","a medium shot of the young woman shielding her small son as the father shouts off-frame","MS","eye","static","day",False,False,
  "Миша, уже здоровый, жмётся к тебе, когда отец кричит, и ты закрываешь его собой."),
 ("A4_SH07","SON_CHILD","poor_flat","a close-up of the frightened fair-haired boy clutching his little red toy car with wide eyes","CU","high","static","day",False,False,
  "сын смотрит на вас большими глазами и сжимает свою красную машинку, как ты когда-то сжимала надежду."),
 ("A4_SH08",None,"small_town_street","a wide view of a grey small-town street where net curtains twitch, an atmosphere of gossip and judgement","WS","eye","pan_left","day",True,False,
  "в посёлке уже шепчутся, откуда у вас деньги, и слухи ползут быстрее, чем ты успеваешь их гасить."),
 ("A4_SH09","MUZH_BASE","poor_flat","a medium close-up of the husband packing a bag by the door, not meeting her eyes","MCU","over","static","day",False,False,
  "однажды Толя собирает сумку, говорит, что не может жить с женщиной, которая торгует животом."),
 ("A4_SH10","HERO_YOUNG","poor_flat","a close-up of the woman letting him go, quietly agreeing with him inside","CU","eye","push_in","day",False,False,
  "ты не удерживаешь его, потому что где-то в глубине согласна с каждым его словом."),
 ("A4_SH11",None,"small_town_street","a wide view of a lone man's blurred figure walking away down a grey street, not looking back","WS","eye","static","day",True,False,
  "он уходит по серой улице, не оборачиваясь, и ты остаёшься одна с сыном и с долгами."),
 ("A4_SH12",None,None,"an extreme close-up macro insert of a forgotten cigarette packet left on a bare shelf by an empty coat hook, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "на вешалке пусто, только его забытая пачка сигарет на полке напоминает, что здесь был муж."),
 ("A4_SH13","HERO_YOUNG","poor_flat","a medium shot of the woman of thirty standing alone with her son in the poor flat","MS","eye","static","day",False,False,
  "в тридцать ты одна с ребёнком, без мужа, без профессии, и деньги за первого малыша уже кончились."),
 ("A4_SH14","HERO_YOUNG","kitchen_night","a close-up of the woman's worn face doing sums at the night table","CU","eye","static","night",False,False,
  "операция съела половину, долги съели вторую, и ты снова там же, откуда начинала."),
 ("A4_SH15",None,"kitchen_night","a wide view of a dim poor kitchen at night, bills spread on the table under a low bulb, quiet and heavy","WS","eye","static","night",True,False,
  "ночами ты считаешь на кухне чужие счета и не понимаешь, как выбраться из этой ямы."),
 ("A4_SH16","HERO_YOUNG","poor_flat","a medium close-up of the woman looking at her growing son with worry","MCU","eye","static","day",False,False,
  "Миша растёт, ему нужны одежда, еда, школа, а у тебя нет ни работы, ни поддержки."),
 ("A4_SH17","SON_CHILD","poor_flat","a close-up of the boy quietly sharing a sweet with his mother, uncomplaining","CU","high","static","day",False,False,
  "он не жалуется, донашивает чужое и делится с тобой последней конфетой, и это больнее всего."),
 ("A4_SH18",None,None,"an extreme close-up macro insert of a growing stack of unpaid bills on a kitchen table, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "на столе растёт стопка неоплаченных счетов, и с каждым днём их становится всё больше."),
 ("A4_SH19","HERO_YOUNG","kitchen_night","a medium shot of the woman sitting in the dark kitchen, a hard idea returning to her","MS","eye","push_in","night",False,False,
  "и когда становится совсем нечем платить, ты снова думаешь о том единственном, что умеешь продавать."),
 ("A4_SH20","HERO_YOUNG","kitchen_night","a close-up of the woman of thirty resolving to call the agency again, ashamed and certain","CU","eye","push_in","night",False,True,
  "тебе тридцать, ты клялась, что это был один раз, и уже знаешь, что позвонишь Инне снова."),
]

SECOND=[
 ("A5_SH01",None,"coordinator_office","a wide view of the tidy agency office with a glass desk and stacked contracts, cool and familiar","WS","eye","push_in","day",True,False,
  "в тридцать два ты снова сидишь в том же чистом офисе, и Инна Сергеевна встречает тебя как родную."),
 ("A5_SH02","COORD_BASE","coordinator_office","a medium close-up of the coordinator leaning in warmly, a lanyard and tablet, offering a new deal","MCU","over","static","day",False,False,
  "она говорит, что для тебя как раз есть пара, отчаявшаяся, готовая заплатить ещё больше, чем в первый раз."),
 ("A5_SH03","HERO_MID","coordinator_office","a close-up of the woman of thirty-two telling herself this is the last time","CU","eye","static","day",False,False,
  "ты говоришь себе, что это в последний раз, что просто нужно закрыть долги и выучить сына."),
 ("A5_SH04",None,None,"an extreme close-up macro insert of a hand signing a contract with a steady pen, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "ты снова подписываешь договор, и на этот раз рука не дрожит совсем, и это пугает тебя больше всего."),
 ("A5_SH05","HERO_MID","clinic_room","a medium shot of the woman on a clinic couch again, the same procedure repeating under cold light","MS","eye","static","day",False,False,
  "в клинике всё повторяется, тот же перенос, те же слова про медицину и деньги, тот же холодный свет."),
 ("A5_SH06",None,"clinic_corridor","a wide view of a familiar hushed clinic corridor with empty chairs and closed doors, cool light","WS","eye","pan_right","day",True,False,
  "коридоры клиники ты теперь знаешь наизусть, будто это твоя вторая, стыдная работа."),
 ("A5_SH07","RICHW_BASE","clinic_corridor","a medium close-up of a younger anxious intended mother with a pale silk scarf, hungry with hope","MCU","eye","static","day",False,False,
  "новая заказчица моложе прежней, но смотрит на твой живот с той же голодной надеждой."),
 ("A5_SH08","HERO_MID","clinic_corridor","a close-up of the woman avoiding the intended mother's eyes, guarded","CU","eye","static","day",False,False,
  "ты стараешься не смотреть ей в глаза и не думать о том, что снова растишь в себе чужого."),
 ("A5_SH09",None,None,"an extreme close-up macro insert of a hand resting on a pregnant belly under a plain dress, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","eye","static","day",True,False,
  "второй чужой ребёнок толкается внутри, и ты снова, против воли, начинаешь его любить."),
 ("A5_SH10","HERO_MID","kitchen_night","a medium shot of the woman at the night kitchen table, a hand on her belly, whispering to it","MS","eye","static","night",False,False,
  "по ночам ты снова говоришь ему не привыкать, но сама привыкаешь с каждым днём сильнее."),
 ("A5_SH11",None,"small_town_street","a wide view of the unchanging grey small-town street under a flat sky","WS","eye","static","day",True,False,
  "посёлок за окном не меняется, только ты в нём становишься всё более чужой самой себе."),
 ("A5_SH12",None,None,"an extreme close-up macro insert of hands knitting a second tiny baby bootie by lamplight, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,False,
  "ты снова тайком вяжешь крошечную пинетку, вторую, для коробки, о которой не знает никто."),
 ("A5_SH13","HERO_MID","maternity_ward","a medium shot of the woman of thirty-three in labour again on a hospital bed, her body remembering","MS","eye","static","night",False,False,
  "в тридцать три ты рожаешь во второй раз, и всё тело помнит, что будет дальше."),
 ("A5_SH14","HERO_MID","maternity_ward","a close-up of the woman's face at the second first cry, hope flaring and dying","CU","eye","push_in","night",False,False,
  "ты снова слышишь первый крик и снова на секунду веришь, что этот ребёнок останется с тобой."),
 ("A5_SH15",None,None,"an extreme close-up macro insert of small scissors snipping a hospital ID bracelet off a wrist, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","night",True,True,
  "и снова медсестра срезает браслет с твоей руки, и снова уносят свёрток к другим родителям."),
 ("A5_SH16","HERO_MID","hospital_room","a medium shot of the woman alone in a bare recovery room, emptier than before","MS","eye","static","day",False,False,
  "палата, пустые руки, ненужное молоко, всё как в первый раз, только внутри тебя стало ещё пустее."),
 ("A5_SH17","RICHW_BASE","rich_home","a medium close-up of a second intended mother cradling a newborn in a bright wealthy home","MCU","eye","static","day",False,False,
  "где-то в чужом доме вторая заказчица баюкает ребёнка, которого ты носила девять месяцев."),
 ("A5_SH18",None,None,"an extreme close-up macro insert of a tin box now holding two hospital bracelets and two tiny booties, filling the frame in sharp focus, background out of focus, shallow depth of field","ECU","top","static","day",True,False,
  "в жестяной коробке теперь два браслета и две пинетки, от двоих, кого ты уже не увидишь."),
 ("A5_SH19","HERO_MID","kitchen_night","a close-up of the woman's exhausted face at the night table, debts cleared but joyless","CU","eye","static","night",False,False,
  "деньги закрывают долги, но радости нет, только усталость и ощущение, что ты продаёшь себя по частям."),
 ("A5_SH20",None,"kitchen_night","a wide view of a dim poor kitchen at night, quiet after the child is gone, one low pool of light","WS","eye","static","night",True,False,
  "Миша спит, счета оплачены, а ты сидишь в темноте и не чувствуешь ни облегчения, ни гордости."),
 ("A5_SH21","HERO_MID","poor_flat","a medium shot of the woman promising herself again that this was the last time","MS","eye","static","day",False,False,
  "ты обещаешь себе, что это точно был последний раз, и почти сама себе не веришь."),
 ("A5_SH22","HERO_MID","poor_flat","a close-up of the woman of thirty-three, two bracelets in a box, two children growing far away","CU","eye","push_in","day",False,True,
  "тебе тридцать три, у тебя в коробке два браслета, и где-то растут двое детей, которые не знают тебя."),
]

if __name__=="__main__":
    seed_act("husband", P_H, H, render_mode="static")
    seed_act("second",  P_2, SECOND, render_mode="static")
