-- Enrich «Газ» location descriptions (2026-05-31). Richer space/materials/era/light/wear
-- so the renderer has enough to not hallucinate. English SDXL prose, NO style tokens.
SET client_encoding='UTF8';
\set pid '6a200000-0000-4000-8000-000000000001'

UPDATE locations SET description=$d$interior of a small two-room Soviet-era apartment in a 1970s Riga panel block, low ceilings, worn pale-yellow wallpaper with a faded floral pattern peeling at the seams, scuffed grey-brown linoleum flooring, a cramped kitchen with a chipped white enamel sink, a four-ring gas stove, a humming little fridge, a folding sofa-bed with a checkered cover, a dark wooden wardrobe with a sticky door, a boxy old television on a stand, net curtains over a single window onto identical grey panel blocks across the yard, a painted radiator under the sill, a threadbare patterned rug, family photographs and a ticking wall clock. cramped, clean, modest, lit by one warm ceiling bulb. atmosphere of a tired working-class home where nobody has time.$d$ WHERE "projectId"=:'pid' AND slug='racer_apartment';

UPDATE locations SET description=$d$a tight driver's-eye view inside the cabin of an old 1990s German sedan at night, worn black leather seats cracked and split at the seams, a scuffed three-spoke steering wheel wrapped in fraying grip tape, a glowing amber-green analog instrument cluster with a large tachometer and speedometer, a stubby gear lever with a worn knob, cracked matte dashboard plastic, a slightly sagging fabric headliner, a small rear-view mirror with a dangling trinket, faint blue and amber dashboard light pooling on the dials and on hands, the windscreen framing wet dark road and smeared streaks of oncoming headlights, condensation creeping at the edges of the glass. claustrophobic, intimate, trembling with engine vibration. atmosphere of a low-lit cockpit at speed.$d$ WHERE "projectId"=:'pid' AND slug='bmw_interior';

UPDATE locations SET description=$d$a wide multi-lane cable-stayed road bridge over the broad Daugava river in Riga at night, a long empty asphalt deck with cracked painted lane markings and tar-sealed seams, a single tall white concrete pylon with fanned steel stay-cables sweeping overhead, low scuffed concrete crash barriers along both edges, metal expansion joints across the road, a receding row of orange sodium street lamps, black river water far below catching scattered reflections, the lit skyline and church spires of Old Riga on both banks, harbour cranes and warehouse silhouettes downstream, wet glossy tarmac mirroring the lamps, thin patches of slush and black ice at the kerbs, cold still January air with faint exhaust haze. vast, exposed, deserted. atmosphere of a high-speed night straightaway.$d$ WHERE "projectId"=:'pid' AND slug='southern_bridge';

UPDATE locations SET description=$d$interior of a cramped private concrete garage box in the Chiekurkalns district of Riga, a single car raised over a brick-lined inspection pit, bare breeze-block walls hung with spanners, worn tyres and coils of cable, a cluttered steel workbench strewn with engine parts, oil filters and greasy rags, dark oil stains soaked into the rough concrete floor, a portable work lamp on a long orange cable throwing hard raking shadows, a wheezing kerosene heater glowing in the corner, a car battery and a jack on the floor, a faded calendar and a shelf of dented cans and jars, the corrugated metal up-and-over door half raised onto a dark yard. low-ceilinged, greasy, close and warm. atmosphere of an amber oil-smelling night workshop.$d$ WHERE "projectId"=:'pid' AND slug='chiekurkalns_garages';

UPDATE locations SET description=$d$a wide signalised four-way road intersection in the Maskavas forstate, the old Russian-speaking district of Riga, worn cracked asphalt with faded lane paint and tram rails crossing diagonally, a slip-road merging from the right, sagging overhead trolley wires, low pre-war brick tenements and Soviet panel blocks with small shuttered shops at street level, traffic lights on rusting steel poles, a lonely bus shelter, bare winter lime trees, a row of orange sodium street lamps, wet black tarmac glossy with melt-water, ridges of dirty grey ploughed snow heaped along the kerbs, a few parked cars under a thin film of frost. quiet, faded, working-class. atmosphere of a near-empty arterial after midnight.$d$ WHERE "projectId"=:'pid' AND slug='maskavas_intersection';

UPDATE locations SET description=$d$a courtyard between weathered five-storey Khrushchev-era panel apartment blocks in the Bolderaja port district of Riga, pale grey and ochre rendered walls streaked with damp, rows of small balconies cluttered with junk, a steep cracked concrete ramp running down to a line of dented rusty metal garage boxes, tufts of grass forcing through broken asphalt, a beaten-carpet rail and a bent climbing frame, a few parked old Soviet cars, birch and poplar trees shedding white fluff in summer, sagging laundry lines strung between poles, the tops of harbour cranes and a water tower visible beyond the rooftops. ordinary, a little run-down, sleepy. atmosphere of a warm working-class summer afternoon.$d$ WHERE "projectId"=:'pid' AND slug='bolderaja_yard';

UPDATE locations SET description=$d$a derelict industrial yard on Kundzinsala island in Riga at night, vast cracked concrete slabs with weeds forcing through the joints, the looming brick hulk of an abandoned warehouse with smashed black windows and peeling paint, rusted chain-link fencing and a sagging steel gate, scattered oil drums, broken pallets and rubble, a single failing floodlight buzzing high on a pole, a loose semicircle of cars parked with their headlights aimed inward cutting cones through the cold haze, oily puddles reflecting the beams, harbour cranes and the black river beyond the fence. empty, echoing, hidden from the city. atmosphere of a secret after-midnight gathering ground.$d$ WHERE "projectId"=:'pid' AND slug='industrial_race_lot';

UPDATE locations SET description=$d$a small bare interview room in a Latvian state police station, institutional pale-green painted walls scuffed grey at chair height, a heavy steel table bolted to the floor, two mismatched chairs, a closed grey case folder and a plastic water cup on the table, a small barred window with frosted glass, a single buzzing fluorescent tube in a yellowed diffuser overhead, a worn speckled vinyl floor, a plain wall clock and a laminated notice taped to the wall, the faint smell of cold coffee and disinfectant. confined, hard-lit, impersonal. atmosphere of cold institutional fluorescent pressure.$d$ WHERE "projectId"=:'pid' AND slug='police_room';

UPDATE locations SET description=$d$a strict-regime prison near Jelgava in Latvia, tall raw grey concrete perimeter walls topped with coils of rusting razor wire, a steel watchtower with a swivelling floodlight, a long two-storey grey barracks block with rows of small barred windows, cracked tarmac in the exercise yard with faded painted lines, a heavy sliding chain-link and steel gate on rollers, security lamps on tall poles, bare packed earth and one leafless tree, a low leaden overcast sky. bleak, hard-edged, enclosed. atmosphere of grey institutional confinement.$d$ WHERE "projectId"=:'pid' AND slug='jelgava_prison';

UPDATE locations SET description=$d$the A10 Riga to Jurmala dual carriageway at night, a long straight ribbon of asphalt flanked on both sides by dense dark pine and birch forest, reflective white lane markings and steel crash barriers, an occasional overhead green sign gantry, sodium lamps clustered only near the junctions and otherwise near-total darkness, the road surface wet and gleaming, faint mist hanging low between the tree trunks, the sparse red tail-lights and white headlights of distant traffic, hoar-frost at the grassy verges. fast, lonely, hemmed in by forest. atmosphere of an empty forest motorway at night.$d$ WHERE "projectId"=:'pid' AND slug='jurmala_highway';

UPDATE locations SET description=$d$a modest Latvian courtroom, pale honey-coloured wood wall panelling and matching benches in rows, a raised judge's bench with the Latvian state coat of arms mounted above it, a railed wooden defendant's dock to one side, tall windows with half-closed slatted blinds letting in flat grey daylight, a worn carpet runner down the aisle, a clerk's table with stacked papers and a microphone, recessed fluorescent ceiling panels, a plain round clock. quiet, formal, sparsely filled. atmosphere of solemn daylight gravity.$d$ WHERE "projectId"=:'pid' AND slug='courtroom';

UPDATE locations SET description=$d$a wide empty approach road near Riga international airport at night, fresh smooth dark asphalt with crisp white markings, low blue and white runway and taxiway lights blinking in sequence across flat open fields beyond a chain-link perimeter fence, sparse tall lamp posts casting isolated pools of light, a distant lit control tower and the faint glow of a terminal, a windsock on a pole, no other traffic, a cold flat horizon under a dark sky. open, deserted, faintly humming with distant jets. atmosphere of an out-of-town night straightaway.$d$ WHERE "projectId"=:'pid' AND slug='lidostas_road';

UPDATE locations SET description=$d$interior of a cosy renovated flat in a pre-war Riga apartment building, warm honey parquet flooring, tall old double-glazed windows with deep sills crowded with potted plants, white-painted cast-iron radiators, full bookshelves and stacked poetry volumes, a small kitchen nook with a kettle and patterned ceramic mugs, a soft worn sofa under a knitted throw, framed prints and a strand of warm fairy lights, a paper lampshade casting a soft glow, a woven rug, the lingering warmth of brewed tea. lived-in, bookish, gentle. atmosphere of a warm homely evening.$d$ WHERE "projectId"=:'pid' AND slug='liga_apartment';

UPDATE locations SET description=$d$interior of a small independent bookshop on Terbatas street in central Riga, tall dark-wood shelves packed tight with worn book spines, a hand-lettered poetry section sign, a narrow aisle with a wheeled wooden step-stool, a little coffee corner with a chrome espresso machine and two stools, a worn parquet floor, warm low pendant lamps, a tall street-facing window with gold-leaf lettering letting in soft afternoon light, a counter stacked with new releases beside a small brass till. snug, hushed, smelling of paper and coffee. atmosphere of a warm paper-and-coffee refuge.$d$ WHERE "projectId"=:'pid' AND slug='bookshop_terbatas';

UPDATE locations SET description=$d$a quiet old Riga cemetery under a low overcast sky, rows of modest dark granite and weathered limestone headstones, wrought-iron plot railings furred with rust, narrow gravel paths between mossy stone kerbs, tall bare lindens and a few black firs, drifts of wet fallen leaves, simple metal crosses and faded plastic flowers in jars, a distant red-brick chapel with a small green spire, soft flat grey light, no wind. still, damp, solemn. atmosphere of grey mourning.$d$ WHERE "projectId"=:'pid' AND slug='cemetery_riga';

UPDATE locations SET description=$d$the Riga freeport waterfront on the Daugava, long rows of stacked rusty shipping containers in faded reds, blues and greens, towering gantry cranes on rails, an oily stained concrete quay with thick steel bollards and coiled mooring ropes, the dark riveted hull of a moored cargo ship alongside, puddles slicked with a diesel rainbow sheen, a low corrugated-steel warehouse, forklifts and stacked pallets, the wide flat grey estuary meeting an overcast Baltic sky, wheeling gulls, a cold damp wind. heavy, industrial, vast. atmosphere of a cold working harbour morning.$d$ WHERE "projectId"=:'pid' AND slug='riga_port';

UPDATE locations SET description=$d$interior of a small tyre-fitting workshop on the grey outskirts of Riga, a tyre-changing machine and a wheel-balancer bolted to a stained concrete floor, leaning stacks of worn used tyres against breeze-block walls, a roller shutter half-raised onto a bleak grey yard, a grimy workbench with pneumatic tools on coiled red air-lines, a wall calendar and a curling price list, a kettle and a chipped mug on a stool, a single cold fluorescent strip flickering, the smell of rubber and grease. plain, cramped, low-paid. atmosphere of a tired grey working day.$d$ WHERE "projectId"=:'pid' AND slug='tire_shop';

UPDATE locations SET description=$d$the riverside embankment promenade along the broad Daugava in central Riga at golden summer sunset, a low weathered stone parapet, wide grey paving slabs, cast-iron lamp posts and benches, leafy linden trees, neat flowerbeds, the calm wide river glowing copper, the lit silhouette of Old Riga with church spires and the cable-stayed bridge on the far bank, a few strollers and cyclists, gulls drifting low, warm raking golden light and long shadows. open, peaceful, unhurried. atmosphere of a warm summer evening.$d$ WHERE "projectId"=:'pid' AND slug='daugava_embankment';

UPDATE locations SET description=$d$the wide flat white-sand beach at Jurmala on the Gulf of Riga, fine pale sand rippled by the wind, a shallow calm grey-blue sea with gentle foam at the tideline, low grassy dunes backed by tall pines, weathered wooden beach huts and a lifeguard chair in the distance, scattered shells and bleached driftwood, a soft hazy overcast summer sky, a few distant figures walking the waterline. broad, breezy, serene. atmosphere of a calm seaside afternoon.$d$ WHERE "projectId"=:'pid' AND slug='jurmala_beach';

UPDATE locations SET description=$d$the Gauja river valley near Sigulda in Latvia, steep red-sandstone cliffs streaked iron-orange and overhung with tree roots, dense green forest filling the gorge, a winding river glinting far below, the grey stone ruins of a medieval castle on a wooded ridge, a wooden viewing platform with a timber railing, a gravel footpath, drifting cloud shadow over the canopy, bright clear summer daylight. high, green, expansive. atmosphere of a vast peaceful nature outlook.$d$ WHERE "projectId"=:'pid' AND slug='sigulda_gauja';

UPDATE locations SET description=$d$interior of a small modest neighbourhood pharmacy on Maskavas street in Riga, a white melamine counter with a scratched glass divider and a worn card reader, tall shelves of boxed medicines in muted greens and whites behind, a glowing green cross sign, a glass-fronted refrigerator of vials, scuffed grey linoleum, a chrome queue rail and two plastic chairs, a buzzing fluorescent ceiling, faded promotional posters taped to the glass, a small barred window onto the grey street. clinical, tired, fluorescent. atmosphere of a weary mid-afternoon.$d$ WHERE "projectId"=:'pid' AND slug='pharmacy_maskavas';

SELECT slug||' -> '||length(description)||' chars' FROM locations WHERE "projectId"=:'pid' ORDER BY length(description);
