# -*- coding: utf-8 -*-
"""Seed CH10 — Ремесло и гордость (action-first). Idempotent."""
from _seed_tiler_act_engine import seed_act

MOOD = "cold marble glare with a quiet flicker of craftsman pride, gilded edges"

SHOTS = [
    ("CH10_SH01", "BAKHTI", "marble",
     "the master laying an intricate geometric star pattern into a marble floor, piece by piece, absorbed",
     "MS", "eye", "static", "object_day", False, False,
     "но руки своё помнили, а руки не врут."),
    ("CH10_SH02", "BAKHTI", "marble",
     "extreme close-up of fingers fitting a cut marble wedge precisely into a radiating star inlay",
     "ECU", "top_down", "static", "object_day", False, False,
     "я собирал звезду из камня, как складывают молитву."),
    ("CH10_SH03", None, "marble",
     "wide symmetrical shot of a perfect marble hall with a single tiny kneeling figure off-centre on the vast floor",
     "WS", "high", "push_in", "object_day", False, True,
     "зал выходил такой, что самому делалось не по себе."),
    ("CH10_SH04", None, "marble",
     "medium shot of a couple of Russian site workers stopping to stare silently at the finished inlaid floor, faces in shadow",
     "MS", "eye", "static", "object_day", True, False,
     "местные замолкали, когда видели мой узор."),
    ("CH10_SH05", "BAKHTI", "marble",
     "extreme close-up of the master's finger tracing a Samarkand star into a film of marble dust on the floor",
     "ECU", "top_down", "static", "object_day", False, True,
     "иногда я чертил на пыли самаркандскую звезду, для себя."),
    ("CH10_SH06", "BAKHTI", "marble",
     "extreme close-up of the master's palm quickly wiping the dust-drawn star away",
     "ECU", "top_down", "static", "object_day", False, False,
     "и стирал, пока не увидел гена, не положено."),
    ("CH10_SH07", "BAKHTI", "marble",
     "medium close-up of the master standing back, hands on hips, quietly proud of the finished floor",
     "MCU", "eye", "static", "object_day", False, False,
     "единственное, что у меня было, что я делаю это лучше всех."),
    ("CH10_SH08", "BAKHTI", "marble",
     "close-up of the master's face reflected in the mirror-polished marble he just laid",
     "CU", "high", "static", "object_day", False, False,
     "своё лицо я видел в их полу, как в воде."),
    ("CH10_SH09", None, "marble",
     "close-up of chandelier crystals scattering refracted light across a marble wall, no people",
     "CU", "low", "static", "object_day", True, False, ""),
    ("CH10_SH10", None, "marble",
     "wide shot of the gilded marble hall taking finished shape, columns and inlaid floor gleaming, no people",
     "WS", "eye", "push_in", "object_day", True, False,
     "зал за залом я одевал в камень, чужую сказку."),
    ("CH10_SH11", "BAKHTI", "marble",
     "the master buffing a marble seam smooth with a cloth, careful and slow",
     "MS", "eye", "static", "object_day", False, False,
     "каждый шов выглаживал до зеркала."),
    ("CH10_SH12", "BAKHTI", "marble",
     "extreme close-up of a knife blade failing to slide into a flawless tight marble seam",
     "ECU", "top_down", "static", "object_day", False, True,
     "между плит не входило лезвие, вот моя подпись была."),
    ("CH10_SH13", "BAKHTI", "aqua",
     "the master on his knees laying glossy black and gold tiles around the rim of the sunken aquadisco pool, a mirrored ceiling above",
     "MS", "high", "static", "object_day", False, True,
     "и бассейны мы выкладывали, плитку к плитке, мы, узбеки, а они потом в них дискотеку устроили, ту самую аквадискотеку, прости господи."),
    ("CH10_SH14", "BAKHTI", "aqua",
     "extreme close-up of a black and gold tile pressed into the aquadisco pool rim, coloured disco light reflected in the wet glaze",
     "ECU", "eye", "static", "object_day", False, False,
     "зеркальный потолок, цветомузыка, дискотека прямо в воде, в бассейне, что я выложил вот этими руками, для одного человека."),
]

if __name__ == "__main__":
    seed_act(10, "object_marble_cold", MOOD, "static", "CH10 Craft", SHOTS)
