# -*- coding: utf-8 -*-
"""preretire atmosphere breathers: 2 per act (A1..A11), id_region='a', unique per-act schemes."""
from _preretire_engine import seed_act

PALS = {
 "A1": "warm plant daylight, bread and steel tones, soft flour dust",
 "A2": "cool digital white, tablet-screen accents, flat even light",
 "A3": "grey office light, cold window glare, drained institutional tones",
 "A4": "clear autumn light, gold leaf accents, long confident shadows",
 "A5": "washed grey daylight, screen-glow accents, tired urban tones",
 "A6": "flat fluorescent class light, plastic chair tones, grey window day",
 "A7": "cold november light, bare branch shadows, thin low sun",
 "A8": "dim lamp evening, deep blue windows, warm booth glow",
 "A9": "deep winter blue, sparse lamplight, breath-fog cold",
 "A10": "warm bakery glow, flour gold, soft oven light",
 "A11": "bright winter light, crisp snow tones, warm interior amber",
}

ATMO = {
 "A1": [
  ("A1_SZ01", None, "plant_floor",
   "loaves riding the cooling conveyor in even ranks, steam rising into a ceiling extractor, warm light along the line",
   "WS", "high", "pan_right", "day", True, False,
   "хлеб идёт по остывочному конвейеру ровными рядами — восемь тысяч буханок за смену.",
   "steam climbs off the riding loaves into the slow pull of the extractor"),
  ("A1_SZ02", None, "flat_kitchen",
   "the windowsill radio glowing its dial at dusk, net curtains breathing, a watered plant beside it",
   "ECU", "eye", "static", "evening", True, False,
   "радио на подоконнике играет с шести утра до полуночи — так в доме звучит второй голос.",
   "the dial glow steadies as the net curtain breathes with the window draught"),
 ],
 "A2": [
  ("A2_SZ01", None, "plant_floor",
   "a row of new sensor pucks blinking on old machine casings down the line, QR labels in a neat rank",
   "ECU", "low", "track", "day", True, False,
   "датчики мигают по цеху зелёной строчкой — новая азбука, которой машины пока не выучили.",
   "the sensor lights blink down the line in an uneven green morse"),
  ("A2_SZ02", None, "plant_gate",
   "the honour board being re-glazed, half the portraits laid out on a bench, sky reflected in the fresh glass",
   "WS", "eye", "static", "day", True, False,
   "доску почёта стеклят заново — портретов на бенче меньше, чем гнёзд на фетре.",
   "sky glides across the fresh glass over the half-empty felt"),
 ],
 "A3": [
  ("A3_SZ01", None, "plant_locker",
   "the locker-room bench with one folded navy work jacket left on it, a rag beside, lockers standing open",
   "INSERT", "eye", "push_in", "day", True, False,
   "спецовку ты складываешь на скамью по-армейски — рукав к рукаву, швом наружу.",
   "the folded jacket holds its square as the locker doors sway open"),
  ("A3_SZ02", None, "street_plant",
   "the plant horn sounding over evening rooftops, birds lifting off the fence line, the sky brass-coloured",
   "EWS", "low", "static", "evening", True, False,
   "заводской гудок в шесть теперь звучит для тебя из-за забора — по ту сторону расписания.",
   "birds lift off the fence line in a slow wave under the brass sky"),
 ],
 "A4": [
  ("A4_SZ01", None, "courtyard",
   "a paper city map on a kitchen table corner with pencil crosses over factory districts, reading glasses on it",
   "INSERT", "top", "static", "evening", True, False,
   "крестики на карте стоят кустами вокруг промзон — география надежды, октябрь.",
   "lamplight pools on the pencilled crosses under the resting glasses"),
  ("A4_SZ02", None, "street_plant",
   "golden poplar leaves piling against the plant fence, a sweeper's wide broom leaned on the fence unattended",
   "WS", "eye", "static", "day", True, False,
   "листья у забора метут раз в день, и к вечеру их снова по колено — октябрь работает быстрее людей.",
   "single leaves plane down onto the pile beside the leaning broom"),
 ],
 "A5": [
  ("A5_SZ01", None, "job_center",
   "the employment-centre hall after closing, joined chairs in rows, the ticket terminal glowing alone",
   "WS", "eye", "push_in", "evening", True, False,
   "после закрытия в зале остаются стулья и терминал — очередь разошлась, очередь придёт.",
   "the terminal screen glows over the empty joined chairs"),
  ("A5_SZ02", None, "flat_kitchen",
   "the gifted smartphone charging on the windowsill by the radio, both screens dark, frost on the glass",
   "ECU", "eye", "static", "night", True, False,
   "телефон заряжается рядом с радио — два поколения техники спят на одном подоконнике.",
   "the charge light pulses beside the dark radio dial under the frosted glass"),
 ],
 "A6": [
  ("A6_SZ01", None, "courses_class",
   "school desks with grown men's reading glasses and thermoses on them, the projector beam full of dust",
   "MS", "eye", "static", "day", True, False,
   "на партах очки и термосы — класс, где у всех за спиной по цеху, а впереди по анкете.",
   "dust drifts through the projector beam over the quiet grown desks"),
  ("A6_SZ02", None, "guard_booth",
   "the parking barrier in falling snow at night, its striped arm collecting a white ridge",
   "ECU", "low", "static", "night", True, False,
   "на стреле шлагбаума за ночь вырастает снежный гребень — единственный, кому тут спокойно.",
   "snow builds its slow ridge along the striped barrier arm"),
 ],
 "A7": [
  ("A7_SZ01", None, "flat_kitchen",
   "the pill organiser and the blood-pressure cuff sharing the windowsill with the radio, morning grey outside",
   "INSERT", "eye", "static", "morning", True, False,
   "подоконник теперь делят радио, таблетница и манжета — коммуналка возраста.",
   "grey light creeps along the shared sill past the coiled cuff"),
  ("A7_SZ02", None, "street_plant",
   "bare november branches over the plant fence, one glove frozen onto a fence spike, low thin sun",
   "WS", "low", "pan_left", "day", True, False,
   "ноябрь оставляет на заборе чью-то примёрзшую перчатку — город теряет тепло по мелочи.",
   "the frozen glove holds its wave as bare branches tick in the wind"),
 ],
 "A8": [
  ("A8_SZ01", None, "flat_room",
   "the certificate wall in lamplight with one empty hook where a frame was taken down for reading",
   "ECU", "eye", "static", "night", True, False,
   "на стене грамот появляется пустой крючок — одну ты так и держишь на столе, перечитываешь.",
   "lamplight holds the empty hook in the level row of frames"),
  ("A8_SZ02", None, "bus_stop_w",
   "the last evening bus pulling away from the winter stop, red lights smearing in the snow air",
   "WS", "eye", "static", "night", True, False,
   "последний автобус уходит в одиннадцать, и остановка остаётся сторожить проспект одна.",
   "the red tail lights smear into the snow air as the bus pulls off"),
 ],
 "A9": [
  ("A9_SZ01", None, "courtyard",
   "the snowy courtyard noticeboard with handwritten ads, several phone tabs torn off the machine-repair one, footprints below it",
   "WS", "eye", "push_in", "day", True, False,
   "на твоём объявлении оторвано уже пять язычков — сарафанное радио запускается медленно, но честно.",
   "the torn fringe of the ad flutters as snow dusts the board"),
  ("A9_SZ02", None, "flat_kitchen",
   "the school notebook of prices open beside the tea glass, entries growing denser down the page",
   "ECU", "high", "static", "night", True, False,
   "тетрадка расценок заполняется вниз всё плотнее — у ремесла пошёл оборот.",
   "lamplight crosses the densening entries as the tea glass steams"),
 ],
 "A10": [
  ("A10_SZ01", None, "bakery",
   "racks of fresh loaves cooling by the bakery window at dawn, steam fogging the glass from inside",
   "WS", "eye", "static", "morning", True, False,
   "к шести утра пекарня запотевает изнутри — хлеб дышит на стекло, как школьник на мороз.",
   "steam blooms up the window glass over the cooling racks"),
  ("A10_SZ02", None, "bakery",
   "a flour handprint on the dark housing of the dough mixer, five clear fingers, warm lamp above",
   "ECU", "eye", "static", "day", True, False,
   "на кожухе тестомеса остаётся мучной отпечаток ладони — подпись мастера, смывается, ставится снова.",
   "flour dust drifts down past the five-fingered print on the dark steel"),
 ],
 "A11": [
  ("A11_SZ01", None, "street_plant",
   "the industrial street in bright winter sun, the bread kiosk queue steaming, the old plant fence running beyond",
   "EWS", "high", "static", "day", True, False,
   "город живёт, как жил, — завод за забором, киоск с хлебом, очередь с паром изо ртов.",
   "the queue's breath fog drifts over the kiosk as sun hardens the snow"),
  ("A11_SZ02", None, "flat_room",
   "the certificate wall with a new small frame added at the row's end: a photo of a bakery crew",
   "INSERT", "eye", "pull_out", "day", True, False,
   "в конце ряда грамот появляется новая рамка — фотография смены маленькой пекарни.",
   "daylight settles along the row to the new small frame at its end"),
 ],
}

if __name__ == "__main__":
    for act, shots in ATMO.items():
        seed_act(act, PALS[act], shots, id_region="a")
