# -*- coding: utf-8 -*-
"""hidden_layoff shots: A3 (firing + first lie), A4 (the ritual), A5 (rejections)."""
from _hidden_layoff_engine import seed_act

PAL_A3 = "hard white light, deep window shadow, cold grey-green"
PAL_A4 = "soft april daylight, pale green buds, cool grey paths"
PAL_A5 = "bright hazy summer light, washed-out warm grey, glare on asphalt"

A3 = [
 ("A3_SH01", "VADIM_BASE", "meeting_room",
  "Vadim sits at the oval table with a thin folder squared in front of him, one open palm indicating the chair opposite, his face smooth and neutral",
  "WS", "eye", "static", "day", False, False,
  "вадим показывает ладонью на стул напротив и придвигает к тебе тонкую папку раньше, чем ты садишься.",
  "the young director slides the thin folder forward across the table with two fingers"),
 ("A3_SH02", "MARK_MAIN", "meeting_room",
  "Mark sits upright across the table, hands flat and still on his thighs, listening with the face of a man taking a delivery report",
  "MCU", "eye", "static", "day", False, False,
  "слова простые — должность выводится из штата, снабжение переходит подрядчику с первого апреля.",
  "the man sits perfectly still and only his throat moves once as he swallows"),
 ("A3_SH03", None, "meeting_room",
  "a two-page agreement lying square on the white table, a heavy pen resting across the signature line, a water glass beside it",
  "ECU", "top", "static", "day", False, False,
  "по соглашению сторон тебе предлагают три оклада — триста пятьдесят четыре тысячи рублей.",
  "the ceiling light glints along the pen barrel lying still across the signature line"),
 ("A3_SH04", ("VADIM_BASE", "MARK_MAIN"), "meeting_room",
  "past Vadim's dark shoulder, Mark asks something with one hand slightly raised, his brows drawn, the glass wall bright behind him",
  "OTS", "over", "static", "day", False, False,
  "ты спрашиваешь про линию, и вадим отвечает, что линия — больше не твоя забота.",
  "the man's raised hand lowers slowly to the table as the answer lands"),
 ("A3_SH05", "MARK_MAIN", "meeting_room",
  "Mark's face very close, the moment of understanding settling in, his eyes steady on the papers below the frame",
  "CU", "eye", "push_in", "day", False, True,
  "девятнадцать лет заканчиваются за четыре с половиной минуты вежливого разговора.",
  "his gaze drops from the middle distance to the papers and his lips press to a line"),
 ("A3_SH06", "MARK_MAIN", None,
  "his own hand in frame signing the agreement with an even steady stroke, the pen firm, the cuff of his grey suit crisp",
  "POV", "pov", "static", "day", False, False,
  "твоя рука ставит подпись ровно, будто подписывает очередной договор поставки.",
  "the pen draws one even signature and lifts cleanly off the paper"),
 ("A3_SH07", None, None,
  "a grey-green work record booklet lying on the white meeting table, a folded agreement sheet tucked under its cover, one corner creased soft",
  "INSERT", "eye", "static", "day", False, False,
  "кадровик кладёт сверху трудовую книжку, где через всю страницу одна запись длиной в жизнь.",
  "the booklet cover settles flat and the folded sheet under it eases open a degree",
  "RECORD"),
 ("A3_SH08", ("MARK_MAIN", "NINA_BASE"), "office_openspace",
  "Mark packs a small cardboard box on his cleared desk, a mug and a worn notebook going in, Nina standing a step away with her hands clasped",
  "WS", "eye", "static", "day", False, False,
  "картонная коробка со стола собирается быстро — кружка, зарядка и записная книжка на нужной букве.",
  "the mug and the notebook go into the box one after another under his measured hands"),
 ("A3_SH09", "NINA_BASE", "office_openspace",
  "Nina's face fighting for the right words, her fingers twisting the headset cord at her neck, the office soft behind her",
  "MCU", "eye", "static", "day", False, False,
  "нина хочет что-то сказать, но говорит только «позвоните, если что», и это звучит как прощание.",
  "her fingers twist the headset cord and her mouth opens and closes on the unsaid words"),
 ("A3_SH10", "MARK_MAIN", "office_lobby",
  "Mark presses his pass card to the turnstile reader, a small red light on the reader, the box balanced on his other arm",
  "MS", "eye", "static", "day", False, True,
  "на выходе пропуск вспыхивает красным — карту погасили, пока ты спускался со второго этажа.",
  "the red light blinks twice under the pressed card and the turnstile arm stays rigid"),
 ("A3_SH11", "MARK_MAIN", "factory_yard",
  "Mark small in the frame walking out through the factory gates with the cardboard box in both arms, the afternoon sky wide and pale over him",
  "EWS", "high", "static", "day", False, False,
  "ты выходишь за ворота с коробкой в руках в шестнадцать десять, и на улице ещё совсем светло.",
  "the man carries the box away from the gates at a slow even pace, his shadow long on the asphalt"),
 ("A3_SH12", None, None,
  "the worn brown briefcase standing upright on a bus seat beside a cardboard box, the brass locks catching the low sun",
  "ECU", "eye", "static", "day", False, False,
  "портфель едет домой на соседнем сиденье, и ты дважды перекладываешь его с места на место.",
  "low sunlight slides across the brass locks as the seat vibrates gently under the moving bus",
  "BRIEFCASE"),
 ("A3_SH13", ("LENA_BASE", "MARK_MAIN"), "flat_kitchen",
  "Lena stirs a pot at the stove telling something over her shoulder while Mark sits at the table with his hands folded around an untouched cup",
  "MS", "eye", "static", "evening", False, False,
  "дома лена рассказывает про очередь в регистратуре, и ты киваешь в нужных местах.",
  "she stirs the pot and glances over her shoulder while his thumb strokes the cup handle"),
 ("A3_SH14", "MARK_MAIN", "flat_kitchen",
  "Mark's face across the kitchen table, mouth just opening to speak and closing again, lamplight warm on half of him",
  "CU", "eye", "push_in", "evening", False, True,
  "ты открываешь рот, чтобы сказать про сокращение, и говоришь — «всё нормально, обычный день».",
  "his mouth opens on the first word, closes again, and he covers it with a sip from the cup"),
 ("A3_SH15", ("MARK_MAIN", "LENA_BASE"), "flat_kitchen",
  "the kitchen from the doorway, Mark and Lena at supper under the fabric-shaded lamp, an ordinary quiet evening in every detail",
  "WS", "eye", "static", "evening", False, False,
  "ужин проходит как тысячи ужинов до него, только ты второй раз солишь уже посоленный суп.",
  "his hand tips the salt over the plate a second time while she reaches for the bread"),
 ("A3_SH16", "LENA_BASE", "flat_kitchen",
  "Lena's open unworried face in lamplight as she talks, a teaspoon turning slowly in her cup",
  "MCU", "eye", "static", "evening", False, False,
  "лена ничего не замечает, потому что девятнадцать лет ты приходил домой с одним и тем же лицом.",
  "the teaspoon turns slowly in her cup as she talks on, her eyes soft and unguarded"),
 ("A3_SH17", "MARK_MAIN", "flat_bedroom",
  "Mark lies awake on his back in the dark bedroom, eyes open at the ceiling, one forearm across his forehead, Lena a sleeping shape beside him",
  "MS", "high", "static", "night", False, False,
  "ночью ты решаешь просто — найдёшь новое место за месяц, тогда и расскажешь, зачем её пугать.",
  "his chest rises and falls slowly and his fingers curl closed above his forehead"),
 ("A3_SH18", None, "flat_bedroom",
  "an alarm clock on a bedside table set to six forty, its digits glowing in the dark room",
  "ECU", "eye", "static", "night", False, False,
  "будильник остаётся на прежнем времени, потому что завтра ты «идёшь на работу».",
  "the clock digits glow steadily in the dark while the curtain edge breathes with a draught"),
]

A4 = [
 ("A4_SH01", ("LENA_BASE", "MARK_MAIN"), "flat_hall",
  "Lena tucks the lilac-lidded lunch container into Mark's open briefcase held on the shoe bench, he holds the flap up for her with one hand",
  "MCU", "eye", "static", "morning", False, False,
  "в понедельник утром лена кладёт в портфель контейнер с обедом, как клала всегда.",
  "her hands settle the container into the briefcase and his hand lowers the flap over it",
  "LUNCHBOX"),
 ("A4_SH02", None, None,
  "the two brass locks of the brown briefcase snapping shut in the dim hallway light, seen close from a low angle, a coat hem hanging above",
  "ECU", "low", "static", "morning", False, True,
  "клац-клац — замки щёлкают так же уверенно, как в любое настоящее утро.",
  "the two brass locks snap down in turn and the briefcase sways once on its handle",
  "BRIEFCASE"),
 ("A4_SH03", "MARK_MAIN", "bus_stop",
  "Mark in his grey suit stands at the bus shelter among three blurred commuters, the briefcase in one hand, his eyes ahead down the avenue",
  "WS", "eye", "static", "morning", False, False,
  "ты выходишь в семь двадцать и едешь в сторону фабрики, как ездил девятнадцать лет.",
  "the man shifts the briefcase from one hand to the other while traffic passes beyond the shelter",
  None, "crowd"),
 ("A4_SH04", "MARK_MAIN", None,
  "his own hand in frame gripping a bus handrail, the window beyond showing a park gate approaching, his reflection faint in the glass",
  "POV", "pov", "static", "morning", False, False,
  "только теперь ты выходишь на две остановки раньше — у старого парка с прудом.",
  "the park gate slides closer in the bus window and the hand tightens on the rail"),
 ("A4_SH05", "MARK_MAIN", "park_pond",
  "a tiny figure of a man in a grey suit sitting down on a green bench by the still pond, gravel paths empty around him, april trees bare",
  "EWS", "high", "static", "morning", False, True,
  "в восемь ноль пять ты садишься на зелёную лавку у пруда, и рабочий день начинается.",
  "the small figure settles onto the bench and sets the briefcase down flat across his knees"),
 ("A4_SH06", "MARK_MAIN", "park_pond",
  "Mark on the bench arranging his workplace, phone set to his left, notebook squared to his right, back straight as at a desk",
  "MS", "eye", "static", "morning", False, False,
  "ты раскладываешься, как в офисе — телефон слева, блокнот справа, спина прямая.",
  "his hands square the notebook and the phone into their places on the bench slats",
  "BRIEFCASE"),
 ("A4_SH07", "MARK_MAIN", None,
  "his own thumbs in frame typing on a phone over a job-site list of vacancies, the bench slats and one polished shoe blurred below",
  "POV", "pov", "static", "day", False, False,
  "до обеда ты отправляешь резюме одиннадцати компаниям и ставишь себе план, как ставил его отделу.",
  "the thumbs type steadily and the vacancy list scrolls up screen by screen"),
 ("A4_SH08", None, None,
  "the lunch box open on a painted bench slat, the lid propped against its side, the fork freed from its elastic band laid across the rim",
  "ECU", "eye", "static", "day", False, False,
  "ровно в тринадцать ноль-ноль ты обедаешь из контейнера, потому что расписание держит человека.",
  "faint steam rises off the open container and the elastic band dangles from the lid",
  "LUNCHBOX"),
 ("A4_SH09", None, "park_pond",
  "the april pond with two ducks drawing long ripples, empty painted benches along the gravel path, thin green buds on the lindens",
  "WS", "eye", "pan_right", "day", True, False,
  "парк в апреле пахнет мокрой корой, и кроме тебя в костюме здесь только утки.",
  "two ducks draw slow crossing ripples over the still water of the pond"),
 ("A4_SH10", "MARK_MAIN", "park_pond",
  "Mark checks his wristwatch and closes the notebook with one hand, the settled face of a man ending a shift",
  "CU", "eye", "static", "evening", False, False,
  "в семнадцать тридцать ты закрываешь блокнот — рабочий день закончен, пора домой.",
  "his wrist turns up to check the watch and the notebook cover falls shut under his palm"),
 ("A4_SH11", ("LENA_BASE", "MARK_MAIN"), "flat_hall",
  "Lena takes Mark's coat at the door asking something light, he answers over the coat rack with a practiced easy face",
  "MS", "eye", "static", "evening", False, False,
  "в прихожей лена спрашивает «как на работе», и ты отвечаешь — «обычный дурдом».",
  "she lifts the coat onto the rack while he talks, his hand smoothing his hair back once"),
 ("A4_SH12", ("LENA_BASE", "MARK_MAIN"), "flat_kitchen",
  "past Lena's shoulder, Mark eats supper telling a small story with his fork raised, easy and convincing, lamplight warm on the table",
  "OTS", "over", "static", "evening", False, False,
  "ложь оказывается лёгкой, потому что она сделана из чистой правды прошлых лет.",
  "his raised fork sketches a small circle in the air as he talks on easily"),
 ("A4_SH13", None, None,
  "a white postal envelope in an open desk drawer among receipts, a pencil column of numbers on its face topped by two hundred eighty thousand",
  "INSERT", "top", "static", "night", False, False,
  "в ящике стола лежит конверт с накоплениями — двести восемьдесят тысяч, подписанные карандашом.",
  "lamplight shifts across the pencil numbers as the drawer eases a centimetre wider",
  "ENVELOPE"),
 ("A4_SH14", "MARK_MAIN", None,
  "his own hand in frame holding a phone over a banking screen, a transfer of seventy four thousand set up, the send button under his thumb",
  "POV", "pov", "static", "night", False, False,
  "пятого числа ты переводишь лене семьдесят четыре тысячи, и для неё это обычная зарплата.",
  "the thumb hovers over the send button a long second and presses it once"),
 ("A4_SH15", "MARK_MAIN", "park_pond",
  "Mark alone on the bench under a black umbrella in steady rain, the briefcase sheltered against his hip, the pond surface stippled",
  "WS", "eye", "static", "day", False, False,
  "в дождь ты сидишь под зонтом, потому что «работу» никто не отменял.",
  "rain stipples the pond and drips in a steady line off one rib of the umbrella",
  "BRIEFCASE"),
 ("A4_SH16", "MARK_MAIN", "park_pond",
  "Mark on the bench with the phone at his ear, his professional half-smile on, one hand gesturing as if across a desk",
  "MCU", "eye", "static", "day", False, False,
  "по телефону ты говоришь бывшим поставщикам, что «рассматриваешь предложения», и голос твой звучит начальственно.",
  "his free hand turns over in a smooth practiced gesture as he talks into the phone"),
 ("A4_SH17", None, "park_pond",
  "a pair of polished black shoes planted still on wet gravel, a pigeon walking past the toes, a briefcase corner at the frame edge",
  "ECU", "eye", "static", "day", False, False,
  "голуби в парке уже узнают твои ботинки, а ты стараешься об этом не думать.",
  "the pigeon crosses the frame in small steps past the motionless polished shoes"),
 ("A4_SH18", "MARK_MAIN", "park_pond",
  "the park at dusk from above, one small suited figure rising from the bench and buttoning his jacket, long shadows across the paths",
  "EWS", "high", "pull_out", "evening", False, False,
  "апрель заканчивается, и у тебя всё ещё есть план, деньги и спокойный голос.",
  "the small figure rises from the bench and buttons his jacket with two unhurried moves"),
]

A5 = [
 ("A5_SH01", "MARK_MAIN", "hr_office",
  "past a recruiter's near shoulder, Mark sits upright on a low lime-green sofa holding out a printed CV across a glass table, his tie perfectly knotted",
  "OTS", "over", "static", "day", False, False,
  "на первом собеседовании тебе двадцать минут рассказывают, какая у них молодая команда.",
  "the printed CV passes over the glass table from his hand and he settles back upright"),
 ("A5_SH02", "MARK_MAIN", "hr_office",
  "Mark's face keeping polite attention while something tightens around his eyes, the bright coworking wall soft behind him",
  "CU", "eye", "static", "day", False, False,
  "слово «драйв» звучит четыре раза, и ты киваешь, как кивал на планёрках.",
  "he nods slowly at even intervals while his eyes stay flat and tired"),
 ("A5_SH03", "MARK_MAIN", "bus_stop",
  "Mark walks along the hot avenue with his jacket over one arm and the briefcase in the other hand, heat shimmer over the asphalt behind him",
  "WS", "eye", "track", "day", False, False,
  "в мае ты ходишь на собеседования, как на переговоры — костюм, портфель, твёрдое рукопожатие.",
  "the man walks a steady line along the pavement, the folded jacket swaying on his arm",
  "BRIEFCASE"),
 ("A5_SH04", "MARK_MAIN", None,
  "his own hand in frame holding a phone with a short email on screen, the sender line blurred, two brief paragraphs visible",
  "POV", "pov", "static", "day", False, False,
  "ответ приходит через восемь дней и умещается в два предложения со словом «к сожалению».",
  "the thumb scrolls the short email down and back up as if a third paragraph might appear"),
 ("A5_SH05", None, None,
  "a printed CV page lying on a glass table, a career of one company in one long block of text, a recruiter's pen tapping beside it",
  "ECU", "high", "static", "day", False, False,
  "в твоём резюме девятнадцать лет опыта, и для половины контор это минус, а не плюс.",
  "the pen taps twice beside the printed block and slides off frame"),
 ("A5_SH06", "MARK_MAIN", "hr_office",
  "Mark listens across the glass table with his hands folded on one knee, his jaw set, sunlight harsh through the floor-to-ceiling window",
  "MS", "eye", "static", "day", False, False,
  "второй кадровик честно говорит, что ты слишком дорогой, и предлагает «пересмотреть ожидания».",
  "his folded hands tighten slightly on his knee and he tilts his head as if weighing it"),
 ("A5_SH07", "MARK_MAIN", "hr_office",
  "Mark's face taking the question with a slow blink, the polite mask holding, a water cooler blurred behind his shoulder",
  "MCU", "eye", "static", "day", False, False,
  "третий смотрит в анкету и спрашивает, комфортно ли тебе будет с руководителем моложе тебя.",
  "he blinks slowly once and his brows draw a fraction as he holds the polite mask"),
 ("A5_SH08", "MARK_MAIN", "park_pond",
  "the june park from above in white midday heat, one suited figure on the bench in a wool suit, everyone else in the distance in t-shirts",
  "EWS", "high", "static", "day", False, False,
  "в июне в парке плюс двадцать девять, а ты сидишь в шерстяном костюме, потому что «на работе дресс-код».",
  "heat shimmer bends the air over the gravel path around the still seated figure"),
 ("A5_SH09", None, "park_pond",
  "a damp shirt collar and the loosened green striped tie in tight close-up, a suit jacket folded over the bench back behind",
  "ECU", "eye", "static", "day", False, False,
  "галстук ты теперь снимаешь в девять утра и надеваешь обратно в семнадцать пятнадцать.",
  "the loosened tie sways a centimetre as a warm draught crosses the bench"),
 ("A5_SH10", "MARK_MAIN", "canteen",
  "Mark carries a canteen tray with soup and bread along the rail, his suit jacket over his forearm, the queue rail guiding him",
  "MS", "eye", "static", "day", False, False,
  "обедать ты ходишь в столовую за парком, где бизнес-ланч отдают за двести сорок рублей.",
  "the tray slides along the steel rail under his hands and the soup surface trembles"),
 ("A5_SH11", None, None,
  "the white money envelope with the pencil column, the figure two hundred eighty crossed out and two hundred eight written under it",
  "INSERT", "eye", "static", "night", False, True,
  "в конце июня ты первый раз вскрываешь конверт, и двести восемьдесят превращаются в двести восемь.",
  "the pencil line settles under the new smaller number as the envelope flap eases down",
  "ENVELOPE"),
 ("A5_SH12", "MARK_MAIN", "park_pond",
  "Mark looks at his silent phone lying face-up on the bench slat, arms resting on his knees, shoulders a little lower than in spring",
  "MCU", "eye", "static", "day", False, False,
  "телефон звонит всё реже, и ты начинаешь отвечать даже на скрытые номера.",
  "his eyes hold on the dark phone screen and his thumb rubs the edge of his palm"),
 ("A5_SH13", "MARK_MAIN", "park_pond",
  "Mark stands under a linden in shirt sleeves looking out at the pond, the briefcase upright at his feet, jacket hooked on a finger over his shoulder",
  "WS", "eye", "static", "day", False, False,
  "ты повторяешь про себя, что до осени рынок мёртвый и что осенью всё обязательно закрутится.",
  "the linden leaves above him stir in the heat and his jacket sways gently on its finger hook",
  "BRIEFCASE"),
 ("A5_SH14", ("LENA_BASE", "MARK_MAIN"), "flat_kitchen",
  "past Lena's shoulder at the kitchen table, Mark stirs his tea looking into it, her hand resting near his elbow with the evening cup",
  "OTS", "over", "static", "evening", False, False,
  "вечером лена спрашивает, почему ты стал таким тихим, и ты отвечаешь — «жара».",
  "his spoon turns slowly in the tea while her hand settles quietly near his elbow"),
 ("A5_SH15", "MARK_MAIN", "flat_bedroom",
  "Mark's face on the pillow in the dark, eyes open, the ceiling light strip from the window across them",
  "CU", "eye", "push_in", "night", False, True,
  "ложь перестала быть временным решением задачи — теперь она и есть твоя основная работа.",
  "his open eyes shine faintly in the dark and a slow blink closes and reopens them"),
 ("A5_SH16", None, "bus_stop",
  "the summer avenue at dusk from above, sparse traffic, a bus pulling away leaving one man standing at the shelter",
  "EWS", "high", "static", "evening", True, False,
  "лето идёт мимо тебя, как автобус, на который ты больше не садишься.",
  "the bus pulls away from the shelter trailing warm dust in the low evening light"),
]

if __name__ == "__main__":
    seed_act("A3", PAL_A3, A3)
    seed_act("A4", PAL_A4, A4)
    seed_act("A5", PAL_A5, A5)
