# -*- coding: utf-8 -*-
"""Seed CH13 — Настоящая любовь (HEROINE_YOUNG + ANDREAS). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "real love unlike the wave, his modest warm flat, tender and frightening, soft lamplight"
SHOTS = [
 ("CH13_SH01", ("HEROINE_YOUNG","ANDREAS"), "andreas_flat",
  "medium of him bringing her into his modest flat, drafting plans and books around",
  "MS","eye","static","gdr_eve",False,False,
  "Андреас приводит тебя в свою скромную квартирку, чертежи на столе, книги, запах крепкого чая."),
 ("CH13_SH02", None, "andreas_flat",
  "close-up of the cosy flat details, a spare key resting on the table",
  "CU","eye","static","gdr_eve",True,False,
  "здесь так тепло и тихо, и впервые тебе не хочется бежать к утру в чью-то чужую ночь."),
 ("CH13_SH03", ("HEROINE_YOUNG","ANDREAS"), "andreas_flat",
  "medium close-up of him holding her gently, like something precious, non-explicit",
  "MCU","eye","static","gdr_eve",False,False,
  "он обнимает тебя не как добычу, а как драгоценность, бережно, будто боится спугнуть."),
 ("CH13_SH04", "HEROINE_YOUNG", "andreas_flat",
  "close-up of her feeling the long-lost warmth from childhood",
  "CU","eye","static","gdr_eve",False,True,
  "и ты вдруг чувствуешь то самое тепло из детства, которого ждала у холодного окна."),
 ("CH13_SH05", ("HEROINE_YOUNG","ANDREAS"), "andreas_flat",
  "medium of the two waking together, him making coffee in the morning",
  "MS","eye","static","dawn",False,False,
  "вы засыпаете рядом, и наутро он всё ещё здесь, варит кофе и тихо улыбается тебе."),
 ("CH13_SH06", "HEROINE_YOUNG", "andreas_flat",
  "medium close-up of her by the no-longer-empty side of the bed",
  "MCU","eye","static","dawn",False,True,
  "впервые вторая половина постели не пуста, и от этого почему-то хочется заплакать."),
 ("CH13_SH07", "ANDREAS", "andreas_flat",
  "close-up of Andreas reassuring her",
  "CU","eye","static","gdr_eve",False,False,
  "что во мне такого, шепчешь ты, а он отвечает просто, ты для меня целый мир."),
 ("CH13_SH08", ("HEROINE_YOUNG","ANDREAS"), "park",
  "medium of them in the park, him untroubled by the rumours",
  "MS","eye","static","gdr_day",False,False,
  "он не верит слухам о тебе, говорит, я вижу тебя настоящую, а не то, что болтают вокруг."),
 ("CH13_SH09", "HEROINE_YOUNG", "andreas_flat",
  "close-up of her almost forgetting the wave",
  "CU","eye","static","gdr_eve",False,False,
  "на несколько месяцев ты почти забываешь про волну, тебе хватает его одного, только его."),
 ("CH13_SH10", "HEROINE_YOUNG", "andreas_flat",
  "medium close-up of her timid hope",
  "MCU","eye","static","gdr_eve",False,False,
  "может, думаешь ты с робкой надеждой, может, я всё-таки умею любить по-настоящему."),
 ("CH13_SH11", None, "andreas_flat",
  "wide B-roll of the warm lamplit flat at night, silent",
  "WS","eye","static","gdr_eve",True,False,""),
]
if __name__ == "__main__":
    seed_act(13, "warm_home", MOOD, "static", "CH13 Real love", SHOTS)
