# -*- coding: utf-8 -*-
"""A7 (act_07_debt_pit) — collectors, garnishment fear, selling belongings, failed video call. Rock bottom."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from _seed_message_act_engine import seed_act

MOOD = ("bleak grey early-spring daylight and harsh phone-glow, oppressive debt-grey palette draining of color, "
        "cold hard shadows, exhausted cornered mood")

SHOTS = [
 ("A7_SH01","IRINA","kitchen","medium shot of the gaunt tired woman at the kitchen table buried in overdue notices","MS","eye","static","early_spring_grey_2026",False,False,
  "апрель, ты больше не успеваешь гасить, проценты сжирают зарплату, и займы уходят в просрочку"),
 ("A7_SH02",None,"kitchen","extreme close-up of the phone, an unknown number and a harsh collector on the line","ECU","eye","static","early_spring_grey_2026",False,False,
  "звонит незнакомый номер, жёсткий голос называет твою фамилию и сумму долга с пенями"),
 ("A7_SH03","IRINA","kitchen","medium shot of the woman going cold with shame as the collector speaks","MS","eye","static","early_spring_grey_2026",False,False,
  "у тебя холодеют руки, ты не знала что бывает такой стыд, когда чужой требует с тебя деньги"),
 ("A7_SH04",None,"room","close-up of the phone with threats about seizing property and calling her workplace","CU","eye","static","early_spring_grey_2026",False,False,
  "тебе говорят про опись имущества, про работу, про то что сообщат директору школы о долгах"),
 ("A7_SH05","IRINA","room","medium shot of the woman gripped by fear of exposure rather than of the debt itself","MS","eye","static","early_spring_grey_2026",False,False,
  "и ты боишься не долга, а того что узнают в школе, что скажут коллеги, что дойдёт до даши"),
 ("A7_SH06","IRINA","kitchen","medium shot of the woman flinching at the constantly ringing phone, refusing unknown numbers","MS","eye","static","early_spring_grey_2026",False,False,
  "теперь телефон звонит каждый день, разные агентства, ты перестаёшь брать незнакомые номера"),
 ("A7_SH07",None,"room","close-up of the phone with threatening texts and a photo of her own building entrance","CU","eye","static","early_spring_evening_2026",False,False,
  "приходят смс с угрозами, с фотографией твоего подъезда, они знают где именно ты живёшь"),
 ("A7_SH08","IRINA","stair","medium shot of a heavy-set man waiting by the building entrance as the woman slips past","MS","eye","static","early_spring_grey_2026",False,False,
  "однажды у подъезда тебя ждёт мужчина, спрашивает ирину сергеевну, ты проходишь мимо не дыша"),
 ("A7_SH09","IRINA","stair","close-up of the woman locking herself in, sitting in the dark so it seems no one is home","CU","eye","static","early_spring_evening_2026",False,False,
  "ты запираешься дома, сидишь в темноте и не зажигаешь свет, чтобы думали что никого нет"),
 ("A7_SH10","IRINA","room","medium shot of the woman selling her television, then the crystal set, stripping the room","MS","eye","static","early_spring_grey_2026",False,False,
  "ты продаёшь телевизор, потом бабушкин сервиз, потом золотую цепочку матери, всё в счёт долга"),
 ("A7_SH11",None,"room","extreme close-up of a pale rectangle on the wall where a rug hung and an empty cabinet, the flat emptying","ECU","eye","push_in","early_spring_grey_2026",False,True,
  "на стене светлый прямоугольник там где висел ковёр, в серванте пусто, квартира пустеет на глазах"),
 ("A7_SH12","IRINA","kitchen","close-up of the woman paying the most aggressive loan while the rest pile up","CU","eye","static","early_spring_evening_2026",False,False,
  "ты гасишь самый злой займ, остальные ждут, и снова не хватает на еду до самой зарплаты"),
 ("A7_SH13","IRINA","class","medium shot of the grey exhausted woman teaching, pupils noticing she looks ill","MS","eye","static","early_spring_grey_2026",False,False,
  "ты приходишь в школу серая, дети спрашивают вы заболели, а ты просто не спала и не ела"),
 ("A7_SH14","IRINA","staff","close-up of the woman flinching at every phone ring in the staff room, dreading discovery","CU","eye","static","early_spring_grey_2026",False,False,
  "ты вздрагиваешь от каждого звонка в учительской, вдруг это коллекторы дозвонились на работу"),
 ("A7_SH15",None,"kitchen","close-up of the phone with Viktor demanding another fee before his cargo is auctioned","CU","eye","static","early_spring_evening_2026",False,False,
  "а виктор пишет, груз выставят на аукцион если не оплатить хранение, ещё двести тысяч, умоляю"),
 ("A7_SH16","IRINA","kitchen","medium shot of the woman finally typing a desperate honest confession to him","MS","eye","static","early_spring_evening_2026",False,False,
  "и впервые ты пишешь ему, виктор у меня больше нет, я в долгах, я заложила кольцо, я не могу"),
 ("A7_SH17",None,"room","close-up of the phone with Viktor's wounded guilt-tripping reply","CU","eye","static","early_spring_evening_2026",False,False,
  "он отвечает обиженно, значит ты мне не веришь, значит всё было зря, я думал ты меня любишь"),
 ("A7_SH18","IRINA","room","close-up of the woman apologizing first, terrified of losing him","CU","eye","static","early_spring_evening_2026",False,False,
  "и ты пугаешься потерять его, извиняешься первой, обещаешь найти, хотя искать уже совсем негде"),
 ("A7_SH19","IRINA","kitchen","medium shot of the woman daring a video call at night, just needing to see his face","MS","eye","static","early_spring_night_2026",False,False,
  "ночью ты не выдерживаешь и сама набираешь видеозвонок, тебе просто надо увидеть его лицо"),
 ("A7_SH20",None,"kitchen","extreme close-up of the phone, the call ringing then dropping, replaced by his text excuse","ECU","eye","static","early_spring_night_2026",False,False,
  "идут гудки, потом сброс, потом сообщение, связь не тянет видео родная, ты же всё знаешь"),
 ("A7_SH21","IRINA","kitchen","medium shot of the woman swallowing the worm of doubt, too invested to stop","MS","low","static","early_spring_night_2026",False,False,
  "червь сомнения шевелится, но ты слишком устала и слишком много вложила, чтобы перестать верить"),
 ("A7_SH22",None,"kitchen","close-up of the phone with the logistics accomplice urging her not to quit at the finish","CU","eye","static","early_spring_night_2026",False,False,
  "снова звонит логист, груз почти ваш, не бросайте на финише, виктор за вас поручился своими деньгами"),
 ("A7_SH23","IRINA","room","medium shot of the woman borrowing from a neighbour with a made-up story","MS","eye","static","early_spring_grey_2026",False,False,
  "ты занимаешь у соседки, у бывшей коллеги, придумываешь операцию, похороны, что угодно ради денег"),
 ("A7_SH24","IRINA","stair","close-up of the woman moving through her town like a shadow, eyes down, owing almost everyone","CU","eye","static","early_spring_grey_2026",False,False,
  "ты ходишь по своему городу как тень, опустив глаза, ты должна почти всем кого знаешь"),
 ("A7_SH25",None,"kitchen","close-up of the phone calculator showing the staggering total of all her debts","CU","eye","static","early_spring_night_2026",False,True,
  "однажды ты складываешь все долги в одну цифру и не можешь поверить, два с половиной миллиона"),
 ("A7_SH26","IRINA","kitchen","medium shot of the woman frozen before the number, the weight of it on her face","MS","eye","static","early_spring_night_2026",False,False,
  "два с половиной миллиона тенге, за полгода переписки, и ни разу ты не слышала его живого голоса"),
 ("A7_SH27","IRINA","room","close-up of the woman still finding excuses for him, blaming storms and customs","CU","eye","static","early_spring_night_2026",False,False,
  "и всё равно ты находишь ему оправдание, шторм, таможня, бюрократия, не он же виноват во всём этом"),
 ("A7_SH28","IRINA","kitchen","medium shot of the failing greying woman taking yet another loan in a friend's name","MS","eye","static","early_spring_grey_2026",False,False,
  "ты худеешь, седеешь, давление скачет, но идёшь и берёшь ещё один займ под паспорт знакомой"),
 ("A7_SH29",None,"room","close-up of the phone with Viktor swearing a Friday auction is the very last payment","CU","eye","static","early_spring_evening_2026",False,False,
  "виктор клянётся всем святым, последний платёж, аукцион в пятницу, успей, и я сразу к тебе"),
 ("A7_SH30","IRINA","room","close-up of the cornered woman with nothing left to pay either old debts or him","CU","eye","static","early_spring_night_2026",False,False,
  "ты загнана в угол, нечем платить старое и нечем платить ему, и не у кого больше просить взаймы"),
 ("A7_SH31","IRINA","kitchen","medium shot of the woman reaching for the phone to call her daughter, then stopping, ashamed","MS","eye","static","early_spring_night_2026",False,False,
  "ночью ты думаешь о даше, тянешься к телефону, но не можешь набрать, стыд сильнее одиночества"),
 ("A7_SH32","IRINA","kitchen","close-up of the hollowed woman alone in the dark kitchen at the end of April, clinging to Friday","CU","low","static","early_spring_night_2026",False,True,
  "конец апреля, ты на дне, в долгах по горло, одна, и держишься только за его обещание про пятницу"),
]

if __name__ == "__main__":
    seed_act("e7","A7_debt_grey",MOOD,"0107000000","0157000000","static","act_07_debt_pit",SHOTS)
