# -*- coding: utf-8 -*-
"""Seed CH33 — Старость подступает (HEROINE_OLD debut). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "real old age arriving, the body and the chase both finished, grey resignation"
SHOTS = [
 ("CH33_SH01", "HEROINE_OLD", "old_flat",
  "medium of the heroine truly old now, the hunt long over",
  "MS","eye","static","day",False,False,
  "годы идут, и однажды охотиться уже не на что и незачем, ты состарилась по-настоящему."),
 ("CH33_SH02", "HEROINE_OLD", "old_flat",
  "close-up of the old woman in the mirror she once mocked in others",
  "CU","eye","static","day",False,False,
  "в зеркале старуха, та самая, над которой ты когда-то смеялась в других, в чужих."),
 ("CH33_SH03", None, "old_flat",
  "wide of a small quiet grey apartment in reunified Berlin",
  "WS","eye","static","day",True,False,
  "ты доживаешь в маленькой квартирке в объединённом Берлине, тихой, серой, совершенно пустой."),
 ("CH33_SH04", "HEROINE_OLD", "old_flat",
  "medium close-up of her unable to feel without the wave",
  "MCU","eye","static","day",False,False,
  "тёплая волна больше не приходит совсем, и без неё ты будто разучилась чувствовать."),
 ("CH33_SH05", "HEROINE_OLD", "street_west",
  "medium of her on the street, no one turning to look anymore",
  "MS","eye","static","day",False,False,
  "на улице на тебя больше никто не оборачивается, ты стала прозрачной, совсем невидимой."),
 ("CH33_SH06", None, "park",
  "wide of a park bench across the changing seasons",
  "WS","eye","static","day",True,False,
  "ты подолгу сидишь в парке и смотришь, как сменяются времена года без всякого смысла."),
 ("CH33_SH07", "HEROINE_OLD", "park",
  "close-up of her watching young couples, never having learned closeness",
  "CU","eye","static","day",False,False,
  "молодые проходят мимо парами, и ты вспоминаешь, что так и не научилась быть с кем-то."),
 ("CH33_SH08", "HEROINE_OLD", "old_flat",
  "medium close-up of her talking to herself in the evenings",
  "MCU","eye","static","eve",False,False,
  "вечерами ты разговариваешь сама с собой, потому что больше просто не с кем, ни души."),
 ("CH33_SH09", None, "old_flat",
  "extreme close-up of the dusty box with Andreas's key",
  "ECU","top_down","static","day",True,True,
  "ключ Андреаса всё лежит в шкатулке, и пыль на ней становится толще с каждым годом."),
 ("CH33_SH10", "HEROINE_OLD", "old_flat",
  "close-up of her summing up a long life full of men, utterly alone",
  "CU","eye","static","day",False,True,
  "ты понимаешь, что прожила долгую жизнь, полную мужчин, и при этом совершенно одна."),
 ("CH33_SH11", None, "park",
  "wide B-roll of a grey seasonal park, silent",
  "WS","eye","static","day",True,False,""),
]
if __name__ == "__main__":
    seed_act(33, "eldritch_grey", MOOD, "static", "CH33 Old age creeps", SHOTS)
