# -*- coding: utf-8 -*-
"""Seed CH18 — Оправдание, я свободна (HEROINE_YOUNG). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "hollow bravado, telling herself she is free, grey daylight, denial papering over loss"
SHOTS = [
 ("CH18_SH01", "HEROINE_YOUNG", "her_room",
  "medium of the heroine steeling herself, refusing to grieve",
  "MS","eye","static","gdr_day",False,False,
  "ты решаешь не горевать, ты убеждаешь себя, что Андреас был ошибкой и почти что капканом."),
 ("CH18_SH02", "HEROINE_YOUNG", "street_east",
  "medium close-up of her chin up, repeating her mantra",
  "MCU","eye","static","gdr_day",False,False,
  "мне никто не нужен, повторяешь ты, я никому ничего не должна, я совершенно свободна."),
 ("CH18_SH03", None, "disco",
  "wide of the dancehall, back to the old life",
  "WS","eye","static","night",True,False,
  "и ты возвращаешься в привычную ночь, как ни в чём не бывало, с прежней боевой улыбкой."),
 ("CH18_SH04", None, "disco",
  "close-up of faceless men, the wave returning on command",
  "CU","eye","static","night",True,False,
  "снова дискотеки, снова взгляды, снова чужие руки, и волна послушно к тебе возвращается."),
 ("CH18_SH05", "HEROINE_YOUNG", "disco",
  "medium close-up of her noticing the wave fades faster now",
  "MCU","eye","static","night",False,False,
  "только теперь волна гаснет ещё быстрее, и тебе приходится подливать её всё чаще."),
 ("CH18_SH06", "HEROINE_YOUNG", "her_room",
  "close-up of his face surfacing in her mind at night",
  "CU","eye","static","night",False,False,
  "по ночам иногда всплывает его лицо, но ты гонишь его прочь очередным новым свиданием."),
 ("CH18_SH07", None, "factory",
  "medium of coworkers gossiping on the floor",
  "MS","eye","static","gdr_day",True,False,
  "на заводе шепчут, бросила такого хорошего парня, совсем, видать, с ума сошла девка."),
 ("CH18_SH08", "HEROINE_YOUNG", "factory",
  "close-up of her defiant retort",
  "CU","eye","static","gdr_day",False,False,
  "а ты задираешь подбородок, мне с ним было бы скучно, я не создана для кастрюль и пелёнок."),
 ("CH18_SH09", "HEROINE_YOUNG", "her_room",
  "medium close-up of the lie wearing thin at night",
  "MCU","eye","static","night",False,False,
  "но ночью, в пустой комнате, эта ложь звучит всё менее убедительно даже для тебя самой."),
 ("CH18_SH10", None, "her_room",
  "extreme close-up of the box with the key, lid snapping shut",
  "ECU","top_down","static","night",True,True,
  "ты открываешь шкатулку, смотришь на его ключ и тут же быстро захлопываешь крышку."),
 ("CH18_SH11", None, "disco",
  "wide B-roll of the smoky dancehall, silent",
  "WS","eye","static","night",True,False,""),
]
if __name__ == "__main__":
    seed_act(18, "gdr_grey", MOOD, "static", "CH18 Justify", SHOTS)
