# -*- coding: utf-8 -*-
"""Seed CH08 — Объект под прицелом (action-first). Idempotent."""
from _seed_tiler_act_engine import seed_act

MOOD = "vast cold fortress construction site, sea haze, surveillance menace, blinding marble glare"

SHOTS = [
    ("CH08_SH01", None, "objext",
     "aerial establishing of a colossal secret palace construction site clinging to a cliff cape above the grey Black Sea, scaffolding, tower cranes, perimeter fences, no people",
     "EWS", "high", "push_in", "object_day", True, True,
     "и я увидел его, стройку размером с город, на скале у моря."),
    ("CH08_SH02", "BAKHTI", "objext",
     "the master stepping off the bus and staring up, dwarfed, mouth open at the impossible scale",
     "MS", "low", "static", "object_day", False, False,
     "я строил всю жизнь, но такого не видел никогда."),
    ("CH08_SH03", None, "objext",
     "wide low-angle of vast scaffolding clinging to a towering pale stone facade, dizzying height, sea wind, no people",
     "WS", "low", "pan", "object_day", True, False,
     "леса уходили в небо, и ветер с моря свистел в них."),
    ("CH08_SH04", None, "objext",
     "medium shot of a perimeter watchtower with the dark silhouette of a sniper and a guard dog below, against a hazy sky",
     "MS", "low", "static", "object_day", False, True,
     "по периметру вышки, собаки, бесполётная зона."),
    ("CH08_SH05", None, "objext",
     "view through a sniper rifle scope, crosshairs centred on a tiny lone worker crossing the marble courtyard far below",
     "WS", "pov", "static", "object_day", False, True,
     "и ствол, что смотрел тебе в спину каждую минуту."),
    ("CH08_SH06", "GENA", "objext",
     "a heavy shaven-headed security guard planting himself in the master's path, jabbing a finger, contemptuous",
     "MS", "eye", "static", "object_day", False, False,
     "охранник гена встретил меня вот так."),
    ("CH08_SH07", ("GENA", "BAKHTI"), "objext",
     "Gena on the left jabbing a finger into Bakhti's chest on the right, sneering an order",
     "MCU", "eye", "static", "object_day", False, False,
     "понаехавший, плитку клади, в ту сторону не смотри, там снимут."),
    ("CH08_SH08", "BAKHTI", "objext",
     "close-up of the master's face lowering, jaw tight, swallowing the insult in silence",
     "CU", "eye", "static", "object_day", False, False,
     "я опускал голову и шёл, спорить себе дороже."),
    ("CH08_SH09", None, "bytovka",
     "wide shot of grim crowded site workers' barracks, rows of bunks, bare bulbs, no clear faces",
     "WS", "high", "static", "object_day", True, False,
     "жили мы тут же, в бараках, как и везде."),
    ("CH08_SH10", "BAKHTI", "bytovka",
     "extreme close-up of the master laying out his tile tools and the wrapped turquoise shard on the bunk",
     "ECU", "top_down", "static", "object_day", False, True,
     "руки мои тут золото, а сам я понаехавший."),
    ("CH08_SH11", None, "marble",
     "wide shot of an immense marble hall in scaffolding, mountains of crated Italian marble under tarps, gilded ceiling above, no people",
     "WS", "low", "push_in", "object_day", True, True,
     "а внутри ждал мрамор, горами, на миллиарды."),
    ("CH08_SH12", "BAKHTI", "marble",
     "medium close-up of the master running a hand over a crate of veined Italian marble, awed and grim",
     "MCU", "eye", "static", "object_day", False, False,
     "я считал в плитках, один смеситель, как весь мой квартал."),
    ("CH08_SH13", None, "marble",
     "close-up of stacked crates of veined Italian marble and boxes of gilded fixtures, price tags glimpsed, no people",
     "CU", "eye", "pan", "object_day", True, False,
     "мимо текли деньги, каких я и сосчитать не мог."),
    ("CH08_SH14", "BAKHTI", "objext",
     "the master glancing up warily at the distant watchtower as he carries a tile box, the crosshair feeling on his back",
     "MS", "low", "static", "object_day", False, False,
     "тебя не тронут, ты ценный, повторял я себе."),
    ("CH08_SH15", None, "objext",
     "wide night B-roll of the floodlit fortress site glowing against the black sea, tiny figures, no clear faces",
     "WS", "eye", "static", "object_day", True, False, ""),
    ("CH08_SH16", "BAKHTI", "bytovka",
     "close-up of the master's face in the dark barrack, fear and resolve mixed, gripping the turquoise shard",
     "CU", "eye", "static", "object_day", False, True,
     "но ствол в спину чувствуешь, даже когда спишь."),
]

if __name__ == "__main__":
    seed_act(8, "object_marble_cold", MOOD, "animated", "CH08 Under-scope", SHOTS)
