# -*- coding: utf-8 -*-
"""optimizer shots: A3 (conveyor + layoff-hero cameo), A4 (the parking question), A5 (mother's box)."""
from _optimizer_engine import seed_act

PAL_A3 = "flat grey conveyor light, muted institutional tones, pale window haze"
PAL_A4 = "low evening sun on concrete, long car shadows, amber and grey"
PAL_A5 = "warm old-flat lamplight, faded wallpaper tones, soft window daylight"

A3 = [
 ("A3_SH01", None, "client_open",
  "a long institutional corridor of a factory administration, identical doors with number plates, a floor polisher's wet trail shining",
  "EWS", "eye", "track", "day", True, False,
  "дальше — конвейер: мебельная фабрика, молочный комбинат, типография, страховая, сеть аптек.",
  "the wet polish trail dries slowly along the corridor as the strip lights hum"),
 ("A3_SH02", None, None,
  "a printed day schedule on a clipboard, twenty-two surnames in fifteen-minute slots, two already struck through in pen",
  "INSERT", "top", "static", "day", False, False,
  "в графике на день двадцать две фамилии с шагом в пятнадцать минут.",
  "a pen tip strikes through the next surname with one clean line"),
 ("A3_SH03", "ELYA_BASE", "client_meeting",
  "Elya arranges a client meeting room before the first session, setting the tissue box to the left and the water bottle to the right with both hands",
  "MS", "eye", "static", "day", False, False,
  "ты входишь в чужую переговорку первой и ставишь салфетки слева, воду справа.",
  "her hands place the tissue box and the bottle into their exact positions and square them",
  "TISSUES"),
 ("A3_SH04", None, "client_meeting",
  "the meeting room door opening, a man entering seen from behind, a folder clutched to his chest, the oval table waiting",
  "WS", "eye", "static", "day", False, False,
  "люди заходят по одному, и у каждого в руках почему-то что-то есть — папка, телефон, стакан.",
  "the door swings open and the entering figure pauses one beat on the threshold",
  None, "crowd"),
 ("A3_SH05", "ELYA_BASE", "client_meeting",
  "Elya mid-phrase across the table, her hands open and calm over the laminated card, her voice visibly even",
  "MCU", "eye", "static", "day", False, False,
  "ты говоришь фразы с карточки, и они работают, потому что ты собрала их из настоящих разговоров.",
  "her open hands make one small calming gesture over the card and settle",
  "CARD"),
 ("A3_SH06", None, None,
  "a hand reaching across a table and drawing a tissue from the white cube box, the tissue lifting cleanly",
  "ECU", "eye", "static", "day", False, False,
  "салфетку берут семь человек из десяти, всегда правой, как ты и рассчитала.",
  "the hand draws the tissue out in one slow pull and the next tissue rises in its place",
  "TISSUES"),
 ("A3_SH07", "GEROY_MAIN", "client_meeting",
  "a tired man with an employee pass card on a blue lanyard sits down across the table, setting his folder square in front of him",
  "MS", "eye", "static", "day", False, True,
  "после обеда напротив садится мужчина с пропуском на синем шнурке — логистика, девятнадцать лет стажа.",
  "he lowers himself onto the chair and squares the folder in front of him with both hands"),
 ("A3_SH08", ("ELYA_BASE", "GEROY_MAIN"), "client_meeting",
  "past Elya's shoulder, the logistics manager leans forward asking something with one hand slightly raised, his lanyard swinging",
  "OTS", "over", "static", "day", False, False,
  "он спрашивает не про деньги, а про линию — кто теперь не даст ей встать.",
  "he leans forward onto the table edge and his raised hand opens on the question"),
 ("A3_SH09", "ELYA_BASE", "client_meeting",
  "Elya's face keeping the professional mask while something behind her eyes registers the question, her lips parting a beat late",
  "CU", "eye", "push_in", "day", False, True,
  "ты отвечаешь по карточке, что линия — забота подрядчика, и впервые фраза царапает тебя саму.",
  "her professional mask holds while her eyes flicker once away from his and back"),
 ("A3_SH10", None, None,
  "an employee pass card on a blue lanyard lying on the table edge beside a signed agreement, the photo corner visible",
  "ECU", "high", "static", "day", False, False,
  "его карту погасят раньше, чем он спустится со второго этажа, — так написано в регламенте.",
  "the lanyard slides a centimetre as the card settles flat on the polished table"),
 ("A3_SH11", ("ELYA_BASE", "GEROY_MAIN"), "client_meeting",
  "through the glass wall, the logistics manager walks away with a cardboard box while Elya watches from the table, her stopwatch still in hand",
  "WS", "eye", "static", "day", False, False,
  "он выходит с коробкой ровно на четвёртой минуте, и по нормативу это идеальная сессия.",
  "he recedes down the corridor beyond the glass while her thumb stops the watch"),
 ("A3_SH12", "ELYA_BASE", "client_meeting",
  "Elya alone at the table checking her watch, then reaching for the untouched water bottle across the table",
  "MCU", "eye", "static", "day", False, False,
  "до конца дня ещё девять фамилий, и ты наливаешь себе его нетронутую воду.",
  "her hand draws the untouched bottle across the table and unscrews the cap slowly"),
 ("A3_SH13", None, "client_open",
  "a factory yard seen from a second-floor window, three distant figures crossing with cardboard boxes, their steps slow",
  "EWS", "high", "static", "day", True, False,
  "за окном через двор идут трое с коробками, и их шаг медленнее обычного заводского.",
  "the three distant figures cross the yard slowly, boxes held to their chests",
  None, "crowd"),
 ("A3_SH14", ("RITA_BASE", "ELYA_BASE"), "client_meeting",
  "Rita marks a session count on her tablet standing beside seated Elya, glancing at her with open apprentice admiration",
  "MS", "eye", "static", "day", False, False,
  "рита ведёт счёт сессий в планшете и смотрит на тебя, как на мастера цеха.",
  "the young woman taps the count on her tablet and steals an admiring glance down"),
 ("A3_SH15", None, None,
  "a diminished stack of flat cardboard boxes by the meeting room door, a fresh strapped bundle being set down beside it",
  "INSERT", "eye", "static", "evening", False, False,
  "коробки у двери переговорки заканчиваются к вечеру, и рита приносит новую пачку.",
  "the fresh bundle settles against the wall and the strap tension eases audibly",
  "BOXES"),
 ("A3_SH16", "ELYA_BASE", "parking",
  "Elya's face in the rear-view mirror of her parked car at dusk, make-up perfect, eyes flat with a day of other people's endings",
  "MCU", "eye", "static", "evening", False, False,
  "вечером в зеркале машины у тебя лицо человека, который хорошо сделал непонятно что.",
  "her eyes in the mirror hold their own reflection and one slow blink resets them"),
 ("A3_SH17", "ELYA_BASE", None,
  "her own hand holding a phone over a banking app, a salary line of two hundred sixty thousand highlighted",
  "POV", "pov", "static", "evening", False, False,
  "оклад приходит пятого, ровно двести шестьдесят, и цифра не задаёт вопросов.",
  "the thumb pulls the banking screen down to refresh and the salary line holds"),
 ("A3_SH18", None, "parking",
  "the business tower at night from the car park, floors going dark in irregular patches, red aircraft lamps on the roof",
  "EWS", "low", "static", "night", True, False,
  "этажи, где ты сегодня работала, гаснут один за другим до следующего списка.",
  "lit floors die in irregular patches up the dark tower face"),
]

A4 = [
 ("A4_SH01", "ELYA_BASE", "parking",
  "Elya stops mid-step in the car park, keys in hand, a man's still silhouette waiting by her car three rows ahead",
  "WS", "eye", "static", "evening", False, False,
  "у парковки тебя ждёт человек из утреннего списка, и охрану звать поздно.",
  "she stops mid-step and her keys settle silent into her closing palm",
  None, "crowd"),
 ("A4_SH02", "ELYA_BASE", "parking",
  "Elya's face assessing calmly, chin level, her eyes doing the trained scan from hands to exits",
  "MCU", "eye", "static", "evening", False, False,
  "ты оцениваешь дистанцию и его руки, как учили на тренинге по безопасности.",
  "her eyes travel one measured pass from his hands to the exit lane and back"),
 ("A4_SH03", ("ELYA_BASE",), "parking",
  "past a man's corduroy shoulder, Elya stands composed with her bag strap in both hands, evening sun flaring behind her",
  "OTS", "over", "static", "evening", False, False,
  "он говорит, что не скандалить пришёл, а спросить одну вещь.",
  "her hands settle on the bag strap and she gives him one small permitting nod"),
 ("A4_SH04", "ELYA_BASE", "parking",
  "Elya's face as the question lands, the composure intact but her eyes suddenly very still, amber light across her cheek",
  "CU", "eye", "push_in", "evening", False, True,
  "вопрос простой — «как вы спите?» — и он разворачивается и уходит первым.",
  "all the motion drains out of her eyes while the amber light holds her face"),
 ("A4_SH05", None, "parking",
  "a man walking away between the car ranks into low sun, unhurried, his long shadow sliding over bonnets",
  "WS", "eye", "static", "evening", False, False,
  "ты стоишь у машины дольше, чем заняла вся ваша встреча.",
  "his long shadow slides across the car bonnets as he recedes into the sun glare",
  None, "crowd"),
 ("A4_SH06", "ELYA_BASE", "elya_flat",
  "Elya in her armchair by the big dark window, legs drawn up, an untouched glass of wine on the floor beside her",
  "MS", "eye", "static", "night", False, False,
  "дома ты честно проверяешь — спишь ты хорошо, семь часов, без снов.",
  "she draws her knees up a little tighter and her fingers tap once on the armrest"),
 ("A4_SH07", None, None,
  "a phone screen with a sleep tracker graph, seven hours twelve minutes in large digits, a dark bedroom blurred behind",
  "ECU", "eye", "static", "night", False, False,
  "трекер показывает семь часов двенадцать минут, и это лучший сон по отделу.",
  "the tracker graph glows steadily while the screen dims one shade toward sleep"),
 ("A4_SH08", "ELYA_BASE", "elya_flat",
  "Elya at the night window with her arms crossed loosely, her forehead almost touching the cold glass, city lights below",
  "MCU", "eye", "static", "night", False, False,
  "тебя смущает не совесть, а то, что вопрос был задан без злости.",
  "her forehead tips slowly toward the glass until it almost touches"),
 ("A4_SH09", None, None,
  "the laminated card lying alone on a white kitchen island under a single spot lamp, its handwriting small and neat",
  "INSERT", "top", "static", "night", False, False,
  "ты достаёшь карточку и первый раз читаешь её не как инструмент, а как текст.",
  "the spot lamp glow trembles once across the laminate as the flat air shifts",
  "CARD"),
 ("A4_SH10", "ELYA_BASE", "training_hall",
  "Elya at the flipchart mid-sentence with the marker lowered, a beat of lost words, the listening rows patient before her",
  "WS", "eye", "static", "day", False, False,
  "в четверг на тренинге ты впервые теряешь строку, и зал вежливо ждёт.",
  "her marker lowers by degrees and her eyes search the flipchart for the lost line",
  None, "crowd"),
 ("A4_SH11", ("RITA_BASE", "ELYA_BASE"), "training_hall",
  "Rita catches up with Elya in the emptying hall aisle, concern on her face, Elya already reassembling the composed smile",
  "MS", "eye", "static", "day", False, False,
  "рита переспрашивает, всё ли в порядке, и ты отвечаешь слишком быстро для человека, у которого всё в порядке.",
  "the young woman tilts her head in concern while the older one's smile snaps back on"),
 ("A4_SH12", "KIRILL_BASE", "training_hall",
  "Kirill watches from the hall doorway with his thermo-mug raised halfway, his eyes doing quiet arithmetic",
  "CU", "eye", "static", "day", False, False,
  "кирилл замечает сбой из дверей зала и делает глоток из термокружки.",
  "he takes one slow sip and his eyes stay fixed over the mug rim"),
 ("A4_SH13", ("KIRILL_BASE", "ELYA_BASE"), "consult_office",
  "Kirill and Elya walk the glass corridor side by side, he talking with a small economical gesture, she nodding a shade too evenly",
  "MS", "eye", "track", "day", False, False,
  "он говорит без укора — «устала — возьми неделю», и это звучит как диагностика оборудования.",
  "the two walk in step along the glass wall, his hand sketching one small economical arc"),
 ("A4_SH14", None, None,
  "a potted white orchid on an office windowsill, two blooms open and a third bud splitting, city haze beyond the glass",
  "ECU", "eye", "static", "day", False, False,
  "орхидея в кабинете цветёт вторым цветком — единственное, что ты вырастила, а не сократила.",
  "the splitting bud trembles faintly in the ventilation draught by the glass",
  "ORCHID"),
 ("A4_SH15", "ELYA_BASE", "elya_cabinet",
  "Elya waters the orchid from a small measuring cup, her face soft for once, the office blurred bright behind her",
  "MCU", "eye", "static", "day", False, False,
  "ты поливаешь её по средам, по расписанию, как всё живое в твоей жизни.",
  "the thin stream of water runs from the cup while her face softens by a degree",
  "ORCHID"),
 ("A4_SH16", None, "consult_office",
  "the city in evening rush from the consultancy floor, rivers of headlights between towers, one floor of lights dying nearby",
  "EWS", "high", "static", "evening", True, False,
  "неделю ты не берёшь — впереди сезон бюджетов, а это всегда сезон списков.",
  "rivers of headlights crawl between the towers as dusk settles floor by floor"),
]

A5 = [
 ("A5_SH01", None, "mother_plant",
  "a knot of workers at the old plant checkpoint reading pinned sheets on the veteran board, shoulders close, morning cold",
  "WS", "eye", "static", "morning", False, False,
  "в октябре на заводе точных приборов объявляют «программу эффективности» — не твою, чужую.",
  "the knot of readers tightens by a shoulder as a new sheet settles on the board",
  None, "crowd"),
 ("A5_SH02", "GALINA_BASE", "mother_plant",
  "Galina reads a notification sheet at the checkpoint, holding it at arm's length the way far-sighted people do, her badge on her lapel",
  "MCU", "eye", "static", "morning", False, False,
  "матери выдают уведомление прямо на проходной, между турникетом и доской ветеранов.",
  "she holds the sheet out at arm's length and her chin lifts as she reads it"),
 ("A5_SH03", None, None,
  "an official notification sheet in worn hands, dense grey paragraphs, a round stamp and an illegible signature",
  "ECU", "eye", "static", "morning", False, False,
  "в бумаге написано «оптимизация штатной численности», и ни одного человеческого слова.",
  "the sheet trembles slightly in the worn hands holding it"),
 ("A5_SH04", None, "mother_plant",
  "a security guard's high-visibility shoulder in the foreground, a line of workers with boxes filing through the turnstile beyond",
  "MS", "eye", "static", "day", False, False,
  "их выводят по десять человек в день, с охраной, без стаканов воды и без салфеток.",
  "the file of workers moves through the turnstile one by one, boxes held level",
  None, "crowd"),
 ("A5_SH05", "GALINA_BASE", "mother_plant",
  "Galina walks out through the turnstile carrying a printer-paper box, her back straight, the veteran photo board behind her",
  "WS", "eye", "static", "day", False, True,
  "тридцать один год стажа умещается в коробку из-под бумаги для принтера.",
  "she carries the box through the turnstile with her back held deliberately straight"),
 ("A5_SH06", "GALINA_BASE", "mother_plant",
  "Galina's lined face held firm, chin up, her eyes fixed ahead past the camera, the checkpoint clock above her",
  "CU", "eye", "static", "day", False, False,
  "она держит спину, потому что на доске у проходной всё ещё висит её фотография.",
  "her chin stays up while her eyes glisten once and refuse to spill"),
 ("A5_SH07", "ELYA_BASE", "parking",
  "Elya slams her car door and strides across cracked asphalt toward the plant gate, coat flying open, tablet left on the seat",
  "MS", "eye", "track", "day", False, False,
  "ты бросаешь встречу и едешь на завод через весь город.",
  "she strides fast across the cracked asphalt, her open coat swinging with each step"),
 ("A5_SH08", ("GALINA_BASE", "ELYA_BASE"), "mother_plant",
  "past Galina's shoulder, Elya reaches for the printer-paper box with both hands while her mother keeps hold of it a beat longer",
  "OTS", "over", "static", "day", False, False,
  "мать говорит «не начинай», хотя ты ещё ничего не начала.",
  "four hands hold the same box for a long beat before the older pair lets go"),
 ("A5_SH09", None, None,
  "the enamel veteran badge on the coat lapel in tight close-up, a thumb brushing across it once",
  "ECU", "eye", "static", "day", False, False,
  "значок ветерана на её лацкане им вернуть нельзя — он не числится на балансе.",
  "a thumb brushes across the badge enamel and drops away"),
 ("A5_SH10", "GALINA_BASE", "mother_flat",
  "Galina unpacks the box on the kitchen table, setting out a mug, a desk calendar and a framed workshop photo in a careful row",
  "MS", "eye", "static", "day", False, False,
  "дома из коробки выходят кружка, настольный календарь и фотография цеха девяносто восьмого года.",
  "her hands set the mug, the calendar and the framed photo down in one careful row"),
 ("A5_SH11", "ELYA_BASE", "mother_flat",
  "Elya's face watching from the kitchen doorway, guilt and tenderness fighting under the composed surface",
  "CU", "eye", "push_in", "day", False, True,
  "ты смотришь, как это выглядит с третьей стороны — не из-за стола и не напротив, а из семьи.",
  "her composed surface thins as her eyes follow each object out of the box"),
 ("A5_SH12", ("ELYA_BASE", "GALINA_BASE"), "mother_flat",
  "Elya slides a thick envelope across the oilcloth table and Galina pushes it back behind the bread bin with the flat of her hand",
  "MS", "eye", "static", "evening", False, False,
  "ты кладёшь на стол конверт, и мать отодвигает его хлебницей, не глядя.",
  "the envelope slides forward under one hand and back behind the bread bin under the other"),
 ("A5_SH13", None, None,
  "a thick white envelope wedged behind an old bread bin on a kitchen counter, lamplight on its edge",
  "ECU", "eye", "static", "evening", False, False,
  "конверт так и остаётся под хлебницей до самого твоего ухода.",
  "the envelope edge glows in the lamplight as the kitchen shadow deepens around it"),
 ("A5_SH14", "GALINA_BASE", "mother_flat",
  "Galina asks a quiet question over her teacup, her eyes level and unhurried on her daughter",
  "MCU", "eye", "static", "evening", False, False,
  "она спрашивает тихо — «а у вас там, у кадровых, тоже так делают?».",
  "her teacup lowers slowly and her level eyes wait over its rim"),
 ("A5_SH15", "ELYA_BASE", "mother_flat",
  "Elya's face answering with a steadiness that costs her, lamplight warm on one cheek, the crystal dresser blurred behind",
  "CU", "eye", "static", "evening", False, False,
  "ты отвечаешь «у нас по-другому, мама», и это правда, от которой не легче.",
  "her steady answering face holds while her thumb rubs the teacup handle below the frame"),
 ("A5_SH16", "ELYA_BASE", "mother_flat",
  "Elya sits on the stairwell steps between floors in her coat, elbows on knees, the landing window grey above her",
  "WS", "high", "static", "evening", False, False,
  "на лестнице между этажами ты сидишь десять минут, прежде чем спуститься к машине.",
  "she sits motionless on the step and her breath fogs faintly in the stairwell cold"),
]

if __name__ == "__main__":
    seed_act("A3", PAL_A3, A3)
    seed_act("A4", PAL_A4, A4)
    seed_act("A5", PAL_A5, A5)
