# -*- coding: utf-8 -*-
"""squeeze_out shots: A3 (the squeeze begins), A4 (the notebook), A5 (Pasha leaves)."""
from _squeeze_out_engine import seed_act

PAL_A3 = "grey institutional light, drained colours, pale cold windows"
PAL_A4 = "cold evening desk light, deep shadow corners, blue dusk windows"
PAL_A5 = "clear spring light, fresh green accents, warm brick tones"

A3 = [
 ("A3_SH01", ("ZHANNA_BASE", "ANTON_BASE"), "director_office",
  "Zhanna slides a reassignment memo across the glass desk to Anton with two fingers, her red pen laid precisely beside it",
  "MS", "eye", "static", "day", False, False,
  "первым уходит южный узел — «передаём молодой команде, вы же не против наставничества».",
  "the memo slides across the glass under her two fingers and stops square before him"),
 ("A3_SH02", "ANTON_BASE", "bureau_open",
  "Anton looks at his monitor where a project folder icon is greyed out, his hand still on the mouse, his jaw working",
  "MCU", "eye", "static", "day", False, False,
  "доступ к своим же файлам ты теряешь в пятницу вечером, без письма и без объяснений.",
  "his hand clicks the greyed folder twice and goes still on the mouse"),
 ("A3_SH03", None, None,
  "a chat window on a monitor listing project groups, one group row marked as left the conversation",
  "ECU", "eye", "static", "day", False, False,
  "из чата развязки тебя выключают ночью — утром ты просто видишь строку «вы покинули группу».",
  "the chat list scrolls one line and the greyed row settles at the bottom"),
 ("A3_SH04", "ANTON_BASE", "meeting_bureau",
  "Anton half rises at the long table asking a question while faces turn to the presenter instead, his hand flat on a rolled plan",
  "WS", "eye", "static", "day", False, False,
  "на планёрке твой вопрос повисает в воздухе, и следующий слайд отвечает не тебе.",
  "he settles slowly back onto his chair as the faces stay turned away",
  None, "crowd"),
 ("A3_SH05", ("PASHA_BASE", "ANTON_BASE"), "bureau_open",
  "Pasha and Anton at the window with paper cups, Pasha counting something off on his fingers, Anton staring into the middle distance",
  "MS", "eye", "static", "day", False, False,
  "паша загибает пальцы — проекты, чаты, планёрки — и говорит «это называется выживают».",
  "three fingers fold down one by one on the counting hand between the paper cups",
  "HELMET"),
 ("A3_SH06", "ANTON_BASE", "bureau_open",
  "Anton's face refusing the word, a stubborn half-smile forming, his glasses catching flat grey light",
  "CU", "eye", "static", "day", False, False,
  "ты отвечаешь «меня нельзя выжить, на мне узлы» — и сам слышишь, как это звучит.",
  "the stubborn half-smile sets on his face and holds a shade too long"),
 ("A3_SH07", None, "bureau_open",
  "two movers carrying a drawing station desk across the hall, its drawers taped shut, colleagues clearing a path",
  "WS", "eye", "track", "day", False, False,
  "в четверг твой стол переезжает «по плану рассадки» — к двери серверной.",
  "the taped desk floats across the hall on four hands as the aisle clears before it",
  None, "crowd"),
 ("A3_SH08", "ANTON_BASE", "server_corner",
  "Anton sets his monitor on the desk wedged by the server-room door, cable trays over his head, the fire extinguisher at his elbow",
  "MS", "eye", "static", "day", False, False,
  "новое место официально называется «зона проектного сопровождения», неофициально — у серверной.",
  "he sets the monitor down and shifts it twice to fit the wedged desk"),
 ("A3_SH09", None, "server_corner",
  "the server-room door with its ventilation grille, a red status light, the hum almost visible in the frame",
  "ECU", "eye", "static", "day", False, False,
  "серверная гудит на одной ноте девять часов в день, и нота эта — си.",
  "the red status light pulses in slow rhythm behind the ventilation grille"),
 ("A3_SH10", ("ZHANNA_BASE",), "bureau_open",
  "past a worried employee's shoulder, Zhanna spreads her hands in polished regret, her red pen between two fingers like a cigarette",
  "OTS", "over", "static", "day", False, True,
  "жанна говорит фразу, которую ты запомнишь дословно — «мы никого не увольняем».",
  "her spread hands close softly together over the folder as the phrase lands"),
 ("A3_SH11", "ANTON_BASE", "server_corner",
  "Anton works at the wedged desk in headphones, his back straight out of spite, the corridor traffic passing behind him",
  "MCU", "eye", "static", "day", False, False,
  "ты решаешь просто — работать так, чтобы им стало стыдно, и не дождутся.",
  "his back straightens another deliberate degree as he pulls the headphones on",
  None, "crowd"),
 ("A3_SH12", None, None,
  "the interchange drawing pinned above the wedged desk, its corner brushing the server-door frame, slightly curled by the warm air",
  "INSERT", "eye", "static", "day", False, False,
  "распечатку развязки ты перевешиваешь над новым столом — флаг гарнизона.",
  "the drawing's curled corner lifts and settles in the warm air from the grille",
  "BLUEPRINT"),
 ("A3_SH13", ("ANTON_BASE", "MARINA_BASE"), "home_kitchen",
  "Anton retells the desk move at supper with forced lightness while Marina watches his hands instead of his face",
  "MS", "eye", "static", "evening", False, False,
  "дома ты подаёшь переезд как анекдот, но марина смотрит не на лицо, а на руки.",
  "his fork sketches the office plan in the air while her eyes stay on his hands"),
 ("A3_SH14", None, None,
  "a man's hand at a supper table crumbling a bread slice into small pieces beside an untouched plate",
  "ECU", "high", "static", "evening", False, False,
  "руки у тебя крошат хлеб в мелкую крошку, и тарелка стоит нетронутая.",
  "the fingers crumble the bread edge into smaller and smaller pieces"),
 ("A3_SH15", "TIMA_BASE", "home_kitchen",
  "Tima under the table walks the dinosaur along a chair leg, glancing up at the quiet adults above",
  "CU", "low", "static", "evening", False, False,
  "тима под столом водит динозавра по ножке стула и впервые делает это молча.",
  "the dinosaur climbs the chair leg slowly in the small fist as the boy's eyes lift",
  "DINO"),
 ("A3_SH16", "ANTON_BASE", "home_hall",
  "Anton stands in the dark hallway still in his coat, keys in hand, looking at himself in the photo-framed mirror",
  "MS", "eye", "static", "night", False, False,
  "перед сном ты стоишь в прихожей в пальто и репетируешь завтрашнее спокойное лицо.",
  "his reflection squares its shoulders and sets its face into practiced calm"),
 ("A3_SH17", None, "bureau_open",
  "the old half of the bureau hall with three desks already empty, tube racks orphaned, one fig plant browning",
  "WS", "eye", "pan_left", "day", True, False,
  "за месяц старый зал теряет троих — они уходят сами, и статистика жанны остаётся чистой.",
  "the browning fig leaves stir as the empty desks hold their squares of dust"),
 ("A3_SH18", None, None,
  "a staff list close-up with three names struck through in red and one name circled twice",
  "ECU", "eye", "static", "day", False, True,
  "в её списке три фамилии зачёркнуты, а твоя обведена дважды — ты крепче, чем они думали.",
  "the red pen hovers over the circled name and taps it twice"),
]

A4 = [
 ("A4_SH01", None, None,
  "a squared notebook opening on a desk, dated entries in small dense handwriting, a sticky-note bookmark being pressed down",
  "INSERT", "top", "static", "evening", False, True,
  "ты заводишь блокнот и записываешь каждый эпизод с датой — инженер документирует всё.",
  "a thumb presses the fresh sticky-note flat beside the newest dated entry",
  "NOTEBOOK"),
 ("A4_SH02", "ANTON_BASE", "server_corner",
  "Anton writes in the notebook shielded by his monitor, his eyes flicking up over the glasses at the passing corridor",
  "MCU", "eye", "static", "day", False, False,
  "записи короткие — «пятое число, снят с планёрки», «девятое, отключён доступ к архиву».",
  "his pen writes two short lines while his eyes flick up over the glasses once",
  "NOTEBOOK"),
 ("A4_SH03", ("ANTON_BASE",), "meeting_bureau",
  "past a lawyer's suited shoulder, Anton pushes the opened notebook across the table, his finger holding a marked page",
  "OTS", "over", "static", "day", False, False,
  "юрист листает твой блокнот десять минут и говорит слово, которое хуже приговора, — «законно».",
  "his finger keeps the marked page open as the notebook turns under another hand",
  "NOTEBOOK"),
 ("A4_SH04", "ANTON_BASE", "street_bureau",
  "Anton on the granite steps after the consultation, tie loosened, watching the traffic with unseeing eyes",
  "WS", "eye", "static", "day", False, False,
  "выдавливание не статья, а стиль управления, и защищаться от него можно только собой.",
  "he stands on the steps with his coat open while traffic slides past unseen"),
 ("A4_SH05", "ANTON_BASE", "server_corner",
  "Anton demonstratively polishes his work: a perfect drawing on screen, desk squared, the mug aligned with the monitor edge",
  "MS", "eye", "static", "day", False, False,
  "твой ответ — работать безупречно: если они ждут повода, повода не будет.",
  "his hand squares the mug to the monitor edge in one final precise move",
  "MUG"),
 ("A4_SH06", None, None,
  "a flawless technical drawing on a monitor in the dim corner, reflected cable trays crossing the screen",
  "ECU", "eye", "static", "day", False, False,
  "чертежи из угла у серверной выходят лучше, чем из любого светлого места в зале.",
  "the drawing rotates slowly on screen under the reflected cable trays"),
 ("A4_SH07", ("ZHANNA_BASE", "ANTON_BASE"), "bureau_open",
  "Zhanna pauses by Anton's corner desk with bright administrative concern, he half turns from the monitor with a held-together face",
  "MS", "eye", "static", "day", False, False,
  "жанна интересуется, «комфортно ли на новом месте», и умеет спрашивать это без иронии.",
  "she tilts her head in bright concern while he half turns with a level face"),
 ("A4_SH08", "ANTON_BASE", "server_corner",
  "Anton's face after she leaves, the held expression dissolving into plain tiredness, server light red on his cheek",
  "CU", "eye", "push_in", "day", False, False,
  "ты отвечаешь «вполне», и это первая фраза за год, где вы оба соврали.",
  "the level expression drains off his face as the red light pulses on his cheek"),
 ("A4_SH09", None, "home_kitchen",
  "the family kitchen with supper going cold, one chair empty, a phone lying face down by the empty plate",
  "WS", "eye", "static", "evening", True, False,
  "ужины ты теперь пропускаешь не из-за работы — из-за того, что после неё надо отсидеться.",
  "steam thins over the cooling plates around the one empty chair"),
 ("A4_SH10", ("MARINA_BASE", "ANTON_BASE"), "home_kitchen",
  "Marina turns from the sink mid-question while Anton answers into his cup, the distance across the small kitchen suddenly visible",
  "MCU", "eye", "static", "night", False, False,
  "марина спрашивает «сколько это ещё будет длиться», и ты честно отвечаешь «пока не выиграю».",
  "she turns with the towel still in her hands while he speaks into the cup"),
 ("A4_SH11", "MARINA_BASE", "home_kitchen",
  "Marina's face at the sink, love and a new fear of the word he chose, the towel pressed still in her hands",
  "CU", "eye", "static", "night", False, True,
  "её пугает не подвал и не проценты — её пугает слово «выиграю».",
  "her hands press the towel flat as her eyes search the word for its cost"),
 ("A4_SH12", "ANTON_BASE", "child_room",
  "Anton sits on the low bed reading to sleeping Tima anyway, the rocket lamp warm, the book half closed on his knee",
  "MS", "eye", "static", "night", False, False,
  "тиме ты читаешь уже спящему — так тоже считается, говоришь ты себе.",
  "the book lowers slowly to his knee as he watches the sleeping boy breathe"),
 ("A4_SH13", None, None,
  "the toy dinosaur standing guard on the bedside shelf, its worn crest toward the door, the rocket lamp glow behind",
  "ECU", "eye", "static", "night", False, False,
  "динозавр на полке стоит гребнем к двери — тима говорит, что так он охраняет.",
  "the rocket lamp glow flickers once across the worn crest of the standing dinosaur",
  "DINO"),
 ("A4_SH14", "ANTON_BASE", "home_hall",
  "Anton in the dark hallway checks the notebook in his bag like a soldier checking a magazine, then zips it shut",
  "MCU", "eye", "static", "morning", False, False,
  "утром ты проверяешь блокнот в сумке, как проверяют документы перед границей.",
  "his hand pats the notebook through the bag fabric and draws the zip shut",
  "NOTEBOOK"),
 ("A4_SH15", None, "street_bureau",
  "the bureau entrance in cold morning light, the old poplar bare, a queue of new white-collar backs at the door",
  "WS", "low", "static", "morning", True, False,
  "в бюро теперь входят по пропускам с фотографией — головная компания любит учёт.",
  "the queue of backs shuffles up the granite steps one card-beep at a time",
  None, "crowd"),
 ("A4_SH16", "ANTON_BASE", "bureau_open",
  "Anton walks the hall aisle past the new white desks, nodding to men who consult their screens instead of nodding back",
  "MS", "eye", "track", "morning", False, False,
  "ты идёшь через зал, здороваясь, и половина приветствий возвращается в пустоту.",
  "he nods left and right along the aisle while the screens hold the new faces",
  None, "crowd"),
]

A5 = [
 ("A5_SH01", ("PASHA_BASE", "ANTON_BASE"), "bureau_open",
  "Pasha stands at his cleared desk fitting the last things into a bicycle pannier, Anton beside him with both hands in his pockets",
  "MS", "eye", "static", "day", False, False,
  "весной паша собирает стол за двадцать минут — он уходит сам, не дожидаясь своей галочки.",
  "the pannier flap closes over the last mug as the curly-haired man buckles it",
  "HELMET"),
 ("A5_SH02", "PASHA_BASE", "bureau_open",
  "Pasha's merry face gone serious for once, the helmet held against his chest like a hat at a funeral",
  "CU", "eye", "static", "day", False, True,
  "он говорит «я инженер, а не мебель» — и в зале никто не поднимает головы.",
  "his fingers tighten on the helmet rim as the joke leaves his face"),
 ("A5_SH03", None, "bureau_open",
  "a cleared drawing station with pale rectangles where photos were taped, a coiled cable left in the dust outline",
  "ECU", "eye", "static", "day", False, False,
  "после него остаются светлые прямоугольники от фотографий и контур пыли от кульмана.",
  "the coiled cable settles slowly into the dust outline of the missing station"),
 ("A5_SH04", ("PASHA_BASE", "ANTON_BASE"), "street_bureau",
  "Pasha wheels his bicycle beside walking Anton along the bureau street, gesturing wide with his free hand, spring light through the poplar",
  "WS", "eye", "track", "day", False, False,
  "на улице он говорит — «нас девять человек, десятый стол уже стоит, это твой».",
  "the bicycle wheels tick along between them as his free hand sketches the offer"),
 ("A5_SH05", "ANTON_BASE", "street_bureau",
  "Anton stops by the signboard column, shaking his head with a grateful half-smile, one hand flat on his chest",
  "MCU", "eye", "static", "day", False, False,
  "ты благодаришь и отказываешься — «я пятнадцать лет строил это бюро, они должны заплатить».",
  "his flat hand presses his chest once as his head shakes the slow refusal"),
 ("A5_SH06", "PASHA_BASE", "street_bureau",
  "Pasha looks at Anton the way engineers look at a crack in a load-bearing wall, then claps his shoulder",
  "CU", "eye", "static", "day", False, False,
  "паша смотрит на тебя, как на трещину в несущей стене, и говорит «ладно, стол подождёт».",
  "his hand claps the shoulder twice and stays there half a beat too long"),
 ("A5_SH07", None, "pasha_office",
  "a small studio office with nine mismatched desks, a bicycle hung on exposed brick, plans pinned everywhere, kettle steam",
  "WS", "eye", "static", "day", True, False,
  "его бюро — девять столов, кирпич, чайник и очередь заказов на полгода вперёд.",
  "kettle steam drifts across the hung bicycle and the pinned plans",
  None, "crowd"),
 ("A5_SH08", "ANTON_BASE", "server_corner",
  "Anton back at the wedged desk looks at the corridor where Pasha used to appear with coffee, the second chair empty",
  "MS", "eye", "static", "day", False, False,
  "в первый понедельник без паши тишина у серверной делается на тон гуще.",
  "his eyes drift to the empty second chair and return slowly to the screen"),
 ("A5_SH09", None, None,
  "two paper coffee cups in a bin, one clean and upright, one crumpled, seen from above",
  "ECU", "top", "static", "day", False, False,
  "кофе из автомата ты теперь носишь один стакан вместо двух.",
  "the upright cup settles a degree deeper into the bin as the lid swings"),
 ("A5_SH10", "ZHANNA_BASE", "director_office",
  "Zhanna updates the city map, moving a green flag onto the old bureau district, her face pleasantly neutral",
  "MCU", "eye", "static", "day", False, False,
  "в отчёте жанны уход паши называется «естественным оттоком дублирующих функций».",
  "her hand presses the green flag pin into the map with a small final push"),
 ("A5_SH11", "ANTON_BASE", "bureau_open",
  "Anton watches movers stack Pasha's drawing table onto a trolley, his arms folded, his thumb rubbing the vest wool",
  "WS", "eye", "static", "day", False, False,
  "кульман паши увозят в архив в тот же четверг — быстрее, чем увозили его проекты.",
  "the trolley rolls past with the stacked table while his thumb works the vest wool",
  None, "crowd"),
 ("A5_SH12", ("ANTON_BASE", "MARINA_BASE"), "home_kitchen",
  "Marina reads Pasha's forwarded office photo on Anton's phone, hope flickering, Anton already reaching to take the phone back",
  "MCU", "eye", "static", "evening", False, False,
  "марина смотрит фото пашиного бюро дольше, чем нужно, и возвращает телефон молча.",
  "her thumb lingers on the photo as the phone passes back between their hands"),
 ("A5_SH13", "MARINA_BASE", "home_kitchen",
  "Marina at the window with her back to the room, her reflection watching Anton in the dark glass",
  "MS", "eye", "static", "night", False, False,
  "она не уговаривает — она из тех, кто дожидается, пока человек услышит себя сам.",
  "her reflection in the dark glass holds him while her shoulders stay turned away"),
 ("A5_SH14", "ANTON_BASE", "home_hall",
  "Anton wipes dust from the framed hallway photo of the family at his interchange opening, his thumb slow on the glass",
  "ECU", "eye", "static", "night", False, False,
  "на фото с открытия развязки вы трое смеётесь, и тима там ростом с ограждение.",
  "his thumb wipes one slow arc of dust off the laughing figures under the glass"),
 ("A5_SH15", "ANTON_BASE", "server_corner",
  "Anton pins a fresh calendar page over the wedged desk and crosses out the first square hard",
  "MCU", "eye", "static", "day", False, False,
  "ты вешаешь над столом календарь и начинаешь зачёркивать дни, как в казарме.",
  "the pen crosses the first calendar square with two hard strokes"),
 ("A5_SH16", None, "courtyard_bins",
  "the back courtyard in spring rain, a discarded drawing table leg sticking out of the waste container by the brick wall",
  "WS", "eye", "static", "day", True, False,
  "во дворе у баков торчит нога списанного кульмана — бюро избавляется от лишнего дерева.",
  "rain streaks the brick wall while the table leg juts motionless from the container"),
]

if __name__ == "__main__":
    seed_act("A3", PAL_A3, A3)
    seed_act("A4", PAL_A4, A4)
    seed_act("A5", PAL_A5, A5)
