# -*- coding: utf-8 -*-
"""Seed CH03 — Школа, первая красавица (2nd person). Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "warm sepia 1980s school glow, soft grain, charged social air"
SHOTS = [
 ("CH03_SH01", None, "school",
  "wide establishing of a late-Soviet school corridor, scuffed parquet, tall windows, pupils milling",
  "WS","high","pan","sepia_80s",True,False,
  "в школе ты быстро понимаешь, красота, это власть."),
 ("CH03_SH02", None, "school",
  "medium shot of a pretty twelve-year-old schoolgirl checking herself in the cloakroom mirror, sure of herself",
  "MS","eye","static","sepia_80s",True,False,
  "ты первая красавица класса, и это твой маленький трон."),
 ("CH03_SH03", None, "school",
  "medium shot of two boys squabbling to carry the girl's satchel down the corridor",
  "MS","eye","static","sepia_80s",True,False,
  "мальчишки дерутся за право нести твой портфель."),
 ("CH03_SH04", None, "school",
  "close-up of the schoolgirl's confident smiling face getting all the attention",
  "CU","eye","static","sepia_80s",True,False,
  "тебе всё прощают, двойки, дерзость, лишь бы ты улыбнулась."),
 ("CH03_SH05", None, "school",
  "wide shot of plain girls whispering enviously behind the pretty girl's back",
  "WS","eye","static","sepia_80s",True,False,
  "девчонки шепчутся за спиной, завидуют, и тебе это сладко."),
 ("CH03_SH06", None, "school",
  "medium shot of a teacher softening and favouring the pretty pupil at her desk",
  "MS","eye","static","sepia_80s",True,False,
  "даже учителя смягчаются, красивым словно ставят на балл выше."),
 ("CH03_SH07", None, "school",
  "extreme close-up of the girl admiring her own reflection in a dark window pane",
  "ECU","eye","push_in","sepia_80s",True,True,
  "ты ловишь своё отражение в каждом стекле и не можешь оторваться."),
 ("CH03_SH08", None, "school",
  "medium shot of a talented plain girl at the blackboard, ignored while the beauty shines",
  "MS","eye","static","sepia_80s",True,False,
  "отличница тащит все олимпиады, но звезда тут всё равно ты."),
 ("CH03_SH09", None, "school",
  "close-up of the schoolgirl learning to use a glance and a turn of the head to command a room",
  "CU","eye","static","sepia_80s",True,False,
  "ты учишься пользоваться этим, один взгляд, поворот, и все твои."),
 ("CH03_SH10", "MOTHER", "mother",
  "medium close-up of the proud mother at home, glowing at her daughter's triumphs",
  "MCU","eye","static","sepia_80s",False,False,
  "мама светится, вот увидишь, красота тебя по жизни вывезет."),
 ("CH03_SH11", None, "school",
  "extreme close-up of the girl's face flushed with the first warm rush of being looked at",
  "ECU","eye","static","sepia_80s",True,True,
  "и внутри впервые та тёплая волна, когда на тебя оборачиваются."),
 ("CH03_SH12", None, "school",
  "wide sepia B-roll of the empty school yard at golden hour, bare poplars",
  "WS","high","static","sepia_80s",True,False,""),
]
if __name__ == "__main__":
    seed_act(3, "sepia_warm", MOOD, "animated", "CH03 School", SHOTS)
