# -*- coding: utf-8 -*-
"""Seed CH24 — Зеркала врут, фото без фильтра (2nd person). Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "cold honest daylight, the flattering illusion shattering, raw"
SHOTS = [
 ("CH24_SH01", None, "cafe",
  "wide establishing of an ordinary cafe in daylight, someone raising a phone to photograph a group",
  "WS","high","push_in","cafe_day",True,False,
  "ты сидишь в кафе, кто-то фотографирует компанию."),
 ("CH24_SH02", "HEROINE_OLD", "cafe",
  "medium shot of the heroine caught in the background of a stranger's candid photo",
  "MS","eye","static","cafe_day",False,False,
  "и ты случайно попадаешь в чужой кадр."),
 ("CH24_SH03", None, "cafe",
  "extreme close-up of a phone screen showing an unfiltered daylight photo of her mask-like face",
  "ECU","top_down","static","cafe_day",True,True,
  "без фильтра, при дневном свете, ты видишь вот это."),
 ("CH24_SH04", "HEROINE_OLD", "cafe",
  "close-up of the heroine frozen with shock at the photo",
  "CU","eye","static","cafe_day",False,False,
  "и впервые понимаешь, что видят все остальные."),
 ("CH24_SH05", "HEROINE_OLD", "cafe",
  "medium close-up of the heroine, the gap between her self-image and reality collapsing",
  "MCU","eye","static","cafe_day",False,False,
  "не та красавица из домашнего зеркала, а застывшая маска."),
 ("CH24_SH06", None, "cafe",
  "extreme close-up of the photo beside a memory-flash of her radiant young face",
  "ECU","eye","static","cafe_day",True,False,
  "куда делось твоё лицо, твоё настоящее лицо."),
 ("CH24_SH07", "HEROINE_OLD", "bathroom",
  "medium shot of the heroine rushing to a bathroom mirror to see the truth",
  "MS","eye","pan","cafe_day",False,False,
  "ты бежишь к зеркалу и впервые видишь правду."),
 ("CH24_SH08", None, "bathroom",
  "extreme close-up of her reflection truly seen for once, no flattery",
  "ECU","eye","static","cafe_day",True,True,
  "домашнее зеркало льстило, а это, честное, не врёт."),
 ("CH24_SH09", "HEROINE_OLD", "bathroom",
  "close-up of the heroine wanting to break down, the mask holding",
  "CU","eye","static","cafe_day",False,False,
  "ты хочешь разрыдаться, а лицо держит маску."),
 ("CH24_SH10", "HEROINE_OLD", "bathroom",
  "medium close-up of the heroine covering the mirror with her hand",
  "MCU","eye","static","cafe_day",False,False,
  "ты закрываешь зеркало ладонью."),
 ("CH24_SH11", "HEROINE_OLD", "bathroom",
  "close-up of the heroine's face, unbearable to look at",
  "CU","eye","static","cafe_day",False,True,
  "впервые в жизни тебе невыносимо смотреть на себя."),
 ("CH24_SH12", None, "park",
  "wide B-roll of a cold grey park, bare trees, the truth settling in",
  "WS","high","static","cafe_day",True,False,""),
]
if __name__ == "__main__":
    seed_act(24, "cold_day", MOOD, "static", "CH24 Mirrors lie", SHOTS)
