# -*- coding: utf-8 -*-
"""irreplaceable shots: A3 (single point of failure), A4 (the vendor), A5 (parallel run)."""
from _irreplaceable_engine import seed_act

PAL_A3 = "grey boardroom light, red accent glare, cold window haze"
PAL_A4 = "vendor teal accents, badge-lanyard colours, bright project light"
PAL_A5 = "dual screen glow, split warm and cold light, late office dusk"

A3 = [
 ("A3_SH01", ("ARTUR_BASE", "BORIS_BASE"), "cio_office",
  "Artur asks Boris across the standing desk for a knowledge-transfer plan, calm and direct, the whiteboard diagram behind him",
  "MS", "eye", "static", "day", False, False,
  "артур просит по-хорошему — план передачи знаний, три месяца, любой удобный формат.",
  "his open hand offers the request across the standing desk"),
 ("A3_SH02", "BORIS_BASE", "cio_office",
  "Boris agrees with a broad accommodating smile, the smile of a man planning to drown the request in process",
  "MCU", "eye", "static", "day", False, False,
  "ты соглашаешься широко и радушно — так соглашаются утопить дело в согласованиях.",
  "his broad smile settles in as his eyes stay busy behind it"),
 ("A3_SH03", None, None,
  "a knowledge-transfer plan document of three pages, every line a meeting about a meeting, approvals chained",
  "ECU", "top", "static", "day", False, False,
  "твой «план передачи» — три страницы совещаний о совещаниях, и артур читает его молча.",
  "the three pages fan slowly under a reading thumb"),
 ("A3_SH04", "KATYA_BASE", "it_room",
  "Katya sits opposite Boris with a notebook for the first scheduled session, he lectures history instead of substance",
  "MS", "eye", "static", "day", False, False,
  "на первой «сессии» ты два часа рассказываешь кате историю системы и ни одного пароля.",
  "her pen waits over the empty page as the lecture circles the substance"),
 ("A3_SH05", "KATYA_BASE", "it_room",
  "Katya's face across the desk, patience thinning into clarity, the pencil going back into her bun",
  "CU", "eye", "static", "day", False, False,
  "катя закрывает пустой блокнот и говорит — «борис палыч, я же не враг, враг — это автобус».",
  "the notebook closes under her hand as the pencil slides back into the bun"),
 ("A3_SH06", "BORIS_BASE", "it_room",
  "Boris blinks at the word, thrown for one beat, then reassembles the benevolent mask",
  "MCU", "eye", "static", "day", False, False,
  "«какой автобус» — «который собьёт вас, и восемнадцать тысяч позиций лягут навсегда».",
  "one blink cracks the mask before the benevolence reassembles"),
 ("A3_SH07", None, "meeting_it",
  "a risk map projected on the meeting-room screen, one red square dominating the corner, board members' backs",
  "WS", "eye", "static", "day", False, False,
  "на совете директоров показывают карту рисков, и в углу горит красный квадрат с одной фамилией.",
  "the red square holds the corner as heads angle toward it",
  None, "crowd"),
 ("A3_SH08", "BORIS_BASE", "meeting_it",
  "Boris at the board table almost pleased, arms crossed over the cardigan, the red square reflected in his glasses",
  "MCU", "eye", "static", "day", False, True,
  "ты сидишь под этим квадратом почти польщённый — впервые твою незаменимость показывают на проекторе.",
  "the red square glints in his glasses over the almost-pleased mouth"),
 ("A3_SH09", ("ARTUR_BASE",), "meeting_it",
  "past a board member's shoulder, Artur delivers the alternative of replacing the system itself, a budget slide behind",
  "OTS", "over", "static", "day", False, False,
  "и тогда артур говорит фразу, которая всё решает, — «незаменимых людей не бывает, бывают незаменённые системы».",
  "his level voice lands the line as the budget slide settles behind him"),
 ("A3_SH10", "BORIS_BASE", "meeting_it",
  "Boris's face as the sentence lands, the pleasure draining, the arithmetic arriving late but whole",
  "CU", "eye", "push_in", "day", False, True,
  "до тебя доходит с опозданием на минуту — уволить нельзя тебя, но можно уволить систему.",
  "the pleasure drains by degrees as the late arithmetic fills his eyes"),
 ("A3_SH11", None, "meeting_it",
  "a show of hands around the board table, sleeves rising one after another, minutes being typed",
  "WS", "eye", "static", "day", False, False,
  "совет голосует за миграцию единогласно, и твой красный квадрат становится строкой бюджета.",
  "sleeves rise around the table one after another as the minutes fill",
  None, "crowd"),
 ("A3_SH12", "BORIS_BASE", "corridor_it",
  "Boris walks the corridor after the vote, nodding to people mechanically, his hand finding the flash drive cord",
  "MS", "eye", "track", "day", False, False,
  "из переговорки ты выходишь с прямой спиной, и рука сама держится за шнурок на шее.",
  "his mechanical nods pass down the corridor as his hand rides the cord",
  "USB"),
 ("A3_SH13", ("GENA_BASE", "BORIS_BASE"), "server_room",
  "Gena listens to the retelling and exhales slowly through pursed lips, a long technical whistle",
  "CU", "eye", "static", "evening", False, False,
  "гена выслушивает и присвистывает длинно, по-инженерному — так свистят над сгоревшей платой.",
  "the slow whistle escapes as his head tips at the racks"),
 ("A3_SH14", "BORIS_BASE", "server_room",
  "Boris pats the old tower twice, defiance stiffening back into his shoulders",
  "MS", "eye", "static", "evening", False, False,
  "ты хлопаешь сервер и говоришь — «пусть попробуют, миграции без меня не живут».",
  "his two defiant pats land on the steel as his shoulders square",
  "SERVER"),
 ("A3_SH15", None, None,
  "the drawer with the cipher notebook being locked, then checked twice, the key disappearing under the collar",
  "INSERT", "eye", "static", "evening", False, False,
  "в тот вечер ты запираешь ящик и дважды проверяешь — крепость переходит на осадное положение.",
  "the key turns, checks twice and vanishes under the collar on its cord",
  "CIPHER"),
 ("A3_SH16", "KATYA_BASE", "openspace_trade",
  "Katya at her desk late, teaching herself from vendor documentation PDFs, a second monitor of diagrams",
  "MS", "eye", "static", "night", False, False,
  "катя тем временем скачивает документацию вендора и читает её, как читают билеты перед экзаменом.",
  "the vendor PDF scrolls on her second monitor as her notes fill the first"),
 ("A3_SH17", "BORIS_BASE", "boris_flat",
  "Boris at his home desk stares at a forum draft he cannot finish, the bravado thread abandoned mid-sentence",
  "MCU", "eye", "static", "night", False, False,
  "дома ты садишься писать на форум привычную браваду, и она не пишется.",
  "the cursor blinks mid-sentence in the abandoned bravado draft"),
 ("A3_SH18", None, "it_room",
  "the IT room at night, the audit probe blinking beside the old tower, the cactus between two monitor glows",
  "WS", "eye", "static", "night", True, False,
  "крепость стоит, гарнизон спит плохо, а маленькая коробочка аудита слушает и учится.",
  "the probe diode flickers its fast pattern beside the steady green tower"),
]

A4 = [
 ("A4_SH01", None, "openspace_trade",
  "vendor implementation consultants arriving in matching polo shirts, rolling cases, badge lanyards in company teal",
  "WS", "eye", "static", "day", False, False,
  "в мае приходят внедренцы — восемь человек в одинаковых поло, контракт на восемь миллионов.",
  "the rolling cases file through the office in a matched teal line",
  None, "crowd"),
 ("A4_SH02", "BORIS_BASE", "openspace_trade",
  "Boris watches the vendor row set up from his doorway, arms folded, a siege commander counting enemy tents",
  "MCU", "eye", "static", "day", False, False,
  "ты смотришь на их ряды из дверей каморки, как комендант — на осадные шатры.",
  "his folded arms settle as his eyes count the teal row desk by desk"),
 ("A4_SH03", ("ARTUR_BASE", "BORIS_BASE"), "meeting_it",
  "the kickoff meeting, Artur presenting the migration timeline, Boris raising procedural objections with pleasure",
  "MS", "eye", "static", "day", False, False,
  "на кикофе ты задаёшь одиннадцать процедурных вопросов, и каждый прибавляет проекту неделю.",
  "his raised pen counts objections as the timeline slide waits behind"),
 ("A4_SH04", None, None,
  "a migration Gantt chart with several bars already shifted right, red dependency arrows crossing",
  "ECU", "eye", "static", "day", False, False,
  "график миграции едет вправо ещё до старта, и ты собираешь эти сдвиги, как трофеи.",
  "the shifted bars hold their red arrows across the crowded chart"),
 ("A4_SH05", "BORIS_BASE", "it_room",
  "Boris answers a vendor data request strictly by regulation: a printed form, a signature field, a queue number",
  "MS", "eye", "static", "day", False, True,
  "саботируешь ты честно, по регламенту — на каждый запрос форма, подпись и очередь.",
  "the printed form slides across with its queue number stamped square",
  "CIPHER"),
 ("A4_SH06", None, "corridor_it",
  "a vendor consultant waiting by the printer alcove with a folder, checking his watch against the corridor clock",
  "MCU", "eye", "static", "day", False, False,
  "внедренцы учатся ждать у твоей двери, и в их отчётах появляется слово «блокер».",
  "the consultant's watch lifts against the corridor clock over the folder",
  None, "crowd"),
 ("A4_SH07", "ARTUR_BASE", "cio_office",
  "Artur reads a weekly report where one surname repeats in the blockers column, his face patient and cooling",
  "CU", "eye", "static", "evening", False, False,
  "в еженедельном отчёте одна фамилия повторяется в колонке «блокеры» девять раз.",
  "his stylus underlines the repeating surname down the blockers column"),
 ("A4_SH08", "KATYA_BASE", "meeting_it",
  "Katya translates between the vendor team and warehouse staff, two dialects meeting in her diagrams",
  "WS", "eye", "static", "day", False, False,
  "катя становится переводчиком между складом и вендором — единственная, кто говорит на обоих языках.",
  "her diagram bridges the table as heads from both sides lean in",
  None, "crowd"),
 ("A4_SH09", "BORIS_BASE", "warehouse_trade",
  "Boris on the warehouse floor demonstratively fixes an old-system glitch in minutes while a vendor consultant films the process",
  "MS", "eye", "static", "day", False, False,
  "при внедренцах ты чинишь сбой старой системы за семь минут — пусть видят, что такое рука мастера.",
  "his fingers close the glitch as the consultant's phone films over his shoulder",
  None, "crowd"),
 ("A4_SH10", None, None,
  "a phone screen filming hands over a keyboard, the recording timer running, a note app open beside",
  "ECU", "eye", "static", "day", False, False,
  "они снимают твои руки на видео, и ты не сразу соображаешь, что это тоже документация.",
  "the recording timer climbs as the filmed hands work the keys"),
 ("A4_SH11", "BORIS_BASE", "it_room",
  "Boris pauses mid-typing, the thought landing, his eyes going to the audit probe on the rack",
  "CU", "eye", "push_in", "day", False, False,
  "миграцию нельзя заблокировать человеком, если человека можно записать на видео.",
  "his typing stalls as his eyes travel to the blinking probe"),
 ("A4_SH12", ("GENA_BASE", "BORIS_BASE"), "pelmennaya",
  "Gena and Boris at a high round table over dumplings, steam on the window, Gena talking sense with a fork",
  "MS", "eye", "static", "evening", False, False,
  "в пельменной гена говорит с вилкой в руке — «боря, ты воюешь с прогрессом методом очередей».",
  "his fork conducts the sense over the steaming plates"),
 ("A4_SH13", "GENA_BASE", "pelmennaya",
  "Gena leans in, glasses fogged from the dumpling steam, delivering the line that will stay",
  "CU", "eye", "static", "evening", False, False,
  "«ты не незаменимый, боря, ты — незаменённый, пока» — и пар от пельменей не смягчает формулировку.",
  "his fogged glasses hold steady as the line crosses the little table"),
 ("A4_SH14", "BORIS_BASE", "pelmennaya",
  "Boris looks at his dumplings, the comeback dying unspoken, steam rising between him and the window lights",
  "MCU", "eye", "static", "evening", False, False,
  "ответ у тебя был заготовлен, но между «был» и «есть» помещается вся эта весна.",
  "the ready comeback dies as his fork stirs the cooling plate"),
 ("A4_SH15", None, "street_office",
  "the office at night from the street, the vendor floor lit bright, his small IT window dark beside it",
  "EWS", "low", "static", "night", True, False,
  "этаж внедренцев светится до одиннадцати, и его свет ложится на твоё тёмное окно.",
  "the bright vendor floor glows over the one dark window beside it",
  None, "crowd"),
 ("A4_SH16", None, None,
  "the Gantt chart updated: shifted bars pulled back left, a new resource line added at the top",
  "ECU", "eye", "static", "day", False, False,
  "к июлю график выравнивается — вендор просто закладывает тебя в него как погодный риск.",
  "the pulled-back bars settle level under the new top resource line"),
]

A5 = [
 ("A5_SH01", None, "warehouse_trade",
  "warehouse scanners with split screens: old system green on the left, new system teal on the right, workers comparing",
  "WS", "eye", "static", "day", False, False,
  "с августа склад живёт на двух системах сразу — старая слева, новая справа, зелёное против бирюзового.",
  "the split screens flicker in the cradles as workers glance between the halves",
  None, "crowd"),
 ("A5_SH02", "BORIS_BASE", "it_room",
  "Boris keeps a gleeful bug journal of the new system, a printed list with checkmarks, marker in his teeth",
  "MS", "eye", "static", "day", False, False,
  "ты ведёшь журнал багов новой системы с удовольствием коллекционера — тридцать одна позиция за месяц.",
  "his marker ticks another line as the gleeful list grows down the page"),
 ("A5_SH03", None, None,
  "the bug list in close-up: neat numbered entries, several already struck through by someone else's pen",
  "ECU", "eye", "static", "day", False, False,
  "правда, половину твоих багов вендор закрывает быстрее, чем ты успеваешь их смаковать.",
  "the other pen's strikethroughs cross entry after entry down the list"),
 ("A5_SH04", "KATYA_BASE", "openspace_trade",
  "Katya conducts a training for storekeepers on the new system, confident at the projector, the room actually listening",
  "WS", "eye", "static", "day", False, False,
  "катя ведёт обучение по новой системе, и склад слушает её так, как когда-то слушал тебя.",
  "her pointer sweeps the projected screen as the rows of caps nod along",
  None, "crowd"),
 ("A5_SH05", "BORIS_BASE", "openspace_trade",
  "Boris watches the training from the back doorway, an emotion he refuses to name working his face",
  "MCU", "eye", "static", "day", False, False,
  "ты стоишь в дверях её тренинга и не заходишь — у чувства, которое тебя держит, нет удобного имени.",
  "his hand grips the door frame as the unnamed feeling works his jaw"),
 ("A5_SH06", ("KATYA_BASE", "BORIS_BASE"), "corridor_it",
  "Katya catches Boris in the corridor, honest and direct, offering him the co-lead of the parallel run",
  "WS", "eye", "static", "day", False, False,
  "после тренинга катя догоняет тебя и предлагает вести параллельный запуск вдвоём, официально.",
  "she plants herself in his path with the offer held out like a hand"),
 ("A5_SH07", "BORIS_BASE", "corridor_it",
  "Boris pats her shoulder with granddad condescension and declines, the mask kind, the fear underneath",
  "MCU", "eye", "static", "day", False, False,
  "ты отвечаешь «учись, катюша, у тебя получается» — и это звучит щедро, а работает как дверь.",
  "his condescending pat lands soft as the kind mask holds the door shut"),
 ("A5_SH08", "KATYA_BASE", "corridor_it",
  "Katya watches him go, disappointment hardening into resolve, the pencil going into the bun like a decision",
  "CU", "eye", "static", "day", False, True,
  "катя смотрит тебе вслед и перестаёт стучаться — с этого дня она растёт мимо тебя.",
  "the pencil slides into the bun with the click of a decision made"),
 ("A5_SH09", None, None,
  "the old tower and a new virtualisation node side by side in the rack, cable tags handwritten versus printed",
  "ECU", "low", "static", "day", False, False,
  "в стойке теперь два поколения — твои рукописные ярлыки против их печатных.",
  "the handwritten tags stir beside the printed ones in the cold aisle flow",
  "SERVER"),
 ("A5_SH10", "BORIS_BASE", "warehouse_trade",
  "Boris helps an old storekeeper who still calls him first, fixing a legacy terminal, a small island of the old world",
  "MS", "eye", "static", "day", False, False,
  "старые кладовщики по привычке зовут тебя, и эти вызовы ты носишь, как ордена.",
  "his hands revive the legacy terminal as the old storekeeper hovers grateful",
  None, "crowd"),
 ("A5_SH11", None, None,
  "a ticket dashboard where legacy-system requests thin week by week on a falling graph",
  "ECU", "eye", "static", "day", False, False,
  "заявок на старую систему всё меньше — график тает на четверть в месяц.",
  "the request graph steps down week by week on the glowing dashboard"),
 ("A5_SH12", "ARTUR_BASE", "cio_office",
  "Artur updates the migration status at his whiteboard, wiping one more block from the legacy column",
  "MS", "eye", "static", "evening", False, False,
  "артур стирает со своей доски ещё один блок старой системы — методично, без злорадства.",
  "the eraser lifts another block off the legacy column in one clean pass"),
 ("A5_SH13", "BORIS_BASE", "boris_flat",
  "Boris at home opens the vendor documentation portal for the first time, reading glasses on, pride swallowed for an hour",
  "MCU", "eye", "static", "night", False, False,
  "ночью ты впервые открываешь документацию новой системы — просто посмотреть, что там у них.",
  "the portal loads under his lowered glasses as pride sits swallowed"),
 ("A5_SH14", None, "boris_flat",
  "the documentation portal on screen: thousands of tidy pages, search, versions, examples, everything he refused to write",
  "ECU", "eye", "static", "night", False, False,
  "у них там четыре тысячи страниц, поиск и примеры — всё то, чем ты гордился не быть.",
  "the page counter and tidy sidebar hold the screen as the cursor hovers"),
 ("A5_SH15", "BORIS_BASE", "boris_flat",
  "Boris closes the laptop slowly, the tea cold, the flat very quiet around a man beginning to see",
  "CU", "eye", "push_in", "night", False, True,
  "ты закрываешь ноутбук медленно, и в тишине квартиры впервые слышно, как тикает твой собственный план.",
  "the laptop lid sinks under his hand as the quiet flat settles around him"),
 ("A5_SH16", None, "openspace_trade",
  "the office at dusk, the vendor corner celebrating a milestone with pizza boxes, teal balloons on a monitor",
  "WS", "eye", "static", "evening", True, False,
  "у внедренцев пицца и шарики — «этап два закрыт досрочно», и это уже не смешно.",
  "teal balloons sway over the pizza boxes in the milestone corner",
  None, "crowd"),
]

if __name__ == "__main__":
    seed_act("A3", PAL_A3, A3)
    seed_act("A4", PAL_A4, A4)
    seed_act("A5", PAL_A5, A5)
