# -*- coding: utf-8 -*-
"""monotown atmosphere breathers: 2 per act (A1..A11), id_region='a', unique per-act schemes."""
from _monotown_engine import seed_act

PALS = {
 "A1": "warm plant-town light, brick and steel tones, morning smoke gold",
 "A2": "receiver grey, cold suit tones, flat ledger light",
 "A3": "farewell industrial light, stamped paper tones, cold shop haze",
 "A4": "fading town colours, papered glass grey, thin daylight",
 "A5": "quiet morning blue, unrung silence tones, pale window light",
 "A6": "crossroad amber, evening kitchen warm, cold offer paper white",
 "A7": "auction cold light, lot-number yellow, loading dust",
 "A8": "resolve lamp glow, deep window night, iron and amber",
 "A9": "last shift gold, long slanting light, iron dust motes",
 "A10": "grey thaw tones, garage lantern warm, wet concrete",
 "A11": "spark morning light, chalk white accents, fog silver and gold",
}

ATMO = {
 "A1": [
  ("A1_SZ01", None, "shop_floor",
   "iron dust turning gold inside one skylight beam over a lathe bed, the motes climbing and falling",
   "ECU", "low", "tilt_up", "morning", True, False,
   "по утрам цех стоит в косых столбах света, и железная пыль в них ходит золотом.",
   "gold dust turns slow in the climbing skylight shafts"),
  ("A1_SZ02", None, "town_square",
   "sunday on the square: ice-cream kiosk queue, pigeons at the memorial, accordion faint from the house of culture",
   "EWS", "eye", "static", "day", True, False,
   "по воскресеньям площадь живёт мороженым и гармошкой из дк — городу есть чем дышать после смены.",
   "the kiosk queue shuffles as pigeons work the memorial steps",
   None, "crowd"),
 ],
 "A2": [
  ("A2_SZ01", None, "plant_gate_m",
   "the checkpoint hall with the receiver's pilot-case parked alone by the wall, its handle up like a periscope",
   "WS", "eye", "static", "day", True, False,
   "портфель на колёсиках паркуется у проходной, как машина директора, — город выучил его первым.",
   "the parked case stands its handle up against the checkpoint wall"),
  ("A2_SZ02", None, "plant_yard_m",
   "weeds breaking the yard concrete along the rail siding, one rail shining, one rusting",
   "ECU", "high", "static", "day", True, False,
   "на подъездных путях один рельс блестит, второй ржавеет — по двору уже видно расписание будущего.",
   "grass nods between the shining rail and the rusting one"),
 ],
 "A3": [
  ("A3_SZ01", None, "plant_gate_m",
   "the shift board photographed at dusk: half the hooks bare, the remaining tags clustered to one side",
   "ECU", "eye", "push_in", "evening", True, False,
   "номерки на доске сбились в одну сторону, как птицы перед отлётом.",
   "the clustered tags sway together over the field of bare hooks"),
  ("A3_SZ02", None, "town_street",
   "a farewell gathering spilling from a cafe onto the evening street, toasts through the window, coats on chairs",
   "WS", "eye", "static", "evening", True, False,
   "в кафе на главной гуляют проводы — теперь это главный жанр городских праздников.",
   "toast silhouettes lift beyond the window as coats hold the chairs",
   None, "crowd"),
 ],
 "A4": [
  ("A4_SZ01", None, "five_story",
   "a papered ground-floor window with a child's drawing taped facing out: a sun over a factory with smoke",
   "ECU", "eye", "static", "day", True, False,
   "в заклеенной витрине кто-то повесил детский рисунок наружу — солнце над заводом с дымом.",
   "the taped drawing curls at one corner behind the dusty glass"),
  ("A4_SZ02", None, "bus_station_m",
   "the bus station at dawn, one bus warming up, breath fog around the queue of work bags",
   "WS", "eye", "static", "morning", True, False,
   "утренний рейс в область уходит полным — город ездит на работу к чужим гудкам.",
   "breath fog drifts along the queue as the one bus warms",
   None, "crowd"),
 ],
 "A5": [
  ("A5_SZ01", None, "horn_room",
   "the horn cabin locked, the order on the door faded by sun, dust settling on the high window",
   "INSERT", "eye", "static", "day", True, False,
   "будка гудка стоит запертой, и приказ на двери выцветает быстрее, чем привычка к семи тридцати.",
   "sun-fade creeps across the pinned order on the locked door"),
  ("A5_SZ02", None, "five_story",
   "alarm clocks visible on windowsills up the block wall, three different models in three windows",
   "ECU", "low", "tilt_up", "morning", True, False,
   "на подоконниках пятиэтажек появляются будильники — город раздал гудок по квартирам.",
   "the tilt climbs the wall past the three sill-top alarm clocks"),
 ],
 "A6": [
  ("A6_SZ01", None, "matvey_kitchen",
   "the offer envelope behind the radio, its corner catching lamplight, the radio dial glowing",
   "ECU", "eye", "static", "night", True, False,
   "конверт из области живёт за радио и напоминает о себе углом — решения тоже требуют ухода.",
   "the envelope corner glows beside the murmuring dial"),
  ("A6_SZ02", None, "overlook",
   "november wind combing the dry grass on the rise, the two-plank bench empty, the town smoking thin below",
   "WS", "eye", "static", "day", True, False,
   "ветер на пригорке чешет сухую траву, и лавка из двух досок пустует до выходных.",
   "dry grass combs flat in waves past the empty plank bench"),
 ],
 "A7": [
  ("A7_SZ01", None, "shop_floor",
   "yellow auction tags on a row of machines, one tag torn off leaving a zip-tie stub",
   "ECU", "eye", "static", "day", True, False,
   "жёлтые бирки висят на станках, и одна уже сорвана — кто-то не выдержал канцелярии.",
   "the zip-tie stub sways where the torn tag hung"),
  ("A7_SZ02", None, "garage_coop",
   "the garage row from above at dusk: one glowing door, tyre tracks converging to it through slush",
   "EWS", "high", "static", "evening", True, False,
   "к светящейся секции сходятся следы через весь кооператив — гараж петровича стал адресом.",
   "converging tracks darken the slush toward the one lit door"),
 ],
 "A8": [
  ("A8_SZ01", None, "shop_floor",
   "the stop-date notice on the board with a work glove hung over the board corner, someone's quiet comment",
   "INSERT", "eye", "static", "day", True, False,
   "на угол доски с датой остановки кто-то повесил рабочую рукавицу — комментарий без слов.",
   "the hung glove sways its wordless comment over the notice"),
  ("A8_SZ02", None, "town_street",
   "spring dusk on the main street, the pharmacy cross and the garage-row glow now the two brightest lights",
   "WS", "eye", "static", "evening", True, False,
   "вечером в городе два главных огня — аптечный крест и гаражный ряд.",
   "the two glows hold the dusk street between them",
   None, "crowd"),
 ],
 "A9": [
  ("A9_SZ01", None, "shop_floor",
   "the empty foreman desk after the last shift: the journal squared, a pencil across it, the chair pushed in",
   "INSERT", "eye", "static", "evening", True, False,
   "стол мастера остаётся прибранным — журнал по центру, карандаш поперёк, стул задвинут.",
   "the pencil rests its diagonal on the squared journal"),
  ("A9_SZ02", None, "town_square",
   "the square at dusk on shutdown day, people standing in twos and threes, talking low, facing the plant",
   "WS", "eye", "static", "evening", True, False,
   "вечером на площади стоят по двое, по трое, лицом к заводу — так стоят у больничных окон.",
   "the low-talking clusters hold their plant-ward faces in the dusk",
   None, "crowd"),
 ],
 "A10": [
  ("A10_SZ01", None, "garage_coop",
   "the shared water tap at the garage row wearing a new insulation coat, a path shovelled to it",
   "ECU", "eye", "static", "day", True, False,
   "общий кран в кооперативе одевают в утеплитель — за инфраструктурой артели следят.",
   "meltwater beads off the new insulation coat at the tap"),
  ("A10_SZ02", None, "town_street",
   "a papered shopfront reopening as a tool-and-fastener shop, a hand-painted sign going up",
   "WS", "eye", "static", "day", True, False,
   "одна из заклеенных витрин открывается обратно — метизы и инструмент, спрос диктуют гаражи.",
   "the hand-painted sign rises over the unpapered glass",
   None, "crowd"),
 ],
 "A11": [
  ("A11_SZ01", None, "garage_coop",
   "the artel's chalk board rain-washed and rewritten, the new week's orders in the same firm hand",
   "INSERT", "eye", "static", "morning", True, False,
   "дождь смывает меловую доску, и её переписывают тем же почерком — расписание живучее мела.",
   "fresh chalk lines dry over the rain-ghosted old ones"),
  ("A11_SZ02", None, "overlook",
   "summer morning from the rise: the dark plant, the working garage row, kids cycling the main street",
   "EWS", "high", "static", "morning", True, False,
   "летним утром город виден весь — тёмный завод, живые гаражи и велосипеды на главной.",
   "cyclists thread the main street between the hulk and the working row",
   None, "crowd"),
 ],
}

if __name__ == "__main__":
    for act, shots in ATMO.items():
        seed_act(act, PALS[act], shots, id_region="a")
