# -*- coding: utf-8 -*-
"""preretire shots: A0 (packing line crisis), A1 (the hands), A2 (digital transformation)."""
from _preretire_engine import seed_act

PAL_A0 = "flour haze in morning light, warm conveyor glow, steel blue shadows"
PAL_A1 = "warm plant daylight, bread and steel tones, soft flour dust"
PAL_A2 = "cool digital white, tablet-screen accents, flat even light"

A0 = [
 ("A0_SH01", None, "plant_floor",
  "a bread-plant packing line mid-fault, torn film curling off the wrapping machine, loaves backing up along the conveyor",
  "WS", "eye", "static", "morning", False, False,
  "за час до отгрузки упаковочный автомат начинает рвать плёнку на каждой третьей буханке.",
  "torn film curls off the roller while loaves crowd slowly up the conveyor line"),
 ("A0_SH02", None, "plant_floor",
  "a reject tray filling with badly wrapped loaves, film tails trailing, a red fault lamp reflected in the steel",
  "ECU", "high", "static", "morning", False, False,
  "брак сыплется в лоток, и каждая буханка в нём — минус к премии всей смены.",
  "another botched loaf drops onto the pile as the red lamp blinks in the steel"),
 ("A0_SH03", "STEPAN_BASE", "plant_floor",
  "Stepan walks up the line unhurried through the flour haze, wiping his hands on a rag, workers stepping back to give him the machine",
  "MS", "eye", "track", "morning", False, False,
  "смена расступается, потому что за тридцать восемь лет здесь выучили — сейчас будет тихо.",
  "he walks the line at an even pace, folding the rag away as the others step back",
  None, "crowd"),
 ("A0_SH04", "STEPAN_BASE", "plant_floor",
  "Stepan lays his whole palm flat on the machine casing and closes his eyes, his head tilted like a doctor at a chest",
  "CU", "eye", "static", "morning", False, True,
  "ты кладёшь ладонь на станину и слушаешь — машины врут глазам, но не рукам.",
  "his palm settles flat on the casing and his eyes close as his head tilts"),
 ("A0_SH05", "STEPAN_BASE", None,
  "his own hands sliding a thin steel feeler blade into a gap at an eccentric bearing, the fan of blades splayed in his other hand",
  "POV", "pov", "static", "morning", False, False,
  "щуп на две сотки проходит там, где должен стоять насмерть, — подшипник эксцентрика просел.",
  "the thin blade slides into the gap and the fan of spare blades tilts in the other hand",
  "GAUGE"),
 ("A0_SH06", None, None,
  "the feeler gauge fan lying open on the machine casing beside a fresh bearing in oiled paper",
  "INSERT", "eye", "static", "morning", False, False,
  "диагноз занимает минуту, замена — двенадцать, и это твой личный норматив.",
  "the oiled paper unwraps a finger's width around the waiting bearing",
  "GAUGE"),
 ("A0_SH07", "STEPAN_BASE", "plant_floor",
  "Stepan tightens the last bolt with a short torque wrench, his quartz watch pushed up his forearm, grease to the wrist",
  "MS", "eye", "static", "morning", False, False,
  "ты ставишь подшипник с третьего движения, потому что первые два ушли на молодость.",
  "the wrench pulls the last bolt home in one short controlled arc",
  "TOOLBOX"),
 ("A0_SH08", None, "plant_floor",
  "the wrapping machine running clean, film sealing loaf after loaf in a steady rhythm, the red lamp dark",
  "WS", "eye", "static", "morning", False, False,
  "линия идёт, плёнка ложится ровно, и отгрузка уходит вовремя, как уходила всегда.",
  "film seals loaf after loaf in an even rhythm as the conveyor settles to its pace"),
 ("A0_SH09", "DENIS_BASE", "plant_floor",
  "Denis watches from the gantry rail with open admiration, his trainee badge swinging as he leans over",
  "MCU", "eye", "static", "morning", False, False,
  "денис смотрит с мостика так, будто ты только что показал фокус, а ты показал ремесло.",
  "the young man leans over the rail and his badge swings out on its lanyard"),
 ("A0_SH10", ("STEPAN_BASE", "DENIS_BASE"), "plant_floor",
  "Stepan hands Denis the used feeler blade to feel the worn spot himself, guiding the young hand to the bearing seat",
  "MS", "eye", "static", "morning", False, False,
  "ты даёшь денису пощупать выработку самому — этому не учат по планшету.",
  "his big hand guides the younger one to the bearing seat with the blade",
  "GAUGE"),
 ("A0_SH11", None, "plant_floor",
  "a wall-mounted shift clock over the line, flour dust drifting through its light, the minute hand settling on the hour",
  "ECU", "low", "static", "morning", False, False,
  "до конца смены ещё шесть часов, и они пройдут так же ровно, как эта плёнка.",
  "flour dust drifts through the clock light as the minute hand settles"),
 ("A0_SH12", "STEPAN_BASE", "plant_locker",
  "Stepan washes his hands at the locker-room sink methodically to the elbow, the rag over his shoulder, steam on the mirror",
  "MS", "eye", "static", "day", False, False,
  "руки ты моешь до локтя дважды — привычка человека, который здоровается с хлебом.",
  "lather runs off his forearms as the methodical washing works to the elbows"),
 ("A0_SH13", "STEPAN_BASE", "plant_locker",
  "Stepan's weathered face in the locker mirror, calm and sure, the grey crew cut beaded with wash water",
  "CU", "eye", "push_in", "day", False, True,
  "тебе пятьдесят восемь, до пенсии двадцать четыре месяца, и завод у тебя в ладонях.",
  "his steady eyes hold the mirror as water beads slide down his temple"),
 ("A0_SH14", "STEPAN_BASE", "plant_gate",
  "Stepan from behind walking out through the checkpoint turnstile, nodding to the guard booth, evening light down the fence line",
  "BACK", "eye", "static", "evening", False, False,
  "останься до конца и подпишись — я расскажу, как завод, который ты слышишь ладонью, перестанет слышать тебя.",
  "he pushes the turnstile bar and lifts two fingers to the guard booth in passing"),
]

A1 = [
 ("A1_SH01", None, "street_plant",
  "the industrial street at dawn, the long plant fence with poplars, a bread kiosk opening its shutter, pipes crossing overhead",
  "EWS", "eye", "static", "morning", True, False,
  "ты пришёл на этот завод в двадцать лет, и с тех пор город вокруг него перестроили дважды.",
  "the kiosk shutter rolls up slowly as dawn light climbs the plant fence"),
 ("A1_SH02", "STEPAN_BASE", "plant_gate",
  "Stepan presses his pass to the checkpoint reader with the ease of ritual, the honour board with his photo behind him",
  "MS", "eye", "static", "morning", False, False,
  "проходная знает твой шаг — тридцать восемь лет по одному звонку и одному маршруту.",
  "his pass taps the reader and the turnstile gives way under his practiced push"),
 ("A1_SH03", None, "plant_gate",
  "the honour board behind glass, rows of portraits, one photo of a younger crew-cut man among them",
  "ECU", "eye", "static", "morning", False, False,
  "на доске почёта висит твоя фотография, где ёжик ещё тёмный.",
  "reflected morning light slides across the glass over the rows of portraits"),
 ("A1_SH04", "STEPAN_BASE", "plant_floor",
  "Stepan walks his line touching machines in passing the way farmers touch fences, each touch a half-second check",
  "WS", "eye", "track", "day", False, False,
  "обход у тебя начинается с ладоней — по касанию на машину, и цех прочитан.",
  "his hand brushes each casing in passing, pausing half a beat on the third"),
 ("A1_SH05", "STEPAN_BASE", None,
  "his own hands laying tools into the steel box by their shadow outlines, each tool finding its painted silhouette",
  "POV", "pov", "static", "day", False, False,
  "инструмент у тебя разложен по теням — глядя в ящик, можно проводить инвентаризацию.",
  "each tool settles into its painted silhouette as the tray folds down",
  "TOOLBOX"),
 ("A1_SH06", ("STEPAN_BASE", "DENIS_BASE"), "plant_floor",
  "Denis holds a tablet checklist while Stepan corrects his grip on a wrench, both bent over an open gearbox",
  "MS", "eye", "static", "day", False, False,
  "дениса тебе дали в мае, и ты учишь его тому, что в чек-листах не помещается.",
  "his hand adjusts the young grip on the wrench and pats it once approvingly"),
 ("A1_SH07", "DENIS_BASE", "plant_floor",
  "Denis listens with the cap turned backwards, repeating a motion in the air with his hand, memorising by muscle",
  "CU", "eye", "static", "day", False, False,
  "он переспрашивает по три раза, и это правильные три раза — так спрашивают те, кто останется.",
  "his hand repeats the shown motion in the air twice, slower the second time"),
 ("A1_SH08", "STEPAN_BASE", "flat_kitchen",
  "Stepan eats supper alone at the oilcloth table, the radio on, a second chair pushed in square and unused",
  "WS", "eye", "static", "evening", False, False,
  "дома тихо — восемь лет как ты вдовец, и радио на подоконнике работает за двоих.",
  "steam rises off the plate as the radio dial glows and the second chair stands square"),
 ("A1_SH09", None, None,
  "framed honour certificates on the living-room wall, gold lettering catching lamplight, arranged level to a millimetre",
  "ECU", "eye", "pan_right", "evening", False, False,
  "грамоты на стене висят по уровню — двенадцать штук, по одной на каждую пятилетку с гаком.",
  "lamplight glides along the gold lettering of the level-hung frames",
  "CERTS"),
 ("A1_SH10", "STEPAN_BASE", "flat_kitchen",
  "Stepan talks on speakerphone with the gifted smartphone lying on the table, addressing it from a distance like a microphone",
  "MCU", "eye", "static", "evening", False, False,
  "алёна звонит по воскресеньям, и ты разговариваешь с телефоном, как с трибуной, — издалека.",
  "he leans toward the lying phone to answer and back again after each phrase",
  "SMARTPHONE"),
 ("A1_SH11", "ALYONA_BASE", None,
  "Alyona on a video call screen in her kitchen far away, the chunky knitted scarf on a hook behind her",
  "CU", "eye", "static", "evening", False, False,
  "дочь живёт в двух днях поезда и каждый раз зовёт к себе, и ты каждый раз шутишь в ответ.",
  "her face on the call screen leans closer as the connection sharpens"),
 ("A1_SH12", None, None,
  "an old quartz watch on a stretched steel bracelet being wound and checked against a wall clock, thick fingers precise",
  "INSERT", "eye", "static", "evening", False, False,
  "часы у тебя кварцевые, но ты всё равно сверяешь их с заводскими — привычка точности.",
  "the thick fingers turn the watch to the light and match it against the wall clock",
  "WATCH"),
 ("A1_SH13", ("STEPAN_BASE", "MIKHALYCH_BASE"), "guard_booth",
  "Stepan and Mikhalych drink tea in the cramped guard booth, the kettle steaming, keys on the carabiner hung by the window",
  "MS", "eye", "static", "evening", False, False,
  "михалыч год как на пенсии, сторожит стоянку и уверяет, что высыпается впервые с юности.",
  "two mugs steam between them as the kettle clicks off in the cramped booth"),
 ("A1_SH14", "MIKHALYCH_BASE", "guard_booth",
  "Mikhalych over his half-moon glasses, wagging a rusk like a pointer, mid-friendly-lecture",
  "MCU", "eye", "static", "evening", False, False,
  "он машет сухарём и говорит — «два года дотяни, стёпа, и живи, как человек».",
  "the rusk wags in his hand like a conductor's baton over the tea"),
 ("A1_SH15", "STEPAN_BASE", "guard_booth",
  "Stepan laughs into his tea, waving the advice off, the watch bracelet glinting on his wrist",
  "CU", "eye", "static", "evening", False, False,
  "ты отмахиваешься — куда они денутся, машины без рук не живут.",
  "his laugh shakes the tea surface as his free hand waves the advice away"),
 ("A1_SH16", None, "plant_floor",
  "the packing floor at night shift change, machines idling warm, one work lamp left burning over the line",
  "WS", "eye", "static", "night", True, False,
  "цех на пересменке дышит тёплым хлебом, и это твой любимый час на заводе.",
  "the idling machines tick as they cool under the one burning work lamp"),
]

A2 = [
 ("A2_SH01", "GLEB_BASE", "plant_floor",
  "Gleb tours the packing floor with a tablet held up like a compass, his earpiece blinking, an entourage of clipboards behind",
  "WS", "eye", "track", "day", False, False,
  "новый директор по производству приходит в феврале — глеб, тридцать шесть, гарнитура в ухе.",
  "he sweeps the tablet across the line like a scanner as the entourage keeps pace",
  None, "crowd"),
 ("A2_SH02", None, None,
  "a vibration sensor puck being zip-tied to a machine casing, a QR label freshly stuck beside it",
  "ECU", "eye", "static", "day", False, False,
  "на станины клеят датчики вибрации с кьюар-кодами — «цифровой слух», как их называет глеб.",
  "the zip tie draws tight around the sensor puck as the label settles"),
 ("A2_SH03", "STEPAN_BASE", "plant_floor",
  "Stepan looks at a sensor puck stuck where his palm usually lands, his head tilted, amusement and distrust mixed",
  "MCU", "eye", "static", "day", False, False,
  "датчик приклеили ровно туда, куда ты кладёшь ладонь, и ты не знаешь, смеяться или ревновать.",
  "his head tilts at the sensor puck and one eyebrow climbs slowly"),
 ("A2_SH04", ("GLEB_BASE", "STEPAN_BASE"), "plant_floor",
  "Gleb shows Stepan a dashboard on the tablet, all green icons, while behind them a machine runs with a barely audible knock",
  "WS", "eye", "static", "day", False, False,
  "глеб показывает планшет — «всё зелёное», а за его спиной машина стучит на четверть сотки.",
  "the tablet turns toward the older man as the dashboard icons hold their green"),
 ("A2_SH05", "STEPAN_BASE", "plant_floor",
  "Stepan lays his palm on the machine behind Gleb's back and holds up two fingers a small gap apart",
  "MCU", "eye", "static", "day", False, True,
  "ты молча кладёшь ладонь и показываешь пальцами зазор — планшет узнает об этом через месяц.",
  "his two fingers open to a small precise gap as his palm rests on the casing"),
 ("A2_SH06", None, "plant_floor",
  "a printed transformation roadmap pinned on the shop noticeboard, arrows and quarters, the phrase about age structure in a box",
  "ECU", "eye", "static", "day", False, False,
  "на доске объявлений висит «дорожная карта», и в третьем квартале там стоит «омоложение возрастной структуры».",
  "the roadmap sheet lifts at one corner in the door draught and settles"),
 ("A2_SH07", ("STEPAN_BASE", "MIKHALYCH_BASE"), "guard_booth",
  "Mikhalych reads the photographed roadmap on Stepan's smartphone at arm's length, glasses up on his bald head",
  "OTS", "over", "static", "evening", False, False,
  "михалыч читает фразу вслух дважды и переводит — «стариков будут выдавливать по-хорошему».",
  "the smartphone turns at arm's length as he reads the boxed phrase twice",
  "SMARTPHONE"),
 ("A2_SH08", "STEPAN_BASE", "guard_booth",
  "Stepan waves it off but his hand finds the watch bracelet and turns it around his wrist twice",
  "MCU", "eye", "static", "evening", False, False,
  "ты отвечаешь «меня это не касается», и рука сама дважды проворачивает браслет часов.",
  "his hand turns the steel bracelet around his wrist twice while he talks",
  "WATCH"),
 ("A2_SH09", None, "plant_floor",
  "young technicians in new branded overalls photographing machine plates with phones, tablets in holsters",
  "WS", "eye", "static", "day", False, False,
  "в цех приходят «мультиспециалисты» — молодые, вежливые, с планшетами в кобурах.",
  "phones click along the line as the new overalls move machine to machine",
  None, "crowd"),
 ("A2_SH10", ("DENIS_BASE", "STEPAN_BASE"), "plant_floor",
  "Denis shows Stepan the new app where fault tickets are assigned, scrolling, Stepan's name appearing rarely",
  "MS", "eye", "static", "day", False, False,
  "заявки теперь раздаёт приложение, и твоя фамилия выпадает в нём всё реже.",
  "the young thumb scrolls the ticket list as both heads bend over the screen"),
 ("A2_SH11", "STEPAN_BASE", "plant_floor",
  "Stepan stands by his quiet section of line, arms crossed, watching a new technician wait for a sensor verdict",
  "CU", "eye", "static", "day", False, False,
  "молодой ждёт вердикта датчика тридцать долгих минут там, где твоей ладони хватило бы одной.",
  "his crossed arms tighten as the technician waits on the frozen dashboard"),
 ("A2_SH12", "GLEB_BASE", "plant_gate",
  "Gleb at the checkpoint talking into his earpiece, ticking something on the tablet, the honour board behind his shoulder",
  "MS", "eye", "static", "day", False, False,
  "глеб не злодей — он искренне верит, что завод это данные, а данные не стареют.",
  "his stylus ticks the tablet as he talks into the blinking earpiece"),
 ("A2_SH13", None, "plant_locker",
  "two lockers standing open and cleared in the locker row, name stickers peeled to pale rectangles",
  "ECU", "eye", "static", "day", False, False,
  "в раздевалке пустеют два шкафчика — токарь и электрик ушли «по собственному» до срока.",
  "the open locker doors sway a centimetre as the room door closes"),
 ("A2_SH14", "STEPAN_BASE", "flat_kitchen",
  "Stepan at his kitchen table counts months on his fingers under the radio, the calendar pinned by the window",
  "MCU", "eye", "static", "evening", False, False,
  "ты считаешь на пальцах — двадцать четыре месяца, сто четыре недели, дотянуть можно.",
  "his fingers fold one by one as his eyes hold the pinned calendar"),
 ("A2_SH15", "STEPAN_BASE", "flat_room",
  "Stepan straightens the certificate frames with one knuckle, an old soldier squaring his medals",
  "MS", "eye", "static", "evening", False, False,
  "перед сном ты подравниваешь грамоты костяшкой пальца — они висят ровно, но так спокойнее.",
  "his knuckle nudges each frame a hair's width along the level row",
  "CERTS"),
 ("A2_SH16", None, "street_plant",
  "the plant at night from the street, one office floor lit late over the dark shops, a banner being fixed to the fence",
  "EWS", "low", "static", "night", True, False,
  "над тёмными цехами допоздна горит один этаж — там пересчитывают людей в проценты.",
  "the office floor light holds over the dark shops as the banner ripples on the fence",
  None, "crowd"),
]

if __name__ == "__main__":
    seed_act("A0", PAL_A0, A0)
    seed_act("A1", PAL_A1, A1)
    seed_act("A2", PAL_A2, A2)
