# -*- coding: utf-8 -*-
"""Seed CH14 — Он хочет будущее, замуж, на Запад вместе (HEROINE_YOUNG + ANDREAS). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "he wants marriage and a future, dreaming aloud of crossing West together, hope shadowed by dread"
SHOTS = [
 ("CH14_SH01", ("HEROINE_YOUNG","ANDREAS"), "andreas_flat",
  "medium of Andreas taking her hands across the table, speaking of the future",
  "MS","eye","static","gdr_eve",False,False,
  "проходит полгода, и однажды вечером Андреас берёт тебя за руки и заговаривает о будущем."),
 ("CH14_SH02", "ANDREAS", "andreas_flat",
  "medium close-up of Andreas proposing simply and sincerely",
  "MCU","eye","static","gdr_eve",False,False,
  "выходи за меня, говорит он просто, я хочу состариться рядом именно с тобой, ни с кем больше."),
 ("CH14_SH03", "HEROINE_YOUNG", "andreas_flat",
  "close-up of her heart leaping and freezing at once",
  "CU","eye","static","gdr_eve",False,False,
  "сердце замирает, ты ждала этих слов всю жизнь, и одновременно тебя сковывает ледяной ужас."),
 ("CH14_SH04", ("HEROINE_YOUNG","ANDREAS"), "andreas_flat",
  "medium of him dreaming aloud of saving and crossing West",
  "MS","eye","static","gdr_eve",False,False,
  "он мечтает вслух, как накопит денег, как однажды вы вместе уйдёте на ту сторону, на Запад."),
 ("CH14_SH05", None, "the_wall",
  "wide of the grey wall under a pale sky, the forbidden other side beyond",
  "WS","eye","static","gdr_day",True,False,
  "он кивает в сторону стены и говорит, там будет наша свобода, наш дом, наши дети."),
 ("CH14_SH06", "HEROINE_YOUNG", "the_wall",
  "medium close-up of her torn between the child who wanted warmth and the beast afraid of a cage",
  "MCU","eye","static","gdr_day",False,True,
  "ты слушаешь, и в тебе бьются двое, девочка, мечтавшая о тепле, и зверь, что боится клетки."),
 ("CH14_SH07", "ANDREAS", "andreas_flat",
  "close-up of Andreas slipping a plain ring onto her finger",
  "CU","eye","static","gdr_eve",False,False,
  "он надевает тебе на палец простое колечко, и впервые за всё время ты плачешь от счастья."),
 ("CH14_SH08", "HEROINE_YOUNG", "andreas_flat",
  "medium close-up of the familiar panic creeping in that night",
  "MCU","eye","static","night",False,False,
  "но той же ночью к горлу подкатывает знакомая паника, навсегда, один, на всю долгую жизнь."),
 ("CH14_SH09", None, "andreas_flat",
  "extreme close-up of the spare door key he presses into her palm",
  "ECU","top_down","static","gdr_eve",True,True,
  "он даёт тебе ключ от своей квартиры, теперь это и твой дом тоже, говорит он совсем тихо."),
 ("CH14_SH10", "HEROINE_YOUNG", "andreas_flat",
  "close-up of her clutching the key, unsure",
  "CU","eye","static","gdr_eve",False,False,
  "ты сжимаешь этот ключ в кулаке и не понимаешь, что это, спасение твоё или ловушка."),
 ("CH14_SH11", None, "andreas_flat",
  "wide B-roll of the warm flat, the ring on the sill, silent",
  "WS","eye","static","gdr_eve",True,False,""),
]
if __name__ == "__main__":
    seed_act(14, "warm_home", MOOD, "static", "CH14 He wants a future", SHOTS)
