# -*- coding: utf-8 -*-
"""Seed CH08 — Рождение дочери, первый ужас тела (2nd person). Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "warm but anxious domestic light, the chill of a changing body"
SHOTS = [
 ("CH08_SH01", None, "maternity",
  "wide establishing of a modern maternity ward, a bassinet by a bright window, soft daylight",
  "WS","high","push_in","warm_day",True,False,
  "ты рожаешь дочь."),
 ("CH08_SH02", "HEROINE_YOUNG", "maternity",
  "medium shot of the young mother holding her newborn but already anxious about herself",
  "MS","eye","static","warm_day",False,False,
  "но первое, о чём ты думаешь в роддоме, не о ней, а о себе."),
 ("CH08_SH03", "HEROINE_YOUNG", "bathroom",
  "extreme close-up of the mother examining her changed postpartum body in the mirror, horrified",
  "ECU","eye","static","warm_day",False,True,
  "тело предало, живот, растяжки, и ты в ужасе."),
 ("CH08_SH04", None, "family",
  "extreme close-up of the newborn daughter sleeping in her crib",
  "ECU","top_down","static","warm_day",True,False,
  "дочка спит, а ты не можешь оторваться от зеркала."),
 ("CH08_SH05", "HEROINE_YOUNG", "family",
  "medium shot of the mother exercising and dieting hard right after birth, driving herself",
  "MS","eye","static","warm_day",False,False,
  "ты гонишь себя до изнеможения, лишь бы вернуть фигуру, лишь бы он не разлюбил."),
 ("CH08_SH06", ("HUSBAND","HEROINE_YOUNG"), "family",
  "the husband on the left letting his appraising eye run over the wife on the right",
  "MS","eye","static","warm_day",False,False,
  "ты ловишь его оценивающий взгляд и худеешь ещё."),
 ("CH08_SH07", "HEROINE_YOUNG", "family",
  "close-up of the mother looking at her baby daughter, already appraising her looks",
  "CU","eye","static","warm_day",False,False,
  "и на дочь ты уже смотришь оценивающе, красивая ли."),
 ("CH08_SH08", None, "family",
  "extreme close-up of the baby daughter's tiny face",
  "ECU","top_down","static","warm_day",True,False,
  "будет ли она красивой, вот что тебя тревожит больше всего."),
 ("CH08_SH09", "HEROINE_YOUNG", "family",
  "medium close-up of the mother's determined face",
  "MCU","low","static","warm_day",False,False,
  "моя дочь будет идеальной, клянёшься ты себе."),
 ("CH08_SH10", None, "family",
  "wide shot of a warm family scene with a cold undertone, mother apart by a mirror",
  "WS","eye","static","warm_day",True,False,
  "семья, ребёнок, муж, а ты всё время одним глазом в зеркале."),
 ("CH08_SH11", "HEROINE_YOUNG", "bathroom",
  "close-up of the mother back at the mirror, figure restored but fear lingering",
  "CU","eye","static","warm_day",False,False,
  "красота вернулась, но страх уже никуда не уходит."),
 ("CH08_SH12", None, "park",
  "wide B-roll of a summer city park, leafy trees, a quiet pond, marking time passing",
  "WS","high","static","warm_day",True,False,""),
]
if __name__ == "__main__":
    seed_act(8, "warm_home", MOOD, "static", "CH08 Daughter born", SHOTS)
