# -*- coding: utf-8 -*-
"""Seed CH32 — Попытка сблизиться, разучилась (HEROINE_MID). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "a late attempt to let someone in, but she has forgotten how, cold lonely night"
SHOTS = [
 ("CH32_SH01", "HEROINE_MID", "cafe_west",
  "medium of the heroine trying to meet someone for real, not for a night",
  "MS","eye","static","night",False,False,
  "ты пытаешься измениться, познакомиться по-настоящему, не ради ночи, а чтобы рядом был кто-то."),
 ("CH32_SH02", None, "cafe_west",
  "close-up of a gentle older widower, seen mostly from behind, no lust in his look",
  "CU","eye","static","night",True,False,
  "находится спокойный вдовец, добрый, одинокий, он смотрит на тебя без всякой похоти."),
 ("CH32_SH03", "HEROINE_MID", "cafe_west",
  "medium close-up of her lost without the game of desire",
  "MCU","eye","static","night",False,False,
  "и ты теряешься, ведь без игры в желание ты не знаешь, о чём с мужчиной вообще говорить."),
 ("CH32_SH04", "HEROINE_MID", "her_room",
  "close-up of the inner wall rising at real closeness",
  "CU","eye","static","night",False,False,
  "стоит ему приблизиться по-человечески, и в тебе снова поднимается та самая глухая стена."),
 ("CH32_SH05", "HEROINE_MID", "cafe_west",
  "medium close-up of her fear of steady warmth",
  "MCU","eye","static","night",False,False,
  "ты привыкла к вспышкам, а ровное тепло пугает тебя, как пугало всегда, всю твою жизнь."),
 ("CH32_SH06", None, "cafe_west",
  "wide of him inviting her for a simple walk, her pulling back",
  "WS","eye","static","night",True,False,
  "он зовёт тебя просто погулять, без всего, а ты находишь повод не прийти."),
 ("CH32_SH07", "HEROINE_MID", "her_room",
  "close-up of the atrophied ability to let anyone in",
  "CU","eye","static","night",False,True,
  "ты совсем разучилась впускать, эта мышца, которой не пользуются полвека, давно атрофировалась."),
 ("CH32_SH08", "HEROINE_MID", "her_room",
  "medium close-up of the widower leaving for someone who can be present",
  "MCU","eye","static","night",False,False,
  "добрый вдовец уходит к той, что умеет быть рядом, а ты снова остаёшься совсем одна."),
 ("CH32_SH09", None, "her_room",
  "extreme close-up of Andreas's key",
  "ECU","top_down","static","night",True,False,
  "ты достаёшь ключ Андреаса и понимаешь, что и его дверь ты закрыла этой же самой стеной."),
 ("CH32_SH10", "HEROINE_MID", "her_room",
  "close-up of the truth that she drove them all away",
  "CU","eye","static","night",False,True,
  "не мужчины уходили от тебя, ты сама гнала каждого, кто подходил слишком близко."),
 ("CH32_SH11", None, "cafe_west",
  "wide B-roll of an empty night cafe, silent",
  "WS","eye","static","night",True,False,""),
]
if __name__ == "__main__":
    seed_act(32, "cold_blue", MOOD, "static", "CH32 Try to connect", SHOTS)
