# -*- coding: utf-8 -*-
"""Seed CH09 — Завод и общежитие, много мужчин (HEROINE_YOUNG). Non-explicit. Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "drab GDR working life, factory floor and dormitory, a parade of interchangeable men, grey routine"
SHOTS = [
 ("CH09_SH01", "HEROINE_YOUNG", "factory",
  "medium of the heroine arriving at a grey state factory in overalls",
  "MS","eye","static","gdr_day",False,False,
  "ты идёшь работать на завод, как все вокруг, серые цеха, гудки, бесконечный сменный график."),
 ("CH09_SH02", None, "factory",
  "wide of a socialist factory floor, machines and propaganda banners",
  "WS","eye","static","gdr_day",True,False,
  "но и здесь ты звезда, мастера и инженеры наперебой ищут повод заговорить с тобой."),
 ("CH09_SH03", "HEROINE_YOUNG", "factory",
  "medium close-up of her flirting between the machines",
  "MCU","eye","static","gdr_day",False,False,
  "ты заводишь романы прямо в цеху, женатый бригадир, молодой инженер, какая, в сущности, разница."),
 ("CH09_SH04", None, "dormitory",
  "close-up of a spartan dormitory room, a narrow iron bed",
  "CU","eye","static","gdr_eve",True,False,
  "живёшь в общежитии, и по твоему коридору мужчины ходят чаще, чем через проходную завода."),
 ("CH09_SH05", "HEROINE_YOUNG", "dormitory",
  "medium of the heroine indifferent to who they are",
  "MS","eye","static","gdr_eve",False,False,
  "тебе всё равно, женат он или нет, есть ли у него другая, тебе нужен только новый приход."),
 ("CH09_SH06", None, "dormitory",
  "extreme close-up of an empty narrow bed in cold morning light",
  "ECU","top_down","static","dawn",True,False,
  "и снова утро, снова пустая половина койки, снова кто-то ушёл, даже не обернувшись."),
 ("CH09_SH07", "HEROINE_YOUNG", "factory",
  "close-up of the heroine feeling power, not shame",
  "CU","eye","static","gdr_day",False,False,
  "ты не чувствуешь стыда, ты чувствуешь силу, ведь это ты выбираешь и ты бросаешь."),
 ("CH09_SH08", None, "factory",
  "medium of coworkers whispering behind their hands",
  "MS","eye","static","gdr_day",True,False,
  "за спиной уже вовсю шепчутся, но тебе будто всё нипочём, пока есть на кого охотиться."),
 ("CH09_SH09", "HEROINE_YOUNG", "street_east",
  "medium close-up of her changing men like gloves",
  "MCU","eye","static","gdr_day",False,False,
  "ты меняешь мужчин, как перчатки, и каждый раз говоришь себе, вот теперь точно загорится."),
 ("CH09_SH10", "HEROINE_YOUNG", "dormitory",
  "close-up of the growing emptiness behind her eyes",
  "CU","eye","static","gdr_eve",False,True,
  "но огонь гаснет всё быстрее, и холодная пустота внутри становится только больше и больше."),
 ("CH09_SH11", None, "factory",
  "wide B-roll of the empty grey factory floor after shift, silent",
  "WS","eye","static","gdr_eve",True,False,""),
]
if __name__ == "__main__":
    seed_act(9, "gdr_grey", MOOD, "static", "CH09 Factory", SHOTS)
