# -*- coding: utf-8 -*-
"""best_thing shots: A6 (Roza's school), A7 (the market corner), A8 (the ninety-thousand wedding)."""
from _best_thing_engine import seed_act

PAL_A6 = "salon cool green, zinc bucket shine, ribbon colour accents"
PAL_A7 = "market string lights, kraft warm tones, fresh stem greens"
PAL_A8 = "frost night blue, van headlight beams, cold breath silver"

A6 = [
 ("A6_SH01", "LIDA_BASE", "roza_salon",
  "Lida scrubs zinc buckets in the salon backroom, sleeves up, the glamour of floristry at its true starting point",
  "MS", "eye", "static", "morning", False, False,
  "школа розы начинается с вёдер — их у неё двадцать два, и все должны звенеть.",
  "her scrubbing hands work the zinc shine as suds slide down the drain",
  "APRON"),
 ("A6_SH02", "ROZA_BASE", "roza_salon",
  "Roza inspects a finished bouquet, pulls one stem, hands it back with the single word that runs her school",
  "CU", "eye", "static", "day", False, False,
  "роза вытягивает из твоего букета один стебель и говорит «переделай» — это слово здесь вместо учебника.",
  "the pulled stem returns with the verdict as her bracelet turns"),
 ("A6_SH03", "LIDA_BASE", "roza_salon",
  "Lida redoes the bouquet the seventh time, jaw set, hands finding a better line each round",
  "MS", "eye", "static", "day", False, False,
  "переделываешь ты седьмой раз, и седьмой почему-то встаёт лучше шестого — так тут учат.",
  "the seventh assembly finds its cleaner line under her set jaw",
  "SHEARS"),
 ("A6_SH04", None, None,
  "a salon work table scarred by knife lines, stem offcuts in a neat pile, ribbon spools racked by colour",
  "ECU", "eye", "static", "day", False, False,
  "стол в салоне изрезан ножами трёх поколений учениц — теперь и твои полоски там.",
  "stem offcuts settle onto the pile beside the scarred knife lines"),
 ("A6_SH05", "LIDA_BASE", "flower_base",
  "Lida at the night base now buying for the salon, checking boxes fast, bargaining with a grower's back",
  "WS", "eye", "static", "night", False, False,
  "на ночную базу ты теперь ездишь за салон, и торговаться учишься быстрее, чем вязать бант.",
  "her quick hands check box after box as the trolley fills",
  None, "crowd"),
 ("A6_SH06", "ROZA_BASE", "roza_salon",
  "Roza shows the economics on the back of a receipt: stem cost, waste percentage, margin, rent",
  "CU", "eye", "static", "day", False, False,
  "экономику роза объясняет на обороте чека, и твоё бухгалтерское сердце впервые здесь дома.",
  "her pencil walks the receipt back through cost, waste and margin"),
 ("A6_SH07", "LIDA_BASE", "roza_salon",
  "Lida rebuilds Roza's receipt into a proper cost table in her ledger, adding columns of her own invention",
  "MS", "eye", "static", "evening", False, False,
  "вечером ты переносишь её чек в настоящую таблицу — с колонками, которых у розы не было никогда.",
  "the receipt figures migrate into ruled columns under her pen",
  "LEDGER"),
 ("A6_SH08", "ROZA_BASE", "roza_salon",
  "Roza studies the ledger table over her glasses, sniffs, and pockets a photocopy in guarded silence",
  "MCU", "eye", "static", "evening", False, True,
  "роза изучает твою таблицу, хмыкает и забирает копию — так две школы обмениваются послами.",
  "the photocopy folds into her smock pocket under the guarded sniff",
  "LEDGER"),
 ("A6_SH09", None, "roza_salon",
  "the salon at closing: buckets rinsed and upturned, the cooler humming, one lamp over the scarred table",
  "WS", "eye", "static", "night", True, False,
  "салон закрывается в девять, и перевёрнутые вёдра стоят рядами, как каски после смены.",
  "the upturned buckets hold their ranks under the one closing lamp"),
 ("A6_SH10", "LIDA_BASE", "lida_hall",
  "Lida comes home smelling of stems and cold water, Sergey sniffing theatrically and grinning",
  "MCU", "eye", "static", "night", False, False,
  "домой ты приходишь пахнущая стеблями и холодной водой, и серёжа говорит, что это лучше офисных духов.",
  "his theatrical sniff breaks into the grin as her coat comes off"),
 ("A6_SH11", "LIDA_BASE", "lida_kitchen",
  "Lida counts her first salon pay at the kitchen table, small money laid out honestly in one row",
  "MS", "eye", "static", "night", False, False,
  "первая зарплата у розы — пятьдесят две тысячи, вдвое меньше прежней, и ты пересчитываешь их без тоски.",
  "the modest notes square into their honest row under the lamp"),
 ("A6_SH12", "KOLYA_BASE", "lida_kitchen",
  "Kolya shows Lida a phone screen: a page named after her flowers with the first eighty followers",
  "CU", "eye", "static", "night", False, False,
  "коля разворачивает телефон — он завёл тебе страницу, и на ней уже восемьдесят подписчиков.",
  "the phone turns to show the young page and its first followers"),
 ("A6_SH13", None, None,
  "a phone gallery grid of bouquet photos, market light, thumb scrolling, likes ticking upward",
  "ECU", "eye", "static", "night", False, False,
  "твои букеты в ленте собирают сердечки от незнакомых людей, и это странная новая валюта.",
  "the thumb scrolls the bouquet grid as the like counters tick"),
 ("A6_SH14", "ROZA_BASE", "roza_salon",
  "Roza hands Lida the salon keys for the saturday shift, a trust ceremony disguised as logistics",
  "MCU", "eye", "static", "day", False, False,
  "к весне роза выдаёт тебе ключи от субботы — в её школе это диплом с отличием.",
  "the salon keys pass into her palm with deliberate offhand ceremony"),
 ("A6_SH15", "LIDA_BASE", "roza_salon",
  "Lida runs the salon alone on saturday: customers, wraps, the register, the rhythm holding under her",
  "WS", "eye", "static", "day", False, False,
  "субботу ты отрабатываешь одна — двенадцать букетов, касса сходится, руки не дрожат.",
  "the saturday rhythm runs through her hands from bucket to wrap to register",
  None, "crowd"),
 ("A6_SH16", "LIDA_BASE", "roza_salon",
  "Lida's face at saturday close, tired the good way, a stem leaf caught in her hair",
  "CU", "eye", "push_in", "evening", False, True,
  "в девять вечера ты устала так, как не уставала в отчётность, — и это усталость со вкусом.",
  "the good tiredness settles on her face under the caught leaf"),
]

A7 = [
 ("A7_SH01", ("LIDA_BASE", "ROZA_BASE"), "roza_salon",
  "Roza pushes a handwritten market-corner contact across the table to Lida, gruff, avoiding the moment's weight",
  "MS", "eye", "static", "day", False, False,
  "весной роза сама двигает тебе бумажку с контактом — «угол на рынке освобождается, иди, ученица».",
  "the handwritten contact slides across under her gruff pushing finger"),
 ("A7_SH02", "LIDA_BASE", "market_corner",
  "Lida measures her empty market corner with steps, planning buckets and table in the air with her hands",
  "WS", "eye", "static", "day", False, False,
  "угол — три шага на четыре, аренда двадцать две тысячи, и весь он с этого дня твой.",
  "her pacing steps measure the bare corner as her hands sketch the layout"),
 ("A7_SH03", "SERGEY_BASE", "market_corner",
  "Sergey assembles the folding table and the kraft roll bracket with his van tools, a man building his wife a country",
  "MS", "eye", "static", "day", False, False,
  "серёжа собирает тебе стол и кронштейн для крафта из своих фургонных инструментов за один вечер.",
  "his van tools set the bracket true as the folding table locks its legs",
  "WRAP"),
 ("A7_SH04", None, None,
  "the finished market corner: zinc buckets ranked, string lights on, the kraft roll ready, a hand-lettered price card",
  "ECU", "eye", "static", "evening", False, False,
  "к открытию у тебя восемь вёдер, гирлянда, крафт и ценник, написанный от руки без ошибок.",
  "the string lights warm the ranked buckets and the lettered card",
  "WRAP"),
 ("A7_SH05", "LIDA_BASE", "market_corner",
  "the first customer: Lida wraps a small bouquet in kraft, hands steadier than her heart, the first sale",
  "MCU", "eye", "static", "day", False, True,
  "первый букет уходит за тысячу восемьсот, и купюры ты кладёшь в кассу двумя руками, как птенца.",
  "the kraft folds crisp around the first bouquet under her steady hands",
  "WRAP"),
 ("A7_SH06", None, None,
  "the order ledger's first page: date, bouquet, sum — one line, written large and underlined",
  "INSERT", "top", "static", "evening", False, False,
  "в тетради заказов появляется первая строка, и ты подчёркиваешь её, как итог года.",
  "the first ledger line dries under its double underline",
  "LEDGER"),
 ("A7_SH07", "LIDA_BASE", "flower_base",
  "Lida at the night base buying for herself now, trolley smaller, eye sharper, dawn behind the gates",
  "MS", "eye", "static", "night", False, False,
  "на базу ты теперь ездишь за себя, и каждый стебель в тележке посчитан до продажи.",
  "her sharpened eye culls the boxes as the small trolley fills",
  None, "crowd"),
 ("A7_SH08", "KOLYA_BASE", "market_corner",
  "Kolya films the corner for stories: bouquets, hands, kraft, the string lights, directing his mother like talent",
  "MS", "eye", "static", "day", False, False,
  "коля снимает угол для сторис и командует «мам, заверни ещё раз, свет хороший» — у тебя теперь есть медиаотдел.",
  "his pop-socket phone orbits the wrapping hands under the lights",
  None, "crowd"),
 ("A7_SH09", None, None,
  "a phone notification screen: three order messages via the page, one asking for delivery",
  "ECU", "eye", "static", "evening", False, False,
  "через страницу приходят три заказа за неделю, и один — с доставкой, которой у тебя нет.",
  "the three order banners stack on the lit screen"),
 ("A7_SH10", "SERGEY_BASE", "family_car",
  "Sergey clears a corner of his van bay, strapping a flower box, improvising the delivery service",
  "MCU", "eye", "static", "day", False, False,
  "серёжа освобождает угол фургона и говорит — «доставка есть, считай смету», — так у мастерской появляется логистика.",
  "the strap cinches the first flower box into the cleared van corner"),
 ("A7_SH11", "LIDA_BASE", "market_corner",
  "Lida serves a small queue: regulars now, a woman pointing at eucalyptus, a man collecting a pre-order",
  "WS", "eye", "static", "day", False, False,
  "к лету у угла появляется очередь из трёх человек, и двоих ты знаешь по именам.",
  "the small queue shifts as her hands run wrap after wrap",
  None, "crowd"),
 ("A7_SH12", "LIDA_BASE", "market_corner",
  "Lida does evening accounts at the folding table, the big-key calculator among stems, tape curling",
  "MS", "eye", "static", "evening", False, False,
  "вечером ты сводишь кассу на старом калькуляторе, и он щёлкает среди стеблей, как дома.",
  "the big keys click among the stems as the tape curls down",
  "CALC"),
 ("A7_SH13", None, None,
  "the ledger spread of the first market month: income column, cost column, a small red minus at the bottom",
  "ECU", "top", "static", "evening", False, False,
  "первый месяц закрывается в минус на девять тысяч, и ты записываешь это ровно, без паники — по плану.",
  "the small red minus settles at the honest column's foot",
  "LEDGER"),
 ("A7_SH14", "TOMA_BASE", "market_corner",
  "Toma visits the corner in her lunch break, office lanyard on, buying a bouquet and inspecting everything",
  "MCU", "eye", "static", "day", False, False,
  "тома приезжает в обед при бейджике, покупает букет и осматривает угол, как ревизия — с любовью.",
  "her lanyard swings over the bouquet as her audit eye sweeps the corner"),
 ("A7_SH15", ("TOMA_BASE", "LIDA_BASE"), "street_market",
  "the two friends with coffee at the market entrance, comparing lives with easy warmth, laughing at both",
  "WS", "eye", "static", "day", False, False,
  "вы пьёте кофе у входа и сравниваете жизни без зависти — у неё оклад, у тебя рассвет на базе, и обе не поменялись бы.",
  "two coffees tilt at the market entrance as the easy laugh passes"),
 ("A7_SH16", "LIDA_BASE", "market_corner",
  "Lida re-letters the price card at close, adding a wedding-bouquet line for the first time",
  "MCU", "eye", "static", "evening", False, False,
  "в конце лета ты дописываешь на ценник строку «свадебные букеты» — рука чуть медлит и дописывает.",
  "the marker hesitates a beat and finishes the new bottom line"),
 ("A7_SH17", None, "market_corner",
  "the corner at night behind its lowered net, string lights off, buckets covered, ledger locked in the cash box",
  "WS", "eye", "static", "night", True, False,
  "на ночь угол засыпает под сеткой, и тетрадь заказов ночует в кассовом ящике — ей есть что хранить.",
  "the lowered net stripes the covered buckets in the market night"),
 ("A7_SH18", None, None,
  "a phone message thread: a bride asking about a wedding for ninety thousand, photos of a hall attached",
  "ECU", "eye", "static", "night", False, True,
  "в сентябре приходит сообщение — свадьба, полное оформление, бюджет девяносто тысяч.",
  "the bride's message glows with its attached hall photos"),
]

A8 = [
 ("A8_SH01", "LIDA_BASE", "lida_kitchen",
  "Lida costs the wedding at the kitchen table late: sketches, stem counts, the calculator tape running long",
  "MS", "eye", "static", "night", False, False,
  "свадьбу на девяносто ты считаешь три вечера — закупка, работа, доставка, и запас всего восемь процентов.",
  "the tape runs long over the sketches as the counts settle",
  "CALC"),
 ("A8_SH02", "LIDA_BASE", "flower_base",
  "Lida at the base makes the big buy: trolley stacked with boxed roses and eucalyptus, breath fogging over the load",
  "WS", "eye", "static", "night", False, False,
  "закупка выходит на тридцать восемь тысяч — самая большая тележка твоей жизни.",
  "the stacked trolley rolls heavy through the breath fog",
  None, "crowd"),
 ("A8_SH03", None, "family_car",
  "the van bay loaded with flower boxes, moving blankets tucked, the taped thermometer showing near zero",
  "ECU", "eye", "static", "night", False, False,
  "ночью резко минусит, и термометр в фургоне сползает к нулю быстрее прогноза.",
  "the thermometer needle eases toward zero over the blanketed boxes"),
 ("A8_SH04", "SERGEY_BASE", "family_car",
  "Sergey drives through frost fog, jaw tight, one hand adjusting the cab heater vents backward",
  "MCU", "eye", "static", "night", False, False,
  "серёжа гонит через морозный туман и гонит печку в кузов, но фургон не термос.",
  "his hand angles the heater vents back as the frost fog swallows the beams"),
 ("A8_SH05", "LIDA_BASE", "family_car",
  "Lida opens a box at a stop and finds frost-touched petals, edges glassing dark, her breath stopping",
  "CU", "eye", "static", "night", False, True,
  "на остановке ты открываешь коробку, и у трети роз лепестки стеклянные по краю.",
  "the lifted lid shows the glassed petal edges as her breath stops"),
 ("A8_SH06", "LIDA_BASE", "family_car",
  "Lida sits one long moment with the shears gripped in her fist, then starts sorting boxes fast",
  "MCU", "eye", "static", "night", False, False,
  "одну долгую минуту ты сидишь с ножницами в кулаке, а потом начинаешь сортировать — паника подождёт.",
  "the gripped shears steady her fist before her hands fly to the sorting",
  "SHEARS"),
 ("A8_SH07", None, None,
  "a phone screen mid-call at night: the flower base contact, a time of half past three visible",
  "ECU", "eye", "static", "night", False, False,
  "в половине четвёртого ты звонишь на базу, и там, к счастью, не спят никогда.",
  "the night call connects under the half-past-three clock"),
 ("A8_SH08", "TOMA_BASE", None,
  "Toma on a video call in a dressing gown, wide awake in seconds, already writing an offer of help",
  "CU", "eye", "static", "night", False, False,
  "тома отвечает со второго гудка и через минуту уже едет — дружба расписаний не читает.",
  "her dressing-gown resolve sharpens on the call screen"),
 ("A8_SH09", None, "flower_base",
  "the base at four a.m.: a grower loading replacement roses onto the van dolly, money counted under a lamp",
  "WS", "eye", "static", "night", False, False,
  "запасная закупка съедает весь резерв и ещё одиннадцать тысяч сверху — из отпускных.",
  "replacement boxes ride the dolly as notes count under the lamp",
  None, "crowd"),
 ("A8_SH10", ("LIDA_BASE", "TOMA_BASE"), "wedding_hall",
  "the banquet hall at dawn: Lida and Toma unpacking stems onto trestles, aprons over party-less clothes",
  "MS", "eye", "static", "morning", False, False,
  "в зал вы въезжаете в шесть утра — ты, тома и триста стеблей на козлах.",
  "stems fan onto the trestles under four fast hands in the dawn hall",
  "APRON"),
 ("A8_SH11", "LIDA_BASE", "wedding_hall",
  "Lida works the arch composition on a ladder, wire in her teeth replaced by wire in hand, correcting herself aloud",
  "WS", "eye", "static", "morning", False, False,
  "арку ты собираешь на стремянке, и руки решают быстрее головы — школа розы, всё по счёту «переделай».",
  "the arch line grows under her ladder-top hands wire by wire"),
 ("A8_SH12", None, "wedding_hall",
  "the finished tables: low centrepieces in even rows, the arch framing the light, one chair with the bridal bouquet box",
  "EWS", "eye", "static", "day", False, False,
  "к одиннадцати зал стоит собранный — арка, семнадцать композиций и коробка с букетом невесты на стуле.",
  "even centrepiece rows lead the eye to the finished light-framed arch"),
 ("A8_SH13", "TOMA_BASE", "lida_kitchen",
  "days later: Toma delivers her own news over tea — a lead-accountant offer for Lida at her firm, salary named",
  "MCU", "eye", "static", "evening", False, False,
  "через неделю тома привозит новость — у них ищут ведущего бухгалтера, и ставка выше твоей прежней.",
  "the offer crosses the tea table under her honest bright frames"),
 ("A8_SH14", "LIDA_BASE", "lida_kitchen",
  "Lida turns her teacup, honestly weighing it for three seconds, then shaking her head with a clear face",
  "CU", "eye", "push_in", "evening", False, True,
  "ты честно думаешь три секунды и качаешь головой — обратно дороги есть, просто они больше не твои.",
  "the cup turns a slow quarter before her clear headshake lands"),
 ("A8_SH15", "TOMA_BASE", "lida_kitchen",
  "Toma nods, satisfied like someone who checked a box, and pulls out her phone to order flowers for the office",
  "MCU", "eye", "static", "evening", False, False,
  "тома кивает с облегчением проверяющего и тут же заказывает у тебя цветы на их ресепшн — «для порядка».",
  "her satisfied nod turns into the thumbed flower order"),
 ("A8_SH16", None, None,
  "the wedding payment entry in the ledger: income, the double costs beneath, a thin final plus circled",
  "INSERT", "top", "static", "night", False, False,
  "свадьба закрывается в плюс на четыре тысячи — смешной, вымученный и самый важный плюс года.",
  "the thin circled plus dries at the foot of the double-cost column",
  "LEDGER"),
]

if __name__ == "__main__":
    seed_act("A6", PAL_A6, A6)
    seed_act("A7", PAL_A7, A7)
    seed_act("A8", PAL_A8, A8)
