# -*- coding: utf-8 -*-
"""hidden_layoff atmosphere breathers: 2 per act (A1..A11), id_region='a'.

Each act's tail has its OWN camera scheme and subjects (§5.1a): no two acts
share scale order, angle set or movement; every insert carries a concrete VO bit.
"""
from _hidden_layoff_engine import seed_act

PALS = {
 "A1": "warm amber light, soft golden haze, faded nostalgic colours",
 "A2": "flat white office light, cool glass reflections, muted grey-blue",
 "A3": "hard white light, deep window shadow, cold grey-green",
 "A4": "soft april daylight, pale green buds, cool grey paths",
 "A5": "bright hazy summer light, washed-out warm grey, glare on asphalt",
 "A6": "deep green park shade, dusty gold air, dim warm lamplight",
 "A7": "late summer amber evening, long warm shadows, tired gold",
 "A8": "grey overcast daylight, first yellow leaves, cold flat light",
 "A9": "low golden october sun, long cold shadows, thin blue sky",
 "A10": "dim warm lamplight, deep blue night windows, muted browns",
 "A11": "pale winter daylight, grey concrete, one warm interior glow",
}

ATMO = {
 "A1": [
  ("A1_SZ01", None, "office_openspace",
   "a two thousand seven office desk in evening light, a corded phone, carbon-copy sheets on a spike, a small desk fan turning",
   "INSERT", "eye", "static", "evening", True, False,
   "в те годы на твоём столе живёт телефон с диском и гвоздь для накладных.",
   "the small desk fan turns slowly and the top carbon sheet lifts and settles"),
  ("A1_SZ02", None, "bus_stop",
   "the avenue of the mid two-thousands at golden evening, a trolleybus passing under sagging wires, old kiosks along the pavement",
   "EWS", "high", "pan_right", "evening", True, False,
   "город тех лет пахнет тёплой пылью, и все дороги в нём ведут на фабрику.",
   "the trolleybus slides along under the wires trailing a soft spark at the pole"),
 ],
 "A2": [
  ("A2_SZ01", None, "office_openspace",
   "the open-plan office at night, rows of dark monitors, one forgotten desk lamp burning at the far end",
   "WS", "eye", "tilt_down", "night", True, False,
   "по вечерам опенспейс теперь пустеет к шести — люди стали уходить вовремя.",
   "the far desk lamp glows steadily while the dark monitors hold their sleeping screens"),
  ("A2_SZ02", None, "meeting_room",
   "first spring rain drops hitting the glass wall of the meeting room, the empty oval table beyond, chairs pushed in square",
   "ECU", "eye", "static", "day", True, False,
   "март стучит в стекло переговорки, а переговорка стоит прибранная, как перед комиссией.",
   "rain drops strike the glass one by one and run down in thin joining lines"),
 ],
 "A3": [
  ("A3_SZ01", None, "factory_yard",
   "the factory yard seen from the roof edge, pigeons crossing over the ramp, one truck small below, cold spring sky",
   "EWS", "high", "pull_out", "day", True, False,
   "с крыши фабрика выглядит так же, как в твой первый день — только без тебя.",
   "pigeons cross the yard in a slow arc and settle along the ramp edge"),
  ("A3_SZ02", None, None,
   "a cardboard box on a bus seat, a mug handle and a notebook spine showing over its edge, evening light through the window",
   "INSERT", "top", "static", "evening", True, False,
   "коробка с девятнадцатью годами едет домой на соседнем сиденье автобуса.",
   "evening light sweeps slowly across the box as the bus turns"),
 ],
 "A4": [
  ("A4_SZ01", None, "park_pond",
   "morning mist thinning over the pond, the water like grey glass, bare linden branches doubled in it",
   "WS", "eye", "pan_left", "morning", True, False,
   "в восемь утра пруд ещё держит ночной туман, и в парке слышно каждую каплю.",
   "the mist thins slowly off the water and the doubled branches sharpen in the glass"),
  ("A4_SZ02", None, "park_pond",
   "new grass blades pushing up through wet gravel beside a bench leg, one early bee over them",
   "ECU", "top", "push_in", "day", True, False,
   "апрельская трава пробивает гравий у лавки за неделю — быстрее, чем приходит хоть один ответ.",
   "the bee drifts a low circle over the grass blades and lands on the gravel"),
 ],
 "A5": [
  ("A5_SZ01", None, "bus_stop",
   "the summer avenue boiling with heat haze at noon, asphalt shimmering, a water truck spraying the far lane",
   "EWS", "low", "static", "day", True, False,
   "в полдень асфальт плывёт от жары, и город работает, как работал без тебя всегда.",
   "heat haze bends the far buildings and the water truck's spray drifts sideways"),
  ("A5_SZ02", None, "canteen",
   "condensation running down the inside of the canteen window, plastic tables empty after lunch, trays stacked",
   "ECU", "eye", "tilt_up", "day", True, False,
   "к трём часам столовая пустеет, и по стеклу сползает холодный пот кондиционера.",
   "a condensation drop gathers and runs a long clean line down the glass"),
 ],
 "A6": [
  ("A6_SZ01", None, "library_hall",
   "the reading hall at closing time, green lamps going dark one by one down the long tables, dust in the last light",
   "WS", "eye", "push_in", "evening", True, False,
   "в восемь вечера библиотека гасит зелёные лампы по одной, как отбой в казарме.",
   "the green lamps go dark one after another down the long row of tables"),
  ("A6_SZ02", None, "park_pond",
   "the pond surface in deep summer shade, water striders drawing rings, a linden flower floating",
   "ECU", "top", "static", "day", True, False,
   "по воде ходят водомерки, и у них, в отличие от тебя, всё по-настоящему.",
   "water striders dart and pause, drawing small crossing rings around the floating flower"),
 ],
 "A7": [
  ("A7_SZ01", None, "garage_row",
   "the garage row at sunset from above, long shadows of the boxes striping the cracked asphalt, one door standing open and empty",
   "EWS", "high", "pan_right", "evening", True, False,
   "гаражи стоят рядами, как сейфы, и один из них с этого вечера чужой.",
   "the long shadows of the garage boxes stretch slowly across the cracked asphalt"),
  ("A7_SZ02", None, None,
   "an old brass padlock standing on a kitchen shelf between a tea tin and a jar of screws, its shackle open",
   "INSERT", "eye", "static", "night", True, False,
   "навесной замок поселяется на кухонной полке между чаем и банкой шурупов.",
   "lamplight breathes across the open shackle as the shelf shadow shifts"),
 ],
 "A8": [
  ("A8_SZ01", None, "park_pond",
   "wet yellow leaves plastered along the gravel path after rain, the path curving away between black tree trunks",
   "WS", "eye", "track", "day", True, False,
   "листья ложатся на дорожку жёлтой разметкой, по которой ты ходишь пятый месяц.",
   "single leaves drop and slide along the wet path in the passing draught"),
  ("A8_SZ02", None, "warehouse",
   "a row of orange vests on hooks by the warehouse security window, one hook empty, grey light on the reflective strips",
   "ECU", "low", "static", "day", True, False,
   "на проходной склада висят восемь оранжевых жилетов, и один крючок стоит пустой.",
   "the reflective strips glimmer faintly as the vests sway together in the gate draught"),
 ],
 "A9": [
  ("A9_SZ01", None, "bus_stop",
   "the october avenue in low sun, shadows of people stretched ten metres long across the pavement, gold leaves along the kerb",
   "EWS", "high", "pull_out", "day", True, False,
   "октябрьское солнце кладёт тени длиной в десять метров, и врать в такую погоду труднее всего.",
   "the stretched shadows crawl slowly along the pavement as leaves tick along the kerb"),
  ("A9_SZ02", None, None,
   "the closed chess tin on a wet bench slat, rain beads on its chipped paint, a folded cap left beside it",
   "INSERT", "top", "push_in", "evening", True, False,
   "жестяная коробочка остаётся на мокрой лавке до самого вечера.",
   "rain beads gather and join on the chipped tin lid in the failing light"),
 ],
 "A10": [
  ("A10_SZ01", None, "flat_kitchen",
   "the kitchen at two in the morning, one small lamp on, two chairs at opposite table ends, the window deep blue",
   "WS", "eye", "static", "night", True, False,
   "кухня теперь засыпает позже всех в квартире — у неё больше всего работы.",
   "the lamp flame of light trembles once as a night bus passes below the window"),
  ("A10_SZ02", None, "flat_kitchen",
   "frost creeping in a thin fern pattern along the outer edge of the kitchen window glass, the dark yard beyond",
   "ECU", "eye", "tilt_down", "night", True, False,
   "по краю стекла ползёт первый иней — ноябрь приходит в квартиру раньше календаря.",
   "the frost fern thickens imperceptibly along the glass edge in the cold"),
 ],
 "A11": [
  ("A11_SZ01", None, "warehouse",
   "the city rooftops from the warehouse yard under first snow at dusk, chimney steam standing straight, windows lighting up",
   "EWS", "low", "tilt_up", "evening", True, False,
   "первый снег ложится на город ровно, без различия — на фабрики, склады и парки.",
   "snow drifts down steadily and chimney steam climbs straight into the still air"),
  ("A11_SZ02", None, "flat_hall",
   "a brass door handle of the flat entrance door with snowflakes melting on it, a wet glove print fading on the metal",
   "ECU", "eye", "pull_out", "evening", True, False,
   "на латунной ручке двери тают снежинки — кто-то только что вернулся домой насовсем.",
   "the snowflakes on the brass handle shrink into beads and slide slowly down"),
 ],
}

if __name__ == "__main__":
    for act, shots in ATMO.items():
        seed_act(act, PALS[act], shots, id_region="a")
