# -*- coding: utf-8 -*-
"""Seed CH28 — Внучка (2nd person). Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "warm hesitant light returning to the grey home, fragile hope"
SHOTS = [
 ("CH28_SH01", None, "old_flat",
  "close-up of a doorbell and a hand hesitating, grey hallway",
  "CU","eye","static","home_day",True,False,
  "и однажды звонок в дверь."),
 ("CH28_SH02", ("DAUGHTER","HEROINE_OLD"), "stairwell",
  "the grown daughter on the left holding a small granddaughter, the old heroine on the right at the open door",
  "MS","eye","static","home_day",False,False,
  "на пороге дочь, спустя годы, а на руках малышка, твоя внучка."),
 ("CH28_SH03", "DAUGHTER", "family",
  "medium close-up of the daughter, cautious and uncertain why she came",
  "MCU","eye","static","home_day",False,False,
  "я и сама не знаю зачем пришла, говорит она, просто, чтоб ты увидела внучку."),
 ("CH28_SH04", None, "family",
  "extreme close-up of the granddaughter's little fresh innocent face",
  "ECU","eye","push_in","home_day",True,False,
  "и ты смотришь на личико внучки."),
 ("CH28_SH05", "HEROINE_OLD", "family",
  "medium close-up of the heroine's hand rising by old habit to appraise the child's looks",
  "MCU","eye","static","home_day",False,False,
  "и по привычке, той самой, тянешься оценить, красивая ли."),
 ("CH28_SH06", "HEROINE_OLD", "family",
  "extreme close-up of her hand stopping in mid-air near the child's face",
  "ECU","eye","static","home_day",False,True,
  "и впервые в жизни замираешь."),
 ("CH28_SH07", "HEROINE_OLD", "family",
  "close-up of the heroine's stricken realisation",
  "CU","eye","static","home_day",False,False,
  "ты ловишь себя на том, что чуть не сделала с ней то же, что мама с тобой."),
 ("CH28_SH08", "HEROINE_OLD", "family",
  "medium close-up of the heroine slowly lowering her hand",
  "MCU","eye","static","home_day",False,False,
  "и ты убираешь руку."),
 ("CH28_SH09", "HEROINE_OLD", "family",
  "close-up of the heroine looking into the child's eyes for once, not at her face",
  "CU","eye","static","home_day",False,True,
  "впервые ты смотришь не на лицо, а в глаза ребёнку."),
 ("CH28_SH10", None, "family",
  "wide B-roll of warm light filling the grey room, the child's toys appearing",
  "WS","eye","static","home_day",True,False,""),
]
if __name__ == "__main__":
    seed_act(28, "warm_home", MOOD, "static", "CH28 Granddaughter", SHOTS)
