# -*- coding: utf-8 -*-
"""Seed CH02 — Урок матери (2nd person). Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "warm sepia nostalgic glow, vanity-mirror lamplight, soft grain"
SHOTS = [
 ("CH02_SH01", "MOTHER", "mother",
  "medium close-up of the elegant mother at her vanity dresser powdering her face, an unhurried daily ritual",
  "MCU","eye","static","sepia_70s",False,False,
  "каждое утро у мамы один и тот же ритуал, целый час перед зеркалом."),
 ("CH02_SH02", None, "mother",
  "extreme close-up of manicured hands dabbing powder and applying lipstick at a vanity",
  "ECU","top_down","static","sepia_70s",True,False,
  "пудра, помада, ни шагу за порог с ненакрашенным лицом."),
 ("CH02_SH03", None, "mother",
  "medium shot of a little girl sitting close by, watching the ritual, absorbing it",
  "MS","eye","static","sepia_70s",True,False,
  "ты сидишь рядом и впитываешь, что лицо важнее всего на свете."),
 ("CH02_SH04", "MOTHER", "mother",
  "the mother gently turning the little girl's chin toward the mirror, instructing her",
  "MS","eye","static","sepia_70s",False,True,
  "смотри, говорит мама, вот твоё единственное приданое, береги пуще жизни."),
 ("CH02_SH05", None, "mother",
  "close-up of faded framed photographs of beautiful grandmothers lining the wall",
  "CU","eye","pan","sepia_70s",True,False,
  "на стене бабки и прабабки, одна красивее другой, целый иконостас красоты."),
 ("CH02_SH06", None, "school",
  "medium shot of a diligent plain neighbour girl with books, being pitied rather than praised",
  "MS","eye","static","sepia_70s",True,False,
  "соседская девочка умница, отличница, а мама её жалеет, бедная, некрасивая."),
 ("CH02_SH07", None, "mother",
  "extreme close-up of the little girl's thoughtful face, drawing the cruel lesson",
  "ECU","eye","static","sepia_70s",True,False,
  "и ты понимаешь, ум здесь не в счёт, в счёт только лицо."),
 ("CH02_SH08", "MOTHER", "mother",
  "medium close-up of the mother catching a tiny wrinkle in the mirror, a flicker of fear",
  "MCU","eye","push_in","sepia_70s",False,True,
  "мама ловит у зеркала первую морщинку, и в её глазах ты впервые видишь страх постареть."),
 ("CH02_SH09", None, "mother",
  "wide shot of the little girl practicing a grown-up smile in the big vanity mirror",
  "WS","eye","static","sepia_70s",True,False,
  "и ты уже репетируешь мамину улыбку, поворот головы, взгляд."),
 ("CH02_SH10", None, "mother",
  "close-up of the antique powder compact set down on the dresser at dusk",
  "CU","top_down","static","sepia_70s",True,False,
  "молодость не вечна, вздыхает мама, лови момент, пока красива."),
 ("CH02_SH11", None, "mother",
  "wide shot of the dim vanity corner at dusk, mirror catching the last light",
  "WS","eye","static","sepia_70s",True,False,""),
]
if __name__ == "__main__":
    seed_act(2, "sepia_warm", MOOD, "animated", "CH02 Mother's lesson", SHOTS)
