# -*- coding: utf-8 -*-
"""Seed CH16 — Измена, бежишь к новой дозе (HEROINE_YOUNG + ANDREAS). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "betrayal, she runs to a new high, harsh neon night sliding into black shame"
SHOTS = [
 ("CH16_SH01", "HEROINE_YOUNG", "disco",
  "medium of the heroine staying at the dancehall though she is expected home",
  "MS","eye","static","night",False,False,
  "в тот вечер ты остаёшься на дискотеке, хотя Андреас ждёт тебя дома с горячим ужином."),
 ("CH16_SH02", None, "disco",
  "close-up of a faceless stranger approaching, the wave igniting",
  "CU","eye","static","night",True,False,
  "к тебе подходит чужой, и знакомая волна вспыхивает быстрее, чем совесть успевает крикнуть."),
 ("CH16_SH03", "HEROINE_YOUNG", "disco",
  "medium close-up of her rationalising",
  "MCU","eye","static","night",False,False,
  "ты говоришь себе, только разок, в самый последний раз, просто чтобы вспомнить, кто я."),
 ("CH16_SH04", None, "street_east",
  "wide of her leaving into the night with a faceless man",
  "WS","eye","static","night",True,False,
  "и ты уходишь с ним в ночь, а кольцо Андреаса остаётся лежать дома на полке."),
 ("CH16_SH05", None, "her_room",
  "extreme close-up of two glasses in cold morning light",
  "ECU","top_down","static","dawn",True,False,
  "наутро накрывает не волна, а стыд, густой и чёрный, какого ты ещё никогда не знала."),
 ("CH16_SH06", "HEROINE_YOUNG", "her_room",
  "close-up of her sick realisation",
  "CU","eye","static","dawn",False,False,
  "ты предала единственного, кто любил тебя по-настоящему, и ради чего, ради чужой спины."),
 ("CH16_SH07", "HEROINE_YOUNG", "street_east",
  "medium close-up of her hurrying to Andreas",
  "MCU","eye","static","dawn",False,False,
  "ты бежишь к Андреасу, чтобы покаяться или промолчать, ты и сама ещё не знаешь."),
 ("CH16_SH08", ("HEROINE_YOUNG","ANDREAS"), "andreas_flat",
  "medium of Andreas at the door, already knowing",
  "MS","eye","static","gdr_day",False,False,
  "но он уже всё знает, город тесен, добрые соседи донесли ему ещё до самого рассвета."),
 ("CH16_SH09", "ANDREAS", "andreas_flat",
  "close-up of Andreas, not anger but a light gone out",
  "CU","eye","static","gdr_day",False,True,
  "он стоит в дверях, и в его глазах не злость, а что-то куда страшнее, погасший свет."),
 ("CH16_SH10", "HEROINE_YOUNG", "andreas_flat",
  "medium close-up of her quiet confession",
  "MCU","eye","static","gdr_day",False,False,
  "прости, шепчешь ты, я просто не умею иначе, и впервые эти слова чистая правда."),
 ("CH16_SH11", None, "andreas_flat",
  "wide B-roll of the flat, the ring on the sill, silent",
  "WS","eye","static","gdr_day",True,False,""),
]
if __name__ == "__main__":
    seed_act(16, "neon_gdr", MOOD, "static", "CH16 Betrayal", SHOTS)
