# -*- coding: utf-8 -*-
"""Seed CH06 — Свадьба, триумф красоты (2nd person). Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "warm bright 1990s wedding glow, champagne and chandeliers, triumphant"
SHOTS = [
 ("CH06_SH01", None, "wedding",
  "wide establishing of a 1990s wedding banquet hall, white tables, champagne, balloons and tulle, warm chandelier light",
  "WS","high","push_in","warm_day",True,False,
  "из всех мужчин ты выбираешь самого видного, самого завидного."),
 ("CH06_SH02", ("HEROINE_YOUNG","HUSBAND"), "wedding",
  "the radiant bride on the left and the handsome groom on the right at the head table, the perfect couple",
  "MS","eye","static","warm_day",False,False,
  "красавица и красавец, все ахают, идеальная пара."),
 ("CH06_SH03", "HUSBAND", "wedding",
  "medium close-up of the groom gazing at his bride, proud to have won the prettiest woman",
  "MCU","eye","static","warm_day",False,False,
  "он выбрал тебя за лицо, и ты это знаешь, и тебе всё равно."),
 ("CH06_SH04", None, "wedding",
  "extreme close-up of wedding rings being slipped onto hands over white lace",
  "ECU","top_down","static","warm_day",True,False,
  "кольца, фата, шампанское, твой настоящий звёздный час."),
 ("CH06_SH05", ("HEROINE_YOUNG","HUSBAND"), "wedding",
  "wide shot of the bride on the left and groom on the right in their first dance, the whole hall watching her",
  "WS","eye","static","warm_day",False,False,
  "первый танец, и весь зал смотрит только на тебя."),
 ("CH06_SH06", None, "wedding",
  "medium shot of envious bridesmaids and a tearful happy mother among the guests",
  "MS","eye","static","warm_day",True,False,
  "подруги завидуют, мама плачет от счастья."),
 ("CH06_SH07", "HEROINE_YOUNG", "wedding",
  "extreme close-up of the bride's radiant glowing face at the peak of her triumph",
  "ECU","eye","push_in","warm_day",False,True,
  "ты на самой вершине, красота привела тебя прямо к мечте."),
 ("CH06_SH08", "MOTHER", "wedding",
  "medium close-up of the proud mother raising a toast, vindicated",
  "MCU","low","static","warm_day",False,False,
  "вот видишь, говорит мама сквозь слёзы, я же говорила, красота вывезет."),
 ("CH06_SH09", "HEROINE_YOUNG", "wedding",
  "medium shot of the bride tossing the bouquet over a crowd of reaching hands",
  "MS","high","static","warm_day",False,False,
  "ты бросаешь букет и думаешь, жизнь окончательно удалась."),
 ("CH06_SH10", ("HEROINE_YOUNG","HUSBAND"), "wedding",
  "close-up of the bride on the left and groom on the right sharing a kiss",
  "CU","eye","static","warm_day",False,True,""),
 ("CH06_SH11", "HEROINE_YOUNG", "wedding",
  "close-up of the bride's happy face, unaware",
  "CU","eye","static","warm_day",False,False,
  "ты не знаешь, что он выбрал лицо, а лицо, оно не вечно."),
 ("CH06_SH12", None, "wedding",
  "wide B-roll of the empty wedding hall late at night after the guests have gone",
  "WS","eye","static","warm_day",True,False,""),
]
if __name__ == "__main__":
    seed_act(6, "warm_wedding", MOOD, "static", "CH06 Wedding", SHOTS)
