# -*- coding: utf-8 -*-
"""Seed CH37 — Финал, ключ Андреаса, поздняя правда (HEROINE_OLD). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "late realization, holding Andreas's key, a bitter quiet truth understood too late, a faint hard-won calm"
SHOTS = [
 ("CH37_SH01", "HEROINE_OLD", "old_flat",
  "medium of the heroine lifting Andreas's key from the box, wiping off the dust",
  "MS","eye","static","eve",False,False,
  "однажды вечером ты достаёшь из шкатулки ключ Андреаса и стираешь с него полувековую пыль."),
 ("CH37_SH02", None, "old_flat",
  "extreme close-up of the small key in her aged hand",
  "ECU","top_down","static","eve",True,True,
  "маленький ключ от двери, в которую ты так и не вошла, единственной, что вела к теплу."),
 ("CH37_SH03", "HEROINE_OLD", "old_flat",
  "close-up of her not snapping the box shut this time",
  "CU","eye","static","eve",False,False,
  "ты держишь его и впервые не захлопываешь шкатулку, а позволяешь себе всё вспомнить."),
 ("CH37_SH04", "HEROINE_OLD", "old_flat",
  "medium close-up of the warm memory of Andreas",
  "MCU","eye","static","eve",False,False,
  "ты вспоминаешь его круглые очки, запах чая, кофе по утрам и не пустую тогда подушку."),
 ("CH37_SH05", "HEROINE_OLD", "old_flat",
  "close-up of her quiet admission, too late",
  "CU","eye","static","eve",False,True,
  "слишком поздно, шепчешь ты, но хотя бы теперь ты знаешь, где именно свернула не туда."),
 ("CH37_SH06", "HEROINE_OLD", "east_side_gallery",
  "medium of her laying the key on the wall's parapet like flowers at a grave",
  "MS","eye","static","eve",False,False,
  "ты идёшь к обломку стены и кладёшь ключ на парапет, как кладут цветы у тихой могилы."),
 ("CH37_SH07", "HEROINE_OLD", "east_side_gallery",
  "close-up of the key resting by the fallen wall",
  "CU","eye","static","eve",False,False,
  "пусть лежит здесь, у павшей стены, рядом с уроком, который город усвоил, а ты нет."),
 ("CH37_SH08", "HEROINE_OLD", "east_side_gallery",
  "medium close-up of her facing the emptiness instead of fleeing it",
  "MCU","eye","static","eve",False,True,
  "и впервые за всю жизнь ты не бежишь от пустоты, а просто стоишь и смотришь ей в глаза."),
 ("CH37_SH09", None, "east_side_gallery",
  "wide of the Spree at dusk, a bitter quiet that resembles peace",
  "WS","eye","static","eve",True,False,
  "над Шпрее садится солнце, и в этой тихой горечи есть что-то похожее на покой."),
 ("CH37_SH10", "HEROINE_OLD", "east_side_gallery",
  "close-up of the heroine, the whole life in one line",
  "CU","eye","static","eve",False,True,
  "тебя хотели всю жизнь, а любить ты так и не позволила, и в этом вся твоя жизнь."),
 ("CH37_SH11", None, "east_side_gallery",
  "wide B-roll of the painted wall at dusk by the river, silent",
  "WS","eye","static","eve",True,False,""),
]
if __name__ == "__main__":
    seed_act(37, "warm_dim", MOOD, "static", "CH37 Finale", SHOTS)
