# -*- coding: utf-8 -*-
"""preretire shots: A9 (the bottom: paper ads), A10 (the dough mixer), A11 (bread and gauge)."""
from _preretire_engine import seed_act

PAL_A9 = "deep winter blue, sparse lamplight, breath-fog cold"
PAL_A10 = "warm bakery glow, flour gold, soft oven light"
PAL_A11 = "bright winter light, crisp snow tones, warm interior amber"

A9 = [
 ("A9_SH01", "STEPAN_BASE", "flat_kitchen",
  "Stepan lies on the made bed in daytime clothes staring at the ceiling, the pill organiser within reach, curtains half drawn",
  "MS", "eye", "static", "day", False, False,
  "неделю тебя держит дома давление, и потолок ты изучаешь, как чужой чертёж.",
  "his chest rises slowly as his eyes trace the ceiling crack line"),
 ("A9_SH02", None, None,
  "a blood-pressure monitor on the kitchen table showing a high reading, its cuff coiled like a question mark",
  "ECU", "eye", "static", "day", False, False,
  "тонометр показывает цифры, от которых врач хмурится, а ты злишься.",
  "the monitor digits hold their reading as the coiled cuff settles"),
 ("A9_SH03", "STEPAN_BASE", "flat_kitchen",
  "Stepan lays the feeler gauge fan open on the oilcloth and looks at his own spread hands beside it",
  "MCU", "high", "static", "day", False, True,
  "ты раскладываешь щупы на столе и понимаешь простую вещь — руки без машины глохнут.",
  "the steel fan spreads under the lamp as his hands open flat beside it",
  "GAUGE"),
 ("A9_SH04", "STEPAN_BASE", "flat_kitchen",
  "Stepan writes an ad by hand at the table, ruler-straight lines, cutting phone-number tabs with kitchen scissors",
  "MS", "eye", "static", "evening", False, False,
  "и тогда ты пишешь объявление от руки — «наладка любого оборудования», телефонные язычки под линейку.",
  "the scissors cut the number tabs in even strips along the ruled line"),
 ("A9_SH05", None, None,
  "a handwritten ad sheet with a fringe of phone tabs, block letters neat as a stamp, lying by a glue stick",
  "INSERT", "eye", "static", "evening", False, False,
  "почерк у тебя чертёжный — объявление выходит красивее половины заводской документации.",
  "the glue stick rolls a centimetre as lamplight crosses the block letters"),
 ("A9_SH06", "STEPAN_BASE", "courtyard",
  "Stepan pins his ad to a snowy noticeboard among older ads, pressing each corner with his thumb",
  "WS", "eye", "static", "day", False, False,
  "ты обходишь восемь дворов и клеишь листки по доскам, прижимая углы большим пальцем.",
  "his thumb presses each corner flat as snow dusts the plywood board",
  None, "crowd"),
 ("A9_SH07", None, "courtyard",
  "his ad on the board in falling snow, one phone tab lifted by the wind but holding",
  "ECU", "eye", "static", "day", False, False,
  "первый язычок отрывают в тот же вечер — или это ветер, но ты выбираешь верить в людей.",
  "one paper tab flutters hard in the wind and holds to the sheet"),
 ("A9_SH08", "STEPAN_BASE", "flat_kitchen",
  "Stepan repairs a neighbour's meat grinder at his kitchen table, parts laid out on newspaper in exploded-view order",
  "MS", "eye", "static", "evening", False, False,
  "первый звонок — соседская мясорубка, и ты перебираешь её всерьёз, как турбину.",
  "the grinder parts settle onto the newspaper in exact exploded order",
  "TOOLBOX"),
 ("A9_SH09", None, None,
  "a small pile of banknotes and a jar of home pickles on the table corner, payment country-style",
  "ECU", "high", "static", "evening", False, False,
  "платят пятьсот рублей и банкой огурцов, и это первые честные деньги за четыре месяца.",
  "lamplight rounds the pickle jar beside the small squared pile of notes"),
 ("A9_SH10", "STEPAN_BASE", "courtyard",
  "Stepan fixes a stroller wheel for a young mother by the entrance, kneeling on cardboard, tools from his pocket",
  "WS", "eye", "static", "day", False, False,
  "дальше идут коляска, дверной доводчик и швейная машинка чьей-то бабушки.",
  "the stroller wheel spins true under his hand as the young mother watches",
  None, "crowd"),
 ("A9_SH11", "ALYONA_BASE", None,
  "Alyona on the call screen listening to the pickle-jar story, laughing and wiping one eye at the same time",
  "CU", "eye", "static", "evening", False, False,
  "алёна смеётся над банкой огурцов и одновременно вытирает глаз — у дочерей так бывает.",
  "her laugh breaks across the call screen as one finger catches the eye corner"),
 ("A9_SH12", "STEPAN_BASE", "flat_kitchen",
  "Stepan writes a price list in a school notebook, thinking hard over each line like an estimate",
  "MCU", "eye", "static", "night", False, False,
  "ты заводишь тетрадку с расценками и назначаешь себе оклад сам — впервые за тридцать восемь лет.",
  "his pen weighs each price line as the school notebook fills"),
 ("A9_SH13", None, "bus_stop_w",
  "the winter stop at dawn, one set of large boot prints leading to it through fresh snow",
  "WS", "low", "static", "morning", True, False,
  "по утрам ты снова выходишь из дома первым — у безработного это тоже дисциплина.",
  "fresh snow settles into the single line of boot prints toward the shelter"),
 ("A9_SH14", None, None,
  "the money tin with a few small piles again, the countdown replaced by a plus column pencilled on the lid",
  "INSERT", "top", "static", "night", False, False,
  "в жестянке появляется столбик с плюсами — маленькими, но плюсами.",
  "the pencil adds a small plus figure to the new column on the lid"),
 ("A9_SH15", "STEPAN_BASE", "flat_room",
  "Stepan dusts the certificate frames with a cloth, unhurried, a man tending the past while living in the present",
  "MS", "eye", "static", "day", False, False,
  "грамоты ты теперь протираешь по субботам — прошлому положен уход, а не поклонение.",
  "the cloth passes along the frames in even unhurried strokes",
  "CERTS"),
 ("A9_SH16", "STEPAN_BASE", "flat_kitchen",
  "Stepan's face at the evening table, thinner but steadier, the gauge fan in his breast pocket again out of habit",
  "CU", "eye", "push_in", "evening", False, True,
  "ты худее, чем осенью, но глаза у тебя снова наладчицкие — ищут, что починить.",
  "his steadied eyes sweep the kitchen for faults out of pure habit",
  "GAUGE"),
 ("A9_SH17", None, "street_plant",
  "the bread kiosk queue at dusk, warm loaves passing over the counter, breath fog over the queue",
  "WS", "eye", "static", "evening", True, False,
  "у хлебного киоска пахнет твоим бывшим заводом, и ты приходишь сюда чаще, чем нужно хлебу.",
  "warm loaves pass over the counter as breath fog drifts along the queue",
  None, "crowd"),
 ("A9_SH18", None, None,
  "a paper ad tab with a phone number lying by a landline phone in someone's hallway, picked up by unseen fingers",
  "ECU", "eye", "static", "evening", False, False,
  "где-то в чужой прихожей твой бумажный язычок ложится у телефона — и ждёт своего часа.",
  "the paper tab settles by the phone as a shadow crosses the hallway light"),
]

A10 = [
 ("A10_SH01", "STEPAN_BASE", "flat_kitchen",
  "Stepan answers the landline-style call on speaker, already reaching for the tool box with his free hand",
  "MCU", "eye", "static", "morning", False, False,
  "в марте звонит женщина из мини-пекарни — «тестомес стучит, мастер, а хлеб ждать не умеет».",
  "his free hand hooks the tool box handle before the caller finishes",
  "TOOLBOX"),
 ("A10_SH02", "STEPAN_BASE", "street_plant",
  "Stepan walks through march slush with the steel box, the old work stride back in his legs",
  "WS", "eye", "track", "morning", False, False,
  "ты идёшь через слякоть с ящиком, и походка сама вспоминает заводскую.",
  "the steel box swings low in his grip as the work stride eats the slush",
  "TOOLBOX"),
 ("A10_SH03", None, "bakery",
  "the bakery backroom with a knocking dough mixer, flour-dusted racks, a worried baker's silhouette by the proofing cabinet",
  "WS", "eye", "static", "morning", False, False,
  "тестомес стучит на каждом обороте, и пекарня слушает его, как больное сердце.",
  "the mixer arm knocks on each turn as flour dust hangs in the warm light",
  None, "crowd"),
 ("A10_SH04", "STEPAN_BASE", "bakery",
  "Stepan lays his palm flat on the mixer housing and closes his eyes, flour settling on his dark jacket sleeve",
  "MCU", "eye", "static", "morning", False, True,
  "ты кладёшь ладонь на кожух, и машина рассказывает тебе всё за полминуты.",
  "his palm settles on the housing as flour dusts the dark sleeve"),
 ("A10_SH05", "STEPAN_BASE", None,
  "his own hands sliding a feeler blade into the mixer shaft gap, the fan bright against flour-white steel",
  "POV", "pov", "static", "morning", False, False,
  "щуп входит на две сотки там, где положено на полторы, — втулка, старая знакомая болезнь.",
  "the thin blade slides the gap as the fan tilts against the floured steel",
  "GAUGE"),
 ("A10_SH06", "STEPAN_BASE", "bakery",
  "Stepan works on the opened mixer with the tool trays unfolded beside him, movements economical, the baker watching from the door",
  "WS", "eye", "static", "day", False, False,
  "ты перебираешь узел на месте, из подручного, потому что запчасть ждать неделю, а хлеб — нет.",
  "his economical hands work the opened unit over the unfolded trays",
  "TOOLBOX"),
 ("A10_SH07", None, "bakery",
  "the dough mixer running smooth and quiet, dough folding evenly in the bowl, flour dust settling",
  "ECU", "eye", "static", "day", False, False,
  "через два часа тестомес идёт ровно, как метроном, и пекарня выдыхает всей сменой.",
  "dough folds evenly in the turning bowl as the last dust settles"),
 ("A10_SH08", "STEPAN_BASE", "bakery",
  "the baker presses warm bread and an envelope on Stepan, who takes the bread and half-argues about the envelope",
  "MS", "eye", "static", "day", False, False,
  "хозяйка суёт тебе конверт и горячую буханку, и от второй отказаться труднее.",
  "the warm loaf passes into his hands as the envelope hovers between them"),
 ("A10_SH09", "STEPAN_BASE", "bakery",
  "the owner shows Stepan the backroom equipment row, gesturing at each machine like introducing family",
  "WS", "eye", "static", "day", False, False,
  "потом она ведёт тебя вдоль машин и честно говорит — «мастер нам нужен свой, постоянный».",
  "her open hand introduces each machine down the row as he follows",
  None, "crowd"),
 ("A10_SH10", "STEPAN_BASE", "bakery",
  "Stepan runs his hand along the proofing cabinet edge, the working man's appraisal already half a yes",
  "MCU", "eye", "static", "day", False, False,
  "пятьдесят восемь тысяч и ночные, машины старые и честные — твой профиль до последней сотки.",
  "his hand travels the cabinet edge in a slow appraising line"),
 ("A10_SH11", "STEPAN_BASE", "bakery",
  "Stepan's face saying yes with a single nod, flour in the air catching the warm lamp behind him",
  "CU", "eye", "push_in", "day", False, True,
  "ты соглашаешься одним кивком, потому что горло на всякий случай лучше не пробовать.",
  "his single nod lands as flour drifts through the warm lamp glow"),
 ("A10_SH12", None, None,
  "a warm loaf in paper under a kitchen lamp at home, steam still rising off the crust split",
  "INSERT", "eye", "static", "evening", False, False,
  "дома буханка ещё тёплая, и ты ешь её просто с солью, как в двадцать лет после смены.",
  "steam threads up from the crust split under the home lamp"),
 ("A10_SH13", "STEPAN_BASE", "flat_kitchen",
  "Stepan tells the propped phone the news, standing, shaven, ten years off his face",
  "MCU", "eye", "static", "evening", False, False,
  "алёне ты звонишь сам, не по расписанию, и голос твой она узнаёт не сразу — он молодой.",
  "he talks standing to the propped screen as his hand keeps smoothing the jacket",
  "SMARTPHONE"),
 ("A10_SH14", "ALYONA_BASE", None,
  "Alyona on the call screen with her hand over her mouth, eyes bright, the scarf slipping off one shoulder",
  "CU", "eye", "static", "evening", False, False,
  "дочь молчит секунду, потом говорит «ну наконец-то», и вы оба делаете вид, что она про работу.",
  "her hand presses her mouth as the bright eyes give the rest away"),
]

A11 = [
 ("A11_SH01", None, "bakery",
  "the bakery at five in the morning, ovens glowing, racks of loaves rolling past, the mixer running clean",
  "WS", "eye", "static", "morning", True, False,
  "теперь твой будильник звонит к пяти, и цех у тебя маленький, тёплый и пахнет мукой.",
  "the loaf racks roll past the glowing ovens as the mixer turns its even beat",
  None, "crowd"),
 ("A11_SH02", "STEPAN_BASE", "bakery",
  "Stepan in a clean navy work jacket makes his morning round, palm brushing the mixer, the proofer, the oven rail",
  "MS", "eye", "track", "morning", False, False,
  "обход у тебя прежний — ладонь на каждую машину, и цех прочитан за три минуты.",
  "his palm brushes machine after machine in the old three-minute liturgy"),
 ("A11_SH03", None, None,
  "the feeler gauge fan in the breast pocket of a clean navy jacket, blade figures catching warm light",
  "ECU", "eye", "static", "morning", False, True,
  "щупы живут в нагрудном кармане новой спецовки — на том же месте, что и тридцать восемь лет.",
  "warm light catches the stamped figures as the pocket fan rides a breath",
  "GAUGE"),
 ("A11_SH04", "STEPAN_BASE", "bakery",
  "Stepan shows a young baker how to listen to the mixer with a palm, guiding her hand to the housing",
  "MCU", "eye", "static", "day", False, False,
  "молодую пекаршу ты учишь слушать машину ладонью, и она смеётся, а потом слышит.",
  "his hand guides hers to the housing until her laugh stops mid-breath"),
 ("A11_SH05", None, "flat_kitchen",
  "the kitchen calendar with a circled date and the word pension pencilled in block letters, months ahead",
  "INSERT", "eye", "static", "day", False, False,
  "пенсия приходит через два года ровно по календарю, и ты встречаешь её работающим человеком.",
  "morning light crosses the circled date and its pencilled block word"),
 ("A11_SH06", "STEPAN_BASE", "flat_kitchen",
  "Stepan reads the pension award letter at the table and files it into a folder matter-of-factly, tea steaming",
  "MS", "eye", "static", "day", False, False,
  "письмо о назначении ты читаешь один раз и убираешь в папку — событие, а не спасение.",
  "the letter folds into the folder in one unceremonious motion by the tea"),
 ("A11_SH07", ("DENIS_BASE", "STEPAN_BASE"), "bakery",
  "Denis, older now with a lead-tech badge, visits the bakery, notebook out, Stepan drawing on a flour-dusted table",
  "MS", "eye", "static", "day", False, True,
  "денис приезжает в отпуск с новой должностью и старыми вопросами, и ты рисуешь ему схему прямо по муке.",
  "his finger draws the diagram in the flour dust as the young pen races again"),
 ("A11_SH08", "DENIS_BASE", "bakery",
  "Denis photographs the flour diagram with his phone, grinning, the lead-tech badge swinging forward",
  "CU", "eye", "static", "day", False, False,
  "он фотографирует муку с твоей схемой и говорит, что повесит её в цеху — «для датчиков».",
  "the phone clicks over the flour diagram as the badge swings out"),
 ("A11_SH09", ("STEPAN_BASE", "MIKHALYCH_BASE"), "guard_booth",
  "Stepan and Mikhalych by the booth with tea in the spring sun, the barrier up, both men easy",
  "WS", "eye", "static", "day", False, False,
  "с михалычем вы теперь оба «люди со сменами», и чай в сторожке стал просто чаем.",
  "the two mugs lift in the spring sun as the raised barrier holds its salute"),
 ("A11_SH10", "STEPAN_BASE", "bakery",
  "Stepan's face to the lens in the warm bakery light, flour on one shoulder, steady and unbeaten",
  "CU", "eye", "push_in", "day", False, False,
  "тебя списали за два года до срока, но руки, которые слушают машины, не списываются приказом.",
  "his steady gaze finds the lens as flour drifts off his shoulder"),
 ("A11_SH11", "STEPAN_BASE", "bakery",
  "Stepan turns back to the mixer and lays his palm on it, the frame warm with oven glow around him",
  "MCU", "eye", "static", "day", False, False,
  "подпишись и останься — на этом канале каждую неделю кто-то заново собирает свою жизнь по соткам.",
  "his palm settles back onto the housing as the oven glow warms the frame"),
 ("A11_SH12", None, None,
  "the feeler gauge fan lying beside a warm loaf on a wooden workbench, steam rising past the steel blades",
  "INSERT", "eye", "push_in", "day", False, True,
  "эта история вымышлена, все совпадения случайны — не повторяй чужих ошибок.",
  "steam threads past the steel blades as the loaf cools beside the fan",
  "GAUGE"),
]

if __name__ == "__main__":
    seed_act("A9", PAL_A9, A9)
    seed_act("A10", PAL_A10, A10)
    seed_act("A11", PAL_A11, A11)
