# -*- coding: utf-8 -*-
"""Seed CH16 — Маска нарастает, зеркало льстит (2nd person). Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "cold mirror light, a face setting into a mask while the mirror flatters, unsettling"
SHOTS = [
 ("CH16_SH01", "HEROINE_MID", "bathroom",
  "medium close-up of the heroine gazing into the big mirror, seeing a beauty",
  "MCU","eye","static","mirror_day",False,False,
  "ты смотришь в зеркало и видишь красавицу."),
 ("CH16_SH02", "HEROINE_MID", "bathroom",
  "extreme close-up of her over-done face, forehead like stone, lips unnaturally full",
  "ECU","eye","static","mirror_day",False,True,
  "а лицо уже не двигается, лоб как камень, губы чужие."),
 ("CH16_SH03", None, "street",
  "medium shot of people on the street glancing at her and then looking away uneasily",
  "MS","eye","static","mirror_day",True,False,
  "на улице всё ещё оборачиваются, но уже как-то иначе."),
 ("CH16_SH04", None, "street",
  "close-up of a small child staring and pointing at the mask-like face",
  "CU","eye","static","mirror_day",True,False,
  "ребёнок тычет пальцем, мам, а что у тёти с лицом."),
 ("CH16_SH05", "HEROINE_MID", "street",
  "medium close-up of the heroine not noticing, seeing only what flatters her",
  "MCU","eye","static","mirror_day",False,False,
  "ты не слышишь, ты видишь только то, что тебе льстит."),
 ("CH16_SH06", None, "bathroom",
  "extreme close-up of the home mirror reflecting her, lying back to her sweetly",
  "ECU","eye","push_in","mirror_day",True,False,
  "домашнее зеркало врёт тебе ласково, ты молодая."),
 ("CH16_SH07", None, "cafe",
  "medium shot of old friends exchanging worried looks but staying silent",
  "MS","eye","static","mirror_day",True,False,
  "подруги переглядываются, но молчат, неудобно сказать."),
 ("CH16_SH08", "HEROINE_MID", "family",
  "medium shot of the heroine taking filtered selfies, losing touch with her real face",
  "MS","eye","static","mirror_day",False,False,
  "в телефоне фильтры, и ты совсем теряешь связь с настоящим лицом."),
 ("CH16_SH09", None, "family",
  "extreme close-up of a phone showing a flawless filtered selfie",
  "ECU","top_down","static","mirror_day",True,True,
  "там, в экране, ты по-прежнему безупречна."),
 ("CH16_SH10", "HEROINE_MID", "clinic",
  "medium close-up of the heroine booking yet another procedure",
  "MCU","eye","static","clinic_day",False,False,
  "и ты записываешься снова, ещё капельку, ещё чуть-чуть."),
 ("CH16_SH11", "HEROINE_MID", "bathroom",
  "close-up of the heroine's frozen confident face",
  "CU","eye","static","mirror_day",False,False,
  "тебе кажется, ты побеждаешь само время."),
 ("CH16_SH12", None, "park",
  "wide B-roll of a windy autumn park, leaves stripping from the trees",
  "WS","high","static","mirror_day",True,False,""),
]
if __name__ == "__main__":
    seed_act(16, "mirror_cold", MOOD, "static", "CH16 Mask grows", SHOTS)
