# -*- coding: utf-8 -*-
"""Seed CH03 — Москва, рублёвские особняки. v2: enriched VO + atmosphere. Idempotent."""
from _seed_tiler_act_engine import seed_act

MOOD = "cold grey Moscow daylight against gilded mansion opulence, glossy marble glare, lonely chill"

SHOTS = [
    ("CH03_SH01", None, "mstreet",
     "wide grey wet winter Moscow street, dense traffic and slush, towering luxury billboards, dirty snowbanks, overcast sky, no clear faces",
     "WS", "high", "pan", "moscow_grey", True, False, ""),
    ("CH03_SH02", "BAKHTI", "mansion",
     "the master kneeling on a grand marble staircase of a new mansion, setting a large veined marble slab into place, hands working",
     "MS", "eye", "static", "moscow_day", False, False,
     "в москве я клал мрамор богатым, в их новых трёхэтажных дворцах, каких у нас в долине отродясь не видели."),
    ("CH03_SH03", "BAKHTI", "mansion",
     "extreme close-up of the master's hands tapping a marble slab level with a rubber mallet, checking the seam",
     "ECU", "top_down", "static", "moscow_day", False, True,
     "шов подгонял так, что лезвие не входило, хозяева цокали языком, а цену всё равно сбивали."),
    ("CH03_SH04", "BAKHTI", "mansion",
     "low wide shot of the tiny lone master kneeling at the foot of an enormous gilded marble staircase that towers over him",
     "WS", "low", "static", "moscow_day", False, True,
     "роскошь росла вокруг меня этаж за этажом, а я в ней был меньше плитки под ногами."),
    ("CH03_SH05", None, "mansion",
     "wide shot of a vast empty gilded mansion hall with chandeliers under dust sheets and floor-to-ceiling windows onto a snowy estate, no people",
     "WS", "eye", "push_in", "moscow_day", True, False,
     "пустые залы по триста метров, где никто не жил, только эхо чужих денег гуляло по углам."),
    ("CH03_SH05A", None, "mansion",
     "close-up of ornate gilded moulding and a crystal chandelier wrapped in dust sheets, opulent detail, no people",
     "CU", "low", "static", "moscow_day", True, False,
     "позолота, лепнина, люстры в чехлах, я и слов таких не знал, как это всё называется."),
    ("CH03_SH06", "BAKHTI", "mansion",
     "over the master's shoulder, a wealthy hostess at the doorway wrinkling her nose and pointing down at his feet with disdain",
     "OTS", "over_shoulder", "static", "moscow_day", False, False,
     "хозяйка кривила губы, пусть эти понаехавшие разуваются у порога, не наследят."),
    ("CH03_SH07", None, "mansion",
     "close-up of worn dusty work boots being pulled off at a pristine marble threshold beside polished designer shoes",
     "CU", "high", "static", "moscow_day", False, False,
     "и я снимал стоптанные ботинки и шёл по их мрамору в дырявых носках."),
    ("CH03_SH08", "BAKHTI", "bytovka",
     "medium close-up of the master sitting on his bunk holding up his phone for a video call, a tired warm smile",
     "MCU", "eye", "static", "moscow_night", False, False,
     "а вечером звонил домой, слышал нигору, азиза, и всё это как-то терпелось."),
    ("CH03_SH09", None, "bytovka",
     "insert close-up of a cracked phone screen showing a wife by a half-built house with a fresh new roof going up, no clear face",
     "CU", "eye", "static", "moscow_night", True, False,
     "на мои деньги дома уже клали крышу, и я был от этого по-настоящему счастлив."),
    ("CH03_SH10", None, "bytovka",
     "insert close-up of a pixelated phone screen showing a small boy waving, grown a little since last time, no clear face",
     "CU", "eye", "static", "moscow_night", True, False,
     "азиз рос рывками, от звонка к звонку, я видел его только в телефоне и пропускал всё."),
    ("CH03_SH11", None, "bytovka",
     "wide shot of a cramped workers' cabin, several tired men eating from a shared pot under a single bulb, condensation on the window, faces in shadow",
     "WS", "high", "static", "moscow_night", False, False,
     "нас, мастеров, держали в бытовке по шестеро, на окраине, подальше от чужих глаз."),
    ("CH03_SH12", "BAKHTI", "bytovka",
     "close-up of the master lying on his bunk staring at the ceiling, sleepless",
     "CU", "low", "static", "moscow_night", False, False,
     "понаехавший, чурка, слышал я в спину едва ли не каждый день."),
    ("CH03_SH13", "BAKHTI", "bytovka",
     "extreme close-up of the master's heavily calloused hands resting open in his lap",
     "ECU", "top_down", "static", "moscow_night", False, True,
     "руки мои ценили на вес золота, а меня самого будто и не существовало вовсе."),
    ("CH03_SH13A", "BAKHTI", "bytovka",
     "medium shot of the master at the small cabin window watching snow fall over the alien city at night",
     "MS", "eye", "static", "moscow_night", False, False,
     "я смотрел в окно бытовки на чужой снег и считал дни до дома."),
    ("CH03_SH14", None, "mstreet",
     "wide exterior of a snowy gated Rublyovka estate behind tall fences at dusk, warm windows, cold blue snow, no people",
     "WS", "eye", "static", "moscow_grey", True, False, ""),
    ("CH03_SH15", "BAKHTI", "mansion",
     "the master carrying a heavy offcut of marble across a glittering empty hall, shoulders bowed with fatigue",
     "MS", "eye", "pan", "moscow_day", False, False,
     "я носил их мрамор и строил дома, в которых мне самому не жить никогда."),
    ("CH03_SH16", "BAKHTI", "mansion",
     "close-up of the master's face at a tall window, looking out over grey Moscow rooftops",
     "CU", "eye", "static", "moscow_day", False, False,
     "а каждый кирпич моего дома там, дома, был вот отсюда, из этой чужой холодной роскоши."),
]

if __name__ == "__main__":
    seed_act(3, "moscow_grey_gold", MOOD, "animated", "CH03 Moscow", SHOTS)
