-- bio_plus shots — CODA «Та самая аптека» (10 shots, same January 2026 evening)
BEGIN;

INSERT INTO shots (id, "projectId", "sceneId", "shotCode", "promptFields", "shotType", "cameraAngle", "cameraMove", "storyBeat", "narrativeFunction", "vignetteSlug", "isBroll", "isIconic", "timeOfDay", "paletteKey", "createdAt", "updatedAt")
SELECT gen_random_uuid()::text, p.id, s.id, v.shot_code, v.prompt_fields::jsonb, v.shot_type, v.camera_angle, v.camera_move, v.story_beat, v.narrative_function, v.vignette_slug, v.is_broll, v.is_iconic, v.time_of_day, v.palette_key, NOW(), NOW()
FROM projects p
JOIN scenes s ON s."projectId" = p.id AND s."sceneKey" = 'coda_pharmacy'
CROSS JOIN (VALUES
  ('CD_SH01', $pp${"positivePrompt": "{STYLE}, {PALETTE_CODA}, close-up of {HEROINE_ELENA_AGE_46} standing at dark dormitory room window three-quarter view, face partially illuminated by cool indigo night spilling through glass and faint distant warm orange from pharmacy sign twelve courtyards away (visible through window behind her shoulder), expression neutral and patient no movement, flat cool single-tone on her face — no warm cheek glow no steel hatching no leitmotif lighting recipe, silver cross necklace on outside of blouse catching faint distant warm tint at chain edge, hard ink outline on face hair cross cell-shaded skin in cool single-tone with single warm pixel-tint on chain edge from distant pharmacy, CU eye level locked off 16:9", "negativeRef": "{NEG}", "narrationRu": "Аптека Здоровье работает с восьми утра до десяти вечера, твоей матери за прилавком нет"}$pp$, 'CU', 'eye', 'static', 'final_image', 'character', 'heroine_elena', FALSE, FALSE, 'january_night_2026', 'CODA_indigo_distant'),
  ('CD_SH02', $pp${"positivePrompt": "{STYLE}, {PALETTE_CODA}, wide shot from low angle in dormitory courtyard at night, looking up at dormitory building facade eight storeys snow-dusted concrete, on seventh floor single window lit warm-pale from inside — heroine room — only illuminated window on that side of building, deep indigo winter night sky above, few falling snowflakes captured mid-air, hard ink outline on building grid window light snow streaks cell-shaded color blocks deep indigo sky dark grey concrete grid single warm window square, WS low angle locked off 16:9", "negativeRef": "{NEG}", "narrationRu": "Твоя мать умерла через четыре месяца после переезда в общежитие, инсульт во сне на узкой койке"}$pp$, 'WS', 'low', 'static', 'final_image', 'atmosphere', NULL, TRUE, FALSE, 'january_night_2026', 'CODA_indigo_distant'),
  ('CD_SH03', $pp${"positivePrompt": "{STYLE}, {PALETTE_CODA}, POV shot from heroine perspective looking through dormitory window across dark snowy courtyard at distant horizon, twelve courtyard distances away (about 850 metres) small bright warm-yellow rectangle of Pharmacy Zdorovye illuminated sign on Pervomayskaya 38, between camera and distant sign rows of indigo-shadowed five-storey panel buildings leafless birch tree silhouettes faint streetlamps casting small warm dots along way, faint snowfall in air, hard ink outline on building silhouettes distant pharmacy rectangle streetlamp dots cell-shaded color deep indigo midground scattered tiny warm streetlamp dots single bright distant warm pharmacy sign, POV eye level slow push-in toward distant pharmacy 16:9", "negativeRef": "{NEG}", "narrationRu": "Свету Орлову закрыли на пять лет по статье двести тридцать три, незаконная предпринимательская деятельность"}$pp$, 'POV', 'eye', 'push_in', 'final_image', 'atmosphere', NULL, TRUE, FALSE, 'january_night_2026', 'CODA_indigo_distant'),
  ('CD_SH04', $pp${"positivePrompt": "{STYLE}, {PALETTE_CODA}, extreme close-up of small Orthodox silver cross hanging on thin tarnished silver chain over heroine blue blouse fabric, cross metal surface aged slightly tarnished polished only at points where fingers have touched it over years, each link of chain individually visible in detail blouse weave visible in macro behind, cool indigo window light from frame-right faint distant warm orange from pharmacy sign catching very tip of cross lower arm with tiny warm pixel, hard ink outline on every chain link cross arms blouse weave cell-shaded color tarnished silver cool grey faint warm pixel-catch at cross-tip dark blouse, ECU eye level locked off 16:9 iconic anchor composition", "negativeRef": "{NEG}", "narrationRu": "Виктор Соколовский числится в розыске с февраля, по данным следствия, выехал через Грузию в Стамбул"}$pp$, 'ECU', 'eye', 'static', 'final_image', 'iconic', 'heroine_elena', FALSE, TRUE, 'january_night_2026', 'CODA_indigo_distant'),
  ('CD_SH05', $pp${"positivePrompt": "{STYLE}, {PALETTE_CODA}, close-up of {HEROINE_ELENA_AGE_46} three-quarter view no expression movement, all electric light in room turned off — face illuminated only by deep indigo night through window and very distant warm pharmacy sign, flat cool single-tone on face, silver cross necklace visible at open blouse collar, eyes calm focused on distant horizon out-of-frame, hard ink outline on face cross hair strands cell-shaded skin in cool single-tone only, CU eye level locked off 16:9", "negativeRef": "{NEG}", "narrationRu": "На твоей тумбочке нет ни одной таблетки, на полке у плиты пустой стакан и сухарик в полиэтилене"}$pp$, 'CU', 'eye', 'static', 'final_image', 'character', 'heroine_elena', FALSE, FALSE, 'january_night_2026', 'CODA_indigo_distant'),
  ('CD_SH06', $pp${"positivePrompt": "{STYLE}, {PALETTE_CODA}, medium shot of {HEROINE_ELENA_AGE_46} seated on edge of dormitory bed, back straight hands resting on knees expression patient and still, behind her shoulder visible through window distant warm rectangle of pharmacy sign, NO electric light in room — only indigo night light distant warm pharmacy light through glass, mother silver cross on outside of blouse, hard ink outline on silhouette bed windowsill cell-shaded color cool indigo room distant warm rectangle small in background, MS eye level locked off 16:9", "negativeRef": "{NEG}", "narrationRu": "Узла в груди больше нет, на его месте тихая пустая пропасть, точно по центру груди"}$pp$, 'MS', 'eye', 'static', 'final_image', 'character', 'heroine_elena', FALSE, FALSE, 'january_night_2026', 'CODA_indigo_distant'),
  ('CD_SH07', $pp${"positivePrompt": "{STYLE}, {PALETTE_CODA}, close-up of {HEROINE_ELENA_AGE_46} in profile facing right (toward window), on right side of frame soft-focus distant warm pharmacy rectangle through window glass, profile catches both cool indigo from window and faint warm pharmacy spill on cheekbone — but warm spill is minimal only enough to register as thin warm pixel-line along cheek contour, hard ink outline on profile jaw line mole eyelash edge cell-shaded skin in two-tone with cool dominant and faint distant warm pixel-edge, CU eye level locked off 16:9", "negativeRef": "{NEG}", "narrationRu": "Из окна общежития виден дальний жёлтый прямоугольник аптеки за двенадцать дворов"}$pp$, 'CU', 'eye', 'static', 'final_image', 'character', 'heroine_elena', FALSE, FALSE, 'january_night_2026', 'CODA_indigo_distant'),
  ('CD_SH08', $pp${"positivePrompt": "{STYLE}, {PALETTE_CODA}, close-up still composition of {HEROINE_ELENA_AGE_46} from same angle as CD_SH07 but focus rack now shifted away from her face, her face goes into soft focus and distant pharmacy rectangle through window glass comes into sharp focus, warm yellow electrified sign visible in detail small distant cyrillic letterforms АПТЕКА ЗДОРОВЬЕ on sign fluorescent tube of sign-housing, flat cool dormitory light on her soft-focus face, hard ink outline now sharp on distant pharmacy sign and soft on her face cell-shaded color heroine soft-cool-tone pharmacy sharp warm-yellow, CU eye level locked off with focus rack shift 16:9", "negativeRef": "{NEG}", "narrationRu": "Между окном общежития и аптекой Здоровье восемнадцать лет и семнадцать минут пешком"}$pp$, 'CU', 'eye', 'static', 'final_image', 'iconic', 'heroine_elena', FALSE, TRUE, 'january_night_2026', 'CODA_indigo_distant'),
  ('CD_SH09', $pp${"positivePrompt": "{STYLE}, {PALETTE_CODA}, close-up pushing in slowly on {HEROINE_ELENA_AGE_46} face three-quarter view, eyes calm gaze on distant pharmacy out-of-frame lips slightly parted but no breath movement, deep indigo night light faint distant warm orange edge-light on cheekbone (from pharmacy sign she looking at — minimal just registering), silver cross necklace visible, ABSOLUTE STILLNESS in composition — no movement no expression change, hard ink outline on face cross hair cell-shaded skin in cool single-tone with minimal warm pixel-edge, CU eye level slow push-in 16:9 iconic final-look composition", "negativeRef": "{NEG}", "narrationRu": "Внизу под окном идёт первый трамвай в шесть утра, по крыше трамвая лежит мокрый снег"}$pp$, 'CU', 'eye', 'push_in', 'final_image', 'iconic', 'heroine_elena', FALSE, TRUE, 'january_night_2026', 'CODA_indigo_distant'),
  ('CD_SH10', $pp${"positivePrompt": "{STYLE}, {PALETTE_CODA}, wide shot pulling out slowly from inside dormitory room looking through window into night, in foreground dim interior of room with heroine small silhouette seated on bed at right edge of frame head slightly turned toward window, through window deep indigo courtyard snow falling distant warm-yellow Pharmacy Zdorovye rectangle visible across courtyard distance, no other electric light anywhere in room, hard ink outline on room interior window frame distant pharmacy sign seated heroine silhouette cell-shaded color dark indigo room dark indigo night single distant warm pharmacy rectangle, DISCLAIMER OVERLAY centred on frame in white bold cyrillic typography over image ИСТОРИЯ ВЫМЫШЛЕНА ВСЕ СОВПАДЕНИЯ СЛУЧАЙНЫ text rendered as crisp ink-outlined letterforms, WS eye level slow pull-out 16:9 final iconic composition with text overlay", "negativeRef": "{NEG}", "narrationRu": "Эта история вымышлена, все совпадения с реальными людьми и событиями случайные"}$pp$, 'WS', 'eye', 'pull_out', 'final_image', 'iconic', NULL, TRUE, TRUE, 'january_night_2026', 'CODA_indigo_distant')
) AS v(shot_code, prompt_fields, shot_type, camera_angle, camera_move, story_beat, narrative_function, vignette_slug, is_broll, is_iconic, time_of_day, palette_key)
WHERE p.slug = 'bio_plus';

COMMIT;
