# -*- coding: utf-8 -*-
"""Seed CH16 — Фонтан изнутри + спектакль абсурдной роскоши (viral). Idempotent."""
from _seed_tiler_act_engine import seed_act

MOOD = "eerie coloured fountain-machine glow, absurd opulence, industrial wonder, blue night"

SHOTS = [
    ("CH16_SH01", None, "fountain",
     "wide night shot of the grand ornamental palace fountain terraces, still dark water, sea beyond",
     "WS", "eye", "push_in", "object_night", True, False,
     "ночью я набрёл на нутро их фонтанов."),
    ("CH16_SH02", "BAKHTI", "machine",
     "the master descending a service ladder into a dim underground machine room",
     "MS", "high", "static", "object_night", False, False,
     "под террасой оказался целый подземный зал."),
    ("CH16_SH03", None, "machine",
     "wide low-angle of a cathedral-like vault of huge steel pipes, pumps and coloured-light projectors",
     "WS", "low", "static", "object_night", True, True,
     "целый завод под землёй, и всё ради игрушки."),
    ("CH16_SH04", None, "machine",
     "close-up of a control panel of blinking indicators, valves and labelled switches",
     "CU", "eye", "static", "object_night", True, False,
     "насосы, форсунки, музыка, свет, всё, чтобы вода танцевала."),
    ("CH16_SH05", "BAKHTI", "machine",
     "medium close-up of the master hesitating, a hand hovering over a glowing switch, childlike curiosity",
     "MCU", "eye", "static", "object_night", False, False,
     "у нас, дома, фонтан, это чаша и вода, как слеза."),
    ("CH16_SH06", "BAKHTI", "machine",
     "the master flipping a switch, a low hum rising through the pipes",
     "MS", "eye", "static", "object_night", False, False,
     "я не удержался, тронул один рычаг."),
    ("CH16_SH07", None, "fountain",
     "wide shot of the fountains erupting in jets lit by shifting coloured light against the night",
     "WS", "low", "static", "object_night", False, True,
     "и вода взметнулась, заплясала под цвет и музыку."),
    ("CH16_SH08", "BAKHTI", "fountain",
     "close-up of the master's face washed in the coloured fountain light, a flicker of childlike awe",
     "CU", "eye", "static", "object_night", False, False,
     "красиво, чего уж там, как чужое холодное чудо."),
    ("CH16_SH08A", None, "aqua",
     "wide reveal of the underground aquadisco, a black and gold tiled hall around a sunken pool under a mirrored ceiling with a coloured nightclub dance floor",
     "WS", "high", "push_in", "object_night", True, True,
     "а за стеной открылись бассейны под зеркальным потолком, вот тут они и крутили свою аквадискотеку, дискотеку прямо в воде."),
    ("CH16_SH08B", None, "party",
     "medium shot through a doorway of a plush gold hookah lounge leading to a private casino and a small theatre",
     "MS", "eye", "pan", "object_night", True, False,
     "дальше кальянная, за ней казино, за ним маленький театр, и всё это для одного человека."),
    ("CH16_SH08C", None, "marble",
     "extreme close-up of an absurd gilded golden toilet brush standing in a lavish marble bathroom",
     "ECU", "eye", "push_in", "object_night", True, True,
     "в уборной стоял золочёный ёршик, я не вру, золотой ёршик, он стоил как моя машина дома."),
    ("CH16_SH08D", "BAKHTI", "aqua",
     "wide shot of the master standing tiny and alone amid the gilded opulence of the aquadisco hall",
     "WS", "high", "static", "object_night", False, True,
     "я ходил по этим залам один и считал, сколько моих жизней тут закопано в позолоту."),
    ("CH16_SH10", "BAKHTI", "machine",
     "medium close-up of the master quickly killing the switch, glancing over his shoulder, fearful",
     "MCU", "eye", "static", "object_night", False, False,
     "потом я выключил всё, пока не застукали, и тихо ушёл."),
    ("CH16_SH11", None, "machine",
     "close-up of the dark silent machine room, indicators dimming",
     "CU", "eye", "static", "object_night", True, False,
     "вода тут была не для жажды и не для красоты."),
    ("CH16_SH12", "BAKHTI", "machine",
     "close-up of the master's thoughtful face in the dark, understanding something",
     "CU", "low", "static", "object_night", False, True,
     "а чтобы показать, что у меня даже вода пляшет, как я прикажу."),
]

if __name__ == "__main__":
    seed_act(16, "object_aqua_glow", MOOD, "static", "CH16 Fountain+Luxury", SHOTS)
