# -*- coding: utf-8 -*-
"""optimizer shots: A9 (friday 15:00 — her own script read back), A10 (borsch), A11 (the other side of the table)."""
from _optimizer_engine import seed_act

PAL_A9 = "hard white meeting light, cold grey-green shadow, glass wall glare"
PAL_A10 = "warm night kitchen lamplight, deep blue windows, homely browns"
PAL_A11 = "pale daylight through tall windows, dusty gold air, worn red seats"

A9 = [
 ("A9_SH01", ("KIRILL_BASE", "RITA_BASE"), "client_meeting",
  "Kirill and Rita sit side by side at the oval table, Rita holding a tablet like a shield, the chair opposite already drawn out",
  "WS", "eye", "static", "day", False, False,
  "в переговорке сидят двое — кирилл и рита с планшетом, и стул напротив уже отодвинут.",
  "the drawn-out chair stands waiting while the young woman squares the tablet in her hands"),
 ("A9_SH02", None, None,
  "the white cube tissue box standing to the left of the table setting, a still-water bottle to the right, both exactly placed",
  "ECU", "eye", "static", "day", False, True,
  "салфетки стоят слева, вода справа — всё расставлено по твоим правилам.",
  "the raised tissue sways once in the ventilation and holds its sail",
  "TISSUES"),
 ("A9_SH03", "ELYA_BASE", "client_meeting",
  "Elya lowers herself onto the drawn-out chair, reading the table arrangement in one glance, her face going professionally calm",
  "MCU", "eye", "static", "day", False, False,
  "ты садишься, и картинка складывается сама — по расстановке предметов на столе.",
  "she settles onto the chair and her eyes make one slow pass over the table setting"),
 ("A9_SH04", ("KIRILL_BASE", "ELYA_BASE"), "client_meeting",
  "past Kirill's charcoal shoulder, Elya listens upright, her hands folded on the table in her own prescribed position",
  "OTS", "over", "static", "day", False, False,
  "кирилл говорит, что совет объединяет практики, а живой контакт «уходит в цифровой канал».",
  "her folded hands stay perfectly still on the table through the spoken sentence"),
 ("A9_SH05", "ELYA_BASE", "client_meeting",
  "Elya's face taking the sentence, the calm intact, only her breathing visibly slower and deeper",
  "CU", "eye", "static", "day", False, False,
  "твой отдел выводят за штат целиком — шесть человек и одна легенда практики.",
  "her chest rises in one slow deliberate breath and settles"),
 ("A9_SH06", "RITA_BASE", "client_meeting",
  "Rita reads from the tablet with her eyes held down on it, her turquoise nails tight on its edges, her voice following printed lines",
  "MS", "eye", "static", "day", False, True,
  "рита читает с планшета фразы, и ты узнаёшь каждую — это твоя карточка, слово в слово.",
  "her eyes track the tablet lines while her nails press white on its edges",
  "TABLET"),
 ("A9_SH07", None, None,
  "a clean printed copy of the script card in a clear file on the table, its corners square, the laminate gloss unbroken",
  "ECU", "high", "static", "day", False, False,
  "у копии в файле нет кофейного полукольца, и почему-то именно это бьёт сильнее всего.",
  "the meeting-room light lies flat and even across the clean printed copy",
  "CARD"),
 ("A9_SH08", "RITA_BASE", "client_meeting",
  "Rita falters mid-line, her eyes lifting from the tablet for the first time, a live unscripted pause opening",
  "MCU", "eye", "static", "day", False, False,
  "на третьей фразе рита сбивается и делает паузу — живую, не по шаблону.",
  "her eyes rise slowly from the tablet and her lips part on the unfinished line"),
 ("A9_SH09", "ELYA_BASE", "client_meeting",
  "Elya gives a single small nod across the table, granting permission, her eyes steady and almost kind",
  "CU", "eye", "static", "day", False, False,
  "ты кивком помогаешь ей дочитать, потому что кто-то здесь должен остаться профессионалом.",
  "she gives one small steady nod and her eyes soften by a readable degree"),
 ("A9_SH10", None, None,
  "a printed dismissal order in a clear file on the table, a pen laid across the empty signature line",
  "ECU", "top", "static", "day", False, False,
  "по соглашению сторон тебе выходит три оклада — семьсот восемьдесят тысяч, по твоему же регламенту.",
  "the pen lies balanced across the signature line as the file settles flat",
  "ORDER"),
 ("A9_SH11", "ELYA_BASE", None,
  "her own hand signing the order with one even stroke, the manicure perfect, the cuff of her blazer crisp",
  "POV", "pov", "static", "day", False, False,
  "подпись выходит ровной, как на тысяче чужих приказов до этого.",
  "the pen draws one even signature and lifts cleanly away"),
 ("A9_SH12", ("KIRILL_BASE", "ELYA_BASE"), "client_meeting",
  "Kirill stands and offers his hand across the table, Elya rising to meet it, both perfectly composed, the glass wall bright behind",
  "WS", "eye", "static", "day", False, False,
  "кирилл протягивает руку и говорит «ничего личного, ты же понимаешь механику».",
  "he rises with his hand extended and she comes up to meet it in one motion"),
 ("A9_SH13", "ELYA_BASE", "client_meeting",
  "Elya's firm handshake in close framing, her grip deliberate, her eyes locked on his over the joined hands",
  "MCU", "eye", "static", "day", False, False,
  "ты жмёшь его руку крепко, потому что слабое рукопожатие он записал бы себе в оправдание.",
  "the joined hands hold one firm beat longer than courtesy requires"),
 ("A9_SH14", None, None,
  "a single flat cardboard box being set on a desk, a wholesale stamp visible on its underside flap",
  "INSERT", "eye", "static", "day", False, True,
  "коробку тебе приносят из твоей же оптовой партии — на дне штамп твоего заказа.",
  "the box settles onto the desk and its underside stamp catches the light",
  "BOXES"),
 ("A9_SH15", "ELYA_BASE", "elya_cabinet",
  "Elya packs her office into the box, lowering the orchid pot in first, then two framed letters, her movements even and unhurried",
  "MS", "eye", "static", "day", False, False,
  "в коробку помещаются орхидея, две благодарности в рамках и запасные колготки из ящика.",
  "her hands lower the orchid pot into the box and steady it against the side",
  "ORCHID"),
 ("A9_SH16", "ELYA_BASE", "lift_lobby",
  "Elya waits for the lift with the box balanced on her forearms, watching the floor indicator strip count",
  "WS", "eye", "static", "day", False, False,
  "у лифта ты считаешь этажи на табло, потому что считать — спокойнее, чем думать.",
  "the indicator numbers step down one by one while she stands balancing the box"),
 ("A9_SH17", None, None,
  "a corporate pass card being laid flat on a reception counter by a manicured hand, the lanyard coiled neatly around it",
  "ECU", "eye", "static", "day", False, True,
  "пропуск ты кладёшь на ресепшн сама, не дожидаясь, пока его погасят.",
  "the manicured hand coils the lanyard around the card and withdraws slowly"),
 ("A9_SH18", "ELYA_BASE", "parking",
  "Elya from directly behind walking out of the tower doors with the box, her posture perfect, the afternoon glare swallowing her outline",
  "BACK", "eye", "static", "day", False, False,
  "ты выходишь из башни в четыре часа дня, и сессия заняла ровно четыре с половиной минуты.",
  "she walks out through the doors into the glare at an even unbroken pace"),
]

A10 = [
 ("A10_SH01", "ELYA_BASE", "parking",
  "Elya sits behind the wheel of her parked car, hands resting at ten and two, the key lying on the passenger seat",
  "MS", "eye", "static", "day", False, False,
  "в машине ты сидишь двадцать минут, и ключ так и лежит на пассажирском сиденье.",
  "her hands rest motionless on the wheel while her thumb taps it once"),
 ("A10_SH02", "ELYA_BASE", "parking",
  "Elya's face through the windscreen, dry-eyed and very tired, the tower reflected across the glass over her",
  "CU", "eye", "push_in", "day", False, False,
  "плакать не получается — у тебя слишком много профессиональных знаний об этой стадии.",
  "the tower's reflection slides slowly across the glass over her still face"),
 ("A10_SH03", "ELYA_BASE", None,
  "her own thumb scrolling a phone contact list and stopping on the entry for mother, the call button under it",
  "POV", "pov", "static", "day", False, False,
  "из всех контактов в телефоне ты выбираешь тот, где не нужно формулировать.",
  "the thumb stops its scroll on the contact and hovers a beat before pressing"),
 ("A10_SH04", "GALINA_BASE", "mother_flat",
  "Galina at the stove with the phone at her ear, already reaching for a second plate with her free hand",
  "MCU", "eye", "static", "evening", False, False,
  "мать слушает три секунды и говорит два слова — «приезжай, борщ».",
  "her free hand lifts the second plate down from the shelf while she listens"),
 ("A10_SH05", ("GALINA_BASE", "ELYA_BASE"), "mother_flat",
  "mother and daughter eat soup at the oilcloth table in lamplight, the cardboard box standing by the door, spoons unhurried",
  "WS", "eye", "static", "evening", False, True,
  "вы едите молча, и это первое молчание за годы, в котором тебе не надо работать.",
  "the two spoons rise and dip in an unhurried offset rhythm under the lamp"),
 ("A10_SH06", None, None,
  "two soup plates side by side on oilcloth, a bread slice laid beside the nearer one by an older hand",
  "ECU", "high", "static", "evening", False, False,
  "мать подкладывает хлеб так же, как семь лет назад, только теперь тебе.",
  "the older hand lays the bread slice down and pats the oilcloth once"),
 ("A10_SH07", "GALINA_BASE", "mother_flat",
  "Galina's face across the table, stern kindness and zero triumph in it, lamplight deep in her wrinkles",
  "MCU", "eye", "static", "evening", False, False,
  "она не говорит «я же говорила», и ты благодарна ей за это больше, чем за борщ.",
  "her stern kind face holds level while her hand turns her teacup a quarter"),
 ("A10_SH08", ("ELYA_BASE", "GALINA_BASE"), "mother_flat",
  "Elya talks openly across the table with her hands loose around her cup, Galina listening with her chin on her knuckles",
  "MS", "eye", "static", "night", False, True,
  "ты рассказываешь всё в первый же вечер, и у твоей истории нет семи месяцев тайны.",
  "her loose hands turn the cup slowly as she talks and her mother's knuckles hold her chin"),
 ("A10_SH09", None, None,
  "an older hand covering a younger manicured hand on the oilcloth, both resting still, crumbs beside them",
  "ECU", "eye", "static", "night", False, False,
  "мать накрывает твою руку своей, и её ладонь тяжёлая от тридцати одного года завода.",
  "the older hand settles over the younger and both go perfectly still"),
 ("A10_SH10", "ELYA_BASE", "elya_flat",
  "Elya stands in her flat in morning light in a loose sweater, the day unplanned around her, dust motes in the sun shaft",
  "WS", "eye", "static", "morning", False, False,
  "утром ты просыпаешься без будильника, и в квартире непривычно много дневного света.",
  "dust motes drift through the long sun shaft as she stands loose-shouldered in it"),
 ("A10_SH11", "ELYA_BASE", "elya_flat",
  "Elya writes a day plan at the kitchen island in a notebook, her handwriting round and easy, coffee steaming beside",
  "MCU", "eye", "static", "morning", False, False,
  "по привычке ты пишешь себе план на день, и в нём первый раз нет чужих фамилий.",
  "her pen fills a short easy list while the coffee steam drifts across the page"),
 ("A10_SH12", None, None,
  "the white orchid on a sunny kitchen windowsill, a third bloom open, a measuring cup of water beside the pot",
  "ECU", "eye", "static", "day", False, False,
  "орхидея переезжает на кухонный подоконник и через неделю выпускает третий цветок.",
  "the third bloom nods minutely in the warm air rising from the radiator",
  "ORCHID"),
 ("A10_SH13", "ELYA_BASE", "elya_flat",
  "Elya on the armchair arm with the phone at her ear, listening to an apology, her face settling into something kind",
  "MS", "eye", "static", "evening", False, False,
  "звонит рита, извиняется шёпотом, и ты говоришь ей честно — «ты всё сделала правильно».",
  "she listens with her head tipped and her hand makes one small absolving turn"),
 ("A10_SH14", "ELYA_BASE", "elya_flat",
  "Elya's face after the call, wry and clear-eyed, evening light warm across her",
  "CU", "eye", "static", "evening", False, False,
  "это правда — она всё сделала по карточке, а карточку писала ты.",
  "a wry half-smile forms and settles as the phone lowers from her ear"),
]

A11 = [
 ("A11_SH01", None, "dk_hall",
  "an old house-of-culture hall in pale daylight, rows of worn red seats, a plain table with two chairs on the small stage",
  "EWS", "eye", "static", "day", True, False,
  "через полгода по вторникам ты ведёшь в дк бесплатные разборы резюме для уволенных.",
  "dust hangs in the tall window light over the worn red seats"),
 ("A11_SH02", "ELYA_BASE", "dk_hall",
  "Elya at the plain stage table with printed CVs fanned before her, a scatter of people in coats in the front rows",
  "MS", "eye", "static", "day", False, False,
  "приходят по двадцать человек, и половина сначала сидит в куртках, как на вокзале.",
  "she squares the fanned CVs while coated figures settle into the front rows",
  None, "crowd"),
 ("A11_SH03", "ELYA_BASE", "dk_hall",
  "Elya marks a CV with a red pen while talking to someone across the table, her gestures open and unhurried",
  "MCU", "eye", "static", "day", False, False,
  "ты правишь резюме красной ручкой и учишь говорить «меня сократили» без опущенных глаз.",
  "her red pen underlines a line and turns to point encouragingly across the table"),
 ("A11_SH04", None, None,
  "a printed CV close-up with red margin notes in a round hand, one long employment line underlined twice",
  "ECU", "top", "static", "day", False, False,
  "девятнадцать лет на одном месте — это не приговор, пишешь ты на полях, это актив.",
  "the red pen adds two firm underlines beneath the long employment line"),
 ("A11_SH05", ("ELYA_BASE", "GEROY_MAIN"), "dk_hall",
  "the logistics manager pauses in the hall doorway recognising Elya at the stage table, she already half risen from her chair",
  "WS", "eye", "static", "day", False, True,
  "на третьей встрече ты узнаёшь мужчину с мебельной фабрики раньше, чем он узнаёт тебя.",
  "he stops one beat in the doorway while she rises halfway out of her chair"),
 ("A11_SH06", "GEROY_MAIN", "dk_hall",
  "the logistics manager talks across the stage table, his collar open with the lanyard gone, his weariness settled into something calmer",
  "MCU", "eye", "static", "day", False, False,
  "он говорит, что нашёл место в логистике поменьше, и спрашивает, как у тебя дела.",
  "he talks with his big hands folded and one thumb slowly circling the other"),
 ("A11_SH07", "ELYA_BASE", "dk_hall",
  "Elya's face answering him, the corporate lacquer gone, something plainer and sturdier in its place",
  "CU", "eye", "static", "day", False, False,
  "ты отвечаешь «по-разному», и это самый честный ответ за девять лет.",
  "her plain unlacquered face holds his gaze and a small true smile arrives"),
 ("A11_SH08", ("ELYA_BASE", "GEROY_MAIN"), "dk_hall",
  "Elya and the logistics manager bent together over a CV at the table, her red pen moving, his finger holding a line for her",
  "MS", "high", "static", "day", False, False,
  "полчаса вы вместе правите резюме его сменщика, которого сократили следом.",
  "his finger pins a line on the sheet while her red pen corrects above it"),
 ("A11_SH09", None, "bank_open",
  "the bank floor evenly repopulated with new sparse desks, a large screen on the wall cycling a corporate dashboard",
  "EWS", "high", "static", "morning", True, False,
  "бот в банке тем временем рассылает уведомления сам — по вторникам, в десять утра.",
  "the wall dashboard cycles its slides over the sparse floor in even silence",
  None, "crowd"),
 ("A11_SH10", None, None,
  "the original laminated card with the coffee ring lying in an open desk drawer on a folded scarf, a drawer organiser beside it",
  "INSERT", "eye", "static", "day", False, True,
  "уходя, ты оставила рите настоящую карточку — с кофейным полукольцом, не копию.",
  "the drawer light catches the coffee ring on the laminate as the drawer stands open",
  "CARD"),
 ("A11_SH11", "RITA_BASE", "client_meeting",
  "Rita before a session alone in the meeting room, holding the laminated card in both hands and breathing herself steady",
  "MS", "eye", "static", "day", False, False,
  "рита достаёт её перед сложными разговорами и держит паузы там, где бот не умеет.",
  "she holds the card in both hands and takes one long steadying breath over it",
  "CARD"),
 ("A11_SH12", None, None,
  "a strapped bundle of flat cardboard boxes against the wall of a dark empty office, a cleared desk pale beyond it",
  "INSERT", "low", "push_in", "night", False, True,
  "в тёмном кабинете практики у стены лежит пачка плоских коробок — по девяносто рублей оптом.",
  "a corridor light sweeps slowly across the strapped bundle and lets the dark refill",
  "BOXES"),
 ("A11_SH13", "ELYA_BASE", "dk_hall",
  "Elya's face turned to the lens at the stage table, tired, clear and unafraid, the tall windows bright behind her",
  "MCU", "eye", "push_in", "day", False, False,
  "подпишись и останься — на этом канале каждую неделю кто-то проживает жизнь вместо тебя.",
  "her head turns slowly to the lens and holds there with a level open look"),
 ("A11_SH14", None, "dk_hall",
  "the empty hall after the meeting, chairs at casual angles, a forgotten glove on a front seat, dust in the window light",
  "WS", "eye", "pull_out", "evening", False, False,
  "эта история вымышлена, все совпадения случайны — не повторяй чужих ошибок.",
  "dust drifts through the window light over the casually angled chairs"),
]

if __name__ == "__main__":
    seed_act("A9", PAL_A9, A9)
    seed_act("A10", PAL_A10, A10)
    seed_act("A11", PAL_A11, A11)
