# -*- coding: utf-8 -*-
"""Seed CH20 — Пустое утро, пустая подушка, стыд (HEROINE_YOUNG). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "the empty morning laid bare, shame at dawn, the empty pillow, cold blue light"
SHOTS = [
 ("CH20_SH01", None, "her_room",
  "wide of a grey dawn bedroom, one side of the bed empty again",
  "WS","high","static","dawn",True,False,
  "утро, серый свет, чужая постель или своя, какая разница, рядом снова совсем никого."),
 ("CH20_SH02", "HEROINE_YOUNG", "her_room",
  "medium close-up of her hand reaching to the cold empty half",
  "MCU","eye","static","dawn",False,False,
  "ты просыпаешься и первым делом тянешься рукой на ту половину, а она пуста и холодна."),
 ("CH20_SH03", None, "her_room",
  "extreme close-up of the empty pillow and crumpled sheet",
  "ECU","top_down","static","dawn",True,True,
  "пустая подушка, смятая простыня, и ни записки, ни имени, ни обещания когда-нибудь вернуться."),
 ("CH20_SH04", "HEROINE_YOUNG", "her_room",
  "close-up of the childhood feeling of abandonment flooding back",
  "CU","eye","static","dawn",False,False,
  "и накатывает оно, то самое, из детства, чувство, что тебя снова бросили совсем одну."),
 ("CH20_SH05", "HEROINE_YOUNG", "her_room",
  "medium close-up of the night-queen, morning-orphan truth",
  "MCU","eye","static","dawn",False,True,
  "ночью ты королева, тебя хотят, а утром ты опять брошенная девочка у холодного окна."),
 ("CH20_SH06", None, "street_east",
  "wide of her walking home through a waking grey Berlin, eyes avoiding her",
  "WS","eye","static","dawn",True,False,
  "ты идёшь домой через просыпающийся Берлин, и встречные стыдливо отводят от тебя глаза."),
 ("CH20_SH07", "HEROINE_YOUNG", "street_east",
  "medium close-up of her not recognising her tired reflection",
  "MCU","eye","static","dawn",False,False,
  "ты ловишь своё отражение в стекле и на миг не узнаёшь эту усталую чужую женщину."),
 ("CH20_SH08", "HEROINE_YOUNG", "her_room",
  "close-up of her hollow promise to herself",
  "CU","eye","static","gdr_day",False,False,
  "дома ты обещаешь себе, всё, хватит, завтра начну жить иначе, тихо, по-человечески."),
 ("CH20_SH09", "HEROINE_YOUNG", "her_room",
  "medium close-up of the promise dissolving by evening",
  "MCU","eye","static","gdr_eve",False,False,
  "но к вечеру пустота снова гонит тебя за дверь, и обещание тает, как сигаретный дым."),
 ("CH20_SH10", None, "her_room",
  "extreme close-up of the box holding Andreas's key, untouched",
  "ECU","top_down","static","gdr_eve",True,True,
  "лишь ключ Андреаса лежит в шкатулке, как немой укор всему, что ты могла бы иметь."),
 ("CH20_SH11", None, "street_east",
  "wide B-roll of a grey dawn street, silent",
  "WS","eye","static","dawn",True,False,""),
]
if __name__ == "__main__":
    seed_act(20, "cold_blue", MOOD, "static", "CH20 Empty morning", SHOTS)
