# -*- coding: utf-8 -*-
"""monotown shots: A6 (the regional offer), A7 (the lathe at auction), A8 (the final refusal)."""
from _monotown_engine import seed_act

PAL_A6 = "crossroad amber, evening kitchen warm, cold offer paper white"
PAL_A7 = "auction cold light, lot-number yellow, loading dust"
PAL_A8 = "resolve lamp glow, deep window night, iron and amber"

A6 = [
 ("A6_SH01", "MATVEY_BASE", "matvey_kitchen",
  "Matvey on a call at the kitchen window, listening long, his face working through a big offer",
  "MCU", "eye", "static", "evening", False, False,
  "в октябре звонят с большого завода в области — мастером участка, с переездом.",
  "the long listen works his face at the darkening window"),
 ("A6_SH02", None, None,
  "an offer letter on the kitchen table: a salary line, relocation allowance of two hundred fifty thousand, a start date",
  "ECU", "top", "static", "evening", False, False,
  "в письме всё серьёзно — ставка выше здешней, подъёмные двести пятьдесят тысяч, старт с декабря.",
  "lamplight crosses the allowance line and the start date"),
 ("A6_SH03", ("MATVEY_BASE", "GALYA_BASE"), "matvey_kitchen",
  "Matvey and Galya over the letter, her finger on the relocation line, both doing separate arithmetic",
  "MS", "eye", "static", "evening", False, False,
  "вы читаете письмо вдвоём, и у каждого своя арифметика — у тебя цех, у гали её лежачая мать.",
  "her finger holds the relocation line as two silent arithmetics run"),
 ("A6_SH04", "GALYA_BASE", "matvey_kitchen",
  "Galya speaks her half plainly, hands folded, a nurse's honesty about who cannot be moved",
  "MCU", "eye", "static", "evening", False, False,
  "галя говорит прямо — «маму не перевезти, матвей, а бросить я её не смогу».",
  "her folded hands underwrite the plain spoken half"),
 ("A6_SH05", "MATVEY_BASE", "shop_floor",
  "Matvey walks the single live aisle next morning, seeing it double: as his shop and as a thing already ending",
  "WS", "eye", "track", "morning", False, False,
  "утром ты идёшь по последнему живому пролёту и видишь его двойным зрением — цех и память о цехе.",
  "his double-sighted walk measures the one ringing aisle",
  None, "crowd"),
 ("A6_SH06", ("MATVEY_BASE", "PETROVICH_BASE"), "garage_coop",
  "Petrovich pours tea in his garage, listening to the offer story, his spanner drawing lines on the spool table",
  "MS", "eye", "static", "evening", False, False,
  "петрович выслушивает про область и чертит ключом по катушке — «езжай, боря тут не скажет никто».",
  "the spanner draws its slow lines as the offer story lands"),
 ("A6_SH07", "PETROVICH_BASE", "garage_coop",
  "Petrovich adds his real thought, eyes on the tea: who signs the last clearance sheets if the master leaves",
  "CU", "eye", "static", "evening", False, False,
  "потом добавляет тихо — «только кто мужикам последние обходные подпишет, писарь из области?».",
  "his quiet afterthought rises from the tea to meet the other eyes"),
 ("A6_SH08", "MATVEY_BASE", "overlook",
  "Matvey on the rise with the offer letter folded in his jacket, the town below him breathing its thin smoke",
  "MS", "eye", "static", "day", False, False,
  "с письмом в кармане ты сидишь на пригорке час, и город снизу смотрит на тебя всеми трубами.",
  "the folded letter rides his pocket as the thin smoke breathes below"),
 ("A6_SH09", "SANYA_BASE", None,
  "Sanya on a call arguing warmly for the move, hostel noise behind, gesturing with a canteen fork",
  "CU", "eye", "static", "evening", False, False,
  "саня по телефону голосует за переезд горячо — «батя, тут жизнь, тут смены белые».",
  "his canteen fork conducts the warm argument on the call screen"),
 ("A6_SH10", "MATVEY_BASE", "matvey_kitchen",
  "Matvey writes a reply asking to postpone the decision, the pen slower than his signature ever is",
  "MS", "eye", "static", "night", False, False,
  "ты просишь у области время до весны, и это первая твоя нерешительность за двадцать шесть лет.",
  "the slow pen drafts the postponement under the lamp"),
 ("A6_SH11", None, "town_square",
  "the house of culture with a jobs-fair banner: three stands, two of them from other regions",
  "WS", "eye", "static", "day", False, False,
  "в дк проводят ярмарку вакансий — три стенда, и два из них зовут уехать.",
  "the three stands wait under the banner as coats drift between them",
  None, "crowd"),
 ("A6_SH12", "GALYA_BASE", "town_square",
  "Galya crosses the square from her shift, nodding to patients everywhere — a woman woven into the town",
  "MS", "eye", "track", "day", False, False,
  "галю на площади знает каждый второй — фельдшера из города не пересаживаются.",
  "her crossing nods stitch the square together person by person",
  None, "crowd"),
 ("A6_SH13", ("MATVEY_BASE", "GALYA_BASE"), "five_story",
  "Matvey and Galya on the courtyard bench in coats, the unspoken decision sitting between them like a third person",
  "WS", "eye", "static", "evening", False, False,
  "на лавке вы сидите молча, и решение сидит между вами третьим — уже принятое, ещё не сказанное.",
  "the shared silence holds its third seat between their coats"),
 ("A6_SH14", "MATVEY_BASE", "five_story",
  "Matvey takes Galya's hand on the bench, the answer passing in silence, her head tipping to him",
  "MCU", "eye", "static", "evening", False, True,
  "ты берёшь её руку, и этим всё решено — остаёмся, и цех я догашу сам.",
  "his hand closes over hers as the wordless answer passes"),
 ("A6_SH15", None, "matvey_kitchen",
  "the offer letter refolded into its envelope, set behind the radio — kept, declined, honoured",
  "INSERT", "eye", "static", "night", False, False,
  "письмо из области возвращается в конверт и встаёт за радио — отказ хранят, как награду.",
  "the envelope settles behind the radio in the lamp shadow"),
 ("A6_SH16", None, "overlook",
  "first snow on the rise, the plant below with its one lit band, the bench planks white",
  "WS", "low", "static", "evening", True, False,
  "первый снег ложится на пригорок, и завод внизу держит свою последнюю тёплую полосу.",
  "snow builds on the plank bench over the one-band plant"),
]

A7 = [
 ("A7_SH01", None, "shop_floor",
  "auction lot tags in yellow zip-tied to machines down the shop, numbers in marker, a printed catalogue on a crate",
  "WS", "eye", "static", "day", False, False,
  "в феврале на станки вешают жёлтые бирки лотов — имущество цеха идёт с молотка.",
  "yellow lot tags sway down the rows over the marker numbers",
  None, "crowd"),
 ("A7_SH02", "PETROVICH_BASE", "shop_floor",
  "Petrovich reads the lot tag on his own lathe, his hand closing on the handwheel like on a shoulder",
  "MCU", "eye", "static", "day", False, True,
  "петрович читает бирку на своём станке, и рука сама ложится на маховик, как на плечо.",
  "his hand closes on the polished handwheel under the yellow tag",
  "LATHE"),
 ("A7_SH03", None, None,
  "the clearance sheet with Petrovich's name, the wave list beside it, the foreman line waiting",
  "ECU", "top", "static", "day", False, False,
  "предпоследняя волна забирает петровича — токарь высшего разряда в графе «излишняя численность».",
  "the wave list holds his name over the waiting foreman line",
  "BYPASS"),
 ("A7_SH04", ("MATVEY_BASE", "PETROVICH_BASE"), "shop_floor",
  "Matvey signs Petrovich's clearance sheet with both of them holding the clipboard, a two-man honour guard",
  "MS", "eye", "static", "day", False, False,
  "его обходной вы держите вдвоём, и подпись мастера выходит ровной только со второго захода.",
  "four hands steady the clipboard through the twice-attempted signature",
  "BYPASS"),
 ("A7_SH05", "PETROVICH_BASE", "meeting_dk",
  "Petrovich at the auction in the house of culture raises his hand for his own lathe, defiant and absurd and right",
  "MCU", "eye", "static", "day", False, False,
  "на торгах петрович поднимает руку на собственный станок — лот тридцать девять, начальная цена смешная.",
  "his defiant hand rises for the lot as heads turn along the row",
  None, "crowd"),
 ("A7_SH06", None, "meeting_dk",
  "the auctioneer's gavel over a lot sheet, the hammer falling, a modest figure circled",
  "ECU", "eye", "static", "day", False, False,
  "молоток падает на тридцати одной тысяче — станок уходит своему же токарю.",
  "the gavel lands over the circled modest figure"),
 ("A7_SH07", None, "plant_yard_m",
  "the lathe craned onto a borrowed trailer in the yard, Petrovich steadying it like livestock, men helping free",
  "WS", "eye", "static", "day", False, False,
  "грузят его всем бывшим пролётом, бесплатно, и станок едет через город на прицепе, как призовой бык.",
  "the slung lathe settles onto the trailer under six steadying hands",
  None, "crowd"),
 ("A7_SH08", None, "town_street",
  "the trailer with the lathe rolling down the main street, pedestrians stopping, someone raising a phone, someone a hand",
  "WS", "eye", "track", "day", False, False,
  "через главную улицу станок едет медленно, и город прощается с ним, как с оркестром.",
  "the slow trailer draws raised hands and phones along the papered street",
  None, "crowd"),
 ("A7_SH09", "PETROVICH_BASE", "garage_coop",
  "the lathe backed into the garage, Petrovich levelling it with shims by lantern light, midnight and unhurried",
  "MS", "eye", "static", "night", False, False,
  "в гараже петрович выставляет станину по уровню до полуночи — станок должен стоять, как стоял.",
  "shims tap under the bed as the lantern holds the level bubble",
  "LATHE"),
 ("A7_SH10", "MATVEY_BASE", "garage_coop",
  "Matvey brings a box of tooling saved from the auction lots, setting it by the lathe wordlessly",
  "CU", "eye", "static", "night", False, False,
  "ты приносишь коробку оснастки, спасённой из лотов, и ставишь у станины без объяснений.",
  "the tooling box lands by the bed under his wordless delivery",
  "LATHE"),
 ("A7_SH11", ("MATVEY_BASE", "PETROVICH_BASE"), "garage_coop",
  "the two men drink tea on crates beside the installed lathe, the garage smelling of grease and beginning",
  "MS", "eye", "static", "night", False, True,
  "чай на ящиках у работающего станка — и вы оба молчите о том, что это похоже на начало.",
  "steam shares the lantern light between the crates and the humming lathe",
  "LATHE"),
 ("A7_SH12", None, "shop_floor",
  "the shop with gaps in the rows where sold machines stood, oil shadows marking their outlines",
  "WS", "eye", "static", "day", False, False,
  "в цеху на месте проданных станков остаются масляные тени — контуры точные, как обводка мелом.",
  "oil shadows hold the machine outlines down the gapped rows"),
 ("A7_SH13", "MATVEY_BASE", "shop_floor",
  "Matvey stands in one oil shadow, boots inside the outline, measuring the loss with his body",
  "MS", "high", "static", "day", False, False,
  "ты встаёшь в один из контуров ботинками, и он оказывается ровно в твой рост.",
  "his boots settle inside the oil outline as the shop rings thinner"),
 ("A7_SH14", "RECEIVER_BASE", "plant_gate_m",
  "the receiver at the checkpoint checks off the last removals on his tablet, the pilot-case at heel",
  "CU", "eye", "static", "day", False, False,
  "управляющий закрывает реестр вывоза и впервые за год выглядит довольным — активы оптимизированы.",
  "his stylus closes the register as the pilot-case waits at heel"),
 ("A7_SH15", "GALYA_BASE", "matvey_kitchen",
  "Galya sews a button onto Matvey's work jacket at night, her stitches slow, keeping her hands from other thoughts",
  "MCU", "eye", "static", "night", False, False,
  "галя пришивает тебе пуговицу медленнее, чем умеет, — рукам сейчас нужно простое дело.",
  "her slow stitches walk the button home in the lamp pool"),
 ("A7_SH16", None, "garage_coop",
  "the garage row at night with one door glowing from inside, lathe sounds escaping into the snow",
  "WS", "eye", "static", "night", True, False,
  "в гаражном ряду светится одна секция, и из-под двери в снег выходит звук резца.",
  "lathe light leaks under the one glowing door into the snow"),
 ("A7_SH17", "MATVEY_BASE", "matvey_kitchen",
  "Matvey marks the shop's remaining headcount in his journal: a two-digit number where thousands lived",
  "MS", "eye", "static", "night", False, False,
  "в журнале мастера остаётся двузначное число там, где когда-то жили тысячи.",
  "his pen sets the two-digit figure under the old thousands"),
 ("A7_SH18", None, None,
  "the brass whistle and the folded offer envelope side by side on the kitchen shelf, two roads in objects",
  "INSERT", "eye", "static", "night", False, False,
  "свисток и конверт из области лежат на полке рядом — две дороги, и выбрана та, что тяжелее.",
  "shelf lamplight bridges the whistle and the declined envelope",
  "WHISTLE"),
]

A8 = [
 ("A8_SH01", "MATVEY_BASE", "matvey_kitchen",
  "Matvey answers the region's follow-up call standing, the deadline offered politely and finally",
  "MCU", "eye", "static", "evening", False, False,
  "весной область звонит второй раз — «решайтесь до пятницы, матвей ильич, место уходит».",
  "the polite deadline lands as he stands into the call"),
 ("A8_SH02", "MATVEY_BASE", "shop_floor",
  "Matvey walks the shop with the phone still warm in his pocket, the last dozen men at the live machines",
  "WS", "eye", "track", "day", False, False,
  "ты идёшь по цеху с тёплым телефоном в кармане, и последняя дюжина работает, не поднимая глаз.",
  "his walk threads the last working dozen down the single aisle",
  None, "crowd"),
 ("A8_SH03", "MATVEY_BASE", "shop_floor",
  "Matvey stops under the glory banner, looking up, the answer assembling itself in his face",
  "CU", "low", "push_in", "day", False, True,
  "под «славой труду» ты останавливаешься, и ответ собирается сам — кто-то должен погасить цех правильно.",
  "the fringe stirs above as the answer sets into his upturned face",
  "BANNER"),
 ("A8_SH04", ("MATVEY_BASE", "GALYA_BASE"), "matvey_kitchen",
  "Matvey tells Galya the decision, and she lays her hand over the whistle at his chest and nods once",
  "MCU", "eye", "static", "evening", False, True,
  "галя кладёт ладонь на свисток у тебя на груди и кивает — она выбрала то же самое раньше тебя.",
  "her palm covers the whistle as the single nod seals it",
  "WHISTLE"),
 ("A8_SH05", "MATVEY_BASE", None,
  "his own hand writing the refusal reply, thanking, declining, the handwriting steady as a weld seam",
  "POV", "pov", "static", "evening", False, False,
  "отказ ты пишешь от руки — благодарю, остаюсь, дела здесь, — и почерк ровный, как шов.",
  "the steady hand walks the refusal across the page"),
 ("A8_SH06", "SANYA_BASE", None,
  "Sanya on the call taking the refusal hard, then quiet, then asking one grown question",
  "CU", "eye", "static", "evening", False, False,
  "саня сначала вскидывается, потом молчит, потом спрашивает по-взрослому — «а после цеха что, батя?».",
  "the grown question settles his young face on the call screen"),
 ("A8_SH07", "MATVEY_BASE", "matvey_kitchen",
  "Matvey answers his son honestly at the propped phone, the after-plan thinner than his voice admits",
  "MCU", "eye", "static", "evening", False, False,
  "ты отвечаешь честно — «после цеха посмотрим», — и оба слышите, какой это тонкий лёд.",
  "his honest answer crosses to the propped screen on thin ice"),
 ("A8_SH08", ("MATVEY_BASE", "PETROVICH_BASE"), "garage_coop",
  "Petrovich hears about the refusal, nods slowly, and pushes a mug of tea across the spool table",
  "MS", "eye", "static", "evening", False, False,
  "петрович выслушивает про отказ, кивает и двигает тебе кружку — в гаражах это принятие в братство.",
  "the pushed mug crosses the spool table under the slow nod"),
 ("A8_SH09", None, "garage_coop",
  "a second garage door standing open down the row, a workbench visible, another laid-off machinist setting up",
  "WS", "eye", "static", "day", False, False,
  "в ряду открывается вторая секция — ещё один цеховой ставит себе верстак.",
  "the second door stands open on the forming workbench",
  None, "crowd"),
 ("A8_SH10", None, None,
  "a region job portal on a phone: the foreman vacancy marked as closed, a grey checkmark",
  "ECU", "eye", "static", "night", False, False,
  "в пятницу вакансия в области закрывается серой галочкой — окно захлопнулось, как ты и решил.",
  "the grey checkmark seals the closed vacancy on the lit screen"),
 ("A8_SH11", "MATVEY_BASE", "overlook",
  "Matvey on the rise watches the plant's one lit band, his choice sitting straight on his shoulders",
  "MS", "eye", "static", "night", False, False,
  "с пригорка ты смотришь на последнюю тёплую полосу окон и несёшь свой выбор ровно.",
  "the one lit band holds below as his shoulders carry the choice"),
 ("A8_SH12", "GALYA_BASE", "town_square",
  "Galya at the ambulatory point calms an old patient, her voice the town's remaining institution",
  "MCU", "eye", "static", "day", False, False,
  "галя успокаивает стариков на площади голосом — из городских учреждений он работает надёжнее всех.",
  "her calming voice settles the old shoulders before her",
  None, "crowd"),
 ("A8_SH13", None, "shop_floor",
  "an official notice on the shop board: final production stop date, the receiver's signature, a month away",
  "ECU", "eye", "static", "day", False, True,
  "на доске появляется дата полной остановки — через месяц, подпись управляющего.",
  "the stop-date notice hangs square under the receiver's signature"),
 ("A8_SH14", "MATVEY_BASE", "shop_floor",
  "Matvey reads the date and pockets his glasses slowly, a man given his final work order",
  "MCU", "eye", "static", "day", False, False,
  "ты читаешь дату и убираешь очки медленно — у мастера появился последний наряд.",
  "the glasses fold away as the final order settles in"),
 ("A8_SH15", ("MATVEY_BASE", "PETROVICH_BASE"), "garage_coop",
  "the two men sketch an artel plan on kraft paper: seven names, a lathe, a welder, small honest work listed",
  "MS", "eye", "static", "evening", False, False,
  "на крафте вы пишете семь фамилий и столбик работ — петли, ограды, теплицы, ремонт.",
  "the kraft sheet fills with seven names and the honest column"),
 ("A8_SH16", None, None,
  "the kraft plan pinned to the garage wall with a magnet, the lathe humming beside it",
  "INSERT", "eye", "static", "evening", False, False,
  "план артели висит на магните у станка — семь человек, и это уже штатное расписание.",
  "the magnet pins the seven-name plan beside the humming lathe",
  "LATHE"),
]

if __name__ == "__main__":
    seed_act("A6", PAL_A6, A6)
    seed_act("A7", PAL_A7, A7)
    seed_act("A8", PAL_A8, A8)
