# -*- coding: utf-8 -*-
"""Seed CH04 — Детство в тени Стены (2nd person). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "grey divided childhood in the wall's shadow, longing for the forbidden other side, cold and yearning"
SHOTS = [
 ("CH04_SH01", None, "street_east",
  "wide of a grey divided East Berlin street under the looming wall",
  "WS","eye","static","gdr_day",True,False,
  "детство твоё проходит в тени стены, в сером городе, где всё лучшее, кажется, по ту сторону."),
 ("CH04_SH02", None, "childhood_flat",
  "medium shot of the cold mother working, no warmth to spare",
  "MS","eye","static","gdr_day",True,False,
  "мать тянет вас одна, озлобленная, и ласки от неё не дождёшься, только работа и упрёки."),
 ("CH04_SH03", None, "school",
  "close-up of a quiet plain girl at a school desk under FDJ banners",
  "CU","eye","static","gdr_day",True,False,
  "в школе ты тихая, незаметная девочка, которой отчаянно хочется, чтобы её наконец увидели."),
 ("CH04_SH04", None, "courtyard",
  "medium of children getting attention in the courtyard while one girl watches apart",
  "MS","eye","static","gdr_day",True,False,
  "ты смотришь, как другим достаётся внимание и тепло, и внутри растёт жадный голодный пустырь."),
 ("CH04_SH05", None, "the_wall",
  "extreme close-up of imagined western light glowing beyond the wall's edge",
  "ECU","eye","static","night",True,False,
  "по ту сторону, говорят, огни, музыка, красивые мужчины, и ты грезишь о запретном Западе."),
 ("CH04_SH06", None, "childhood_flat",
  "close-up of a girl studying herself in a shard of mirror",
  "CU","eye","static","gdr_day",True,False,
  "ты подолгу разглядываешь себя в осколке зеркала, гадая, заметят ли тебя когда-нибудь."),
 ("CH04_SH07", None, "street_east",
  "medium of a growing teenage girl as a stranger's gaze lingers on her",
  "MS","eye","static","gdr_day",True,False,
  "годы идут, ты вытягиваешься, и однажды на улице чужой мужчина задерживает на тебе взгляд."),
 ("CH04_SH08", None, "childhood_flat",
  "extreme close-up of her changing reflection in the mirror shard",
  "ECU","eye","static","gdr_day",True,False,
  "что-то меняется, ты больше не пустое место, в тебе появляется то, на что оборачиваются."),
 ("CH04_SH09", None, "the_wall",
  "wide of the grey wall standing over the city again",
  "WS","eye","static","gdr_day",True,True,
  "а стена всё стоит, и тоска по той стороне намертво срастается в тебе с тоской по любви."),
 ("CH04_SH10", None, "courtyard",
  "close-up of a teenage girl alone in the grey courtyard, a hard resolve",
  "CU","eye","static","gdr_day",True,False,
  "ты клянёшься себе, что вырвешься из этой серости, что тебя будут хотеть и добиваться."),
 ("CH04_SH11", None, "street_east",
  "wide B-roll of a grey East Berlin street at dusk, silent",
  "WS","eye","static","gdr_eve",True,False,""),
]
if __name__ == "__main__":
    seed_act(4, "wall_concrete", MOOD, "static", "CH04 Shadow of wall", SHOTS)
