# -*- coding: utf-8 -*-
"""Seed CH20 — Соперница, он ушёл к молодой (2nd person). RIVAL debut. Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "cold restaurant and street light, the marriage ending, bitter recognition"
SHOTS = [
 ("CH20_SH01", ("HEROINE_MID","HUSBAND"), "family",
  "the heroine on the left frozen, the husband on the right with a packed suitcase announcing he is leaving",
  "MS","eye","static","home_night",False,False,
  "и однажды муж говорит, я ухожу."),
 ("CH20_SH02", "HEROINE_MID", "family",
  "close-up of the heroine stunned, mask-face unable to react",
  "CU","eye","static","home_night",False,True,
  "как, после всего, что я для тебя сделала с собой."),
 ("CH20_SH03", "HUSBAND", "family",
  "medium close-up of the husband not even looking at her, zipping the case",
  "MCU","eye","static","home_night",False,False,
  "он даже не смотрит, молча собирает чемодан."),
 ("CH20_SH04", None, "restaurant",
  "wide shot of the husband at a restaurant with a young woman, seen from across the room",
  "WS","eye","static","restaurant_eve",True,False,
  "а через неделю ты видишь его с ней."),
 ("CH20_SH05", "RIVAL", "restaurant",
  "medium shot of a fresh bleached-blonde young woman of twenty-five, no procedures, glowing",
  "MS","eye","static","restaurant_eve",False,False,
  "молодая, свежая, лет двадцать пять, ни укола, ни морщинки."),
 ("CH20_SH06", "HEROINE_MID", "restaurant",
  "close-up of the heroine staring at the rival, recognising something",
  "CU","eye","static","restaurant_eve",False,False,
  "и ты узнаёшь в ней себя, ту, из девяностых."),
 ("CH20_SH07", None, "restaurant",
  "extreme close-up contrasting the rival's natural young face and the heroine's mask",
  "ECU","eye","static","restaurant_eve",True,True,
  "то, за чем ты гналась шприцами, у неё просто есть, даром."),
 ("CH20_SH08", "HEROINE_MID", "restaurant",
  "medium close-up of the heroine's grim realisation",
  "MCU","eye","static","restaurant_eve",False,False,
  "красоту не удержать, её просто меняют на свежую, понимаешь ты."),
 ("CH20_SH09", None, "restaurant",
  "medium shot of the husband laughing warmly with the young woman",
  "MS","eye","static","restaurant_eve",True,False,
  "он смеётся с ней так, как давно не смеялся с тобой."),
 ("CH20_SH10", "HEROINE_MID", "street",
  "close-up of the heroine standing alone outside, devastated",
  "CU","eye","static","restaurant_eve",False,False,
  "ты стоишь одна, с натянутым лицом."),
 ("CH20_SH11", "HEROINE_MID", "street",
  "extreme close-up of her frozen face, tears that cannot break through",
  "ECU","eye","static","restaurant_eve",False,True,
  "слёзы есть, а лицо не пускает их наружу."),
 ("CH20_SH12", "HEROINE_MID", "bathroom",
  "medium close-up of the heroine at her mirror blaming a lack of beauty, not herself",
  "MCU","eye","static","home_night",False,False,
  "дома ты винишь не себя, а недостаток красоты."),
 ("CH20_SH13", "HEROINE_MID", "bathroom",
  "close-up of the heroine's hardening resolve",
  "CU","eye","static","home_night",False,False,
  "значит, надо ещё, надо лучше, надо вернуть."),
 ("CH20_SH14", None, "family",
  "wide B-roll of the emptied apartment after he has gone",
  "WS","eye","static","home_night",True,False,""),
]
if __name__ == "__main__":
    seed_act(20, "neon_cold", MOOD, "static", "CH20 Rival", SHOTS)
