# -*- coding: utf-8 -*-
"""Seed CH01 — Рождение, Восточный Берлин 1953 (2nd person). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "cold grey 1950s East Berlin light, a joyless birth into a loveless home, austere postwar gloom"
SHOTS = [
 ("CH01_SH01", None, "childhood_flat",
  "wide establishing of a grey austere 1950s East Berlin communal apartment",
  "WS","eye","static","gdr_day",True,False,
  "ты рождаешься весной пятьдесят третьего, в сером Восточном Берлине, в доме, где не умеют обнимать."),
 ("CH01_SH02", None, "childhood_flat",
  "extreme close-up of a newborn in a plain wooden crib under a thin blanket",
  "ECU","top_down","static","gdr_day",True,False,
  "тебя приносят в холодную квартиру, где радости не больше, чем тепла в нетопленой печи."),
 ("CH01_SH03", "MOTHER", "childhood_flat",
  "medium shot of the severe mother looking at the baby without warmth",
  "MS","eye","static","gdr_day",False,False,
  "мать смотрит на тебя устало, ещё один рот, ещё одна забота, ни улыбки, ни нежности."),
 ("CH01_SH04", "FATHER", "childhood_flat",
  "medium close-up of the distant father in his cap turning toward the window",
  "MCU","eye","static","gdr_eve",False,False,
  "отец отворачивается к окну, для него ты лишь шум в и без того тяжёлой, безрадостной жизни."),
 ("CH01_SH05", None, "childhood_flat",
  "close-up of a cold austere kitchen, a coal stove and bare table",
  "CU","eye","static","gdr_day",True,False,
  "в этом доме не целуют на ночь, тут только работают, молчат и терпят, стиснув зубы."),
 ("CH01_SH06", ("MOTHER","FATHER"), "childhood_flat",
  "the mother on the left and the father on the right sitting apart at a table, cold distance between them",
  "WS","eye","static","gdr_eve",False,False,
  "мать и отец сидят за столом порознь, между ними давно остыла любая любовь."),
 ("CH01_SH07", None, "courtyard",
  "wide of a damp grey tenement back-courtyard, soot-stained brick and beaten carpets",
  "WS","high","static","gdr_day",True,False,
  "ты растёшь в сыром дворе-колодце, среди серого кирпича, выбитых ковров и чужих закрытых окон."),
 ("CH01_SH08", None, "childhood_flat",
  "medium close-up of a small child's hands reaching up to be picked up",
  "MCU","eye","static","gdr_day",True,False,
  "совсем крошкой ты тянешь ручки, чтобы тебя взяли, подняли, прижали, но руки не приходят."),
 ("CH01_SH09", "MOTHER", "childhood_flat",
  "close-up of the mother brushing the child aside, busy and cold",
  "CU","eye","static","gdr_day",False,False,
  "не лезь, я занята, говорит мать, и ты усваиваешь, что любовь надо как-то заслужить."),
 ("CH01_SH10", None, "childhood_flat",
  "extreme close-up of a child's hand on a cold bare floor",
  "ECU","top_down","static","gdr_day",True,False,
  "ты ещё не знаешь слова нежность, но уже всем тельцем чувствуешь, как сильно её не хватает."),
 ("CH01_SH11", "FATHER", "street_east",
  "medium shot of the father leaving for work before dawn, back turned, grey street",
  "MS","eye","static","gdr_eve",False,False,
  "отец уходит на завод затемно и приходит затемно, ты почти не видишь его усталого лица."),
 ("CH01_SH12", None, "childhood_flat",
  "wide B-roll of the cold dim home at dusk, empty and still",
  "WS","eye","static","gdr_eve",True,False,""),
]
if __name__ == "__main__":
    seed_act(1, "gdr_grey", MOOD, "static", "CH01 Birth", SHOTS)
