# -*- coding: utf-8 -*-
"""optimizer shots: A6 (the bank project), A7 (automation), A8 (point of no return)."""
from _optimizer_engine import seed_act

PAL_A6 = "vast white bank light, even cold illumination, glass and steel"
PAL_A7 = "cool screen-blue glow, dim office dusk, monitor light on faces"
PAL_A8 = "late amber office light, deep window dusk, warm lamp pools"

A6 = [
 ("A6_SH01", None, "bank_atrium",
  "the glass atrium of a bank tower, crossing escalators, a huge abstract mural, tiny figures on the polished stone floor",
  "EWS", "low", "static", "day", True, False,
  "в ноябре кирилл приводит тебя в банк — стеклянный атриум, эскалаторы, тысяча двести человек в списке.",
  "the escalators glide in opposite directions carrying scattered tiny figures",
  None, "crowd"),
 ("A6_SH02", ("KIRILL_BASE", "ELYA_BASE"), "bank_atrium",
  "Kirill and Elya ride the escalator up side by side, he pointing out floors with his thermo-mug, she scanning upward",
  "MS", "low", "static", "day", False, False,
  "контракт на четырнадцать миллионов, и главный KPI прежний — тишина.",
  "the escalator carries the two upward while his mug tips toward the high floors"),
 ("A6_SH03", "ELYA_BASE", "bank_open",
  "Elya listens at the edge of a glass meeting room, arms holding the tablet to her chest, a row of dark-suited backs before her",
  "MCU", "eye", "static", "day", False, False,
  "правление хочет, чтобы к маю этажи опустели, а в прессе не появилось ни строчки.",
  "her arms tighten a degree around the tablet as the suited backs confer",
  "TABLET"),
 ("A6_SH04", None, "bank_open",
  "a vast bank office floor of identical desks under even white light, hundreds of mugs and small personal objects on them",
  "EWS", "high", "static", "day", False, True,
  "ты выходишь на этаж и видишь не тысячу двести фамилий, а тысячу двести кружек на столах.",
  "the even white light hums over the endless desks while a printer blinks far away",
  None, "crowd"),
 ("A6_SH05", None, None,
  "a desk close-up with a framed photo of a dog, a calendar with days crossed off toward a circled vacation date, a worn mouse pad",
  "ECU", "eye", "static", "day", False, False,
  "на ближнем столе фотография собаки и календарь с зачёркнутыми днями до отпуска.",
  "the calendar page lifts at one corner in the ventilation and settles back"),
 ("A6_SH06", "ELYA_BASE", "bank_open",
  "Elya walks slowly between the desk rows with the tablet lowered, heads staying down over keyboards on both sides",
  "MS", "eye", "track", "day", False, False,
  "ты идёшь между рядами, и головы не поднимаются — тебя здесь ещё никто не знает.",
  "she walks the aisle at a measured pace, her eyes moving desk to desk",
  None, "crowd"),
 ("A6_SH07", "ELYA_BASE", None,
  "her own hands over the tablet, a floor plan divided into coloured waves of two hundred, a stylus tapping a zone",
  "POV", "pov", "static", "day", False, False,
  "в планшете ты делишь этажи на волны — по двести человек в месяц, тише не бывает.",
  "the stylus taps a floor zone and drags it into the next coloured wave",
  "TABLET"),
 ("A6_SH08", "ELYA_BASE", "bank_open",
  "Elya's face lit by the white floor light, a professional's appetite for scale plainly readable in it",
  "CU", "eye", "push_in", "day", False, False,
  "и тебе нравится масштаб задачи, а это самый честный из тревожных признаков.",
  "her eyes travel once across the floor and settle with unmistakable appetite"),
 ("A6_SH09", "ELYA_BASE", "client_meeting",
  "Elya briefs a table of bank HR officers, standing with her fingertips on the table edge, the tissue box demo set before her",
  "WS", "eye", "static", "day", False, False,
  "ты собираешь местных кадровиков и раздаёшь им свои правила, как устав.",
  "her fingertips press the table edge as she leans over the demo arrangement",
  None, "crowd"),
 ("A6_SH10", None, None,
  "a fresh stack of colour-printed copies of the script card on a printer tray, glossy and identical, the top one perfectly clean",
  "INSERT", "eye", "static", "day", False, True,
  "карточку размножают на цветном принтере, и у копий нет кофейного полукольца.",
  "the warm printed copies settle in the tray as one more slides out over them",
  "CARD"),
 ("A6_SH11", ("ELYA_BASE", "RITA_BASE"), "bank_open",
  "Elya hands Rita a project badge across a desk, Rita straightening with the pride of a promotion, her turquoise nails bright on the badge",
  "MS", "eye", "static", "day", False, False,
  "риту ты берёшь в проект старшей, и она заводит себе такую же карточку, только новую.",
  "the badge passes hand to hand and the young woman pins it on with quick fingers"),
 ("A6_SH12", "KIRILL_BASE", "client_meeting",
  "Kirill presents to a row of board members' backs, his thermo-mug on the table, a slide of falling headcount behind him",
  "MCU", "eye", "static", "day", False, False,
  "кирилл обещает правлению «ноль публичности», и правление в ответ обещает ему премиальный фонд.",
  "his hand sweeps along the falling curve on the slide and closes into a soft fist",
  None, "crowd"),
 ("A6_SH13", None, None,
  "a presentation screen close-up with a motivation table, one row highlighted at nine hundred thousand, a laser dot resting on it",
  "ECU", "eye", "static", "day", False, False,
  "твоя строка в мотивации — девятьсот тысяч по закрытии проекта.",
  "the laser dot trembles minutely on the highlighted row"),
 ("A6_SH14", "ELYA_BASE", "elya_cabinet",
  "Elya writes at her desk at night among printed drafts, sleeves pushed up, the orchid a pale shape on the dark sill",
  "WS", "eye", "static", "night", False, False,
  "регламент выходит на сто двадцать страниц, и ты пишешь его три недели по ночам.",
  "her pen fills the margin of a draft page while the desk lamp holds its pool"),
 ("A6_SH15", None, None,
  "a title page in a clear file reading as an official regulation, a subtitle line in small print, a consultancy logo bottom right",
  "ECU", "top", "static", "night", False, False,
  "на титульном листе написано «гуманное высвобождение», и никто не смеётся.",
  "lamplight glides across the clear file as the title page settles"),
 ("A6_SH16", "ELYA_BASE", "elya_cabinet",
  "Elya closes her laptop with both hands in the dark office, her face tired and satisfied, the city lights scattered behind",
  "MCU", "eye", "static", "night", False, False,
  "это лучший документ твоей жизни, и ты подписываешь его собственным именем.",
  "the laptop lid sinks slowly under her two hands until its light dies"),
]

A7 = [
 ("A7_SH01", None, "bank_open",
  "the bank floor with every fifth desk already cleared, flat boxes waiting by the lift block, work continuing around the gaps",
  "WS", "high", "static", "day", True, False,
  "первая волна проходит за месяц — двести человек, ноль публикаций, две благодарности.",
  "figures work on among the cleared gaps while a trolley of boxes rolls past the lifts",
  None, "crowd"),
 ("A7_SH02", "ELYA_BASE", "client_meeting",
  "Elya conducts a session across the oval table, her hand mid-gesture of careful explanation, the tissue box in its exact place",
  "MS", "eye", "static", "day", False, False,
  "ты всё ещё ведёшь сложные случаи сама — предпенсионных, многодетных, злых.",
  "her explaining hand turns palm-up slowly and rests open on the table",
  "TISSUES"),
 ("A7_SH03", "ELYA_BASE", "bank_open",
  "Elya stands behind two seated IT men pointing at a monitor, her arms folding as she reads the interface over their heads",
  "MCU", "eye", "static", "day", False, False,
  "айти-отдел банка предлагает «оптимизировать сам процесс» — бота, который рассылает уведомления.",
  "her arms fold slowly as her eyes track line by line down the screen",
  None, "crowd"),
 ("A7_SH04", None, None,
  "a monitor close-up of a chat-bot template editor, a highlighted paragraph of familiar handwriting-styled phrases pasted into a field",
  "ECU", "eye", "static", "day", False, True,
  "в шаблон бота вставляют фразы с твоей карточки, слово в слово, без пауз.",
  "the text cursor blinks steadily at the end of the pasted paragraph"),
 ("A7_SH05", None, "client_meeting",
  "a demo in a glass meeting room, a projected bot dialogue on the wall screen, applauding silhouettes rimmed by the projector glow",
  "WS", "eye", "static", "day", False, False,
  "на демо бот увольняет условного сотрудника за девяносто секунд, и зал аплодирует экономии.",
  "the projector glow flickers over the applauding silhouettes as the dialogue scrolls",
  None, "crowd"),
 ("A7_SH06", "ELYA_BASE", "client_meeting",
  "Elya's face in the projector's blue wash, the only unclapping stillness in the room, her jaw set",
  "CU", "eye", "static", "day", False, False,
  "ты единственная в зале, кто знает, что паузы там были не лишними.",
  "the blue projector wash flickers across her motionless face"),
 ("A7_SH07", ("RITA_BASE", "ELYA_BASE"), "elya_cabinet",
  "Rita photographs the laminated card on Elya's desk with her phone, grinning, Elya watching with an unreadable half-smile",
  "MS", "eye", "static", "day", False, False,
  "рита фотографирует твою карточку на телефон — «для истории», говорит она.",
  "the phone hovers over the card and the young woman's grin flashes up for approval",
  "CARD"),
 ("A7_SH08", None, None,
  "a ticket-system screen with a shrinking queue of live sessions, most rows marked as handled by the digital channel",
  "ECU", "eye", "static", "day", False, False,
  "живых сессий в графике становится вдвое меньше, и это называется успехом внедрения.",
  "the queue counter ticks down by one as another row greys out"),
 ("A7_SH09", ("RITA_BASE", "ELYA_BASE"), "bank_open",
  "Rita asks Elya a question across their shared desk, her turquoise nails drumming once, Elya answering with a tired steadiness",
  "MS", "eye", "static", "day", False, False,
  "рита спрашивает — «зачем тогда мы?», и ты отвечаешь — «кто-то должен нажимать».",
  "the young woman's nails drum once on the desk and still as the answer lands"),
 ("A7_SH10", None, "bank_open",
  "the bank floor in spring light with desks standing empty in a regular pattern, a cleaner's cart far down the aisle",
  "EWS", "high", "static", "day", True, False,
  "к марту столы на этаже стоят через один, и уборщицы моют пустые ряды быстрее.",
  "the cleaner's cart crawls down the far aisle between the emptied desks",
  None, "crowd"),
 ("A7_SH11", None, None,
  "flat cardboard boxes stacked by the lift block with a printed system label on the top bundle, a barcode corner",
  "INSERT", "eye", "static", "day", False, False,
  "коробки теперь заказывает система сама, автоматически, по числу фамилий в волне.",
  "the lift indicator light slides across the stacked bundles as doors open off frame",
  "BOXES"),
 ("A7_SH12", "ELYA_BASE", "client_meeting",
  "Elya passes the tissue box across the table toward a woman whose shaking shoulders edge the frame, her own face carefully soft",
  "MS", "eye", "static", "day", False, False,
  "сложные случаи всё ещё твои, но их всё меньше — бот не делит людей на сложных.",
  "her hand slides the tissue box slowly across the table toward the shaking shoulders",
  "TISSUES"),
 ("A7_SH13", "ELYA_BASE", "elya_cabinet",
  "Elya's tired face at her desk at dusk, the monitor glow on her cheek, her eyes fixed on a middle distance beyond the screen",
  "CU", "eye", "push_in", "evening", False, True,
  "ты работаешь всё лучше и нужна всё меньше, и эти кривые пересекутся.",
  "the monitor glow flickers once across her still face as her eyes lose focus"),
 ("A7_SH14", "ELYA_BASE", "elya_flat",
  "Elya on the floor of her flat with her back against the armchair, a wine glass beside her, talking toward the orchid on the sill",
  "WS", "eye", "static", "night", False, False,
  "дома ты рассказываешь орхидее про смешное — больше некому, все разговоры под неразглашением.",
  "her hand turns the wine glass slowly by its stem as she talks toward the sill",
  "ORCHID"),
 ("A7_SH15", "KIRILL_BASE", "consult_office",
  "Kirill at a quarterly review lectern glancing at his tablet as he speaks, his praise addressed to the room rather than to anyone",
  "MCU", "eye", "static", "day", False, False,
  "кирилл на итогах квартала называет проект «образцовым» и смотрит при этом в планшет, не на тебя.",
  "his eyes drop to the tablet mid-sentence and lift to the room a beat too late"),
 ("A7_SH16", None, None,
  "a printed satisfaction report page, a large ninety-three percent figure in a green circle, dense method notes below",
  "ECU", "top", "static", "day", False, False,
  "в отчёте пишут, что девяносто три процента уволенных «не имеют претензий», и никто не спрашивает остальных семерых.",
  "lamplight settles on the green circle while the page corner lifts and falls"),
 ("A7_SH17", ("RITA_BASE", "ELYA_BASE"), "lift_lobby",
  "Rita and Elya side by side in the lift lobby, Rita talking up at her with shining ambition, Elya's smile kind and complicated",
  "MS", "eye", "static", "evening", False, False,
  "в лифте рита говорит, что хочет вырасти «как ты», и ты не знаешь, поздравить её или предупредить.",
  "the young woman talks up at her with bright eyes while the lift indicator counts down"),
 ("A7_SH18", None, "consult_office",
  "the city in spring dusk from the glass floor, wet rooftops shining, one tower crane lit red against the afterglow",
  "EWS", "eye", "static", "evening", True, False,
  "весна приходит в город раньше, чем в банк — там всё ещё зима по графику волн.",
  "wet rooftops glisten in the afterglow as single windows warm up across the city"),
]

A8 = [
 ("A8_SH01", "ELYA_BASE", "elya_cabinet",
  "Elya with her phone at her ear turning from the window, surprise arranging itself into caution on her face",
  "MCU", "eye", "static", "day", False, False,
  "в апреле тебе звонят конкуренты — уходи к нам с командой, доля в практике, свобода.",
  "she turns slowly from the window and her free hand finds the desk edge"),
 ("A8_SH02", ("ELYA_BASE",), "client_meeting",
  "past a stranger's tailored shoulder, Elya listens over an untouched espresso, her fingers laced, her eyes weighing",
  "OTS", "over", "static", "day", False, False,
  "они предлагают то, чего у кирилла нет, — твоё имя на двери.",
  "her laced fingers tighten a degree while the untouched espresso steams between them"),
 ("A8_SH03", "ELYA_BASE", "elya_flat",
  "Elya's face at her night window, temptation and loyalty crossing it in turns, city lights scattered in the glass",
  "CU", "eye", "push_in", "night", False, False,
  "ты просишь неделю на подумать, и неделя уходит на уговаривание самой себя остаться.",
  "her reflection in the dark glass steadies as her chin comes up a degree"),
 ("A8_SH04", "ELYA_BASE", "consult_office",
  "Elya stands at the edge of the consultancy floor looking down its length, her people at the desks, a thanks-letter wall behind her",
  "WS", "eye", "static", "day", False, False,
  "здесь твои люди, твои правила и твоя стена с благодарностями клиентов.",
  "she stands still at the floor's edge while her eyes travel slowly down the desks",
  None, "crowd"),
 ("A8_SH05", "KIRILL_BASE", "consult_office",
  "Kirill pours coffee from his steel thermo-mug into a spare cup and slides it across the desk, his eyes warm for once",
  "MCU", "eye", "static", "day", False, True,
  "кирилл говорит «мы — ядро, остальное обвес», и наливает тебе кофе из своей термокружки.",
  "the coffee runs thin and dark from the mug into the cup and he slides it across"),
 ("A8_SH06", None, None,
  "a spare white cup of black coffee on a glass desk, steam rising, a steel thermo-mug standing beside it like a donor",
  "ECU", "eye", "static", "day", False, False,
  "это высшая форма его доверия, и ты приносишь ему отказ конкурентам, как трофей.",
  "steam climbs from the cup in a thin steady rope and bends at the top"),
 ("A8_SH07", "ELYA_BASE", None,
  "her own hands typing a short refusal email on a laptop, the send arrow under the cursor, morning light on the keys",
  "POV", "pov", "static", "morning", False, False,
  "письмо с отказом уходит в пятницу утром — короткое, вежливое, окончательное.",
  "the cursor settles on the send arrow and the fingertip commits it with one tap"),
 ("A8_SH08", None, "bank_open",
  "the bank floor almost empty in may light, a last row of desks occupied near the windows, boxes gone from the lifts",
  "WS", "high", "static", "day", True, False,
  "в мае проект закрывается точно в срок — тысяча двести, ноль строчек в прессе.",
  "the last occupied row works quietly by the windows as a lift chimes far off",
  None, "crowd"),
 ("A8_SH09", None, None,
  "a banking app screen with a bonus line of nine hundred thousand landing, a transfer form already open below it",
  "ECU", "eye", "static", "day", False, False,
  "девятьсот тысяч приходят одной строкой, и ты переводишь треть матери, не спрашивая.",
  "the confirmation tick blooms on the transfer form and fades"),
 ("A8_SH10", "GALINA_BASE", "mother_flat",
  "Galina at her kitchen table with a button phone held at arm's length, typing a reply with one deliberate finger",
  "MS", "eye", "static", "evening", False, False,
  "мать возвращает перевод в тот же вечер с комментарием из одного слова — «работай».",
  "her one finger presses the button phone keys in slow deliberate strokes"),
 ("A8_SH11", "ELYA_BASE", "elya_flat",
  "Elya reads the returned transfer on her phone in the armchair, a laugh and a wince sharing her face",
  "MCU", "eye", "static", "evening", False, False,
  "это её способ сказать, что деньги пахнут, и вы обе делаете вид, что это шутка.",
  "a laugh and a wince cross her face in one motion as the phone lowers"),
 ("A8_SH12", None, None,
  "a boardroom screen with an agenda list, one line reading as internal-functions optimisation among routine items",
  "ECU", "eye", "static", "day", False, False,
  "в июне в повестке совета появляется пункт «оптимизация внутренних функций» — стандартная формулировка.",
  "the agenda line holds steady on the screen as a page indicator blinks below"),
 ("A8_SH13", None, "consult_office",
  "IT engineers wheeling a server rack crate across the consultancy floor, desks pulled aside, cables coiled on the crate lid",
  "WS", "eye", "static", "day", False, False,
  "на ваш этаж заводят тот самый банковский бот — «для внутренних пилотов», говорят айтишники.",
  "the crate rolls slowly between the pulled-aside desks on squeaking castors",
  None, "crowd"),
 ("A8_SH14", "RITA_BASE", "consult_office",
  "Rita at her desk glancing up at someone passing and quickly back to her screen, her turquoise nails still on the keys",
  "MCU", "eye", "static", "day", False, False,
  "рита начинает отводить глаза за неделю до пятницы, и ты списываешь это на усталость.",
  "her glance flicks up and drops back to the screen a beat too fast"),
 ("A8_SH15", None, None,
  "a laptop calendar close-up, a friday meeting slot at fifteen hundred with an empty subject line, the cursor hovering",
  "INSERT", "eye", "static", "day", False, True,
  "в четверг в твоём календаре появляется встреча без темы — пятница, пятнадцать ноль-ноль.",
  "the cursor hovers over the empty subject line and the reminder toggles itself on"),
 ("A8_SH16", "ELYA_BASE", "consult_office",
  "Elya walks the glass corridor toward the meeting room with her tablet and her composure, her reflection keeping step in the glass",
  "CU", "eye", "track", "day", False, False,
  "ты идёшь к переговорке со своим планшетом и своим спокойствием — это же просто встреча.",
  "her reflection keeps step with her in the glass wall as her chin sets level",
  "TABLET"),
]

if __name__ == "__main__":
    seed_act("A6", PAL_A6, A6)
    seed_act("A7", PAL_A7, A7)
    seed_act("A8", PAL_A8, A8)
