# -*- coding: utf-8 -*-
"""Seed CH31 — Что ты потеряла (HEROINE_MID). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "the full weight of what she threw away, cold blue evening grief, honesty breaking through"
SHOTS = [
 ("CH31_SH01", "HEROINE_MID", "her_room",
  "medium of the heroine after the encounter, unable to lie to herself",
  "MS","eye","static","eve",False,False,
  "после встречи с Андреасом что-то ломается, ты больше не можешь врать себе, как раньше."),
 ("CH31_SH02", "HEROINE_MID", "her_room",
  "close-up of her counting not lovers but everything she missed",
  "CU","eye","static","eve",False,False,
  "ты лежишь ночами и считаешь уже не любовников, а всё то, что прошло мимо тебя."),
 ("CH31_SH03", None, "her_room",
  "extreme close-up of Andreas's key in her hand",
  "ECU","top_down","static","eve",True,True,
  "семья, дети, внуки, рука, что держала бы твою в старости, всё это ты отдала сама."),
 ("CH31_SH04", "HEROINE_MID", "her_room",
  "medium close-up of her naming the trade she made",
  "MCU","eye","static","eve",False,False,
  "ты всю жизнь гналась за вспышкой чужого желания и проворонила настоящий, ровный, тёплый огонь."),
 ("CH31_SH05", "HEROINE_MID", "the_wall",
  "medium of her at the trace of the old wall, a hard parallel dawning",
  "MS","eye","static","eve",False,False,
  "ты приходишь туда, где стояла стена, и понимаешь, отец сбежал, а ты повторила его побег."),
 ("CH31_SH06", "HEROINE_MID", "the_wall",
  "close-up of the bitter recognition",
  "CU","eye","static","eve",False,False,
  "он сбежал за бетон, а ты всю жизнь сбегала от каждого, кто пытался тебя полюбить."),
 ("CH31_SH07", None, "park",
  "wide of an empty park bench where Andreas once held her hand",
  "WS","eye","static","eve",True,False,
  "ты сидишь на той самой скамейке в парке, где Андреас когда-то держал тебя за руку."),
 ("CH31_SH08", "HEROINE_MID", "park",
  "medium close-up of her understanding why she fled warmth",
  "MCU","eye","static","eve",False,False,
  "тогда ты сбежала от тепла, потому что тепло требовало впустить, открыться и остаться."),
 ("CH31_SH09", "HEROINE_MID", "her_room",
  "close-up of her facing what she never could do",
  "CU","eye","static","eve",False,False,
  "а ты умела только брать вспышку и бежать, отдать себя по-настоящему ты так и не смогла."),
 ("CH31_SH10", None, "her_room",
  "extreme close-up of the empty pillow, hers by her own hand",
  "ECU","eye","static","eve",True,True,
  "и теперь рядом пусто, и эта пустота, ты наконец признаёшь, дело твоих собственных рук."),
 ("CH31_SH11", None, "the_wall",
  "wide B-roll of the old wall trace at dusk, silent",
  "WS","eye","static","eve",True,False,""),
]
if __name__ == "__main__":
    seed_act(31, "cold_blue", MOOD, "static", "CH31 What you lost", SHOTS)
