# -*- coding: utf-8 -*-
"""best_thing shots: A0 (the kopeck), A1 (flowers on wednesdays), A2 (the outsourcing news)."""
from _best_thing_engine import seed_act

PAL_A0 = "ledger white morning light, spreadsheet glow, crisp paper tones"
PAL_A1 = "warm office daylight, plant green accents, amber window light"
PAL_A2 = "cold news grey, flat corporate light, drained colours"

A0 = [
 ("A0_SH01", None, "office_acc",
  "the accounting office at quarter close, desks buried in printouts, a wall clock over a deadline whiteboard",
  "WS", "eye", "static", "morning", False, False,
  "закрытие квартала, и на обороте в тридцать четыре миллиона не сходится одна копейка.",
  "printouts settle over the desks as the wall clock ticks toward the deadline",
  None, "crowd"),
 ("A0_SH02", None, None,
  "a reconciliation screen with a difference field showing a single kopeck highlighted red",
  "ECU", "eye", "static", "morning", False, False,
  "копейка — это не деньги, это ошибка, а ошибок квартал не прощает.",
  "the red kopeck field blinks its highlight over the balanced columns"),
 ("A0_SH03", "LIDA_BASE", "office_acc",
  "Lida rolls her chair to the problem desk, calm among the panic, pulling the bank statement stack toward herself",
  "MS", "eye", "static", "morning", False, False,
  "паникуют молодые, а ты просто подтягиваешь к себе выписки за квартал.",
  "her chair rolls in and the statement stack slides under her settled hands"),
 ("A0_SH04", "LIDA_BASE", None,
  "her own finger running down a bank statement line by line, a pencil ticking each row, the calculator tape growing",
  "POV", "pov", "static", "morning", False, False,
  "ты идёшь по выписке строка за строкой, и карандаш ставит птички со скоростью чтения.",
  "the pencil ticks row after row as the calculator tape climbs",
  "CALC"),
 ("A0_SH05", None, "office_acc",
  "a second monitor showing the bank-client app frozen on a spinner, a payment deadline timer visible on a sticky note",
  "ECU", "eye", "static", "morning", False, False,
  "тем временем виснет банк-клиент, а до крайнего срока платежей поставщикам — час.",
  "the spinner turns its frozen circle beside the deadline sticky note"),
 ("A0_SH06", "LIDA_BASE", "office_acc",
  "Lida with a phone wedged at her shoulder talks to the bank hotline while her free hand keeps ticking the statement",
  "MCU", "eye", "static", "morning", False, False,
  "с банком ты говоришь по горячей линии, не переставая идти по выписке второй рукой.",
  "the phone rides her shoulder as both tasks run under her split attention"),
 ("A0_SH07", "LIDA_BASE", "office_acc",
  "Lida stops on one line, tapping it twice with the pencil, the quiet smile of a hunter arriving",
  "MCU", "eye", "push_in", "morning", False, True,
  "и вот она — задвоенная комиссия на девятой странице, копейка в копейку.",
  "her pencil taps the found line twice as the quiet smile arrives"),
 ("A0_SH08", None, None,
  "the calculator tape torn off with a figure circled, laid across the statement page like a verdict",
  "INSERT", "top", "static", "morning", False, False,
  "лента калькулятора с обведённой суммой ложится на выписку, как приговор с печатью.",
  "the torn tape settles across the page with its circled figure",
  "CALC"),
 ("A0_SH09", None, "office_acc",
  "the bank-client app coming back to life, a payment queue flushing green row by row",
  "ECU", "eye", "static", "morning", False, False,
  "банк-клиент поднимают за двадцать минут, и платежи уходят зелёной колонной, все в срок.",
  "the payment rows flush green one after another down the revived screen"),
 ("A0_SH10", "LIDA_BASE", "office_acc",
  "colleagues bring Lida tea and a chocolate as tribute, she already tidying the statements into a neat block",
  "MS", "eye", "static", "day", False, False,
  "тебе несут чай и шоколадку, а ты уже собираешь выписки в ровную стопку — порядок дороже почестей.",
  "the tribute tea lands beside her as the statements square into their block",
  None, "crowd"),
 ("A0_SH11", None, "office_acc",
  "an office bouquet drooping in a vase on the windowsill, one stem bent, water cloudy",
  "ECU", "eye", "static", "day", False, False,
  "а на подоконнике тем временем погибает очередной офисный букет — и это тоже твой профиль.",
  "the bent stem sags a degree lower in the cloudy vase water"),
 ("A0_SH12", "LIDA_BASE", "office_acc",
  "Lida opens her desk drawer where the brass garden shears lie among stationery, taking them out with habit",
  "MCU", "eye", "static", "day", False, True,
  "в твоём ящике пятнадцать лет живут бабушкины садовые ножницы — сейчас их выход.",
  "the drawer rolls open and the brass rings catch the light in her reaching hand",
  "SHEARS"),
 ("A0_SH13", "LIDA_BASE", "office_acc",
  "Lida trims the bouquet stems at an angle over a waste bin, quick sure cuts, the vase refilled beside",
  "WS", "eye", "static", "day", False, False,
  "три косых среза, свежая вода, и букет получает ещё неделю жизни — офис зовёт это «среда лиды».",
  "the shears make three quick angled cuts over the bin as the vase waits",
  "SHEARS"),
 ("A0_SH14", "LIDA_BASE", "office_acc",
  "Lida from behind at the windowsill arranging the revived bouquet, the accounting office soft behind her",
  "BACK", "eye", "static", "day", False, False,
  "останься до конца и подпишись — я расскажу, как лучший бухгалтер этажа стала человеком, к которому эта контора ходит за цветами.",
  "her hands settle the revived stems as the office hums soft behind"),
]

A1 = [
 ("A1_SH01", None, "office_acc",
  "the accounting office on an ordinary morning, binders in labelled rows, the windowsill line of office plants thriving",
  "EWS", "eye", "static", "morning", True, False,
  "расчётный отдел — восемь столов, годовые папки по алфавиту и подоконник, который цветёт только у вас.",
  "morning light crosses the thriving sill line over the labelled binders"),
 ("A1_SH02", "LIDA_BASE", "office_acc",
  "Lida works a spreadsheet with the calculator to her right, entries flowing, her amber claw clip catching light",
  "MS", "eye", "static", "day", False, False,
  "пятнадцать лет ты сводишь этой сети зарплаты и отпускные, и сходится у тебя всегда.",
  "her fingers walk the big keys as the entries flow down the sheet",
  "CALC"),
 ("A1_SH03", ("TOMA_BASE", "LIDA_BASE"), "office_acc",
  "Toma perches on Lida's desk with tea, mid-gossip, her bright frames flashing, Lida smiling into her monitor",
  "MCU", "eye", "static", "day", False, False,
  "тома сидит на краю твоего стола пятнадцать лет, и новости отдела начинаются с неё.",
  "the bright frames flash with the gossip as tea steam drifts between them"),
 ("A1_SH04", None, None,
  "a wednesday desk calendar page with a small flower doodled in the corner in pen",
  "ECU", "eye", "static", "day", False, False,
  "по средам в отделе цветочный день — так вышло само, лет двенадцать назад.",
  "lamplight settles on the doodled flower in the calendar corner"),
 ("A1_SH05", "LIDA_BASE", "office_acc",
  "Lida rewires a colleague's drooping bouquet: shears, angled cuts, stripped lower leaves, sure floristry in miniature",
  "MS", "eye", "static", "day", False, False,
  "ты перебираешь чужой букет за четыре минуты, и он встаёт, как после отпуска.",
  "her hands strip the lower leaves and reset the stems in quick order",
  "SHEARS"),
 ("A1_SH06", "TOMA_BASE", "office_acc",
  "Toma holds up her revived vase admiring it, calling across the office, laughter off frame",
  "MCU", "eye", "static", "day", False, False,
  "тома поднимает вазу и объявляет отделу — «у лиды не руки, а реанимация».",
  "the lifted vase turns in her hands as the office laughs off frame",
  None, "crowd"),
 ("A1_SH07", "LIDA_BASE", "lida_kitchen",
  "Lida cooks dinner while checking Kolya's homework over his shoulder, the kitchen warm and loud",
  "WS", "eye", "static", "evening", False, False,
  "дома у тебя серёжа, коля и ужин на плите — обычное счастье, которое не замечаешь, пока оно фоном.",
  "the pot steams as she leans over the homework while keeping one hand at the stove"),
 ("A1_SH08", ("SERGEY_BASE", "LIDA_BASE"), "lida_kitchen",
  "Sergey tells a road story with truck-driver gestures, Lida laughing with a towel over her shoulder",
  "MS", "eye", "static", "evening", False, False,
  "серёжа привозит с рейсов истории, и половина из них даже правда.",
  "his road-wide gesture sweeps the kitchen as her laugh bends her over the towel"),
 ("A1_SH09", "KOLYA_BASE", "lida_kitchen",
  "Kolya films the dinner table on his phone for a story, pop-socket grip, headphones around his neck",
  "MCU", "eye", "static", "evening", False, False,
  "коля снимает ужин в сторис, потому что «контент, мам», и вы уже привыкли.",
  "the pop-socket phone pans the table under his practiced thumb"),
 ("A1_SH10", None, "lida_kitchen",
  "a window shelf at home crowded with cuttings in jars, roots visible in the water, labels in neat handwriting",
  "ECU", "eye", "static", "evening", False, False,
  "на твоём подоконнике укореняются черенки в банках, подписанные почерком бухгалтера.",
  "root threads sway in the jar water under the neat labels"),
 ("A1_SH11", "LIDA_BASE", "lida_kitchen",
  "Lida at the evening window trims a cutting with the brass shears, unhurried, a small private ritual",
  "MCU", "eye", "static", "night", False, False,
  "перед сном ты подрезаешь черенки бабушкиными ножницами, и это твои личные десять минут.",
  "the brass shears make one careful cut as the night kitchen settles",
  "SHEARS"),
 ("A1_SH12", None, None,
  "the brass shears lying on the windowsill by the jars, rings toward the lamp, blades dark with plant sap",
  "INSERT", "eye", "static", "night", False, True,
  "ножницам лет шестьдесят — бабушка стригла ими сад, мама — рассаду, ты — офисные букеты.",
  "lamplight rounds the polished rings as sap dries dark on the blades",
  "SHEARS"),
 ("A1_SH13", None, "office_acc",
  "the office at lunch, someone watering the sill plants from a mug, spreadsheets asleep on screens",
  "WS", "eye", "pan_right", "day", True, False,
  "в обед отдел поливает подоконник из кружек, и это лучший регламент компании.",
  "the mug tips its careful stream as screens sleep behind the sill line",
  None, "crowd"),
 ("A1_SH14", "LIDA_BASE", "office_meeting",
  "Lida reports quarter numbers at the meeting table, confident, slides of clean columns behind her",
  "MS", "eye", "static", "day", False, False,
  "на планёрках твои цифры не обсуждают — их принимают, как прогноз погоды от того, кто её делает.",
  "her steady hand turns the slide as the clean columns settle behind",
  None, "crowd"),
 ("A1_SH15", "LIDA_BASE", "office_acc",
  "Lida's content face at her desk in afternoon light, flowers behind her, numbers before her, both in order",
  "CU", "eye", "push_in", "day", False, True,
  "жизнь у тебя сведена, как хороший баланс, — и ты не знаешь, что через месяц её пересчитают.",
  "afternoon light warms her content face between the flowers and the numbers"),
 ("A1_SH16", None, "courtyard_home",
  "the home courtyard at dusk, the rowan tree over the bench, windows lighting up one by one",
  "WS", "low", "static", "evening", True, False,
  "рябина во дворе стоит в первых ягодах — сентябрь, самое ровное время года.",
  "windows warm up the block wall one by one behind the berry-laden rowan"),
]

A2 = [
 ("A2_SH01", None, "office_meeting",
  "the meeting room set for an announcement: HR folders at each seat, water bottles, a projector waiting on a logo",
  "WS", "eye", "static", "day", False, False,
  "в октябре отдел собирают в переговорке, и на столе перед каждым лежит папка.",
  "the folders wait at each seat as the projector hums on its logo",
  None, "crowd"),
 ("A2_SH02", None, "office_meeting",
  "a projected slide reading as accounting function outsourcing, a timeline bar ending at new year",
  "ECU", "eye", "static", "day", False, False,
  "слайд называется «передача учётной функции подрядчику», и полоска на нём кончается новым годом.",
  "the timeline bar holds its end date as the slide light flickers"),
 ("A2_SH03", "LIDA_BASE", "office_meeting",
  "Lida listens with her hands folded on the unopened folder, very still, reading the room instead of the slide",
  "MCU", "eye", "static", "day", False, False,
  "ты слушаешь и первым делом считаешь — восемь столов, восемь семей, десять недель.",
  "her folded hands stay on the sealed folder as her eyes count the room"),
 ("A2_SH04", "TOMA_BASE", "office_meeting",
  "Toma whispers furiously to Lida behind her hand, her bright frames slipping down her nose",
  "MCU", "eye", "static", "day", False, False,
  "тома шепчет за ладонью — «пятнадцать лет, лид, они нас в экселе сократили», — и она права буквально.",
  "her furious whisper bends behind the hand as the frames slip down"),
 ("A2_SH05", None, "office_acc",
  "the office after the announcement, everyone back at desks, the silence of people typing on blind autopilot",
  "WS", "eye", "static", "day", False, False,
  "после собрания все возвращаются к столам и работают — тишина в отделе стоит рабочая и неживая.",
  "keys click in a broken rhythm down the office as screens glow unseen",
  None, "crowd"),
 ("A2_SH06", "LIDA_BASE", "office_acc",
  "Lida waters the sill plants at day's end, steadying herself with the routine, her reflection doubled in the dark window",
  "MS", "eye", "static", "evening", False, False,
  "вечером ты поливаешь подоконник по расписанию — руки заняты, и это сейчас главное их назначение.",
  "the watering stream steadies as her doubled reflection holds the dark glass"),
 ("A2_SH07", ("LIDA_BASE", "SERGEY_BASE"), "lida_kitchen",
  "Lida tells Sergey the news at the kitchen table, his hands going still around his mug mid-story",
  "MS", "eye", "static", "evening", False, False,
  "дома ты говоришь всё сразу, в первый же вечер, — в этой семье новости не выдерживают.",
  "his mug stops mid-lift as the news lands across the table"),
 ("A2_SH08", "SERGEY_BASE", "lida_kitchen",
  "Sergey's broad face working through the arithmetic of mortgage and school, fear arriving honest and unhidden",
  "CU", "eye", "static", "evening", False, False,
  "серёжа считает вслух — ипотека, колина учёба, твоя ставка — и арифметика у него не сходится.",
  "the honest fear crosses his broad face as the sums fall short"),
 ("A2_SH09", "LIDA_BASE", "lida_kitchen",
  "Lida covers his hand with hers across the table, steadier than she feels, the towel still on her shoulder",
  "MCU", "eye", "static", "evening", False, False,
  "ты накрываешь его руку своей и говоришь «прорвёмся», хотя цифры у тебя те же.",
  "her hand settles over his and presses once with borrowed steadiness"),
 ("A2_SH10", None, None,
  "an HR folder open on a kitchen table: a severance sheet with three salaries totalled, a consultation schedule",
  "ECU", "top", "static", "night", False, False,
  "в папке всё по закону — три оклада, двести шестьдесят семь тысяч, и расписание «карьерных консультаций».",
  "lamplight crosses the totalled severance line and the schedule grid"),
 ("A2_SH11", "KOLYA_BASE", "lida_kitchen",
  "Kolya lingers in the kitchen doorway at night, headphones off for once, a teenager reading the room",
  "MCU", "eye", "static", "night", False, False,
  "коля всё слышит через стену, снимает наушники и впервые за год моет посуду без просьбы.",
  "he hovers in the doorway with the headphones down and moves to the sink"),
 ("A2_SH12", "LIDA_BASE", "office_acc",
  "Lida updates her CV at lunch, the form asking skills, her cursor blinking in an empty field",
  "MS", "eye", "static", "day", False, False,
  "ты садишься за резюме, и графа «навыки» смотрит на тебя шире, чем хотелось бы.",
  "the cursor blinks in the empty skills field under her hovering hands"),
 ("A2_SH13", "TOMA_BASE", "office_acc",
  "Toma shows Lida job listings on her phone, scrolling fast, already three interviews booked",
  "CU", "eye", "static", "day", False, False,
  "тома уже разослала резюме по двадцати адресам и зовёт тебя в этот же поезд.",
  "her fast thumb flips listing after listing under the bright frames"),
 ("A2_SH14", None, "office_acc",
  "the wednesday bouquet on the sill standing perfect while the office empties into winter dusk",
  "WS", "eye", "static", "evening", False, False,
  "букет среды стоит идеально, и до нового года ему цвести ещё при вас.",
  "the perfect stems hold their arc as dusk blues the emptying office"),
 ("A2_SH15", "LIDA_BASE", "office_acc",
  "Lida looks at the bouquet, then at her hands, a thought arriving that she puts away like contraband",
  "CU", "eye", "push_in", "evening", False, True,
  "и мысль приходит контрабандой — руки у тебя умеют не только сводить, но её пока рано думать.",
  "her gaze travels from the bouquet to her open hands and holds there"),
 ("A2_SH16", None, "street_market",
  "the street by the covered market at dusk, flower vans unloading buckets under string lights",
  "WS", "eye", "static", "evening", True, False,
  "по дороге домой ты впервые замечаешь, как у рынка разгружают вёдра с цветами.",
  "buckets pass hand to hand off the van under the warming string lights",
  None, "crowd"),
]

if __name__ == "__main__":
    seed_act("A0", PAL_A0, A0)
    seed_act("A1", PAL_A1, A1)
    seed_act("A2", PAL_A2, A2)
