# -*- coding: utf-8 -*-
"""Seed CH02 — Холодный отец (2nd person). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "cold dim 1950s East Berlin home, a child starving for a father's warmth, grey emotional austerity"
SHOTS = [
 ("CH02_SH01", None, "childhood_flat",
  "wide of a small child standing alone in the dim austere flat",
  "WS","eye","static","gdr_day",True,False,
  "ты подрастаешь, и больше всего на свете хочешь, чтобы отец хоть раз посмотрел на тебя с теплом."),
 ("CH02_SH02", "FATHER", "childhood_flat",
  "medium close-up of the father behind a newspaper, ignoring the child",
  "MCU","eye","static","gdr_eve",False,False,
  "но отец вечно где-то далеко, за газетой, за бутылкой, за своим тяжёлым угрюмым молчанием."),
 ("CH02_SH03", None, "childhood_flat",
  "close-up of a child's hands holding up a crayon drawing",
  "CU","eye","static","gdr_eve",True,False,
  "ты тянешь ему рисунок, смотри, папа, смотри, а он лишь молча кивает, не отрывая глаз."),
 ("CH02_SH04", "FATHER", "childhood_flat",
  "medium shot of the father turning his back, a closed door beyond",
  "MS","eye","static","gdr_eve",False,False,
  "и снова спина, снова закрытая дверь, ты привыкаешь любить того, кто тебя совсем не замечает."),
 ("CH02_SH05", None, "courtyard",
  "wide of other fathers in the courtyard tossing their daughters up to the sky",
  "WS","eye","static","gdr_day",True,False,
  "во дворе чужие отцы подкидывают дочек к небу, а ты смотришь со стороны и глотаешь комок."),
 ("CH02_SH06", "MOTHER", "childhood_flat",
  "medium close-up of the cold mother scolding",
  "MCU","eye","static","gdr_day",False,False,
  "у матери для тебя только упрёки, причешись, не егози, не смей позорить нашу семью."),
 ("CH02_SH07", None, "childhood_flat",
  "extreme close-up of a lonely child sitting on the floor",
  "ECU","eye","static","gdr_eve",True,False,
  "ты усваиваешь страшное правило, чтобы тебя заметили, надо что-то делать, просто так не любят."),
 ("CH02_SH08", "FATHER", "kneipe",
  "medium shot of the father slumped at a smoky pub drinking alone",
  "MS","eye","static","night",False,False,
  "по вечерам отец сидит в пивной, и ты понимаешь, дома его держит привычка, а не любовь."),
 ("CH02_SH09", None, "childhood_flat",
  "close-up of a child waiting at a window in the dark",
  "CU","eye","static","gdr_eve",True,False,
  "ты часами ждёшь у окна его шагов, и эта тоска по мужскому теплу останется с тобой навсегда."),
 ("CH02_SH10", None, "childhood_flat",
  "extreme close-up of a cold empty hallway and unlit stove",
  "ECU","eye","static","gdr_eve",True,False,
  "пустой коридор, холодная печь, и маленькая ты, которой так не хватает одного тёплого взгляда."),
 ("CH02_SH11", "FATHER", "street_east",
  "wide B-roll of the father walking away down a grey street, silent",
  "WS","eye","static","gdr_eve",False,False,""),
]
if __name__ == "__main__":
    seed_act(2, "gdr_grey", MOOD, "static", "CH02 Cold father", SHOTS)
