# -*- coding: utf-8 -*-
"""Seed CH36 — Осознание (HEROINE_OLD). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "the full late realization, chased being wanted never letting herself be loved, grey evening clarity"
SHOTS = [
 ("CH36_SH01", "HEROINE_OLD", "old_flat",
  "medium of the heroine in the quiet, the truth finally arriving",
  "MS","eye","static","eve",False,False,
  "дома, в тишине, к тебе приходит то, от чего ты бегала всю жизнь, простая правда о себе."),
 ("CH36_SH02", "HEROINE_OLD", "old_flat",
  "close-up of the core confusion she lived by",
  "CU","eye","static","eve",False,True,
  "ты всю жизнь путала, когда тебя хотят, с тем, что тебя любят, а это совсем не одно и то же."),
 ("CH36_SH03", "HEROINE_OLD", "old_flat",
  "medium close-up of the distinction made clear",
  "MCU","eye","static","eve",False,False,
  "желание это вспышка, оно про того, кто желает, а любовь, она про того, кого впускают."),
 ("CH36_SH04", None, "old_flat",
  "extreme close-up of Andreas's key",
  "ECU","top_down","static","eve",True,True,
  "тебя желали сотни, а впустить любовь ты не дала ни одному, даже своему Андреасу."),
 ("CH36_SH05", "HEROINE_OLD", "old_flat",
  "close-up of her tracing it back to the cold father",
  "CU","eye","static","eve",False,False,
  "холодный отец научил тебя, что любовь надо заслужить телом, и ты поверила в это навсегда."),
 ("CH36_SH06", "HEROINE_OLD", "old_flat",
  "medium close-up of the late correction",
  "MCU","eye","static","eve",False,False,
  "а оказалось, любовь не заслуживают, её просто впускают, открыв ту самую страшную дверь."),
 ("CH36_SH07", None, "old_flat",
  "wide of the empty rooms around her",
  "WS","eye","static","eve",True,False,
  "и теперь, в пустой квартире, ты считаешь уже не мужчин, а годы, прожитые впустую."),
 ("CH36_SH08", "HEROINE_OLD", "old_flat",
  "close-up of freedom turned to loneliness",
  "CU","eye","static","eve",False,False,
  "вся твоя хвалёная свобода обернулась одиночеством, вся твоя власть, пустотой и холодом."),
 ("CH36_SH09", "HEROINE_OLD", "old_flat",
  "medium close-up of the final naming of her prison",
  "MCU","eye","static","eve",False,True,
  "ты не жертва мужчин и не жертва стены, ты пленница той, что построила сама в себе."),
 ("CH36_SH10", None, "old_flat",
  "extreme close-up of the dusty key, the realization too late",
  "ECU","top_down","static","eve",True,False,
  "и это понимание приходит к тебе честным, ясным и непоправимо, безнадёжно поздним."),
 ("CH36_SH11", None, "old_flat",
  "wide B-roll of the grey evening apartment, silent",
  "WS","eye","static","eve",True,False,""),
]
if __name__ == "__main__":
    seed_act(36, "eldritch_grey", MOOD, "static", "CH36 Realization", SHOTS)
