# -*- coding: utf-8 -*-
"""monotown shots: A3 (the clearance sheets), A4 (the town empties), A5 (the horn cancelled)."""
from _monotown_engine import seed_act

PAL_A3 = "farewell industrial light, stamped paper tones, cold shop haze"
PAL_A4 = "fading town colours, papered glass grey, thin daylight"
PAL_A5 = "quiet morning blue, unrung silence tones, pale window light"

A3 = [
 ("A3_SH01", "MATVEY_BASE", "shop_floor",
  "Matvey at the foreman desk with a stack of clearance sheets, signing the first, the man's shoulder waiting at the frame edge",
  "MS", "eye", "static", "day", False, True,
  "обходные твоих людей подписываешь ты — последняя графа, мастер, и очередь к столу тихая.",
  "his pen lands the foreman line as the stack waits under his other hand",
  "BYPASS"),
 ("A3_SH02", None, None,
  "a clearance sheet in close-up: stamps at angles, the foreman signature fresh, a thumb smudge of shop oil in the corner",
  "ECU", "top", "static", "day", False, False,
  "на обходном все печати вразнобой и одно пятно масла — цех расписался по-своему.",
  "the fresh signature dries beside the oil thumb smudge",
  "BYPASS"),
 ("A3_SH03", "MATVEY_BASE", "shop_floor",
  "Matvey shakes hands with a leaving machinist, both grips working double duty for the unsaid",
  "MCU", "eye", "static", "day", False, False,
  "рукопожатий на неделю приходится по тридцать, и каждое длиннее обычного на секунду.",
  "the double-duty grip holds its extra second before releasing"),
 ("A3_SH04", None, "plant_gate_m",
  "the shift board with gaps spreading among the number tags, hooks bare in patches",
  "ECU", "eye", "static", "day", False, False,
  "доска номерков у проходной лысеет пятнами — по ней теперь читают сводки.",
  "bare hooks hold their gaps among the thinning tags"),
 ("A3_SH05", "PETROVICH_BASE", "shop_floor",
  "Petrovich teaches a young machinist his finishing trick, urgently now, knowledge leaving town with every wave",
  "MS", "eye", "static", "day", False, False,
  "петрович учит молодого своей доводке спешно, впрок — знание уезжает из города волнами.",
  "his guiding hand hurries the trick into the younger grip",
  "LATHE"),
 ("A3_SH06", None, "bus_station_m",
  "the bus station with work bags and tool rolls among the luggage, men buying one-way tickets",
  "WS", "eye", "static", "day", False, False,
  "на автовокзале в багаже теперь инструментальные скатки — город продаёт билеты в одну сторону.",
  "tool rolls ride the luggage pile as the ticket window queue shuffles",
  None, "crowd"),
 ("A3_SH07", "MATVEY_BASE", "shop_floor",
  "Matvey re-balances the aisle after the wave: tarpaulins over three more machines, work compressed to the live rows",
  "WS", "eye", "track", "day", False, False,
  "после каждой волны ты сжимаешь цех, как гармонь, — живые ряды к середине, брезент к стенам.",
  "tarpaulins settle over the dead row as the live aisles tighten inward",
  None, "crowd"),
 ("A3_SH08", ("MATVEY_BASE", "PETROVICH_BASE"), "shop_floor",
  "Matvey and Petrovich share tea from the thermos at the lathe, the shop quieter around them by degrees",
  "MS", "eye", "static", "day", False, False,
  "чай у станка вы пьёте вдвоём там, где год назад стояли вшестером.",
  "the thermos pours two cups where six once gathered",
  "LATHE"),
 ("A3_SH09", "GALYA_BASE", "town_square",
  "Galya at the ambulatory point on the square sees a queue grown longer, pressure cuffs working, worry rows deep",
  "WS", "eye", "static", "day", False, False,
  "у гали в амбулатории очередь растёт с каждой волной — давление в городе теперь общее.",
  "the cuff pumps under her steady hands as the queue holds its worry",
  None, "crowd"),
 ("A3_SH10", "MATVEY_BASE", "matvey_kitchen",
  "Matvey at the night kitchen with the shift journal, planning who to shield in the next wave, pencil hovering",
  "MCU", "eye", "static", "night", False, False,
  "по ночам ты решаешь страшную арифметику мастера — кого прикрыть в следующем списке.",
  "the pencil hovers over the journal names in the lamp pool"),
 ("A3_SH11", None, None,
  "the brass whistle hung on the kitchen hook beside the keys, out of place among the household things",
  "INSERT", "eye", "static", "night", False, False,
  "свисток теперь ночует на кухонном крючке — цех перестал быть местом, откуда уходят спокойно.",
  "the whistle sways once on the key hook in the night kitchen",
  "WHISTLE"),
 ("A3_SH12", "RECEIVER_BASE", "plant_yard_m",
  "the receiver oversees loaders craning a mothballed machine onto a flatbed truck, ticking his tablet",
  "MS", "eye", "static", "day", False, False,
  "часть станков уезжает «на другие площадки группы», и обратных адресов у них нет.",
  "his stylus ticks the manifest as the machine settles onto the flatbed",
  None, "crowd"),
 ("A3_SH13", "MATVEY_BASE", "plant_yard_m",
  "Matvey watches the flatbed leave through the gates, his thumb rubbing the whistle flank at his collar",
  "MCU", "eye", "static", "day", False, False,
  "ты провожаешь машины глазами, и большой палец сам трёт бок свистка.",
  "his thumb works the bright flank as the flatbed shrinks in the gates",
  "WHISTLE"),
 ("A3_SH14", None, "shop_floor",
  "the shop at evening: half the lights banded off over the tarpaulin rows, the live half still ringing",
  "WS", "eye", "static", "evening", False, False,
  "свет в цеху теперь включают наполовину, и тьма стоит ровно над брезентом.",
  "the live half rings under its light band as the dark half holds the tarps"),
 ("A3_SH15", "SANYA_BASE", "shop_floor",
  "Sanya welds in the live half, working harder than needed, a son proving the shop still breathes",
  "MS", "eye", "static", "evening", False, False,
  "саня варит за двоих — молодым кажется, что цех можно удержать усилием.",
  "his spark fountain doubles its arc in the live half's ring"),
 ("A3_SH16", "MATVEY_BASE", "shop_floor",
  "Matvey watches his son weld, pride and foreknowledge in one face, the cap shadowing his eyes",
  "CU", "eye", "static", "evening", False, True,
  "ты смотришь на сына и знаешь то, чего ему пока нельзя говорить вслух.",
  "pride and foreknowledge share his shadowed face as the sparks reflect"),
 ("A3_SH17", None, "five_story",
  "the courtyard at dusk with two windows dark that were always lit, a moving van at the far entrance",
  "WS", "eye", "static", "evening", False, False,
  "во дворе гаснут насовсем два окна, и у дальнего подъезда стоит грузовик с вещами.",
  "the moving van swallows boxes as the two dark windows hold their blanks",
  None, "crowd"),
 ("A3_SH18", None, None,
  "a domino piece left on the courtyard bench under first rain, dots up",
  "ECU", "eye", "static", "evening", False, False,
  "на лавке под первым дождём остаётся забытая костяшка домино — дубль пусто.",
  "rain beads gather on the blank double left dots-up"),
]

A4 = [
 ("A4_SH01", None, "town_street",
  "the main street with a third of the shopfronts papered, a pharmacy cross still glowing, foot traffic thinned",
  "EWS", "eye", "static", "day", True, False,
  "к осени бумага закрывает каждую третью витрину, и улица начинает экономить на людях.",
  "thin figures pass the papered fronts under the lone pharmacy cross",
  None, "crowd"),
 ("A4_SH02", None, "town_square",
  "the school on the square with a notice about merged classes taped to its door, bicycles fewer at the rack",
  "ECU", "eye", "static", "day", False, False,
  "в школе сливают два четвёртых класса в один — детям объясняют это словом «оптимизация».",
  "the taped notice stirs at one corner over the thinned bike rack"),
 ("A4_SH03", "GALYA_BASE", "matvey_kitchen",
  "Galya counts the household notebook at the kitchen table, moving sums between columns with a pencil",
  "MCU", "eye", "static", "evening", False, False,
  "галя пересобирает семейную тетрадь — врачебные подработки в плюс, всё лишнее в минус.",
  "her pencil walks sums between the notebook columns"),
 ("A4_SH04", "SANYA_BASE", "matvey_kitchen",
  "Sanya stands at the kitchen door with the regional offer printed out, holding it like both a shield and an apology",
  "MS", "eye", "static", "evening", False, True,
  "саня кладёт на стол распечатку — сварщики нужны в области, общежитие и белая ставка.",
  "the printed offer lands on the table under his shield-and-apology grip"),
 ("A4_SH05", "MATVEY_BASE", "matvey_kitchen",
  "Matvey reads the offer slowly, then looks up at his son with the hardest kind of approval",
  "CU", "eye", "static", "evening", False, False,
  "ты читаешь и говоришь единственно верное — «поезжай», — и это самое дорогое твоё слово за год.",
  "the hard approval lifts from the sheet to the waiting young face"),
 ("A4_SH06", "GALYA_BASE", "matvey_kitchen",
  "Galya turns to the stove to hide her face, stirring an already-finished soup, shoulders squared",
  "MCU", "eye", "static", "evening", False, False,
  "галя мешает суп, которому это не нужно, и спина у неё ровная, как на дежурстве.",
  "the needless stirring holds her squared back to the room"),
 ("A4_SH07", None, "five_story",
  "the courtyard rug frame where a wrestling mat now hangs: someone moving out beats dust for the last time",
  "WS", "eye", "static", "day", False, False,
  "выбивалка во дворе всё чаще прощальная — пыль выбивают перед погрузкой, а не после зимы.",
  "dust clouds off the hung mat toward the waiting boxes",
  None, "crowd"),
 ("A4_SH08", "MATVEY_BASE", "market_town",
  "Matvey at the town market buys from a former crane operator now selling honey, both men steering the talk from the plant",
  "MS", "eye", "static", "day", False, False,
  "на рыночке мёдом торгует бывший крановщик — мёд у него, кстати, честный.",
  "the honey jar passes between them as the plant stays unmentioned",
  None, "crowd"),
 ("A4_SH09", None, "bus_station_m",
  "the timetable board with two departures struck through with tape, the town's transit thinning",
  "ECU", "eye", "static", "day", False, False,
  "с расписания автовокзала снимают два рейса — городу урезают даже дороги из него.",
  "tape strips hold their lines through the struck departures"),
 ("A4_SH10", "PETROVICH_BASE", "garage_coop",
  "Petrovich in his garage tinkers a neighbour's cultivator back to life, tools on a cable-spool table",
  "MS", "eye", "static", "day", False, False,
  "петрович по выходным чинит в гараже соседские культиваторы — руки просят работы вперёд головы.",
  "the cultivator sputters alive under his spool-table surgery"),
 ("A4_SH11", "MATVEY_BASE", "garage_coop",
  "Matvey visits the garage row, drawn by the sound of tools, standing in the door with recognition",
  "MCU", "eye", "static", "day", False, False,
  "ты приходишь на звук инструмента и стоишь в воротах дольше, чем требует вежливость.",
  "the tool sounds hold him in the doorway past politeness"),
 ("A4_SH12", None, "shop_floor",
  "the shop where the live rows have shrunk to one aisle, the banner still hanging over mostly tarpaulin",
  "WS", "low", "static", "day", False, False,
  "живой пролёт в цеху остаётся один, и «слава труду» висит теперь в основном над брезентом.",
  "the banner fringe stirs over the tarpaulin field and the one live aisle"),
 ("A4_SH13", "MATVEY_BASE", "shop_floor",
  "Matvey signs the week's clearance sheets, the stack thinner only because the shop itself is thinner",
  "MS", "eye", "static", "day", False, False,
  "обходных на неделю меньше — не потому что волна мельче, а потому что цех мельче.",
  "his pen works the thinner stack in the emptier shop",
  "BYPASS"),
 ("A4_SH14", ("MATVEY_BASE", "GALYA_BASE"), "town_square",
  "Matvey and Galya walk the evening square, her arm through his, the house of culture dark on a weekday",
  "MS", "eye", "track", "evening", False, False,
  "вечером вы идёте через площадь под руку, и дк стоит тёмный — в будни его больше не топят.",
  "their linked arms cross the square past the dark house of culture"),
 ("A4_SH15", "MATVEY_BASE", "overlook",
  "Matvey alone on the rise at dusk, counting lit windows in the plant bands, fewer each month",
  "CU", "eye", "push_in", "evening", False, False,
  "с пригорка ты считаешь тёплые окна завода, и счёт каждый месяц короче.",
  "his counting gaze travels the thinning window bands below"),
 ("A4_SH16", None, "overlook",
  "the plant panorama with one window band lit of three, smoke from a single chimney, dusk closing",
  "EWS", "high", "static", "evening", True, False,
  "из трёх полос окон горит одна — завод сжимается, как зрачок на ярком свету.",
  "the single lit band holds against the dusk under one working chimney"),
]

A5 = [
 ("A5_SH01", None, None,
  "an order pinned to the horn cabin door: horn signals discontinued for economy, a receiver's signature",
  "ECU", "eye", "static", "day", False, True,
  "приказ вешают на дверь будки — «подачу гудка прекратить в целях экономии энергоресурсов».",
  "the pinned order stirs at its free corner on the cabin door",
  "HORN"),
 ("A5_SH02", "MATVEY_BASE", "horn_room",
  "Matvey reads the order at the cabin, his hand resting on the brass lever like on a coffin edge",
  "MCU", "eye", "static", "day", False, False,
  "ты читаешь приказ, и рука сама ложится на латунный рычаг — попрощаться.",
  "his hand settles on the brass lever through the reading",
  "HORN"),
 ("A5_SH03", None, "five_story",
  "the courtyard at half past seven in the new hornless quiet: windows lighting raggedly, the morning arrhythmic",
  "WS", "eye", "static", "morning", False, False,
  "первое утро без гудка город просыпается вразнобой, и эта рвань страшнее любой сводки.",
  "windows light in ragged disorder across the hornless morning",
  None, "crowd"),
 ("A5_SH04", "GALYA_BASE", "matvey_kitchen",
  "Galya wakes by habit at twenty-nine past seven and lies listening to the silence where the horn lived",
  "CU", "eye", "static", "morning", False, False,
  "галя просыпается в семь двадцать девять по привычке и слушает тишину на месте гудка.",
  "her open eyes hold the ceiling through the unrung half minute"),
 ("A5_SH05", "MATVEY_BASE", "matvey_kitchen",
  "Matvey winds an alarm clock at the kitchen table, setting the town's new ersatz horn for the family",
  "MS", "eye", "static", "evening", False, False,
  "ты заводишь будильник впервые за двадцать шесть лет — гудок теперь личное дело каждого.",
  "the alarm key turns under his thumb in the lamp pool"),
 ("A5_SH06", "SANYA_BASE", "five_story",
  "Sanya loads two bags and a welding mask box into a neighbour's car boot, the courtyard watching from windows",
  "WS", "eye", "static", "morning", False, False,
  "саня грузит две сумки и коробку с маской — всё, что нажил сварщик за четыре года.",
  "the mask box settles into the boot under the watching windows"),
 ("A5_SH07", ("MATVEY_BASE", "SANYA_BASE"), "bus_station_m",
  "father and son at the bus bay, the embrace short and fierce, the driver waiting with the door",
  "MCU", "eye", "static", "morning", False, True,
  "обнимаетесь вы коротко и крепко, по-мужски неумело, и водитель ждёт с открытой дверью.",
  "the short fierce embrace rocks once as the bus door stands open"),
 ("A5_SH08", "GALYA_BASE", "bus_station_m",
  "Galya tucks a food bag into Sanya's hands through the bus window, her medical watch trembling once",
  "CU", "eye", "static", "morning", False, False,
  "галя суёт в окно пакет с едой на три дня пути, хотя пути — четыре часа.",
  "the food bag passes through the window under her trembling watch"),
 ("A5_SH09", None, "bus_station_m",
  "the bus pulling out of the bay, a young hand at the glass, the parents' reflections sliding off the window",
  "WS", "eye", "static", "morning", False, False,
  "автобус выходит из кармана, и ваши отражения съезжают с его окна на асфальт.",
  "the young palm holds the glass as the reflections slide away",
  None, "crowd"),
 ("A5_SH10", ("MATVEY_BASE", "GALYA_BASE"), "bus_station_m",
  "Matvey and Galya stand in the empty bay after the bus, her head finding his shoulder, his cap in his hand",
  "MS", "eye", "static", "morning", False, False,
  "вы стоите в пустом кармане дольше расписания, и город вокруг молчит без гудка особенно.",
  "her head settles onto his shoulder in the emptied bay"),
 ("A5_SH11", None, "town_street",
  "the main street on a hornless weekday noon, quieter than sundays used to be, a dog crossing unhurried",
  "WS", "eye", "static", "day", True, False,
  "будний полдень звучит теперь тише прежнего воскресенья, и собаки переходят улицу без оглядки.",
  "the unhurried dog crosses the quiet street between the papered fronts"),
 ("A5_SH12", "MATVEY_BASE", "shop_floor",
  "Matvey gathers the shift with the brass whistle now — two short — the sound smaller but keeping the shape",
  "MS", "eye", "static", "day", False, False,
  "смену ты собираешь теперь свистком — два коротких, — звук меньше, но порядок тот же.",
  "the two short notes gather the thinned shift around him",
  "WHISTLE"),
 ("A5_SH13", "PETROVICH_BASE", "shop_floor",
  "Petrovich mutters to his lathe as he works, the ear defenders up, keeping the old rhythm privately",
  "MCU", "eye", "static", "day", False, False,
  "петрович работает в глушилках и держит старый ритм внутри — у токарей память в руках.",
  "his private rhythm rides the cut as the defenders seal him in",
  "LATHE"),
 ("A5_SH14", "SANYA_BASE", None,
  "Sanya on a video call from a workers' hostel room, bunk beds behind, showing a new badge to the camera",
  "CU", "eye", "static", "evening", False, False,
  "саня звонит из общежития и показывает в камеру пропуск — устроился, батя, всё белое.",
  "the new badge fills the call screen over the bunk-bed room"),
 ("A5_SH15", "MATVEY_BASE", "matvey_kitchen",
  "Matvey talks to the propped phone holding it too far, pride working through the gruffness",
  "MCU", "eye", "static", "evening", False, False,
  "ты держишь телефон на вытянутой руке и ворчишь от гордости — путают их, эти нежности.",
  "the gruff pride talks at the too-far phone in the lamp light"),
 ("A5_SH16", None, "overlook",
  "the town from the rise at half past seven in the morning, smoke from stoves instead of the horn, thin and scattered",
  "EWS", "high", "static", "morning", True, False,
  "в семь тридцать над городом теперь только печной дым — расписание держат одни трубы.",
  "scattered stove smoke stands thin where the horn used to carry"),
]

if __name__ == "__main__":
    seed_act("A3", PAL_A3, A3)
    seed_act("A4", PAL_A4, A4)
    seed_act("A5", PAL_A5, A5)
