# -*- coding: utf-8 -*-
"""Seed CH20 — Цена человека, Шухрат (no gore; action-first). Idempotent."""
from _seed_tiler_act_engine import seed_act

MOOD = "cold marble glare, the hush after sudden disaster, indifferent and final"

SHOTS = [
    ("CH20_SH01", None, "objext",
     "wide shot of workers high up on towering scaffolding under a domed ceiling, no clear faces",
     "WS", "low", "static", "object_day", True, False,
     "шухрат работал высоко, под самым куполом."),
    ("CH20_SH02", "SHUKHRAT", "objext",
     "medium shot of the cheerful gap-toothed laborer up on the scaffolding cracking a joke to the others",
     "MS", "low", "static", "object_day", False, False,
     "балагур, даже там, наверху, шутил без умолку."),
    ("CH20_SH03", None, "objext",
     "wide shot of a scaffolding board tilting and a figure falling, motion blur, no gore, no clear face",
     "WS", "eye", "static", "object_day", False, True,
     "доска поехала, и он сорвался."),
    ("CH20_SH04", "BAKHTI", "objext",
     "close-up of the master looking up in horror, mouth open in a shout",
     "CU", "low", "static", "object_day", False, False,
     "скорую, кричал я, вызовите скорую."),
    ("CH20_SH05", None, "objext",
     "wide shot of men crouched in a ring around a still figure on the ground, seen from a distance, no gore",
     "WS", "high", "static", "object_day", False, False,
     "его обступили, тихо, без паники, будто привыкли."),
    ("CH20_SH06", "GENA", "objext",
     "medium close-up of the guard blocking the call with a flat hand, cold and businesslike",
     "MCU", "eye", "static", "object_day", False, False,
     "нет, сказал гена, своими, тихо, без шума и без скорых."),
    ("CH20_SH07", None, "objext",
     "wide shot of men carrying a covered figure out toward a van, no faces",
     "WS", "eye", "pan", "object_day", False, False,
     "его увезли куда-то, и всё, как не было."),
    ("CH20_SH08", None, "objext",
     "extreme close-up of a worker's knitted cap left abandoned on the dusty ground",
     "ECU", "top_down", "static", "object_day", False, True,
     "осталась только его шапка на земле."),
    ("CH20_SH09", None, "objext",
     "medium shot of a brand-new unfamiliar worker already taking the dead man's place on the scaffolding",
     "MS", "low", "static", "object_day", True, False,
     "к обеду на его место поставили другого."),
    ("CH20_SH10", "BAKHTI", "objext",
     "close-up of the master's stunned face, staring at the empty spot",
     "CU", "eye", "static", "object_day", False, False,
     "у нас даже имени не остаётся."),
    ("CH20_SH11", ("BAKHTI", "DILSHOD"), "objext",
     "Bakhti on the left holding the shaking frightened young Dilshod on the right by the shoulders",
     "MS", "eye", "static", "object_day", False, True,
     "дилшод трясся весь, я держал его, тише, тише, малой."),
    ("CH20_SH12", "BAKHTI", "objext",
     "medium close-up of the master's grim hollow face",
     "MCU", "eye", "static", "object_day", False, False,
     "был шухрат, стал минус один, найдите замену."),
    ("CH20_SH13", None, "objext",
     "wide shot of the scaffolding as work resumes as if nothing happened, no clear faces",
     "WS", "low", "static", "object_day", True, False,
     "и работа пошла дальше, дешевле плитки мы стоили."),
    ("CH20_SH14", "BAKHTI", "bytovka",
     "close-up of the master's face at night, something hardening behind his eyes",
     "CU", "eye", "static", "object_night", False, True,
     "в ту ночь я понял, кто мы тут для них, расходник."),
]

if __name__ == "__main__":
    seed_act(20, "object_marble_cold", MOOD, "static", "CH20 Price", SHOTS)
