# -*- coding: utf-8 -*-
"""Seed COLD OPEN for project `wall` (2nd person). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "cold grey present-day light, hollow solitude, the city wall long gone but one still standing inside her"
SHOTS = [
 ("B_SH01", None, "old_flat",
  "wide establishing of a dim present-day Berlin apartment at dawn, an old bed with one side untouched and cold",
  "WS","high","push_in","old_now",True,False,
  "тебе шестьдесят три, и каждое утро ты просыпаешься в постели, где вторая половина всегда холодная и пустая."),
 ("B_SH02", "HEROINE_OLD", "old_flat",
  "medium close-up of the aged heroine lying awake, staring at the empty side of the bed",
  "MCU","eye","static","old_now",False,False,
  "ты лежишь и смотришь на пустую подушку рядом, и так было уже очень, очень много лет."),
 ("B_SH03", None, "old_flat",
  "extreme close-up of a small worn door key kept on the nightstand",
  "ECU","top_down","static","old_now",True,True,
  "на тумбочке лежит чужой ключ, который ты хранишь полвека, единственное, что осталось от настоящего."),
 ("B_SH04", "HEROINE_OLD", "old_flat",
  "close-up of the heroine's lined hollow face turned to the window",
  "CU","eye","static","old_now",False,False,
  "за окном Берлин, в котором давно нет никакой стены, её снесли, а твоя так и стоит."),
 ("B_SH05", None, "street_west",
  "wide of a modern reunified Berlin street where the wall once ran, a faint line in the pavement",
  "WS","eye","pan","old_now",True,False,
  "город давно сросся обратно, а ведь когда-то прямо здесь всё рассекала бетонная стена."),
 ("B_SH06", "HEROINE_OLD", "old_flat",
  "medium shot of the heroine standing at the window looking out",
  "MS","eye","static","old_now",False,False,
  "ты прожила бурную жизнь, и в твоей постели перебывал, кажется, весь Восточный Берлин."),
 ("B_SH07", "HEROINE_OLD", "old_flat",
  "close-up of the heroine holding an old photo of her striking young self",
  "CU","eye","static","old_now",False,False,
  "а вот ты молодая, рыжая, дерзкая, на тебя оборачивался каждый мужчина на улице."),
 ("B_SH08", None, "old_flat",
  "extreme close-up of a fan of old photographs of many faceless men",
  "ECU","top_down","static","old_now",True,True,
  "сотни мужчин, сотни ночей, и ни одного имени, которое ты вспомнила бы сейчас с теплом."),
 ("B_SH09", "HEROINE_OLD", "old_flat",
  "medium close-up of the heroine's hollow realization",
  "MCU","eye","static","old_now",False,False,
  "тебя хотели все, а любить ты не позволила ни одному, и вот теперь ты совсем одна."),
 ("B_SH10", None, "old_flat",
  "wide of the empty quiet apartment around the small old woman",
  "WS","high","static","old_now",True,False,
  "хочешь знать, как из первой красавицы Восточного Берлина выходит вот эта одинокая старуха?"),
 ("B_SH11", "HEROINE_OLD", "old_flat",
  "close-up of the heroine, a bitter knowing look toward the viewer",
  "CU","eye","static","old_now",False,False,
  "всё началось там, в детстве, за серой стеной, с холодного отца, что так и не обнял."),
 ("B_SH12", None, "the_wall",
  "extreme close-up of cold grey concrete wall surface, raw and oppressive",
  "ECU","eye","push_in","gdr_day",True,True,
  "и со стены, которую возвели прямо посреди города, когда тебе было всего восемь лет."),
]
if __name__ == "__main__":
    seed_act(0, "eldritch_grey", MOOD, "static", "COLD OPEN", SHOTS)
