# -*- coding: utf-8 -*-
"""Seed CH34 — Пустая квартира, вторая подушка пуста навсегда (HEROINE_OLD). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "the empty apartment, the empty pillow forever, hollow ticking stillness"
SHOTS = [
 ("CH34_SH01", None, "old_flat",
  "wide of the silent apartment, only a clock ticking",
  "WS","eye","static","day",True,False,
  "твоя квартира тиха, как могила, часы тикают, и больше во всём доме ни единого звука."),
 ("CH34_SH02", "HEROINE_OLD", "old_flat",
  "medium close-up of her waking in a big bed, the far side empty",
  "MCU","eye","static","day",False,False,
  "ты просыпаешься в большой кровати, и вторая половина пуста, как была пуста всегда."),
 ("CH34_SH03", None, "old_flat",
  "extreme close-up of the empty pillow",
  "ECU","top_down","static","day",True,True,
  "пустая подушка рядом, та же, что в детстве, та же, что в юности, та же и сейчас."),
 ("CH34_SH04", "HEROINE_OLD", "old_flat",
  "close-up of her never once waking beside someone she truly loved",
  "CU","eye","static","day",False,False,
  "за всю жизнь ты так и не проснулась ни разу в обнимку с тем, кого по-настоящему любишь."),
 ("CH34_SH05", None, "old_flat",
  "medium of a shelf of faded photographs of many men",
  "MS","eye","static","day",True,False,
  "на полке выцветшие снимки, сотни лиц, и ни одно из них не пришло тебя навестить."),
 ("CH34_SH06", "HEROINE_OLD", "old_flat",
  "medium close-up of her phone silent for weeks",
  "MCU","eye","static","day",False,False,
  "телефон молчит неделями, никто не звонит, некому, ты пережила всех своих случайных."),
 ("CH34_SH07", None, "old_flat",
  "close-up of a single plate, a single cup on the table",
  "CU","eye","static","day",True,False,
  "одна тарелка, одна чашка, один стул, ты накрываешь стол только на одну себя."),
 ("CH34_SH08", "HEROINE_OLD", "old_flat",
  "medium close-up of the worst loneliness, no one to tell the day to",
  "MCU","eye","static","eve",False,True,
  "и страшнее всего, что некому даже сказать, как прошёл твой день, и был ли он вообще."),
 ("CH34_SH09", None, "old_flat",
  "extreme close-up of the dusty key box, her whole inheritance",
  "ECU","top_down","static","day",True,False,
  "только мамин холод да отцов побег, да чужие спины, вот и весь твой багаж."),
 ("CH34_SH10", "HEROINE_OLD", "old_flat",
  "medium close-up of her listening to others' lives through the wall",
  "MCU","eye","static","eve",False,False,
  "ты лежишь и слушаешь чужую жизнь за стеной, смех, шаги, голоса, всё у других."),
 ("CH34_SH11", None, "old_flat",
  "wide B-roll of the empty still apartment, silent",
  "WS","eye","static","eve",True,False,""),
]
if __name__ == "__main__":
    seed_act(34, "eldritch_grey", MOOD, "static", "CH34 Empty flat", SHOTS)
