# -*- coding: utf-8 -*-
"""Seed CH15 — Конфликт с Геной под прицелом (action-first). Idempotent."""
from _seed_tiler_act_engine import seed_act

MOOD = "cold tense marble glare, sudden violent humiliation, red laser threat"

SHOTS = [
    ("CH15_SH01", "BAKHTI", "objext",
     "the master carrying a bucket of mortar walking toward a restricted terrace, not realising the danger",
     "MS", "eye", "pan", "object_day", False, False,
     "я пошёл за раствором и свернул не туда."),
    ("CH15_SH02", "GENA", "objext",
     "the security guard wheeling around and bellowing an order, hand raised, furious",
     "MCU", "low", "static", "object_day", False, False,
     "гена заорал стой, но я не понял слова."),
    ("CH15_SH03", None, "objext",
     "extreme close-up of a red sniper laser dot settling on the centre of a man's chest",
     "ECU", "eye", "static", "object_day", False, True,
     "и на груди вспыхнула красная точка."),
    ("CH15_SH04", "BAKHTI", "objext",
     "close-up of the master freezing mid-step, bucket dropping, eyes wide",
     "CU", "eye", "static", "object_day", False, False,
     "я замер, ноги приросли."),
    ("CH15_SH05", ("GENA", "BAKHTI"), "marble",
     "Gena on the left shoving Bakhti on the right face-down onto the marble floor, knee on his back",
     "WS", "high", "static", "object_day", False, True,
     "меня свалили лицом в мрамор и держали."),
    ("CH15_SH06", "BAKHTI", "marble",
     "extreme close-up of the master's cheek pressed against the cold polished marble, breath fogging it",
     "ECU", "eye", "static", "object_day", False, False,
     "щекой я лежал на полу, что сам же выложил."),
    ("CH15_SH07", "GENA", "marble",
     "extreme close-up of a heavy boot grinding down and cracking a freshly laid tile",
     "ECU", "top_down", "static", "object_day", False, True,
     "гена раздавил сапогом плитку, что я клал три дня."),
    ("CH15_SH08", "GENA", "marble",
     "medium close-up of Gena sneering down, jabbing a finger",
     "MCU", "low", "static", "object_day", False, False,
     "понаехавший, русского не знает, а лезет куда не велено."),
    ("CH15_SH09", "BAKHTI", "marble",
     "the master slowly getting to his feet, dusting himself, eyes down, swallowing the shame",
     "MS", "eye", "static", "object_day", False, False,
     "я встал, отряхнулся и молчал, спорить себе дороже."),
    ("CH15_SH10", None, "marble",
     "wide shot of other workers watching and quickly looking away, no clear faces",
     "WS", "eye", "static", "object_day", True, False,
     "земляки смотрели и отворачивались, каждый думал, лишь бы не я."),
    ("CH15_SH11", "BAKHTI", "marble",
     "the master at night on his knees gathering the cracked tile fragments and arranging them into a pattern",
     "MS", "high", "static", "object_night", False, False,
     "ночью я собрал осколки и сложил из них узор."),
    ("CH15_SH12", None, "marble",
     "close-up of broken tile shards carefully arranged into a small star on the dark floor",
     "CU", "top_down", "static", "object_night", False, False,
     "привычка мастера, из битого делать целое."),
    ("CH15_SH13", "GENA", "bytovka",
     "the guard tossing a pack of cigarettes onto the bunk without looking, already turning away",
     "MS", "eye", "static", "object_night", False, False,
     "гена бросил мне пачку сигарет, не глядя, и ушёл."),
    ("CH15_SH14", "BAKHTI", "bytovka",
     "close-up of the master looking at the cigarettes, unreadable",
     "CU", "eye", "static", "object_night", False, True,
     "не прощение, но и не плевок, у них тоже что-то скребло."),
]

if __name__ == "__main__":
    seed_act(15, "object_marble_cold", MOOD, "static", "CH15 Gena", SHOTS)
