# -*- coding: utf-8 -*-
"""optimizer atmosphere breathers: 2 per act (A1..A11), id_region='a'.
Each act tail has its own camera scheme and subjects — no template shared with
other acts (and none shared with hidden_layoff)."""
from _optimizer_engine import seed_act

PALS = {
 "A1": "warm office daylight, soft beige tones, gentle window glow",
 "A2": "steel corporate light, cool white desks, glass reflections",
 "A3": "flat grey conveyor light, muted institutional tones, pale window haze",
 "A4": "low evening sun on concrete, long car shadows, amber and grey",
 "A5": "warm old-flat lamplight, faded wallpaper tones, soft window daylight",
 "A6": "vast white bank light, even cold illumination, glass and steel",
 "A7": "cool screen-blue glow, dim office dusk, monitor light on faces",
 "A8": "late amber office light, deep window dusk, warm lamp pools",
 "A9": "hard white meeting light, cold grey-green shadow, glass wall glare",
 "A10": "warm night kitchen lamplight, deep blue windows, homely browns",
 "A11": "pale daylight through tall windows, dusty gold air, worn red seats",
}

ATMO = {
 "A1": [
  ("A1_SZ01", None, "client_open",
   "a recruiter's cork board layered with pinned CVs and thank-you postcards, a red marker hanging on a string",
   "INSERT", "eye", "push_in", "day", True, False,
   "на пробковой доске рекрутера висят открытки от устроенных людей — их тогда было много.",
   "the pinned postcards lift at their corners in a passing draught and settle"),
  ("A1_SZ02", None, "elya_flat",
   "the city at first light from a high window, mist between towers, a single tram crossing an empty bridge",
   "EWS", "high", "pan_left", "morning", True, False,
   "в те годы город просыпается для тебя списками вакансий, а не списками фамилий.",
   "the single tram crawls across the empty bridge through thinning mist"),
 ],
 "A2": [
  ("A2_SZ01", None, "consult_office",
   "a wall of framed client logos in a glass corridor, a cleaner's reflection ghosting across the glass",
   "WS", "low", "track", "evening", True, False,
   "стена клиентов растёт на два логотипа в квартал, и половина из них — твои.",
   "a faint reflection glides along the framed logos and slips off the glass edge"),
  ("A2_SZ02", None, "training_hall",
   "rows of empty conference chairs after a training, one chair out of line, a forgotten printed handout on a seat",
   "ECU", "eye", "tilt_down", "evening", True, False,
   "после четвергового тренинга в зале всегда остаётся один лишний конспект.",
   "the handout page lifts at its corner and settles back onto the empty seat"),
 ],
 "A3": [
  ("A3_SZ01", None, "client_open",
   "a client office kitchenette with a corporate anniversary mug rack, one hook already empty, a kettle steaming alone",
   "INSERT", "eye", "static", "day", True, False,
   "в кухне клиента на рейке юбилейных кружек уже есть один пустой крючок.",
   "steam from the kettle drifts across the mug rack and its one empty hook"),
  ("A3_SZ02", None, "parking",
   "the business-centre car park at lunch hour from above, cars in even ranks, one man eating behind a wheel",
   "EWS", "high", "static", "day", True, False,
   "в обед на парковке всегда кто-то ест за рулём — теперь ты знаешь, кто именно.",
   "a distant windscreen catches the sun as the ranks of cars hold still",
   None, "crowd"),
 ],
 "A4": [
  ("A4_SZ01", None, "parking",
   "long evening shadows of lamp posts striping the emptying car park, a barrier arm rising for one car",
   "WS", "eye", "pan_right", "evening", True, False,
   "вечером шлагбаум поднимается всё реже — этаж клиента уехал домой раньше срока.",
   "the barrier arm rises, holds, and settles back down across the lane"),
  ("A4_SZ02", None, "elya_flat",
   "a bedside table with a sleep tracker charging, a glass of water, a book with a receipt for a bookmark",
   "ECU", "top", "push_in", "night", True, False,
   "книга у кровати читается по странице в неделю — закладка из чека почти не движется.",
   "the charging light pulses slowly beside the untouched book"),
 ],
 "A5": [
  ("A5_SZ01", None, "mother_plant",
   "the veteran photo board by the plant checkpoint, rows of small portraits behind glass, one reflection of passing clouds",
   "INSERT", "eye", "static", "day", True, False,
   "на доске ветеранов десятки лиц, и все они смотрят чуть выше объектива.",
   "cloud reflections slide slowly across the glass over the rows of portraits"),
  ("A5_SZ02", None, "mother_flat",
   "an old kitchen dresser with crystal glasses and a workshop photo from ninety-eight leaned against them, lace curtain light",
   "ECU", "eye", "tilt_up", "day", True, False,
   "фотография цеха девяносто восьмого года встаёт на буфет между хрусталём — насовсем.",
   "lace-filtered light climbs slowly up the leaning photograph and the crystal"),
 ],
 "A6": [
  ("A6_SZ01", None, "bank_atrium",
   "the bank atrium at dawn before opening, escalators running empty, the mural lit by cleaning lights",
   "EWS", "low", "tilt_up", "morning", True, False,
   "атриум банка запускает эскалаторы в семь, за час до первых людей.",
   "the empty escalators glide in their loops under the cleaning lights"),
  ("A6_SZ02", None, "bank_open",
   "a bank desk being cleared into a flat box, a cactus and a mug going in, the monitor already dark",
   "INSERT", "high", "static", "day", True, False,
   "стол в банке собирается в коробку за четыре минуты — ты замеряла.",
   "the cactus pot settles into the box corner beside the mug"),
 ],
 "A7": [
  ("A7_SZ01", None, "bank_open",
   "a dark bank floor at night with one row of monitors left on standby, their screens breathing dim blue",
   "WS", "eye", "push_in", "night", True, False,
   "по ночам мониторы уволенных ещё дышат синим — айти доберётся до них в пятницу.",
   "the standby screens pulse dim blue in an uneven silent rhythm"),
  ("A7_SZ02", None, "consult_office",
   "a server rack in a glass corner of the consultancy floor, status diodes running green, cable ties neat",
   "ECU", "low", "static", "evening", True, False,
   "бот живёт в стеклянном углу этажа и работает без обеда и без пауз.",
   "the status diodes flicker green in quick irregular runs down the rack"),
 ],
 "A8": [
  ("A8_SZ01", None, "consult_office",
   "the thanks-letter wall in evening lamp pools, framed letters slightly uneven, a hook freshly empty at the row's end",
   "WS", "eye", "track", "evening", True, False,
   "на стене благодарностей появился свободный крюк — рамки переезжают в архив по одной.",
   "lamplight pools shift as a door closes somewhere and the frames hold their angles"),
  ("A8_SZ02", None, "elya_flat",
   "a wardrobe open on a row of identical dark blazers, one hanger turned the wrong way, city night in the window",
   "ECU", "eye", "static", "night", True, False,
   "в шкафу висят шесть одинаковых блейзеров, и ты вдруг не помнишь, какой сегодняшний.",
   "the wrong-turned hanger sways a centimetre as the wardrobe door drifts wider"),
 ],
 "A9": [
  ("A9_SZ01", None, "consult_office",
   "the consultancy floor from the lift doors, her glass corner office standing dark while the rest of the floor works",
   "EWS", "eye", "static", "day", True, False,
   "стеклянный угол этажа стоит тёмным уже в пятницу вечером — свет там больше некому включать.",
   "figures move about the lit floor while the dark glass corner holds still",
   None, "crowd"),
  ("A9_SZ02", None, "parking",
   "a cardboard box with an orchid leaf showing over its edge, standing on a car's back seat in afternoon light",
   "INSERT", "eye", "push_in", "day", True, False,
   "орхидея едет с парковки на заднем сиденье, листом наружу, как пассажир.",
   "the orchid leaf trembles over the box edge as the car settles on its springs"),
 ],
 "A10": [
  ("A10_SZ01", None, "mother_flat",
   "an old kitchen radio on the fridge glowing its dial, two teacups draining on the rack, night outside the lace",
   "WS", "eye", "static", "night", True, False,
   "радио на холодильнике доигрывает вечерний концерт двум пустым чашкам на сушилке.",
   "the radio dial glows steadily while a curtain edge stirs by the window vent"),
  ("A10_SZ02", None, "elya_flat",
   "morning light across an empty white kitchen island, a single notebook and pen aligned at its corner",
   "ECU", "high", "pan_left", "morning", True, False,
   "на белой столешнице теперь только блокнот и ручка — больше ей нечего держать.",
   "the long morning light creeps across the empty white surface toward the notebook"),
 ],
 "A11": [
  ("A11_SZ01", None, "dk_hall",
   "coat hooks in the house-of-culture lobby heavy with winter coats, puddles of melted snow under the bench",
   "WS", "eye", "tilt_down", "day", True, False,
   "по вторникам в гардеробе дк снова тесно — у безработицы свой сезонный график.",
   "melt-water gathers slowly into the floor puddles under the heavy coats"),
  ("A11_SZ02", None, "dk_hall",
   "a red pen lying across a stack of corrected CVs on the stage table, afternoon light long across the paper",
   "INSERT", "eye", "pull_out", "evening", True, False,
   "к вечеру стопка правленых резюме толще, чем любой твой регламент.",
   "the long light slides off the paper stack as the hall dims by degrees"),
 ],
}

if __name__ == "__main__":
    for act, shots in ATMO.items():
        seed_act(act, PALS[act], shots, id_region="a")
