# -*- coding: utf-8 -*-
"""Seed CH22 — Восьмидесятые, доза не работает (HEROINE_YOUNG). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "the 1980s grind on, the dose barely works, grey exhaustion, looks beginning to fade"
SHOTS = [
 ("CH22_SH01", "HEROINE_YOUNG", "street_east",
  "medium of the heroine in her mid-thirties, tiredness where defiance used to be",
  "MS","eye","static","gdr_day",False,False,
  "восьмидесятые, тебе под тридцать пять, и в зеркале всё чаще усталость вместо прежнего вызова."),
 ("CH22_SH02", None, "disco",
  "wide of the same dancehall where she is now the oldest",
  "WS","eye","static","night",True,False,
  "дискотеки всё те же, но теперь ты среди них самая старшая, и это заметно уже всем."),
 ("CH22_SH03", "HEROINE_YOUNG", "disco",
  "medium close-up of her drinking more, painting on more",
  "MCU","eye","static","night",False,False,
  "приходится пить больше, краситься гуще, чтобы хоть кто-то задержал на тебе взгляд."),
 ("CH22_SH04", None, "disco",
  "close-up of younger women laughing behind their hands",
  "CU","eye","static","night",True,False,
  "молоденькие смеются над тобой за спиной, смотри, опять эта, всё никак не угомонится."),
 ("CH22_SH05", "HEROINE_YOUNG", "kneipe",
  "close-up of her catching pity instead of desire",
  "CU","eye","static","night",False,False,
  "ты ловишь теперь не желание, а жалость, и это куда больнее любых грязных слухов."),
 ("CH22_SH06", "HEROINE_YOUNG", "her_room",
  "medium close-up of the wave reduced to bare habit",
  "MCU","eye","static","dawn",False,False,
  "волна почти не приходит, остаётся лишь привычка, голая, механическая, без всякого тепла."),
 ("CH22_SH07", None, "her_room",
  "extreme close-up of the empty cold half of the bed",
  "ECU","eye","static","dawn",True,True,
  "ты ложишься с чужим и не чувствуешь уже почти ничего, кроме всё той же знакомой пустоты."),
 ("CH22_SH08", "HEROINE_YOUNG", "street_east",
  "medium of her quickening her step past Andreas's building",
  "MS","eye","static","gdr_day",False,False,
  "иногда ты проходишь мимо дома Андреаса и ускоряешь шаг, чтобы не смотреть на его окна."),
 ("CH22_SH09", "HEROINE_YOUNG", "her_room",
  "close-up of the ache at hearing he married",
  "CU","eye","static","gdr_eve",False,False,
  "ты слышала, он женился, у него растут дети, и от этого внутри что-то болезненно сжимается."),
 ("CH22_SH10", "HEROINE_YOUNG", "her_room",
  "medium close-up of her drowning the regret again",
  "MCU","eye","static","night",False,True,
  "но признать свою ошибку ты не можешь и снова глушишь её единственным знакомым способом."),
 ("CH22_SH11", None, "disco",
  "wide B-roll of the dim dancehall, silent",
  "WS","eye","static","night",True,False,""),
]
if __name__ == "__main__":
    seed_act(22, "gdr_night", MOOD, "static", "CH22 Eighties", SHOTS)
