# -*- coding: utf-8 -*-
"""Seed CH13 — Филлеры, ещё чуть-чуть (2nd person). HEROINE_MID debuts (mask forms). Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "cold clinical white clinic light, the mask beginning to set, seductive sterile"
SHOTS = [
 ("CH13_SH01", ("ALINA","HEROINE_MID"), "clinic",
  "Alina on the left with a filler syringe, the heroine on the right in the chair, her face starting to look over-smoothed",
  "MS","eye","static","clinic_day",False,False,
  "ботокса уже мало, говорит алина, давай филлеры, скулы, губки."),
 ("CH13_SH02", None, "clinic",
  "extreme close-up of a filler needle going into a lip",
  "ECU","eye","push_in","clinic_day",True,True,
  "игла в губы, в скулы, ты терпишь, ради красоты можно всё."),
 ("CH13_SH03", "HEROINE_MID", "bathroom",
  "medium close-up of the heroine in the mirror, lips plumped, cheekbones sharp, delighted",
  "MCU","eye","static","clinic_day",False,False,
  "губы пухлые, скулы как у молодой, ты в восторге."),
 ("CH13_SH04", "HEROINE_MID", "bathroom",
  "extreme close-up of her over-plumped lips and too-smooth face",
  "ECU","eye","static","clinic_day",False,True,
  "только улыбка стала чуть чужой, но ты не замечаешь."),
 ("CH13_SH05", ("HEROINE_MID","ALINA"), "clinic",
  "the heroine on the left asking for more, Alina on the right ready to oblige",
  "MS","eye","static","clinic_day",False,False,
  "ещё капельку, просишь ты, и тут, и вот тут."),
 ("CH13_SH06", "ALINA", "clinic",
  "medium close-up of Alina's sweet dealer's smile, never refusing",
  "MCU","eye","static","clinic_day",False,False,
  "алина никогда не откажет, ей это выгодно."),
 ("CH13_SH07", None, "family",
  "extreme close-up of expensive clinic receipts being hidden in a drawer",
  "ECU","top_down","static","clinic_day",True,False,
  "процедуры дорогие, и ты прячешь чеки от мужа."),
 ("CH13_SH08", "HEROINE_MID", "family",
  "medium shot of the heroine tucking receipts away, rehearsing a lie",
  "MS","eye","static","clinic_day",False,False,
  "была на массаже, на маникюре, врёшь ты легко."),
 ("CH13_SH09", "HEROINE_MID", "bathroom",
  "extreme close-up of the heroine admiring her frozen-smooth face, seeing youth not a mask",
  "ECU","eye","push_in","clinic_day",False,False,
  "зеркало льстит, ты видишь молодую, а не маску."),
 ("CH13_SH10", None, "clinic",
  "close-up of a clinic procedure menu with ever more options",
  "CU","top_down","static","clinic_day",True,False,
  "каждый раз чуть больше, чуть сильнее, точь-в-точь как доза."),
 ("CH13_SH11", "HEROINE_MID", "clinic",
  "medium close-up of the heroine's tense hopeful face",
  "MCU","eye","static","clinic_day",False,True,
  "ещё чуть-чуть, и стану совсем как раньше, твердишь ты."),
 ("CH13_SH12", None, "shop",
  "wide B-roll of the lit clinic facade at dusk",
  "WS","eye","static","clinic_day",True,False,""),
]
if __name__ == "__main__":
    seed_act(13, "clinic_white", MOOD, "static", "CH13 Fillers", SHOTS)
