# -*- coding: utf-8 -*-
"""irreplaceable shots: A0 (the night save), A1 (the empire of 112 passwords), A2 (the audit)."""
from _irreplaceable_engine import seed_act

PAL_A0 = "deep night blue, server diode glow, cold monitor light"
PAL_A1 = "warm lamp clutter, paper and dust tones, amber screen glow"
PAL_A2 = "clean audit white, cool glass tones, whiteboard glare"

A0 = [
 ("A0_SH01", None, "warehouse_trade",
  "the trade warehouse frozen at night, scanners dark in their cradles, pallet lanes lit by emergency strips, a stopped conveyor",
  "EWS", "high", "static", "night", True, False,
  "в ночь перед годовой инвентаризацией складская система падает, и восемнадцать тысяч позиций повисают в воздухе.",
  "emergency strips hum over the stopped lanes as a scanner cradle light blinks red"),
 ("A0_SH02", None, "openspace_trade",
  "two night-duty operators helpless before a frozen error screen, one phone already at an ear, printouts scattered",
  "WS", "eye", "static", "night", False, False,
  "дежурные тычут в мёртвый экран и делают единственное, что умеют в таких случаях, — звонят тебе.",
  "the frozen error dialog glows over the two hunched silhouettes and the lifted phone",
  None, "crowd"),
 ("A0_SH03", "BORIS_BASE", "boris_flat",
  "Boris answers the phone in the dark flat already sitting up, glasses chain swinging, his other hand finding the laptop by feel",
  "CU", "eye", "static", "night", False, False,
  "ты просыпаешься со второго гудка, и рука сама находит ноутбук раньше, чем ты — тапки.",
  "he sits up into the phone glow as his free hand closes on the laptop lid"),
 ("A0_SH04", "BORIS_BASE", "it_room",
  "Boris in his cramped IT room at night, coat still on, pulling the cipher notebook from the desk drawer with ceremony",
  "MS", "eye", "static", "night", False, True,
  "в два ночи ты открываешь ящик и достаёшь клетчатый блокнот — сто двенадцать паролей твоим личным шифром.",
  "the drawer rolls open and the taped-spine notebook comes out in his careful hand",
  "CIPHER"),
 ("A0_SH05", "BORIS_BASE", None,
  "his own thick fingers typing fast on a yellowed keyboard, terminal lines scrolling, the notebook propped open against the screen",
  "POV", "pov", "static", "night", False, False,
  "команды ты набираешь по памяти, а в блокнот смотришь только за солью шифра.",
  "the thick fingers rattle the yellowed keys as terminal lines climb the dark screen",
  "KEYBOARD"),
 ("A0_SH06", None, None,
  "a terminal screen where a recovery process crawls through percent marks, a tea mug steaming beside the yellowed keyboard",
  "ECU", "eye", "static", "night", False, False,
  "база поднимается по проценту в минуту, и каждый процент — это шестьсот позиций склада.",
  "the percent counter ticks up as steam drifts across the terminal glow"),
 ("A0_SH07", "BORIS_BASE", "it_room",
  "Boris leans back watching the recovery, hands laced on his stomach, the flash drive cord visible at his collar",
  "MCU", "eye", "static", "night", False, False,
  "ты сидишь спокойно, потому что эту базу ты знаешь глубже, чем её написавший студент двухтысячных.",
  "his laced hands rise and settle on his stomach with one unhurried breath",
  "USB"),
 ("A0_SH08", None, "server_room",
  "the old server tower among modern racks, its handwritten cable tags stirring in the cold aisle airflow, diodes settling green",
  "WS", "low", "static", "night", False, False,
  "старый сервер прокашливается и встаёт, и его рукописные ярлыки на кабелях вздрагивают от вентиляторов.",
  "the cable tags stir in the airflow as the diode column settles from amber to green"),
 ("A0_SH09", None, "warehouse_trade",
  "the warehouse waking: scanners chirping back online in their cradles, lane lights stepping on section by section",
  "WS", "high", "static", "night", False, False,
  "без двадцати четыре сканеры оживают по всему складу, и пересчёт стартует точно по графику.",
  "lane lights step on section by section as the scanner cradles chirp awake",
  None, "crowd"),
 ("A0_SH10", "BORIS_BASE", "openspace_trade",
  "night operators applaud Boris as he walks through with his laptop bag, he accepts it with a small czar-like nod",
  "MS", "eye", "static", "night", False, False,
  "дежурные хлопают тебе в пустом опенспейсе, и ты принимаешь это, как царь — хлеб-соль.",
  "he passes through the sparse applause with one gracious nod, bag over shoulder",
  None, "crowd"),
 ("A0_SH11", None, None,
  "the cipher notebook going back into the drawer, a key turning in the drawer lock, the flash drive cord lowered over it",
  "ECU", "eye", "static", "night", False, False,
  "блокнот возвращается в ящик, ящик — под ключ, а ключ — на шнурок к флешке.",
  "the drawer key turns and the knotted cord lowers onto the closed lock",
  "CIPHER"),
 ("A0_SH12", "BORIS_BASE", "street_office",
  "Boris walks to a night taxi under the office lights, unhurried, a man leaving a kingdom in order",
  "WS", "eye", "static", "night", False, False,
  "домой ты едешь в четыре утра с чувством глубокой правильности мира.",
  "he crosses to the waiting taxi at a sovereign pace under the entrance lights"),
 ("A0_SH13", "BORIS_BASE", "it_room",
  "Boris's satisfied heavy face in the monitor glow, reading glasses down on the chain, absolute certainty in it",
  "CU", "eye", "push_in", "night", False, True,
  "формула у тебя простая — пока ты незаменим, тебя нельзя уволить, и она работает двадцать лет.",
  "the monitor glow steadies on his certain face as the glasses settle on their chain"),
 ("A0_SH14", "BORIS_BASE", "it_room",
  "Boris from behind at his desk, the server diodes green beyond, the little cactus silhouetted on the monitor top",
  "BACK", "eye", "static", "night", False, False,
  "останься до конца и подпишись — я расскажу, как самого незаменимого человека компании уволили, не уволив.",
  "the diode column holds green beyond his still silhouette and the cactus",
  "CACTUS"),
]

A1 = [
 ("A1_SH01", "BORIS_BASE", "it_room",
  "Boris enters his cramped room at nine sharp, hangs his bag on the same hook, pats the server tower once like a horse",
  "MS", "eye", "static", "morning", False, False,
  "твой день начинается одинаково двадцать лет — крючок для сумки и ладонь на тёплый бок сервера.",
  "the bag lands on its hook and his palm pats the warm server flank once",
  "SERVER"),
 ("A1_SH02", None, None,
  "the monitor cactus in its tea tin being watered from a syringe, gravel darkening around the stem",
  "ECU", "eye", "static", "morning", False, False,
  "кактус на мониторе ты поишь из шприца по вторникам — он здесь дольше половины отдела кадров.",
  "the syringe drops darken the gravel ring around the little cactus",
  "CACTUS"),
 ("A1_SH03", "BORIS_BASE", None,
  "his own hand adding a new ciphered line to the notebook, ruler under the row, letters small and even",
  "POV", "pov", "static", "day", False, True,
  "новый пароль — новая строка шифра, под линейку, и таких строк уже сто двенадцать.",
  "the pen adds the small even cipher line along the ruler edge",
  "CIPHER"),
 ("A1_SH04", "KATYA_BASE", "it_room",
  "Katya in the doorway with a printed request, hopeful and businesslike, the pencil in her bun catching light",
  "CU", "eye", "static", "day", False, False,
  "катя приходит с заявкой на доступ к ядру системы — третий раз за год.",
  "she holds the printed request out a hopeful centimetre further into the room"),
 ("A1_SH05", "BORIS_BASE", "it_room",
  "Boris signs a refusal across the request with a benevolent smile, the resolution short and final",
  "MCU", "eye", "static", "day", False, False,
  "ты пишешь на заявке доброе «не лезь, сломаешь» — только официальными словами.",
  "his pen draws the short refusal diagonal and he hands the sheet back smiling"),
 ("A1_SH06", "KATYA_BASE", "corridor_it",
  "Katya walks the corridor reading the refusal, jaw tight, folding the sheet in precise angry halves",
  "MS", "eye", "track", "day", False, False,
  "катя складывает отказ вчетверо ровными злыми движениями и идёт учить систему снаружи, по крохам.",
  "the sheet folds in precise halves as her steps eat the corridor line"),
 ("A1_SH07", None, "openspace_trade",
  "the open office mid-day, spreadsheets glowing, a queue of three people waiting by the IT-room door with papers",
  "WS", "eye", "static", "day", False, False,
  "к твоей двери всегда очередь — доступы, выгрузки, отчёты, всё через одного человека.",
  "the small queue shifts papers hand to hand outside the door",
  None, "crowd"),
 ("A1_SH08", "BORIS_BASE", "warehouse_trade",
  "Boris walks the warehouse mezzanine like an inspecting owner, storemen below nodding up at him",
  "WS", "high", "track", "day", False, False,
  "на складе тебя зовут «сам» — «сам сказал», «сам поправит», «без самого не трогай».",
  "he paces the mezzanine glass as nods ripple along the lanes below",
  None, "crowd"),
 ("A1_SH09", None, None,
  "a vacation schedule printout with one row of empty year cells, other rows stamped with dates",
  "ECU", "eye", "static", "day", False, False,
  "в графике отпусков твоя строка пустая шестой год — «система не поймёт».",
  "lamplight crosses the one empty row among the stamped ones"),
 ("A1_SH10", "GENA_BASE", "server_room",
  "Gena works a rack with his multitool, talking over his shoulder to Boris, patch cords looped on his arm",
  "MS", "eye", "static", "day", False, False,
  "гена — единственный, кто зовёт тебя борей, а не борисом палычем, и этим всё сказано.",
  "the multitool clicks in his hand as patch cords sway on his forearm"),
 ("A1_SH11", ("GENA_BASE", "BORIS_BASE"), "server_room",
  "Gena and Boris drink coffee between the racks, two veterans in the diode light, an old joke passing between them",
  "CU", "eye", "static", "day", False, False,
  "с геной вы пьёте кофе среди стоек двадцать лет, и шутки у вас ровесники серверов.",
  "two coffee cups tilt in the diode light as the old joke lands again"),
 ("A1_SH12", "BORIS_BASE", "boris_flat",
  "Boris at home among book towers answering a work chat at midnight, glasses low, kettle steaming behind",
  "MS", "eye", "static", "night", False, False,
  "дома тебя ждут книги, чайник и рабочий чат, который ты не выключаешь никогда.",
  "his thumb answers the chat as the kettle steams behind the book towers"),
 ("A1_SH13", None, "boris_flat",
  "a bachelor fridge door with one magnet and a pizza flyer, the kitchen tidy in an unlived way",
  "ECU", "eye", "static", "night", False, False,
  "холодильник у тебя пустой и чистый — семья не сложилась, сложилась система.",
  "the single magnet holds the flyer as the fridge hums into the tidy quiet"),
 ("A1_SH14", "BORIS_BASE", "it_room",
  "Boris explains something at his whiteboard corner to an intern, enjoying the lecture, marker conducting",
  "MS", "eye", "static", "day", False, False,
  "объяснять ты любишь — но только «что», никогда «как», потому что «как» и есть твоя валюта.",
  "the marker conducts two airy circles above the diagram as he lectures",
  None, "crowd"),
 ("A1_SH15", "BORIS_BASE", "it_room",
  "Boris's content face in the amber lamp light, a man certain his fortress walls reach the sky",
  "CU", "eye", "push_in", "evening", False, True,
  "ты не жадный и не злой — ты просто выстроил крепость и забыл, что живёшь в ней один.",
  "his content gaze softens at the warm lamp as the room hums around him"),
 ("A1_SH16", None, "it_room",
  "the IT room at night: the server diodes, the locked drawer, the cactus, a coat forgotten on the chair back",
  "WS", "eye", "static", "night", True, False,
  "по ночам крепость сторожит сама себя — ящик под ключом, сервер под ярлыками, кактус на посту.",
  "the diode light breathes over the locked drawer and the forgotten coat"),
]

A2 = [
 ("A2_SH01", "ARTUR_BASE", "openspace_trade",
  "Artur crosses the open office on his first day with the sticker laptop under one arm, reading the room through round glasses",
  "MS", "eye", "track", "day", False, False,
  "новый ит-директор приходит в марте — артур, тридцать восемь, ноутбук в наклейках.",
  "his round glasses sweep the office as the sticker laptop rides his arm"),
 ("A2_SH02", ("ARTUR_BASE", "BORIS_BASE"), "it_room",
  "Artur stands in the doorway of the cramped IT room taking in the server, the shelves, the blocked window, Boris rising to meet him",
  "WS", "eye", "static", "day", False, False,
  "он заходит в твою каморку, оглядывает стеллажи с бэкапами и вежливо спрашивает, где документация.",
  "his glance travels the shelves and the blocked window as the heavy man rises"),
 ("A2_SH03", "BORIS_BASE", "it_room",
  "Boris spreads his arms with a proud half-smile, presenting himself, the flash drive cord swinging forward",
  "MCU", "eye", "static", "day", False, True,
  "ты разводишь руками и отвечаешь фразой, которую потом будешь слышать во сне, — «я документация».",
  "his arms spread in the proud presenting gesture as the cord swings forward",
  "USB"),
 ("A2_SH04", "ARTUR_BASE", "it_room",
  "Artur nods slowly, writing one short line in his laptop, his face carefully unreadable behind the round glasses",
  "CU", "eye", "static", "day", False, False,
  "артур кивает и записывает одну короткую строчку — ты не видишь какую, и зря.",
  "his one short line lands in the laptop as the nod hides his eyes"),
 ("A2_SH05", None, None,
  "a risk-audit spreadsheet on a laptop screen, one cell filled solid red among green and yellow",
  "ECU", "eye", "static", "day", False, False,
  "в его таблице рисков появляется одна сплошь красная ячейка, и в ней твоя фамилия.",
  "the red cell holds its colour as the cursor blinks beside the surname"),
 ("A2_SH06", "ARTUR_BASE", "meeting_it",
  "Artur interviews department heads in the meeting room, sticky notes climbing the glass wall behind him",
  "WS", "eye", "static", "day", False, False,
  "две недели артур ходит по отделам и слушает, и стеклянная стена обрастает стикерами.",
  "sticky notes climb the glass wall as another interview leans into the table",
  None, "crowd"),
 ("A2_SH07", ("GENA_BASE", "BORIS_BASE"), "server_room",
  "Gena talks seriously to Boris between the racks, multitool for once in its pouch, coffee untouched",
  "MS", "eye", "static", "day", False, False,
  "гена говорит тихо — «боря, он не про тебя спрашивал, он про то, что будет, если тебя не будет».",
  "his hands stay off the racks for once as the quiet words cross the aisle"),
 ("A2_SH08", "BORIS_BASE", "server_room",
  "Boris chuckles and slaps the old server tower, the answer of a man holding all hundred twelve keys",
  "CU", "eye", "static", "day", False, False,
  "ты хлопаешь сервер по боку и отвечаешь — «если меня не будет, вот это встанет, и они это знают».",
  "his palm lands the confident slap on the humming steel flank",
  "SERVER"),
 ("A2_SH09", "KATYA_BASE", "meeting_it",
  "Katya answers Artur's questions with precise diagrams drawn from memory, the pencil out of her bun and working",
  "MS", "eye", "static", "day", False, False,
  "катя рисует артуру схему системы по памяти — снаружи, по крохам, но пугающе точно.",
  "the pencil from her bun draws the clean diagram as his glasses lean in"),
 ("A2_SH10", "ARTUR_BASE", "cio_office",
  "Artur at his whiteboard drawing one box with one stick figure inside and many arrows leading to it",
  "MCU", "eye", "static", "evening", False, False,
  "на своей доске артур рисует квадрат, человечка внутри и двадцать стрелок, ведущих в квадрат.",
  "the marker crowds arrow after arrow toward the one boxed figure"),
 ("A2_SH11", None, "cio_office",
  "the whiteboard diagram in close-up: the boxed figure circled twice in red, a question mark beside it",
  "ECU", "eye", "static", "evening", False, False,
  "потом он обводит квадрат красным дважды и ставит рядом знак вопроса.",
  "the red marker rings the boxed figure twice and dots the question mark"),
 ("A2_SH12", "BORIS_BASE", "corridor_it",
  "Boris passes the CIO office and glimpses the diagram through glass, slowing half a step, then walking on with a snort",
  "MS", "eye", "static", "evening", False, False,
  "ты видишь эту доску через стекло, хмыкаешь и проходишь мимо — рисуй, милый, рисуй.",
  "his half-step falters at the glass and recovers into the confident stride"),
 ("A2_SH13", "BORIS_BASE", "boris_flat",
  "Boris at his home desk telling the monitor screen a story with relish, an old forum thread open, tea in hand",
  "MCU", "eye", "static", "night", False, False,
  "дома ты пишешь на старом форуме, как очередной «эффективный» захотел документацию, и собираешь смайлики.",
  "his fingers type the relished story as the forum thread scrolls up"),
 ("A2_SH14", None, "openspace_trade",
  "the office notice screen cycling a slide about an IT infrastructure audit, employees passing with trays",
  "WS", "eye", "static", "day", False, False,
  "на экране в опенспейсе крутится слайд «аудит ит-инфраструктуры», и внимательно его читаешь только ты.",
  "the audit slide cycles over the passing trays and inattentive shoulders",
  None, "crowd"),
 ("A2_SH15", "BORIS_BASE", "openspace_trade",
  "Boris reads the cycling slide with folded arms, amusement cooling into the first real attention",
  "CU", "eye", "push_in", "day", False, False,
  "слайд ты перечитываешь трижды, и усмешка на третьем разе не собирается.",
  "his folded arms tighten as the third read wipes the amusement"),
 ("A2_SH16", None, None,
  "the server room at night, the old tower's diodes green, a new network probe device blinking on the rack beside it",
  "ECU", "low", "static", "night", True, False,
  "ночью рядом со старым сервером появляется маленькая коробочка аудита — она просто слушает.",
  "the probe's single diode blinks fast beside the old tower's steady green",
  "SERVER"),
]

if __name__ == "__main__":
    seed_act("A0", PAL_A0, A0)
    seed_act("A1", PAL_A1, A1)
    seed_act("A2", PAL_A2, A2)
