# -*- coding: utf-8 -*-
"""A5 (act_05_credit_quarrel) — first Kaspi credit (400 000), open phone quarrel with Dasha."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from _seed_message_act_engine import seed_act

MOOD = ("harsh Kaspi-red app glow and cold night-kitchen blue, tense rising-conflict palette, "
        "hard high-contrast shadows, anxious mood")

SHOTS = [
 ("A5_SH01","IRINA","kitchen","close-up of the woman reading a new alarming demand at the dark kitchen table","CU","eye","static","winter_night_2026",False,False,
  "сбережения кончились, а виктор пишет что на таможне всплыл новый штраф, без оплаты груз арестуют"),
 ("A5_SH02",None,"kitchen","extreme close-up of the phone screen with a 400 000 tenge demand and a threat that all is lost","ECU","eye","static","winter_night_2026",False,False,
  "ещё четыреста тысяч тенге, иначе всё пропало, и его расчётные, и подарок, и сам приезд"),
 ("A5_SH03","IRINA","kitchen","medium shot of the woman in quiet panic over a phone showing a zero balance","MS","eye","static","winter_night_2026",False,False,
  "у тебя больше нет ни тенге свободных, ты сидишь над пустым счётом и не знаешь что делать"),
 ("A5_SH04","IRINA","kitchen","medium shot of the woman noticing the in-app credit offer on her phone","MS","eye","static","winter_night_2026",False,False,
  "и тут каспи сам подсказывает, оформить кредит за две минуты, без справок, прямо в приложении"),
 ("A5_SH05",None,"kitchen","extreme close-up of the Kaspi credit screen, 400 000 tenge at a high interest rate","ECU","eye","push_in","winter_night_2026",False,True,
  "четыреста тысяч под огромный процент, ежемесячный платёж почти как половина твоей зарплаты"),
 ("A5_SH06","IRINA","kitchen","medium shot of the woman hesitating over the loan, a lifetime of caution in her face","MS","eye","static","winter_night_2026",False,False,
  "ты замираешь, тридцать лет ты ни разу не брала в долг, тебя так воспитали, в долг это стыдно"),
 ("A5_SH07",None,"kitchen","close-up of the phone with Viktor swearing he will repay with interest, one last paper left","CU","eye","static","winter_night_2026",False,False,
  "но виктор пишет, родная, я верну с процентами, осталась последняя бумага, и я твой навсегда"),
 ("A5_SH08","IRINA","kitchen","medium shot of the woman tapping to confirm the loan, money appearing instantly","MS","eye","static","winter_night_2026",False,False,
  "и ты нажимаешь оформить, деньги падают на счёт мгновенно, как будто залезть в долг это так легко"),
 ("A5_SH09",None,"kitchen","extreme close-up of the Kaspi transfer of 400 000 to the stranger's card in the port","ECU","eye","static","winter_night_2026",False,False,
  "и так же мгновенно ты отправляешь их марату, четыреста тысяч, чужому человеку в порту, не себе"),
 ("A5_SH10","IRINA","kitchen","close-up of the woman's tired face, the warmth under her ribs barely flickering now","CU","low","static","winter_night_2026",False,False,
  "под рёбрами теплеет всё тише, ты уже почти не чувствуешь толчка, только тяжёлую усталость"),
 ("A5_SH11","IRINA","kitchen","medium shot of the woman reading the first loan bill, doing grim math","MS","high","static","winter_day_2026",False,False,
  "через неделю каспи присылает первый счёт по кредиту, и ты считаешь, на что жить до зарплаты"),
 ("A5_SH12","IRINA","street","wide shot of the woman walking instead of taking the bus, buying the cheapest food at a corner shop","WS","eye","static","winter_day_2026",False,False,
  "ты начинаешь экономить на всём, ходишь пешком, покупаешь самое дешёвое в магазине у дома"),
 ("A5_SH13",None,"room","close-up of the phone with Viktor going quiet, then blaming storms on the rig for the delay","CU","eye","static","winter_evening_2026",False,False,
  "виктор то на связи, то пропадает, пишет что шторм, что вышку треплет, что скоро всё решится"),
 ("A5_SH14","IRINA","room","close-up of the woman lying awake, a flicker of doubt she cannot quite name","CU","eye","static","winter_evening_2026",False,False,
  "иногда ночью тебе кажется что-то не сходится, но утром приходит доброе утро и сомнение тает"),
 ("A5_SH15","IRINA","kitchen","medium shot of the woman answering a weekend call, tension already in her shoulders","MS","eye","static","winter_day_2026",False,False,
  "в субботу звонит даша и сразу слышит по голосу, что с тобой что-то не так этой зимой"),
 ("A5_SH16","DASHA","dasha","medium shot of the cherry-red-haired daughter on the phone in Astana, worried and direct","MS","eye","static","winter_day_2026",False,False,
  "мам, ты странная последний месяц, у тебя точно всё в порядке с деньгами, спрашивает она прямо"),
 ("A5_SH17","IRINA","kitchen","close-up of the woman lying with a trembling voice the daughter catches","CU","eye","static","winter_day_2026",False,False,
  "ты говоришь что всё хорошо, но голос дрожит, и даша мгновенно цепляется за эту дрожь"),
 ("A5_SH18","DASHA","dasha","medium close-up of the daughter pressing the question, jaw tight","MCU","eye","static","winter_day_2026",False,False,
  "даша спрашивает в лоб, мам, ты давала этому своему виктору деньги, скажи мне правду сейчас"),
 ("A5_SH19","IRINA","kitchen","close-up of the woman caught in a too-long silence, the truth in her face","CU","eye","static","winter_day_2026",False,False,
  "ты молчишь слишком долго, и в этой паузе дочь понимает всё, и у неё срывается голос"),
 ("A5_SH20","DASHA","dasha","medium shot of the daughter naming the scam, eyes wide with fear for her mother","MS","eye","static","winter_day_2026",False,True,
  "мам, это развод, таких историй тысячи, нет никакого инженера, тебя разводят, очнись пожалуйста"),
 ("A5_SH21","IRINA","kitchen","close-up of the woman flaring up in defensive anger, gripping the phone","CU","eye","static","winter_day_2026",False,False,
  "и ты вспыхиваешь, кричишь что она не знает его, что он не такой, что он же вернул те деньги"),
 ("A5_SH22","DASHA","dasha","close-up of the daughter near tears, demanding the total amount","CU","eye","static","winter_day_2026",False,False,
  "даша почти плачет, какие деньги, мам, сколько ты уже ему отправила, назови сумму, сколько"),
 ("A5_SH23","IRINA","kitchen","medium shot of the woman refusing to say the sum, shame curdling into anger","MS","eye","static","winter_day_2026",False,False,
  "ты не называешь сумму, тебе стыдно, и от этого стыда ты злишься на дочь ещё сильнее"),
 ("A5_SH24","IRINA","kitchen","medium shot of the woman shouting into the phone, the fight at its peak","MS","eye","static","winter_day_2026",False,False,
  "вы кричите друг на друга через тысячу километров, впервые в жизни так, до хрипоты и слёз"),
 ("A5_SH25",None,"kitchen","extreme close-up of the phone as the call drops to flat dial tones","ECU","eye","static","winter_day_2026",False,False,
  "даша бросает, разбирайся сама, и в трубке гудки, и ты остаёшься одна в тёмной кухне"),
 ("A5_SH26","IRINA","room","medium shot of the woman sitting shaken, hands unsteady after the call","MS","eye","static","winter_evening_2026",False,False,
  "руки трясутся, ты не понимаешь, как родная дочь могла сказать тебе такое про любимого человека"),
 ("A5_SH27",None,"room","close-up of the phone with Viktor instantly soothing and turning her against her daughter","CU","eye","static","winter_evening_2026",False,False,
  "ты пишешь виктору, и он тут же утешает, дочь ревнует, она не хочет чтобы ты была счастлива"),
 ("A5_SH28","IRINA","room","close-up of the woman choosing to believe him, the isolation settling in","CU","eye","static","winter_evening_2026",False,False,
  "и ты веришь ему, а не ей, он рядом каждый вечер, а даша далеко и только осуждает тебя"),
 ("A5_SH29","IRINA","kitchen","medium shot of the woman paying the first loan installment, going to bed without supper","MS","eye","static","winter_evening_2026",False,False,
  "ты платишь первый взнос по кредиту и ложишься спать без ужина, чтобы хватило до зарплаты"),
 ("A5_SH30",None,"room","close-up of the phone with Viktor's fresh vow that one last payment will bring him home","CU","eye","static","winter_night_2026",False,False,
  "виктор клянётся, ещё чуть-чуть, последний платёж за бумаги, и я наконец сяду в самолёт к тебе"),
 ("A5_SH31","IRINA","room","medium shot of the woman clinging to his words, the only thing she has left","MS","eye","static","winter_night_2026",False,False,
  "и ты держишься за эти слова как за последнее что у тебя осталось, ведь дочь ты уже оттолкнула"),
 ("A5_SH32","IRINA","kitchen","close-up of the woman alone in the dark February kitchen, debt and promises ahead","CU","low","static","winter_night_2026",False,True,
  "за окном февраль, на тебе кредит в четыреста тысяч, и впереди только его обещания, больше ничего"),
]

if __name__ == "__main__":
    seed_act("e5","A5_kaspi_red",MOOD,"0105000000","0155000000","static","act_05_credit_quarrel",SHOTS)
