# -*- coding: utf-8 -*-
"""irreplaceable atmosphere breathers: 2 per act (A1..A11), id_region='a', unique per-act schemes."""
from _irreplaceable_engine import seed_act

PALS = {
 "A1": "warm lamp clutter, paper and dust tones, amber screen glow",
 "A2": "clean audit white, cool glass tones, whiteboard glare",
 "A3": "grey boardroom light, red accent glare, cold window haze",
 "A4": "vendor teal accents, badge-lanyard colours, bright project light",
 "A5": "dual screen glow, split warm and cold light, late office dusk",
 "A6": "warm dumpling steam, evening window lights, amber and grey",
 "A7": "cold datacenter white, badge-reader green, hard even light",
 "A8": "amber offer light, deep office dusk, warm lamp pools",
 "A9": "farewell grey light, cold projector glow, thin winter windows",
 "A10": "night desk lamp amber, deep blue flat shadows, paper white",
 "A11": "bright new office light, plant green accents, warm daylight",
}

ATMO = {
 "A1": [
  ("A1_SZ01", None, "it_room",
   "shelves of labelled backup boxes rising to the ceiling, dates in marker from two decades, one gap in the row",
   "WS", "low", "tilt_up", "day", True, False,
   "бэкапы стоят на стеллажах по годам — двадцать лет компании в коробках с маркером.",
   "dust drifts down the rising shelf faces past the dated marker labels"),
  ("A1_SZ02", None, "warehouse_trade",
   "a scanner cradle row charging at night, small green eyes in the dark warehouse, a forklift parked mid-lane",
   "ECU", "eye", "static", "night", True, False,
   "сканеры спят в зарядках, как птенцы, и старая система считает их сны без ошибок.",
   "the cradle diodes glow their small green row into the dark"),
 ],
 "A2": [
  ("A2_SZ01", None, "meeting_it",
   "the glass meeting-room wall covered edge to edge in sticky notes, one lone red note among the yellow field",
   "WS", "eye", "push_in", "day", True, False,
   "среди жёлтых стикеров аудита есть один красный, и на нём всего два слова.",
   "the red note holds its corner as the yellow field flutters in the vent draught"),
  ("A2_SZ02", None, "street_office",
   "the office centre at lunch, revolving doors spinning people out toward the coffee kiosk, spring glare",
   "WS", "eye", "static", "day", True, False,
   "в обед офис выкручивает людей через вертушку к кофейному киоску, порция за порцией.",
   "the revolving door spins figure after figure into the spring glare",
   None, "crowd"),
 ],
 "A3": [
  ("A3_SZ01", None, "cio_office",
   "the whiteboard diagram of the boxed figure and arrows, half wiped now, the red circle still legible",
   "INSERT", "eye", "static", "evening", True, False,
   "доску артура протёрли наполовину, но красный круг ещё читается — такие круги стираются последними.",
   "the half-wiped diagram ghosts under the surviving red circle"),
  ("A3_SZ02", None, "openspace_trade",
   "the office at night with one lit corner where budget folders stack, a calculator left on",
   "WS", "eye", "static", "night", True, False,
   "по ночам в углу финансистов теперь горит лампа — миграцию считают в третий раз.",
   "the calculator display glows over the stacked budget folders"),
 ],
 "A4": [
  ("A4_SZ01", None, "openspace_trade",
   "a teal vendor banner hung over the project corner, matching mugs on the desks, a burn-down chart poster",
   "ECU", "eye", "pan_right", "day", True, False,
   "у внедренцев всё бирюзовое — баннер, кружки и график сгорания задач.",
   "the banner edge ripples over the matching mugs and the chart poster"),
  ("A4_SZ02", None, "server_room",
   "the cold aisle at night, old handwritten cable tags fluttering beside new printed ones in the airflow",
   "WS", "low", "static", "night", True, False,
   "в холодном ряду двадцать лет рукописных ярлыков дрожат рядом с новыми печатными.",
   "the paper tags flutter their two generations in the steady airflow"),
 ],
 "A5": [
  ("A5_SZ01", None, "warehouse_trade",
   "a warehouse scanner screen split green and teal, a worker's thumb hovering between the halves",
   "ECU", "eye", "static", "day", True, False,
   "на сканерах два мира сразу, и пальцы кладовщиков голосуют за тот, где меньше кнопок.",
   "the hovering thumb drifts toward the teal half of the split screen"),
  ("A5_SZ02", None, "openspace_trade",
   "the office at dusk, the training room lit with rows listening to a projector, the IT-room door dark",
   "WS", "eye", "static", "evening", True, False,
   "вечером учебный класс светится, а дверь каморки стоит тёмная — центр тяжести переехал.",
   "the lit training rows glow against the one dark door down the corridor",
   None, "crowd"),
 ],
 "A6": [
  ("A6_SZ01", None, "pelmennaya",
   "the dumpling café counter, plastic menu letters missing one character, steam drifting from the kitchen hatch",
   "INSERT", "eye", "static", "evening", True, False,
   "в меню пельменной двадцать лет не хватает одной буквы, и это тоже форма стабильности.",
   "kitchen steam drifts past the gap-toothed plastic menu"),
  ("A6_SZ02", None, "street_office",
   "the office bike racks in autumn light with one empty slot in the row, leaves gathering in the vacant loop",
   "WS", "high", "static", "day", True, False,
   "у велопарковки освобождается одна петля, и листья занимают её в тот же день.",
   "leaves gather slowly in the vacant rack loop"),
 ],
 "A7": [
  ("A7_SZ01", None, "datacenter",
   "the colocation hall's long aisle of numbered cages, all identical, a badge reader blinking at each",
   "EWS", "eye", "track", "day", True, False,
   "в цоде все клетки одинаковые, и по номерам здесь ищут не серверы, а прошлое.",
   "the badge readers blink their row down the receding identical aisle"),
  ("A7_SZ02", None, "it_room",
   "the IT room with the empty rack corner, the pale dust rectangle, a chess window open on the lone monitor",
   "WS", "eye", "static", "day", True, False,
   "каморка без сервера звучит иначе — тише на один орган.",
   "the chess window glows alone over the pale dust rectangle"),
 ],
 "A8": [
  ("A8_SZ01", None, "new_office",
   "the new support office at night, four dark monitors, the regulations wall pale in the corridor light",
   "WS", "eye", "static", "night", True, False,
   "новый офис поддержки спит по регламенту — с восьми до восьми, как написано.",
   "corridor light lies pale across the regulation wall and the dark monitors"),
  ("A8_SZ02", None, "boris_flat",
   "a wall calendar in the bachelor flat with wednesdays circled faintly in pencil, every circle left uncrossed",
   "ECU", "eye", "push_in", "night", True, False,
   "в календаре у тебя карандашом обведены среды — обведены, но ни одна не зачёркнута.",
   "lamplight grazes the faint circled wednesdays on the hanging calendar"),
 ],
 "A9": [
  ("A9_SZ01", None, "meeting_it",
   "the ceremony room after everyone left, cake crumbs on plates, the shutdown slide still projected",
   "WS", "eye", "static", "evening", True, False,
   "после церемонии слайд «двадцать лет службы» горит в пустой переговорке ещё час.",
   "the projector holds the farewell slide over the crumbed plates"),
  ("A9_SZ02", None, "datacenter",
   "cage seven with the dark tower, a decommission tag zip-tied to the mesh, white silence",
   "ECU", "low", "static", "night", True, False,
   "на сетке клетки номер семь висит бирка «выведено из эксплуатации» — эпитафия казённым шрифтом.",
   "the decommission tag hangs still against the mesh over the dark tower"),
 ],
 "A10": [
  ("A10_SZ01", None, "boris_flat",
   "the desk at night mid-manual: printed pages, sticky tabs, a ruler, the lamp pool tight and busy",
   "INSERT", "top", "static", "night", True, False,
   "стол превращается в верстак письма — линейка, закладки, три стопки по главам.",
   "the lamp pool holds the busy desk as a page settles onto its stack"),
  ("A10_SZ02", None, "street_office",
   "february sun on the office street, icicles dripping over the coffee kiosk, sparrows loud",
   "WS", "low", "static", "day", True, False,
   "февраль капает с сосулек над киоском, и воробьи орут, как релиз-менеджеры.",
   "icicle drops flash in the sun over the loud sparrow argument"),
 ],
 "A11": [
  ("A11_SZ01", None, "new_office",
   "plants along the office sill in morning light, a watering can with a printed schedule taped to it",
   "ECU", "eye", "static", "morning", True, False,
   "цветы здесь поливают по расписанию, приклеенному к лейке, — и они цветут.",
   "morning light crosses the taped schedule on the waiting watering can"),
  ("A11_SZ02", None, "street_office",
   "spring evening on the office street, the revolving door slow, long light down the plane trees",
   "EWS", "eye", "pull_out", "evening", True, False,
   "весна выходит из офиса вместе с людьми и не оформляет на это заявку.",
   "long light runs the plane trees as the revolving door turns easy",
   None, "crowd"),
 ],
}

if __name__ == "__main__":
    for act, shots in ATMO.items():
        seed_act(act, PALS[act], shots, id_region="a")
