# -*- coding: utf-8 -*-
"""best_thing shots: A9 (the family firm), A10 (the workshop), A11 (the order from the past life)."""
from _best_thing_engine import seed_act

PAL_A9 = "warm team glow, family kitchen amber, working daylight"
PAL_A10 = "workshop warm light, wood and kraft tones, cooler glass shine"
PAL_A11 = "full circle light, celebration warm, winter evening gold"

A9 = [
 ("A9_SH01", ("SERGEY_BASE", "LIDA_BASE"), "family_car",
  "Sergey fits insulation panels into the van bay while Lida holds the thermometer, a family engineering session",
  "MS", "eye", "static", "day", False, False,
  "после свадьбы серёжа утепляет фургон по-настоящему — пенопласт, датчик и урок мороза выучен.",
  "the insulation panel seats into the bay wall under their four hands"),
 ("A9_SH02", "KOLYA_BASE", "lida_kitchen",
  "Kolya edits a reel at the kitchen table: the wedding arch timelapse, headphones on, brows drawn in set focus",
  "MCU", "eye", "static", "evening", False, False,
  "коля монтирует ролик со свадебной аркой, и за ночь его смотрят одиннадцать тысяч человек.",
  "the timelapse scrubs under his set focus as the counter climbs"),
 ("A9_SH03", None, None,
  "the page's inbox stacking order requests, dates requested into next month, one corporate signature visible",
  "ECU", "eye", "static", "evening", False, False,
  "после ролика заказы встают в очередь на месяц вперёд, и среди них первый корпоративный.",
  "request banners stack the inbox over the corporate signature"),
 ("A9_SH04", "LIDA_BASE", "market_corner",
  "Lida trains a hired helper on wrapping, guiding the kraft fold angles, teacher now on her own corner",
  "MS", "eye", "static", "day", False, False,
  "к осени ты берёшь помощницу на выходные и слышишь в своём голосе интонации розы.",
  "her guiding hands set the kraft fold as the helper mirrors it",
  "WRAP"),
 ("A9_SH05", "SERGEY_BASE", "street_market",
  "Sergey loads the morning delivery run, route list on the dash, three boxed bouquets strapped in order",
  "MS", "eye", "static", "morning", False, False,
  "серёжа берёт доставки перед рейсами — три адреса до девяти, и маршрут построен по-водительски точно.",
  "the boxed bouquets strap into their route order under his quick hands"),
 ("A9_SH06", "LIDA_BASE", "flower_base",
  "Lida at the base greets growers by name now, her order set aside and waiting, a regular's standing",
  "WS", "eye", "static", "night", False, False,
  "на базе тебя знают по имени, и твой заказ собирают к приезду — статус, который не купишь.",
  "her set-aside order waits by the gate as greetings pass down the row",
  None, "crowd"),
 ("A9_SH07", None, None,
  "the ledger monthly spread: october closing with a firm plus, the columns thicker, handwriting unchanged",
  "ECU", "top", "static", "night", False, False,
  "октябрь закрывается в плюс на двадцать шесть тысяч, и почерк в тетради всё тот же ровный.",
  "the firm plus settles under the thickened columns",
  "LEDGER"),
 ("A9_SH08", "LIDA_BASE", "lida_kitchen",
  "the family dinner where the plan is drawn on a napkin: a real workshop, rent figures, a sign sketch",
  "WS", "eye", "static", "evening", False, True,
  "за ужином на салфетке появляется план — настоящая мастерская, аренда и вывеска с цветком.",
  "the napkin sketch grows under three leaning heads"),
 ("A9_SH09", "ROZA_BASE", "roza_salon",
  "Roza hears the workshop plan, snorts approvingly, and pulls a box of her old vases from under the counter as a dowry",
  "MCU", "eye", "static", "day", False, False,
  "роза выслушивает план, хмыкает и достаёт из-под прилавка коробку своих старых ваз — «приданое».",
  "the vase box slides from under the counter with the approving snort"),
 ("A9_SH10", "LIDA_BASE", "roza_salon",
  "Lida hugs Roza across the counter, the older woman enduring it exactly two seconds before patting free",
  "WS", "eye", "static", "day", False, False,
  "ты обнимаешь розу через прилавок, и она терпит ровно две секунды — по её меркам это овация.",
  "the counter hug holds its two allotted seconds before the freeing pat"),
 ("A9_SH11", "KOLYA_BASE", "market_corner",
  "Kolya photographs the corner's last market day for the page, documenting the era's end like a pro",
  "MCU", "eye", "static", "day", False, False,
  "последний день угла коля снимает, как хронику, — «мам, это исторический кадр, стой ровно».",
  "his framing hands direct the last market-day shot"),
 ("A9_SH12", None, "market_corner",
  "the emptied corner handed over: bare table, coiled string lights, the price card taken down leaving a bright patch",
  "WS", "eye", "static", "evening", False, False,
  "угол ты сдаёшь чистым, и на стене остаётся светлый след от ценника — три шага на четыре истории.",
  "the coiled lights rest on the bare table under the bright wall patch"),
 ("A9_SH13", ("LIDA_BASE", "SERGEY_BASE"), "workshop",
  "the empty workshop before renovation: Lida and Sergey stand in the bare room planning with pointed fingers",
  "WS", "eye", "static", "day", False, False,
  "мастерская встречает вас голыми стенами, и вы делите её пальцами — тут верстак, тут холодильник, тут крафт.",
  "their pointing fingers zone the bare room wall by wall"),
 ("A9_SH14", "SERGEY_BASE", "workshop",
  "Sergey mounts the workbench, level in his teeth swapped to his hand, checking the bubble twice",
  "MS", "eye", "static", "day", False, False,
  "верстак серёжа ставит по уровню дважды — «у жены руки точные, стол должен соответствовать».",
  "the level bubble centres twice under his checking eye"),
 ("A9_SH15", None, None,
  "the brass shears being laid on a velvet pad on the new workbench, the first object to move in",
  "INSERT", "eye", "static", "day", False, True,
  "первыми в мастерскую въезжают ножницы — на бархатную подложку, как главный инструмент.",
  "the brass rings settle onto the velvet pad in the workbench light",
  "SHEARS"),
 ("A9_SH16", "LIDA_BASE", "workshop",
  "Lida stocks the glass-door cooler with the first workshop buy, arranging buckets by colour temperature",
  "MS", "eye", "static", "day", False, False,
  "холодильник ты заполняешь первой закупкой и расставляешь вёдра по цвету — теперь можно и красиво.",
  "buckets grade by colour behind the closing glass door"),
 ("A9_SH17", "KOLYA_BASE", "workshop",
  "Kolya wires a ring light and phone mount by the workbench, building his mother a content corner",
  "MCU", "eye", "static", "day", False, False,
  "коля монтирует у верстака кольцевую лампу — у мастерской будет свой канал, решено без тебя.",
  "the ring light blinks on over the mounted phone cradle"),
 ("A9_SH18", None, "workshop",
  "the workshop at night before opening: cooler glowing, kraft racked, the velvet pad with shears under the lamp",
  "WS", "eye", "static", "night", True, False,
  "накануне открытия мастерская стоит готовая и тихая, как класс перед первым сентября.",
  "the cooler glow and the lamp share the ready night room"),
]

A10 = [
 ("A10_SH01", ("SERGEY_BASE", "LIDA_BASE"), "workshop",
  "Sergey hangs the pyrography sign over the door while Lida steadies the ladder, the cage lamp waiting",
  "MS", "low", "static", "morning", False, True,
  "вывеску вешаете вдвоём — деревянная, с выжженным цветком, и лампочка над ней тёплая.",
  "the sign settles onto its hooks as the ladder holds steady",
  "SIGN"),
 ("A10_SH02", None, None,
  "the wooden sign lit by the cage lamp, the burned flower crisp, first snow dusting the doorframe",
  "ECU", "low", "static", "morning", False, False,
  "гореть ей каждый вечер до девяти — расписание у лампочки теперь рабочее.",
  "the cage lamp warms the burned flower as snow dusts the frame",
  "SIGN"),
 ("A10_SH03", "LIDA_BASE", "workshop",
  "opening day: Lida serves the first workshop customer, the space working around her like a fitted glove",
  "WS", "eye", "static", "day", False, False,
  "в день открытия приходят одиннадцать человек, и семеро из них — с рынка, твои.",
  "the first customers thread the working space around her wrap station",
  None, "crowd"),
 ("A10_SH04", "LIDA_BASE", "workshop",
  "Lida does the month's books at the workbench, calculator among ribbon spools, the ledger thick now",
  "MS", "eye", "static", "evening", False, False,
  "восьмой месяц дела закрывается в ноль с копейками, и ты знаешь цену этому нулю лучше всех в городе.",
  "the big keys click among the ribbon spools over the thickened ledger",
  "CALC"),
 ("A10_SH05", None, None,
  "the ledger page with the break-even month: income and costs meeting, a clean line drawn beneath",
  "ECU", "top", "static", "evening", False, False,
  "точка безубыточности приходится на март, и под ней ты проводишь линию, как под годовым балансом.",
  "the clean line rules itself under the meeting columns",
  "LEDGER"),
 ("A10_SH06", "ROZA_BASE", "workshop",
  "Roza visits the workshop, walking it slowly, touching the workbench, the cooler, saying nothing for a long time",
  "MS", "eye", "static", "day", False, False,
  "роза приходит без предупреждения, обходит мастерскую молча и трогает верстак, как трогают породу.",
  "her slow inspection hand travels bench to cooler in the silence"),
 ("A10_SH07", "ROZA_BASE", "workshop",
  "Roza's verdict: she straightens one stem in the cooler bucket by two degrees and nods at the room",
  "MCU", "eye", "static", "day", False, True,
  "вердикт у неё короткий — она поправляет один стебель на два градуса и кивает всей мастерской сразу.",
  "the two-degree correction lands and the room-wide nod follows"),
 ("A10_SH08", "LIDA_BASE", "workshop",
  "Lida works a big order at the bench, helper wrapping beside, Sergey's boxes queuing by the door — a small firm running",
  "WS", "eye", "static", "day", False, False,
  "по пятницам вас в мастерской трое, и это уже не хобби, а маленькая фирма с логистикой.",
  "the three-hand rhythm runs bench to wrap to waiting boxes",
  None, "crowd"),
 ("A10_SH09", "KOLYA_BASE", "workshop",
  "Kolya films a wrapping tutorial at the ring light, Lida's hands the star, his direction confident",
  "MCU", "eye", "static", "evening", False, False,
  "ролики коли собирают заказы из соседних районов, и мама-в-кадре у него строго по сценарию.",
  "the ring light rounds her working hands under his framing"),
 ("A10_SH10", ("LIDA_BASE", "SERGEY_BASE"), "courtyard_home",
  "Lida and Sergey walk home through the courtyard at night, tired together, her head briefly on his shoulder",
  "MS", "eye", "track", "night", False, False,
  "домой вы идёте пешком, уставшие одинаково, и это лучшее равенство, какое вы знали.",
  "their tired steps sync through the courtyard as her head tips briefly over"),
 ("A10_SH11", "LIDA_BASE", "lida_kitchen",
  "Lida at the night kitchen, the old fear's chair empty now, tea steaming over the ledger's good news",
  "CU", "eye", "push_in", "night", False, False,
  "ночная кухня больше не место страха — теперь здесь просто пьют чай над хорошей тетрадью.",
  "the tea steam rises easy over the open good-news page",
  "LEDGER"),
 ("A10_SH12", None, "workshop",
  "the workshop through its window at night: sign lit, cooler glowing, the velvet pad catching the lamp",
  "WS", "low", "static", "night", True, False,
  "вечерами мастерская светится на всю улицу двумя огнями — вывеской и холодильником.",
  "the two glows share the window as snow drifts past the sign"),
 ("A10_SH13", "LIDA_BASE", "workshop",
  "Lida teaches a saturday mini-class: three women at the bench, stems in every hand, laughter",
  "MS", "eye", "static", "day", False, False,
  "по субботам ты ведёшь мини-курс на троих, и слово «переделай» произносишь с розиной интонацией.",
  "three learner bouquets rise unevenly under her circling guidance",
  None, "crowd"),
 ("A10_SH14", "LIDA_BASE", "workshop",
  "Lida's face at the bench in warm light, the year visible in it — worn in and lit up at once",
  "CU", "eye", "static", "day", False, False,
  "год назад тебя сократили, и это по-прежнему больно вспоминать — просто теперь это начало истории, а не конец.",
  "warm bench light holds the worn-in lit-up face"),
]

A11 = [
 ("A11_SH01", None, None,
  "an email on the workshop laptop: the old trade company's logo, a corporate event flower order request",
  "ECU", "eye", "static", "day", False, True,
  "в декабре приходит письмо с логотипом, который ты пятнадцать лет видела на пропуске, — заказ на корпоратив.",
  "the familiar logo heads the order request on the workshop laptop"),
 ("A11_SH02", "LIDA_BASE", "workshop",
  "Lida reads the order twice and laughs one clean round laugh at the ceiling",
  "MCU", "eye", "static", "day", False, False,
  "шестьдесят тысяч, оформление зала и «возможно, вы нас помните» — ты смеёшься один раз, звонко.",
  "the clean laugh tips her head back over the glowing screen"),
 ("A11_SH03", "LIDA_BASE", "flower_base",
  "the base run for the corporate order: trolley precise, list checked twice, dawn coming up over the gates",
  "WS", "eye", "static", "night", False, False,
  "закупку под их зал ты собираешь, как когда-то их баланс, — дважды проверив каждую строку.",
  "the precise trolley rolls the dawn rows under the checked list",
  None, "crowd"),
 ("A11_SH04", "LIDA_BASE", "workshop",
  "Lida builds the corporate arrangements at the bench with the brass shears, unhurried mastery, kraft and ribbon flowing",
  "MS", "eye", "static", "day", False, True,
  "собираешь ты сама, теми же ножницами, которыми пятнадцать лет спасала их подоконник.",
  "the brass shears run the stems as kraft and ribbon flow through her hands",
  "SHEARS"),
 ("A11_SH05", "SERGEY_BASE", "office_meeting",
  "Sergey delivers the arrangements into the old meeting room, boxes riding his careful arms past the long table",
  "MS", "eye", "static", "day", False, False,
  "доставляет серёжа — в ту самую переговорку, где вам когда-то показали слайд с полоской до нового года.",
  "the flower boxes ride his careful arms past the long familiar table"),
 ("A11_SH06", None, "office_meeting",
  "the old meeting room transformed: her arrangements down the long table, the projector dark, the room warm for once",
  "WS", "eye", "static", "evening", False, False,
  "переговорка стоит в твоих цветах, и проектор в ней сегодня выключен — хороший баланс.",
  "her arrangements run the long table under the dark projector"),
 ("A11_SH07", "TOMA_BASE", "office_meeting",
  "Toma at the corporate party photographs the flowers and video-calls Lida, panning the room proudly",
  "MCU", "eye", "static", "evening", False, False,
  "тома звонит с корпоратива и водит камерой по залу — «лид, тут все спрашивают, чьи цветы».",
  "her proud pan sweeps the flowered room into the call"),
 ("A11_SH08", "LIDA_BASE", "workshop",
  "Lida takes the call at the workbench, the workshop warm behind her, waving at her old world through the screen",
  "MCU", "eye", "static", "evening", False, False,
  "ты машешь в экран из мастерской, и оба твоих мира наконец здороваются друг с другом.",
  "her wave crosses the call as the workshop glows behind"),
 ("A11_SH09", None, None,
  "the ledger's december spread: the corporate order entered, the year's totals beneath, a firm confident hand",
  "ECU", "top", "static", "night", False, False,
  "заказ ложится в тетрадь строкой на шестьдесят тысяч, и годовой итог под ним уже не стыдно показать томе.",
  "the confident entry settles over the year's honest totals",
  "LEDGER"),
 ("A11_SH10", "LIDA_BASE", "workshop",
  "Lida's face to the lens at the workbench, the velvet pad and shears before her, a woman exactly where she works best",
  "MCU", "eye", "push_in", "evening", False, False,
  "подпишись и останься — на этом канале не все истории про увольнение кончаются плохо, но все — по-настоящему.",
  "her settled gaze finds the lens over the velvet pad and the brass rings"),
 ("A11_SH11", None, None,
  "the final image: brass shears on the velvet pad, the big-key calculator beside, the lit sign through the window beyond",
  "INSERT", "eye", "push_in", "night", False, True,
  "ножницы на бархате, калькулятор рядом — две профессии на одном верстаке, и обе твои.",
  "lamplight bridges the shears and the calculator as the sign glows beyond",
  "SHEARS"),
 ("A11_SH12", None, "workshop",
  "the workshop window from the snowy street at night, warm and full, the sign's flower crisp under its lamp",
  "WS", "eye", "pull_out", "night", False, False,
  "эта история вымышлена, совпадения случайны — а хорошие ошибки всё равно делай свои.",
  "snow drifts past the warm full window under the crisp burned flower"),
]

if __name__ == "__main__":
    seed_act("A9", PAL_A9, A9)
    seed_act("A10", PAL_A10, A10)
    seed_act("A11", PAL_A11, A11)
