# -*- coding: utf-8 -*-
"""A8 (act_08_no_return) — Dasha flies in, reverse-image-search reveal, the airport message slams the window shut."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from _seed_message_act_engine import seed_act

MOOD = ("tense spring daylight turning to evening lamp, palette of truth-grey clashing with false-hope amber, "
        "hard emotional high-contrast, climactic mood")

# ch may be ("IRINA","DASHA") for dual two-shots (left=IRINA, right=DASHA)
SHOTS = [
 ("A8_SH01","IRINA","kitchen","close-up of the gaunt woman in panic at the kitchen table on the deadline morning","CU","eye","static","spring_day_2026",False,False,
  "наступает пятница, день аукциона, а у тебя нет ни тенге, и взять негде, ты в полном отчаянии"),
 ("A8_SH02",None,"kitchen","extreme close-up of the phone with Viktor pressuring her hourly not to fail at the last step","ECU","eye","static","spring_day_2026",False,False,
  "виктор пишет каждый час, успеешь родная, осталось чуть-чуть, не подведи нас в самый последний момент"),
 ("A8_SH03","DASHA","dasha","medium shot of the daughter in Astana unable to reach her mother for a week, sick with worry","MS","eye","static","spring_day_2026",False,False,
  "а в астане даша уже неделю не может до тебя дозвониться, и сердце её совсем не на месте"),
 ("A8_SH04","DASHA","dasha","close-up of the daughter booking the first flight to Petropavlovsk","CU","eye","static","spring_day_2026",False,False,
  "она берёт билет на первый рейс до петропавловска, отпрашивается с работы и летит к матери"),
 ("A8_SH05","IRINA","street","wide shot of the worn woman going door to door asking anyone left for a loan","WS","eye","static","spring_day_2026",False,False,
  "ты в это время обиваешь пороги, просишь в долг у всех кто ещё не отвернулся от тебя"),
 ("A8_SH06","DASHA","street","medium shot of the daughter arriving by taxi at the grey panel block at dusk","MS","eye","static","spring_day_2026",False,False,
  "даша приезжает к твоему дому под вечер, поднимается на девятый этаж и звонит в дверь"),
 ("A8_SH07","IRINA","stair","medium shot of the woman frozen in the doorway seeing the daughter she pushed away","MS","eye","static","spring_evening_2026",False,False,
  "ты открываешь и застываешь, на пороге дочь, которую ты оттолкнула полгода назад"),
 ("A8_SH08",("IRINA","DASHA"),"room","wide shot, the older woman on the left and her daughter on the right, the daughter frozen at the stripped empty room","WS","eye","static","spring_evening_2026",False,False,
  "даша входит и замирает, нет телевизора, нет ковра, пустые полки, мать худая и седая"),
 ("A8_SH09","DASHA","room","close-up of the daughter's legs nearly buckling with horror","CU","eye","static","spring_evening_2026",False,False,
  "у неё подкашиваются ноги, мам, что здесь произошло, где все вещи, что с тобой стало"),
 ("A8_SH10",("IRINA","DASHA"),"room","medium shot, the mother on the left mumbling a deflection, the daughter on the right not believing it","MS","eye","static","spring_evening_2026",False,False,
  "ты бормочешь что всё нормально, что просто решила обновить, но голос выдаёт тебя сразу"),
 ("A8_SH11","DASHA","room","close-up of the daughter taking her mother's hands, gentle but firm","CU","eye","static","spring_evening_2026",False,False,
  "даша садится рядом, берёт твои руки, мам, покажи мне переписку с виктором, прошу тебя"),
 ("A8_SH12",("IRINA","DASHA"),"room","medium shot, the mother on the left handing over the phone, the daughter on the right taking it carefully","MS","eye","static","spring_evening_2026",False,False,
  "и ты впервые за полгода даёшь кому-то телефон, потому что слишком устала держать это одна"),
 ("A8_SH13","DASHA","room","close-up of the daughter's face hardening as she reads every request and transfer","CU","eye","static","spring_evening_2026",False,False,
  "даша читает, листает, и лицо её каменеет, она видит каждую просьбу, каждую сумму, каждый перевод"),
 ("A8_SH14",None,"room","extreme close-up of the single profile photo of the man in the orange hard hat on the phone","ECU","eye","static","spring_evening_2026",False,False,
  "она открывает единственное фото, мужчина в оранжевой каске, и хмурится, мам, это точно он"),
 ("A8_SH15","DASHA","room","medium close-up of the daughter saving the photo and running a reverse image search","MCU","eye","static","spring_evening_2026",False,False,
  "она сохраняет фото и загружает в поиск по картинке, прямо при тебе, на своём телефоне"),
 ("A8_SH16",None,"room","extreme close-up of a screen of reverse-search results, the same face on dozens of foreign pages","ECU","eye","push_in","spring_evening_2026",False,True,
  "и экран выдаёт десятки страниц, это фото испанского фотографа, его крадут мошенники по всему миру"),
 ("A8_SH17",("IRINA","DASHA"),"room","medium shot, the daughter on the right turning the screen toward the stunned mother on the left","MS","eye","static","spring_evening_2026",False,False,
  "она поворачивает экран к тебе, смотри мама, это сток, его лицо на сотне чужих анкет"),
 ("A8_SH18","IRINA","room","close-up of the woman as the ground drops away, the truth almost landing","CU","eye","static","spring_evening_2026",False,False,
  "и на секунду земля уходит из-под ног, ты смотришь на эти страницы, и внутри всё обрушивается"),
 ("A8_SH19","DASHA","room","close-up of the daughter holding her mother, telling her it is not her fault","CU","eye","static","spring_evening_2026",False,False,
  "даша обнимает тебя, мам, его нет, его никогда не было, ты ни в чём не виновата, это болезнь"),
 ("A8_SH20",("IRINA","DASHA"),"room","medium shot, the mother on the left almost letting go, shoulders dropping, the daughter on the right holding her","MS","eye","static","spring_evening_2026",False,False,
  "и ты почти веришь дочери, почти отпускаешь, плечи опускаются, ты готова заплакать и проснуться"),
 ("A8_SH21",None,"room","extreme close-up of the phone lighting up at that exact second with an airport message","ECU","eye","push_in","spring_evening_2026",False,True,
  "и в эту самую секунду телефон вспыхивает, любимая, я прошёл таможню, я в аэропорту астаны"),
 ("A8_SH22","IRINA","room","close-up of the woman's face as the fantasy roars back to life","CU","eye","static","spring_evening_2026",False,False,
  "он пишет, не хватает только на билет до тебя, восемьдесят тысяч, и через три часа я обниму тебя"),
 ("A8_SH23",("IRINA","DASHA"),"room","medium shot, the mother on the left clutching the phone with desperate hope, the daughter on the right reaching for her","MS","eye","static","spring_evening_2026",False,False,
  "и всё что собрала даша рассыпается, ведь он уже здесь, в стране, прошёл таможню, почти рядом"),
 ("A8_SH24","IRINA","room","close-up of the woman seizing the phone, choosing the lie over the proof","CU","eye","static","spring_evening_2026",False,False,
  "ты вырываешь телефон, ты говоришь, видишь, он не врал, он приехал, а ты не верила в него"),
 ("A8_SH25",("IRINA","DASHA"),"room","medium shot, the daughter on the right begging in tears, the mother on the left turning away","MS","eye","static","spring_evening_2026",False,False,
  "даша плачет, мам это бот, это скрипт, он пишет это тысяче женщин прямо сейчас, не отправляй ничего"),
 ("A8_SH26",("IRINA","DASHA"),"room","medium shot, the mother on the left pushing the daughter's hands away on the right, shouting","MS","eye","static","spring_evening_2026",False,False,
  "но ты уже не слышишь, ты отталкиваешь её руки, ты кричишь что она всё испортит в последний момент"),
 ("A8_SH27","DASHA","room","close-up of the daughter looking at her mother like a stranger, defeated by a ghost","CU","eye","static","spring_evening_2026",False,False,
  "даша смотрит на тебя как на чужую, и понимает что проиграла какому-то призраку из телефона"),
 ("A8_SH28",("IRINA","DASHA"),"stair","medium shot, the daughter leaving on the right, the mother on the left not stopping her","MS","eye","static","spring_evening_2026",False,False,
  "она уходит, ты не останавливаешь, дверь закрывается, и в пустой квартире снова только ты и телефон"),
 ("A8_SH29","IRINA","kitchen","close-up of the woman feverishly scraping together the last sum she can find","CU","eye","static","spring_night_2026",False,False,
  "ты лихорадочно ищешь восемьдесят тысяч, последний микрозайм, занимаешь у соседки сверху на билет"),
 ("A8_SH30",None,"kitchen","extreme close-up of the Kaspi transfer of 80 000 tenge for the ticket","ECU","eye","static","spring_night_2026",False,False,
  "ты переводишь восемьдесят тысяч на билет и пишешь, я жду тебя, я всё это время ждала только тебя"),
 ("A8_SH31","IRINA","kitchen","medium shot of the woman with a pounding heart reading his reply","MS","eye","static","spring_night_2026",False,False,
  "он отвечает, бегу на регистрацию родная, скоро, скоро, и сердце твоё колотится от счастья"),
 ("A8_SH32","IRINA","room","close-up of the woman tidying the bare flat and putting on her best dress","CU","eye","static","spring_night_2026",False,False,
  "ты прибираешь пустую квартиру, надеваешь лучшее платье и садишься у окна ждать его звонка из астаны"),
 ("A8_SH33","IRINA","room","medium shot of the woman waiting by the window, imagining him boarding the plane","MS","eye","static","spring_night_2026",False,False,
  "ты ждёшь час, потом два, ты представляешь как он садится в самолёт и летит к тебе через всю степь"),
 ("A8_SH34","IRINA","kitchen","close-up of the woman by the dark window as the phone stays silent and dread creeps in","CU","low","static","spring_night_2026",False,True,
  "но телефон молчит, и за окном темнеет, и где-то глубоко ты уже чувствуешь что что-то не так"),
]

if __name__ == "__main__":
    seed_act("e8","A8_daylight_truth",MOOD,"0108000000","0158000000","static","act_08_no_return",SHOTS)
