# -*- coding: utf-8 -*-
"""Seed CH03 — 1961, Стену возводят, отец остаётся на той стороне (2nd person). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "grey shock of August 1961, a city split overnight by concrete and barbed wire, cold dread"
SHOTS = [
 ("CH03_SH01", None, "street_east",
  "medium shot of a grey East Berlin street on an August 1961 morning, people stopped in shock",
  "MS","eye","static","gdr_day",True,False,
  "тебе восемь, когда однажды августовским утром весь город просыпается рассечённым ровно надвое."),
 ("CH03_SH02", None, "the_wall",
  "wide of soldiers raising the first barrier, barbed wire and concrete blocks going up",
  "WS","eye","static","gdr_day",True,False,
  "за одну ночь посреди Берлина встаёт стена, бетон, колючая проволока, солдаты с автоматами."),
 ("CH03_SH03", None, "the_wall",
  "medium shot of silent people staring at the new barrier cutting their street",
  "MS","eye","static","gdr_day",True,False,
  "люди молча стоят и смотрят, как их улицу, их город разрезают наглухо, навсегда."),
 ("CH03_SH04", "MOTHER", "the_wall",
  "medium close-up of the mother gripping the child's hand, staring across the wall",
  "MCU","eye","static","gdr_day",False,False,
  "мать стискивает твою ладонь и впивается взглядом в ту сторону, где утром остался отец."),
 ("CH03_SH05", None, "the_wall",
  "extreme close-up of a hand pressed against cold raw concrete",
  "ECU","eye","static","gdr_day",True,True,
  "отец уехал на ту сторону по работе, и стена захлопнулась между вами уже навсегда."),
 ("CH03_SH06", None, "checkpoint",
  "medium of armed guards at a stark border checkpoint, striped barrier down",
  "MS","eye","static","gdr_day",True,False,
  "теперь там вооружённый кпп, и пройти к нему нельзя, отца у тебя больше нет."),
 ("CH03_SH07", None, "the_wall",
  "close-up of a child's upturned face looking up at the towering wall",
  "CU","low","static","gdr_day",True,False,
  "ты стоишь у серой стены и не понимаешь, как папа мог исчезнуть просто так, за бетоном."),
 ("CH03_SH08", "MOTHER", "childhood_flat",
  "medium shot of the mother hardened and bitter at home",
  "MS","eye","static","gdr_eve",False,False,
  "мать ожесточается совсем, бросил, сбежал на свой Запад, шипит она сквозь стиснутые зубы."),
 ("CH03_SH09", None, "the_wall",
  "wide of the grey wall stretching away into the haze",
  "WS","eye","pan","gdr_day",True,False,
  "а ты каждый день смотришь на стену и думаешь, там, за ней, тебя кто-то всё же любит."),
 ("CH03_SH10", None, "the_wall",
  "extreme close-up of barbed wire against a pale sky",
  "ECU","low","static","gdr_day",True,False,
  "та сторона становится твоей мечтой, всё запретное и недостижимое манит тебя сильнее всего."),
 ("CH03_SH11", None, "the_wall",
  "close-up of a small child's silhouette dwarfed against the wall",
  "CU","eye","static","gdr_day",True,True,
  "так в восемь лет ты усваиваешь, что любовь, это всегда то, до чего нельзя дотянуться."),
 ("CH03_SH12", None, "the_wall",
  "wide B-roll of the wall at dusk under floodlights, silent",
  "WS","eye","static","night",True,False,""),
]
if __name__ == "__main__":
    seed_act(3, "wall_concrete", MOOD, "static", "CH03 Wall 1961", SHOTS)
