# -*- coding: utf-8 -*-
"""monotown shots: A9 (the last horn), A10 (the garages), A11 (seven-thirty in chalk)."""
from _monotown_engine import seed_act

PAL_A9 = "last shift gold, long slanting light, iron dust motes"
PAL_A10 = "grey thaw tones, garage lantern warm, wet concrete"
PAL_A11 = "spark morning light, chalk white accents, fog silver and gold"

A9 = [
 ("A9_SH01", None, "shop_floor",
  "the last shift morning: a dozen men at the remaining machines, the shop swept clean as for an inspection",
  "WS", "eye", "static", "morning", False, False,
  "последнюю смену цех встречает выметенным до бетона — уходить решили по-заводски, чисто.",
  "the swept aisle shines under the dozen working stations",
  None, "crowd"),
 ("A9_SH02", "MATVEY_BASE", "shop_floor",
  "Matvey signs the last stack of clearance sheets at the foreman desk, each man waiting his turn with his tag",
  "MS", "eye", "static", "day", False, False,
  "обходные последней смены ты подписываешь по одному, и на каждый уходит дольше, чем положено.",
  "the last stack thins sheet by sheet under his unhurried pen",
  "BYPASS"),
 ("A9_SH03", ("MATVEY_BASE", "PETROVICH_BASE"), "shop_floor",
  "Petrovich, come back for the day as a volunteer, helps grease and sheet the last machines for mothballing",
  "MS", "eye", "static", "day", False, False,
  "петрович приходит добровольцем — консервировать станки, которые пережили его увольнение.",
  "grease works into the beds under the four veteran hands",
  None, "crowd"),
 ("A9_SH04", None, None,
  "Matvey's own clearance sheet on the desk, every box stamped, the foreman line empty — his own name above it",
  "ECU", "top", "static", "day", False, True,
  "последний обходной на столе — твой собственный, и графа мастера в нём пустая.",
  "the empty foreman line waits under his own printed name",
  "BYPASS"),
 ("A9_SH05", "MATVEY_BASE", None,
  "his own hand signing the foreman line of his own clearance sheet, the pen steady, the loop closing",
  "POV", "pov", "static", "day", False, False,
  "ты подписываешь сам себе — мастер увольняет мастера, и подпись выходит ровной.",
  "the pen closes the loop on the foreman line in one even stroke",
  "BYPASS"),
 ("A9_SH06", "MATVEY_BASE", "horn_room",
  "Matvey in the horn cabin unhooks the fixing chain from the brass lever, the schedule plate dusted clean",
  "CU", "eye", "static", "day", False, False,
  "в будке гудка ты снимаешь цепочку с рычага — приказ приказом, а проводить город положено.",
  "the fixing chain slips its hook under his deliberate hand",
  "HORN"),
 ("A9_SH07", "MATVEY_BASE", "horn_room",
  "Matvey pulls the lever: three long blasts, his arm riding the brass, his eyes shut on the third",
  "MS", "eye", "static", "day", False, True,
  "три длинных — по одному на смену, — и на третьем ты закрываешь глаза.",
  "his arm rides the lever through the three long pulls",
  "HORN"),
 ("A9_SH08", None, "town_square",
  "the town square stopping mid-step at the horn: heads lifting, a woman's hand to her mouth, pigeons bursting up",
  "WS", "eye", "static", "day", False, False,
  "город останавливается посреди шага — гудок среди тишины все понимают правильно.",
  "lifted heads hold the square still as the pigeons burst",
  None, "crowd"),
 ("A9_SH09", "GALYA_BASE", "town_square",
  "Galya at the ambulatory door listens to the three blasts, her hand finding the doorframe",
  "CU", "eye", "static", "day", False, False,
  "галя слушает три длинных, держась за косяк, и считает их, как пульс.",
  "her hand steadies on the frame through the counted blasts"),
 ("A9_SH10", "MATVEY_BASE", "shop_floor",
  "Matvey walks the dead shop pulling the row breakers down one by one, lights dying band by band behind him",
  "WS", "eye", "track", "evening", False, True,
  "рубильники ты опускаешь по порядку, и свет уходит из цеха полосами, как отлив.",
  "light bands die behind his walk breaker by breaker",
  None, "crowd"),
 ("A9_SH11", None, None,
  "the glory banner in the last lit band, then the light going, the fringe vanishing into the dark",
  "ECU", "low", "static", "evening", False, False,
  "«слава труду» уходит в темноту последней — над ней свет держится на секунду дольше.",
  "the fringe holds its extra second before the dark takes it",
  "BANNER"),
 ("A9_SH12", ("MATVEY_BASE", "RECEIVER_BASE"), "plant_gate_m",
  "Matvey hands the key ring to the receiver at the checkpoint, the exchange correct and glacial",
  "MS", "eye", "static", "evening", False, False,
  "ключи ты сдаёшь управляющему под опись, и рукопожатия в этой процедуре не предусмотрено.",
  "the key ring crosses under the checklist in strict handshake-free formality"),
 ("A9_SH13", "RECEIVER_BASE", "plant_gate_m",
  "the receiver pauses a beat too long over the keys, something almost human crossing the neutral face, then gone",
  "CU", "eye", "static", "evening", False, False,
  "управляющий задерживает ключи в руке на лишнюю секунду — даже функции бывает неловко.",
  "the almost-human beat crosses the neutral face and dissolves"),
 ("A9_SH14", "MATVEY_BASE", "plant_gate_m",
  "Matvey flips his number tag off the shift board last, pocketing it, the board left bare",
  "MCU", "eye", "static", "evening", False, False,
  "свой номерок ты снимаешь с доски последним и уносишь в кармане — доска остаётся голой.",
  "the last tag leaves the bare board into his pocket"),
 ("A9_SH15", "MATVEY_BASE", "town_street",
  "Matvey walks home down the main street in the first evening of the stopped plant, the town's new silence walking with him",
  "BACK", "eye", "track", "evening", False, False,
  "домой ты идёшь через город, который впервые за восемьдесят лет не слышит за спиной завода.",
  "his silhouette carries the new silence down the papered street",
  None, "crowd"),
 ("A9_SH16", ("MATVEY_BASE", "GALYA_BASE"), "matvey_kitchen",
  "Galya meets Matvey with supper held warm, taking his cap with both hands like a helmet after battle",
  "CU", "eye", "static", "evening", False, False,
  "галя забирает у тебя кепку двумя руками, как каску после боя, и ставит греть ужин.",
  "the cap passes into her two receiving hands at the door"),
 ("A9_SH17", None, "overlook",
  "the plant from the rise at night: fully dark for the first time, a moonlit hulk, the town lights small before it",
  "EWS", "high", "static", "night", False, False,
  "с пригорка завод впервые стоит целиком тёмный — гора железа под луной.",
  "the moonlit hulk holds its full dark over the small town lights"),
 ("A9_SH18", None, None,
  "the brass whistle laid in the kitchen drawer on a folded cloth, the drawer easing shut",
  "INSERT", "eye", "static", "night", False, False,
  "свисток ложится в ящик на сложенную тряпицу — мастеру без цеха свистеть некому.",
  "the drawer eases shut over the cloth-cradled whistle",
  "WHISTLE"),
]

A10 = [
 ("A10_SH01", None, "meeting_dk",
  "the employment office set up in the house of culture foyer: two desks, a queue of work jackets, forms on a ping-pong table",
  "WS", "eye", "static", "day", False, False,
  "центр занятости разворачивают в фойе дк — две стойки, очередь и анкеты на теннисном столе.",
  "the jacket queue shuffles past the two desks and the form table",
  None, "crowd"),
 ("A10_SH02", "MATVEY_BASE", "meeting_dk",
  "Matvey fills the unemployment form, his handwriting too neat for the flimsy paper, the whistle cord visible at his collar",
  "MCU", "eye", "static", "day", False, False,
  "анкету ты заполняешь чертёжным почерком, и графа «желаемая должность» смотрит на тебя пусто.",
  "his neat hand overqualifies the flimsy form line by line"),
 ("A10_SH03", None, "town_street",
  "grey thaw on the main street, meltwater running past the papered shopfronts, a bus with three passengers",
  "WS", "eye", "static", "day", True, False,
  "серые месяцы город пережидает, как непогоду, — экономно и не глядя друг другу в глаза.",
  "meltwater threads the gutter past the three-passenger bus",
  None, "crowd"),
 ("A10_SH04", "PETROVICH_BASE", "garage_coop",
  "Petrovich at the lathe turns hinge pins, a crate of finished ones filling, the garage warm with work",
  "MS", "eye", "static", "day", False, False,
  "у петровича в гараже точатся петли для полгорода — крышки погребов, ворота, теплицы.",
  "hinge pins drop into the filling crate off the steady lathe",
  "LATHE"),
 ("A10_SH05", ("PETROVICH_BASE", "MATVEY_BASE"), "garage_coop",
  "Petrovich hands Matvey the artel ledger and points at the master column left empty for him",
  "MCU", "eye", "static", "day", False, True,
  "петрович суёт тебе тетрадь артели и тычет в пустую графу — «мастер нужен, боря, без мастера мы кружок».",
  "his finger lands on the empty master column of the offered ledger",
  "LATHE"),
 ("A10_SH06", "MATVEY_BASE", "garage_coop",
  "Matvey looks down the garage row: three doors open now, benches and vices visible, men at work",
  "WS", "eye", "static", "day", False, False,
  "ты смотришь вдоль ряда — три открытые секции, верстаки, тиски, и у каждого руки по делу.",
  "the three open doors line his look with benches and working backs",
  None, "crowd"),
 ("A10_SH07", "MATVEY_BASE", "garage_coop",
  "Matvey takes the whistle from his pocket and hangs it on a nail over Petrovich's bench, the appointment accepted",
  "MCU", "eye", "static", "day", False, True,
  "ты достаёшь свисток и вешаешь на гвоздь над верстаком — мастер вступает в должность.",
  "the whistle settles on its new nail over the bench",
  "WHISTLE"),
 ("A10_SH08", None, None,
  "the artel ledger's first pages: seven names, small orders listed with sums, the master column now signed",
  "ECU", "top", "static", "evening", False, False,
  "в тетради семь фамилий и первые заказы — петли, оградка, два крыльца, ремонт культиватора.",
  "the signed master column heads the small honest sums"),
 ("A10_SH09", "MATVEY_BASE", "garage_coop",
  "Matvey organises the row like a shop: work split between garages, a chalk board of orders on a door",
  "MS", "eye", "track", "day", False, False,
  "ты раскладываешь работу по секциям, как по пролётам, и на воротах появляется меловая доска нарядов.",
  "his chalk splits the orders across the door board",
  "GRINDER"),
 ("A10_SH10", "SANYA_BASE", "garage_coop",
  "Sanya, home for the weekend, welds a fence section in the yard between garages, his father holding the square",
  "WS", "eye", "static", "day", False, False,
  "саня приезжает на выходные и варит секции оград — в области смены, дома артель.",
  "his weld runs the fence seam as the square holds true",
  None, "crowd"),
 ("A10_SH11", "GALYA_BASE", "garage_coop",
  "Galya brings a pot of soup to the garage row at noon, feeding the artel off the spool table",
  "MS", "eye", "static", "day", False, False,
  "галя приносит в гаражи суп на семерых, и обед у артели становится узаконенным.",
  "the pot lands on the spool table as bowls gather",
  None, "crowd"),
 ("A10_SH12", None, "garage_coop",
  "the chalk order board on the garage door: lines of jobs, half struck through, dates in a firm hand",
  "ECU", "eye", "static", "evening", False, False,
  "меловая доска нарядов заполняется и стирается, как положено доске, — работой.",
  "chalk lines strike through job after job in the firm hand"),
 ("A10_SH13", "MATVEY_BASE", "overlook",
  "Matvey on the rise looks from the dark plant to the garage row's lit doors, the town's pulse relocated",
  "MS", "eye", "static", "evening", False, False,
  "с пригорка видно оба огня — тёмный завод и светящиеся гаражи, и пульс города теперь во втором.",
  "his look bridges the dark hulk and the lit garage row"),
 ("A10_SH14", "MATVEY_BASE", "garage_coop",
  "Matvey's face in the garage lantern light, master again in a shop of seven, the tiredness honest",
  "CU", "eye", "push_in", "evening", False, False,
  "у тебя снова есть цех — на семь человек, без гудка, зато без управляющего.",
  "the lantern light settles on the honest master's tiredness"),
]

A11 = [
 ("A11_SH01", None, None,
  "an email printout on the spool table: a regional construction order for fence sections, four hundred eighty thousand",
  "ECU", "top", "static", "day", False, True,
  "весной приходит настоящий заказ — ограждения для областной стройки, четыреста восемьдесят тысяч.",
  "the printed order lies square on the spool table under the sum"),
 ("A11_SH02", ("MATVEY_BASE", "PETROVICH_BASE"), "garage_coop",
  "Matvey and Petrovich read the order together, the old shop arithmetic waking in both faces",
  "MCU", "eye", "static", "day", False, False,
  "вы читаете заказ вдвоём, и в глазах у обоих просыпается цеховая арифметика — успеем, если по-заводски.",
  "the shared read lights the old arithmetic in both faces"),
 ("A11_SH03", "MATVEY_BASE", "garage_coop",
  "Matvey plans the order on the chalk board: sections split by garage, dates, a supply column",
  "MS", "eye", "static", "day", False, False,
  "ты раскидываешь заказ по секциям мелом — прокат, резка, сварка, покраска, отгрузка.",
  "the chalk plan grows its five columns across the door",
  "GRINDER"),
 ("A11_SH04", None, "garage_coop",
  "the garage row at seven thirty: doors rolling up in sequence, tools starting, the row waking like a shift",
  "WS", "eye", "static", "morning", False, True,
  "в семь тридцать секции открываются по очереди — расписание живёт, просто адрес сменился.",
  "doors roll up in sequence as the row wakes to its shift",
  None, "crowd"),
 ("A11_SH05", "SANYA_BASE", "garage_coop",
  "Sanya welds fence sections with two local young men watching and learning, the next generation forming",
  "MS", "eye", "static", "day", False, False,
  "саня варит и учит двух местных пацанов — у артели появляется своя молодёжь.",
  "his seam draws the two watching heads closer to the work",
  None, "crowd"),
 ("A11_SH06", None, None,
  "sparks fountaining from the angle grinder onto wet concrete, bouncing gold against the grey",
  "ECU", "eye", "static", "day", False, False,
  "искры от болгарки скачут по мокрому бетону — золото по-серому, живой цвет города.",
  "grinder sparks bounce their gold across the wet grey",
  "GRINDER"),
 ("A11_SH07", None, "plant_yard_m",
  "finished fence sections loading onto a flatbed at the garage row, stacked neat, strapped by many hands",
  "WS", "eye", "static", "day", False, False,
  "готовые секции грузят всем рядом, и штабель на платформе стоит по-заводски ровно.",
  "the neat stack straps down under the many working hands",
  None, "crowd"),
 ("A11_SH08", "MATVEY_BASE", "garage_coop",
  "Matvey signs the delivery note on the flatbed door, the artel's first big paper, Petrovich witnessing",
  "MCU", "eye", "static", "day", False, False,
  "накладную ты подписываешь на дверце платформы, и это первая большая бумага артели.",
  "his signature lands on the door-braced delivery note"),
 ("A11_SH09", "GALYA_BASE", "matvey_kitchen",
  "Galya pins her medical watch on at the morning kitchen, the plant dark in the window but the town alive below it",
  "MCU", "eye", "static", "morning", False, False,
  "галя прикалывает часики у окна, за которым завод тёмный, а город — нет.",
  "the watch pins on against the window's dark hulk and live street"),
 ("A11_SH10", "MATVEY_BASE", "garage_coop",
  "Matvey's face to the lens at the garage bench, the whistle on its nail behind him, a master with a shop again",
  "CU", "eye", "push_in", "day", False, False,
  "подпишись и останься — на этом канале даже выключенные города ищут, где включиться обратно.",
  "his settled gaze holds the lens under the nailed whistle",
  "WHISTLE"),
 ("A11_SH11", None, "garage_coop",
  "chalk on the garage gate: the figures seven-thirty written large, doubled by habit and pride",
  "INSERT", "eye", "static", "morning", False, True,
  "на воротах гаража мелом выведено «семь тридцать» — расписание смены, как раньше, только своё.",
  "morning light hardens the chalked seven-thirty on the steel gate"),
 ("A11_SH12", None, "overlook",
  "morning fog over the dark plant beyond the fence, and below it the garage row with one door up and sparks inside",
  "EWS", "high", "pull_out", "morning", False, False,
  "эта история вымышлена, все совпадения случайны — не повторяй чужих ошибок.",
  "fog holds the dark hulk as sparks flicker in the one open door below"),
]

if __name__ == "__main__":
    seed_act("A9", PAL_A9, A9)
    seed_act("A10", PAL_A10, A10)
    seed_act("A11", PAL_A11, A11)
