# -*- coding: utf-8 -*-
"""A4 (act_04_first_transfer) — first big transfer 250 000 tenge (cargo customs lie), empties Halyk savings."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from _seed_message_act_engine import seed_act

MOOD = ("cold institutional bank light against night-kitchen blue, anxious palette of hope shadowed by dread, "
        "harder high-contrast creeping in")

SHOTS = [
 ("A4_SH01","IRINA","room","close-up of the woman beaming at her phone, pure joy on her tired face","CU","eye","static","winter_evening_2025",False,False,
  "и вот оно, он пишет, контракт заканчивается через две недели, я наконец лечу к тебе"),
 ("A4_SH02","IRINA","room","medium shot of the woman pressing the phone to her chest, counting days in her head","MS","eye","static","winter_evening_2025",False,False,
  "ты прижимаешь телефон к груди, считаешь дни, никому пока не говоришь, боишься спугнуть"),
 ("A4_SH03",None,"room","close-up of the phone screen choosing a flight date and arrival plans","CU","eye","static","winter_evening_2025",False,False,
  "вы выбираете дату, рейс на астану, ты уже знаешь у какого выхода будешь стоять"),
 ("A4_SH04","IRINA","kitchen","medium shot of the woman reading an alarmed message, her smile fading","MS","eye","static","winter_evening_2025",False,False,
  "за день до вылета он пишет встревоженно, возникла проблема с его контейнером"),
 ("A4_SH05",None,"kitchen","extreme close-up of the phone, a message about cargo stuck at port customs","ECU","eye","static","winter_evening_2025",False,False,
  "он везёт домой инструмент и подарок тебе, но груз застрял на таможне в порту"),
 ("A4_SH06","IRINA","kitchen","medium close-up of the woman frowning as she reads about an insurance fee","MCU","eye","static","winter_evening_2025",False,False,
  "чтобы растаможить, нужна страховка груза, а его деньги заморожены до берега"),
 ("A4_SH07",None,"kitchen","extreme close-up of the phone with a long ashamed pleading message from Viktor","ECU","eye","static","winter_evening_2025",False,False,
  "ему мучительно стыдно просить, он пишет что вернёт втрое с расчётных, это наше будущее"),
 ("A4_SH08",None,"kitchen","extreme close-up of the phone screen naming the sum and a colleague's Kaspi card","ECU","eye","push_in","winter_evening_2025",False,True,
  "нужно двести пятьдесят тысяч тенге, перевести его коллеге марату, тот всё оформит в порту"),
 ("A4_SH09","IRINA","kitchen","medium shot of the woman going still, the shock of the sum on her face","MS","eye","static","winter_evening_2025",False,False,
  "у тебя обрывается внутри, это почти все твои сбережения в халыке, копила годами"),
 ("A4_SH10","IRINA","room","medium shot of the woman lying awake with the phone, not answering till morning","MS","high","static","winter_evening_2025",False,False,
  "ты не отвечаешь до утра, и он не давит, не торопит, и от этого ты веришь ещё сильнее"),
 ("A4_SH11","IRINA","kitchen","close-up of the woman talking herself into it at the kitchen table","CU","eye","static","winter_morning_2025",False,False,
  "ты говоришь себе, он же вернул те пять тысяч до тенге, это наше общее будущее"),
 ("A4_SH12","IRINA","kitchen","medium shot of the woman resolute, deciding to tell her daughter nothing","MS","eye","static","winter_morning_2025",False,False,
  "ты решаешься и не говоришь даше ни слова, она не поймёт, а виктор поймёт"),
 ("A4_SH13","IRINA","street","wide shot of the woman walking through the frozen town toward the bank, gripping her card","WS","eye","push_in","winter_day_2025",False,False,
  "наутро ты идёшь в отделение халык через морозный город, сжимая карту в кармане"),
 ("A4_SH14","IRINA","halyk","medium shot of the woman at the Halyk bank counter withdrawing her savings","MS","eye","static","winter_day_2025",False,False,
  "у окна ты снимаешь почти всё, что откладывала на чёрный день и на старость"),
 ("A4_SH15",None,"halyk","close-up of a young teller counting banknotes behind the glass, indifferent","CU","eye","static","winter_day_2025",False,False,
  "молодая девушка за стеклом считает купюры, ей всё равно, для тебя это годы"),
 ("A4_SH16","IRINA","halyk","close-up of the woman leaving the bank with an empty account and a heavy heart","CU","eye","static","winter_day_2025",False,False,
  "ты выходишь из банка с пустым счётом и тяжёлым сердцем, но говоришь себе это ради него"),
 ("A4_SH17","IRINA","kitchen","medium shot of the woman at the night kitchen table opening the Kaspi app","MS","high","static","winter_night_2025",False,False,
  "дома ты открываешь каспи, вводишь номер карты марата, который прислал виктор"),
 ("A4_SH18",None,"kitchen","extreme close-up of the Kaspi transfer screen, 250 000 tenge to a stranger's card","ECU","eye","push_in","winter_night_2025",False,True,
  "на экране двести пятьдесят тысяч тенге, незнакомому человеку, палец застывает"),
 ("A4_SH19","IRINA","kitchen","medium shot of the woman pressing send after a last look at his photo","MS","eye","static","winter_night_2025",False,False,
  "ты смотришь на фото в оранжевой каске и нажимаешь, ради него, ради вас двоих"),
 ("A4_SH20",None,"kitchen","extreme close-up of the phone showing transfer complete, the screen going dark","ECU","eye","static","winter_night_2025",False,True,
  "перевод выполнен, экран гаснет, и в квартире становится очень тихо"),
 ("A4_SH21","IRINA","kitchen","medium shot of the woman alone at the table, a hollow chill under the familiar warmth","MS","low","static","winter_night_2025",False,False,
  "под рёбрами привычно теплеет, но впервые рядом с теплом холодок, ты его гонишь"),
 ("A4_SH22",None,"room","close-up of the phone overflowing with Viktor's jubilant messages","CU","eye","static","winter_night_2025",False,False,
  "виктор ликует, груз отпустили, я собираю чемодан, скоро обниму тебя по-настоящему"),
 ("A4_SH23","IRINA","room","medium shot of the woman drifting to sleep imagining the airport meeting","MS","eye","static","winter_night_2025",False,False,
  "ты засыпаешь, представляя как он идёт к тебе через зал аэропорта"),
 ("A4_SH24",None,"kitchen","close-up of the phone with a message that the flight is postponed and a new fee appeared","CU","eye","static","winter_day_2025",False,False,
  "но через два дня он пишет, рейс перенесли, и всплыл какой-то таможенный сбор"),
 ("A4_SH25","IRINA","kitchen","close-up of the woman with a flicker of unease she pushes down","CU","eye","static","winter_day_2025",False,False,
  "внутри ёкает нехорошо, но ты отгоняешь мысль, осталось совсем чуть-чуть до встречи"),
 ("A4_SH26","IRINA","kitchen","medium shot of the woman on the phone forcing a cheerful tone to her daughter","MS","eye","static","winter_day_2025",False,False,
  "звонит даша, ты бодро врёшь что всё хорошо, что денег хватает, что не скучаешь"),
 ("A4_SH27","IRINA","room","close-up of the woman setting the phone down heavily, guilt on her face","CU","eye","static","winter_day_2025",False,False,
  "ты врёшь дочери и кладёшь трубку с тяжестью, говоришь себе что так лучше для всех"),
 ("A4_SH28",None,"room","close-up of the phone with Viktor reassuring her, one more small fee and he is hers","CU","eye","static","winter_evening_2025",False,False,
  "виктор успокаивает, ещё один маленький сбор и я твой навсегда, потерпи родная"),
 ("A4_SH29","IRINA","kitchen","medium shot of the woman staring at a zero balance on her phone, convincing herself","MS","eye","static","winter_evening_2025",False,False,
  "ты смотришь на нулевой остаток в халыке и убеждаешь себя, что это временно"),
 ("A4_SH30","IRINA","room","medium shot of the woman rereading his promises by lamplight at night","MS","high","static","winter_night_2025",False,False,
  "ночью ты перечитываешь его обещания, расчётные, втрое, дом, мы вместе"),
 ("A4_SH31",None,"room","close-up of the phone with another customs message mentioning the colleague and papers","CU","eye","static","winter_night_2025",False,False,
  "он снова про таможню, про коллегу марата, про бумаги, и ты киваешь экрану"),
 ("A4_SH32","IRINA","kitchen","close-up of the woman alone in the dark kitchen, the first deep crack beneath her hope","CU","low","static","winter_night_2025",False,True,
  "ты ещё не видишь, что отдала свою подушку безопасности человеку, которого ни разу не слышала"),
]

if __name__ == "__main__":
    seed_act("e4","A4_bank_cold",MOOD,"0104000000","0154000000","static","act_04_first_transfer",SHOTS)
