# -*- coding: utf-8 -*-
"""Seed CH27 — Молодые побеждают, взгляды уходят (HEROINE_MID). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "the gazes all go to the young now, neon western night, a slow creeping invisibility"
SHOTS = [
 ("CH27_SH01", "HEROINE_MID", "cafe_west",
  "medium of the heroine at a bar, dressed up but unseen",
  "MS","eye","static","night",False,False,
  "пятьдесят на горизонте, и ты с ужасом замечаешь, что стала в баре совсем невидимой."),
 ("CH27_SH02", None, "cafe_west",
  "close-up of men's gazes sliding past her to younger women",
  "CU","eye","static","night",True,False,
  "взгляды мужчин пролетают сквозь тебя и липнут к молоденьким, как когда-то липли к тебе."),
 ("CH27_SH03", "HEROINE_MID", "cafe_west",
  "medium close-up of her at the counter, no one inviting her",
  "MCU","eye","static","night",False,False,
  "ты сидишь у стойки нарядная, надушенная, и впервые домой тебя никто не зовёт."),
 ("CH27_SH04", None, "street_west",
  "wide of her walking the night street home alone",
  "WS","eye","static","night",True,False,
  "ты возвращаешься одна по ночному городу, и эта дорога с каждым годом всё длиннее."),
 ("CH27_SH05", "HEROINE_MID", "street_west",
  "close-up of her remembering mocking older women once",
  "CU","eye","static","night",False,False,
  "ты вспоминаешь, как сама когда-то смеялась над старшими, всё никак не угомонится, мол."),
 ("CH27_SH06", "HEROINE_MID", "her_room",
  "medium close-up of the wheel having turned on her",
  "MCU","eye","static","night",False,False,
  "теперь смеются над тобой, и колесо, которое ты крутила всю жизнь, наконец повернулось."),
 ("CH27_SH07", None, "disco",
  "close-up of a much younger crowd in a club",
  "CU","eye","static","night",True,False,
  "ты идёшь на дискотеки помоложе и чувствуешь себя там нелепо, не к месту, совсем чужой."),
 ("CH27_SH08", "HEROINE_MID", "disco",
  "close-up of a young man mistaking her attention",
  "CU","eye","static","night",False,False,
  "молодой парень принимает твоё внимание за ошибку, тётенька, вы что-то, кажется, перепутали."),
 ("CH27_SH09", "HEROINE_MID", "street_west",
  "medium close-up of shame she once dealt out now burning her",
  "MCU","eye","static","night",False,True,
  "и тебя обжигает стыд, тот самый, которым ты когда-то так щедро поливала других."),
 ("CH27_SH10", None, "her_room",
  "extreme close-up of the empty pillow, no casual guests left either",
  "ECU","eye","static","night",True,True,
  "а дома всё та же пустая подушка, только теперь рядом нет даже случайных ночных гостей."),
 ("CH27_SH11", None, "street_west",
  "wide B-roll of a neon western street at night, silent",
  "WS","eye","static","night",True,False,""),
]
if __name__ == "__main__":
    seed_act(27, "neon_west", MOOD, "static", "CH27 Young win", SHOTS)
