# -*- coding: utf-8 -*-
"""Seed CH19 — Эскалация, пустее и быстрее (HEROINE_YOUNG). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "escalation, the men blur into one faceless smear, emptier and faster, harsh cold neon"
SHOTS = [
 ("CH19_SH01", "HEROINE_YOUNG", "disco",
  "medium of the heroine in the same smoke years later, still hunting",
  "MS","eye","static","night",False,False,
  "годы летят, а ты всё там же, в дыму, в погоне, только лиц с каждым годом всё больше."),
 ("CH19_SH02", None, "disco",
  "close-up of a blur of faceless men around her",
  "CU","eye","static","night",True,False,
  "они сливаются в одно безликое пятно, ты уже не помнишь ни имён их, ни лиц."),
 ("CH19_SH03", "HEROINE_YOUNG", "kneipe",
  "medium close-up of her needing more for the same high",
  "MCU","eye","static","night",False,False,
  "тебе нужно всё больше, чтобы поймать ту же волну, что когда-то давал один лишь взгляд."),
 ("CH19_SH04", None, "her_room",
  "extreme close-up of the empty pillow and a stranger's smell",
  "ECU","eye","static","dawn",True,True,
  "и каждое, каждое утро всё та же холодная пустая подушка и чужой запах на ней."),
 ("CH19_SH05", "HEROINE_YOUNG", "her_room",
  "close-up of her hollowness despite the bravado",
  "CU","eye","static","dawn",False,False,
  "ты говоришь себе, что живёшь полной жизнью, но внутри гулко и пусто, как в старой бочке."),
 ("CH19_SH06", None, "street_east",
  "wide of her grey dawn walk home past the wall and dark shop windows",
  "WS","eye","static","dawn",True,False,
  "ты бредёшь домой на рассвете мимо стены, мимо своего отражения в тёмных витринах."),
 ("CH19_SH07", "HEROINE_YOUNG", "her_room",
  "medium close-up of her aging, still searching for what isn't there",
  "MCU","eye","static","gdr_day",False,False,
  "тридцать, потом тридцать пять, а ты всё ищешь в чужих глазах то, чего там нет."),
 ("CH19_SH08", None, "disco",
  "close-up of younger faces appearing in the dancehall",
  "CU","eye","static","night",True,False,
  "на дискотеках всё больше молоденьких, и ты впервые ловишь на себе оценивающие взгляды."),
 ("CH19_SH09", "HEROINE_YOUNG", "kneipe",
  "close-up of her trying harder to still be chosen",
  "CU","eye","static","night",False,False,
  "приходится стараться, краситься ярче, смеяться громче, лишь бы тебя всё ещё выбирали."),
 ("CH19_SH10", "HEROINE_YOUNG", "her_room",
  "medium close-up of the wave barely flickering now",
  "MCU","eye","static","dawn",False,True,
  "а волна теперь едва теплится, как догорающая спичка, и гаснет почти сразу же."),
 ("CH19_SH11", None, "disco",
  "wide B-roll of the neon dancehall, silent",
  "WS","eye","static","night",True,False,""),
]
if __name__ == "__main__":
    seed_act(19, "neon_gdr", MOOD, "static", "CH19 Escalation", SHOTS)
