# -*- coding: utf-8 -*-
"""Seed CH19 — Долги и займы (2nd person). Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "cold harsh microloan light, the debt pit tightening, anxious"
SHOTS = [
 ("CH19_SH01", None, "mfo",
  "wide establishing of the cheap microloan office, fast-cash signage glowing",
  "WS","high","push_in","office_day",True,False,
  "операция, уколы, нити, всё это ты брала в долг."),
 ("CH19_SH02", "HEROINE_MID", "mfo",
  "medium shot of the heroine taking yet another loan at the counter",
  "MS","eye","static","office_day",False,False,
  "один займ, второй, третий, ты уже путаешься в них."),
 ("CH19_SH03", None, "mfo",
  "extreme close-up of loan contracts piling up, interest figures climbing",
  "ECU","top_down","static","office_day",True,False,
  "проценты растут, ты гасишь один кредит другим."),
 ("CH19_SH04", "HEROINE_MID", "family",
  "medium close-up of the heroine ignoring a ringing phone full of bank calls",
  "MCU","eye","static","home_eve",False,False,
  "звонят из банков, а ты не берёшь трубку."),
 ("CH19_SH05", None, "family",
  "close-up of a phone screen full of overdue-payment threats",
  "CU","top_down","static","home_eve",True,False,
  "сыплются смс, оплатите, иначе будет хуже."),
 ("CH19_SH06", "HEROINE_MID", "family",
  "medium shot of the heroine hiding the debt papers from her husband",
  "MS","eye","static","home_eve",False,False,
  "от мужа прячешь всё, он не знает, в какой ты яме."),
 ("CH19_SH07", None, "family",
  "extreme close-up of an almost empty purse beside a full vanity of expensive cosmetics",
  "ECU","top_down","static","home_eve",True,False,
  "на еду остаётся всё меньше, а на лицо находится всегда."),
 ("CH19_SH08", "HEROINE_MID", "clinic",
  "medium close-up of the heroine choosing a procedure over paying a bill",
  "MCU","eye","static","clinic_day",False,False,
  "счёт за свет подождёт, а вот процедуру пропускать нельзя."),
 ("CH19_SH09", None, "family",
  "close-up of a bare fridge contrasted with a packed luxury cosmetics shelf",
  "CU","eye","static","home_eve",True,False,
  "холодильник пустой, а в косметичке всё самое дорогое."),
 ("CH19_SH10", "HEROINE_MID", "bathroom",
  "close-up of the heroine's anxious face at the mirror",
  "CU","eye","static","home_eve",False,True,
  "ты живёшь в долг ради лица, которое уже сама не узнаёшь."),
 ("CH19_SH11", "HEROINE_MID", "bathroom",
  "medium close-up of the heroine unable to stop",
  "MCU","eye","static","home_eve",False,False,
  "но остановиться ты не можешь, как наркоман."),
 ("CH19_SH12", None, "mfo",
  "wide B-roll of the microloan arcade at night, cold neon",
  "WS","eye","static","office_day",True,False,""),
]
if __name__ == "__main__":
    seed_act(19, "mfo_cold", MOOD, "static", "CH19 Debt", SHOTS)
