# -*- coding: utf-8 -*-
"""Seed CH10 — Не можешь быть одна (HEROINE_YOUNG). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "the compulsion bares itself, terror of an empty bed, the night pulling her out again, cold dread under neon"
SHOTS = [
 ("CH10_SH01", "HEROINE_YOUNG", "her_room",
  "medium of the heroine alone in her room as evening falls, unease rising",
  "MS","eye","static","gdr_eve",False,False,
  "ты замечаешь за собой странное, ты физически не выносишь оставаться одна по вечерам."),
 ("CH10_SH02", "HEROINE_YOUNG", "her_room",
  "close-up of the empty room seeming to close in on her",
  "CU","eye","static","gdr_eve",False,False,
  "стоит остаться в пустой комнате, и накатывает та самая тоска, знакомая ещё с детства."),
 ("CH10_SH03", None, "her_room",
  "extreme close-up of the empty cold pillow beside her",
  "ECU","eye","static","gdr_eve",True,True,
  "пустая подушка рядом смотрит на тебя, как немой укор, и ты этого просто не выдерживаешь."),
 ("CH10_SH04", "HEROINE_YOUNG", "street_east",
  "medium of the heroine dressed up, hurrying out into the night",
  "MS","eye","static","night",False,False,
  "ты красишься, одеваешься и снова бежишь туда, где тебя хоть кто-нибудь да захочет."),
 ("CH10_SH05", None, "disco",
  "wide of the crowded smoky dancehall",
  "WS","eye","static","night",True,False,
  "дискотека, пивная, чужая квартира, лишь бы только не оставаться наедине с собой."),
 ("CH10_SH06", "HEROINE_YOUNG", "disco",
  "medium close-up of her in the crowd, the dread receding",
  "MCU","eye","static","night",False,False,
  "в толпе, под чужими взглядами, тоска отступает, и ты снова дышишь полной грудью."),
 ("CH10_SH07", None, "street_east",
  "close-up of a faceless man waiting to lead her off",
  "CU","eye","static","night",True,False,
  "всегда найдётся кто-то, готовый увести тебя в ночь, и ты идёшь за ним, не раздумывая."),
 ("CH10_SH08", "HEROINE_YOUNG", "her_room",
  "close-up of her back home at dawn, a faceless back dressing to leave",
  "CU","eye","static","dawn",False,False,
  "а под утро снова это, чужая спина тихо одевается и уходит, и ты опять совсем одна."),
 ("CH10_SH09", "HEROINE_YOUNG", "her_room",
  "medium close-up of her lying awake, wondering",
  "MCU","eye","static","dawn",False,False,
  "ты лежишь и думаешь, отчего же тепла хватает ровно до рассвета, а дальше снова холод."),
 ("CH10_SH10", None, "her_room",
  "extreme close-up of the empty side of the bed",
  "ECU","eye","static","dawn",True,True,
  "и единственное лекарство от этой пустоты, что ты знаешь, ещё один, и станет легче."),
 ("CH10_SH11", None, "disco",
  "wide B-roll of the smoky neon dancehall, silent",
  "WS","eye","static","night",True,False,""),
]
if __name__ == "__main__":
    seed_act(10, "gdr_night", MOOD, "static", "CH10 Cannot be alone", SHOTS)
