# -*- coding: utf-8 -*-
"""Seed CH11 — Первый укол, Алина (2nd person). Idempotent. Heroine still natural-faced (YOUNG)."""
from _seed_beauty_act_engine import seed_act
MOOD = "cold clinical white clinic light, sterile seductive promise of youth"
SHOTS = [
 ("CH11_SH01", None, "clinic",
  "wide establishing of a sleek modern cosmetology clinic room, a reclining chair like a throne, a ring-lit mirror",
  "WS","high","push_in","clinic_day",True,False,
  "клиника, белый кабинет, кресло как трон."),
 ("CH11_SH02", "ALINA", "clinic",
  "medium close-up of the sleek cosmetologist Alina welcoming a client with a sweet warm smile",
  "MCU","eye","static","clinic_day",False,False,
  "косметолог алина встречает тебя как родную, ласковая, улыбчивая."),
 ("CH11_SH03", ("ALINA","HEROINE_YOUNG"), "clinic",
  "Alina on the left holding a syringe, the heroine on the right in the chair listening, a consultation",
  "MS","eye","static","clinic_day",False,False,
  "всего капельку ботокса, говорит она, и десять лет как не бывало."),
 ("CH11_SH04", None, "clinic",
  "extreme close-up of a fine needle approaching a smooth forehead",
  "ECU","eye","push_in","clinic_day",True,True,
  "первый укол, холодная игла, ты зажмуриваешься."),
 ("CH11_SH05", "HEROINE_YOUNG", "clinic",
  "close-up of the heroine wincing slightly in the treatment chair",
  "CU","eye","static","clinic_day",False,False,
  "лёгкий щипок, и всё, ты даже не успеваешь испугаться."),
 ("CH11_SH06", "HEROINE_YOUNG", "bathroom",
  "medium close-up of the heroine days later examining her smoothed forehead in the mirror",
  "MCU","eye","static","clinic_day",False,False,
  "через пару дней лоб гладкий, морщинки исчезли."),
 ("CH11_SH07", "HEROINE_YOUNG", "bathroom",
  "extreme close-up of her smooth youthful forehead reflected in the mirror",
  "ECU","eye","push_in","clinic_day",False,True,
  "ты не веришь отражению, как будто снова двадцать пять."),
 ("CH11_SH08", "HEROINE_YOUNG", "bathroom",
  "close-up of the heroine's face flooded with relief and joy",
  "CU","eye","static","clinic_day",False,True,
  "и та самая тёплая волна, что в юности от взглядов, теперь от иглы."),
 ("CH11_SH09", ("ALINA","HEROINE_YOUNG"), "clinic",
  "Alina on the left handing a loyalty card to the heroine on the right with a knowing wink",
  "MS","eye","static","clinic_day",False,False,
  "приходи через полгода, говорит алина и подмигивает, как старому другу."),
 ("CH11_SH10", "HEROINE_YOUNG", "stairwell",
  "medium shot of the heroine floating out of the clinic, lighter and rejuvenated",
  "MS","eye","pan","clinic_day",False,False,
  "ты выходишь окрылённая, помолодевшая, заново влюблённая в себя."),
 ("CH11_SH11", "HEROINE_YOUNG", "stairwell",
  "close-up of her reflection beaming in the clinic glass door",
  "CU","eye","static","clinic_day",False,False,
  "ты на крючке, только ещё совсем этого не знаешь."),
 ("CH11_SH12", None, "shop",
  "wide B-roll of the clinic exterior at dusk, lit sign glowing",
  "WS","eye","static","clinic_day",True,False,""),
]
if __name__ == "__main__":
    seed_act(11, "clinic_white", MOOD, "static", "CH11 First injection", SHOTS)
