# -*- coding: utf-8 -*-
"""best_thing shots: A3 (the box and the shears), A4 (the fork), A5 (the courses)."""
from _best_thing_engine import seed_act

PAL_A3 = "farewell amber light, winter window blue, warm lamp pools"
PAL_A4 = "crossroad dusk tones, cold listing glow, warm salon accents"
PAL_A5 = "green class light, stem and ribbon colours, fresh water shine"

A3 = [
 ("A3_SH01", None, "office_acc",
  "the accounting office in december, boxes appearing under desks, binders being labelled for handover",
  "WS", "eye", "static", "day", False, False,
  "декабрь проходит в передаче дел — подрядчику уезжают папки, регламенты и пятнадцать лет порядка.",
  "handover labels settle onto the binder spines as boxes gather under desks",
  None, "crowd"),
 ("A3_SH02", "LIDA_BASE", "office_acc",
  "Lida writes handover notes margin by margin, thorough to the end, teaching an absent successor",
  "MS", "eye", "static", "day", False, False,
  "ты пишешь пояснения на полях для людей, которых никогда не увидишь, — работа должна сходиться и без тебя.",
  "her pen fills margin after margin in the open handover binder"),
 ("A3_SH03", ("TOMA_BASE", "LIDA_BASE"), "office_acc",
  "Toma and Lida pack the shared shelf, dividing fifteen years of small things with laughter that keeps catching",
  "MS", "eye", "static", "day", False, False,
  "вы с томой делите общую полку и смеётесь чаще, чем нужно, потому что иначе никак.",
  "small shared things pass between four hands as the laughter catches twice",
  None, "crowd"),
 ("A3_SH04", None, None,
  "the big-key calculator being wrapped in bubble film on a desk, the tape roll standing by",
  "INSERT", "eye", "static", "day", False, False,
  "калькулятор с большими клавишами ты заворачиваешь в плёнку — его списали вместе с тобой, и ты его выкупаешь за смешные деньги.",
  "bubble film winds around the calculator under her careful hands",
  "CALC"),
 ("A3_SH05", "LIDA_BASE", "office_acc",
  "Lida takes the brass shears from the drawer last, holding them a beat, then wrapping them in a handkerchief",
  "MCU", "eye", "static", "day", False, True,
  "последними из ящика выходят ножницы, и ты заворачиваешь их в платок, как документы.",
  "the shears lift from the drawer and fold into the handkerchief in her palms",
  "SHEARS"),
 ("A3_SH06", None, "office_acc",
  "the windowsill plants being adopted: colleagues carrying pots away one by one, the sill emptying",
  "WS", "eye", "static", "day", False, False,
  "подоконник разбирают по домам, горшок за горшком, — цветам увольнение не положено.",
  "pots leave the sill one by one in careful carrying hands",
  None, "crowd"),
 ("A3_SH07", "LIDA_BASE", "office_meeting",
  "the farewell tea in the meeting room, a modest cake, Lida's bouquet centrepiece the only bright thing on the table",
  "MS", "eye", "static", "evening", False, False,
  "на прощальном чаепитии посреди стола стоит твой букет — последний офисный, собранный уже не по случаю.",
  "the centrepiece bouquet holds the table as paper cups gather around it",
  None, "crowd"),
 ("A3_SH08", "ROZA_BASE", "office_meeting",
  "Roza, invited as someone's aunt, studies the centrepiece bouquet professionally, her pincushion bracelet turning",
  "CU", "eye", "static", "evening", False, True,
  "чья-то тётя в зелёном халате долго смотрит на букет, потом на твои руки, потом снова на букет.",
  "her appraising eyes travel bouquet to hands and back as the bracelet turns"),
 ("A3_SH09", ("ROZA_BASE", "LIDA_BASE"), "office_meeting",
  "Roza asks Lida one question across the cake, direct as a cut, the room chatting past them",
  "MCU", "eye", "static", "evening", False, False,
  "она спрашивает одно — «спираль сама поставила или учил кто?» — и ты не сразу знаешь, что ответить.",
  "the direct question crosses the cake as the chatter flows past them"),
 ("A3_SH10", "LIDA_BASE", "lida_hall",
  "Lida comes home with the box, Sergey taking it from her at the door wordlessly, Kolya hovering",
  "MS", "eye", "static", "evening", False, False,
  "домой ты приходишь с коробкой, и серёжа забирает её у порога молча — есть вещи не для слов.",
  "the box passes at the threshold as the boy hovers at the corridor end"),
 ("A3_SH11", None, None,
  "the box unpacked on the kitchen table: the calculator, a mug, the wrapped shears, a folder of certificates",
  "ECU", "high", "static", "night", False, False,
  "пятнадцать лет умещаются на кухонном столе — калькулятор, кружка, ножницы и папка грамот.",
  "lamplight inventories the unpacked fifteen years across the table",
  "CALC"),
 ("A3_SH12", "LIDA_BASE", "lida_kitchen",
  "Lida awake at the night kitchen with tea, the fear finally allowed out now that everyone sleeps",
  "CU", "eye", "push_in", "night", False, False,
  "страх ты выпускаешь только ночью, на кухне, — днём он пугал бы не тебя, а семью.",
  "the tea steam thins as the held fear finally crosses her face"),
 ("A3_SH13", "SERGEY_BASE", "lida_kitchen",
  "Sergey appears in the night kitchen doorway in a t-shirt, reading the scene, coming to sit close",
  "MS", "eye", "static", "night", False, False,
  "серёжа приходит на свет чайника, садится рядом и говорит — «ну, значит, придумаем».",
  "he settles onto the near chair and his shoulder leans into hers"),
 ("A3_SH14", None, None,
  "two teacups side by side on the night table, close enough to touch, steam mixing",
  "ECU", "eye", "static", "night", False, False,
  "две чашки стоят вплотную, и пар над ними смешивается — на этой кухне решают вместе.",
  "the two steams twine over the touching cups"),
 ("A3_SH15", "LIDA_BASE", None,
  "her own hands unwrapping the shears from the handkerchief at the window, the brass rings warm in lamplight",
  "POV", "pov", "static", "night", False, False,
  "перед сном ты разворачиваешь ножницы и держишь их в руках дольше, чем нужно для держания.",
  "the handkerchief folds back and the brass rings settle into her palms",
  "SHEARS"),
 ("A3_SH16", None, "courtyard_home",
  "the courtyard in first snow at night, the rowan berries capped white, one kitchen window warm",
  "WS", "low", "static", "night", True, False,
  "первый снег ложится на рябину, и одно окно на весь дом горит дольше всех — ваше.",
  "snow builds soft caps on the berry clusters under the one warm window"),
 ("A3_SH17", "LIDA_BASE", "office_acc",
  "the last day: Lida hands her pass to the guard desk and looks back once at the empty sill",
  "MS", "eye", "static", "day", False, False,
  "в последний день ты сдаёшь пропуск и оглядываешься один раз — на пустой подоконник.",
  "the pass lands on the desk as her single look back finds the bare sill"),
 ("A3_SH18", None, "office_acc",
  "the empty accounting office, chairs pushed in, screens dark, pale rectangles where photos were taped",
  "EWS", "eye", "static", "day", False, False,
  "отдел стоит пустой и прибранный, как квартира перед сдачей ключей.",
  "dust settles through the pale light over the pushed-in chairs"),
]

A4 = [
 ("A4_SH01", "TOMA_BASE", "lida_kitchen",
  "Toma at Lida's kitchen with her laptop open on listings, evangelising the safe path, tea going cold",
  "MS", "eye", "static", "day", False, False,
  "тома приезжает с ноутбуком и планом — «идём вместе в новую сеть, ставки выше наших прежних».",
  "her turning laptop presents the listings as the tea cools between them"),
 ("A4_SH02", None, None,
  "a vacancy page: senior accountant, salary range, requirements list running past the fold",
  "ECU", "eye", "static", "day", False, False,
  "вакансия хорошая, честная — старший бухгалтер, деньги выше прежних, всё как у людей.",
  "the salary range holds the screen as the requirements scroll past the fold"),
 ("A4_SH03", "LIDA_BASE", "lida_kitchen",
  "Lida reads the vacancy with polite attention, her thumb rubbing the amber claw clip taken off the table",
  "CU", "eye", "static", "day", False, False,
  "ты читаешь и слышишь странное — хорошие слова, а внутри тихо, как в пустом отделе.",
  "her thumb turns the amber clip while her eyes walk the good words"),
 ("A4_SH04", "LIDA_BASE", "office_meeting",
  "an interview at a new company: Lida answers well across the table, her CV praised by a nodding suit shoulder",
  "OTS", "over", "static", "day", False, False,
  "на собеседовании тебя хвалят и почти берут, и ты отвечаешь правильно, как по регламенту.",
  "her correct answers cross the table under the nodding praise"),
 ("A4_SH05", "LIDA_BASE", "street_market",
  "Lida walks home past the market flower vans again, stopping this time, watching the buckets go by",
  "MS", "eye", "static", "evening", False, False,
  "после собеседования ноги сами ведут мимо рынка, и ты стоишь у разгрузки дольше приличного.",
  "she stands rooted as the buckets pass hand to hand before her",
  None, "crowd"),
 ("A4_SH06", "LIDA_BASE", "street_market",
  "Lida's face lit by the string lights, hunger of a specific kind in it, her breath fogging",
  "CU", "eye", "push_in", "evening", False, True,
  "у витрины с вёдрами ты чувствуешь то, чего не было на собеседовании, — руки просятся.",
  "the string lights warm her hungry look as her breath fogs slow"),
 ("A4_SH07", ("ROZA_BASE", "LIDA_BASE"), "roza_salon",
  "Lida steps into Roza's old salon with the farewell-bouquet photo on her phone, Roza recognising her at once",
  "MS", "eye", "static", "day", False, False,
  "салон розы ты находишь по визитке с чаепития, и роза узнаёт тебя раньше, чем ты здороваешься.",
  "the phone photo turns toward the counter as recognition crosses the smock"),
 ("A4_SH08", "ROZA_BASE", "roza_salon",
  "Roza examines Lida's hands like a horse trader, turning them palm up, nodding at the calluses of work",
  "CU", "eye", "static", "day", False, False,
  "роза берёт твои руки, поворачивает ладонями вверх и говорит — «бухгалтерские, но живые».",
  "her trader hands turn the offered palms up and weigh them"),
 ("A4_SH09", "ROZA_BASE", "roza_salon",
  "Roza lays out the terms with a knife-straight finger: courses first, then her salon, low pay, real school",
  "MCU", "eye", "static", "day", False, False,
  "условия у неё прямые — «сначала курсы за свои, потом ко мне, платить буду мало, учить честно».",
  "her straight finger sets the terms out point by point on the counter"),
 ("A4_SH10", "LIDA_BASE", "lida_kitchen",
  "the family council: Lida lays the two paths on the table literally — the vacancy printout and the courses flyer",
  "WS", "eye", "static", "evening", False, False,
  "вечером ты кладёшь на стол две бумаги — вакансию старшего бухгалтера и листовку курсов.",
  "the two sheets settle side by side as three heads lean over them"),
 ("A4_SH11", "SERGEY_BASE", "lida_kitchen",
  "Sergey looks between the papers, fear and love wrestling openly, his hand hovering over both",
  "CU", "eye", "static", "evening", False, False,
  "серёжа честно говорит «мне страшно», и так же честно двигает к тебе листовку курсов.",
  "his hovering hand lands on the flyer and slides it across"),
 ("A4_SH12", "KOLYA_BASE", "lida_kitchen",
  "Kolya spins his phone on the table and announces the obvious with teenage clarity",
  "MCU", "eye", "static", "evening", False, False,
  "коля крутит телефон и выдаёт — «мам, ты в экселе спишь, а с цветами просыпаешься».",
  "the spinning phone stops as the teenage verdict lands"),
 ("A4_SH13", "LIDA_BASE", "lida_kitchen",
  "Lida laughs and cries a little in one breath, pulling both men into a clumsy three-way hug",
  "WS", "eye", "static", "evening", False, True,
  "ты смеёшься и трёшь глаза одновременно, и решение принимается всей кухней сразу.",
  "the clumsy three-way hug gathers over the two papers"),
 ("A4_SH14", "LIDA_BASE", None,
  "her own hand filling the course application, the payment line of thirty-eight thousand written in a firm steady hand",
  "POV", "pov", "static", "night", False, False,
  "заявку на курсы ты заполняешь в тот же вечер — тридцать восемь тысяч из выходного, первая ставка на себя.",
  "the pen fills the payment line in a steady accountant hand"),
 ("A4_SH15", "TOMA_BASE", None,
  "Toma on a video call, wishing luck with wet eyes and a joke, her bright frames pushed up",
  "CU", "eye", "static", "night", False, False,
  "тома выслушивает и говорит — «ну и правильно, а я пойду считать, кто-то же должен», — и вы обе правы.",
  "her joke lands through wet eyes as the frames ride up her hair"),
 ("A4_SH16", None, None,
  "the two papers on the night table: the vacancy folded away, the course flyer flattened under the shears",
  "INSERT", "top", "static", "night", False, False,
  "вакансия складывается вчетверо, а листовку прижимают на столе ножницы — распределение ролей понятно.",
  "lamplight holds the flattened flyer under the resting brass rings",
  "SHEARS"),
]

A5 = [
 ("A5_SH01", None, "courses_flor",
  "the floristry classroom on day one: steel tables, buckets of greens, students of all ages tying aprons",
  "WS", "eye", "static", "day", False, False,
  "курсы начинаются в январе — стальные столы, вёдра с зеленью и группа, где ты старше половины.",
  "aprons tie along the steel tables as the buckets steam with cold",
  None, "crowd"),
 ("A5_SH02", "LIDA_BASE", "courses_flor",
  "Lida unwraps her brass shears while neighbours click new bright secateurs, a small proud ceremony",
  "MCU", "eye", "static", "day", False, True,
  "все достают новенькие секаторы, а ты разворачиваешь платок с латунными ножницами, и группа затихает.",
  "the handkerchief opens on the brass rings as new secateurs click around",
  "SHEARS"),
 ("A5_SH03", "LIDA_BASE", None,
  "her own hands making the first spiral bouquet, stems crossing at one angle, thumb anchoring the bind point",
  "POV", "pov", "static", "day", False, False,
  "спираль у тебя встаёт со второго раза — руки, оказывается, ждали этого пятнадцать лет.",
  "the stems cross into the spiral under her anchoring thumb",
  "SHEARS"),
 ("A5_SH04", None, "courses_flor",
  "a work table of first-attempt bouquets, most lopsided, one standing balanced and clean among them",
  "ECU", "eye", "static", "day", False, False,
  "на столе первых работ один букет стоит ровно, и преподаватель дважды проверяет, чей он.",
  "the balanced bouquet holds its arc among the leaning first attempts"),
 ("A5_SH05", "LIDA_BASE", "courses_flor",
  "Lida takes notes in accountant columns: stem counts, angles, water temperatures, costs per stem",
  "MS", "eye", "static", "day", False, False,
  "конспект ты ведёшь бухгалтерски — колонками: стебли, углы, температура воды, себестоимость.",
  "her columned notes fill the page in the even accountant hand",
  "LEDGER"),
 ("A5_SH06", "LIDA_BASE", "lida_kitchen",
  "Lida practices at home past midnight, the kitchen a jungle of practice greens, family asleep",
  "WS", "eye", "static", "night", False, False,
  "дома ты тренируешься за полночь, и кухня зарастает учебной зеленью по подоконник.",
  "practice greens crowd the night kitchen as her hands work the spiral"),
 ("A5_SH07", "SERGEY_BASE", "lida_kitchen",
  "Sergey pads in at night, silently clears her workspace wider and sets tea within reach, retreating",
  "MS", "eye", "static", "night", False, False,
  "серёжа приходит ночью не отговаривать, а молча расширить тебе стол и поставить чай.",
  "his quiet hands widen the workspace and land the tea within reach"),
 ("A5_SH08", None, None,
  "a course notebook page where bouquet sketches share space with cost columns, a hybrid of two professions",
  "ECU", "top", "static", "night", False, False,
  "в тетради эскизы букетов соседствуют со сметами — две профессии знакомятся на одной странице.",
  "lamplight crosses the sketches and the cost columns sharing the page",
  "LEDGER"),
 ("A5_SH09", "ROZA_BASE", "courses_flor",
  "Roza visits the courses as a guest master, demonstrating a hand-tied bouquet in ninety seconds flat",
  "MS", "eye", "static", "day", False, False,
  "роза приходит гостевым мастером и собирает букет за девяносто секунд — без единого лишнего движения.",
  "her hands run the ninety-second bouquet as the class holds its breath",
  None, "crowd"),
 ("A5_SH10", "ROZA_BASE", "courses_flor",
  "Roza pauses at Lida's table, lifts her bouquet, turns it once, sets it back with a single nod",
  "MCU", "eye", "static", "day", False, True,
  "у твоего стола она задерживается, поворачивает букет один раз и кивает — это высшая оценка сезона.",
  "the bouquet turns once in her appraising hands and earns the nod"),
 ("A5_SH11", "LIDA_BASE", "courses_flor",
  "Lida's face after the nod, flushed like a schoolgirl, hiding the smile in her shoulder",
  "CU", "eye", "static", "day", False, False,
  "ты прячешь улыбку в плечо — похвала, добытая руками, слаще любой цифровой.",
  "the hidden smile escapes past her shoulder as the flush climbs"),
 ("A5_SH12", None, "flower_base",
  "the night wholesale flower base: pallet rows of boxed blooms, breath fog, buyers with trolleys at five a.m.",
  "EWS", "eye", "static", "night", False, False,
  "практика включает ночную базу — в пять утра здесь выбирают цветы те, кто в восемь их продаёт.",
  "trolleys roll the pallet rows through breath fog under the strip lights",
  None, "crowd"),
 ("A5_SH13", "LIDA_BASE", "flower_base",
  "Lida learns to check boxed roses at the base: opening a lid, pressing a bud, reading stem cut colour",
  "MS", "eye", "static", "night", False, False,
  "тебя учат читать коробку роз, как выписку, — по срезу, по бутону, по запаху воды.",
  "the box lid lifts under her learning hands as the bud takes the press test"),
 ("A5_SH14", "LIDA_BASE", "courses_flor",
  "the course exam: Lida assembles a bridal bouquet against the clock, calm hands, tied and lifted at the bell",
  "MS", "eye", "static", "day", False, False,
  "экзамен — свадебный букет на время, и ты заканчиваешь за минуту до звонка, руки сухие, спина мокрая.",
  "the bridal bouquet lifts finished at the bell under her dry steady hands",
  None, "crowd"),
 ("A5_SH15", None, None,
  "a floristry course certificate beside the old accounting diploma on the kitchen table, two lives in paper",
  "INSERT", "eye", "static", "evening", False, False,
  "сертификат ложится рядом с бухгалтерским дипломом, и вместе они смотрятся не ссорой, а библиотекой.",
  "lamplight bridges the two documents lying edge to edge",
  "LEDGER"),
 ("A5_SH16", "LIDA_BASE", "roza_salon",
  "Lida in a fresh apron reports for her first day at Roza's salon, the zinc buckets waiting like a class",
  "MS", "eye", "static", "morning", False, False,
  "в понедельник ты выходишь к розе — пятьдесят две тысячи, фартук и школа строже любой налоговой.",
  "the fresh apron ties as the zinc buckets wait in their morning rows",
  "APRON"),
]

if __name__ == "__main__":
    seed_act("A3", PAL_A3, A3)
    seed_act("A4", PAL_A4, A4)
    seed_act("A5", PAL_A5, A5)
