# -*- coding: utf-8 -*-
"""Seed CH23 — Дочь рвёт связь (2nd person). Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "cold grey home light, a final break, heavy"
SHOTS = [
 ("CH23_SH01", ("HEROINE_OLD","DAUGHTER"), "family",
  "the ruined-faced heroine on the left and the grown daughter on the right, the daughter horrified by her face and the debts",
  "MS","eye","static","home_day",False,False,
  "дочь приходит, видит твоё лицо и долги, и не выдерживает."),
 ("CH23_SH02", "DAUGHTER", "family",
  "medium close-up of the daughter crying and angry",
  "MCU","eye","static","home_day",False,False,
  "мама, ты себя изуродовала, я тебя не узнаю."),
 ("CH23_SH03", "HEROINE_OLD", "family",
  "close-up of the heroine defending herself, mask unmoving",
  "CU","eye","static","home_day",False,False,
  "ты оправдываешься, я хотела как лучше, быть красивой."),
 ("CH23_SH04", "DAUGHTER", "family",
  "medium close-up of the daughter, bitter",
  "MCU","eye","static","home_day",False,False,
  "для кого, мама, муж ушёл, подруг нет, ты осталась с зеркалом."),
 ("CH23_SH05", None, "family",
  "extreme close-up contrasting the daughter's tearful natural face and the mother's tearless mask",
  "ECU","eye","static","home_day",True,True,
  "она плачет за двоих, а твоё лицо не умеет."),
 ("CH23_SH06", "DAUGHTER", "daughter",
  "medium shot of the daughter packing her things to leave",
  "MS","eye","static","home_day",False,False,
  "она собирает вещи, я не могу на это смотреть."),
 ("CH23_SH07", "HEROINE_OLD", "family",
  "close-up of the heroine reaching out, unable to express her grief through the frozen face",
  "CU","eye","static","home_day",False,False,
  "ты тянешься к ней, но не можешь даже заплакать, чтоб она поверила."),
 ("CH23_SH08", "DAUGHTER", "stairwell",
  "medium shot of the daughter pausing at the door",
  "MS","eye","static","home_day",False,False,
  "не звони мне, говорит она, пока не вернёшься к себе настоящей."),
 ("CH23_SH09", None, "stairwell",
  "close-up of the front door closing for real this time",
  "CU","eye","static","home_day",True,False,
  "дверь закрывается, и теперь по-настоящему."),
 ("CH23_SH10", "HEROINE_OLD", "family",
  "medium close-up of the heroine losing the last person who loved her",
  "MCU","eye","static","home_day",False,False,
  "ты теряешь последнего человека, ради красоты, которой уже нет."),
 ("CH23_SH11", "HEROINE_OLD", "family",
  "extreme close-up of her frozen face that cannot even grieve",
  "ECU","eye","static","home_day",False,True,
  "и даже горевать по-человечески ты больше не можешь."),
 ("CH23_SH12", None, "family",
  "wide B-roll of the silent emptied apartment",
  "WS","eye","static","home_day",True,False,""),
]
if __name__ == "__main__":
    seed_act(23, "home_cold", MOOD, "static", "CH23 Daughter cuts", SHOTS)
