# -*- coding: utf-8 -*-
"""Seed CH25 — Девяностые, новый мир, но ты стареешь (HEROINE_MID debut). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "the 1990s, a dizzying reunified world, but the first real aging shows, bright cold western day"
SHOTS = [
 ("CH25_SH01", "HEROINE_MID", "street_west",
  "medium of the heroine over forty on a bright loud new Berlin street",
  "MS","eye","static","day",False,False,
  "девяностые, тебе за сорок, новый Берлин гремит и сверкает, а ты в нём уже не первая."),
 ("CH25_SH02", None, "street_west",
  "wide of shop windows overflowing with western goods",
  "WS","eye","static","day",True,False,
  "витрины ломятся от того, о чём вы мечтали за стеной, но тебе всё чаще не до них."),
 ("CH25_SH03", "HEROINE_MID", "cafe_west",
  "medium close-up of her still hunting in bars, gazes catching less often",
  "MCU","eye","static","day",False,False,
  "ты всё ещё ходишь по барам на охоту, но взгляды цепляются за тебя всё реже и реже."),
 ("CH25_SH04", "HEROINE_MID", "cafe_west",
  "close-up of her feeling her age beside bright young western girls",
  "CU","eye","static","day",False,False,
  "молодые западные девчонки яркие, свободные, и рядом с ними ты вдруг остро чувствуешь возраст."),
 ("CH25_SH05", None, "cafe_west",
  "wide of a younger crowd being chosen instead",
  "WS","eye","static","night",True,False,
  "там, где раньше всегда выбирала ты, теперь выбирают других, моложе, свежее и легче."),
 ("CH25_SH06", "HEROINE_MID", "her_room",
  "medium close-up of her studying new lines in the mirror",
  "MCU","eye","static","day",False,False,
  "дома у зеркала ты впервые подолгу разглядываешь морщинки у глаз и у горьких губ."),
 ("CH25_SH07", "HEROINE_MID", "her_room",
  "close-up of how rare the warm wave has become",
  "CU","eye","static","day",False,True,
  "тёплая волна теперь приходит так редко, что ты готова на всё, лишь бы её вернуть."),
 ("CH25_SH08", None, "street_west",
  "close-up of her buying young lovers' attention",
  "CU","eye","static","night",True,False,
  "ты гоняешься за молодыми любовниками и покупаешь их внимание ужинами, подарками, собой."),
 ("CH25_SH09", "HEROINE_MID", "cafe_west",
  "medium close-up of them taking and leaving for younger women",
  "MCU","eye","static","night",False,False,
  "они берут, что дают, и уходят к ровесницам, а ты остаёшься с пустым кошельком и постелью."),
 ("CH25_SH10", "HEROINE_MID", "her_room",
  "close-up of her fearing her own age for the first time",
  "CU","eye","static","day",False,False,
  "впервые ты по-настоящему боишься того, что всегда было твоей силой, своего возраста."),
 ("CH25_SH11", None, "street_west",
  "wide B-roll of a bright reunified Berlin street, silent",
  "WS","eye","static","day",True,False,""),
]
if __name__ == "__main__":
    seed_act(25, "west_day", MOOD, "static", "CH25 Nineties", SHOTS)
