# -*- coding: utf-8 -*-
"""Seed CH05 — Первый мужской взгляд, тёплая волна (teen, HEROINE_YOUNG). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "first warm charge of being desired, a grey world suddenly lit by a stranger's gaze, dawning allure"
SHOTS = [
 ("CH05_SH01", "HEROINE_YOUNG", "street_east",
  "medium of the young heroine at sixteen walking a grey street, suddenly striking with dark auburn hair",
  "MS","eye","static","gdr_day",False,False,
  "в шестнадцать ты расцветаешь, тёмно-рыжие волосы, дерзкий взгляд, и улица вдруг начинает тебя замечать."),
 ("CH05_SH02", None, "street_east",
  "close-up of faceless men's heads turning to follow her, seen from behind",
  "CU","eye","static","gdr_day",True,False,
  "мужчины оборачиваются тебе вслед, один, другой, и провожают глазами до самого угла."),
 ("CH05_SH03", "HEROINE_YOUNG", "street_east",
  "close-up of her face as the first warm wave rises in her chest",
  "CU","eye","static","gdr_day",False,True,
  "и в груди поднимается тёплая волна, незнакомая, сладкая, от которой слегка кружится голова."),
 ("CH05_SH04", "HEROINE_YOUNG", "street_east",
  "medium close-up of her straightening, basking in the attention",
  "MCU","eye","static","gdr_day",False,False,
  "впервые в жизни ты чувствуешь себя не пустым местом, а кем-то важным, желанным, особенным."),
 ("CH05_SH05", None, "street_east",
  "wide of the grey street now seeming alive and charged with colour",
  "WS","eye","static","gdr_day",True,False,
  "серый город будто вспыхивает красками, и всё из-за одного только жадного мужского взгляда."),
 ("CH05_SH06", "HEROINE_YOUNG", "courtyard",
  "medium close-up of her practicing the new power, a turn of the head",
  "MCU","eye","static","gdr_day",False,False,
  "дома ты репетируешь эту новую силу, поворот головы, взгляд украдкой из-под ресниц."),
 ("CH05_SH07", None, "her_room",
  "extreme close-up of a small mirror and a stub of lipstick",
  "ECU","top_down","static","gdr_day",True,False,
  "ты подкрашиваешь губы материной помадой, и зеркало впервые отвечает тебе одобрением."),
 ("CH05_SH08", "HEROINE_YOUNG", "street_east",
  "medium of her walking out again, seeking that gaze",
  "MS","eye","static","gdr_day",False,False,
  "и ты выходишь снова, чтобы поймать ещё, эта тёплая волна нужна тебе опять и опять."),
 ("CH05_SH09", None, "street_east",
  "close-up of another faceless man's lingering gaze from behind",
  "CU","eye","static","gdr_day",True,False,
  "каждый новый взгляд, как глоток тепла, которого тебе так не давали в детстве."),
 ("CH05_SH10", "HEROINE_YOUNG", "street_east",
  "medium close-up of her satisfied, already hooked",
  "MCU","eye","static","gdr_day",False,True,
  "ты ещё совсем не знаешь, что именно эта волна станет твоей дозой на всю жизнь."),
 ("CH05_SH11", "HEROINE_YOUNG", "courtyard",
  "wide B-roll of the young heroine in the grey courtyard at dusk, silent",
  "WS","high","static","gdr_eve",False,False,""),
]
if __name__ == "__main__":
    seed_act(5, "gdr_warm", MOOD, "static", "CH05 First gaze", SHOTS)
