# -*- coding: utf-8 -*-
"""Seed CH05 — Первая соперница (2nd person). Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "glossy neon 1990s club light turning cold, first jealous chill"
SHOTS = [
 ("CH05_SH01", "HEROINE_YOUNG", "disco",
  "medium shot of the young beauty holding court at her nightclub, sure of her crown",
  "MS","eye","static","neon_90s",False,False,
  "и вот однажды на твоей дискотеке появляется она."),
 ("CH05_SH02", None, "disco",
  "wide shot of a fresh new beautiful girl entering, heads turning away from the heroine toward her",
  "WS","eye","static","neon_90s",True,False,
  "моложе, ярче, и взгляды, твои взгляды, плывут к ней."),
 ("CH05_SH03", "HEROINE_YOUNG", "disco",
  "close-up of the heroine's smile faltering, a cold flicker behind the eyes",
  "CU","eye","static","neon_90s",False,True,
  "ты улыбаешься, а внутри впервые холодок."),
 ("CH05_SH04", "HEROINE_YOUNG", "disco",
  "extreme close-up of her hand tightening around a glass",
  "ECU","top_down","static","neon_90s",False,False,
  "ты не привыкла быть второй."),
 ("CH05_SH05", "HEROINE_YOUNG", "bathroom",
  "medium close-up of the heroine at a club bathroom mirror, scrutinising her own face for the first time",
  "MCU","eye","push_in","neon_90s",False,False,
  "ты бежишь к зеркалу и впервые ищешь в себе изъян."),
 ("CH05_SH06", "HEROINE_YOUNG", "bathroom",
  "extreme close-up of her face in the mirror, hunting for tiny flaws she never noticed before",
  "ECU","eye","static","neon_90s",False,True,
  "вот тут не так, и тут, раньше ты этого даже не замечала."),
 ("CH05_SH07", None, "disco",
  "wide shot of the new rival laughing in a ring of the heroine's former admirers",
  "WS","eye","static","neon_90s",True,False,
  "а она смеётся в кругу твоих поклонников."),
 ("CH05_SH08", "HEROINE_YOUNG", "bathroom",
  "medium shot of the heroine fixing her makeup harder, defiant",
  "MS","eye","static","neon_90s",False,False,
  "ты красишься ещё ярче, надо вернуть своё."),
 ("CH05_SH09", "HEROINE_YOUNG", "bathroom",
  "extreme close-up of lipstick pressed hard against her lips",
  "ECU","eye","static","neon_90s",False,False,
  "ты будешь биться, ты не отдашь свой трон без боя."),
 ("CH05_SH10", "HEROINE_YOUNG", "disco",
  "medium shot of the heroine walking back into the room with a battle-ready smile",
  "MS","eye","pan","neon_90s",False,False,
  "и возвращаешься в зал с боевой улыбкой."),
 ("CH05_SH11", "HEROINE_YOUNG", "disco",
  "close-up of her tense determined face under the club lights",
  "CU","low","static","neon_90s",False,True,
  "ты ещё не знаешь, что эта война с зеркалом, на всю твою жизнь."),
 ("CH05_SH12", None, "disco",
  "wide cold neon B-roll of the emptying club at dawn, no clear faces",
  "WS","eye","static","neon_90s",True,False,""),
]
if __name__ == "__main__":
    seed_act(5, "neon_glam", MOOD, "animated", "CH05 First rival", SHOTS)
