# -*- coding: utf-8 -*-
"""hidden_layoff shots: A9 (exposure, oct 14), A10 (aftermath), A11 (finale + coda)."""
from _hidden_layoff_engine import seed_act

PAL_A9 = "low golden october sun, long cold shadows, thin blue sky"
PAL_A10 = "dim warm lamplight, deep blue night windows, muted browns"
PAL_A11 = "pale winter daylight, grey concrete, one warm interior glow"

A9 = [
 ("A9_SH01", None, "flat_kitchen",
  "a phone lying face down on the kitchen table beside a charging cable, morning light along its edge",
  "ECU", "eye", "static", "morning", False, False,
  "четырнадцатого октября ты забываешь телефон на кухне — первый раз за много лет.",
  "the charging light pulses slowly along the phone edge in the morning quiet"),
 ("A9_SH02", "MARK_MAIN", "park_pond",
  "Mark on the bench patting his jacket pockets one after another, the briefcase open beside him, mild annoyance on his face",
  "MS", "eye", "static", "morning", False, False,
  "пропажу ты замечаешь уже на лавке и решаешь, что один день без звонков переживёшь.",
  "his hands pat the jacket pockets in turn and drop to his knees in resignation",
  "BRIEFCASE"),
 ("A9_SH03", "LENA_BASE", "flat_kitchen",
  "Lena stands at the kitchen table weighing Mark's phone in her hand, her coat already on, keys in the other hand",
  "MCU", "eye", "static", "day", False, False,
  "лена видит телефон, думает до обеда — и решает завезти его тебе на фабрику.",
  "she turns the phone over once in her hand and her keys swing still in the other"),
 ("A9_SH04", "LENA_BASE", "office_lobby",
  "Lena at the reception desk of the factory lobby holding out the phone, the three steel turnstiles beyond her, a guard window at the desk",
  "WS", "eye", "static", "day", False, False,
  "в лобби она называет твою фамилию и протягивает телефон дежурному на проходной.",
  "she holds the phone out over the desk and leans a little toward the guard window"),
 ("A9_SH05", "LENA_BASE", "office_lobby",
  "Lena's face at the moment the words land, the polite smile still on her mouth while her eyes stop moving",
  "CU", "eye", "push_in", "day", False, True,
  "дежурный говорит буднично — «так он у нас не работает с конца марта».",
  "the smile stays on her mouth while all the movement drains out of her eyes"),
 ("A9_SH06", None, "office_lobby",
  "a woman's hand holding a phone at her side against a cream cardigan hem, the grip loose, the lobby floor stretching behind",
  "ECU", "eye", "static", "day", False, False,
  "телефон в её руке опускается медленно, как будто начал весить килограммы.",
  "the hand with the phone sinks slowly to her side and the fingers barely keep their hold"),
 ("A9_SH07", "LENA_BASE", "bus_stop",
  "Lena from directly behind walking the avenue pavement in her coat, her pace even and too straight, the afternoon crowd thin around her",
  "BACK", "eye", "track", "day", False, False,
  "домой она идёт пешком через парк, потому что в автобусе можно заплакать.",
  "she walks an unnaturally straight line down the pavement, her coat hem swaying"),
 ("A9_SH08", ("MARK_MAIN", "SEMYON_BASE"), "park_pond",
  "the pond from the gravel path, two men on the far bench bent over something small between them, october sun low through the lindens",
  "EWS", "high", "static", "day", False, False,
  "с гравийной дорожки видно лавку у пруда и двоих мужчин над жестяной коробочкой.",
  "the two distant figures lean together over the bench while leaves drift down between the trees"),
 ("A9_SH09", ("MARK_MAIN", "SEMYON_BASE"), "park_pond",
  "Mark advances a tiny pawn on the magnetic board and laughs at something, Semyon scattering sunflower seeds to pigeons with a broad hand",
  "MS", "eye", "static", "day", False, False,
  "ты двигаешь пешку и смеёшься над тем, что сказал семён.",
  "his fingers advance the tiny pawn while the older man's hand scatters seeds in an arc",
  "CHESS"),
 ("A9_SH10", "LENA_BASE", "park_pond",
  "Lena stopped dead on the gravel path, one hand risen to the collar of her coat, her eyes fixed on something off frame",
  "CU", "eye", "static", "day", False, False,
  "лена узнаёт этот смех с тридцати метров — дома он звучит всё реже.",
  "her risen hand closes slowly on her coat collar as she stands unmoving"),
 ("A9_SH11", ("MARK_MAIN", "LENA_BASE", "SEMYON_BASE"), "park_pond",
  "Lena sits down on the far end of the bench looking at the pond, Mark frozen mid-move at the near end, Semyon rising tactfully with his cap",
  "WS", "eye", "static", "day", False, True,
  "она молча садится на дальний край лавки и смотрит на пруд, а не на тебя.",
  "she settles onto the bench end and the older man rises quietly, gathering his coat"),
 ("A9_SH12", "MARK_MAIN", "park_pond",
  "Mark's hand holding a tiny chess piece in mid-air over the board, the rest of him perfectly still, his eyes on the woman off frame",
  "MCU", "eye", "static", "day", False, False,
  "рука с пешкой замирает в воздухе, и семён тихо закрывает жестяную крышку.",
  "the hand with the tiny piece lowers slowly until it rests on the board edge",
  "CHESS"),
 ("A9_SH13", ("LENA_BASE", "MARK_MAIN"), "park_pond",
  "past Mark's shoulder, Lena in profile on the bench end, speaking two words at the pond, her hands folded on her lap",
  "OTS", "over", "static", "day", False, False,
  "она говорит два слова — «поехали домой» — и встаёт первой.",
  "her folded hands part and she rises from the bench in one straight motion"),
 ("A9_SH14", ("MARK_MAIN", "LENA_BASE"), "park_pond",
  "the park path from high above, a man and a woman walking toward the gate an arm's length apart, one small figure left on the bench far behind",
  "EWS", "high", "static", "day", False, False,
  "вы идёте к выходу из парка на расстоянии вытянутой руки, и это самое длинное расстояние за семнадцать лет.",
  "the two figures move slowly along the path holding the same fixed gap between them"),
 ("A9_SH15", ("MARK_MAIN", "LENA_BASE"), "flat_kitchen",
  "Mark lays the work record book and a folded agreement on the kitchen table in front of seated Lena, his hand flattening them once",
  "MS", "eye", "static", "evening", False, False,
  "дома ты сам кладёшь на стол трудовую книжку и соглашение от двадцать седьмого марта.",
  "his hand sets the booklet down and presses it flat against the table once",
  "RECORD"),
 ("A9_SH16", "LENA_BASE", "flat_kitchen",
  "Lena reads the booklet under the lamp, her finger on the record line, her lips counting months silently",
  "CU", "eye", "static", "evening", False, True,
  "лена читает дату и считает вслух — апрель, май, июнь, июль, август, сентябрь, октябрь.",
  "her finger moves along the record line while her lips shape the counted months",
  "RECORD"),
 ("A9_SH17", None, None,
  "a woman's finger resting on the dismissal date line of the open work record book, lamplight on the grey-green paper",
  "ECU", "top", "static", "evening", False, False,
  "семь месяцев, говорит она, семь месяцев я жила с человеком, которого рядом не было.",
  "her fingertip presses the date line until the soft paper dents under it",
  "RECORD"),
 ("A9_SH18", ("MARK_MAIN", "LENA_BASE"), "flat_kitchen",
  "the kitchen from the doorway late at night, Mark and Lena at opposite table ends over untouched cold tea, only the small lamp on",
  "WS", "eye", "static", "night", False, False,
  "вы сидите над остывшим чаем до половины второго ночи, и никто не включает верхний свет.",
  "steam has stopped over the two cups and only the lamp flame of light holds the table"),
]

A10 = [
 ("A10_SH01", "LENA_BASE", "flat_kitchen",
  "Lena stands at the sink with her back half turned, wringing a towel in her hands slowly, her face composed and closed",
  "MCU", "eye", "static", "night", False, False,
  "лена не кричит ни в эту ночь, ни после — и это хуже крика.",
  "her hands wring the towel through one slow twist and go still on the sink edge"),
 ("A10_SH02", "LENA_BASE", "flat_kitchen",
  "Lena's face straight to the lens across the table, calm and terribly tired, the lamp between her and the dark window",
  "CU", "eye", "push_in", "night", False, True,
  "она говорит, что простила бы сокращение за один вечер, а вот семь месяцев прощать не умеет.",
  "her eyes hold steady on the lens and one slow blink underlines the spoken words"),
 ("A10_SH03", "LENA_BASE", "flat_bedroom",
  "Lena carries a folded blanket and a pillow out through the bedroom door, her chin level, the corridor dark beyond",
  "MS", "eye", "static", "night", False, False,
  "с этой ночи она стелет себе в комнате даши, и дверь закрывается на мягкий щелчок.",
  "she carries the folded blanket through the door and it swings slowly to behind her"),
 ("A10_SH04", None, "flat_kitchen",
  "two tea mugs standing at opposite ends of the kitchen table in morning light, the sugar bowl exactly between them",
  "ECU", "eye", "static", "morning", False, False,
  "за завтраком вы разговариваете вежливо, как коллеги из разных отделов.",
  "morning light creeps along the table between the two distant standing mugs"),
 ("A10_SH05", ("DASHA_BASE", "MARK_MAIN"), "flat_hall",
  "Dasha in her school blazer hugs Mark in the hallway a beat longer than usual, her cheek against his shoulder, his hand rising slowly to her braid",
  "MS", "eye", "static", "morning", False, False,
  "даша ничего не спрашивает и только обнимает тебя утром чуть дольше обычного.",
  "her arms tighten around him a moment longer and his hand comes up gently to her braid"),
 ("A10_SH06", "MARK_MAIN", None,
  "his own hand in frame dialling a number written on a torn notebook corner, the paper pinned under his thumb",
  "POV", "pov", "static", "day", False, False,
  "ты набираешь номер стройбазы сам и произносишь три слова — «место ещё есть».",
  "the thumb dials the number in steady presses while the torn corner trembles slightly"),
 ("A10_SH07", "MARK_MAIN", "flat_kitchen",
  "Mark with the phone at his ear, his eyes closing in relief for one long second, his palm flat on the table",
  "CU", "eye", "static", "day", False, False,
  "место есть, и пятьдесят две тысячи больше не звучат как оскорбление.",
  "his eyes close for a long second and his flat palm relaxes on the table"),
 ("A10_SH08", None, None,
  "the work record book open at a fresh second entry, an ink stamp beside it still glossy, a pen laid across the page",
  "INSERT", "eye", "static", "day", False, False,
  "в трудовой появляется вторая запись за девятнадцать лет — «кладовщик склада материалов».",
  "the glossy ink of the fresh stamp dulls slowly as it dries on the page",
  "RECORD"),
 ("A10_SH09", "MARK_MAIN", "warehouse",
  "Mark in an orange vest over a checked shirt walks the aisle between pallet racks with a clipboard, his stride already sure",
  "WS", "eye", "track", "morning", False, False,
  "в понедельник ты выходишь в семь тридцать, и жилет пахнет чужим потом и цементом.",
  "the man walks the rack aisle checking lines off the clipboard as he goes"),
 ("A10_SH10", "MARK_MAIN", "warehouse",
  "Mark argues a point with a driver whose elbow leans at the frame edge, tapping the clipboard with the back of his hand, vest bright in the grey hall",
  "MS", "eye", "static", "day", False, False,
  "к обеду ты уже споришь с водителем о недовозе, и голос сам вспоминает начальственные ноты.",
  "the back of his hand taps the clipboard twice on the disputed line"),
 ("A10_SH11", "MARK_MAIN", "warehouse",
  "Mark by the security window hanging his vest on the hook at shift end, his collar open, his face tired in the plain honest way",
  "MCU", "eye", "static", "evening", False, False,
  "галстук ты оставляешь дома — здесь он смешон, и от этого почему-то легче.",
  "he hangs the vest on the hook and rolls his neck once with plain tiredness"),
 ("A10_SH12", None, "flat_kitchen",
  "a printed pay slip with a modest sum lying on the kitchen table in lamplight, a bank card set squarely on top of it",
  "ECU", "top", "static", "evening", False, False,
  "первая честная зарплата вдвое меньше прежней, но её больше незачем носить через банкомат.",
  "lamplight settles on the pay slip while the card's chip glints once"),
 ("A10_SH13", ("MARK_MAIN", "LENA_BASE", "DASHA_BASE"), "flat_kitchen",
  "the family at supper under the lamp, Dasha talking with her fork raised, Lena asking Mark something across the table, the air a degree warmer",
  "WS", "eye", "static", "evening", False, True,
  "за ужином лена спрашивает, как прошёл день на складе, и слушает ответ до конца.",
  "the girl's raised fork dips as she listens and the woman leans in on her elbows"),
 ("A10_SH14", "LENA_BASE", "flat_kitchen",
  "Lena pours tea into Mark's cup at the table, her face still guarded but her hand steady and unhurried",
  "CU", "eye", "push_in", "evening", False, False,
  "это ещё не прощение, но она впервые за месяц наливает тебе чай сама.",
  "the tea rises slowly in the cup under her steady pouring hand"),
]

A11 = [
 ("A11_SH01", None, "warehouse",
  "the warehouse yard under first november frost, rack tops white-dusted, a truck at the gate with its lights on in the grey dawn",
  "EWS", "high", "static", "morning", True, False,
  "ноябрь красит склад в серый, и в семь двадцать ты уже отмечаешь первую машину.",
  "the truck's headlight beams swing slowly across the frosted yard as it turns in"),
 ("A11_SH02", "MARK_MAIN", "warehouse",
  "Mark in the orange vest waves a forklift back with one raised hand, the clipboard tucked under his other arm, breath steaming",
  "MS", "eye", "static", "morning", False, False,
  "ты знаешь этот склад наизусть за месяц, потому что снабжение — это снабжение с любой стороны ворот.",
  "his raised hand beckons the forklift back in short measured waves, breath steaming"),
 ("A11_SH03", "MARK_MAIN", "canteen",
  "Mark in the vest eats from the lilac-lidded lunch box at a plastic table, a mug steaming beside it, workers' shoulders blurred around him",
  "MCU", "eye", "static", "day", False, False,
  "обед из контейнера теперь съедается в комнате с мужиками, и вилка на резинке веселит всю смену.",
  "he lifts the strapped fork free of its elastic band and the mug steam drifts",
  "LUNCHBOX"),
 ("A11_SH04", None, None,
  "the lunch box washed and open, drying upside down on the rack over a kitchen sink, the lilac lid leaning against it",
  "ECU", "eye", "static", "evening", False, False,
  "вечером пустой контейнер сохнет над раковиной, и в этом опять есть простой честный смысл.",
  "a last water drop slides down the upturned container and falls to the sink",
  "LUNCHBOX"),
 ("A11_SH05", "MARK_MAIN", "flat_hall",
  "Mark carries the pressed grey suit on wooden hangers toward the open wardrobe, holding it high and flat like something official",
  "WS", "eye", "static", "evening", False, False,
  "серый костюм ты относишь в шкаф сам — отглаженный и застёгнутый на все пуговицы.",
  "he carries the hanging suit across the hallway holding it high so the trousers swing clear",
  "SUIT"),
 ("A11_SH06", None, None,
  "the grey suit hanging in the dark wardrobe between winter coats, the green striped tie draped over the crossbar, a thin light seam at the door edge",
  "INSERT", "eye", "static", "evening", False, True,
  "он висит в темноте между зимними куртками, как знамя расформированной части.",
  "the thin seam of light narrows across the hanging suit as the wardrobe door drifts",
  "SUIT"),
 ("A11_SH07", "MARK_MAIN", "flat_hall",
  "Mark lifts the brown briefcase up onto the top hallway shelf with both hands, settling it carefully flat, his chin up to watch it in",
  "MS", "low", "static", "evening", False, False,
  "портфель отца ты поднимаешь на антресоль двумя руками, как поднимают спящего ребёнка.",
  "his two hands ease the briefcase onto the high shelf and square it gently in place",
  "BRIEFCASE"),
 ("A11_SH08", None, None,
  "the two brass locks of the briefcase at rest in the dark of the top shelf, dull gleam only, dust already settling on the leather",
  "ECU", "low", "static", "night", False, True,
  "латунные замки молчат, и утро теперь начинается без клац-клац.",
  "the dull gleam on the brass locks fades slowly as the shelf light dies",
  "BRIEFCASE"),
 ("A11_SH09", "SEMYON_BASE", "park_pond",
  "Semyon alone on the green bench in thin first snow, setting up the tiny chessmen with bare fingers, his cap and shoulders dusted white",
  "WS", "eye", "static", "day", False, False,
  "семён всё ещё выходит к пруду к восьми, и его лавку уже присыпает первым снегом.",
  "his bare fingers stand the tiny chessmen one by one while snow settles on his cap",
  "CHESS"),
 ("A11_SH10", "MARK_MAIN", "flat_kitchen",
  "Mark at the dark kitchen window with a mug, looking out at the lit windows of other flats, his reflection soft in the glass",
  "MCU", "eye", "static", "night", False, False,
  "ты не судишь его — ты просто знаешь цену каждому из его спокойных «так всем проще».",
  "steam from the mug climbs past his still face as he watches the lit windows"),
 ("A11_SH11", "MARK_MAIN", "flat_kitchen",
  "Mark's face turning from the window toward the lens, tired, honest, at rest, the kitchen lamp warm behind him",
  "CU", "eye", "push_in", "night", False, False,
  "останься на канале — здесь каждую неделю выходит ещё одна чужая жизнь, прожитая за тебя.",
  "his head turns slowly from the window to the lens and holds there, calm"),
 ("A11_SH12", None, None,
  "the grey suit on its hangers seen through the narrow gap of the almost-closed wardrobe door, one thin blade of lamplight down the fabric",
  "INSERT", "eye", "push_in", "night", False, True,
  "эта история вымышлена, все совпадения случайны — не повторяй чужих ошибок.",
  "the blade of lamplight down the suit narrows to a thread as the door eases shut",
  "SUIT"),
]

if __name__ == "__main__":
    seed_act("A9", PAL_A9, A9)
    seed_act("A10", PAL_A10, A10)
    seed_act("A11", PAL_A11, A11)
