# -*- coding: utf-8 -*-
"""Seed CH07 — Первый раз, приход (HEROINE_YOUNG). Non-explicit. Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "a first night mistaken for love, dim and tender then hollow by dawn, smoky neon glow, non-explicit"
SHOTS = [
 ("CH07_SH01", "HEROINE_YOUNG", "disco",
  "medium of the heroine at seventeen as an older confident man approaches in the dancehall",
  "MS","eye","static","night",False,False,
  "в семнадцать на дискотеке к тебе подходит парень постарше, уверенный, с горящими глазами."),
 ("CH07_SH02", None, "disco",
  "close-up of a dim slow dance, the partner faceless, only his shoulder",
  "CU","eye","static","night",True,False,
  "он шепчет, что ты самая красивая в зале, и тёплая волна накрывает тебя с головой."),
 ("CH07_SH03", "HEROINE_YOUNG", "street_east",
  "medium close-up of her leaving into the night, a faceless man's back beside her",
  "MCU","eye","static","night",False,False,
  "ты уходишь с ним в ночь, впервые в жизни, и сердце колотится от страха и восторга."),
 ("CH07_SH04", None, "her_room",
  "extreme close-up of a lamp and clothes draped over a chair, a closed door, suggestive not explicit",
  "ECU","eye","static","night",True,False,
  "что было дальше, ты прячешь за закрытой дверью, но наутро весь мир кажется тебе другим."),
 ("CH07_SH05", "HEROINE_YOUNG", "her_room",
  "close-up of the heroine in morning light, glowing, sure she is in love",
  "CU","eye","static","dawn",False,False,
  "тебе кажется, вот она, любовь, вот оно, то самое тепло, которого ты искала всю жизнь."),
 ("CH07_SH06", None, "her_room",
  "medium of the bed beside her already empty and cold, he is gone",
  "MS","eye","static","dawn",True,False,
  "но рядом уже пусто, он ушёл на рассвете, не оставив даже короткой записки."),
 ("CH07_SH07", "HEROINE_YOUNG", "her_room",
  "medium close-up of her first taste of the empty morning",
  "MCU","eye","static","dawn",False,True,
  "и впервые ты чувствуешь это, сладкую ночь и холодное гулкое утро наедине с собой."),
 ("CH07_SH08", None, "street_east",
  "close-up of the same man with another girl, both faceless, from behind",
  "CU","eye","static","gdr_day",True,False,
  "через неделю ты видишь его с другой и понимаешь, для него это была просто ночь."),
 ("CH07_SH09", "HEROINE_YOUNG", "her_room",
  "close-up of the hurt turning into craving",
  "CU","eye","static","gdr_eve",False,False,
  "больно, но странно, тебе уже снова хочется повторить ту волну, и почти всё равно с кем."),
 ("CH07_SH10", "HEROINE_YOUNG", "her_room",
  "medium close-up of her quiet fateful decision",
  "MCU","eye","static","gdr_eve",False,True,
  "раз любовь так похожа на это, думаешь ты, значит, надо просто искать её снова и снова."),
 ("CH07_SH11", None, "disco",
  "wide B-roll of the dim empty dancehall, silent",
  "WS","eye","static","night",True,False,""),
]
if __name__ == "__main__":
    seed_act(7, "gdr_night", MOOD, "static", "CH07 First time", SHOTS)
