# -*- coding: utf-8 -*-
"""squeeze_out atmosphere breathers: 2 per act (A1..A11), id_region='a', per-act unique schemes."""
from _squeeze_out_engine import seed_act

PALS = {
 "A1": "warm bureau daylight, paper and wood tones, soft window light",
 "A2": "renovated white light, fresh paint tones, cool glass accents",
 "A3": "grey institutional light, drained colours, pale cold windows",
 "A4": "cold evening desk light, deep shadow corners, blue dusk windows",
 "A5": "clear spring light, fresh green accents, warm brick tones",
 "A6": "dim basement light, pipe shadows, one barred window glow",
 "A7": "hard autumn light, long cold shadows, bronze leaf accents",
 "A8": "late lamp amber, deep evening blue, warm and cold split",
 "A9": "flat winter white, pale even light, thin grey shadows",
 "A10": "thaw morning light, wet asphalt shine, soft clearing sky",
 "A11": "clear january light, crisp snow tones, warm brick interior",
}

ATMO = {
 "A1": [
  ("A1_SZ01", None, "archive_room",
   "yellowed tube labels on rolled plans in the archive rack, decades of dates in fading ink, one work lamp glow",
   "ECU", "eye", "push_in", "day", True, False,
   "в архиве бюро лежат мосты за шестьдесят лет — город в рулонах, полка за полкой.",
   "the work lamp glow deepens down the receding shelves of labelled tubes"),
  ("A1_SZ02", None, "site_bridge",
   "morning fog lifting off the river under a finished bridge span, a tug pushing a barge through the middle arch",
   "EWS", "high", "static", "morning", True, False,
   "под твоим первым мостом каждое утро проходит баржа с песком — точная, как будильник.",
   "the barge slides through the arch as fog thins off the brown water"),
 ],
 "A2": [
  ("A2_SZ01", None, "bureau_open",
   "a pallet of identical branded chairs in factory wrap by the hall wall, assembly instructions taped to the top one",
   "INSERT", "eye", "static", "day", True, False,
   "новые кресла приезжают на одной палете, одинаковые, как галочки в её распечатанном списке.",
   "the factory wrap crackles faintly and settles over the identical stacked chairs"),
  ("A2_SZ02", None, "street_bureau",
   "the old bureau signboard being unscrewed while a new backlit panel waits against the wall below",
   "WS", "low", "tilt_down", "day", True, False,
   "вывеску бюро меняют на панель с подсветкой — буквы те же, шрифт уже чужой.",
   "the old signboard tilts on its last screw above the waiting backlit panel",
   None, "crowd"),
 ],
 "A3": [
  ("A3_SZ01", None, "server_corner",
   "the server-room grille breathing warm air at a desk corner, a sticky note curling on the monitor edge",
   "ECU", "eye", "static", "day", True, False,
   "тёплый ветер серверной сушит стикеры на мониторе за один день.",
   "the sticky note curls slowly upward in the warm grille draught"),
  ("A3_SZ02", None, "bureau_open",
   "the bureau hall at seven in the evening, the new half dark and tidy, the old half lit by two stubborn lamps",
   "WS", "eye", "static", "evening", True, False,
   "новая половина зала уходит домой в шесть, старая по привычке досиживает до темноты.",
   "two stubborn lamps hold their pools in the old half as the hall dims",
   None, "crowd"),
 ],
 "A4": [
  ("A4_SZ01", None, "home_kitchen",
   "children's drawings on the fridge, the newest one showing a stick family where the tall figure stands slightly apart",
   "ECU", "eye", "push_in", "evening", True, False,
   "на новом рисунке тимы папа стоит чуть в стороне от домика — дети рисуют точно.",
   "the drawing's corner lifts under the fridge magnet as the door closes somewhere"),
  ("A4_SZ02", None, "street_bureau",
   "november rain on the bureau street at night, the new backlit sign doubling in the wet asphalt",
   "EWS", "low", "static", "night", True, False,
   "к ноябрю дожди смывают со стен последние объявления старого бюро.",
   "the backlit sign shivers in the wet asphalt as rain needles the street"),
 ],
 "A5": [
  ("A5_SZ01", None, "pasha_office",
   "a wall of pinned thank-you postcards and small project photos in the studio, string and clothes pegs, brick behind",
   "INSERT", "eye", "pan_right", "day", True, False,
   "у паши на кирпиче висят открытки от заказчиков — на бечёвке, прищепками, без рамок.",
   "the pinned postcards sway together gently on their string against the brick"),
  ("A5_SZ02", None, "street_bureau",
   "poplar fluff drifting across the bureau street in low evening sun, catching in the granite step corners",
   "WS", "eye", "static", "evening", True, False,
   "тополиный пух собирается в углах крыльца, как черновики, которые никто не подберёт.",
   "fluff drifts across the low sun and gathers slowly in the step corners"),
 ],
 "A6": [
  ("A6_SZ01", None, "bureau_basement",
   "the basement corridor with pipe runs overhead, a cage of old chairs and lamps at its end under a bare bulb",
   "WS", "eye", "push_in", "day", True, False,
   "в конце подвального коридора стоит клетка со списанной мебелью — сюда ссылают вещи.",
   "the bare bulb sways a centimetre and the caged chair shadows sway with it"),
  ("A6_SZ02", None, "bureau_basement",
   "hot water pipes overhead wrapped in bandage lagging, one slow drip falling from a valve into a tin can",
   "ECU", "low", "static", "day", True, False,
   "с вентиля над столом капает ровно раз в минуту, и жестянка под ним тихо звенит.",
   "the slow drip gathers, falls and rings faintly in the tin can below"),
 ],
 "A7": [
  ("A7_SZ01", None, "bureau_open",
   "the framed interchange print in the empty evening hall, a cleaner's floor machine parked beneath it",
   "WS", "low", "static", "evening", True, False,
   "вечером у флагманской рамы паркуется поломоечная машина — искусство и быт делят холл.",
   "the floor machine's warning light blinks slowly beneath the framed print"),
  ("A7_SZ02", None, "street_bureau",
   "bronze leaves flowing along the gutter past the bureau steps in a gust, pinned briefly against a drain grate",
   "ECU", "high", "static", "day", True, False,
   "листья идут по водостоку сплошной лентой — осень работает без пересмотра мотивации.",
   "the leaf stream pins against the drain grate and tears free again"),
 ],
 "A8": [
  ("A8_SZ01", None, "pasha_office",
   "the studio window at dusk from outside, nine warm desk lamps and a bicycle silhouette against the brick",
   "EWS", "eye", "static", "evening", True, False,
   "у паши в окнах девять тёплых ламп, и все девять гаснут до восьми вечера.",
   "the nine warm lamps glow steady as one by one they begin to die"),
  ("A8_SZ02", None, "home_hall",
   "the hallway mirror with family photos tucked into its frame, the newest photo slightly askew",
   "INSERT", "eye", "push_in", "night", True, False,
   "новых фотографий в раме зеркала не прибавлялось уже два года — некому нажимать кнопку.",
   "lamplight from the kitchen grazes the tucked photos as the flat settles for the night"),
 ],
 "A9": [
  ("A9_SZ01", None, "bureau_open",
   "the hall after the farewell party, cake crumbs on paper plates, the bouquet cellophane in a bin, chairs askew",
   "WS", "eye", "static", "evening", True, False,
   "после проводов остаются крошки торта и целлофан — праздники здесь убирают быстро.",
   "cellophane in the bin unfolds itself slowly among the crumbed plates"),
  ("A9_SZ02", None, "bureau_basement",
   "the barred basement window from inside at dusk, snow beginning to seal the outside sill upward",
   "ECU", "low", "static", "evening", True, False,
   "снег за окном подвала растёт снизу вверх, как уровень воды.",
   "snow builds slowly up the outer sill, dimming the window slot light"),
 ],
 "A10": [
  ("A10_SZ01", None, "street_bureau",
   "thaw morning on the bureau street, long meltwater streams running down the gutter, sparrows working a bare patch",
   "EWS", "high", "pan_left", "morning", True, False,
   "оттепель вскрывает улицу за одно утро, и вода идёт по жёлобу весёлая, как гурьба школьников.",
   "meltwater threads braid down the gutter while sparrows hop the bare patch"),
  ("A10_SZ02", None, "home_kitchen",
   "a block-built overpass left standing on the kitchen table, the dinosaur parked on its span, afternoon sun across it",
   "INSERT", "eye", "static", "day", True, False,
   "эстакада из кубиков стоит на столе третий день, и никто не требует освободить площадь.",
   "afternoon sun slides along the block span under the parked dinosaur"),
 ],
 "A11": [
  ("A11_SZ01", None, "pasha_office",
   "melting snow pooling on spread newspaper under leaned sleds and a bicycle wheel in the studio entry",
   "ECU", "eye", "static", "day", True, False,
   "в прихожей бюро зимой паркуются велосипед и двое санок — штат растёт.",
   "meltwater spreads slowly across the newspaper under the leaning sleds"),
  ("A11_SZ02", None, "site_bridge",
   "the small river bridge site under fresh snow at sunset, survey stakes with orange ribbons in a clean line",
   "EWS", "low", "static", "evening", True, False,
   "колышки нового мостика стоят под снегом ровной строчкой — весной по ней пойдёт первая свая.",
   "orange ribbons flutter in a line above the fresh snow as the sunset light deepens"),
 ],
}

if __name__ == "__main__":
    for act, shots in ATMO.items():
        seed_act(act, PALS[act], shots, id_region="a")
