# -*- coding: utf-8 -*-
"""Seed CH29 — Одна в новом Берлине (HEROINE_MID). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "alone in the new Berlin, the chase finally failing, hollow cold daylight"
SHOTS = [
 ("CH29_SH01", "HEROINE_MID", "street_west",
  "medium of the heroine over fifty, the hunt no longer working",
  "MS","eye","static","day",False,False,
  "пятьдесят с лишним, и охота, которой ты жила полвека, больше не приносит никакой добычи."),
 ("CH29_SH02", "HEROINE_MID", "cafe_west",
  "medium close-up of her drinking alone in a corner",
  "MCU","eye","static","day",False,False,
  "ты ещё ходишь по барам, но всё чаще просто пьёшь одна в углу и смотришь на чужое веселье."),
 ("CH29_SH03", None, "cafe_west",
  "wide of groups and couples around her empty table",
  "WS","eye","static","day",True,False,
  "вокруг компании, пары, смех, а у тебя ни подруги, ни мужа, ни ребёнка, совсем никого."),
 ("CH29_SH04", "HEROINE_MID", "her_room",
  "close-up of her sorting through memories of hundreds of men",
  "CU","eye","static","day",False,False,
  "ты перебираешь в памяти сотни мужчин и не находишь ни одного, кто остался бы рядом."),
 ("CH29_SH05", "HEROINE_MID", "her_room",
  "medium close-up of her grasping she burned love to ash each time",
  "MCU","eye","static","day",False,False,
  "ты выжигала любовь дотла, едва она появлялась, и вот выжгла дочиста всё вокруг себя."),
 ("CH29_SH06", None, "her_room",
  "extreme close-up of the box holding Andreas's key",
  "ECU","top_down","static","day",True,True,
  "только ключ Андреаса всё лежит в шкатулке, единственная дверь, что когда-то была открыта."),
 ("CH29_SH07", "HEROINE_MID", "her_room",
  "close-up of her holding the key, wondering",
  "CU","eye","static","day",False,False,
  "ты впервые достаёшь его, держишь на ладони и думаешь, а что, если бы ты тогда осталась."),
 ("CH29_SH08", "HEROINE_MID", "street_west",
  "medium of her walking alone past cheerful shop windows",
  "MS","eye","static","day",False,False,
  "по новому Берлину ты бредёшь одна, мимо весёлых витрин, мимо чужого, неподдельного счастья."),
 ("CH29_SH09", None, "street_west",
  "close-up of the indifferent city she once dreamed of",
  "CU","eye","static","day",True,False,
  "город, о свободе которого ты мечтала за стеной, оказался к тебе совсем равнодушен."),
 ("CH29_SH10", "HEROINE_MID", "her_room",
  "medium close-up of the bitter sum, freedom without love",
  "MCU","eye","static","day",False,True,
  "свобода была, желание было, а любви, простой человеческой любви, так и не случилось."),
 ("CH29_SH11", None, "street_west",
  "wide B-roll of a hollow bright western street, silent",
  "WS","eye","static","day",True,False,""),
]
if __name__ == "__main__":
    seed_act(29, "west_day", MOOD, "static", "CH29 Alone in Berlin", SHOTS)
