# -*- coding: utf-8 -*-
"""optimizer shots: A0 (cold open), A1 (origin: the card), A2 (consulting rise)."""
from _optimizer_engine import seed_act

PAL_A0 = "cold glass morning light, pale blue reflections, grey office tones"
PAL_A1 = "warm office daylight, soft beige tones, gentle window glow"
PAL_A2 = "steel corporate light, cool white desks, glass reflections"

A0 = [
 ("A0_SH01", None, "client_open",
  "an open-plan office frozen mid-morning, a man sitting on the floor beside his desk with a cardboard box, standing figures keeping a wary circle around him",
  "EWS", "high", "static", "morning", False, False,
  "в опенспейсе клиента сидит на полу человек с картонной коробкой и не собирается вставать.",
  "the seated figure hugs the box a little tighter while the circle of onlookers holds its distance",
  None, "crowd"),
 ("A0_SH02", "ELYA_BASE", "lift_lobby",
  "Elya strides out of the lift with the slim tablet against her chest, her free hand already pulling her hair behind one ear, eyes fixed ahead",
  "MCU", "eye", "track", "morning", False, False,
  "тебя выдёргивают со встречи этажом выше, потому что это уже твой профиль — тишина.",
  "she walks fast out of the opening lift doors, tucking a strand of hair behind her ear",
  "TABLET"),
 ("A0_SH03", None, "client_open",
  "two security guards seen from behind, shoulders squared toward the seated man in the distance, radios in their belts",
  "WS", "eye", "static", "morning", False, False,
  "охрана предлагает просто взять его под руки, и это худшее, что можно сделать.",
  "the near guard shifts his weight forward and his hand settles on his belt radio",
  None, "crowd"),
 ("A0_SH04", None, "client_open",
  "raised hands holding phones over the tops of monitors, screens aimed at one point, office plants blurred between them",
  "ECU", "eye", "static", "morning", False, False,
  "по периметру подняты телефоны, и каждый такой ролик завтра ляжет на репутацию клиента.",
  "the raised phones hold steady while one screen tilts slowly for a better angle",
  None, "crowd"),
 ("A0_SH05", "ELYA_BASE", "client_open",
  "Elya dismisses the guards with one small flat-palm gesture and slips her blazer off onto a chair back, her eyes on the seated man off frame",
  "MS", "eye", "static", "morning", False, False,
  "ты отсылаешь охрану одним движением ладони и снимаешь пиджак на спинку стула.",
  "her flat palm makes one small dismissing motion and the blazer slides off her shoulders"),
 ("A0_SH06", "ELYA_BASE", "client_open",
  "Elya crouches down level beside the seated man whose hunched back fills the frame edge, her forearms on her knees, her face patient",
  "WS", "low", "static", "morning", False, True,
  "ты садишься рядом с ним на корточки, на его высоту, и молчишь первые полминуты.",
  "she lowers herself onto her heels beside him and settles into a still patient crouch"),
 ("A0_SH07", None, None,
  "a plastic cup of water passing from a woman's manicured hand into a man's rough hesitant hand, a cardboard box blurred below",
  "ECU", "eye", "static", "morning", False, False,
  "стакан воды из кулера он берёт не сразу, но берёт.",
  "the cup passes slowly from her steady hand into his hesitant fingers"),
 ("A0_SH08", "ELYA_BASE", "client_open",
  "Elya listens with her chin slightly tipped, holding eye contact downward, her tablet face-down on the floor beside her",
  "MCU", "eye", "static", "morning", False, False,
  "три минуты он говорит про собаку, которую теперь не на что лечить, и ты слушаешь.",
  "she holds her listening stillness and gives one slow nod at the right moment"),
 ("A0_SH09", "ELYA_BASE", None,
  "her own view downward, a man's hands folding the box flaps closed one over another, then bracing against the floor",
  "POV", "pov", "static", "morning", False, False,
  "потом он сам закрывает клапаны коробки и упирается рукой в пол, чтобы встать.",
  "the hands fold the flaps shut in turn and press down hard against the floor"),
 ("A0_SH10", "ELYA_BASE", "client_open",
  "Elya walks toward the exit carrying the man's cardboard box while he walks beside her a step behind, the office rows parting ahead",
  "WS", "eye", "track", "morning", False, False,
  "до турникета его коробку несёшь ты, и это не жест для публики — это техника.",
  "she carries the box at an even pace and he keeps half a step behind her shoulder"),
 ("A0_SH11", None, None,
  "a firm handshake in close-up between a woman's manicured hand and a man's broad hand, a turnstile arm blurred behind",
  "CU", "eye", "static", "morning", False, False,
  "у выхода он жмёт тебе руку, и охрана делает вид, что так и было задумано.",
  "the two hands grip once, hold a beat, and release slowly"),
 ("A0_SH12", "ELYA_BASE", "client_open",
  "Elya walks back through the rows pulling her blazer on, heads bowed to monitors again on both sides of her path",
  "MS", "eye", "static", "morning", False, False,
  "телефоны опускаются сами — досматривать здесь больше нечего.",
  "she shrugs the blazer back over her shoulders in mid-stride, her pace unbroken"),
 ("A0_SH13", None, None,
  "the slim tablet held in one hand, its screen showing a checklist row ticked closed and a calendar slot at eleven thirty",
  "INSERT", "eye", "static", "morning", False, True,
  "в лифте ты ставишь в планшете отметку «инцидент закрыт, шесть минут» и открываешь расписание.",
  "a fingertip ticks the checklist row and the screen slides to the day's calendar",
  "TABLET"),
 ("A0_SH14", "ELYA_BASE", "lift_lobby",
  "Elya's reflection doubled in the brushed steel lift doors, her posture perfect, the floor indicator counting above",
  "MCU", "eye", "push_in", "morning", False, False,
  "останься до конца — я расскажу, как ты стала человеком, которого зовут, когда надо тихо уволить тысячу двести человек.",
  "her blurred steel reflection straightens as the floor numbers climb one by one"),
]

A1 = [
 ("A1_SH01", "ELYA_BASE", "client_open",
  "Elya at twenty-four at a recruiter's desk with two phones and a wall of printed CVs behind her, mid-call, bright and quick",
  "WS", "eye", "static", "day", False, False,
  "семь лет назад тебе двадцать четыре, и ты лучший рекрутер этажа — ты людей находишь.",
  "she swivels her chair between the two ringing phones and catches the second receiver"),
 ("A1_SH02", "ELYA_BASE", "client_open",
  "young Elya smiles into the phone with genuine warmth, one hand pressing the receiver close, the other giving a small victory squeeze",
  "MCU", "eye", "static", "day", False, False,
  "ты звонишь человеку и меняешь его жизнь к лучшему, и тебе за это платят.",
  "her free hand closes into a small quiet victory fist as she talks"),
 ("A1_SH03", None, None,
  "a single printed sheet on a desk with five typed surnames, a handwritten note in the margin, a director's heavy signature below",
  "ECU", "top", "static", "day", False, False,
  "в кризисный квартал руководство приносит тебе список из пяти фамилий — «выведи аккуратно».",
  "desk lamplight slides along the five typed lines as the sheet settles flat"),
 ("A1_SH04", "ELYA_BASE", "client_open",
  "Elya alone in the evening office holding the list in both hands, the ceiling lights off except one row, her face working the problem",
  "MS", "eye", "static", "evening", False, False,
  "увольнять у нас не умеет никто, и задача падает на ту, кто умеет разговаривать.",
  "her thumbs tighten on the sheet edges and she reads the five lines over again"),
 ("A1_SH05", "ELYA_BASE", None,
  "her own hand drafting phrases on a notepad at night, several lines crossed out hard, a tea mug at the page corner",
  "POV", "pov", "static", "night", False, False,
  "ночью ты пишешь себе шпаргалку — какие слова говорить и какие запрещены навсегда.",
  "the pen crosses out one line with two hard strokes and writes a shorter one beneath"),
 ("A1_SH06", None, None,
  "a white handwritten card emerging from the rollers of a small laminator, the film still warm and glossy, a coffee ring visible on one corner",
  "INSERT", "eye", "static", "morning", False, True,
  "утром ты прогоняешь карточку через ламинатор, чтобы слова держали форму дольше бумаги.",
  "the card slides slowly out of the laminator rollers with a soft gloss on its film",
  "CARD"),
 ("A1_SH07", "ELYA_BASE", "client_meeting",
  "young Elya across a small table from a man whose hunched back edges the frame, her hands folded on the laminated card, a tissue box to her left",
  "WS", "eye", "static", "day", False, False,
  "первый из пяти плачет, второй молчит, третий благодарит — и все пятеро выходят без охраны.",
  "her folded hands rest still on the card while the man's shoulders sag by degrees",
  "CARD"),
 ("A1_SH08", "ELYA_BASE", "client_open",
  "Elya's face over a washroom sink, wet hands gripping the porcelain edge, her eyes down, mirror light flat on her",
  "CU", "eye", "static", "day", False, False,
  "после пятого ты долго моешь руки в туалете этажа, хотя руки чистые.",
  "water drips from her fingers as her grip slowly loosens on the sink edge"),
 ("A1_SH09", "ELYA_BASE", "client_open",
  "Elya at her desk while an older manager's hand rests on the desk edge from off frame, her face polite under the praise",
  "MS", "eye", "static", "day", False, False,
  "начальство называет это «талантом к сложным разговорам» и выписывает тебе премию.",
  "her polite smile holds while her fingers square the papers on the desk"),
 ("A1_SH10", None, None,
  "a thin bonus envelope lying on a desk keyboard, a payslip corner protruding, morning light across it",
  "ECU", "eye", "static", "day", False, False,
  "в конверте тридцать тысяч, и это первые деньги, заработанные на чужом уходе.",
  "the envelope flap lifts a degree in the draught of a passing colleague"),
 ("A1_SH11", ("GALINA_BASE", "ELYA_BASE"), "mother_flat",
  "Galina stirs a pot at the stove half turned to Elya who sits at the oilcloth table, the kitchen warm and cluttered around them",
  "MS", "eye", "static", "evening", False, False,
  "мать спрашивает, кем ты работаешь, и ты отвечаешь — «по кадрам, мама».",
  "the mother stirs the pot and glances over her shoulder while the daughter studies her cup"),
 ("A1_SH12", "GALINA_BASE", "mother_flat",
  "Galina's lined face in lamplight, a knowing reserve in her eyes, her hand setting a slice of bread onto a plate",
  "CU", "eye", "static", "evening", False, False,
  "она кивает так, будто услышала не всё, и подкладывает тебе хлеб.",
  "her hand lays the bread slice down gently and pats the plate edge once"),
 ("A1_SH13", "ELYA_BASE", "parking",
  "young Elya walks across an old courtyard at dusk between parked cars, her coat collar up, her step quick and decided",
  "WS", "eye", "track", "evening", False, False,
  "по дороге домой ты решаешь, что «по кадрам» — это почти правда, а почти достаточно.",
  "she walks a brisk straight line between the cars, her collar up against the chill"),
 ("A1_SH14", "ELYA_BASE", "elya_flat",
  "Elya at her dark window with a phone against her ear, a new offer conversation, her reflection sharp against the city lights",
  "MCU", "eye", "static", "night", False, False,
  "через полгода тебя зовут уже в другие компании — у тебя получается то, что никому не нравится делать.",
  "she turns from the window mid-call and her reflection turns with her against the lights"),
 ("A1_SH15", None, None,
  "the laminated card sliding into an inner pocket of a leather handbag, the coffee ring on its corner catching the light",
  "INSERT", "eye", "static", "night", False, False,
  "карточка переезжает в сумку насовсем, и кофейное полукольцо на углу становится её частью.",
  "the card slides down into the bag pocket until only its glossy corner shows",
  "CARD"),
 ("A1_SH16", None, "elya_flat",
  "the city at dusk from a high window, cranes and office towers with scattered lit floors, a plane light crossing",
  "EWS", "high", "static", "evening", True, False,
  "городу всегда кого-то надо нанимать, а значит — и увольнять, и ты нужна всем.",
  "scattered office floors light up one by one across the dusk skyline"),
]

A2 = [
 ("A2_SH01", None, "consult_office",
  "an open glass consultancy floor in morning light, long white desks, a wall of framed client logos, the city in haze beyond",
  "EWS", "eye", "static", "morning", True, False,
  "кирилл находит тебя сам — его консалтинг продаёт компаниям «тихие оптимизации» под ключ.",
  "morning haze brightens slowly behind the glass wall over the still white desks"),
 ("A2_SH02", "KIRILL_BASE", "consult_office",
  "Kirill studies someone across his desk over the rim of a steel thermo-mug, his pale eyes appraising, silver glasses low on his nose",
  "MCU", "eye", "static", "day", False, False,
  "он смотрит на тебя поверх термокружки и говорит, что талант должен масштабироваться.",
  "he lowers the thermo-mug a centimetre and his eyes stay level over the rim"),
 ("A2_SH03", ("ELYA_BASE", "KIRILL_BASE"), "consult_office",
  "Elya signs an offer at the glass desk while Kirill stands beside it with his mug, her pen steady, his head tilted in approval",
  "MS", "eye", "static", "day", False, False,
  "ты подписываешь оффер с окладом двести шестьдесят тысяч и отдельной строкой про неразглашение.",
  "her pen draws the signature while he tips his head a slow approving degree"),
 ("A2_SH04", None, None,
  "a fresh business card held between two fingers, an embossed title line and a discreet consultancy logo, the wording soft and neutral",
  "ECU", "eye", "static", "day", False, False,
  "на визитке пишут «руководитель практики расставаний», и слово «увольнение» не пишут нигде.",
  "the card turns slowly between the two fingers and its embossed line catches the light"),
 ("A2_SH05", "ELYA_BASE", "training_hall",
  "Elya on the small stage of a conference hall by a flipchart, rows of listeners' backs before her, a marker raised mid-point",
  "WS", "eye", "static", "day", False, False,
  "по четвергам ты учишь чужих кадровиков своим правилам — зал всегда полный.",
  "her marker taps the flipchart twice while the rows of heads angle up to her",
  None, "crowd"),
 ("A2_SH06", "ELYA_BASE", "training_hall",
  "Elya at the flipchart writing a short rule, her blazer sleeve pulled back, her face lit with the certainty of a specialist",
  "MCU", "eye", "static", "day", False, False,
  "правило первое — салфетки всегда слева, потому что за ними тянутся правой.",
  "the marker writes a short line and she underlines it with one firm stroke"),
 ("A2_SH07", None, None,
  "a plain white cube tissue box on a demonstration table, one tissue raised like a sail, a bottle of still water beside it",
  "INSERT", "eye", "static", "day", False, False,
  "правило второе — вода без газа уже на столе, чтобы не выходить и не прерывать.",
  "the raised tissue sways a centimetre in the hall's ventilation draught",
  "TISSUES"),
 ("A2_SH08", ("ELYA_BASE", "RITA_BASE"), "training_hall",
  "Elya holds up a stopwatch while Rita beside her marks time on a clipboard, both in profile to the listening rows",
  "MS", "eye", "static", "day", False, True,
  "правило третье — четыре с половиной минуты на человека, дольше жестоко, быстрее оскорбительно.",
  "her thumb clicks the stopwatch and the young woman beside her notes the split"),
 ("A2_SH09", None, None,
  "the laminated card lying on a lectern edge under stage light, its handwritten lines and the pale coffee ring clearly visible",
  "ECU", "high", "static", "day", False, False,
  "свою карточку ты кладёшь перед собой на каждой сессии, хотя давно знаешь её наизусть.",
  "stage light glints across the laminate film as the card lies perfectly still",
  "CARD"),
 ("A2_SH10", "ELYA_BASE", "elya_cabinet",
  "Elya in her small glass office beside a strapped bundle of flat cardboard boxes leaning on the wall, one hand resting on the top sheet",
  "WS", "eye", "static", "day", False, False,
  "в твоём кабинете у стены всегда лежит пачка плоских коробок — оптом они по девяносто рублей.",
  "her hand pats the top sheet of the bundle once and slides off it",
  "BOXES"),
 ("A2_SH11", "KIRILL_BASE", "consult_office",
  "Kirill mid-pitch at a glass table gesturing toward someone off frame with an open palm, his thermo-mug standing before him like a chess piece",
  "MCU", "eye", "static", "day", False, False,
  "кирилл называет тебя козырем и достаёт тебя на переговорах, как достают козырь.",
  "his open palm turns upward in a presenting gesture and holds there"),
 ("A2_SH12", "ELYA_BASE", None,
  "her own hand scrolling a tablet calendar packed with client names, factory and pharmacy chains colour-coded week by week",
  "POV", "pov", "static", "day", False, False,
  "в твоём календаре месяц расписан по заводам, сетям и одному издательству.",
  "the fingertip scrolls the packed calendar down through four colour-coded weeks",
  "TABLET"),
 ("A2_SH13", "ELYA_BASE", "elya_cabinet",
  "Elya's composed face at her desk, the orchid blurred on the sill behind her, her chin level and her eyes quietly certain",
  "CU", "eye", "push_in", "day", False, True,
  "ты говоришь себе, что делаешь страшное дело нестрашно — и это твоя форма честности.",
  "her level gaze holds the lens and one slow breath lifts and settles her shoulders"),
 ("A2_SH14", "GALINA_BASE", "mother_plant",
  "Galina walks through the old plant checkpoint turnstile among a thin morning shift, nodding to the guard booth, her badge on her lapel",
  "MS", "eye", "static", "morning", False, False,
  "мать всё ещё ходит через свою проходную к семи и зовёт это «наш завод».",
  "she pushes through the turnstile with a practiced hip and nods to the guard booth",
  None, "crowd"),
 ("A2_SH15", None, None,
  "a small enamel veteran badge on a coat lapel in tight close-up, its gilt edge worn, a knitted cardigan collar beneath",
  "ECU", "eye", "static", "morning", False, False,
  "эмалевый значок на её лацкане старше половины твоих клиентов.",
  "the badge catches a modest gleam as the coat lapel rises with a breath"),
 ("A2_SH16", None, "consult_office",
  "the consultancy floor at night from outside the glass, one of the few lit floors in the dark tower, tiny figures still at desks",
  "EWS", "low", "static", "night", True, False,
  "консалтинг растёт на чужих сокращениях, и твой этаж светится дольше всех в башне.",
  "the lit floor glows steadily in the dark tower while single windows die around it",
  None, "crowd"),
]

if __name__ == "__main__":
    seed_act("A0", PAL_A0, A0)
    seed_act("A1", PAL_A1, A1)
    seed_act("A2", PAL_A2, A2)
