# -*- coding: utf-8 -*-
"""hidden_layoff shots: A0 (cold open), A1 (origin 2007), A2 (new director)."""
from _hidden_layoff_engine import seed_act

PAL_A0 = "cold fluorescent light, pale blue morning windows, grey office tones"
PAL_A1 = "warm amber light, soft golden haze, faded nostalgic colours"
PAL_A2 = "flat white office light, cool glass reflections, muted grey-blue"

A0 = [
 ("A0_SH01", None, "factory_yard",
  "the loading ramp of a furniture factory at dawn, the dock door rolled up onto an empty bay, stacked flat-pack panels waiting under film",
  "EWS", "high", "static", "morning", True, False,
  "в семь тридцать пять утра на рампе мебельной фабрики должна стоять фура с фурнитурой, и рампа пуста.",
  "thin morning mist drifts across the wet asphalt and a loose corner of packing film stirs slowly"),
 ("A0_SH02", "NINA_BASE", "office_openspace",
  "Nina pulls her phone headset down to her neck with one hand and turns toward the camera, her other hand still on the keyboard, alarm on her face",
  "MCU", "eye", "static", "morning", False, False,
  "нина снимает гарнитуру и говорит, что водитель стоит со сломанной коробкой передач в ста шестидесяти километрах.",
  "the young woman pulls the headset down to her neck and turns her head quickly toward the desk opposite"),
 ("A0_SH03", "MARK_MAIN", "office_openspace",
  "Mark looks up at a wall clock with a calm unhurried face, his chin lifted, morning light on his grey suit shoulder",
  "CU", "eye", "push_in", "morning", False, False,
  "сборочная линия съест последний ящик петель в одиннадцать ноль-ноль, и ты совершенно спокоен.",
  "the man's eyes narrow a little as he studies the clock and his jaw sets with quiet confidence"),
 ("A0_SH04", "MARK_MAIN", "office_openspace",
  "Mark sits at his desk with a worn address notebook open flat, one finger running down the page, the other hand lifting a desk phone to his ear",
  "MS", "eye", "static", "morning", False, False,
  "ты открываешь потёртую записную книжку на нужной букве и набираешь первый номер по памяти.",
  "his finger slides down the open notebook page and he lifts the desk phone receiver to his ear"),
 ("A0_SH05", None, "office_openspace",
  "a whiteboard of delivery schedules, the word for hinges circled twice in red marker beside the time eleven hundred",
  "ECU", "eye", "static", "morning", False, False,
  "на доске поставок напротив строки с петлями стоит время одиннадцать, обведённое красным маркером дважды.",
  "morning light brightens slowly across the whiteboard grid while the red circle holds its line"),
 ("A0_SH06", "MARK_MAIN", "office_openspace",
  "Mark paces slowly along the row of desks with the phone pressed to his ear, his free hand chopping the air on each point he makes",
  "WS", "eye", "track", "morning", False, False,
  "перевозчик разводит руками по телефону — запасной машины у него в этом городе просто нет.",
  "the man takes two slow steps along the desks, his free hand chopping the air as he talks"),
 ("A0_SH07", "MARK_MAIN", "office_openspace",
  "Mark wedges the phone between ear and shoulder and writes a phone number on his own palm with a ballpoint pen, eyes fixed ahead",
  "MCU", "eye", "static", "morning", False, False,
  "ты вспоминаешь, что мимо того места каждое утро идёт порожний рефрижератор молочного комбината.",
  "he wedges the phone between ear and shoulder and writes a number across his palm"),
 ("A0_SH08", "MARK_MAIN", None,
  "his own hands in frame, one thumb dialling a number on a phone while the other hand flattens the notebook page against a knee",
  "POV", "pov", "static", "morning", False, False,
  "два звонка, один встречный водитель и один знакомый логист — и перегруз назначен прямо на обочине трассы.",
  "the thumb dials the number while the other hand presses the notebook page flat"),
 ("A0_SH09", None, "office_openspace",
  "a round office wall clock reading twelve minutes past nine, a strip of pale window light across its face",
  "ECU", "eye", "static", "morning", False, False,
  "в девять двенадцать водитель пишет, что паллеты переехали в чужой рефрижератор целыми.",
  "the second hand sweeps steadily around the clock face as the window light creeps"),
 ("A0_SH10", None, "factory_yard",
  "a white refrigerated truck reversing toward the loading ramp, its reversing lights on, the dock door rolled up ready",
  "WS", "high", "static", "morning", False, False,
  "в десять тридцать восемь белый рефрижератор сдаёт задом к рампе твоей фабрики.",
  "the white truck eases backwards toward the ramp, its reversing lights blinking against the grey morning"),
 ("A0_SH11", ("MARK_MAIN", "NINA_BASE"), "office_openspace",
  "Mark and Nina stand at the tall window looking down at the yard, Nina glancing up at Mark with open relief, Mark's hands in his trouser pockets",
  "MS", "eye", "static", "morning", False, False,
  "нина смотрит на тебя так, будто ты вытащил эту фуру из кювета руками.",
  "the young woman glances up at the man and back down to the yard, her shoulders easing"),
 ("A0_SH12", "MARK_MAIN", "office_openspace",
  "Mark wipes the red marker circle from the whiteboard with one slow stroke of an eraser sponge, his face routine and unimpressed",
  "MCU", "eye", "static", "morning", False, False,
  "ты стираешь с доски красный кружок, и утро снова становится обычным утром.",
  "his hand wipes the red circle from the whiteboard in one unhurried stroke"),
 ("A0_SH13", "MARK_MAIN", "office_openspace",
  "Mark's calm tired face looking slightly past the lens, the green striped tie neat at his collar, desks soft behind him",
  "CU", "eye", "push_in", "morning", False, True,
  "девятнадцать лет подряд ты человек, который решает всё за двадцать минут.",
  "the man holds the lens with a steady gaze and gives one small settled nod"),
 ("A0_SH14", "MARK_MAIN", "office_openspace",
  "Mark from directly behind at the tall window, shoulders square, the factory yard and the white truck far below him",
  "BACK", "eye", "static", "morning", False, False,
  "останься до конца и подпишись — я расскажу, как ты будешь уходить на эту работу даже после того, как она исчезнет.",
  "the man stands motionless at the window while a forklift crawls across the yard far below"),
]

A1 = [
 ("A1_SH01", None, "factory_yard",
  "the open gates of a furniture factory on a summer morning of two thousand seven, an old banner over the entrance, sunlight on the concrete",
  "EWS", "eye", "static", "day", True, False,
  "в две тысячи седьмом тебе двадцать пять, и ты первый раз проходишь эти ворота насквозь.",
  "pigeon shadows flick across the sunlit concrete and dust drifts in the warm morning air"),
 ("A1_SH02", None, None,
  "a stiff new brown leather briefcase standing on a kitchen table amid folded tissue paper, its two brass locks bright and untouched",
  "INSERT", "eye", "static", "day", False, False,
  "утром отец ставит перед тобой новый портфель и говорит, что у мужика два инструмента — слово и портфель.",
  "lamplight glints on the two brass locks as the tissue paper settles around the standing briefcase",
  "BRIEFCASE"),
 ("A1_SH03", "MARK_YOUNG", "flat_kitchen",
  "young Mark presses both brass locks of the new briefcase with his thumbs, the flap lifting a finger's width, his face lit with the first pride of it",
  "MCU", "eye", "static", "day", False, True,
  "два латунных замка щёлкают под твоими пальцами — клац-клац — и этот звук станет твоим будильником на девятнадцать лет.",
  "his thumbs press the two brass locks and the briefcase flap lifts a finger's width",
  "BRIEFCASE"),
 ("A1_SH04", "MARK_YOUNG", "office_openspace",
  "young Mark walks between the rows of desks carrying the briefcase in one hand, his boxy suit a size too big, morning light down the office",
  "WS", "low", "track", "day", False, False,
  "твой первый стол — у самого окна, и телефон на нём начинает звонить уже в девять утра.",
  "the young man walks steadily up the aisle between desks, the briefcase swinging slightly at his side"),
 ("A1_SH05", "MARK_YOUNG", None,
  "his own young hands in frame sorting carbon-copy delivery sheets beside a corded phone, a pen cap chewed at one end",
  "POV", "pov", "static", "day", False, False,
  "ты учишься находить вагон досок за три часа и грузовик стекла за сутки.",
  "the hands shuffle the carbon sheets into two piles and reach for the corded phone"),
 ("A1_SH06", None, None,
  "two hands over a lace tablecloth, a man's hand in a suit sleeve sliding a thin gold ring onto a woman's finger, festive glasses blurred behind",
  "ECU", "eye", "static", "day", False, False,
  "в две тысячи девятом ты надеваешь кольцо на руку лены, держа телефон отдела в кармане пиджака.",
  "the man's hand slides the thin ring slowly onto her finger and both hands settle together"),
 ("A1_SH07", "MARK_YOUNG", "flat_kitchen",
  "young Mark stands at the kitchen window rocking a swaddled newborn in both arms, his head bent low over the bundle",
  "MS", "eye", "static", "day", False, False,
  "в две тысячи одиннадцатом рождается даша, и ты впервые держишь её, как хрустальную.",
  "the man sways his weight gently from foot to foot, rocking the small bundle at the window"),
 ("A1_SH08", None, None,
  "a rectangular plastic lunch container with a lilac lid on a kitchen counter, a fork strapped to its side with an elastic band, a folded note under it",
  "INSERT", "eye", "static", "day", False, False,
  "лена заводит правило — каждое утро в твоём портфеле контейнер с обедом и вилка на резинке.",
  "steam from an unseen kettle drifts across the counter past the waiting lunch container",
  "LUNCHBOX"),
 ("A1_SH09", "MARK_YOUNG", "bus_stop",
  "young Mark stands at the bus shelter with the briefcase held in front of him in both hands, leaning to look up the avenue for the bus",
  "WS", "eye", "static", "morning", False, False,
  "маршрут один и тот же — остановка, восемь остановок до фабрики, турникет, второй этаж.",
  "the young man leans out past the shelter glass to look up the avenue and rocks back on his heels"),
 ("A1_SH10", "MARK_MAIN", "flat_hall",
  "Mark, older now with grey temples, straightens the same green striped tie in the hallway mirror with a slow habitual motion, chin lifted",
  "MCU", "eye", "static", "morning", False, False,
  "годы меняют твоё лицо и седят виски, но галстук в косую полоску остаётся тот же.",
  "the man straightens the striped tie in one slow habitual motion and lifts his chin at the mirror"),
 ("A1_SH11", ("LENA_BASE", "MARK_MAIN"), "flat_hall",
  "Lena reaches up and smooths the collar of Mark's grey jacket with both hands while he stands still and lets her, the hallway mirror behind them",
  "OTS", "over", "static", "morning", False, False,
  "каждое утро лена поправляет тебе воротник, хотя воротник и так в полном порядке.",
  "her hands smooth the jacket collar flat and pat it once while the man stands still"),
 ("A1_SH12", None, None,
  "the two brass locks of the worn brown briefcase snapping shut, seen from directly above, the leather around them polished pale by years of thumbs",
  "ECU", "top", "static", "morning", False, True,
  "клац-клац — и ты уходишь, и так шесть тысяч девятьсот раз подряд.",
  "both brass locks snap down one after the other under the pressing thumbs",
  "BRIEFCASE"),
 ("A1_SH13", None, "bus_stop",
  "a wide avenue in morning light, a bus pulling away from the glass shelter, new tower blocks rising behind old five-storey houses",
  "EWS", "high", "pan_right", "morning", True, False,
  "город вокруг маршрута перестраивается трижды, а сам маршрут не меняется ни на одну остановку.",
  "the bus pulls away from the shelter and morning traffic flows steadily along the avenue"),
 ("A1_SH14", ("MARK_MAIN", "NINA_BASE"), "office_openspace",
  "Mark stands at the whiteboard tapping a schedule line with a marker while Nina beside him writes fast in a notebook, both in profile to the camera",
  "MS", "eye", "static", "day", False, False,
  "ты вырастаешь до начальника отдела снабжения и учишь молодых, как звучит уверенный голос по телефону.",
  "the man taps the whiteboard twice with the marker and the young woman writes quickly beside him"),
 ("A1_SH15", "MARK_MAIN", "office_openspace",
  "Mark's face in thought at his desk, eyes down on papers, the green striped tie loosened half a knot, afternoon light across him",
  "CU", "eye", "push_in", "day", False, True,
  "на вопрос «кто ты» ты давно отвечаешь должностью, а не именем.",
  "his eyes lift slowly from the papers to the middle distance and hold there"),
 ("A1_SH16", "MARK_MAIN", "factory_yard",
  "Mark walks out through the factory gates at dusk, small in the frame, the briefcase in one hand, warm windows lit behind him",
  "WS", "eye", "pull_out", "evening", False, False,
  "девятнадцать лет подряд фабрика каждый вечер отпускает тебя домой, и ты уверен, что так будет всегда.",
  "the man walks away from the lit gates with an even unhurried stride, the briefcase swinging low"),
]

A2 = [
 ("A2_SH01", None, "office_lobby",
  "the factory administration lobby with three steel turnstiles, a new large portrait frame leaning against the reception desk, waiting to be hung",
  "EWS", "low", "static", "day", True, False,
  "в феврале на фабрику приходит новый управляющий директор, и ему тридцать три.",
  "a strip light flickers once over the turnstiles and settles into a steady hum of glow"),
 ("A2_SH02", "VADIM_BASE", "office_openspace",
  "Vadim walks briskly between the desks in an unbuttoned wool coat, eyes down on a tablet in one hand, the other hand loose at his side",
  "MS", "eye", "track", "day", False, False,
  "вадим проходит по опенспейсу, не снимая пальто, и смотрит не на людей, а в планшет.",
  "the young director strides between the desks, his coat hem swinging, his eyes fixed on the tablet"),
 ("A2_SH03", None, None,
  "a bulky black smartwatch on a wrist below a crisp navy suit cuff, the screen lit with a notification, a tablet edge in the same hand",
  "ECU", "eye", "static", "day", False, False,
  "его массивные смарт-часы вибрируют каждые несколько минут, и он всегда отвечает им первым.",
  "the smartwatch screen lights up and the wrist turns slightly toward it"),
 ("A2_SH04", "VADIM_BASE", "meeting_room",
  "Vadim stands at the wall screen beside a slide of falling cost curves, one arm extended at the chart, the backs of seated heads soft in the foreground",
  "WS", "eye", "static", "day", False, False,
  "на общем собрании слайд называется «оптимизация закупочного контура», и слово «аутсорс» звучит шесть раз.",
  "the young director sweeps his extended hand along the falling curve on the screen",
  None, "crowd"),
 ("A2_SH05", "MARK_MAIN", "meeting_room",
  "Mark listens with his arms folded and his head tilted a degree, a patient half-smile of a man who has outlasted four directors",
  "MCU", "eye", "static", "day", False, False,
  "ты слушаешь и почти жалеешь молодого — он же ещё просто не знает, как тут всё устроено.",
  "the man's half-smile fades by a fraction and his fingers tighten on his folded sleeve"),
 ("A2_SH06", ("NINA_BASE", "MARK_MAIN"), "office_openspace",
  "Nina leans across from her desk toward Mark, one hand shielding the side of her mouth, Mark bending an ear to her while his eyes stay on his papers",
  "MS", "eye", "static", "day", False, False,
  "нина шепчет тебе, что кадровикам заказали списки отделов с окладами выше ста тысяч.",
  "the young woman leans in behind her shielding hand and the man tilts his ear toward her"),
 ("A2_SH07", None, "office_openspace",
  "a laser printer tray with a fresh stack of stapled tables, the top sheet showing dense rows of names and salary columns",
  "ECU", "high", "static", "day", False, False,
  "принтер в углу выплёвывает таблицу, где твоя фамилия стоит четвёртой сверху.",
  "a warm printed sheet slides out onto the tray and the stack settles under it"),
 ("A2_SH08", "MARK_MAIN", "office_openspace",
  "Mark leans back in his chair with both hands laced behind his head, looking at the whiteboard of schedules like a general at a map",
  "MS", "eye", "static", "day", False, False,
  "ты успокаиваешь себя просто — без тебя линия встанет, а этого никто здесь не допустит.",
  "the man rocks his chair back a few degrees and laces his hands behind his head"),
 ("A2_SH09", None, "factory_yard",
  "the factory yard under thin march light, one box truck at the ramp where three used to queue, tyre tracks in slush",
  "WS", "high", "static", "day", True, False,
  "поставки в марте идут ровно, и по двору пока никак нельзя сказать, что что-то кончается.",
  "thin slush water trickles along the tyre tracks and steam rises off the truck bonnet"),
 ("A2_SH10", ("VADIM_BASE", "MARK_MAIN"), "office_lobby",
  "Vadim and Mark stand mid-conversation by the turnstiles, Vadim glancing at his smartwatch as he talks, Mark half a head taller and very still",
  "MCU", "eye", "static", "day", False, False,
  "в коридоре вадим спрашивает, сколько лет ты на этом месте, и кивает быстрее, чем ты договариваешь.",
  "the younger man nods twice in quick succession while his wrist turns up toward the smartwatch"),
 ("A2_SH11", "MARK_MAIN", "office_lobby",
  "Mark's face a moment after the conversation, the polite mask still on but the eyes gone watchful, lobby light flat on him",
  "CU", "eye", "push_in", "day", False, False,
  "этот быстрый кивок короче любого выговора, и ты запомнишь его на всю жизнь.",
  "the polite smile drains slowly from the man's face leaving only the watchful eyes"),
 ("A2_SH12", "MARK_MAIN", None,
  "his own hand in frame holding a phone with a calendar screen, a meeting slot with an empty subject line on friday at fifteen hundred",
  "POV", "pov", "static", "day", False, True,
  "в четверг в твоём календаре появляется встреча без темы — пятница, пятнадцать ноль-ноль, переговорная.",
  "the thumb scrolls the calendar up and stops dead on the empty meeting slot"),
 ("A2_SH13", None, "office_lobby",
  "a steel turnstile arm with a small reader glowing green, a pass card on a blue lanyard pressed against it",
  "ECU", "eye", "static", "morning", False, False,
  "в пятницу утром турникет пищит зелёным и пропускает тебя, как пропускал девятнадцать лет.",
  "the reader light blinks green and the turnstile arm gives way a few degrees"),
 ("A2_SH14", ("MARK_MAIN", "NINA_BASE"), "office_openspace",
  "Mark hands Nina a thick folder across the desks, she takes it with both hands, his face calm, her face uncertain",
  "MS", "eye", "static", "day", False, False,
  "ты отдаёшь нине график поставок на май, который уже никому не понадобится.",
  "the folder passes from his hand into her two hands and she hugs it to her chest"),
 ("A2_SH15", "MARK_MAIN", "meeting_room",
  "Mark stands at the glass door of the meeting room with one hand on the handle, the bright room beyond him, his reflection faint in the glass",
  "WS", "eye", "static", "day", False, False,
  "в пятнадцать ноль-ноль ты открываешь стеклянную дверь с тем же лицом, с каким открывал её сотни раз.",
  "the man pushes the glass door and it swings open a slow quarter of its arc"),
 ("A2_SH16", None, "meeting_room",
  "a chrome door handle of a glass door in tight close-up, a man's hand releasing it, the bright blurred room beyond the pane",
  "ECU", "eye", "static", "day", False, True,
  "щёлкает дверная ручка, и это единственный звук, который ты запомнишь из всего этого дня.",
  "the hand slides off the chrome handle and the glass door settles shut behind it"),
]

if __name__ == "__main__":
    seed_act("A0", PAL_A0, A0)
    seed_act("A1", PAL_A1, A1)
    seed_act("A2", PAL_A2, A2)
