# -*- coding: utf-8 -*-
"""squeeze_out shots: A0 (night site crisis), A1 (who you are), A2 (the merger)."""
from _squeeze_out_engine import seed_act

PAL_A0 = "deep night blue, sodium work lights, wet concrete sheen"
PAL_A1 = "warm bureau daylight, paper and wood tones, soft window light"
PAL_A2 = "renovated white light, fresh paint tones, cool glass accents"

A0 = [
 ("A0_SH01", None, "site_bridge",
  "a road-interchange construction site at night, a concrete pylon in crossed sodium work lights, the unfinished span black against the sky",
  "EWS", "low", "static", "night", True, False,
  "в час ночи звонит прораб — у третьей опоры не сходятся высотные отметки, утром монтаж пролёта.",
  "the crossed work lights hum over the pylon while a loose tarpaulin edge lifts and falls"),
 ("A0_SH02", "ANTON_BASE", "home_hall",
  "Anton in the dark hallway with the phone at his ear, already pulling his coat off the rack with one hand, his glasses still on his forehead",
  "MCU", "eye", "static", "night", False, False,
  "если ошибка в проекте, стройка встанет, и каждый её день съест примерно два миллиона.",
  "he pulls the coat off the rack in one motion while the phone stays pressed to his ear"),
 ("A0_SH03", "ANTON_BASE", "archive_room",
  "Anton rolls out an old tracing-paper plan on the wide layout table under a single work lamp, weighting its corners with whatever is near",
  "WS", "high", "static", "night", False, False,
  "в архиве ты поднимаешь кальки двенадцатого года — свои собственные, с твоим штампом.",
  "the tracing paper unrolls under his spreading hands and settles as he weights the corners"),
 ("A0_SH04", "ANTON_BASE", None,
  "his own hands walking a ruler and the mechanical pencil across benchmark tables, a calculator beside a mug of cold tea",
  "POV", "pov", "static", "night", False, False,
  "ты сверяешь реперные отметки строку за строкой, как сверял их пятнадцать лет подряд.",
  "the pencil tip walks down the benchmark column line by line and stops on one figure"),
 ("A0_SH05", None, None,
  "a benchmark table close-up with one elevation figure circled twice in pencil, a discrepancy note in the margin",
  "ECU", "eye", "static", "night", False, False,
  "к четырём утра ты находишь её — репер сбит при переносе, это геодезия, не проект.",
  "the pencil circles the elevation figure a second time and underlines the margin note"),
 ("A0_SH06", "ANTON_BASE", "archive_room",
  "Anton leans back from the layout table taking off his glasses, rubbing the bridge of his nose, relief loosening his shoulders",
  "MS", "eye", "static", "night", False, False,
  "проект чист, и это значит, что монтаж можно начинать по графику.",
  "he leans back off the table and his shoulders drop as the glasses come off"),
 ("A0_SH07", "ANTON_BASE", "site_bridge",
  "Anton in a hard hat and his knitted vest at dawn among rebar cages, showing a marked plan to someone whose high-vis shoulder edges the frame",
  "MS", "eye", "static", "morning", False, False,
  "в семь утра ты стоишь у третьей опоры и показываешь геодезистам их же сбитый репер.",
  "his finger taps the marked point on the plan and sweeps toward the pylon base"),
 ("A0_SH08", None, "site_bridge",
  "the crane over the interchange span beginning to turn in first light, cables tensioning, workers small below",
  "WS", "low", "tilt_up", "morning", False, False,
  "монтаж начинается в восемь ноль-ноль, минута в минуту, как записано в графике.",
  "the crane arm turns slowly against the dawn sky as the cables draw taut",
  None, "crowd"),
 ("A0_SH09", None, None,
  "a mechanical pencil being clipped back into a knitted vest pocket, concrete dust on the vest wool",
  "ECU", "eye", "static", "morning", False, False,
  "ошибка была не твоя, но нашёл её ты — это и есть твоя работа.",
  "the pencil slides into the vest pocket and the clip snaps home"),
 ("A0_SH10", "ANTON_BASE", "site_bridge",
  "Anton walks away from the site gate against the flow of arriving workers, hard hat under his arm, morning sun behind him",
  "WS", "eye", "track", "morning", False, False,
  "домой ты едешь спать три часа, потому что в полдень планёрка по новому мосту.",
  "he walks against the stream of arriving figures, the hard hat swinging under his arm",
  None, "crowd"),
 ("A0_SH11", "ANTON_BASE", "bureau_open",
  "Anton at his drawing station in the bureau hall, colleagues' heads turned to him as he tells the night story with dry economy",
  "MS", "eye", "static", "day", False, False,
  "в бюро эта ночь станет байкой на неделю, а для тебя она — обычный вторник.",
  "his hand sketches the pylon in the air in two dry strokes as heads lean in",
  None, "crowd"),
 ("A0_SH12", None, None,
  "a white mug with a faded blue logo and an award year standing on a desk among pencil shavings and a roll of plans",
  "INSERT", "eye", "static", "day", False, False,
  "кружку «лучшему инженеру» тебе вручили при всех, и с тех пор она не мылась чужими руками.",
  "steam rises off the mug between the pencil shavings and the rolled plans",
  "MUG"),
 ("A0_SH13", "ANTON_BASE", "bureau_open",
  "Anton's calm face with the heavy glasses catching window light, a man exactly where he belongs",
  "CU", "eye", "push_in", "day", False, True,
  "пятнадцать лет подряд это место держится в том числе на тебе, и все это знают.",
  "his eyes settle on the middle distance with the ease of a man at home"),
 ("A0_SH14", "ANTON_BASE", "bureau_open",
  "Anton from behind at the window overlooking the street, hands in pockets, rolled plans on the sill beside him",
  "BACK", "eye", "static", "day", False, False,
  "останься до конца и подпишись — я расскажу, как человека увольняют, ни разу не произнеся слово «увольнение».",
  "he stands motionless at the window while traffic drifts along the street below"),
]

A1 = [
 ("A1_SH01", None, "street_bureau",
  "the bureau entrance with granite steps and an old poplar, a brass plaque by the door, morning buses passing",
  "EWS", "eye", "static", "morning", True, False,
  "проектное бюро занимает этот дом дольше, чем ты живёшь на свете.",
  "poplar shade sways slowly across the granite steps as a bus passes"),
 ("A1_SH02", "ANTON_BASE", "bureau_open",
  "Anton adjusts the levers of his worn ergonomic chair with a mechanic's precision before sitting, one hand testing the backrest give",
  "MS", "eye", "static", "morning", False, True,
  "твоё кресло настроено под твою спину годами, как инструмент — под руку.",
  "his hand works the chair lever twice and tests the backrest with a push",
  "CHAIR"),
 ("A1_SH03", None, None,
  "the worn office chair alone in morning light, its seat moulded to one silhouette, armrests polished pale, insulating tape on the lift",
  "INSERT", "eye", "static", "morning", False, False,
  "по вмятине на сиденье можно снять твою мерку точнее, чем в ателье.",
  "dust motes drift through the light around the still, moulded chair",
  "CHAIR"),
 ("A1_SH04", "ANTON_BASE", "bureau_open",
  "Anton draws a long clean line on a wide monitor with a stylus, the interchange model rotating on a second screen",
  "MCU", "eye", "static", "day", False, False,
  "ты ведёшь развязки — узлы, где город либо едет, либо стоит.",
  "the stylus draws one long clean arc and the interchange model turns to meet it"),
 ("A1_SH05", None, "site_bridge",
  "a finished road interchange from high above at golden hour, streams of cars flowing over the overpass in both directions",
  "EWS", "high", "static", "evening", True, False,
  "твоя эстакада на юге пропускает две тысячи четыреста машин в час, и город этого не замечает — значит, она работает.",
  "twin streams of headlights and tail lights flow steadily over the curved overpass",
  None, "crowd"),
 ("A1_SH06", ("PASHA_BASE", "ANTON_BASE"), "bureau_open",
  "Pasha perches on the edge of Anton's desk with his bicycle helmet under one arm, mid-joke, Anton laughing over his shoulder from the chair",
  "MS", "eye", "static", "day", False, False,
  "паша сидит на краю твоего стола пятнадцать лет, и охрана давно считает это мебелью.",
  "the curly-haired man rocks on the desk edge with his joke while the other laughs",
  "HELMET"),
 ("A1_SH07", "ANTON_BASE", None,
  "his own hands in frame marking a young colleague's drawing with the mechanical pencil, patient small corrections",
  "POV", "pov", "static", "day", False, False,
  "молодые носят тебе чертежи на проверку, и ты правишь их мягче, чем правили тебя.",
  "the pencil makes three small patient corrections along the drawn edge"),
 ("A1_SH08", ("MARINA_BASE", "TIMA_BASE"), "home_kitchen",
  "Marina ladles soup while Tima marches the rubber dinosaur along the table edge toward the bread, evening lamplight warm",
  "WS", "eye", "static", "evening", False, False,
  "дома марина делит суп, а тима ведёт динозавра через стол в обход хлебницы.",
  "the small dinosaur hops along the table edge in the boy's fist while soup steams",
  "DINO"),
 ("A1_SH09", ("ANTON_BASE", "TIMA_BASE"), "child_room",
  "Anton kneels by the low bed helping Tima stand the dinosaur on a block tower, both heads bent together under the rocket lamp",
  "MCU", "eye", "static", "evening", False, False,
  "перед сном вы с тимой строите динозавру эстакаду из кубиков — семейный подряд.",
  "four hands steady the block tower as the dinosaur settles on its summit",
  "DINO"),
 ("A1_SH10", None, None,
  "the engineer mug being rinsed and set upside down on a drying rack by a careful male hand, evening window light",
  "ECU", "eye", "static", "evening", False, False,
  "кружку две тысячи пятнадцатого года ты моешь сам — примета, а не гигиена.",
  "water sheets off the upturned mug as the hand sets it carefully on the rack",
  "MUG"),
 ("A1_SH11", "ANTON_BASE", "bureau_open",
  "Anton pins a printed interchange sheet to the wall rail by his desk, stepping back half a pace to check its level",
  "MS", "eye", "static", "day", False, False,
  "распечатку новой развязки ты вешаешь у стола — не для гостей, для себя.",
  "he pins the sheet, steps back half a pace and nudges one corner level",
  "BLUEPRINT"),
 ("A1_SH12", "MARINA_BASE", "home_kitchen",
  "Marina laughs at the table with her chin on her hand, her gold hoop earrings catching the lamp, a family evening in mid-flow",
  "CU", "eye", "static", "evening", False, False,
  "марина говорит, что замужем за бюро с пристройкой в виде тебя, и это пока шутка.",
  "her chin settles on her hand and the small hoops swing once with her laugh"),
 ("A1_SH13", None, "bureau_open",
  "the bureau hall at lunch, chess played on a drawing table, someone watering a fig plant, rolled plans everywhere",
  "WS", "eye", "pan_right", "day", True, False,
  "в обед в зале играют в шахматы на кульмане, и никто никуда не спешит.",
  "a chess piece moves on the drawing table while the fig leaves sway under the watering can",
  None, "crowd"),
 ("A1_SH14", "ANTON_BASE", "meeting_bureau",
  "Anton reports at the long table gesturing at a bridge photo on the wall, senior faces nodding along, papers relaxed",
  "MCU", "eye", "static", "day", False, False,
  "на техсоветах твоё слово весит столько, сколько должно весить слово главного по узлам.",
  "his open hand turns toward the framed bridge photo and the heads nod along",
  None, "crowd"),
 ("A1_SH15", "ANTON_BASE", "bureau_open",
  "Anton's content face at his station in late light, glasses pushed up into his hair, the day's work done",
  "CU", "eye", "push_in", "evening", False, True,
  "ты не строишь карьеру — ты строишь развязки, и тебе казалось, что это одно и то же.",
  "his eyes rest on the finished drawing and the glasses slide down from his hair"),
 ("A1_SH16", None, "street_bureau",
  "the bureau windows lit warm at dusk from across the street, silhouettes moving between drawing stations",
  "WS", "low", "static", "evening", True, False,
  "так выглядит место, которое ты считаешь своим, за месяц до слияния.",
  "warm window light flickers as silhouettes cross between the drawing stations",
  None, "crowd"),
]

A2 = [
 ("A2_SH01", None, "bureau_open",
  "the bureau hall mid-renovation, floor protection film over the parquet, new white desks stacked in factory wrap",
  "WS", "eye", "static", "day", True, False,
  "слияние приходит как ремонт — плёнка на паркете, новые белые столы в заводской упаковке.",
  "the protective film ripples along the floor as a draught runs the length of the hall"),
 ("A2_SH02", "ZHANNA_BASE", "bureau_open",
  "Zhanna walks the hall with a folder held like a clipboard, her red lacquered pen ticking as she passes the drawing stations",
  "MS", "eye", "track", "day", False, False,
  "жанна приходит из головной компании со словом «аудит» и красной лаковой ручкой.",
  "the red pen ticks a line on her folder at each station she passes"),
 ("A2_SH03", None, None,
  "a red lacquered pen making a small tick against a printed staff list, manicured fingers precise",
  "ECU", "eye", "static", "day", False, False,
  "галочка у неё короткая, как выстрел, и ставит она их только напротив старых фамилий.",
  "the red pen sets one short precise tick and moves down the list"),
 ("A2_SH04", "ZHANNA_BASE", "meeting_bureau",
  "Zhanna presents at the long table, a slide reading as functions audit behind her, her posture perfect, the room's shoulders tense",
  "WS", "eye", "static", "day", False, False,
  "на общем собрании она говорит «дублирование функций» одиннадцать раз — ты считал.",
  "her hand slices small horizontal cuts in the air on each repeated point",
  None, "crowd"),
 ("A2_SH05", "ANTON_BASE", "meeting_bureau",
  "Anton listens with his arms crossed over the knitted vest, the engineer's face of a man waiting for the technical part",
  "MCU", "eye", "static", "day", False, False,
  "ты ждёшь, когда начнётся инженерия, а инженерия в этой презентации не начинается.",
  "his crossed arms settle heavier as his eyes track the slide change"),
 ("A2_SH06", None, "bureau_open",
  "young unfamiliar specialists unpacking at the new white desks, monitors still in foam, branded notebooks aligned",
  "WS", "eye", "static", "day", False, False,
  "к новым столам приходят новые люди — вежливые, быстрые, из головной компании.",
  "foam packing slides off a monitor as the new desks fill in even order",
  None, "crowd"),
 ("A2_SH07", ("PASHA_BASE", "ANTON_BASE"), "bureau_open",
  "Pasha leans over Anton's shoulder nodding toward the new desks, speaking low, his helmet dangling from two fingers",
  "OTS", "over", "static", "day", False, False,
  "паша говорит тихо — «смотри, у них ни одного рулона, одни презентации».",
  "his helmet swings from two fingers as he nods toward the far white desks",
  "HELMET"),
 ("A2_SH08", "ANTON_BASE", "bureau_open",
  "Anton waves it off with a half-smile, turning back to his drawing, the stylus already reaching for the line",
  "CU", "eye", "static", "day", False, False,
  "ты отмахиваешься — развязки сами себя не спроектируют, а всё остальное шум.",
  "his hand waves the worry off and returns the stylus to the waiting line"),
 ("A2_SH09", None, "director_office",
  "the renovated director office, a city map with pinned flags, coloured folders in a wall organiser, a glass desk bare of paper",
  "WS", "eye", "static", "day", True, False,
  "в кабинете на карте города появляются флажки — по одному на каждый «оптимизируемый» отдел.",
  "a pinned flag trembles on the city map as the door closes somewhere off frame"),
 ("A2_SH10", ("ZHANNA_BASE", "ANTON_BASE"), "director_office",
  "Zhanna across the glass desk from Anton, her fingers laced over his printed project list, her smile administrative",
  "MS", "eye", "static", "day", False, False,
  "жанна хвалит твой опыт так, как хвалят здание перед реконструкцией.",
  "her laced fingers settle flat on his project list as the smile holds"),
 ("A2_SH11", "ANTON_BASE", "director_office",
  "Anton's face across the desk, politeness over the first cold notch of alarm, window light hard on his glasses",
  "CU", "eye", "push_in", "day", False, True,
  "слово «пока» в её фразе «пока всё по-прежнему» ты услышишь ночью, задним числом.",
  "light shifts on his glasses as his head tilts back a wary degree"),
 ("A2_SH12", "ANTON_BASE", None,
  "his own hand scrolling a phone org-chart, his box moved one level down under an unfamiliar name",
  "POV", "pov", "static", "evening", False, False,
  "в новой оргсхеме твой квадратик съезжает на уровень вниз, под фамилию, которую ты видишь в первый раз.",
  "the thumb stops the scroll on the lowered box and the screen glow steadies"),
 ("A2_SH13", None, None,
  "a bureau anniversary group photo on the wall, half the faces in it circled by reflection glare from new white light",
  "ECU", "eye", "static", "evening", False, False,
  "на юбилейной фотографии бюро половина людей уже тихо присматривает себе другое место.",
  "white light glare slides across the group photo glass as the hall lights switch bands"),
 ("A2_SH14", ("MARINA_BASE", "ANTON_BASE"), "home_kitchen",
  "Marina sets tea in front of Anton who retells the day with ironic gestures, his glasses on the table between them",
  "MS", "eye", "static", "evening", False, False,
  "дома ты пересказываешь «аудит» в лицах, и марина смеётся чуть позже, чем обычно.",
  "his ironic gesture builds the scene in the air while she sets the tea down slowly"),
 ("A2_SH15", "MARINA_BASE", "home_kitchen",
  "Marina's face listening over her cup, the laugh gone, a mother's early-warning system working behind her eyes",
  "CU", "eye", "static", "evening", False, False,
  "она спрашивает один раз — «а тебя это касается?» — и ты отвечаешь «меня — нет».",
  "her eyes hold steady over the cup rim through his answer"),
 ("A2_SH16", None, "bureau_open",
  "the hall at night, old drawing stations in the dark half, new white desks glowing under their own strip of light",
  "EWS", "eye", "static", "night", True, False,
  "зал теперь освещён наполовину, и граница света проходит точно по границе команд.",
  "the strip light over the new desks flickers once and steadies against the dark half"),
]

if __name__ == "__main__":
    seed_act("A0", PAL_A0, A0)
    seed_act("A1", PAL_A1, A1)
    seed_act("A2", PAL_A2, A2)
