# -*- coding: utf-8 -*-
"""Seed CH11 — Слухи, репутация (HEROINE_YOUNG). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "whispers and reputation in the tight GDR world, judged but defiant, cold grey daylight"
SHOTS = [
 ("CH11_SH01", "HEROINE_YOUNG", "street_east",
  "medium of the heroine walking a grey street, neighbours turning away",
  "MS","eye","static","gdr_day",False,False,
  "к двадцати о тебе уже судачит весь район, дурная слава бежит далеко впереди тебя."),
 ("CH11_SH02", None, "street_east",
  "close-up of faceless neighbour women whispering, lips pursed",
  "CU","eye","static","gdr_day",True,False,
  "соседки поджимают губы, мужья отводят глаза, а матери уводят сыновей от тебя подальше."),
 ("CH11_SH03", "HEROINE_YOUNG", "factory",
  "medium close-up of the heroine on the factory floor, words flung at her back",
  "MCU","eye","static","gdr_day",False,False,
  "на заводе тебя в спину зовут гулящей, и эти слова липнут к тебе, как мазут."),
 ("CH11_SH04", "HEROINE_YOUNG", "factory",
  "close-up of her chin held high, defiant",
  "CU","eye","static","gdr_day",False,False,
  "но ты держишь голову высоко, пусть завидуют, думаешь ты, просто завидуют моей свободе."),
 ("CH11_SH05", None, "kneipe",
  "wide of a smoky pub, men exchanging knowing glances",
  "WS","eye","static","night",True,False,
  "в пивной мужчины перемигиваются, она доступная, говорят они, и всё равно тянутся к тебе."),
 ("CH11_SH06", "HEROINE_YOUNG", "street_east",
  "medium close-up of her hiding the hurt",
  "MCU","eye","static","gdr_day",False,False,
  "тебе больно от слухов, но боль ты глушишь привычным способом, очередным чужим взглядом."),
 ("CH11_SH07", None, "street_east",
  "close-up of a faceless man's lingering gaze",
  "CU","eye","static","gdr_day",True,False,
  "ведь стоит кому-то снова тебя захотеть, и на короткий миг ты опять чего-то стоишь."),
 ("CH11_SH08", "HEROINE_YOUNG", "her_room",
  "close-up of the heroine alone at night, the words echoing",
  "CU","eye","static","night",False,False,
  "а ночью, оставшись одна, ты снова и снова слышишь эти слова, гулящая, пустая, дрянь."),
 ("CH11_SH09", "HEROINE_YOUNG", "her_room",
  "medium close-up of her bewilderment",
  "MCU","eye","static","night",False,False,
  "и ты не понимаешь, почему то, что даёт тебе тепло, другие зовут таким грязным словом."),
 ("CH11_SH10", None, "her_room",
  "extreme close-up of the cold empty pillow",
  "ECU","eye","static","night",True,True,
  "ты убеждаешь себя, что счастлива и свободна, но подушка рядом всё так же холодна."),
 ("CH11_SH11", None, "street_east",
  "wide B-roll of a grey East Berlin street at dusk, silent",
  "WS","eye","static","gdr_eve",True,False,""),
]
if __name__ == "__main__":
    seed_act(11, "gdr_grey", MOOD, "static", "CH11 Rumors", SHOTS)
