# -*- coding: utf-8 -*-
"""squeeze_out shots: A9 (the victory), A10 (the resignation), A11 (finale: employee, and free)."""
from _squeeze_out_engine import seed_act

PAL_A9 = "flat winter white, pale even light, thin grey shadows"
PAL_A10 = "thaw morning light, wet asphalt shine, soft clearing sky"
PAL_A11 = "clear january light, crisp snow tones, warm brick interior"

A9 = [
 ("A9_SH01", None, "bureau_open",
  "a farewell cake on a hall table, paper cups, a bouquet in cellophane, staff gathering in a loose half-circle",
  "WS", "eye", "static", "day", False, False,
  "на четвёртый год жанна уходит на повышение в головную компанию — с тортом и букетом.",
  "the loose half-circle tightens around the cake table as cups pass hand to hand",
  None, "crowd"),
 ("A9_SH02", "ZHANNA_BASE", "bureau_open",
  "Zhanna gives a gracious farewell speech beside the cake, the red pen clipped to her folder for the last time here",
  "MCU", "eye", "static", "day", False, False,
  "в прощальной речи она благодарит коллектив «за гибкость», и зал вежливо хлопает.",
  "her gracious nod sweeps the half-circle as polite applause patters",
  None, "crowd"),
 ("A9_SH03", "ANTON_BASE", "bureau_open",
  "Anton at the back of the gathering with a paper cup held untouched at his chest, his face unreadable behind the glasses",
  "MCU", "eye", "static", "day", False, False,
  "ты стоишь в заднем ряду с нетронутым стаканом и ждёшь, что почувствуешь победу.",
  "his thumb dents the paper cup rim slowly as the applause dies around him",
  None, "crowd"),
 ("A9_SH04", "ANTON_BASE", "bureau_basement",
  "Anton back at the basement desk the same afternoon, the desk unchanged, the plastic chair unchanged, the pipes unchanged",
  "WS", "eye", "static", "day", False, True,
  "жанна уехала, а подвал остался — осада кончилась, и гарнизон награждён гарнизоном.",
  "he lowers himself onto the plastic chair and the basement holds its exact stillness",
  "CHAIR"),
 ("A9_SH05", None, None,
  "the grievance notebook lying closed under the desk lamp, its rubber band snapped and retied in a knot",
  "ECU", "eye", "static", "day", False, False,
  "блокнот больше некому предъявлять — противник выбыл, не заметив твоей войны.",
  "the knotted rubber band creaks faintly as the notebook settles under the lamp",
  "NOTEBOOK"),
 ("A9_SH06", "ANTON_BASE", "bureau_open",
  "a young manager shakes Anton's hand in the hall, loud and friendly, calling him a legend of resilience to two colleagues",
  "MS", "eye", "static", "day", False, False,
  "новый руководитель жмёт тебе руку и ставит тебя в пример — «вот человек-скала, учитесь».",
  "the loud handshake pumps twice while the two colleagues nod on cue",
  None, "crowd"),
 ("A9_SH07", "ANTON_BASE", "bureau_open",
  "Anton's face during the praise, hearing the words as a diagnosis, the smile he returns costing visible effort",
  "CU", "eye", "push_in", "day", False, True,
  "тебя хвалят за то, что ты четыре года просидел в подвале, и хвалят искренне.",
  "his answering smile assembles itself piece by piece and stops short of the eyes"),
 ("A9_SH08", "ANTON_BASE", None,
  "his own hands laying out the arithmetic on a notepad: years, percentages, a small figure circled at the bottom",
  "POV", "pov", "static", "night", False, False,
  "ночью ты считаешь — четыре года, минус восемнадцать процентов, ноль новых узлов, один сын, выросший мимо.",
  "the pencil circles the small bottom figure twice and stops pressing"),
 ("A9_SH09", None, "child_room",
  "a boy's room subtly older: the dinosaur poster swapped for a space one, the rubber dinosaur on a high shelf among books",
  "WS", "eye", "static", "night", True, False,
  "динозавр переехал на верхнюю полку — тима теперь занимается космосом.",
  "the high shelf holds the small dinosaur still among the spines of thicker books"),
 ("A9_SH10", ("MARINA_BASE", "ANTON_BASE"), "home_kitchen",
  "Marina and Anton at the kitchen table with tea, older by four quiet years, a calmness between them that has been paid for",
  "MS", "eye", "static", "night", False, False,
  "марина осталась — не потому что было легко, а потому что решила остаться.",
  "their two cups steam between them as her hand turns hers a slow quarter"),
 ("A9_SH11", None, "bureau_open",
  "a new department head's silhouette at the director office door, a tablet against her hip, movers carrying in a new chair",
  "WS", "eye", "static", "day", False, False,
  "в кабинет наверху заходит новая метла — с планшетом, аудитом и своим списком.",
  "the movers angle the new chair through the door past the waiting silhouette",
  None, "crowd"),
 ("A9_SH12", "ANTON_BASE", "bureau_basement",
  "Anton listens to the ceiling where furniture is being moved overhead, dust sifting from a pipe joint",
  "MCU", "low", "static", "day", False, False,
  "по потолку подвала едет чья-то мебель, и звук этот тебе уже знаком наизусть.",
  "fine dust sifts from the pipe joint as the ceiling rumbles overhead"),
 ("A9_SH13", None, None,
  "a fresh audit questionnaire sheet in the basement in-tray, the word functions visible in its title line",
  "ECU", "eye", "static", "day", False, False,
  "в лоток входящих ложится анкета нового аудита, и первый вопрос в ней — «ваши функции?».",
  "the questionnaire sheet settles into the in-tray and its corner lifts once"),
 ("A9_SH14", "ANTON_BASE", "bureau_basement",
  "Anton reads the questionnaire holding it in both hands, and begins, very quietly, to laugh for real",
  "MCU", "eye", "static", "day", False, False,
  "ты читаешь вопрос про функции и смеёшься — впервые за четыре года по-настоящему.",
  "the sheet trembles in his hands as the quiet real laugh builds through him"),
 ("A9_SH15", "ANTON_BASE", "bureau_basement",
  "Anton stands and looks around the basement slowly, at the pipes, the calendar, the mug, a man taking final inventory",
  "WS", "eye", "static", "day", False, False,
  "смех кончается, и ты впервые видишь подвал глазами марины, паши и тимы сразу.",
  "his slow turning gaze inventories the pipes, the calendar and the desk in one pass"),
 ("A9_SH16", None, None,
  "the calendar above the desk with years of crossed squares, a hand tearing the whole page block off the wall nail",
  "ECU", "eye", "static", "day", False, False,
  "календарь с крестиками ты снимаешь целиком, не отрывая листов по одному.",
  "the whole page block comes off the nail in one pull and folds under the hand"),
 ("A9_SH17", "ANTON_BASE", "bureau_basement",
  "Anton sits down and opens a blank document, the cursor blinking in the empty white, his hands calm on the keyboard",
  "MS", "eye", "static", "day", False, False,
  "потом ты открываешь чистый лист, и курсор мигает в белом поле, как свободная касса.",
  "the cursor blinks in the empty document as his hands settle onto the keys"),
 ("A9_SH18", None, "street_bureau",
  "the bureau street in flat winter light, a thaw dripping off the signboard column, buses passing with wet flanks",
  "EWS", "eye", "static", "day", True, False,
  "за окнами тает первый большой снег — город живёт, не спрашивая ни у кого разрешения.",
  "meltwater drips steadily off the signboard while wet buses hiss past"),
]

A10 = [
 ("A10_SH01", "ANTON_BASE", None,
  "his own hands printing and signing a short application, the signature even, the date written with care",
  "POV", "pov", "static", "morning", False, True,
  "заявление по собственному занимает четыре строки, и ты пишешь его без черновика.",
  "the pen signs the short application and adds the date in careful strokes"),
 ("A10_SH02", "ANTON_BASE", "director_office",
  "Anton lays the application on the new head's desk, standing straight, his face lighter than it has looked in years",
  "MS", "eye", "static", "morning", False, False,
  "новая руководительница читает его тридцать секунд и не находит причин удерживать.",
  "the application settles on the desk and his shoulders come down easy at last"),
 ("A10_SH03", None, None,
  "the short application on a desk, a resolution scrawled diagonally in its corner in red ink",
  "ECU", "top", "static", "morning", False, False,
  "резолюция занимает угол листа, и красные чернила в ней уже чужие, новые.",
  "the red diagonal resolution dries slowly across the application corner"),
 ("A10_SH04", "ANTON_BASE", "bureau_basement",
  "Anton packs the basement desk into one box: the mug, the notebook, the rolled original print, nothing else worth taking",
  "MS", "eye", "static", "day", False, False,
  "сборы занимают одиннадцать минут — кружка, блокнот, оригинал развязки, всё.",
  "the mug and the notebook settle into the box beside the rolled print",
  "MUG"),
 ("A10_SH05", None, None,
  "the engineer mug standing alone on the emptied basement desk, deliberately left, lamplight on the chipped handle",
  "INSERT", "eye", "static", "day", False, True,
  "кружку две тысячи пятнадцатого ты в последний момент ставишь обратно — она отсюда, пусть сторожит.",
  "lamplight steadies on the lone mug as the box scrapes off the desk edge",
  "MUG"),
 ("A10_SH06", "ANTON_BASE", "bureau_open",
  "Anton crosses the bright hall with his box, and this time heads do rise from the white desks, one after another",
  "WS", "eye", "track", "day", False, False,
  "через зал ты идёшь с коробкой, и головы поднимаются — уходящих здесь провожают взглядом.",
  "heads lift from the white desks one by one as he carries the box up the aisle",
  None, "crowd"),
 ("A10_SH07", "ANTON_BASE", "street_bureau",
  "Anton on the granite steps in thaw light, box under one arm, breathing out long and slow, the poplar dripping",
  "MCU", "eye", "static", "day", False, False,
  "на крыльце ты выдыхаешь так, как не выдыхал четыре года, и воздух пахнет талым снегом.",
  "his long breath fogs and thins as meltwater ticks off the poplar above"),
 ("A10_SH08", None, "courtyard_bins",
  "the broken cast-off office chair lying on its side by the waste containers, one wheel slowly turning in the wind",
  "WS", "eye", "push_in", "day", True, True,
  "списанное кресло лежит у баков на боку, и одно колесо ещё крутится на ветру.",
  "the upturned chair wheel turns slowly to a stop by the container wall"),
 ("A10_SH09", ("MARINA_BASE", "ANTON_BASE"), "home_hall",
  "Marina opens the door to Anton with the box at midday, reads his face in one second, and pulls him in by the coat lapel",
  "MCU", "eye", "static", "day", False, False,
  "марина открывает дверь, смотрит одну секунду — и втягивает тебя в дом за лацкан.",
  "her hand closes on the coat lapel and draws him over the threshold in one pull"),
 ("A10_SH10", ("ANTON_BASE", "TIMA_BASE"), "home_kitchen",
  "Anton and Tima build a block overpass on the kitchen table in the middle of a weekday, the dinosaur presiding from the sugar bowl",
  "WS", "eye", "static", "day", False, False,
  "в среду днём вы с тимой строите эстакаду из кубиков, и никто никуда не опаздывает.",
  "four hands raise the block span while the dinosaur presides from the sugar bowl",
  "DINO"),
 ("A10_SH11", "ANTON_BASE", "home_kitchen",
  "Anton laughs at the table mid-game, glasses pushed up, and the laugh reaches his eyes with easy warmth",
  "CU", "eye", "static", "day", False, False,
  "смеяться в среду днём оказывается просто — надо только уволиться из осаждённой крепости.",
  "his laugh crinkles the corners of his eyes as the glasses ride up his hair"),
 ("A10_SH12", "ANTON_BASE", None,
  "his own hand dialling a number saved years ago, the contact photo showing a curly-haired man with a bicycle",
  "POV", "pov", "static", "evening", False, False,
  "вечером ты набираешь пашу и произносишь три слова — «стол ещё стоит?».",
  "the thumb presses the call button under the curly-haired contact photo"),
 ("A10_SH13", "PASHA_BASE", "pasha_office",
  "Pasha in his studio at dusk answers the phone, and his grin arrives before the second word is out",
  "MCU", "eye", "static", "evening", False, False,
  "паша молчит две секунды и отвечает — «стоит, но карточку я тогда выбросил, придёшь сотрудником».",
  "his grin spreads as the phone presses tighter to his ear"),
 ("A10_SH14", "ANTON_BASE", "home_kitchen",
  "Anton with the phone at his ear takes the condition on the chin, nodding slowly, his hand flat on the kitchen table",
  "CU", "eye", "static", "evening", False, False,
  "сотрудником так сотрудником — за партнёрство ты уже заплатил, просто в другую кассу.",
  "his slow nod settles the terms as his flat hand presses the table once"),
]

A11 = [
 ("A11_SH01", None, "pasha_office",
  "the small studio in january morning light, nine desks filling with people in sweaters, kettle steam, bicycle on the brick wall",
  "WS", "eye", "static", "morning", True, False,
  "в январе ты выходишь десятым в бюро на девять столов, и кофе здесь пахнет кофе.",
  "kettle steam drifts across the brick wall as sweaters settle at the mismatched desks",
  None, "crowd"),
 ("A11_SH02", "ANTON_BASE", "pasha_office",
  "Anton at his new desk unrolls the original interchange print and pins it to the brick, straightening it with one finger",
  "MS", "eye", "static", "morning", False, False,
  "оригинал развязки ты вешаешь над новым столом — со своей фамилией в штампе.",
  "his finger nudges the pinned print level against the exposed brick",
  "BLUEPRINT"),
 ("A11_SH03", ("PASHA_BASE", "ANTON_BASE"), "pasha_office",
  "Pasha drops a new project folder on Anton's desk and perches on its edge exactly as he did for fifteen years",
  "MCU", "eye", "static", "day", False, False,
  "паша садится на край твоего стола, как раньше, и стол сразу становится обжитым.",
  "the folder lands and he perches on the desk edge in the old practiced move",
  "HELMET"),
 ("A11_SH04", None, None,
  "a fresh drawing on a monitor: a small bridge over a river, clean early lines, a boy's dinosaur sticker on the monitor corner",
  "ECU", "eye", "static", "day", False, False,
  "первый твой узел здесь — мостик через речку в новом районе, и линии идут легко.",
  "the clean early lines extend across the screen under the dinosaur sticker",
  "DINO"),
 ("A11_SH05", "ANTON_BASE", "site_bridge",
  "Anton in a hard hat at a small river-bridge site, laughing with a foreman whose gloved hand points at the far bank",
  "WS", "eye", "static", "day", False, False,
  "на площадке тебя снова зовут по имени-отчеству, и слово твоё снова весит столько, сколько должно.",
  "the foreman's glove sweeps toward the far bank as the two men laugh",
  None, "crowd"),
 ("A11_SH06", "ANTON_BASE", "pasha_office",
  "Anton works late by choice, alone and easy, the studio lamps warm, his coat already on the hook by the door",
  "MCU", "eye", "static", "evening", False, False,
  "задерживаешься ты теперь по желанию, и это, оказывается, совсем другая усталость.",
  "his pencil taps a happy rhythm on the desk edge as the drawing closes out"),
 ("A11_SH07", ("ANTON_BASE", "MARINA_BASE"), "home_kitchen",
  "Anton and Marina cook together shoulder to shoulder, she hands him the salt before he asks, the kitchen loud with ordinary evening",
  "MS", "eye", "static", "evening", False, True,
  "марина передаёт тебе соль раньше, чем ты просишь, — дом снова слышит сам себя.",
  "the salt passes between their hands in one unthinking practiced motion"),
 ("A11_SH08", None, "courtyard_bins",
  "the old bureau courtyard in snow, the waste containers lidded, the broken chair gone, only a rectangle of bare asphalt left",
  "WS", "high", "static", "day", True, False,
  "кресло у баков в старом дворе увезли, и на асфальте остался тёмный прямоугольник.",
  "snow thins around the bare dark rectangle where the chair lay by the wall"),
 ("A11_SH09", None, None,
  "the basement desk in the dark, the engineer mug standing where it was left, the window slot glowing faint above it",
  "INSERT", "eye", "push_in", "night", False, True,
  "кружка две тысячи пятнадцатого стоит на пустом столе бэ-четыре и сторожит, как договаривались.",
  "the faint window glow breathes over the lone mug on the empty desk",
  "MUG"),
 ("A11_SH10", "ANTON_BASE", "pasha_office",
  "Anton's face to the lens at his new desk, the glasses catching warm lamp light, a man assembled back into himself",
  "CU", "eye", "push_in", "evening", False, False,
  "тебя нельзя было уволить, и это правда — тебя четыре года увольняли по-другому, и почти уволили от себя.",
  "his level gaze finds the lens and holds it with the ease of a man home"),
 ("A11_SH11", "ANTON_BASE", "pasha_office",
  "Anton turns back to the drawing, the studio warm behind him, the interchange print a quiet banner on the brick",
  "MCU", "eye", "static", "evening", False, False,
  "подпишись и останься — на этом канале каждую неделю чужая жизнь разбирается по узлам.",
  "he turns from the lens back to the drawing and the stylus finds its line",
  "BLUEPRINT"),
 ("A11_SH12", None, "pasha_office",
  "the studio at night from the doorway, lamps off except one over the pinned interchange print, snow drifting past the window",
  "WS", "eye", "pull_out", "night", False, False,
  "эта история вымышлена, все совпадения случайны — не повторяй чужих ошибок.",
  "the one lamp holds its pool over the pinned print as snow drifts past the glass"),
]

if __name__ == "__main__":
    seed_act("A9", PAL_A9, A9)
    seed_act("A10", PAL_A10, A10)
    seed_act("A11", PAL_A11, A11)
