# -*- coding: utf-8 -*-
"""irreplaceable shots: A9 (shutdown day), A10 (the manual), A11 (regulation №1)."""
from _irreplaceable_engine import seed_act

PAL_A9 = "farewell grey light, cold projector glow, thin winter windows"
PAL_A10 = "night desk lamp amber, deep blue flat shadows, paper white"
PAL_A11 = "bright new office light, plant green accents, warm daylight"

A9 = [
 ("A9_SH01", None, "meeting_it",
  "a shutdown ceremony slide reading twenty years of service with the old system's start screen on it, rows of heads",
  "WS", "eye", "static", "day", False, False,
  "день выключения назначают на пятницу и делают из него церемонию — слайд, торт, двадцать лет службы.",
  "the start-screen slide glows over the gathered heads and the sheet cake",
  None, "crowd"),
 ("A9_SH02", "ARTUR_BASE", "meeting_it",
  "Artur gives a correct short speech thanking Boris by name, gesturing to him across the room",
  "MCU", "eye", "static", "day", False, False,
  "артур говорит правильные слова и называет тебя по имени-отчеству трижды — всё честно.",
  "his presenting hand turns toward the heavy man at the room's edge",
  None, "crowd"),
 ("A9_SH03", "BORIS_BASE", "meeting_it",
  "Boris stands at the room's edge accepting the applause, flash drive cord over the good shirt he wore for this",
  "CU", "eye", "static", "day", False, False,
  "тебе хлопают искренне, и ты стоишь в парадной рубашке на похоронах собственной незаменимости.",
  "the applause patters around his still figure in the ceremonial shirt",
  None, "crowd"),
 ("A9_SH04", ("BORIS_BASE", "ARTUR_BASE"), "datacenter",
  "in cage seven, Artur offers Boris the honour of the final shutdown command, stepping back from the terminal",
  "MS", "eye", "static", "day", False, False,
  "финальную команду артур предлагает ввести тебе — жест уважения, от которого холодно рукам.",
  "his step back opens the terminal to the older man in the cage light"),
 ("A9_SH05", "BORIS_BASE", None,
  "his own fingers typing the shutdown command slowly on the terminal, each letter deliberate, the enter key waiting",
  "POV", "pov", "static", "day", False, True,
  "команду ты набираешь медленно, по букве, как набирают телеграмму о смерти.",
  "each deliberate letter lands as the enter key waits at the line's end",
  "KEYBOARD"),
 ("A9_SH06", None, None,
  "the old tower's diode column stepping from green through amber to dark, fan noise dying, the cage very quiet",
  "ECU", "low", "static", "day", False, True,
  "диоды гаснут сверху вниз, вентиляторы выдыхают, и в клетке номер семь становится тихо.",
  "the diode column steps down to dark as the fan note dies away",
  "SERVER"),
 ("A9_SH07", "BORIS_BASE", "datacenter",
  "Boris stands with his palm on the dead warm metal, the last heat leaving it into his hand",
  "MCU", "eye", "static", "day", False, False,
  "ты держишь ладонь на остывающем корпусе, пока металл не сравнивается с комнатой.",
  "his palm rides the cooling flank until the warmth is gone",
  "SERVER"),
 ("A9_SH08", ("KATYA_BASE", "BORIS_BASE"), "datacenter",
  "Katya stands beside Boris in the cage doorway, respectful of the silence, her hand briefly on his sleeve",
  "MS", "eye", "static", "day", False, False,
  "катя стоит рядом и молчит правильно — так молчат люди, которые понимают размер потери.",
  "her hand rests on his sleeve one beat and withdraws"),
 ("A9_SH09", "BORIS_BASE", "cio_office",
  "the severance conversation: a folder passed across the standing desk, respectful, final",
  "WS", "eye", "static", "day", False, False,
  "сокращение тебе оформляют «с почётом» — благодарность в приказе и полгода оклада.",
  "the severance folder crosses the desk under two courteous hands"),
 ("A9_SH10", None, None,
  "the cipher notebook lying on the emptied IT-room desk, useless now, its taped spine catching the last office light",
  "INSERT", "eye", "static", "evening", False, True,
  "сто двенадцать паролей превращаются в макулатуру за одну команду — шифр пережил свою тайну.",
  "the last office light slides along the taped spine of the useless notebook",
  "CIPHER"),
 ("A9_SH11", "BORIS_BASE", "it_room",
  "Boris packs the room into one box: the cactus, the keyboard, the notebook, the multitool pouch",
  "MS", "eye", "static", "evening", False, False,
  "каморка собирается в одну коробку — кактус, клавиатура, блокнот и генин мультитул.",
  "the cactus tin settles into the box beside the yellowed keyboard",
  "CACTUS"),
 ("A9_SH12", "BORIS_BASE", "openspace_trade",
  "Boris carries the box through the office, and people stand up as he passes — the old-world honour, real and useless",
  "WS", "eye", "track", "evening", False, False,
  "через опенспейс ты идёшь с коробкой, и люди встают — честь старого мира, настоящая и бесполезная.",
  "figures rise desk by desk as the box rides his careful arms",
  None, "crowd"),
 ("A9_SH13", "BORIS_BASE", "street_office",
  "Boris on the office steps with the box, looking up at the building, a king abdicated by referendum",
  "MCU", "eye", "static", "evening", False, False,
  "на крыльце ты оборачиваешься на здание, где двадцать лет был незаменимым, и здание не оборачивается.",
  "his upward look measures the lit floors as the box rests on his hip"),
 ("A9_SH14", "BORIS_BASE", "hr_room",
  "a recruiter across the round table scans Boris's CV, polite confusion growing line by line",
  "MS", "eye", "static", "day", False, False,
  "на первом собеседовании тебя спрашивают, с какими системами ты работал, и список кончается на одной.",
  "the recruiter's pen taps the single-line skills column"),
 ("A9_SH15", None, None,
  "a job site search field with the old system's name typed in, zero results, the cursor blinking",
  "ECU", "eye", "static", "day", False, False,
  "название твоей системы рынок не ищет — ноль вакансий, ноль упоминаний, ноль будущего.",
  "the zero-results page holds under the blinking cursor"),
 ("A9_SH16", "BORIS_BASE", "hr_room",
  "another interview, a younger panel, Boris mid-story about the night save, the panel checking the time",
  "MCU", "eye", "static", "day", False, False,
  "ты рассказываешь про ночь с инвентаризацией, и панель вежливо смотрит на часы — им нужен стек, а не сага.",
  "his story hands rise as the panel's wrists turn in quiet sync",
  None, "crowd"),
 ("A9_SH17", "BORIS_BASE", "boris_flat",
  "Boris at home lays the notebook, the flash drive and the keyboard on the desk like a veteran laying out medals",
  "MS", "eye", "static", "night", False, False,
  "дома ты раскладываешь на столе блокнот, флешку и клавиатуру — арсенал войны, которая кончилась.",
  "the three relics settle onto the desk in a straight museum row",
  "CIPHER"),
 ("A9_SH18", "BORIS_BASE", "boris_flat",
  "Boris's face over the relics in lamplight, twenty years weighing themselves in front of him",
  "CU", "eye", "push_in", "night", False, False,
  "двадцать лет опыта весят на рынке ноль, потому что ты хранил их в одном экземпляре.",
  "the lamp light holds his face as the arithmetic finishes itself"),
]

A10 = [
 ("A10_SH01", "BORIS_BASE", "boris_flat",
  "Boris opens the cipher notebook beside a blank document, begins translating the first line into plain instructions",
  "MS", "eye", "static", "night", False, True,
  "однажды ночью ты открываешь блокнот и начинаешь переписывать шифр в открытый текст.",
  "his eyes walk the cipher line as his fingers type the plain translation",
  "CIPHER"),
 ("A10_SH02", None, None,
  "a document titled as a system manual growing on screen, headings numbered, the first diagram pasted in",
  "ECU", "eye", "static", "night", False, False,
  "сначала это просто способ не сойти с ума, потом у файла появляется оглавление.",
  "the numbered headings stack as the first diagram lands in the page"),
 ("A10_SH03", "BORIS_BASE", "boris_flat",
  "Boris writes at dawn, unshaven, absorbed, tea forgotten, the flat lighter around him than in months",
  "MCU", "eye", "static", "morning", False, False,
  "пишешь ты запоем, как не писал никогда, — оказывается, отдавать знание физически легче, чем стеречь.",
  "his absorbed hands ride the keys as dawn pales the window behind"),
 ("A10_SH04", None, None,
  "the manual printed and clipped, three fat chapters on the desk, sticky tabs marking the diagrams",
  "INSERT", "top", "static", "day", False, False,
  "за три недели выходит триста страниц — документация системы, которой больше нет.",
  "the clipped chapters square themselves under the tabbed diagrams",
  "WIKI"),
 ("A10_SH05", "BORIS_BASE", "boris_flat",
  "Boris rereads a chapter and laughs one short honest laugh at himself, shaking his head",
  "CU", "eye", "static", "day", False, False,
  "перечитывая, ты смеёшься один раз, коротко — всей этой тайны было на три недели письма.",
  "the short honest laugh shakes him as the page lowers"),
 ("A10_SH06", "BORIS_BASE", "street_office",
  "Boris walks the winter street lighter, the multitool pouch on his belt, a folder of the manual under his arm",
  "WS", "eye", "track", "day", False, False,
  "с этой папкой под мышкой ты ходишь на собеседования иначе — тебе снова есть что отдавать.",
  "his lighter stride carries the folder past the frosted kiosk",
  None, "crowd"),
 ("A10_SH07", "BORIS_BASE", "hr_room",
  "an interviewer leafs the manual with growing respect, pausing at a diagram, glancing up at Boris differently",
  "MS", "eye", "static", "day", False, False,
  "интервьюеры листают твой мануал и смотрят на тебя уже не как на сагу, а как на метод.",
  "the leafing pauses at the diagram as the glance lifts and changes"),
 ("A10_SH08", None, None,
  "an email on screen from Gena with a cloud-company signature, a single line and a winking emoticon",
  "ECU", "eye", "static", "evening", False, False,
  "гена присылает одну строчку — «говорят, ты начал писать, боря, значит, живой».",
  "the one-line email holds the screen over the cloud signature"),
 ("A10_SH09", "BORIS_BASE", "boris_flat",
  "Boris types a reply longer than any he has written Gena in years, two fingers turning into ten",
  "MCU", "eye", "static", "evening", False, False,
  "ответ ты пишешь длинный, на страницу, и впервые за год это письмо не о прошлом.",
  "his reply fills the screen as the two-finger peck becomes real typing"),
 ("A10_SH10", "BORIS_BASE", "warehouse_trade",
  "Boris visits the warehouse as a guest, teaches an old storekeeper a new-system trick he learned at night",
  "WS", "eye", "static", "day", False, False,
  "на старый склад ты заходишь гостем и показываешь кладовщику фокус уже в новой системе.",
  "his finger walks the teal screen as the old storekeeper leans in",
  None, "crowd"),
 ("A10_SH11", "KATYA_BASE", "new_office",
  "Katya reads a forwarded copy of the manual at her desk, recognising the handwriting of thought, reaching for her phone",
  "MCU", "eye", "static", "day", False, False,
  "копия мануала доходит до кати, и она узнаёт руку — так строит фразы только один человек.",
  "her scrolling stops mid-page as her hand finds the phone",
  "WIKI"),
 ("A10_SH12", None, None,
  "a phone screen with an outgoing call to a contact saved years ago as Boris Palych legacy",
  "ECU", "eye", "static", "day", False, False,
  "в её телефоне ты записан «борис палыч легаси», и она нажимает вызов, не переименовывая.",
  "the call timer starts under the old contact name"),
 ("A10_SH13", "BORIS_BASE", "boris_flat",
  "Boris answers the phone and listens, his hand slowly setting down the tea, the invitation landing",
  "MCU", "eye", "static", "evening", False, False,
  "катя зовёт тебя на собеседование в свою команду, и ты слышишь в её голосе регламент и улыбку.",
  "the tea glass lowers slowly as the invitation settles in"),
 ("A10_SH14", "BORIS_BASE", "boris_flat",
  "Boris stands at the window after the call, the city lights on, an old man surprised by a door",
  "MS", "eye", "static", "night", False, False,
  "ты стоишь у окна дольше обычного — двери, оказывается, открываются и в эту сторону.",
  "the city lights hold his still silhouette at the dark glass"),
]

A11 = [
 ("A11_SH01", None, "new_office",
  "the bright support office in morning light, four paired desks, plants on the sill, the regulations wall tidy",
  "WS", "eye", "static", "morning", True, False,
  "офис поддержки живёт по регламентам, и в нём светло так, как в каморке не было никогда.",
  "morning light lies along the paired desks and the tidy regulation wall"),
 ("A11_SH02", ("KATYA_BASE", "BORIS_BASE"), "hr_room",
  "the interview: Katya across the round table from Boris, both fighting smiles through the formal questions",
  "MS", "eye", "static", "day", False, True,
  "собеседование ведёт катя, и вы оба честно играете в формальные вопросы, пряча улыбки.",
  "the formal questions pass between two suppressed smiles at the round table"),
 ("A11_SH03", "KATYA_BASE", "hr_room",
  "Katya slides the offer across: analyst of support, a documentation clause highlighted, her pen offered",
  "CU", "eye", "static", "day", False, False,
  "условие в оффере одно, маркером — «документируем всё», и ты узнаёшь школу артура.",
  "the highlighted clause leads the sheet across as her pen turns to him"),
 ("A11_SH04", "BORIS_BASE", None,
  "his own hand signing the offer, the signature the same old-school line, the salary line visible above",
  "POV", "pov", "static", "day", False, False,
  "сто двадцать тысяч против прежних двухсот десяти, и подпись выходит легче, чем тогда.",
  "the old-school signature lands lighter than its predecessor"),
 ("A11_SH05", "BORIS_BASE", "new_office",
  "Boris sets the cactus tin on his new monitor, adjusting it to face the window, a rite of settlement",
  "ECU", "eye", "static", "day", False, False,
  "кактус переезжает на новый монитор, и на этом переезд, в сущности, закончен.",
  "the tea tin settles on the monitor top and turns to face the window",
  "CACTUS"),
 ("A11_SH06", "BORIS_BASE", "new_office",
  "Boris writes his first wiki page at the new desk, typing steadily, the manual folder open beside for reference",
  "MS", "eye", "static", "day", False, False,
  "первую вики-страницу ты пишешь сам, добровольно, и называешь её «регламент номер один».",
  "his steady typing fills the wiki editor as the folder waits open",
  "WIKI"),
 ("A11_SH07", None, None,
  "the printed wiki page pinned over the new desk, tidy headings, a pin at each corner this time",
  "INSERT", "eye", "static", "day", False, True,
  "распечатку ты вешаешь над столом на четыре кнопки — чтобы висела ровно и долго.",
  "four pins take the corners as the printed page settles flat",
  "WIKI"),
 ("A11_SH08", ("BORIS_BASE", "KATYA_BASE"), "new_office",
  "Boris hands Katya the cipher notebook across her desk, a museum donation, her hands receiving it accordingly",
  "MS", "eye", "static", "day", False, True,
  "блокнот-шифр ты отдаёшь кате насовсем — «в музей отдела, чтобы молодые видели, как нельзя».",
  "the taped-spine notebook passes into her careful receiving hands",
  "CIPHER"),
 ("A11_SH09", "KATYA_BASE", "new_office",
  "Katya places the notebook in her drawer on a folded scarf, closing it gently, curator of a small dark exhibit",
  "CU", "eye", "static", "day", False, False,
  "катя укладывает его в ящик на сложенный шарф, и у крепости появляется музейный этаж.",
  "the drawer closes gently over the notebook on its folded scarf",
  "CIPHER"),
 ("A11_SH10", "BORIS_BASE", "new_office",
  "Boris answers a junior's question by pointing at the wiki instead of reciting, then adds one paragraph to it",
  "MS", "eye", "static", "day", False, False,
  "на вопрос молодого ты впервые отвечаешь ссылкой, а потом дописываешь в статью абзац.",
  "his pointing finger sends the junior to the wiki as his other hand types the addition",
  None, "crowd"),
 ("A11_SH11", "BORIS_BASE", "new_office",
  "Boris's face to the lens at the new desk, the flash drive cord still on, a man translated into a living language",
  "CU", "eye", "push_in", "day", False, False,
  "подпишись и останься — на этом канале каждую неделю чья-то крепость учится открывать ворота.",
  "his settled gaze holds the lens as the office hums warm behind him"),
 ("A11_SH12", None, "new_office",
  "the new desk at evening: the printed wiki page, the cactus on the monitor, the multitool pouch hung on the chair",
  "WS", "eye", "pull_out", "evening", False, False,
  "эта история вымышлена, все совпадения случайны — не повторяй чужих ошибок.",
  "evening light settles over the pinned page, the cactus and the hung pouch"),
]

if __name__ == "__main__":
    seed_act("A9", PAL_A9, A9)
    seed_act("A10", PAL_A10, A10)
    seed_act("A11", PAL_A11, A11)
