# -*- coding: utf-8 -*-
"""Seed CH08 — Погоня начинается (HEROINE_YOUNG). Non-explicit. Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "the chase takes hold, one is never enough, smoky neon GDR nights, restless hunger"
SHOTS = [
 ("CH08_SH01", "HEROINE_YOUNG", "disco",
  "medium of the heroine working the dancehall, scanning the room",
  "MS","eye","static","night",False,False,
  "и начинается твоя погоня, дискотека за дискотекой, новое лицо за новым лицом, ночь за ночью."),
 ("CH08_SH02", None, "disco",
  "close-up of faceless men's eyes lighting up around her",
  "CU","eye","static","night",True,False,
  "тебе нравится сам этот миг, когда чужие глаза вспыхивают, когда тебя выбирают и желают."),
 ("CH08_SH03", "HEROINE_YOUNG", "kneipe",
  "medium close-up of her at a smoky pub table, in control",
  "MCU","eye","static","night",False,False,
  "ты быстро поняла, чтобы получить волну, не нужно ждать любви, достаточно просто захотеть."),
 ("CH08_SH04", None, "kneipe",
  "wide of a smoky low-lit pub, dark booths and a beer tap",
  "WS","eye","static","night",True,False,
  "в прокуренной пивной всегда найдётся тот, кто купит тебе выпить и проводит до дома."),
 ("CH08_SH05", "HEROINE_YOUNG", "street_east",
  "medium of her leaving with a faceless man, another waiting in the shadows",
  "MS","eye","static","night",False,False,
  "один провожает, другой ждёт завтра, и тебе кажется, что ты держишь весь мир за ниточки."),
 ("CH08_SH06", None, "her_room",
  "extreme close-up of two glasses and an ashtray in cold morning light",
  "ECU","top_down","static","dawn",True,False,
  "но каждое утро повторяется одно, чужой запах на подушке и снова пустая холодная постель."),
 ("CH08_SH07", "HEROINE_YOUNG", "her_room",
  "medium close-up of her already restless by morning",
  "MCU","eye","static","dawn",False,False,
  "приход всё короче, и уже наутро тебе снова мало, снова нужен кто-то совершенно новый."),
 ("CH08_SH08", None, "street_east",
  "close-up of another faceless gaze in the street",
  "CU","eye","static","gdr_day",True,False,
  "ты считаешь чужие взгляды, как монеты, и тратишь себя, не замечая, как стремительно."),
 ("CH08_SH09", "HEROINE_YOUNG", "disco",
  "medium close-up of her scorn for steady couples",
  "MCU","eye","static","night",False,False,
  "подруги встречаются с одним и тем же парнем, а тебя от одной этой мысли просто тошнит."),
 ("CH08_SH10", "HEROINE_YOUNG", "disco",
  "close-up of her certainty",
  "CU","eye","static","night",False,True,
  "один навсегда, нет, это точно не про тебя, тебе нужно много, нужно всегда новое."),
 ("CH08_SH11", None, "disco",
  "wide B-roll of the smoky neon dancehall, silent",
  "WS","eye","static","night",True,False,""),
]
if __name__ == "__main__":
    seed_act(8, "neon_gdr", MOOD, "static", "CH08 Chase begins", SHOTS)
