# -*- coding: utf-8 -*-
"""Seed CH21 — Удвоить ставку, назло (2nd person). Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "cold clinic white light, desperate doubling-down, the mask hardening"
SHOTS = [
 ("CH21_SH01", ("HEROINE_MID","ALINA"), "clinic",
  "the heroine on the left demanding more, Alina on the right with a tray of syringes",
  "MS","eye","static","clinic_day",False,False,
  "ты врываешься к алине, делай что хочешь, верни мне молодость."),
 ("CH21_SH02", "ALINA", "clinic",
  "medium close-up of Alina hesitating for a flicker, then obliging, money is money",
  "MCU","eye","static","clinic_day",False,False,
  "даже алина на миг замялась, но деньги есть деньги."),
 ("CH21_SH03", None, "clinic",
  "extreme close-up of yet more needles and threads going into the face, without measure",
  "ECU","eye","push_in","clinic_day",True,True,
  "ещё уколы, ещё нити, ещё филлеры, уже без всякой меры."),
 ("CH21_SH04", "HEROINE_MID", "bathroom",
  "medium close-up of the heroine seeing triumph in a face turning ever more into a mask",
  "MCU","eye","static","clinic_day",False,False,
  "лицо всё больше похоже на маску, но ты видишь в нём триумф."),
 ("CH21_SH05", None, "mfo",
  "close-up of new loan papers signed without a second thought",
  "CU","top_down","static","office_day",True,False,
  "новые займы, плевать, лишь бы доказать."),
 ("CH21_SH06", "HEROINE_MID", "family",
  "medium shot of the heroine dressing up obsessively to win her husband back",
  "MS","eye","static","home_eve",False,False,
  "ты пишешь ему, наряжаешься, караулишь у дома."),
 ("CH21_SH07", "HUSBAND", "family",
  "close-up of the husband's phone silent, ignoring her messages",
  "CU","eye","static","home_eve",False,False,
  "а он не отвечает, его телефон молчит."),
 ("CH21_SH08", "HEROINE_MID", "clinic",
  "medium shot of the heroine back in the chair again, going in circles",
  "MS","eye","static","clinic_day",False,False,
  "и ты снова в кресло, и снова, по замкнутому кругу."),
 ("CH21_SH09", "HEROINE_MID", "bathroom",
  "extreme close-up of her increasingly distorted face in the mirror",
  "ECU","eye","static","clinic_day",False,True,
  "ты уже не помнишь своё настоящее лицо."),
 ("CH21_SH10", "HEROINE_MID", "bathroom",
  "close-up of the heroine's obsessive fixed stare",
  "CU","eye","static","home_eve",False,False,
  "докажу, твердишь ты, всем докажу, что ещё красива."),
 ("CH21_SH11", "HEROINE_MID", "clinic",
  "medium close-up of the heroine betting everything on one last big procedure",
  "MCU","eye","static","clinic_day",False,True,
  "ты ставишь на красоту последнее, что у тебя осталось."),
 ("CH21_SH12", None, "shop",
  "wide B-roll of the clinic facade glowing cold at night",
  "WS","eye","static","clinic_day",True,False,""),
]
if __name__ == "__main__":
    seed_act(21, "clinic_white", MOOD, "static", "CH21 Double down", SHOTS)
