# -*- coding: utf-8 -*-
"""Seed CH21 — Цена, последствия, досье Штази (HEROINE_YOUNG). Non-explicit. Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "consequences arrive, an unwanted procedure faced alone, a Stasi file on her, cold institutional dread"
SHOTS = [
 ("CH21_SH01", "HEROINE_YOUNG", "her_room",
  "medium of the heroine sitting stunned with a realisation",
  "MS","eye","static","gdr_day",False,False,
  "однажды погоня предъявляет счёт, ты понимаешь, что беременна, и не знаешь даже от кого."),
 ("CH21_SH02", "HEROINE_YOUNG", "clinic",
  "close-up of the heroine alone on a clinic couch, no hand to hold",
  "CU","eye","static","gdr_day",False,False,
  "в холодной поликлинике ты лежишь одна, без мужа, без руки, которую можно было бы сжать."),
 ("CH21_SH03", None, "clinic",
  "extreme close-up of an enamel tray and frosted glass, clinical and discreet",
  "ECU","top_down","static","gdr_day",True,False,
  "ты делаешь то, что делаешь, тихо и стыдливо, и уходишь домой по серым пустым улицам."),
 ("CH21_SH04", "HEROINE_YOUNG", "her_room",
  "medium close-up of her doubting for the first time",
  "MCU","eye","static","gdr_eve",False,False,
  "никто не держит тебя за руку, и впервые ты думаешь, а что, если Андреас был прав."),
 ("CH21_SH05", None, "stasi_office",
  "wide of a cold state-security office, a grey file folder on a bare desk",
  "WS","eye","static","gdr_day",True,False,
  "а ещё оказывается, что государство давно завело на тебя тонкую серую папку."),
 ("CH21_SH06", None, "stasi_office",
  "extreme close-up of the buff file folder and typed lines",
  "ECU","top_down","static","gdr_day",True,True,
  "аморальный образ жизни, беспорядочные связи, выведено там сухим, безжалостным казённым почерком."),
 ("CH21_SH07", "HEROINE_YOUNG", "stasi_office",
  "medium close-up of the heroine being lectured across the desk",
  "MCU","eye","static","gdr_day",False,False,
  "тебя вызывают, отчитывают, грозят, ты позоришь облик советской женщины, цедят они."),
 ("CH21_SH08", "HEROINE_YOUNG", "street_east",
  "close-up of her crushed but already drawn back to the chase",
  "CU","eye","static","gdr_eve",False,False,
  "ты выходишь раздавленная, но к вечеру снова бежишь за своей дозой, чтобы хоть как-то забыться."),
 ("CH21_SH09", "HEROINE_YOUNG", "her_room",
  "medium close-up of her seeking oblivion in a stranger's arms",
  "MCU","eye","static","night",False,False,
  "ведь только в чужих объятиях ты на пару часов не слышишь этот вынесенный тебе приговор."),
 ("CH21_SH10", None, "her_room",
  "extreme close-up of the box with Andreas's key, the door never entered",
  "ECU","top_down","static","night",True,True,
  "а ключ Андреаса всё лежит в шкатулке, дверь, в которую ты так и не решилась войти."),
 ("CH21_SH11", None, "clinic",
  "wide B-roll of the cold empty clinic corridor, silent",
  "WS","eye","static","gdr_day",True,False,""),
]
if __name__ == "__main__":
    seed_act(21, "cold_blue", MOOD, "static", "CH21 The price", SHOTS)
