# -*- coding: utf-8 -*-
"""best_thing atmosphere breathers: 2 per act (A1..A11), id_region='a', unique per-act schemes."""
from _best_thing_engine import seed_act

PALS = {
 "A1": "warm office daylight, plant green accents, amber window light",
 "A2": "cold news grey, flat corporate light, drained colours",
 "A3": "farewell amber light, winter window blue, warm lamp pools",
 "A4": "crossroad dusk tones, cold listing glow, warm salon accents",
 "A5": "green class light, stem and ribbon colours, fresh water shine",
 "A6": "salon cool green, zinc bucket shine, ribbon colour accents",
 "A7": "market string lights, kraft warm tones, fresh stem greens",
 "A8": "frost night blue, van headlight beams, cold breath silver",
 "A9": "warm team glow, family kitchen amber, working daylight",
 "A10": "workshop warm light, wood and kraft tones, cooler glass shine",
 "A11": "full circle light, celebration warm, winter evening gold",
}

ATMO = {
 "A1": [
  ("A1_SZ01", None, "office_acc",
   "the office sill line at golden hour, plant shadows long across a desk of closed binders",
   "WS", "eye", "pan_right", "evening", True, False,
   "к вечеру тени от подоконника доходят до годовых папок — офисный солнечный календарь.",
   "long plant shadows creep across the closed binders in the gold light"),
  ("A1_SZ02", None, "courtyard_home",
   "jars of cuttings on a home windowsill against the courtyard dusk, roots luminous in the backlight",
   "ECU", "eye", "static", "evening", True, False,
   "черенки на домашнем подоконнике светятся корнями против заката — маленький питомник надежд.",
   "backlit root threads sway in the jar water against the dusk"),
 ],
 "A2": [
  ("A2_SZ01", None, "office_meeting",
   "the meeting room after the announcement: folders left on seats, one chair turned away from the table",
   "WS", "eye", "static", "day", True, False,
   "после объявления папки остаются на стульях — их заберут, но не сразу.",
   "the abandoned folders hold their seats as the turned chair stands apart"),
  ("A2_SZ02", None, "street_market",
   "flower buckets outside the market glowing under string lights in early winter dusk, steam from a kiosk",
   "ECU", "eye", "push_in", "evening", True, False,
   "у рынка вёдра с хризантемами светятся под гирляндой — декабрь, а они держат цвет.",
   "the chrysanthemum heads glow under the lights as kiosk steam drifts past"),
 ],
 "A3": [
  ("A3_SZ01", None, "office_acc",
   "a handover trolley of labelled binders waiting by the office door, a coat thrown over its handle",
   "INSERT", "eye", "static", "day", True, False,
   "тележка с папками стоит у двери третий день — пятнадцать лет уезжают партиями.",
   "the coat sways on the trolley handle as the labelled spines wait"),
  ("A3_SZ02", None, "courtyard_home",
   "the rowan tree in snow at night, berries bright under the entrance lamp, tracks converging at the door",
   "WS", "low", "static", "night", True, False,
   "рябина у подъезда держит ягоды под снегом — запас на плохие времена у неё продуман.",
   "lamp light rounds the snow-capped berry clusters over the converging tracks"),
 ],
 "A4": [
  ("A4_SZ01", None, "roza_salon",
   "the salon's cold display case from the street: buckets graded by colour, a hand-written price card, breath fog on glass",
   "WS", "eye", "static", "evening", True, False,
   "витрина розы собрана по цвету, как палитра, и ценники в ней написаны от руки — школа видна с улицы.",
   "breath fog blooms on the case glass over the graded colour rows"),
  ("A4_SZ02", None, "lida_kitchen",
   "two papers on the night kitchen table under the lamp: a folded vacancy and a flattened course flyer",
   "ECU", "top", "push_in", "night", True, False,
   "две бумаги на столе спят по-разному — вакансия сложена, листовка расправлена.",
   "the lamp pool holds the folded and the flattened side by side"),
 ],
 "A5": [
  ("A5_SZ01", None, "courses_flor",
   "the classroom at break: aprons on hooks, practice greens in buckets, stems and offcuts swept into a pile",
   "MS", "eye", "static", "day", True, False,
   "на перемене класс пахнет свежим срезом — запах, который ты теперь узнаешь из тысячи.",
   "swept offcuts settle into their pile under the hooked aprons"),
  ("A5_SZ02", None, "flower_base",
   "dawn breaking over the flower base gates, empty trolleys returning, the last vans loading",
   "EWS", "low", "static", "morning", True, False,
   "база закрывает торги к семи — те, кто выбрал цветы на сегодня, уже развозят их по городу.",
   "returning trolleys rattle the dawn gates as the last vans close up",
   None, "crowd"),
 ],
 "A6": [
  ("A6_SZ01", None, "roza_salon",
   "ribbon spools racked by colour on the salon wall, one spool spinning down to its last metre",
   "ECU", "eye", "static", "day", True, False,
   "ленты у розы стоят по спектру, и жёлтая всегда кончается первой — город любит солнце.",
   "the near-empty spool turns its last metre in the racked spectrum"),
  ("A6_SZ02", None, "street_market",
   "spring rain on the market street, flower vans with wipers going, buckets under awnings",
   "WS", "eye", "static", "day", True, False,
   "весенний дождь цветам праздник — вёдра под навесами стоят умытые и наглые.",
   "rain beads the awnings as the washed buckets crowd beneath",
   None, "crowd"),
 ],
 "A7": [
  ("A7_SZ01", None, "market_corner",
   "the corner's string lights at dusk reflected in zinc buckets, kraft roll edge glowing warm",
   "ECU", "eye", "push_in", "evening", True, False,
   "гирлянда отражается в цинке восемью маленькими рассветами — твой угол научился светиться.",
   "eight small reflections warm in the zinc as the lights settle"),
  ("A7_SZ02", None, "street_market",
   "the covered market at closing: shutters rolling down in sequence, one flower corner still lit",
   "WS", "eye", "static", "night", True, False,
   "рынок закрывается ставнями по очереди, и цветочный угол гаснет последним — заказ доделывался.",
   "shutters step down the row as the one lit corner holds out",
   None, "crowd"),
 ],
 "A8": [
  ("A8_SZ01", None, "family_car",
   "the van's headlight beams boring through frost fog on an empty night road, ice crystals in the light",
   "EWS", "eye", "static", "night", True, False,
   "мороз стоит такой, что свет фар виден весь, до последнего метра.",
   "ice crystals drift through the twin beams on the empty road"),
  ("A8_SZ02", None, "wedding_hall",
   "the banquet hall arch at dawn before guests: finished, lit by service light, chairs still stacked",
   "WS", "low", "static", "morning", True, False,
   "арка стоит готовая за пять часов до гостей — цветы умеют ждать красиво.",
   "service light models the finished arch over the stacked chairs"),
 ],
 "A9": [
  ("A9_SZ01", None, "workshop",
   "renovation in the workshop: a paint roller resting in a tray, masking tape lines, the sign leaning wrapped",
   "INSERT", "eye", "static", "day", True, False,
   "ремонт в мастерской идёт по выходным, и вывеска ждёт своего гвоздя в упаковке.",
   "the roller rests in its tray beside the wrapped waiting sign"),
  ("A9_SZ02", None, "lida_kitchen",
   "the family kitchen with three phones charging in a row by the bread bin, the household's new fleet",
   "ECU", "eye", "static", "night", True, False,
   "у хлебницы заряжаются три телефона — касса, доставка и медиаотдел одной семьи.",
   "three charge lights pulse their row beside the bread bin"),
 ],
 "A10": [
  ("A10_SZ01", None, "workshop",
   "the cooler's glass door fogged in a corner from a warm delivery, bucket colours soft behind it",
   "ECU", "eye", "static", "day", True, False,
   "холодильник запотевает от каждой тёплой поставки — у мастерской своё дыхание.",
   "the fog patch thins on the glass over the soft bucket colours"),
  ("A10_SZ02", None, "courtyard_home",
   "the home courtyard in deep winter, the rowan bare now, a snowman with a dried flower in its twig hand",
   "WS", "eye", "static", "day", True, False,
   "снеговик во дворе стоит с сухоцветом в руке — колина работа, судя по ракурсу для фото.",
   "the twig hand holds its dried flower as snow fine-drifts past"),
 ],
 "A11": [
  ("A11_SZ01", None, "office_acc",
   "the old accounting office windowsill, bare of plants now, blinds half open on winter light",
   "WS", "eye", "static", "day", True, False,
   "старый подоконник в отделе стоит пустой — цветы оттуда разъехались вместе с людьми.",
   "winter light strips the bare sill through the half-open blinds"),
  ("A11_SZ02", None, "workshop",
   "the workshop doorstep at night: fresh footprints, the sign's warm pool of light, snow settling on the kraft delivery box",
   "ECU", "low", "tilt_up", "night", True, False,
   "у порога мастерской снег не залёживается — следы обновляются чаще, чем прогноз.",
   "the tilt climbs from the fresh prints to the sign's warm pool",
   None, None),
 ],
}

if __name__ == "__main__":
    for act, shots in ATMO.items():
        seed_act(act, PALS[act], shots, id_region="a")
