-- Seed: last_shift project (200 shots, 8 acts, 9 characters with IP-Adapter).
-- Idempotent-by-slug: rerunning will DELETE then re-INSERT the project (CASCADE
-- will wipe scenes/shots/characters tied to it). Workflow templates/routes
-- belonging to last_shift are also cleared.

BEGIN;

-- Idempotent cleanup ---------------------------------------------------------
DELETE FROM projects WHERE slug = 'last_shift';

DO $$
DECLARE
  v_proj  TEXT := gen_random_uuid()::text;
  v_a1    TEXT := gen_random_uuid()::text;
  v_a2    TEXT := gen_random_uuid()::text;
  v_a3    TEXT := gen_random_uuid()::text;
  v_a4    TEXT := gen_random_uuid()::text;
  v_a5    TEXT := gen_random_uuid()::text;
  v_a6    TEXT := gen_random_uuid()::text;
  v_a7    TEXT := gen_random_uuid()::text;
  v_a8    TEXT := gen_random_uuid()::text;
  v_ch_cond TEXT := gen_random_uuid()::text;
  v_ch_mil  TEXT := gen_random_uuid()::text;
  v_ch_mom  TEXT := gen_random_uuid()::text;
  v_ch_brd  TEXT := gen_random_uuid()::text;
  v_ch_biz  TEXT := gen_random_uuid()::text;
  v_ch_vet  TEXT := gen_random_uuid()::text;
  v_ch_he   TEXT := gen_random_uuid()::text;
  v_ch_she  TEXT := gen_random_uuid()::text;
  v_ch_mus  TEXT := gen_random_uuid()::text;
  v_ch_grl  TEXT := gen_random_uuid()::text;
  v_pr_cond TEXT := gen_random_uuid()::text;
  v_pr_mil  TEXT := gen_random_uuid()::text;
  v_pr_mom  TEXT := gen_random_uuid()::text;
  v_pr_brd  TEXT := gen_random_uuid()::text;
  v_pr_biz  TEXT := gen_random_uuid()::text;
  v_pr_vet  TEXT := gen_random_uuid()::text;
  v_pr_he   TEXT := gen_random_uuid()::text;
  v_pr_she  TEXT := gen_random_uuid()::text;
  v_pr_mus  TEXT := gen_random_uuid()::text;
  v_pr_grl  TEXT := gen_random_uuid()::text;
BEGIN

-- Project --------------------------------------------------------------------
INSERT INTO projects (id, slug, name, "scriptText", settings, "targetPlatform", "safetyTier", "createdAt", "updatedAt")
VALUES (v_proj, 'last_shift', 'Последний рейс', NULL, NULL, 'youtube', 'advertiser_safe', NOW(), NOW());

-- Scenes (8 acts) ------------------------------------------------------------
INSERT INTO scenes (id, "projectId", "sceneKey", title, "sortOrder", "actBeat", "defaultPaletteKey", "defaultTimeOfDay", "createdAt") VALUES
  (v_a1, v_proj, 'act_01_boarding',   'A1 — Boarding',   0, 'setup',                  'A1_sodium',         'sunset_day1',      NOW()),
  (v_a2, v_proj, 'act_02_settling',   'A2 — Settling',   1, 'rising',                 'A2_amber_indigo',   'early_night_day1', NOW()),
  (v_a3, v_proj, 'act_03_deep_night', 'A3 — Deep Night', 2, 'rising',                 'A3_amber_indigo',   'peak_night_day1',  NOW()),
  (v_a4, v_proj, 'act_04_pre_dawn',   'A4 — Pre-dawn',   3, 'rising',                 'A4_cool_blue',      'predawn_day2',     NOW()),
  (v_a5, v_proj, 'act_05_daylight',   'A5 — Daylight',   4, 'rising',                 'A5_cold_birch',     'day_day2',         NOW()),
  (v_a6, v_proj, 'act_06_midpoint',   'A6 — Midpoint',   5, 'midpoint_twist',         'A6_golden_warm',    'late_day_day2',    NOW()),
  (v_a7, v_proj, 'act_07_crisis',     'A7 — Crisis',     6, 'climax',                 'A7_dark_emerald',   'night_day2',       NOW()),
  (v_a8, v_proj, 'act_08_resolution', 'A8 — Resolution', 7, 'final_image',            'A8_pink_fog',       'morning_day2',     NOW());

-- Characters -----------------------------------------------------------------
INSERT INTO characters (id, "projectId", code, "displayName", "createdAt") VALUES
  (v_ch_cond, v_proj, 'CONDUCTOR',   'Conductor',                 NOW()),
  (v_ch_mil,  v_proj, 'PAX_MIL',     'Military passenger',        NOW()),
  (v_ch_mom,  v_proj, 'PAX_MOM',     'Mother with infant',        NOW()),
  (v_ch_brd,  v_proj, 'PAX_BRIDE',   'Solo bride',                NOW()),
  (v_ch_biz,  v_proj, 'PAX_BIZ',     'Businessman',               NOW()),
  (v_ch_vet,  v_proj, 'PAX_VET',     'Veteran grandfather',       NOW()),
  (v_ch_he,   v_proj, 'PAX_HE',      'Couple — him',              NOW()),
  (v_ch_she,  v_proj, 'PAX_SHE',     'Couple — her',              NOW()),
  (v_ch_mus,  v_proj, 'PAX_MUS',     'Musician',                  NOW()),
  (v_ch_grl,  v_proj, 'PAX_GIRL',    'Child girl with owl',       NOW());

-- Character profiles --------------------------------------------------------
-- Conductor uses LoRA (loraPath populated after user trains CONDUCTOR_BASE).
-- All passengers use IP-Adapter from a single reference portrait.
INSERT INTO character_profiles (id, "characterId", "profileCode", "ageLabel", "promptBase", negative, "loraPath", "triggerToken", "useIpAdapter", "createdAt") VALUES
  (v_pr_cond, v_ch_cond, 'CONDUCTOR_BASE', '38-42',
   $pp$CONDUCTOR_BASE, female train conductor late 30s, dark blonde low bun under navy peaked cap, grey-green tired eyes, thin scar above left eyebrow, natural skin pores, no makeup, dark navy uniform jacket with one shoulder stripe and brass buttons, white shirt collar, grey fingerless wool gloves$pp$,
   $pp$(plastic skin:1.2), (oversmooth:1.2), (cartoon:1.2), (anime:1.3), (cgi:1.2), makeup, lipstick, jewelry on hands, modern logos, text on uniform, deformed hands, extra fingers, duplicate face$pp$,
   NULL, 'CONDUCTOR_BASE', FALSE, NOW()),
  (v_pr_mil,  v_ch_mil,  'PAX_MIL',   '30',
   $pp$30yo man in plain dark green military shirt without insignia, short buzzcut, hollow cheeks, sharp jawline, brown thousand-yard stare eyes$pp$, NULL, NULL, NULL, TRUE, NOW()),
  (v_pr_mom,  v_ch_mom,  'PAX_MOM',   '25',
   $pp$25yo woman with long dark hair loose, no makeup, cream cardigan, holding sleeping infant against shoulder, gentle exhausted face$pp$, NULL, NULL, NULL, TRUE, NOW()),
  (v_pr_brd,  v_ch_brd,  'PAX_BRIDE', '24',
   $pp$24yo woman, light brown messy ponytail, no makeup, grey hoodie and joggers, holding white garment bag with wedding dress visible through plastic, red-rimmed eyes$pp$, NULL, NULL, NULL, TRUE, NOW()),
  (v_pr_biz,  v_ch_biz,  'PAX_BIZ',   '45',
   $pp$45yo man, rumpled white dress shirt with loosened dark tie, glasses pushed up on head, salt-pepper receding hair, gold wedding ring, mild defeated expression$pp$, NULL, NULL, NULL, TRUE, NOW()),
  (v_pr_vet,  v_ch_vet,  'PAX_VET',   '80',
   $pp$80yo man in dark wool blazer with three rows of generic medal ribbons no readable insignia, thin white side hair on bald head, deep wrinkles, pale blue eyes, calloused hands resting on simple wooden cane$pp$, NULL, NULL, NULL, TRUE, NOW()),
  (v_pr_he,   v_ch_he,   'PAX_HE',    '33',
   $pp$33yo man, short dark hair and trimmed beard, navy crew neck sweater, set jaw$pp$, NULL, NULL, NULL, TRUE, NOW()),
  (v_pr_she,  v_ch_she,  'PAX_SHE',   '32',
   $pp$32yo woman with auburn hair in low ponytail, oversized grey turtleneck, red eyes$pp$, NULL, NULL, NULL, TRUE, NOW()),
  (v_pr_mus,  v_ch_mus,  'PAX_MUS',   '22',
   $pp$22yo man, messy dark curly hair, denim jacket over white tee, acoustic guitar across knees, gentle absent smile$pp$, NULL, NULL, NULL, TRUE, NOW()),
  (v_pr_grl,  v_ch_grl,  'PAX_GIRL',  '7',
   $pp$7yo girl, brown shoulder length hair, light blue cardigan over white tee, holding worn plush owl with one button eye missing, solemn dark eyes, natural child proportions$pp$, NULL, NULL, NULL, TRUE, NOW());

-- Shots (200) ----------------------------------------------------------------
-- Columns: id, projectId, sceneId, shotCode, promptFields,
--          shotType, cameraAngle, cameraMove, storyBeat, narrativeFunction,
--          vignetteSlug, isBroll, isIconic, timeOfDay, paletteKey,
--          createdAt, updatedAt
INSERT INTO shots (id, "projectId", "sceneId", "shotCode", "promptFields", "shotType", "cameraAngle", "cameraMove", "storyBeat", "narrativeFunction", "vignetteSlug", "isBroll", "isIconic", "timeOfDay", "paletteKey", "createdAt", "updatedAt") VALUES

-- ========== A1 — BOARDING (22) ==========
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH01', jsonb_build_object('positivePrompt', $pp${TRAIN_EXT}, aerial wide deserted small railway platform at autumn dusk, single sodium lamp flickering to life, no city around, {LIGHT_A1}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'EWS', 'high', 'static', 'opening_image', 'atmosphere', NULL, TRUE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH02', jsonb_build_object('positivePrompt', $pp$extreme close-up vintage brass ticket punch piercing blank cardboard ticket, hand in grey wool fingerless glove, {LIGHT_A1}, sharp 100mm macro, deep shadow, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'theme_stated', 'iconic', NULL, TRUE, TRUE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH03', jsonb_build_object('positivePrompt', $pp${CONDUCTOR}, medium shot, standing at open train carriage door checking ticket, evening platform, {LIGHT_A1}, breath visible in cool air, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'setup', 'character', 'conductor', FALSE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH04', jsonb_build_object('positivePrompt', $pp${CONDUCTOR}, close-up face low angle, deep tiredness in grey-green eyes, breath fogging slightly, sodium rim light from behind, {LIGHT_A1}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'low', 'static', 'setup', 'character', 'conductor', FALSE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH05', jsonb_build_object('positivePrompt', $pp$extreme close-up, white folded resignation letter envelope tucked into dark navy uniform breast pocket, no readable text on envelope, slight wear on corner, warm sodium glow, {LIGHT_A1}, 100mm macro$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'catalyst', 'plot', 'conductor', FALSE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH06', jsonb_build_object('positivePrompt', $pp$OTS over conductor shoulder, hand returning ticket to {PAX_MIL} stepping up to train, dark green shirt, looking down, {LIGHT_A1}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'OTS', 'eye', 'static', 'setup', 'character', 'military', FALSE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH07', jsonb_build_object('positivePrompt', $pp$wide shot lateral motion, {PAX_MOM} stepping up into train carriage doorway, large soft bag in hand, careful protective movement, {LIGHT_A1}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'track_lateral', 'setup', 'character', 'mother_baby', FALSE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH08', jsonb_build_object('positivePrompt', $pp$medium close-up three quarter, {PAX_BRIDE} standing alone on platform with large white garment bag, looking at nothing, sodium light catching dress visible through plastic, {LIGHT_A1}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'setup', 'character', 'bride', FALSE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH09', jsonb_build_object('positivePrompt', $pp$medium shot low angle, {PAX_BIZ} hurrying along platform with laptop bag swinging, half a coffee cup in hand, looking flustered, {LIGHT_A1}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'low', 'static', 'setup', 'character', 'businessman', FALSE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH10', jsonb_build_object('positivePrompt', $pp$medium shot, {PAX_VET} standing patiently with simple cane, holding small fabric-wrapped bundle, three rows of generic medal ribbons under open wool coat, {LIGHT_A1}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'setup', 'character', 'veteran', FALSE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH11', jsonb_build_object('positivePrompt', $pp$wide shot, {PAX_SHE} stepping into carriage first looking down, {PAX_HE} behind carrying two suitcases, visible distance between them, both silent, {LIGHT_A1}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'static', 'setup', 'character', 'couple_fight', FALSE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH12', jsonb_build_object('positivePrompt', $pp$medium shot handheld, {PAX_MUS} with guitar case strap across chest, easy smile nodding to off-frame conductor, {LIGHT_A1}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'handheld', 'setup', 'character', 'musician', FALSE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH13', jsonb_build_object('positivePrompt', $pp$high angle close-up, {PAX_GIRL} standing alone on platform beside small wheeled suitcase, solemn eyes looking up toward camera, owl held tight, no adult visible nearby, {LIGHT_A1}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'high', 'static', 'setup', 'plot', 'child_girl', FALSE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH14', jsonb_build_object('positivePrompt', $pp$extreme close-up brass ticket punch piercing a small child-sized ticket, conductor gloved hand steady, child small hand at frame edge offering it, {LIGHT_A1}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'setup', 'iconic', 'child_girl', FALSE, TRUE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH15', jsonb_build_object('positivePrompt', $pp${CONDUCTOR} MCU, subtle micro-expression of recognition behind professional calm, looking off-frame down toward child, sodium evening light, {LIGHT_A1}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'setup', 'character', 'conductor', FALSE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH16', jsonb_build_object('positivePrompt', $pp$high wide overhead, train platform from above, last passenger boarding, conductor closing carriage door, steam rising in cold air, no other people, {LIGHT_A1}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'high', 'static', 'setup', 'atmosphere', NULL, TRUE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH17', jsonb_build_object('positivePrompt', $pp$back shot lateral track, {CONDUCTOR} walking down narrow train corridor away from camera, hand brushing each compartment door, tungsten lamps clicking on ahead, {TRAIN_INT}, {LIGHT_A1} fading to {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'track_lateral', 'setup', 'transition', 'conductor', FALSE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH18', jsonb_build_object('positivePrompt', $pp$extreme close-up vintage gauge dial in dim cabin light, needle trembling alive from rest at zero, brass casing, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'setup', 'atmosphere', NULL, TRUE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH19', jsonb_build_object('positivePrompt', $pp$low wide, train wheels starting to turn slowly, steam venting from beneath, empty platform receding, sodium lamps blurring, no city in view, {LIGHT_A1}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'EWS', 'low', 'static', 'catalyst', 'atmosphere', NULL, TRUE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH20', jsonb_build_object('positivePrompt', $pp${CONDUCTOR} MCU sitting in narrow conductor crew compartment, pulling folded resignation envelope from breast pocket, holding it in lap, twilight outside window, {LIGHT_A1} {LIGHT_A2} mix, {STYLE}$pp$, 'negativeRef', '{NEG}', 'narrationRu', $pp$Двенадцать лет я считаю чужие билеты. Сегодня — последний рейс.$pp$), 'MCU', 'eye', 'static', 'catalyst', 'character', 'conductor', FALSE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH21', jsonb_build_object('positivePrompt', $pp$extreme close-up her gloved hand smoothing unopened envelope on thigh fabric before tucking it back into breast pocket, hesitation visible, {LIGHT_A2}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'catalyst', 'plot', 'conductor', FALSE, FALSE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a1, 'A1_SH22', jsonb_build_object('positivePrompt', $pp$slow aerial drone wide, train snaking through wide autumn field at final sunset light, no city anywhere, golden grass cold sky, melancholy widescreen, {TRAIN_EXT}, {LIGHT_A1}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'EWS', 'high', 'static', 'setup', 'iconic', NULL, TRUE, TRUE, 'sunset_day1', 'A1_sodium', NOW(), NOW()),

-- ========== A2 — SETTLING (22) ==========
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH01', jsonb_build_object('positivePrompt', $pp$wide lateral corridor of train at night, warm amber tungsten ceiling lamps in long perspective, deep indigo windows, no people, slow sway of train motion, {TRAIN_INT}, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'track_lateral', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH02', jsonb_build_object('positivePrompt', $pp$OTS through compartment doorway, {PAX_MIL} sitting alone in SV class compartment looking out indigo window, uniform jacket on hook beside him, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'OTS', 'eye', 'static', 'rising', 'character', 'military', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH03', jsonb_build_object('positivePrompt', $pp$medium close-up low angle, {PAX_MIL} face in amber interior light against dark window, thousand-yard stare, jaw set, no expression, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'low', 'static', 'rising', 'character', 'military', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH04', jsonb_build_object('positivePrompt', $pp$extreme close-up hands of {PAX_MIL} opening and refolding small worn photograph at tabletop, subject of photo not visible to camera, reading lamp warm pool, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'character', 'military', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH05', jsonb_build_object('positivePrompt', $pp$close-up eyes only of {PAX_MIL} slow push-in, not blinking, reflections of passing window lights crossing iris, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'push_in', 'rising', 'character', 'military', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH06', jsonb_build_object('positivePrompt', $pp$back shot, {CONDUCTOR} silhouette framed by compartment doorway, holding tea glass, not entering, watching, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH07', jsonb_build_object('positivePrompt', $pp$medium shot, {PAX_MIL} turning his head, micro-nod toward off-frame conductor, no smile, silence mutual, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'rising', 'character', 'military', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH08', jsonb_build_object('positivePrompt', $pp${CONDUCTOR} MCU returning nod with restraint, setting glass of tea on floor at compartment threshold, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH09', jsonb_build_object('positivePrompt', $pp$extreme close-up vintage metal tea-glass holder on compartment floor in amber corridor light, liquid swaying with train motion, no logo on glass, 100mm macro$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'iconic', NULL, TRUE, TRUE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH10', jsonb_build_object('positivePrompt', $pp$back lateral track, {CONDUCTOR} walking away from compartment door, hand brushing wall, lamps strobing past, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'track_lateral', 'rising', 'transition', 'conductor', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH11', jsonb_build_object('positivePrompt', $pp$wide high angle into compartment, {PAX_MIL} still in same posture, untouched tea glass on small folding table, indigo window, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'high', 'static', 'rising', 'character', 'military', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH12', jsonb_build_object('positivePrompt', $pp$extreme close-up clenched fist resting on thigh, knuckles white, faint old scar across back of hand, lit warm amber, {LIGHT_A2}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'character', 'military', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH13', jsonb_build_object('positivePrompt', $pp$POV through compartment window, dark rolling fields, single distant farm light flickering past, deep indigo sky, {TRAIN_EXT}, {LIGHT_A2}$pp$, 'negativeRef', '{NEG}'), 'POV', 'eye', 'window_pov', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH14', jsonb_build_object('positivePrompt', $pp$medium shot low angle, {PAX_MIL} finally reaching for tea glass, single slow sip, eyes still on window, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'low', 'static', 'rising', 'character', 'military', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH15', jsonb_build_object('positivePrompt', $pp$close-up profile, steam rising from tea glass past {PAX_MIL} cheek, single moisture catch on lower eyelash, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'static', 'rising', 'character', 'military', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH16', jsonb_build_object('positivePrompt', $pp$extreme close-up high angle of photograph face-up on tabletop, content abstracted (blurred faces, generic figures), only worn corner sharp, reading lamp pool, {LIGHT_A2}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'high', 'static', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH17', jsonb_build_object('positivePrompt', $pp$medium shot, {PAX_MIL} carefully sliding photograph back into shirt pocket, deliberate gentle motion, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'rising', 'character', 'military', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH18', jsonb_build_object('positivePrompt', $pp$OTS over {CONDUCTOR} shoulder briefly catching the military man in his compartment as she walks past corridor, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'OTS', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH19', jsonb_build_object('positivePrompt', $pp${CONDUCTOR} MCU walking corridor, slight pause in step, recognition of shared silence in her face, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH20', jsonb_build_object('positivePrompt', $pp$extreme close-up vintage analog watch on conductor wrist showing 23:12, warm wrist light, leather strap, {LIGHT_A2}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH21', jsonb_build_object('positivePrompt', $pp$wide aerial slow, train moving through vast nighttime field, moon partly veiled in cloud, no city anywhere, long stretch of empty land, {TRAIN_EXT}, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'EWS', 'high', 'static', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a2, 'A2_SH22', jsonb_build_object('positivePrompt', $pp$back lateral, {CONDUCTOR} from behind reaching her crew compartment door, opening it quietly, {LIGHT_A2}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'track_lateral', 'rising', 'transition', 'conductor', FALSE, FALSE, 'early_night_day1', 'A2_amber_indigo', NOW(), NOW()),

-- ========== A3 — DEEP NIGHT (25) ==========
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH01', jsonb_build_object('positivePrompt', $pp$wide aerial, train moving slowly through wide nighttime landscape, moon fully veiled now, no city, sense of deep silence, {TRAIN_EXT}, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'EWS', 'high', 'static', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH02', jsonb_build_object('positivePrompt', $pp$wide high angle plackart sleeping car at deep night, {PAX_MOM} sitting on lower berth trying to soothe restless infant, other passengers asleep around her, single reading lamp pool, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'high', 'static', 'rising', 'character', 'mother_baby', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH03', jsonb_build_object('positivePrompt', $pp$medium close-up high angle, {PAX_MOM} rocking infant against shoulder, exhausted soft smile, hair coming loose, warm reading lamp on her face, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'high', 'static', 'rising', 'character', 'mother_baby', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH04', jsonb_build_object('positivePrompt', $pp$extreme close-up tiny infant hand gripping mother index finger, both warm lit, indigo window blur behind, 100mm macro, {LIGHT_A3}$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'iconic', 'mother_baby', FALSE, TRUE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH05', jsonb_build_object('positivePrompt', $pp$wide, {PAX_MOM} stepping barefoot into amber corridor still rocking infant, careful not to wake sleepers behind her, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'static', 'rising', 'character', 'mother_baby', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH06', jsonb_build_object('positivePrompt', $pp$back lateral, {PAX_MOM} from behind walking corridor at half-pace, swaying infant, amber lamps glowing past her, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'track_lateral', 'rising', 'character', 'mother_baby', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH07', jsonb_build_object('positivePrompt', $pp$OTS over {CONDUCTOR} shoulder looking down long corridor at small distant figure of mother rocking infant, soft amber depth, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'OTS', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH08', jsonb_build_object('positivePrompt', $pp${CONDUCTOR} MCU, unreadable depth in eyes watching mother off-frame, hand resting on corridor wall, breath held, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH09', jsonb_build_object('positivePrompt', $pp$close-up high angle, sleeping infant face against {PAX_MOM} shoulder, peaceful, tiny breath visible, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'high', 'static', 'rising', 'character', 'mother_baby', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH10', jsonb_build_object('positivePrompt', $pp$medium shot, {PAX_MOM} leaning forehead against vestibule window, infant cradled, eyes closed for a beat of rest, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'rising', 'character', 'mother_baby', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH11', jsonb_build_object('positivePrompt', $pp$medium high, {CONDUCTOR} appearing beside mother, quietly placing folding stool, no words exchanged, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'high', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH12', jsonb_build_object('positivePrompt', $pp$MCU, {PAX_MOM} small grateful nod, slowly sitting still rocking, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'rising', 'character', 'mother_baby', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH13', jsonb_build_object('positivePrompt', $pp$back, {CONDUCTOR} retreating down corridor away from camera leaving mother behind, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'static', 'rising', 'transition', 'conductor', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH14', jsonb_build_object('positivePrompt', $pp$wide, SV class compartment at night, wedding dress in clear garment bag hanging on hook, {PAX_BRIDE} sitting beneath it on berth, hugging her knees, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'static', 'rising', 'character', 'bride', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH15', jsonb_build_object('positivePrompt', $pp$extreme close-up wedding dress lace and tulle pressed against translucent garment bag plastic, amber reading lamp lighting it from one side, 100mm macro, {LIGHT_A3}$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'iconic', 'bride', FALSE, TRUE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH16', jsonb_build_object('positivePrompt', $pp$MCU, {PAX_BRIDE} looking at phone screen which goes dark, no message visible on screen, red-rimmed eyes, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'rising', 'character', 'bride', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH17', jsonb_build_object('positivePrompt', $pp$extreme close-up her left hand resting on knee, conspicuously bare ring finger with faint indent where ring used to be, {LIGHT_A3}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'character', 'bride', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH18', jsonb_build_object('positivePrompt', $pp$close-up profile, {PAX_BRIDE} single tear sliding down cheek without her wiping it, looking at nothing, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'static', 'rising', 'character', 'bride', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH19', jsonb_build_object('positivePrompt', $pp$OTS over {CONDUCTOR} shoulder looking at slightly ajar SV door, glimpse of garment bag visible inside, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'OTS', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH20', jsonb_build_object('positivePrompt', $pp$medium shot slow push-in, {CONDUCTOR} knuckle softly tapping door once, hesitant, hand pulling back, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'push_in', 'rising', 'character', 'conductor', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH21', jsonb_build_object('positivePrompt', $pp$medium shot, {PAX_BRIDE} turning face away toward indigo window, not opening door, breath shaky, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'rising', 'character', 'bride', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH22', jsonb_build_object('positivePrompt', $pp$back, {CONDUCTOR} silhouette at compartment door, lowering raised hand, head bowed slightly, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH23', jsonb_build_object('positivePrompt', $pp$POV through SV window, near-total darkness outside except one impossibly distant single lamp blinking past, {TRAIN_EXT}, {LIGHT_A3}$pp$, 'negativeRef', '{NEG}'), 'POV', 'eye', 'window_pov', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH24', jsonb_build_object('positivePrompt', $pp$close-up, {PAX_BRIDE} eyes finally closing while still sitting upright under hanging dress, exhaustion winning, {LIGHT_A3}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'static', 'rising', 'character', 'bride', FALSE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a3, 'A3_SH25', jsonb_build_object('positivePrompt', $pp$extreme close-up shadow of wedding dress on compartment wall, gently swaying with train motion, amber light, soft poetic, {LIGHT_A3}, 50mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'peak_night_day1', 'A3_amber_indigo', NOW(), NOW()),

-- ========== A4 — PRE-DAWN (18) ==========
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH01', jsonb_build_object('positivePrompt', $pp$wide aerial, train moving across landscape at pre-dawn hour, sky beginning to lighten from black to deep blue, first hint of warmth on horizon, no city, {TRAIN_EXT}, {LIGHT_A4}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'EWS', 'high', 'static', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH02', jsonb_build_object('positivePrompt', $pp$medium shot, {PAX_BIZ} hunched over open laptop in compartment, glasses on nose, frowning at screen, untouched tea glass beside him, {LIGHT_A4}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'rising', 'character', 'businessman', FALSE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH03', jsonb_build_object('positivePrompt', $pp$extreme close-up laptop screen showing abstract no-connection icon (X over wifi bars, no readable text), faint reflection of his face, {LIGHT_A4}, 50mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'character', 'businessman', FALSE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH04', jsonb_build_object('positivePrompt', $pp$medium close-up low angle, {PAX_BIZ} leaning head back against compartment seat looking up at ceiling lamp, slow exhale of defeat, {LIGHT_A4}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'low', 'static', 'rising', 'character', 'businessman', FALSE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH05', jsonb_build_object('positivePrompt', $pp$medium shot, {PAX_BIZ} slowly closing laptop lid with palm, glasses now on table, looking at his own hand, {LIGHT_A4}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'rising', 'character', 'businessman', FALSE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH06', jsonb_build_object('positivePrompt', $pp$extreme close-up his hand on closed laptop, gold wedding ring slightly worn, no other jewelry, {LIGHT_A4}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'character', 'businessman', FALSE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH07', jsonb_build_object('positivePrompt', $pp$medium shot, {PAX_BIZ} carefully picking up paperback book left on seat across from him, the seat occupant sleeping turned to wall, {LIGHT_A4}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'rising', 'character', 'businessman', FALSE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH08', jsonb_build_object('positivePrompt', $pp$medium close-up, {PAX_BIZ} opening book to random page, glasses back on, expression softening into curiosity, {LIGHT_A4}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'rising', 'character', 'businessman', FALSE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH09', jsonb_build_object('positivePrompt', $pp$OTS over {CONDUCTOR} shoulder watching through doorway, businessman now visibly reading, faintest hint of smile on her face, {LIGHT_A4}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'OTS', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH10', jsonb_build_object('positivePrompt', $pp${CONDUCTOR} close-up, ghost of smile not quite reaching her eyes, warm corridor light on cheek, {LIGHT_A4}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH11', jsonb_build_object('positivePrompt', $pp$extreme close-up still life: tea glass in metal holder, open paperback book face-down beside it, dim reading lamp, indigo window beyond, {LIGHT_A4}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH12', jsonb_build_object('positivePrompt', $pp$back lateral track, {CONDUCTOR} walking down corridor on her round, ceiling lamps still warm, hint of dawn through windows ahead, {LIGHT_A4}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'track_lateral', 'rising', 'transition', 'conductor', FALSE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH13', jsonb_build_object('positivePrompt', $pp$POV through window, horizon edge beginning to lighten from indigo to pale blue, single farmhouse silhouette far in distance, {TRAIN_EXT}, {LIGHT_A4}$pp$, 'negativeRef', '{NEG}'), 'POV', 'eye', 'window_pov', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH14', jsonb_build_object('positivePrompt', $pp$wide, train vestibule with door slightly ajar, cold air visibly moving the curtain, pre-dawn blue light slicing in, {TRAIN_INT}, {LIGHT_A4}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'static', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH15', jsonb_build_object('positivePrompt', $pp$medium close-up, {CONDUCTOR} standing in vestibule, taking deep breath of cold pre-dawn air, eyes closed briefly, {LIGHT_A4}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH16', jsonb_build_object('positivePrompt', $pp$extreme close-up vintage watch on her wrist showing 04:38, pre-dawn blue light on her sleeve, {LIGHT_A4}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH17', jsonb_build_object('positivePrompt', $pp$slow aerial wide, train crossing simple steel bridge over river at first dawn light, sky pale gold-pink edge, no city anywhere, ethereal, {TRAIN_EXT}, {LIGHT_A4} transitioning to {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'EWS', 'high', 'static', 'rising', 'iconic', NULL, TRUE, TRUE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a4, 'A4_SH18', jsonb_build_object('positivePrompt', $pp$back, {CONDUCTOR} from behind in vestibule doorway facing the brightening landscape, silhouette against dawn, {LIGHT_A4} {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'predawn_day2', 'A4_cool_blue', NOW(), NOW()),

-- ========== A5 — DAYLIGHT (30) ==========
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH01', jsonb_build_object('positivePrompt', $pp$wide lateral corridor by day, windows strobing with passing birch trees, cold white light shafts crossing floor, no people, {TRAIN_INT}, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'track_lateral', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH02', jsonb_build_object('positivePrompt', $pp$OTS through {CONDUCTOR} shoulder into compartment, {PAX_VET} seated, newspaper folded on knees no readable text, cane against wall, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'OTS', 'eye', 'static', 'rising', 'character', 'veteran', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH03', jsonb_build_object('positivePrompt', $pp$medium shot low angle, {PAX_VET} profile against window, three rows of generic medal ribbons catching cold light, dignity in stillness, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'low', 'static', 'rising', 'character', 'veteran', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH04', jsonb_build_object('positivePrompt', $pp$extreme close-up medal ribbons on his blazer, generic three-row arrangement, no readable text or insignia, slight wear, cold daylight, {LIGHT_A5}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'character', 'veteran', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH05', jsonb_build_object('positivePrompt', $pp$medium close-up, {PAX_VET} gently unwrapping small homemade pie from cloth bundle on table, careful old fingers, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'rising', 'character', 'veteran', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH06', jsonb_build_object('positivePrompt', $pp$extreme close-up high angle, simple homemade pie cradled in old hand, no decoration just food, cold daylight, {LIGHT_A5}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'high', 'static', 'rising', 'character', 'veteran', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH07', jsonb_build_object('positivePrompt', $pp$OTS from behind {PAX_VET} looking up at {CONDUCTOR} placing tea glass on his table, gentle exchange, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'OTS', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH08', jsonb_build_object('positivePrompt', $pp$medium close-up low angle, {PAX_VET} nodding thanks, breaking small piece of pie, gesturing it toward off-frame conductor, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'low', 'static', 'rising', 'character', 'veteran', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH09', jsonb_build_object('positivePrompt', $pp${CONDUCTOR} MCU accepting offered piece between gloved fingertips, real soft smile breaking through tiredness, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH10', jsonb_build_object('positivePrompt', $pp${CONDUCTOR} close-up high angle taking small bite, eyes briefly closing — taste of something from another life, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'high', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH11', jsonb_build_object('positivePrompt', $pp$medium shot, {PAX_VET} watching her enjoy the pie, soft contentment in his face, no words needed, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'rising', 'character', 'veteran', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH12', jsonb_build_object('positivePrompt', $pp$POV through compartment window, birch trees flickering past in rhythm, open field beyond, single abandoned wooden shed sliding by, {TRAIN_EXT}, {LIGHT_A5}$pp$, 'negativeRef', '{NEG}'), 'POV', 'eye', 'window_pov', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH13', jsonb_build_object('positivePrompt', $pp$extreme close-up tea glass in vintage metal holder, lemon slice floating inside, entire blurred background strobing with passing birch trees, 100mm shallow DOF, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'iconic', NULL, TRUE, TRUE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH14', jsonb_build_object('positivePrompt', $pp$medium shot, {PAX_VET} carefully placing small black-and-white photograph on compartment table, content not yet visible, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'rising', 'character', 'veteran', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH15', jsonb_build_object('positivePrompt', $pp$extreme close-up high angle photograph from above, content deliberately abstracted (blurred figures), only worn yellowed edges sharp, {LIGHT_A5}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'high', 'static', 'rising', 'character', 'veteran', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH16', jsonb_build_object('positivePrompt', $pp$back, {CONDUCTOR} stepping out of compartment, softly sliding door closed behind her, head bowed slightly, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'static', 'rising', 'transition', 'conductor', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH17', jsonb_build_object('positivePrompt', $pp$wide symmetrical compartment shot, {PAX_HE} by window, {PAX_SHE} by door, both facing forward, large gap between them, cold daylight, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'static', 'rising', 'character', 'couple_fight', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH18', jsonb_build_object('positivePrompt', $pp$medium close-up, {PAX_HE} profile, jaw set, looking out window, not blinking, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'rising', 'character', 'couple_fight', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH19', jsonb_build_object('positivePrompt', $pp$medium close-up, {PAX_SHE} profile, eyes downcast, hands in oversized sweater sleeves, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'rising', 'character', 'couple_fight', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH20', jsonb_build_object('positivePrompt', $pp$extreme close-up split: his hand with gold wedding band visible, her hand bare on knee, {LIGHT_A5}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'character', 'couple_fight', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH21', jsonb_build_object('positivePrompt', $pp$extreme close-up vintage analog wall clock inside compartment, 10:12 reading, second hand sweeping, {LIGHT_A5}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH22', jsonb_build_object('positivePrompt', $pp$medium shot, {PAX_HE} holding open book on lap, eyes not moving, pages still, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'rising', 'character', 'couple_fight', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH23', jsonb_build_object('positivePrompt', $pp$medium close-up, {PAX_SHE} pouring tea from thermos with slight tremble in hand, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'rising', 'character', 'couple_fight', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH24', jsonb_build_object('positivePrompt', $pp$extreme close-up tea slightly overflowing glass rim from trembling hand, beading on metal holder, {LIGHT_A5}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH25', jsonb_build_object('positivePrompt', $pp$close-up, {PAX_SHE} eyes slow long blink, lashes wet, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'static', 'rising', 'character', 'couple_fight', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH26', jsonb_build_object('positivePrompt', $pp$medium shot, {PAX_HE} slowly closing book and placing it on seat between them deliberately like a gesture, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'rising', 'character', 'couple_fight', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH27', jsonb_build_object('positivePrompt', $pp$medium close-up, {PAX_SHE} reaching out fingertips resting on book between them, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'rising', 'character', 'couple_fight', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH28', jsonb_build_object('positivePrompt', $pp$extreme close-up his hand slowly covering hers on book cover, gold ring against bare finger, gentle, {LIGHT_A5}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'iconic', 'couple_fight', FALSE, TRUE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH29', jsonb_build_object('positivePrompt', $pp$close-up, {PAX_SHE} first exhale releasing, eyes still down but face softening, not yet looking at him, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'static', 'rising', 'character', 'couple_fight', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a5, 'A5_SH30', jsonb_build_object('positivePrompt', $pp$wide same symmetrical compartment frame as SH17, but now joined hands on book between them, daylight softening, {LIGHT_A5}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'static', 'rising', 'character', 'couple_fight', FALSE, FALSE, 'day_day2', 'A5_cold_birch', NOW(), NOW()),

-- ========== A6 — MIDPOINT (18) ==========
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH01', jsonb_build_object('positivePrompt', $pp$wide, {PAX_MUS} sitting on floor of vestibule with acoustic guitar across knees, late afternoon golden light from open vestibule window, {LIGHT_A6}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'static', 'rising', 'character', 'musician', FALSE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH02', jsonb_build_object('positivePrompt', $pp$medium close-up low angle, {PAX_MUS} fingerpicking guitar string slowly, eyes half-closed in playing trance, {LIGHT_A6}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'low', 'static', 'rising', 'character', 'musician', FALSE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH03', jsonb_build_object('positivePrompt', $pp$extreme close-up guitar strings under fingertips, golden warm light catching steel, pluck visible, {LIGHT_A6}, 100mm macro$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'character', 'musician', FALSE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH04', jsonb_build_object('positivePrompt', $pp$medium shot, {PAX_MUS} in vestibule, doorway open behind him with golden field rushing past, hair lifted by warm wind, {LIGHT_A6}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'rising', 'character', 'musician', FALSE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH05', jsonb_build_object('positivePrompt', $pp$OTS over {CONDUCTOR} shoulder standing in vestibule doorway watching musician, not interrupting, {LIGHT_A6}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'OTS', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH06', jsonb_build_object('positivePrompt', $pp${CONDUCTOR} medium close-up leaning against vestibule frame, eyes closed for a beat listening, first real pause of her shift, {LIGHT_A6}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH07', jsonb_build_object('positivePrompt', $pp$medium shot low angle, {PAX_MUS} silhouette against bright open vestibule door with golden field behind, cold backlight transitioning to warm, guitar in lap, painterly composition, {LIGHT_A6}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'low', 'static', 'rising', 'iconic', 'musician', FALSE, TRUE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH08', jsonb_build_object('positivePrompt', $pp$close-up, {PAX_MUS} face, gentle absent smile while playing, looking out at landscape, {LIGHT_A6}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'static', 'rising', 'character', 'musician', FALSE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH09', jsonb_build_object('positivePrompt', $pp$POV from open vestibule door, golden field rushing past, power line poles flicking by, no houses in view, {TRAIN_EXT}, {LIGHT_A6}$pp$, 'negativeRef', '{NEG}'), 'POV', 'eye', 'window_pov', 'rising', 'atmosphere', NULL, TRUE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH10', jsonb_build_object('positivePrompt', $pp$extreme close-up final note ringing on held string, vibration dying out, finger lifting, {LIGHT_A6}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'rising', 'character', 'musician', FALSE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH11', jsonb_build_object('positivePrompt', $pp$medium shot, {CONDUCTOR} silently clapping just once toward musician, slight nod, then turning away to continue her round, {LIGHT_A6}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'rising', 'character', 'conductor', FALSE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH12', jsonb_build_object('positivePrompt', $pp$back lateral track, {CONDUCTOR} walking down corridor away from vestibule, faint smile visible in slight cheek tilt, {LIGHT_A6}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'track_lateral', 'rising', 'transition', 'conductor', FALSE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH13', jsonb_build_object('positivePrompt', $pp$OTS over {CONDUCTOR} shoulder pausing at child compartment doorway, {PAX_GIRL} visible inside on berth playing quietly with plush owl, {LIGHT_A6}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'OTS', 'eye', 'static', 'midpoint_twist', 'character', 'child_girl', FALSE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH14', jsonb_build_object('positivePrompt', $pp$medium shot, {PAX_GIRL} sitting on berth holding plush owl up at eye level, whispering to it, late warm light through compartment window, {LIGHT_A6}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'midpoint_twist', 'character', 'child_girl', FALSE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH15', jsonb_build_object('positivePrompt', $pp$extreme close-up slow push-in on worn plush owl in child hands, one button eye missing showing thread, fabric faded, late golden light, photorealistic textile detail, {LIGHT_A6}, 100mm macro$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'push_in', 'midpoint_twist', 'iconic', 'child_girl', FALSE, TRUE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH16', jsonb_build_object('positivePrompt', $pp$close-up slow push-in, {CONDUCTOR} face going still as she sees the owl off-frame, all professional composure drops for one second, hand involuntarily rising to chest where chain hangs, {LIGHT_A6}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'push_in', 'midpoint_twist', 'plot', 'conductor', FALSE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH17', jsonb_build_object('positivePrompt', $pp$extreme close-up {CONDUCTOR} hand pulling thin chain out from under shirt collar, simple gold wedding band threaded on it, fingers touching, {LIGHT_A6}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'midpoint_twist', 'plot', 'conductor', FALSE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a6, 'A6_SH18', jsonb_build_object('positivePrompt', $pp$back, {CONDUCTOR} stepping back from child doorway, shoulders dropping slightly, hand still at chest, {LIGHT_A6} transitioning to {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'static', 'midpoint_twist', 'character', 'conductor', FALSE, FALSE, 'late_day_day2', 'A6_golden_warm', NOW(), NOW()),

-- ========== A7 — CRISIS (35) ==========
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH01', jsonb_build_object('positivePrompt', $pp$wide aerial, train moving into thick snow squall at night, swirling white, dark forest below, no town lights anywhere, {TRAIN_EXT}, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'EWS', 'high', 'static', 'bad_guys_close_in', 'atmosphere', NULL, TRUE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH02', jsonb_build_object('positivePrompt', $pp$POV interior to exterior, sideways snow plastering against window glass, near-zero visibility beyond, {LIGHT_A7}$pp$, 'negativeRef', '{NEG}'), 'POV', 'eye', 'window_pov', 'bad_guys_close_in', 'atmosphere', NULL, TRUE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH03', jsonb_build_object('positivePrompt', $pp$wide lateral track corridor, ceiling lamps flickering once, dark emerald compartment curtain shadows stretching, {TRAIN_INT}, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'track_lateral', 'bad_guys_close_in', 'atmosphere', NULL, TRUE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH04', jsonb_build_object('positivePrompt', $pp$OTS over {CONDUCTOR} shoulder peering through child compartment door, {PAX_GIRL} curled on berth, owl beside her, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'OTS', 'eye', 'static', 'bad_guys_close_in', 'plot', 'child_girl', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH05', jsonb_build_object('positivePrompt', $pp$medium close-up high angle, {PAX_GIRL} sleeping on berth, cheeks flushed red, hair damp on forehead, blanket half off, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'high', 'static', 'bad_guys_close_in', 'plot', 'child_girl', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH06', jsonb_build_object('positivePrompt', $pp$extreme close-up back of {CONDUCTOR} gloved hand resting against {PAX_GIRL} forehead, slight heat shimmer suggestion, dark emerald shadow, {LIGHT_A7}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'bad_guys_close_in', 'plot', 'conductor', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH07', jsonb_build_object('positivePrompt', $pp${CONDUCTOR} close-up, expression sharpening from tiredness to full alertness, recognizing fever, looking down off-frame, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'static', 'bad_guys_close_in', 'plot', 'conductor', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH08', jsonb_build_object('positivePrompt', $pp$medium shot, {CONDUCTOR} pulling old glass-style thermometer from medical drawer in crew compartment, no readable text on it, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'bad_guys_close_in', 'plot', 'conductor', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH09', jsonb_build_object('positivePrompt', $pp$extreme close-up classic mercury-style thermometer, visually generic with no readable numbers, red liquid clearly past safe threshold, dim emerald light, {LIGHT_A7}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'bad_guys_close_in', 'plot', NULL, TRUE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH10', jsonb_build_object('positivePrompt', $pp${CONDUCTOR} close-up, jaw tight, breathing controlled, calculation in eyes, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'static', 'bad_guys_close_in', 'plot', 'conductor', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH11', jsonb_build_object('positivePrompt', $pp$medium shot, {CONDUCTOR} reaching driver cabin door at front of train, finding it locked, knocking sharply, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'bad_guys_close_in', 'plot', 'conductor', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH12', jsonb_build_object('positivePrompt', $pp$extreme close-up her fist striking metal cabin door, faint reverberation visible in light dust around impact, {LIGHT_A7}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'bad_guys_close_in', 'plot', NULL, TRUE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH13', jsonb_build_object('positivePrompt', $pp$wide, {CONDUCTOR} walking back into empty dimly lit corridor, dark emerald curtains, dead night, no one awake, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'static', 'all_is_lost', 'plot', 'conductor', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH14', jsonb_build_object('positivePrompt', $pp$medium close-up slight dutch tilt, {CONDUCTOR} face under flickering lamp, decision pressing in, breath visible despite interior, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'dutch', 'static', 'all_is_lost', 'plot', 'conductor', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH15', jsonb_build_object('positivePrompt', $pp$OTS over {CONDUCTOR} shoulder, {PAX_GIRL} in feverish restless sleep, weak whimper, owl fallen to floor, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'OTS', 'eye', 'static', 'all_is_lost', 'plot', 'child_girl', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH16', jsonb_build_object('positivePrompt', $pp$extreme close-up high angle worn plush owl lying on compartment floor, fabric fold sad, dark emerald shadow, {LIGHT_A7}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'high', 'static', 'all_is_lost', 'iconic', 'child_girl', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH17', jsonb_build_object('positivePrompt', $pp${CONDUCTOR} close-up low angle, looking up and ahead, no longer in subordinate posture, decision crystallizing, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'low', 'static', 'dark_night_of_the_soul', 'character', 'conductor', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH18', jsonb_build_object('positivePrompt', $pp$back lateral fast track, {CONDUCTOR} walking purposefully toward vestibule, lamps flickering, snow visible through doors ahead, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'track_lateral', 'dark_night_of_the_soul', 'plot', 'conductor', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH19', jsonb_build_object('positivePrompt', $pp$wide low angle, {CONDUCTOR} standing facing emergency brake handle mounted on vestibule wall, single sickly yellow emergency light overhead, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'low', 'static', 'dark_night_of_the_soul', 'plot', 'conductor', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH20', jsonb_build_object('positivePrompt', $pp$extreme close-up red emergency brake handle with intact wire seal, peeling paint, dim emergency light, generic no text on plate, {LIGHT_A7}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'dark_night_of_the_soul', 'iconic', NULL, TRUE, TRUE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH21', jsonb_build_object('positivePrompt', $pp${CONDUCTOR} close-up facing brake handle directly, deep slow breath in, eyes closing for one beat, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'static', 'break_into_three', 'plot', 'conductor', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH22', jsonb_build_object('positivePrompt', $pp$extreme close-up slow push-in, {CONDUCTOR} grey wool fingerless glove tightening around red brake handle, knuckles whitening, seal wire trembling, {LIGHT_A7}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'push_in', 'break_into_three', 'iconic', 'conductor', FALSE, TRUE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH23', jsonb_build_object('positivePrompt', $pp${CONDUCTOR} close-up eyes opening sharp and resolved, no doubt left, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'static', 'break_into_three', 'plot', 'conductor', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH24', jsonb_build_object('positivePrompt', $pp$extreme close-up brake handle pulled down decisively, wire seal snapping with small visible spark of metal, {LIGHT_A7}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'break_into_three', 'plot', NULL, FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH25', jsonb_build_object('positivePrompt', $pp$wide aerial slow motion, train brakes locking up in snowy field at night, sparks visible from wheels on rails, snowstorm easing, {TRAIN_EXT}, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'EWS', 'high', 'static', 'break_into_three', 'iconic', NULL, TRUE, TRUE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH26', jsonb_build_object('positivePrompt', $pp$close-up handheld, {PAX_MIL} jolting awake fully alert, soldier reflex, eyes immediately scanning, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'handheld', 'all_is_lost', 'character', 'military', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH27', jsonb_build_object('positivePrompt', $pp$close-up handheld, {PAX_MOM} instinctively scooping infant closer, half-asleep already protective, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'handheld', 'all_is_lost', 'character', 'mother_baby', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH28', jsonb_build_object('positivePrompt', $pp$close-up handheld, {PAX_BRIDE} sitting up under hanging dress which sways from deceleration, eyes wide but calm, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'handheld', 'all_is_lost', 'character', 'bride', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH29', jsonb_build_object('positivePrompt', $pp$close-up handheld, {PAX_BIZ} scrambling awake, glasses askew, book sliding off lap, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'handheld', 'all_is_lost', 'character', 'businessman', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH30', jsonb_build_object('positivePrompt', $pp$close-up handheld, {PAX_VET} already sitting up calmly, hand on cane, having seen worse, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'handheld', 'all_is_lost', 'character', 'veteran', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH31', jsonb_build_object('positivePrompt', $pp$close-up handheld, {PAX_HE} and {PAX_SHE} both upright, hands gripped together immediately, fear shared, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'handheld', 'all_is_lost', 'character', 'couple_fight', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH32', jsonb_build_object('positivePrompt', $pp$close-up handheld, {PAX_MUS} curling around guitar protectively, calm, looking around, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'CU', 'eye', 'handheld', 'all_is_lost', 'character', 'musician', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH33', jsonb_build_object('positivePrompt', $pp$wide handheld, {CONDUCTOR} striding back through corridor of half-awake passengers, no one blocking her, only one who knows why, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'handheld', 'all_is_lost', 'plot', 'conductor', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH34', jsonb_build_object('positivePrompt', $pp$OTS, {CONDUCTOR} lifting feverish {PAX_GIRL} into her arms, wrapping in compartment blanket, owl tucked under girl arm, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'OTS', 'eye', 'static', 'all_is_lost', 'plot', 'child_girl', FALSE, FALSE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a7, 'A7_SH35', jsonb_build_object('positivePrompt', $pp$medium shot low angle, {CONDUCTOR} carrying child through dim corridor toward vestibule, passengers faces watching from compartment doors silently, {LIGHT_A7}, {STYLE}$pp$, 'negativeRef', '{NEG}', 'narrationRu', $pp$За двенадцать лет я ни разу не нарушила правил. Один раз — стоит того.$pp$), 'MS', 'low', 'static', 'all_is_lost', 'iconic', 'conductor', FALSE, TRUE, 'night_day2', 'A7_dark_emerald', NOW(), NOW()),

-- ========== A8 — RESOLUTION (30) ==========
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH01', jsonb_build_object('positivePrompt', $pp$wide slow aerial drone, passenger train stopped on tracks crossing snow-covered field, dawn pink sky pale, no city visible, ethereal silence, {TRAIN_EXT}, dawn pink and snow blue palette, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'EWS', 'high', 'static', 'break_into_three', 'iconic', NULL, TRUE, TRUE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH02', jsonb_build_object('positivePrompt', $pp$wide low angle, snow-covered field stretching to horizon either side of rails, perfect stillness, faint pink dawn glow, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'low', 'static', 'break_into_three', 'atmosphere', NULL, TRUE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH03', jsonb_build_object('positivePrompt', $pp$wide aerial track shot, single ambulance with quiet blue lights moving along narrow rural road toward stopped train, no other traffic anywhere, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'EWS', 'high', 'track_lateral', 'break_into_three', 'plot', NULL, TRUE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH04', jsonb_build_object('positivePrompt', $pp$wide, {CONDUCTOR} standing on lowered train step holding wrapped {PAX_GIRL}, watching dawn road, blanket fluttering in cold air, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'static', 'break_into_three', 'plot', 'conductor', FALSE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH05', jsonb_build_object('positivePrompt', $pp$medium shot low angle, ambulance stopping, two medics in generic jackets stepping out into snow, no readable text on vehicle, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'low', 'static', 'break_into_three', 'plot', NULL, FALSE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH06', jsonb_build_object('positivePrompt', $pp$medium close-up, {PAX_GIRL} carefully transferred from conductor arms to medic, still wrapped in blanket and clutching owl, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MCU', 'eye', 'static', 'break_into_three', 'plot', 'child_girl', FALSE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH07', jsonb_build_object('positivePrompt', $pp$extreme close-up plush owl bouncing gently in {PAX_GIRL} hand as she is carried, dawn pink soft on worn fabric, hopeful and sad, {LIGHT_A8}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'break_into_three', 'iconic', 'child_girl', FALSE, TRUE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH08', jsonb_build_object('positivePrompt', $pp$medium shot, {CONDUCTOR} standing in snow beside train, watching medics carry child to ambulance, hand at chest near hidden chain, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'break_into_three', 'character', 'conductor', FALSE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH09', jsonb_build_object('positivePrompt', $pp$wide aerial, ambulance pulling away from stopped train down narrow snowy road, train still motionless, dawn pink saturating, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'EWS', 'high', 'static', 'break_into_three', 'atmosphere', NULL, TRUE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH10', jsonb_build_object('positivePrompt', $pp$back, {CONDUCTOR} silhouette from behind standing in light snow watching disappearing ambulance, breath fogging into pink dawn air, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'static', 'break_into_three', 'character', 'conductor', FALSE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH11', jsonb_build_object('positivePrompt', $pp$wide slow aerial, train moving again, emerging from low morning fog toward tiny rural platform, milky pink light, no city beyond, {TRAIN_EXT}, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'EWS', 'high', 'static', 'final_image', 'atmosphere', NULL, TRUE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH12', jsonb_build_object('positivePrompt', $pp$wide, deserted small platform with single number sign no city name, morning fog rolling over rails, no other buildings, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'static', 'final_image', 'atmosphere', NULL, TRUE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH13', jsonb_build_object('positivePrompt', $pp$medium shot, {CONDUCTOR} alone in crew compartment, slowly unbuttoning navy uniform jacket, removing it carefully, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'final_image', 'plot', 'conductor', FALSE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH14', jsonb_build_object('positivePrompt', $pp$extreme close-up high angle, conductor navy uniform jacket neatly folded on compartment seat, peaked cap placed on top, morning pink light through window, {LIGHT_A8}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'high', 'static', 'final_image', 'iconic', NULL, FALSE, TRUE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH15', jsonb_build_object('positivePrompt', $pp$extreme close-up high angle, white folded resignation envelope placed on top of folded uniform, still unopened but visibly being left behind, {LIGHT_A8}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'high', 'static', 'final_image', 'iconic', NULL, FALSE, TRUE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH16', jsonb_build_object('positivePrompt', $pp$extreme close-up, {CONDUCTOR} hand pulling thin gold chain over head, ring sliding off, both placed on envelope, deliberate, {LIGHT_A8}, 100mm$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'final_image', 'plot', 'conductor', FALSE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH17', jsonb_build_object('positivePrompt', $pp${CONDUCTOR} close-up, face calm without weight of uniform, no makeup, soft morning fog light, first peace, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}', 'narrationRu', $pp$Двенадцать лет — это очень долго. И очень коротко.$pp$), 'CU', 'eye', 'static', 'final_image', 'character', 'conductor', FALSE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH18', jsonb_build_object('positivePrompt', $pp$wide, woman late 30s in only plain white shirt and trousers, dark blonde hair now down loose, no cap no jacket, stepping out of crew compartment, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'static', 'final_image', 'character', 'conductor', FALSE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH19', jsonb_build_object('positivePrompt', $pp$back lateral track, same woman from behind walking corridor toward exit door, lighter without uniform, lamps fading in morning light, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'track_lateral', 'final_image', 'character', 'conductor', FALSE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH20', jsonb_build_object('positivePrompt', $pp$OTS over shoulder, looking out open train doorway into milky morning fog of small platform, no people anywhere, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'OTS', 'eye', 'static', 'final_image', 'atmosphere', NULL, TRUE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH21', jsonb_build_object('positivePrompt', $pp$medium shot low angle, woman stepping down train steps into fog, white shirt glowing softly in pink dawn, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'low', 'static', 'final_image', 'character', 'conductor', FALSE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH22', jsonb_build_object('positivePrompt', $pp$wide, woman on empty platform looking back once at train, no sentimentality just acknowledgment, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'static', 'final_image', 'character', 'conductor', FALSE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH23', jsonb_build_object('positivePrompt', $pp$back slow push-in, woman from behind walking away from camera into pink morning fog field, figure softening into haze, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'BACK', 'eye', 'push_in', 'final_image', 'iconic', 'conductor', FALSE, TRUE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH24', jsonb_build_object('positivePrompt', $pp$wide aerial, tiny figure walking away into vast pink fog field, no path no destination visible, ethereal, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'EWS', 'high', 'static', 'final_image', 'atmosphere', NULL, TRUE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH25', jsonb_build_object('positivePrompt', $pp$medium shot, a different male conductor in generic uniform — 40yo man in similar navy jacket — no LoRA no IP-Adapter, closing train door, mild confusion, going through motions, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'MS', 'eye', 'static', 'final_image', 'plot', NULL, FALSE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH26', jsonb_build_object('positivePrompt', $pp$wide low, train slowly starting again, leaving empty platform, fog drifting in its wake, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'EWS', 'low', 'static', 'final_image', 'atmosphere', NULL, TRUE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH27', jsonb_build_object('positivePrompt', $pp$wide lateral track inside train corridor, younger female conductor — different face no LoRA generic 25yo brunette in same navy uniform — walking with bright posture fresh, {TRAIN_INT}, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'WS', 'eye', 'track_lateral', 'final_image', 'character', NULL, FALSE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH28', jsonb_build_object('positivePrompt', $pp$OTS over young new conductor shoulder, looking into empty compartment, blanket folded on berth, no child no owl, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}'), 'OTS', 'eye', 'static', 'final_image', 'plot', 'child_girl', FALSE, FALSE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH29', jsonb_build_object('positivePrompt', $pp$extreme close-up single small button eye from plush owl lying on compartment seat, glinting faintly, all that remains of the vignette, {LIGHT_A8}, 100mm macro$pp$, 'negativeRef', '{NEG}'), 'ECU', 'eye', 'static', 'final_image', 'iconic', NULL, FALSE, TRUE, 'morning_day2', 'A8_pink_fog', NOW(), NOW()),
(gen_random_uuid()::text, v_proj, v_a8, 'A8_SH30', jsonb_build_object('positivePrompt', $pp$close-up, young new conductor walking corridor briefly absent-mindedly touching her own chest where a chain would be but is not yet, echo of former conductor gesture, slight smile, then frame cuts to black mid-step, {LIGHT_A8}, {STYLE}$pp$, 'negativeRef', '{NEG}', 'narrationRu', $pp$Поезд идёт. Всегда идёт. Просто на следующем рейсе — буду уже не я.$pp$), 'CU', 'eye', 'static', 'final_image', 'iconic', NULL, FALSE, TRUE, 'morning_day2', 'A8_pink_fog', NOW(), NOW());

END $$;

COMMIT;
