# -*- coding: utf-8 -*-
"""Seed CH26 — Первые морщины, желание иссякает (HEROINE_MID). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "desire drying up, the mirror grown cruel, cold flat western daylight, dawning panic"
SHOTS = [
 ("CH26_SH01", "HEROINE_MID", "her_room",
  "medium of the heroine facing a merciless morning mirror",
  "MS","eye","static","day",False,False,
  "сорок пять, и зеркало по утрам всё безжалостнее, морщины, тяжёлые веки, поплывший овал."),
 ("CH26_SH02", "HEROINE_MID", "her_room",
  "close-up of her covering the lines with makeup",
  "CU","eye","static","day",False,False,
  "ты замазываешь их кремами и тоном, но желание в чужих глазах уже не загорается, как прежде."),
 ("CH26_SH03", None, "cafe_west",
  "wide of a bar where she now waits long before anyone approaches",
  "WS","eye","static","night",True,False,
  "в баре ты теперь сидишь дольше, прежде чем кто-то подсядет, а иногда и вовсе никто."),
 ("CH26_SH04", "HEROINE_MID", "cafe_west",
  "medium close-up of her flirting more desperately",
  "MCU","eye","static","night",False,False,
  "ты ловишь себя на том, что заигрываешь отчаяннее и громче, и это заметно, и это жалко."),
 ("CH26_SH05", None, "street_west",
  "close-up of young couples in love passing by",
  "CU","eye","static","day",True,False,
  "вокруг молодые влюблённые пары, а у тебя нет даже этого, и не было никогда."),
 ("CH26_SH06", "HEROINE_MID", "her_room",
  "medium close-up of the warm wave coming ever rarer",
  "MCU","eye","static","day",False,False,
  "тёплая волна, твой наркотик всей жизни, приходит всё реже и тает всё быстрее."),
 ("CH26_SH07", "HEROINE_MID", "her_room",
  "close-up of her panic at not knowing who she is without desire",
  "CU","eye","static","day",False,True,
  "ты впадаешь в панику, ведь без чужого желания ты не знаешь, кто ты вообще такая."),
 ("CH26_SH08", None, "her_room",
  "extreme close-up of a mirror crowded with cosmetics",
  "ECU","top_down","static","day",True,False,
  "всё больше времени у зеркала, всё больше косметики, и всё меньше той, что под ней."),
 ("CH26_SH09", "HEROINE_MID", "cafe_west",
  "medium close-up of her settling for anyone who looks",
  "MCU","eye","static","night",False,False,
  "ты соглашаешься на любого, кто посмотрит, лишь бы ещё разок почувствовать ту искру."),
 ("CH26_SH10", "HEROINE_MID", "her_room",
  "close-up of the spark dying ever faster",
  "CU","eye","static","day",False,False,
  "но искра гаснет всё быстрее, и чёрная пустота после неё становится только глубже."),
 ("CH26_SH11", None, "street_west",
  "wide B-roll of a cold bright western street, silent",
  "WS","eye","static","day",True,False,""),
]
if __name__ == "__main__":
    seed_act(26, "cold_day", MOOD, "static", "CH26 First lines", SHOTS)
