# -*- coding: utf-8 -*-
"""Seed CH10 — Подруги стареют (2nd person). Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "muted greying everyday light, the quiet dread of aging, ordinary"
SHOTS = [
 ("CH10_SH01", None, "cafe",
  "wide establishing of an ordinary cafe, small tables, soft daylight from large windows",
  "WS","high","push_in","muted_day",True,False,
  "сорок уже на горизонте, и ты замечаешь, подруги сдались."),
 ("CH10_SH02", None, "cafe",
  "medium shot of a table of aging women friends with natural wrinkles and greying hair, content",
  "MS","eye","static","muted_day",True,False,
  "вон они, с морщинами, с сединой, спокойные, постаревшие."),
 ("CH10_SH03", "HEROINE_YOUNG", "cafe",
  "close-up of the heroine looking at her friends with quiet horror",
  "CU","eye","static","muted_day",False,False,
  "ты смотришь на них с ужасом, нет, я так не хочу."),
 ("CH10_SH04", None, "cafe",
  "close-up of a friend laughing freely, soft lines around her eyes",
  "CU","eye","static","muted_day",True,False,
  "у них внуки, мужья, спокойная старость, а тебя трясёт."),
 ("CH10_SH05", "HEROINE_YOUNG", "bathroom",
  "medium close-up of the heroine at home swearing an oath to her mirror",
  "MCU","eye","push_in","muted_day",False,False,
  "дома у зеркала ты клянёшься, я не буду как они."),
 ("CH10_SH06", "HEROINE_YOUNG", "bathroom",
  "extreme close-up of her own faint early wrinkles examined up close",
  "ECU","eye","static","muted_day",False,True,
  "ты будешь биться за каждый год, за каждую морщину."),
 ("CH10_SH07", None, "park",
  "wide B-roll of a grey spring park, bare branches just budding, time passing",
  "WS","high","static","muted_day",True,False,""),
 ("CH10_SH08", "HEROINE_YOUNG", "shop",
  "medium shot of the heroine stopping before a beauty-clinic sign promising eternal youth",
  "MS","eye","static","muted_day",False,False,
  "и однажды на глаза попадается вывеска, вечная молодость, инъекции красоты."),
 ("CH10_SH09", None, "shop",
  "close-up of a clinic poster of a flawless young face without a single wrinkle",
  "CU","eye","push_in","muted_day",True,False,
  "с плаката улыбается идеальное лицо без единой морщинки."),
 ("CH10_SH10", "HEROINE_YOUNG", "stairwell",
  "medium close-up of the heroine hesitating at the clinic door, not yet daring",
  "MCU","eye","static","muted_day",False,False,
  "ты стоишь у двери и не решаешься, ещё нет, ещё рано."),
 ("CH10_SH11", "HEROINE_YOUNG", "stairwell",
  "close-up of the heroine's tempted face",
  "CU","eye","static","muted_day",False,True,
  "но семя уже посеяно, и ты записываешься на консультацию."),
 ("CH10_SH12", None, "shop",
  "wide B-roll of the bright clinic entrance from the street",
  "WS","eye","static","muted_day",True,False,""),
]
if __name__ == "__main__":
    seed_act(10, "muted_grey", MOOD, "static", "CH10 Friends age", SHOTS)
