# -*- coding: utf-8 -*-
"""Seed CH30 — Встреча с прошлым, Андреас с семьёй (HEROINE_MID + ANDREAS). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "she runs into Andreas with a happy family, the life she refused made flesh, bittersweet daylight"
SHOTS = [
 ("CH30_SH01", "HEROINE_MID", "park",
  "medium of the heroine freezing as a grey-haired man approaches in the park",
  "MS","eye","static","day",False,False,
  "однажды в парке ты застываешь, навстречу идёт он, постаревший, седой, но это точно Андреас."),
 ("CH30_SH02", ("HEROINE_MID","ANDREAS"), "park",
  "wide of older Andreas in round glasses with a kind-faced wife and two grown children",
  "WS","eye","static","day",False,False,
  "рядом с ним женщина с добрым лицом и двое уже взрослых детей, у него получилась семья."),
 ("CH30_SH03", "ANDREAS", "park",
  "medium close-up of older grey-haired Andreas, same round glasses, greeting her warmly",
  "MCU","eye","static","day",False,False,
  "он узнаёт тебя, кивает спокойно, без злости, без боли, просто тепло, как старой знакомой."),
 ("CH30_SH04", "HEROINE_MID", "park",
  "close-up of everything dropping inside her",
  "CU","eye","static","day",False,True,
  "а у тебя внутри всё обрывается, ведь это могла быть твоя жизнь, твоя семья, твой он."),
 ("CH30_SH05", ("HEROINE_MID","ANDREAS"), "park",
  "medium of them exchanging a few words, each kind word a cut",
  "MS","eye","static","day",False,False,
  "вы говорите пару минут ни о чём, и каждое его доброе слово режет тебя без всякого ножа."),
 ("CH30_SH06", "ANDREAS", "park",
  "close-up of older Andreas, content, grandchildren on the way",
  "CU","eye","static","day",False,False,
  "он счастлив, спокоен, у него скоро внуки, он выбрал любовь и, как видишь, не прогадал."),
 ("CH30_SH07", "HEROINE_MID", "park",
  "medium close-up of her forced smile over a howl",
  "MCU","eye","static","day",False,False,
  "ты улыбаешься через силу, рада за тебя, а внутри воешь, ведь ты сама всё это разрушила."),
 ("CH30_SH08", None, "park",
  "wide of Andreas walking off down the avenue with his family",
  "WS","eye","static","day",True,False,
  "он уходит со своей семьёй по аллее, и ты долго смотришь им вслед, одна на скамейке."),
 ("CH30_SH09", "HEROINE_MID", "park",
  "close-up of her by the door she slammed herself",
  "CU","eye","static","day",False,True,
  "вот она, та самая дверь, от которой у тебя был ключ, и ты захлопнула её своими руками."),
 ("CH30_SH10", "HEROINE_MID", "street_west",
  "medium close-up of her crying not from self-pity but late clarity",
  "MCU","eye","static","day",False,False,
  "ты идёшь домой и впервые плачешь не от жалости к себе, а от ясного, очень позднего понимания."),
 ("CH30_SH11", None, "park",
  "wide B-roll of the empty park avenue, silent",
  "WS","eye","static","day",True,False,""),
]
if __name__ == "__main__":
    seed_act(30, "west_day", MOOD, "static", "CH30 Meets past", SHOTS)
