# -*- coding: utf-8 -*-
"""Seed CH12 — Взгляды вернулись, крючок (2nd person). Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "warm intoxicating glow of attention returning, seductive"
SHOTS = [
 ("CH12_SH01", "HEROINE_YOUNG", "street",
  "medium shot of the heroine walking down the street, heads turning after her once again",
  "MS","eye","pan","neon_eve",False,False,
  "и снова на тебя оборачиваются, как когда-то в юности."),
 ("CH12_SH02", None, "street",
  "medium shot of men glancing admiringly, soft compliments in the air",
  "MS","eye","static","neon_eve",True,False,
  "комплименты, взгляды, ты будто и правда помолодела на десять лет."),
 ("CH12_SH03", "HEROINE_YOUNG", "street",
  "close-up of the heroine's glowing reawakened face",
  "CU","eye","static","neon_eve",False,True,
  "та тёплая волна, ты и забыла, как это сладко."),
 ("CH12_SH04", "HUSBAND", "family",
  "medium close-up of the husband noticing his wife with renewed interest",
  "MCU","eye","static","neon_eve",False,False,
  "даже муж снова смотрит на тебя с интересом."),
 ("CH12_SH05", ("HEROINE_YOUNG","HUSBAND"), "family",
  "the wife on the left and husband on the right, a warmer moment between them",
  "MS","eye","static","neon_eve",False,False,
  "вот он, решаешь ты, секрет, как удержать всё разом."),
 ("CH12_SH06", "HEROINE_YOUNG", "bathroom",
  "extreme close-up of the heroine admiring herself in the mirror, no longer afraid of it",
  "ECU","eye","push_in","neon_eve",False,False,
  "ты больше не боишься зеркала, оно снова твой друг."),
 ("CH12_SH07", None, "family",
  "close-up of a calendar with a clinic appointment circled",
  "CU","top_down","static","neon_eve",True,False,
  "ты считаешь дни до следующей процедуры."),
 ("CH12_SH08", "HEROINE_YOUNG", "clinic",
  "medium close-up of the heroine greeted by name in the clinic, a regular now",
  "MCU","eye","static","clinic_day",False,False,
  "алина теперь знает тебя по имени, ты постоянный клиент."),
 ("CH12_SH09", None, "clinic",
  "medium shot of a clinic waiting room full of other women chasing youth, faces turned",
  "MS","eye","static","clinic_day",True,False,
  "в очереди такие же, как ты, женщины, что гонятся за молодостью."),
 ("CH12_SH10", "HEROINE_YOUNG", "clinic",
  "extreme close-up of the heroine's face, the hook sinking deeper",
  "ECU","eye","static","clinic_day",False,True,
  "ещё чуть-чуть, думаешь ты, и стану совсем как раньше."),
 ("CH12_SH11", "HEROINE_YOUNG", "family",
  "close-up of the heroine's content unsuspecting face",
  "CU","eye","static","neon_eve",False,False,
  "ты счастлива и не видишь, как тебя затягивает."),
 ("CH12_SH12", None, "street",
  "wide B-roll of the evening city, warm lights, no clear faces",
  "WS","high","static","neon_eve",True,False,""),
]
if __name__ == "__main__":
    seed_act(12, "neon_glam", MOOD, "static", "CH12 Gaze returns", SHOTS)
