# -*- coding: utf-8 -*-
"""A6 (act_06_pawn_mfo) — MFO microloans (Solva/KMF/Tengo) + pawning the wedding ring."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from _seed_message_act_engine import seed_act

MOOD = ("dim amber pawnshop strip-light and cold microloan-office white, oppressive debt-grey palette, "
        "heavy high-contrast shadows, numb dread mood")

SHOTS = [
 ("A6_SH01","IRINA","kitchen","close-up of the worn woman reading yet another demand at the dark kitchen table","CU","eye","static","late_winter_night_2026",False,False,
  "март, виктор пишет что его расчётные заморозили, нужен залог чтобы их разморозить, ещё триста тысяч"),
 ("A6_SH02",None,"kitchen","extreme close-up of the phone with Viktor swearing it is the last time before they are together","ECU","eye","static","late_winter_night_2026",False,False,
  "он божится что это в последний раз, что после этого вы вместе поедете выбирать тебе новое кольцо"),
 ("A6_SH03","IRINA","kitchen","medium shot of the woman hitting a credit limit wall in the Kaspi app","MS","eye","static","late_winter_night_2026",False,False,
  "ты идёшь в каспи за новым кредитом, но лимит исчерпан, больше тебе не дают ни одного тенге"),
 ("A6_SH04","IRINA","kitchen","close-up of the woman typing a desperate search into her phone","CU","eye","static","late_winter_night_2026",False,False,
  "и ты впервые в жизни вбиваешь в поиске, где срочно взять денег без отказа и без справок"),
 ("A6_SH05",None,"kitchen","extreme close-up of the phone listing predatory microloan apps with fast-cash promises","ECU","eye","static","late_winter_night_2026",False,False,
  "вылезают десятки микрозаймов, солва, кмф, тенго, деньги за пять минут, ты и не знала что это так просто"),
 ("A6_SH06","IRINA","room","medium shot of the woman taking loan after loan on her phone in a daze","MS","eye","static","late_winter_night_2026",False,False,
  "ты берёшь первый микрозайм в солве, потом второй в кмф, гасишь один другим, как в тумане"),
 ("A6_SH07",None,"room","extreme close-up of a microloan screen with a frightening interest rate in fine print","ECU","eye","static","late_winter_night_2026",False,False,
  "проценты пугают, но ты не вчитываешься, главное чтобы виктор успел оплатить этот залог в срок"),
 ("A6_SH08","IRINA","kitchen","close-up of the woman sending the money again, his thanks lighting her screen","CU","eye","static","late_winter_night_2026",False,False,
  "ты снова отправляешь всё марату, и снова приходит спасибо родная, ты моё единственное спасение"),
 ("A6_SH09","IRINA","kitchen","medium shot of the woman lost among overlapping payment dates on the table","MS","high","static","late_winter_day_2026",False,False,
  "теперь у тебя три займа и кредит, платежи наслаиваются, ты путаешься в датах и суммах"),
 ("A6_SH10",None,"room","close-up of the phone with Viktor inventing yet another port fee","CU","eye","static","late_winter_evening_2026",False,False,
  "а виктор уже про новый сбор, портовый сбор, их как будто специально придумывают один за другим"),
 ("A6_SH11","IRINA","kitchen","medium shot of the woman with nowhere left to borrow, staring at her own hands","MS","eye","static","late_winter_evening_2026",False,False,
  "брать больше негде, лимиты везде закрыты, и ты сидишь над столом и смотришь на свои руки"),
 ("A6_SH12",None,"kitchen","extreme close-up of the woman's left hand with the thin plain gold wedding ring, the last gold she owns","ECU","eye","push_in","late_winter_evening_2026",False,True,
  "на левой руке твоё обручальное кольцо, единственное золото, что у тебя ещё осталось"),
 ("A6_SH13","IRINA","room","close-up of the woman fighting off a returning thought, jaw tense","CU","eye","static","late_winter_evening_2026",False,False,
  "ты гонишь мысль, но она возвращается, кольцо можно заложить, временно, ты ведь его выкупишь"),
 ("A6_SH14","IRINA","street","wide shot of the woman hurrying to a pawnshop on the edge of town, face hidden in her collar","WS","eye","static","late_winter_day_2026",False,False,
  "наутро ты идёшь в ломбард на окраине, прячешь лицо в воротник, вдруг увидит кто из школы"),
 ("A6_SH15","IRINA","pawn","medium shot of the woman at the pawnshop counter handing her ring to the clerk","MS","eye","static","late_winter_day_2026",False,False,
  "за прилавком мужчина под лампой берёт твоё кольцо, кладёт на весы, смотрит в лупу долго"),
 ("A6_SH16",None,"pawn","extreme close-up of the gold wedding ring on the pawnshop scale under hard light","ECU","high","static","late_winter_day_2026",False,True,
  "двадцать лет ты не снимала его, даже когда муж ушёл, а теперь оно лежит на чужих весах"),
 ("A6_SH17",None,"pawn","close-up of a handwritten pawn ticket and a redemption date with interest","CU","eye","static","late_winter_day_2026",False,False,
  "он называет цену вдвое ниже чем оно стоит, и пишет квитанцию, выкуп через месяц с процентом"),
 ("A6_SH18","IRINA","pawn","medium shot of the woman hesitating one second at the counter, then nodding","MS","eye","static","late_winter_day_2026",False,False,
  "ты медлишь секунду, кольцо ещё можно забрать, но виктор ждёт, и ты киваешь, оформляйте"),
 ("A6_SH19","IRINA","pawn","close-up of the woman's face and bare left hand as she leaves with the cash, a chill running through her","CU","eye","static","late_winter_day_2026",False,False,
  "ты выходишь с пачкой купюр и голой левой рукой, и по телу проходит холод, будто что-то предала"),
 ("A6_SH20","IRINA","kitchen","medium shot of the woman sending the ring money, staring at the white band on her finger","MS","eye","static","late_winter_evening_2026",False,False,
  "дома ты отправляешь деньги за кольцо марату, и смотришь на белую полоску, оставшуюся на пальце"),
 ("A6_SH21",None,"kitchen","close-up of the phone overflowing with Viktor's tearful gratitude and a final-payment promise","CU","eye","static","late_winter_evening_2026",False,False,
  "виктор пишет что плачет от благодарности, что не достоин тебя, что осталась всего одна оплата"),
 ("A6_SH22","IRINA","kitchen","close-up of the woman feeling nothing now, only fear of the next payment","MS","low","static","late_winter_evening_2026",False,False,
  "а ты уже не чувствуешь тёплого толчка под рёбрами, там только пустота и страх перед платежами"),
 ("A6_SH23",None,"kitchen","extreme close-up of the phone with an incoming call from a supposed port logistics man","ECU","eye","static","late_winter_evening_2026",False,False,
  "тебе звонит какой-то логист из порта, подтверждает что груз почти оформлен, и ты веришь ещё крепче"),
 ("A6_SH24","IRINA","kitchen","medium shot of the woman calmed by the stranger's voice, the lie now seeming real","MS","eye","static","late_winter_evening_2026",False,False,
  "этот чужой голос успокаивает тебя больше всего, теперь виктор не один, есть свидетель, значит правда"),
 ("A6_SH25","IRINA","class","wide shot of the exhausted woman teaching on autopilot before a noisy class","WS","eye","static","late_winter_day_2026",False,False,
  "в школе ты ведёшь урок на автомате, дети шумят, ты не спала и считаешь в уме проценты по займам"),
 ("A6_SH26","IRINA","staff","medium close-up of the woman quietly borrowing money from a colleague, lying about a burst pipe","MCU","eye","static","late_winter_day_2026",False,False,
  "ты занимаешь у коллеги до зарплаты, говоришь что прорвало трубу, врать стало привычкой"),
 ("A6_SH27",None,"room","close-up of the phone with overdue reminders stacking from Solva, KMF and Tengo","CU","eye","static","late_winter_evening_2026",False,False,
  "приходит первое смс о просрочке, солва напоминает о платеже, потом кмф, потом тенго, один за другим"),
 ("A6_SH28","IRINA","room","medium shot of the woman buried under a snowballing pile of debts at night","MS","high","static","late_winter_night_2026",False,False,
  "долги растут как снежный ком, ты гасишь один займ новым, и общая сумма становится всё больше"),
 ("A6_SH29","IRINA","kitchen","close-up of the woman avoiding even thinking of her daughter, phone silent","CU","eye","static","late_winter_night_2026",False,False,
  "даша больше не звонит после той ссоры, и ты не звонишь первой, тебе нечего сказать кроме лжи"),
 ("A6_SH30",None,"room","close-up of the phone with Viktor's last vow that he has bought a ticket and is coming","CU","eye","static","late_winter_night_2026",False,False,
  "виктор клянётся последним, ещё один платёж и я в аэропорту, я уже купил билет, ты только верь"),
 ("A6_SH31","IRINA","room","medium shot of the woman clinging to his promise because she has nothing else","MS","eye","static","late_winter_night_2026",False,False,
  "и ты веришь, потому что если это ложь, то ты осталась без кольца, без денег и без дочери зря"),
 ("A6_SH32","IRINA","kitchen","close-up of the woman alone in the dark kitchen, bare ring finger, the end of March","CU","low","static","late_winter_night_2026",False,True,
  "март кончается, на тебе четыре займа и кредит, палец без кольца, а виктора всё нет и нет"),
]

if __name__ == "__main__":
    seed_act("e6","A6_pawn_amber",MOOD,"0106000000","0156000000","static","act_06_pawn_mfo",SHOTS)
