# -*- coding: utf-8 -*-
"""Seed CH09 — 30, первая морщинка (2nd person). Idempotent."""
from _seed_beauty_act_engine import seed_act
MOOD = "cold harsh bathroom-mirror light, the first dread of aging, clinical"
SHOTS = [
 ("CH09_SH01", "HEROINE_YOUNG", "bathroom",
  "medium close-up of the woman at the mirror discovering her very first wrinkle",
  "MCU","eye","push_in","cold_day",False,False,
  "тридцать, и однажды у зеркала ты находишь её, первую морщинку."),
 ("CH09_SH02", "HEROINE_YOUNG", "bathroom",
  "extreme close-up of a fine line at the corner of her eye, magnified",
  "ECU","eye","static","cold_day",False,True,
  "тонкая линия у глаза, а тебе будто зачитали приговор."),
 ("CH09_SH03", "HEROINE_YOUNG", "bathroom",
  "close-up of the woman grabbing a magnifying mirror, hunting for more lines",
  "CU","eye","static","cold_day",False,False,
  "ты хватаешь лупу, и находишь ещё, и ещё."),
 ("CH09_SH04", None, "shop",
  "wide shot of cosmetics-store shelves crammed with anti-age creams and serums under bright retail light",
  "WS","eye","pan","cold_day",True,False,
  "ты сметаешь с полок все кремы, сыворотки, чудо-баночки."),
 ("CH09_SH05", None, "shop",
  "extreme close-up of an expensive jar of anti-age cream held up like a relic",
  "ECU","eye","static","cold_day",True,False,
  "самые дорогие, лишь бы остановить время."),
 ("CH09_SH06", "HEROINE_YOUNG", "bathroom",
  "medium close-up of the woman applying creams obsessively by the clock",
  "MCU","eye","static","cold_day",False,False,
  "ты мажешься строго по часам, утром, днём и ночью."),
 ("CH09_SH07", None, "family",
  "close-up of a stack of glossy beauty magazines screaming about looking ten years younger",
  "CU","top_down","static","cold_day",True,False,
  "журналы кричат, как выглядеть на десять лет моложе."),
 ("CH09_SH08", "HEROINE_YOUNG", "family",
  "medium shot of the woman comparing her face to a twenty-year-old model on a cover",
  "MS","eye","static","cold_day",False,False,
  "ты сравниваешь себя с двадцатилетними девочками с обложек."),
 ("CH09_SH09", None, "bathroom",
  "close-up of the mirror at night, the woman's anxious reflection checking for new lines",
  "CU","eye","static","cold_day",True,False,
  "и каждое утро первым делом к зеркалу, не постарела ли за ночь."),
 ("CH09_SH10", "HEROINE_YOUNG", "bathroom",
  "medium close-up of her anxious tightening face",
  "MCU","eye","static","cold_day",False,False,
  "страх стал твоим утренним будильником."),
 ("CH09_SH11", None, "park",
  "wide B-roll of an autumn park, yellowing trees and falling leaves, time marching on",
  "WS","high","static","cold_day",True,False,
  "а время идёт своим чередом, как ни мажься."),
 ("CH09_SH12", "HEROINE_YOUNG", "bathroom",
  "close-up of the woman's frightened face in the mirror",
  "CU","eye","static","cold_day",False,True,
  "ты ещё не знаешь, что уже есть та, кто продаст тебе вечную молодость в шприце."),
]
if __name__ == "__main__":
    seed_act(9, "bathroom_cold", MOOD, "static", "CH09 First wrinkle", SHOTS)
