# -*- coding: utf-8 -*-
"""Seed CH17 — Андреас уходит, оставляет ключ (HEROINE_YOUNG + ANDREAS). Idempotent."""
from _seed_wall_act_engine import seed_act
MOOD = "he leaves heartbroken, the key left behind, cold blue grief, the single real thing lost"
SHOTS = [
 ("CH17_SH01", ("HEROINE_YOUNG","ANDREAS"), "andreas_flat",
  "medium of Andreas quietly gathering her things, no shouting",
  "MS","eye","static","gdr_eve",False,False,
  "Андреас не кричит и не упрекает, он просто тихо начинает собирать в сумку твои вещи."),
 ("CH17_SH02", "ANDREAS", "andreas_flat",
  "medium close-up of Andreas saying the truth gently",
  "MCU","eye","static","gdr_eve",False,False,
  "я бы простил измену, говорит он, но ты не хочешь быть со мной, ты хочешь всё время бежать."),
 ("CH17_SH03", "HEROINE_YOUNG", "andreas_flat",
  "close-up of her silent because he is right",
  "CU","eye","static","gdr_eve",False,False,
  "ты молчишь, потому что он прав, и это молчание ранит вас обоих сильнее любых слов."),
 ("CH17_SH04", "ANDREAS", "andreas_flat",
  "medium close-up of him taking back the ring but not the key",
  "MCU","eye","static","gdr_eve",False,False,
  "он снимает с твоего пальца кольцо, но ключ, говорит он, ключ всё-таки оставь себе."),
 ("CH17_SH05", None, "andreas_flat",
  "extreme close-up of the key pressed back into her hand",
  "ECU","top_down","static","gdr_eve",True,True,
  "вдруг однажды ты захочешь вернуться по-настоящему, и тогда эта дверь всё ещё будет открыта."),
 ("CH17_SH06", "HEROINE_YOUNG", "street_east",
  "medium of her leaving his building, key in fist",
  "MS","eye","static","gdr_eve",False,False,
  "ты выходишь из подъезда с ключом в кулаке, и за спиной закрывается твоё единственное настоящее."),
 ("CH17_SH07", "ANDREAS", "andreas_flat",
  "close-up of Andreas watching from the window",
  "CU","eye","static","gdr_eve",False,False,
  "он смотрит тебе вслед из окна, и ты чувствуешь этот взгляд спиной весь свой путь."),
 ("CH17_SH08", "HEROINE_YOUNG", "the_wall",
  "medium close-up of her by the wall, realising she built her own",
  "MCU","eye","static","gdr_eve",False,True,
  "ты идёшь вдоль стены и понимаешь, что сама построила такую же, только внутри себя."),
 ("CH17_SH09", "HEROINE_YOUNG", "her_room",
  "close-up of her placing the key in a small box at home",
  "CU","eye","static","night",False,False,
  "дома ты кладёшь ключ в шкатулку и говоришь себе, так даже лучше, теперь я свободна."),
 ("CH17_SH10", None, "her_room",
  "extreme close-up of the key resting in the box",
  "ECU","top_down","static","night",True,False,
  "но впервые свобода на вкус, как тяжёлая потеря, и эту горечь не смыть ничем."),
 ("CH17_SH11", None, "the_wall",
  "wide B-roll of the wall at dusk, silent",
  "WS","eye","static","gdr_eve",True,False,""),
]
if __name__ == "__main__":
    seed_act(17, "cold_blue", MOOD, "static", "CH17 Andreas leaves", SHOTS)
